### ISSUE TITLE
cannot find the branch avp list!

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1001]
Hello

I am trying to upgrade a system I have to 2.2 but I have the following issue.

I am using uac_replace_from and uac_replace_to. When I call those functions I get

ERROR:tm:pv_set_tm_branch_avp: cannot find the branch avp list!

and auto restore_mode is not working.

I didn't had that issue before so probably something changed and need to be added before calling those functions.

Please advise.

**Comment by razvancrainea** [comment]
This error message was introduced in opensips in commit 343a532258, but it was downgraded to a debug yesterday (92fde1be1). The next release will suppress this ERROR.

**Comment by apsaras** [comment]
Hello 

Thank you for instant response. 

Is that a real error or a fault message? Because as I mentioned above the auto restore_mode is not working.

Thank you.

**Comment by razvancrainea** [comment]
No, that commit shouldn't change anything.
Is that the only error you are seeing in the code? It doesn't work in the sense that the URI is not changed for the replies? Can you provide some debugging logs?

**Comment by apsaras** [comment]
The problem appears on Bye. 

Please find attached a debug log.

[debug1.txt](https://github.com/OpenSIPS/opensips/files/636192/debug1.txt)

**Comment by razvancrainea** [comment]
There is indeed a bug introduced by 343a532: restoring TO/FROM for UPSTREAM messages does not work.
I will commit a fix and let you know so you can update your code.

Thanks for report and debug!

**Comment by razvancrainea** [comment]
I've just pushed a fix. Can you take the latest sources and test please? Thanks!

**Comment by apsaras** [comment]
Hello

Thank you for the patch.

It works but need a small fix. The display is not restored, only the URI is.

Initial Invite
To: 5537302123456789 <sip:5537302123456789@2.2.2.105>
From: <sip:6123456789@2.2.2.105>;tag=3690096609-229769

Bye
From: "302123456789" <sip:5537302123456789@2.2.2.105>;tag=as32991ced
To: "6123456789" <sip:6123456789@2.2.2.105>;tag=3690096609-229769

**Comment by razvancrainea** [comment]
Display name was never restored. If you do need this, please open a feature request.

Thanks for doing your tests too :)

**Comment by apsaras** [comment]
Not important
 👍
