### ISSUE TITLE
opensips 2_2 xcap table error

### ISSUE THREAD

**Issue by soulofmischief87** [OpenSIPS/opensips#1004]
I am trying to implement presence on my opensip 2_2 instance with the latest pull but the db created is not the one the module is expecting.

Dec 15 21:56:59 cloud-server-06 /sbin/opensips[31547]: ERROR:core:db_check_table_version: invalid version 0 for table xcap found, expected 4
Dec 15 21:56:59 cloud-server-06 /sbin/opensips[31547]: ERROR:xcap:mod_init: error during table version check.
Dec 15 21:56:59 cloud-server-06 /sbin/opensips[31547]: ERROR:core:init_mod: failed to initialize module xcap

I am loading the module much like the simple config like 

 loadmodule "xcap.so"
 loadmodule "presence.so"
loadmodule "presence_xml.so"
 modparam("xcap|presence", "db_url",
       "mysql://opensips:cancer123@localhost/opensips")
modparam("presence_xml", "force_active", 1)
 modparam("presence", "server_address", "sip:127.0.0.1:5060") # CUSTOMIZE ME

**Comment by razvancrainea** [comment]
Are you sure you did install the presence tables? Can you check the database to see if you have the following tables: presentity, active_watchers, watchers, xcap and pua?

If not, you might need to re-run `opensipsdbctl create` and when prompt `Install presence related tables?`, select `y`.

**Comment by soulofmischief87** [comment]
Razvan,


I've recreated the tables several times and I am not sure why I dont see those tables. I tried the following


show tables;
+----------------------------+
| Tables_in_opensips         |
+----------------------------+
| acc                        |
| address                    |
| aliases                    |
| b2b_entities               |
| b2b_logic                  |
| cachedb                    |
| carrierfailureroute        |
| carrierroute               |
| cc_agents                  |
| cc_calls                   |
| cc_cdrs                    |
| cc_flows                   |
| clusterer                  |
| cpl                        |
| dbaliases                  |
| dialog                     |
| dialplan                   |
| dispatcher                 |
| domain                     |
| domainpolicy               |
| dr_carriers                |
| dr_gateways                |
| dr_groups                  |
| dr_partitions              |
| dr_rules                   |
| emergency_report           |
| emergency_routing          |
| emergency_service_provider |
| fraud_detection            |
| globalblacklist            |
| grp                        |
| imc_members                |
| imc_rooms                  |
| load_balancer              |
| location                   |
| missed_calls               |
| re_grp                     |
| registrant                 |
| route_tree                 |
| rtpproxy_sockets           |
| silo                       |
| sip_trace                  |
| speed_dial                 |
| subscriber                 |
| tls_mgm                    |
| uri                        |
| userblacklist              |
| usr_preferences            |
| version                    |
+----------------------------+
49 rows in set (0.00 sec)

mysql> exit
Bye
# opensipsdbctl presence
MySQL password for root: 
INFO: creating presence tables into opensips ...
Warning: Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 1: Duplicate entry 'presentity' for key 't_name_idx'
ERROR: Failed to create presence tables!

**Comment by soulofmischief87** [comment]
I got this after dropping the tables and recreating.
opensipsdbctl create
MySQL password for root: 
INFO: test server charset
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
INFO: creating database opensips ...
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
INFO: Using table engine InnoDB.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
INFO: Core OpenSIPS tables successfully created.
Install presence related tables? (y/n): y
INFO: creating presence tables into opensips ...
Warning: Using a password on the command line interface can be insecure.
ERROR 1101 (42000) at line 2: BLOB/TEXT column 'extra_hdrs' can't have a default value
ERROR: Failed to create presence tables!

**Comment by razvancrainea** [comment]
It looks like in Mysql 5.7 you are no longer allowed to set a default value for a blob field. This means that the presentity table cannot be created, because its signature is: `extra_hdrs BLOB DEFAULT '' NOT NULL`.

In order to fix this, we need to update opensips's code to handle NULL values for extra headers.

In the meantime, you can do the following temporary fixes (in my order of preference):

1. Change the SQL mode according to [this thread](https://gistpages.com/posts/blob_text_column_can_t_have_a_default_value_create_table_from_mysql)
2. edit the `mysql/presence-create.sql` file and remove the `DEFAULT ""` tokens from all the BLOB and TEXT fields
3. Switch to mariadb :)
4. Downgrade the mysql server :))

We will keep this ticket open until we have a final fix.
