### ISSUE TITLE
segmentation fault crash possibly in dialog.so

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#1005]
Hi, 

Not quite sure how this crash is triggered, happened a couple of times now spread over a few weeks.
Core file is available on original machine, ping me 'hydrosine' on IRC for looking through it.
Also I have the error logs related to this crash which contain a lot of 
`/usr/sbin/opensips[17240]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 390336510 ms (now 390336610 ms), it may overlap..`
right before the crash. I will not share this log here, but will gladly send you the link to it.

(gdb) bt
#0  0x00000000004b4093 in fm_malloc ()
#1  0x00007f3689bd0c9e in dlg_add_leg_info () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
#2  0x00007f3689bbba5e in ?? () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
#3  0x00007f3689bc2ca2 in dlg_create_dialog () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
#4  0x00007f3689ba823a in ?? () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
#5  0x000000000041cdbf in do_action ()
#6  0x0000000000422c70 in run_action_list ()
#7  0x0000000000420302 in do_action ()
#8  0x0000000000422c70 in run_action_list ()
#9  0x0000000000420302 in do_action ()
#10 0x0000000000422c70 in run_action_list ()
#11 0x0000000000422d46 in ?? ()
#12 0x000000000041f4f5 in do_action ()
#13 0x0000000000422c70 in run_action_list ()
#14 0x0000000000420302 in do_action ()
#15 0x0000000000422c70 in run_action_list ()
#16 0x0000000000422f80 in run_top_route ()
#17 0x00000000004698c9 in receive_msg ()
#18 0x000000000052747d in ?? ()
#19 0x000000000051cccb in udp_rcv_loop ()
#20 0x000000000051d6f6 in udp_start_processes ()
#21 0x0000000000419715 in main ()

**Comment by hydrosine** [comment]
Just experienced another crash, again in the log a lot of utimers but crashed on a different .so this time usrloc.
Again, Core is available, i can supply the logs in PM via irc.

#0  0x00000000004b4093 in fm_malloc ()
#1  0x00007f3eb5602664 in new_urecord () from /usr/lib/x86_64-linux-gnu/opensips/modules/usrloc.so
#2  0x00007f3eb55fb318 in mem_insert_urecord ()
   from /usr/lib/x86_64-linux-gnu/opensips/modules/usrloc.so
#3  0x00007f3eb55fbf68 in insert_urecord () from /usr/lib/x86_64-linux-gnu/opensips/modules/usrloc.so
#4  0x00007f3eb4ba199f in save_aux () from /usr/lib/x86_64-linux-gnu/opensips/modules/registrar.so
#5  0x00007f3eb4ba34ed in save () from /usr/lib/x86_64-linux-gnu/opensips/modules/registrar.so
#6  0x000000000041cdbf in do_action ()
#7  0x0000000000422c70 in run_action_list ()
#8  0x0000000000420302 in do_action ()
#9  0x0000000000422c70 in run_action_list ()
#10 0x0000000000422f80 in run_top_route ()
#11 0x00000000004698c9 in receive_msg ()
#12 0x000000000052747d in ?? ()
#13 0x000000000051cccb in udp_rcv_loop ()
#14 0x000000000051d6f6 in udp_start_processes ()
#15 0x0000000000419715 in main ()

**Comment by bogdan-iancu** [comment]
Hi @hydrosine , the crash points to some memory corruption...hard to say which modules is responsible for it. I see you use the F_MALLOC memory manager - do you have the  DBG_MALLOC flag also compiled in ? ( check via "opensips -V").

Also, can you check if you have this commit in your code : https://github.com/OpenSIPS/opensips/commit/68d4240698e639490ab7dfa187b1458f00146fb3#diff-75cd9b613b8633e4c20e9b5020da2011 ?

**Comment by hydrosine** [comment]
I do not have the DBG_MALLOC compiled in, also the commit is not there :(
Also on the machine on which i have the _dbg.deb installed there is no DBG_MALLOC

**Comment by bogdan-iancu** [comment]
@hydrosine , do you have any updates on this ?

**Comment by bogdan-iancu** [comment]
one more ping here :)

**Comment by bogdan-iancu** [comment]
@hydrosine if you still get the crash, please open a new ticket, I will close this one.
