### ISSUE TITLE
rtpproxy and timeout socket

### ISSUE THREAD

**Issue by denis7979** [OpenSIPS/opensips#1009]
Hello!

I am using rtpproxy in my VoIP network and now i want to locate it on another server rather then Opensips instance.
Rtpproxy is started with such parameters:
/usr/local/rtpproxy2/bin/rtpproxy -u <user> -p <path/to/pidfile> -l <ip> -s udp:<ip>:<port> -i -T 10 -n tcp:<ip>:2229 -m 35000 -M 45000 -r <path/to/callrecords> -R -P -d INFO LOG_LOCAL5
 
The Proxy of rtp packet works fine but when i emulated stop transfer of rtp i see in log such string:
ERR:<callid>:rtpp_command_ul_handle: invalid socket name <ip>:2229

The version of rtpproxy - 2.2.alpha.20160822

**Comment by bogdan-iancu** [comment]
@denis7979 , in the `-n` param, you should have the IP too, like `tcp:ip:2229`. This socket has to match the one defined in the rtpproxy module via [rtpp_notify_socket](http://www.opensips.org/html/docs/modules/2.2.x/rtpproxy.html#id293871)

**Comment by denis7979** [comment]
Hello! I downloaded the latest rtpproxy version and try to start it.The command/usr/local/rtpproxy/bin/rtpproxy -u opensips -p /sock/rtpproxy.pid -l <ip> -s udp:<ip>:221 -i -T 10 -n tcp:<ip>:2229 -m 35000 -M 45000 -r /mnt/callrecords/ -R -P -d INFO LOG_LOCAL5 rtpproxy started successfully. But when i checked listening ports on the system (netstat -aon | grep 2229) i cannot see any tcp socket fot the 2229 port.Meanwhile the udp socket of 221 i can see. What the problem may be? Thank you. -- С уважением, Денис.Best regards, Denis     25.01.2017, 18:32, "Bogdan Andrei IANCU" <notifications@github.com>:@denis7979 , in the -n param, you should have the IP too, like tcp:ip:2229. This socket has to match the one defined in the rtpproxy module via rtpp_notify_socket—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by razvancrainea** [comment]
The `-n` parameter is used to tell RTPProxy where to send the notification. This socket is opened by OpenSIPS, not by RTPProxy.

PS: please open a new ticket for new issues. This was one already closed.

**Comment by denis7979** [comment]
Yes, Razvan, it was my fault about understanding of the process. Timeout working. Thank you one more time. -- С уважением, Денис.Best regards, Denis     09.02.2017, 15:18, "Răzvan Crainea" <notifications@github.com>:The -n parameter is used to tell RTPProxy where to send the notification. This socket is opened by OpenSIPS, not by RTPProxy.PS: please open a new ticket for new issues. This was one already closed.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
