### ISSUE TITLE
tm and dispatcher custom max-forward header

### ISSUE THREAD

**Issue by darencrew** [OpenSIPS/opensips#1011]
Hello,

Thanks for the great job made with OpenSIPS, i made in some hours what i didn't succeed to do with lots of other software (even with some cousins :) )

The last thing missing was a requirement to use Max-Forwards value of 0 for probing peers, but that is unfortunately not settable on dispatch module parameters.

I probably should create a parallel feature request?

In the doubt and to go faster i made a small patch to dispatch.c:
```
                                        str headers = { "Max-Forwards: 0\r\n", 17};
                                        if (tmb.t_request_within(&ds_ping_method,
                                                        &headers,
                                                        NULL,
                                                        dlg,
                                                        ds_options_callback,
                                                        (void*)cb_param,
                                                        shm_free_cb_param) < 0) {
                                                LM_ERR("unable to execute dialog\n");
                                        }

```

The problem is TM (used for the probing) is always adding "Max-Forwards" header, even if already present.
I'm not expert enough on available function to test header presence to condition if it should be added (if missing), so i made small changes on t_msgbuilder.c `build_uac_req` function, things like:

```
....
        if(headers)
        {
                /* Additional headers */
                *len += (headers ? headers->len : 0);
        }
        else
        {
                /* Max-Forwards */
                *len += LOCAL_MAXFWD_HEADER_LEN;
        }
....
....
        if (headers)
        {
                append_string(w, headers->s, headers->len);
        }
        else
        {
                /* Max-Forwards */
                append_string(w, LOCAL_MAXFWD_HEADER, LOCAL_MAXFWD_HEADER_LEN);
        }
```

I know that's not perfect to consider additional headers forcibly contains Max-Forwards header, but that was the best solution i found with my very little knowledge about opensips available functions and about programing.

If you agree with the request, and know how to better manage that, that would be great to have the "custom headers on dispatch ping" added to trunk !

Let me know if you need any additional information.

Thanks again !

PS: attached are the modded two files, sorry not to have the diff

[dispatch.c.txt](https://github.com/OpenSIPS/opensips/files/679166/dispatch.c.txt)
[t_msgbuilder.c.txt](https://github.com/OpenSIPS/opensips/files/679165/t_msgbuilder.c.txt)

**Comment by bogdan-iancu** [comment]
@darencrew. Are you sure that adding a MF 0 header is correct ? IMHO, this conflicts with rfc3261, 8.1.1.6 chapter:
> If the Max-Forwards value reaches 0 before the request reaches its destination, it will be rejected with a 483(Too Many Hops) error response.
So, the probes should be discarded by the destination with 483.

Still, chapter 16.3 Request Validation, bullet 3, says:

> If the request contains a Max-Forwards header field with a field value of zero (0), the element MUST NOT forward the request.  If the request was for OPTIONS, the element MAY act as the final recipient and respond per Section 11.  Otherwise, the element MUST return a 483 (Too many hops) response.

where section 11 Querying for Capabilities says:

> Alternatively, a server receiving an OPTIONS request with a Max-Forwards header field value of 0 MAY respond to the request regardless of the Request-URI.

So, the MF 0 may be used ONLY with OPTIONS, but IMHO most servers will actually decline such "probes" as a failed MF test.

**Comment by darencrew** [comment]
Hi Bogdan,
Sorry for the delay in my reply, i missed the notification mail :(


As you mention on RFC, it deals with, in case of MF=0
- reply with 483 : that's the expected behavior
- not to forwards : that's also the expected behavior, as not forwarding doesn't mean not to reply...
MF 0 is, indeed, used for probe, but, in dispatch module, I only have to specify 483 as acceptable reply and that does the job.


As you can imagine, I'm not at the origin of the request, that a requirement from the french telecom federation, and more specifically from Orange...

**Comment by bogdan-iancu** [comment]
Hi @darencrew ,

So, the fix should include:
* allow module option in dispatcher to configure the value for MF on pinging (spit an error if MF is set to 0 for a non OPTIONS ping method).
* the t_uac() should accept as input the MF header (and add one only if no MF hdr is provided).

Is this correct ?

**Comment by darencrew** [comment]
Hi Bogdan,

Yes, i couldn't say that better :)

That was more difficult for me to code it as you can see above ;)

Thank you !
