### ISSUE TITLE
OpenSips 2.2.2 - Problem aaa_radius 

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1015]
OS - Centos 7.3
Opensips - 2.2.2 latest from git 
ERROR:core:sr_load_module: could not open module </usr/local/lib64/opensips/modules/aaa_radius.so>: /usr/local/lib64/opensips/modules/aaa_radius.so: undefined symbol: rc_acct_resume
ERROR:core:load_module: failed to load module
CRITICAL:core:yyerror: parse error in config file /etc/opensips/opensips.cfg, line 53, column 13-14: failed to load module aaa_radius.so
ERROR:core:set_mod_param_regex: no module matching aaa_radius found

**Comment by razvancrainea** [comment]
What is the radius client library you are using and what version?

**Comment by goup2010** [comment]
I use freeradius-client-1.1.7

Applay patch with follow command:

mkdir freeRADIUS-client;
cd freeRADIUS-client
wget ftp://ftp.freeradius.org/pub/freeradius/freeradius-client-1.1.7.tar.gz
tar -xzvf freeradius-client-1.1.7.tar.gz
cd freeradius-client/freeradius-client-1.1.7.tar.gz
patch -p1 < /root/opensips_2_2/modules/aaa_radius/radius_async_support.patch
./configure
make
make install


cp include/freeradius-client.h /usr/include/freeradius-client.h

2017-01-10 11:35 GMT+02:00 Răzvan Crainea <notifications@github.com>:

**Comment by razvancrainea** [comment]
Can you run `ldd /usr/local/lib64/opensips/modules/aaa_radius.so | grep radius; ls -l /usr/local/lib/ | grep radius` and send over the output?

**Comment by goup2010** [comment]
libfreeradius-client.so.2 => /lib64/libfreeradius-client.so.2 (0x00007f929c296000)
-rw-r--r-- 1 root root 348932 Jan  9 18:23 libfreeradius-client.a
-rwxr-xr-x 1 root root   1040 Jan  9 18:23 libfreeradius-client.la
lrwxrwxrwx 1 root root     29 Jan  9 18:23 libfreeradius-client.so -> libfreeradius-client.so.2.0.0
lrwxrwxrwx 1 root root     29 Jan  9 18:23 libfreeradius-client.so.2 -> libfreeradius-client.so.2.0.0
-rwxr-xr-x 1 root root 210712 Jan  9 18:23 libfreeradius-client.so.2.0.0

**Comment by razvancrainea** [comment]
It looks you have both `freeradius-client` library installed from the packages in `/lib64` as well as the library compiled manually and installed in `/usr/local/lib`.
If you want to use the manually compiled one, remove the `freeradius-client` package and OpenSIPS will auto-detect it.

However, we should provide a way to be able to force a specific library (i.e. using `CROSS_COMPILE` features).

**Comment by goup2010** [comment]
Thanks!
Now working fine!
