### ISSUE TITLE
dbtext: presentity table issue with empty values

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#1017]
The following fields from presentity table must accept empty/null values:
- body
- extra_hdrs
- sender

In the dbtext file, the above fields should be defined as: 
````
... body(blob,null) extra_hdrs(blob,null) sender(string,null)
````
The definition for **body** and **extra_headers** should be identical in ./db/schema/pr_presentity.xml
For regular presence stuff, extra_hdrs field will not be used and for sca (aka call-info) the body field will not be used.

**Comment by razvancrainea** [comment]
Hi, Ovidiu!

This looks somehow related to #1004. As documented there, MySQL does not allow a blob to have a default value. If we would set them to `NULL`, that ticket will also be fixed.
I was about to check if those `extra_headers` can and/or should be `NULL`, but didn't find the time yet. Did you manage to test this with `NULL` body and extra_headers?

Best regards,
Răzvan

**Comment by ovidiusas** [comment]
Here's what works for sca with both db_text and db_mysql:
````
    <column>
        <name>body</name>
        <type>binary</type>
        <null/>
    </column>

    <column>
        <name>extra_hdrs</name>
        <type>binary</type>
        <null/>
    </column>

    <column id="sender">
        <name>sender</name>
        <type>string</type>
        <null/>
        <size>&uri_len;</size>
        <description>Sender contact</description>
    </column>
````
and this will create the fields in mysql like this:
````
    body BLOB,
    extra_hdrs BLOB,
    sender CHAR(128),
````

I can commit the changes if this is ok with everybody.

**Comment by ovidiusas** [comment]
I tested with NULL values in the table and it is working ok.
I tested with sca only. The code seems to check for NULL values.
I haven't tested with regular presence (which uses the **body** field and ignores **extra_hdr** field).
The presentity table is populated by the opensips (in other word not by hand), so this should work ok.
