### ISSUE TITLE
mi_json returns invalid response for address_dump

### ISSUE THREAD

**Issue by l7s** [OpenSIPS/opensips#1018]
Hi,

mi_json in OpenSIPS v. 2.2.2 returns invalid JSON string for address_dump command, see below:
```
GET /json/address_dump HTTP/1.1.
User-Agent: Level 7 MI Client.
Host: 172.16.16.228:8001.
Accept: application/json.

HTTP/1.1 200 OK.
Connection: close.
Content-Length: 250.
Content-Type: application/json.
Date: Wed, 11 Jan 2017 17:24:12 GMT.

{"value":"default
", "value":".  59 <81.201.82.50,2, 0, 0, NULL, TermGw:2>", "value":".  63 <173.248.154.23,2, 0, 0, NULL, TermGw:32>", "value":".  92 <87.238.73.137,2, 0, 0, NULL, TermGw:12>", "value":". 116 <172.16.16.42,2, 0, 0, NULL, TermGw:22>"}
```

The above response doesn't validate at http://jsonlint.com/

Regards,
Chris

**Comment by liviuchircu** [comment]
Indeeed, @l7s , the output structure was not compatible with the `mi_json` module. I have pushed a fix for this on the `master` branch (a56854b9fc5). As soon as I make sure it doesn't break the Control Panel (or we adapt its address module as well), I'll have it backported to `2.2` branch.

**Comment by l7s** [comment]
@liviuchircu - thanks for fixing this. Any chance of merging [this commit](https://github.com/OpenSIPS/opensips/commit/a56854b9fc50a7be46372f77743158bcd054c98e) into 2.2.2 branch?
Regards,
Chris

**Comment by liviuchircu** [comment]
Double-checked the Control Panel, and it seems to not do any `address_reload` commands at all, so I backported the patch to `2.2`. The JSONs of `2.1`'s `address_reload` command are valid, nothing to do there.

**Comment by l7s** [comment]
Unfortunately this isn't working correctly yet. Response contains horizontal TAB characters (hex 09) which are not allowed in JSON - see below:

![tab-ngrep](https://cloud.githubusercontent.com/assets/5430068/22987107/a090f0fc-f3a5-11e6-9f02-c0dc7a3c5a4e.png)

![tab-hex](https://cloud.githubusercontent.com/assets/5430068/22987124/aa38c6ac-f3a5-11e6-9a02-f8f19c8f6ed2.png)

at the moment response is (`.` represents horizontal TAB character):

```
{"part": [{"value":"default", "children":{"dest": [{"value":".  59 <81.201.82.50,2, 0, 0, NULL, TermGw:2>"}, {"value":".  63 <173.248.154.23,2, 0, 0, NULL, TermGw:32>"}, {"value":".  92 <87.238.73.137,2, 0, 0, NULL, TermGw:12>"}, {"value":". 116 <172.16.16.42,2, 0, 0, NULL, TermGw:22>"}]}}]}
```

what I would suggest instead is:


```
{"part": [{"value":"default", "children":{"dest": [{"value":"59 <81.201.82.50,2, 0, 0, NULL, TermGw:2>"}, {"value":"63 <173.248.154.23,2, 0, 0, NULL, TermGw:32>"}, {"value":"92 <87.238.73.137,2, 0, 0, NULL, TermGw:12>"}, {"value":"116 <172.16.16.42,2, 0, 0, NULL, TermGw:22>"}]}}]}
```
so TAB and leading spaces are removed.

**Comment by l7s** [comment]
After re-considering, I think the most optimal JSON format for address data would be:

for empty address table:
```
[]
```

for address table with data:
```
[ { "grp": 2, "ip": "192.168.5.5", "mask": 32, "port": 5060, "proto": "any", "pattern": null, "context_info": null } ]
```

the current format is somewhat difficult to work with and requires further parsing of "value" element for data to be usable.

**Comment by liviuchircu** [comment]
Thank you for the suggestions, @l7s ! I did this change on the `master` branch, to avoid any backwards-incompatibility issues with existing MI parsing code. [Here](http://pastebin.com/SS1CEj3d)'s how the output ended up looking like.
