### ISSUE TITLE
mysql/call_center-create.sql missing INSERT INTO version...

### ISSUE THREAD

**Issue by l7s** [OpenSIPS/opensips#1020]
Hi,

File below:
https://github.com/OpenSIPS/opensips/blob/master/scripts/mysql/call_center-create.sql#L39

is missing:
```
INSERT INTO version (table_name, table_version) values ('cc_calls','1');
```

at line 39.

Regards,
Chris

**Comment by razvancrainea** [comment]
Hi, Chris!

I don't think that's needed, because OpenSIPS does not check the version of the `cc_calls` table.
Is this something that you noticed it is missing, or I am missing something and this really is a bug?

Best regards,
Răzvan

**Comment by l7s** [comment]
Hi Răzvan, I was just reviewing files in `scripts/mysql` folder and noticed that `cc_calls` is the only table which is missing `INSERT INTO version ...` statement, but if that table doesn't check it's version, that is fine and we can close this ticket as invalid. (I am not using call_center module, so didn't validate if OpenSIPs is complaining about this or not).

Out of curiosity - is there any particular reason they this table isn't checked in `version` table?

Regards,
Chris

**Comment by razvancrainea** [comment]
Not sure, it's just that the author of the module did not write the code to check the version. Or simply did not find it important enough to just not start OpenSIPS if that version is wrong. At the end of the day, calls will still go though if that table is wrong, they will just not be stored in the db and will not survive restart.

Anyway, I will leave this ticket opened until we determine whether we should have version check or not. But will set as a low priority.
