### ISSUE TITLE
async radius problem

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1025]
When run  async radius from onreply_route Opensips crashed.
All working fine if use async radius from main route.

OS - CEntOs 7.3
Opensips 2.2.2 - git hub from 15.01.2017

onreply_route[outgoing] {
	  .....
	  if (t_check_status("200")) {
		  async( radius_send_auth("prepayout","prepayin"), return_rad );
	  }
}

route[return_rad] {
	xlog("L_ERR", "Radius return $rc");
}

Here is part of Opensips log level 6:

 /usr/sbin/opensips[21026]: DBG:tm:update_totag_set: new totag
 /usr/sbin/opensips[21026]: DBG:tm:insert_timer_unsafe: [2]: 0x7fee75f19bd0 (36)
 /usr/sbin/opensips[21026]: DBG:tm:run_trans_callbacks: trans=0x7fee75f19b50, callback type 64, id 0 entered
 /usr/sbin/opensips[21005]: DBG:core:handle_sigs: status = 11
 /usr/sbin/opensips[21005]: INFO:core:handle_sigs: child process 21026 exited by a signal 11
 /usr/sbin/opensips[21005]: INFO:core:handle_sigs: core was not generated
 /usr/sbin/opensips[21005]: INFO:core:handle_sigs: terminating due to SIGCHLD
 /usr/sbin/opensips[21024]: INFO:core:sig_usr: signal 15 received
 /usr/sbin/opensips[21011]: INFO:core:sig_usr: signal 15 received
 /usr/sbin/opensips[21018]: INFO:core:sig_usr: signal 15 received

**Comment by razvancrainea** [comment]
Currently async operations are only available for requests, not for replies. In the onreply_route you can only use synchronous operations for now.
