### ISSUE TITLE
"404 Contact not found" after use 'opensipsctl fifo ul_rm_contact location'

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1027]
Hello! I can not delete a contact from an AOR record with ul_rm_contact command.

Existing AOR:
opensipsctl fifo ul_show_contact location user@domain
AOR:: user@domain
	Contact:: sip:user@7.7.7.7:49738;rinstance=5562c1f3b98928a0;transport=TCP Q=
		Expires:: 1785
		Callid:: YmM5NjcyZDExMjI3ZmQ3MTc1ZDc0NmYzNzcwYzNlNDc.
		Cseq:: 2
		User-agent:: Z 3.3.25608 r25552
		State:: CS_SYNC
		Flags:: 0
		Cflags:: NAT_PING
		Socket:: udp:192.168.2.2:5060
		Methods:: 5951

I am trying to use: 
opensipsctl fifo ul_rm_contact location user@domain sip:user@7.7.7.7:49738;rinstance=5562c1f3b98928a0;transport=TCP

And i see answer from server: 404 Contact not found
Maybe i am incorrect copying contact from AOR?

modparam("usrloc", "matching_mode", 1)
OpenSIPS (2.2.2 (x86_64/linux))

Thanks you very much!

**Comment by bogdan-iancu** [comment]
Hi @kertor , it is a shell issue, interpreting your contact URI :).
Try:

> opensipsctl fifo ul_rm_contact location user@domain 'sip:user@7.7.7.7:49738;rinstance=5562c1f3b98928a0;transport=TCP'

(note the ' around the URI).

**Comment by kertor** [comment]
Great, thanks you Bogdan)) I ask forgiveness for your time
