### ISSUE TITLE
Radius ACC - wrong Sip-Call-Setuptime

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1032]
I use OpenSips  2.2.2 with Radius ACC.
Radius server receive wrong Sip-Call-Setuptime like this:
Sip-Call-Setuptime = 2938

When using OpenSips 1.10 all is OK.

**Comment by razvancrainea** [comment]
Please elaborate a bit your issue. Your problem is that you receive a Sip-Call-Setuptime of 2938, but you were expecting a different value? What value were you expecting?

**Comment by goup2010** [comment]
When using Opensips 1.10 from Sip-Call-Setuptime I receive Setup Time for call (from 3 to15).
When using Opensips 2.2.2 I receive value like this 2938.  This is not valid.

**Comment by ionutrazvanionita** [comment]
@goup2010 what values do you have for Sip-Call-Duration and Sip-Call-Created? Are they correct?

**Comment by goup2010** [comment]
To clarify - I am expecting this parameter to return call setup time in seconds (that is what 1.10 returns). Now values go in the thousands - definitely not correct as setup time is usually few seconds only.
Here is the info Radius gets from OpenSips (2.2.2) for call duration one second:

&request:Sip-Call-Setuptime = $RAD_REQUEST{'Sip-Call-Setuptime'} -> '1057'
&request:Sip-Call-Created = $RAD_REQUEST{'Sip-Call-Created'} -> '?'
&request:Sip-Method = $RAD_REQUEST{'Sip-Method'} -> 'Invite'
&request:Sip-From-Tag = $RAD_REQUEST{'Sip-From-Tag'} -> 'as1a6659d7'
&request:Sip-Response-Code = $RAD_REQUEST{'Sip-Response-Code'} -> '0'
&request:Sip-Call-Duration = $RAD_REQUEST{'Sip-Call-Duration'} -> '1'

**Comment by ionutrazvanionita** [comment]
Please try this patch and tell me if it fixes your problem
[acc_fix_bad_extra.patch.txt](https://github.com/OpenSIPS/opensips/files/745549/acc_fix_bad_extra.patch.txt)

**Comment by goup2010** [comment]
I have problem to apply the patch:

# patch -p1 < ../patch.opensips
patching file modules/acc/acc.c
Hunk #1 FAILED at 953.
1 out of 1 hunk FAILED -- saving rejects to file modules/acc/acc.c.rej

2017-02-01 19:08 GMT+02:00 Ionut Ionita <notifications@github.com>:

**Comment by ionutrazvanionita** [comment]
@goup2010 yes sorry that bug was only in master branch

**Comment by ionutrazvanionita** [comment]
@goup2010 please try the latest commit from 2.2 https://github.com/OpenSIPS/opensips/commit/081c166bb5a8a9537b41889e58cbc19e6e81a7ff

**Comment by ionutrazvanionita** [comment]
@goup2010 not necessarily related to this issue. can you tell me if Sip-Call-Created is populated? from what i see in the sources it is not and it looks like a bug.

**Comment by goup2010** [comment]
Hello,

I compiled the new update from git hub.
In the first call Sip-Call-Setuptime='Route-IP-No'
In the second call Sip-Call-Setuptime='7'

"Sip-Call-Setuptime" must be integer.
Why in the first call it is string?


######## Test call to 9999
Sip-Call-Setuptime = $RAD_REQUEST{'Sip-Call-Setuptime'} -> 'Route-IP-No'
Acct-Session-Id = $RAD_REQUEST{'Acct-Session-Id'} ->
'o8PLAaj8YIYh021gQLXyjQ..'
Sip-Call-MSDuration = $RAD_REQUEST{'Sip-Call-MSDuration'} -> '7410'
Service-Type = $RAD_REQUEST{'Service-Type'} -> 'SIP-Session'
Acct-Unique-Session-Id = $RAD_REQUEST{'Acct-Unique-Session-Id'} ->
'3b1a27e1a9d5a72dd6f99071d6d57fe4'
MV-System = $RAD_REQUEST{'MV-System'} -> 'testcall'
Acct-Status-Type = $RAD_REQUEST{'Acct-Status-Type'} -> 'Stop'
Sip-From-Tag = $RAD_REQUEST{'Sip-From-Tag'} -> '9223fc43'
Sip-Method = $RAD_REQUEST{'Sip-Method'} -> 'Invite'
NAS-IP-Address = $RAD_REQUEST{'NAS-IP-Address'} -> '127.0.0.1'
Sip-To-Tag = $RAD_REQUEST{'Sip-To-Tag'} -> 'as4306cf8b'
Attr-55 = $RAD_REQUEST{'Attr-55'} -> '0x'
MV-UserName = $RAD_REQUEST{'MV-UserName'} -> '348902386333'
Sip-Response-Code = $RAD_REQUEST{'Sip-Response-Code'} -> '200'
Event-Timestamp = $RAD_REQUEST{'Event-Timestamp'} -> '%??X5?'
MV-Number = $RAD_REQUEST{'MV-Number'} -> '9999'
Sip-Call-Duration = $RAD_REQUEST{'Sip-Call-Duration'} -> '8'
NAS-Port = $RAD_REQUEST{'NAS-Port'} -> '5060'
Acct-Delay-Time = $RAD_REQUEST{'Acct-Delay-Time'} -> '0'

######### Test call to 354884441356
Sip-Call-Setuptime = $RAD_REQUEST{'Sip-Call-Setuptime'} -> '7'
Acct-Session-Id = $RAD_REQUEST{'Acct-Session-Id'} ->
'YIUaJv756JKi-swTKviJsw..'
Sip-Call-MSDuration = $RAD_REQUEST{'Sip-Call-MSDuration'} -> '10419'
Service-Type = $RAD_REQUEST{'Service-Type'} -> 'SIP-Session'
Acct-Unique-Session-Id = $RAD_REQUEST{'Acct-Unique-Session-Id'} ->
'bb5e4306065515e834cf2ba5a6252fac'
MV-System = $RAD_REQUEST{'MV-System'} -> 'testcall'
Acct-Status-Type = $RAD_REQUEST{'Acct-Status-Type'} -> 'Stop'
Sip-From-Tag = $RAD_REQUEST{'Sip-From-Tag'} -> '861b1476'
Sip-Method = $RAD_REQUEST{'Sip-Method'} -> 'Invite'
NAS-IP-Address = $RAD_REQUEST{'NAS-IP-Address'} -> '127.0.0.1'
Sip-To-Tag = $RAD_REQUEST{'Sip-To-Tag'} -> 'as6f3b806b'
Attr-55 = $RAD_REQUEST{'Attr-55'} -> '0x'
MV-UserName = $RAD_REQUEST{'MV-UserName'} -> '348902386333'
Sip-Response-Code = $RAD_REQUEST{'Sip-Response-Code'} -> '200'
Event-Timestamp = $RAD_REQUEST{'Event-Timestamp'} -> 'Ȟ?X5?'
MV-Number = $RAD_REQUEST{'MV-Number'} -> '354884441356'
MV-Timestamp = $RAD_REQUEST{'MV-Timestamp'} -> '1486069441'
Sip-Call-Duration = $RAD_REQUEST{'Sip-Call-Duration'} -> '11'
NAS-Port = $RAD_REQUEST{'NAS-Port'} -> '5060'
Acct-Delay-Time = $RAD_REQUEST{'Acct-Delay-Time'} -> '0'

2017-02-02 18:54 GMT+02:00 Ionut Ionita <notifications@github.com>:

**Comment by ionutrazvanionita** [comment]
@goup2010 that's a conflict between **Sip-Call-Setuptime** AVP from dictionary.opensips and **Ascend-Route-IP** from dictionary.ascend, both having index 228. **Ascend-Route-IP** has values defined for 0(**Route-IP-No**) and 1(**Route-IP-Yes**). If you don't use dictionary.ascend you can remove it, or you can change AVP indexesin dictionary.opensips.

**Comment by ionutrazvanionita** [comment]
@goup2010 We digged a little more into this problem, and indeed there is a problem with dictionary.opensips and our implementation in acc module. But in order to solve this we need an unique vendor ID from IANA which we hope to get as soon as possible. For the moment I will close this ticket and open another one concerning this problem.
