### ISSUE TITLE
mi_xmlrpc error reporting

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#1033]
When issuing an XMLRPC command that is not implemented/does not exist, the mi_xmlrpc_ng module returns `Internal server error!`, instead of specifying a proper error.

**Comment by ionutrazvanionita** [comment]
Hey @razvancrainea check this PR https://github.com/OpenSIPS/opensips/pull/1038

**Comment by razvancrainea** [comment]
That seems right. Thanks!
