### ISSUE TITLE
In dialog pinging starting between 200 OK and ACK causing disconnects

### ISSUE THREAD

**Issue by thesipguy** [OpenSIPS/opensips#1034]
http://lists.opensips.org/pipermail/users/2017-February/036482.html

I attached a pcap file, IP 94.226.190.243 is the USER, IP 104.131.42.102 is the OpensSIPS server, IP 95.85.11.107 is the gateway (Freeswitch) , you can see that after the 200 the pinging starts, and then when the USER sends a ACK,  OpenSIPS uses the cseq (602) from the OPTION ping for the ACK sent to the Gateway, gateway ignores it because it does not match a invite and keeps on sending OK's and OpenSIPS keeps on sending the wrong CSEQ's in the ACK, until the gateway finally gives up and sends a BYE with Reason: SIP;cause=408;text="ACK Timeout"

[ackCSEQ.zip](https://github.com/OpenSIPS/opensips/files/744839/ackCSEQ.zip)

**Comment by bogdan-iancu** [comment]
@thesipguy , this is a fix I tested on master, still I'm not able to get the kind of overlapping between the ACK and first ping (as per your original report) - could you please test the fix before doing a backport ?
Thanks, Bogdan

**Comment by thesipguy** [comment]
@bogdan-iancu I didnt apply this fix because its a production server, and I its very difficult for me to test it because it happens very randomly, I guess I will wait till I upgrade to the next minor version, which version should have this fix?

**Comment by thesipguy** [comment]
@bogdan-iancu does the 2.2.3 have the fix?

**Comment by thesipguy** [comment]
@bogdan-iancu I dont see the fix in the 2.2.3 changelog :-(

**Comment by bogdan-iancu** [comment]
@thesipguy , I just backported the fix to 2.2 branch - the fix will be part of the next minor release on 2.2 branch (2.2.4) ; or simply use the 2.2 GIT branch to get the code.
