### ISSUE TITLE
Stale TCP socket on failed de-register causes problems

### ISSUE THREAD

**Issue by jdlouw** [OpenSIPS/opensips#1035]
Hi,
I have the following opensips.cfg settings set up:

`modparam("registrar", "max_contacts", 1)`
`save("location", "fp1")`

If a UAC fails to de-register properly, then re-registers (basically power-cycles), the contact is successfully overwritten by opensips, but a stale TCP connection remains open:

`$opensipsctl ul show`
`        AOR:: test1`
`                Contact:: sip:test1@10.0.0.183:5061;transport=tls Q=`
`                        Expires:: 299`
`                        Callid:: 54fc4edd37184792`
`                        Cseq:: 55933`
`                        User-agent:: UA v1.0`
`                        State:: CS_NEW`
`                        Flags:: 0`
`                        Cflags:: `
`                        Socket:: tls:10.0.0.100:5061`
`                        Methods:: 4294967295`

`$sockstat -P tcp`
`USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS`
`opensips opensips   2371  37 tcp4   10.0.0.100:5061       10.0.0.183:55111`
`opensips opensips   2371  38 tcp4   10.0.0.100:5061       10.0.0.183:50945`

This causes problems when a subsequent MESSAGE is sent to this AOR, because opensips uses the wrong (stale) socket to forward the MESSAGE to. 

Im thinking opensips should close the associated TCP socket when a contact is overwritten

**Comment by bogdan-iancu** [comment]
Hi @jdlouw, If the UAC restarted, I suppose it dropped all its TCP connection. The question is why there is no EOF (and connection terminated) reported at the TCP/IP level in the machine where OpenSIPS run.
OpenSIPS itself cannot determine if a connection is stale or not without any reporting from the OS level (TCP/IP).

**Comment by jdlouw** [comment]
Hi Bogdan, thanks for taking the time.

Yes, I understand that OpenSIPS cannot determine if the socket is stale if no TCP FIN or RST is received from the UAC. However, when UAC is abruptly disconnected (wifi disconnect, ethernet disconnect, power cable disconnect) there is no time to close the TCP socket cleanly from the UAC side.

What OpenSIPS does have control over is list of contacts for an AOR. There should be some association between contact and TCP socket somewhere right? When an old contact is deleted on re-register (`max_contacts = 1`) the associated TCP socket should be closed from OpenSIPS's side as well.

Further details: I'm running OpenSIPS on FreeBSD but I suppose all TCP stacks will have this issue. Another interesting behaviour I noticed was that a different brand UAC does not trigger this bug. The only difference I could detect was that the brand2 UAC reports the ephemeral port in the `contact` header, whereas the brand1 UAC always report port 5061. I'm thinking there's some hash table lookup in the contact code that returns wrong socket for brand1 UAC but right socket for brand2 UAC.

**Comment by bogdan-iancu** [comment]
@jdlouw , could you provide (even PM) 2 traces - one for the registration of brand1 and the other for brand2 ? Let's see if we spot any issues.

On the other hand the idea of keeping the registrations correlated to the TCP connections may be interesting, but maybe also a but dangerous - still I think it worth investigating.

**Comment by jdlouw** [comment]
[uac_brand1_stale.zip](https://github.com/OpenSIPS/opensips/files/760797/uac_brand1_stale.zip)

Attached is a pcap trace of UAC brand1, showing a registration from UAC from 10.0.0.30 and OpenSIPS on 10.0.0.248. UAC registers using tcp src port 52904, then re-registers using src port 52908, but OpenSIPS tries to forward subsequent request to the old port 52904 and receives a TCP RST.

**Comment by bogdan-iancu** [comment]
@jdlouw , sorry for the delay. I took a look at the trace and I have a question for you: what opensips version are you using ? I'm asking as there are some big differences between versions, when comes to the TCP alias behaving .

**Comment by jdlouw** [comment]
I tested with 1.11.7 and 2.2.2

**Comment by bogdan-iancu** [comment]
Do you do any force_tcp_aliases() from the script ? Or anything related to aliases?

**Comment by jdlouw** [comment]
No, I didn't touch anything related to aliases.

**Comment by jdlouw** [comment]
What about ` save("location", "fp1")`? The documentation says about the 'f' flag: "This flag makes sense only if "cxx" is used." I set the global `modparam("registrar", "max_contacts", 1)`. Anyway, I believe I tested 'c01' without sucess.

**Comment by bogdan-iancu** [comment]
@jdlouw , this is strange, as in 2.2 , without aliases or fix_nated_contact() this registration will not be usable. 
The registered contact is `sip:test1@10.0.0.183:5061;transport=tls`, but the actual TCP connection points to `10.0.0.183:55111` . So, when trying to route the SIP request (after lookup) to `sip:test1@10.0.0.183:5061;transport=tls`, OpenSIPS will not be able to map this destination over the TCP connection, as the conn is know as pointing to a different destination ( `10.0.0.183:55111` ).  This is why I asked if you do anything explicitly with the TCP aliases.

**Comment by jdlouw** [comment]
Even though the registered contact is `sip:test1@10.0.0.183:5061;transport=tls` the call does seem to be routed to `10.0.0.183:55111` most of the time. 

Where does OpenSIPS obtain the contact from. Is it from the contact header in the SIP packet, or is it the from the received socket port? If from the SIP contact header, is this a UAC bug? Should the UAC source port and contact header source port always be the same (not talking about the NAT case)?

**Comment by bogdan-iancu** [comment]
@jdlouw, sorry for dropping this - any availability to continue here ?

**Comment by jdlouw** [comment]
Yep, still here

**Comment by bogdan-iancu** [comment]
@jdlouw , as per previous [comment](https://github.com/OpenSIPS/opensips/issues/1035#issuecomment-293852189), without a fix_nated_contact(), the TCP conn re-usage will not work.
Run this sequence:
1. use 2.4, apply this [patch](https://github.com/OpenSIPS/opensips/files/3468263/opensips_tcp_mi_extra.patch.txt) and recompile
2. register your TCP device and do `opensipsctl fifo ul_dump` and `opensipsctl fifo list_tcp_conns`
3. force the restart of the device and run again the 2 MI commands.

Post here the output of the 2 sets of commands.
