### ISSUE TITLE
Permissions: check_address pattern is not a regular expression

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#1041]
Hi all
Using function check_address of permissions module, I've discovered (unfortunately after a lot of tests) that the pattern parameter is not a regular expression as indicated in the documentation but a "Unix shell-style wildcards pattern" because it is used fnmatch. 
I think that you could clarify in the documentation the use of pattern with an example to immediately understend how to use it. 

I'm going to use this function for implementing a User-Agent blacklist using a subnet mask of length 0 in order to match all IP addresses
Thank you very much for your great work!
Alessandro

**Comment by bogdan-iancu** [comment]
Thank you @arovetto , good point here - the change was done some time ago, but the docs were left behind.
