### ISSUE TITLE
Issue in ACC  (opensips-acc-2.2.2)

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1042]
Hi !

When I just doing:     do_accounting() the Opensips (ver  2.2.2 ) responds:

unknown command <do_accounting>, missing loadmodule?

Even if the do_accouning() is called with wrong parms Opensips should not respond with "unknown command" or did I really missunderstod everything.

**Comment by liviuchircu** [comment]
@stefancn I believe that's the same error given when the wrong params (or param numbers) are used. Could you show the concerned line, so we confirm this?

**Comment by stefancn** [comment]
Hi !
Ye,s I tried the function with parms from only do_accounting("db") to (full set of parms)  do_accounting("db","cdr|missed","acc").  No complain with loading then.  (It would be nice if at least the minimum default values could be used so do_accounting() without parms could run.)
But interesting is that, when I run:     drop_accounting();        opensips responds with:
>>> ERROR:acc:w_drop_acc_2: do_accounting() not used! This function resets flags in do_accounting()!
