### ISSUE TITLE
rtpproxy master version and timeout notifications

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#1043]
Starting with commit sippy/rtpproxy@21e5977, RTPProxy TCP timeout notification mechanism is no longer compatible with OpenSIPS.

Before this commit, when one was using TCP for notification socket, it would have been provisioned as `-n tcp:IP:port`. RTPProxy would strip the `tcp:` part and store the notification socket as `IP:port`. When a new command comes, it compares the notification socket received from OpenSIPS with the one stored. Therefore OpenSIPS needs to send the socket as `IP:port`.

With the new commit, RTPProxy no longer strips the `tcp:` part and stores the socket as `tcp:IP:port`. Therefore OpenSIPS must send the socket as `tcp:IP:port`. This breaks compatibility with older versions.

A solution is to add a module parameter to specify how OpenSIPS should send notification sockets to each RTPProxy engine.

**Comment by flaviogoncalves** [comment]
The problem still remains. A new capture follows. 

[rtpproxy_issue.zip](https://github.com/OpenSIPS/opensips/files/1019948/rtpproxy_issue.zip)

The patched file follows too. 

[timeout_process.zip](https://github.com/OpenSIPS/opensips/files/1019952/timeout_process.zip)
