### ISSUE TITLE
drouting prefix handling is strange (2.2.2)

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1045]
Hi !

In our prefix list we have:

grp 3,     prefix: 70645645   RoutID = "test" and so on.

When I call FROM 70670645645 I use do_routing("3")  I got no match.  
just do_routing() gives the ERROR:drouting:get_group_id: no group for user "70670645645 "@"172.24.7.20"
BUT if I create a new group record with the above data and in this set groupid to 3 It work.
Do I have to do this.

(btw. Incoming call seems to work with just prefixes.)

Thanks for your time.
/S

**Comment by bogdan-iancu** [comment]
Please post the exact module parameters you use for the drouting module.

**Comment by stefancn** [comment]
Hi , thanks for your prompt answer. Here it is:

loadmodule "drouting.so"
modparam("drouting", "db_url","mysql://root:PASSW@localhost/opensips")

modparam("drouting", "use_partitions", 0)
modparam("drouting", "use_domain", 0)
modparam("drouting", "force_dns", 0)

Rest is default.

Quest.  How can drouting know if I want to route of incoming vs. outgoing calls (diff. hdrs !!!.).  One idea would be to add a parm in the rules db. simply a field of:   Inbound , outbound      that sets the data to 0 or 1 for fast parsing.

**Comment by bogdan-iancu** [comment]
@stefancn, are you sure you pass the routing group when invoking do_routing() ? The module is using the dr_group table (to look for the routing group based on the caller - the SIP FROM URI) only if there is no group passed as parameter from the script level.

**Comment by stefancn** [comment]
Hi !

Yes I do, but perhaps I am not so clear in my thoughts.

This is want I (and probably many) will do:

SIP operator 1 ---                                            --- SIP Pbx 1 with numberplan 044203453XXX (1000 nrs)
                              \                                       /                                                prefix: 044203453
                                \                                   /                                                  Always take route to SIP op 1
                                   === Opensips === 
                               /                                    \
                            /                                         \
Sip operator 2 ---                                          --- SIP Pbx 2 with numberplan 0442063454XXX (1000 nrs)
                                                                                                                         prefix: 0442063454
                                                                                                                         Always take route to SIP op 2

I want the SIP Pbx 1 to always take outbound route to Sip operator 2 based on prefix matching 
(eg. part of the users number) NOT the whole user number. 

Is that possible.   
(Incoming from Sip op1 and 2 works as expected NOT Outgoing from Sip Pbx 1 and 2)


thanks for helping me out.

**Comment by bogdan-iancu** [comment]
Let's stick to the initial report, related to the routing group. You are 100% sure you use 
do_routing("3") and still you need the record in the dr_groups table ???

**Comment by stefancn** [comment]
Ok !  Now I i've tried my setup again.  Premises:  I call the dr_routing from invite route and the call is outgoing.

If I call the dr_routing()  without any parms I have to insert a full length phone number  in dr_groups table with appr. grpid. Then the routing engine finds the route.

If I call the dr_routing("3")   grpid 3 in dr_rules and in that rule has a prefix that match some or all of the numbers I got: ERROR:drouting:get_group_id: no group for user .

Summary:   If I want to make a "sourcebased" routing I have to have all our users in the dr_groups->username table and set a appropriate groupid to match outgoing operator. Just put prefixes in a rule with appr. groupid seems not to work.

Hope you understand my issue.

/S

**Comment by bogdan-iancu** [comment]
@stefancn , if I send you a small patch to get more logs, could you apply, recompile and run the scenario with dr_routing("3") ?

**Comment by stefancn** [comment]
Of course,  anything to help


Stefan Carlsson

**Comment by bogdan-iancu** [comment]
Hi @stefancn , sorry for delay. See this patch 
[dr_group_debug.patch.txt](https://github.com/OpenSIPS/opensips/files/902364/dr_group_debug.patch.txt) . It should print via INFO level several logs (at startup and runtime) tagged with "DR_DEBUG". Please send my those lines.

**Comment by bogdan-iancu** [comment]
IMHO this is an invalid report. Nevertheless, if the provided patch reveals some information point the other way, please reopen
