### ISSUE TITLE
Double Route header with Topology Hiding and Overlapping Requests

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1046]
I am testing a scenario where I have opensips doing topology hiding and on overlapping requests it is rejecting the new request with a '491'. However, something I noticed while testing is that when this scenario happens the ACK for the first request that gets forwarded ends up having an extra route header.

I have attached a truncated example (full call is a spam of re-INVITEs to trigger). In this example Cseq 112 is the re-INVITE request that is in progress, CSeq 113 is the overlapping request (re-INVITE and ACK received simultaneously). The ACK for 112, when forwarded, has two route headers. I also included an earlier re-INVITE without overlap that shows a single route header (CSeq 111).

I am also using mc_compact, but not sure if that is related and I don't have a consistent way to trigger this yet. Let me know if any other information would be helpful.

[double_route_ack.txt](https://github.com/OpenSIPS/opensips/files/762091/double_route_ack.txt)

Opensips Info:
version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: ac03a5a
main.c compiled on 09:11:56 Jan 11 2017 with gcc 5.3.1

**Comment by bogdan-iancu** [comment]
@rrb3942 , please try to post the capture as text capture or as pcap - the expanded wireshark-like output is almost impossible to follow.

**Comment by rrb3942** [comment]
Here is the full pcap, hope it helps. Cseq 112 and 113 are the ones to look at.

[Double_RR_ACK.zip](https://github.com/OpenSIPS/opensips/files/788148/Double_RR_ACK.zip)

**Comment by rrb3942** [comment]
Narrowed this down to using validate_dialog()/fix_route_dialog() combined with topology_hiding.
Removed the use of those functions and the problem was solved.
