### ISSUE TITLE
Issue in opensips 2.2.2 and listen ....

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1047]
Have 3 outgoing interfaces eth1, eth1:0, eth1:1 with different IP's.   I've tried to:

listen=udp:172.24.7.12:5060   # Inside eth0
listen=udp:eth1:5060 <<< here I have some problem,  how can I get the opensips to listen too all the eth1 based interfaces.

Chears ...

**Comment by bogdan-iancu** [comment]
Could you be more specific on the "problem" you have ?

**Comment by stefancn** [comment]
Of course ..
I have to explicit tell the opensips to listen to specific IP's not the "physical" interfaces. eg.  

The systemsetup:  [public_ip1]   eth1,     [public_ip2]   eth1:0 ,   [public_ip3]   eth1:1

listen [public_ip1]:5060
listen [public_ip2]:5060
listen [public_ip3]:5060

It would be nice to just do:           listen=udp:eth1:5060 

Hope you understand.

**Comment by bogdan-iancu** [comment]
Please attached the output of "ifconfig" and "ip addr ls" on the machine.

**Comment by stefancn** [comment]
eth0      Link encap:Ethernet  HWaddr 00:50:56:84:0C:6E
          inet addr:172.24.7.12  Bcast:172.24.7.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:364223 errors:0 dropped:0 overruns:0 frame:0
          TX packets:317838 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:126211573 (120.3 MiB)  TX bytes:82601152 (78.7 MiB)

eth1      Link encap:Ethernet  HWaddr 00:50:56:84:4C:9E
          inet addr:X.X.X.X Bcast:X.X.X.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:455812 errors:0 dropped:0 overruns:0 frame:0
          TX packets:228303 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:187046824 (178.3 MiB)  TX bytes:40767269 (38.8 MiB)

eth1:0    Link encap:Ethernet  HWaddr 00:50:56:84:4C:9E
          inet addr:172.24.6.27  Bcast:172.24.6.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:1    Link encap:Ethernet  HWaddr 00:50:56:84:4C:9E
          inet addr:Y.Y.Y.Y  Bcast:Y.Y.Y.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:80278 errors:0 dropped:0 overruns:0 frame:0
          TX packets:80278 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:3427657 (3.2 MiB)  TX bytes:3427657 (3.2 MiB)

*****

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:84:0c:6e brd ff:ff:ff:ff:ff:ff
    inet 172.24.7.12/24 brd 172.24.7.255 scope global eth0
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:50:56:84:4c:9e brd ff:ff:ff:ff:ff:ff
    inet X.X.X.X/24 brd X.X.X.255 scope global eth1
    inet 172.24.6.27/24 brd 172.24.6.255 scope global eth1:0
    inet Y.Y.Y.Y/24 brd Y.Y.Y.255 scope global eth1:1

**Comment by stefancn** [comment]
btw. I just saw that you are one of the authors of the "Building Telephony Systems with openSIPS sec. ed"
a Fantastic book, very pedagogic and has a nice speech. Thanks !!!

**Comment by bogdan-iancu** [comment]
@stefancn, eth1:0 and eth1:1 are actually interfaces different than eth1.  What you have there configured is 2 sub-interfaces with different IPs, not a _single_ interface with multiple IPs.

OpenSIPS is strictly looking for the IPs of "eth1" interface, returning only x.x.x.x .  According to the kernel, 172.24.6.27 and y.y.y.y belong to different interfaces (eth1:0 and eth1:1).

So. the OpenSIPS detection is good , imho :)

**Comment by stefancn** [comment]
Ok !

I’m a windows guy , so I’m not familiar to set multiple IP’s on same eth0 for. ex.  in Centos,  have only seen the virtual interface method.

We have to use different outgoing IP’s because we have multiple internet lines with diff. operators.

So I have to force opensips (via prefixnumbering, in carrierroute) to use correct sender IP  thru our firewall and core router.



Kind Regards

Stefan Carlsson
