### ISSUE TITLE
carrierroute,   did I completly misunderstod its function !!!! or is it a flaw in the code

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1052]
Hi !

The wish:

to select and rewrite the R-URI domain part. (eg.  the host)

The data:

Printing tree for carrier outbound (0)
Printing tree for domain 172.24.7.20
 0443565089: 100.000 %, 'sip.net1.com': ON, '0', '', '', 'To Net1'
  0443478520: 100.000 %, 'sip.net2.com: ON, '0', '', '', 'To Net2'

Calls come from (From URI):

04435650894@172.24.7.20    ===>  $fU => 04435650894   ,   $fd => 172.24.7.20

code ...
	if(!cr_route("outbound","$fd" , "$fU", "$fU", "from_uri", "$avp(host)")) {		
                    xlog("L_ERR", "cr_route Number not found for User:$fU  Domain:$fd");
                   } else 
                   {
                   xlog("Found Carrier:  $avp(host)"); 
                   }

	 
log respons:

Feb 11 21:38:55 siprouter /usr/sbin/opensips[12049]: ERROR:carrierroute:cr_do_route: desired routing domain doesn't exist, prefix 04435650894, carrier 0, domain 0
Feb 11 21:38:55 siprouter /usr/sbin/opensips[12049]: cr_route Number not found for User:04435650894 Domain:172.24.7.20

PLEASE HELP,    Two days, and still I don't understand why this doesn't work.  PLEASE HELP.

Compiled the "master" version, but no change.

**Comment by bogdan-iancu** [comment]
Hi @stefancn , the carrierroute module is not maintained for years. I would strongly advice you to use the Dynamic Routing module (drouting) : http://www.opensips.org/html/docs/modules/2.2.x/drouting.html .

Also, seep in mind that this tracker is intended to used for reporting crashes, bugs or misbehaviors of OpenSIPS. For usage questions, please consider to use the Users's mailing list :
  http://lists.opensips.org/cgi-bin/mailman/listinfo/users

**Comment by stefancn** [comment]
Sorry,   I'm new to git.  When you say "opensips" is it just the core engine or is it the modules as well.
( But I found a misbehave in carrierroute, fixed the code an now it is working. :-) )

**Comment by bogdan-iancu** [comment]
OpenSIPS is core and modules :). 
IF you have a fix, please make pull request or provide a patch file.
