### ISSUE TITLE
usrloc db_mode:3 no delete on unregister in 2.2

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1058]
I can register a user which then inserts into the usrloc database via db_http, updates also work correctly. However if the UA unregistered a delete does not happen.

When the user is unregistered, Opensips appears to do a GET/SELECT request to the database for the username of the user which is un-registering, but does not do anything else from there. (I would have expected a DELETE for the stored contact_id provided during the insert of that user into usrloc).

(Repeated register / un-register causes multiple user_location records which don't expire until my custom timer picks them up).

Opensips is aware of the contact_id and 
modparam("db_http", "cap_last_inserted_id", 1)
is set.

Another annoyance which may be related is that the server continuously performs deletes for the following criteria: expires="Thu Jan  1 00:00:00 1970" regularly.

I am not sure if an un-registered user should have its expire date set to the unix epoc which is later deleted by this period query as I cant find any other reason Opensips sets the expires to 1970.

Regards Jonathan

**Comment by ionutrazvanionita** [comment]
Hey @digipigeon, regarding the second issue can you make a capture of the delete query sent by opensips?

**Comment by digipigeon** [comment]
I will try and get a pcap for you, meanwhile here is the section called from the logging

Feb 22 02:18:02 ubuntu /usr/sbin/opensips[12532]: DBG:db_http:do_http_op: Called with db_op=2
Feb 22 02:18:02 ubuntu /usr/sbin/opensips[12532]: DBG:db_http:do_http_op: Sent:http://my-server:8080/opensips/location
Feb 22 02:18:02 ubuntu /usr/sbin/opensips[12532]: DBG:db_http:do_http_op: Posted:k=expires,expires&op=%3c,%21%3d&v=Wed%20Feb%2022%2002%3a18%3a03%202017%0a,Thu%20Jan%20%201%2000%3a00%3a00%201970%0a&query_type=delete

**Comment by ionutrazvanionita** [comment]
Thank you there's no need for that. There are two criteria after which a contact is removed: 1) it's expires is older than the current time and 2) it's expires is not 0 ( or  Thu Jan  1 00:00:00 1970  which is 0 as unix timestamp). The second criteria allows having contacts which never expire therefore are never removed from the database, so there's no issue in this. As concerns your first problem i'll dig a little more into it.

**Comment by ionutrazvanionita** [comment]
Regarding the first issue, have you tried setting **max_contact_delete** parameter to **1** in usrloc module? This should solve your problem.

**Comment by digipigeon** [comment]
I have not set this as in the documentation it states  _Relevant only in WRITE_THROUGH or WRITE_BACK schemes_ I am using mode 3, for DB Only. Also as the default was 10, I assumed that it would just consider 1 < 10 and delete it correctly.

However I will check this shortly and get back to you, Thank you.

**Comment by digipigeon** [comment]
Just tested this, unfortunately it didn't work, upon un-registration no delete request was sent, just a get request.

**Comment by sasmita11** [comment]
I am also facing the same issue in opensips-2.2.2 . While using db_mode: 3 ,the contacts not getting deleted while unregister .

This is working fine in opensips-1.11 . 

Please update me regarding this also .

**Comment by bogdan-iancu** [comment]
Hi all. There was recent fix (see a5f87c57de03f1e0fabba65a798a7c2cd1edecd6) related to how the contact IDs are generated in OpenSIPS. Be sure you use the latest trunk / 2.3 / 2.2 and give it a try.

**Comment by ionutrazvanionita** [comment]
@digipigeon  @sasmita11 That commit won't fix the problem. This patch along with max_contact_delete set to 1 should fix it. Can any of you please test it and if it works will push it and document it accordingly?

[usrloc.patch.txt](https://github.com/OpenSIPS/opensips/files/947649/usrloc.patch.txt)

**Comment by sasmita11** [comment]
Hi ,

    I was testing this patch . But it seems like wont solve the problem .
Applying the patch also the record not getting deleted from the DB in
db_mode: 3 .

        loadmodule "db_mysql.so"
#### USeR LOCation module
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "db_mode", 3)

modparam("usrloc", "db_url", "mysql://root:root@test.ser.xxx.com/opensips_2
")
modparam("usrloc", "max_contact_delete", 1)


Bellow is my urecord.c file . I have modified this file according to the
patch . Still it not deleting the record from db on un-register .
Please check the file and let me know if anything else needed .

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by ionutrazvanionita** [comment]
@sasmita11 any chance you can get a trace with the mysql query?

**Comment by ionutrazvanionita** [comment]
@sasmita11 @digipigeon we have tested this patch [0] on unregisters and it seems to solve the problem. I will close the issue. If you stiil have scenarios when users unregister and the contact is not deleted from DB please feel free to reopen it, but we strongly believe that this fixes the issue
[0] https://github.com/OpenSIPS/opensips/commit/0e9f1ab3911e684b8ba8e34c65f075d24a986540 maser
[1] https://github.com/OpenSIPS/opensips/commit/f114dd2918b4fb53b5858b06b7110211d221e5ee 2.3
[2] https://github.com/OpenSIPS/opensips/commit/0e83202dc1baaab1ab44a9e12dda63a6d7e2653d 2.2

**Comment by sasmita11** [comment]
Sure . I will try that once more . And will update the status .

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by sasmita11** [comment]
Its fixed for me also in opensips-2.2.2 with patch[2] . I think previously
I was doing some other changes .

Thank you for the update .

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by sasmita11** [comment]
I got a strange behavior  .

When I am connecting to remote DB , with db_mode:3 with this patch it working fine . the db entry getting deleted while unregistered instantly .

But if I am connected to the local database of the linux box with db_mode:3 then the entry not getting deleted instantly , its getting deleted after the register expire time . 

Can anybody check this . I think this should work similarly as its working for remote database  .
