### ISSUE TITLE
ACK propagated with wrong CSeq number associated with the second INVITE after Proxy Auth.

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1059]
Hi !

After a positive proxy-auth done with uac_auth() the ACK is returned with the corresponding CSeq from the INVITE, then the new INVITE is performed and the ACK that is coupled with this second INVITE has the same CSeq as the first one. 

Is that correct behavior ??

Take care you all :-)

**Comment by stefancn** [comment]
Sorry ,  sorry sorry,  looked at wrong interface , damn.

**Comment by stefancn** [comment]
Did a test that I incr. the CSeq numbering on incoming ACK before the t_relay(), now the second ACK has the correct CSeq  is it wise !!!!

**Comment by bogdan-iancu** [comment]
@stefancn, do you still have here any open issue to be reported ?

**Comment by bogdan-iancu** [comment]
I just made a test with a call via uac_auth(), with several on-hold, off-hold and the the cseq was properly incremented and handled automatically across the entire calls. If you have any updates on this, please re-open on create another ticket with the details.
