### ISSUE TITLE
Topology Hiding, Leg-A with Nat Traversal, Leg-B BYE 

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1063]
If the following 3 conditions are met the problem occurs
- Topology Hiding is enabled
- The Caller sends calls with internal IP addresses in the SIP headers (to a Public IP Opensips machine), which are correctly detected and re-written.
- The Callie hangs up the call.

The BYE message is sent to the incorrect (internal, pre-NAT re-written) IP address.

If Topology hiding is not enabled all packets are correctly re-written and are sent to the correct places.

I am using the Ubuntu package for opensips 2.2.2 (x86_64/linux)

**Comment by razvancrainea** [comment]
Can you check if you are calling fix_nated_contact() before create_dialog(), or the other way around?

**Comment by digipigeon** [comment]
I am calling fix_nated_contact() before create_dialog()

**Comment by razvancrainea** [comment]
Then I guess there is an async query between fix_nated_contact() and create_dialog()?
Can you move the fix_nated_contact() logic just above create_dialog()?

**Comment by digipigeon** [comment]
Just tested, This happens regardless of moving the fix_nated_contact() to just before the create dialog.

**Comment by razvancrainea** [comment]
Can you send me debug logs (in private if privacy is a concern).

**Comment by razvancrainea** [comment]
According to the logs you have sent me, the dialog is created at the very beginning of your script - by the `sip_trace` function. That's why the wrong contact is stored in the dailog. Calling `fix_nated_contact()` before creating the dialog (therefore before `sip_trace`) should fix this issue.

**Comment by digipigeon** [comment]
I believe this has solved the issue, however I will some more tests before confirming and closing.

**Comment by razvancrainea** [comment]
If there are no other issues, please don't forget to close the ticket :).

**Comment by digipigeon** [comment]
I can confirm that this is now stable. Thank you.
