### ISSUE TITLE
OpenSIPS crash on mysql re-connect

### ISSUE THREAD

**Issue by staskobzar** [OpenSIPS/opensips#1070]
Hello,

We had OpenSIPS crash with the following message in logs:

_**CRITICAL:presence:update_presentity: #012>>> pkg_free() on non-pkg ptr 0x7fc3b0e4e4c0 - aborting!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues**_

It seems that the problems started when OpenSIPS has received MI command "dr_reload" and following "too many mysql server reconnection failures". 

OpenSIPS version:
```
version: opensips 1.11.6-notls (x86_64/linux)
flags: STATS: On, USE_IPV6, USE_TCP, DISABLE_NAGLE, USE_MCAST, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 16:26:19 Jan 27 2016 with gcc 4.9.2
```

I have attached "bt full" output from core dump and logs with lots of mysql re-connect alerts.

Thank you for your help!
[gdb.txt](https://github.com/OpenSIPS/opensips/files/831635/gdb.txt)

[opensips-crash.log.txt](https://github.com/OpenSIPS/opensips/files/831638/opensips-crash.log.txt)

**Comment by razvancrainea** [comment]
This has already been reported in #854 and fixed in commit b9aa87360eecf1e77baea661b855eec4f5798f2f
Try to update to the latest 1.11 version to fix this.
