### ISSUE TITLE
HTTP async rest_client resume (ACK only?)

### ISSUE THREAD

**Issue by spacetourist** [OpenSIPS/opensips#1074]
Hi All,

I have stumbled on an issue when attempting to perform async HTTP using rest_client module.

Oddly this appears to occur only when I'm performing this during an ACK request.

Here is the error:

```
Mar 14 14:38:33 pci-fram-proxy1.x-onsecure.net /usr/sbin/opensips[3049]:
CRITICAL:rest_client:resume_async_http_req:
>>> failed to delete fd 15
It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
/usr/sbin/opensips[3058]: CRITICAL:core:receive_fd: EOF on 13

```

Here is the code:

```
    # External routing service - New call setup
    if (method == "INVITE") {
        xlog("L_INFO", "$rm: Dispatch to REST client\n");
        async(rest_get("http://puppet:50000/route?$var(url_params_enc)", "$avp(response_body)"), ASYNC_INVITE_RESUME);
    }

     External routing service - Call answered
    if (method == "ACK") {
        xlog("L_INFO", "$rm: Dispatch to REST client\n");
        async(rest_get("http://puppet:50000/start?$var(url_params_enc)", "$avp(response_body)"), ASYNC_OTHER_RESUME);
    }

    # External routing service - Existing call teardown
    if (method == "BYE") {
        xlog("L_INFO", "$rm: Dispatch to REST client\n");
        async(rest_get("http://puppet:50000/end?$var(url_params_enc)", "$avp(response_body)"), ASYNC_OTHER_RESUME);
    }
```

Commenting out the middle block removes the errors. 

As this isn't an urgent requirement for my current project I'll just be removing it for now but will follow this issue in case a cause/resolution is determined.

Running on Centos 7, opensips-2.2.3-1.el7.x86_64, opensips-rest_client-2.2.3-1.el7.x86_64

Hope that's helpful, let me know if any questions.

Callum

**Comment by spacetourist** [comment]
In addition to the above I have discovered that the code is successful when performing the ACK REST call without async() - a very workable interim solution!

**Comment by liviuchircu** [comment]
Although we no longer need to keep track of transfers thanks to [this](https://github.com/OpenSIPS/opensips/commit/ed8984c54320a6712eb6469de2b42ebef4420b47) patch, I left the code there, just to catch any strange behavior, such as exactly the one you ran into. You may try out [this fix](https://gist.github.com/liviuchircu/1e3cf5323e3100a09d06201da4594e97), which likely avoid the `abort()` trap that I left there, and restore your async ACK processing.

However, even if the patch works, before closing this issue I will need to dig into libcurl a bit, and fully understand how `curl_multi_fdset()` works with multiple "multi" handles - maybe it's just not compatible with the async interface after all...
