### ISSUE TITLE
resolve.c - check_ip_address function incorrectly returns 0 when one IP is substring of another

### ISSUE THREAD

**Issue by vkuzmenok** [OpenSIPS/opensips#1077]
As a result of issue in check_ip_address function, received attribute is not added to the Via header for 
combinations of IPs like below
Src IP is 192.168.1.121
IP in Via1 is 192.168.1.12

Problematic code area is

`if (strncmp(name->s, s, name->len)==0)
                                                                return 0;`
The easiest fix would be to check the length of s and name first and proceed to the content check if length is equal. The other option would be to use strcmp function

**Comment by bogdan-iancu** [comment]
@vkuzmenok, could you point the file and line where the above mention code resides ? Thank you

**Comment by vkuzmenok** [comment]
[https://github.com/OpenSIPS/opensips/blob/eae2985abd62d2ae8a6138519cc3634d7bd022ce/resolve.c#L636](https://github.com/OpenSIPS/opensips/blob/eae2985abd62d2ae8a6138519cc3634d7bd022ce/resolve.c#L636)

**Comment by bogdan-iancu** [comment]
and the correct check should be one similar to https://github.com/OpenSIPS/opensips/blob/eae2985abd62d2ae8a6138519cc3634d7bd022ce/resolve.c#L626 ?

**Comment by vkuzmenok** [comment]
Yes

**Comment by bogdan-iancu** [comment]
@vkuzmenok , could you please test and confirm the above fix. If everything is ok, I will do a backport to the 2.x and 1.11 branches too.

Thanks, Bogdan

**Comment by bogdan-iancu** [comment]
keeping it open until the backports are done

**Comment by vkuzmenok** [comment]
@bogdan-iancu, From code perspective fix looks OK. We still use 1.11 version. Is it possible to get a 1.11 branch build to test?

**Comment by bogdan-iancu** [comment]
Backport is done, all the way to 1.11 branch.

**Comment by vkuzmenok** [comment]
@bogdan-iancu, did you also ported the dead code removal to the all branches?

**Comment by bogdan-iancu** [comment]
yes, did so
