### ISSUE TITLE
sipcapture: compiler warning

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#1081]
The warning:
````
Compiling sipcapture.c
sipcapture.c: In function 'get_hep_chunk':
sipcapture.c:1531: warning: comparison is always false due to limited range of data type
````
The test condition (h3->hg.proto_t.data < 0) is always false and should be removed.

**Comment by ionutrazvanionita** [comment]
It was fixed in 2.3 but not cherry picked to 2.2. https://github.com/OpenSIPS/opensips/commit/c9ec3ae20ff1875b9943c1879e503bcb40377a0a
