### ISSUE TITLE
Opensips 2.3.0-beta-1 dialog module in cluster standby node crashing

### ISSUE THREAD

**Issue by tanelvakker** [OpenSIPS/opensips#1084]
I have opensips 2.3.0-beta-1 on debian jessie, installed from opensips deb mirror.
I have configured 2 nodes in cluster doing topology hiding and load balancing.
When I send a call to active node, the second node crashes. 2 processes remain working and the rest will come back automatically in 1 minute after crash.

The dialog database is currently using dbtext and is not shared between the nodes

Here is the bt from core:
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
33	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt full
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:33
No locals.
#1  0x00007f14bdfa9408 in dlg_update_cseq () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
No symbol table info available.
#2  0x00007f14bdfc6591 in dlg_replicated_update () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
No symbol table info available.
#3  0x00007f14bdfc8af0 in receive_repl_packets () from /usr/lib/x86_64-linux-gnu/opensips/modules/dialog.so
No symbol table info available.
#4  0x00007f14be1f6c71 in ?? () from /usr/lib/x86_64-linux-gnu/opensips/modules/clusterer.so
No symbol table info available.
#5  0x000000000042849a in call_callbacks ()
No symbol table info available.
#6  0x00007f14bd924d0c in ?? () from /usr/lib/x86_64-linux-gnu/opensips/modules/proto_bin.so
No symbol table info available.
#7  0x000000000052af0a in ?? ()
No symbol table info available.
#8  0x000000000052e2c8 in tcp_worker_proc_loop ()
No symbol table info available.
#9  0x00000000005370b8 in tcp_start_processes ()
No symbol table info available.
#10 0x000000000041c821 in main ()
No symbol table info available.

These are the last debug log lines:
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:core:bin_pop_str: Popped: 'mVoRgV8hMmtdWDYQ3POtO6SQAAaWjopC' [32]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:core:bin_pop_str: Popped: 'hkK0rsN5rsyKrNOkL6JyF-dpvUPJ2ON6' [32]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:core:bin_pop_str: Popped: '00db8ff40e12e711933452f2be23d136' [32]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:core:bin_pop_str: Popped: 'sip:tanel@192.168.88.4' [22]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:core:bin_pop_str: Popped: 'sip:tanel@192.168.88.4' [22]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:dialog:dlg_replicated_update: replicated update for ['mVoRgV8hMmtdWDYQ3POtO6SQAAaWjopC' 'hkK0rsN5rsyKrNOkL6JyF-dpvUPJ2ON6' '00db8ff40e12e711933452f2be23d136' 'sip:tanel@192.168.88.4' 'sip:tanel@192.168.88.4']
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:dialog:get_dlg: input ci=<mVoRgV8hMmtdWDYQ3POtO6SQAAaWjopC>(32), tt=<hkK0rsN5rsyKrNOkL6JyF-dpvUPJ2ON6>(32), ft=<00db8ff40e12e711933452f2be23d136>(32)
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:dialog:get_dlg: ref dlg 0x7f14c1e9b8d8 with 1 -> 4
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9467]: DBG:dialog:get_dlg: dialog callid='mVoRgV8hMmtdWDYQ3POtO6SQAAaWjopC' found#012 on entry 519, dir=1
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:io_wait_loop_epoll: [TCP_main] EPOLLHUP on IN ->connection closed by the remote peer!
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:handle_worker: dead child 9, pid 9467 (shutting down?)
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:io_watch_del: [TCP_main] io_watch_del op on index 10 36 (0x812500, 36, 10, 0x0,0x1) fd_no=27 called
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:io_wait_loop_epoll: [TCP_main] EPOLLHUP on IN ->connection closed by the remote peer!
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:handle_tcp_worker: dead tcp worker 0 (pid 9467) (shutting down?)
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9476]: DBG:core:io_watch_del: [TCP_main] io_watch_del op on index 18 32 (0x812500, 32, 18, 0x0,0x1) fd_no=26 called
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9458]: DBG:core:handle_sigs: status = 139

messages log file last lines:
Mar 28 13:28:12 opensips1 /usr/sbin/opensips[9467]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Mar 28 13:28:12 opensips1 /usr/sbin/opensips[9467]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 40
Mar 28 13:28:13 opensips1 /usr/sbin/opensips[9467]: INFO:clusterer:receive_msg_known_source: Node: 2 is up
Mar 28 13:28:36 opensips1 kernel: [76068.714124] opensips[9467]: segfault at 1 ip 00007f14c5fb2040 sp 00007ffc5d1188e8 error 4 in libc-2.19.so[7f14c5f20000+1a1000]
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9458]: INFO:core:handle_sigs: child process 9467 exited by a signal 11
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9458]: INFO:core:handle_sigs: core was generated
Mar 28 13:28:36 opensips1 /usr/sbin/opensips[9458]: INFO:core:handle_sigs: terminating due to SIGCHLD

**Comment by liviuchircu** [comment]
I dedicated a couple of hours to replicate this crash today, but without much success. More attempts tomorrow - will probably ask for more info (config file, traces, etc.) if I won't be able to trigger it.

**Comment by tanelvakker** [comment]
[dbtext.tar.gz](https://github.com/OpenSIPS/opensips/files/884731/dbtext.tar.gz)

[opensips.cfg.tar.gz](https://github.com/OpenSIPS/opensips/files/884735/opensips.cfg.tar.gz)
attaching dbtext files and configurations

**Comment by liviuchircu** [comment]
@tanelvakker please re-open if issues persist. Using the config file info, I managed to reproduce the issue, then got it fixed on my setup.
