### ISSUE TITLE
main.c: Would it be possible to print also the line number of the opensips.cfg config file?

### ISSUE THREAD

**Issue by gerontec** [OpenSIPS/opensips#1090]
Hello,
in opensips-2.2/main.c we can see the following error handling:
########################################################################
if ((yyparse()!=0)||(cfg_errors)){
                LM_ERR("bad config file (%d errors)\n", cfg_errors);
                goto error00;
        }
########################################################################
That generates the following error message in my syslog:
opensips[14888]: Apr  3 10:40:24 [14888] ERROR:core:main: bad config file (6 errors)
Would it be possible to print also the line number of the opensips.cfg config file?

Best regards
Georg

**Comment by liviuchircu** [comment]
If you take a closer look in `cfg.y`, the `yyerror()` function required by bison is defined as follows, containing enough information for each relevant error:

```
static void yyerror(char* s)
{
    LM_CRIT("parse error in config file %s, line %d, column %d-%d: %s\n",
            get_cfg_file_name, line, startcolumn, column, s);
    cfg_errors++;
}
```

**Comment by liviuchircu** [comment]
I now realize I may have misinterpreted your problem. If your syslog **only** contains the error line you posted above, then this is definitely an issue. If so, please re-open this issue and pastebin your cfg file here, or send it to liviu@opensips.org if privacy is a concern.

**Comment by gerontec** [comment]
Thanks liviu,
what could cause that static void yyerror(char* s)
{
    LM_CRIT("parse error in config file %s, line %d, column %d-%d: %s\n",
            get_cfg_file_name, line, startcolumn, column, s);
    cfg_errors++;
}
does not work as expected?
Here is my config generated by /usr/sbin/opsconfig:


/opensips-2.2# cat /etc/opensips/opensips.cfg
####### Global Parameters #########

log_level=8
log_stderror=yes
log_facility=LOG_LOCAL0

children=4

/* uncomment the following lines to enable debugging */
#debug_mode=yes

/* uncomment the next line to enable the auto temporary blacklisting of
   not available destinations (default disabled) */
#disable_dns_blacklist=no

/* uncomment the next line to enable IPv6 lookup after IPv4 dns
   lookup failures (default disabled) */
#dns_try_ipv6=yes

/* comment the next line to enable the auto discovery of local aliases
   based on revers DNS on IPs */
auto_aliases=no


listen=udp:127.0.0.1:5060   # CUSTOMIZE ME

listen=tcp:127.0.0.1:5060   # CUSTOMIZE ME
listen=tls:127.0.0.1:5061   # CUSTOMIZE ME



####### Modules Section ########

#set module path
mpath="/usr/lib/x86_64-linux-gnu/opensips/modules/"

#### HTTPD module
loadmodule "httpd.so"
modparam("httpd", "port", 8888)

#### SIGNALING module
loadmodule "signaling.so"

#### StateLess module
loadmodule "sl.so"

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
/* do not append from tag to the RR (no need for this script) */
modparam("rr", "append_fromtag", 0)

#### MAX ForWarD module
loadmodule "maxfwd.so"

#### SIP MSG OPerations module
loadmodule "sipmsgops.so"

#### FIFO Management Interface
loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)

#### URI module
loadmodule "uri.so"
modparam("uri", "use_uri_table", 0)

#### MYSQL module
loadmodule "db_mysql.so"

#### AVPOPS module
loadmodule "avpops.so"

####  DYNAMIC ROUTING module
loadmodule "drouting.so"
modparam("drouting", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME

####  PERMISSIONS module
loadmodule "permissions.so"
modparam("permissions", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME

#### ACCounting module
loadmodule "acc.so"
/* what special events should be accounted ? */
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
/* by default we do not adjust the direct of the sequential requests.
   if you enable this parameter, be sure the enable "append_fromtag"
   in "rr" module */
modparam("acc", "detect_direction", 0)
modparam("acc", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME


#### DIALOG module
loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 21600)  # 6 hours timeout
modparam("dialog", "db_mode", 2)
modparam("dialog", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME



####  DIALPLAN module
loadmodule "dialplan.so"
modparam("dialplan", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME


####  MI_HTTP module
loadmodule "mi_http.so"


loadmodule "proto_udp.so"

loadmodule "proto_tcp.so"
loadmodule "proto_tls.so"
modparam("proto_tls","verify_cert", "1")
modparam("proto_tls","require_cert", "0")
modparam("proto_tls","tls_method", "TLSv1")
modparam("proto_tls","certificate", "/usr/local/etc/opensips/tls/user/user-cert.pem")
modparam("proto_tls","private_key", "/usr/local/etc/opensips/tls/user/user-privkey.pem")
modparam("proto_tls","ca_list", "/usr/local/etc/opensips/tls/user/user-calist.pem")



####### Routing Logic ########

# main request routing logic

route{

        if (!mf_process_maxfwd_header("10")) {
                sl_send_reply("483","Too Many Hops");
                exit;
        }

        if ( check_source_address("1","$avp(trunk_attrs)") ) {
                # request comes from trunks
                setflag(IS_TRUNK);
        } else if ( is_from_gw() ) {
                # request comes from GWs
        } else {
                send_reply("403","Forbidden");
                exit;
        }

        if (has_totag()) {
                # sequential request withing a dialog should
                # take the path determined by record-routing
                if (loose_route()) {

                        # validate the sequential request against dialog
                        if ( $DLG_status!=NULL && !validate_dialog() ) {
                                xlog("In-Dialog $rm from $si (callid=$ci) is not valid according to dialog\n");
                                ## exit;
                        }

                        if (is_method("BYE")) {
                                # do accounting even if the transaction fails
                                do_accounting("db","failed");

                        } else if (is_method("INVITE")) {
                                # even if in most of the cases is useless, do RR for
                                # re-INVITEs alos, as some buggy clients do change route set
                                # during the dialog.
                                record_route();
                        }

                        # route it out to whatever destination was set by loose_route()
                        # in $du (destination URI).
                        route(RELAY);
                } else {
                        if ( is_method("ACK") ) {
                                if ( t_check_trans() ) {
                                        # non loose-route, but stateful ACK; must be an ACK after
                                        # a 487 or e.g. 404 from upstream server
                                        t_relay();
                                        exit;
                                } else {
                                        # ACK without matching transaction ->
                                        # ignore and discard
                                        exit;
                                }
                        }
                        sl_send_reply("404","Not here");
                }
                exit;
        }

        #### INITIAL REQUESTS

        if ( !isflagset(IS_TRUNK) ) {
                ## accept new calls only from trunks
                send_reply("403","Not from trunk");
                exit;
        }

        # CANCEL processing
        if (is_method("CANCEL")) {
                if (t_check_trans())
                        t_relay();
                exit;
        } else if (!is_method("INVITE")) {
                send_reply("405","Method Not Allowed");
                exit;
        }

        if ($rU==NULL) {
                # request with no Username in RURI
                sl_send_reply("484","Address Incomplete");
                exit;
        }

        t_check_trans();

        # preloaded route checking
        if (loose_route()) {
                xlog("L_ERR",
                "Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]");
                if (!is_method("ACK"))
                        sl_send_reply("403","Preload Route denied");
                exit;
        }

        # record routing
        record_route();

        do_accounting("db");



        # create dialog with timeout
        if ( !create_dialog("B") ) {
                send_reply("500","Internal Server Error");
                exit;
        }





        # apply transformations from dialplan table
        dp_translate("0","$rU/$rU");

        # route calls based on prefix
        if ( !do_routing("1") ) {
                send_reply("404","No Route found");
                exit;
        }

        t_on_failure("GW_FAILOVER");

        route(RELAY);
}


route[RELAY] {
        if (!t_relay()) {
                sl_reply_error();
        };
        exit;
}


failure_route[GW_FAILOVER] {
        if (t_was_cancelled()) {
                exit;
        }

        # detect failure and redirect to next available GW
        if (t_check_status("(408)|([56][0-9][0-9])")) {
                xlog("Failed GW $rd detected \n");

                if ( use_next_gw() ) {
                        t_on_failure("GW_FAILOVER");
                        t_relay();
                        exit;
                }

                send_reply("500","All GW are down");
        }
}


local_route {
        if (is_method("BYE") && $DLG_dir=="UPSTREAM") {

                acc_db_request("200 Dialog Timeout", "acc");

        }
}

**Comment by gerontec** [comment]
Thanks, Ticket closed was the right desicion!
my fault , it works as expected!
