### ISSUE TITLE
Opensips 2.3 crash, seems to be in event_routing module

### ISSUE THREAD

**Issue by Vahan-accontech** [OpenSIPS/opensips#1093]
For push notifications, I have added the forking call logic in the config file, the peace of config code was taken from here:
https://blog.opensips.org/2017/03/10/advanced-sip-scenarios-with-event-based-routing/

The crash happens very often. You just need to make a call and at the moment of ringing register the called user.

Peace of the Log:

Apr 04 16:38:13 push-dev /usr/local/sbin/opensips[16615]: INFO:core:probe_max_sock_buff: using snd buffer of 512 kb
Apr 04 16:38:13 push-dev /usr/local/sbin/opensips[16615]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 67
Apr 04 16:38:14 push-dev kernel: opensips[16607]: segfault at 30 ip 00007fc54bb9a0b3 sp 00007fff7291c750 error 4 in event_routing.so[7fc54bb93000+b000]
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16615]: CRITICAL:core:receive_fd: EOF on 37
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16598]: INFO:core:handle_sigs: child process 16607 exited by a signal 11
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16598]: INFO:core:handle_sigs: core was generated
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16598]: INFO:core:handle_sigs: terminating due to SIGCHLD
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16614]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16613]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16612]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16611]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16610]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16609]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16608]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16606]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16605]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16604]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16603]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16602]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16599]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16601]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16615]: INFO:core:sig_usr: signal 15 received
Apr 04 16:38:14 push-dev /usr/local/sbin/opensips[16600]: INFO:core:sig_usr: signal 15 received

Any help would be grately appreciated.

**Comment by bogdan-iancu** [comment]
@Vahan-accontech , are you able to extract and post here the backtrace from the core file ?

**Comment by Vahan-accontech** [comment]
@bogdan-iancu , thank you for your prompt response, here is the core dump
[core.opensips.sig11.20257.gz](https://github.com/OpenSIPS/opensips/files/895893/core.opensips.sig11.20257.gz)

**Comment by bogdan-iancu** [comment]
@Vahan-accontech , thank but I don not need the actual corefile, but the backtrace extracted from it (using gdb). See : http://www.opensips.org/Documentation/TroubleShooting-Crash, the "Extracting a back trace from the core file" section.

**Comment by Vahan-accontech** [comment]
@bogdan-iancu , o... sorry about that, here it is

[gdb.core.opensips.sig11.23379 .txt](https://github.com/OpenSIPS/opensips/files/896134/gdb.core.opensips.sig11.23379.txt)

**Comment by bogdan-iancu** [comment]
@Vahan-accontech , please apply this patch [ebr_fix.patch.txt](https://github.com/OpenSIPS/opensips/files/899816/ebr_fix.patch.txt) , recompile and see again.

**Comment by nikbyte** [comment]
Bogdan, with patch it still crashes on the same place as before patch.

Variables from the first step of backtrace:
\# p *ev
$8 = {event_name = {s = 0x7f8e75590c90 "E_UL_CONTACT_INSERT", len = 19}, event_id = 6, lock = 1, subs = 0x0,
  next = 0x0}

\# p sub_next
$10 = (ebr_subscription *) 0x0

**Comment by nikbyte** [comment]
It happens with the following scenario:

1. User 1 is registered
2. User 2 calls to user 1
3. During ringing register additional user 1
4. User 1 receives forked INVITE after registration
5. Unregister user 1
6. Re-register user 1 and you have crash

**Comment by Vahan-accontech** [comment]
@bogdan-iancu , applied your patch, the issue is still reproducible.
here is the dump
[core.opensips.sig11.5141.txt](https://github.com/OpenSIPS/opensips/files/900786/core.opensips.sig11.5141.txt)


And again in the logs:
Apr  5 20:13:21 push-dev kernel: [697896.624952] opensips[5141]: segfault at 30 ip 00007ff43f65f0b3 sp 00007fff778f3ae0 error 4 in event_routing.so[7ff43f658000+b000]
Apr  5 20:13:21 push-dev /usr/local/sbin/opensips[5159]: CRITICAL:core:receive_fd: EOF on 17
Apr  5 20:13:22 push-dev /usr/local/sbin/opensips[5137]: INFO:core:handle_sigs: child process 5141 exited by a signal 11
Apr  5 20:13:22 push-dev /usr/local/sbin/opensips[5137]: INFO:core:handle_sigs: core was generated
Apr  5 20:13:22 push-dev /usr/local/sbin/opensips[5137]: INFO:core:handle_sigs: terminating due to SIGCHLD

**Comment by bogdan-iancu** [comment]
Thank you @Vahan-accontech - it is really strange as what the backtrace shows is weird. Could you please print in GDB the ev->subs value ?

Also if you could describe a bit more in details the scenario leading to this crash....I might be able to reproduce it.

**Comment by bogdan-iancu** [comment]
I managed to reproduce the crash when there is only one subscription per event type and it is found as expired at the event raising time......working on a fix

**Comment by Vahan-accontech** [comment]
@bogdan-iancu, thank you.
The scenario I use to reproduce the crash is:
1. user1 calls user2 while user2 is offline (in the config script SIP 404 "Not Found" reply part is commented to give time for user2 to register and receive the call);
2. user2 registers and receives the forked call;
3. (a) or (b) or (c):
    3a. another device with user2 credentials registers - crash! or
    3b. call is being closed, user2 (from the same device) unregisters and registers again - crash! or
    3c. even without closing the current call, user2 (from the same device) unregisters and registers again - crash!

**Comment by bogdan-iancu** [comment]
@Vahan-accontech , @nikbyte , thanks for your report and support - the fix is available now on GIT (head and 2.3 branches).

**Comment by Vahan-accontech** [comment]
@bogdan-iancu , thank you very much, the crash is resolved!!! great support!
