### ISSUE TITLE
ON_REPLY, ON_BRANCH, ON_FAIL for branch forked by event

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1096]
Hello!

If we call t_wait_for_new_branches() when we have no one registered contact, how to let ON_REPLY, ON_BRANCH and ON_FAIL works for branches created by t_inject_branches ?
If I call t_on_reply(), t_on_failure(), t_on_branch() before t_wait_for_new_branches(), I have crashed opensips. If I call t_on_reply(), t_on_failure(), t_on_branch() right before t_inject_branches(), I cannot get them worked. I really need it because I enable rtpengine in ON_BRANCH route and I save source IP addresses for NAT processing in ON_REPLY route.

**Comment by trevorgfrancis** [comment]
@bogdan-iancu any chance this can be escalated, as it should be blocking for 2.3 release.

**Comment by bogdan-iancu** [comment]
t_wait_for_new_branches() requires an existing transaction, so you have to do a t_newtran() in advance. Now, when you do t_on_failure() ? before or after the the t_newtran() ?
I tried putting a t_on_failure() before t_newtran() or after it (still before t_wait_for_new_branches()) and it worked (the failure route was triggered).
Of course, I tested your scenario with no contact in place at the call time.

**Comment by nikbyte** [comment]
Bogdan, thank you for your reply. I did many changes in my configuration these days and now I cannot reproduce exactly why I didn't have ON_REPLY, ON_BRANCH, ON_FAIL few days ago.
Now I have all of them. And of course I used t_newtran() because without it I don't have injected branch. Let it be problems in my configuration, sorry for your time and thank you again.

But now I expected crashes. What I have for now.

First of all, is it okay to have these errors in log when branch is injecting?
> ERROR:core:parse_from_header: bad msg or missing FROM header
> ERROR:core:pv_get_from_attr: cannot parse From header
> ERROR:core:pv_get_callid: cannot parse Call-Id header
> ERROR:core:pv_get_cseq: cannot parse CSEQ header

I see them when notify_on_event() triggers event E_UL_CONTACT_INSERT and before it executes route.

Second thing is crashes. I tested them more. They occur in ON_BRANCH route only when I have rtpengine_offer() there. I checked core dumps and the problem is here:

> #0  0x00000000004251c9 in context_get_ptr (type=type@entry=CONTEXT_GLOBAL, ctx=0x0, pos=2) at context.c:235
>         __FUNCTION__ = "context_get_ptr"
> #1  0x00007f974ce28f0e in rtpe_function_call (bencbuf=bencbuf@entry=0x7ffdb2fcaa50, msg=<optimized out>,     op=<optimized out>, flags_str=<optimized out>, body_out=<optimized out>, spvar=<optimized out>)     at rtpengine.c:1390

**Comment by bogdan-iancu** [comment]
@nikbyte , let's have this ticket close - please open a new one in regards to the crash in branch route (as this is a completely different topic)

**Comment by nikbyte** [comment]
Okay, thank you.
