### ISSUE TITLE
Record-Route header... Again.

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1097]
Hi Bogdan,

I'm trying to add RR to injected by event branches and have problems.

1. If I have modparam("tm", "auto_100trying", 0), the RR header is not working.
2. If enable back auto_100trying, only way I can add RR to injected branch is:
record_route();
create_dialog();
t_wait_for_new_branches();

If I insert t_newtran() in any place before or between these commands, I have no RR header.

Also I have one server which is crashing on 180 or 200 (randomly) with strange way.
Crash is on build_res_buf_from_sip_req() and it crashes when tries to send "Server error occurred (1/SL)" reply (SL???). Cannot understand why and why another server works at the close configuration.

[gdb.txt](https://github.com/OpenSIPS/opensips/files/907879/gdb.txt)

**Comment by bogdan-iancu** [comment]
@nikbyte , the above commit will prevent the crash you reported (off ticket, via email) on using the record_route() from the notification route.
Still, I'm looking into the bracktrace you posted here and in the RR insertion - I will try to reproduce your cases. BTW, I suppose you use my previous fix 6455ccba84539d91d7575161989bf9ef41c392e9 (which is only in trunk for the moment)

**Comment by bogdan-iancu** [comment]
just looking at the BT you attached - do you use sl_reply_error() from the notification route ??

**Comment by nikbyte** [comment]
> just looking at the BT you attached - do you use sl_reply_error() from the notification route ??

No. I don't have it there. It's strange for me also. Maybe some internal function call it?

Sorry, my bad to insert two problems in one ticket. Let this ticket will be about auto_100trying only. I'll check version with latest commit and open separate ticket if I'll still have any crashes. Thank you.

**Comment by nikbyte** [comment]
Closing this ticket because needs additional testing. I have unstable working of branches injecting by event. It may works well, then it doesn't work. After restart it works again. I cannot understand what it depends on. Will open new separate issue as soon as I will debug and understand it. Thank you.

**Comment by bogdan-iancu** [comment]
OK, take your time. In teh mean while I will backport to 2.3 the 2 fixes I did.
