### ISSUE TITLE
Crashes on ON_BRANCH when using branch injecting by event

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1100]
Hello!

When I use injected by event branch I have crashes.

First of all, is it okay to have these errors in log when branch is injecting?
> ERROR:core:parse_from_header: bad msg or missing FROM header
> ERROR:core:pv_get_from_attr: cannot parse From header
> ERROR:core:pv_get_callid: cannot parse Call-Id header
> ERROR:core:pv_get_cseq: cannot parse CSEQ header

I see them when notify_on_event() triggers event E_UL_CONTACT_INSERT and before it executes route.

Second thing is crashes. I tested them more. They occur in ON_BRANCH route only when I have rtpengine_offer() there. I checked core dumps and the problem is here:

> #0  0x00000000004251c9 in context_get_ptr (type=type@entry=CONTEXT_GLOBAL, ctx=0x0, pos=2) at context.c:235
>         __FUNCTION__ = "context_get_ptr"
> #1  0x00007f974ce28f0e in rtpe_function_call (bencbuf=bencbuf@entry=0x7ffdb2fcaa50, msg=<optimized out>,     op=<optimized out>, flags_str=<optimized out>, body_out=<optimized out>, spvar=<optimized out>)     at rtpengine.c:1390

**Comment by bogdan-iancu** [comment]
@nikbyte , please see the above commit - this will take care of the crash in branch route via the inject branch stuff. Let me know if it does the trick for you.

**Comment by nikbyte** [comment]
Bogdan, now it works well. Thank you very much.
