### ISSUE TITLE
tls_mgm ERROR

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1103]
Hello,

When try to use tls_mgm module receive follow errors:
 
Apr  9 22:13:28 dev /usr/local/sbin/opensips[31161]: INFO:tls_mgm:mod_init: initializing TLS protocol
Apr  9 22:13:28 dev /usr/local/sbin/opensips[31161]: WARNING:tls_mgm:mod_init: disabling compression due ZLIB problems
Apr  9 22:13:29 dev /usr/local/sbin/opensips[31161]: INFO:tls_mgm:check_for_krb: KRB5 cipher KRB5-IDEA-CBC-SHA found
Apr  9 22:13:29 dev /usr/local/sbin/opensips[31161]: ERROR:tls_mgm:mod_init: compiled agaist an openssl with kerberos, but run with one with kerberos
Apr  9 22:13:29 dev /usr/local/sbin/opensips[31161]: ERROR:core:init_mod: failed to initialize module tls_mgm
Apr  9 22:13:29 dev /usr/local/sbin/opensips[31161]: ERROR:core:main: error while initializing modules

Opensips: 2.2.3 (latest from git)
OS: CentOS 7.2
SSL modules:
openssl-1.0.1e-60.el7_3.1.x86_64
openssl-libs-1.0.1e-60.el7_3.1.x86_64
mod_ssl-2.4.6-45.el7.centos.x86_64
openssl-devel-1.0.1e-60.el7_3.1.x86_64

**Comment by goup2010** [comment]
I discovered the problem. 
I have found OpenSSL from RPM and OpenSSL from compilation.

Please close the issue.

**Comment by razvancrainea** [comment]
So you were using different libraries one installed from RPM and one locally compiled?
