### ISSUE TITLE
error while using proto_hep module in openisps-2.2

### ISSUE THREAD

**Issue by sasmita11** [OpenSIPS/opensips#1104]
Bellow is the error I am getting . I had set the hep module like below in my config file .

```
loadmodule "proto_hep.so"
loadmodule "siptrace.so"
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_id",
"[tid]uri=hep:x.x.x.x:9060;") 

$var(trace_id) = "tid";
$var(user) = "osip_user@opensips.org";

                if (is_method("INVITE")) {
----------------------------
sip_trace("$var(trace_id)", "d", "$var(user)");
----------------------
                }
```
I am getting Bellow error . Please have a look and suggest if I am doing somehing wrong .

```
CRITICAL:siptrace:msg_send: #012>>> using proto 9 which is not init!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
 ERROR:siptrace:trace_send_hep_duplicate: cannot send duplicate message
 ERROR:siptrace:save_siptrace: Failed to duplicate with hep to <:>
 CRITICAL:siptrace:msg_send: #012>>> using proto 9 which is not init!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
 ERROR:siptrace:trace_send_hep_duplicate: cannot send duplicate message
 ERROR:siptrace:save_siptrace: Failed to duplicate with hep to <:>
```

**Comment by bogdan-iancu** [comment]
@sasmita11 this is not a bug (even if the log says so), but a configuration error. You forget to define a HEP listener in your .cfg:
`listen = hep_tcp:z.z.z.z:8632`

**Comment by sasmita11** [comment]
I did that and now I am getting some different error .


 ERROR:siptrace:sip_trace_w: Trace id <<null>> not defined!

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by ionutrazvanionita** [comment]
Can you print $var(trace_id) before  calling sip_trace? It seems the var is null/not defined.

**Comment by sasmita11** [comment]
Below is the format my config file look like . Am I missing something to
declare the trace_id ??



loadmodule "db_mysql.so"
loadmodule "siptrace.so"

modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_id",
"[tid]
uri=mysql://root:root@localhost/opensips;
table=sip_trace;")



route{

$var(trace_id) = "tid";

xlog(" what is the value of trace_id $var(trace_id) \n");    // this is
printing tid . Nothing else .
$var(user) = "osip_user@opensips.org";

   ----------------------------------------

        if (is_method("REGISTER")) {


         sip_trace("$var(tid)", "t", "$var(user)");

                # indicate that the client supports DTLS
                # so we know when he is called
                if (isflagset(SRC_WS))
                        setbflag(DST_WS);

                fix_nated_register();
                if (!save("location"))
                        sl_reply_error();

                exit;
        }
------------------------------------

}

Error :

what is the value of trace_id tid   // log message what I am printing .
ERROR:siptrace:sip_trace_w: Trace id <<null>> not defined!


Please help me if I am doing something wrong .


*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by sasmita11** [comment]
I make it work . Thanks .

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by ionutrazvanionita** [comment]
Hi @sasmita11, what was the problem? Is it a bug in siptrace?

**Comment by sasmita11** [comment]
Not bug , Its miss-configuration  . trace_id was null thats why it was not
doing anything . And the format I was declaring was wrong . So I changed
that and it works fine .


Thank you
Sasmita


*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*
