### ISSUE TITLE
[rtpproxy] hardcoded mandatory default setID 0

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#1105]
The module has hardcoded, as default set, the serID 0 ; at mod init, there is a lookup on setID 0 in order to translate the ID to the actual list.
This makes mandatory the definition of the group 0

If you use in your script (defined and invoked) like setID 1 and setID 2, you will get this phony error at startup:
>  DBG:rtpproxy:select_rtpp_set: Looking for set_id 0
>  ERROR:rtpproxy:select_rtpp_set:  script error-invalid id_set to be selected

So, either we can either configure the ID for the default set (as mod param), eitherautodetect it (as the first defined set), either.....(other great ideas)

**Comment by razvancrainea** [comment]
Just added in commit c8e5a4129 the possibility to specify a default set.
Although this is not the "nicest" solution, is the "safest" one at this moment. For the later versions we can implement autodetection if no other issues come up.
In the meantime I will decrease the priority and move it to 2.4 milestone.

**Comment by bogdan-iancu** [comment]
ok, makes sense. Thanks for the fix.

**Comment by razvancrainea** [comment]
In the meantime, this has also been converted to a Warning, thus I don't think the report is valid any more. Closing it.
