### ISSUE TITLE
Problem in call with wss connection .

### ISSUE THREAD

**Issue by sasmita11** [OpenSIPS/opensips#1106]
I am using opensips-2.2.2 version .
I am calling from a soft phone to sipml5 . When I am using db_mode : 2 the call is working fine .
But in case of db_mode 3 , I am getting the following error .
```
 ERROR:core:tcp_connect_blocking: timeout 99349 ms elapsed from 100000 s
 ERROR:proto_ws:ws_sync_connect: tcp_blocking_connect failed
 ERROR:proto_ws:ws_connect: connect failed
 ERROR:proto_ws:proto_ws_send: connect failed
 ERROR:tm:msg_send: send() for proto 5 failed
 ERROR:tm:t_forward_nonack: sending request failed
 DBG:tm:t_relay_to: t_forward_nonack returned error
```
My softphone is in tcp/udp and sipml5 is in wss . I am not getting whats the problem . I seen someone has reported same kind of issue from tcp to tls calling in opensips-2.2.0 which get fixed in 2.2.1 version .

Is this an issue or I am doing anything wrong . If I am doing anything wrong then how its working in db_mode:2 . 

Please help me . I am blocked in this from last 1week .

**Comment by sasmita11** [comment]
I have tried the same thing in 2.3 version and thats working fine .So it seems like there is some issue in 2.2.2 . But I am about to use this in production and in opensips-2.3 there are some open issue till now regarding crash . So Can anybody give me any patch for opensips-2.2.2 to fix this problem . 

Please let me know which will be convenient for me . Or I should wait for 2.3 to be bug free .

**Comment by razvancrainea** [comment]
Are you using db_mode 2 or 3 for the usrloc module? Can you check if you have the received field provisioned in the DB when using db_mode 3?

**Comment by sasmita11** [comment]
I am using db_mode 3 . I got a difference in received parameter . I am
making wss connection from the browser  .

   In case of opensips-2.2.2 in received column of location table is
like *"sip:contact_ip:port;transport=WS"
.*

   But in case of opensips-2.3  in received column of location table is
like "*sip:contact_ip:port;transport=WSS*"

   Contact in both case is *
"sips:username@contact_ip:port;rtcweb-breaker=no;transport=wss"
. *

   Is this the problem for which in case 2.2 I am getting 477 send failed
and in 2.3 its working fine . If yes , then how can I fix this . My config
file for both the version is same . The table for both the version is also
same . I am not changing anything . Still why there is difference ?

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by razvancrainea** [comment]
Can you apply commit 5fe4792f54d6dd1f66137f522ef16e4a88743d0c to your OpenSIPS 2.2 sources and check if this gets fixed?

**Comment by sasmita11** [comment]
Hi Razvan ,

    After doing this changes , it get fixed .  And the received value
changed to transport=wss also .

   Will I go ahead and use this . This changes don't have any other side
effect ?  Is this the final change or you will do anything else ?

   Thanks for your help .

*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by razvancrainea** [comment]
Were you using the latest OpenSIPS version? Because I double checked and the fix was already there, starting with commit 186f3d23004e80ddd63857ea36278c7ae179398c in 17th of March.

**Comment by sasmita11** [comment]
I have downloaded from the bellow link .

http://download.opensips.org/opensips-2.2.2.tar.gz


*Thanks & Regards*
*Sasmita Panda*
*Network Testing and Software Engineer*
*3CLogic , ph:07827611765*

**Comment by razvancrainea** [comment]
Unfortunately there's no release yet for this fix. Until 2.2.4 is released, you can either run with the patch I've provided you, or you can checkout the latest 2.2 branch and use those sources.
