### ISSUE TITLE
Sequential request NOTIFY from FS with Event conference not relayed back to UAC

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#1113]
Scenario:

- Blink as UAC (172.27.31.18)
- FS 1.6.x. as UAS (172.27.33.40)
- OS 2.2.x as a proxy in the middle (172.27.26.35)

Blink registered to OS via TCP calls in to OS, call is routed to FS to conference. Blink does a RFC 4575 SUBSCRIBE (Event conference), OS routes it and relays via TCP to FS, to which FS responds with NOTIFY about call participants. OS at that time sends 200 OK, rather than relays it back to Blink.
As a working example, SUBSCRIBE via TCP for message-summary is relayed via UDP to another FS VM server (172.27.26.5). Incoming NOTIFYs from VM server are relayed properly to Blink.
I'm attaching a pcap where I have a working and non-working example. Relayed NOTIFY from VM server is at frame 63, whereas not-relayed NOTIFY from conf server is at frame 99.
[sniff.pcap.zip](https://github.com/OpenSIPS/opensips/files/970256/sniff.pcap.zip)

**Comment by volga629** [comment]
that similar to what we see, but only with SUBSCRIBE and NOTIFY in dialog not sent to client

https://opensips.org/pipermail/users/2017-April/037183.html

**Comment by sekil75** [comment]
I have it working with sending SUBSCRIBEs/NOTIFYs via same protocol as received from UACs.
I will close this for now.
