### ISSUE TITLE
TLS doesn't relay BYE to other client

### ISSUE THREAD

**Issue by rachelxj** [OpenSIPS/opensips#1120]
I set up TLS to make secure call, but when I terminate the call from one side, the other side doesn't terminiate call, and I saw `ERROR:tm:uri2proxy: bad transport for sips uri: 2` from the syslog. I'm using Opensips 2.2.3
here is BYE request sent by imsdroid
SEND: BYE sip:1000@192.168.2.9:8748;transport=TLS;ob SIP/2.0
CSeq: 887086987 BYE
Allow: INVITE, ACK, CANCEL, BYE, MESSAGE, OPTIONS, NOTIFY, PRACK, UPDATE, REFER
CSeq: 887086987 BYE

Here is contact info
```
Contact:: sips:1002@192.168.1.148:52625;transport=tcp Q=
		Expires:: 554
		Callid:: 636fbc6d-fea8-9063-3710-3321765671c0
		Cseq:: 1454001850
		User-agent:: IM-client/OMA1.0 ios-ngn-stack/v00 (doubango r000)
		Received:: sip:192.168.2.178:52628;transport=TLS
		State:: CS_SYNC
		Flags:: 0
		Cflags:: NAT
		Socket:: tls:192.168.2.83:5062
		Methods:: 7535
```

**Comment by razvancrainea** [comment]
The error you have indicated seems to be related, but doesn't contain too much information. Are there any other errors in the logs?
