### ISSUE TITLE
Opensips 2.3 - Crash

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1123]
When make call opensips 2.3 crashed.
Message from log:
CRITICAL:core:pv_value_destroy: #012>>> pkg_free() on non-pkg ptr 0x8c6fab - aborting!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:receive_fd: EOF on 21

Can read "bt full" from here: 
https://pastebin.com/f5mqpFHZ

OS: CentOS Linux release 7.3.1611
Opensips from git (12.05.2017)

**Comment by ionutrazvanionita** [comment]
Can you provide the output of val in frame 2?
```
f2
p *val
```

**Comment by goup2010** [comment]
(gdb) f 2
#2  0x000000000050f6c2 in pv_value_destroy (val=val@entry=0x7ffec280c790)
    at pvar.c:4512
4512            if(val->flags&PV_VAL_PKG) pkg_free(val->rs.s);

(gdb) p *val
$1 = {rs = {s = 0x8c6fab <int2str_buf+11> "1494587592", len = 10},
  ri = 1494587592, flags = 60}

**Comment by ionutrazvanionita** [comment]
Thank you. Now can please do the following:
```
f 3
p *a
```
Also, do you have any part in your script where you have a timestamp as a right operand? Something like:
```
$var(aaa) = $Ts;//instead of $Ts could be any value storing a timestamp
```

**Comment by goup2010** [comment]
I have radius request after INVITE.
Radius return $avp(timestamp);

Here is part of my script:
$avp(mv_timestamp) = $avp(timestamp);
$acc_extra(mv_timestamp)= $avp(mv_timestamp);



2017-05-15 12:38 GMT+03:00 Ionut Ionita <notifications@github.com>:

**Comment by ionutrazvanionita** [comment]
And can you use gdb to print the action structure?
```
f 3
p *a
```
When you say radius return $avp(timestamp) you mean variables returned within radius sets via **radius_send_auth** async function?

**Comment by goup2010** [comment]
Yes, that's true.

**Comment by ionutrazvanionita** [comment]
Managed to replicate the bug. The patch attached to this message should fix the problem. Waiting for your feedback ! 
[acc_bogusSetFix.patch.txt (https://github.com/OpenSIPS/opensips/files/1001228/acc_bogusSetFix.patch.txt)

**Comment by goup2010** [comment]
I try this patch.
Opensips crashed.
Here is "bt full"
https://pastebin.com/Tdqb0mfM

**Comment by ionutrazvanionita** [comment]
Try this one 
[acc_bogusSetFixV2.patch.txt](https://github.com/OpenSIPS/opensips/files/1003499/acc_bogusSetFixV2.patch.txt)

**Comment by goup2010** [comment]
[root@dev opensips-2.3]# patch -p1 < acc_bogusSetFixV2.patch.txt
patching file modules/acc/acc_vars.c
Hunk #1 FAILED at 135.
Hunk #2 succeeded at 150 (offset -18 lines).
1 out of 2 hunks FAILED -- saving rejects to file modules/acc/acc_vars.c.rej


2017-05-16 10:18 GMT+03:00 Ionut Ionita <notifications@github.com>:

**Comment by ionutrazvanionita** [comment]
remove the old version of the patch before applying the new one

**Comment by goup2010** [comment]
I make test with new patch.
Opensips not crashed but MV-Timestamp is not receive by Radis.

I have follow setup:
modparam("acc", "extra_fields", "aaa: ......;mv_timestamp->MV-Timestamp")

in route:
$avp(mv_timestamp) = $avp(timestamp);
$acc_extra(mv_timestamp)= $avp(mv_timestamp);

**Comment by ionutrazvanionita** [comment]
Just tested with a very simple scenario
```
modparam("acc","extra_fields", "aaa: test->Sip-User-QOP")
...
if (is_method("INVITE")) {
    $acc_extra(test) = "Test Value";
    do_accounting("aaa");
}
```
and captured the accounting RADIUS packet with wireshark, the AVP **SIP-User-QOP** it's there so it doesn't look like there is a problem there. Used **Sip-User-QOP** AVP only for testing purposes, no reason for that.

**Comment by ionutrazvanionita** [comment]
I'm sorry, indeed there seems to be a problem with extras when doing CDRs. Will come back with a patch.

**Comment by ionutrazvanionita** [comment]
Added 2 commits in master branch: one fixes the extra issue you are complaining about and one fixing an issue when using acc_legs. Try fetching them, the problem should now be fixed!

**Comment by goup2010** [comment]
YES!!!!
All is OK!
Thanks!

**Comment by ionutrazvanionita** [comment]
Great news! Thank you too for your help!
