### ISSUE TITLE
Periodically error message "ERROR:core:proto_udp_send"

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1125]
Hello colleagues. Please help with this problem. Sometimes I see similar errors in logs:
ERROR:core:proto_udp_send: sendto(sock,0x7ff874914010,962,0,0x7ff87495c910,16): Operation not permitted(1)
ERROR:tm:msg_send: send() for proto 1 failed
ERROR:tm:t_forward_nonack: sending request failed

UAC may send 10 request(for example REGISTER) to UAS and one of them(random) failure with this error.
UAS is a border between EXT network and INT network. This error occurs only then traffic comes from EXT to INT. As a consequence of this problem UAC received (477/TM) reply and UAS not passed request inside the network. Some UAC after receiving  (477/TM) reply stops sends any request to server.

Any idea how resolve this problem? Thanks!

**Comment by razvancrainea** [comment]
This message comes from the Operating System and usually indicates that some firewall rules on the Outbound chain do not allow you to send messages to that destination. These rules may be permanent rules or temporary (such as rate limits set by the OS). So the issue you are looking int is probably at the OS side, not in OpenSIPS.
I will close the ticket now. For further assistance, use our [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

**Comment by kertor** [comment]
Thank you for your reply!
