### ISSUE TITLE
Change the order of character in a string

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#1127]
It would be good to have a function that changes the order of characters in a string.

for example:
input string "123456" output string "214365"

**Comment by bogdan-iancu** [comment]
@xaled1 - what is the algorithm of the transformation here ? swapping 2 by 2 chars ?

**Comment by xaled1** [comment]
2 by 2 would work for me as I need it for conversation of some IEs to ISDN type convention for User-to-User signalling. A more generic solution could be potentially useful to more people.

**Comment by xaled1** [comment]
This is what I'm doing right now:

$var(swap_reg) = "/(.)(.)/\2\1/g";
$var(uui_hex) = $(var(uui_hex){re.subst,$var(swap_reg)});

**Comment by bogdan-iancu** [comment]
I think the kind of processing you are looking for is too specific for your case; not to mention that you have a mechanism to do it (via regexp).
At this point I do not see a real need to have a dedicated function/transformation for this case.

**Comment by xaled1** [comment]
fine with me, (.)(.) look good in my script as well ;)
