### ISSUE TITLE
 wait_for_event cancelling

### ISSUE THREAD

**Issue by vladpaiu** [OpenSIPS/opensips#1128]
Hello,

Currently facing some issues while trying to cancel a push notification attempt via wait_for_event().

First, upon receiving a CANCEL from the UAC , OpenSIPS fails to propagate the 487 back from the UAS ( since it already has a pending 'dummy' branch added ) - propagating of the 487 only happens upon fr_inv_timeout seconds

Also, attempting to cancel all pending branches by using t_cancel_branch("a"); ( eg. a branch declines the call with 486 and the desired behavior is to cancel all other pending branches ) fails to work due to the same reason as above.

Best Regards,
Vlad

**Comment by bogdan-iancu** [comment]
@vladpaiu , if I understand correctly your scenario, this is not actually related to event_routing, but to how the canceling works. If you have open branches with no reply at all, you cannot cancel them, as you have no clue what's going on there (maybe the INVITE  + 200 OK are pending somewhere on the network). Please follow this discussion and let me know if it is what you experience : http://lists.opensips.org/pipermail/devel/2015-November/018623.html

**Comment by vladpaiu** [comment]
Hello,

Well, not really true since there is no open branch per se, just a pending registration attempt, so even if the phone registers after the Cancel arrives, the branch should not get pushed into the transaction, so there would not be any need to wait any longer ( t_inject_branches should not do anything when getting called in the event route ) - at least that's my point of view.

Best Regards,
Vlad

**Comment by bogdan-iancu** [comment]
@vladpaiu, after more investigations, I agree with your report, actually similar to #1237 . A fix is under testing right now
