### ISSUE TITLE
Access a specific character in a string

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#1129]
It would also be good to be able to access a specific character in a string.

Something like:
 
$var(str) = "123456";
xlog("first character: $var(str)[0] second character: $var(str)[1] ");

**Comment by bogdan-iancu** [comment]
@xaled1 , the [] indexing applies on the variable and not on its value (like if the variable has multiple values, you can pick one of them, or all).

For what you want, simply use the s.substr transformation (http://www.opensips.org/Documentation/Script-Tran-2-3#toc5): 
  xlog("first character: $(var(str){s.substr,0,1}) second character: $(var(str){s.substr,1,1}) ");
