### ISSUE TITLE
Dialplan module attributes

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#1131]
Hi

This isn't an "issue" as such, however the dialplan module restricts you to a maximum of 32 characters for the attributes column as defined here:

https://github.com/OpenSIPS/opensips/blob/master/modules/dialplan/dp_repl.c#L363
and here 
https://github.com/OpenSIPS/opensips/blob/master/scripts/mysql/dialplan-create.sql#L13

Is it possible this default could be increased to 128 or 256 characters? I've been manually increasing this myself since at least release 1.6 and it hasn't thrown up any issues. I realise it's easy to change when compiling your own copy of OpenSIPS, but it makes the .deb packages very restrictive.

Also, the repl_exp column is defined as a char(32) but the code allows for bigger values, could this be changed to match the code?

Pete

**Comment by bogdan-iancu** [comment]
Hi @petekelly , please confirm this change.
