### ISSUE TITLE
tls is not working

### ISSUE THREAD

**Issue by erhuabushuo** [OpenSIPS/opensips#1133]
Jun  2 18:41:43 [26742] INFO:proto_tls:mod_init: initializing TLS protocol
Jun  2 18:41:43 [26742] ERROR:proto_tls:mod_init: unable to set the memory allocation functions
Jun  2 18:41:43 [26742] ERROR:proto_tls:mod_init: NOTE: check if you have openssl 1.0.1e-fips, as this version is know to be broken; if so, you need to upgrade or downgrade to a differen openssl version !!
Jun  2 18:41:43 [26742] ERROR:core:init_mod: failed to initialize module proto_tls
Jun  2 18:41:43 [26742] ERROR:core:main: error while initializing modules

opensips version: 2.1.5
system: Ubuntu 14.04.5 LTS
openssl version:OpenSSL 1.0.1f 6 Jan 2014

openssl development file installed by `apt install libssl-dev`

# ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
	libssl.so.1.0.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
	libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so

**Comment by erhuabushuo** [comment]
Ubuntu 16 has same issue

**Comment by razvancrainea** [comment]
Are you using the postgres module, or the mongodb one?

**Comment by erhuabushuo** [comment]
postgres module

**Comment by razvancrainea** [comment]
This is a known issue - the postgres and mongodb modules use the libssl library in such a way that is incompatible with OpenSIPS. There's currently no known fix for this, except compiling the postgres library without ssl support. I will try to think of a solution and let you know what to do.

**Comment by razvancrainea** [comment]
Actually this is a duplicate issue of #1114. I will close this one for now, for any updates please follow #1114.
