### ISSUE TITLE
PAI parsing error

### ISSUE THREAD

**Issue by telematico** [OpenSIPS/opensips#1134]
Using Opensips 1.11.9 I noticed an error in PAI parsing.

The header I receive from an upstream provider (masked) is like:
P-Asserted-Identity: "Dr who" <sip:dr.who@siprovider.es>, <tel:+349999999>

according to  rfc3325 section 9.1 providing two parameters is right, if first is an sip addr and second a tel addr.

Opensips fails parsing the header with error:
error route class=1 level=3
info=error parsing PAI header rcode=400 rreason=bad header 

looking at parser/parse_pai.c I can read a comment:
Currently only one name-addr / addr-spec is supported in the header
The code in this file is 11 years old

I agree to not read the second param (the tel addr) but I think if the RFC permits it, Opensips should take only the first part of the PAI header (the sip URI) but never makes a parsing error, because the header is right according the RFC.

thanks for your help

**Comment by bogdan-iancu** [comment]
So more input from #1197:

I have two issues with that.

    Sanity check fails
    I do not know how to normalise that because $ai variable is null.

That is the error I get

ERROR:core:parse_pai_header: bad P-Asserted-Identity header

**Comment by bogdan-iancu** [comment]
check this for 2.3 - http://www.opensips.org/Documentation/Install-DBSchema-2-3#GEN-DB-DR-GATEWAYS
