### ISSUE TITLE
Error message when user location/dialog is stored in mongodb - Opensips 2.3

### ISSUE THREAD

**Issue by jalung** [OpenSIPS/opensips#1135]
[24348] CRITICAL:usrloc:dbrow2info: bad contact id
[24348] ERROR:usrloc:db_load_urecord: skipping record for 3333333333@domain.net in table location

Testing Opensips 2.3 with the cachedb_mongodb module, the above error appears when a UA's AOR is saved on registration. The AOR's are still saved however. Calls can be made and it appears to function normally.

The below errors also appear when dialogs are stored in mongo. They seem to appear at the BYE using the accounting module when calls are between UA's.

[24353] ERROR:cachedb_mongodb:mongo_db_update_trans: Failed to run query. Err = 0, 0 , 0
[24353] ERROR:cachedb_mongodb:mongo_db_update_trans: Fetched ERR key [shards]. Val = May 29 03:32:03 [24353] ERROR:cachedb_mongodb:mongo_db_update_trans: Fetched ERR key [shardRawGLE]. Val = May 29 03:32:03 [24353] ERROR:cachedb_mongodb:mongo_db_update_trans: Fetched ERR key [err]. Val = May 29 03:32:03 [24353] ERROR:cachedb_mongodb:mongo_db_update_trans: Fetched ERR key [ok]. Val = May 29 03:32:03 [24353] ERROR:dialog:update_dialog_dbinfo: could not update database info

Seems to function here normally too. Because the dialogs are being deleted at end of call.

FYI:
Documentation says to use mongo-c-driver 0.6 but that does not compile with 2.3 sips. 2.3 compiles with the 1.x versions of the driver but ultimately the cachedb_module is Dead On Arrival (at least for Mongo 2.6). To test a cachedb_mongodb module on sips 2.3, an older copy on the cached_mongodb module taken from sips 2.1.5 was compiled in and of course using the 0.6 driver.

Opensips 2.3
mongo-c-driver 0.6
MongoDB cluster 2.6.12

**Comment by liviuchircu** [comment]
First of all, I have just updated the _cachedb_mongodb_ docs for OpenSIPS 2.3+, to reflect the driver update. What do you mean by "dead on arrival"? The new module should work with 2.6 Mongo servers, as per the driver docs, so we should start investigating that, rather than copy-pasting the old module.

**Comment by jalung** [comment]
DOA because unable to start opensips 2.3 with the cachedb_mongodb module.  I've tried the packaged version of the mongo-c-driver (1.3.6)  and then the 1.0 - 1.3 downloaded versions. Also tried changing the order in which it will be loaded.  It fails with the same message.

NOTICE:signaling:mod_init: initializing module ...
INFO:core:evi_publish_event: Registered event <E_MYSQL_CONNECTION(3)>
NOTICE:cachedb_mongodb:mod_init: initializing module cachedb_mongodb ...
NOTICE:db_cachedb:mod_init: initializing module db_cachedb ...
INFO:avpops:avpops_init: initializing...
INFO:usrloc:ul_init_locks: locks array size 512
INFO:core:evi_publish_event: Registered event <E_UL_AOR_INSERT(4)>
INFO:core:evi_publish_event: Registered event <E_UL_AOR_DELETE(5)>
INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_INSERT(6)>
INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_DELETE(7)>
INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_UPDATE(8)>
INFO:registrar:mod_init: initializing...
INFO:dialog:mod_init: Dialog module - initializing
INFO:core:evi_publish_event: Registered event <E_DLG_STATE_CHANGED(9)>
kernel: opensips[305]: segfault at a0 ip  error 6 in libmongoc-1.0.so.0.0.0[7ff0707c7000+4d000]
opensips: Jun  7 01:26:33 [302] INFO:core:daemonize: pre-daemon process exiting with -1
systemd: custom-opensips.service: Control process exited, code=exited status=255
systemd: Failed to start Opensips Proxy Service.
systemd: custom-opensips.service: Unit entered failed state.
systemd: custom-opensips.service: Failed with result 'exit-code'.

I've checked out the new docs and verified the configs and prereqs. Tested the old module to make sure there weren't any other issues with the script and new tables.

**Comment by jalung** [comment]
Tested bundle:
Opensips 2.3.1
mongo-c-driver 1.6.3
mongodb cluster 3.2.15 (via mongos router)

[opensips-2.3.1-1.txt](https://github.com/OpenSIPS/opensips/files/1150627/opensips-2.3.1-1.txt)
[opensips-2.3.1-hack.txt](https://github.com/OpenSIPS/opensips/files/1150628/opensips-2.3.1-hack.txt)


Resolved the crashes and stabilized the system with the attached patches.

Issues resolved:
1. If mongo-c-driver is compiled with the recommended switch of "--disable-automatic-init-and-cleanup" then OpenSips does not start. Solution was to execute "mongoc_init()" at module initiation.
2. TLS does not start if mongo-c-driver is compiled without this switch  "--disable-automatic-init-and-cleanup" 
3. In file "db/db_res.c" pkg_free() being used to free memory not created by pkg_malloc().
4. Module cached-mongodb not handling NULL and ObjectID types. 
5. Module cached-mongodb returning the second item in the results array in a "find" query. The first item is what is needed. Function "mongo_con_raw_query" modified to resolve the issue with mongos. The original function however worked with the standalone mongodb
6. Function "kvo_to_bson" crashing on queries where there are only conditional op codes such as "<" and "!=" included in the query. If there is an equal ("=") the query works. This bug is evident on shutdown in the usrloc module executing function "db_timer_udomain".
7. Crash In "registrar/save.c _remove". Object "delete_he" not being initialized before use when deleting by domain.

Issue not resolved:
1. If multiple UA's with the same username are registered, and/or multiple opensips share the same location table, all the UA's with the same name are updated or deleted when one registers.

Hack to resolve this is also attached, but cannot be considered "official" as it utilizes the "contact_id" and "callid" as keys when module parameter switch is used to identify the contacts. In addition, it is specific for DB_ONLY mode with mongodb.
