### ISSUE TITLE
Issue in registrar module in save flags .

### ISSUE THREAD

**Issue by sasmita11** [OpenSIPS/opensips#1136]
I am using opensips-2.2.2 . In registrar module I had set the max_contact parameter to 1 . 
modparam("registrar", "max_contacts", 1)

      And while saving in location table , I am using the bellow flag .

save("location","c1fp1")

      As for the document , when we use "f" flag it saves the contact forcefully . I such case , it removes the older contact and make space for the new contact without exceeding the maximum allowed number  .

     So in my case I am expecting , it must be remove the old contact and save the newer one  . But what it is doing is , its adding the new contact without removing the older one . The older one get removed when its expire time reaches .
         I have just tested this with opensips-1.6 . Its working properly as for my expectation . Its not even working in opensips-2.3 .

      Please let me know whether its an open issue or I am doing anything wrong .

**Comment by razvancrainea** [comment]
Hi, Sasmita!

I've just tested this in 2.2 and it works fine. Are you sure that there is no other `save()` call in your script? Also, how are you checking whether there are two contact or not? Through MI? Are you sure that the old contacts don't have an `expire` value in the `Expire` field?

Best regards,
Răzvan

**Comment by sasmita11** [comment]
Hi , 
 1st : There are other save() function call in the same script but that was not having the same flag .Save() function is getting called in loop and for my AOR the loop it is entering has the save function which I had mention earlier . 

2nd : I am using db_mode:3 , so I am checking this in database directly . 

3rd : Previous register has expire  value in the Expire field . I think every register has expire value in the Expire field .  Out SIP client used to send expire value in Expire field always and also fresh that registered contact before it expires . 


      In the same condition when I am running it in opensips-1.6 , it works for me . Even if there is expire in old register but when new register comes that removes the old one and save the new one . 
     So I am wondering , why opensips-2.2 is not working similarly .

**Comment by liviuchircu** [comment]
@sasmita11 I managed to reproduce this issue and submitted a fix on the `2.2` branch. Please re-open if needed, cheers!
