### ISSUE TITLE
 Opensips 2.3.0 TLS Start-Up Error

### ISSUE THREAD

**Issue by jalung** [OpenSIPS/opensips#1137]
[6708] INFO:tls_mgm:mod_init: initializing TLS management
 [6708] WARNING:tls_mgm:mod_init: disabling compression due ZLIB problems
 [6708] ERROR:tls_mgm:mod_init: compiled agaist an openssl with kerberos, but run with one with no kerberos
 [6708] ERROR:core:init_mod: failed to initialize module tls_mgm
 [6708] ERROR:core:main: error while initializing modules
 [6708] INFO:core:cleanup: cleanup
 [6708] NOTICE:core:main: Exiting....

After some research was able to start it with this patch, as the openssl is correctly installed. The flags are explanatory.

```
diff -urN opensips-2.3.0-orig/modules/tls_mgm/tls_mgm.c opensips-2.3.0/modules/tls_mgm/tls_mgm.c
--- opensips-2.3.0-orig/modules/tls_mgm/tls_mgm.c       2017-04-26 14:27:19.000000000 +0000
+++ opensips-2.3.0/modules/tls_mgm/tls_mgm.c    2017-05-28 04:31:35.730346553 +0000

@@ -1619,7 +1619,7 @@
                return -1;
        }

diff -urN opensips-2.3.0-orig/modules/tls_mgm/tls_mgm.c opensips-2.3.0/modules/tls_mgm/tls_mgm.c
--- opensips-2.3.0-orig/modules/tls_mgm/tls_mgm.c       2017-04-26 14:27:19.000000000 +0000
+++ opensips-2.3.0/modules/tls_mgm/tls_mgm.c    2017-05-28 04:31:35.730346553 +0000

@@ -1619,7 +1619,7 @@
                return -1;
        }

-#if !defined(OPENSSL_NO_COMP)
+#ifdef OPENSSL_NO_COMP
        STACK_OF(SSL_COMP)* comp_methods;
        /* disabling compression */
        LM_WARN("disabling compression due ZLIB problems\n");
@@ -1649,7 +1649,7 @@
        }

        if ( ( n ^
-#ifndef OPENSSL_NO_KRB5
+#ifdef OPENSSL_NO_KRB5
                        1
 #else
                        0
```

**Comment by razvancrainea** [comment]
This is not a fix, but a workaround to make it work on your setup.

Can you print the libssl version you are using?

**Comment by jalung** [comment]
Using version 1.0.2j 

below is the configure options on the package.

`./Configure` \
        --prefix=%{_prefix} --openssldir=%{_sysconfdir}/pki/tls ${sslflags} \
        --system-ciphers-file=%{_sysconfdir}/crypto-policies/back-ends/openssl.config \
        zlib sctp enable-camellia enable-seed enable-tlsext enable-rfc3779 \
        enable-cms enable-md2 enable-rc5 \
        no-mdc2 no-ec2m no-gost no-srp \
        --with-krb5-flavor=MIT --enginesdir=%{_libdir}/openssl/engines \
        --with-krb5-dir=/usr shared  ${sslarch} %{?!nofips:fips}

What needs to be changed?

**Comment by razvancrainea** [comment]
Did you manually compile the library? If so, are you sure opensips is using the one you compiled? You can check by running `ldd tls_mgm.so` and check the `ssl` library path.

**Comment by jalung** [comment]
No, did not manually compile library, am using the packaged version. I was considering recompiling the library if something in the configure parameters needed to be changed. The above configure params are what the maintainers used.

# ldd /usr/lib64/opensips/modules/tls_mgm.so
	linux-vdso.so.1 (0x00007ffc05768000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb3c3a08000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb3c37ed000)
	libsctp.so.1 => /lib64/libsctp.so.1 (0x00007fb3c35e9000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007fb3c3377000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fb3c2f16000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb3c2b54000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c06b7de000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fb3c2906000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fb3c261e000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fb3c2419000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fb3c21e7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fb3c1fd1000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fb3c1dc1000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fb3c1bbd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb3c199f000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fb3c177b000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fb3c1508000)

# dnf list openssl
Last metadata expiration check: 1:22:43 ago on Thu Nov 16 23:48:58 2017.
Installed Packages
openssl.x86_64                                                        1:1.0.2j-1.fc23                                                        @updates

# dnf provides "*/libssl.so.10"
Last metadata expiration check: 1:23:30 ago on Thu Nov 16 23:48:58 2017.
openssl-libs-1:1.0.2j-1.fc23.x86_64 : A general purpose cryptography library with TLS implementation
Repo        : @System

**Comment by razvancrainea** [comment]
Can you try to upgrade the openssl-libs package? I noticed that the latest release for fedora 2.5 is [1.0.2k](https://apps.fedoraproject.org/packages/openssl).
If this doesn't work, can you try to define in your `Makefile.conf` or in the `CC_EXTRA_OPTS` variable the `OPENSSL_NO_KRB5` flag:
```
CC_EXTRA_OPTS="-DOPENSSL_NO_KRB5 -DOPENSSL_NO_COMP"
```

**Comment by jalung** [comment]
Tested on system with 1.0.2k and the result was the same. I then added the flags to the opensips.spec file like this:

`CFLAGS="%{optflags} %{defs} -DOPENSSL_NO_COMP -DOPENSSL_NO_KRB5 -L/usr/lib64" \
%{__make} all %{?_smp_mflags} USE_FREERADIUS=1 TLS=1 SCTP=1 \
  exclude_modules="%EXCLUDE_MODULES" \
  cfg_target=%{_sysconfdir}/opensips/ \
  modules_prefix=%{buildroot}%{_prefix} \
  modules_dir=%{_lib}/%{name}/modules
`
This solves the problem of opensips starting TLS, but can you explain the semantics? Why check for these flags in the code when there is no documentation that says to manually define them. What am I missing?

**Comment by jalung** [comment]
To add : 
If the binary is built with "make menuconfig && make" it is able to resolve the SSL headers and TLS starts.

The issue apparently is with building the binary package with rpmbuild. This is the preferred method for maintenance reasons. Any insights on fixing this?

**Comment by razvancrainea** [comment]
You said it does work if you specify the `-D` flags, correct?
There seems to be an issue with the way the library is build and opensips is using it. I did not look too far into this, since I can't manage to replicate this on my system. I will try to replicate it and let you know, but please confirm the distros you are using.

**Comment by jalung** [comment]
Yes it does work if the -D flags are specified when using rpmbuild.  It also works when compiling with "make" without specifying the -D flags.  Seems rpmbuild is to blame.

Using fc23 & fc24
