### ISSUE TITLE
In-dialog OPTIONS timeout

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1138]
Hello,

I used $T_fr_timeout = 3 in my script before sending initial INVITE. Also I enabled in-dialog OPTIONS ping with timeout of 30 seconds. I found an interesting behaviour:

example:
12:00:00 opensips generated outgoint OPTIONS
12:00:03 opensips complains on timeout "INFO:dialog:reply_from_caller: terminating dialog ( due to timeout ) with callid = <calld>"
12:00:04 B-side generated 200 OK on previous OPTIONS
12:00:30 opensips generated BYE.

Is this correct behaviour?

**Comment by bogdan-iancu** [comment]
@nikbyte , what is the exact parameter that you set to 30 seconds ?

**Comment by nikbyte** [comment]
Wow, a year ago. It's stale bot raised this ticket.
Here I told about options_ping_interval parameter.

**Comment by bogdan-iancu** [comment]
Actually 2 years ago :D .  The `OPTIONS` ping (as transactions) will use as timeout the default value defined in TM - https://opensips.org/html/docs/modules/2.4.x/tm.html#param_fr_timeout . It is not correlated (at all) with the timeout you defined for the `INVITE`

**Comment by nikbyte** [comment]
Thanks, I think it can be closed. 🙂
