### ISSUE TITLE
RTPProxy Stream

### ISSUE THREAD

**Issue by eliakimfelmorais** [OpenSIPS/opensips#1140]
Hello,

I noticed a problem using opensips 1.8.4 rtpproxy_stream2uac and rtpproxy_stream2uas, when I tried to use the both functions the stream not work for the both sides.

I receive this error in rtpproxy.log

Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: INFO:handle_command: lookup on ports 19080/16422, session timer restarted
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: DBUG:doreply: sending reply "183269_60230 16422 177.39.216.199#012"
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: DBUG:handle_command: received command "183269_60231 P1 020B594BF9814000003F31C3@TB009714_VOIP0.TB009714 /var/rtpproxy/prompts/an_chamadacobrarrecebendo.wav session 0D5C3030393731340749C8D5;1 pg2tUB8KN2SjK;1"
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: ERR:handle_play: can't create player
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: DBUG:doreply: sending reply "183269_60231 E6#012"
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: DBUG:handle_command: received command "183269_60232 P1 020B594BF9814000003F31C3@TB009714_VOIP0.TB009714 /var/rtpproxy/prompts/an_chamadacobrarligando.wav session pg2tUB8KN2SjK;1 0D5C3030393731340749C8D5;1"
Jun 16 15:28:30 host-2972178631 rtpproxy[10344]: ERR:handle_play: can't create player
  
This is my code when I active the rtpproxy_streamuac e rtpproxy_streamuas

if($avp(play)==1 && !isflagset(13) && status=="200") {
                                xlog("L_WARN", "Enviada mensagem de chamada a cobrar [$rm/f=$fu/r=$ru/ct=$ct/ci=$ci/$si]");
                                        rtpproxy_offer();
                                        rtpproxy_stream2uac("/var/rtpproxy/prompts/an_chamadacobrarrecebendo.wav","1");
                                        rtpproxy_stream2uas("/var/rtpproxy/prompts/an_chamadacobrarligando.wav","1");
                                        setflag(13);
           }

**Comment by amitpaltech** [comment]
HI eliakimfelmorais, 
            you have  closed this issue,  pls share how is that  resolved, I am getting same issue not able to play media file.
