### ISSUE TITLE
Topology hiding Call-ID partially working

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1148]
Hello.

I am using latest 2.2 on testing environment and SIPp as UAC and UAS to test my configuration. During my tests I found out that the Invite sent to UAS has the original Call-ID where the ACK sent to UAS has the encrypted one.

Original Invite from UAC

INVITE sip:+2222222623@1.1.1.210:5060 SIP/2.0
Via: SIP/2.0/UDP 1.1.1.212:5060;branch=z9hG4bK-16050-1-0
From: "" <sip:+11111115300@1.1.1.212:5060>;tag=1
To: "" <sip:+2222222623@1.1.1.210:5060>
Call-ID: 1-16050@1.1.1.212
CSeq: 1 INVITE
Contact: sip:+11111115300@1.1.1.212:5060
Max-Forwards: 70
Subject: Performance Test
Content-Type: application/sdp
Content-Length:   139

v=0
o=user1 53655765 2353687637 IN IP4 1.1.1.212
s=-
c=IN IP4 1.1.1.212
t=0 0
m=audio 6000 RTP/AVP 8
a=rtpmap:8 PCMA/8000

Invite Sent to UAS

INVITE sip:594+2222222623@1.1.1.213:5090 SIP/2.0
Via: SIP/2.0/UDP 1.1.1.210:5060;branch=z9hG4bKc873.ea21d406.0
From: "" <sip:+11111115300@1.1.1.212:5060>;tag=1
To: "" <sip:+2222222623@1.1.1.210:5060>
Call-ID: 1-16050@1.1.1.212
CSeq: 1 INVITE
Contact: <sip:1.1.1.210;did=557.4481b464>
Max-Forwards: 68
Subject: Performance Test
Content-Type: application/sdp
Content-Length: 166
tel:+2222222623;npdi;rn=594
v=0
o=user1 53655765 2353687637 IN IP4 1.1.1.210
s=-
c=IN IP4 1.1.1.210
t=0 0
m=audio 11052 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=sendrecv
a=rtcp:11053

ACK from UAC

ACK sip:+2222222623@1.1.1.210:5060 SIP/2.0
Via: SIP/2.0/UDP 1.1.1.212:5060;branch=z9hG4bK-16050-1-4
From: "" <sip:+11111115300@1.1.1.212:5060>;tag=1
To: "" <sip:+2222222623@1.1.1.210:5060>;tag=7
Call-ID: 1-16050@1.1.1.212
CSeq: 1 ACK
Contact: sip:+11111115300@1.1.1.212:5060
Max-Forwards: 70
Subject: Performance Test
Content-Length: 0

ACK to UAS

ACK sip:1.1.1.213:5090;transport=UDP SIP/2.0
Via: SIP/2.0/UDP 1.1.1.210:5060;branch=z9hG4bKc873.ea21d406.2
From: "" <sip:+11111115300@1.1.1.212:5060>;tag=1
To: "" <sip:+2222222623@1.1.1.210:5060>;tag=7
Call-ID: isbc_WF5TVR1BWCUIH0NbUkVBU1RGSxxfVw--
CSeq: 1 ACK
Contact: <sip:1.1.1.210;did=557.4481b464>
Max-Forwards: 68
Subject: Performance Test
Content-Length: 0

From OpenSIPs Logs

Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: [1-16050@1.1.1.212] Do Topology Hiding
Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: DBG:core:parse_headers: flags=2000000000
Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: DBG:topology_hiding:w_topology_hiding1: Will change callid while doing topo hiding
Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun 26 20:26:52 isbc-the01 /sbin/opensips[9312]: DBG:topology_hiding:topo_delete_vias: Delete via [Via: SIP/2.0/UDP 1.1.1.212:5060;branch=z9hG4bK-16050-1-0#015#012]

**Comment by apsaras** [comment]
I found the problem but I am not sure if you should do something on module level for that.

The problem was the tel header which was added using append_hf but forgot to add \r\n at the end of the header.

**Comment by bogdan-iancu** [comment]
@apsaras , during the handling of the INVITE (the one with the broken call-id), do you see any errors in the opensips logs ?

**Comment by apsaras** [comment]
If I remember well I didn't saw any error. Unfortunately I do not have the logs to re-check.

**Comment by bogdan-iancu** [comment]
So, simply adding that broken header from script should trigger this behavior (in combination with call-id TH, of course) ?

**Comment by apsaras** [comment]
yes
