### ISSUE TITLE
validation and ipv6

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1150]
Hello,

is it okay if validation don't like contact header with ipv6 like this?

```
Contact: <sip:7018@[2A01:888:888:8888:8888:8888:8888:8888]:54015;app-id=com.domain.prod;pn-type=ap
e;pn-tok=125C335E7D0DDE44919D5DC4EB293E95888CFC8C2F211211C9223FB7FE737CA2;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-call-
d=(null);pn-msg-snd=msg.caf;pn-timeout=0;pn-silent=1;transport=udp>;+sip.instance="<urn:uuid:ee434549-3ee8-4139-9173-66
e3681214>"
```

**Comment by bogdan-iancu** [comment]
@nikbyte , you mean OpenSIPS fails to parse such a Contact hdr ?

**Comment by nikbyte** [comment]
Sorry. I mean it fails sipmsg_validate("shmr", "$var(reason)").

**Comment by bogdan-iancu** [comment]
Do you get any errors in the logs ?

**Comment by nikbyte** [comment]
Bogdan, I'm really sorry. Double checked, it's my mistake in script, not sipmsg_validate() issue.
