### ISSUE TITLE
SNMPSTATS problem at the git revision c492436, OpenSIPS 2.2.4

### ISSUE THREAD

**Issue by yuri2000** [OpenSIPS/opensips#1153]
OpenSIPS 2.2.4 git revision c492436 has a problem with the snmpstats module's functionality:
snmpwalk -v 2c -c IrmcM0n -O e 127.0.0.1 openser | grep METHOD_INVITE
No log handling enabled - turning on stderr logging
openser: Unknown Object Identifier (Sub-id not found: (top) -> openser)

That problem didn't exist before at least at the OpenSIPS 2.2.3 git revision 591edd5:
snmpwalk -v 2c -c IrmcM0n -O e 127.0.0.1 openser | grep METHOD_INVITE
OPENSER-SIP-COMMON-MIB::openserSIPMethodName.1 = STRING: METHOD_INVITE

**Comment by liviuchircu** [comment]
This is really strange, as `snmpstats` code has not changed **at all** between these two specific versions. I've also taken a quick peek for any core library changes, with little success: nothing obvious that could impact the module. There was a single commit related to the module so far this year, namely 8e00b690a5.

I suggest you first try to disable this commit with `git revert 8e00b690`. If that doesn't solve the problem, you could, theoretically, find out the faulty commit using a divide-et-impera approach - but let's keep that as a last option for now!

**Comment by bogdan-iancu** [comment]
moved into #1649
