### ISSUE TITLE
ACC CDR avp is not visible

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1154]
Hello

I am trying to store the value of the Reason header which is received during Bye or 4xx.

OpenSIPs versions

version: opensips 2.1.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 19:19:32 Jul  4 2017 with gcc 4.4.7

I do the following

modparam("tm", "onreply_avp_mode", 1)

modparam("acc", "db_extra", "src_ip=$si;src_user=$(fU{s.substr,0,40});src_domain=$(fd{s.substr,0,40});dst_ouser=$(tU{s.substr,0,40});dst_user=$(rU{s.substr,0,40});dst_domain=$(rd{s.substr,0,40});ppid=$pu;rpid=$re")
modparam("acc", "db_extra_bye", "disconnect_reason=$avp(disconnect_reason)")

-- I also tried to have disconnect_reason at db_extra, same result

route[relay]
{

        if(is_present_hf("Reason"))
        {
                $avp(disconnect_reason)=$hdr(Reason);
                xlog("[$ci][RL] Call to $ru failed with reason: $avp(disconnect_reason)");
        }
....

onreply_route[1]
{
        if(is_present_hf("Reason"))
        {
                $avp(disconnect_reason)=$hdr(Reason);
                xlog("[$ci][RP] Call to $ru failed with reason: $avp(disconnect_reason)");
        }
....

Print out at log example
Jul  5 15:33:26 opensips3 /sbin/opensips[15304]: [vab8av40887hedeuh14dahb8b9acce4d@1.1.1.64][RL] Call to sip:11141@1.1.1.196:5060 failed with reason: Q.850;cause=16;text="Normal call clearing"

Insert SQL Executed Example

insert into acc (method,from_tag,to_tag,callid,sip_code,sip_reason,time,src_ip,src_user,src_domain,dst_ouser,dst_user,dst_domain,ppid,rpid,disconnect_reason,setuptime,created,duration ) values ('INVITE','idgyd0e4-CC-25','as55b19d63','c76t4rc6tfx440dncn6c4cytneftdt6e@1.1.1.64','200','OK','2017-07-05 15:20:16','1.1.1.22','1117492111','1.1.1.22','11141','11141','1.1.1.197','','','',0,'2017-07-05 15:20:16',41)

Is this a bug?

Best regards

**Comment by razvancrainea** [comment]
The CDR is generated when the BYE message finds the dialog it belongs to. This means that if you want to  have the db_extra_bye fields populated, you need to populate them _before_ calling `loose_route` or `match_dialog` on the BYE message. I will update documentation for this.

**Comment by apsaras** [comment]
Does that include failed responses like 480, 404 etc?

**Comment by apsaras** [comment]
I can confirm that this is not working with 480. It only works with Bye. 

Can you please provide a way to implement this? we need to have recorded on CDRs the Reason Header which can be found in any dialog termination message, bye, 4xx, 5xx etc.

Thank you in advance for your help.

**Comment by razvancrainea** [comment]
Unfortunately you can only do this starting with 2.3, because in the latest version, accounting is done when the transaction is completed (all the replies are received). Any version older than 2.3 does the accounting  when the BYE is received, so any information found later, on replies, is useless.

**Comment by razvancrainea** [comment]
As I said earlier, this is not a bug, but a limitation to the initial implementation of accounting. Thus, I closed the ticket.
If this doesn't work in OpenSIPS 2.3, please reopen.
