### ISSUE TITLE
No longer able to read statistics via fifo or mi_json in 2.3

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1157]
Previously (2.2.3) the statistics endpoints for individual stats, i.e. `tcp-load` were working.

As of 2.3.0 none of the stats in the documentation are functional;

```
{
    "error": {
        "code": 404, 
        "message": "Statistics Not Found"
    }
}

```
Statistics seem only to be retrieved via their parent classes now and can no longer be retrieved individually, the documentation here is now non-functional;

https://www.opensips.org/Documentation/Interface-CoreStatistics-2-3#toc15

**Comment by liviuchircu** [comment]
Seems to have been fixed in 1d9b6cd6b.

**Comment by hamid-elaosta** [comment]
Thanks @liviuchircu I'll take a look.

**Comment by hamid-elaosta** [comment]
Confirmed working in 2.3.1
