### ISSUE TITLE
System lockup if HEP via TCP endpoint is unavailable

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1161]
I have setup 2 HEP OpenSIP Servers with DNS round robin (A record only, low TTL).

The main SIP servers send SIP Traces to the 2 HEP OpenSIP servers via TCP.

If any of the HEP OpenSIP servers become unavailable, the main SIP Servers backlog and crash, they do not attempt to resolve the DNS records again, nor to they obey any max buffer limits.

It would be great if we could:
- expire messages in the send buffer to prevent the system crashing, and
- perform a resolve accordingly when attempting to reconnect or
- have the ability to balance, failover the HEP connection.

Using OpenSIPS 2.2.4

Regards Jonathan

**Comment by bogdan-iancu** [comment]
@digipigeon , do you have core file from the crash ?

**Comment by digipigeon** [comment]
Unfortunately I don't, I will try to get this shortly.

**Comment by bogdan-iancu** [comment]
@digipigeon, how reproducible is the crash ? Do you have a step by step actions list that triggers the crash ?

**Comment by digipigeon** [comment]
Every time #1165 happens, this problem happens within 5 minutes afterwards.

Lately its not being crashing (as I have been expecting), it just goes to a 10.00+ load average and stops responding to any requests.

**Comment by bogdan-iancu** [comment]
@digipigeon , sorry for the late reply. Are you still interested in following this up ? If yes, could you detail what exactly is are `buffer limits` ? what buffer are you referring to? Is the crash / load still reproducible?

**Comment by bcnewlin** [comment]
We recently experienced this issue. The SIP servers sending the traces all blocked trying to send HEP over TCP to our capture instances. They blocked against the TCP connections for over 5 minutes so the servers could not process any SIP.
