### ISSUE TITLE
OpenSIPS fails to exit gracefully on SIGTERM

### ISSUE THREAD

**Issue by sobomax** [OpenSIPS/opensips#1169]
Observing the following failure here with the latest 2.2.5 code, the OpenSIPS fails to react properly and exit gracefully upon receiving SIGTERM.

+kill -TERM 21031
+echo MM_PID: 21031
MM_PID: 21031
+wait 21031
Jul 25 05:42:07 [21046] CRITICAL:core:receive_fd: EOF on 10
Jul 25 05:43:07 [21031] CRITICAL:core:sig_alarm_abort: BUG - shutdown timeout triggered, dying...+MM_RC=134

Full log is here:

https://travis-ci.org/sippy/voiptests/jobs/257170795

This issue is not seen very often. This is Ubuntu, running on Travis:

+uname -a
Linux testing-docker-20060ded-6fbb-4d94-86a4-9e8aaf5021c8 4.8.12-040812-generic #201612020431 SMP Fri Dec 2 09:33:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bogdan-iancu** [comment]
Hi @sobomax , in this case, did OpenSIPS failed to actually start at all (due some startup errors ?). I see in the travis logs some errors:

Jul 25 05:41:28 [21037] ERROR:core:tcp_start_processes: failed to send 0 status code
Jul 25 05:41:28 [21038] ERROR:core:tcp_start_processes: failed to send 0 status code

**Comment by sobomax** [comment]
Well believe it or not but it actually runs. We are not enabling TCP at all that maybe why. Is probably another issue to be addressed separately.

Our config is below:

mpath="dist/opensips/modules/"
loadmodule "proto_udp.so"
loadmodule "sl/sl.so"
loadmodule "tm/tm.so"
loadmodule "rr/rr.so"
loadmodule "maxfwd/maxfwd.so"
loadmodule "dialog/dialog.so"
loadmodule "rtpproxy/rtpproxy.so"
loadmodule "textops/textops.so"
loadmodule "uri/uri.so"
modparam("rtpproxy", "rtpproxy_sock", "udp:127.0.0.1:22222")
listen=udp:127.0.0.1:5060
listen=udp:[::1]:5060
route {
    ## initial sanity checks -- messages with
    ## max_forwards==0, or excessively long requests
    if (!mf_process_maxfwd_header("10")) {
        sl_send_reply("483","Too Many Hops");
        exit;
    };
    if (msg:len >= 2048 ) {
        sl_send_reply("513", "Message too big");
        exit;
    };
    ## shield us against retransmits
    if (!t_newtran()) {
        sl_reply_error();
        exit;
    };
    if (method == "INVITE") {
        t_reply("100", "Trying");
        if (rtpproxy_offer("r")) {
            t_on_reply("1");
            if (!has_totag()) {
                t_on_failure("1");
            }
        };
    };
    if (method == "BYE") {
        rtpproxy_unforce();
    };
    record_route();
    if (loose_route()) {
        t_relay();
        exit;
    };
    if (src_port == 5061) {
        rewriteport("5062");
    } else {
        rewriteport("5061");
    };
    t_relay();
    ##rtpproxy_stream2uac("ringback", "10");
    exit;
}
onreply_route[1]
{
    if (status=~"(183)|2[0-9][0-9]") {
        if(!search("^Content-Length:[ ]*0")) {
            rtpproxy_answer("r");
            ##rtpproxy_stream2uas("ringback", "10");
        };
    };
}
failure_route[1]
{
    rtpproxy_unforce();
}

**Comment by bogdan-iancu** [comment]
So opensips starts, runs for a while and when you do shutdown (SIGTERM), the attendant process hangs in there.
And this happens from time to time ?

**Comment by sobomax** [comment]
@bogdan-iancu yes, that what happens except I think instead of hanging the master process (i.e. pid 21031 in my case) exits with non-zero code, which upsets the test. I am not sure if any of the children are left hanging. And you are correct that happens quite rarely, so I suspect some kind of race condition somewhere on SIGTERM delivery.

**Comment by bogdan-iancu** [comment]
@sobomax , the highest probability for something like this to happen is due a deadlock. During the shutdown procedure, the main/attendant process is sending TERM to all the other worker processes. Such a process may be terminated while holding a lock (like iterating some shared hash or list). After terminating the worker processes, the attendant is doing the cleanup and it may try to do some ops with the locks (even if there is no need as there is only by itself at that point) -> this results into a deadlock.
Checking the modules you are using, I identified the dialog module being the one of the module doing such problematic module destroy (using locks in the mod_destroy() callback). Let me make a patch to fix this and give it to you for testing.

**Comment by bogdan-iancu** [comment]
@sobomax , please see 160b42

**Comment by bogdan-iancu** [comment]
Such deadlocks are not possible any more starting with 2.4 where the shutdown is done via IPC and not by `kill`
