### ISSUE TITLE
Load Balancer module doesn't replicate load info to cluster

### ISSUE THREAD

**Issue by gitforxh** [OpenSIPS/opensips#1171]
Hi,

I'm trying to setup a load balancer cluster with two opensips servers serving as load balancer for a bunch of Asterisk servers.

```
[root@opensips-01 /]# opensipsctl fifo clusterer_list
Cluster:: 1
	Node:: 2 DB_ID=2 URL=bin:172.17.0.2:5566 Enabled=1 Link_state=Up      Next_hop=2 Description=ops02

[root@opensips-02 /]# opensipsctl fifo clusterer_list
Cluster:: 1
	Node:: 1 DB_ID=1 URL=bin:172.17.0.6:5566 Enabled=1 Link_state=Up      Next_hop=1 Description=ops01
```

When I make a call through node 1 of the cluster to Asterisk, the lb_list on node 1 shows 'load=1' on the first destination.
```
[root@opensips-01 /]# opensipsctl fifo lb_list
Destination:: sip:172.17.0.5:5060 id=2 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: asterisk max=300 load=1
Destination:: sip:172.17.0.3:5060 id=3 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: asterisk max=300 load=0
```

But lb_list on node 2 of the cluster still shows 'load=0' for this resource.
```
[root@opensips-02 /]# opensipsctl fifo lb_list
Destination:: sip:172.17.0.5:5060 id=2 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: asterisk max=300 load=0
Destination:: sip:172.17.0.3:5060 id=3 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: asterisk max=300 load=0
```

So now I make a second call through node 2, it will keep sending the call to the first destination, which is wrong, because the first destination actually has already loaded with a call, the second destination has zero load and should be chosen for the 2nd call.

I had a look at the lb_replication.c, it seems currently it only replicates the 'status' (enabled/disabled/shutdown) of the destinations, but not the 'load' of them. Is this something to be done or I am understanding it wrong?

Thanks.

**Comment by razvancrainea** [comment]
Hello!

Load balancer uses dialog profiles to keep track of the onging sessions. This means that if you replicate dialog profiles, you basically replicate the load. Therefore, the secret is to make the `load_balancer`'s resource shared. This can be achieved by adding the `/b` prefix to the resource (i.e. `asterisk/b`), both in the database and in the script (`lb_start("1", "asterisk/b")`).

You also need to instruct the dialog module to replicate profiles within the cluster:
```
modparam("dialog", "accept_replicated_profiles", 1)
modparam("dialog", "replicate_profiles_to", 1) 
```

I have just made a successful setup like this. Let me know how it goes for you.

Best regards,
Răzvan

**Comment by gitforxh** [comment]
Hi Răzvan,

Thanks very much for the reply!

I tried changing the resources to have the /b suffix like below:

mysql> select * from load_balancer where group_id=3;
+----+----------+---------------------+----------------+------------+-------------+
| id | group_id | dst_uri             | resources      | probe_mode | description |
+----+----------+---------------------+----------------+------------+-------------+
|  5 |        3 | sip:172.17.0.3:5060 | asterisk/b=300 |          0 | asterisk-02 |
|  4 |        3 | sip:172.17.0.5:5060 | asterisk/b=300 |          0 | asterisk-01 |
+----+----------+---------------------+----------------+------------+-------------+

After this, load balancer module doesn't even load the resources.

Do I need to use devel version of OpenSIPs to test? I'm currently using 2.3.1.

Thanks again!
Xiao

**Comment by razvancrainea** [comment]
Hi, Xiao!

That's weird - can you check if there are any errors in your code? It should work fine in 2.3.1 too.

Best regards,
Răzvan

**Comment by gitforxh** [comment]
Thanks for the quick reply Răzvan. Actually it was my bad, I had some entries in load_balancer table with both resource names as 'asterisk=300' and 'asterisk/b=300' which causes some duplication error. After removing the 'asterisk=300' one, I can see the load info are now shared between two nodes in the cluster.

Thanks very much for the help!
