### ISSUE TITLE
Siptrace logs binary message when using postgres as DB

### ISSUE THREAD

**Issue by MarcWeustink** [OpenSIPS/opensips#1173]
Ubuntu 16.04.3, Postgresql 9.5, OpenSips 2.3.1-1 installed as package from http://apt.opensips.org/

The msg entries written to the sip_trace table look like \x5245474953544552207369703a.....
(which is similar to the binary encoded text you use when writing a blobstring to mysql)

with a simple `update sip_trace set msg = convert_from(decode(right(msg, -2), 'hex'), 'sql_ascii') where msg like '\\x%' ` you can make this column readable (and usable by OpenSIPS-CP)

**Comment by rvlad-patrascu** [comment]
This commit: 36f43169e238a53f7c077832f4d968ca8be38b4f should fix this and write the messages directly as string into the DB.
