### ISSUE TITLE
mid_registrar. registrations failed after restart

### ISSUE THREAD

**Issue by YukkoSergey** [OpenSIPS/opensips#1177]
modparam("usrloc", "db_mode",   2)
modparam("mid_registrar", "mode", 2)
modparam("mid_registrar", "insertion_mode", 0)

I succesfully register a softphone. Then check the location table, AOR is written there OK. Restart opensips.
1. it stops to register the same softphone again. Request timeout.
2. it can crash
3. mysql logs sometimes start to show communication errors

Changing db_mode to 3 is impossible due to requirements of mid_registrar.

Deleting all records from location table before restart helps and softphone re-registers after restart just fine. 

Version of opensips 2.3.1-1
Centos. Installed from repo.

**Comment by liviuchircu** [comment]
Known issue. The initial mid_registrar release of `2.3` has no DB support - this will be added in `2.4`, along with a "location" table update.
