### ISSUE TITLE
Provisional Responses Handling, filtering and forcing / additional header ops functions

### ISSUE THREAD

**Issue by fsantulli** [OpenSIPS/opensips#1180]
I've improved the ability to handle, forcing or striping the 100rel tag from calls in b2b top hiding scenario.
If a call arrives and the invite has the 100rel request, the b2b_entities module takes track of it. On handling the invite, when the remote party ring backs, if the caller required the provisional responses and they do not come back from the callee, the module adds itself the require header and a self generated rseq number.
There are also two exported dialplan functions that on the invite side, suppress (answering and removing) or forces (generating if not present) the Require and the RSeq headers.

Database structure has been updated adding 4 flags: caller and callee RSeq numbers and prov_resp flags on both dialog and leg.

In the commits have also been added some useful functions to sipmsgops.

Documentation has been updated as scripts.

Please merge the pull request if you can.

There is still a bug in the b2b module related to cseq and rseq numbers handled as signed integers so just up to the value of 32767 and not as rfc states in a range of 2**31 (unsigned long) number.
I didn't yet fixed the issue as the changes involves core functions to be implemented str2ulong and ulong2str.

Best Regards.
-Federico Santulli

**Comment by bogdan-iancu** [comment]
@fsantulli  I assume this ticket is about the #1170 pull request ? I moved this description into the PR and I will close this ticket.
Thanks, Bogdan
