### ISSUE TITLE
mid_registrar: segfaults when using clusterer usrloc replications

### ISSUE THREAD

**Issue by rubbermaiden** [OpenSIPS/opensips#1183]
Hi guys.
I found some bugs in mid_registrar module when using clusterer usrloc replication.
When the module received REGISTER Updates or Expire the bug caused a segfault due a null pointer dereference on the remote Opensips via the the binary interface, just after receiving the USRLOC event.  So to replicate the bug you must have 2 Opensips servers running with clusterer mode replicating the USRLOC via binary interfaces.
Using GDB I found that the bug came from the file ulcb.c and fixed it. Basically I just added some validations to see if the mri wasn't NULL before freeing it.
Please feel free to validate it.
Thanks

The branch I did the changes is from the yesterday latest 2.4-dev one.

[ulcb.c.txt](https://github.com/OpenSIPS/opensips/files/1249645/ulcb.c.txt)

**Comment by liviuchircu** [comment]
Thanks for the report and patch, @rubbermaiden ! At least it doesn't crash and burn anymore, which is never bad.

Unfortunately, the mid_registrar data will currently be lost when replicating contacts via binary interface. Support for this is planned to be included in the upcoming DB-enhanced version of the mid_registrar, along with a corresponding usrloc DB schema update.

**Comment by rubbermaiden** [comment]
Hi Liviu.
I forgot to mention, but for me its working because I am also loading the registrar.so module and maybe this cause it update correctly the usrloc contacts.

**Comment by liviuchircu** [comment]
Absolutely, that should work. But the "mid_registrar hot backup" scenario won't work ;)
