### ISSUE TITLE
Sequential topology hiding message not fixed after call failover to backup cluster node

### ISSUE THREAD

**Issue by maklind** [OpenSIPS/opensips#1189]
I have set up an opensips cluster with two nodes. 

Both listen to udp vrrp interface (implemented with keepalived) and binary interface pointed to each other. 
```
listen=udp:{VRRP_IP}:5060
listen=bin:{OTHER_NODE_IP}:5062
```

clusterer db table:
```
id(int,auto) cluster_id(int) node_id(int) url(string) state(int) ls_seq_no(int) top_seq_no(int) no_ping_retries(int) priority(int) sip_addr(string,null) description(string,null)
1:1:1:bin\:{NODE1_IP}\:5062:1:0:0:3:30:NULL:Node 1
2:1:2:bin\:{NODE2_IP}\:5062:1:0:0:3:30:NULL:Node 2
```

Dialogs are replicated to this cluster on both cluster nodes:
```
modparam("dialog", "accept_replicated_dialogs", 1)
modparam("dialog", "replicate_dialogs_to", 1)
```

The load_balancer table has a single row with the address of another machine with a softphone:
`1:1:sip\:{SOFT_PHONE_IP}\:5060:pstn=32:0`

I am testing the setup by calling from another machine's softphone. Both softphones have the {VRRP_IP} set as the proxy.

The call works fine with either of the nodes: I can call, answer, pause and hang up.

The problem occurs when I disconnect the master node after the call has been established. What I expect is that the backup node takes over and handles pauses, resumes and the hang up. What happens is that backup node receives these requests, but relays them to himself until number of hops is exceeded:

1 node handles the call, pausing the call:
```
Sep  1 13:38:55 [29710] DBG:dialog:dlg_onroute: sequential request successfully processed (dst_leg=1)
Sep  1 13:38:55 [29710] DBG:dialog:run_dlg_callbacks: dialog=0x7f4626f29ac0, type=16
Sep  1 13:38:55 [29710] DBG:core:parse_headers: flags=ffffffffffffffff
Sep  1 13:38:55 [29710] DBG:core:parse_headers: flags=ffffffffffffffff
Sep  1 13:38:55 [29710] DBG:topology_hiding:topo_delete_vias: Delete via [Via: SIP/2.0/UDP {SOFT_PHONE2_IP}:5060;branch=z9hG4bK8009f26b6f8de711a3bf3176b242f38f;rport
]
Sep  1 13:38:55 [29710] DBG:dialog:fix_route_dialog: Fixing message. Next hop is Loose router
Sep  1 13:38:55 [29710] DBG:dialog:fix_route_dialog: Setting new URI to  <sip:service@{SOFT_PHONE_IP}> 
```

A call with failover to backup node, pausing the call:
```
Sep  1 13:35:13 [29538] DBG:dialog:dlg_onroute: sequential request successfully processed (dst_leg=1)
Sep  1 13:35:13 [29538] DBG:dialog:dlg_onroute: dialog_timeout: 21600
Sep  1 13:35:13 [29538] DBG:dialog:switch_cseqs: prev_cseq = 1 for leg 1
[...]
 DBG:tm:_reply_light: finished
Sep  1 13:35:13 [29538] DBG:core:parse_uri: parsed uri:
 type=1 user=<service>(7)
 passwd=<>(0)
 host=<{VRRP_IP}>(14)
 port=<>(0): 0
 params=<did=645.47fbc325>(16)
 headers=<>(0)
```
The missing part here is the run_dlg_callbacks.

When both nodes are still connected, the `opensipsctl fifo dlg_list` command shows identical information on both of them.
[inf_loop.txt](https://github.com/OpenSIPS/opensips/files/1283847/inf_loop.txt)
[ok.txt](https://github.com/OpenSIPS/opensips/files/1283848/ok.txt)

Route script:
```

route{
	xlog("\n\n\n\n\n\n\n\n||||||NEW ITERATION ||||||||");
	if (!mf_process_maxfwd_header("10")) {
    	sl_send_reply("483","Too Many Hops");
        exit;
    }

    if (has_totag() && is_method("INVITE|ACK|BYE|UPDATE")) {
            xlog("\n||||||HAS TO TAG |||||||| \n");
            if (topology_hiding_match()) {
                xlog("\n||||||SUCCESFUL TOPOLOGY HIDING MATCH|||||||| \n");
                if (is_method("BYE")&&  $DLG_status<= 2) { 
                #reject invalid BYE 
                send_reply("481","Dialog state does not allow BYE"); 
                exit; 
           } 
                route(RELAY);
                exit;
            }
		else {
			xlog("===============TOPOLOGY HIDING DID NOT MATCH====================");
			if ( is_method("ACK") ) {
				xlog("L_ERR", "============ METHOD ACK   ============");
                if ( t_check_trans() ) {
                	# non loose-route, but stateful ACK; must be an ACK after
                    # a 487 or e.g. 404 from upstream server
                    t_relay();
                    exit;
                } else {
                	xlog("L_ERR", "============ ACK WITHOUT MATCHING TRANSACTION ============");
                    # ACK without matching transaction ->
                    # ignore and discard
                    exit;
                }
            }
            sl_send_reply("404","Not here");
	    }
        exit;
    }

    #### INITIAL REQUESTS

    # CANCEL processing
    if (is_method("CANCEL")) {
    	if (t_check_trans())
        	t_relay();
            exit;
    }
    else if (!is_method("INVITE")) {
    	send_reply("405","Method Not Allowed");
        exit;
    }
	else {
		create_dialog();
	}

    if ($rU==NULL) {
    	# request with no Username in RURI
        sl_send_reply("484","Address Incomplete");
        exit;
	}

    t_check_trans();

    # preloaded route checking
    if (loose_route()) {
        xlog("L_ERR",
        "Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]");
        if (!is_method("ACK"))
        	sl_send_reply("403","Preload Route denied");
        exit;
    }

    # record routing
    record_route();

    do_accounting("log");

	topology_hiding("UC");	
    if ( !load_balance("1","pstn")) {
    	send_reply("500","No Destination available");
        exit;
    }


    t_on_failure("GW_FAILOVER");
    route(RELAY);
}


route[RELAY] {
    if (!t_relay()) {
		sl_reply_error();
    };
    exit;
}


failure_route[GW_FAILOVER] {
    if (t_was_cancelled()) {
            exit;
    }

    # failure detection with redirect to next available trunk
    if (t_check_status("(408)|([56][0-9][0-9])")) {
        xlog("Failed trunk $rd/$du detected \n");


    if ( load_balance("1","pstn") ) {

        t_on_failure("GW_FAILOVER");
        t_relay();
        exit;
    }

        send_reply("500","All GW are down");
    }
}


local_route {
    if (is_method("BYE") && $DLG_dir=="UPSTREAM") {

        acc_log_request("200 Dialog Timeout");

    }
}
```

**Comment by maklind** [comment]
The issue seems to be that when replicating the active dialogs to backup cluster node, the callback functions are not replicated.
When the master node goes down and sequential requests go to the backup node, it does not fix the message before relying it.
By debugging the opensips on master node and also looking at the logs I can say that at least this functions are registered as callbacks: topology_hiding:topo_delete_vias, dialog:fix_route_dialog, topology_hiding:topo_dlg_replace_contact.
When I hardcoded the topo_delete_vias and fix_route dialogs into the dlg_handlers.c file, the sequential requests started reaching the machine withe the sofpthone. (hardcoding the fix_route_dialog was not so trivial, so didnt try that). But this shows that the missing callbacks are indeed what is wrong.

So is this an actual bug or missing functionality in dialog replication, or have I configured something incorrectly?

**Comment by rvlad-patrascu** [comment]
Hi @maklind 
Thanks for the very nice report. There were indeed some issues with replicated dialogs and callbacks not being run in that case. Check out the latest versions of the master, 2.3 or 2.2 branches for the fix.

**Comment by maklind** [comment]
Hi @rvlad-patrascu
I tried it out and can confirm that a failover works now as intended.
However the opposite scenario doesnt work:
1. The master node in the cluster is already down and the backup node establishes a call.
2. The master node comes back and traffic gets redirected to it.
3. Sequential requests of the established call dont get a topology hiding match.

**Comment by rvlad-patrascu** [comment]
Which `db_mode` are you using for the dialog module? If the nodes don't save the dialogs in a shared DB it is normal that this scenario is not working. Since the master node is down when the call is established on the backup node, the master node can't receive the dialogs through BIN replication when they are created and thus, when it comes up, it can't match the sequential requests. We are planning to implement a sync on startup feature for dialog replication through clusterer in OpenSIPS 2.4.

**Comment by maklind** [comment]
I am using `modparam("dialog", "db_mode", 1)` with a separate machine that has the mysql service running.
The thing is that the node that takes over actually has the dialog in its list.

**Comment by maklind** [comment]
I managed to resolve the issue by instructing keepalived to stop opensips when entering FAULT state (taking the eth cable out) and starting it again when entering MASTER (will have no effect if transitioning from slave to master).
This way when the new node appears in network and gets elected as master, the opensips starts and loads the dialogs from the shared database.

So both the initial issue and the new one I had are resolved.

**Comment by rvlad-patrascu** [comment]
You could also have OpenSIPS load the dialogs from DB by triggering the [dlg_db_sync](http://www.opensips.org/html/docs/modules/2.4.x/dialog.html#idp5929152) MI command if you don't want a full restart.
