### ISSUE TITLE
Memory leak suspected in acc_extra, acc_logic and acc_vars

### ISSUE THREAD

**Issue by StellaTeam** [OpenSIPS/opensips#1190]
Hello,

Watching memory usage (because of an important previous leak), i discovered a probably new leak related to acc_extra, acc_logic and acc_vars.

It seems related to "failed" dialogs as, according to memory statistics, the allocation counters are almost half the number of failed dialogs.

I don't know if there is something i may have missed in freeing "acc" related commands.

Below are some counters (dialog and memory statistics) showing the allocated (and not released) memory.

Please let me know if i can give more informations in order to fix such memory allocation problem.

Thanks

First server (2 months runtime)

Dialog counter

dialog:active_dialogs:: 47
dialog:early_dialogs:: 3
dialog:processed_dialogs:: 697135
dialog:expired_dialogs:: 0
dialog:failed_dialogs:: 101706
dialog:create_sent:: 0
dialog:update_sent:: 0
dialog:delete_sent:: 0
dialog:create_recv:: 0
dialog:update_recv:: 0
dialog:delete_recv:: 0

Memory statistics (filtered):
Sep  8 17:11:03 ft-dc2 opensips[22583]: Sep  8 17:11:03 [22585]     1063512 : 55907 x [acc_logic.c: store_acc_table, line 1253]
Sep  8 17:11:03 ft-dc2 opensips[22583]: Sep  8 17:11:03 [22585]    10783272 : 55907 x [acc_extra.c: build_acc_extra_array, line 419]
Sep  8 17:11:03 ft-dc2 opensips[22583]: Sep  8 17:11:03 [22585]     5873616 : 55907 x [acc_logic.c: init_acc_ctx, line 1277]
Sep  8 17:11:03 ft-dc2 opensips[22583]: Sep  8 17:11:03 [22585]     8009000 : 251411 x [acc_vars.c: set_value_shm, line 147]

Second server (2 weeks runtime)

Dialog counters:

dialog:active_dialogs:: 48
dialog:early_dialogs:: 3
dialog:processed_dialogs:: 323849
dialog:expired_dialogs:: 0
dialog:failed_dialogs:: 48614
dialog:create_sent:: 0
dialog:update_sent:: 0
dialog:delete_sent:: 0
dialog:create_recv:: 0
dialog:update_recv:: 0
dialog:delete_recv:: 0

Memory statistics (filtered):
Sep  8 17:12:23 ft-th2 opensips[24021]: Sep  8 17:12:23 [24023]      547456 : 28586 x [acc_logic.c: store_acc_table, line 1253]
Sep  8 17:12:23 ft-th2 opensips[24021]: Sep  8 17:12:23 [24023]     4185000 : 130529 x [acc_vars.c: set_value_shm, line 147]
Sep  8 17:12:23 ft-th2 opensips[24021]: Sep  8 17:12:23 [24023]     5493512 : 28586 x [acc_extra.c: build_acc_extra_array, line 419]
Sep  8 17:12:23 ft-th2 opensips[24021]: Sep  8 17:12:23 [24023]     2996104 : 28586 x [acc_logic.c: init_acc_ctx, line 1277]

**Comment by liviuchircu** [comment]
Thank you for the nice report - this in itself already solves the problem by 50%. Could you also please include your OpenSIPS version? Thanks!

**Comment by StellaTeam** [comment]
The version is 2.4-dev from master branch on 2017/05/29.
I didn't see any issue about the leak nor any mention on module code about a potential leak fix, so i supposed nobody got it until now, i hope that hasn't been already fixed in an intermediate release.

**Comment by rvlad-patrascu** [comment]
Hi,
I've tried doing some tests but I can't reproduce the leak without some additional details. Could you provide the configuration script? You can send it to: vladp@opensips.org if privacy is an issue.

**Comment by StellaTeam** [comment]
Thank you @rvlad-patrascu I sent the configuration by mail.
Please let me know if i can help.

**Comment by rvlad-patrascu** [comment]
The memory leak was caused by inappropriate usage of the _do_accounting()_ function. You were trying to account CANCEL transactions but the [report_cancels](http://www.opensips.org/html/docs/modules/2.4.x/acc.html#idp5581232) modparam was not set. You should set this parameter to 1 and the leak should no longer happen.
Indeed OpenSIPS was not producing any warnings and furthermore memory was being allocated without any actual accounting being done. This commit aa32bf1b6909c8471eea8c2170a3a2a3f94be1cf fixed this and the function now immediately exits and properly logs the warning.

**Comment by StellaTeam** [comment]
@rvlad-patrascu Indead that was probably not easy to find.
Thank you for your job !
