### ISSUE TITLE
SIP registration problems with DST (Daylight Saving Time)

### ISSUE THREAD

**Issue by nud** [OpenSIPS/opensips#1196]
Opensips stores the registration "expires" timestamp as a DATETIME column in MySQL. But this field type is always using the system timezone and is not timezone aware itself.

It has the "funny" consequency of dropping all registrations immediately between "DST end time - registration timeout" and "DST end time".

Example (max_expires is set to 20 minutes):

Date will change from DST to not DST at 3:00 AM. it means that at 3:00 AM CEST we will now be at 2:00 CET. At 2:55 AM (CEST) opensips receives a REGISTER. It will hence set the expire time at 3:15 (CEST), which strftime will actually render as 2:15 (CET). Since timezone is not stored in MySQL's DATETIME field, when the value is read the next time before 3:00 AM (CEST) it will be understood as 2:15 AM (CEST) and opensips will happily discard / drop the record.

It means that the phone will not be reachable until it registers again, up to max_expires minutes after the timezone change happened.

It turns out the same problem has been fixed in kamailio in 2014: https://github.com/kamailio/kamailio/commit/cb6e934a591451c23f7736bd88ea5953cacd9ebf

We might provide a patch soon-ish.

**Comment by bogdan-iancu** [comment]
@nud , the proper fix for this issue will be store in DB the unix timestamp instead of datatime.. In this way we avoid any issue DST.

**Comment by bogdan-iancu** [comment]
@nud, the fix was pushed into master branch, unfortunately it cannot be backported to the stable released versions as it implies changes in the DB schema and table versions.
