### ISSUE TITLE
Double PAI Header parsing / sanity issue

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1197]
Hello

We have a case where the interconnected carrier is sending a double PAI header as follows
```
P-Asserted-Identity: <sip:+123123@example.com;user=phone;cpc=ordinary>,<tel:+123123;cpc=ordinary>
```
I have two issues with that.

1. Sanity check fails
2. I do not know how to normalise that because $ai variable is null.

That is the error I get

ERROR:core:parse_pai_header: bad P-Asserted-Identity header

Can that be fixed or is there any other way to overcome this?

OpenSIPs 2.2 latest from git

Regards

**Comment by apsaras** [comment]
Hello. 

Any update on that? 

Can you suggest any work around?

Regards

**Comment by bogdan-iancu** [comment]
Hi @apsaras , isn;t your report identical to #1134  ?

**Comment by apsaras** [comment]
Hello Bogdan.

Yes is the same issue. I am just mentioning as an extra, that Sanity check also fails.

**Comment by bogdan-iancu** [comment]
OK @apsaras , I moved the extra requirements in #1134 and merge the 2 tickets. Thanks for the report !
