### ISSUE TITLE
Bad handling of subsequent 18x responses with b2bua + topology hiding

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#120]
We have an issue with subsequent 18x series responses getting improperly handled by b2bua. In this case, we get a 183 session progress and properly prack it to a-leg and b-leg and then a subsequent 180 series ringing message that is forwarded to a-leg who pracks back to switch, but the switch never relays the prack to the b-leg and the call starts breaking down. See trace.

INVITE sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;transport=udp SIP/2.0
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;rport;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Allow-Events: message-summary, refer, dialog, line-seize, presence, call-info, as-feature-event
Max-Forwards: 70
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx
CSeq: 981162894 INVITE
Expires: 180
Organization: MetaSwitch
Supported: resource-priority, 100rel
Content-Length: 175
Content-Type: application/sdp
Allow: INVITE, ACK, CANCEL, BYE, REGISTER, OPTIONS, PRACK, UPDATE, SUBSCRIBE, NOTIFY, REFER, INFO, PUBLISH
Contact: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;isup-oli=00
P-Asserted-Identity: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060

v=0
o=- 601618818 601618818 IN IP4 xxx.xxx.xxx.xxx
s=-
c=IN IP4 xxx.xxx.xxx.xxx
t=0 0
m=audio 34280 RTP/AVP 0 101
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=sendrecv
SIP/2.0 100 Giving a try
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx
CSeq: 981162894 INVITE
Server: XXXX(XXXX) Edge-R1.6
Content-Length: 0

SIP/2.0 183 Session Progress
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20694
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
PRACK sip:10.0.0.21:5061 SIP/2.0
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;branch=z9hG4bK-7715d4904ec93d83f2e128c9044719281-xxx.xxx.xxx.xxx-1
Allow-Events: message-summary, refer, dialog, line-seize, presence, call-info, as-feature-event
Max-Forwards: 70
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162895 PRACK
RAck: 20694 981162894 INVITE
Organization: MetaSwitch
Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Supported: resource-priority, 100rel
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;branch=z9hG4bK-7715d4904ec93d83f2e128c9044719281-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162895 PRACK
Server: XXXX(XXXX)-R7.0
Content-Length: 0

SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
PRACK sip:10.0.0.21:5061 SIP/2.0
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;branch=z9hG4bK-2d077dfd0ea8701f9621f28419237e7b1-xxx.xxx.xxx.xxx-1
Allow-Events: message-summary, refer, dialog, line-seize, presence, call-info, as-feature-event
Max-Forwards: 70
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162896 PRACK
RAck: 20695 981162894 INVITE
Organization: MetaSwitch
Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Supported: resource-priority, 100rel
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;branch=z9hG4bK-2d077dfd0ea8701f9621f28419237e7b1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162896 PRACK
Server: XXXX(XXXX)-R7.0
Content-Length: 0

SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
SIP/2.0 180 Ringing
Record-Route: sip:10.0.0.21;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;did=ce12.faed9bb6
Record-Route: sip:10.0.0.4;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Record-Route: sip:xxx.xxx.xxx.xxx;r2=on;lr;ftag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=XXXX.327.212
CSeq: 981162894 INVITE
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,PRACK,UPDATE
Require: 100rel
RSeq: 20695
Init-CallID: XXXX.105.2168912
Contact: sip:10.0.0.21:5061
Server: XXXX(XXXX)-R7.0
Content-Length: 230

v=0
o=Sonus_UAC 19999 3390 IN IP4 4.55.23.35
s=SIP Media Capabilities
c=IN IP4 4.55.23.6
t=0 0
m=audio 17752 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=maxptime:20
SIP/2.0 503 Service Unavailable
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;received=xxx.xxx.xxx.xxx;rport=5060;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=155c340f586c28d0300cf5a6ccf90d99-7897
CSeq: 981162894 INVITE
X-RS-IP: 10.0.0.21
X-Reason: No more gateways
Server: XXXX(XXXX)-R7.2
Content-Length: 0

ACK sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;transport=udp SIP/2.0
Via: SIP/2.0/UDP xxx.xxx.xxx.xxx:5060;rport;branch=z9hG4bK-618f9ca8bbb77d02f9bd02a51a3ef48a1-xxx.xxx.xxx.xxx-1
Allow-Events: message-summary, refer, dialog, line-seize, presence, call-info, as-feature-event
Max-Forwards: 70
Call-ID: A6B917D0@xxx.xxx.xxx.xxx
From: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;tag=xxx.xxx.xxx.xxx+1+269d09+cfd30e3c;isup-oli=00
To: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx;tag=155c340f586c28d0300cf5a6ccf90d99-7897
CSeq: 981162894    ACK
Expires: 180
Organization: MetaSwitch
Supported: resource-priority, 100rel
Content-Length:   0
Contact: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060;isup-oli=00
P-Asserted-Identity: sip:+1405XXXXXXX@xxx.xxx.xxx.xxx:5060

**Comment by bogdan-iancu** [comment]
staying alive....
