### ISSUE TITLE
drouting OPTIONS pinging does not select the correct listen interface

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#1200]
I am using the drouting module with a gateway configured in the dr_gateways table.

OpenSIPS is listening on 2 interfaces like so:

```
listen=udp:10.0.0.1:5062
listen=udp:10.0.0.1:5060 AS 94.173.163.53:5060
```

The dr_gateways entry specifies a socket to use of udp:10.0.0.1:5060 for the gateway in question.

Calls (INVITEs) are routed correctly via the :5060 interface and the advertised IP of 94.173.163.53 is being substituted correctly.

However there is a problem with the generated OPTIONS messages by OpenSIPS. They are being sent from the :5062 interface, and as such the advertised address is not being substituted and the Via header contains the wrong IP and port information.

If I swap the listen lines around so that the aliased IP is at the top of the list the OPTIONS message starts to be generated correctly.

It looks like when sending OPTIONS messages that OpenSIPS is using the first listen= line that it comes across rather than using the socket column from dr_gateways.

I've tested this on latest master

**Comment by bogdan-iancu** [comment]
@petekelly , what version of OpenSIPS are you using ? does your dr_gateways table have a "socket" field ?

**Comment by bogdan-iancu** [comment]
check this for 2.3 - http://www.opensips.org/Documentation/Install-DBSchema-2-3#GEN-DB-DR-GATEWAYS

**Comment by petekelly** [comment]
@bogdan-iancu I'm using the latest master (2.4.x) and yes the socket is defined in the dr_gateways table - it is being respected for INVITE's but not for OPTIONS

**Comment by bogdan-iancu** [comment]
OK, let me double check on that

**Comment by bogdan-iancu** [comment]
@petekelly, if you run in debug mode, when the OPTIONS are sent out, you should see a log like:

DBG:tm:t_uac: sending socket is ........

Do you see there the configured socket ? or the wrong one ?

Also, btw, is there any proto difference between the 2 involved sockets ?

**Comment by bogdan-iancu** [comment]
any updates @petekelly  ?

**Comment by petekelly** [comment]
@bogdan-iancu  I need to build a lab machine and check your comments from 16th Oct

**Comment by bogdan-iancu** [comment]
ok, please update me when you get the data.

**Comment by bogdan-iancu** [comment]
I assume the socket definition (in DB, per gateway) had some syntax error (like URI format instead of listener format), so this attribute was discarded (during DR reload) and the first UDP listener was used. If this an issue, please reopen
