### ISSUE TITLE
topology_hiding generates invalid header param

### ISSUE THREAD

**Issue by lamSteven** [OpenSIPS/opensips#1201]
The Contact-header param th_contact_encode_param generated by the topology_hiding module is invalid as the param value is quoted.

Example:
Contact: <sip:x.x.x.x;thinfo="VG8SbzAdIFtiY2VCJBw3KzwIPjogWxBXcVphV2J9ZlpjQXJEYVtiZWZXY1QxHT4SJzI6DDVSIkQxA2JrbFZjViIWZ1MyZEJvJQszTmFZZn1gXX5ec1phUGNpYV9mXw==">

When OpenSIPS receives an request with an To-header based on the contact generated by the topology_hiding module, the debug reads:

[12936] ERROR:core:parse_to: unexpected char ["] in status 6: <<<sip:x.x.x.x;thinfo=>> .
[12936] ERROR:core:get_hdr_field: bad to header
[12936] DBG:core:set_err_info: ec: 1, el: 3, ei: 'error parsing To header'
[12936] DBG:core:get_hdr_field: error exit
[12936] INFO:core:parse_headers: bad header field
[12936] ERROR:uri:has_totag: To parsing failed

Also the padding of the base64 string with == can be a problem i think.

Steven

**Comment by bogdan-iancu** [comment]
@lamSteven , the parameter you mention there is a header parameter, not a URI parameter. Checking with the RFC3261, a quoted string is allowed in the value of a header param
```
generic-param  =  token [ EQUAL gen-value ]
gen-value      =  token / host / quoted-string
```

and `==` area allowed in a quoted string.

Do you have a pcap of the SIP message generating the reported parsing error ?

**Comment by bogdan-iancu** [comment]
@lamSteven , any chances to get the pcap ?

**Comment by vasilevalex** [comment]
Related to https://github.com/OpenSIPS/opensips/issues/1447. Fixed with https://github.com/OpenSIPS/opensips/pull/1448. I think, it can be closed.

**Comment by bogdan-iancu** [comment]
Thanks @vasilevalex
