### ISSUE TITLE
I started opensips failed and the log showed as below

### ISSUE THREAD

**Issue by danceinrain** [OpenSIPS/opensips#1202]
```
sip-router[41080]: CRITICAL:core:free_raw_fetch: #012>>> pkg_free() on non-pkg ptr 0x3feaa43fd7 - aborting!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
```

**Comment by danceinrain** [comment]
And I found the number  #12  appeared at :
    sip-router[25317]: NOTICE:regex:mod_init: loading pcres...
    sip-router[25317]: NOTICE:regex:load_pcres: num groups = 0     #012

**Comment by liviuchircu** [comment]
Hi @danceinrain, and thank you for the report. Please follow the [bug reporting guide](https://github.com/OpenSIPS/opensips/wiki/How-to-File-a-Bug-Report), so we can start narrowing down the problem.

**Comment by bogdan-iancu** [comment]
@danceinrain , any update here ? if not, we will expire and close this report.
