### ISSUE TITLE
Module Dialog modparam "profile_value_prefix" "profile_size_prefix" "profile_no_value_prefix" not correctly initialized when cachedb_url enable

### ISSUE THREAD

**Issue by Tinet-AaronAn** [OpenSIPS/opensips#1203]
in dialog.c  function mod_init cdb_val_prefix.len/cdb_noval_prefix.len/cdb_size_prefix.len should initialized before call init_cachedb_utils.

it should be changed like this:

static int mod_init(void)
...
...
	/* we are only interested in these parameters if the cachedb url was defined */
	if (cdb_url.s) {
		cdb_val_prefix.len = strlen(cdb_val_prefix.s);
		cdb_noval_prefix.len = strlen(cdb_noval_prefix.s);
		cdb_size_prefix.len = strlen(cdb_size_prefix.s);

		cdb_url.len = strlen(cdb_url.s);
		if (init_cachedb_utils() <0) {
			LM_ERR("cannot init cachedb utils\n");
			return -1;
		}
	}

**Comment by Tinet-AaronAn** [comment]
this bug will lead to wrong dlg_prefix name in cachedb.

**Comment by bogdan-iancu** [comment]
Thank you @Tinet-AaronAn for the good catch ! I pushed the fix you suggested on the all the maintained versions of OpenSIPS.
