### ISSUE TITLE
OpenSips 2.3.2 Registration of Multiple Contact with Identical Credentials

### ISSUE THREAD

**Issue by jalung** [OpenSIPS/opensips#1205]
Seeing an issue when user has multiple contacts and registration data is stored in Mongodb. 

1. All contacts get updated when one of them re-registers. Seems the port should be part of the "aor hash".
2. All contacts get deleted when remove() is used if all the contacts are on the same IP. Seems the port should be part of the criteria.
3. If multiple OpenSips share the same location table, each OpenSips will update contacts that are not registered to it.  It seems OpenSips should not attempt updating a contact unless it is registered on one of its sockets. Want to argue that this should also apply to lookup(), is_registered() and all similar routines that use the location table.

**Comment by razvancrainea** [comment]
Can you detail a bit more what is the problem you are facing, with some examples?

1. Not sure what hash you are talking about. An AOR does not contain a port, it only contains a user and a domain. Or are you using the same domain with different ports?

2. Contacts are never deleted based on IP, it is deleted either based on a contact id computed by OpenSIPS when the REGISTER is received, or if it expires based on the expiration time.

3. Why are you sharing the same location table if you don't want the instances to share the information between it? Why don't you just use different tables/collections for each instance?

As I said before, I am not sure I understand what is your problem unless you come with some examples of what is happening and what you are expecting to happen.

**Comment by jalung** [comment]
for item 1: 
This is the initial registration data for two UA's using the same credentials on the same instance.

`{ "_id" : ObjectId("5a3d129fe0ac1339bb62261c"), "contact_id" : NumberLong("20688410788233216"), "username" : "threezero", "contact" : "sip:threezero@77.77.77.77:53443;app-id=com.jamSIP.voip.prod;pn-type=apple;pn-tok=8BDB38350E0DEDB2380F5DFF54519D55411DCA1AB5AB6E64F877401590B7D9E0;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-call-snd=notes_of_the_optimistic.caf;pn-msg-snd=msg.caf;pn-timeout=0;pn-silent=1;transport=tcp", "expires" : ISODate("2017-12-22T15:11:43Z"), "q" : -1, "callid" : "kSFmBRYrwU", "cseq" : 29, "flags" : 0, "cflags" : "uas_ip4 NAT_BFLAG", "user_agent" : "JamSip_iPhone.6s.Plus_iOS10.3.3/3.16-33-gd230b892 (belle-sip/1.5.0)", "received" : "sip:77.77.77.77:53443;transport=tcp", "path" : null, "socket" : "tcp:222.222.222.222:5060", "methods" : null, "last_modified" : ISODate("2017-12-22T14:11:43Z"), "sip_instance" : "<urn:uuid:55e30e5d-0237-4cb1-b8ec-0fe765504583>", "attr" : "172.16.1", "domain" : "jamsip.net" }

{ "_id" : ObjectId("5a3d12e8e0ac1339bb62261d"), "contact_id" : NumberLong("20688410788233216"), "username" : "threezero", "contact" : "sip:threezero@77.77.77.77:46061;app-id=12121212121;pn-type=firebase;pn-tok=daBLT-JxP6Y:APA91bGPXxm1uFKZ2pyU8IMNb1AIH3wP1cKvbNY7NUrNGKu-z4AofhQAIv-7X_xB3sD_91ADRstJRsPOW1RFbvRjR7P9tCzTPFK1inDSWH56jURnPuvsT1hEArmPEXbOQaO3EnwcqZp6;pn-silent=1;transport=tcp", "expires" : ISODate("2017-12-22T15:12:56Z"), "q" : -1, "callid" : "r0shnXLSEL", "cseq" : 21, "flags" : 0, "cflags" : "uas_ip4 NAT_BFLAG", "user_agent" : "JamSipAndroid/1.3 (belle-sip/1.6.3)", "received" : "sip:77.77.77.77:46061;transport=tcp", "path" : null, "socket" : "tcp:222.222.222.222:5060", "methods" : null, "last_modified" : ISODate("2017-12-22T14:12:56Z"), "sip_instance" : "<urn:uuid:aa3d255b-6f42-4c35-85c8-8c65b9ea8749>", "attr" : "172.16.1", "domain" : "jamsip.net" }
`

This is the registration data for the UA's after one of them re-registers. Notice that nearly all the fields are updated in both contacts. This is not good because these fields are used in custom routines in the script based on the contact.

`{ "_id" : ObjectId("5a3d129fe0ac1339bb62261c"), "contact_id" : NumberLong("20688410788233216"), "username" : "threezero", "contact" : "sip:threezero@77.77.77.77:53443;app-id=com.jamSIP.voip.prod;pn-type=apple;pn-tok=8BDB38350E0DEDB2380F5DFF54519D55411DCA1AB5AB6E64F877401590B7D9E0;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-call-snd=notes_of_the_optimistic.caf;pn-msg-snd=msg.caf;pn-timeout=0;pn-silent=1;transport=tcp", "expires" : ISODate("2017-12-22T15:18:31Z"), "q" : -1, "callid" : "r0shnXLSEL", "cseq" : 23, "flags" : 0, "cflags" : "uas_ip4 NAT_BFLAG", "user_agent" : "JamSipAndroid/1.3 (belle-sip/1.6.3)", "received" : "sip:77.77.77.77:46061;transport=tcp", "path" : null, "socket" : "tcp:222.222.222.222:5060", "methods" : null, "last_modified" : ISODate("2017-12-22T14:18:31Z"), "sip_instance" : "<urn:uuid:55e30e5d-0237-4cb1-b8ec-0fe765504583>", "attr" : "172.16.1", "domain" : "jamsip.net" }

{ "_id" : ObjectId("5a3d12e8e0ac1339bb62261d"), "contact_id" : NumberLong("20688410788233216"), "username" : "threezero", "contact" : "sip:threezero@77.77.77.77:46061;app-id=12121212121;pn-type=firebase;pn-tok=daBLT-JxP6Y:APA91bGPXxm1uFKZ2pyU8IMNb1AIH3wP1cKvbNY7NUrNGKu-z4AofhQAIv-7X_xB3sD_91ADRstJRsPOW1RFbvRjR7P9tCzTPFK1inDSWH56jURnPuvsT1hEArmPEXbOQaO3EnwcqZp6;pn-silent=1;transport=tcp", "expires" : ISODate("2017-12-22T15:18:31Z"), "q" : -1, "callid" : "r0shnXLSEL", "cseq" : 23, "flags" : 0, "cflags" : "uas_ip4 NAT_BFLAG", "user_agent" : "JamSipAndroid/1.3 (belle-sip/1.6.3)", "received" : "sip:77.77.77.77:46061;transport=tcp", "path" : null, "socket" : "tcp:222.222.222.222:5060", "methods" : null, "last_modified" : ISODate("2017-12-22T14:18:31Z"), "sip_instance" : "<urn:uuid:aa3d255b-6f42-4c35-85c8-8c65b9ea8749>", "attr" : "172.16.1", "domain" : "jamsip.net" }
`
for item 2:
Answer to your question..
In the same manner as item 1, both these contacts are removed when "remove" is used.

for item 3:
Answer to your question..
I want the instances to control the number of contacts within a single location table, not share information per se. When using the same location table, it is pointless to do a "lookup" when UA's are behind NAT and could be registered on any instance. For the purpose, a lookup is not done, instead; the location info is used to build the branches and set the branch flags and $du. 
   
Opensips Version 2.1.5 works well for the aforementioned method,  all instances sharing the same location table was not a problem.

In version 2.3.2, items 1 & 2 are evident because of the new "contact_id" to identify contacts. It may work well in MySQL, but this issue not only present in mongoDB, but I suspect also for contacts stored in memory (if I were to do a lookup there). 

So the solution is to fix 1&2 and 3 is also solved. It needs to correctly identify the UA with multiple contacts in the memory cache.

Temp fix:
Currently using different location tables and using a hack to give each contact a different contact_id and controlling the number of contacts by script.

**Comment by jalung** [comment]
These patches resolve the issues specific to the case of multiple Openips sharing a single registration database in database DB_ONLY mode. I am submitting these for review as increasing the DB field size is not applicable to MYSQL.

The patches are numbered in the order in which they appear in the attached file.

Patches 1 & 9 especially should be pull requests.  

1. Removed 1 line of code as Opensips crashes when using mongodb (pkg_free() on memory not allocated by pkg_malloc )
2. Applicable to mongo db: contact strings with push notification data exceeds 255 characters
3. Applicable to mongo db: contact strings with push notification data exceeds 255 characters
4. Applicable to mongo db: contact strings with push notification data exceeds 255 characters
5. Fix Size errors
6-8. Fix multiple instances of the same user in DB 
9. Make the contact ID really unique: Fixing mutiple instances of the same user being assigned the same contact_id when on the same domain
10-19. Fix multiple instances of the same user in DB 
20-21. Fix Size errors
22. Replace DEPRECATED Mongodb function
[opensips-2.3.3.txt](https://github.com/OpenSIPS/opensips/files/2037426/opensips-2.3.3.txt)

**Comment by liviuchircu** [comment]
Hi, @jalung, and sorry for being slow on this! I've actually started dissecting your patches - there is a big mix-in of: bugs, correct fixes, unnecessary edits, adjusted buffer sizes for real-life use cases, etc.  And before I apply a patch, I have to understand the problem, not just "Fix Size errors".  I'm trying to come back with a conclusion asap.  Cheers!

**Comment by jalung** [comment]
Thanks. The biggest issue was that the contact_id was not unique for UA's using the same credentials on the same IP.  Deletes and updates were not working per UA but as batch.

**Comment by liviuchircu** [comment]
@jalung , my sincere apologies for leaving this PR behind.  **Two** years is quite a bit of time to get some feedback from your PR and I will strive to prevent this from happening in the future.  Meanwhile, here is how things have changed with regards to the changes you've proposed in your patch:

* starting with `3.1`, the [save()](https://opensips.org/html/docs/modules/3.1.x/registrar#func_save) function includes the option of matching contacts against a custom `Contact` header parameter.  See the `M<param>` matching flag.
* in `2.4`, there is full support for sharing usrloc contact data via a NoSQL database.  Make sure to read the ["full-sharing-cachedb"](https://opensips.org/html/docs/modules/3.1.x/usrloc.html#param_cluster_mode) clustering mode and all the related documentation.  There are also plenty of blog posts and tutorials, such as [this one](https://www.opensips.org/Documentation/Tutorials-Distributed-User-Location-Full-Sharing).  Initially, only MongoDB was supported as a NoSQL DB.
* in `3.0`, @rvlad-patrascu added support for Cassandra, so the usrloc can store its fully shared data over there as well.  The tutorial includes the DB schema as well, if you need it.

In short:  this direction towards NoSQL storage of runtime data has shifted our focus from the "SQL ONLY" mode, which we currently do minimal maintenance on or highly ever recommend using.  Moreover, over 90% of your patch logic is already implemented.  The only parts which are missing are the DB column size and `avpops` buffer adjustments, which I'm sure we can fix at any time.

**However**, in order to keep things clean in the upcoming `3.1` release, I will start an internal discussion regarding "SQL ONLY": if we decide to drop it, we definitely need to provide a 100% working alternative.  And an idea which I personally fancy is that we could extend `cachedb_sql` such that it can work on top of `"full-sharing-cachedb-cluster"`, effectively providing a NoSQL database which sits on top of MySQL, thus fully replacing "SQL ONLY", without us having to maintain even more code.

Closing here for now.  Cheers!
