### ISSUE TITLE
b2bua unenclosed To header

### ISSUE THREAD

**Issue by Edwin-Hoff** [OpenSIPS/opensips#1210]
When using the b2b_init_request("top hiding/p") the To header is generated without <> brackets:
To: sip:31123456789@domain.com

Also if I add ;user=phone, the header is presented in the same format:
To: sip:31123456789@domain.com;user=phone

Even if this is valid (RFC 3261), we found some sip clients that could not proces the To number anymore, in some cases we could switch to the Request URI. So hereby a feature request to enclose the To header with <> brackets anyway, just to prevent problems with buggy sip clients

**Comment by bogdan-iancu** [comment]
Hi @Edwin-Hoff , what is the way you add the "user" param ?

**Comment by Edwin-Hoff** [comment]
On the secundairy opensips server I use this statement, the result is sent to the B2Bua server which does the top hiding:
uac_replace_to("sip:$avp(phonenumber)@mydomain.tls;user=phone");

**Comment by bogdan-iancu** [comment]
@Edwin-Hoff , so you do 
> uac_replace_to("sip:$avp(phonenumber)@mydomain.tls;user=phone");
on opensips1 and than B2B on opensips2 , right ? All these resulting in
> To: sip:31123456789@domain.com;user=phone
?
What is the To header in the request after leaving opensips 1 ?

**Comment by Edwin-Hoff** [comment]
Before b2bua: To: <sip:+31123456789@1.2.3.4:5060> 
After b2bua:  To: sip:+31123456789@1.2.3.4:5060

Before b2bua: To: <sip:+31123456789@1.2.3.4:5060;user=phone> 
After b2bua:  To: sip:+31123456789@1.2.3.4:5060;user=phone

**Comment by bogdan-iancu** [comment]
In this case, the To header is already broken before B2B - in the incoming TO hdr the user param is already packed as a hdr param and not an URI param. So it is not B2B's fault.

**Comment by bogdan-iancu** [comment]
Could you provide a ngrep capture covering the incoming and outgoing traffic (relative to the b2b OpenSIPS) ? you can send it off ticket to bogdan at opensips dot org.

**Comment by vtzan** [comment]
Dear @bogdan-iancu 

I have verified that issue with b2bua on Opensips 2.4.1. I have this setup
SIP EDGE Proxy port 65060 -----> B2BUA port 65070 -----> SIP PROXY port 65080

Here is the INVITE leaving EDGE Proxy (To: is correct)
https://pastebin.com/en8gLQXF

and Here is the INVITE leaving B2BUA (To: is wrong)
https://pastebin.com/V0Lc5E49

B2BUA Server config is plain simple. I can provide config in private if you want.

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

Please mark this as valid.

thank you

**Comment by bogdan-iancu** [comment]
Dear @vtzan - the `To: sip:101@server.hostname:65060` is perfectly valid form RFC3261 pov. If there are no hdr parameter, the URI doesn;t have to be enclosed.
