### ISSUE TITLE
Got:   Invalid path: modules/db_unixodbc/con.c when cloning

### ISSUE THREAD

**Issue by stefancn** [OpenSIPS/opensips#1212]
Any ideas what the cause of this is ....  Tried to clone version 2.2 with same result.

Regards //

S.

**Comment by razvancrainea** [comment]
No idea. Is this happening everytime you are cloning? Is it a git error?
Also, what type of file system are you using?

**Comment by viperlong** [comment]
you clone it in windows environment，windows keep "con" as deviece name, and it can't be a file name.

**Comment by daniyalIbrahim** [comment]
So here's my analysis:

- the module i wanted to clone had other direct and indirect dependencies which were
not compatible with my under laying operating windows, i tried git clone and dot this error
- so i used docker pull image_of_module instead 


![Capture](https://user-images.githubusercontent.com/48337074/73618311-10ef2b80-4627-11ea-95b7-1de137fa2fb0.JPG)
