### ISSUE TITLE
opensips children lock

### ISSUE THREAD

**Issue by donazito** [OpenSIPS/opensips#1215]
Opensips version: 2.3

Running opensips some children process never exit and lock the CPU:

What's happened?

**top - 17:10:53 up 11 days,  6:24,  3 users,  load average: 2.05, 2.10, 2.08
Tasks: 201 total,   3 running, 198 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.6 us, 21.6 sy,  0.0 ni, 74.7 id,  0.1 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 15946636 total,   183004 free,   498872 used, 15264760 buff/cache
KiB Swap:  1046520 total,  1046328 free,      192 used. 14172304 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20765 opensips  20   0 4438460   9512   5964 R  99.7  0.1 109:09.62 opensips
20766 opensips  20   0 4438464   9396   5836 R  99.7  0.1 126:25.61 opensips
 9559 root      rt   0  192700  48456  34216 S   0.7  0.3 128:14.46 corosync**

**Comment by razvancrainea** [comment]
Please run the `opensipsctl trap` and send us the output.

**Comment by razvancrainea** [comment]
Actually not the output of the command, I am talking about the generated file.

**Comment by donazito** [comment]
Thanks for your response!

Please find attached gdb trap file.

The process locked is 20095


[gdb_opensips_20171121_100339.txt](https://github.com/OpenSIPS/opensips/files/1490686/gdb_opensips_20171121_100339.txt)

**Comment by liviuchircu** [comment]
What is your exact OpenSIPS version? (`opensips -V`) This looks like a bug that was fixed starting with `2.3.2`.

**Comment by donazito** [comment]
version: opensips 2.3.0 (x86_64/linux)

**Comment by donazito** [comment]
need to upgrade?

**Comment by liviuchircu** [comment]
Yes, please :)
