### ISSUE TITLE
mid_registrar  overwrite_all_contact_hostports error

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1218]
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31635]: forwarding REGISTER to main registrar ($ci=70TJAs3lrS-1GuaHiyrT2xAcnzGTZrLB)
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31635]: ERROR:mid_registrar:overwrite_all_contact_hostports: SCRIPT BUG - second attempt to change URI Contact
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31635]: ERROR:mid_registrar:mid_reg_req_fwded: failed to overwrite Contact URI

Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31636]: forwarding REGISTER to main registrar ($ci=70TJAs3lrS-1GuaHiyrT2xAcnzGTZrLB)
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31636]: ERROR:mid_registrar:overwrite_all_contact_hostports: SCRIPT BUG - second attempt to change URI Contact
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31636]: ERROR:mid_registrar:mid_reg_req_fwded: failed to overwrite Contact URI
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31636]: ROUTE TO REGISTRAR: [REGISTER] ru[sip:p1.3trunks.com] fu[sip:5280000@p1.3trunks.com] tu[sip:5280000@p1.3trunks.com] s[udp:49.92.183.35:11364] CID[70TJAs3lrS-1GuaHiyrT2xAcnzGTZrLB][TIME:21:25:20.837127]
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:get_match_token: a Contact from main registrar (sip:5280000@49.92.183.35:11363) is missing the 'rid' hf parameter
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:restore_reply_contacts: failed to get match token
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:mid_reg_resp_in: failed to overwrite Contact header field domain
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:get_match_token: a Contact from main registrar (sip:5280000@49.92.183.35:11363) is missing the 'rid' hf parameter
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:match_contact: failed to get match token
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:save_rpl_contacts: Contact 'sip:5280000@10.101.145.147:32900' not found in reply from main registrar!
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: ERROR:mid_registrar:mid_reg_resp_in: failed to process rpl contacts for AoR '5280000'
Nov 21 21:25:20 iZj6cgs5bd83lt62lv7repZ /opt/opensips/sbin/opensips[31633]: Reg REPLY FROM REGISTRAR: [REGISTER][200] <null> sip:5280000@p1.example.com to sip:5280000@p1.example.com {si[47.52.39.192:5060]} CID[70TJAs3lrS-1GuaHiyrT2xAcnzGTZrLB][TIME:21:25:20.843181]

my mid_registrar config is:
#### MidRegistrar module
loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 1) /* 0 = Contact mirroring / 1 = Contact throttling / 2 = AOR throttling */
modparam("mid_registrar", "outgoing_expires", 7200)
modparam("mid_registrar", "insertion_mode", 0) /* 0 = contact; 1 = path */
modparam("mid_registrar", "received_avp", "$avp(received_nh)")
#modparam("mid_registrar", "contact_match_param", "rid")

**Comment by liviuchircu** [comment]
My guess is that you are doing something like `fix_nated_contacts()` or `replace()` before calling `mid_registrar_save()` within your script. This is not supported, since only one Contact header modification can be done per each SIP request.

Regarding NAT traversal with mid_registrar: the current 2.3 does not support it, which we actually consider to be a bug. I have already merged the fix for it on the `master` mid_registrar (so you can test it out immediately if you can build from source), but I'd still like to make sure it does not introduce issues for a few more days before backporting it to `2.3`.

**Comment by futsystems** [comment]
thanks, i find the problem about keepalive with nat_traversal, that problem is the fix_contact as you say.
i will test the master branch.

**Comment by liviuchircu** [comment]
@futsystems , I have backported the mid-registrar support for routing to NAT'ed endpoints into `2.3` now as well. Closing for now, please open a new ticket if you run into any issues with the new code.
