### ISSUE TITLE
make menuconfig config file mpath

### ISSUE THREAD

**Issue by adivjoseph** [OpenSIPS/opensips#1225]
The default mpath points to 
"mpath=/usr/local/lib/opensips/modules/" 32 bit ARCH
when bulding on 64 bit ARCH (arch64, amd64, ...) mpath should be
"mpath=/usr/local/lib64/opensips/modules/" to work, no "# CUSTOMIZE ME" set.
Simple solution menuconfig/Makefile
```
$(EXEC_NAME): $(MENUCONFIG_FILES)
ARCH = $(shell uname -m | sed -e 's/.*64.*/64b/')
ifeq ($(ARCH),64b)
	sed -i "/mpath/c\mpath=/usr/local/lib64/opensips/modules/" configs/opensips_residential.m4
else
	sed -i "/mpath/c\mpath=/usr/local/lib/opensips/modules/" configs/opensips_residential.m4
endif
	$(CC) -o $(EXEC_NAME) $(CFLAGS) $^ $(MY_LDFLAGS)
```

**Comment by bogdan-iancu** [comment]
Hi @adivjoseph , thank for the report. How do in install OpenSIPS? Do you do local compiling ? if yes, do you use special settings (like prefix) when doing "make all" and "make install" ?

Also, could you output the "uname -a" from that machine ?
