### ISSUE TITLE
Error in processing of "Diversion" header

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1228]
Hello! While communicate with one SIP provider we find this bug.
Provider send INVITE to opensips with "Diversion" header:
```
Diversion: "84999999999"<sip:84999999999@10.23.0.5:5060>;reason=unconditional;privacy=off;counter=1,"4999999999"<sip:4999999999@10.23.0.5:5060>;reason=unknown;privacy=off;counter=1
```
Opensips cannot processing this header, but header is correct:
```
Dec  5 10:59:58 opensips /usr/sbin/opensips[22460]: ERROR:core:parse_to_param: unexpected char ["] in status 27: <<;reason=unconditional;privacy=off;counter=1,>> .
Dec  5 10:59:58 opensips /usr/sbin/opensips[22460]: ERROR:core:parse_to: unexpected end of header in state 27
```

If turn to RFC wee see this:
1) https://tools.ietf.org/html/rfc7544#section-4.2
```
Example:

   Diversion:
   <sip:diverting_user2_addr>;reason=user-busy;counter=1;privacy=full,
   <sip:diverting_user1_addr>;reason=unconditional;counter=1;privacy=off
```
2) https://tools.ietf.org/html/rfc3261#section-25.1
```
name-addr      =  [ display-name ] LAQUOT addr-spec RAQUOT
display-name   =  *(token LWS)/ quoted-string
```

Version opensips:
```
bash-4.2# opensips -V
version: opensips 2.1.3 (x86_64/linux)
git revision: 248c836
main.c compiled on 14:10:49 Jun 16 2016 with gcc 4.8.2
```

Can you help me with solve this problem? Thanks!

**Comment by bogdan-iancu** [comment]
Thanks @kertor for reporting this - indeed, the parser for the Diversion header does not expect to find a multi-body payload for the header .... A similar issue was reported for the PAI hdr in #1134
I'm evaluating a generic fix for all these cases. I will update on this.
