### ISSUE TITLE
RTP engine -- logic error while parsing options opensips not aware of

### ISSUE THREAD

**Issue by Jeffrey2019** [OpenSIPS/opensips#1232]
Dear Sir/ Madam
In parse_flags() function,
While(1) loop,

If pass one option with the same length defined in the switch case, the loop will break.

For exmaple, if pass an 4 characters length option not aware of, the while loop will break.

```
			case 4:
				if (str_eq(&key, "SRTP"))
					ng_flags->transport |= 0x101;
				else if (str_eq(&key, "AVPF"))
					ng_flags->transport |= 0x102;
				else
					break;
```

**Comment by razvancrainea** [comment]
The `break` keyword you indicated breaks the `switch`, not the `while` loop.
Is there an issue you are hitting? Can you give us more details?

**Comment by Jeffrey2019** [comment]
Dear Sir
You are right!
No issue hitting.
