### ISSUE TITLE
usrloc + clusterer + xmlrpc = crash

### ISSUE THREAD

**Issue by dronord** [OpenSIPS/opensips#1236]
OpenSIPS version 2.2.5
Configure two nodes cluster
Configure usrloc replication
Try ul_add by mi_xmlrpc_ng

CRITICAL:core:receive_fd: EOF on 11
INFO:core:handle_sigs: child process 15868 exited by a signal 11

**Comment by dronord** [comment]
OpenSIPS version 2.2.2 is OK

**Comment by rvlad-patrascu** [comment]
Hi,
This issue has been fixed on the 2.2 branch with: https://github.com/OpenSIPS/opensips/commit/fa52af6914c1a393e021ce69d8baceae6572b0b3. You should upgrade to the latest version of 2.2 from the repo.

**Comment by dronord** [comment]
OpenSIPS version 2.2.5 from yum.opensips.org on Centos 7.
This is another errror.
Fixed was replication by opensipsctl fifo ul_add.
Now xmlrpc_ng.

P.S. opensipsctl fifo ul_add also strange working. opensipsctl fifo ul_dump show truncated AOR in slave node. And opensipsctl fifo ul_dump locks in master.
Please tell me you have successfully works the following? :
opensipsctl fifo ul_add location ....
opensipsctl fifo ul_rm / ul_rm_contact location ...
opensipsctl fifo ul_dump

opensipsctl fifo ul_add location ....
opensipsctl fifo ul_dump

**Comment by rvlad-patrascu** [comment]
The issue I mentioned and the subsequent fix affect all the transport layers of the MI Interface, so it should be also valid for xmlrpc_ng as well as fifo.
So, to be more clear, I meant that you should get the nightly build which includes the latest changes (as the fix was done later that the initial release).
If it is an entire different problem, let me know.

**Comment by dronord** [comment]
Nightly build is okey.
Would you like a new release in 2.2?

**Comment by bogdan-iancu** [comment]
@dronord there will be a new minor release on the 2.2 branch in the next week, we will announce it shortly
