### ISSUE TITLE
 missing attributes in the event  E_UL_CONTACT_*

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1238]
contact's attr is not included in E_UL_CONTACT_INSERT argument.

when branch is generated by lookup ,then contact's attr fileld is passed into branch_route. we can get the attr filed in branch_route.

if branch is generated by t_inject_branches,then event's args do not have attr field,so we can not get attr field in branch_route.
maybe it is better for E_UL_CONTACT_INSERT event to supply contact's attr field.

**Comment by bogdan-iancu** [comment]
While looking into this I found a logical issue - even if it is easy to push the contact attribute into the event, it will be hard for EBR to expose it as AVP at script level with the right AVP name. As the AVP name used by the contact attributes is configurable via the registrar module (see attr_avp - http://www.opensips.org/html/docs/modules/2.3.x/registrar.html#idp5618896).
So EBR can expose the attribute string into the resume route, but not with the same name as the registrar module.
The attributes will be found as AVP "attr" - the AVP name is the same with the param name of the event.

**Comment by bogdan-iancu** [comment]
@futsystems , please see 3fb5817be092655da9347f58515eb9563de3d95c and 824e21c9688bc747f2a4b2225df3ef0b52d49c4b and let me know if it does the trick.

**Comment by futsystems** [comment]
@bogdan-iancu ,my current branch is 2.3,so let me do some testing on master branch later,any test result,i will post here.

**Comment by futsystems** [comment]
@bogdan-iancu i have test the master branch,on the fork_call route, we can get $avp(attr) same as the value setted in register route.
this feature is filled. awesome!

**Comment by bogdan-iancu** [comment]
@futsystems , that is great ! Let me review if all the docs were properly updated and I will close the ticket.
