### ISSUE TITLE
2.3 build problem with HP_MALLOC

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1240]
latest 2.3 cannot be built with HP_MALLOC:

In file included from ../../mem/hp_malloc_stats.h:30:0,
                 from ../../mem/hp_malloc.h:48,
                 from ../../mem/common.h:44,
                 from ../../mem/mem.h:41,
                 from sipstate.c:30:
sipstate.c: In function 'l_sipstate_getshminfo':
../../mem/shm_mem.h:198:44: error: expected expression before ']' token
 #define shm_lock(i)    lock_get(&mem_lock[i])
                                            ^
../../mem/../lock_ops.h:93:34: note: in definition of macro 'lock_get'
  #define lock_get(lock) get_lock(lock)
                                  ^
../../mem/shm_mem.h:621:2: note: in expansion of macro 'shm_lock'
  shm_lock(); \
  ^
sipstate.c:277:3: note: in expansion of macro 'shm_info'
   shm_info(&info);
   ^
../../mem/shm_mem.h:199:48: error: expected expression before ']' token
 #define shm_unlock(i)  lock_release(&mem_lock[i])
                                                ^
../../mem/../lock_ops.h:90:41: note: in definition of macro 'lock_release'
 #define lock_release(lock) release_lock(lock)
                                         ^
../../mem/shm_mem.h:623:2: note: in expansion of macro 'shm_unlock'
  shm_unlock(); \
  ^
sipstate.c:277:3: note: in expansion of macro 'shm_info'
   shm_info(&info);
   ^
../../Makefile.rules:25: recipe for target 'sipstate.o' failed
make[3]: *** [sipstate.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** wait: No child processes.  Stop.
Makefile:204: recipe for target 'modules' failed
make[2]: *** [modules] Error 2
make[2]: Leaving directory '/home/sa/build/opensips-23'
debian/rules:257: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/sa/build/opensips-23'
debian/rules:349: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by bogdan-iancu** [comment]
Hi @nikbyte, are you sure you do not have any other memory manager defined (along HP_MALLOC) in your Makefile.cong (like F_MALLOC ) ?

**Comment by nikbyte** [comment]
Yes, I'm sure. The problem is in LUA module because it uses shm_info(&info) function.
This function defined like:
#define shm_info(mi) \
do{\
    shm_lock(); \
    MY_MEMINFO(shm_block, mi); \
    shm_unlock(); \
}while(0)

but HP_MALLOC requires shm_lock/shm_unlock with parameter, but shm_info() define uses only shm_lock/shm_unlock without parameter.

**Comment by bogdan-iancu** [comment]
Thank you @nikbyte for the hint !!
