### ISSUE TITLE
osipsconfig on xenial from apt fails to write config files

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1242]
When attempting to dump the load-balancer config using osipsconfig in a clean install of Opensips 2.3.2-1 on Xenial from the apt repo;

Running as non-root causes the write to fail with no error shown, in fact no indication is given.
Running as root creates the empty file in /etc/opensips but does not write the content and fails with a basic error:

`Config generated : /etc/opensips/opensips_loadbalancer_2017-12-29_16:7:6.cfg =  FAILED. Press any key to continue`

Furthermore, due to permissions, it would be useful if the output directory could be configured so the file can be written to a location not requiring root privileges.

**Comment by bogdan-iancu** [comment]
Hi @hamid-elaosta ,
I tried to reproduce your reports:
* as non-root user, it is normal to fail to write the files as there are no permissions on the /etc/opensips directory. Still, I agree it should be nice to get a message about this (versus silently doing nothing)
* as a root user, I got the success message `Config generated : /etc/opensips/opensips_loadbalancer_2018-1-3_18:5:2
1.cfg =  SUCCESS. Press any key to continue` and the file is actually on disk. To be honest I see no reasons for the failures (maybe you do not have 'm4' installed on your system ?) . There is a curses.out file created for logging (by osipsconfig) in the local directory - could you check it for errors ?

**Comment by hamid-elaosta** [comment]
Hi @bogdan-iancu, thanks for the update.

I can confirm that installing "m4" resolves the issue and the file is written when running as root.
Given the outcome, I suggest the "bug" is that of documentation; I am running Opensips from the apt repo, and therefore have no external dependency/requirement knowledge (I'm not building from source therefore am unaware of and unlikely to install m4 without a hint).

My suggested solution would be an error message (perhaps in curses.out), similarly for lack of permissions, add one suggesting that generation failed due to lack of m4 being present.

"curses.out" showed no errors for either the permissions nor the missing m4 situation if that information is of use.

**Comment by bogdan-iancu** [comment]
OK, let me summarize : 
* the opensips package should have m4 as dependency
* the osipsconfig should properly check for m4 presence (when running from sources)
* better reporting of errors (on interface) on permission errors.

**Comment by hamid-elaosta** [comment]
That covers it I think.

**Comment by hex1848** [comment]
I just ran into this issue in debian buster with the opensips 2.4.6 deb packages.  Once I did an:

`apt-get install -y m4`

The issue went away.

**Comment by bogdan-iancu** [comment]
The fix is to display to the console the error output of running `m4` - this will give hints on what went wrong, like missing m4, no write permissions, etc.
