### ISSUE TITLE
opensips 2.3.2 on Centos 6.6 - Core created after upgrade from 2.2 to 2.3.2

### ISSUE THREAD

**Issue by JonHVU** [OpenSIPS/opensips#1244]
[Debugoutput.txt](https://github.com/OpenSIPS/opensips/files/1597945/Debugoutput.txt)
Hi Guys,

We have been running with opensips 2.2 for a while now, and I want to do event routing so I am looking to upgrade to 2.3.

However when I have updated (from git) 

, as soon as an invite hits opensips it generates a core;

Jan  2 15:32:50 HPBXProxy1-beta HAPBXProxy1[2569]: CRITICAL:core:build_req_buf_from_sip_req: #012>>> len mistmatch : calculated 1206, written 1198#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2601]: CRITICAL:core:receive_fd: EOF on 50
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2555]: INFO:core:handle_sigs: child process 2569 exited by a signal 6
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2555]: INFO:core:handle_sigs: core was generated
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2555]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2599]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2593]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2591]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2567]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2558]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2557]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2561]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2581]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2583]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2587]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2585]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2579]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2564]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2559]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2572]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2562]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2560]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2597]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2565]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2573]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2566]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2570]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2589]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2601]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2575]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2571]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2577]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2595]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2563]: INFO:core:sig_usr: signal 15 received
Jan  2 15:33:05 HPBXProxy1-beta HAPBXProxy1[2555]: INFO:core:cleanup: cleanup

And in this case the core file is created, and I am running a BT full on it using gdb version 7.9

-rw-------.   1 root root 140517376 Jan  2 15:33 core.2569
[root@HPBXProxy1-beta /]# /sbin/opensips -V
version: opensips 2.3.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 01c078d
main.c compiled on 11:44:37 Jan  2 2018 with gcc 4.4.7
[root@HPBXProxy1-beta /]# /usr/local/bin/gdb /sbin/opensips core.2569

The output is attached.

Please can you advise?

Many thanks

Jon

**Comment by JonHVU** [comment]
Hi Bogdan, 

Thanks for the response.
Sure I can share whatever you need just let me know what you want and will upload/transfer to you.

In terms of reproducing it seems to be any outbound call from a registered device, inbound interestingly doesnt produce the issue.

Thanks

Jon

**Comment by bogdan-iancu** [comment]
@JonHVU, please provide (off ticket, use bogdan at opensips dot org) the minimal opensips.cfg that produces this cfg and the pcap of the inbound requests that triggers the crash - I will try to reproduce it on my side. Thank you for your effort and support !

**Comment by JonHVU** [comment]
@bogdan-iancu  thanks email on its way to you!
