### ISSUE TITLE
Opensips 2.4.0-dev REST_POST misbehavior

### ISSUE THREAD

**Issue by goharahmed** [OpenSIPS/opensips#1247]
Hi,
I've upgraded my opensips from 2.2.x to 2.4 version for testing and rest_client module has different results from older version. 

If I make a rest_post() query to the URL then the $var(body) contains the whole HTTP message along with the body eg:

`xlog("L_INFO","[XLOG-API] HTTP SERVER Body:$var(body) \n");`

Prints: 

`[XLOG-API] HTTP SERVER Body:HTTP/1.1 200 OK#015#012Date: Wed, 03 Jan 2018 18:56:44 GMT#015#012Content-Type: text/plain;charset=UTF-8#015#012Server: Apache#015#012Content-Length: 4#015#012#015#012PASS`

While the same line on older version Prints:

`[XLOG-API] HTTP SERVER Body:PASS`

VERSION:
```
version: opensips 2.4.0-dev (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: d1a4419
main.c compiled on 18:03:59 Dec  2 2017 with gcc 4.8
```

Kindly advise is there is any discrepancy in my script usage or bug in the backend code.

**Comment by liviuchircu** [comment]
Thank you for the report! It seems commit c549e6ec0 broke it. Will provide a fix asap.

**Comment by goharahmed** [comment]
Thats amazing how quick you were able to find out the anomaly. I'll be
waiting for the fix.

Thanks and awesome work.

**Comment by goharahmed** [comment]
@liviuchircu GOod day again; is there any easy way I can revert the commit and re-compile to continue with my opensips-script testing? Also Im curious to known the HEP tracing of the HTTP queries functionality; don't see any reference to enable/disable that in the module-documentations so far.

**Comment by liviuchircu** [comment]
The enable/disable parts for different traffic you may want to trace all belong to the `siptrace` module.

**Comment by liviuchircu** [comment]
@goharahmed you only need to remove [line 852](https://github.com/OpenSIPS/opensips/blob/master/modules/rest_client/rest_methods.c#L852) from `modules/rest_client/rest_methods.c`, and the output pvar should go back to the correct behavior. I just want to clarify things with Ionut before I push the fix myself.

**Comment by goharahmed** [comment]
Commenting that line worked 100% for me. 
Thanks for the accurate and timely help.
