### ISSUE TITLE
Memory counters overflow in 2.3 + HP_MALLOC

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1251]
2.3 + HP_MALLOC can show something like
pkmem:6-free_size:: 18446744073674133680
in statistics after memory is over.

**Comment by razvancrainea** [comment]
Do you still get this with 2.4?

**Comment by nikbyte** [comment]
Sometimes.

**Comment by liviuchircu** [comment]
According to the HP_MALLOC fix-series starting with fc9344a5b22d, all HP_MALLOC memory stat tracking issues are now fixed and backported down to `2.4`.  Closing at last :)
