### ISSUE TITLE
Documentation clarification - dispatcher module

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#1267]
Hi Bogdan

A reminder as requested about the docs for dispatcher module:

The dispatcher module DB structure uses a "status" column to hold the current (and initial) GW status. This can be 0,1,2 which differs from the normal a/i/p within the module.

Could the  mappings between 0,1,2 and a/i/p be documented on the modules page please, to reduce ambiguity (and confusion, probably on my part only here ;) )

Pete

**Comment by bogdan-iancu** [comment]
It seems to actually be such a mapping in the docs:
http://www.opensips.org/html/docs/modules/2.3.x/dispatcher.html#idp5684864
Nevertheless, it is too obscure, I admit. Ideally a new section should be added about the possible statuses of the destinations.
Also, I will push the mapping description in the DB description too

**Comment by bogdan-iancu** [comment]
a bit more on this....checking more into code/docs, I found some inconsistency. If in the code when operating via MI or script functions the conventions is 0=inactive, 1=active, 2=probing, in DB there is a different conventions: 0=active, 1=inactive, 2=probing (see http://www.opensips.org/Documentation/Install-DBSchema-2-3#AEN4379).
I checked the code and the documentation is in sync with the code. But I guess this is very very prone to confusions and errors.
