### ISSUE TITLE
opensips-2.3.3 crash on $cgr variable handling 

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#1268]
version: opensips 2.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 00:00:55 Jan 19 2018 with gcc 4.8.5

(latest from yum repo)

I'm trying to do some auth/accounting via cgrates module and it seems opensips crashes every time i try to add some $cgr(name) variables into the script. Without that variables it works great, but if i add at least one variable with any name - it immediately crashes on its handling.
Could you check whats wrong, please.
bt full's output is in the attachment: 

[bt_full.txt](https://github.com/OpenSIPS/opensips/files/1678437/bt_full.txt)

Thanks!

**Comment by achalkov** [comment]
any information about what to do with it?

**Comment by razvancrainea** [comment]
Just committed a fix on master and 2.3. If this does not sort out your problem, please reopen the ticket.

**Comment by achalkov** [comment]
thanks, Razvan! i'll try to test tomorrow

**Comment by achalkov** [comment]
i've just tested problem case and it looks like all works fine now
