### ISSUE TITLE
ERROR:core:fm_malloc: not enough free shm memory

### ISSUE THREAD

**Issue by VuDn5** [OpenSIPS/opensips#1272]
Hello everybody!  
i am Vu( Wu) and i from Viet Nam.
My systems installed opensips 2.3.2  and it's crash loop 1 times/3 days.  Opensips anoucement like that: 
`ERROR:core:fm_malloc: not enough free shm memory (0 bytes left, need 48), please increase the "-m" command line parameter!
Feb  2 15:10:31 DB-MobiCall /sbin/opensips[533]: ERROR:usrloc:shm_str_dup: no shared memory left
Feb  2 15:10:31 DB-MobiCall /sbin/opensips[533]: ERROR:usrloc:new_ucontact: no more shm memory
Feb  2 15:10:31 DB-MobiCall /sbin/opensips[533]: ERROR:usrloc:mem_insert_ucontact: failed to create new contact
Feb  2 15:10:31 DB-MobiCall /sbin/opensips[533]: ERROR:usrloc:insert_ucontact: failed to insert contact
Feb  2 15:10:31 DB-MobiCall /sbin/opensips[533]: ERROR:registrar:insert_contacts: failed to insert contact`
....
And opensips still alive but only loop:
....
`Feb  2 16:26:57 DB-MobiCall /sbin/opensips[539]: ERROR:core:tcpconn_new: shared memory allocation failure
Feb  2 16:26:57 DB-MobiCall /sbin/opensips[539]: ERROR:core:handle_new_connect: tcpconn_new failed, closing socket
Feb  2 16:26:57 DB-MobiCall /sbin/opensips[539]: ERROR:core:fm_malloc: not enough free shm memory (32 bytes left, need 368), please increase the "-m" command line parameter!`

....
nothing working and i don't know what is cause of problem. How can i fix it? that is bug? and why it's  happened?   thanks for read.
regards,
Vu

**Comment by bogdan-iancu** [comment]
Hi @VuDn5 - you mentioned the word "crash" - this means opensips processes terminate ? or is it still running but without handling traffic ?
Maybe OpenSIPS simply ran out for shared memory and it cannot handle more traffic. Try to run "opensipsctl fifo get_statistics shmem: " once you start getting the above errors.

**Comment by VuDn5** [comment]
Hi @bogdan-iancu- opensips" is it still running but without handling traffic",
 why it occur?  i don't wan't to encounter error and how can i wary or alert it? Do not let that happen again, please!  my systems can't die 1/3 days!   
Thanks @bogdan-iancu for you help!

**Comment by bogdan-iancu** [comment]
@VuDn5, no need to panic - take a deep breath and follow my indications :) 
Have you ran "opensipsctl fifo get_statistics shmem: " once you started getting the above errors ?

**Comment by VuDn5** [comment]
@bogdan-iancu  , I just calm down!  ^-^, the system is still alive but i will update topic if it occur again!   
is output of you command:
`shmem:total_size:: 33554432
shmem:used_size:: 6208960
shmem:real_used_size:: 6889832
shmem:max_used_size:: 6918384
shmem:free_size:: 266646` 

(right now, system is working).
Thanks @bogdan-iancu ! ^-^

**Comment by bogdan-iancu** [comment]
I see you configured 32M of shared memory, which for a production system may be a bit too low. But of course, it depends on the nature of your traffic and service.
Also the stats shows the you used maximum ~7M so far (see shmem:real_used_size value).
Keep monitoring this value (shmem:real_used_size) to see if you see an increasing value in time.

**Comment by VuDn5** [comment]
how i increasing the shm values?   if values continuous increase which is overloads in one day?   because my systems restart too much times and my boss don't like that!   ^-^  Thanks

**Comment by bogdan-iancu** [comment]
There is the `-m` command line parameter to configure the amount of shared memory. See `opensips -h` for details. So try to start with `-m 512` to have opensips starting with 512M (0.5G) of shared mem

**Comment by VuDn5** [comment]
`opensipsctl restart -m 4096 `
i run
`opensipsctl fifo get_statistics shmem:`
but output bellow:
`shmem:total_size:: 33554432
shmem:used_size:: 3542288
shmem:real_used_size:: 3709032
shmem:max_used_size:: 3737688
shmem:free_size:: 29845400
shmem:fragments:: 5408`

nothing values change!??

**Comment by bogdan-iancu** [comment]
How is your opensips installed ? Packages ?

**Comment by VuDn5** [comment]
i installed it from Packages 
` yum install opensips opensips-db_mysql.x86_64 opensips-rtpengine.x86_64 opensips-topology_hiding.x86_64 opensips-redis.x86_64 opensips-proto_wss.x86_64 opensips-proto_ws.x86_64 opensips-proto_tls.x86_64 opensips-tls_mgm.x86_64 opensips-rest_client.x86_64 opensips-proto_hep.x86_64 opensips-b2bua.x86_64
`
Have a diffenrent Packages and build source?

**Comment by bogdan-iancu** [comment]
OK, check in `/etc/defaults/opensips` file and change `S_MEMORY=64` value to what you need. And do not forget to restart opensips.

**Comment by VuDn5** [comment]
Unfortunately, no file opensips in > /etc/defaults/. In directory only have" useradd" and "nss"- nothing more.   Also, i can not find S_MEMORY in" opensipsctlrc", " osipsconsolerc", " opensips.cfg" else any places.  @bogdan-iancu

**Comment by bogdan-iancu** [comment]
@VuDn5 , I feel you lack some basics in working with a linux machine.....this will make difficult to operate your opensips. Check for the `/etc/sysconfig/opensips` file and change the S_MEMORY option

**Comment by VuDn5** [comment]
i think you understand me, I changed contend in file /etc/sysconfig/opensips before
`#
# OpenSIPS startup options
#

# Amount of shared memory to allocate for the running OpenSIPS server (in Mb)
S_MEMORY=4096

# Amount of pkg memory to allocate for the running OpenSIPS server (in Mb)
P_MEMORY=512

# Any additional OpenSIPS options
OPTIONS=""
~                 `
but ouput still not change after restart opensips,.
`shmem:total_size:: 33554432
shmem:used_size:: 3585192
shmem:real_used_size:: 3753928
shmem:max_used_size:: 3753928
shmem:free_size:: 29800504
shmem:fragments:: 5616
`
In cent os 6, i just writed S_MEMORY=4096  in file /etc/init.d/opensips, restart and done. but it's don't simple like that in cent os 7.      And for give me about my level used linux. Thanks @bogdan-iancu

**Comment by VuDn5** [comment]
Sorry @liviuchircu i change 
`[Unit]
Description=OpenSIPS is a very fast and flexible SIP (RFC3261) server
After=network.target mysqld.service postgresql.service rtpproxy.service

[Service]
Type=forking
User=opensips
Group=opensips
Environment=P_MEMORY=4096 S_MEMORY=4096
EnvironmentFile=-/etc/sysconfig/opensips
PIDFile=/var/run/opensips/opensips.pid
ExecStart=/usr/sbin/opensips -P /var/run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS
ExecStartPre=/usr/sbin/opensips-m4cfg
Restart=always
TimeoutStopSec=30s
LimitNOFILE=262144

[Install]
`

but it's notthing change at all.
`shmem:total_size:: 33554432
shmem:used_size:: 3623368
shmem:real_used_size:: 3798152
shmem:max_used_size:: 3841768
shmem:free_size:: 29756280
shmem:fragments:: 5744`


thanks for you help!

**Comment by liviuchircu** [comment]
These are all possible changing points, and `/etc/sysconfig/opensips` worked for me on a fresh CentOS 7.3 install, as you can see (here)[http://chunk.io/liviuc/e1da345daf324cfdbd05fd46b500f707].

**Comment by liviuchircu** [comment]
Maybe the values you are setting are too high. Try something like `S_MEMORY=256`, `P_MEMORY=16`, and see if it works.

**Comment by VuDn5** [comment]
dear @liviuchircu ! 
`[root@localhost opensips]# yum install opensips
Loaded plugins: fastestmirror
Repository home_kamailio_v4.4.x-rpms is listed more than once in the configuration
CityFan                                                  | 2.9 kB     00:00     
base                                                     | 3.6 kB     00:00     
epel/x86_64/metalink                                     | 6.0 kB     00:00     
epel                                                     | 4.7 kB     00:00     
extras                                                   | 3.4 kB     00:00     
home_kamailio_v4.4.x-rpms                                | 1.3 kB     00:00     
mysql-connectors-community                               | 2.5 kB     00:00     
mysql-tools-community                                    | 2.5 kB     00:00     
mysql57-community                                        | 2.5 kB     00:00     
openresty/7/x86_64/signature                             |  490 B     00:00     
openresty/7/x86_64/signature                             | 2.9 kB     00:00 !!! 
opensips                                                 | 1.5 kB     00:00     
opm                                                      | 2.9 kB     00:00     
updates                                                  | 3.4 kB     00:00     
(1/3): epel/x86_64/updateinfo                              | 900 kB   00:00     
epel/x86_64/primary_db         FAILED                                           
https://mirrors.tuna.tsinghua.edu.cn/epel/7/x86_64/repodata/09a27c6f2be460803b31afa82627def106e62024409faec50705d3cfbdb2f99d-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

(2/3): epel/x86_64/primary_db                              | 6.3 MB   00:00     
(3/3): CityFan/7/x86_64/primary_db                         | 467 kB   00:02     
Loading mirror speeds from cached hostfile
 * base: mirror.digistar.vn
 * epel: mirror.pregi.net
 * extras: mirror.digistar.vn
 * updates: mirror.digistar.vn
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
--> Running transaction check
---> Package opensips.x86_64 0:2.3.3-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch            Version              Repository         Size
================================================================================
Installing:
 opensips          x86_64          2.3.3-1.el7          opensips          2.6 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 2.6 M
Installed size: 8.1 M
Is this ok [y/d/N]: y
Downloading packages:
opensips-2.3.3-1.el7.x86_64.rpm                            | 2.6 MB   00:03     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : opensips-2.3.3-1.el7.x86_64                                  1/1 
  Verifying  : opensips-2.3.3-1.el7.x86_64                                  1/1 

Installed:
  opensips.x86_64 0:2.3.3-1.el7                                                 

Complete!
[root@localhost opensips]# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 33554432
shmem:used_size:: 3206248
shmem:real_used_size:: 3264320
shmem:max_used_size:: 3264472
shmem:free_size:: 30290112
shmem:fragments:: 1014
[root@localhost opensips]# opensipsctl restart -m 4096

INFO: Restarting OpenSIPS : 
INFO: stopped

INFO: Starting OpenSIPS : 
INFO: started (pid: 30298)
[root@localhost opensips]# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 33554432
shmem:used_size:: 3206248
shmem:real_used_size:: 3264320
shmem:max_used_size:: 3264472
shmem:free_size:: 30290112
shmem:fragments:: 1014
[root@localhost opensips]# vim /etc/sysconfig/opensips
[root@localhost opensips]# tail /etc/sysconfig/opensips
#

# Amount of shared memory to allocate for the running OpenSIPS server (in Mb)
S_MEMORY=128

# Amount of pkg memory to allocate for the running OpenSIPS server (in Mb)
P_MEMORY=128

# Any additional OpenSIPS options
OPTIONS=""
[root@localhost opensips]# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 33554432
shmem:used_size:: 3206248
shmem:real_used_size:: 3264320
shmem:max_used_size:: 3264472
shmem:free_size:: 30290112
shmem:fragments:: 1014
[root@localhost opensips]# 
[root@localhost opensips]# vim /usr/lib/systemd/system/opensips.service
[root@localhost opensips]# tail /usr/lib/systemd/system/opensips.service
PermissionsStartOnly=yes
PIDFile=%t/opensips/opensips.pid
ExecStart=/usr/sbin/opensips -P %t/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS
ExecStartPre=/usr/sbin/opensips-m4cfg
Restart=always
TimeoutStopSec=30s
LimitNOFILE=262144

[Install]
WantedBy=multi-user.target
[root@localhost opensips]# opensipsctl fifo get_statistics shmem:
\shmem:total_size:: 33554432
shmem:used_size:: 3206248
shmem:real_used_size:: 3264320
shmem:max_used_size:: 3264472
shmem:free_size:: 30290112
shmem:fragments:: 1014
[root@localhost opensips]# opensipsctl restart

INFO: Restarting OpenSIPS : 
INFO: stopped

INFO: Starting OpenSIPS : 
INFO: started (pid: 30445)
[root@localhost opensips]# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 33554432
shmem:used_size:: 3206248
shmem:real_used_size:: 3264320
shmem:max_used_size:: 3264472
shmem:free_size:: 30290112
shmem:fragments:: 1014
[root@localhost opensips]# 
`


so, what i can do to change shmem:total_size:: ?  And shmem:used_size  is still increase, oneday the opensips become overload and crash?

**Comment by liviuchircu** [comment]
I think `opensipsctl restart` may be broken. Can you please do a `ps aux | grep opensips` and see if it starts multiple times? The `2.3+` code does not perform an exclusive UDP interface bind, allowing subsequent instances to do the same thing.

If the answeris "yes", please only restart opensips using `systemctl restart opensips`, like I did in my example.

**Comment by VuDn5** [comment]
dear @liviuchircu !  My opensips just  only restart by  _opensipsctl restart_ . this is a _/usr/lib/systemd/system/opensips.service_

`[Unit]
Description=OpenSIPS is a very fast and flexible SIP (RFC3261) server
After=network.target mysqld.service postgresql.service rtpproxy.service

[Service]
Type=forking
User=opensips
Group=opensips
Environment=P_MEMORY=1024 S_MEMORY=1024
EnvironmentFile=-/etc/sysconfig/opensips
PIDFile=/var/run/opensips/opensips.pid
ExecStart=/usr/sbin/opensips -P /var/run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS
ExecStartPre=/usr/sbin/opensips-m4cfg
Restart=always
TimeoutStopSec=10s
LimitNOFILE=262144
RestartSec=1s
[Install]
WantedBy=multi-user.target`


output of _systemctl status opensips.service_
`● opensips.service - OpenSIPS is a very fast and flexible SIP (RFC3261) server
   Loaded: loaded (/usr/lib/systemd/system/opensips.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2018-03-13 22:40:42 ICT; 5s ago
  Process: 29239 ExecStart=/usr/sbin/opensips -P /var/run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS (code=exited, status=255)
  Process: 29236 ExecStartPre=/usr/sbin/opensips-m4cfg (code=exited, status=0/SUCCESS)

Mar 13 22:40:41 DB-MobiCall systemd[1]: Unit opensips.service entered failed state.
Mar 13 22:40:41 DB-MobiCall systemd[1]: opensips.service failed.
Mar 13 22:40:42 DB-MobiCall systemd[1]: opensips.service holdoff time over, scheduling restart.
Mar 13 22:40:42 DB-MobiCall systemd[1]: start request repeated too quickly for opensips.service
Mar 13 22:40:42 DB-MobiCall systemd[1]: Failed to start OpenSIPS is a very fast and flexible SIP (RFC3261) server.
Mar 13 22:40:42 DB-MobiCall systemd[1]: Unit opensips.service entered failed state.
Mar 13 22:40:42 DB-MobiCall systemd[1]: opensips.service failed.
Mar 13 22:40:43 DB-MobiCall systemd[1]: start request repeated too quickly for opensips.service
Mar 13 22:40:43 DB-MobiCall systemd[1]: Failed to start OpenSIPS is a very fast and flexible SIP (RFC3261) server.
Mar 13 22:40:43 DB-MobiCall systemd[1]: opensips.service failed.`


and last, output of _ps aux | grep opensips_
`[root@DB-MobiCall ~]# ps aux | grep opensips
root     29323  0.0  0.0 193808  8308 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29324  0.0  0.0 193808  3064 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29325  0.0  0.0 193808  3064 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29326  0.2  0.0 193808  2424 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29327  0.4  0.0 193808  2420 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29328  0.0  0.0 193808  3080 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29329  0.0  0.0 193808  3076 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29330  0.0  0.0 193808  3076 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29331  0.0  0.0 193808  3076 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29332  0.0  0.0 193808  4280 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29333  0.0  0.0 193808  3312 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29334  0.0  0.0 193808  3320 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29335  0.0  0.0 193808  3320 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29336  0.0  0.0 193808  4300 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29337  0.0  0.0 193808  3320 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29338  0.0  0.0 193808  3320 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29339  0.0  0.0 193808  3076 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29340  0.1  0.0 193808  3072 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29341  0.0  0.0 193808  2916 ?        S    22:42   0:00 /sbin/opensips -P /var/run/opensips.pid
root     29376  0.0  0.0 112648   928 pts/0    S+   22:44   0:00 grep --color=auto opensips`

**Comment by liviuchircu** [comment]
The recommended way to manage OpenSIPS via RPM packages is with `systemctl`. As you can see from above, if you use `opensipsctl`, the default command-line does not include `opensips ... -m128 -M16`, it's just: `opensips -P /var/run/opensips.pid`.

If you intend to use `systemctl`, you can try to do `systemctl stop opensips` before doing `systemctl restart opensips`, or just grep `/var/log/messages` and check if there are any errors that prevent it from starting. Let me know if I can help you more with any errors.

If you still want to use `opensipsctl`, you should first edit `/etc/opensips/opensipsctlrc` and define `STARTOPTIONS="-m128 -M16"`. That should finally make it work :)

**Comment by VuDn5** [comment]
Sorry @liviuchircu  , opensips when start by _systemctl restart opensips_   it will "Permission denied" of /etc/opensips/opensips.cfg
all error in here is that.  but i have a 3 problems:
1. why `opensipsctl restart -m 128 -M 64`  don't work?
2 why 
`
opensipsctl restart
/etc/opensips/opensipsctlrc: line 146: -m 128 -M16: command not found
/etc/opensips/opensipsctlrc: line 146: -m 128 -M16: command not found
` 

with config in _/etc/opensips/opensipsctlrc_ : 
`STARTOPTIONS= "-m128 -M16"` .
3. why and how fix: shmem:used_size is still increase, oneday the opensips become overload and crash?  thanks for your help, it very useful! @liviuchircu

**Comment by liviuchircu** [comment]
Man, I even copy-pasted code for you: `STARTOPTIONS="-m128 -M16"`. Why do you write this (`STARTOPTIONS= "-m128 -M16"`), then come back and say it doesn't work?!

**Comment by VuDn5** [comment]
thanks  @liviuchircu
