### ISSUE TITLE
sip_trace+topology_hiding module, Call-ID is not changed when tracing to HEP

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#1273]
Hi

I am using the sip_trace module to trace dialogs to a HEP server.

I am also using topology_hiding to change the Call-ID of a call as it moves through the OpenSIPS Proxy.

However, when the trace packet of the call is sent to the HEP server, the original Call-ID is sent (instead of the changed one after topology_hiding is called).

I have also tested tracing to a normal sip uri, and the bug is not present there.

Some details are below (see the snippet of the "Outgoing trace to HEP" for the bug)

Module configuration:
```
modparam("proto_hep", "hep_id", "[hid] HOMER_CAPTURE_HOST:HOMER_CAPTURE_PORT; transport=udp; version=3")
modparam("siptrace", "trace_on", 1)
modparam("siptrace", "trace_id",  "[hep1]uri=hep:hid")
modparam("siptrace", "trace_id", "[hep1]uri=sip:127.0.0.1:5080")
```

In request route:
```
    if(is_method("INVITE")) {
        sip_trace("hep1", "d", "sip|xlog");
    }
```

Incoming INVITE to OpenSIPS:
```
U 2018/02/05 11:25:04.385287 93.158.33.109:5070 -> 93.158.33.112:5060
...
Call-ID: 0daccbed-850a-1236-26b2-2c600c60268d.
```
Incoming trace to HEP

```
U 2018/02/05 11:25:04.385810 93.158.33.112:6061 -> 198.19.255.108:9060
HEP3.....................................
...
Call-ID: 0daccbed-850a-1236-26b2-2c600c60268d.
```

Incoming trace to SIP URI:
```
U 2018/02/05 11:25:04.385842 93.158.33.112:5060 -> 127.0.0.1:5080
...
Call-ID: 0daccbed-850a-1236-26b2-2c600c60268d.
```

Outgoing SIP:
```
U 2018/02/05 11:25:04.393805 93.158.33.112:5060 -> 93.158.33.97:5080
...
Call-ID: THIBQwkECBALATNeVVBbEkRVZUBbSFlFC1Z6QQ5TW0MKUmdBW10P.
```

Outgoing trace to HEP. **This is the problem Call-ID, the post- topo hiding Call-ID has not been used**
```
U 2018/02/05 11:25:04.393836 93.158.33.112:6061 -> 198.19.255.108:9060
HEP3.....................................
...
Call-ID: 0daccbed-850a-1236-26b2-2c600c60268d.
```

Outgoing trace to SIP URI **Call-ID is changed here as expected**
```
U 2018/02/05 11:25:04.393864 93.158.33.112:5060 -> 127.0.0.1:5080
...
Call-ID: THIBQwkECBALATNeVVBbEkRVZUBbSFlFC1Z6QQ5TW0MKUmdBW10P.
```

 OpenSIPS version:
```
version: opensips 2.3.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: b24672a
main.c compiled on 13:00:39 Dec 13 2017 with gcc 4.9.2
```

**Comment by bogdan-iancu** [comment]
Thanks @petekelly  for the report. Indeed, this happens as the call-id changing is done on a very late callback (relative to the moment of sending out the SIP message) and the siptrace module is capturing the SIP message *before* having the call-id changed. 
The SIP URI trace works as being SIP based, the callback for changing the call-ID is triggered before replicating the message for capturing.
I will check if the tracing cannot be moved even later, in the same type of callback as call-id changing.

**Comment by bruceborrett** [comment]
Duplicate of #459 ?

**Comment by razvancrainea** [comment]
Indeed, seems to be the same issue in #459. Will close this one and we will follow up there.
