### ISSUE TITLE
Can opensips generate update messages for refreshing session timers?

### ISSUE THREAD

**Issue by mrsanvicente** [OpenSIPS/opensips#1274]
Can opensips generate update messages for refreshing session timers?

(Send updates every x time to maintain long duration calls)

This is described on RFC 4028.

Thanks

**Comment by bogdan-iancu** [comment]
@mrsanvicente, while using the dialog module, OpenSIPS can do in-dialog pinging to the end-points involved in the dialog (one or both). The pinging can be with an OPTIONS request or with a re-INVITE - see the `P` and `p` flags for [create_dialog()](http://www.opensips.org/html/docs/modules/2.3.x/dialog.html#idp5826896)  .
Still, this pinging is not SST related (it is not negotiated and triggered by end-points), but it servers the exactly same purpose.

**Comment by mrsanvicente** [comment]
@bogdan-iancu ,  I think this will work, I will test it and let you know.

Thank you

**Comment by mrsanvicente** [comment]
@bogdan-iancu What i missing is how to shoot re-invite every 15 minutes?? I was trying to use sst, but i am not sure this will work.

Thank you

**Comment by bogdan-iancu** [comment]
What exactly have you tried so far ?

**Comment by mrsanvicente** [comment]
@bogdan-iancu Hello, with reinvite,  the feature that works for me is  Set reinvite_ping_interval parameter from in_dialog module.

Thanks

**Comment by bogdan-iancu** [comment]
@mrsanvicente , the re-INVITE pinging via dialog is controlled by the "r" and "R" flags that have to be passed to create_dialog() function - do you have this in your script ?

**Comment by mrsanvicente** [comment]
Hello @bogdan-iancu 

I insert the following.. but it is not working

if ( is_method("INVITE")) {
                                     xlog("test  '$ru'");  
                                     create_dialog(r);
                                     rewritehostport("x.x.x.x:5060");        
}


Is that correct?

thank you

**Comment by mrsanvicente** [comment]
The behavior expected it to send reinvites so the callee every 5 mins.  Here the module config.

loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 2)
modparam("dialog", "reinvite_ping_interval", 300)


Thank you

**Comment by bogdan-iancu** [comment]
Doing 
`create_dialog("rR");`
for the initial INVITE and having
`modparam("dialog", "reinvite_ping_interval", 300)`
should do the trick.
Are you sure your dialog is created ? what is the listing of `opensipsctl fifo dlg_list` after the dialog was established ?

**Comment by mrsanvicente** [comment]
Hello,

The Dialog is created,  but no reinvite are generated.   Please find attached the config, the dialog info, and the syslog from the dialog.    

loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 2)
modparam("dialog", "options_ping_interval", 20)
modparam("dialog", "default_timeout", 3600)
modparam("dialog", "profiles_with_value", "caller ; callee")
modparam("dialog", "profiles_no_value", "inbound ; outbound")
modparam("dialog", "reinvite_ping_interval", 60)

        if ( is_method("INVITE")) {
                xlog("test '$ru'");
                do_accounting("log");
                create_dialog();
                create_dialog("rR");
                append_hf("P-hint: foreign request\r\n");
                rewritehostport("x.x.x.x:5060");
                route(relay);
                exit;
        }


[dialog.txt](https://github.com/OpenSIPS/opensips/files/1775069/dialog.txt)
[fifo_dialog.txt](https://github.com/OpenSIPS/opensips/files/1775070/fifo_dialog.txt)

**Comment by mrsanvicente** [comment]
FYI

The feature looks activated on the log, but it is not working at all.

DBG:dialog:w_create_dialog2: re-invite ping callee activated
DBG:dialog:w_create_dialog2: re-invite ping caller activated

Thanks

**Comment by mrsanvicente** [comment]
Hello bogdan-iancu,


HOw is this done?  "either you do not properly handle the ACK in your script (as matching it against the dialog)."

**Comment by razvancrainea** [comment]
Make sure you call `loose_route()` or `match_dialog()` on the mid-dialog ACK.
Will close this ticket as it doesn't seem to be any internal issues.
