### ISSUE TITLE
t_wait_for_new_branches with early media crash

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1276]
we config opensips event_routing with push notify and early_media, open sips will crash when hit tm's fr_inv_timeout.

        
route[invite]{

        create_dialog();

        t_newtran();

        # keep the transaction alive (even if all branches will 
        # terminate) until the FR INVITE timer hits (we want to wait
        # for new possible contacts being registered)
        # if t_wait_for_new_branches, caller callel still can not cancel it
        t_wait_for_new_branches();

        # subscribe to new contact registration event,
        # but for our callee only,if timeout registration will not fire the callback
        $avp(filter) = "aor="+$rU;
        notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)","fork_call", "15");

        # rise call evnet,then push server will send notify to device
        $avp(push_info) = "caller="+$fU+";"+"callee="+$rU;
        raise_event("E_PUSH_CALL", $avp(push_info));

        # for each branch we will call the function below
        t_on_branch("per_branch_ops");

        # if the call was not completed, so failure route
        t_on_failure("handle_error_onnet");
        
        # handle invite reply
        t_on_reply("handle_invite");

        #append early_media branch for prompt
        append_branch("sip:prompt@IVR:5062");#set branch rui
        $(branch(duri)[-1]) = "sip:IVR:5062";#set branch destion uri
        setbflag(1,9);#set minor branch flag

        # fetch already registered contacts and relay if any
        if(lookup("location","m"))
        {
                xlog("there are terminals registed under $tU");
        }

        route("relay");
        exit;
}

**Problem1:**if callee not answer or reject the call, tm will time out when hit  fr_inv_timeout

Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z kernel: [4411225.768616] opensips[21028]: segfault at 18 ip 00007f32d7d5a37e sp 00007fff6508a220 error 4 in tm.so[7f32d7cea000+88000]
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21029]: CRITICAL:core:receive_fd: EOF on 67
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21010]: INFO:core:handle_sigs: child process 21028 exited by a signal 11
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21010]: INFO:core:handle_sigs: core was not generated
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21010]: INFO:core:handle_sigs: terminating due to SIGCHLD
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21013]: INFO:core:sig_usr: signal 15 received
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21012]: INFO:core:sig_usr: signal 15 received
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21011]: INFO:core:sig_usr: signal 15 received
Feb 10 09:40:20 iZj6c50ypqr3yx1rmyc7t2Z /opt/opensips/sbin/opensips[21016]: INFO:core:sig_usr: signal 15 received

**Comment by bogdan-iancu** [comment]
@futsystems , thanks for your report - what OpenSIPS version and revision are you using ? Also, is this crash reproducible in a deterministic manner ?

**Comment by futsystems** [comment]
soory for delay, opensips version is 2.3.  but later, i have not generate this bug anymore.

**Comment by bogdan-iancu** [comment]
OK, let's close this outdated and if the issue pops up again, just open a new report. Thank you so much for your help !
