### ISSUE TITLE
LoadBalancer - disable gateway

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1280]
Hello,
The LoadBalancer module sends OPTIONS to gateway. Why when does not receive a answer does not disable it.
Is this a setup problem?
Opensips v2.2 from git hub.

**Comment by bogdan-iancu** [comment]
@goup2010 , try to set the "probing_verbose" module parameter to 1 and check the logs (be sure you allow INFO level) for messages like `disable destination N <name> after X reply on probe`

**Comment by goup2010** [comment]
I can not find information about this parameter in the documentation.
Can you tell me where he is.

**Comment by bogdan-iancu** [comment]
Ha, this parameter was not even documented - I did this right now (see previous listed commits). Until the online html docs are re-generated, just do:

> modparam("load_balancer", "probing_verbose", 1)

**Comment by goup2010** [comment]
I have log level=3 (info - right?) but after adding this parameter no entry appears for a proxy that is timing out, nor it gets disabled.

**Comment by bogdan-iancu** [comment]
OK, if I make a simple C patch for logging more data (regarding the handling of the ping replies) , would you be able to compile it in ?

**Comment by goup2010** [comment]
no problem - send over the patch and i will try it

**Comment by bogdan-iancu** [comment]
@goup2010 , sorry for dropping the ball here, is still possible to run the tests if I prepare a patch ?

**Comment by goup2010** [comment]
Yes I wait patch from you

**Comment by bogdan-iancu** [comment]
Please see this patch to log (as CRITICAL) some extra messages on sending probes and receiving replies - [lb_probe_extra_logs.txt](https://github.com/OpenSIPS/opensips/files/1920770/lb_probe_extra_logs.txt) . Recompile and send me the logs please
