### ISSUE TITLE
Opensips Version 2.3 logs writing on console even log_stderror=no

### ISSUE THREAD

**Issue by pavanps** [OpenSIPS/opensips#1281]
Hi,
I have installed new version of Opensips 2.3 and when am running script with log_stderror=no, logs are written on console but are not redirected to syslog file, configured as mention in documentation. Is it know issue or any thing i need to configured in configuration file for redirecting logs to syslog file

**Comment by bogdan-iancu** [comment]
Do you set `debug_mode` after setting the `log_stderr` option ?

**Comment by pavanps** [comment]
No, this is how i have configured in configuration file.
debug_mode=yes
children=8
tcp_children=8

log_level=6
sip_warning=0
log_stderror=no
log_facility=LOG_LOCAL0
log_name="opensips"

**Comment by razvancrainea** [comment]
@pavanps you might want to check your rsyslog/syslog-ng configuration, perhaps you have it configured to dump everything at console.
Are you seeing all the logs at console, or only ERRORS?

**Comment by pavanps** [comment]
I have configured /etc/rsyslog.conf file and also created /var/log/opensips.log file. And in the opensips.cfg file, 
log_stderror=no is configured. All the logs are seeing on console.

**Comment by bogdan-iancu** [comment]
The issue is the `debug_mode=yes` - it forces the logging to console : http://www.opensips.org/Documentation/Script-CoreParameters-2-3#debug_mode

**Comment by pavanps** [comment]
Yea, got it. Thank you :)
