### ISSUE TITLE
OpenSIPS need to create new TCP connection...

### ISSUE THREAD

**Issue by pavanps** [OpenSIPS/opensips#1283]
I am working on Opensips 2.3 and configured opensips.cfg for listening on tcp connection. SIP messages are receiving on tcp connection. But my configuration file need to send the received message on new TCP connection destination. 
How is it possible in opensips. I mean what configuration i need to do in opensips.cfg for achieving that functionality. 

Thank you

**Comment by bogdan-iancu** [comment]
@pavanps, you do not have to do anything from the script level - the internal TCP stack will try to open a new TCP connection if there is none pointing to the destination given by the SIP layer.

**Comment by bogdan-iancu** [comment]
No follow up, closing
