### ISSUE TITLE
New error logs about "forked REGISTERs" from mid-registrar since upgrade to 2.3.3

### ISSUE THREAD

**Issue by attermann** [OpenSIPS/opensips#1285]
Hi All,

Yesterday I upgraded a server running mid-registrar module from 2.3.2 to 2.3.3 in an attempt to improve stability, but since that upgrade I am seeing new errors in logs like:

```
/usr/local/opensips/sbin/opensips[1364]: ERROR:mid_registrar:mid_reg_req_fwded: mid-registrar does not support forked REGISTERs!
```

This happens in spurts where there is no sign of the error, and then it happens frequently for a period of time before it subsides.  The last spurt made opensips almost completely unresponsive and required restart. The config I am using for mid-registrar is as follows

```
loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2) /* 0 = mirror / 1 = ct / 2 = AoR */
modparam("mid_registrar", "outgoing_expires", 7200)
modparam("mid_registrar", "insertion_mode", 0) /* 0 = contact; 1 = path */
modparam("mid_registrar", "tcp_persistent_flag", 10)
```

I can provide more details if required, but I first wanted to ask what this logs means, and what could be causing this?  Since nothing has changed in config or traffic patterns since the upgrade, it would seem that either something is being caught by the upgraded module that was being ignored previously, or something is amiss in the upgraded module.

Any advice would be appreciated.

Thanks!

**Comment by liviuchircu** [comment]
Hi, @attermann ! The `2.3.2` mid-registrar had a major flaw - it wouldn't handle NAT'ed endpoints at all (I overlooked this during initial development). In short, the `fix_nated_register()` had no effect, with the INVITES still getting routed to the Contact IP, rather than the source IP.

Fixing this issue required quite a few changes internally, and the output SIP packets do look a bit different now (no more `;regid=`, new username, etc.). However, the end result is exactly the same: it masquerades contacts to point to itself.

Let me know how I can help. Thanks!

**Comment by attermann** [comment]
Hey @liviuchircu, thanks for the quick reply!  I am not using `fix_nated_register()` or any other NAT manipulation so not sure how the latest changes would affect my registrations.  Do you know what could be happening to cause this log?  I took a quick look at the code in save.c and I see that this log is generated whenever the TMCB_REQUEST_FWDED callback is called more than once for the same mri struct, but not sure what the significance of this is yet.  Is there something that you can suggest, or shall I attempt to capture debug logs (might not be easy given the load on the server and the transient nature of the error).

Thanks!

**Comment by liviuchircu** [comment]
Regarding the "forked REGISTERS" error, that happens when the module receives two or more consecutive "forwarded" events for the same initial REGISTER without having received a reply at all (e.g. at least some `403` error). In other words, it forces this type of behavior:

```
1 x forwarded_request.... N x replies (due to retransmits) .... 1 x forwarded_request (e.g. using a failure_route) ... a.s.o.
```

Assuming you aren't actually forking REGISTERs to more than one destination, the only explanation would be that some kind of looping is happening on your system. But I have to double-check that the `TMCB_REQUEST_FWDED` gets called multiple times in such a case.

**Comment by attermann** [comment]
When you say "some kind of looping", would that be internal looping, or would a loop with another host lead to the same behavior?  I know that I am not (purposely) forking registrations.  If the latter then I will definitely examine traces to see if there could be a loop.

**Comment by liviuchircu** [comment]
I was alluding to a possible relay looping error where a REGISTER ends up getting relayed to the local box. Again, this is one immediate explanation I could come up with - the problem could be completely different.

I can push a quick fix in order to also print out the Call-ID of such "forked" requests. Would that be useful, or do you already have some logging mechanisms to easily link to the trace?

**Comment by attermann** [comment]
Logging the Call-ID would be great.  There are actually no logs of mine preceding these that I can tell, so it's not clear what leads up to it.

**Comment by liviuchircu** [comment]
Done.

**Comment by attermann** [comment]
Got it thanks! Will get back to you.

**Comment by attermann** [comment]
Hey @liviuchircu, I saw these "forked REGISTERs" error logs again this morning.  This time they coincided with a known outage in our network, and with the CID you provided in the logs I was able to find some helpful traces.  I'm working on getting pcaps now to send to you, but wanted to let you know what I observed.

We are forwarding registrations to a hostname that has SRV records for primary and backup, and in this particular instance the primary failed to respond.  According to traces, opensips sent REGISTER to the primary IP 3 times (over about 3 seconds) with no reply, and then sent one REGISTER to the backup IP.  The backup replied correctly with a 407, but there was nothing after this so presumably opensips stopped responding, and this corresponds to the "forked REGISTERs" error log.

I will send the pcap and more extensive logs from opensips shortly.

**Comment by attermann** [comment]
Attached is a pcap showing the registration fail-over, and below are the corresponding opensips logs that I was able to retrieve (sorry no debug logs yet).  I can't really tell what if any effect the "forked REGISTERs" error condition had on the registration because REGISTER was sent to the backup IP, and 407 was received from it, but opensips was unable to relay the 407 because of the TCP connection error (which I presume but haven't confirmed is due to the upstream proxy timing-out and disconnecting the TCP connection as evidenced from the 408 it returns).


Hopefully with your familiarity of the module you can provide some insight about what might be happening in opensips in this situation.

Thanks again for any help.

```
Feb 16 01:13:38 ingress-nyj /usr/local/opensips/sbin/opensips[24521]: register: [11269D54CF19DBA1AD4DED986A2A1D1E60935285] tcp:70.42.44.35:10000 -> 70.42.44.204:5060 REGISTER sip:cheneygroup.18127.service, from: sip:107m@cheneygroup.18127.service, to: sip:107m@cheneygroup.18127.service, contact: <sip:107m@70.42.44.35:5060;sbc-reg=9101619107184610824>;expires=600
Feb 16 01:13:38 ingress-nyj /usr/local/opensips/sbin/opensips[24521]: *** relaying REGISTER to main registrar
Feb 16 01:13:38 ingress-nyj /usr/local/opensips/sbin/opensips[24521]: skyswitch_domain: cheneygroup.18127.service
Feb 16 01:13:38 ingress-nyj /usr/local/opensips/sbin/opensips[24521]: relaying registration to sip:18127.hpbx.outboundproxy.com
```

```
Feb 16 01:13:42 ingress-nyj /usr/local/opensips/sbin/opensips[24535]: ERROR:mid_registrar:mid_reg_req_fwded: mid-registrar does not support forked REGISTERs (ci: 11269D54CF19DBA1AD4DED986A2A1D1E60935285)!
```

```
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: onreply: [11269D54CF19DBA1AD4DED986A2A1D1E60935285] udp:216.24.144.15:5060 -> 70.42.44.204:6050 -> <null>:<null>:<null> 407 <null>, from: sip:107m@cheneygroup.18127.service, to: sip:107m@cheneygroup.18127.service
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 6
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: ERROR:core:tcpconn_async_connect: poll error: flags 1c
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: ERROR:core:tcpconn_async_connect: failed to retrieve SO_ERROR [server=70.42.44.35:10000] (111) Connection refused
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: ERROR:core:proto_tcp_send: async TCP connect failed
Feb 16 01:13:43 ingress-nyj /usr/local/opensips/sbin/opensips[24515]: ERROR:tm:msg_send: send() to 70.42.44.35:10000 for proto tcp/2 failed
```

[forked_reg.pcap.zip](https://github.com/OpenSIPS/opensips/files/1732650/forked_reg.pcap.zip)

**Comment by liviuchircu** [comment]
Oh, dear God, so obvious! Of course the `TMCB_RESPONSE_IN` does not get called on either failed forwards (such as in your case), or 408 timeouts! I will try to find a way to circumvent this problem - either by adapting mid-registrar to know more about SIP transactions or by changing the `tm` callback behavior...

**Comment by attermann** [comment]
Glad it was obvious to you! Thanks a lot for your attention to this.

**Comment by liviuchircu** [comment]
Can you please try out [this](http://chunk.io/liviuc/eea3822a5c7b4cd39ff0eeb72a46cbf4) patch? I dropped the "forked REGISTER detection" idea because there is literally no way of distinguishing between that or a failed send / reply timeout + retry.

**Comment by attermann** [comment]
Sure thing.  I'll build and update tonight.  I'll also figure out a way to reproduce the issue on demand and get back to you.

**Comment by attermann** [comment]
Just FYI, I wasn't able to actually apply your patch until today.  It is in production now though and I will monitor and provide feedback in a few days.
