### ISSUE TITLE
opensips 2.3.3 Core happened last night -Please investigate Urgently! :)

### ISSUE THREAD

**Issue by JonHVU** [OpenSIPS/opensips#1286]
Hi Guys,

WE have recently upgraded from 2.2 to version: opensips 2.3.3 running on Centos 6.

Last night OpenSIPs crashed and a core was generated;

Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1787]: CRITICAL:core:receive_fd: EOF on 28
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1756]: INFO:core:handle_sigs: child process 1762 exited by a signal 11
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1756]: INFO:core:handle_sigs: core was generated
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1756]: INFO:core:handle_sigs: terminating due to SIGCHLD
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1787]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1781]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1782]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1773]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1779]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1777]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1758]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1770]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1764]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1772]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1775]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1771]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1786]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1783]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1763]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1767]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1778]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1766]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1784]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1759]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1765]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1769]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1768]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1785]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1760]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1774]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1776]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1780]: INFO:core:sig_usr: signal 15 received
Feb 14 23:46:03 HPBXProxy1 HAPBXProxy1[1756]: INFO:core:cleanup: cleanup

Please see core back trace attached, I can also send wireshark captures as required.

Let me know if this is enough detail, this version has been running in production for the last week without issue.

Thanks

Jon
[Corebacktrace150218.txt](https://github.com/OpenSIPS/opensips/files/1726829/Corebacktrace150218.txt)

**Comment by JonHVU** [comment]
Hi Guys, anyone had a chance to pickup yet?

Thanks

Jon

**Comment by liviuchircu** [comment]
Thanks for the nice report, @JonHVU ! Unfortunately, the backtrace is only a consequence of a previous memory corruption (specifically, a double `pkg_free()`) that only now shows its effects.

Did you install from packages or source? If the latter, I just pushed an stability improvement that will help bypass double free operations, and will definitely help avoid your crashes. Just pull the latest `2.3` and re-deploy. Otherwise, we can either make progress by compiling from source or by sending me your `opensips.cfg` for static analysis. You may email it to liviu at opensips dot org.

**Comment by JonHVU** [comment]
Hello,

Thanks for the reply!  

Yes I installed from source, I will pull the latest and redeploy and see how we go!

Will keep you posted!

Many thanks!

Jon

**Comment by liviuchircu** [comment]
Sorry, @JonHVU, my previous instructions were not correct. I haven't backported commit 2254d0011535d3 to `2.3` yet, as I want more teammates to approve it beforehand. Meanwhile, you can just cherry pick it into your latest `2.3` with:

    git cherry-pick -x 2254d001153

**Comment by liviuchircu** [comment]
Update: the fix is now backported to `2.3` and `2.2`.

**Comment by liviuchircu** [comment]
This is either outdated, or the backport masked the underlying issue. Nevertheless, please re-open if needed.
