### ISSUE TITLE
Parsing Issue - Comma is not allowed at From Header

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1290]
Hello 

we have an issue with comma character at From header.

ERROR:core:_parse_to: unexpected char [,] in status 1: <<"xxxxxx>> .
ERROR:core:parse_from_header: bad from header
ERROR:core:pv_get_from_attr: cannot parse From header

As per RFC3261, “comma” is allowed into a quoted string in display name (check qdtext)

My version

version: opensips 2.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 3a2ea8d
main.c compiled on 07:23:38 Jan 10 2018 with gcc 4.8.5

**Comment by bogdan-iancu** [comment]
Hi @apsaras , this was fixed some time ago, be sure you use sources from latest git 2.2 or nightly build for 2.2 packages.

**Comment by apsaras** [comment]
Hello.

My version is as shown above.
git revision: 3a2ea8d
version: opensips 2.2.5 (x86_64/linux)

latest build was 10.1.18. 

I will try to download latest and rebuild and let you know.

Regards

**Comment by bogdan-iancu** [comment]
This is the fix I did on this issue 8bf502c7f3a649fcc06f97be76f9291b9d512ad2

**Comment by apsaras** [comment]
Ok. That is on 2.3 branch. I am using 2.2.5

The latest git 2.2 code is
```
case '"':
                                switch (status)
                                {
                                        case S_PARA_VALUE:
                                                param->value.s = tmp+1;
                                                status = PARA_VALUE_QUOTED;
                                                break;
                                        case PARA_VALUE_QUOTED:
                                                param->value.len=tmp-param->value.s ;
                                                add_param( param , to_b );
                                                status = E_PARA_VALUE;
                                                break;
                                        case F_CRLF:
                                        case F_LF:
                                        case F_CR:
                                                /*previous=crlf and now !=' '*/
                                                goto endofheader;
                                        default:
                                                goto parse_error;
                                }
                                break;
```

**Comment by apsaras** [comment]
Ok. I just checked the sources 2.2.5 (the one I have) does not have the patch 2.2.6 (just downloaded) has it.

Thank you Bogdan once more.
