### ISSUE TITLE
uac_replace_to() adds extra-space

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1291]
Hi!

uac_replace_to("", "") adds extra-space into To: header.
Result after uac_replace_to() call:

To:  <sip:url@domain>
.....^^ two spaces here

**Comment by bogdan-iancu** [comment]
Hi @nikbyte , your example shows one space :) . First of all, according to the SIP grammar, any amount of space is allowed there.
And, could you post the exact original TO hdr and the exact resulting TO hdr, showing the issue ?

**Comment by nikbyte** [comment]
Hi Bogdan! Github eats my spaces :slightly_smiling_face:
I know that it's correct according to the SIP grammar, but looks strange and better to fix this. :)

**Comment by bogdan-iancu** [comment]
TH should not affect the TO / FROM headers at all, so I don't think it's the case.
The 2 spaces are a result of removing the display part and keeping the space separating the hdr name from the display name and the space separating the display name from the URI.
Again, it is not against the SIP grammar, it is harmless and the text beautification does not pay off the effort IMHO.
