### ISSUE TITLE
Allow dispatcher in branch route

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1292]
Hi!

Please allow using of ds_select_dst, ds_select_domain ds_is_in_list to use in branch route. Tested, works well.

Thanks.

**Comment by bogdan-iancu** [comment]
Hi @nikbyte , if you already did it, could you generate a PR for us ?

**Comment by nikbyte** [comment]
Sure Bogdan, made for master and 2.3. Thanks.
