### ISSUE TITLE
Do not fork command line option not working correctly in 2.3.3

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1295]
Running opensips -D causes a string of debug log to be printed (even though config file is set to LOG_LEVEL=-1) and then the main process exits, leaving Opensips running in the background and returning me to my shell.

Given that -F keeps the main process in the foreground and forks the others, the expected behaviour of -D is that Opensips runs in foreground-blocking mode and does not exit until cancelled (^C).

I'm running 2.3.3 from the Xenial apt repo.

**Comment by bogdan-iancu** [comment]
@hamid-elaosta , before investigating this, keep in mind that the command line parameter are overwritten by the similar parameter inside the script. Are you sure it is not your case ?

**Comment by bogdan-iancu** [comment]
BTW, -D (forcing debug mode) is a powerful option and it overrides all the options involved into switching in debug mode (like foreground, log level, number of processes, etc)

**Comment by bogdan-iancu** [comment]
@hamid-elaosta , could you point to the documentation where -D is listed as "Do not fork" ? actually starting with 2.2 there is the `debug_mode` option which obsoleted the old `fork=no` option

**Comment by hamid-elaosta** [comment]
@bogdan-iancu 
```
root@sip:/# opensips -h
version: opensips 2.3.3 (x86_64/linux)
Usage: opensips -l address [-l address ...] [options]
Options:
    -f file      Configuration file (default /etc/opensips/opensips.cfg)
<snip>
    -d           Debugging mode (multiple -d increase the level)
    -D           Do not fork into daemon mode
<snip>
```

**Comment by bogdan-iancu** [comment]
Good point :D - I fixed the help message, thanks for pointing this out.
Now, going back the original report - is there anything still potentially wrong as behavior ?

**Comment by hamid-elaosta** [comment]
Well, I'm not sure. Is the debug mode (-D) supposed to block the shell until cancelled? Because it does not. If this is expected then we can close this ticket :D

**Comment by bogdan-iancu** [comment]
First check the definition of the debug mode:
http://www.opensips.org/Documentation/Script-CoreParameters-2-3#debug_mode

**Comment by hamid-elaosta** [comment]
Ok, looks like it behaves as documented there. If debug_mode is NOT in the config file, -D will foreground-block when started, if debug_mode=no is in config it will override the command line parameter and exit the main processes after backgrounding Opensips.

Thanks for clearing that up, I'll close this as it appears to function correctly (barring the misundertanding with the usage label).
