### ISSUE TITLE
uac_replace_from does not change PRACK From Header

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1296]
Hello.

I am using uac_replace_from during initial Invite and I am remover From Quoted string like bellow

uac_replace_from("","$avp(dpfrom)")

During the call a PRACK is sent which contains Unicode Quoted String and I was expected that this quoted string will be automatically removed which is not. The uac_replace_from only replaces the sip part of the header.

My version

version: opensips 2.3.2 (x86_64/linux)
git revision: 7581bd575

Ingress Invite
-------------------------
Session Initiation Protocol (INVITE)
    Request-Line: INVITE sip:10009+1022222222@172.17.253.16 SIP/2.0
    Message Header
        Via: SIP/2.0/UDP 172.17.253.8:5060;branch=z9hG4bKf14f.cf78ea93.0
        Max-Forwards: 68
        To: "1022222222" <sip:1022222222@172.17.253.8>
        From: "2022222222" <sip:2022222222@172.17.253.6>;tag=20559
        Call-ID: PROXY1_MC0tLyY8IVhaCioJFCc9FAF+JzogOzNSJi41GCgyJzQDIi93LSo5OBUHMh4tPSdVBCEtLjdSOxgBLyc2PRk2AxokI0MlKyFnKSE7AhZO
        CSeq: 1 INVITE
        Contact: <sip:172.17.253.8;did=8e3.40456f21>
        P-Asserted-Identity: <sip:2022222222@anonymous.invalid>
        Supported: timer,100rel
        Session-Expires: 3600
        Allow: INVITE,ACK,CANCEL,BYE,PRACK,OPTIONS,REGISTER,INFO,NOTIFY,UPDATE
        Content-Type: application/sdp
        User-Agent: Panasonic-MPR08-V7.1104/VSIPGW-V2.3002
        Content-Length: 294
        X-Orig-CallID: 00002725-b116755e5777100092ef0080f031def6@172.31.0.14

Egress Invite
---------------

    Request-Line: INVITE sip:+1022222222;npdi@2.2.2.2;user=phone SIP/2.0
    Message Header
        Via: SIP/2.0/UDP 1.1.1.1:5060;branch=z9hG4bK1eed.33e6f1d1.0
        Max-Forwards: 67
        To:  <sip:+1022222222@conn.cn;user=phone>
        From:  <sip:+2022222222@conn.cn;transport=udp;user=phone>;tag=20559
        Call-ID: Exelysis_OSEtO3RQKyVyHhklGitXKzcbBG0HCj5oJBFQNSMlBisOB1ZhFycwOAZWUDQmSRcvDn8jOwBKUS9+DkEnc3slJAtGGzIyFzNsLSAAYg0WOjwaBG8tDQsDfj8CUTMXDQo6VWMCLg1oCTk6NlUiRTs7
        P-Asserted-Identity: <sip:+2022222222@conn.cn;user=phone>
        Tel:+302810391856;npdi
        CSeq: 1 INVITE
        Contact: <sip:1.1.1.1;did=aae.67aa9c84>
        Supported: timer,100rel
        Session-Expires: 3600
        Allow: INVITE,ACK,CANCEL,BYE,PRACK,OPTIONS,REGISTER,INFO,NOTIFY,UPDATE
        Content-Type: application/sdp
        Content-Length: 298
    Message Body

Ingress PRACK
----------------

Session Initiation Protocol (PRACK)
    Request-Line: PRACK sip:172.17.253.16;did=aae.67aa9c84 SIP/2.0
    Message Header
        Via: SIP/2.0/UDP 172.17.253.8:5060;branch=z9hG4bKc14f.f6a90397.0
        Max-Forwards: 68
        To: sip:1022222222@172.17.253.8;tag=c5covfaf-CC-1002
        From: "\312\301\321\301\314\320\305\313\301" <sip:2022222222@172.17.253.6>;tag=20559
        Call-ID: PROXY1_MC0tLyY8IVhaCioJFCc9FAF+JzogOzNSJi41GCgyJzQDIi93LSo5OBUHMh4tPSdVBCEtLjdSOxgBLyc2PRk2AxokI0MlKyFnKSE7AhZO
        CSeq: 2 PRACK
        RAck: 1 1 INVITE
        Allow: INVITE,ACK,CANCEL,BYE,PRACK,OPTIONS,REGISTER,INFO,NOTIFY,UPDATE
        User-Agent: Panasonic-MPR08-V7.1104/VSIPGW-V2.3002
        Content-Length: 0

Egress PRACK
----------------
Session Initiation Protocol (PRACK)
    Request-Line: PRACK sip:2.2.2.2;transport=udp;Dpt=8878-400;Hpt=8f78_16;CxtId=3;TRC=ffffffff-ffffffff SIP/2.0
    Message Header
        Route: <sip:2.2.2.2:5060;transport=udp;lr;Hpt=8f78_116;CxtId=3;TRC=ffffffff-ffffffff;X-HwB2bUaCookie=22424>
        Via: SIP/2.0/UDP 1.1.1.1:5060;branch=z9hG4bKeded.ca9fe6b3.0
        Max-Forwards: 67
        To: sip:+1022222222@conn.cn;user=phone;tag=c5covfaf-CC-1002
        From: "\312\301\321\301\314\320\305\313\301" <sip:+2022222222@conn.cn;transport=udp;user=phone>;tag=20559
        Call-ID: Exelysis_OSEtO3RQKyVyHhklGitXKzcbBG0HCj5oJBFQNSMlBisOB1ZhFycwOAZWUDQmSRcvDn8jOwBKUS9+DkEnc3slJAtGGzIyFzNsLSAAYg0WOjwaBG8tDQsDfj8CUTMXDQo6VWMCLg1oCTk6NlUiRTs7
        CSeq: 2 PRACK
        RAck: 1 1 INVITE
        Allow: INVITE,ACK,CANCEL,BYE,PRACK,OPTIONS,REGISTER,INFO,NOTIFY,UPDATE
        Content-Length: 0

**Comment by bogdan-iancu** [comment]
@apsaras , the automatic restoring works only over the URI part of the TO/FROM, it does not cover the display name part of the header. Why ? as the display is relevant only in the initial request, serving no purpose in the sequential request.
A best practice is to simply strip the display name in the sequential request if you know you did some display name manipulation in the initial request.

**Comment by apsaras** [comment]
Hello Bogdan.

Thank you for your reply.My problem now is that Display name is in Unicode and I will probably have issue to remove it. I will give it a try. 

Thank you.

**Comment by bogdan-iancu** [comment]
you can easily remove it by uac_replace_from("",""); <- this will strip down the display without touching the URI

**Comment by apsaras** [comment]
I will try it. My concern is the Unicode. If uac_replace_from does any parsing it might fail.

**Comment by bogdan-iancu** [comment]
If the case, please let me know
