### ISSUE TITLE
json_mi returns "poor quality" json

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1298]
Using `cache_*` via the JSON MI is  a useful feature. However, the format of the JSON responses leaves a lot to be desired.

Performing the following request for a cached item with the following values:
Key: "this_is_my_key"
Value: "this_is_my_value"
```
curl 127.0.0.1:8888/json/cache_fetch?params=local%2Cthis_is_my_key
```
returns the following "JSON":
```
{"value":"this_is_my_key = [this_is_my_value]"}
```
Although this looks like JSON, it's functionally not really. There is either one, or there are two values I need in the response to that request; the `value` is a certain, and optionally the `key`.

The response contains one item "value", its content is a convoluted mix of my key, `=` and my value wrapped in square bracks, and all space seperated.

The only way for this response to be useful is to parse the content of "value" to retrieve the actual `value` and optionally also parse out the `key`, if required.

A more suitable, and immediately useable response would look like this;
```
{"key": "this_is_my_key", "value": "this_is_my_value"}
```
No string parsing required, less room for error, and much more readable.

**Comment by liviuchircu** [comment]
Yup, that's definitely a limitation of the `mi_cachefetch()` function. Fortunately, we can fix it in two possible ways by only changing a line! So, please take your pick:

```
[liviu ◄ Rivendell opensips (master)]
$ scripts/opensipsctl fifo cache_store local a b
[liviu ◄ Rivendell opensips (master)]
$ scripts/opensipsctl fifo cache_fetch local a
a:: b
key:: a
value:: b
[liviu ◄ Rivendell opensips (master)]
$ curl '10.0.0.10:8080/json/cache_fetch?params=local%2Ca'
{"a": "b", "key": "a", "value": "b"}[liviu ◄ Rivendell opensips (master)]
$ 
```

Which, in your opinion, is more useful? The short version (`{"a": "b"}`), or the long one (`{"key": "a", "value": "b"}`)? Personally, I'm leaning towards the long one.

**Comment by hamid-elaosta** [comment]
Absolutely the long one.  Given these are key values, it gives us known keys for each type in the JSON.

**Comment by hamid-elaosta** [comment]
Thanks @liviuchircu 
Fastest improvement/enhancement ever :tada:
