### ISSUE TITLE
$(<request>rU) giving NULL with IPV6 on Opensips 2.3.3

### ISSUE THREAD

**Issue by ankurgupta001** [OpenSIPS/opensips#1300]
$(\<request\>rU) giving NULL when the request contains an IPv6 address on Opensips 2.3.3.The same works fine when the request contains IPv4 address.Please investigate.

**Comment by bogdan-iancu** [comment]
Please paste here the exact RURI you have.

**Comment by ankurgupta001** [comment]
Hi Bogdan,
Thanks for reply.Below are the details.

$(\<request\>ru) = sip:1000001006@[2600:1f18:49b:7a00:274:699c:34de:2da0].When used in onreply_route $(\<request\>rU) is givng NULL.
Please let me know in case any further information is needed.

**Comment by ankurgupta001** [comment]
Hi Bogdan,
Did u get a chance to have a look at it?

**Comment by bogdan-iancu** [comment]
I just ran a small test with:
```
onreply_route[handle_nat] {
	xlog("incoming reply URI was $(<request>ru), username $(<request>rU) \n");
}
```
and the values were ok:
```
Mar 14 12:59:56 [2324] DBG:core:pv_get_spec_value: Found context function 0x7feb09e0b4f1
Mar 14 12:59:56 [2324] DBG:tm:tm_pv_context_request: in fct din tm
Mar 14 12:59:56 [2324] incoming reply URI was sip:1000001006@[2600:1f18:49b:7a00:274:699c:34de:2da0], username 1000001006
Mar 14 12:59:56 [2324] DBG:tm:t_should_relay_response: T_code=100, new_code=403
Mar 14 12:59:56 [2324] DBG:tm:t_pick_branch: picked branch 0, code 403 (prio=603)
```

Could you run in debug mode and print the full logs covering the whole reply processing ?

**Comment by ankurgupta001** [comment]
Hi Bogdan,
Thanks for checking the same.It seems the issue not only with IPV6 but also with IPV4.
Below is the exact statement that is  written in reply_route

xlog("L_INFO","onreply_route_plumplusincall | ci = '$ci' | fu = '$fu' | tu = '$tu' | ru = '$(\<request\>ru)' | rU = '$(\<request\>rU)'| DLG_status = $DLG_status'");

Logs---
Mar 15 18:48:49 ip-10-3-3-69 /usr/local/sbin/opensips[27928]: DBG:tm:tm_pv_context_request: in fct din tm
Mar 15 18:48:49 ip-10-3-3-69 /usr/local/sbin/opensips[27928]: onreply_route_plumplusincall | ci = 
'06D954F3-5AAAC009000C9A6E-8ACEC700' | fu = 'sip:+19174102100@67.44.9.142' | tu = 'sip:+444444888@34.195.160.25' | ru = 'sip:1006@49.205.219.198:21707;transport=TCP;ob' | rU = '?

Please let me know in case any further information is required to debug the same.

**Comment by ankurgupta001** [comment]
Hi Bogdan,
Did you get a chance to look at the same?Please let me know in case any further info is required.

**Comment by bogdan-iancu** [comment]
@ankurgupta001 , it is strange as there is noting after the `rU =`, even if your xlog statement print more data like DLG_status. Are you sure you are not overflowing the xlog buffer, getting the output truncated ? Do you see any errors in logs before the xlog ?

**Comment by bogdan-iancu** [comment]
Hello @ankurgupta001 , do you have any updates here ?

**Comment by bogdan-iancu** [comment]
But printing $ru in onreply route will give you data from the the reply, not from the request...it will actually return NULL in the context of a reply.

**Comment by ankurgupta001** [comment]
I mean $(<request>ru{uri.user}) gives the correct result.I did a typo while writing above response.

**Comment by bogdan-iancu** [comment]
ah :D , so `$(<request>ru{uri.user})` shows ok, but `$(<request>rU)` returns null ??

**Comment by ankurgupta001** [comment]
Correct `$(<request>ru{uri.user})` show fine but `$(<request>rU) `returns null.

**Comment by bogdan-iancu** [comment]
If I provide a small patch to log more info, would you be able to compile it in ?

**Comment by ankurgupta001** [comment]
Sure Please provide the patch.I will test it out.

**Comment by bogdan-iancu** [comment]
@ankurgupta001 , please apply and get the output (using both ways of getting the username) from this [patch](https://github.com/OpenSIPS/opensips/files/1932914/ruri_extra_logs_patch.txt)
You will get some CRITICAL logs with TEST keyword, so do not worry :)

**Comment by ankurgupta001** [comment]
`Apr 21 19:57:34 ip-10-3-3-69 /usr/local/sbin/opensips[4100]: CRITICAL:core:pv_get_ruri: TEST: RURI is <sip:1006@183.82.27.47:7489;transport=TCP;ob>
Apr 21 19:57:34 ip-10-3-3-69 /usr/local/sbin/opensips[4100]: CRITICAL:core:pv_get_ruri_attr: TEST: RURI is <sip:1006@183.82.27.47:7489;transport=TCP;ob>
Apr 21 19:57:34 ip-10-3-3-69 /usr/local/sbin/opensips[4100]: CRITICAL:core:pv_get_xuri_attr: TEST: USER is <>`

**Comment by bogdan-iancu** [comment]
Many thanks @ankurgupta001 for the output - I managed to find and fix the bug - could you update from GIT and confirm the fix for me ?
