### ISSUE TITLE
Opensips 2.3 tls_mgm can't read certificate on Debian 9.3

### ISSUE THREAD

**Issue by Piszi** [OpenSIPS/opensips#1302]
I installed opensips 2.3 and all the modules I need on a Debian 9.3 and copied my cfg from a Debian 8.10 machine running the same version of Opensips but when I start Opensips it fails with can't read certificate.
I triple checked permissions and path but everithing is fine.
Everyone can read the file but only root can edit, 
opensips runs as root (checked with `top | grep opensips` and `ps aux | grep opensips`)
I chmod-ed the the whole route and the files with 777
and it still fails.

Is it a bug with deb 9.3 and tls_mgm module or did I miss something? 
Oh and tls module is loaded, and opensips can bind the address given in `listen=`
Also I tried it with 4.9.0-4 and 4.9.0-6 kernels but the result is the same.

**Comment by razvancrainea** [comment]
There is no known bug, nor something that I've seen before.
Are you starting opensips using systemd? What's the full path of the certificates?

**Comment by Piszi** [comment]
Yes I'm starting opensips with systemd. Currently my path to the certificates is /home/myuser/certs and I tried the cerificates that comes with opensips and those are under /etc/opensips/tls/user. I also tried to copy these to under /certs but no luck.

**Comment by razvancrainea** [comment]
Are you setting a `RootDirectory=` directive in your systemd service? Or you're just using the plain stock systemd that comes with the `opensips` package?

**Comment by Piszi** [comment]
I'm kind of using the stock. The only modification I made is some services names that Opensips should wait for (like msqld.service to mysql.service) and changed user/group to root in the opensips.service.

**Comment by volga629** [comment]
Same on Fedora server last git 

LOG

````
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: INFO:tls_mgm:mod_init: initializing TLS management
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: INFO:tls_mgm:mod_init: openssl version: OpenSSL 1.1.0g-fips  2 Nov 2017
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: INFO:tls_mgm:mod_init: disabling compression due ZLIB problems
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: INFO:tls_mgm:init_tls_dom: Processing TLS domain 'default'
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: NOTICE:tls_mgm:init_ssl_ctx_behavior: No EC curve defined
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: INFO:tls_mgm:init_ssl_ctx_behavior: client verification NOT activated. Weaker security.
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: ERROR:tls_mgm:load_certificate: unable to load certificate file '/etc/opensips/tls/user/user-cert.pem'
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: ERROR:tls_mgm:init_tls_domains: Failed to init TLS domain 'default'
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: ERROR:core:init_mod: failed to initialize module tls_mgm
Mar 10 13:46:14 canldev01-fedora27 /usr/sbin/opensips[17864]: ERROR:core:main: error while initializing modules
````

CONFIG

````
#### TLS protocol
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm", "tls_method", "TLSv1")
modparam("tls_mgm", "require_cert", "0")
modparam("tls_mgm", "verify_cert", "0")
modparam("tls_mgm", "certificate", "/etc/opensips/tls/user/user-cert.pem")
modparam("tls_mgm", "private_key", "/etc/opensips/tls/user/user-privkey.pem")
modparam("tls_mgm", "ca_list", "/etc/opensips/tls/user/user-calist.pem")
````

````
[root@canldev01-fedora27 ~]# tree  /etc/opensips/tls
/etc/opensips/tls
├── ca.conf
├── cert.pem
├── request.conf
├── rootCA
│   ├── cacert.pem
│   ├── certs
│   │   └── 01.pem
│   ├── index.txt
│   ├── private
│   │   └── cakey.pem
│   └── serial
├── user
│   ├── user-calist.pem
│   ├── user-cert.pem
│   ├── user-cert_req.pem
│   └── user-privkey.pem
└── user.conf

[root@canldev01-fedora27 ~]# ls -la  /etc/opensips/tls
total 32
drwxr-x--- 4 opensips opensips 4096 Mar 10 13:44 .
drwxr-x--- 3 opensips opensips 4096 Mar 10 13:48 ..
-rw-r--r-- 1 opensips opensips 2049 Mar 10 13:44 ca.conf
-rw-r--r-- 1 opensips opensips 3023 Mar 10 13:16 cert.pem
-rw-r--r-- 1 opensips opensips 1127 Mar 10 13:44 request.conf
drwxr-x--- 4 opensips opensips 4096 Mar 10 13:44 rootCA
drwxr-x--- 2 opensips opensips 4096 Mar 10 13:44 user
-rw-r--r-- 1 opensips opensips  591 Mar 10 13:44 user.conf


`````

**Comment by Piszi** [comment]
I don't know whats happening but if I create a selfsigned cert with openssl anywhere on my machine, than tls_mgm works. If I try to use our signed cert or the opensips cert than it fails. With the opensips cert it could be that it is not valid anymore. But our cert is valid and is readable. I can't try it with lets encrypt because we are on local network and does not have a domain set up and lets encryt doesn't authenticate IP address.

**Comment by volga629** [comment]
no selinux disabled

**Comment by razvancrainea** [comment]
Did you manage to fix this?

**Comment by volga629** [comment]
In my dev vm I got it working, I think the main issue is missing dependency modules for mgm_tls 
and should not segfault 

here are config which worked with self sign certs


````

#### TLS protocol
loadmodule "proto_hep.so"
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm", "tls_method", "TLSv1")
modparam("tls_mgm", "require_cert", "0")
modparam("tls_mgm", "verify_cert", "0")
modparam("tls_mgm", "certificate", "/etc/opensips/tls/canldev01-fedora27-cert.pem")
modparam("tls_mgm", "private_key", "/etc/opensips/tls/canldev01-fedora27-key-nopasswd.pem")
modparam("tls_mgm", "ca_list", "/etc/opensips/tls/ca-cert.pem")
modparam("tls_mgm", "ca_dir", "/etc/opensips/tls")

```

**Comment by razvancrainea** [comment]
Can you swap the `loadmodule` lines a bit and check where the error was?
If you can no longer replicate this, please close the ticket.

**Comment by razvancrainea** [comment]
This looks like a configuration file, since the tls specifications have changed in 3.0.
Please follow the migration document for more information:
https://www.opensips.org/Documentation/Migration-2-4-0-to-3-0-0
