### ISSUE TITLE
null pointer de-reference in resolve.c

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#1303]
In our old version of 1.11 we ran into an issue where opensips segfaulted dereferencing a null pointer in resolve.c, all other dereferences are gaurded buy if (proto && *proto==......)

The issue appears to remain in upstream master. 

https://github.com/OpenSIPS/opensips/blob/master/resolve.c#L1685

**Comment by bogdan-iancu** [comment]
@etamme , the code you are point to is not in used, it is commented for some time :) (even in 1.11)  - see https://github.com/OpenSIPS/opensips/blob/master/resolve.c#L1605

**Comment by bogdan-iancu** [comment]
This is the relevant link for 1.11 - https://github.com/OpenSIPS/opensips/blob/1.11/resolve.c#L1790
