### ISSUE TITLE
OpenSIPS 2.2.5: SNMPstats not working

### ISSUE THREAD

**Issue by lexus45** [OpenSIPS/opensips#1306]
Hi all.

- CentOS 7.4.1708
- OpenSIPS 2.2.5
- configured as written here  http://www.opensips.org/html/docs/modules/2.2.x/snmpstats.html  and http://saevolgo.blogspot.ru/2012/09/opensips-monitoring-using-snmp-part-i.html
-  OPENSER-MIB, OPENSER-REG-MIB, OPENSER-SIP-COMMON-MIB, OPENSER-SIP-SERVER-MIB, OPENSER-TC - put from opensips-2.2.5.gz to all MIBs location (/usr/share/snmp/mibs/)

opensips.cfg
***************
loadmodule "snmpstats.so"
modparam("snmpstats", "snmpgetPath", "/usr/bin/")
modparam("snmpstats", "sipEntityType", "registrarServer")

netstat OK:
***************
sip01 ~ # netstat -tulpn | grep -e opens -e snm
tcp 0 0 127.0.0.1:705 0.0.0.0:* LISTEN 26539/snmpd 
tcp 0 0 127.0.0.1:199 0.0.0.0:* LISTEN 26539/snmpd 
udp 0 0 10.5.10.21:5060 0.0.0.0:* 26569/opensips 
udp 0 0 0.0.0.0:161 0.0.0.0:* 26539/snmpd 

opensipsctl fifo OK:
***************
sip01 ~ # opensipsctl fifo ps
Process:: ID=0 PID=26569 Type=attendant
Process:: ID=1 PID=26571 Type=SNMP AgentX
...

But this command shows no output:
***************
snmpd -f -Dagentx -x tcp:localhost:705 2>&1

And as a result - SNMP monitoring does not work.

******************************
UPDATE:
created /etc/snmp/snmp.conf like this:

mibs +OPENSER-MIB
mibs +OPENSER-REG-MIB
mibs +OPENSER-SIP-COMMON-MIB
mibs +OPENSER-SIP-SERVER-MIB
mibs +OPENSER-TC As for now, at least this works:

sip01 ~ # snmptranslate -IR -On openserSIPRegStats
.1.3.6.1.4.1.27483.3.1.2.1.6

sip01 ~ # snmpwalk -v 2c -c public localhost openserSIPRegCfg
OPENSER-SIP-SERVER-MIB::openserSIPRegCfg = No more variables left in this MIB View (It is past the end of the MIB tree)

*********************************************
But we stopped configuring and decided to use MI_JSON for Zabbix monitoring.

**Comment by nferreyra** [comment]
A similar problem already reported on https://opensips.org/pipermail/users/2016-February/033784.html.
If you `snmpget` the individual OID it works though

**Comment by bogdan-iancu** [comment]
moving investigation to  #1649
