### ISSUE TITLE
acc: corefile generated on failed startup

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#1307]
In [this script](http://chunk.io/liviuc/d25e48a758a547c7aa83a55ea0b2da5a), the `E_UL_LATENCY_EVENT` is not defined, hence startup is aborted. However, `acc` also produces a corefile when freeing the extras.

**Comment by bogdan-iancu** [comment]
This was fixed via 1e61bdc5bf0e52da5a9e2458395c4e2c716bcddb . Retake the test and confirm.

**Comment by liviuchircu** [comment]
Yup. No more corefile! :)
