### ISSUE TITLE
MI Command to kill all dialogs at the same time

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1311]
Hi team!

Please add MI command into dialog module to kill all dialogs at the same time.
Thank you.

**Comment by bogdan-iancu** [comment]
Hi @nikbyte , I guess you can do this now via the profile_end_dlgs MI command (see http://www.opensips.org/html/docs/modules/2.4.x/dialog.html#idp6009008) - just put all your calls into a profile, and if you want to terminate them all, use this function.
