### ISSUE TITLE
2.4 mid-registrar: no way to keep the contact as-is ?

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#1318]
mid-registrar, no way to keep the contact as in original? Only mirroring? (I would not mind to have one only registration, eg, no need for multiple devices on same account)

This breaks a lot of things esthetically (extended CDRs, reports, etc). 

Eg, mid-registrar -> FreeSWITCH (then FS generates unexpected CDRs and reports). Calls work no problem, but a lot of third party stuff will pick the mid-registrar generated contact as destination_number, etc

**Comment by liviuchircu** [comment]
Yes, I've also thought of this. What if we change the `insertion_mode` to work like this:

```
Regardless of the working mode, the mid-registrar mangles the Contact header field values of all forwarded registration requests by replacing any original IP and port of a Contact URI with those of one of the mid-registrar's listening interfaces.

Additionally, each contact will be assigned an unique identifier, which will be utilized in future lookups. This information will be included in each forwarded Contact URI. The "contact_id_insertion" modparam controls how this information will be placed.

"contact_id_insertion" - Controls where the additional unique Contact identification information (64-bit, hex-encoded integers) will be placed within outgoing Contact header fields.

- `ct-param (default)` - the contact IDs shall be appended to Contact URIs as a `;cid=` parameters
- `ct-username` - the contact IDs will effectively replace the username parts of outgoing Contact URIs
```

Please let me know your thoughts. Thanks!

**Comment by gmaruzz** [comment]
Perfect for me!
Thx Liviu!

**Comment by volga629** [comment]
ctid=  parameter is optimal. Thank you.

**Comment by gmaruzz** [comment]
kewl man, thx !
