### ISSUE TITLE
2.4 mid-registrar feature MI command to resend all current registrations to downstream registrar

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#1319]
Feature Request
Use case:
mid-registrar -> FS
FS crashes
FS own DB is wiped (FS has no more memory of registrations)
FS restart
MI to mid-registrar so mid-registrar resends all registrations in usrloc to FS

**Comment by liviuchircu** [comment]
One quick comment: isn't the direction "downstream", rather than "upstream"? As I see it, both registrations and calls flow like this (we are interested in the bold part):

    UAC-1 (upstream) -> **mid-reg -> FS** -> mid-reg -> UAC-2 (downstream)

I like this idea. Moreover, the code is already aware of each different FS under each contact, because it needs to De-REGISTER them in case they turn off Wi-Fi. This makes it easier to implement (not trivial, the API still needs a little tweak). So how about:

    opensipsctl fifo mid_reg_downstream_dump ALL/downstream_ip

The `ALL` keyword is for safety reasons, as it will cause all contacts to be fully re-sent to all underlying FreeSWITCHes. The other option, the `downstream_ip`, is self-explanatory.

**Comment by gmaruzz** [comment]
:) yeah, I was in doubt about upstream/downstream... Dunno why, in my mind was upstream because takes an additional effort :) you right FS is definitely downstream in the flow from client1, to mid, to fs

Your solution is perfect to me

One comment, about mid_reg_downstream_dump ALL|downstream_ip:

we can have roughly three use cases:
A) one only FS behind mid-registrar, all domains and all users in one FS DB
B) a farm of FSs, load-balanced, behind mid-registrar, all domains and all users in one shared FS DB
C) a farm of FSs, partitioned by userids|domains, behind mid-registrar (each one FS has its own DB, containing its own partition of domains|userids)

If I understood correctly, dumping to ALL means resend ALL registrations, each registration will be resent to the FS it was sent before (the one in table for de-REGISTER). So, each registration will be resent one only time

As opposed, dumping to downstream_ip means to resend only the registrations that were originally sent to that particular downstream_ip (the one in table for de-REGISTER). So, only a fraction of registrations will be resent.

If I understood correctly, then dumping to a downstream_ip (as opposed to ALL) has only sense if we are in the C use case. In A and B use cases you must dump to ALL (in A case ALL and downstream_ip would coincide, btw).

Is this correct?

**Comment by liviuchircu** [comment]
Yes, indeed! Your interpretations are spot on, and all use cases sound fine. Let's add any future comments/improvements here, otherwise I will proceed with implementing this last iteration of the functionality when I get into cleaning up the mid-registrar, probably next week.

**Comment by gmaruzz** [comment]
1) I am very happy with your solution
2) maybe, in a future, can be introduced a third dumping option: ALL|downstream_ip|ALL_to_an_arbitrary_ip
3) this third option would be useful in case the original downstream_ips are no more online, and you want to dump registrations to a new, arbitrary, downstream FS (not-pre-existing). This would imply to rewrite the mid-registrar table for de-REGISTER downstream_ips to the new arbitrary downstream address
4) I repeat, this third option is a proposal for far future, I am very happy with your solution

Thx!!!

**Comment by liviuchircu** [comment]
How does this sound?

    opensipsctl fifo mid_reg_downstream_dump ALL|target_registrar_ip [replacement_ip]

Synopsis:

```
mid_reg_downstream_dump target_registrar_ip [replacement_ip]

Synchronizes the mid-registrar and the @target_registrar_ip by re-sending the last
successfully forwarded REGISTER of each corresponding in-memory contact using
the lastly chosen transport protocol.

If a @replacement_ip is provided, the mid-registrar will synchronize to it instead,
while matching in-memory contacts using @target_registrar_ip. During this
process, the in-memory contacts are also updated to belong to @replacement_ip.
This is required in order to correctly generate future possible De-REGISTER requests.

Parameter values:

- @target_registrar_ip: IP[:port] or SIP URI. Also, a special token may be provided instead:
 "ALL". The token will cause all in-memory contacts to be dumped to their currently stored
downstream registrar.

- @replacement_ip: IP[:port] or SIP URI. New physical target for the synchronization.
The @target_registrar_ip will only be used for in-memory matching purposes before
being replaced with the @replacement_ip. If the "ALL" token is given as a target, all
in-memory contacts will be dumped and re-pointed to @replacement_ip.
```

**Comment by gmaruzz** [comment]
YAY!
RFC grade!! :)

**Comment by bogdan-iancu** [comment]
As per email, we discussed this feature and we decided it makes more sense to implement it via an external script (python?). Such script will fetches via MI all the mid-registrations and fire the REGISTER requests using the t_uac_dlg MI function. There will be no need to add more code in OpenSIPS.
@liviuchircu already pushed the commit to extend the ul_dump MI function in oder to also expose the context (the key-values set) used by mid-registrar.

**Comment by vasilevalex** [comment]
Hello @liviuchircu. I just wonder, what is the final solution? Can you please explain little bit more?ul_dump over mi_json returns interesting values, second KV-Store is on the level of Contact array member:
```
[
  {
    "value": "200",
    "children": {
      "Contact": [
        {
          "value": "sip:200@172.16.1.29:2199;transport=tls",
          "attributes": {
            "Q": "1"
          },
          "children": {
            "ContactID": "3160049194786444716",
            "Expires": "2742",
            "Callid": "313534313339343231343430373138-05m2ah8mb1xw",
            "Cseq": "123",
            "User-agent": "snom",
            "Received": "sip:192.168.10.138:2199;transport=tls",
            "State": "CS_NEW",
            "Flags": "0",
            "Cflags": "KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT TCP_NO_NEW_CONN",
            "Socket": "tls:10.20.0.248:5061",
            "Methods": "7999",
            "SIP_instance": "<urn:uuid:a0276171-6b66-48c8-8fe3-0004134DEC0E>",
            "KV-Store": "{\"CID\":\"313534313339343231343430373138-05m2ah8mb1xw\",\"Con\":\"sip:200@10.20.0.248:5060;x-proxy\",\"F\":\"sip:200@sip.test.com\",\"LRTs\":0,\"Seq\":123,\"T\":\"sip:200@sip.test.com\",\"exp\":3600,\"expO\":3600,\"ru\":\"sip:10.30.10.247\"}"
          }
        },
        {
          "value": "{\"CID\":\"313534313339343231343430373138-05m2ah8mb1xw\",\"Con\":\"sip:200@10.20.0.248:5060;x-proxy\",\"F\":\"sip:200@sip.test.com\",\"LRTs\":1541508584,\"Seq\":123,\"T\":\"sip:200@sip.test.com\",\"expO\":3600,\"ru\":\"sip:10.30.10.247\"}"
        }
      ]
    }
  }
]

```
Ok, but still I can get data from it and send REGISTER to registrar with t_uac_dlg. But how does registrar accept this request? It doesn't contain any auth data. May be I'm doing something totally wrong?

**Comment by vasilevalex** [comment]
@liviuchircu Sorry, that I write here. Start from last

- I'll think what to do with auth. Thanks, now I understand approach.
- yes, of course, KV-Store JSON contains all the information. I just want to mention, how it presents in JSON output. AOR MI node contains array of children. And this array named by first child - "Contact". Then each contact is member of array and has "value" and children hash with other properties. But AOR's KV-Store is also added as child of AOR MI tree and in JSON output it is just last element in array "Contact".
To my mind, this looks more logical:
```
{
  "AOR": [
    {
      "value": "200",
      "attributes": {
        "KV-Store": "{\"CID\":\"313534313531343234303438313331-fk0gn5ltghov\",\"Con\":\"sip:200@10.20.0.248:5060;x-proxy\",\"F\":\"sip:200@sip.test.com\",\"LRTs\":1541577985,\"Seq\":48,\"T\":\"sip:200@sip.test.com\",\"expO\":3600,\"noDR\":1,\"ru\":\"sip:10.30.10.247\"}"
      },
      "children": {
        "Contact": [
          {
            "value": "sip:200@172.16.1.29:2104;transport=tls",
            "attributes": {
              "Q": "1"
            },
            "children": {
              "ContactID": "3160049194787252491",
              "Expires": "2323",
              "Callid": "313534313531343234303438313331-fk0gn5ltghov",
              "Cseq": "42",
              "User-agent": "snom",
              "Received": "sip:192.168.10.138:2104;transport=tls",
              "State": "CS_NEW",
              "Flags": "0",
              "Cflags": "KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT TCP_NO_NEW_CONN",
              "Socket": "tls:10.20.0.248:5061",
              "Methods": "7999",
              "SIP_instance": "<urn:uuid:a0276171-6b66-48c8-8fe3-0004134DEC0E>",
              "KV-Store": "{\"_urec_kvs\":\"{\\\"CID\\\":\\\"313534313531343234303438313331-fk0gn5ltghov\\\",\\\"Con\\\":\\\"sip:200@10.20.0.248:5060;x-proxy\\\",\\\"F\\\":\\\"sip:200@sip.test.com\\\",\\\"LRTs\\\":1541577985,\\\"Seq\\\":48,\\\"T\\\":\\\"sip:200@sip.test.com\\\",\\\"expO\\\":3600,\\\"noDR\\\":1,\\\"ru\\\":\\\"sip:10.30.10.247\\\"}\"}"
            }
          },
          {
            "value": "sip:200@172.16.1.29:2110;transport=tls",
            "attributes": {
              "Q": "1"
            },
            "children": {
              "ContactID": "3160049194786376873",
              "Expires": "3323",
              "Callid": "313534313531343234303438313331-fk0gn5ltghov",
              "Cseq": "48",
              "User-agent": "snom",
              "Received": "sip:192.168.10.138:2110;transport=tls",
              "State": "CS_NEW",
              "Flags": "0",
              "Cflags": "KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT TCP_NO_NEW_CONN",
              "Socket": "tls:10.20.0.248:5061",
              "Methods": "7999",
              "SIP_instance": "<urn:uuid:a0276171-6b66-48c8-8fe3-0004134DEC0E>",
              "KV-Store": "{\"LRTs\":1541577985,\"Seq\":48,\"exp\":3600,\"expO\":3600}"
            }
          }
        ]
      }
    }
  ]
}
```
With this change https://github.com/vasilevalex/opensips/commit/d7665381814afee93677df5f9816074fc06ead5d
But it looks not good with display from opensipsctl. And may be MI node "attribute" is for another purpose...
