### ISSUE TITLE
SIP-I ISUP 'Redirecting number' parameter support

### ISSUE THREAD

**Issue by enp** [OpenSIPS/opensips#1323]
I need to extract ISUP parameter 'Redirecting number' from SIP-I
INVITE request and add it as SIP header with 'X-' prefix to process in
FreeSWITCH. Discussion (and even patch) is here - http://lists.opensips.org/pipermail/users/2018-March/039171.html - is it possible to apply it?

**Comment by enp** [comment]
Thank you! Which binary release will contain this fix and when in will be ready?

**Comment by rvlad-patrascu** [comment]
The first release to feature this will be 2.4.0 stable on 30th of April.
