### ISSUE TITLE
tm: got garbage from $T_id (usage of local memory buffer after function exit), 2.3 branch.

### ISSUE THREAD

**Issue by sisoftrg** [OpenSIPS/opensips#1326]
I want to get transaction id to use in MI t_reply command. but instead of hexa encoded id's I got some trash from memory. I see the code and found this in tm.c:
```c
static int pv_get_t_id(struct sip_msg *msg, pv_param_t *param, pv_value_t *res) {
    char buf[INTasHEXA_SIZE+1+INTasHEXA_SIZE];
 [skipped]
    res->flags = PV_VAL_STR;
    res->rs.s = buf;
    res->rs.len = p-buf;
    return 0;
}
```
Dangerous and not working code, because memory from `buf` can be freed or reused immediately after leaving this function.
Making this buffer static solves problem, but I think it should be fixed in more correct way.

**Comment by liviuchircu** [comment]
"can be freed" is a very nice way of putting it :) IMO, `static` is actually a clean solution, as we cannot allocate memory dynamically while also ensuring that calling code frees it.
