### ISSUE TITLE
Wrong "via-branch" value in offer to rtpengine if multiple branch exist and use topology_hiding().

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1327]
Hello collegues! Can you help with fix the problem below?

SIP sheme: softswitch <-INT-> opensips  <-EXT-> B(user)
RTP scheme: rtpproxy  <-INT-> rtpengine <-EXT-> B(user)

Two UA registered by one SIP URI(user1@sipnet.com) - CSipSimple and SIPP. After lookup() i have two branches.
In main route i call topology hiding, before processing of incoming INVITE. Values branch in via:
1) INVITE request from softswitch to opensips:
```
Request-Line: INVITE sip:user1@sipnet.com SIP/2.0
Via: SIP/2.0/UDP 10.10.10.17:5093;branch=z9hG4bK-524287-1---77b714677bf3f14b;rport
```
2) INVITE request from opensips to UA(SIPP), first branch:
```
Request-Line: INVITE sip:user1@89.200.250.249:33999 SIP/2.0
Via: SIP/2.0/UDP 71.80.80.40:5060;branch=z9hG4bKfd04.b6d3a3f6.1
```
3) INVITE request from opensips to UA(CSipSimple), second branch:
```
Request-Line: INVITE sip:user1@30.0.0.235:4169;ob SIP/2.0
Via: SIP/2.0/UDP 71.80.80.40:5060;branch=z9hG4bKfd04.b6d3a3f6.2
```
Scheme:

```           
                                                                        INVITE with branch=z9hG4bKfd04.b6d3a3f6.1
                                                                  |>    ---------------------------------->SIPP
               IVITE with branch=z9hG4bK-524287-1-...             |      
sotftswitch--------------------------------------------------> opensips 
                                                                  |     ---------------------------------->CSipSimple
                                                                  |>    INVITE with branch=z9hG4bKfd04.b6d3a3f6.2
```

In branch route for each branch, a function is called - 'rtpengine_offer("RTP/AVP replace-origin replace-session-connection ICE=remove via-branch=1 internal external");'.
In this case rtpengine_offer calls twice. In rtpengine debug logs i see it:
1) rtpengine_offer in first branch, rtpengine received:
```
Mar 30 13:53:37 rtpengine[18411]: DEBUG: [bYHCS6cPo8UMTflyVknHRw..]: ... col": "RTP/AVP", "call-id": "bYHCS6cPo8UMTflyVknHRw..", "via-branch": "z9hG4bK-524287-1---1a60a966229d8c43"...
```
2) rtpengine_offer in second branch, rtpengine received:
```
Mar 30 13:53:37 rtpengine[18411]: DEBUG: [bYHCS6cPo8UMTflyVknHRw..]: ... col": "RTP/AVP", "call-id": "bYHCS6cPo8UMTflyVknHRw..", "via-branch": "z9hG4bK-524287-1---1a60a966229d8c43",
```

**Opensips in offer to rtpengine put in "via-branch" same value from incoming INVITE.** I think decision may be:
a) opensips automatically put correct branch value in rtpengine_offer
b) use 'extra_id_pv' of rtpengine module, but i don`t understand where i may get "branch" value(in Via) of each new branch.
Thanks for help!

**Comment by kertor** [comment]
Opensips version:
```
version: opensips 2.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 0bef0f4
main.c compiled on 13:53:57 Jun 21 2017 with gcc 4.8.3
```

**Comment by bogdan-iancu** [comment]
Hi @kertor. I think this is TH unrelated and it is more about the correct configuration/usage of RTPengine.

As per documentation, if you want to do per-branch sessions you need to use the `extra_id_pv` (your plan b) in conjunction with the `via-branch=extra` when invoking rtpengine. BTW, the default `via-branch=via1` for requests fetches branch value from the **incoming** VIA hdr and not from outgoing VIA.

So you may try to construct the `extra_id_pv` to hold the branch via1 + [$T_branch_idx](http://www.opensips.org/html/docs/modules/2.3.x/tm.html#idp5857328) value.

**Comment by kertor** [comment]
Thanks for reply @bogdan-iancu , i fix config and rtpengine receives via1 + '.' + $T_branch_idx in offers.
One question more on theme, please) In moment, when opensips receives 200 ok response from CSipSimple, he generate CANCEL to the not answered SIPP. This CANCEL must trigger rtpengine_delete() with to_tag of the cancelled branch. I dont understand how i may to catch this auto-CANCEL in the config, any idea how possible to do it?

**Comment by kertor** [comment]
Very thanks for help! Now i known, what i must to do further)
