### ISSUE TITLE
gentoo compile opensips error(opensips-2.1.0.ebuild)

### ISSUE THREAD

**Issue by liulanghaitun** [OpenSIPS/opensips#1331]
This is the error links:   https://bpaste.net/show/21a799e1c8ff

**Comment by bogdan-iancu** [comment]
woow....the 2.1 is obsolete (see http://www.opensips.org/About/AvailableVersions). Even more, the 2.1.0 is one of the first, so even harder to say.
Checking the latest 2.1 (2.1.5), I do not see anymore the reset_proc_debug_level() function as inline...So maybe the issues you are facing were already fixed. Tty getting some newer versions.

**Comment by liulanghaitun** [comment]
Can anyone update the gentoo ebuild file?

**Comment by bogdan-iancu** [comment]
Not sure who's the maintainer of the opensips package on OpenSIPS; for sure it is not us. If you are able to extract such info from the package, we can try to contact the person.

**Comment by liulanghaitun** [comment]
I change the opensips-2.1.0.ebuild  to opensips-2.3.3.ebuid 
 http://bpaste.net/show/f8f394a6cfef .

Compilation success, but hints the follow error:
Cannot load core functions '/usr/sbin/opensipsctl.base' - exiting ...

**Comment by bogdan-iancu** [comment]
The error you mentioned is a runtime error (while trying to use opensipsctl) or an error still at install time ?

**Comment by liulanghaitun** [comment]
installation is successful, it should be code problem. Now it should be a configuration problem.
Thansks!

**Comment by bogdan-iancu** [comment]
What is the resulting installation path for the opensipsctl tool ?

**Comment by liulanghaitun** [comment]
I compile and install it through source code, not using ebuild installation.

**Comment by bogdan-iancu** [comment]
ok, so you did a manual installation from the sources and not using ebuild. Have you defined a custom installation prefix ? by default opensips installs itself under /usr/local, so you should find the binaries under /usr/local/sbin/  .

**Comment by bogdan-iancu** [comment]
ping....
