### ISSUE TITLE
MI JSON + benchmark module

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1332]
Hi team.

Latest 2.3.

"opensipsctl fifo bm_poll_results" prints:
LOOKUP_RATE
	2/15203767/26086/15177681/7601883.500000
	2060/18273264741718986/8357/1522771447335678/8870516864912.128906

but MI JSON prints only:
{'': [{'value': 'LOOKUP_RATE', 'children': {'value': '2060/18273264741718986/8357/1522771447335678/8870516864912.128906'}}]}

how to get first string? Looks like bug.

**Comment by bogdan-iancu** [comment]
Please try this patch:

```
diff --git a/modules/benchmark/benchmark.c b/modules/benchmark/benchmark.c
index e49a704..7465605 100644
--- a/modules/benchmark/benchmark.c
+++ b/modules/benchmark/benchmark.c
@@ -650,6 +650,7 @@ static void add_results_node(struct mi_node *node, benchmark_timer_t *timer) {
        struct mi_node *timer_node;
 
        timer_node = addf_mi_node_child(node, 0, 0, 0, "%s", timer->name);
+       timer_node->flags |= MI_IS_ARRAY;
        addf_mi_node_child(timer_node, 0, 0, 0,
                        "%i/%lld/%lld/%lld/%f",
                        timer->calls,
```

**Comment by nikbyte** [comment]
It helps. Now it looks like:
{"": [{"value":"LOOKUP_RATE", "children":{"": [{"value":"6/5870133/23314/5738137/978355.500000"}, {"value":"18/4568368990602351/22909/1522789664358217/253798277255686.156250"}]}}]}

Thank you!
