### ISSUE TITLE
remove_hf() must be case insensitive

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1333]
Hi team,

opensips 2.3

it looks like remove_hf() with g or r flags is case sensitive. But SIP headers are not case sensitive.

**Comment by bogdan-iancu** [comment]
Checking with the code, I see that the "r" flag (when using a regexp in first param) is triggering an case insensitive matching - are you sure about your test ?

**Comment by nikbyte** [comment]
Let me recheck. I'll be back soon.

**Comment by nikbyte** [comment]
You're right. "r" flag is case insensitive. But "g" flag is still case sensitive and it's the issue.
