### ISSUE TITLE
ipv6 address check

### ISSUE THREAD

**Issue by pasanmdev** [OpenSIPS/opensips#1334]
Hi Guys,

I'm testing ipv6 on opensips 2.3. and I'm using the following script function to findout if the requesting ip is already registered with that ip.
But the function is failing with following error message.

script function call
is_ip_registered("location","$var(aor)","$si"));

error message from logs.

ERROR:permissions:check_addr_6: invalid ip set <24xx:xxx:0:1:x000:0:0:2>

There's an AOR already with that IP

0 [ 3/04 18:53:29] root@:/root>> opensipsctl ul show
Domain:: location table=512 records=1
        AOR:: 0xxxx
                Contact:: sip: 0xxxx@[24xx:xxx:0:1:x000::2];line=180c0d2da1b3e81 Q=
                        ContactID:: 3275524303981917232
                        Expires:: 3495
                        Callid:: 490179714
                        Cseq:: 2
                        User-agent:: Linphone/3.6.1 (eXosip2/4.1.0)
                        Received:: sip:[2400:xxx:0:1:x000:0:0:2]:5060
                        State:: CS_SYNC
                        Flags:: 0
                        Cflags:: PING NAT
                        Socket:: udp:[24xx:xx0:1D:F0:0:0:1:88]:5060
                        Methods:: 4294967295

It appears to be failing at /modules/permissions/address.c line 517 . looks like str2ip function in line 515 doesn't return a valid ip.

**Comment by bogdan-iancu** [comment]
@pasanmdev , the report is a bit confusion and you mentioned calling the is_ip_registered() function, while the reported error comes from the permissions module, from a check[_source]_address() function.
Anyhow, I did the fix for the permission module, if you could give it a try and confirm it...so I can do a backport.

**Comment by pasanmdev** [comment]
@bogdan-iancu It was puzzling me too. as to why error pops up from permission module. .I have check_address() function call before is_ip_registered() function. probably it would be the reason it show in the log. But anyhow is_ip_registered() function fails too, when I remove it from condition check script continues normally.

I'll get this build and test and report back soon.

**Comment by pasanmdev** [comment]
@bogdan-iancu on further investigation I found following in my log when starting opensips

DBG:core:fix_actions: fixing is_ip_registered, /etc/opensips/opensips.cfg:970

and following is whats at line 970 in my config
	$var(aor) = "sip:" + $(au{s.escape.common}) + "@" + $(fd{s.escape.common});
            if(is_ip_registered("location","$var(aor)","$si")){
                xlog("L_INFO","Call: Auth INVITE - From=$fU from_uri=$fu Auth_user=$au Request=$rU IP=$si AOR=$var(aor) ID=$ci");
            } else {
                xlog("L_WARN","Call: Auth INVITE from Unregistered IP - From=$fU from_uri=$fu Auth_user=$au Request=$rU IP=$si Via=$avp(vip) AOR=$var(aor) ID=$ci");
                sl_send_reply("401", "Unauthorized");
                exit;
            }
Am I using the function in a wrong way ? whats the fix_actions do to the function call ?
And when I make a test call I can't see is_ip_registered func getting call in debug log. It only prints my debug line which is "Call: Auth INVITE from Unregistered IP -"

**Comment by pasanmdev** [comment]
@bogdan-iancu your fix works, it handles ipv6 address properly now.

Apr  5 14:10:41 voip2-sip23a /usr/sbin/opensips[10017]: DBG:core:check_ip_address: params 24x0:xxx0:0:1:6000:0:0:2, [2x00:xxx0:0:1:6000::2], 0
Apr  5 14:10:41 voip2-sip23a /usr/sbin/opensips[10017]: DBG:core:parse_headers: flags=ffffffffffffffff
Apr  5 14:10:41 voip2-sip23a /usr/sbin/opensips[10017]: DBG:permissions:check_addr_6: Looking for : <0, 2400:A240:0:1:6000:0:0:2, udp, 5060, >
Apr  5 14:10:41 voip2-sip23a /usr/sbin/opensips[10017]: DBG:permissions:hash_match: no match in the hash table
Apr  5 14:10:41 voip2-sip23a /usr/sbin/opensips[10017]: DBG:permissions:match_subnet_table: subnet table is empty

**Comment by pasanmdev** [comment]
@bogdan-iancu also db back address table only appears to be handle ipv4 address. I can't specify an ipv6 address with mask greater than 32. I submit it separately.

**Comment by bogdan-iancu** [comment]
@pasanmdev , I did the backport, I will close this ticket and look for the other one on the mask.
