### ISSUE TITLE
Opensips Crashed

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1335]
Hello,

I use stable LTS:
version: opensips 2.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 6a921f1
main.c compiled on 01:08:40 Mar 10 2018 with gcc 4.4.7

Opensips crased. 
Here is dump log:
https://pastebin.com/aFcbjkLZ

Best regards,
Dragomir

**Comment by razvancrainea** [comment]
Unfortunately the core dump is no longer available on pastebin. Can you send it again?
If not, do you remember the funciton where opensips was crashing?

**Comment by bogdan-iancu** [comment]
@goup2010, could you update here ?

**Comment by goup2010** [comment]
In last few mount Opensips working without crash.

На вт, 19.06.2018 г. в 10:32 ч. Bogdan Andrei IANCU <
notifications@github.com> написа:

**Comment by bogdan-iancu** [comment]
I'm quite sure the bug is still there, but if you do not have the corefile (so no way to investigate), we can close and eventually reopen if it happens again.
But as a final check with you - you do not have anymore the corefile and binary ?
