### ISSUE TITLE
opensipsctl  dispatcher

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips#1338]
Hello Everyone,
Opensipsctl  dispatcher  add new gateway is not working  when I try  insert into column weight freeswitch event socket syntax.

[root@casbc00 ~> [~]# rpm -qa | grep opensips
opensips-db_mysql-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-2.4.3.0d494e5e6-11.fc27.x86_64

```
[root@casbc00 ~> [~]# opensipsctl dispatcher addgw 1 sip:my_ip:5160 '' 0 'fs://:my_passwd@my_freeswitch_ip:8021' '' 'FS casip00'
ERROR:  syntax error at or near ":"
LINE 1: ...ion) VALUES (1, 'sip:my_ip:5160', '', 0, fs://:my_paswd...
                                                             ^
ERROR: dispatcher - SQL Error
```

**Comment by bogdan-iancu** [comment]
Starting with 2.3, the `weight` column was changed from integer to string - http://www.opensips.org/Documentation/Install-DBSchema-2-3#AEN4379 -, so the DB ops should reflect this change (like adding the quotes here).
