### ISSUE TITLE
drouting with srv lookup

### ISSUE THREAD

**Issue by pasanmdev** [OpenSIPS/opensips#1340]
Hi Guys,

I'm testing a dual-stack environment with drouting and I have setup a gateway address to have a both v4 and v6 address by appropriately setting up the srv records. 
My intention was opensips would pickup the v6 ip when a request received via its v6 address and vice versa. But It only always pickup the first record which is v4 address, is it the expected behavior ? 

I could see in the debug logs opensips picks up the v6 hostname but it only use v4 address when call is forwarded to gateway. (However dns based fail over works as expeted if v4 address is not responding it'll try v6 address )

DBG:core:mk_proxy: doing DNS lookup...
DBG:core:sip_resolvehost: no port, no proto -> do NAPTR lookup!
DBG:core:get_record: lookup(voip2gw.xx.xx, 35) failed
DBG:core:sip_resolvehost: no valid NAPTR record found for voip2gw.xx.xx, trying direct SRV lookup...
DBG:core:do_srv_lookup: resolving [voip2-gwv4.xx.xx.xx.xx]
DBG:core:do_srv_lookup: SRV(_sip._udp.voip2gw.xx.xx.xx) = voip2-gwv4.xx.xx:5060
DBG:core:a2dns_node: storing voip2-gwv6.xx.xx.xx:5060

My SRV records

;; QUESTION SECTION:
;_sip._udp.voip2gw.xx.xx. IN    SRV

;; ANSWER SECTION:
_sip._udp.voip2gw.xx.xx. 1800 IN SRV    5 1 5060 voip2-gwv6.xxx.xxx
_sip._udp.voip2gw.xx.xx. 1800 IN SRV    5 1 5060 voip2-gwv4.xxx.xxx.

;; ADDITIONAL SECTION:
voip2-gwv4.xxx.xxx 1800 IN  A       10.3.1.142
voip2-gwv6.xxx.xxx. 417 IN   AAAA    2x0x:xx00:xx:f1::1:8d

If opensips use same address family when it does the forwarding for drouting to a received request I could avoid use of rtpengine to bridge the two endpoints.

**Comment by bogdan-iancu** [comment]
Hi @pasanmdev , the drouting module is not ipv4 / ipv6 aware. If you want to force different routing depending on the AF, you need to place the rules and the gateways accordingly (maybe using different routing groups, one per AF). 
So, what you describe there is the intended behavior of the module.

In your case, maybe you should not use SRV, but point directly to the A/AAAA records, in order to control the ipv4/ipv6 routing (especially if your opensips can do bridging between the two).

**Comment by pasanmdev** [comment]
@bogdan-iancu Thanks for the reply. That's what I thought if this was the intended behavior. I'll setup routing groups separately for v4 and v6.

**Comment by pasanmdev** [comment]
@bogdan-iancu I figured a workaround using force_send_socket which will not make mess on drouting tables :) what I did was detect the AF and force opensips outgoing socket to use appropriate socket with corresponding AF.

**Comment by bogdan-iancu** [comment]
That's a nice approach ! :+1:
