### ISSUE TITLE
[script] $branch(flags) returns bitmask, not list of flags

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#1341]
and it should not be settable.

**Comment by liviuchircu** [comment]
Any specific reason why we would want it to be read-only? Keep in mind that `$branch` is fully read-write now.

```
$(branch(flags)[2]) = "SIPPING_ENABLE SIPPING_RTO";
```
To me, this ^ looks fine, and should be allowed.

**Comment by bogdan-iancu** [comment]
it makes sense.
