### ISSUE TITLE
After restart opensips dialogs lost sdp section of callee and caller

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1342]
Hello collegues! Find some "strange behavior" after restart opensips.
**First. dialogs lost sdp section of callee and caller** 
Dialog before restart opensips:
```
dialog::  ID=141897505221
	state:: 4
	user_flags:: 0
	timestart:: 1523618028
	datestart:: 2018-04-13 11:13:48
	timeout:: 1523621628
	dateout:: 2018-04-13 12:13:48
	callid:: 146-20214@1.1.1.1
	from_uri:: sip:3019878165@1.1.1.1:5060
	to_uri:: sip:service@5.5.5.5:5060
	caller_tag:: 20214SIPpTag00146
	caller_contact:: sip:X.did.12.8bb6da52@4.4.4.4
	callee_cseq:: 0
	caller_route_set:: 
	caller_bind_addr:: udp:3.3.3.3:5060
	caller_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 2.2.2.2
s=-
c=IN IP4 2.2.2.2
t=0 0
m=audio 17204 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtcp:17205
	CALLEES:: 
		callee:: 
			callee_tag:: 18093SIPpTag0152
			callee_contact:: sip:X.did.12.9bb6da52@4.4.4.4
			caller_cseq:: 1
			callee_route_set:: 
			callee_bind_addr:: udp:3.3.3.3:5060
			callee_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 2.2.2.2
s=-
c=IN IP4 2.2.2.2
t=0 0
m=audio 17218 RTP/AVP 0
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtcp:17219
```
Dialog after restart opensips:
```
dialog::  ID=141897505221
    state:: 4
    user_flags:: 0
    timestart:: 1523618028
    datestart:: 2018-04-13 11:13:48
    timeout:: 1523621629
    dateout:: 2018-04-13 12:13:49
    callid:: 146-20214@1.1.1.1
    from_uri:: sip:3019878165@1.1.1.1:5060
    to_uri:: sip:service@5.5.5.5:5060
    caller_tag:: 20214SIPpTag00146
    caller_contact:: sip:X.did.12.8bb6da52@4.4.4.4
    callee_cseq:: 0
    caller_route_set:: 
    caller_bind_addr:: udp:3.3.3.3:5060
    caller_sdp:: 
    CALLEES:: 
        callee:: 
            callee_tag:: 18093SIPpTag0152
            callee_contact:: sip:X.did.12.9bb6da52@4.4.4.4
            caller_cseq:: 1
            callee_route_set:: 
            callee_bind_addr:: udp:3.3.3.3:5060
            callee_sdp:: 
```

SDP is lost.
db_mode=1

**Second. After restart Opensips stops pinging dialogs use in-dialog Re-INVITE SIP messages.**
Use:
modparam("dialog", "reinvite_ping_interval", 60)
create_dialog("BRr");

version=latest 2.3 from git

**Comment by bogdan-iancu** [comment]
Hi @kertor , this is a know issue - as OpenSIPS is caching and re-using the latest received SDP (from end point) when generating the re-INVITE, an restart event will loose the cached SDP, so the next re-INVITEs will have nothing to carry.
An idea of  @liviuchircu  is to serialize and store the SDP into a dedicated dialog value which is restart persistent via DB.

**Comment by kertor** [comment]
Hi Bogdan. Any idea about second issue - after restart opensips, it stops to pinging dialogs use in-dialog Re-INVITE SIP messages?

**Comment by nikbyte** [comment]
I suspect https://github.com/OpenSIPS/opensips/commit/5444c8c613ebdc529a936a5f5ba40a6180f621d6 will fix ping issue, but sdp is still required.

**Comment by bogdan-iancu** [comment]
Oh..sorry, I missed that . So, after an restart, there is no in-dialog pinging any more ?

**Comment by kertor** [comment]
Hello! In-dialog ping(reINVITE) not work after restart opensips. I checked this on a new build with this commit.

**Comment by kertor** [comment]
Thanks!
