### ISSUE TITLE
Accounting variables swapping

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1344]
Hello team,

we expect accounting variables swapping after restart:

without restart
Apr 18 21:11:22 localhost opensips[30586]: Apr 18 21:11:22 [30858] var(time)=1524085816
Apr 18 21:11:22 localhost opensips[30586]: Apr 18 21:11:22 [30858] var(created)=1524085815
Apr 18 21:11:22 localhost opensips[30586]: Apr 18 21:11:22 [30858] var(setuptime)=1
Apr 18 21:11:22 localhost opensips[30586]: Apr 18 21:11:22 [30858] var(duration)=66

after restart
Apr 18 21:12:44 localhost opensips[30932]: Apr 18 21:12:44 [31143] var(time)=1524085895
Apr 18 21:12:44 localhost opensips[30932]: Apr 18 21:12:44 [31143] var(created)=0
Apr 18 21:12:44 localhost opensips[30932]: Apr 18 21:12:44 [31143] var(setuptime)=1524085895
Apr 18 21:12:44 localhost opensips[30932]: Apr 18 21:12:44 [31143] var(duration)=69

it looks like created and setuptime variables are swapped.

**Comment by nikbyte** [comment]
Additional info:
- latest 2.3 from git
- evi accounting
- dialog persistence using postgresql

**Comment by bogdan-iancu** [comment]
@nikbyte , please provide the output of:
* `dlg_list_dlg dlg_id` MI command before the restart (for that dialog) 
* the `dlg_vals` db column for that dialog, while opensips is stopped 
* `dlg_list_dlg dlg_id` MI command after the restart (for that dialog)

**Comment by nikbyte** [comment]
Before restart. opensipsctl fifo dlg_list_ctx:
dialog::  ID=12641401924923
    state:: 4
    user_flags:: 0
    timestart:: 1524257149
    datestart:: 2018-04-20 20:45:49
    timeout:: 1524260749
    dateout:: 2018-04-20 21:45:49
    callid:: 1-13230@1.1.1.1
    from_uri:: sip:7742532622@1.1.1.1:5060
    to_uri:: sip:service@3.3.3.3:5060
    caller_tag:: 13230SIPpTag001
    caller_contact:: sip:X.did.f7b.7b433f43@10.0.4.51
    callee_cseq:: 0
    caller_route_set:: 
    caller_bind_addr:: udp:10.0.4.52:5060
    caller_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 7.7.7.7
s=-
c=IN IP4 7.7.7.7
t=0 0
m=audio 10012 RTP/AVP 0
a=rtpmap:0 PCMU/8000
    CALLEES:: 
        callee:: 
            callee_tag:: 
            callee_contact:: 
            caller_cseq:: 
            callee_route_set:: 
            callee_bind_addr:: 
            callee_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 1.1.1.1
s=-
c=IN IP4 1.1.1.1
t=0 0
m=audio 6000 RTP/AVP 0
a=rtpmap:0 PCMU/8000
        callee:: 
            callee_tag:: 12413SIPpTag014
            callee_contact:: sip:X.did.f7b.8b433f43@10.0.4.51
            caller_cseq:: 1
            callee_route_set:: 
            callee_bind_addr:: udp:10.0.4.52:5060
            callee_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 1.1.1.1
s=-
c=IN IP4 1.1.1.1
t=0 0
m=audio 6000 RTP/AVP 0
a=rtpmap:0 PCMU/8000
    context:: 
        values:: 
            accX_created:: |Q\xdaZ\x00\x00\x00\x00
            accX_flags:: \x00\x00\x00\x00\x0f\x00'\x00
            accX_extra:: =\x00\x0b\x0017742532622\x0b\x0015122031234\x0b\x0015125770082\x00\x00\f\x001.1.1.1\f\x007.7.7.7\x04\x005061\x01\x001\x01\x002\x02\x0011\x01\x001\x04\x001111\x01\x00E\x01\x000\x01\x000\x01\x000\n\x000.00207000\n\x000.00001000\x01\x00E\x01\x006\x01\x006\x01\x006\x01\x006\x05\x001002#\f\x003.3.3.3\r\x00United States\x03\x00512\x0f\x00NORMAL_CLEARING\x01\x001\x01\x001\n\x007742532622\x07\x00service\x00\x00\x00\x00\x0b\x0015122031234\n\x005125770082\x03\x00128\x04\x006889\t\x00WORCESTER\x03\x00558\x04\x006529\x06\x00AUSTIN\x03\x00558\x04\x006529\x06\x00AUSTIN\x00\x00\x00\x00\x00\x00\x07\x001512577\n\x001524257148\t\x0010.0.4.52\x01\x000\n\x001524257148\x01\x008\x01\x006\x01\x006\x01\x000\x01\x000\x00\x00\x00\x00\x01\x001
            accX_ctx:: X\xb4\x1d\r\x97\x7f\x00\x00
            accX_core:: \x06\x00INVITE\x0f\x0013230SIPpTag001\x0f\x0012413SIPpTag014\x14\x001-13230@1.1.1.1\x03\x00200\x02\x00OK\x10\x00}Q\xdaZ\x00\x00\x00\x00\xc9\xaf\t\x00\x00\x00\x00\x00
            vst:: sip:service@3.3.3.3:5060
            vsf:: sip:7742532622@1.1.1.1:5060
            739824:: sip:1002#15122031234@7.7.7.7
            739823:: sip:17742532622@3.3.3.3
            min_bye:: 8
            delay_bye:: 1
        profiles:: 
            dialog:: tg|11|conn
            dialog:: ts|all|conn
            dialog:: ts|1|conn
            dialog:: tg|11|init
            dialog:: ts|all|init
            dialog:: ts|1|init

While opensips stopped, dlg_vals is:
COPY public.dialog (dlg_id, callid, from_uri, from_tag, to_uri, to_tag, mangled_from_uri, mangled_to_uri, caller_cseq, callee_cseq, caller_ping_cseq, callee_ping_cseq, caller_route_set, callee_route_set, caller_contact, callee_contact, caller_sock, callee_sock, state, start_time, timeout, vars, profiles, script_flags, module_flags, flags) FROM stdin;
12641401924923  1-13230@1.1.1.1 sip:7742532622@1.1.1.1:5060 13230SIPpTag001 sip:service@3.3.3.3:5060    12413SIPpTag014 sip:17742532622@3.3.3.3 sip:1002#15122031234@7.7.7.7    01  0   0   \N  \N  sip:X.did.f7b.7b433f43@10.0.4.51    sip:X.did.f7b.8b433f43@10.0.4.51    udp:10.0.4.52:5060  udp:10.0.4.52:5060  4   1524257149  1524260750  \\x616363585f63726561746564235c7c51da5a000000007c616363585f666c61677323000000000f0027007c616363585f6578747261233d000b0031373734323533323632320b0031353132323033313233340b00313531323537373030383200000c0036362e3139382e33382e36300c0036362e3139382e33382e3631040035303631010031010032020031310100310400313131310100450100300100300100300a00302e30303230373030300a00302e30303030313030300100450100360100360100360100360500313030325c230c0036362e3139382e33382e35310d00556e697465642053746174657303003531320f004e4f524d414c5f434c454152494e470100310100310a0037373432353332363232070073657276696365000000000b0031353132323033313233340a003531323537373030383203003132380400363838390900574f524345535445520300353538040036353239060041555354494e0300353538040036353239060041555354494e0000000000000700313531323537370a0031353234323537313438090031302e302e342e35320100300a0031353234323537313438010038010036010036010030010030000000000100317c616363585f6374782358b41d0d977f00007c616363585f636f7265230600494e564954450f003133323330534950705461673030310f003132343133534950705461673031341400312d31333233304036362e3139382e33382e3630030032303002004f4b10007d51da5a00000000c9af0900000000007c767374237369703a736572766963654036362e3139382e33382e35313a353036307c767366237369703a373734323533323632324036362e3139382e33382e36303a353036307c373339383234237369703a313030325c2331353132323033313233344036362e3139382e33382e36317c373339383233237369703a31373734323533323632324036362e3139382e33382e35317c6d696e5f62796523387c64656c61795f62796523317c   dialog/b#tg\\|11\\|conn|dialog/b#ts\\|all\\|conn|dialog/b#ts\\|1\\|conn|dialog/b#tg\\|11\\|init|dialog/b#ts\\|all\\|init|dialog/b#ts\\|1\\|init|    0   0   31000
\.

After restart opensipsctl fifo dlg_list_ctx
dialog::  ID=12641401924923
    state:: 4
    user_flags:: 0
    timestart:: 1524257149
    datestart:: 2018-04-20 20:45:49
    timeout:: 1524260751
    dateout:: 2018-04-20 21:45:51
    callid:: 1-13230@1.1.1.1
    from_uri:: sip:7742532622@1.1.1.1:5060
    to_uri:: sip:service@3.3.3.3:5060
    caller_tag:: 13230SIPpTag001
    caller_contact:: sip:X.did.f7b.7b433f43@10.0.4.51
    callee_cseq:: 0
    caller_route_set:: 
    caller_bind_addr:: udp:10.0.4.52:5060
    caller_sdp:: 
    CALLEES:: 
        callee:: 
            callee_tag:: 12413SIPpTag014
            callee_contact:: sip:X.did.f7b.8b433f43@10.0.4.51
            caller_cseq:: 1
            callee_route_set:: 
            callee_bind_addr:: udp:10.0.4.52:5060
            callee_sdp:: 
    context:: 
        values:: 
            delay_bye:: 1
            min_bye:: 8
            739823:: sip:17742532622@3.3.3.3
            739824:: sip:1002#15122031234@7.7.7.7
            vsf:: sip:7742532622@1.1.1.1:5060
            vst:: sip:service@3.3.3.3:5060
            accX_core:: \x06\x00INVITE\x0f\x0013230SIPpTag001\x0f\x0012413SIPpTag014\x14\x001-13230@1.1.1.1\x03\x00200\x02\x00OK\x10\x00}Q\xdaZ\x00\x00\x00\x00\xc9\xaf\t\x00\x00\x00\x00\x00
            accX_ctx:: H\xa5\xd5\xb1\xf6\x7f\x00\x00
            accX_extra:: =\x00\x0b\x0017742532622\x0b\x0015122031234\x0b\x0015125770082\x00\x00\f\x001.1.1.1\f\x007.7.7.7\x04\x005061\x01\x001\x01\x002\x02\x0011\x01\x001\x04\x001111\x01\x00E\x01\x000\x01\x000\x01\x000\n\x000.00207000\n\x000.00001000\x01\x00E\x01\x006\x01\x006\x01\x006\x01\x006\x05\x001002#\f\x003.3.3.3\r\x00United States\x03\x00512\x0f\x00NORMAL_CLEARING\x01\x001\x01\x001\n\x007742532622\x07\x00service\x00\x00\x00\x00\x0b\x0015122031234\n\x005125770082\x03\x00128\x04\x006889\t\x00WORCESTER\x03\x00558\x04\x006529\x06\x00AUSTIN\x03\x00558\x04\x006529\x06\x00AUSTIN\x00\x00\x00\x00\x00\x00\x07\x001512577\n\x001524257148\t\x0010.0.4.52\x01\x000\n\x001524257148\x01\x008\x01\x006\x01\x006\x01\x000\x01\x000\x00\x00\x00\x00\x01\x001
            accX_flags:: \x00\x00\x00\x00\x0f\x00'\x00
            accX_created:: |Q\xdaZ\x00\x00\x00\x00
        profiles:: 
            dialog:: ts|1|init
            dialog:: ts|all|init
            dialog:: tg|11|init
            dialog:: ts|1|conn
            dialog:: ts|all|conn
            dialog:: tg|11|conn

**Comment by bogdan-iancu** [comment]
@nikbyte , all the accX_* variables (expect the ctx one) are identical as value after the restart. Now, when you do those printings (in the initial report), how do you take the values ? for "var(created)" what do you actually print ?

**Comment by nikbyte** [comment]
this way

route {
   do_accounting("evi", "cdr|missed|failed");
}

event_route[E_ACC_CDR] {
   fetch_event_params("created=$var(created);setuptime=$var(setuptime);
   xlog("var(created)=$var(created)\n");
   xlog("var(setuptime)=$var(setuptime)\n");
}

it prints variables after call (which was active when opensips restarted) finished.

**Comment by nikbyte** [comment]
call without restart:
created=1524495201;
call_start_time=1524495202;
duration=30;
ms_duration=30736;
setuptime=1;
method=INVITE;
from_tag=31087SIPpTag001;
to_tag=30347SIPpTag011;
call_id=1-31087@66.198.38.60;
code=200;
reason=OK

call with restart:
created=0;
call_start_time=1524495247;
duration=30;
ms_duration=30904;
setuptime=1524495247;
method=INVITE;
from_tag=31093SIPpTag001;
to_tag=30344SIPpTag012;
call_id=1-31093@66.198.38.60;
code=200;
reason=OK

fields are swapped

**Comment by razvancrainea** [comment]
They are actually not swapped, but created is *always 0*, because it is not properly restored after a restart. And since `setuptime` is computed as `start_time - created`, `setuptime` will always be equal to `start_time`.

I am going to push a fix for this now, thank you for reporting it!

**Comment by nikbyte** [comment]
Thank you! Only one question: why created is not saving?
