### ISSUE TITLE
Wrong CANCEL proccessing with state "Dialog unconfirmed"

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1350]
Hello colleagues! Found some problem in CANCEL processing.
Scheme.

Step 1:
```
                 INV                     INV
(Subscriber A) ---------> opensips(LB) ---------> opensips(TS)
```
Step 2:
```
                                 INV                     INV
(Subscriber B - IP 1.1.1.1 ) <-------- opensips(LB) <--------- opensips(TS)
```
Step 3: Subscriber B bihind IP 1.1.1.1 did not answer on incoming INVITE requset. So, after 8 sec TS generate CANCEL for stop trying sends requests to mute IP and trying another IP of subscriber B:
```
                                                       CANCEL
(Subscriber B - IP 1.1.1.1 ) <-------- opensips(LB) <--------- opensips(TS)
```
Step 4: LB respond to CANCEL request with 200 cancelling:
```
                                                   200 Cancelling
(Subscriber B - IP 1.1.1.1 ) <-------- opensips(LB) --------------> opensips(TS)
```
Problem on opensips-LB. After Step 4 the following may happen:
1) "1 - Dialog unconfirmed (created but no reply received at all)" - In this case, after LB receives CANCEL from TS, it will still send INVITE to B behind IP address 1.1.1.1, which does not respond at all.  Here is wrong behavior, at this time I'm already calling on another IP sub B.
2) "2 - Dialog in early state (created provisional reply received, but no final reply received yet)" + B behind IP address 1.1.1.1 sends only "100 Trying" to incoming INVITE - in this case, after LB receives from TS CANCEL, it will start spamming CANCEL towards subscriber B behind IP address 1.1.1.1 , which did not answer the call.
3) "2 - Dialog in early state (created provisional reply received, but no final reply received yet)" + B behind IP address 1.1.1.1 sends "100 Trying" to incoming INVITE requests and responds to a CANCEL request with "200 cancelling" responses and 487 request terminated. Here is perfect behavior, LB did not generate any requests on mute IP.

If opensips stopped to send retransmits to subscriber B after he received CANCEL, it will be perfect!

If necessary, I can send dumps of problem calls to your personal mail - they clearly show error.
Thanks!

**Comment by bogdan-iancu** [comment]
@kertor , in case (1), if the B side did not reply at all to the INVITE (not even 100Trying), OpenSIPS performs CANCELing as per RFC3261 - keep retransmitting the INVITE without sending actually no CANCEL. The Cancel will be send *ONLY* if B will eventually send back a reply.
