### ISSUE TITLE
Bug related to cross transport routing using double_rr

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#1356]
https://github.com/OpenSIPS/opensips/blob/d9e8bbf26fd47d6cf0282705a3c77341701077a6/modules/rr/loose.c#L770

Consider the code below. nameaddr.uri contains only the uri `sip:192.168.2.1:5060` and does not include the route params. So setting `uri = rt->nameaddr.uri` and then `parse_uri(uri.s, uri.len, &puri)` 
`puri.params` will be empty.

```c
	str uri;
	struct socket_info *si;
	int force_ss = 0;

	hdr = _m->route;
	rt = (rr_t*)hdr->parsed;
	uri = rt->nameaddr.uri;

	if (parse_uri(uri.s, uri.len, &puri) < 0) {
		LM_ERR("failed to parse the first route URI\n");
		return RR_ERROR;
	}
```

So `is_2rr(&puri.params)` on line 770 is always false.

**Comment by ar45** [comment]
Is it because FS sends the header host:port part enclosed in `<>` and the params outside of it.
`Record-Route: <sip:10.0.8.241>;transport=tcp;r2=on;lr;ftag=b6414737.`
vs 
`Record-Route: <sip:10.0.8.241;transport=tcp;r2=on;lr;ftag=b6414737>.`

**Comment by bogdan-iancu** [comment]
@ar45 , the OpenSIPS code is correct - the FS is doing a lousy job in constructing the Route headers. According to RFC, `transport` is a URI param, not a header param, so it must be enclosed all the time (between the `<>`). Also, OpenSIPS adds the `r2` param into RR header as URI parameter, so FS must mirror it back (in Route hdr ) as URI param (that's what the RFC said).
Shortly said, if a param is received enclosed (which means it is a URI param) it MUST be mirror exactly as it is, as URI param. The RFC does not makes mandatory the header parameters.
Let me know if this clarifies you.

**Comment by ar45** [comment]
Thanks.

**Comment by ar45** [comment]
I created a PR for FS https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1523/overview

**Comment by bogdan-iancu** [comment]
yeah, it is not accessible without creating an account :(...anyhow, keep me posted please with the progress.
