### ISSUE TITLE
xmlrpc memory leak

### ISSUE THREAD

**Issue by ydinari** [OpenSIPS/opensips#1359]
Seems like there's a memory leak in either mi_xmlrpc_ng.
OS: Debian GNU/Linux 8 (jessie), Kernel: Linux 3.16.0-5-amd64
Opensips version details:
```
version: opensips 2.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 56c14fd
main.c compiled on  with gcc 4.9.2
```
But I see it on 2.1 as well.
This happens gradually due to a lot of xmlrpc get_statistics() requests. To speed it up I ran the following python script (calls get_statistics() every 100 us):
```
import xmlrpclib
import time

connection = xmlrpclib.ServerProxy("http://127.0.0.1:8080/RPC2")

while True:
    all_stats = connection.get_statistics('all')
    time.sleep(0.0001)
```
Then using top you can see the memory usage of the opensips httpd process increasing in seconds.
This happens in both format versions of mi_xmlrpc_ng module.

**Comment by ydinari** [comment]
Seems like the responsible module is mi_xmlrpc_ng, because when using the mi_json module there'e no leak.

**Comment by bogdan-iancu** [comment]
@ydinari , which mem is leaking according to your tests - the shm? pkg? or system memory ?
