### ISSUE TITLE
exec redis-cli in script

### ISSUE THREAD

**Issue by seanchann** [OpenSIPS/opensips#1361]
hi: 
   I want to call redis-cli to load a lua script by `exec` function. but always failure.
   in console, that work fine.
```
redis-cli -h 127.0.0.1  SCRIPT LOAD "$(cat /usr/local/etc/opensips/redis-check-limit.lua)"  
```

 but in opensips script  it not work,  how to give a `""` in exec . my code like this : 
```
exec("redis-cli -h 127.0.0.1  SCRIPT LOAD "$$(cat /usr/local/etc/opensips/redis-check-limit.lua)"  ",,"$var(redis_eval_out) ",,);
```

**Comment by bogdan-iancu** [comment]
@seanchann , have you escaped the  `" ` inside the first exec() argument ? or use `'` for quoting the exec arguments, to avoid conflicting with the shell

**Comment by seanchann** [comment]
@bogdan-iancu thank you very much  I move this into shell script. it work fine.
