### ISSUE TITLE
mmgeoip - GeoLite City database stopped updating - need compatibility with GeoLite2 City

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1362]
Hello! From message MaxMind website (https://dev.maxmind.com/geoip/legacy/geolite/):
```
Updated versions of the GeoLite Legacy databases are now only available to redistribution license
customers, although anyone can continue to download the March 2018 GeoLite Legacy builds.
Starting January 2, 2019, the last build will be removed from our website. GeoLite Legacy database
users will need to switch to the GeoLite2 or commercial GeoIP databases and update their
integrations by January 2, 2019. 
```

I am use GeoLite City database in production (customers haves greater security), therefore it is very important for me. Will you modify the mmgeoip module for compatibility with GeoLite2 City (https://dev.maxmind.com/geoip/geoip2/geolite2/)? Thanks!

**Comment by razvancrainea** [comment]
If MaxMind will deprecate the old usage, we will definitely update the driver to adapt. I am not sure yet what this presumes, but I will keep an eye to make sure we don't fall behind.

Regards,
Răzvan

**Comment by kertor** [comment]
Thanks, I'll wait.

**Comment by kertor** [comment]
Hello collegues! Any news about this ticket? Thanks!
