### ISSUE TITLE
dns_cache wrong behaviour

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1363]
Hello colleagues! In dns_cache i have found some strange thing. I use DNS fail-over by this scheme:
```
                   DNS
A ----> opensips ------> softsfitch
```

First opensips forming domain name is depend on customer A, second opensips resolving that domain name, third sending request to IP address.
Domain usually have four IP addresses, for example:
```
10.0.0.10
10.0.0.11
10.0.0.12
10.0.0.13
```
These IPs return in mixed order(Round-Robin DNS) in DNS reply, opensips get first IP from list and sends request there. Without enabled module dns_cache requests sends evenly on all IPs.

I enable module in cfg:
```
loadmodule "dns_cache.so"
modparam("dns_cache", "cachedb_url","local://")
modparam("dns_cache", "blacklist_timeout",900)
```
After that, all requests sends to only one IP address. I think opensips cached only one IP of four.
I expect opensips cached all four IP addresses and continue to send requests to all of them, as i said before.
Thanks!

**Comment by bogdan-iancu** [comment]
@kertor , if you do a shell line dig/host on the A record of the softswitch, do you get back a single record/IP ?

**Comment by kertor** [comment]
Output:
```
# dig user-ss5.domain

; <<>> DiG <<>> user-ss5.domain
;user-ss5.domain.	IN	A

;; ANSWER SECTION:
user-ss5.domain	300 IN	A	10.0.0.10
user-ss5.domain.	300 IN	A	10.0.0.11
user-ss5.domain.	300 IN	A	10.0.0.12
user-ss5.domain.	300 IN	A	10.0.0.13
```

**Comment by bogdan-iancu** [comment]
@kertor, I think your whole setup is illogic. If your DNS server returns the set of the 4 IPs in different order (based on the Round Robin policy) - so it returns a dynamic output -, how do you expect to work by introducing caching (which will reuse the latest set of values) ?? IMHO, caching makes no sense if your DNS returns a dynamic output for the same query. The two concepts conflict.

**Comment by bogdan-iancu** [comment]
OpenSIPS is not a DNS server.  IT is just a cacher which keeps repeating *exactly* the same as received first time.
If for the first query, the DNS server replied with A,B,C,D , this will be cached and return without any changes - that's the definition of a cache.
The cache does not implement any logic in re-ordering the records, that's something that only a DNS server can do. So, if you want a dynamic DNS response, do not use cache.
