### ISSUE TITLE
Nathelper doesn't remove AOR record in Mongodb

### ISSUE THREAD

**Issue by gitforxh** [OpenSIPS/opensips#1367]
Running multiple opensips instances as a Federation cluster with version opensips 2.4.0-1. Having following settings:

loadmodule "cachedb_mongodb.so"
loadmodule "usrloc.so"

modparam("usrloc", "cachedb_url", "mongodb://x.x.x.x:27017/opensipsDB.userlocation")
modparam("usrloc", "cluster_mode", "federation-cachedb")
modparam("usrloc", "use_domain", 1)
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "db_url", "mysql://xxxx:xxxx@x.x.x.x/nf_opensips")
modparam("usrloc", "sql_write_mode", "write-through")
modparam("usrloc", "restart_persistency", "load-from-sql")
modparam("usrloc", "skip_replicated_db_ops", 1)
modparam("usrloc", "location_cluster", 50)
...
loadmodule "nathelper.so"
modparam("nathelper", "max_pings_lost", 5)
modparam("nathelper", "remove_on_timeout_bflag", "SIPPING_RTO")
modparam("nathelper", "natping_interval", 30)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "sipping_bflag", "NAT")
modparam("nathelper", "sipping_from", "sip:pinger@x.x.x.x")
...
if (is_method("REGISTER"))
{
...
        setbflag(SIPPING_RTO);
...

Then do the following steps:

1. Register a softphone to an opensips node in the cluster, watch that an AOR record is created both in MySQL and MongoDB.
2. Kill the softphone.
3. The opensips node keeps sending SIP OPTIONS ping request to softphone for 5 times
4. Watch that AOR record in MySQL is deleted, but the record in MongoDB is not.

**Comment by liviuchircu** [comment]
Thank you for the nice bug report, @gitforxh ! Managed to reproduce and I'm currently working on a fix!
