### ISSUE TITLE
clusterer.sip_addr confusion in federation-cachedb mode

### ISSUE THREAD

**Issue by gitforxh** [OpenSIPS/opensips#1369]
Running mulitple opensips 2.4.0-1 instances in federation-cachedb mode. 

According to clusterer document:

`“sip_addr” - is a SIP address for the node with currently no application in replication scenarios; reserved for further development of other modules which might use the clusterer module for communication`

So we left clusterer.sip_addr NULL in the beginning, but only found that it failed to replicate urecord to other nodes in the cluster whenever we register a phone to a node. The error message below are printed in log:

```
May 23 02:21:52 [16403] ERROR:clusterer:str_strcmp: bad parameters
May 23 02:21:52 [16403] ERROR:clusterer:str_strcmp: bad parameters
May 23 02:21:52 [16403] INFO:usrloc:replicate_urecord_insert: All destinations in cluster: 50 are down or probing
May 23 02:21:52 [16403] ERROR:usrloc:replicate_urecord_insert: replicate urecord insert failed
```

The cluster is actully up:

```
[root@d08e47fdc0bb /]# opensipsctl fifo clusterer_list
Cluster:: 50
	Node:: 1002 DB_ID=67 URL=bin:69.168.214.84:5566 Enabled=1 Link_state=Up      Next_hop=1002 Description=opensips-stage_sip.38b465e7-5cb6-11e8-8819-70b3d580000a
	Node:: 1000 DB_ID=63 URL=bin:69.168.214.106:5566 Enabled=1 Link_state=Up      Next_hop=1000 Description=opensips-stage_sip.38b417c5-5cb6-11e8-8819-70b3d580000a
```

Then we tried puting each node's ip address into the clusterer.sip_addr column so the clusterer table is like below:

```
mysql> select id,cluster_id,node_id,url,state,no_ping_retries,priority,sip_addr,flags from clusterer where cluster_id='50';
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
| id | cluster_id | node_id | url                     | state | no_ping_retries | priority | sip_addr       | flags |
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
| 63 |         50 |    1000 | bin:69.168.214.106:5566 |     1 |               3 |       50 | 69.168.214.106 | seed  |
| 65 |         50 |    1001 | bin:69.168.214.122:5566 |     1 |               3 |       50 | 69.168.214.122 | NULL  |
| 67 |         50 |    1002 | bin:69.168.214.84:5566  |     1 |               3 |       50 | 69.168.214.84  | NULL  |
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
3 rows in set (0.16 sec)
```

Then when we register a phone to one of the node, it still failed to replicate with following error msgs:

```
May 23 02:30:46 [16568] INFO:usrloc:replicate_ucontact_insert: All destinations in cluster: 50 are down or probing
May 23 02:30:46 [16568] ERROR:usrloc:replicate_ucontact_insert: replicate ucontact insert failed
```

Then we change all nodes' clusterer.sip_addr to the same like below:

```
mysql> select id,cluster_id,node_id,url,state,no_ping_retries,priority,sip_addr,flags from clusterer where cluster_id='50';
+----+------------+---------+-------------------------+-------+-----------------+----------+-------------------------+-------+
| id | cluster_id | node_id | url                     | state | no_ping_retries | priority | sip_addr                | flags |
+----+------------+---------+-------------------------+-------+-----------------+----------+-------------------------+-------+
| 63 |         50 |    1000 | bin:69.168.214.106:5566 |     1 |               3 |       50 | sip.nf-stg.fonality.com | seed  |
| 65 |         50 |    1001 | bin:69.168.214.122:5566 |     1 |               3 |       50 | sip.nf-stg.fonality.com | NULL  |
| 67 |         50 |    1002 | bin:69.168.214.84:5566  |     1 |               3 |       50 | sip.nf-stg.fonality.com | NULL  |
+----+------------+---------+-------------------------+-------+-----------------+----------+-------------------------+-------+
```

Note that domain name "sip.nf-stg.fonality.com" has 3 A records pointing to the 3 nodes' ip addresses.

Replication is working correctly after this. But new problem is that once a phone is registered, the nathelper doesn't always send ping from the 'home' node that the phone is registered to, but also from other nodes as well. So it seems the cluster doesn't really know which node is the real home node. This is causing the phone's registration loss due to no ping response sent back to other nodes.

Note the home_ip in AOR record of Mongodb is set as the same string as set in sip_addr:

`{ "_id" : "HP-00156502E463-2@sip.nf-stg.fonality.comsip.nf-stg.fonality.com", "home_ip" : "sip.nf-stg.fonality.com", "aor" : "HP-00156502E463-2@sip.nf-stg.fonality.com" }`

So what exactly should we put into the sip_addr column?

**Comment by liviuchircu** [comment]
Thank you for the thorough testing, @gitforxh ! Again, I apologize for the lack of documentation on setting up federated clustering deployments -- updates on this matter will follow asap. Here is the correct way to set it up (you almost did it anyway):

```
mysql> select id,cluster_id,node_id,url,state,no_ping_retries,priority,sip_addr,flags from clusterer where cluster_id='50';
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
| id | cluster_id | node_id | url                     | state | no_ping_retries | priority | sip_addr       | flags |
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
| 63 |         50 |    1000 | bin:69.168.214.106:5566 |     1 |               3 |       50 | 69.168.214.106 | seed  |
| 65 |         50 |    1001 | bin:69.168.214.122:5566 |     1 |               3 |       50 | 69.168.214.122 | seed  |
| 67 |         50 |    1002 | bin:69.168.214.84:5566  |     1 |               3 |       50 | 69.168.214.84  | seed  |
+----+------------+---------+-------------------------+-------+-----------------+----------+----------------+-------+
3 rows in set (0.16 sec)
```

For the `flags` column:
* if you are doing `sync-from-cluster` restart persistency, each individual POP (Point of Presence) MUST have at least one `"seed"` node. If you want HA inside a POP, you can group a POP's nodes via a common `"sip_addr"`, and only specify `"seed"` for one of them, so you can bootstrap the OpenSIPS cluster.
* if you are doing `load-from-sql` restart persistency, `"flags"` are not considered -- you can set them to anything, and the `opensipsctl fifo clusterer_list_cap` should print `Ok` for each node, regardless of when you start or restart it.
