### ISSUE TITLE
Random Selection of gateway for do_routing 

### ISSUE THREAD

**Issue by haeferer** [OpenSIPS/opensips#1375]
Hi, 

This is described as a feature within the documentation (search for "random")

http://www.opensips.org/html/docs/modules/2.3.x/drouting.html

and described in earlier version (< 1.8) as a parameter, 

http://www.opensips.org/html/docs/modules/1.6.x/drouting.html

is this feature  gone or replaced ?

Thx for your great work,

Andreas

**Comment by bogdan-iancu** [comment]
@haeferer , in 2.3 the "random" selection based on weight is enabled via the "W" flag in the 'flags' parameter of do_routing()

**Comment by haeferer** [comment]
(from the docs: )

```
W - Instead of using the destination (from the rule definition) in the given order, sort them based on their weight.
```
so if all weights are the same, it will choose randomly ?

**Comment by bogdan-iancu** [comment]
yes, that's the way the weight-based selection works

**Comment by haeferer** [comment]
Thx a lot 

cu Andreas
