### ISSUE TITLE
OpenSIPS 2.4 presence problems

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#1378]
- OS 2.4 git rev
- same hw with same number of users (about 50) - upgrade from 2.3 to 2.4

I have many problems with db operations relating presence, starting from 2.4 (there was not a single issue like this on 2.3)

CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1062): Duplicate entry 'door-it011.iqtel.rs-dialog-a.1528354568.17750.380.1' for key 'presentity_idx'
CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1062): Duplicate entry 'door-it011.iqtel.rs-dialog-a.1528354568.17741.151.1' for key 'presentity_idx'
CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1213): Deadlock found when trying to get lock; try restarting transaction

I have logs of mysql queries, I can send them if needed.

**Comment by bogdan-iancu** [comment]
@sekil75 , I assume the presence configuration is same (between 2.3 and 2.4) ? Could off ticket send me the logs ?

**Comment by bogdan-iancu** [comment]
@sekil75, any updates here ? Impossible to investigate without further information from your side.

**Comment by harishyadav1465** [comment]
Hi ,
I am also having the same problem.....
I am handling both [ opensips + presence server ] in one cfg file.
I am trying  BLA  setup  with the Opensips 2.4 version...I am thinking that i have some problems with my cfg file....Here is my cfg file attached to it..


####### Global Parameters #########

log_level=3
log_stderror=no
log_facility=LOG_LOCAL0

children=4

/* uncomment the following lines to enable debugging */
#debug_mode=yes

/* uncomment the next line to enable the auto temporary blacklisting of
   not available destinations (default disabled) */
#disable_dns_blacklist=no

/* uncomment the next line to enable IPv6 lookup after IPv4 dns
   lookup failures (default disabled) */
#dns_try_ipv6=yes
/* comment the next line to enable the auto discovery of local aliases
   based on revers DNS on IPs */
auto_aliases=no


listen=udp:192.168.1.68:5050   # CUSTOMIZE ME



####### Modules Section ########


#set module path
mpath="/home/wsadmin/opensips/lib64/opensips/modules/"
loadmodule "db_mysql.so"

loadmodule "textops.so"


#### SIGNALING module
loadmodule "signaling.so"

#### StateLess module
loadmodule "sl.so"

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
/* do not append from tag to the RR (no need for this script) */
modparam("rr", "append_fromtag", 0)

#### MAX ForWarD module
loadmodule "maxfwd.so"

loadmodule "sipmsgops.so"

#### FIFO Management Interface
loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)

#### URI module
loadmodule "uri.so"
modparam("uri", "use_uri_table", 0)

loadmodule "dialog.so"
loadmodule "presence.so"
loadmodule "presence_xml.so"
#loadmodule "presence_dialoginfo.so"
loadmodule "pua.so"
loadmodule "pua_dialoginfo.so"

loadmodule "xcap.so"

#loadmodule "pua_usrloc.so"
loadmodule "pua_bla.so"

# Uncomment this if you want digest authentication
#loadmodule "auth.so"
#loadmodule "auth_db.so"


db_default_url="mysql://wsadmin:worksmart@192.168.1.51/opensips_blablf"

#loadmodule "nathelper.so"
#modparam("nathelper", "natping_interval", 10)
#modparam("nathelper", "ping_nated_only", 1)
#modparam("nathelper", "received_avp", "$avp(received_nh)")
                                                                                                                                                     109,44        24%
#### USeR LOCation module
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "db_mode",   1)
modparam("usrloc", "db_url", "mysql://wsadmin:worksmart@192.168.1.51/opensips_blablf")

#### REGISTRAR module
loadmodule "registrar.so"
modparam("registrar", "tcp_persistent_flag", "TCP_PERSISTENT")
/* uncomment the next line not to allow more than 10 contacts per AOR */
#modparam("registrar", "max_contacts", 10)

#### ACCounting module
loadmodule "acc.so"
/* what special events should be accounted ? */
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
/* by default we do not adjust the direct of the sequential requests.
   if you enable this parameter, be sure the enable "append_fromtag"
   in "rr" module */
modparam("acc", "detect_direction", 0)



# -- dialog params --
modparam("dialog", "db_url","mysql://wsadmin:worksmart@192.168.1.51/opensips_blablf")
modparam("dialog", "db_mode", 1)
modparam("dialog", "dlg_match_mode", 1)

# -- core presence params --
modparam("presence","db_url","mysql://wsadmin:worksmart@192.168.1.51/opensips_blablf")

modparam("presence","server_address","sip:192.168.1.68:5050")
modparam("presence_xml","force_active",1)
###modparam("presence_dialoginfo", "force_single_dialog", 1)

# -- pua and pua_dialoginfo parameters --
modparam("pua","db_url","mysql://wsadmin:worksmart@192.168.1.51/opensips_blablf")
modparam("pua_dialoginfo", "presence_server", "sip:192.168.1.68:5050")
#
#modparam("pua_dialoginfo", "publish_on_trying", 0)
loadmodule "proto_udp.so"

modparam("pua_bla", "server_address", "sip:192.168.1.68:5050")
modparam("pua_bla", "default_domain",  "192.168.1.68")
modparam("pua_bla", "header_name",  "Sender")
modparam("pua_bla", "outbound_proxy",  "sip:192.168.1.68:5050")
modparam("pua_bla", "presence_server",  "sip:192.168.1.68:5050")
modparam("presence", "db_update_period", 1)
modparam("presence", "clean_period", 40)

loadmodule "pua_usrloc.so"

modparam("pua_usrloc", "default_domain", "192.168.1.68:5050")

# -------------------------  request routing logic -------------------

# main routing logic
route{

    # initial sanity checks
    if(!mf_process_maxfwd_header("10")) {
        send_reply("483","Too Many Hops");
        exit;
    }
    if (has_totag()) {
        # sequential requests within a dialog should
        # take the path determined by record-routing
        if (loose_route()) {
            route(relay);
            exit;
        } else {
            if (is_method("SUBSCRIBE") &&  is_myself("$rd")) {
                                                                # in-dialog subscribe requests
                route(handle_presence);
                exit;
            } else if ( is_method("ACK") ) {
                if ( t_check_trans() ) {
                    # non loose-route, but stateful ACK; must be an ACK after 
                    # a 487 or e.g. 404 from upstream server
                    t_relay();
                    exit;
                } else {
                    # ACK without matching transaction ->
                    # ignore and discard
                    exit;
                    }
                }
             else if (is_method("NOTIFY") && $hdr(event)=="dialog;sla" ) {
                         bla_handle_notify();
                         t_reply("200", "OK");
                        exit;
                     }

                send_reply("404","Not here");
            }
        exit;
}
    # CANCEL processing
    if (is_method("CANCEL")) {
        if (t_check_trans())
            t_relay();
        exit;
    }
t_check_trans();

# record routing
    if (!is_method("REGISTER|MESSAGE")){
             record_route();
}
    if (!is_myself("$rd")) {
        # routing to other SIP domains
        route(relay);
    }

#   if (is_method("INVITE") && !($si =="192.168.1.69")) {
    if (is_method("INVITE") && !($si =="192.168.1.69" && $sp=="9090")) {
        create_dialog();

        dialoginfo_set();

        rewritehostport("192.168.1.69:9090");

        route(relay);
        ###do_accounting("log");
        exit;
     }
    # SIP 2 SIP presence traffic
    if (is_method("PUBLISH|SUBSCRIBE")) {
            route(handle_presence);
             exit;
    }
    # handle BLA Notifications
    if (is_method("NOTIFY") && $hdr(event)=="dialog;sla" ) {
        bla_handle_notify();
        t_reply("200", "OK");
    }

    if (is_method("REGISTER")) {
        bla_set_flag();
        if(!save("location")){
                    sl_reply_error();
        }
        exit;
    }
    # native SIP destinations are handled using our USRLOC DB
    if(!lookup("location")) {
        send_reply("404","Not Found");
        exit;
    }
    route(relay);
}
route[relay]{
 if(!t_relay()){
        sl_reply_error();
    }
    exit;
}
route[handle_presence]
{
    if(!t_newtran()){
        sl_reply_error();
        exit;
    }
    if (is_method("PUBLISH")) {
        if($hdr(Sender)!= NULL)
            handle_publish("$hdr(Sender)");
        else
            handle_publish();
    } else

    if (is_method("SUBSCRIBE")) {
        handle_subscribe();
    }
    exit;
}


                                                                                                                                                     340,0-1       Bot
                                                                                                                                                     273,44        89%

**Comment by harishyadav1465** [comment]
hey sekil75 have you found any solutions for this problem

**Comment by sekil75** [comment]
Any update? I would say presence is really broken at this time on 2.4.

**Comment by bogdan-iancu** [comment]
@sekil75 , I pushed a question to you almost 1.5 months ago - if the presence setup is the same for 2.3 and 2.4

**Comment by sekil75** [comment]
Hello, yes you did and I responded on the IRC (but not here, my mistake, I apologize). It is exactly the same setup.

**Comment by bogdan-iancu** [comment]
What kind of events you have there ? presence ? or BLF ?

**Comment by sekil75** [comment]
Both, but mostly BLFs.

**Comment by bogdan-iancu** [comment]
@sekil75, please see the above fix, yet only on devel version - if you could confirm the fix, it will be great, so I can backport it to 2.4 also.
