### ISSUE TITLE
cachedb_mongodb: when user and password is present in the connection string, collection name is not stripped out from the mongodb connection string

### ISSUE THREAD

**Issue by vkuzmenok** [OpenSIPS/opensips#1381]
In cachedb_mongodb_dbase.c, when user and password are present, collection name is not stripped out from id->database and as a result, the final connection string which is passed to mongoc library is not valid.

When user and password are empty, connection string is OK, and it is possible to connect to mongo.

Sample config:
loadmodule "cachedb_mongodb.so" 
modparam("cachedb_mongodb", "compat_mode_3.0", 1) 
loadmodule "db_cachedb.so" 
modparam("cachedb_mongodb|db_cachedb", "cachedb_url", "mongodb:global://myUser:SuperSecret@mongocluster:27017/opensips.col") 
modparam("db_cachedb", "cachedb_url", "mongodb:instance1://myUser:SuperSecret@mongolocal:27017/opensips.col") 

Output from the log:

Jun  8 19:39:02 [30738] DBG:core:parse_cachedb_url: parsing [mongodb:instance1://myUser:SuperSecret@mongolocal:27017/opensips.col] 
Jun  8 19:39:02 [30738] DBG:core:parse_cachedb_url: in host - : 
Jun  8 19:39:02 [30738] DBG:core:cachedb_do_init: opening new connection 
Jun  8 19:39:02 [30738] DBG:cachedb_mongodb:mongo_new_connection: MongoDB conn for [opensips-30738]: mongodb:instance1 myUser:SuperSecret |mongolocal|:27017 
Jun  8 19:39:02 [30738] DBG:cachedb_mongodb:mongo_new_connection: cstr: mongodb://myUser:SuperSecret@mongolocal:27017/opensips.col 
2018/06/08 19:39:02.0865: [30738]:  WARNING:       mongoc: Error parsing URI: 'Invalid database name in URI' 
Jun  8 19:39:02 [30738] ERROR:cachedb_mongodb:mongo_new_connection: failed to connect to Mongo (mongodb://myUser:SuperSecret@mongolocal:27017/opensips.col) 
Jun  8 19:39:02 [30738] ERROR:core:cachedb_do_init: failed to open connection 
Jun  8 19:39:02 [30738] ERROR:db_cachedb:db_cachedb_init: Failed to connect to the cachedb back-end 

I did a simple code change below on my server in the build_mongodb_connect_string function of cachedb_mongodb_dbase.c to fix the issue. Could you fix this in the main repo and backport the fix to 2.3 branch?

        if (id->username && id->password) {
                if (id->flags & CACHEDB_ID_MULTIPLE_HOSTS) {
                        sprintf(ret, "mongodb://%s:%s@%s/%.*s", id->username, id->password,
                                id->host, (int)(p ? p - id->database : strlen(id->database)), id->database);
                } else {
                        sprintf(ret, "mongodb://%s:%s@%s:%d/%.*s", id->username, id->password,
                                id->host, id->port, (int)(p ? p - id->database : strlen(id->database)), id->database);
                }
        } else {
                if (id->flags & CACHEDB_ID_MULTIPLE_HOSTS) {
                        sprintf(ret, "mongodb://%s/%.*s", id->host,
 

Thanks,
Vladimir

**Comment by liviuchircu** [comment]
Fixed in e4f98a6d4c

**Comment by vkuzmenok** [comment]
Is there going to be a patch back to 2.3.x branch?

**Comment by liviuchircu** [comment]
It's already [there](https://github.com/OpenSIPS/opensips/commit/2c4b1583148411c6f69474417566b48be631fa26)!

**Comment by vkuzmenok** [comment]
Thanks!
