### ISSUE TITLE
TLS Error general protection ip

### ISSUE THREAD

**Issue by mehdioui** [OpenSIPS/opensips#1384]
Hello, i deployed an Opensips (2.3.0.1 ) Centos 7 on cloud environment (Openstack ) with 1 Vcpu and 1 Gio RAM,
Opensips has 2 two interfaces (one UDP and one  TLS),
after 3 days of running it crashes with this errors:

aaa/emailAddress=root@somename.somewhere.com, issuer: /CN=*/ST=Toulouse/C=FR/emailAddress=YOUR_EMAIL/O=John
Jun  8 15:13:26 localhost kernel: opensips[5956]: segfault at 0 ip 00000000004cb2e3 sp 00007fff36292430 error 6 in opensips[400000+1b9000]
Jun  8 15:13:26 localhost /sbin/opensips[5956]: INFO:core:probe_max_sock_buff: using snd buffer of 341 kb
Jun  8 15:13:26 localhost /sbin/opensips[5956]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 71
Jun  8 15:13:27 localhost /sbin/opensips[5926]: INFO:core:handle_sigs: child process 5956 exited by a signal 11
Jun  8 15:13:27 localhost /sbin/opensips[5926]: INFO:core:handle_sigs: core was generated
Jun  8 15:13:27 localhost /sbin/opensips[5926]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jun  8 15:13:27 localhost /sbin/opensips[5946]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:27 localhost /sbin/opensips[5945]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5944]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5943]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5942]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5941]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5940]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5939]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5937]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5936]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5935]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5934]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5933]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5932]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5930]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5931]: INFO:core:sig_usr: signal 15 received
Jun  8 15:13:28 localhost /sbin/opensips[5926]: INFO:core:cleanup: cleanup
Jun  8 15:14:27 localhost /sbin/opensips[5926]: CRITICAL:core:sig_alarm_abort: BUG - shutdown timeout triggered, dying...

second crash :
Jun 12 14:26:11 sbc /sbin/opensips[6810]: INFO:proto_tls:tls_dump_cert_info: tls_accept: local TLS server certificate subject: /C=XY/ST=Some State/O=My Large Organization Name/OU=My Subunit of Large Organization/CN=aaaa/emailAddress=root@somename.somewhere.com, issuer: /CN=*/ST=Toulouse/C=FR/emailAddress=YOUR_EMAIL/O=John
Jun 12 14:26:13 sbc kernel: traps: opensips[6820] general protection ip:538c1d sp:7ffe385c2a80 error:0 in opensips[400000+1b9000]
Jun 12 14:26:13 sbc /sbin/opensips[6820]: CRITICAL:core:receive_fd: EOF on 33
Jun 12 14:26:14 sbc /sbin/opensips[6795]: INFO:core:handle_sigs: child process 6808 exited by a signal 11
Jun 12 14:26:14 sbc /sbin/opensips[6795]: INFO:core:handle_sigs: core was generated
Jun 12 14:26:14 sbc /sbin/opensips[6795]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jun 12 14:26:14 sbc /sbin/opensips[6814]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6813]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6811]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6810]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6809]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6807]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6799]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6816]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6815]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6812]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6801]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6805]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6806]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6800]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:14 sbc /sbin/opensips[6802]: INFO:core:sig_usr: signal 15 received
Jun 12 14:26:15 sbc /sbin/opensips[6795]: INFO:core:cleanup: cleanup
Jun 12 14:27:14 sbc /sbin/opensips[6795]: CRITICAL:core:sig_alarm_abort: BUG - shutdown timeout triggered, dying...

**Comment by bogdan-iancu** [comment]
Thanks @mehdioui for the report. Do you still have the corefile for this crash ? do you know how to extract the backtrace from it ?

**Comment by razvancrainea** [comment]
Close for inactivity. Most likely latest TLS changes should have fixed this.
