### ISSUE TITLE
OpenSIPS 2.4 core dump (SIP-I involved )

### ISSUE THREAD

**Issue by rinor** [OpenSIPS/opensips#1390]
Hello,

OpensSIPS:
version: opensips 2.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 5d34c94
main.c compiled on 14:33:32 Jun 12 2018 with gcc 4.9.2

Modules used:
01) "signaling.so"
02) "sl.so"
03) "tm.so"
04) "rr.so"
05) "maxfwd.so"
06) "sipmsgops.so"
07) "textops.so"
08) "uri.so"
09) "db_mysql.so"
10) "event_route.so"
11) "options.so"
12) "sip_i.so"
13) "dialog.so"
14) "load_balancer.so"
15) "mi_fifo.so"
16) "proto_udp.so"

Memory config:
SHM_MEMORY=64 (-m 64)
PKG_MEMORY=32 (-M 32)

===

FUNCTION:
SIP <-> SIP-i signaling.

===

ISSUE:
Program terminated with signal SIGSEGV, Segmentation fault.
Multiple crashes during the day. Volume is low, 10-40 concurrent calls attempts, with 1-3 CPS.

LOG:
Jun 13 14:34:44 SIPi /usr/local/opensips/sbin/opensips[11550]: ERROR:core:qm_malloc: not enough free pkg memory (0 bytes left, need 144), please increase the "-M" command line parameter!
Jun 13 14:34:44 SIPi /usr/local/opensips/sbin/opensips[11550]: ERROR:sip_i:alloc_opt_param: No more pkg mem!
Jun 13 14:34:44 SIPi /usr/local/opensips/sbin/opensips[11550]: ERROR:core:qm_malloc: not enough free pkg memory (0 bytes left, need 48), please increase the "-M" command line parameter!
Jun 13 14:34:44 SIPi /usr/local/opensips/sbin/opensips[11550]: ERROR:core:parse_content_type_hdr: Unable to allocate memory
Jun 13 14:34:44 SIPi /usr/local/opensips/sbin/opensips[11550]: ERROR:core:qm_malloc: not enough free pkg memory (0 bytes left, need 240), please increase the "-M" command line parameter!
....
Complete log with memory dump attached file : [LOG_opensips_core_dump_20180613.log](https://github.com/OpenSIPS/opensips/files/2098241/LOG_opensips_core_dump_20180613.log)

BT FULL:
Program terminated with signal SIGSEGV, Segmentation fault.
Complete output of bt full attached file : [GDB_opensips_core_dump_20180613.log](https://github.com/OpenSIPS/opensips/files/2098244/GDB_opensips_core_dump_20180613.log)

ROUTING CONFIG:
Can share the full config in private if needed.

Suspected SIP -> SIP-i direction:
if (is_method("INVITE")) {
...
	remove_hf("Content-Disposition");
	remove_hf("Allow-Events");
	add_isup_part("IAM");
	$isup_param(Nature of connection indicators | Echo Control Device Indicator) = "included";
	$isup_param(Forward Call Indicators | National/international call indicator) = "international";
	$isup_param(Transmission Medium Requirement) = "speech"; 
}

**Comment by rvlad-patrascu** [comment]
Hi @rinor 
[This](https://github.com/OpenSIPS/opensips/commit/c7e912bee4bfee11faea89cbe1846dd2e1520603) patch should fix the crash but we're probably still facing a memory leak. If you encounter any out of memory errors after applying this fix, please trigger a memory dump for the corresponding processes (with "kill -SIGUSR1 PID").

**Comment by rinor** [comment]
Hi @rvlad-patrascu 
[c7e912b_memory_dump](https://github.com/OpenSIPS/opensips/files/2105473/c7e912b_memory_dump.txt) has the memory dump of one of the processes. It is NOT CRASHING anymore, but still leaking.

total_bytes : num_allocations x [file: func, line]
19622184 : 136265 x [sip_i.c: alloc_opt_param, line 1181]

**Comment by rvlad-patrascu** [comment]
Analyzing the code, it seems that that memory should be freed fine and I've also haven't been able to reproduce the leak. Can you share the full config in private? ( vladp@opensips.org)

**Comment by rinor** [comment]
@rvlad-patrascu Just sent. Thank you

**Comment by rinor** [comment]
@rvlad-patrascu We suspect our issue is related/caused/similar to issue #1348 . We will make a quick test and update

**Comment by rinor** [comment]
Confirmed at least 1 case when PAI present, numeric and length > 15 it start leaking

``
P-Asserted-Identity: "1234567890123456" <sip:+1234567890123456@111.222.33.4:5060>
`` : leaks
``
P-Asserted-Identity: "123456789012345" <sip:+123456789012345@111.222.33.4:5060>
`` : No issue
``
P-Asserted-Identity: "1234567890123456" <sip:+123456789012345@111.222.33.4:5060>
`` : No issue

**Comment by rvlad-patrascu** [comment]
Thanks for catching this, there shouldn't be any more issues but let me know if anything still appears.

**Comment by rinor** [comment]
@rvlad-patrascu Thank you for fixing it.
