### ISSUE TITLE
transformation {uri.domain} not work if the text contains "<" and ">" symbols

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1391]
Hello! After update opensips to 2.3 version (from 2.1) i see that transformation {uri.domain} not work if the text contains "<" and ">" symbols. For example, code:
```
$var(uritest1) = "<sip:12345678912@1.1.1.1:5060>;transport=udp;expires=153";
$var(uritest2) = "sip:12345678912@1.1.1.1:5060;transport=udp;expires=153";
$var(uritest3) = "sip:12345678912@1.1.1.1:5060";
$var(uriresult1) = $(var(uritest1){uri.domain});
$var(uriresult2) = $(var(uritest2){uri.domain});
$var(uriresult3) = $(var(uritest3){uri.domain});
xlog("L_INFO", "[DEBUGURISUPER] var(uritest1)=$var(uritest1) var(uriresult1)=$var(uriresult1) RPLHDR");
xlog("L_INFO", "[DEBUGURISUPER] var(uritest2)=$var(uritest2) var(uriresult2)=$var(uriresult2) RPLHDR");
xlog("L_INFO", "[DEBUGURISUPER] var(uritest3)=$var(uritest3) var(uriresult3)=$var(uriresult3) RPLHDR");
```

Result:
```
[DEBUGURISUPER] var(uritest1)=<sip:12345678912@1.1.1.1:5060>;transport=udp;expires=153 var(uriresult1)=<null>
[DEBUGURISUPER] var(uritest2)=sip:12345678912@1.1.1.1:5060;transport=udp;expires=153 var(uriresult2)=1.1.1.1
[DEBUGURISUPER] var(uritest3)=sip:12345678912@1.1.1.1:5060 var(uriresult3)=1.1.1.1
```
I use {uri.domain} for work with "Contact" headers. In one reply/request may contain a few "Contact" headers.

Opensips version:
```
version: opensips 2.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: a0bed9d
main.c compiled on 20:03:01 May 15 2018 with gcc 4.8.3
```
Can you check and fix it? Thanks!

**Comment by bogdan-iancu** [comment]
@kertor , the `<sip:12345678912@1.1.1.1:5060>;transport=udp;expires=153` is not a valid SIP URI. Actually that is a name-addre format, according to the RFC3261. The headers like To, From, RPID, PAI or Contact do not hold a SIP URI, but a name-addr (again, check the grammar in the RFC3261).
The proper way to pars it will be `$(var(uritest1){nameaddr.uri}{uri.domain})`.

**Comment by kertor** [comment]
Thanks! I thought you might be interested to know about this. In version 2.1 this worked, but on version 2.3 there is no. But many thanks for simple solution.

**Comment by bogdan-iancu** [comment]
@kertor , that means in 2.1 is too loose or broken :), but 2.1 is no longer maintained.
