### ISSUE TITLE
The SIP package is not read by TCP listener

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#1402]
environment : asterisk(TCP register) -> (LAN)opensips-2.3(WAN) -> SIP Provider
[not_read_401.zip](https://github.com/OpenSIPS/opensips/files/2118594/not_read_401.zip)
opensips listen: 
listen=tcp:192.88.99.100:8888 ->  LAN
listen=tcp:10.0.1.166:8888 -> WAN

asterisk send register to opensips-LAN listener
opensips-WAN listener send register to SIP Provider
SIP Provider response 401 

use tcpdump command capture package(not_read_401.zip) , it show 401 packet have arrived device,but opensips didn't receiveed.

use netstat -an | grep 8888
tcp   211366      0 10.0.1.166:60785        201.28.104.28:5060      ESTABLISHED
it show: tcp conn 's Recv-Q is very big.

If need any other log .pls let me know.

**Comment by razvancrainea** [comment]
Most likely OpenSIPS is either stuck, or very busy processing something else.
Can you run `opensipsctl trap` when this happens, so we can see exactly what each TCP worker is doing?

**Comment by xiaoluweiba** [comment]
[trap_log_file.zip](https://github.com/OpenSIPS/opensips/files/2123492/trap_log_file.zip)
thank you for your reply @razvancrainea 
trap_log_file.zip is  opensipsctl trap log file when it happen.

**Comment by razvancrainea** [comment]
It looks like opensips is completely idle, so most likely the messages don't even get to opensips, but they get stuck somewhere at the OS level. Are you using a firewall or something that can block the communication between the two endpoints? Can you try to completely disable the firewall and make another test?

**Comment by xiaoluweiba** [comment]
I disable the firewall ,but the situation still exists.
I will be very grateful if you can test once. not need use asterisk to register , just opensips
trunk info: tcp:registro.phonoway.com.br:5060   username/pwd: 1111/2222 (it's wrong.just for test)

What should I do next ?

**Comment by razvancrainea** [comment]
Hello!

I've tried to connect to your server and it looks like the TCP connection is properly established. However, I indeed don't get any reply, nor 407, nor nothing.
Can you send me the opensips debug logs for connecting and sending the messages?
Also, are you running CentOS? If so, can you make sure it's not a selinux problem?

Best regards,
Răzvan

**Comment by xiaoluweiba** [comment]
[401_log.zip](https://github.com/OpenSIPS/opensips/files/2158705/401_log.zip)
401.pcap:  sip flow
401: opensips log, log_level=4, search "07afce3d-4a89-430f-87b5-ee8cb997dcfe" (callid) can find register log
I test opensips use ubuntu not centos. 

Thank you for your patience to this question.~~

**Comment by razvancrainea** [comment]
Indeed, I don't see any 401 read by opensips. From your initial post, it also looks like the receive queue is piling up, correct?
Can you send me the output of `opensips -V`?

Best regards,
Răzvan

**Comment by xiaoluweiba** [comment]
Hello，
output of opensips -v 
（）Listening on 
             udp: 192.88.99.100 [192.88.99.100]:5060
             udp: 10.0.1.166 [10.0.1.166]:5060
             udp: 192.88.99.100 [192.88.99.100]:5067
             udp: 192.88.99.100 [192.88.99.100]:5077
             udp: 192.88.99.100 [192.88.99.100]:5078
             udp: 192.88.99.100 [192.88.99.100]:5088
             udp: 192.88.99.100 [192.88.99.100]:5099
             udp: 192.88.99.100 [192.88.99.100]:5090
             tcp: 192.88.99.100 [192.88.99.100]:5060
             tcp: 10.0.1.166 [10.0.1.166]:5060
             tls: 192.88.99.100 [192.88.99.100]:5061
             tls: 10.0.1.166 [10.0.1.166]:5061
Aliases: 
From your initial post, it also looks like the receive queue is piling up, correct? -> Yes, the tcp connection 's Rev-Q is very big.

**Comment by razvancrainea** [comment]
are you setting a `poll_method` in your script? If not, can you force in your script `poll_method=epoll_lt`?

**Comment by xiaoluweiba** [comment]
ok, I will try and tell you later.

**Comment by xiaoluweiba** [comment]
Hi, I change poll_method=epoll_lt, but the situation still exist.
opensips -c 
Jul  5 09:30:59 [23077] INFO:core:fix_poll_method: using epoll_lt as the IO watch method (config)

**Comment by xiaoluweiba** [comment]
Hello, Have any try need me to do 0.0?

**Comment by xiaoluweiba** [comment]
What Should do next?@razvancrainea

**Comment by razvancrainea** [comment]
Apologies, I somehow missed this ticket :(. Can you try to update your sources to the latest version and see if this still happens?
If this still happens, can you send me the following info:
1. output of `opensips -V`
2. output of `ss -tpn`
3. output of `opensipsctl fifo get_statistics all:`

Best regards,
Razvan

**Comment by xiaoluweiba** [comment]
Thank you for your reply,It's does't matter now...
I am very interested in b2bua,  It's so amazing,  very little information can be found online. can you give me some detail document about it ?
