### ISSUE TITLE
Clusterer 2.4, usrloc and working_mode_preset=sql-only

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1403]
Hello, since upgrading from 2.2 to 2.4 db_mode=3 stopped working with usrloc, I tried to modify the config to the following.

```modparam("usrloc", "db_url", "http://xyz")
modparam("usrloc", "working_mode_preset", "sql-only")
```

I am using version
```version: opensips 2.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on with gcc 7
```
from deb.opensips.org

But the following error appears and desired behaviour is not achieved.

```Jun 20 13:09:42 li443-44 /usr/sbin/opensips22708: ERROR:usrloc:check_runtime_config: unrecognized preset: sql-only, defaulting to ‘single-instance-no-db’
Jun 20 13:09:42 li443-44 /usr/sbin/opensips22708: INFO:usrloc:ul_init_locks: locks array size 512
```

I can confirm things work as expected with ```single-instance-sql-write-through```

Regards Jonathan

**Comment by digipigeon** [comment]
Additionally setting

```modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "sql_write_mode", "write-through")
```

replicates to other machines in the cluster successfully however it fails to write to the sql database.

settings ```modparam("usrloc", "restart_persistency", "load-from-sql")``` has no effect either.

Regards Jonathan

**Comment by liviuchircu** [comment]
If there are still remaining issues, can you please let me know your exact set of usrloc configuration params? Thanks!

**Comment by digipigeon** [comment]
This has fixed the single server scenario, thank you. However when using the following settings it still ignores the database completely (e.g new registrations don't appear in the customer).

```modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "sql_write_mode", "write-through") # we want/expect the record to appear immediately in the database
modparam("usrloc", "location_cluster", 76) # Clustering seems to work fine, contact appears on all nodes.
modparam("usrloc", "skip_replicated_db_ops", 0) # This does not make any difference (e.g primary or replicas fail to write to db
modparam("usrloc", "restart_persistency", "load-from-sql") # has no effect either.
```
changing the last line to 

```modparam("usrloc", "restart_persistency", "load-from-sql")```

has an immediate positive effect on saving to the database.

Regards Jonathan

**Comment by liviuchircu** [comment]
I am a bit confused:

* If those are the only 4 parameters you set, then there should not be any replication happening at all, as it would be running in a `"none"` clustering mode.  Are you sure `cluster_mode` or `working_mode_preset` were not set when you saw contacts getting replicated?
* what exactly did you do to fix the SQL writes? In your example, the last line is just copy-pasted

Thanks!

**Comment by digipigeon** [comment]
Hi Liviu,

All the replication is working fine, nodes are being loaded from the database, but the following config for the cluster is available

```loadmodule "clusterer.so"
modparam("clusterer", "current_id", 1298)
modparam("clusterer", "db_url", "http://xyz.com:8080/opensips")
```
this is the output
```
opensipsctl fifo clusterer_list
Cluster:: 76
        Node:: 1301 DB_ID=1301 URL=bin:107.170.20.xx:5062 Enabled=1 Link_state=Down    Next_hop=none Description=sip-nyc-2
        Node:: 211 DB_ID=211 URL=bin:176.58.97.xx:5062 Enabled=1 Link_state=Up      Next_hop=211 Description=sip-lon-3
        Node:: 210 DB_ID=210 URL=bin:178.79.159.xx:5062 Enabled=1 Link_state=Down    Next_hop=none Description=sip-lon-4
```

I am sorry, I wrote the wrong line above, , toggling between the following to:
Working (saving to the database)
```modparam("usrloc", "working_mode_preset", "sql-only")```

Working (not saving to the database)
```modparam("usrloc", "working_mode_preset", "full-sharing-cluster")```

Regards Jonathan

**Comment by digipigeon** [comment]
Can we get this issue marked as open again please, I don't want it getting lost :)

Thanks, Regards Jonathan
