### ISSUE TITLE
[Feature] SyncSessions in cgrates module 

### ISSUE THREAD

**Issue by TeoV** [OpenSIPS/opensips#1405]
Hello Everyone,
We have recently implemented in CGRateS which allow us to detect stale sessions.
In order to do this we will be calling an API on OpenSIPS side : 
{"method":"SessionSv1.GetActiveSessionIDs","params":[""],"id":1}
As reply a slice of SessionID which have two parameters OriginHost and OriginID.
{"id":1103043594,"result":[ { "OriginHost":"", "OriginID":"9656cedad668d250831f25eebe2f46ad@0:0:0:0:0:0:0:0"}],"error":null}
It would be great if OpenSIPS could reply with SessionIDs of RPC call.
For any further information don't hesitate to contact me.

Thanks,
TeoV

**Comment by voransoy** [comment]
A fix on this would be perfect since it is a big headache.

**Comment by razvancrainea** [comment]
We are working on this feature, I will update this ticket when it is completed.
