### ISSUE TITLE
Function sipmsg_validate do not validate some wrong symbols

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1408]
Hello! I found error in sipmsg_validate().
When opensips receives INVITE from UAC, sipmsg_validate() check this request. I use this construction:
```
   if (!sipmsg_validate("shmrt", "$var(reason)")) {
        switch($retcode) {
            case -1:
                xlog("L_ERR", "[VALIDATE] No SIP message [$var(reason)], sent [400 - Bad Request] reply LOGHDR");
                break;
            case -2:
....
```
Softhone sends to opensips INVITE with:
```
Request-URI: sip:\362\363\362@softphone.domain.com:5060
To: <sip:\362\363\362@softphone.domain.com:5060>
```
This symbols:
\362\363\362 - In wireshark
��� - in logs opensips

In opensips logs i see this errors:
```
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:db_postgres:db_postgres_submit_query: 0x7fdd11a4b0a0 PQsendQuery Error: ERROR:  invalid byte sequence for encoding "UTF8": 0xf2 0xf3 0xf2 0x27
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:core:db_do_raw_query: error while submitting query
Jun 25 10:17:45 opensips /usr/sbin/opensips[1105]: ERROR:avpops:db_query_avp: raw_query failed: db0() SELECT id1, id2, id3...
```
I think this symbols do not meet the requirements described in RFC. It would be very good, if opensips had detected similarly wrong symbols.

Thanks!

'opensips -V' output:
```
version: opensips 2.3.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: a14fead
main.c compiled on 15:48:26 Jun 19 2018 with gcc 4.8.3
```

**Comment by bogdan-iancu** [comment]
@kertor, could you share the pcap with the INVITE ? I want to see the exact encoding.

**Comment by kertor** [comment]
Hey @bogdan-iancu !
I send you pcap and sipp scenario in private (Slack).

**Comment by bogdan-iancu** [comment]
Hey @kertor , could you please resend it :D

**Comment by bogdan-iancu** [comment]
Nop, let's keep this on, I just need to find the pcap from @kertor

**Comment by bogdan-iancu** [comment]
Nop, let's keep this on, I just need to find the pcap from @ker

**Comment by bogdan-iancu** [comment]
@kertor, I changed this from BUG to FEATURE, as the old code didn't do any kind of checks over the username part of the URI. So, a missing functionality, not a bug.
Also see the  269ad7a commit - please do some heavy testing on it. Now  the username part is checked (as per RFC3261) for allowed chars for the RURI (when checked) , TO and FROM hdrs (when checked)
