### ISSUE TITLE
event_flatstore potential lock

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1409]
Hi team,

investigating code of event_flatstore I found interesting part in rotating():

```
int index = fs->file_index_process;
int rc;

lock_get(global_lock);

if (!fs)
    return;
```

I think it must be

```
if (!fs)
    return;

int index = fs->file_index_process;
int rc;

lock_get(global_lock);
```

to avoid crash with empty pointer and global lock.

**Comment by bogdan-iancu** [comment]
Thank you @nikbyte , good catch !
