### ISSUE TITLE
The phone hears the sound of another call.

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#1420]
Hi, I have encountered a strange phenomenon when I was testing.
one call setup will hears the sound of another call.

environment（ubuntu）：
iphone->opensips_2.3.2+rtpproxy_2.0.0 -> asterisk

1. use sipp to setup calls about 70
2. use iphone1 to call another iphone2 will hear the sound of sipp's call

opensips start with "-m512 -M64" ， listen 10 udp ports, rtpproxy_offer("fieocswr");
rtpproxy start command: rtpproxy -l WANIP LANIP -s udp:localhost 7890 -L 8192 -m 20000 -M 40000 -F -d DBUG LOG_LOCAL0

Can you give me some advices  to solve or find the reason ? 
Looking forward to your reply

**Comment by lmangani** [comment]
Are you using the same ports for both calls by any chance? Sounds like this is potentially the issue. Please capture the two INVITE/200OK generated by SIPP and compare the SDP deails. If this is the case you need to adjust your SIPP scenario or allow it to use random ports or ranges.

**Comment by xiaoluweiba** [comment]
OK,I will try it,thank you
