### ISSUE TITLE
Duplicate Entry Error in BLA

### ISSUE THREAD

**Issue by harishyadav1465** [OpenSIPS/opensips#1422]
opensips version ---- 2.4
System                   ---- Centos 6

Hi,
         I am facing problems when i am  using BLA through OPENSIPS.  The problem is
                   Two users are register for the BLA notifications . Opensips generating publish messages for both the users.I found one record for the each user in the presentity table with event:dialog;sla which is fine.Then one of the users want to update its state Then  I GOT THE BELOW ERROR

Jul 10 16:07:27 Anusha /home/opensips/sbin/opensips[24056]: CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1062): Duplicate entry '1212-192.168.1.68-dialog;sla-a.1531215355.24056.180.1' for key 'presentity_idx'
Jul 10 16:07:27 Anusha /home/opensips/sbin/opensips[24056]: ERROR:core:db_do_update: error while submitting query

This is causing because of Two entries are there in the Presentity table with same values [username,domain,event] 

Thanking you,
HarishKumar

**Comment by bogdan-iancu** [comment]
@harishyadav1465 , could you (privately) share with me a pcap sharing the whole presence traffic that leads to that error ? that will be very very helpful to me. Thanks!

**Comment by harishyadav1465** [comment]
Right now i am not at my Desktop.I will share the pcap when i got there....Before that I will try to explain the things bit more in code level...

Actual Process:

1)After Subscribe from opensips to the Phone...The phone will send the NOTIFY  to the Opensips then the opensips covert this message into PUBLISH and send to the presence.

[In the Presence Module]

2)After receiving the PUBLISH message..The code will check whether it is the initial request or sequential request ...Based on this it will insert or update it in the presentity table.

Problem for BLA:
Assume two phones have the same BLA AOR on their phones.

1)when the two phones send their initial NOTIFY request...two rows stored in the presentity table for single AOR.

2) When a call came for that BLA AOR ...one of them answer the call then that Phone send the NOTIFY to the opensips.....After this opensips want to update it in the Presentity table with this new NOTIFY but it will fail..because in presentity table we have two rows for the single BLA AOR but the update query is on the event ,domain,username but it is same for two rows [unique id error]

**Comment by bogdan-iancu** [comment]
@harishyadav1465 , please see the above fix, yet only on devel version - if you could confirm the fix, it will be great, so I can backport it to 2.4 also.
