### ISSUE TITLE
Presence Problems

### ISSUE THREAD

**Issue by harishyadav1465** [OpenSIPS/opensips#1425]
it  seems  nobody  interested  in my past issue...here i elaborate more.....

I have BLA Setup in opensips. I have two Two polycom ip phones . i have two BLA users one in each phone.
when call come to this BLA  AOR ,it rings at both phones and also show notifications on each other.
That is currently not happening to my setup.

I found the problem which causing this bug.The Problem is when two phones sends the notifications upon subscribe....these Two info stored in the database.when the call state [confirmed , hold]  changes ,it tries to update information in database but having the below error...

Jul 10 16:07:27 Anusha /home/opensips/sbin/opensips[24056]: CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1062): Duplicate entry '1212-192.168.1.68-dialog;sla-a.1531215355.24056.180.1' for key 'presentity_idx'
Jul 10 16:07:27 Anusha /home/opensips/sbin/opensips[24056]: ERROR:core:db_do_update: error while submitting query

it is good if some of the Opensips-developers respond to this bug.Otherwise it will be a great problem in the Presence module which is not great.

Thanking you,
D.HarishKumar

**Comment by bogdan-iancu** [comment]
Hey @harishyadav1465 , my bad for the late reply on this. You say this error is BLA related - can you reproduce this ? there were several similar reports, but I was not able to reproduce it in order to investigate and fix it.
Many thanks,

**Comment by bogdan-iancu** [comment]
let's move discussion on #1422
