### ISSUE TITLE
Feature Request :  Async Support on JsonRPC Module

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1426]
Dear Team,

We are integrating OpenSIPS with a jsonrpc API service and we would like to use asynchronous command just like rest_client does.

thank you in advance

**Comment by vtzan** [comment]
Dear Team,

Also Please add and extra variable to receive full server response even if "error" member object exists in the response.

 It seems there are some server side implementations in GO Language (like CGRates) that are sending this "error:null" json member object always in their responses even if the API Call is correct.

Check here : https://github.com/cgrates/cgrates/issues/1147

thank you in advance

**Comment by razvancrainea** [comment]
Not sure I get the last part: should we return the entire response, like everything that's send back from the server, because you are interested in cases where both error and result is sent? Or shall we just make sure that if `error` is `null`, we return the `result`. Will this work?

**Comment by razvancrainea** [comment]
BTW, if you are interested in interacting with cgrates, why not using the [cgrates](http://www.opensips.org/html/docs/modules/2.4.x/cgrates.html) module directly? It has support for async commands. Are there any other limitations?

**Comment by vtzan** [comment]
I think its more safe to cover cases where both error and result is sent.

**Comment by vtzan** [comment]
I am using for this case jsonrpc/rest_client for CGRATES Users Module (UsersV1.GetUsers method) and come across with this.
