### ISSUE TITLE
Opensips 2.4.1 Xenial apt crash when using siptrace and xlog

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1432]
I am running Opensips 2.4.1-1 from the Xenial apt repo;
```
version: opensips 2.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 5.3.1
```
I have various informational xlogs taking advantage of lots of core variables, and colour codes. Some conflict between these xlogs and the siptrace library is causing Opensips to crash.

Here is an example of the xlog I am using;
`xlog("[$C(px)$(ci{s.width, 36})$C(xx)] [$C(yx)$si:$sp$C(xx)] [$C(cx)WAITING $C(xx)] [$C(gx)$fU|$fd$C(xx)] $C(rx)----$C(xx) [$C(gx)$tU|$td$C(xx)]\n");`

I have a core dump, I cannot share it here due to sensitive content. I can share it privately if required. I will include the first few (redacted) lines of the backtrace in case it is of use.

```
#0  0x00007f329846a793 in is_id_traced (id=id@entry=86, info=info@entry=0x10)
    at siptrace.c:2647
        pos = <optimized out>
        trace_types = <optimized out>
        __FUNCTION__ = "is_id_traced"
#1  0x00007f329846ac1b in sip_context_trace_impl (id=86, from_su=0x0, 
    to_su=0x0, payload=0x0, net_proto=6, correlation_id=0x7f32c268a8e8, 
    mod_p=0x7ffff1f4dfb0) at siptrace.c:2701
        it = <optimized out>
        hash = <optimized out>
        trace_msg = <optimized out>
        __FUNCTION__ = "sip_context_trace_impl"
#2  0x000000000045689e in trace_xlog (len=<optimized out>, 
    buf=0x7f32c24658f8 "<xlogged message here>"..., msg=0x7f32c2699580) at xlog.c:171
        mod_p = {mod_f = 0x455d80 <add_xlog_data>, param = 0x7ffff1f4dfc0}
        xtrace_param = {msg = 0x7f32c2699580, buf = {
            s = 0x7f32c24658f8 "<xlogged message here>"..., len = 232}}
        proto = 6
#3  xl_print_log (msg=0x7f32c2699580, list=<optimized out>, 
    len=<optimized out>) at xlog.c:185
No locals.
#4  0x0000000000456d0f in xlog_1 (msg=msg@entry=0x7f32c2699580, 
    frm=<optimized out>, str2=<optimized out>) at xlog.c:246
        log_len = 232
        ret = <optimized out>
        __FUNCTION__ = "xlog_1"
```

**Comment by bogdan-iancu** [comment]
Hi @hamid-elaosta - is this crash reproducible? Could you privately share the full BT ? Thank you !

**Comment by hamid-elaosta** [comment]
@bogdan-iancu Hi, yes I can reproduce it quite frequently. I just need to get sign-off on sending over the core dump and I'll get it sent over.

**Comment by bogdan-iancu** [comment]
Hi @hamid-elaosta , if this crash is still valid, let me know if there are any chances to get the backtrace.

**Comment by hamid-elaosta** [comment]
Hi @bogdan-iancu I have been testing this again. It seems 2.4.1 still has the crashes, but it hasn't crashed yet with 2.4.4. I will be continuing my testing. If I still haven't reproduced with 2.4.4 I'll let you know so it can be closed.

**Comment by hamid-elaosta** [comment]
@bogdan-iancu I haven't been able to reproduce this issue with 2.4.4. I do have a lot of segfaults/worker threads dying though which appear unrelated.

Would you like to close this one and I'll open a new issue or shall I continue reporting here?

**Comment by bogdan-iancu** [comment]
Hi @hamid-elaosta , if this issue is 'cured ' in 2.4.4, let's close this ticket. Please open new tickets for separate reports.
