### ISSUE TITLE
Running MI commands directly at the script level

### ISSUE THREAD

**Issue by vladpaiu** [OpenSIPS/opensips#1433]
Hello,

Sometimes it is very useful to be able to trigger MI command directly from the script level, and also to be able to fetch & parse the output of the MI command.

Currently, what I'm usually doing is calling either an external script with opensipsctl, or using rest_client to query the same OpenSIPS server via REST, in order to get a JSON that I can easily parse within the script.

It would be nice to get rid of all this unnecessary overhead, and short-circuit the MI command directly to the script level, with the output being a regular JSON so it's easily accessible / parsable.  

Regards,
Vlad

**Comment by bogdan-iancu** [comment]
As an follow up here, let's consider this - https://opensips.org/Development/Design-Opensips-Script-Preprocessing - this is the RFC for re-working the entire MI engine. With the new philosophy, the data exchanged via MI will be json only (JSON-RPC structures), so interacting with the MI interface from the script level will be simpler as the script function may simply return the MI result as $json() object, without going through any other representation (like text).

**Comment by johandeclercqdemocon** [comment]
If you are interested, I am willing to help on this.

**Comment by bogdan-iancu** [comment]
If helping translates into coding this feature, any contribution is more than welcome :)

**Comment by razvancrainea** [comment]
This has been implemented through [mi_script](https://opensips.org/docs/modules/3.2.x/mi_script).
