### ISSUE TITLE
proto_wss:wss_read_req: cannot fix read connection

### ISSUE THREAD

**Issue by ketan-kothari** [OpenSIPS/opensips#1434]
I have upgrade opensips from 2.2 to 2.4.1 and now getting below error while wss connection.

Aug  1 15:10:12 localhost /usr/local/sbin/opensips[21544]: ERROR:proto_wss:wss_read_req: cannot fix read connection
Aug  1 15:10:15 localhost /usr/local/sbin/opensips[21544]: ERROR:proto_wss:tls_accept: New TLS connection from 17.47.91.162:59554 failed to accept
opensips.cfg
listen=wss:domainl:4431
loadmodule "proto_wss.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm", "certificate","/etc/nginx/ssl/wildcard.bundle")
modparam("tls_mgm", "private_key","/etc/nginx/ssl/wildcard.key")

Any suggestion to resolve the issue?

**Comment by kertor** [comment]
Hello! I have this problem too. 

opensips -V
version: opensips 2.3.4 (x86_64/linux)

**Comment by razvancrainea** [comment]
It does not seem to be an issue in opensips, this seems to be a tls handshake problem.
Can you provide all the errors in the log, in the exact order they are triggered?

**Comment by kertor** [comment]
Hello! I see only this messages in logs (log_level=4):
```
Aug 15 20:48:07 test opensips: DBG:core:load_module: loading module /usr/lib64/opensips/modules/proto_wss.so
Aug 15 20:48:07 test opensips: DBG:core:add_module_dependency: adding type 0 dependency proto_wss - (module proto_hep)
Aug 15 20:48:08 test opensips: DBG:core:solve_module_dependencies: solving dependency proto_wss -> module proto_hep
Aug 15 20:48:08 test opensips: DBG:core:solve_module_dependencies: module proto_wss depends on module proto_hep, but it was not loaded!
Aug 15 20:48:08 test opensips: DBG:core:socket2str: <wss:9.9.9.9:7443>
Aug 15 20:48:08 test /usr/sbin/opensips[2171]: INFO:tls_mgm:mod_init: initializing TLS management
Aug 15 20:48:08 test /usr/sbin/opensips[2171]: INFO:tls_mgm:init_tls_dom: Processing TLS domain 'default'
Aug 15 20:48:08 test /usr/sbin/opensips[2171]: INFO:tls_mgm:init_tls_dom: Processing TLS domain 'default'
Aug 15 20:48:26 test /usr/sbin/opensips[2171]: INFO:proto_tls:mod_init: initializing TLS protocol
Aug 15 20:48:26 test /usr/sbin/opensips[2171]: INFO:proto_wss:mod_init: initializing Secure WebSocket protocol
Aug 15 20:48:37 test /usr/sbin/opensips[2337]: ERROR:proto_wss:tls_accept: New TLS connection from 100.1.1.1:33394 failed to accept
Aug 15 20:48:37 test /usr/sbin/opensips[2337]: ERROR:proto_wss:wss_read_req: cannot fix read connection
Aug 15 20:50:20 test /usr/sbin/opensips[2337]: ERROR:proto_wss:tls_accept: New TLS connection from 100.1.1.1:34368 failed to accept
Aug 15 20:50:20 test /usr/sbin/opensips[2337]: ERROR:proto_wss:wss_read_req: cannot fix read connection
```

**Comment by razvancrainea** [comment]
Yup, looks like a similar problem. Is this a controlled environment, where you are sure that the connection should have established? Or is it part of a production environment, where anything can happen :)?

**Comment by kertor** [comment]
This is production environment. Any idea how to debug this problem? In Chrome console i see:
```
 WebSocket opening handshake was canceled
```

**Comment by kertor** [comment]
Hello, I resove this problem. Thanks!

**Comment by razvancrainea** [comment]
Can you detail a bit how you sorted this out? Just to make sure if somebody else hits it, it can have some ideas where to look to. Thanks!

**Comment by kertor** [comment]
I use this settings for enable wss:
```
listen = wss:EXT_IP:7443

########################################################################
loadmodule "proto_wss.so"
########################################################################
modparam("proto_wss", "wss_port", 7443)

########################################################################
loadmodule "tls_mgm.so"
########################################################################
modparam("tls_mgm", "certificate","/etc/opensips/ssl/certificate.pem")
modparam("tls_mgm", "private_key","/etc/opensips/ssl/privitekey.pem")
modparam("tls_mgm", "require_cert", "0")
modparam("tls_mgm", "verify_cert", "0")
```
With settings above i can not see error with TLS connection. wss works correctly, but i have another error with using wss: https://github.com/OpenSIPS/opensips/issues/1454

**Comment by prathibhacdac** [comment]
I am getting the same issue. Can you help me to resolve this?
