### ISSUE TITLE
usrloc: db mode, expiration date still passed as a string

### ISSUE THREAD

**Issue by adrien-martin** [OpenSIPS/opensips#1446]
In Opensips 2.4 (currently testing 2.4.2) usrloc "expires" is now an integer (#1196).

The queries scaning expired registrations each second are still using a string as date.
Both db_mode 3 (deprecated) and cluster_mode sql-only use theses queries.

With queries like :
`select received, contact, socket, cflags, path, contact_id from location where expires > '2018-08-21 10:22:13' and contact_id % 30 = 21`
Postgresql returns an error :
`invalid input syntax for integer: "2018-08-21 10:22:13"`

Don't know if is is related or not, when configured like that and the sql errors happen, after some time a process crash :
`CRITICAL:core:sig_usr: segfault in process pid: 24105, id: 7`
No crash happen when expiration queries are not used in other modes.

**Comment by bogdan-iancu** [comment]
Hi @adrien-martin , thanks for the report. The bogus query is triggered in DB_ONLY mode when using nathelper/nat_traversal for pinging purposes. Working on fix as we speak

**Comment by adrien-martin** [comment]
Hi, thanks for the fix.

Sorry for the late reply, was away, could not test.
