### ISSUE TITLE
Topology hiding without dialog doesn't match RFC 3261

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#1447]
When using topology hiding without dialog module, it encodes all the topology headers in Contact header. It creates header like this for example:
```
Contact: <sip:[0:0:0:0:0:0:0:1]:8061;transport=wss;thinfo="U2h5YhUORg5uUBNZW1dIUAQadlZjRlFWUV0DBHJXRGgWBhZdBwxxSWRaTVBWXxgGcF9pXVNUVg==">
```
https://tools.ietf.org/html/rfc3261#section-25.1
Between LAQUOT and RAQUOT there is addr-spec. And according to RFC it can't contain  quoted-string, or even DQUOTE symbol. And parameter value can't contain EQUAL sign.

**Comment by bogdan-iancu** [comment]
Fixed via #1448
