### ISSUE TITLE
mid_registrar: dangling AoR if downstream registrar does not reply at all

### ISSUE THREAD

**Issue by viperlong** [OpenSIPS/opensips#1449]
in mid-registar module，savc.c file and  overwrite_req_contacts function . the        

          r->no_clear_ref++;

make the aor can't delete from usrloc when  it's unregistered . I think it shoud be：

          if (r->no_clear_ref==0)
                 r->no_clear_ref++;

**Comment by liviuchircu** [comment]
hi, @viperlong - thanks for hinting at that code.  Your report is not an issue per-say, as the REGISTER "expires=0" requests pass through fine without leaving any hanging AoRs.  However, the AoR **will** remain hanging of the downstream registrar fails to respond to the REGISTER -- this is a bug.

**Comment by liviuchircu** [comment]
@viperlong - you should no longer experience any dangling & empty AoRs, regardless of what elements you route out your SIP registrations to.

**Comment by viperlong** [comment]
how about register fail？ for example the downstream registrar  respone to the REGISTER  407/403 ?

**Comment by viperlong** [comment]
how about register fail？ for example the downstream registrar respone to the REGISTER 407/403 ?

**Comment by viperlong** [comment]
@liviuchircu ，thanks to your reply,I'm not very sure about how to fix it.I just found in some situations there has a empty aor。
For example the downstream registrar respone to the REGISTER 407/403 or the aor unregistered In ct throttling modes

**Comment by liviuchircu** [comment]
Indeed, before this patch, authenticated or failed registrations would cause dangling empty AoRs when the UA eventually de-registers.  You should no longer experience this now.
