### ISSUE TITLE
bug db_mysql !!

### ISSUE THREAD

**Issue by devorel** [OpenSIPS/opensips#1450]
https://github.com/OpenSIPS/opensips/blob/2504fbd87a52a404b9c32e7b7f46110e8ef4f825/modules/db_mysql/res.c#L26

root@sd:/usr/local/src/opensips# make include_modules="db_mysql" modules

make[1]: Entering directory '/usr/local/src/opensips/modules/db_mysql'
Compiling row.c
Compiling my_con.c
Compiling val.c
Compiling db_mysql.c
Compiling dbase.c
Compiling res.c
res.c:26:25: fatal error: mysql/mysql.h: No such file or directory
 #include <mysql/mysql.h>
                         ^

**Comment by liviuchircu** [comment]
What OS are you using?  Have you installed `libmysqlclient-dev` or some equivalent package?

**Comment by devorel** [comment]
OS : Debian Linux 9 Stretch

the problem because mariadb

i can't install

apt install default-libmariadbclient-dev

so i installed, for fix it

sudo apt install mariadb-client

sudo apt install libmariadb-dev

sudo apt install libmariadb-dev-compat

sudo apt install libmariadbclient-dev

https://stackoverflow.com/questions/51110986/libmariadbclient-dev-install-error-depends-libmariadbclient18OS

‫בתאריך יום ה׳, 23 באוג׳ 2018 ב-18:16 מאת ‪Liviu Chircu‬‏ <‪
notifications@github.com‬‏>:‬
