### ISSUE TITLE
opensips does not terminate the call if TCP connection is lost

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1454]
Hello everyone! Can you please help me to understand one thing. I have scheme:
```
|-------------------------------------------------------------------------------------------------------------------------------------------------------|
| "User with Google Chrome tab with widget" <---------------------------> (WSS)opensips(UDP) <------------> softswitch.|
|                                                                             SIP in WSS(TCP)                                         SIP(UDP)                  | - TRANSPORT
|__________________________________________________________________________________________|
```
When the user has finished work with widget, he just close browser tab with widget. As a consequence of this, opensips cannot received BYE from widget and dialog continues, although the TCP session is closed.
I want to understand, is there a way to detect closed TCP connections and terminate calls for them automatically?
Or other situation - the user has lost the Internet connection and other.

About use "create_dialog()"
```
Yes, is is possible way, but not preferred, because appears time lag between actual time end of call(user close tab) and time when opensips drop call can be up to 25 seconds (my interval reINVITE pinging).
I mean i use create_dialog() with reINVITE, but the accuracy is less. This has a negative effect on the CDR, i have wrong call duration stat.
I want end call exactly at the same time when TCP connection closed.
```
Thank you!

p.s.
version: opensips 2.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 00:00:26 Aug 15 2018 with gcc 4.8.5

**Comment by bogdan-iancu** [comment]
Hi @kertor , in SIP the is no relation between the transport channels and the SIP dialogs. There is no must to have an a transport channel up when there is no need for SIP signaling. A call may have the INVITE transaction via TCP conn 1 and the BYE transaction via TCP conn 2, with not TCP conn set during the call. Also multiple SIP sessions may share the same transport channel.
