### ISSUE TITLE
[Feature] Dynamic traversal of a json?

### ISSUE THREAD

**Issue by danceinrain** [OpenSIPS/opensips#1458]
I wonder how to traversal a json.
For example:
```json
{ "INVITE-10.10.5.80": 30, "INVITE-10.10.5.39": 30 }
```
I want to get the first key "INVITE-10.10.5.80" and get its value,and then get the second key and get its value and go on if there is more objects.
I know that a json array can be traversed.I wonder if there is a method to traversal a json like above

**Comment by liviuchircu** [comment]
AFAIK, this is currently not possible -- turning this thread into a feature request.  Below are two possible implementations:

### Ideal but challenging to implement

```
# only works on objects
for ($var(k), $var(v) in $json(obj_only)) {
    ...
}

# for arrays or objects: iterates over values
for ($var(v) in $json(obj_or_arr)) {
    ...
}
```

### Not ideal but straightforward to implement

This is similar to the [statistics iterators](https://opensips.org/html/docs/modules/3.0.x/statistics.html#func_stat_iter_next)

```
json_iter_init("$json(obj_only)", "iter");
while (json_iter_next("$var(k)", "$var(v)", "iter")) {
    ...
}

json_iter_init("$json(obj_or_arr)", "iter");
while (json_iter_next("$var(v)", "iter")) {
    ...
}
```

**Comment by danceinrain** [comment]
Thanks you very much

**Comment by bogdan-iancu** [comment]
Another approach to this limitation is to extend the $json variable to be able to return the keys or the values from a certain json node (similar to the `$xml` where beside returning the xml subtree, you can get the attributes or the value like `$xml(/path/to/node.attr/name)` ).
Maybe something like `$json(path/to/node.keys)` to return an array with all the keys under a given node or `$json(path/to/node.values)` to return an array with all the values under that node.

Once you know the keys beneath the node, you can dynamically build the json path to go deeper into the object.

**Comment by bogdan-iancu** [comment]
@liviuchircu , I see items 1 and 2 as something that can be done relatively fast, as a first stage - they require changing only the `$json` variable. The items 3 and 4 are maybe a second step as they impact also how the looping works in the script (the implementation of the `for` statement).

**Comment by liviuchircu** [comment]
Very true for **3)** -- it is a bit of a syntactic quirk and we can leave it last.  On the other hand, **4)** is almost synonymous to **2)**, since we already have `$json` iterators.

**Comment by bogdan-iancu** [comment]
:+1: true if we look only to the top `for`
