### ISSUE TITLE
ERROR:dispatcher:ds_is_in_list: IP val is not IP <2606:6000:50D9:.....>

### ISSUE THREAD

**Issue by palmtown** [OpenSIPS/opensips#1459]
Hello,

ds_is_in_list is generating an error when it is IPv6.  Please resolve:

ERROR:dispatcher:ds_is_in_list: IP val is not IP <2606:6000:50D9:.....>

**Comment by palmtown** [comment]
Thanks Bogdan!

**Comment by bogdan-iancu** [comment]
Backport also done to 2.4, 2.3 and 2.2 versions - thanks @palmtown
