### ISSUE TITLE
glags in 2.4 doesn't work

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1460]
Hello team,

gflags module in 2.4

```
# opensipsctl fifo is_gflag 1
FALSE
# opensipsctl fifo is_gflag 2
FALSE
# opensipsctl fifo set_gflag 1
# opensipsctl fifo is_gflag 1
TRUE
# opensipsctl fifo is_gflag 2
FALSE
```
however in script:
```
$var(z1) = is_gflag("1");
$var(z2) = is_gflag("2");
xlog("$var(z1) $var(z2)");
```
returns "-1 -1".

gflags are not available from the script.

**Comment by bogdan-iancu** [comment]
@nikbyte , please note that the is_gflag() takes as input the index of the flag to test, while the MI function take as parameter a bitmask for the flags to operate with.

**Comment by nikbyte** [comment]
Ok, thanks for comment. But anyway 1 is index and bitmask too (the same for 1st flag), yes?

**Comment by nikbyte** [comment]
Not obvious, maybe it's good reason to attend this in doc?
Thank you for you comments.
