### ISSUE TITLE
mysql dialog.caller_contact & dialog.callee_contact not enough chars to support IPv6

### ISSUE THREAD

**Issue by palmtown** [OpenSIPS/opensips#1462]
OpenSIPs generates an error when dialog.caller_contact or dialog.callee_contact contains an IPv6 address and fails to insert the mysql table record which causes issues with the call.  I manually increased it to 255 which works.

**Comment by palmtown** [comment]
Hello,

I checked the fix you implemented and I think the value should be 255 and not 256.  Reason being is max length for CHAR in MySQL is 255, if you enter 256, it will generate an error.

**Comment by bogdan-iancu** [comment]
Hi @palmtown, thanks for spotting the typo, I fixed it.
