### ISSUE TITLE
Call center module configuration

### ISSUE THREAD

**Issue by cleberb** [OpenSIPS/opensips#1464]
Is there a clear and objective how to configure the call center module? If yes, can they indicate? I can not find the scenario_callcenter.xml file mentioned on the module's documentation page.

**Comment by bogdan-iancu** [comment]
@cleberb how do you have your OpenSIPS installed ? The XML is available here https://github.com/OpenSIPS/opensips/blob/master/modules/call_center/scenario_callcenter.xml .

In terms of usage, have you went through the README file ?

**Comment by cleberb** [comment]
Thank you! installed via apt-get. With the packages installed, I can not find the file.

<pre>
# dpkg -l | grep opensips
ii  opensips                          2.4.2-1                        amd64        very fast and configurable SIP server
ii  opensips-b2bua-module:amd64       2.4.2-1                        amd64        B2B User Agent modules for OpenSIPS
ii  opensips-console                  2.4.2-1                        amd64        Generic tool for OpenSIPS provisioning
ii  opensips-dialplan-module:amd64    2.4.2-1                        amd64        Generic string translation module for OpenSIPS
ii  opensips-http-modules:amd64       2.4.2-1                        amd64        HTTP transport layer and Management Interface for OpenSIPS
ii  opensips-json-module:amd64        2.4.2-1                        amd64        Support for JSON handling in OpenSIPS script
ii  opensips-lua-module:amd64         2.4.2-1                        amd64        Lua extensions for OpenSIPS
ii  opensips-memcached-module:amd64   2.4.2-1                        amd64        Interface module to interact with a memcached server
ii  opensips-perl-modules:amd64       2.4.2-1                        amd64        Perl extensions and database driver for OpenSIPS
ii  opensips-postgres-module:amd64    2.4.2-1                        amd64        PostgreSQL database connectivity module for OpenSIPS
ii  opensips-redis-module:amd64       2.4.2-1                        amd64        Interface module to interact with a Redis server
ii  opensips-regex-module:amd64       2.4.2-1                        amd64        PCRE regexp modules for OpenSIPS
ii  opensips-restclient-module:amd64  2.4.2-1                        amd64        REST client module for OpenSIPS
ii  opensips-xml-module:amd64         2.4.2-1                        amd64        Support for XML documents handling in OpenSIPS script
</pre>

**Comment by bogdan-iancu** [comment]
Right, we are looking into the `install` and `packaging` procedures to be sure that the xml file is also deployed
