### ISSUE TITLE
proto_hep module close connection

### ISSUE THREAD

**Issue by danceinrain** [OpenSIPS/opensips#1476]
When I watch the log,I found some lines like below:
Sep 25 02:21:21 [30] ERROR:proto_hep:hep_handle_req: Made 64 read attempts but message is not complete yet - closing connection

But I don't know what it means.Does it mean that the message is too long?
Thanks in advance!

**Comment by bogdan-iancu** [comment]
@danceinrain , is your OpenSIPS server reading any hep traffic ? like using it for hep proxy or with sipcapture module ?

**Comment by danceinrain** [comment]
@bogdan-iancu Yes,I use both prot_hep and sipcapture modules.I use opensips as a hep server to receive HEPv3 messages.

**Comment by bogdan-iancu** [comment]
The error you get translates into : OpenSIPS did 64 I/O read operations on the TCP connection without reading enough data to complete the HEP packet.

What kind of HEP data are you receiving and who's generating it ?

**Comment by danceinrain** [comment]
Opensips server gets a huge amount of HEP data,and some HEP data will cause the phenomenon.I don't get the HEP data that cause the error,because too much HEP data was received.

Asterisk generate HEP data and sent it to Opensips server.

**Comment by bogdan-iancu** [comment]
I see. Do you think it will help you if I prepare a patch to also log the already read buffer and its size ? maybe it will give you hint.

**Comment by danceinrain** [comment]
@bogdan-iancu Thanks.I think it will help a lot.

**Comment by bogdan-iancu** [comment]
@danceinrain , please apply this small path and let's see:

```
diff --git a/modules/proto_hep/proto_hep.c b/modules/proto_hep/proto_hep.c
index f8afebf..9974f7e 100644
--- a/modules/proto_hep/proto_hep.c
+++ b/modules/proto_hep/proto_hep.c
@@ -1013,6 +1013,9 @@ static inline int hep_handle_req(struct tcp_req *req,
                if (con->msg_attempts == _max_msg_chunks) {
                        LM_ERR("Made %u read attempts but message is not complete yet - "
                                   "closing connection \n",con->msg_attempts);
+                       LM_ERR("Expected len was %d, read %ld, buf is [%.*s]\n",
+                               req->content_len, req->pos-req->buf,
+                               (int)(req->pos-req->buf), req->buf);
                        goto error;
                }
```

**Comment by danceinrain** [comment]
@bogdan-iancu Thanks,I will recomplie opensips and see what will happen.

**Comment by bogdan-iancu** [comment]
@danceinrain , any follow up here? (otherwise I will close it)
