### ISSUE TITLE
Cannot rename dr_group table in drouting

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1479]
Hello team,

2.4 has bug with length of dr_group table (I think with another tables too).

dr_group is 8 characters.

modparam("drouting", "drg_table", "abcde_group")

Sep 30 21:53:05 [71842] ERROR:drouting:dr_init: error during table version check<dr_groups table 'abcde_gro', for partition 'test'>

It looks like we have this situation because of pre-initialised variables in module:
> str drg_table = str_init("dr_groups");
and when opensips applies new name, it doesn't reallocate memory.

**Comment by bogdan-iancu** [comment]
Hi @nikbyte - are you using partitions with DR ? Also, what is the exact revision you have?

**Comment by nikbyte** [comment]
I tried on 2.4 revision 4290b2334. Latest for few days ago.
I use partitions but tried to change dr_groups name with module parameter.
I tried to change this with module parameter because I couldn't change it with dr_partitions table too.

**Comment by bogdan-iancu** [comment]
@nikbyte , could you (off ticket) send me the DB dump with all the DR related tables + the module configuration ? This will speed up things

**Comment by kertor** [comment]
Hello Bogdan! I have the same situation. opensips version:
```
[root@localhost opensips]# opensips -V
version: opensips 2.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4290b23
main.c compiled on 18:30:40 Oct  2 2018 with gcc 4.8.5

#### DROUTING module
loadmodule "drouting.so"
modparam("drouting", "db_url", "postgres://opensips:pass@localhost/opensips")
modparam("drouting", "drd_table", "dr_gateways")
modparam("drouting", "drr_table", "dr_rules")
modparam("drouting", "drg_table", "dr_groupabcdefg")
modparam("drouting", "drc_table", "dr_carriers")
modparam("drouting", "db_partitions_url", "postgres://opensips:pass@localhost/opensips")
modparam("drouting", "db_partitions_table", "dr_partitions")
modparam("drouting", "use_domain", 1)
modparam("drouting", "use_partitions", 1)
modparam("drouting", "drg_user_col", "username")
modparam("drouting", "drg_domain_col", "domain")
modparam("drouting", "drg_grpid_col", "groupid")
modparam("drouting", "force_dns", 1)
modparam("drouting", "probing_interval", 15)
modparam("drouting", "probing_method", "OPTIONS")
modparam("drouting", "probing_from", "sip:dr_pinger@1.1.1.1)")
modparam("drouting", "gw_id_avp", "$avp(gw_id)")
```

I have two partitions, "temp" and "test".
I have diffrent setups:
1) "drg_table" define in configuration:
```
modparam("drouting", "drg_table", "dr_groupabcdefg")
```
1.1) "drg_table" defines in both partitions:
```
opensips=# select drg_table from dr_partitions;
    drg_table    
-----------------
 dr_groupabcdefg
 dr_group1234
(2 rows)
```
All starting ok!
1.2) "drg_table" defines in first partition:
```
opensips=# select drg_table from dr_partitions;
    drg_table    
-----------------
 dr_groupabcdefg
 
(2 rows)
```
I have error:
```
Oct  3 02:16:55 [80106] ERROR:core:db_check_table_version: invalid version 0 for table dr_groupa found, expected 2
Oct  3 02:16:55 [80106] ERROR:drouting:dr_init: error during table version check<dr_groups table 'dr_groupa', for partition 'temp'>
```
1.3) "drg_table" do not defines in partitions
```
opensips=# select drg_table from dr_partitions;
 drg_table 
-----------
 
 
(2 rows)
```
I have error:
```
Oct  3 02:22:57 [80133] ERROR:core:db_check_table_version: invalid version 0 for table dr_groupa found, expected 2
Oct  3 02:22:57 [80133] ERROR:drouting:dr_init: error during table version check<dr_groups table 'dr_groupa', for partition 'temp'>

```
2) "drg_table" not define in configuration:
```
#modparam("drouting", "drg_table", "dr_groupabcdefg")
```
2.1) "drg_table" defines in both partitions:
```
opensips=# select drg_table from dr_partitions;
    drg_table    
-----------------
 dr_groupabcdefg
 dr_group1234
(2 rows)
```
All starting ok!
2.2) "drg_table" defines in first partition:
```
opensips=# select drg_table from dr_partitions;
    drg_table    
-----------------
 
 dr_groupabcdefg
(2 rows)
```
All starting ok!
2.3) "drg_table" do not defines in partitions
```
opensips=# select drg_table from dr_partitions;
 drg_table 
-----------
 
 
(2 rows)
```
All starting ok!

I attached sql dump and opensips.cfg file. Thanks!
[dumpall.txt](https://github.com/OpenSIPS/opensips/files/2440094/dumpall.txt)
[opensips.txt](https://github.com/OpenSIPS/opensips/files/2440095/opensips.txt)

**Comment by bogdan-iancu** [comment]
Missing accomplished :)

**Comment by nikbyte** [comment]
Thank you!
