### ISSUE TITLE
Problem with DisconnectCause in CGRates module.

### ISSUE THREAD

**Issue by DigiDaz** [OpenSIPS/opensips#1481]
I am using the CGRates module and the DisconnectCause only seems to be getting populated for billable calls, it seems that if BUSY or CANCEL etc, then {"DisconnectCause":""} seems to be sent to cgrates.

Also things like DestinationID etc only get sent on billable calls. Though this is far less important it would make for a much more complete CDR if it was available somewhere. This info is definitely around as it would have been used to check before the call procceded.

**Comment by vtzan** [comment]
+1 for this. Thx
