### ISSUE TITLE
OpenSIPS shm pointer crash (segfault)

### ISSUE THREAD

**Issue by mmenzo** [OpenSIPS/opensips#1483]
Yesterday the OpenSIPS process on our production server suddenly crashed after running stable for a few months. Today it crashed again, with similar log messages. We're not really sure about the cause of the crashes, except that it seems to be related to freeing memory pointers.

The symptoms for both crashes seem to be similar. Just before the process crashes the following log messages appear:
```
...
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: INFO:acc:acc_dlg_callback: CDR callback already registered [0x7f0dabfd5478|2] - do not run it again!
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0dabfd5598) - skipping!
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0dabfd55c0) - skipping!
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0dabfd55e8) - skipping!
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0dabfd5608) - skipping!
Oct  2 14:58:41 sip3-prod-back1 opensips[11466]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0dabfd5628) - skipping!
...
```

A few seconds later, the process crashes with the following log message:

```
...
Oct  2 14:58:43 sip3-prod-back1 opensips[11471]: CRITICAL:acc:shm_free: #012>>> shm_free() on non-shm ptr 0x32312e35362e3435 - aborting!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Oct  2 14:58:43 sip3-prod-back1 opensips[11478]: CRITICAL:core:receive_fd: EOF on 68
Oct  2 14:58:43 sip3-prod-back1 opensips[11457]: INFO:core:handle_sigs: child process 11471 exited by a signal 6
Oct  2 14:58:43 sip3-prod-back1 opensips[11457]: INFO:core:handle_sigs: core was not generated
Oct  2 14:58:43 sip3-prod-back1 opensips[11457]: INFO:core:handle_sigs: terminating due to SIGCHLD
...
```

I have attached the log files for yesterday's crash and today's crash to this ticket. I also must point out that we're not running the latest version of OpenSIPS, we are currently using OpenSIPS 2.3.4. Is the cause of this crash resolved by some of the changes in OpenSIPS 2.3.5 or OpenSIPS 2.4.x, or is the crash caused by a different problem?

[opensips-log-2018-10-02.txt](https://github.com/OpenSIPS/opensips/files/2441997/opensips-log-2018-10-02.txt)
[opensips-log-2018-10-03.txt](https://github.com/OpenSIPS/opensips/files/2441998/opensips-log-2018-10-03.txt)

**Comment by razvancrainea** [comment]
Yes, there were some major fixes in the acc module between 2.3.4 and 2.3.5, and in the latest 2.4, therefore I strongly suggest you to use one of these newer versions. Closing the ticket for now.
