### ISSUE TITLE
Drouting module socket parameter for probing gateways

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#1484]
When OpenSIPS has serveral listening sockets, it is impossible to specify which one must be used to probe status of gateways. It will use the first one from configuration file.
But for example, in cluster configuration with Virtual IP moving between servers this causes a lot of errors in logs.

**Comment by bogdan-iancu** [comment]
@vasilevalex , in the definition of the DR gateways, you can optionally set a specific socket/listener to be used in relation to that GW (for sending traffic and for probing also) - see the "socket" field in this table - http://www.opensips.org/Documentation/Install-DBSchema-2-4#GEN-DB-DR-GATEWAYS .
Have you tried this ?

**Comment by vasilevalex** [comment]
Yes, I know about this field. But when we have OpenSIPS cluster with shared DB, we need to use different sockets for different servers.

**Comment by vasilevalex** [comment]
I also added MI command to drouting module to enable/disable gateways probing, like in nathelper module to enable/disable ping. I'll put it on github next week for your review. May be MI command is more elegant solution for this task.
