### ISSUE TITLE
400 error while using mi command "profile_end_dlgs" with mi_json

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1486]
Hello guys! On version 2.4 found problem with usage "profile_end_dlgs" over mi_json.
Case of usage:
```
user@dev:~# killall -9 opensips
user@dev:~# curl --connect-timeout 3 --max-time 3 "http://127.0.0.1:8000/mi_json/profile_end_dlgs?params=dialog/b"
```
Error and logs of error:
```
user@dev:/etc/peeredge/sbin# /etc/peeredge/sbin/kill_all_dialogs.sh i_know_what_i_am_doing
{"error": {"code": 400, "message": "Dialog internal error"}}

Oct  5 15:55:00 localhost opensips[18575]: Oct  5 15:55:00 [18593] ERROR:dialog:dlg_end_dlg: Initial transaction does not exist any more
Oct  5 15:55:00 localhost opensips[18575]: Oct  5 15:55:00 [18593] ERROR:dialog:mi_profile_terminate: error while terminating dlg
Oct  5 15:55:00 localhost opensips[18575]: Oct  5 15:55:00 [18597] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled for 990 ms (now 1990 ms), it may overlap.
```

I never seen this error with this case of usage on opensips version 2.3.
But on version 2.4 this error does not disappear after a somo time.
opensips -V:
```
version: opensips 2.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e7003df
main.c compiled on  with gcc 5.4.0
```
Can you please help me to understand meaning of problem and fix it? Thanks!

**Comment by bogdan-iancu** [comment]
The error you get translates into: you do `dlg_end_dlg` on a call which is not yet established (no final reply yet, the call being in early state probably) according to the internal dialog state. So the call cannot be BYE, but a CANCEL must be sent, so OpenSIPS is looking for the INVITE transaction. But this INVITE lookup fails, so here you get the error.
That is a bit strange, indeed. Could you try to see if you can reproduce the scenario ?

**Comment by nikbyte** [comment]
It's hard to reproduce. Usually after restart of hard loaded server. I think it's dialog which was loaded from table, but hung.

**Comment by bogdan-iancu** [comment]
Beside the error, are there any sides effects? Due a hard restart you may end up in one of this weird situation with the early dialogs and no transactions in memory.

**Comment by nikbyte** [comment]
If this ends all "normal" dialogs, it's not issue and could be closed. Maybe add some note into doc?
