### ISSUE TITLE
Shared memory leak with MI interface

### ISSUE THREAD

**Issue by artkos** [OpenSIPS/opensips#1489]
I have four opensips server and one of the server have 
also opensips control panel. I have noticed that there is 
shared memory leak somewhere and I think I have pinpointed where it happens.

So I use Opensips control panel Static Monitor to graph:
Module: dialog - active_dialogs
Module: hsmem - real_used_size

If you look attached picture:
![chart](https://user-images.githubusercontent.com/38854857/46603506-ee650500-cafb-11e8-9121-6d2f80a154de.png)
you can see that shared memory useage is increasing when active dialog count 
increases (drop is when opensips service were restarted).

Shared memory useage were increasing on all servers, but one: server with
opensips control panel. So it seems that if you use opensips-cp to graph 
stats from other than local computer memory leak will occur.

So every server has in the config:
```

loadmodule "httpd.so"
modparam("httpd", "port", 8888)
modparam("httpd", "ip", "10.0.0.x")

loadmodule "json.so"
loadmodule "mi_http.so"
loadmodule "mi_json.so"

```
In Opensips control panel boxes.global.inc.php's I have:

```
//  MI connector (via JSON backend):   json:host:port/json
$boxes[$box_id]['mi']['conn']="json:10.0.0.x:8888/json";
```

Server with Opensips-CP is also configure with 10.0.0.x ip (not 127.0.0.1).

-I disabled stats quering from one of the servers, memory leak stopped (or at least were signifcantly lower).

version: opensips 2.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cf88b4b
main.c compiled on 15:25:51 Oct  2 2018 with gcc 5.4.0

See also attached memory stats log from one of the servers:
[opensip-mem-oct8.txt](https://github.com/OpenSIPS/opensips/files/2455597/opensip-mem-oct8.txt)

**Comment by razvancrainea** [comment]
Please send us all the `do_routing()` calls, with their parameters and the routes they are called from. Thanks!

**Comment by artkos** [comment]
Sent opensips.cfg trough email to you.
