### ISSUE TITLE
use opensips as SIP PROXY,  have some problems when register

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#1491]
phone ------>  opensips -----------> asterisk (10.0.0.2)
            WAN(1.2.3.4)     LAN(10.0.0.1)

1.  phone send register(expires=90)  packet to 1.2.3.4:5060
2.  change contact uri host = 10.0.0.1 and fs = 10.0.0.1:5060  
3.  repost register packet to 10.0.0.2:5060(register expire range is 360-1800), it will response 200OK with expires=360 to 10.0.0.1:5060 
4.  **call **### save()** to   save register ; it will use expires=90 to save（because compare_uris failed, so use request expires but not response）**
5.  repost 200 OK to phone with（expires=360）

If I have any unclear expression, please tell me，By the way, It's strange scenarios like this？
 looking forward to waiting for the reply ~~

**Comment by bogdan-iancu** [comment]
For such questions, please use [opensips user's mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)
