### ISSUE TITLE
nathelper can't delete dead contacts replicated over bin proto

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#1492]
I have 2 running OpenSIPS servers. One has VirtualIP and serves clients. Another one is just hot spare. They use clusterer module, mid_registar and nathelper. So usrloc data replicated on both servers. usrloc without any database, everything is in memory.
Let's restart Active server (after restart it is still Active. VIP on it), this breaks all tcp/tls connections, so phones re-register. Mid_registar is in AOR-throttling mode, so there are immediately two contacts for each AOR.
So before (with one server and DB) nathelper just pinged all contacts, detected dead and deleted them.
But now after restart Active server gets usrloc data not from DB, but from cluster. Nathelper starts the same process of detecting dead contacts:
```
Oct  9 10:10:07 test82 /usr/sbin/opensips[18026]: DBG:nathelper:ping_checker_timer: ping expiring ping cell 3848466619076554985 state=1
Oct  9 10:10:07 test82 /usr/sbin/opensips[18026]: DBG:nathelper:ping_checker_timer: cell with ucoords 3848466619076554985 has 3 unresponded pings
Oct  9 10:10:07 test82 /usr/sbin/opensips[18026]: DBG:nathelper:ping_checker_timer: cell with ucoords 3848466619076554985 exceeded max failed pings! removing...
Oct  9 10:10:07 test82 /usr/sbin/opensips[18026]: DBG:usrloc:delete_ucontact_from_coords: deleting ucoords 3848466619076554985
Oct  9 10:10:07 test82 /usr/sbin/opensips[18026]: DBG:usrloc:delete_ucontact_from_coords: contact with contact id [3848466619076554985] not found
```
In nathelper.c this code is executed:
```
if (cell->not_responded >= max_pings_lost) {
	LM_DBG("cell with ucoords %llu exceeded max failed pings! "
		"removing...\n", (unsigned long long)cell->ct_coords);
	ct_coords = cell->ct_coords;
	_d = cell->d;

	remove_from_hash(cell);

	unlock_hash(cell->hash_id);

	ul.free_ucontact_coords(cell->ct_coords);
	shm_free(cell);

	if (ul.delete_ucontact_from_coords(_d, ct_coords, 0) < 0) {
		/* we keep going since it might work for other contacts */
		LM_ERR("failed to remove ucontact from db\n");
	}
}
```
So the contact is deleted from nathelper's hash table, but usrloc API function "delete_ucontact_from_coords" didn't delet it (but it returns 0 - this is also error)
In usrloc module function delete_ucontact_from_coords for some reason can't find contact with this code:
```
c = get_ucontact_from_id(d, contact_id, &r);
if (!c) {
	LM_DBG("contact with contact id [%"PRIu64"] not found\n", contact_id);
	return 0;
}
```
But contact is still in usrloc data (first one):
```
opensipsctl ul show

 AOR:: 200
                Contact:: sip:200@172.16.1.225:2184;transport=tls Q=1
                        ContactID:: 3848466619076554985
                        Expires:: 2774
                        Callid:: 5BBAD7A8463DDF44-zzt403mfjy8h
                        Cseq:: 118
                        User-agent:: snom360/8.7.4.8.6
                        Received:: sip:10.10.10.138:2184;transport=tls
                        State:: CS_NEW
                        Flags:: 0
                        Cflags:: KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT
                        Socket:: tls:10.0.0.1:5061
                        Methods:: 7999
                        SIP_instance:: <urn:uuid:e1ee25dc-388f-4c0c-8026-00041323467D>
                Contact:: sip:200@172.16.1.225:2186;transport=tls Q=1
                        ContactID:: 3848466619076450459
                        Expires:: 2989
                        Callid:: 5BBAD7A8463DDF44-zzt403mfjy8h
                        Cseq:: 120
                        User-agent:: snom360/8.7.4.8.6
                        Received:: sip:10.10.10.138:2186;transport=tls
                        State:: CS_NEW
                        Flags:: 0
                        Cflags:: KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT
                        Socket:: tls:10.0.0.1:5061
                        Methods:: 7999
                        SIP_instance:: <urn:uuid:e1ee25dc-388f-4c0c-8026-00041323467D>
```
I can't find, why "get_ucontact_from_id" can't find contact. Please help.

**Comment by vasilevalex** [comment]
Hi @bogdan-iancu 
usrloc preset is full-sharing-cluster. This is from config:
```
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NATTED_CLIENT")
modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "location_cluster", 2)
modparam("usrloc", "shared_pinging", 0)

loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2)
modparam("mid_registrar", "outgoing_expires", 1800)
modparam("mid_registrar", "received_avp", "$avp(received_nh)")
modparam("mid_registrar", "extra_contact_params_avp", "$avp(extra_ct_params)")
modparam("mid_registrar", "tcp_persistent_flag", "TCP_PERSISTENT")

loadmodule "nathelper.so"
modparam("nathelper", "natping_interval", 40)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "natping_partitions", 8)
modparam("nathelper", "natping_tcp", 1)
modparam("nathelper", "sipping_bflag", "SIP_PING_FLAG")
modparam("nathelper", "remove_on_timeout_bflag", "KILL_ZOMBIES")
modparam("nathelper", "sipping_from", "sip:pinger@sip.test.com")
modparam("nathelper", "received_avp", "$avp(received_nh)")
```
Everything works. I restart Active server. It gets all the data from cluster, but as phones lost tls connections - they start re-register. So all tls endpoints from cluster are dead and must be cleaned by nathelper. But it can't. No DB for usrloc. Only for another modules.

**Comment by bogdan-iancu** [comment]
I see..May I ask a stupid one - are you sure the contacts nathelper tries to delete are still in memory ? Have you checked with `opensipsctl fifo ul_dump` to see if the contacts are in memory (the listing will also give the contact ID, so you can correlate with the logs).

**Comment by vasilevalex** [comment]
@bogdan-iancu Yes, they are in memory. In first message I wrote output of `opensipsctl ul show` and you can see there the same Contact ID in debug messages and in the output of command.

**Comment by bogdan-iancu** [comment]
yeah, sorry, missed that. Maybe there is a mismatch at the usrloc table level.
What is the name of the usrloc table/domain you use with mid_register module (the first param of the save/lookup functions) ? "location" ? It is the same as the one displayed by "ul_dump" before and after the restart ?

**Comment by vasilevalex** [comment]
usrloc has "location" and "location_inet6" domains (IPv4, IPv6 endpoints). To make it simple, I tested only with "location". Mid_registrar uses "location". I also thought about domain mismatch, so I catched call of `get_ucontact_from_id` with gdb and parameter "d" points to structure for domain "location". So my assumption was wrong.

**Comment by vasilevalex** [comment]
Hi @bogdan-iancu  If I make like this (code for 2.4 branch):
```
diff --git a/modules/usrloc/dlist.c b/modules/usrloc/dlist.c
index 67dbdfc..1e1e580 100644
--- a/modules/usrloc/dlist.c
+++ b/modules/usrloc/dlist.c
@@ -1125,8 +1125,8 @@ ucontact_t* get_ucontact_from_id(udomain_t *d, uint64_t contact_id, urecord_t **
                }

                r = (urecord_t *)*dest;
-               if (r->label != rlabel)
-                       continue;
+               /*if (r->label != rlabel)
+                       continue;*/

                for (c = r->contacts; c != NULL; c = c->next)
                        if ((unsigned short)c->label == clabel) {
```
Everything works fine, contacts can be found and deleted. So something wrong with rlabel. They are not the same. I don't know why?
This patch is not break anything, just less efficient code.

**Comment by bogdan-iancu** [comment]
OK, @liviuchircu has some clue on this matter, he will follow up with this.

**Comment by vasilevalex** [comment]
Hi @liviuchircu , on summit you've said that it is simple to correct. Or I have to use my ugly patch every build.

**Comment by vasilevalex** [comment]
up

**Comment by liviuchircu** [comment]
Apologies for the dead time here -- I don't remember saying that "it's easy to correct", rather "the problem is obvious and this should bring us closer to fixing it".  I will start working on this issue asap, expect a status update by the end of this week.

**Comment by vasilevalex** [comment]
@liviuchircu Sorry, of course, I understand, that the problem is not simple, because I can't fix it myself :) and need help of professionals.

**Comment by liviuchircu** [comment]
Although it took a while, the official fix is finally here, @vasilevalex !  Do let me know if you encounter any more issues with the nathelper deletion logic.

**Comment by vasilevalex** [comment]
@liviuchircu Thanks! I'll try it.
