### ISSUE TITLE
Behaviour of s.substr

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1495]
Hello Team,

please explain me if this correct behaviour or no?

$var(xxx) = "12345";
$var(y) = $(var(xxx){s.substr,3,0}); - returns "45", $rc = 1
$var(y) = $(var(xxx){s.substr,5,0}); - returns "12345", $rc = -1

Return code is ok, but I think the 2nd one must return "". It would be more predictable.

**Comment by nikbyte** [comment]
And as feature request.
Why not to add
$var(y) = $(var(xxx){s.substr,3,-1}); - returns "4"
$var(y) = $(var(xxx){s.substr,0,-1}); - returns "1234"
$var(y) = $(var(xxx){s.substr,0,-2}); - returns "123"
?

**Comment by nikbyte** [comment]
I've made a patch illustrating this conception. Hope you'll find it useful.

https://github.com/OpenSIPS/opensips/pull/1496

**Comment by bogdan-iancu** [comment]
Hi @nikbyte - if `{s.substr,5,0}` returns something else than NULL, it is a bug! I will change the label and run some tests.

**Comment by bogdan-iancu** [comment]
@nikbyte , I tested this code:
```
	$var(xxx) = "12345";
	$var(y) = $(var(xxx){s.substr,3,0});
	$var(y) = $(var(xxx){s.substr,5,0});
	xlog("-----------5/0 =  <$(var(xxx){s.substr,5,0})> / <$var(y)>\n");
```
and what I got is

```
Oct 17 10:53:33 [23051] DBG:core:tr_eval_string: i=3 j=0
Oct 17 10:53:33 [23051] DBG:core:tr_eval_string: i=5 j=0
Oct 17 10:53:33 [23051] ERROR:core:tr_eval_string: substr out of range
Oct 17 10:53:33 [23051] DBG:core:tr_eval_string: i=5 j=0
Oct 17 10:53:33 [23051] ERROR:core:tr_eval_string: substr out of range
Oct 17 10:53:33 [23051] -----------5/0 =  <<null>> / <<null>>

```

which seems correct to me......could you comment on what you observed in the first place ??

**Comment by nikbyte** [comment]
WTF. You cured this with only look. 🙂 Bogdan, I'm sorry for your time.
I'm pretty sure I had this, but now I cannot reproduce. Let me reopen this if I'll find something strange again.

P.S. $var(xxx) = "12345";
$var(y) = $(var(xxx){s.substr,-10,0}); - returns NULL
- normal behaviour?

Please look at my patch, it provides very flexible s.substr. It's already working few days on one of my servers without any issue.

**Comment by bogdan-iancu** [comment]
@nikbyte , the #1496 was already merged
