### ISSUE TITLE
$rs for local generated replies is not available in failure route

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#1515]
Hello guys! I have this situation with $rs value.
On timeout opensips locally generates 408 reply, i can get this info from $rs in on_reply route.
But i can not get this info from $rs in on_failure route.
```
...
t_on_reply("T_REPLY");
t_on_failure("T_FAILED");
...

onreply_route[T_REPLY] {
    xlog("DEBUG-T_FAILED rs=$rs\n")
...

failure_route[T_FAILED] {
    xlog("DEBUG-T_FAILED2 rs=$rs <reply>rs=$(<reply>rs)\n");
...
```
Logs:
```
Oct 26 15:57:55 [27073] DEBUG-T_FAILED1 rs=408
Oct 26 15:58:05 [27071] DEBUG-T_FAILED2 rs=<null> <reply>rs=<null>
```

opensips -V:
```
version: opensips 2.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 026ec3dc3
main.c compiled on  with gcc 7
```
Can you please fix it? Thanks!

**Comment by bogdan-iancu** [comment]
There is nothing to be fixed here. In failure route you handle a sip request, not a sip reply, so the reply specific variables do not work.
If you really need to access from failure route some informatie about the reply, see the "context" option in the docs on scripting variables.

**Comment by nikbyte** [comment]
Hi Bogdan.

But... it wish context.
The issue here that when opensips generates 408 internally, it process onreply route, $rs is available there, but in failure route both $rs (it's ok) and $(<reply>rs) (with context!!!) are null.

**Comment by bogdan-iancu** [comment]
Well, in the example there is no context used at all with the variables. Please post the exact usage case.

**Comment by nikbyte** [comment]
Sorry, Bogdan. Maybe I don't understand something.

From example above:

    xlog("DEBUG-T_FAILED2 rs=$rs <reply>rs=**$(<reply>rs)**\n");

Isn't this context?

**Comment by bogdan-iancu** [comment]
@nikbyte , the $rs and $rr variables return values from a received SIP reply. In your case, you have a 408 internally generated reply, not a received reply. This is why the variables (even with the context) do return NULL.
The best way to access the reply code (received or internally generated) is via the [$T_reply_code](http://www.opensips.org/html/docs/modules/2.4.x/tm.html#pv_T_reply_code) from the TM module.

**Comment by nikbyte** [comment]
Hmmm. Thank you for the explanation, it really helped.

However here is my opinion. If you pass some code (even locally generated) into on_reply route, it must be available via $(<reply>rs) in failure route.

Documentation says:
> The reply context can be used in the failure route to request for the pseudo-variable to be evaluated in the context of the reply message. 

408 is the context of reply message which you generated internally. So, it looks like it must be available. Or add note into doc that it doesn't work for local generated replies.

**Comment by bogdan-iancu** [comment]
@nikbyte, the internally generated replies are not visible in the onreply_route (an local 408 will not trigger onreply, but only failure route).
The internally generated 408 is not a real reply, is a FAKE one (it does not exist as a sip_msg structure, but only as a reply code) - this is why the context does not work for it.

**Comment by nikbyte** [comment]
Ok, thank you for the explanation.
