### ISSUE TITLE
mid_registrar can't handle other Contacts in 200 OK

### ISSUE THREAD

**Issue by jpyle490** [OpenSIPS/opensips#1516]
I have mid_registrar working fine with mode=0 (contact mirroring).  If the SIP UA that registers "though" the mid_registrar is the only Contact on that AoR at the main registrar, all is well.  If there are other Contacts registered outside the mid_registrar (at least from the same IP address), it throws errors and doesn't save the registration in its table.

```
ERROR:mid_registrar:match_contact: failed to locate our ';ctid=' param, ci = 23f45db4-5218-4ace-9a1a-69a5d504657e!
ERROR:mid_registrar:save_restore_rpl_contacts: 200 OK reply does not include all req contacts! (ci: 23f45db4-5218-4ace-9a1a-69a5d504657e)
ERROR:mid_registrar:mid_reg_resp_in: failed to process rpl contacts for AoR 'user'
```

The 200 OK that produced these errors is this one:

```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 6.7.8.9:5060;branch=z9hG4bKd6af.b599c0a6.0
Via: SIP/2.0/UDP 192.168.1.16:36454;received=192.168.1.16;rport=36454;branch=z9hG4bKPj15302dec-a81d-46a6-b6f0-73633d7e4193
From: "Test" <sip:user@domain.org>;tag=51c06d86-069e-4794-8c14-ba651ae895e6
To: "Test" <sip:user@domain.org>;tag=8651f1c7cb44b0388d350e25a17b8e91.24e2
Call-ID: 23f45db4-5218-4ace-9a1a-69a5d504657e
CSeq: 2 REGISTER
Contact: <sip:27359871@6.7.8.9:5062>;expires=354, <sip:20849317@6.7.8.9:5060;ctid=4250694360795977181>;expires=360
Content-Length: 0
```

(IPs and other identifying characteristics have been changed to protect the guilty.)

In this case I had one UA registering through the mid_registrar with interface IP 6.7.8.9, and another UA registering directly from 6.7.8.9.  I haven't tried with separate IPs; I only have the one to work with at the moment.

**Comment by jpyle490** [comment]
I was able to test on a registration with IPs different than the mid_registrar proxy's interface in the Contact headers.  It still showed the errors.

**Comment by liviuchircu** [comment]
Hi, Jeff!  And thank you for the nice report! <3
