### ISSUE TITLE
Accounting feature request

### ISSUE THREAD

**Issue by danpascu** [OpenSIPS/opensips#1519]
It would be helpful to be able to test if accounting is enabled. Sometimes I need to manually add an accounting record, like for example for diverted calls, I need a record for the original call and one for the diverted call, but I only want to do it if accounting was originally enabled for this transaction. Since now flags are internal I can no longer test for them.

This can be considered a regression, since in the old model we set the flags in the script and could test them whenever needed, but now that functionality is lost.

**Comment by liviuchircu** [comment]
Wouldn't you be able to achieve the previous logic by doing:

    do_accounting("db", "cdr|missed|failed");
    setflag(ACC_ENABLED);

... then later on testing it with `isflagset()`, as part of the same transaction?

    if (isflagset(ACC_ENABLED))
        ...

**Comment by danpascu** [comment]
I can. Actually this is what I do right now as a workaround. But it's not nice. I need to add a setflag/resetflag to every do_accounting/drop_accounting call and basically duplicate the information that I want to do accounting in 2 places. Since do_accounting/drop_accounting already update that information internally, it would also make sense to provide a means to query the state to avoid the duplication.
