### ISSUE TITLE
Compiling Opensips with cmake on Centos7

### ISSUE THREAD

**Issue by unvaare** [OpenSIPS/opensips#1520]
Hi Everyone,

I am facing below errors when trying to compile opensips code with Clion IDE on CentOS; I have not changed anything, just compiling from source. Can you please help?

/root/Downloads/clion-2018.2.5/bin/cmake/linux/bin/cmake --build /root/opensips-2.4/cmake-build-debug --target all -- -j 2
[  0%] Building C object CMakeFiles/opensips_2_4.dir/aaa/aaa.c.o
[  0%] Building C object CMakeFiles/opensips_2_4.dir/cachedb/example/example_cachedb.c.o
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: character constant too long for its type [enabled by default]
  MODULE_VERSION,
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: initialization makes pointer from integer without a cast [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: (near initialization for ‘exports.version’) [enabled by default]
In file included from /root/opensips-2.4/cachedb/example/../../sr_module.h:52:0,
                 from /root/opensips-2.4/cachedb/example/example_cachedb.c:32:
/root/opensips-2.4/cachedb/example/../../version.h:26:37: **error: expected ‘}’ before string constant
 #define OPENSIPS_FULL_VERSION  NAME " " VERSION " (" ARCH "/" OS ")"**
                                     ^
/root/opensips-2.4/cachedb/example/../../sr_module.h:102:2: note: in expansion of macro ‘OPENSIPS_FULL_VERSION’
  OPENSIPS_FULL_VERSION, \
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: note: in expansion of macro ‘MODULE_VERSION’
  MODULE_VERSION,
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: character constant too long for its type [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: character constant too long for its type [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:75:2: warning: character constant too long for its type [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:89:1: warning: missing initializer for field ‘compile_flags’ of ‘struct module_exports’ [-Wmissing-field-initializers]
 };
 ^
In file included from /root/opensips-2.4/cachedb/example/example_cachedb.c:32:0:
/root/opensips-2.4/cachedb/example/../../sr_module.h:175:8: note: ‘compile_flags’ declared here
  char *compile_flags;            /*!< compile flags used on the module */
        ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:95:12: warning: ‘mod_init’ defined but not used [-Wunused-function]
 static int mod_init(void)
            ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:137:12: warning: ‘child_init’ defined but not used [-Wunused-function]
 static int child_init(int rank)
            ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:154:13: warning: ‘destroy’ defined but not used [-Wunused-function]
 static void destroy(void)
             ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:59:21: warning: ‘cmds’ defined but not used [-Wunused-variable]
 static cmd_export_t cmds[]=
                     ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:65:23: warning: ‘params’ defined but not used [-Wunused-variable]
 static param_export_t params[]={
                       ^
gmake[2]: *** [CMakeFiles/opensips_2_4.dir/cachedb/example/example_cachedb.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/opensips_2_4.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by liviuchircu** [comment]
Please do `rm -fr ./cachedb/test` and retry.  For your purposes, you don't need to bother compiling in the unit testing framework support.  Curious to see how it goes :)

**Comment by unvaare** [comment]
After deleting ./chachedb/test getting following error:
/root/Downloads/clion-2018.2.5/bin/cmake/linux/bin/cmake --build /root/opensips-2.4/cmake-build-debug --target all -- -j 2
gmake[2]: *** No rule to make target `../cachedb/test/test_backends.c', needed by `CMakeFiles/opensips_2_4.dir/cachedb/test/test_backends.c.o'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[  0%] Building C object CMakeFiles/opensips_2_4.dir/aaa/aaa.c.o
[  0%] Building C object CMakeFiles/opensips_2_4.dir/cachedb/example/example_cachedb.c.o
/root/opensips-2.4/cachedb/example/example_cachedb.c:79:2: warning: initialization from incompatible pointer type [enabled by default]
  params,      /* exported parameters */
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:79:2: warning: (near initialization for ‘exports.acmds’) [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:85:2: warning: initialization from incompatible pointer type [enabled by default]
  mod_init,     /* module initialization function */
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:85:2: warning: (near initialization for ‘exports.procs’) [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:86:2: warning: initialization from incompatible pointer type [enabled by default]
  (response_function) 0,      /* response handling function */
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:86:2: warning: (near initialization for ‘exports.init_f’) [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:87:2: warning: initialization from incompatible pointer type [enabled by default]
  (destroy_function)destroy, /* destroy function */
  ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:87:2: warning: (near initialization for ‘exports.response_f’) [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:89:1: warning: initialization from incompatible pointer type [enabled by default]
 };
 ^
/root/opensips-2.4/cachedb/example/example_cachedb.c:89:1: warning: (near initialization for ‘exports.destroy_f’) [enabled by default]
/root/opensips-2.4/cachedb/example/example_cachedb.c:89:1: warning: missing initializer for field ‘init_child_f’ of ‘struct module_exports’ [-Wmissing-field-initializers]
In file included from /root/opensips-2.4/cachedb/example/example_cachedb.c:32:0:
/root/opensips-2.4/cachedb/example/../../sr_module.h:207:22: note: ‘init_child_f’ declared here
  child_init_function init_child_f;/*!< function called by all processes
                      ^
gmake[1]: *** [CMakeFiles/opensips_2_4.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by liviuchircu** [comment]
`rm -fr ./cachedb/test test/unit_tests*` was the proper command.  I updated my answer too late

**Comment by liviuchircu** [comment]
Now it's trying to compile `cachedb/example/example_cachedb.c`...  Ok, this is too much.  I suggest you either fix these yourself and write a nice blog post about it, or just find a way to use the existing work that we already have inside `Makefile`, `Makefile.defs`, yada yada...
