### ISSUE TITLE
Bug with 2.4 git rev 1cd794c4dedf4881db8b4ffc04a76b34c53a5bab

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#1523]
Since updating, standby server started showing following errors:

Nov  5 13:32:52 db2 /usr/local/sbin/opensips[23992]: CRITICAL:usrloc:store_deserialize: #012>>> non-cJSON_Object kv_store col type (8)#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Nov  5 13:34:34 db2 /usr/local/sbin/opensips[29925]: ERROR:usrloc:store_deserialize: bad JSON input or oom

**Comment by liviuchircu** [comment]
Hi, sekil!  Can you please fill me in on the following:

* did you update and restart both the active and stand-by server, or just one of them?  If the latter, which one?
* what are your usrloc/mid-registrar modparams?
