### ISSUE TITLE
Raising Events via MI interfaces

### ISSUE THREAD

**Issue by goharahmed** [OpenSIPS/opensips#1526]
OpenSIPS can not trigger a config based event from external interfaces (MI) - we can subscribe to an event using the FIFO command: 

`opensipsctl fifo event_subscribe E_PIKE_BLOCKED udp:127.0.0.1:8888 1200`

Now, since we've the ability inside config script to wait_for_event() or notify_on_event() we should be able to trigger the event from outside the opensips script as well. i.e:

`opensipsctl fifo raise_event MY_EVENT param1 param2 param3 ....`

FIFO is just an example ideally this should be doable from any MI_* interface.

Thanks,

**Comment by razvancrainea** [comment]
You can find the new command documented [here](https://www.opensips.org/Documentation/Interface-CoreMI-3-1#toc20)
