### ISSUE TITLE
Make drouting/dispatcher pinging to adhere to the tagging mechanism

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#1532]
Provide a way to disable drouting/dispatcher pinging.

**Comment by vasilevalex** [comment]
Hi @razvancrainea do you mean something like this, https://github.com/OpenSIPS/opensips/pull/1493 ?

**Comment by razvancrainea** [comment]
I'm so sorry, I didn't even realize the feature is already in there. I was using opensips 2.4, which does not have this, so I immediately opened a bug. I apologize for that, your PR does exactly what I was looking for!
However, after some discussions with @bogdan-iancu, it would be nicer if the pinging feature would adhere to the tagging mechanism (used by dialog and presence). So instead of having a function for each module (nh, dispatcher, drouting) to enable/disable pinging, it would be nicer if all would be able to share a `tag`. Whoever within a cluster has the active `tag`, it will enable pinging for all resources that use that tag. This would offer more flexibility and it will be easier to maintain (i.e. when switching from active to backup).
I will now change the "purpose" of this ticket to enhance these module to use the tagging mechanism.

**Comment by bogdan-iancu** [comment]
The above commits cover the mentioned requests. All drouting, load_balancer and dispatcher module do use sharing tag (the new global ones provided by clusterer module) in order to control who is doing the pinging and state sharing inside the cluster.
