### ISSUE TITLE
A bug or not a bug? (drouting)

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1535]
Hi Team,

tell me please.
I have two records in dr_rules table with the same prefix, but with different gwlist.
Like:
group=0, prefix=111 + gwlist="aaa"
and
group=0, prefix=111 + gwlist="bbb"

I call do_route with next params:
do_routing("in:0", "F", "bbb", "$avp(attrs)")

opensips search my route list and find 1st record, then it check filters, decides that aaa != bbb and return an error.

I expect it should match my line with gateway "bbb".

Is current behaviour correct? Is this a bug?

**Comment by bogdan-iancu** [comment]
@nikbyte , this is not a bug - the GW fileter, as the name says, it is just a filter, it is not involved into rule selection - it just filters out some GW from the list you have in the selected rule. If the filtering results in an empty list, there is no fallback or so.
So, maybe you need a different approach on how you use the module.

**Comment by nikbyte** [comment]
Thank you for the explanation.
