### ISSUE TITLE
problem usrloc postgres update and insert

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1538]
**good day!**
Version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3fe6c3804
main.c compiled on 15:52:53 Nov 19 2018 with gcc 7
usrloc module settings - opensips_modules:
loadmodule "usrloc.so"
modparam("usrloc", "use_domain", 0)
modparam("usrloc", "nat_bflag", "NAT_FLAG")
modparam("usrloc", "timer_interval", 30)
modparam("usrloc", "working_mode_preset", "single-instance-sql-write-back")
modparam ("usrloc", "cluster_mode", "none")
modparam("usrloc", "db_url", "postgres://user:password@host/base")
modparam ("usrloc", "restart_persistency", "load-from-sql")
modparam ("usrloc", "sql_write_mode", "write-back")
modparam("usrloc", "matching_mode", 0)

**Problem when adding and updating a table of location, here’s a query:**
_If the user agent is not in the location table (INSERT):
PQsendQuery Error: ERROR: INSERT contains more expressions than target columns
query:_
insert into location (contact_id,username,contact,expires,q,callid,cseq,flags,cflags,user_agent,received,path,socket,methods,last_modified,sip_instance,kv_store,attr ) values (4258527606206517429,'3136439102','sip:3136439102@85.12.217.67:51045;transport=UDP;rinstance=ca36c5caa40637ec',1542696716,-1,00     ,'NjkwYmQ3NTg4NGNmNWNhMjAyODAxMTI2ZmM1NzEzMDk.',114,0,'SIP_PING_FLAG','3CXPhone 6.0.26523.0',NULL,NULL,'udp:85.12.253.12:5060',6079,'2018-11-20 11:50:56',NULL,NULL,NULL)
_if the user agent is present in the table location (UPDATE):
ERROR: syntax error (approximate position: "00")
query:_
update location set contact_id=4258716397632264084,expires=1542697835,q=-1,00     ,cseq=4,flags=0,cflags='',user_agent='Yealink SIP-T19P 31.72.193.20',received=NULL,path=NULL,socket='udp:85.12.253.12:5060',methods=16383,last_modified='2018-11-20 11:10:35',kv_store=NULL,attr=NULL,callid='1059974469@10.227.29.252' where contact_id=4258716397632264084

column q tables location is a data type REAL (NOT NULL DEFAULT 1.0)
postgres syntax can not be ",", expression "-1,00" для q not true!
The correct query should look like this:
insert into location (contact_id,username,contact,expires,q,callid,cseq,flags,cflags,user_agent,received,path,socket,methods,last_modified,sip_instance,kv_store,attr ) values (4258527606206517429,'3136439102','sip:3136439102@85.12.217.67:51045;transport=UDP;rinstance=ca36c5caa40637ec',1542696716,**-1.00**     ,'NjkwYmQ3NTg4NGNmNWNhMjAyODAxMTI2ZmM1NzEzMDk.',114,0,'SIP_PING_FLAG','3CXPhone 6.0.26523.0',NULL,NULL,'udp:85.12.253.12:5060',6079,'2018-11-20 11:50:56',NULL,NULL,NULL)
Or the structure of the table location should be different from the existing:
---------------+-----------------------------+---------------------------------------------------------------------
 contact_id    | bigint                      | NOT NULL DEFAULT nextval('location_contact_id_seq'::regclass)
 username      | character varying(64)       | NOT NULL DEFAULT ''::character varying
 domain        | character varying(64)       | DEFAULT NULL::character varying
 contact       | character varying(255)      | NOT NULL DEFAULT ''::character varying
 received      | character varying(255)      | DEFAULT NULL::character varying
 path          | character varying(255)      | DEFAULT NULL::character varying
 expires       | integer                     | NOT NULL
 q             | real                        | NOT NULL DEFAULT 1.0
 callid        | character varying(255)      | NOT NULL DEFAULT 'Default-Call-ID'::character varying
 cseq          | integer                     | NOT NULL DEFAULT 13
 last_modified | timestamp without time zone | NOT NULL DEFAULT '1900-01-01 00:00:01'::timestamp without time zone
 flags         | integer                     | NOT NULL DEFAULT 0
 cflags        | character varying(255)      | DEFAULT NULL::character varying
 user_agent    | character varying(255)      | NOT NULL DEFAULT ''::character varying
 socket        | character varying(64)       | DEFAULT NULL::character varying
 methods       | integer                     |
 sip_instance  | character varying(255)      | DEFAULT NULL::character varying
 kv_store      | text                        |
 attr          | character varying(255)      | DEFAULT NULL::character varying
Индексы:
    "location_pkey" PRIMARY KEY, btree (contact_id)

**Comment by ilyinvv** [comment]
Help please get rid of messages!
PQsendQuery Error: ERROR: INSERT contains more expressions than target columns
query:
insert into location (contact_id,username,contact,expires,q,callid,cseq,flags,cflags,user_agent,received,path,socket,methods,last_modified,sip_instance,kv_store,attr ) values (4258527606206517429,'3136439102','sip:3136439102@85.12.217.67:51045;transport=UDP;rinstance=ca36c5caa40637ec',1542696716,-1,00 ,'NjkwYmQ3NTg4NGNmNWNhMjAyODAxMTI2ZmM1NzEzMDk.',114,0,'SIP_PING_FLAG','3CXPhone 6.0.26523.0',NULL,NULL,'udp:85.12.253.12:5060',6079,'2018-11-20 11:50:56',NULL,NULL,NULL)
if the user agent is present in the table location (UPDATE):
ERROR: syntax error (approximate position: "00")

**Comment by bogdan-iancu** [comment]
@ilyinvv , thanks for report. Could you run on your in the same console where you start opensips `locale -k LC_NUMERIC` and provide the output here ?

**Comment by ilyinvv** [comment]
**Bogdan-iancu thanks for the answer, here's the conclusion:**
root@node2:/usr/local/etc/opensips# **locale -k LC_NUMERIC**
decimal_point=","
thousands_sep=" "
grouping=3;3
numeric-decimal-point-wc=44
numeric-thousands-sep-wc=8239
numeric-codeset="UTF-8"
root@node2:/usr/local/etc/opensips# **lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by ilyinvv** [comment]
**uname -a**
Linux node2 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 x86_64 x86_64 GNU/Linux

**Comment by bogdan-iancu** [comment]
@ilyinvv , your locals seems to be the problem, as the LC_NUMERIC forces "," as decimal_point. As this setting has a global impact on your system, including over glibc in how `printf()` are formatting the float values.
As a prove of concept, try to change the  LC_NUMERIC to "POSIX" before starting OpenSIPS - see if the issue goes away or not

**Comment by ilyinvv** [comment]
Thanks bogdan-iancu, it really helped.
locale -k LC_NUMERIC - POSIX
decimal_point="."
