### ISSUE TITLE
"Polling is overdue" leads to ignored incoming TCP messages

### ISSUE THREAD

**Issue by alexgraham-RCS** [OpenSIPS/opensips#1550]
**Problem Scenario**
We are running OPENSIPS 2.2.6 with the default TCP connection timeout value “tcp_async_ local_connect_timeout” of 100 msec.

Actions to reproduce the problem:
1. 	Worker 1 initiates a TCP connection to a destination with a round trip time of 130 msec.
2. 	After a duration of tcp_async_local_connection_timeout (100 msec by default), Worker 1 gives up the synchronous connection attempt and goes to async_connect label.  After a few steps, Worker1 send_fd to Worker2 with command ASYNC_CONNECT. 
3. 	Worker2 receives this command and reactor_add_writer. This causes OPENSIPS to not read anything from the TCP connection even if some time later there is data available to read. 

Every time this happens, this log is produced: "Polling is overdue".

**Workaround**
1.	The timeout value was increased to 200 msec:
“This timeout value is configurable via modparam("proto_tcp", "tcp_async_local_connect_timeout", 200);”
2.	OPENSIPS was restarted.
3.	The TCP connection was established before the timeout fired.  The FD READ permissions allowed incoming messages to be processed as expected.

This bug has not been fixed in 2.2.7 or 2.4.3. I did not see any open tickets tracking this bug.

**Comment by razvancrainea** [comment]
I am pretty sure this is the same bug fixed in ca643dee0f8851be7c1756bd270f168e41fb053c.
Can you pull the latest version (of either 2.2 or 2.4) and test again your scenario?

**Comment by alexgraham-RCS** [comment]
Hi,

This is a similar issue. We were tracking the flow through the net/net_tcp.c **handle_worker()** case ASYNC_CONNECT, not the **handle_tcpconn_ev** NOT IO_WATCH_READ branch   Thx!.

**Comment by alexgraham-RCS** [comment]
Additional testing using the 2.2.7 + ca643de fix with tcp_async=0 set successfully showed the "Polling is overdue" log with subsequent establishment of the TCP connection with FD READ set.  All is good.
