### ISSUE TITLE
opensips 2.4.3 high CPU

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#1552]
I am in the process of doing an upgrade from 2.2 to 2.4.3 and ran into an issue with high CPU utilization.  There were 200-400 test calls on the server, ran fine for 6hrs with very low CPU and then 3 cores got hung at 100% utilization.  After all the calls dropped off, there was 1 hung call.  I attempted to end with `dlg_end_dlg` but the command hung and caused a 4th core to hang at 100%.

opensips -V
```
version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c49ae1d53
main.c compiled on 13:53:51 Nov 28 2018 with gcc 6.3.0
```
I have attached condensed output from `opensipsctl trap` below.  PID 31147 corresponds to the `dlg_end_dlg` MI command.
[opensips_trap.log](https://pastebin.com/GyaQrSrG)

OS is debian stretch.  Thanks in advance for the help!

**Comment by bogdan-iancu** [comment]
I assume the trap covers only the processes doing 100% CPU, right ? The 31281 proc looks suspicions - it is doing some memory malloc while holding the some TM/transaction lock. The other procs are simply waiting for that particular lock to be released (the lock waiting is CPU busy).
Is this 100% cpu hanging for ever? or does it recover after some time ?

**Comment by john08burke** [comment]
After more testing, it turns out that the root cause is a segfault.  Systemd was restarting opensips from segfault and the CPU was being locked up due to heavy memory reloading from initialization of dr partitions.

The cause of segfault looks like it's associated with the acc module.  The segfault occurs under load scenario of ~400 calls. The acc module is writing to local mysql and flatfile (see script snippet).

The script line that fails after some time is:
`$acc_extra(outbound_ip) = $dd;`

[gdb bt full output](https://pastebin.com/Dx0X17D6)
[log output](https://pastebin.com/hBEY7xWj) -- for segfault PID
[script snippet](https://pastebin.com/iujc2jYg)

**Comment by liviuchircu** [comment]
Hi @john08burke, it looks like you're runing on the stock `2.4.3` release, thus missing commit e25895624b1c from 18 days ago which seems to be the exact fix for your crash (failure route crashes due to `NULL` context).  Coupled with the fact that you're also missing commit 52e3ada3ab64 from a few days ago, I would *highly* recommend you deployed the nightly `2.4` package and try again.  It is a lot more stable.

Closing for now as outdated.

**Comment by john08burke** [comment]
@liviuchircu many thanks! Successfully verified.
