### ISSUE TITLE
How can i add `Proxy-Authorization`  to  PRACK  header

### ISSUE THREAD

**Issue by Parkistler** [OpenSIPS/opensips#1553]
failure_route[prack_auth] {
    if ($rm == "PRACK") {
        $var(from_number) = $(fU{s.substr, 1, 0});
        $avp(uac_realm) = $fd;
        $avp(uac_username) = "+86" + $var(from_number) + "@" + $fd;
        avp_db_query("SELECT password FROM registrant WHERE (registrar = 'sip:$avp(uac_realm)') AND ( username = '$avp(uac_username)')","$avp(uac_password)");
        uac_auth();
        t_relay();
    }
}

i'm try use uac_auth() or append_hf(), opensips.log is "ERROR:uac:uac_auth: Unable to extract authentication info" 
how can i do, thinks.

**Comment by bogdan-iancu** [comment]
@Parkistler , the `uac_auth()` complains that there is no `Proxy/WWW-Authenticate` header in the reply you received for the PRACK.

**Comment by Parkistler** [comment]
thanks
