### ISSUE TITLE
separate advertised notify socket for rtpproxy

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1563]
I would like to run RTPProxy NATed / routed from the SIP server, for example Opensips is in Docker and binds to an internal address while advertising another.

Opensips does not allow me to bind rtpp_notify_socket to an internal address and advertise a different, public one to RTPProxy when using udp/tcp sockets.

Is it possible to have a different bind and advertised address provided to the RTPProxy module so that it can be run in this configuration?

For example;

Opensips binds on `tcp:172.18.0.3:22222` for the `rtpp_notify_socket`, the Docker container listens on `192.168.0.5:22222`.

RTPProxy is configured with `-n tcp:192.168.0.5:22222`

Opensips doesn't support a different bind/advertised address for the notify socket so Opensips, during call setup sends `tcp:172.18.0.3:22222` which is not valid according to RTPProxy and timeout notifications will not function.

My goal is to run many instances of RTPProxy on distributed hardware, and thus, unix sockets are not suitable.

**Comment by razvancrainea** [comment]
You are right, this is not possible right now - I've tagged this as feature request for the next major release.

**Comment by razvancrainea** [comment]
Hi, Hamid!

What you are trying to achieve is not possible right now, as OpenSIPS 
can't bind a different socket than the one advertised to RTPProxy.
Please open a feature request for this[1].

[1] https://github.com/OpenSIPS/opensips/issues

Răzvan Crainea
OpenSIPS Core Developer
http://www.opensips-solutions.com

**Comment by razvancrainea** [comment]
Just figured out this already is part of a feature request, so you can ignore my previous message.
As I said in the previous ticket, this is not yet available - the documentation you are pointing out refers to the address advertised by RTPProxy in the `c=` line, not the one advertised as the RTPProxy socket. That's a completely different bind socket.

**Comment by hamid-elaosta** [comment]
Understood, thanks for the clarification.

**Comment by razvancrainea** [comment]
I've just developed this: basically what you can do is to specify a socket after the `n` flag, like `n<tcp:ADVERTISED:9999>`.
