### ISSUE TITLE
I have problems with fix_nated_contact

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1566]
If the UA device is behind NAT and the headers from it come with gray IP addresses, then I use the fix_nated_contact () function, and it correctly sends ACK responses to the desired white IP and port, but several INVITEs arrive, then the fix_nated_contact () function does not destinations.

**Example:**
Asterisk -> Proxy Server Opensips -> UA Yealink (client opensips, fore NAT)
Asterisk -> Opensips -> UA Yealink (client opensips, fore NAT)

Invite -> ========================== Invite ->
<- 100 Giving a try  =================== <- 100 Giving a try 
<- 180 Ringing  ===================== <- 180 Ringing (Contact: IP 10.30.32.118)
<- 200 OK SDP ===================== <- 200 OK SDP (Contact: IP 10.30.32.118)
ACK -> ========================== ACK -> (ACK URI 85.14.259.11:60308)
Correctly working dialogue fix_nated_contact () works correctly!
**Further in the same dialogue RE -Invite**
Invite -> ========================== Invite ->
<- 100 Giving a try  =================== <- 100 Giving a try 
<- 180 Ringing  ===================== <- 180 Ringing (Contact: IP 10.30.32.118)
<- 200 OK SDP ===================== <- 200 OK SDP (Contact: IP 10.30.32.118)
ACK -> ========================== ACK -> (ACK URI 10.30.32.118:60308)
**Dialogue fails**

my opensips.cfg
```
onreply_route[invitereply]
{
        if (is_method ("INVITE"))
        {
                if (isflagset(NAT_BFLAG) || isbflagset(NAT_FLAG))
                {
                        fix_nated_contact();
                }
        }
```
NAT_FLAG in location exists!
In the log file, I do not see any deviations or errors fix_nated_contact ()

**Comment by razvancrainea** [comment]
@ilyinvv flags are not persistent in the dialog scope, only in transaction. Therefore, if you set the `NAT_BFLAG` or `NAT_FLAG` during initial INVITE, the flag will *NOT* remain set during sequential requests. You need to check again with `fix_nated_contact()`, or store somehow in dialog (using a dlg flag or variable) that the endpoint is private and needs to be fixed.
