### ISSUE TITLE
[registrar] remove() function doesn't compare contacts correctly

### ISSUE THREAD

**Issue by vitalikvoip** [OpenSIPS/opensips#1569]
When remove() is called with an optional "contact" parameter it compares parameter's value with a contact's received (next_hop) field instead of checking the "contact" field. As a result remove() doesn't delete records for UA behind NAT since contact and next_hop addresses are different.

[save.c.txt](https://github.com/OpenSIPS/opensips/files/2680201/save.c.txt)

**Comment by bogdan-iancu** [comment]
@vitalikvoip , if `contact` is passed to the function (see https://github.com/OpenSIPS/opensips/blob/2.4/modules/registrar/save.c#L965), the IP/port/proto are extracted from that URI (see https://github.com/OpenSIPS/opensips/blob/2.4/modules/registrar/save.c#L994).
The actual check (see https://github.com/OpenSIPS/opensips/blob/2.4/modules/registrar/save.c#L1053) is done between those values and the the registered contact URI (see https://github.com/OpenSIPS/opensips/blob/2.4/modules/registrar/save.c#L1025) and not the received field.

**Comment by bogdan-iancu** [comment]
@vitalikvoip , thank for the details, I see your point. After more thoughts, I think the the 'contact' matching is wrong - no DNS lookup should be involved, it should be a straight SIP URI matching.
Let me workout a fix for this

**Comment by bogdan-iancu** [comment]
@vitalikvoip , please check the above fix

**Comment by vitalikvoip** [comment]
I'm using the 2.4 branch and can't just cherry-pick this one commit since save.c from master also supports remove by sip_instance.

**Comment by bogdan-iancu** [comment]
Try this backport [reg_1569_patch.txt](https://github.com/OpenSIPS/opensips/files/2725381/reg_1569_patch.txt)

**Comment by vitalikvoip** [comment]
Thanks for the backport.

This patch works in general but unfortunately doesn't help in my case.
I save mapping of src_ip:src_port and contact from the event_route[E_UL_CONTACT_INSERT] and 
 from tcp disconnection event_route[] (another my feature) call remove() to delete contact which has lost corresponding tcp/tls connection. And the main problem is that contact field from E_UL_CONTACT_INSERT doesn't match to the contact field in usrloc table, because event's one doesn't have contact params like "transport".
In my case resolving host and matching host:port of the contact uri works better then matching contact as a string.

**Comment by bogdan-iancu** [comment]
Why not saving (in E_UL_CONTACT_INSERT event route) the `uri` value from the event (see  http://www.opensips.org/html/docs/modules/2.4.x/usrloc.html#event_E_UL_CONTACT_INSERT), rather than the src_ip:src_port ? this 'uri' is the perfect match for the contact you need in `remove()`.
BTW, what about sharing the tcp disconnect event patch you have ;) ?

**Comment by vitalikvoip** [comment]
Actually, this is exactly what I do. I use cachedb_local and save contact params like "uri" and "received" into a cache where src_ip:src_port is a key. When opensips loses tcp/tls connection it raises E_TCP_CLOSE event with peer's ip:port as params. From the event_route[E_TCP_CLOSE] I extract uri using ip:port as a key and then provide this "uri" to remove(). And that "uri" from E_UL_CONTACT_INSERT somehow doesn't have ";transport=tcp" which is present in the usrloc record and due to this difference remove() can't find a proper record.

**Comment by bogdan-iancu** [comment]
If you do an `opensipsctl ul show` , do you see the contact URIs with or without the transport parameter ??

**Comment by vitalikvoip** [comment]
Holy cow! Your patch works perfectly.
Checked it once again more carefully and found that I save contact into a param list with other usrloc record params and semicolon in "user@domain;transport=tcp" just created one more "transport" param in a list instead of being a part of "contact".

**Comment by bogdan-iancu** [comment]
:) ok, it is good to know, I will backport the fix to 2.4

Thanks for the support in fixing this !!

**Comment by fgast** [comment]
> Thought about sharing E_TCP_CLOSE/E_TLS_CLOSE events code. Had a feeling it a bit dirty and won't be accepted and also need to make a separate branch for it to make a clean pull request. The main stopper is that I work on 2.4 and didn't have time to check the difference with "master" branch to make a patch for it.

Do you mind sharing your raw code for this? I like the feature and maybe i can help to port this to master...
