### ISSUE TITLE
mc_compact memory corruption/crashes

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1570]
I am getting some strange crashes and segfaults on 2.4 when mc_compact is used. Enabling QM malloc and debug yielded the following:

Dec 14 09:18:11 proxydev /opt/opensips_p1/sbin/opensips[3103]: CRITICAL:core:qm_free: freeing already freed pointer, first free: compression.c: mc_compact_cb(954) - aborting
Dec 14 09:18:11 proxydev /opt/opensips_p1/sbin/opensips[3066]: INFO:core:handle_sigs: child process 3103 exited by a signal 6
Dec 14 09:18:11 proxydev /opt/opensips_p1/sbin/opensips[3066]: INFO:core:handle_sigs: core was generated
Dec 14 09:18:11 proxydev /opt/opensips_p1/sbin/opensips[3066]: INFO:core:handle_sigs: terminating due to SIGCHLD

When running under f_malloc the errors were much more random, so I think it may have been introducing memory corruption.

Backtrace:
[3103_btfull.txt](https://github.com/OpenSIPS/opensips/files/2681160/3103_btfull.txt)

Shows the issue is during run_raw_processing_cb.

We are also using the topology_hiding module (which I think also uses some raw callbacks), but I have not yet tested to see if the problems persists without topology_hiding.

Removing calls to mc_compact seem to completely clear the issue.

Let me know if there is any other information that would be helpful. This is all on a dev system so it's fairly easy to make changes and run more debugging.

Opensips Info:
version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a2662be
main.c compiled on 16:46:56 Dec 13 2018 with gcc 7

Thanks!

Regards,

Ryan Bullock

**Comment by razvancrainea** [comment]
This seems to be a bug introduced by commit be3b60366763c3c0390f20be590420440c834204. Reverting the malicious change.

**Comment by razvancrainea** [comment]
Fixed by 57f142bdeda5dd7ad4406cab184ab7a2668e32a1.
