### ISSUE TITLE
mid_registrar cause segfault fault

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1571]
Hello

I am using latest 2.4 branch and I get a segmentation fault when I am tryning to use mid_registrar to very that the user initiating a call is a registered user. I am not sure if my script is wrong but in any case segmentation should be handled.

Bellow is the logging with level 6

Dec 14 21:08:11 esbc /sbin/opensips[26694]: [INVITE] - New Call from sip:5453@1.1.1.1;transport=UDP to sip:5353@1.1.1.1;transport=UDP
Dec 14 21:08:11 esbc /sbin/opensips[26694]: CRITICAL:core:sig_usr: segfault in process pid: 26694, id: 7
Dec 14 21:08:11 esbc /sbin/opensips[26721]: DBG:core:receive_fd: EOF on 61
Dec 14 21:08:11 esbc /sbin/opensips[26721]: CRITICAL:core:handle_worker: dead child 7 (EOF received), pid 26694
Dec 14 21:08:11 esbc /sbin/opensips[26721]: DBG:core:io_watch_del: [TCP_main] io_watch_del op on index 9 61 (0x8c02a0, 61, 9, 0x0,0x1) fd_no=31 called
Dec 14 21:08:11 esbc /sbin/opensips[26682]: INFO:core:handle_sigs: child process 26694 exited by a signal 11
Dec 14 21:08:11 esbc /sbin/opensips[26682]: INFO:core:handle_sigs: core was not generated
Dec 14 21:08:11 esbc /sbin/opensips[26682]: INFO:core:handle_sigs: terminating due to SIGCHLD

My script

if(is_method("INVITE") && !has_totag())
{
.....
.....
if (!mid_registrar_lookup("location",,"$fU"))
{
......

Regards

**Comment by liviuchircu** [comment]
Thank you for the report, @apsaras ! You actually found a 6-year old bug, since most people have preferred to use the `registered()` function for this purpose up until `2.1`, or the `is_registered()` rename of it, starting from `2.2`!
