### ISSUE TITLE
Transformations should not share the same buffer

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#1572]
Currently, most of the transformations share the same buffer for their output (`_tr_buffer`), or use a buffer that becomes shared (`_ip_addr_A_buff` in case of `ip.ntop` transformation). This leads to an undefined behavior when chaining multiple transformations, or when comparing the output of a transformation (see #1568).

An idea to fix this is to attach a special buffer to the variable's spec, that can be used by any transformation in the chain.

**Comment by vasilevalex** [comment]
It's important to implement. This is the source of not obvious mistakes in config script.
