### ISSUE TITLE
create dialog does not create a callid in the notifi package

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1574]
In order to be able to create the global variable I need in the dialog, I used the create dialog function before INVITE
`        if (is_method("INVITE"))
        {
                create_dialog();
                if (has_totag())
                {
                        fix_nated_contact();
                        xlog("lua => Re-INVITE ==> (FUSER=$fu)\n");
                        lua_exec ("core","Re-INVITE");
..........................................................
`
When an INVITE arrives, the create dialog function creates an INVITE with a new callid type:
Call ID: DLGCH_fkdTXmN4YGp.MFRefXpgfXxCS19icQ--
Dialogue packages, including REFER, contain a new callid, but the NOTIFY request does not receive a new callid when it arrives, and as a result, it does not work as expected. I tried to add create dialog before REFER and NOTIFI but it doesn’t affect in any way. What do I need to do to get a new callid in the existing dialog for the NOTIFY package?
Сreate dialog is currently only used in the INVITE code above.

**Comment by bogdan-iancu** [comment]
@ilyinvv, could you post a pcap showing the inbound and outbound SIP packets (relative to OpenSIPS) ?

**Comment by ilyinvv** [comment]
Yes, of course, the work scheme of the UA -> OPENSIPS -> Asterisk -> OPERSIPS -> UA
[85.12.253.12.cap.zip](https://github.com/OpenSIPS/opensips/files/2739461/85.12.253.12.cap.zip)

**Comment by ilyinvv** [comment]
Good day!
Please help with NOTIFY now the question is very acute, thanks in advance!
The crux of the problem: When using the dialog creation function, NOTIFY does not receive the CALL-ID dialog
create dialog installed before INVITE, INVITE dialog packages, 100Tryning, 200 sdp, ACK, BYE, CANCEL, REFER  get the dialogue notif no
SOS! HELP

**Comment by bogdan-iancu** [comment]
Duplicated by #1603
