### ISSUE TITLE
mid_registrar no "Received" field with saved contacts

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#1580]
Hi all,

OpenSIPS 2.4.3. Cluster with 2 nodes - Active/Passive both are running. Clusterer, mid_registrar, nathelper.
Registrars are asterisk servers. All usrloc data in memory, no db.
```
modparam("usrloc", "nat_bflag", "NATTED_CLIENT")
modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "location_cluster", 1)
modparam("usrloc", "shared_pinging", 0)

loadmodule "nathelper.so"
modparam("nathelper", "natping_interval", 40)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "natping_partitions", 8)
modparam("nathelper", "natping_tcp", 1)
modparam("nathelper", "sipping_bflag", "SIP_PING_FLAG")
modparam("nathelper", "remove_on_timeout_bflag", "KILL_ZOMBIES")
modparam("nathelper", "sipping_from", "sip:pinger@sip.proxy.com")
modparam("nathelper", "received_avp", "$avp(received_nh)")

modparam("mid_registrar", "mode", 2)
modparam("mid_registrar", "outgoing_expires", 1800)
modparam("mid_registrar", "received_avp", "$avp(received_nh)")
modparam("mid_registrar", "extra_contact_params_avp", "$avp(extra_ct_params)")
modparam("mid_registrar", "tcp_persistent_flag", "TCP_PERSISTENT")
```
In script I add parameter to Contact field:
```
$avp(extra_ct_params) = ";x-proxy";
  if ($af == "INET") {
    mid_registrar_save("location");
  } else if ($af == "INET6") {
    mid_registrar_save("location_inet6");
  } else {
    sl_send_reply("403", "Call cannot be served here");
  };
```
I have strange issue.
Suddenly in logs I see errors:
```
Jan  1 11:58:21 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
Jan  1 11:58:36 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
Jan  1 11:58:36 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
```
Then nathelper starts deleting endpoints, trying to access them by their local IP:
```
Jan  1 11:58:26 proxy02 /usr/sbin/opensips[6453]: ERROR:nathelper:msg_send: send() to 192.168.44.117:59150 for proto tls/3 failed
Jan  1 11:58:36 proxy02 /usr/sbin/opensips[6436]: ERROR:tm:msg_send: send() to 10.50.0.63:3077 for proto tls/3 failed
Jan  1 11:59:04 proxy02 /usr/sbin/opensips[6444]: ERROR:nathelper:msg_send: send() to 192.168.4.127:54050 for proto tls/3 failed
```
I temporary disabled nathelper ping, so it stops deleting endpoints.
Then I checked these endpoints and they have no "Received" field at all:
```
AOR:: 202
                Contact:: sip:202@192.168.0.13:2054;transport=tls Q=1
                        ContactID:: 1220686605250556165
                        Expires:: 3006
                        Callid:: 313534353337333537363438373836-djckbebmpky0
                        Cseq:: 4
                        User-agent:: snom300/8.7.5.44
                        State:: CS_NEW
                        Flags:: 0
                        Cflags:: KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT TCP_NO_NEW_CONN
                        Socket:: tls:<proxy02_ip>:5061
                        Methods:: 7999
                        SIP_instance:: <urn:uuid:69608780-f467-4e2c-858c-0004134914FD>
```
They have all the flags according to NAT, but no "Received" field. That's why OpenSIPS can't contact them. It tries to use local IP of phone. And I checked on Asterisk, they also have no Contact parameter ";x-proxy".
So these phones are registered, then deleted from OpenSIPS usrloc, but as TLS connection alive, phone still thinks, that it registered fine. So phones are registered again after 1 hour etc. But of course they can't be called.
Normal record:
```
AOR:: 216
                Contact:: sip:216@10.10.152.100:2054;transport=tls Q=1
                        ContactID:: 4573968371548315309
                        Expires:: 3051
                        Callid:: 313533393531363136383138373533-rk0t8sreqkdr
                        Cseq:: 568
                        User-agent:: snom320/8.7.5.44
                        Received:: sip:1XX.36.1.126:1459;transport=tls
                        State:: CS_NEW
                        Flags:: 0
                        Cflags:: KILL_ZOMBIES SIP_PING_FLAG NATTED_CLIENT TCP_NO_NEW_CONN
                        Socket:: tls:<prixy02_ip>:5061
                        Methods:: 7999
                        SIP_instance:: <urn:uuid:124889ce-057d-4252-8a90-0004134DEC85>
```

This issue is only for about 30-50 random phones from total amount about 1200. All others are working without problem. And before issue proxy was running fine for 2 weeks. I noticed, that all errors with mid_registrar are from one process PID 6501.
And the most strange thing. Issue is resolved when I stop Backup server. Then I enable nathelper ping - it deletes these Contact records from usrloc. After 1 hour they are reregister, but like all the other phones - with "Received" field. Then I start Backup server, it syncs from Active, and everything continue working.
While running cluster, I got this issue several times.
I didn't restart OpenSIPS, so all the same processes still run. So may be I can collect more info, but don't know where to dig.

**Comment by bogdan-iancu** [comment]
@vasilevalex , do you do `fix_nated_register()` before calling the save() in midregistrar ?

**Comment by vasilevalex** [comment]
Hi @bogdan-iancu , yes of course.
I have this code:
```
if (nat_uac_test("59")) {
  if (is_method("REGISTER")) {
    fix_nated_register();
    setbflag(NATTED_CLIENT);
  } else {
    fix_nated_contact();
    setflag(NATTED_CLIENT);
  }
}
```
and only later mid_registrar_save();
And `NATTED_CLIENT` is saved for these phones (as you can see in first message)
I have more than thousand phones working fine, including this temporary failed registrations. As I mentioned, now they work as they should.

**Comment by liviuchircu** [comment]
Am I correct in assuming that this code:

```
$avp(extra_ct_params) = ";x-proxy";
  if ($af == "INET") {
    mid_registrar_save("location");
  } else if ($af == "INET6") {
    mid_registrar_save("location_inet6");
  } else {
    sl_send_reply("403", "Call cannot be served here");
  };
```

is only called in a natural way -- for initial requests only? (just trying to exclude all "weird" scenarios).  If yes, then the only explanation for these errors:

```
Jan  1 11:58:21 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
Jan  1 11:58:36 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
Jan  1 11:58:36 proxy02 /usr/sbin/opensips[6501]: ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)
```

... is that the AVP list is gone! (so `pv_get_avp()` [returns early](https://github.com/OpenSIPS/opensips/blob/master/pvar.c#L2012)).  This "missing AVP list" theory also fits with the other error (`contact.received` is set to `NULL`), since the reply processing code also [digs for](https://github.com/OpenSIPS/opensips/blob/master/modules/mid_registrar/save.c#L1057) the "received" AVP.  If it cannot find it, the "received" field [is reset to NULL](https://github.com/OpenSIPS/opensips/blob/master/modules/usrloc/ucontact.c#L256).

Are you able to obtain a network capture of the registrations which clear the `received` field, so we validate this theory?  Alternatively, if you could apply it, I could also provide a debugging patch.

**Comment by vasilevalex** [comment]
Hi @liviuchircu . Yes, code with mid_registrar_save is only in initial request route. And your explanation with empty AVP list looks like the most probable reason.
I can't capture traffic for these problem registrations, because now everything works fine. But I'm 99% sure, that SIP for them absolutely normal. Because all of them is hardware phones the same as others. And problem disappeared without rebooting/reconfiguring/etc phones.

When I had an issue, I didn't restart opensips (so I still has the same processes running). I've just stopped Passive server in cluster. So cluster synchronization was stopped. After that mid_registrar started saving records with "Received" field. And these errors `ERROR:mid_registrar:get_extra_ct_params: skipping extra Contact params with int value (0)` disappeared. After couple hours I started Passive server. And till now everything works like it should.
Can it be that AVP list cleared accidentally during cluster sync?
As I noticed, it was only 1 process of 16 tcp_children, which reported errors. It seems that errors were only for those phones, which had established TCP sessions with this PID. When phone re-registered, it was using the same session.

Please don't close issue. I'll record tcpdump when I'll get it next time.

**Comment by liviuchircu** [comment]
[Here](https://gist.github.com/liviuchircu/7259610147cc797e5d0d76f8efc9ed8b) is a patch which will make it easier to dig through the pcap.  From what I understood so far, it takes a while before the issue is reproduced.

**Comment by liviuchircu** [comment]
Note: make sure to apply it on **latest** 2.4.

**Comment by vasilevalex** [comment]
@liviuchircu Just want to say, that I built OpenSIPS with patch and it is running without reload more than a month, from 08.01.2019. Still no issues.

**Comment by vasilevalex** [comment]
Hi @liviuchircu . This happened again. About 5% of phones were affected. I have 16 opensips processes, so I still think that in this issue involved only one opensips process. Suddenly in logs we got a lot of such messages (from yours patch):
```
Apr  6 11:16:44 proxy02 /usr/sbin/opensips[6636]: INFO:mid_registrar:get_extra_ct_params: AVP not found, ci: 313533393230363239363430313631-lmbpeu8lflim
Apr  6 11:16:44 proxy02 /usr/sbin/opensips[6521]: INFO:mid_registrar:mid_reg_pack_ci: AVP not found, ci: 313533393230363239363430313631-lmbpeu8lflim
Apr  6 11:16:51 proxy02 /usr/sbin/opensips[6534]: ERROR:nathelper:msg_send: send() to 10.59.30.32:41929 for proto tls/3 failed
...
Apr  6 11:18:09 proxy02 /usr/sbin/opensips[6636]: INFO:mid_registrar:get_extra_ct_params: AVP not found, ci: 313535333234353531363137353638-omo7tf5yxdyu
Apr  6 11:18:09 proxy02 /usr/sbin/opensips[6636]: INFO:mid_registrar:get_extra_ct_params: AVP not found, ci: 313535333234353531363137353638-omo7tf5yxdyu
Apr  6 11:18:09 proxy02 /usr/sbin/opensips[6523]: INFO:mid_registrar:mid_reg_pack_ci: AVP not found, ci: 313535333234353531363137353638-omo7tf5yxdyu
Apr  6 11:18:09 proxy02 /usr/sbin/opensips[6628]: ERROR:nathelper:msg_send: send() to 192.168.13.100:38621 for proto tls/3 failed
```

**Comment by vasilevalex** [comment]
Hi @liviuchircu This issue still very annoying, we created zabbix alert, which looks for messages in logs from your patch. And if we have too much, I know that we have problem. Today I made coredump of process which produced these messages. I hope it can help to find the reason. It is 1,5 Gb, but I can put it somewhere for you to analyse.

**Comment by vasilevalex** [comment]
It is not so often, but Issue still happens.

**Comment by vasilevalex** [comment]
up

**Comment by vasilevalex** [comment]
Hi @liviuchircu , what about new patch for logging? I'd be glad to find the reason of these annoying errors.

**Comment by liviuchircu** [comment]
thank you for the bump, @vasilevalex , I hope to have it done by Friday

**Comment by vasilevalex** [comment]
Hi @liviuchircu , thanks for the patch. The problem is, that errors happen only on production servers. But I'll check it and will try to apply to one server in the cluster.

**Comment by liviuchircu** [comment]
I just made a small edit to the patch, so the history doesn't get dumped in reverse order.  Make sure you grab "v2" :)

**Comment by liviuchircu** [comment]
@vasilevalex Thank you for the debug logs -- they were just enough to pinpoint the issue.  I suggest we close this ticket for now.  If similar symptoms still persist, we can update the debugging patch and then put it in place again.

Cheers!

**Comment by vasilevalex** [comment]
@liviuchircu Thank you for the fix. I'll build it and test, if it helps. Will write here.

**Comment by vasilevalex** [comment]
Hi @liviuchircu . Your fix works fine. There are no AVP errors for two weeks. Thanks a lot!
