### ISSUE TITLE
Opensips TCP worker segfault 

### ISSUE THREAD

**Issue by Steph-Brown** [OpenSIPS/opensips#1585]
Version installed: 2.4.3~20181128~9d32492-1

Over a 24 hour period one of our telephony servers had two issues, the first resulted in 35GB of data being written to opensips.log in a matter of hours, and the second was the box segfaulting the following morning. 

The initial issue was in relation to the opensips edge having issues with talking to the RTPengines:

Jan 11 13:23:21 2TELINTESBCP02 [opensips-edge][1506]: ERROR:rtpengine:send_rtpe_command: can't read reply from a RTP proxy
Jan 11 13:23:21 2TELINTESBCP02 [opensips-edge][1507]: ERROR:core:io_wait_loop_epoll: failed to remove from epoll Bad file descriptor(9)
Jan 11 13:23:21 2TELINTESBCP02 [opensips-edge][1506]: ERROR:rtpengine:send_rtpe_command: can't read reply from a RTP proxy
Jan 11 13:23:21 2TELINTESBCP02 [opensips-edge][1507]: ERROR:core:io_wait_loop_epoll: [TCP_worker] unset/bogus map (idx=217) triggered for 25 by epoll (fd=-1,type=0,flags=0,data=(nil)) -> removing from epoll
Jan 11 13:23:21 2TELINTESBCP02 [opensips-edge][1506]: ERROR:rtpengine:send_rtpe_command: can't read reply from a RTP proxy

These errors were being written thousands of times a minute to the logs, however Opensips had not marked any of its RTPengines as disabled.

Opensips was then restarted at the end of the day, which stopped the issue. There were no further errors in the logs, but the next morning the box segfaulted:

Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1619]: CRITICAL:core:handle_tcp_worker: dead tcp worker 7 (EOF received), pid 1617
Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1511]: INFO:core:handle_sigs: child process 1617 exited by a signal 11
Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1511]: INFO:core:handle_sigs: core was generated
Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1511]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1528]: INFO:core:sig_usr: signal 15 received
Jan 12 04:18:34 2TELINTESBCP02 [opensips-edge][1529]: message repeated 2 times: [ INFO:core:sig_usr: signal 15 received]

Is this an issue that has been raised before? Is there any further information you need to look into it?

**Comment by razvancrainea** [comment]
@Steph-Brown yes, that's the right place to raise this issue.
I see that you have a coredump generated. Can you open it with `gdb` and send us the output of `bt full`?

**Comment by Steph-Brown** [comment]
Hi Razvan, I'm afraid we disable generating core dumps on our servers for compliance reasons, so I don't have one to give you. Do you need this to investigate further?

**Comment by Steph-Brown** [comment]
Hi Razvan, I'm afraid we haven't enabled OpenSIPs to generate a core dump (despite what the log says!)

**Comment by Steph-Brown** [comment]
I'm closing this issue, as the same issue occurred on another node and I was able to get the stack trace @bogdan-iancu bogdan requested. Please see issue #1607 , thank you.

**Comment by Steph-Brown** [comment]
HI all,

Please can you take a look at issue #1607? We've had multiple production servers segfaulting due to this issue.

**Comment by AnjanIpc** [comment]
its bit urgent to know the fixed version number.
Can you please let me know, which version, it is fixed ??
