### ISSUE TITLE
'MYSQL' {aka 'struct st_mysql'} has no member named 'reconnect' (OpenSIPS FTBFS with MariaDB 10.3)

### ISSUE THREAD

**Issue by fauust** [OpenSIPS/opensips#1589]
Hi,
I am filling this issue, to link it to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918393 and to be sure that upstream dev are aware of it.

As explained by Sergei (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919395#36)
> error: 'MYSQL' {aka 'struct st_mysql'} has no member named 'reconnect'
> This is not a bug. MYSQL.reconnect was not part of the API, even in 5.5
> https://dev.mysql.com/doc/refman/5.5/en/c-api-auto-reconnect.html

Regards,
Faustin

**Comment by razvancrainea** [comment]
@fauust Thanks for reporting this, but this has already been resolved upstream. However, I have some problems right now pushing the fixes in the debian upstream.

**Comment by LarryMartell** [comment]
I am getting this error
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918393) building
MySQL-python. Is there a fixed 10.3 I can download for debian buster
that resolves this?

**Comment by fauust** [comment]
I @LarryMartell, as confirmed by @razvancrainea, problem comes from OpenSIPS not using correctly the MySQL API... If you are interested in mariadb 10.3 Debian specific code source, you can check the salsa repository: https://salsa.debian.org/mariadb-team/mariadb-10.3. And the upstream repo is hosted on github (https://github.com/MariaDB/server).

If you can reproduce this error on a specific Debian package that is not listed in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918393, please let me know.

**Comment by LarryMartell** [comment]
I loaded 10.3 and when building mysql-python I still get the same error:

```
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-tG19c8/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mariadb -I/usr/include/mariadb/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
    In file included from _mysql.c:44:
    /usr/include/mariadb/my_config.h:3:2: warning: #warning This file should not be included by clients, include only <mysql.h> [-Wcpp]
     #warning This file should not be included by clients, include only <mysql.h>
      ^~~~~~~
    In file included from _mysql.c:46:
    /usr/include/mariadb/mysql.h:440:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
       MYSQL_CLIENT_PLUGIN_HEADER
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    _mysql.c: In function '_mysql_ConnectionObject_ping':
    _mysql.c:2005:41: error: 'MYSQL' {aka 'struct st_mysql'} has no member named 'reconnect'
      if ( reconnect != -1 ) self->connection.reconnect = reconnect;
                                             ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```

**Comment by fauust** [comment]
@LarryMartell, you should open an issue directly on https://github.com/farcepest/MySQLdb1.
I see 2 problem here:
- header include (should only be mysql.h);
- MYSQL.reconnect was not part of the API, even in 5.5.

**Comment by fauust** [comment]
:+1:

**Comment by klahnen** [comment]
This was happening to me running debian-buster I downgrade to debian-stretch and works.
