### ISSUE TITLE
[Feature] Improve cluster "seed" mechanics

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#1591]
Following a recent [Users mailing list discussion](http://lists.opensips.org/pipermail/users/2019-January/040449.html), the "seed" concept could benefit from a subtle but very useful improvement.

Issues with the current "seed" behavior which could use improvement:
* asymmetry between seed nodes and the rest.  Seed nodes always start with an empty dataset, and require a separate sync command (e.g. `opensipsctl fifo ul_cluster_sync`) in order to pull the data into their memory caches.
* if you solely boot the single seed node of a cluster and run `opensipsctl fifo ul_cluster_sync`, it will get trapped in a `"Not Synced"` state, along with the rest of the cluster, until a full cluster restart.

The current best solution which solves the above, as per the discussion:

```
What if we kept the "seed" concept, but tweaked it such that instead of meaning:

"following a restart, always start in 'synced' state, with an empty dataset"

... it would now mean:

"following a restart or cluster sync command, fall back to a 'synced' state,
with an empty dataset or by keeping the current one (configurable) if and only if
we are unable to find a suitable sync source within X seconds"
```

**Comment by petekelly** [comment]
I would contest the empty dataset assumption - it would be nice to have this as a configurable option, so that we could choose to either 1) revert to an empty dataset OR 2) keep the current dataset in the event that we are unable to find a sync source in X seconds.

**Comment by liviuchircu** [comment]
Sounds like nothing but an improvement, @petekelly - I've updated the requirements.
