### ISSUE TITLE
include_file returning that quoted string must be in quotes

### ISSUE THREAD

**Issue by shairozan** [OpenSIPS/opensips#1592]
So I'm on an older version of opensips (1.9), but I'm curious if there's something wrong with include file / import file. 

If I add the following (per the documentation for core features in 1.9), I get an error at runtime:

`include_file "testing.cfg"`

The error I get is:

`CRITICAL:core:oss_push_yy_state: included file name must be between quotes: "proxy_regs.cfg"`

Doesn't matter if I use single quotes, double quotes, end it with a semicolon. It won't read or parse anything I've put in. Is there something I'm missing?

**Comment by razvancrainea** [comment]
You should use double quotes, and make sure your line does not end with a space or tab.

**Comment by shairozan** [comment]
Must have had a space or something after it then. When I try it here at work everything's good. I'll double check at home and also make sure I didn't add a line feed or carriage return as well. Thanks for the help :)
