### ISSUE TITLE
Failover with  t_on_failure happening after a final response

### ISSUE THREAD

**Issue by ramontelnyx** [OpenSIPS/opensips#1596]
I'm using Opensips version: opensips 2.4.4 (x86_64/linux)

I'm implementing a time out based failover as explained in "1.1.2. Timeout-Based Failover" in the tm module documentation.

I set up the parameter fr_timeout and I'm calling t_on_failure(failure_route). Per what I understand the failure route specified in t_on_failure should only be called when no final response has been received but I see this failure route is being called after a **final** response.

Please find attached a picture of the call flow (Opensips IP is 10.255.0.23) and the logs, if you need the trace I can also provide it. I believe these are the lines where the failover happens:
```
Jan 25 18:04:25 [120632] incoming reply
Jan 25 18:04:25 [120632] DBG:tm:t_should_relay_response: T_code=100, new_code=500
Jan 25 18:04:25 [120632] DBG:tm:t_pick_branch: picked branch 0, code 500 (prio=700)
Jan 25 18:04:25 [120632] DBG:tm:is_3263_failure: dns-failover test: branch=0, last_recv=500, flags=2
Jan 25 18:04:25 [120632] DBG:dispatcher:ds_next_dst: using [sip:10.15.17.5:5070]
```

[logs-opensips.txt](https://github.com/OpenSIPS/opensips/files/2797319/logs-opensips.txt)
![opensips-callflow](https://user-images.githubusercontent.com/10601798/51764791-ad3d3480-209b-11e9-8a81-1ca9e4b639a2.png)

**Comment by liviuchircu** [comment]
Hey, @ramontelnyx !

> If there is no response after fr_timeout seconds, the timer triggers (and failure route will be executed if t_on_failure() was called)

Why does this suggest to you that `failure_route` should only be called on a transaction timeout?  The [purpose](https://www.opensips.org/Documentation/Script-Routes-3-0#toc3) of `failure_route` is to indicate when a SIP transaction has failed (due to internal timeout or a 3xx/4xx/5xx/6xx reply from the downstream element).

Do you think the below wording would make the mechanism more clear for you or any other readers?

> If there is no response after fr_timeout seconds, the timer triggers (and failure route will be executed if t_on_failure() was called, similarly to a transaction failure due to a non-2xx final reply)

**Comment by ramontelnyx** [comment]
Hi Liviu,

Thanks for clarifying, I believe that wording would help. I also assumed that was the behavior because of this description "Sets reply routing block, to which control is passed after a transaction completed with a negative result but before sending a final reply". -- I was thinking about the "B-leg" side and I guess this "final reply" refers to the "A-leg"

In order to exclude the final responses from the failover I'll use the function **t_check_status** on the failure route but let me know if you have other suggestions. Thanks for your help.

**Comment by liviuchircu** [comment]
Note that the proper way to detect an internally triggered transaction timeout is:

    t_local_replied("all") && t_check_status("408")

since if you simply use `t_check_status("408")`, you will not able to discard downstream-originated 408 replies.

**Comment by ramontelnyx** [comment]
This is perfect, thanks
