### ISSUE TITLE
SIP instance not mirrored in 200ok reply for REGISTER

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#1598]
When a registration is made with "reg-id" and "+sip.instance" params, those params should be mirrored back in the 200 OK reply for REGISTER.

Example:
```
REGISTER
Contact: <sip:user@192.168.2.6>;reg-id=1;+sip.instance="<urn:uuid:1111-AABB>";expires=60
```
generates the following reply:
```
200 OK
Contact: <sip:user@192.168.2.6>;expires=60
```
The Contact in 200 OK should mirror the "reg-id" and "+sip.instance" params.

**Comment by ovidiusas** [comment]
According to the example in the rfc5626, the URI params are mirrored:
https://tools.ietf.org/html/rfc5626#section-9.2

**Comment by bogdan-iancu** [comment]
@ovidiusas , see this 

> The REGISTER messages associate Bob's SIP or SIPS URI
   (sip:bob@biloxi.com) with the machine into which he is currently
   logged (conveyed as a SIP or SIPS URI in the Contact header field).

at page 17 in RFC3261 - https://tools.ietf.org/html/rfc3261#page-17

What you mentioned here seems to be a RFC 5626 specific extension - see top page 8 - https://tools.ietf.org/html/rfc5626#page-8
