### ISSUE TITLE
Acc variables not available in failure route for cdr accounting

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1602]
If you call do_accounting() with the 'cdr' flag, accounting variables are not present in the failure route.

If you call do_accounting() with the "failed" or "missed" flags, then accounting variables are present in the failure route.

We only use 'cdr' accounting and do manual accounting of failed transactions because we record some additional items from the failure. As a work around I found that calling do_accounting() at the top of the failure route will load in the accounting context.

I think that the tmcb_func should should always get registered for TMCB_ON_FAILURE when cdr accounting is in use to load the accounting context. The tmcb_func should then only run the on_missed if the acc level flag is also enabled.

This would make the behaviour closer to the old method of accounting avp's, which would be available in all of the routes.

Let me know if that sounds reasonable, and I can work up a patch.

**Comment by bogdan-iancu** [comment]
@rrb3942 , let me recap on the *NOT* working scenario - you do do_accounting() with 'cdr' only; you also set a failure route for your INVITE. And if you get there, the $acc_extra() are not visible ??

**Comment by rrb3942** [comment]
@bogdan-iancu That is correct.

INVITE -> do_accounting("cdr") -> t_on_failure -> t_relay -> relay gets a failure response -> no $acc_extra populated in failure_route.
