### ISSUE TITLE
route process

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1604]
opensips listen at 118.31.105.208:5060
b2bua listen at 118.31.105.208:5061
b2bua send all sip message through outbound proxy opensips 

after call setup, caller UA send re-invite to callee, b2bua call leg2 generate an invite message as followed

b2bua send re-invite to opensips(with 2 routes,), request-uri is the value opensips previously
placed into a Record-Route header field

**U 118.31.105.208:5061 -> 118.31.105.208:5060**
INVITE sip:118.31.105.208 SIP/2.0.
Via: SIP/2.0/UDP 118.31.105.208:5061;branch=z9hG4bKd707f51a830d05b1aaa88e1347cf159d;rport.
Route: <sip:118.31.105.208;lr>.
Route: <sip:1001@114.216.46.237:57465;rinstance=a864958a4719a24b>.
Max-Forwards: 68.
From: <sip:5280020@118.31.105.208>;tag=b32d6fe03528f67a6d00f672b18e6dab.
To: <sip:1001@118.31.105.208>;tag=cc3c2b41.
Call-ID: .7AUjTBBAl7DqcZK.QBLcHtr0Ih4R.fa-b2b_1.
CSeq: 201 INVITE.
Contact: Anonymous <sip:5280020@118.31.105.208:5061>.
Expires: 300.
User-Agent: WOYIN B2BUA (RADIUS).
cisco-GUID: 144038770-82000818-2781517344-2244556231.
h323-conf-id: 144038770-82000818-2781517344-2244556231.
Content-Type: application/sdp.
Content-Length: 415.

**U 118.31.105.208:5060 -> 118.31.105.208:5060**
INVITE sip:1001@114.216.46.237:57465;rinstance=a864958a4719a24b SIP/2.0.
Record-Route: <sip:118.31.105.208;lr>.
Via: SIP/2.0/UDP 118.31.105.208:5060;branch=z9hG4bK7cd9.17c3bfb1.0.
Via: SIP/2.0/UDP 118.31.105.208:5061;received=118.31.105.208;branch=z9hG4bKd707f51a830d05b1aaa88e1347cf159d;rport=5061.
Route: <sip:118.31.105.208;lr>.
Max-Forwards: 67.
From: <sip:5280020@118.31.105.208>;tag=b32d6fe03528f67a6d00f672b18e6dab.
To: <sip:1001@118.31.105.208>;tag=cc3c2b41.
Call-ID: .7AUjTBBAl7DqcZK.QBLcHtr0Ih4R.fa-b2b_1.
CSeq: 201 INVITE.
Contact: Anonymous <sip:5280020@118.31.105.208:5061>.
Expires: 300.
User-Agent: WOYIN B2BUA (RADIUS).
cisco-GUID: 144038770-82000818-2781517344-2244556231.
h323-conf-id: 144038770-82000818-2781517344-2244556231.
Content-Type: application/sdp.
Content-Length: 415.

RFC3621  16.4 Route Information Preprocessing
If the Request-URI of the request contains a value this proxy previously placed into a Record-Route header field (see Section 16.6 item 4), the proxy MUST **replace the Request-URI in the request with the last value from the Route header field**, and **remove that value from the Route header field**.
 
**[problem]**
loose_route replace request-uri with value <sip:1001@114.216.46.237:57465;rinstance=a864958a4719a24b>
but have not  remove Route: <sip:118.31.105.208;lr>.

the opensips's configuration for loose_route 
######## Sequential Requests Section ########
	if (has_totag()) {
		# sequential requests within a dialog should
		# take the path determined by record-routing
		if (loose_route()) {
			xlog("##has_totag - loose_route [$rm]");
			if (is_method("BYE")) {
				# do accunting, even if the transaction fails
				#do_accounting("log","failed");
			} else if (is_method("INVITE")) {
				# even if in most of the cases is useless, do RR for
				# re-INVITEs alos, as some buggy clients do change route set
				# during the dialog.
				record_route();
			}
			# route it out to whatever destination was set by loose_route()
			# in $du (destination URI).
			route('relay');
		} else {
			if ( is_method("ACK") ) {
				if ( t_check_trans() ) {
					# non loose-route, but stateful ACK; must be an ACK after
					# a 487 or e.g. 404 from upstream server
					#t_relay();
					route('relay');
					#xlog("Relay $rm to $du");
					exit;
				} else {
					# ACK without matching transaction ->
					# ignore and discard
					xlog("error ack ,discard");
					exit;
				}
			}
			sl_send_reply("404","Not here");
		}
		exit;
	}

so is it a bug or i make a mistake ?

**Comment by bogdan-iancu** [comment]
I think OpenSIPS acts correctly - it takes the URI from the last Route and remove that Route (the last one) - this is per RFC, according to your quote.
As a result, only one Route hdr (the one on top) will be preserved in the request.

Nevertheless, the B2B does a lousy job in generating the re-INVITE, in terms of filling in the RURI and the Route hdr - why same IP:port in RURI and top Route ?? but of course, to correctly judge it, I need to see the initial request / 200 reply it gets and how RR+Contact headers are populated there

**Comment by bogdan-iancu** [comment]
@futsystems , any update here ? otherwise I will close this ticket in the following days
