### ISSUE TITLE
mid_registrar doesn't set correct contact host when using advertised_address global or per bind socket

### ISSUE THREAD

**Issue by italorossi** [OpenSIPS/opensips#1619]
This makes impossible to use mid_registrar at AWS for example or any other environment with 1:1 NAT.

advertised_address="X.X.X.X" neither
listen=udp:X.X.X.X:5060 AS X.X.X.X:5060

Works, looks like this commits is a good reference (pointed by @liviuchircu) 
https://github.com/OpenSIPS/opensips/commit/7bafce982b1c7a24160

And we may need to poke with uri2sock. I spoke with @liviuchircu and I'm opening this issue for reference.

**Comment by bogdan-iancu** [comment]
I don't think the issue has anything to do with the `uri2sock` function - it only returns the socket; it is up to the code that uses it to pick (from the `struct socket_info`) the advertised component or not (or the global advertised if defined).

**Comment by italorossi** [comment]
Just a note:

I did a few debugging and looks like the socket returned by uri2sock doesn't have the correct adv address there. So maybe need to dig a little big in the socket creation.

I spent a very low time on this and I may be looking at the wrong place...

For now, I'm running it outside AWS, I'll try to get some time next week to work on this but I think @liviuchircu will work on it next week
