### ISSUE TITLE
mid_registrar : LM_ERR on "no record found for" isn't it a bit excessive ?

### ISSUE THREAD

**Issue by StellaTeam** [OpenSIPS/opensips#1620]
Hello,

mid_registrar_lookup() is one of the first and main tests we have to do when using mid_registrar, in order to know if the requested device is known or not, and how to behave with the requester.

But, not to find the requested registration in the database is not forcibily an error, the register may have expired or the database can have been reset by an opensips restart and requester continue to check...

For example:
- if opensips is between a device and asterisk
- if the device has register once, then, with `qualify=yes` , asterisk will try to poke it forever with "OPTIONS" messages.
- If opensips has been restarted since the first register, contact is no more in memory, but that's not really an error, that's only a "not found" event
Unfortunately, in this case, logs are filled for nothing...

Wouldn't it be better to consider this event as a LM_ALERT/INFO/NOTICE message and the script writer do decide if that is really an error?

Thank you!

**Comment by bogdan-iancu** [comment]
@StellaTeam , why is the contact lost after restart ? don;t you use a DB for restart persistence (similar to regular registrations) ?

**Comment by StellaTeam** [comment]
hi @bogdan-iancu 
For now i'm still only using RAM database, so contacts are losts.
Anyway, is a contact not found in database really an error? Said another way, when is it necessary, except while debugging, to know that a contact is not found in mid_registrar database?
Thank you
