### ISSUE TITLE
Blind/Attended Transfers Issues

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1621]
Hello

I am using latest OpenSIPs 2.4 on Centos 7 as a multi homed mid registrar with Topology Hiding in front of an Asterisk.

During deployment I found few issues that I thing that they should be resolved.

1. In-Dialog NOTIFYs do not matched by topology hiding match function which resulted REFER not to work. Work around was to remove C flag from topology hiding.

2. By removing C flag, didn't fully resolve the issue because topology hiding match function didn't match the dialog again, hence I had to add dialog match function in combination with topology hiding match function in order to route correct.
ie if(topology_hiding_match() || match_dialog())

3. Topology Hiding does not work correct on SUBSCRIPTION. My script is executing topology_hiding before forward SUBSCRIPTION to Asterisk but the contact header sent was the initial one.

4. Doing above changes, Blind Transfer worked as expected but Attended didn't. The reason for that was sanity check. I am using Snom Phone Firmware v10 for testing and the REFER on attended transfer looks like this

REFER sip:1.1.1.1;did=9fa.44dd0321 SIP/2.0
Via: SIP/2.0/UDP 2.2.2.2:43984;branch=z9hG4bK-uco48gbim9mf;rport
From: <sip:3702@domain>;tag=ldn4539zq7
To: <sip:2120005300@domain>;tag=as700b813c
Call-ID: 40dba7f9502a2e520a8a8a3666b003c3
CSeq: 2 REFER
Max-Forwards: 70
User-Agent: snomD785/10.1.15.1
Contact: <sip:3702@2.2.2.2:43984;line=fz10cpcg>;reg-id=1
Refer-To: sip:3703@domain;user=phone?Replaces=313535313238323533353435323836-t8m3rkhpsbq7%3Bto-tag%3Das42b83e12%3Bfrom-tag%3Dq51tgcbmju
Referred-By: sip:3702@domain
Authorization: Digest username="3702",realm="domain",nonce="6087f250",uri="sip:1.1.1.1;did=9fa.44dd0321",response="fe7efd3ac546df4c0d6fbde28a05c808",algorithm=MD5
Content-Length: 0

which does not pass sanity check, hence I had to disable it in order to work.

opensips -V
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e64b117
main.c compiled on 21:23:12 Feb 25 2019 with gcc 4.8.5

**Comment by bogdan-iancu** [comment]
@apsaras , there are multiple things reported here, so let's try to take them one by one. I suggest starting with the simpler things like (2) - TH without 'C'. In this case you say the in-dialog requests (REFER + NOTIFY ?) do not match the dialog ? could you provide a pcap + OpenSIPS logs in debug level (corresponding to the full call from pcap) ?

**Comment by bogdan-iancu** [comment]
@apsaras - do you have any follow up here ? If not, I will close the ticket

**Comment by bogdan-iancu** [comment]
On more ping :)

**Comment by apsaras** [comment]
Sorry for the delay. Too busy :-) . Let me fire up the Lab box and I will reply on that during the weekend.

**Comment by bshirazi** [comment]
> 
> 
> @apsaras , there are multiple things reported here, so let's try to take them one by one. I suggest starting with the simpler things like (2) - TH without 'C'. In this case you say the in-dialog requests (REFER + NOTIFY ?) do not match the dialog ? could you provide a pcap + OpenSIPS logs in debug level (corresponding to the full call from pcap) ?

Hi
There is a pcap file here in discussing similar problem in irontec tiny SBC project based on  opensips:
[https://github.com/irontec/itsbc/issues/8](url)
