### ISSUE TITLE
opensips consumes a lot of memory

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1622]
Good day!
opensips 2.4.4 is running in a docker container with the following memory settings:
children = 4
S_MEMORY = 3072
P_MEMORY = 512
1. Why when setting equal to children = 4, the number of opensips processes is equal to 18?
2. Why does all processes consume a little more than 350MB at the initial start-up, but during further operation within 24 hours, the opensips process memory consumption increases to 1.5GB?

**Comment by razvancrainea** [comment]
1. Because you might have different opensips listeners, some for udp, some for tcp, others for bin, etc. Also, the attendant, timer processes are always present, and if you are using `mi_fifo` (or any other MI module), those will fork processes for themselves too. You can find out the purpose of each process by running `opensipsctl ps`
2. This I cannot answer, unless you describe the type of traffic you are doing. Also, if you stop the traffic, does the memory recover?

**Comment by ilyinvv** [comment]
thanks for the answer on the processes, I understood, from memory the type of traffic udp to stop traffic until I can, here is the output after working for 24 hours, top and shmem, the system is not heavily loaded, in the location of 126 contacts, packet processing, the server plays the role of a registrar, respectively a lot of pings.
Is it possible to view the consumption of memory by a specific module in an open-ended mode?
![top](https://user-images.githubusercontent.com/45192944/53591321-8780df00-3bb5-11e9-8d57-d3d53cc52434.png)
:
opensipsctl fifo get_statistics shmem
shmem:total_size:: 3221225472
shmem:used_size:: 3382784
shmem:real_used_size:: 3701112
shmem:max_used_size:: 4547592
shmem:free_size:: 3217524360
shmem:fragments:: 10645

**Comment by bogdan-iancu** [comment]
Let's do some math, starting from 
S_MEMORY = 3072
P_MEMORY = 512
procs = 16
The overall memory requested by OpenSIPS from the operating system is 3072 + 512*16 = 11264 , ~11Gb
So, if OpenSIPS would actually use all the memory you configured for it, it would end up using ~11Gb. But the operating system is smart and dynamically maps real memory to OpenSIPS only when OpenSIPS start actually using it. This is why you see a small footprint after startup and larger one after doing traffic (and forcing OpenSIPS to use part of the memory it has assigned).
