### ISSUE TITLE
Consultation on Ping Options and API

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1623]
Good day!
I have Opensips version 2.4.4 configured and I use the HTTPD and MI_JSON modules I successfully get to use the fifs command of the ps type using an http request. I faced the task of sending the options package, the interaction for sending is supposed to be performed using the http request, the problem is that I don’t find the fifo command to send the ping options, while I can execute the ping options using the following commands:
./opensipsctl ping uri
it works successfully
How can I send ping options using http request and HTTPD and MI_JSON modules?

**Comment by bogdan-iancu** [comment]
@ilyinvv , see the [t_uac_dlg](http://www.opensips.org/html/docs/modules/2.4.x/tm.html#mi_t_uac_dlg) MI command - you can use it to make OpenSIPS sending any request.
