### ISSUE TITLE
fix_route_dialog() function setting incorrect $du in reinvites. 

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#1625]
I've discovered what looks like a problem with the fix_route_dialog function from the dialog module.

I have a call scenario which runs like this:

UACa --> OpenSIPSa --> FreeSWITCH --> OpenSIPSa --> UACb

UACa and UACb are behind the same NAT, as such when they REGISTER fix_nated_register is used, likewise fix_nated_contact for other requests.

I am using record_route() and dialog module when proxying the requests to/from FreeSWITCH and the UACs. By default I am calling validate_dialog and fix_route_dialog() when an in-dialog request is received.

However it seems that once an in-dialog request has been processed (successfully) in one direction (either UACa > UACb or UACb -> UACa), then any subsequent in-dialog requests on the *opposite* direction will fail.

I have narrowed this down to the fix_route_dialog() function changing the $du to be the original (before nat fixup) $du of the UAC, causing OpenSIPS to send the request to an un-routable address.

I have a minimal config file and pcaps (attached) which demonstrate this - the "notbroken" shows the call flow working without the dialog module (see frames 70, and 72), the "broken" shows that when dialog+fix_route_dialog is introduced the call flow breaks (see frames 74 and 76).

The only "oddity" I can see is that there are UPDATE messages generated from FreeSWITCH as soon as the calls are established.. perhaps the dialog is changing internally the Contact IP of one of the UACs when it receives the 200OK from this update? 

OpenSIPS version is:
```
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6c6c513f2
main.c compiled on 10:48:07 Feb 28 2019 with gcc 6.3.0
```

[notbroken.tar.gz](https://github.com/OpenSIPS/opensips/files/2925763/notbroken.tar.gz)
[broken.tar.gz](https://github.com/OpenSIPS/opensips/files/2925764/broken.tar.gz)

**Comment by razvancrainea** [comment]
Hi, Pete!

OpenSIPS definitely updates the contact of the UAC when an UPDATE is sent. Ideally, this contact should not change, unless you really want to do that (for example when changing networks and IPs). This doesn't seem to be the case though.
I was wondering if you could try to run `fix_nated_contact()` *before* `loose_route()` and `fix_route_dialog()` and see if this is resolved.
You can also check how the contact changes by running `opensipsctl fifo dlg_list_ctx` before and after the Update.

**Comment by petekelly** [comment]
Hi Razvan!

Yes adding a fix_nated_contact() *before* `loose_route()` fixes the problem but it seems ugly?

I reverted the fix and then checked the `dlg_list_ctx`. After the first re-invite the Contact address is changed to the local IP - even though `fix_nated_contact()` has been called for every request and response that has happened previously in the dialog.

Should the dialog module not automatically take the `fix_nated_contact()` contact and store that?

**Comment by razvancrainea** [comment]
Well, it should, but apparently it doesn't :)
I will do some review on the code to see why is this happening.

**Comment by razvancrainea** [comment]
Hey, Pete!

I've just pushed a fix for this issue. Any chance you could give it a try as well, before I backport it to the older versions?

Cheers,
