### ISSUE TITLE
drouting: Allow goes_to_gw in ONREPLY_ROUTE

### ISSUE THREAD

**Issue by farmorg** [OpenSIPS/opensips#1628]
While developing my opensips.cfg I needed to make routing decisions based on both the source and destination gateways.
Since goes_to_gw is not usable in ONREPLY_ROUTE I needed to match on $rd in order to work out the destination IP, like this:

`if (is_from_gw("1") && $rd !~"^(172\.*)") {`

In this case, goes_to_gw would have been very useful instead of $rd because I could then add entries for other subnets in the dr_gateways table instead of needing to alter the script.

EG: `if (is_from_gw("1") && goes_to_gw("2")) {`

Thanks for reading.

**Comment by bogdan-iancu** [comment]
How do you want to use goes_to_gw() in a reply route, as time as the function tests a RURI (to see if it points to a GW), but a reply does not have a RURI ??

**Comment by farmorg** [comment]
I see your point, thanks for pointing that out.

My thinking was that it would be useful to have a dynamic method of matching the destination IP address against database entries and goes_to_gw() seemed to make sense. Maybe I should have asked the mailing list first, apologies.

**Comment by bogdan-iancu** [comment]
You can still use goes_to_gw() to match the destination of a request (against DB), but not for replies. Theoretically you should not do any such tests for replies as you can do all the possible tests (src and dst) at request time - and the reply is just going backward :)
Let me know if we can close this

**Comment by farmorg** [comment]
Yes that's fine. Thanks.
Clearly I have much more learning ahead. Thanks for the pointer.
