### ISSUE TITLE
append_to_reply() does not work with t_newtran() + t_reply_with_body()

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1632]
I am calling append_reply() with some headers before t_reply_with_body(), but the headers are not being added to the actual reply.

Example:
                append_to_reply("Content-Type: application/sdp\r\n");
                t_reply_with_body("200", "OK", "$var(body)\r\n");
                exit;

If I replace the call to t_reply_with_body() to t_reply() the headers are added.

This is on 2.4.5.

I found this related commit: https://github.com/OpenSIPS/opensips/commit/783a18a8df4b8e9dcfd147ec0c63caceeeaa7bb9
So I wonder if something else needs to be done in the message cloning to get the reply lumps apply?

**Comment by bogdan-iancu** [comment]
I just tested with a request route like this:

> append_to_reply("Content-Type: application/sdp\r\n");
> append_to_reply("Foo: bar\r\n");
> $var(body) = "text 1 2 3";
> t_reply_with_body("200", "OK", "$var(body)\r\n");
> exit;

and the headers and the body were properly added in the reply.

**Comment by rrb3942** [comment]
Hmm. I didn't have much time Friday to narrow this down, but some more testing this morning shows that it may be an interaction with something else.

If I just reply to an initial invite without any other manipulations the headers are added in the reply. The exact scenario I am testing is actually on a Re-Invite, and we are also doing topology hiding. This scenario is definitely not appending headers correctly. I'll do some more testing to see if I can figure out what triggers it.

**Comment by rrb3942** [comment]
Got it, if you call t_newtran() before t_reply_with_body() the extra headers do not get applied.

t_newtran();
append_to_reply("Content-Type: application/sdp\r\n");
append_to_reply("Foo: bar\r\n");
$var(body) = "text 1 2 3";
t_reply_with_body("200", "OK", "$var(body)\r\n");
exit;

Didn't seem to matter if I put the append_to_reply before or after t_newtran(). Either way the replies did not have the added headers.

I don't think this is an invalid use case? If you replace t_reply_with_body() with t_reply(), the headers are added.

I'm going to review if I actually need to call t_newtran() in my script.

**Comment by bogdan-iancu** [comment]
Many thanks @rrb3942 - I managed to identify the bug and fix it. The fix is already on the git, enjoy it

**Comment by eschmidbauer** [comment]
was this bug fix back ported?
im experiencing the same issue with 2.4.7

**Comment by razvancrainea** [comment]
@eschmidbauer yes, the fix was pushed in the 2.4 branch in commit 16b47f0, on 12nd of March 2019 and released in OpenSIPS 2.4.6. Therefore 2.4.7 should already have the fix.
Are you sure you're experiencing the same issue? Could you please open a new request with a detailed report?

**Comment by eschmidbauer** [comment]
not exactly same issue. `append_to_reply()` is not working if it's called before `remove_hf()` inside a onreply_route block

**Comment by razvancrainea** [comment]
`append_to_reply()` should be called in the context of a request to append that header to all replies of that request. If you just want to add a header to a reply, use the `append_hf()` function.
