### ISSUE TITLE
[BUG] AVPs in local_route to not affect TLS settings

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#1642]
**OpenSIPS version you are running**
```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 09:17:11 Mar 22 2019 with gcc 4.8.5
```

**Describe the bug**
I want to control client TLS connections from OpenSIPS and we have avp exactly for this purpose:
`modparam("tls_mgm", "client_domain_avp", "tls_cli_dom")`
But when I do like this:
```
local_route { 
  if (is_method("OPTIONS")) { 
    # Get IP for outgoing socket 
    $var(ip_out) = $(fs{s.select,1,:}); 
    switch($var(ip_out)) { 
      case "IP1": 
        $avp(tls_cli_dom) = "test1"; 
      break; 
      case "IP2": 
        $avp(tls_cli_dom) = "test2"; 
      break; 
    } 
    xlog("AVP for TLS:  $avp(tls_cli_dom) \n"); 
  } 
}
```
OpenSIPS uses default TLS domain for all connections.

**To Reproduce**
Example:
1. Set any avp in local_route
2. try to catch it later

**Expected behavior**
AVP should be accessible after leaving local_route

**Relevant System Logs**
```
DBG:tls_mgm:tls_find_client_domain: no TLS client domain AVP set, looking to match TLS client domain by socket
DBG:tls_mgm:tls_find_client_domain_addr: virtual TLS client domain not found, Using default TLS client domain settings
```

**OS/environment information**
 - Operating System: CentOS 7
 - OpenSIPS installation:  `git branch 2.4`
 - other relevant information:

**Additional context**
I think, this is because of code in modules/tm/uac.c (start from line 299):
https://github.com/OpenSIPS/opensips/blob/be8d3a8f0e8c959630ae7b626497834e114925a2/modules/tm/uac.c#L299
First, we store to `backup` AVPs from new transaction, then execute local_route, than restore `backup`. Of course all AVP changes will be lost.
If we just move 299 line after executing local_route
https://github.com/OpenSIPS/opensips/blob/be8d3a8f0e8c959630ae7b626497834e114925a2/modules/tm/uac.c#L306
So everything starts working like expected. But I'm not sure about correctness of the code. Why we set AVP list for new transaction before local_route and then restore it?
I need help.

**Comment by bogdan-iancu** [comment]
@vasilevalex , you can use AVPs in local route with no problem.  The actual issue here is that the AVPs you set in the local route do not affect the SIP routing (and the TLS layer). This is because the actual SIP message sending is done outside the context of the local route (you do not have any explicit t_relay() or similar here, like you have in the request route).

**Comment by bogdan-iancu** [comment]
@vasilevalex , try this fix please and see if it addresses your issue.

[avps_local_route_patch.txt](https://github.com/OpenSIPS/opensips/files/3007417/avps_local_route_patch.txt)

**Comment by vasilevalex** [comment]
Thanks, @bogdan-iancu ! It works. TLS client domain is selected by AVP from local_route.

**Comment by bogdan-iancu** [comment]
Thanks @vasilevalex for the confirmation, the fix was uploaded on all maintained versions.
