### ISSUE TITLE
[BUG] WARNING:core:hp_shm_free: free(0) called

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1646]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b76f587
main.c compiled on 13:37:39 Mar 26 2019 with clang 4.2.1
```

**Describe the bug**

Seemingly random, I am getting the following warning in my logs during call handling:
WARNING:core:hp_shm_free: free(0) called

I went ahead and recompiled with DBG_MALLOC and added a logging line right before this message:
Mar 26 14:05:17 testing /usr/sbin/opensips[15903]: WARNING:core:hp_shm_free: shm_free((nil)), called from dlg_hash.c: free_dlg_dlg(193)
Mar 26 14:05:17 testing /usr/sbin/opensips[15903]: WARNING:core:hp_shm_free: free(0) called
Mar 26 14:05:17 testing /usr/sbin/opensips[15903]: WARNING:core:hp_shm_free: shm_free((nil)), called from dlg_hash.c: free_dlg_dlg(194)
Mar 26 14:05:17 testing /usr/sbin/opensips[15903]: WARNING:core:hp_shm_free: free(0) called

Lines 193 and 194 in dlg_hash.c in function free_dlg_dlg are the shm_free below:
                for( i=0 ; i<dlg->legs_no[DLG_LEGS_USED] ; i++) {
                        **shm_free(dlg->legs[i].tag.s);**
                        **shm_free(dlg->legs[i].r_cseq.s);**

Everything else in this block is wrapped with a check before calling shm_free(). 

**To Reproduce**

Not entirely sure. I try making calls with a mix of answering, cancelling quickly, etc and sometimes I see this message. I have a capture at this timestamp that has an INVITE, 100 Trying, and a 503 about a second later before route advancing. These logs would potentially correlate to either the INVITE or 100 Trying.

Wrapping the shm_free in a check would remove the warning, but I can't reason if it would just be masking a symptom of a deeper issue.

**Expected behavior**

No warnings in logs.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Centos 7
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
As a side note, it seems that the `shm_free(dlg->legs[i].tag.s);` code is expected to not run into a `NULL` value on the average case, hence it runs faster, on average, if we omit the `if`.  The other fields are usually the exception - in that case, adding the `if` actually makes the code faster.

Regardless of what we do at the app level, all allocators should happily accept `NULL` and stay quiet.
