### ISSUE TITLE
OpenSIPS 2.4: SNMPstats agent not working

### ISSUE THREAD

**Issue by solarmon** [OpenSIPS/opensips#1649]
**OpenSIPS version you are running**

```
2.4
```

**Describe the bug**

Similar to https://github.com/OpenSIPS/opensips/issues/1306 I can't seem to get snmpstats agent to work.

Copied MIBs:

```
/usr/local/src/opensips_2_4/modules/snmpstats/mibs/* /usr/share/snmp/mibs/
```

opensips.cfg:

```
loadmodule "snmpstats.so"
modparam("snmpstats", "sipEntityType", "proxyServer")
modparam("snmpstats", "snmpgetPath", "/usr/bin/")
```

snmpd.conf:

```
master agentx
agentXSocket tcp:localhost:705
```

snmpstats.conf:

```
agentXSocket tcp:localhost:705
```

After restarting snmpd and opensips services:

```
# netstat -tanp | grep snmp
tcp        0      0 127.0.0.1:199           0.0.0.0:*               LISTEN      26608/snmpd
tcp        0      0 127.0.0.1:705           0.0.0.0:*               LISTEN      26608/snmpd
```

using the test:

snmpd -f -Dagentx -x tcp:localhost:705 2>&1 | less

shows only:

```
registered debug token agentx, 1
Log handling defined - disabling stderr
```

snmpwalk test:

```
snmpwalk -O s -v 2c -c <community-string> localhost OPENSER-SIP-COMMON-MIB::openserSIPCommonObjects
```

shows:
```
openserSIPCommonObjects = No Such Object available on this agent at this OID
```

**To Reproduce**

**Expected behavior**

The snmpstats agent output from '''snmpd -f -Dagentx -x tcp:localhost:705 2>&1 | less''' should be similar to as per:

https://opensips.org/html/docs/modules/2.4.x/snmpstats.html#idp5564816

**Relevant System Logs**

**OS/environment information**
 - Operating System: CentOS 7.6.1810 
 - OpenSIPS installation: git 
 - other relevant information:

**Additional context**

In snmpd.log:

```
agentx_register_app_config_handler: registering .conf token for "agentxsocket"
agentx_register_app_config_handler: registering .conf token for "agentxperms"
agentx_register_app_config_handler: registering .conf token for "agentxRetries"
agentx_register_app_config_handler: registering .conf token for "agentxTimeout"
Turning on AgentX master support.
agentx/config: port spec: tcp:localhost:705
Error opening specified endpoint ""
Server Exiting with code 1
```

**Comment by solarmon** [comment]
Hi, any progress on this issue?

**Comment by bogdan-iancu** [comment]
@solarmon , I will try to put together a SNMP setup to test your report

**Comment by bogdan-iancu** [comment]
We still need to test this, re-assigning the task.

**Comment by solarmon** [comment]
Any updates on this?

**Comment by rvlad-patrascu** [comment]
Hi @solarmon 
The snmpd service should not be already running before you start it manually with `snmpd -f -Dagentx -x tcp:localhost:705 2>&1 | less`.

**Comment by solarmon** [comment]
@rvlad-patrascu 

I believe this is what I did do, but I have just tested again.

I stopped snmpd - `systemctl status snmpd` shows:

```
 â snmpd.service - Simple Network Management Protocol (SNMP) Daemon.
Loaded: loaded (/usr/lib/systemd/system/snmpd.service; enabled; vendor preset: disabled)
Active: inactive (dead) since Tue 2019-11-12 15:08:09 GMT; 1min 14s ago
Process: 5546 ExecStart=/usr/sbin/snmpd $OPTIONS -f (code=exited, status=0/SUCCESS)
Main PID: 5546 (code=exited, status=0/SUCCESS)
```

and I run `snmpd -f -Dagentx -x tcp:localhost:705` 

```
registered debug token agentx, 1
Log handling defined - disabling stderr
```

In another ssh session to the same host I run the query:

```
snmpwalk -O s -v 2c -c <community> localhost OPENSER-SIP-COMMON-MIB::openserSIPCommonObjects
```
and I get the following response:

```
openserSIPCommonObjects = No Such Object available on this agent at this OID
```
And nothing on being outputted to the snmpd session

Just to prove that snmpd is running and working:, I did the following snmpwalk query:

```
# snmpwalk -O s -v 2c -c <community> localhost sysUptime
sysUpTimeInstance = Timeticks: (26937) 0:04:29.37
```

**Comment by rvlad-patrascu** [comment]
In `snmpd.conf` make sure the line `rocommunity public  localhost` is not commented out. Also, in `snmp.conf`, add the following lines: 
`mibs +OPENSER-MIB`
`mibs +OPENSER-REG-MIB`
`mibs +OPENSER-SIP-COMMON-MIB`
`mibs +OPENSER-SIP-SERVER-MIB`
`mibs +OPENSER-TC`
Then, try snmpget or snmptable on an individual scalar or table.

**Comment by solarmon** [comment]
I had already change the community from 'public' to our requirements, and I know it is working as I have to provide that community string for the query to get a response.

I did already have the first four MIBs added, but was missing OPENSER-TC, so I've added this.

I tried the following snmpget query:
```
snmpget -O s -v 2c -c <community> localhost openserSIPProtocolVersion.0
```

and get the following response:

```
openserSIPProtocolVersion.0 = No Such Object available on this agent at this OID
```

It just looks like either the MIB is not loaded or the agent and or opensips is not working for some reason.

How can I verify on the opensips side that it the snmp module is loaded and working as expected?

**Comment by solarmon** [comment]
I also tried the full OID path:

```
snmpget -O s -v 2c -c <community> localhost OPENSER-SIP-COMMON-MIB::openserSIPProtocolVersion.0
openserSIPProtocolVersion.0 = No Such Object available on this agent at this OID
```

**Comment by rvlad-patrascu** [comment]
In the OpenSIPS logs, you should see: `NET-SNMP version 5.7.3 AgentX subagent connected` or otherwise and error or warning from the snmp library.

**Comment by solarmon** [comment]
Thanks.

I restarted the opensips module and checked the logs and was getting the following for the snmpstats module:

```
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:mod_init: Starting up the SNMPStats Module
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: Can't find ul_bind_usrloc
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: failed to register for callbacks with the USRLOC module.
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: openserSIPContactTable and openserSIPUserTable will be unavailable

 /usr/local/sbin/opensips[9873]: INFO:snmpstats:spawn_sysUpTime_child: An snmpCommunity parameter was not provided.  Defaulting to public
```
 
I realised I was missing the community string configuration in opensips.cfg - so I added it and used the same community string as I used for snmpd.conf:

 modparam("snmpstats", "snmpCommunity", "<community>")

This resolved the community string error. However, I'm still getting the following in opensips.log:

```
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:mod_init: Starting up the SNMPStats Module
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: Can't find ul_bind_usrloc
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: failed to register for callbacks with the USRLOC module.
 /usr/local/sbin/opensips[9842]: INFO:snmpstats:registerForUSRLOCCallbacks: openserSIPContactTable and openserSIPUserTable will be unavailable
```

What does this mean and how can I troubleshoot/resolve it?

**Comment by rvlad-patrascu** [comment]
This means that the 'usrloc' module was not loaded, but it shouldn't be any issue if you are not using the registrations and contacts related statistics.

**Comment by solarmon** [comment]
I'm still getting the same SNMP error response:

```
# snmpget -O s -v 2c -c <community> localhost openserSIPProtocolVersion.0
openserSIPProtocolVersion.0 = No Such Object available on this agent at this OID
```

**Comment by rvlad-patrascu** [comment]
So at this point you no longer see anything suspicious in the opensips logs?

**Comment by solarmon** [comment]
There is no other snmptstats log entries and I do not see a log entry for ```NET-SNMP version 5.7.3 AgentX subagent connected``` after running ```snmpd -f -Dagentx -x tcp:localhost:705```.

The only time I get any logs for 'AgentX' is when I restart the opensips service:

```
 /usr/local/sbin/opensips[29983]: INFO:core:shutdown_opensips: process 2(29991) [SNMP AgentX] terminated, still waiting for 21 more
 /usr/local/sbin/opensips[29983]: INFO:snmpstats:mod_destroy: Shutting down the AgentX Sub-Agent!
```

**Comment by solarmon** [comment]
When I use snmptranslate to check if the MIBs have been loaded, it does indicate that they are:

```
# snmptranslate -On OPENSER-REG-MIB::openser
.1.3.6.1.4.1.27483
```

```
snmptranslate -Dinit_mib .1.3.6.1.4.1.27483
registered debug token init_mib, 1
init_mib: Seen MIBDIRS: Looking in '/root/.snmp/mibs:/usr/share/snmp/mibs' for mib dirs ...
init_mib: Seen MIBS: Looking in ':HOST-RESOURCES-MIB:HOST-RESOURCES-TYPES:UCD-DISKIO-MIB:TCP-MIB:UDP-MIB:MTA-MIB:NETWORK-SERVICES-MIB:SCTP-MIB:RMON-MIB:EtherLike-MIB:LM-SENSORS-MIB:SNMPv2-MIB:IF-MIB:IP-MIB:NOTIFICATION-LOG-MIB:DISMAN-EVENT-MIB:DISMAN-SCHEDULE-MIB:UCD-SNMP-MIB:UCD-DEMO-MIB:SNMP-TARGET-MIB:NET-SNMP-AGENT-MIB:SNMP-MPD-MIB:SNMP-USER-BASED-SM-MIB:SNMP-FRAMEWORK-MIB:SNMP-VIEW-BASED-ACM-MIB:SNMP-COMMUNITY-MIB:IPV6-ICMP-MIB:IPV6-MIB:IPV6-TCP-MIB:IPV6-UDP-MIB:IP-FORWARD-MIB:NET-SNMP-PASS-MIB:NET-SNMP-EXTEND-MIB:UCD-DLMOD-MIB:SNMP-NOTIFICATION-MIB:SNMPv2-TM:NET-SNMP-VACM-MIB:OPENSER-MIB:OPENSER-REG-MIB:OPENSER-SIP-COMMON-MIB:OPENSER-SIP-SERVER-MIB:OPENSER-TC' for mib files ...
init_mib: Seen PREFIX: Looking in '.1.3.6.1.2.1' for prefix ...
OPENSER-REG-MIB::openser
```

**Comment by solarmon** [comment]
You mentioned the log message ```NET-SNMP version 5.7.3 AgentX subagent connected```. However, I'm using NET-SNMP 5.7.2 - does that make a difference?

**Comment by rvlad-patrascu** [comment]
It should not. Are you sure though that opensips does not connect to the snmp master agent? (check with `sudo netstat -tanp | grep :705`)

**Comment by solarmon** [comment]
```netstat -tanp | grep :705``` only shows that the SNMP service is listening on TCP 705:

```
# netstat -tanp | grep :705
tcp        0      0 <IP Address>:705       0.0.0.0:*               LISTEN      2065/snmpd
```

What I don't see in the SNMP and OpenSIPS logs are indications that OpenSIPS is trying to connect to it.

You mentioned the ```NET-SNMP version 5.7.3 AgentX subagent connected``` message - which logs should that be seen in?

**Comment by Bosco1105** [comment]
I have the same issue, everything I set is following the document, but always get "No more variables left in this MIB View (It is past the end of the MIB tree)" or openser: Unknown Object Identifier (Sub-id not found: (top) -> openser)
