### ISSUE TITLE
[BUG] Invalid Load statistics reported

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1650]
**OpenSIPS version you are running**

```
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 52ff74af8
main.c compiled on 22:24:12 Mar 22 2019 with gcc 7
```

**Describe the bug**

We are using OpenSIPS 2.4.4 and have implemented some alerts and automated actions for scaling focusing on the OpenSIPS Load statistic. According to the documentation [1] “the load is defined as percentage of time spent in doing processing versus total time.” However we are doing high traffic testing and seeing OpenSIPS consistently reporting load values well over 100, which is not valid for a percentage.

**To Reproduce**

1. Start OpenSIPS
2. Start high traffic
3. Query Load statistics
4. Observe load values >100

**Expected behavior**

A statistic that is a percentage should be reported between 0 and 100 at all times.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Amazon Linux 2
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bcnewlin , if I provide you with a patch for extra logging (that will dump the statistic sampling window) when the value is above 100%, would you run it on your system ?

**Comment by bcnewlin** [comment]
Yes, absolutely.

Ben

**Comment by bogdan-iancu** [comment]
BTW, the issue was observer for the per-process load or for the overall-load ?

**Comment by bcnewlin** [comment]
That would have been good for me to include from the beginning. :)

In my testing it was actually restricted to the "all" statistics, specifically the load1m-all and load10m-all.

**Comment by bogdan-iancu** [comment]
Hi @bcnewlin 
While checking the code I found a bug related to how the `1m` stats are computed in some cases (see af4d8479d3e2902019a9d209690362075c9120d9). 
Still, I don't think the above fix addresses all the problems (affecting different types of load stats). So, I made an auto-debugging patch (committed only on master, as a2460ee) - attached is the patch for 2.4 - [load_dbg_2_4.patch.txt](https://github.com/OpenSIPS/opensips/files/3202530/load_dbg_2_4.patch.txt).
If you run the patch, if something out-of-scale values are detected, some extensive reported (as BUG) is done at syslog without stopping or affecting OpenSIPS - just logging. Could you give it a try to see if it catches something ?
Thanks, Bogdan

**Comment by bogdan-iancu** [comment]
Hi @bcnewlin , any chances to get a run of this patch ?

**Comment by bcnewlin** [comment]
Apologies, I am on vacation. I will check next week.

Ben

**Comment by bcnewlin** [comment]
@bogdan-iancu If this has been closed per @liviuchircu 's fix mentioned above do you still need me to test running your patch?

**Comment by bogdan-iancu** [comment]
No , no need to run my patch. Just update and validate @liviuchircu 's fix.

**Comment by bcnewlin** [comment]
Was the fix patched back to 2.4? We are not ready to upgrade to 3.0 just yet.

**Comment by liviuchircu** [comment]
Yes, [it was](https://github.com/OpenSIPS/opensips/commit/60097425d0de465fbc3866b13146b851935e26e6), @bcnewlin :)

**Comment by bcnewlin** [comment]
Thanks!
