### ISSUE TITLE
[CRASH] OpenSIPS crashes since of child that serves rtpproxy

### ISSUE THREAD

**Issue by zenichev** [OpenSIPS/opensips#1652]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 17:14:18 Mar 19 2019 with gcc 7
```

**Crash Core Dump**

**Describe the traffic that generated the bug**

I have a setup with three SBCs working simultaneously, and traffic is balanced to them using DNS.
The problem is that I migrated from 2.1 branch to 2.4.5 (that is latest LTS) and have started to experience some weird issues with crash of child that serves rtpproxy service.

Why I think it's rtpproxy, is because the PID with which rtpproxy starts working, matches the PID that is set as dead child in the last CRITICAL row. So like this:
```
Mar 29 09:55:09 <some_name> opensips[24108]: INFO:rtpproxy:rtpp_test: rtp proxy </var/run/rtpproxy/rtpproxy.sock> found, support for it enabled
Mar 29 10:02:48 <some_name> opensips[24108]: CRITICAL:core:sig_usr: segfault in process pid: 24108, id: 35
Mar 29 10:02:48 <some_name> opensips[24136]: CRITICAL:core:handle_worker: dead child 35 (EOF received), pid 24108
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:core:handle_sigs: child process 24108 exited by a signal 11
```
And this is a constant thing, so each time opensips crashes, child that crashed, has PID of rtpproxy service process (not sure how to describe this better, but I hope it's descriptive for you).

**To Reproduce**

1. Start OpenSIPS 2.4.5 on 18.04.2 LTS
2. Start rtpproxy with version 2.2.alpha.2af612e (the one taken from master branch of the rtpproxy git project).
3. Start obtaining a traffic, especially traffic that time-outs sessions by absence of sound for a while (no audio and BYE generated with help of rtpp_notify_socket).
4. Get a crash

**Relevant System Logs**

```
Mar 29 10:02:48 <some_name> opensips[24136]: CRITICAL:core:handle_worker: dead child 35 (EOF received), pid 24108
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:core:handle_sigs: child process 24108 exited by a signal 11
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:core:handle_sigs: core was generated
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:core:handle_sigs: terminating due to SIGCHLD
Mar 29 10:02:48 <some_name> opensips[24071]: INFO:core:sig_usr: signal 15 received
Mar 29 10:02:48 <some_name> opensips[24073]: INFO:core:sig_usr: signal 15 received
Mar 29 10:02:48 <some_name> opensips[24072]: INFO:core:sig_usr: signal 15 received
Mar 29 10:02:48 <some_name> opensips[24075]: INFO:core:sig_usr: signal 15 received
Mar 29 10:02:48 <some_name> opensips[24074]: INFO:core:sig_usr: signal 15 received
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:core:cleanup: cleanup
Mar 29 10:02:48 <some_name> opensips[24064]: NOTICE:cachedb_redis:destroy: destroy module cachedb_redis ...
Mar 29 10:02:48 <some_name> opensips[24064]: INFO:pike:pike_exit: destroying...
Mar 29 10:02:48 <some_name> opensips[24064]: NOTICE:event_route:destroy: destroy module ...
```

**OS/environment information**
 - Operating System: `Ubuntu 18.04.2 LTS`
 - OpenSIPS installation: `official opensips git`
 - other relevant information: rtpproxy version `2.2.alpha.2af612e` - strange that it contains 'alpha' mark, since it's taken from official rtpproxy master branch.

**Additional context**

What I think of, is that it's somehow related to timed out sessions since of no audio for quite a while within a certain dialog.
Why I consider this version, is because the timestamp for the last update of rtpp_notify_socket file, matches a time of child's crashing.
So it has something to do with it.

This is rtpproxy module configuration
```
loadmodule "rtpproxy.so"
modparam("rtpproxy", "rtpproxy_sock", "/var/run/rtpproxy/rtpproxy.sock")
modparam("rtpproxy", "rtpp_notify_socket", "/var/run/rtpproxy/rtpproxy_timeout.sock")
modparam("rtpproxy", "rtpproxy_autobridge", 1)
modparam("rtpproxy", "nortpproxy_str", "")
```

Thanks for your attention and let me know if I can add something else.
Sorry that there is no core dump right now, I can add this if it's relevant.

**Comment by razvancrainea** [comment]
I see that OpenSIPS reports that a core dump was generated - can you inspect that corefile and send us the backtrace?

**Comment by zenichev** [comment]
@razvancrainea  unfortunately seems that opensips  has written to the standard input of that program instead of to a file, I cannot find a coredump. I will specify "-w" option to get an exact place for core dumps.

**Comment by zenichev** [comment]
@razvancrainea here is a backtrace, please take a look:
https://drive.google.com/open?id=1lpOvGF_7H0psjpElmGkrPtOe4xF4bjNY

**Comment by zenichev** [comment]
@razvancrainea and one more:
https://drive.google.com/open?id=1PqfH2yE2PKyw1iVCXtH9qhqiPj6VDkIj

**Comment by zenichev** [comment]
@razvancrainea sorry for disturbing you, but I'm experiencing really huge problems now since of that, could you be so kind and at least hint where to look into?

**Comment by razvancrainea** [comment]
Can you run in debug mode?
Also, are you using clustering support?

**Comment by zenichev** [comment]
@razvancrainea you mean to run openSIPS with log_level=4  and debug_mode=yes ?
no I don't use any cluster support.

**Comment by razvancrainea** [comment]
Just `log_level-4`, no `debug_mode`.
In the meantime, I found a bug that might have caused the issues that generated the corefile. However, they are not related to the rtpproxy process, so there might be a different issue in there.

**Comment by zenichev** [comment]
@razvancrainea Is it related to nathelper? 

Alright I will enable log_level4 and will see if this works out.
Let me know which  gmail address you have, so I can share a log file only for you.
Thanks!

**Comment by razvancrainea** [comment]
I've just committed a fix on master and 2.4 branch. Can you pull the latest sources and try again, and confirm if this was fixed or not?
You can send your logs at razvan at opensips.org.

**Comment by zenichev** [comment]
@razvancrainea alright! Will check this out soon and will report.

**Comment by zenichev** [comment]
@razvancrainea I recompiled all SBCs yesterday and seems to be working fine since that.
But not 100% sure, because not that much time left. I'll report today in the evening as well, just in case!

Thanks for the job done!

**Comment by zenichev** [comment]
@razvancrainea All seems to be working fine, sorry for so late response.
I will close this ticket.

Please let me know if possible, whether this bug could have affection on NAT pings over TCP?
I had a sporadic problem just before this one, when OpenSIPS was crashing when tried to ping remote host (with OPTIONS) over TCP transporting.

**Comment by razvancrainea** [comment]
Yes, this could have happened for TCP pinging as well.
