### ISSUE TITLE
contact related issue in mid_registrar 

### ISSUE THREAD

**Issue by vipulpatel310** [OpenSIPS/opensips#1653]
We are trying to setup opensips-2.4 for our existing environment in which we used freeswitch as a proxy and registrar server. Now, we want to make opensips as a mid registrar and freeswitch will be our main registrar. For that we decide to used mid_registrar module in opensips but we are facing two issue.

Our environment will be:

- Opensips have a two interface: 
    1. Private IP interface, 
    2. Public IP interface (as an advertised addres)
    
- freeswitch have only private interface

- Here, Opensips and freeswitch can direct comminication in private network

- In mid_registrar configuratuion:
    modparam("mid_registrar", "mode", 1)
    modparam("mid_registrar", "outgoing_expires", 120)
    
    if (is_method("REGISTER"))
    {
            #fix_nated_contact();
            #remove_hf("Contact");
            #append_hf("Contact: <sip:$tU@$si:$sp>\r\n");

            mid_registrar_save("location");
            switch ($retcode) {
                    case 1:
                            xlog("L_INFO", "forwarding REGISTER to main registrar...\n");
                            $ru = "sip:OUR_FREESWITCH_IP:OUR_FREESWITCH_PORT";

                            if (!t_relay()) {
                                    send_reply("500", "Server Internal Error 1");
                            }

                            break;
                    case 2:
                            xlog("L_INFO", "REGISTER has been absorbed!\n");
                            break;
                    default:
                            xlog("L_ERR", "mid-registrar error!\n");
                            send_reply("500", "Server Internal Error 2");
            }

            exit;
    }
    
    if (is_method("INVITE") and $si == OUR_FREESWITCH_IP and $sp == OUR_FREESWITCH_PORT) {
        if (!mid_registrar_lookup("location")) {
                t_reply("404","Not Found");
                exit;
        }

        if (!t_relay())
                send_reply("500", "Server Internal Error 3");
            exit;
        }
    }

    
We are facing two issue in this situation
1. SIP user is in public and it send register request to opensips which will save user contact detail and forward that request with modification. Opensips update it public ip in contact but as per our need, it should be a private ip in contact cause freeswitch is in private network. 
2. In case of behind NAT user's register request, mid_registrar_save() function store the local location of user instead of publically available. So that we used fix_nated_contact but it can't club with  mid_registrar_save(). 

Please suggest on above issue

**Comment by liviuchircu** [comment]
Try using `set_advertised_address()` with the private IP address before relaying to FS. The mid registrar will pick it up and include it in the contact header.
