### ISSUE TITLE
[BUG] Wrong To tag on CANCEL response

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1655]
**OpenSIPS version you are running**

```
bash-4.2# opensips -V
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 52ff74af8
main.c compiled on 17:29:16 Mar 28 2019 with gcc 7
```

**Describe the bug**

When OpenSIPS matches an incoming CANCEL request to an INVITE transaction, it automatically sends the "200 canceling" reply. This reply contains always a new To tag value generated by OpenSIPS and doesn't not use any previously received To tag value from the INVITE transaction. Sometimes the 487 response also contains the new To tag, but also sometimes contains the original To tag.

**To Reproduce**

1. Start OpenSIPS
2. Place a call and cancel the call after ringing. The attached SIPp scenarios can also be used.
3. Capture traces of SIP messaging
4. Verify the "200 canceling" response contains a new To tag generated by OpenSIPS
5. Verify the 487 response may contain either the new To tag or the original request To tag.

**Expected behavior**

If a To tag has already been set in a response to the original request, the 200 response to the CANCEL and the 487 response to the original request should use that To tag as tags should not be changed within a transaction.
Per RFC 3261, Section 16.7:
```
An element SHOULD preserve the To tag when simply forwarding a 3-6xx response to a request that did not contain a To tag.
```
Per RFC 3261, Section 9.2:
```
Regardless of the method of the original request, as long as the CANCEL matched an existing transaction, the UAS answers the CANCEL request itself with a 200 (OK) response.  This response is constructed following the procedures described in Section 8.2.6 noting that the To tag of the response to the CANCEL and the To tag in the response to the original request SHOULD be the same.  The response to CANCEL is passed to the server transaction for
transmission.
```

**Relevant System Logs**

[CANCEL Tag.zip](https://github.com/OpenSIPS/opensips/files/3031062/CANCEL.Tag.zip)
I am attaching SIPp scenarios that reproduce the issue, as well as a PCAP of the messages with the tags. Our architecture contains 2 layers of OpenSIPS, one which is a transactional proxy and one using Dialog and Topology Hiding. The call flow for the INVITE is

SIPp (203.0.113.4) -> OpenSIPS (TM only) (203.0.113.2) -> OpenSIPS (Dialog) (203.0.113.3) -> OpenSIPS (TM only) (203.0.113.2) -> SIPp (203.0.113.5)

You can see in the trace that the 180 reply contains a To tag and is proxied through all OpenSIPS instances. However, when the CANCEL is received each instance creates a new To Tag for the response instead of using the existing tag.

For the 487, the first OpenSIPS proxy receives the 487 and proxies it with the To tag unchanged, however the rest of the OpenSIPS instances all change the To tag in the 487 to the one used in the CANCEL reply.

**OS/environment information**
 - Operating System: Amazon Linux 2
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by wdoekes** [comment]
For the hop-by-hop CANCEL, I don't think it is wrong to generate a fresh To by the TM module.

Consider a forking proxy: two or more 1xx responses with different To-tags will have been forwarded. Now OpenSIPS gets a CANCEL and replies immediately: which of the two forwarded To-tags should it use? A fresh one as far as I'm concerned.

I think for a stateful proxy, you shouldn't be reading section 9.2. That is, you should stop reading after this bit:
```
   The processing of a CANCEL request at a server depends on the type of
   server.  A stateless proxy will forward it, a stateful proxy might
   respond to it and generate some CANCEL requests of its own, and a UAS
   will respond to it.  See Section 16.10 for proxy treatment of CANCEL.
```
Which is before your quoted bit, which concerns an UAS.

> For the 487, the first OpenSIPS proxy receives the 487 and proxies it with the To tag unchanged, however the rest of the OpenSIPS instances all change the To tag in the 487 to the one used in the CANCEL reply.

That however, appears wrong. If there is no b2bua in between, OpenSIPS should not mangle any existing To-tags. (Although you say you're using Topo Hiding, which changes the matter.)

In short:
```
CANCEL sip:+15552340000@203.0.113.2:5060;transport=TCP;user=phone SIP/2.0
Via: SIP/2.0/TCP 203.0.113.4:8060;rport=36699;received=203.0.113.4;branch=z9hG4bK-1-01
From: "INVITE" <sip:+15554560000@203.0.113.4>;tag=15SIPpTag31
To: sip:+15552340000@203.0.113.2:5060
Call-ID: OB_CANCEL-40///1-15@203.0.113.4
CSeq: 1 CANCEL
Max-Forwards: 70
Content-Length: 0

SIP/2.0 200 canceling
Via: SIP/2.0/TCP 203.0.113.4:8060;received=203.0.113.4;rport=36699;received=203.0.113.4;branch=z9hG4bK-1-01
From: "INVITE" <sip:+15554560000@203.0.113.4>;tag=15SIPpTag31
To: sip:+15552340000@203.0.113.2:5060;tag=7980237320740c0c2b81412bf3e2ec07-9277
Call-ID: OB_CANCEL-40///1-15@203.0.113.4
CSeq: 1 CANCEL
Content-Length: 0
```
^- I think that is okay

```
SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 203.0.113.4:8060;rport=36699;received=203.0.113.4;branch=z9hG4bK-1-01
Record-Route: <sip:203.0.113.2:5060;du=203.0.113.3:6060;ftag=15SIPpTag31;lr;r2=on>,<sip:203.0.113.2:5060;transport=tcp;ftag=15SIPpTag31;lr;r2=on>
From: "INVITE" <sip:+15554560000@203.0.113.4>;tag=15SIPpTag31
To: sip:+15552340000@203.0.113.2:5060;tag=7SIPpTag112
Call-ID: OB_CANCEL-40///1-15@203.0.113.4
CSeq: 1 INVITE
Content-Length: 0

SIP/2.0 487 Request Terminated
Via: SIP/2.0/TCP 203.0.113.4:8060;received=203.0.113.4;rport=36699;branch=z9hG4bK-1-01
From: "INVITE" <sip:+15554560000@203.0.113.4>;tag=15SIPpTag31
To: sip:+15552340000@203.0.113.2:5060;tag=7980237320740c0c2b81412bf3e2ec07-9277
Call-ID: OB_CANCEL-40///1-15@203.0.113.4
CSeq: 1 INVITE
Content-Length: 0
```
^- but this is not okay.

Is it the topology hiding that's breaking things? Can you check?

**Comment by bcnewlin** [comment]
@wdoekes I agree with your assessment on both points. I realize that using the existing To tag is not always achievable in the case of forking, but in my case there is no forking so it seems like a reasonable default would be to use the existing To tag to avoid confusion. But the changing of the To tag between responses within the INVITE transaction seems to be the real bug.

**Comment by bogdan-iancu** [comment]
Hi guys! my 2 cents on the matter, without diving in the darkness of the RFC3261. Let's start from two given facts:
1) An UAC **MUST** be ready to accept multiple TO-tags in the early/final stage of the transaction, in order to cop with serial and parallel forking 
2) The TO-tag must reflect the end-point which generated the reply (like in parallel/serial forking, each UAS end-point will generate its own TO-tag)

Now, putting things together - isn't the proxy/OpenSIPS yet another UAS point in the transaction, so entitled to generate its own TO-tag? After all the `200 canceling` is a reply generated by OpenSIPS (and not by the UAS) and this should be reflected by the TO-tag ?

If we use the (re) use in the `200 canceling` the same TO-tag as the one received from final UAS (which generated an `183` let's say), from the UAC perspective, both `200 Cancel` and `183 INVITE` would have been generated by the same UAS, which is totally wrong.

Again, my 2 cents on this.

**Comment by wdoekes** [comment]
> After all the 200 canceling is a reply generated by OpenSIPS (and not by the UAS) and this should be reflected by the TO-tag ?

Yes. I agree with both your points.

That doesn't explain the altered To-tag in the 487 though. Although I haven't seen that behaviour myself. Perhaps @bcnewlin can create a minimal routing script so we can reproduce.

**Comment by bogdan-iancu** [comment]
Within the same dialog, a final UAC (end point) MUST use the same To-tag . Have you came across something different ?

**Comment by bogdan-iancu** [comment]
The replies you mentioned (180 and 487) are both generated by sipp (.5:7060) - am I right on this ?

**Comment by wdoekes** [comment]
@bcnewlin: I'll let you answer that.

**Comment by bcnewlin** [comment]
The logical endpoint of the call is a SIPp server, so yes the 180 and 487
were generated originally by SIPp. However the messages in the capture are
after passing through an OpenSIPs instance, as I noted. The messages were
sent from SIPp with the same to-tag; it is OpenSIPs which changed the
to-tag in the 487 to match the one it generated for the CANCEL. I can
provide a SIPp scenario which reproduces, but I am on vacation so it will
be next week.

Ben

**Comment by bogdan-iancu** [comment]
@bcnewlin, there is something weird with .3 server. As the trace shows, the .2 OpenSIPS is perfectly mirroring the 487 reply (in both cases). But .3 OpenSIPS (which does TH also) doesn't.
First take a look at frame 30 versus 28 - they do look almost identical (except VIA), showing a reply relaying by TM.
Now look at frame 32 versus 30 - they look completely different - less headers, stripped body, etc. This tells me the 487 was not relayed, but a 487 was locally generated by OpenSIPS, replacing the incoming one. Are you sure you do not do any t_reply(487) in your failure route in .3 OpenSIPS ??? This will explain the behavior.

**Comment by bcnewlin** [comment]
Ah, I think you may have found it. I believe we did add a t_relay call in
that case. I will confirm when I return next week.

Ben

**Comment by bogdan-iancu** [comment]
I guess you mean `t_reply`, not `t_relay`, right ?

**Comment by bcnewlin** [comment]
Sorry, yes. It's hard to type on mobile. :)

Ben

**Comment by bcnewlin** [comment]
Removing the explicit call to t_reply for the 487 reply resolved the issue.
