### ISSUE TITLE
[BUG] Opensips 2.4.x does not connect  to mongodb ReplicaSet

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1656]
**OpenSIPS 2.4.5**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 17:22:29 Mar 23 2019 with gcc 5.4.0

```

**Describe the bug**
Opensips 2.4.x doesn't connect to MongoDB ReplicaSet.

**To Reproduce**
```
loadmodule "usrloc.so"
modparam("usrloc", "location_cluster", 2)
modparam("usrloc", "cluster_mode", "full-sharing-cachedb")
modparam("usrloc", "cachedb_url", "mongodb://IP1:27017,IP2:27017,IP3:27017/opensipsDB.userlocation2?replicaSet=myReplicaSet")
```

**Expected behavior**
According to https://docs.mongodb.com/manual/reference/connection-string/
we should be able to connect with the following uri format : 
```
mongodb://mongodb0.example.com:27017,mongodb1.example.com:27017,mongodb2.example.com:27017/DBNAME?replicaSet=myReplicaSet
```

We should also be able to pass to the uri string all mongodb connection options :
https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options

**Relevant System Logs**
```
ERROR:cachedb_mongodb:mongo_con_update: last error: 15.13053: No servers yet eligible for rescan
```
Also it seems that usrloc tries to to lookup to wrong DB/table which means that OpenSIPs doesn't recognize the correct db connection options uri format.
```
DBG:cachedb_mongodb:mongo_con_query: find all in opensipsDB.userlocation2?replicaSet=opensips24_edge_v1
```

**OS/environment information**
 - Operating System: Description:	Ubuntu 16.04.6 LTS
 - OpenSIPS installation: Source

**Additional context**
When changing the config with just the Primary MongoDB Node of the cluster :
```
modparam("usrloc", "cachedb_url", "mongodb://IP1:27017/opensipsDB.userlocation2")
```
everything is working fine. Is there anything that I am missing here or OpenSIPs doesn't support MongoDB replicaSet yet?

Best Regards
Vasilios Tzanoudakis

**Comment by liviuchircu** [comment]
Hi Vasilios!

Indeed, the current version seems to lack support for the extra options part (`"?replicaSet=..."`).  However, specifying multiple comma-separated `host[:port]` elements should work.  I am not entirely sure without testing for myself that the driver will properly handle failover to the next CSV node without having a `?replicaSet` hint in the URL.

Will take care of this asap, and also backport to `2.4`.

**Comment by vtzan** [comment]
Hi @liviuchircu!

Thank you for you response. Specifying multiple comma-separated host[:port] elements is not going to work in a MongoDB ReplicaSet. In Replica setup the mongo client lib asks Mongos to find the Primary node and by default writes and reads from the Primary Node.  (unless the parameters we are talking about are set to read from other nodes of the Cluster)

But just for fun I have already tried your proposal and it didn't worked out.The logs are saying : 
```
ERROR:cachedb_mongodb:mongo_con_update: last error: 15.13053: No servers yet eligible for rescan
[15769]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1000 ms (now 2980 ms), it may overlap..
[15769]: WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 1000 ms (now 3970 ms), it may overlap..
ERROR:usrloc:cdb_flush_urecord: cache update query for AoR XXXXXX@domain failed!
```

The multiple comma-separated host[:port] elements I found out that they are sending requests in parallel mode. Enabling this mode even with 2 separate Master Mongo Servers(Non Cluster) I always get many many logs like this and writes are not working either: 
 
`WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 980 ms (now 2960 ms), it may overlap..`

The (multiple comma-separated host[:port] feature) might be interesting where you can just have 3 separate (non-Cluster mode) MongoDBs and be able to send requests to 3 nodes one by one, and what I mean is this : try to write in First Local DB first and then asynchronously (without blocking the script) send writes to the remain 2 nodes for backup purposes.
The same for Reading side (user lookup). Try to read from the First (Local Node) and if user not found or node is unreachable try to read from the second nodes. I know this is not the best Solution for many reasons but might be a good approach for some cases. 
But this (multiple comma-separated host[:port] elements) is also not working right now as mentioned so I think fixing the MongoDB extra options part is the best approach right now and then why not make a feature to be able to read/write user location from other Secondary noSQL or Mysql DBs too as a failover solution. (You can use the virtualDB module for this feature)

So looking forward for the extra MongoDB options part. 
Let me know if I can help more regarding this feature.

Best Regards
Vasilios Tzanoudakis

**Comment by liviuchircu** [comment]
@vtzan, please re-open if you have any more problems related to replica set interactions
