### ISSUE TITLE
[BUG] cachedb_cassandra - when parameters are set, OpenSIPS doesn't start

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1658]
**OpenSIPS version you are running**
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 17:22:29 Mar 23 2019 with gcc 5.4.0

**Describe the bug**
When setting cachedb_cassandra parameters, OpenSIPS doesn't start.
When setting just 

`loadmodule "cachedb_cassandra.so"
modparam("cachedb_cassandra", "cachedb_url","cassandra:userdata://IP3:9042/userdatakeyspace.userdata")`

OpenSIPS is working fine!

Here is the list of all errors per parameter:

`
connect_timeout:
ERROR:core:set_mod_param_regex:` type mismatch for parameter <connect_timeout> in module <cachedb_cassandra>
CRITICAL:core:yyerror: parse error in config file opensips.cfg, line 109, column 20-21: Parameter <connect_timeout> not found in module <cachedb_cassandra> - can't set

query_timeout:
opensips.cfg, line 109, column 22-23: syntax error

wr_consistency_level:
column 21-22: syntax error
``

**To Reproduce**
loadmodule "cachedb_cassandra.so"
modparam("cachedb_cassandra", "cachedb_url","cassandra:userdata://IP3:9042/userdatakeyspace.userdata")
modparam("cachedb_cassandra", "wr_consistency_level", "each_quorum");
modparam("cachedb_cassandra", "query_timeout",1000);
modparam("cachedb_cassandra", "connect_timeout",1000);

**OS/environment information**
 - Operating System: Ubuntu 16.04
 - OpenSIPS installation: source

Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

I have also noticed that after restarting the Cassandra Server, OpenSIPS doesn't reconnect to the Cassandra Server until OpenSIPS is restarted.

Best Regards
Vasilios Tzanoudakis

**Comment by rvlad-patrascu** [comment]
Hi Vasilios,
I have not had any problems setting module parameters when I tried to reproduce this. Also, OpenSIPS did reconnect to Cassandra in my tests. What version of the Cassandra library are you using?

**Comment by rvlad-patrascu** [comment]
Hi Vasilios,
Do you still have this issue?

**Comment by vtzan** [comment]
Let me test again with latest code and I will update you

**Comment by vtzan** [comment]
Opensips Logs:
==================
Jun 25 10:17:52 sip-1-de opensips: Traceback (last included file at the bottom):
Jun 25 10:17:52 sip-1-de opensips:  0. /etc/opensips/edge/opensips.m4
Jun 25 10:17:52 sip-1-de opensips: CRITICAL:core:yyerror: parse error in /etc/opensips/edge/opensips.m4:163:22-23: syntax error
Jun 25 10:17:52 sip-1-de opensips: loadmodule "cachedb_cassandra.so"
Jun 25 10:17:52 sip-1-de opensips: modparam("cachedb_cassandra", "cachedb_url","cassandra:userdata1://LOCAL_CASSANDRA_SERVER:9042/userdatakeyspace.userdata")
Jun 25 10:17:52 sip-1-de opensips: modparam("cachedb_cassandra", "connect_timeout",1000);
Jun 25 10:17:52 sip-1-de opensips: ^~
Jun 25 10:17:52 sip-1-de opensips: #modparam("cachedb_cassandra", "query_timeout",1000);
Jun 25 10:17:52 sip-1-de opensips: 


OS:
=========
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

LIBS
==========
```
ii  cassandra-cpp-driver                   2.12.0-1                       amd64        C/C++ client driver for Apache Cassandra - runtime library
ii  cassandra-cpp-driver-dev               2.12.0-1                       amd64        C/C++ client driver for Apache Cassandra - development files
ii  libuv1:amd64                           1.9.1-3                        amd64        asynchronous event notification library - runtime library

```
