### ISSUE TITLE
Segfault on usr_avp.c

### ISSUE THREAD

**Issue by kaduww** [OpenSIPS/opensips#166]
Hello,

I've been having an issue on a running OpenSIPS. I's been crashing at least once a day and we noticed an unknown problem on the corefile.

We're using the OpenSIPS 1.8.3-notls:
opensips -V
version: opensips 1.8.3-notls (x86_64/linux)
flags: STATS: Off, USE_IPV6, USE_TCP, DISABLE_NAGLE, USE_MCAST, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
svnrevision: 2:10376M
@(#) $Id: main.c 10273 2013-10-03 18:40:16Z opensipsrelease $
main.c compiled on 17:44:02 Jan 20 2014 with gcc 4.4.7

The back trace we got:
#0  internal_search_ID_avp (flags=<value optimized out>, id=57, val=0x7fff35d13720, start=0x0) at usr_avp.c:316
No locals.
#1  search_first_avp (flags=<value optimized out>, id=57, val=0x7fff35d13720, start=0x0) at usr_avp.c:354
        head = <value optimized out>
        avp = <value optimized out>
#2  0x0000000000468a10 in pv_get_avp (msg=0x7f11dcd14ba0, param=<value optimized out>, res=0x7fff35d13a20) at pvar.c:1819
        name_type = <value optimized out>
        avp_name = 57
        avp_value = {n = -590263392, s = {s = 0x7f11dcd14ba0 "\340!", len = 902903640}}
        avp = <value optimized out>
        avp_value0 = {n = -1, s = {s = 0xffffffff <Address 0xffffffff out of bounds>, len = 13}}
        avp0 = <value optimized out>
        idx = <value optimized out>
        idxf = <value optimized out>
        p = <value optimized out>
        n = 0
        __FUNCTION__ = "pv_get_avp"
#3  0x000000000046693a in pv_get_spec_value (msg=<value optimized out>, sp=0x7f11dd48a028, value=0x7fff35d13a20) at pvar.c:3989
        ret = 0
        pv_msg = 0x7f11dcd14ba0
        __FUNCTION__ = "pv_get_spec_value"
#4  0x000000000048c58d in comp_scriptvar (e=0x7f11dd48a140, msg=0x7f11dcd14ba0, val=0x0) at route.c:1222
        ln = 0
        rn = 0
        type = <value optimized out>
        lstr = {s = 0x0, len = 0}
        rstr = {s = 0x0, len = 0}
        lvalue = {rs = {s = 0x0, len = 0}, ri = 0, flags = 0}
        rvalue = {rs = {s = 0x7fff35d13f70 "x~M", <incomplete sequence \335>, len = 2}, ri = 1580561094, flags = 62}
#5  eval_elem (e=0x7f11dd48a140, msg=0x7f11dcd14ba0, val=0x0) at route.c:1747
        uri = {user = {s = 0x0, len = 1}, passwd = {s = 0xdcd25340 <Address 0xdcd25340 out of bounds>, len = 902904984}, host = {
            s = 0x35d14220 <Address 0x35d14220 out of bounds>, len = 4276768}, port = {s = 0x7fff35d13f20 "\270\203\231\275\021\177", 
            len = 902905616}, params = {s = 0xffffffff <Address 0xffffffff out of bounds>, len = 2479}, headers = {s = 0x0, len = 1579435111}, 
          port_no = 0, proto = 0, type = 32767, transport = {s = 0x200000000 <Address 0x200000000 out of bounds>, len = 5673572}, ttl = {
---Type <return> to continue, or q <return> to quit---
            s = 0x7fffffffffff <Address 0x7fffffffffff out of bounds>, len = 5673573}, user_param = {s = 0x7fff35d13c98 "", len = 902905203}, 
          maddr = {s = 0x0, len = -612269506}, method = {s = 0x35d13e68 <Address 0x35d13e68 out of bounds>, len = 0}, lr = {s = 0x0, 
            len = 902905436}, r2 = {s = 0x7fff35d13e78 "\270\203\231\275\021\177", len = -1}, gr = {
            s = 0x7fff35d13e98 "314ec47a\300?\321\065\377\177", len = 5673472}, transport_val = {s = 0x3e5e244467 "f\203;", len = 8}, ttl_val = {
            s = 0x7fff35d13ea8 "\020\212F", len = 0}, user_param_val = {s = 0x7fff35d13ec8 "h\345x", len = 0}, maddr_val = {s = 0x7fff35d139e0 "", 
            len = -1}, method_val = {s = 0x7fff35d13e50 "(", len = 0}, lr_val = {
            s = 0x7fff35d14110 "\315\314\314\314\314\314\314\314\310yk\270\021\177", len = 5673648}, r2_val = {
            s = 0x7fff35d13dc8 "\250\377\377\377\377\377\377\377\340>\321\065\377\177", len = -1}, gr_val = {s = 0x7fff35d13e20 "", len = 0}, 
          u_name = {{s = 0x7fff35d13f18 "\376\377\377\377\377\377\377\377\270\203\231\275\021\177", len = 902905612}, {
              s = 0xa000009af <Address 0xa000009af out of bounds>, len = 192}, {s = 0x7fff35d13f20 "\270\203\231\275\021\177", len = 902905285}, {
              s = 0x0, len = 22671520}, {s = 0x7fff35d14080 "\020 ", len = 6}}, u_val = {{s = 0x7fff35d14090 "\020 ", len = 1580561097}, {
              s = 0x3e5e244467 "f\203;", len = 1580561098}, {s = 0x1 <Address 0x1 out of bounds>, len = 1}, {
              s = 0x35d13df8 <Address 0x35d13df8 out of bounds>, len = 0}, {s = 0x7f11dd48e2f8 "\002", len = -590263392}}, u_params_no = 0}
        ret = -5
        ival = <value optimized out>
        lval = {rs = {s = 0x0, len = 4}, ri = 2, flags = 0}
        rval = {rs = {s = 0x7fff35d1430c "\021\177", len = 4775453}, ri = -582462008, flags = 32529}
        p = <value optimized out>
        i = <value optimized out>
        n = <value optimized out>
        __FUNCTION__ = "eval_elem"
#6  0x000000000048de1d in eval_expr (e=0x7f11dd48a140, msg=0x7f11dcd14ba0, val=0x0) at route.c:1783
        rec_lev = 2
        ret = <value optimized out>
        __FUNCTION__ = "eval_expr"
#7  0x000000000048dde3 in eval_expr (e=0x7f11dd48a190, msg=0x7f11dcd14ba0, val=0x0) at route.c:1804
        rec_lev = 2
        ret = <value optimized out>
        __FUNCTION__ = "eval_expr"
#8  0x0000000000411b76 in do_action (a=0x7f11dd48abf8, msg=0x7f11dcd14ba0) at action.c:908
        val_s = {s = 0x2010 <Address 0x2010 out of bounds>, len = 40}
        increment = <value optimized out>
        decrement = <value optimized out>
        aux = {s = 0x60 <Address 0x60 out of bounds>, len = 1582890624}

Best regards,

Carlos

**Comment by bogdan-iancu** [comment]
@kaduww , if the problem persists, please re-open
