### ISSUE TITLE
[BUG]OpenSIPS 2.4.5 When full-sharing-cachedb is set, unregister doesn't remove contact from Mongo cachedb

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1661]
**OpenSIPS 2.4.5**
```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 17:22:29 Mar 23 2019 with gcc 5.4.0

```
**Describe the bug**
When OpenSIPs is configured with **full-sharing-cachedb**
```
modparam("usrloc", "location_cluster", MY_CLUSTER_ID)
modparam("usrloc", "cluster_mode", "full-sharing-cachedb")
```
and then **un-registers**, the contact is not removed from the cachedb.

**Data on mongodb when full-sharing-cachedb**

> /* 1 */
> {
>     "_id" : "+30XXXXXXXXX@DOMAIN",
>     "aorhash" : 373509453,
>     "contacts" : {
>         "c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw==" : {
>             "attr" : null,
>             "sip_instance" : "<urn:uuid:687abd4c-3d20-4b62-84ef-000413820BDD>",
>             "methods" : 7999,
>             "sock" : "udp:OPENSIPS_PUBLIC_IP:65060",
>             "path" : null,
>             "received" : "sip:CUSTOMER_PUBLIC_IP:35892",
>             "cflags" : "SIP_PING_RTO SIP_PING_FLAG NAT_FLAG",
>             "last_mod" : NumberLong(1554465363),
>             "ua" : "snomD120/10.1.33.33",
>             "flags" : 0,
>             "cseq" : 22051,
>             "callid" : "313535343237393436333537303832-i2pjma2blpg7",
>             "q" : 1000,
>             "expires" : 1554465423,
>             "contact" : "sip:+30XXXXXXXXX@CUSTOMER_PUBLIC_IP:35892"
>         }
>     }
> }

**Opensips Debug Logs on UnRegister**
`DBG:usrloc:delete_ucontact: deleting contact 'sip:+30XXXXXXXXX@CUSTOMER_PUBLIC_IP:35892'
DBG:usrloc:cdb_flush_urecord: deleting AoR: +30XXXXXXXXX@DOMAIN, Contact: sip:+30XXXXXXXXX@CUSTOMER_PUBLIC_IP:35892.
DBG:cachedb_mongodb:mongo_con_update: filter: { "_id" : "+30XXXXXXXXX@DOMAIN" }
DBG:cachedb_mongodb:mongo_con_update: set: { "aorhash" : 373509453 }
DBG:cachedb_mongodb:mongo_con_update: unset: { "contacts.c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw==" : null }
DBG:cachedb_mongodb:mongo_con_update: update: { "$set" : { "aorhash" : 373509453 }, "$unset" : { "contacts.c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw==" : null } }
DBG:usrloc:get_domain_cdb_ucontacts: idx=2/max=5, node=0/nr_nodes=1, filter: 858993458 <= aorhash < 1288490188
DBG:cachedb_mongodb:mongo_con_query: find all in opensipsDB.userlocation2
DBG:cachedb_mongodb:mongo_con_query: using filter: { "$and" : [ { "aorhash" : { "$gte" : 858993458 } }, { "aorhash" : { "$lt" : 1288490188 } } ] }
DBG:cachedb_mongodb:mongo_con_query: result count: 0
DBG:usrloc:get_domain_cdb_ucontacts: fetched 0 results`

**To Reproduce**
Try to unregister a user with the following params enabled :
```
modparam("usrloc", "location_cluster", MY_CLUSTER_ID)
modparam("usrloc", "cluster_mode", "full-sharing-cachedb")
```

**Expected behavior**
On un-register OpenSIPS should remove the contact from cachedb too
The removal is working fine when **federation-cachedb** is set on cluster_mode

data on mongodb when federation-cachedb

> /* 1 */
> {
>     "_id" : "+30XXXXXXXXX@DOMAINOPENSIPS_PUBLIC_IP:65060",
>     "aor" : "+30XXXXXXXXX@DOMAIN",
>     "home_ip" : "OPENSIPS_PUBLIC_IP:65060"
> }

**on unregister debug logs from OpenSIPs**
> DBG:usrloc:delete_ucontact: deleting contact 'sip:+30XXXXXXXXX@CUSTOMER_PUBLIC_IP:35892'
> DBG:usrloc:cdb_flush_urecord: deleting AoR: +30XXXXXXXXX@DOMAIN, Contact: sip:+30XXXXXXXXX@CUSTOMER_PUBLIC_IP:35892.
> DBG:core:_dbg_cdb_dict: final ct changes: { contacts.c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw== : null }
> DBG:cachedb_mongodb:mongo_con_update: filter: { "_id" : "+30XXXXXXXXX@DOMAIN" }
> DBG:cachedb_mongodb:mongo_con_update: set: { "aorhash" : 373509453 }
> DBG:cachedb_mongodb:mongo_con_update: unset: { "contacts.c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw==" : null }
> DBG:cachedb_mongodb:mongo_con_update: update: { "$set" : { "aorhash" : 373509453 }, "$unset" : { "contacts.c2lwOiszMDIxMDcwMDEzOThANzcuNjkuNy4yNDQ6MzU4OTI6MzEzNTM1MzQzMjM3MzkzNDM2MzMzNTM3MzAzODMyLWkycGptYTJibHBnNw==" : null } }
> DBG:core:parse_headers: flags=ffffffffffffffff

**OS/environment information**
 - Operating System: Ubuntu 16.04
 - OpenSIPS installation: Source

I don't know this can help you but in the script I am setting a custom AoR before save location.

> save("location","p2v","$avp(custom_aor)

Thank you in advance
Vasilios Tzanoudakis

**Comment by liviuchircu** [comment]
@vtzan, I re-tested this without much success.  See below the initial state (empty), post-registration and post-deregistration states:

```> db.location_fullsharing.find()
> // Register
> db.location_fullsharing.find()
{ "_id" : "liviu@opensips.cluster", "aorhash" : 672156876, "contacts" : { "c2lwOjM2MDc0MTI4QDEwLjAuMC4xMDo1MDk1OmQyZTNlZDA2LTRlODItNGE1ZS05NmZlLWM1ZWEzMTk5NjBkOQ==" : { "attr" : null, "sip_instance" : "<urn:uuid:e5e68d40-f08a-4600-b82e-ff4d5d8c1a8f>", "methods" : null, "sock" : "udp:10.0.0.210:5060", "path" : null, "received" : null, "cflags" : "NAT", "last_mod" : NumberLong(1559035404), "ua" : "Blink 3.2.0 (Linux)", "flags" : 0, "cseq" : 1, "callid" : "d2e3ed06-4e82-4a5e-96fe-c5ea319960d9", "q" : -1, "expires" : 1559036004, "contact" : "sip:36074128@10.0.0.10:5095" } } }
> // De-Register
> db.location_fullsharing.find()
{ "_id" : "liviu@opensips.cluster", "aorhash" : 672156876, "contacts" : {  } }
> 
```

Is your issue related to the lingering AoR with 0 contacts after the deregistration, or did your contacts not get removed at all from the DB?  Looking at the logs, the contacts match perfectly, so the `$unset` query should have worked.

**Comment by vtzan** [comment]
Dear @liviuchircu,

As you already know thanks to your help from this year's Summit I have abandoned mongo and 2.4.x and switched to cassandra & Opensips 3.0.0-beta. 
Deleting and inserting contacts is working great here. So Let assume it is working for mongo too and it was like a false alarm...

thank you
Vasilios Tzanoudakis

**Comment by liviuchircu** [comment]
Perfect. Closing for now, then!
