### ISSUE TITLE
[BUG] mod_siprec cannot find an available rtpproxy node, even when one is available, unless a default proxy set is defined.

### ISSUE THREAD

**Issue by solarmon** [OpenSIPS/opensips#1664]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e1004f8
main.c compiled on 11:58:55 Apr  5 2019 with gcc 4.9.2
```

**Describe the bug**

When using mod_siprec, it cannot create a media stream because it cannot find an rtpproxy node, even though one is available, and is available and used for the normal call (to be recorded) rtp streams.

The following error is generated:

```
ERROR:rtpproxy:rtpproxy_api_recording: no available proxies
ERROR:siprec:srs_handle_media: cannot start recording for stream 0x7fecc7fce278 (label=2)
ERROR:rtpproxy:select_rtpp_node: no set specified
ERROR:rtpproxy:rtpproxy_api_recording: no available proxies
ERROR:siprec:srs_handle_media: cannot start recording for stream 0x7fecc7fcb990 (label=1)
ERROR:siprec:srec_b2b_notify: cannot handle SRS media!
```

However, when a default proxy set is defined in the opensips configuration, then the issue does not occur.

Is this the expected behaviour?

**To Reproduce**

The following config is used when the issue occurs:

```
# Modules required for SIPREC
loadmodule "siprec.so"
loadmodule "b2b_entities.so"
loadmodule "uac_auth.so"
loadmodule "rtpproxy.so"
modparam("rtpproxy", "db_url", "mysql://opensips:opensipsrw@localhost/opensips")
```

The rtpproxy node in the DB is:

```
id | rtpproxy_sock | set_id
1 | udp:127.0.0.1:7899 | 1
```

However, when the following option is added in opensips.cfg, then this issue does not occur:

```
modparam("rtpproxy", "default_set", 1)
```

**Expected behavior**

It is expected that an rtpproxy node is found without having to set a default proxy set.

**Relevant System Logs**

**OS/environment information**
 - Operating System: CentOS Linux release 7.6.1810 (Core)
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by solarmon** [comment]
Some extra info.

This is the siprec_start_recording function I'm using in the routing logic:

```
siprec_start_recording("$var(siprec_srs)",,,,,"$var(siprec_media_ip)");
```

However, as per https://opensips.org/html/docs/modules/2.4.x/siprec , even when I specify a rtpproxy_set (which is optional) of '1' in the siprec_start_recording function:

```
siprec_start_recording("$var(siprec_srs)",,,,"$var(siprec_rtpproxy_set)","$var(siprec_media_ip)");
```

it still has the error:

```
ERROR:rtpproxy:rtpproxy_api_recording: no available proxies
```

It only works when I set the 'default_set' for rtpproxy in the opensips.cfg:

```
modparam("rtpproxy", "default_set", 1)
```

**Comment by razvancrainea** [comment]
Are you 100% sure that the `$var(siprec_rtpproxy_set)` is set to 1 before calling `siprec_start_recording`? Can you add some debugging just above the function's call to make sure?

**Comment by solarmon** [comment]
I have tried setting the variable:

```
$var(siprec_rtpproxy_set) = "1";
```

and

```
$var(siprec_rtpproxy_set) = 1;
```

and to call the siprec_start_recording function with:

```
siprec_start_recording("$var(siprec_srs)",,,,,"$var(siprec_media_ip)");
```

```
siprec_start_recording("$var(siprec_srs)",,,,"$var(siprec_rtpproxy_set)","$var(siprec_media_ip)");
```

```
siprec_start_recording("$var(siprec_srs)",,,,"1","$var(siprec_media_ip)");
```

and restarted opensips with

```
systemctl restart opensips
```

They all produce the following error:

```
ERROR:rtpproxy:rtpproxy_api_recording: no available proxies
ERROR:siprec:srs_handle_media: cannot start recording for stream 0x7f7fc74f4290 (label=2)
ERROR:rtpproxy:rtpproxy_api_recording: no available proxies
ERROR:siprec:srs_handle_media: cannot start recording for stream 0x7f7fc74f37c8 (label=1)
ERROR:siprec:srec_b2b_notify: cannot handle SRS media!
```

Even if "rtpproxy_set" is not set or specified, according to the documentation it is optional - so I don't expect to have to set it in the first place.

I assume when rtpproxy_set is not provided, it tries to fall back to the default. However, as I have found even when I provide it specifically it still seems to fail.

In terms of 'debugging', I just output to the logs with:

```
$var(siprec_rtpproxy_set) = "1";
xlog("### siprec_rtpproxy_set:  $var(siprec_rtpproxy_set) ###\n");
siprec_start_recording("$var(siprec_srs)",,,,"$var(siprec_rtpproxy_set)","$var(siprec_media_ip)");
```

And I do get in the logs:
```
### siprec_rtpproxy_set:  1 ###
```

**Comment by solarmon** [comment]
Sorry, I don't think I made it clear or did not say, that it only works when I configure "default_set" AND don't specify a "rtpproxy_set" value. It only works in that combination.

```
modparam("rtpproxy", "default_set", 1)

siprec_start_recording("$var(siprec_srs)",,,,,"$var(siprec_media_ip)");
```

**Comment by solarmon** [comment]
Hi,

Can it be confirmed that this is a known issue/bug, and if/when it can be resolved?

**Comment by razvancrainea** [comment]
As specified in commit ba81966, there was an issue in the documentation, which also confused me a bit. The idea is that the `siprec_start_recording()` function does not receive the rtpproxy set as parameter, but rather the socket used. This can be got using the 4th parameter of rtpproxy_offer/answer. For example, in your case, you should do something like:
```
rtpproxy_offer(,,"1","$var(siprec_rtpproxy_socket)");
siprec_start_recording("$var(siprec_srs)",,,,"$var(siprec_rtpproxy_socket)","$var(siprec_media_ip)");
```
Apologies for the confusion, I hope now things got fixed.
