### ISSUE TITLE
[CRASH] I have installed the Opensips control panel but it's not connecting to the server, what should i do 

### ISSUE THREAD

**Issue by AyoubStri** [OpenSIPS/opensips#1665]
**OpenSIPS version you are running**

version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e1004f8
main.c compiled on 08:00:33 Apr  9 2019 with gcc 4.9.2

**Crash Core Dump**

**Describe the traffic that generated the bug**

**To Reproduce**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

this is my error 
Sending to json:127.0.0.1:8888/json : Failed to connect to 127.0.0.1 port 8888: Connection refused

**Comment by bogdan-iancu** [comment]
@AyoubStri , most probably your OpenSIPS is not running or it is a misconfiguration of the httpd module. Nevertheless this is NOT a crash to report here. Please use the right channel for asking for help from the community, via the 'users' mailing list http://lists.opensips.org/cgi-bin/mailman/listinfo/users
