### ISSUE TITLE
[BUG]ERROR:tm:update_cloned_msg_from_msg: failed to clone lumps, not updating

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1669]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 78984b2
main.c compiled on 09:32:38 Apr 15 2019 with clang 4.2.1
```

**Describe the bug**

I sometimes see the following error messages in my logs while processing traffic:
Apr 12 12:49:54 testing /usr/sbin/opensips[22337]: ERROR:tm:update_cloned_msg_from_msg: failed to clone lumps, not updating
Apr 12 12:49:54 testing /usr/sbin/opensips[22337]: ERROR:tm:update_cloned_msg_from_msg: failed to clone body lumps, not updating

**To Reproduce**

Sporadic. Have not been able to link to a certain set of signalling or functions. When I check signalling everything is as expected, I don't see any corrupt messages or unwanted changes.

**Expected behavior**

No error messages.

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

We use topologyhiding, mc_compac, uac_replace_to, uac_replace_from functions to manipulate signalling and have hp_malloc enabled.

Looking at the update_cloned_msg_from_msg function it looks like shm_malloc would have to fail for these messages to print, but I'm not getting any other error logs, which should happen on a malloc failure.

I updated the error to include the len that should have been malloced and got the following for the l1_len block where c_msg->add_rm ends up being NULL:
ERROR:tm:update_cloned_msg_from_msg: failed to clone lumps, not updating. Did not allocate 200

So it doesn't look like it is trying to allocate some huge amount either. Could their be an issue with hp_shm_malloc? Or a race happening against the shm version of the message?

**Comment by rrb3942** [comment]
Switched to f_malloc to see if it made a difference. The error seems to happen less frequently, but I also get a segfault periodically, so I think this may be a memory corruption thing.

Also rebuilt with gcc, since gdb was not liking the dumps from the clang build version.

version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 78984b2
main.c compiled on 09:30:27 Apr 18 2019 with gcc 8


[opensips_bt.txt](https://github.com/OpenSIPS/opensips/files/3095450/opensips_bt.txt)

**Comment by rrb3942** [comment]
Rebuilt opensips with -O0 and QM_MALLOC for a better backtrack. Also pulled some of our local patches just to be sure.

Segfault message:
opensips[12101]: segfault at 30 ip 00007fb91acc19ba sp 00007ffe9ba1b140 error 4 in tm.so[7fb91ac7a000+6b000]
[opensips_bt_O0.txt](https://github.com/OpenSIPS/opensips/files/3096106/opensips_bt_O0.txt)

(gdb) p p
$2 = 0x7fb9273b0b68 "\n"
(gdb) p msg->add_rm
$3 = (struct lump *) 0x7fba64862758
(gdb) p c_msg->add_rm
$4 = (struct lump *) 0x0

So same, cause as original error being reported (c_msg->add_rm is getting nulled) but it is happening between the NULL and the call to CLONE_LUMP_LIST.

**Comment by rrb3942** [comment]
Was finally able to narrow this down. This is caused by a race between the INVITE and ACK. I added some additional logging to do_t_cleanup() to catch this.

If we receive an ACK before we return from the script for the original INVITE there is a chance both the ACK and the INVITE will run update_cloned_msg_from_msg over the same shm message.

In our case, the client is very close and our process for sending the response is:
send_reply();
acc_db_request() (this can take time, even if it is ~1ms)
some_other_cleanup() (maybe increment a remote counter, etc, again may take some time even if <1ms)
exit;

While we could call acc_db_request before sending the reply, and that might help avoid the race, the race is still present (and I prefer to respond before taking time to book keep).

Seems like at the very least some locking needs to happen around update_cloned_msg_from_msg() in do_t_cleanup(). I don't know if more locking would also be needed elsewhere (t_reply_with_body also() uses update_cloned_msg_from_msg()), or if it should happen earlier.

I do see that transactions have a reply lock, should they also have a request lock (for modifications)? I am unsure how aggressive you would have to be in acquiring it if you are making changes.

Could Re-Transmissions also trigger this? If they still run do_t_cleanup() after the script even if t_checktrans() is used it is possible they could see update_cloned_msg_from_msg() as needing to be run.

[race_ngrep.txt](https://github.com/OpenSIPS/opensips/files/3099421/race_ngrep.txt)
[log.txt](https://github.com/OpenSIPS/opensips/files/3099422/log.txt)

Other thoughts:
Part of the problem seems to be that if one process sets FL_SHM_UPDATED it is possible for others to also see it and try to push their changes. I wonder if we shouldn't track locally if our changes need to be pushed instead of checking the shm if it needs changes. Locking would still be required around writes/changes but processes wouldn't accidentally try to update the shm.

**Comment by rrb3942** [comment]
See https://github.com/OpenSIPS/opensips/pull/1678

**Comment by rrb3942** [comment]
https://github.com/OpenSIPS/opensips/commit/3a994ceeafc6830a1c3b3f2699a7dc1ea915c83a should also fix this, although calls to update_cloned_msg_from_msg via t_reply_with_body may also need to be protected.

**Comment by razvancrainea** [comment]
That's true, most likely these two issues are related.
Calls to `t_reply_with_body` don't actually need to be protected, because the transaction was previously created with the `full uas cloning` flag, meaning that it can no longer be updated.

**Comment by rrb3942** [comment]
Got it. That was the only other place I could think of that may cause a race, just because of the function call. Just wanted to make sure.

Do you think the change in https://github.com/OpenSIPS/opensips/pull/1678 which prevents the ACK to a local final reply from attempting updates against the shm copy is useful? If not I can close out this bug and pull request, or I can update the patch and test it.
