### ISSUE TITLE
[FEATURE] (or minor bug) 100 "Giving a try" SIP "reason phrase" deviates from the RFC default (and is not grammatically correct in English)

### ISSUE THREAD

**Issue by shaunbro** [OpenSIPS/opensips#1670]
Super low priority but very easily fixed. 

The wording ("reason phrase") for the provisional response 100 in Opensips is "Giving a try"
The default wording from the RFC is simply "Trying".  "Giving a try" is itself not a grammatically sound phrase (at least in english). 

I would propose to either change the wording to the RFC default "Trying" or request a feature to allow modification or regionalisation for other languages etc for this and other reason phrases. 

The change for the 100 trying is a single line in the transaction module (t_lookup.c)
static str relay_reason_100 = str_init("Trying");

Thanks!

**Comment by liviuchircu** [comment]
Agreed -- the original author probably had the "giving <something> a try" phrase in mind, but butchered it.  So `100 Giving It a Try` would at least have been grammatically correct.

Regarding deviating from the RFC: I think I would not do it by default, however I've become quite fond of the current "Giving It a Try" phrase, as it is a surefire way of telling whether a given SIP UA is based on OpenSIPS.  Whether that's a good thing or not is difficult to assess (extra security vs. extra insights).

The clumsy wording makes for a good opportunity to fix it back to the standard `100 Trying`.  Had the wording been correct, I would have voted against changing the custom phrase :)

**Comment by bcnewlin** [comment]
I would add to this the reason phrase for the 200 response to a CANCEL request is also a non-standard "canceling" instead of the normal "OK".

**Comment by grxnola** [comment]
But "Giving a try" is far more charming than "Trying"
