### ISSUE TITLE
[BUG] Documentation of DB tables

### ISSUE THREAD

**Issue by SB-JohnK** [OpenSIPS/opensips#1672]
**OpenSIPS version you are running**
```
This is a bug related to the website.

The DB Schema documentation has several issues that are present in multiple versions.
https://www.opensips.org/Documentation/Install-DBSchema-2-4
https://www.opensips.org/Documentation/Install-DBSchema-3-0
https://www.opensips.org/Documentation/Install-DBSchema-3-1
```

**Describe the bug**

Section 20 'Extensions' with the tag of AEN5845 consists of only a single greater-than symbol.

Section 38 'Sip URI  Checks' with the tag of AEN9868 is linking to documentation that does not exist. the uri-db module was merged with uri in opensips 1.6.x

**To Reproduce**

Navigate the website documentation

**Comment by bogdan-iancu** [comment]
Thanks @SB-JohnK  for the report, all the broken links in the DB schema html page were fixed and online doc regenerated.
