### ISSUE TITLE
[BUG]Redis broken in latest git

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1677]
The commit adding support for mongodb url options breaks redis:
https://github.com/OpenSIPS/opensips/commit/9d82861708457b337d74c43a145a05b5a668d6fb

Example logs:
2019-04-23T12:22:33.107986-07:00 testing /usr/sbin/opensips[27664]: ERROR:cachedb_redis:redis_connect_node: failed to select database  - ERR invalid DB index
2019-04-23T12:22:33.108256-07:00 testing /usr/sbin/opensips[27664]: ERROR:cachedb_redis:redis_connect: failed to init connection

Also get a segfault if a process tries to use a connection.

Reverting the commit fixes the issue and I can connect to redis just fine.

Haven't looked into what specifically is causing the issue with that commit and redis yet.

**Comment by liviuchircu** [comment]
wow, and I even did all kinds of tests to make sure I haven't broken anything with the `?extra_options...` addition.  I'll take a look asap, @rrb3942

**Comment by rrb3942** [comment]
Forgot to add I was using 2.4 from git.

**Comment by liviuchircu** [comment]
Could you copy-paste your Redis URL (make sure to cover up public IPs)?  Maybe it contains some syntax that I have omitted in my tests.

**Comment by rrb3942** [comment]
Here you go. We do use dns names, which may be it?

modparam("cachedb_redis","cachedb_url","redis:myredis://redis.mydomain.internal:6379/")

**Comment by liviuchircu** [comment]
DNS has nothing to do with this -- there is some little bug with the end of the string parsing / zeroization.  And I just noticed your URL ends with a `/` and no database, which is a great lead.

**Comment by liviuchircu** [comment]
thanks for the quick catch, @rrb3942!
