### ISSUE TITLE
Problem with restoring dialog vars after restart.

### ISSUE THREAD

**Issue by gwozniak** [OpenSIPS/opensips#1682]
**OpenSIPS version you are running**

```
version: opensips 2.2.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 7b5d1b4
main.c compiled on 22:23:26 Apr 25 2019 with gcc 4.4.7
```

**Describe the bug**
Bug is also present in version 2.2.2 running on PROD, I installed latest 2.2.x on LAB to check if it was fixed, it wasn't.
As pointed in subject opensips doesn't restore dialog vars (eg. $dlg_val(ctx_acc_from_domain))  after restart.
Restart(actually start on another node along with VIP switch over) is part of HA procedure made by pacemaker.
I need those values for ACC module to store additional info in CDRs.
Dialog module uses DB persistence with configuration(pg uri is local haproxy which connects to DB):
```
modparam("dialog", "db_url", "postgres://xxxx:yyyy@127.0.0.1:5433/cs4_cdr_db")
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 129600)  # 36 hours timeout
modparam("dialog", "db_mode", 2)
modparam("dialog", "db_update_period", 1)
modparam("dialog", "profiles_with_value", "trunkCalls")
modparam("dialog", "options_ping_interval", 300)
```
I added some additional logging to dlg_db_handler.c files and found that value of vars column is passed to read_dialog_vars function as ascii hex representation of real blob value, this log point it:
```
11:44:56.076041 Apr 26 11:44:56 [22763] DBG:dialog:load_dialog_info_from_db: XXXUpdating script variables
11:44:56.076071 Apr 26 11:44:56 [22763] DBG:dialog:load_dialog_info_from_db: XXXVariables <x616363585f7461626c65236163637c616363585f666c6167732300000700000022007c616363....>
```
and reading variables stops at the very beginning  here in read_dialog_vars:
```
               /* read a new pair from input string */
                p = read_pair( p, end, &name, &val);
                if (p==NULL) break;
```
I decided to add additional function hex_to_ascii which simply converts pairs of hex characters to their ascii codes "61" -> 0x61 and dialog variables are now accessible after restart.
Here fragment of load_dialog_info_from_db after modification:
```
/* script variables */
                        if (!VAL_NULL(values+17)) {
                                if (VAL_TYPE(values+17) == DB_BLOB) {
                                        LM_DBG("XXXUpdating script variables\n");
                                        LM_DBG("XXXVariables <%.*s>\n",VAL_BLOB(values+17).len,VAL_BLOB(values+17).s);
                                        char _vars[VAL_BLOB(values+17).len/2];
                                        int i=1; //skip first 'x'
                                        char buf=0;
                                        for(;i<VAL_BLOB(values+17).len;i++){
                                                if(i%2==0){
                                                        _vars[i/2-1]=hex_to_ascii(buf,VAL_BLOB(values+17).s[i]);
                                                }else{
                                                        buf=VAL_BLOB(values+17).s[i];
                                                }
                                        }
                                        str vars = str_init(_vars);
                                        read_dialog_vars( vars.s,
                                                        vars.len, dlg);
                                } else {
                                        LM_ERR("non-blob variables column - cannot store dialog variables\n");
                                }
                        }

``` 
**To Reproduce**

1. Start OpenSIPS
2. Start sip sessiosion
3. Restart opensips
4. Try to xlog some dialog var eg. during BYE or Hold - you will get 'null' printed and will find in debug log:
```
DBG:dialog:fetch_dlg_value: looking for <your_var>
DBG:dialog:fetch_dlg_value: var NOT found!
```

**Expected behavior**
Vars are correctly restored after restart without my dirty workaround.
**Relevant System Logs**
Provided above.

**OS/environment information**
 - Operating System: CentOS release 6.8 (Final)
 - OpenSIPS installation: git
 - other relevant information: postgres (PostgreSQL) 9.4.21

**Additional context**
none

**Comment by liviuchircu** [comment]
I was not able to reproduce this on `2.2.7` with either MySQL or Postgres.  With `db_mode = 1`, after having set up a call and restarted the server, on receipt of the BYE, I printed a `$dlg_val` I had set during the INVITE, and it correctly shows up the value.  Did you change the `opensips.dialog` table schema in any way?

**Comment by liviuchircu** [comment]
Closing here for now, as this issue seems to be specific to your setup, specifically this part:

```
I added some additional logging to dlg_db_handler.c files and found that value of vars column is passed to read_dialog_vars function as ascii hex representation of real blob value, this log point it:
```

There is no logic in OpenSIPS which would cause this "binary to hex" conversion.  If a column is `BLOB`, the data arrives as pure bytes, as per my tests.  Could it be the case that you have enabled some PG server settings which cause this conversion?

If you still want us to dig further here, please re-open and provide a minimal `opensips.cfg` file on top of a PGSQL server with default settings and default OpenSIPS DB schema that still exhibits this issue.

**Comment by gwozniak** [comment]
Hi, I was involved in another project and didn't have time for that support ticket, what is more it is not urgent for me because switching active node in HA is very rare and done at night in service windows.
Anyway I'm going to check this deeper using another postgres versions (8.x,10.x) and also will check it with mysql/mariadb. I will inform you about my findings. Thanks.

**Comment by gwozniak** [comment]
Hi, 
it seems that opensips (exactly db_postgres.so) must be linked to same probably major version of postgres.
In deployment which I take care opensips was compiled by my colleague on separate machine than the DB is located. DB which opensips was talking is 9.4 and postgres-devel package on voipcore machine is 8.4 (centos 6 distribution one). 
Today I installed postgresql94-devel on voipcore machine and recompile module against 9.4.x libs and what a surprise - dialog's vars are restored correctly after restart of opensips during ongoing sip session :) 
Maybe it is worth to mentioned somewhere in README.
