### ISSUE TITLE
[FEATURE] Additional RTPEngine control messages / functions.

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1686]
**Describe the solution you'd like**
Additional function calls to RTP Engine

**Implementation**

RTPEngine Module:

`block DTMF` and `unblock DTMF` Messages
`block media` and `unblock media` Messages
`start forwarding` and `stop forwarding` Messages
`play media` Message
`stop media` Message

**Comment by digipigeon** [comment]
In addition to these the `play media` message is now available, can we please have this as well. Thanks.

**Comment by razvancrainea** [comment]
The functions for blocking and unblocking DTMF and media have been developed on [3.1](https://opensips.org/html/docs/modules/3.1.x/rtpengine.html#func_rtpengine_block_media). We are currently only missing the `start forwarding` and `stop forwarding` commands, but we have these on our roadmap as well.
