### ISSUE TITLE
[BUG] OpenSIPS 3.0.0 - update_stat - Failed to fix command

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1688]
**OpenSIPS version you are running**
OpenSIPS 3.0.0

**Describe the bug**
OpenSIPS Cannot Start if function update_stat is defined.

**To Reproduce**
Define in script :
update_stat("packet:count", "+1");

**Relevant System Logs**
May  2 12:25:20 sip1 opensips[12181]: ERROR:core:fix_cmd: Param [2] expected to be an integer or variable
May  2 12:25:20 sip1 opensips[12181]: ERROR:core:fix_actions: Failed to fix command <update_stat>
May  2 12:25:20 sip1 opensips[12181]: ERROR:core:fix_actions: fixing failed (code=-6) 
May  2 12:25:20 sip1 opensips[12181]: ERROR:core:main: failed to fix configuration with err code -6

**OS/environment information**
 - Operating System: Ubuntu 16.04
 - OpenSIPS installation: git / master
 - other relevant information:

**Comment by rvlad-patrascu** [comment]
Hi,
The correct usage in 3.0 is `update_stat("packet:count", 1);` but I've also just pushed a fix becuase there was also a crash, so be sure to use the latest commit.
