### ISSUE TITLE
[FEATURE] RTPEngine RFC2833 -> OpenSIPs event listener

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#1691]
**Is your feature request related to a problem? Please describe.**

We would like to have the ability for RFC 2833 DTMF events captured from RTPEngine be passed back to OpenSIPs for either logging / CDR / events / Creation of SIP INFO messages.

**Describe the solution you'd like**

A listener available to receive these events.

**Implementation**
 
  - Component: RTPEngine 
  - Type: listener 
  - Name: RTPEngine DTMF Event Listener 

**Describe alternatives you've considered**

There is no feature like this in RTPEngine yet, but this is chicken and egg. Discussing with Razvan one option is expand the xmlrpc-callback to serve more than one purpose.

**Comment by digipigeon** [comment]
Would this feature be any use for rtpengine module to listen for:

https://github.com/sipwise/rtpengine/commit/fcb08df0ae0cb60127da7c94aeaad9f882719242

**Comment by razvancrainea** [comment]
Yes, that could be useful to start with, but I see a few limitations of this approach:

1. it is not standard - you will have to write your own UDP listener (not that's too hard, but it's an extra step) to fetch the command and interpret the payload. I would have imagined to send the event in a standard format, like the dialog end command is triggered over xmlrpc - this way we could get use of the current engines to retrieve the event.
2. it is limited to a single Proxy instance - you can only configure a single destination where *all* events will be sent, no matter which proxy generated them. A nicer way to do this would have been to be able to specify the destination of the DTMF events in the session create

But again, this is very useful for now, and it's something we can start with. Thanks for sharing the updates!
