### ISSUE TITLE
[BUG] tracer module records incorrect from/to ports

### ISSUE THREAD

**Issue by danpascu** [OpenSIPS/opensips#1692]
**OpenSIPS version you are running**

```
version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 08cff3486
main.c compiled on  with gcc 8
```

**Describe the bug**

A client C, connects over TCP to a proxy A, which later forwards the messages to another proxy B also over TCP. The client connects from a random port (let's say 30000) to 5060 on A and A also connects from a random port (let's say in this case 40000) to 5060 on B, as seen from a network trace. The client sends an INVITE that travels C->A->B and gets replies that travel back B->A>C and the tracer module records packets on A.

In the database the tracer module while it correctly records the from port to be 30000 for the INVITE from C to A, it records the from port to be 5060 for the INVITE sent from A to B. The same is true for the replies, only in their case the to port is wrong for the A-B segment.

**Comment by bogdan-iancu** [comment]
@danpascu , could you test the latest 3.0 git code ?

**Comment by danpascu** [comment]
It seems to work now, thanks.

I noticed another issue with the sip trace though. The Max-Forwards header is not updated on the outgoing request when the request is relayed. It shows the same value as the incoming request, despite it actually being updated in the SIP package, it's just the sip trace that is wrong.

**Comment by bogdan-iancu** [comment]
You say the outbound traced requests shows an un-updated MF hdrs ?

**Comment by danpascu** [comment]
Yes. In sip trace I see the incoming invite with N and the outgoing INVITE also with N, while in a network trace I see N on incoming and N-1 on outgoing. So the request is processed correctly, just recorded incorrectly.

**Comment by bogdan-iancu** [comment]
@danpascu , by any chance do you do a t_newtran() or async() (or anything that may build trigger the build of the transaction) before the `mf_process_maxfwd_header()` call ?

**Comment by danpascu** [comment]
No. mf_process_maxfwd_header is literally the first thing I call in the main route:

```
route {

    if (!mf_process_maxfwd_header(10)) {
        xlog("L_WARN", "WARNING: Too many hops for $rm from $fu to $ru via $si:$sp\n");
        if ($rm != "ACK") {
            force_rport();
            sl_send_reply(483, "Too many hops");
        }
        return;
    }

    [...]

```

**Comment by danpascu** [comment]
I trigger tracing per dialog, not sure if this has any relevance, but I thought I'd mention it:

```
    [...]

    if (($rm=="INVITE" && !has_totag())) {
        trace("default", "d", "sip");

        # Stop retransmissions
        t_check_trans();

    [...]
```

**Comment by danpascu** [comment]
Also other elements of the outgoing message, like the added Via/Record-Route headers as well as changes to the existing headers and the SDP are visible in the trace of the sent request. Is just the MF header that is not updated and still shows the same value as the one in the incoming request.

**Comment by bogdan-iancu** [comment]
I will try tomorrow (or today, it is past midnight  :) ) to see if I can reproduce. The MF change is a bit particular, as it is the only one directly changing the msg buffer (and not adding a lump)...still it should work

**Comment by bogdan-iancu** [comment]
Running a basic test on the default cfg with tracer + proto_hep, in combination with opensips-cli and `trace` command:

```1559123758.904466 UDP/SIP 10.0.0.12:5075 -> 10.0.0.15:5060
INVITE sip:11@10.0.0.15 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.12:5075;branch=z9hG4bK-8bcef0be
From: "bob" <sip:bob@10.0.0.15>;tag=f5a2730ceaa58e5o2
To: <sip:11@10.0.0.15>
Call-ID: 1e440f58-3e068909@10.0.0.12
CSeq: 101 INVITE
Max-Forwards: 70
Contact: "bob" <sip:bob@10.0.0.12:5075>
Expires: 240
Content-Length: 393
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, REFER
Supported: replaces
Content-Type: application/sdp

v=0
o=- 51502594 51502594 IN IP4 10.0.0.12
s=-
c=IN IP4 10.0.0.12
t=0 0
m=audio 16450 RTP/AVP 0 2 4 8 18 96 97 98 101
a=rtpmap:0 PCMU/8000
a=rtpmap:2 G726-32/8000
a=rtpmap:4 G723/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729a/8000
a=rtpmap:96 G726-40/8000
a=rtpmap:97 G726-24/8000
a=rtpmap:98 G726-16/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:30
a=sendrecv

1559123758.905448 UDP/SIP 10.0.0.15:5060 -> 10.0.0.12:5075
SIP/2.0 100 Giving it a try
Via: SIP/2.0/UDP 10.0.0.12:5075;branch=z9hG4bK-8bcef0be
From: "bob" <sip:bob@10.0.0.15>;tag=f5a2730ceaa58e5o2
To: <sip:11@10.0.0.15>
Call-ID: 1e440f58-3e068909@10.0.0.12
CSeq: 101 INVITE
Server: OpenSIPS (3.0.0-beta (x86_64/linux))
Content-Length: 0


1559123758.905667 TCP/LOG
ERROR:new branch at sip:11@10.0.0.15:44307;rinstance=32c6c0fe5420631e;transport=UDP

1559123758.906227 UDP/SIP 10.0.0.15:5060 -> 10.0.0.15:44307
INVITE sip:11@10.0.0.15:44307;rinstance=32c6c0fe5420631e;transport=UDP SIP/2.0
Record-Route: <sip:10.0.0.15;lr;did=e71.c5b2c516>
Via: SIP/2.0/UDP 10.0.0.15:5060;branch=z9hG4bK0501.f96e6e67.0
Via: SIP/2.0/UDP 10.0.0.12:5075;branch=z9hG4bK-8bcef0be
From: "bob" <sip:bob@10.0.0.15>;tag=f5a2730ceaa58e5o2
To: <sip:11@10.0.0.15>
Call-ID: 1e440f58-3e068909@10.0.0.12
CSeq: 101 INVITE
Max-Forwards: 69
Contact: "bob" <sip:bob@10.0.0.12:5075>
Expires: 240
Content-Length: 393
Allow: ACK, BYE, CANCEL, INFO, INVITE, NOTIFY, OPTIONS, REFER
Supported: replaces
Content-Type: application/sdp

v=0
o=- 51502594 51502594 IN IP4 10.0.0.12
s=-
c=IN IP4 10.0.0.12
t=0 0
m=audio 16450 RTP/AVP 0 2 4 8 18 96 97 98 101
a=rtpmap:0 PCMU/8000
a=rtpmap:2 G726-32/8000
a=rtpmap:4 G723/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729a/8000
a=rtpmap:96 G726-40/8000
a=rtpmap:97 G726-24/8000
a=rtpmap:98 G726-16/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:30
a=sendrecv

```

As far I can see, the MF is ok in the outbound capturing of the INVITE.

**Comment by bogdan-iancu** [comment]
OK, some update here after running multiple tests.
Indeed, there is a problem with the traced MF value, but not on outbound side, but on the inbound side. 
First, let me remind the MF particularity of making its change directly into the msg buffer and not via lumps.
Now, the outbound is all the time correct. For the inbound leg, it depends on the order between the moment of MF change (via mf_process_maxfwd_header()) and the moment of tracing the inbound msg.
In 99% of the cases, the MF change is done before you do `trace()`, so the inbound will also show the changed value.
In my test, using the `trace` via `opensips-cli`, the hook for tracing the inbound is placed before the script execution, so all the time before the the MF change. This is why I got 70/69 correct values. But checking for ACK and BYE, I noticed the 69/69 wrong values (as dialog-based tracing is done, the sequential requests are traced via dialog callbacks, so after MF change all the time).
There is nothing to fix here (almost impossible), unless we change the `maxfwd` module to do its changes via lumps (as any other module). If the case, please open a separate bug reports with all this information - and let's consider it for the next release.
