### ISSUE TITLE
[BUG]mc_compact() changes lost on retransmit

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1694]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e3f0e88
main.c compiled on 12:43:10 May  9 2019 with clang 4.2.1
```

**Describe the bug**

Changes made by mc_compact are lost for retransmits.

**To Reproduce**

1. Call mc_compact() before t_relay() to non-responsive destination
2. Observe Re-Transmits that are different from original message sent

**Expected behavior**

Re-Transmits should match the original message.

**Relevant System Logs**

No logs. See attached ngrep output.

**OS/environment information**
 - Operating System: CentOS 7
 - OpenSIPS installation: git/local builds

**Additional context**

[opensips_no_compact_retrans.txt](https://github.com/OpenSIPS/opensips/files/3163897/opensips_no_compact_retrans.txt)

**Comment by razvancrainea** [comment]
I've just tested this with the latest opensips 2.4 and it works just fine.
However, I couldn't find the commit you are using (e3f0e88), are you using some custom patches? Can you test with the latest official opensips 2.4 and tell us if this reproduces?

**Comment by rrb3942** [comment]
Going to close this bug for now. 

We moved away from mc_compact for our use case. The local patches we have in place are mostly just back-ports of PRs I have submitted (nothing that should affect this bug). 

If I get some time to revisit this and determine the exact configuration that causes it I will update this bug.
