### ISSUE TITLE
[BUG]OpenSIPS 3.0.0 - ERROR:cachedb_cassandra:execute_query: driver error: line 1:336 mismatched character

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1696]
**OpenSIPS 3.0.0**
```
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 142957c
main.c compiled on 19:12:09 May 13 2019 with gcc 5.4.0
```

**Describe the bug**
After OpenSIPS has started, contacts are inserting just fine in the cassandra DB using the UPDATE function for example 

`[25617]: DBG:cachedb_cassandra:cassandra_col_update: executing query: UPDATE "userdatakeyspace"."usrlocfull" USING TTL 0 SET "aorhash" = ?, "contacts"['c2lwOiszMDIxMDcwMDEzOThANDYuMTk4LjEyOS4xMzA6MzkxNjY7dHJhbnNwb3J0PVRjcDozMTM1MzUzNzM3MzYzMDM1MzAzMDM1MzczNTMyMzMtMjdmNHZpMnIyeXd1'] = ? WHERE "aor" = ?
`

After a while for some reason I can't understand some other UPDATE requests is showing the following errors in log files. I can't find a way to reproduce it but I am still investigating this on my side to help you further reproduce the issue.

**Relevant System Logs**

`DBG:cachedb_cassandra:cassandra_col_update: executing query: UPDATE "userdatakeyspace"."usrlocfull" USING TTL 0 SET "aorhash" = ?, "contacts"['c2lwOiszMDIxMDcwMDEzOTdANDYuMTk4LjEyOS4xMzA6NDQzMTM7dHJhbnNwb3J0PVRjcDtsaW5lPW1kNGJoOW00OjMxMzUzNTM2MzYzNzMwMzEzNjM4MzUzNTM5MzIzMS0zZHlreDloYmN1cHk='] = ?, "contacts"['c2lwOiszMDIxMDcwMDEzOTdANDYuMTk4LjEyOS4xMzA6NDgyMTQ7dHJhbnNwb"aor" = ? WHERE "aor" = ?
[24507]: ERROR:cachedb_cassandra:execute_query: driver error: line 1:336 mismatched character '<EOF>' expecting '''
[24507]: ERROR:cachedb_cassandra:cassandra_col_update: Cassandra 'update' failed`

**OS/environment information**
 - Operating System: Ubuntu 16.04.6 LTS
 - OpenSIPS installation: git master branch

**Comment by vtzan** [comment]
Further investigation shows that this is happening on Re-Registration requests while trying to do [save location function](https://opensips.org/html/docs/modules/3.0.x/registrar.html#func_save).

`[26060]: Route:handle_register:USER XXXXXXXXXX Saving AoR : sip:XXXXXXXXXX@domain
[26060]: ERROR:cachedb_cassandra:execute_query: driver error: line 1:336 mismatched character '<EOF>' expecting '''
[26060]: message repeated 2 times: [ ERROR:cachedb_cassandra:execute_query: driver error: line 1:336 mismatched character '<EOF>' expecting ''']
[26060]: ERROR:cachedb_cassandra:cassandra_col_update: Cassandra 'update' failed
[26060]: ERROR:usrloc:cdb_flush_urecord: cache update query for AoR XXXXXXXXXX@domain failed!
[26060]: ERROR:usrloc:release_urecord: failed to flush AoR XXXXXXXXXX@domain`

**Comment by liviuchircu** [comment]
Good news, @vtzan, we managed to reproduce the issue.  It seems it is directly related to REGISTERs with 2 or more contacts, and we are working on a fix.

**Comment by vtzan** [comment]
@liviuchircu Great news! thank you
