### ISSUE TITLE
Wheezy Debian packages removed from apt.opensips.org

### ISSUE THREAD

**Issue by jimbojd72** [OpenSIPS/opensips#1698]
It seems that debian wheezy repo has been removed from your repository, which I understand since Wheezy is EOL.

I would like to know if it would be possible to provide a FTP links or something similar so we could download the .deb package to put them on our own repository.

In my case, the version used on debian wheezy was:

```
version: opensips 2.3.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on  with gcc 4.7
```

Thanks for your support

**Comment by bogdan-iancu** [comment]
We do not have a copy of it (even for the future, it may be a good idea to have an archive repo or so).  Have you check if you do not have it in `/var/cache/apt/archives/` on one of the servers where the deb was installed?

**Comment by jimbojd72** [comment]
We were doing an `apt-get clean` in our build, so the packages were gone.

I was able to get over the issue by using `sudo dpkg-repack opensips` on a working server to regenerate opensips packages from local file and upload it manually to our own repo.

We have done the same for other opensip modules `opensips-postgres-module` or `opensips-http-modules` for example.

Is there any newsletters that we can subscribe to know about those deprecations before they happen? With a bit of time we would have been able to upgrade to debian stretch and opensips 2.4 before this packages removal.

**Comment by bogdan-iancu** [comment]
We do announce on the mailing list and also there is this status web page - https://opensips.org/About/AvailableVersions
