### ISSUE TITLE
debian9  opensips 2.4.5   load balance problem

### ISSUE THREAD

**Issue by pengwang18** [OpenSIPS/opensips#1700]
Hello asks you questions

The system is debian9 , compile and install opensips 2.4.5 make install   db:mysql    for load balancing. The back end of the system is freeswitch 192.168.100.33.
Opensips VIP  192.168.100.22   （keepalive）
freeswitch 192.168.100.33

Mysql:
INSERT INTO `opensips'. `load_balancer'(`id', `group_id', `dst_uri', `resources', `probe_mode', `description') VALUES (`1', `1', `sip: 192.168.100.33', `vm = 100; conf 100; = 100; PSTN = 500, `1', `transc 1');

The client connection cannot be forwarded to the back-end server 192.168.100.33

opensipsctl fifo lb_list
Destination:: sip: 192.168.100.33 id=1 group=1 enabled=yes auto-reenable=on
        Resources:: 
                Resource:: vm max=100 load=0
                Resource:: conf max=100 load=0
                Resource:: transc max=100 load=0
                Resource:: pstn max=500 load=0

opensipsctl fifo lb_status 1
enable:: yes

Opsiops log:

May 15:55:40 [28750]: DBG: core: udp_read_req: probing packet received len = 4

May 15:55:41 [28749]: DBG: core: parse_msg: SIP Request:

May 15:55:41 [28749]: DBG: core: parse_msg: method: <REGISTER>

May 15:55:41 [28749]: DBG: core: parse_msg: uri: <sip: xxx.xxxx.net>

May 15:55:41 [28749]: DBG: core: parse_msg: version: <SIP/2.0>

May 15:55:41 [28749]: DBG: core: parse_headers: flags = 2

May 15:55:41 [28749]: DBG: core: parse_via_param: found param type 232, <branch>= <z9hG4bK-524287-1 - "f12589562c62ea31>; state=6

May 15:55:41 [28749]: DBG: core: parse_via_param: found param type 235, < rport > = n/a >; state = 17

May 15:55:41 [28749]: DBG: core: parse_via: end of header reached, state = 5

May 15:55:41 [28749]: DBG: core: parse_headers: via found, flags = 2

May 15:55:41 [28749]: DBG: core: parse_headers: this is the first via

May 15:55:41 [28749]: DBG: core: receive_msg: After parse_msg...

May 15:55:41 [28749]: DBG: core: receive_msg: prepare to run routing scripts...

May 15:55:41 [28749]: DBG: core: parse_headers: flags = 100

May 15:55:41 [28749]: DBG: maxfwd: is_maxfwd_present: value = 70

May 15:55:41 [28749]: DBG: core: parse_headers: flags = 8

May 15:55:41 [28749]: DBG: core:_parse_to: end of header reached, state = 10

May 15:55:41 [28749]: DBG: core:_parse_to: display={"1002"}, ruri={sip:1002@xxxx.xxx.net}

May 15:55:41 [28749]: DBG: core: get_hdr_field: <To> [33]; uri= [sip: 1002@xxxx.xxxx.net]

May 15:55:41 [28749]: DBG: core: get_hdr_field: to body ["1002"<sip:1002@xxxx.xxx.net> #015]

May 15:55:41 [28749]: DBG: uri: has_totag: no totag

May 15:55:41 [28749]: DBG: core: parse_headers: flags = ffffffffffffffffffff

May 15:55:41 [28749]: DBG: core: get_hdr_field: cseq < CSeq >: < 1 > < REGISTER >

May 15:55:41 [28749]: DBG: core: get_hdr_field: content_length = 0

May 15:55:41 [28749]: DBG: core: get_hdr_field: found end of header

May 15:55:41 [28749]: DBG: core: destroy_avp_list: destroying list (nil)

May 15:55:41 [28749]: DBG: core: receive_msg: cleaning up

configuration file

####### Global Parameters #########

log_level=4
log_stderror=no
log_facility=LOG_LOCAL0

children=4

/* uncomment the following lines to enable debugging */
#debug_mode=yes

/* uncomment the next line to enable the auto temporary blacklisting of 
   not available destinations (default disabled) */
#disable_dns_blacklist=no

/* uncomment the next line to enable IPv6 lookup after IPv4 dns 
   lookup failures (default disabled) */
#dns_try_ipv6=yes

/* comment the next line to enable the auto discovery of local aliases
   based on reverse DNS on IPs */
auto_aliases=no

listen=udp:192.168.100.22:5060   # CUSTOMIZE ME

####### Modules Section ########

#set module path
mpath="/usr/local//lib64/opensips/modules/"

#### SIGNALING module
loadmodule "signaling.so"

#### StateLess module
loadmodule "sl.so"

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
/* do not append from tag to the RR (no need for this script) */
modparam("rr", "append_fromtag", 0)

#### MAX ForWarD module
loadmodule "maxfwd.so"

#### SIP MSG OPerationS module
loadmodule "sipmsgops.so"

#### FIFO Management Interface
loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)

#### URI module
loadmodule "uri.so"
modparam("uri", "use_uri_table", 0)

#### MYSQL module
loadmodule "db_mysql.so"

#### AVPOPS module
loadmodule "avpops.so"

#### ACCounting module
loadmodule "acc.so"
/* what special events should be accounted ? */
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
/* by default we do not adjust the direct of the sequential requests.
   if you enable this parameter, be sure the enable "append_fromtag"
   in "rr" module */
modparam("acc", "detect_direction", 0)

#### DIALOG module
loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 21600)  # 6 hours timeout
modparam("dialog", "db_mode", 2)
modparam("dialog", "db_url",
        "mysql://opensips:opensipspwd@192.168.2.191/opensips") # CUSTOMIZE ME

#### LOAD BALANCER module
loadmodule "load_balancer.so"
modparam("load_balancer", "db_url",
        "mysql://opensips: opensipspwd @192.168.2.191/opensips") # CUSTOMIZE ME
modparam("load_balancer", "probing_method", "OPTIONS")

modparam("load_balancer", "probing_interval", 30)

loadmodule "proto_udp.so"

####### Routing Logic ########

# main request routing logic

route{

        if (!mf_process_maxfwd_header("10")) {
                send_reply("483","Too Many Hops");
                exit;
        }

        if (has_totag()) {

                # handle hop-by-hop ACK (no routing required)
                if ( is_method("ACK") && t_check_trans() ) {
                        t_relay();
                        exit;
                }

                # sequential request withing a dialog should
                # take the path determined by record-routing
                if ( !loose_route() ) {
                        # we do record-routing for all our traffic, so we should not
                        # receive any sequential requests without Route hdr.
                        send_reply("404","Not here");
                        exit;
                }

                # validate the sequential request against dialog
                if ( $DLG_status!=NULL && !validate_dialog() ) {
                        xlog("In-Dialog $rm from $si (callid=$ci) is not valid according to dialog\n");
                        ## exit;
                }

                if (is_method("BYE")) {
                        # do accounting even if the transaction fails
                        do_accounting("log","failed");
                }

                # route it out to whatever destination was set by loose_route()
                # in $du (destination URI).
                route(RELAY);
                exit;
        }

        #### INITIAL REQUESTS

        # CANCEL processing
        if (is_method("CANCEL")) {
                if (t_check_trans())
                        t_relay();
                exit;
        } else if (!is_method("INVITE")) {
                send_reply("405","Method Not Allowed");
                exit;
        }

        if ($rU==NULL) {
                # request with no Username in RURI
                send_reply("484","Address Incomplete");
                exit;
        }

        t_check_trans();

        # preloaded route checking
        if (loose_route()) {
                xlog("L_ERR",
                        "Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]");
                if (!is_method("ACK"))
                        send_reply("403","Preload Route denied");
                exit;
        }

        # record routing
        record_route();

        do_accounting("log");

        if ( !lb_start("1","channel")) {

                send_reply("500","No Destination available");
                exit;
        }

        t_on_failure("GW_FAILOVER");

        route(RELAY);
}

route[RELAY] {
        if (!t_relay()) {
                sl_reply_error();
        }
        exit;
}

failure_route[GW_FAILOVER] {
        if (t_was_cancelled()) {
                exit;
        }

        # failure detection with redirect to next available trunk
        if (t_check_status("(408)|([56][0-9][0-9])")) {
                xlog("Failed trunk $rd/$du detected \n");

                if ( lb_next() ) {

                        t_on_failure("GW_FAILOVER");
                        t_relay();
                        exit;
                }

                send_reply("500","All GW are down");
        }
}

local_route {
        if (is_method("BYE") && $DLG_dir=="UPSTREAM") {

                acc_log_request("200 Dialog Timeout");

        }
}

**Comment by bogdan-iancu** [comment]
I would suggest you to place in the very top of your script the [script_trace()](https://opensips.org/Documentation/Script-CoreFunctions-2-4#toc42) function , so you can see the path taken by your request through the script . Maybe it never gets to the load balancing part.

**Comment by bogdan-iancu** [comment]
any update here ?

**Comment by bogdan-iancu** [comment]
time out
