### ISSUE TITLE
[FEATURE] Play Media With RTPEngine

### ISSUE THREAD

**Issue by eliakimfelmorais** [OpenSIPS/opensips#1703]
Hi Guys, I'd like to know if is possible to implement:

I was looking the  RTPEngine Module documentation(https://opensips.org/html/docs/modules/2.4.x/rtpengine.html) to migrate from RTPProxy (https://opensips.org/html/docs/modules/2.4.x/rtpproxy.html) and I did not find those commands in the module like the RTPProxy module had.

* rtpproxy_stream2uac
* rtpproxy_stream2uas

The documentation of RTPEngine have the command: play_media and Kamalio have too.
- https://github.com/sipwise/rtpengine#play-media-message 
- https://kamailio.org/docs/modules/5.3.x/modules/rtpengine.html#rtpengine.f.play_media

If is possible to implement those feature with the commands?

* rtpengine_stream2uac
* rtpengine_stream2ua

Thank you,

**Comment by razvancrainea** [comment]
Yes, we have this on our roadmap. I will update this ticket when this is implemented.

**Comment by eliakimfelmorais** [comment]
Thank you for the Reply Razvan!

**Comment by bshirazi** [comment]
Hi
According to 3.1 documentation it seems play media feature was implemented.
Thank You !  When it's package is available ?
Regards

**Comment by razvancrainea** [comment]
Packaging will be available as soon as OpenSIPS 3.1 is released, most likely in April 2020.
