### ISSUE TITLE
[BUG] Permission Module: insert ipv6 Addresses 

### ISSUE THREAD

**Issue by rzerres** [OpenSIPS/opensips#1712]
**OpenSIPS v3.0.0**
version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 470d7148e
main.c compiled on 19:51:59 May 27 2019 with gcc 9.1.0

**GUI insert of a ipv6 Address**
When using opensip-cl to insert an ipv6 address to the permission table it will decline with an error.

**Table: Permissions**
1. Start OpenSIPS-CP (git version)
2. Open HTTPS web-url
3. Menu: Permissions
4. Button: Add Address
5. Insert values
* Group: 10
* Address: 2003:17:452:110:: (Netmask for a /64 subnet)
* Mask: 64
* Port: 5060
* Protocol: TCP

--> !!! Invalid IP address, the entry was not modified in the database 

The same error message will be shown, if ipv6 is precise (e.g: 2003:4444:452:110:0:0:0:10; Mask: 128)
Seems like the input parser isn't capable.

**Expected behavior**
new table entry with the given values.

**OS/environment information**
 - Operating System: arch-linux
 - OpenSIPS installation: arch packages (opensips-git, opensips-modules-git

**Improvement**
accept the ipv6 address in brackets, like 
* pecisely on node:  [<4d>colon<4d>colon<4d>colon<4d>colon<4d>colon<4d>colon<4d>colon<4d>] * nodes netmaks:    [<[a-fA-F0-9]>colon<[a-fA-F-0-9]>colon colon<a-FA-F0-9>]

**Comment by razvancrainea** [comment]
This looks like a ticket for OpenSIPS CP, which is a [different project](https://github.com/OpenSIPS/opensips-cp/).
Could you please close this ticket and open it on the CP project? In the future I might be able to transfer it, but currently this feature is in beta, and it doesn't work at all for me :)

**Comment by rzerres** [comment]
ok. I will follow your advise. I thought it might be correllated to the ipv6 parsing in opensips itself.
Anyway, i will reopen as a new issue to OpenSIPS CP
