### ISSUE TITLE
[CRASH] OpenSIPS 3.0.0 - async + cgrates_cmd Crashes randomly

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1713]
**OpenSIPS version you are running**
```
version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 1dae7c50f
main.c compiled on 11:04:36 May 27 2019 with gcc 6.3.0
```

I don't know this matter  but I am also using autoscaling:

```
auto_scaling_profile = SIP_WORKERS
     scale up to 25 on 80% for 4 cycles within 5
     scale down to 5 on 20% for 10 cycles

udp_workers = 5 use_auto_scaling_profile SIP_WORKERS
listen=udp:MY_PRIVATE_IP:SIP_BIND_PORT use_auto_scaling_profile SIP_WORKERS
```

**Crash Core Dump**
https://pastebin.com/his9EMRX

**Describe the traffic that generated the bug**
This happened when a request was trying this cgrates_cmd + async function.

`async(cgrates_cmd("SessionSv1.AuthorizeEventWithDigest"), cgr_auth_reply);`

**Relevant System Logs**

/usr/local/opensips/sbin/opensips[2201]: CRITICAL:core:sig_usr: segfault in process pid: 2201, id: 15
qkernel: [240031.494518] opensips[2201]: segfault at 0 ip           (null) sp 00007ffeb72fe548 error 14 in opensips[561ec8656000+23e000]

Core file is available if you need any further debugging on this.

Thank you
Vasilios Tzanoudakis

**OS/environment information**
 - Operating System: Debian 9.9
 - OpenSIPS installation: opensips 3.0.0-beta

**Comment by razvancrainea** [comment]
Do you have a core dump for this?
Also, do you happen to know what type of process PID 2201 is? Is it timer, MI, or something else?

**Comment by vtzan** [comment]
Dear @razvancrainea 

Yes I have the core dump. 
No I don't know what type was process pid 2201.

**Comment by razvancrainea** [comment]
Right, apologies, I missed the core in your report. Checking this now...

**Comment by razvancrainea** [comment]
I suspect it crashes when it's under load, is that correct?
If so, as a temporary solution, you can try to increase the [max_async_connections](https://opensips.org/html/docs/modules/3.0.x/cgrates.html#param_max_async_connections) parameter. In the meantime I will investigate and try to figure out how to fix this.

**Comment by razvancrainea** [comment]
In gdb, can you run:
```
f 2
p *c
```

**Comment by vtzan** [comment]
```
(gdb) f 2
#2  0x00007f8ed0f28707 in cgrc_async_read (c=0x7f8ee213b2a0, f=0x0, p=0x0) at cgrates_common.c:721
721			ret = cgrates_process(jobj, c, f, p);

(gdb) p *c
$1 = {fd = 338, flags = 1 '\001', state = CGRC_FREE, disable_time = 0, engine = 0x7f8ee1bca6a8, jtok = 0x560d33732090, list = {prev = 0x7f8ee1bca6f8, next = 0x7f8ee1bca6f8}}

```

**Comment by razvancrainea** [comment]
Do you have any logs from the time before the crash?

**Comment by vtzan** [comment]
let me try to reproduce it with debug level 6 and get back to you.
thank you

**Comment by vtzan** [comment]
Dear @razvancrainea 

here it is: 

`DBG:core:destroy_avp_list: destroying list (nil)
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:core:destroy_avp_list: destroying list (nil)
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:dialog:next_state_dlg: dialog 0x7ff8f2a12c50 changed from state 1 to state 5, due event 4
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:dialog:dlg_onreply: dialog 0x7ff8f2a12c50 failed (negative reply)
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:dialog:unref_dlg: unref dlg 0x7ff8f2a12c50 with 1 -> 2 in entry 0x7ff8f2948510
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:clean_msg_clone: removing hdr->parsed 7
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:cleanup_uac_timers: RETR/FR timers reset
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:set_timer: relative timeout is 500000
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:insert_timer_unsafe: [4]: 0x7ff8f2a14668 (9800000)
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:insert_timer_unsafe: [0]: 0x7ff8f2a14698 (14)
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:_reply_light: reply sent out. buf=0x7ff8f4718430: SIP/2.0 4..., shmem=0x7ff8f2a17e98: SIP/2.0 4
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:run_trans_callbacks: trans=0x7ff8f2a14520, callback type 128, id 3 entered
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:_reply_light: finished
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:do_t_cleanup: transaction 0x7ff8f2a14520 already updated! Skipping update!
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:tm:t_unref: UNREF_UNSAFE: [0x7ff8f2a14520] after is 0
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:dialog:unref_dlg: unref dlg 0x7ff8f2a12c50 with 1 -> 1 in entry 0x7ff8f2948510
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrc_async_read: Event on fd 13 from 10.132.0.9:2014
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrc_async_read: Received (possible partial) json: {{"method":"SessionSv1.GetActiveSessionIDs","params":[""],"id":2}#012}
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrates_process: Processing JSON-RPC: { "method": "SessionSv1.GetActiveSessionIDs", "params": [ "" ], "id": 2 }
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrates_process: treating JSON-RPC as a request
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: INFO:cgrates:cgrates_process_req: Received new request method=SessionSv1.GetActiveSessionIDs param=0x5643de2c3440
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrates_process_req: sending json response: { "error": null, "result": [ ], "id": 2 }
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24425]: DBG:cgrates:cgrc_send: Successfully sent 41 bytes
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:cgrates:cgrc_async_read: Event on fd 338 from 10.132.0.9:2014
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:cgrates:cgrc_async_read: Received (possible partial) json: {{"id":2000396352,"result":{"AttributesDigest":null,"ResourceAllocation":null,"MaxUsage":-1,"SuppliersDigest":null,"Thresholds":"THD_ACNT_+30XXXXXXXX","StatQueues":null},"error":null}#012}
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:cgrates:cgrates_process: Processing JSON-RPC: { "id": 2000396352, "result": { "AttributesDigest": null, "ResourceAllocation": null, "MaxUsage": -1, "SuppliersDigest": null, "Thresholds": "THD_ACNT_+30XXXXXXXX", "StatQueues": null }, "error": null }
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:cgrates:cgrates_process: treating JSON-RPC as a reply
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: CRITICAL:core:sig_usr: segfault in process pid: 24448, id: 15
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:core:restore_segv_handler: restoring SIGSEGV handler...
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24448]: DBG:core:restore_segv_handler: successfully restored system SIGSEGV handler
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrc_async_read: Event on fd 13 from 10.132.0.9:2014
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrc_async_read: Received (possible partial) json: {{"method":"SessionSv1.GetActiveSessionIDs","params":[""],"id":2}#012}
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrates_process: Processing JSON-RPC: { "method": "SessionSv1.GetActiveSessionIDs", "params": [ "" ], "id": 2 }
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrates_process: treating JSON-RPC as a request
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: INFO:cgrates:cgrates_process_req: Received new request method=SessionSv1.GetActiveSessionIDs param=0x5643de2d98c0
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrates_process_req: sending json response: { "error": null, "result": [ ], "id": 2 }
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:cgrates:cgrc_send: Successfully sent 41 bytes
May 29 08:22:19 sip-1-de /usr/local/opensips/sbin/opensips[24445]: DBG:core:ipc_handle_job: received job type 0[RPC] from process 1`

**Comment by razvancrainea** [comment]
Any chance you could post logs a couple of seconds before that?

**Comment by vtzan** [comment]
Dear @razvancrainea,

Please check your email and let me know if you got them.

thank you

**Comment by vtzan** [comment]
I don't know if this can help you somehow but it seems that I am not able to reproduce it if i have DISABLED Auto scaling....

**Comment by razvancrainea** [comment]
Thanks for the logs, I managed to replicate this. I am working on a fix now.
I currently doubt it's a problem with auto scaling, at least the logs you've sent me indicate they are not related. I managed to reproduce this without auto scaling too.
But after I fix the problem I found, we can try to replicate with auto scaling, check if there's another issue.

**Comment by vtzan** [comment]
Sure great! thanks

**Comment by vtzan** [comment]
I have just replicated without autoscaling so you are right.

**Comment by razvancrainea** [comment]
I've just pushed a commit on master branch. Any chance you could get if from there and test again? Or would you rather first backport it to 3.0?

**Comment by vtzan** [comment]
I am using the master branch. I will compile now

**Comment by vtzan** [comment]
something is change has created another issue with async.

I see that this request 
async(cgrates_cmd("SessionSv1.AuthorizeEventWithDigest"), route_reply);

after execution it doesn't go to the route_reply route.


```
Ask CGRates --> SessionSv1.AuthorizeEventWithDigest 
DBG:cgrates:cgr_get_ctx new ctx=0x7f86f0f55db8
DBG:cgrates:cgr_new_real_kv created new key Tenant
DBG:cgrates:pv_set_cgr add cgr kv
DBG:cgrates:cgr_new_real_kv created new key Account
DBG:cgrates:pv_set_cgr add cgr kv
DBG:cgrates:cgr_new_real_kv created new key GetAttributes
DBG:cgrates:pv_set_cgr add cgr kv
DBG:tm:t_newtran transaction on entrance=0xffffffffffffffff
DBG:core:parse_headers flags=ffffffffffffffff
DBG:core:get_hdr_field cseq <CSeq>
DBG:core:get_hdr_field content_length=0
DBG:core:get_hdr_field found end of header
DBG:core:parse_headers flags=78
DBG:tm:t_lookup_request start searching
DBG:tm:matching_3261 RFC3261 transaction matched, tid=-ssy6rymmtxmm
DBG:tm:t_lookup_request REF_UNSAFE:[0x7f86f0f52af8] after is 2
DBG:tm:t_lookup_request transaction found (T=0x7f86f0f52af8)
DBG:tm:t_retransmit_reply nothing to retransmit
```
And it seems to stop there and not continuing to the reply route.

thanks

**Comment by razvancrainea** [comment]
does this happen on a normal call, or after you stress it out a bit?

**Comment by razvancrainea** [comment]
Also, could you send me all logs please?

**Comment by vtzan** [comment]
Dear @razvancrainea,

Please check your email.
thank you

**Comment by razvancrainea** [comment]
You didn't say if this happens all the time, or after high load :).

**Comment by vtzan** [comment]
sorry it happens all the time. I will apply the patch now and let you know.

**Comment by vtzan** [comment]
Dear @razvancrainea 

Problem fixed. I will continue testing and let you know.
thank you for your support!!!

**Comment by razvancrainea** [comment]
Perfect, thanks for confirming!
