### ISSUE TITLE
[BUG] OpenSIPS 3.0.0-beta - when  event_rabbitmq sync_mode = 1

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1717]
**OpenSIPS 3.0.0-beta**

```
version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b14e87109
main.c compiled on 14:56:03 May 29 2019 with gcc 6.3.0
```

**Describe the bug**

when sync_mode is changed from 0 to --> 1 
modparam("event_rabbitmq", "sync_mode", 1) # synchronous

**Relevant System Logs**
```
NOTICE:rabbitmq:mod_init initializing RabbitMQ module ...
NOTICE:event_rabbitmq:mod_init initializing module ......
NOTICE:event_rabbitmq:mod_init heartbeat is enabled for [3] seconds
NOTICE:regex:mod_init 'file' parameter is not set, group matching disabled
NOTICE:event_route:mod_init initializing module ...
ERROR:event_rabbitmq:rmq_init_reader fcntl failed
WARNING:core:utimer_ticker utimer task <tm-utimer> already scheduled 100 ms ago (now 200 ms), delaying execution
WARNING:core:utimer_ticker utimer task <tm-utimer> already scheduled 190 ms ago (now 290 ms), delaying execution
CRITICAL:core:io_watch_add #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f88d96bd100)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f88d96bd100)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f88d96bd100,flags=1) already=0
WARNING:core:handle_timer_job utimer job <tm-utimer> has a 290000 us delay in execution
WARNING:core:utimer_ticker utimer task <tm-utimer> already scheduled 290 ms ago (now 390 ms), delaying execution
CRITICAL:core:io_watch_add #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f88d96bd100)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f88d96bd100)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add [UDP_worker] check failed after successful fd add (fd=13,type=2,data=0x7f88d96bdd50,flags=1) already=0
CRITICAL:core:io_watch_add #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f88d96bdd90)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f88d96bdd90)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f88d96bdd90,flags=1) already=0
CRITICAL:core:io_watch_add #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f88d96bdd90)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f88d96bdd90)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
CRITICAL:core:io_watch_add [UDP_worker] check failed after successful fd add (fd=13,type=2,data=0x7f88d96bdff8,flags=1) already=0
WARNING:drouting:dr_load_routing_info table "dr_rules" is empty
WARNING:dialplan:dp_load_db no data in the db
```

**OS/environment information**
 - Operating System: Debian 9.9
 - OpenSIPS installation: git master

**Comment by razvancrainea** [comment]
@vtzan I see the `ERROR:event_rabbitmq:rmq_init_reader fcntl failed` erorr - I am pretty sure there's something else on that line explaining why it failed :), we could use that.

**Comment by razvancrainea** [comment]
Any updates here :)?

**Comment by vtzan** [comment]
The line is this:
`modparam("event_rabbitmq", "sync_mode", 1)
`

And still getting : 

Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2884]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a3958)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2884]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a3958)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2884]: CRITICAL:core:io_watch_add: [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a3958,flags=1) already=0
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2877]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a3aa8)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2877]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a3aa8)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2877]: CRITICAL:core:io_watch_add: [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a3aa8,flags=1) already=0
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2907]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 2 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a3b18)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2907]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a3b18)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2907]: CRITICAL:core:io_watch_add: [TCP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a3b18,flags=1) already=0
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2887]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a3bf8)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2887]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a3bf8)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2887]: CRITICAL:core:io_watch_add: [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a3bf8,flags=1) already=0
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2891]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 3 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a3d48)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2891]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a3d48)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2891]: CRITICAL:core:io_watch_add: [UDP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a3d48,flags=1) already=0
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2897]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2897]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 172
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2924]: CRITICAL:core:io_watch_add: #012>>> fd_array idx 2 (fd=0) points to bogus map (fd=0,type=2,flags=1,data=0x7f8cc23a4170)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2924]: CRITICAL:core:io_watch_add: #012>>> used fd map fd=0 has bogus data (fd=0,type=2,flags=20000001,data=0x7f8cc23a4170)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jun 25 11:27:49 sip-1-de /usr/local/opensips/sbin/opensips[2924]: CRITICAL:core:io_watch_add: [TCP_worker] check failed after successful fd add (fd=0,type=2,data=0x7f8cc23a4170,flags=1) already=0

let me know how to help you more on this.
thank you
