### ISSUE TITLE
[CRASH] segfault in update_cloned_msg_from_msg

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#1724]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 11:13:56 Jun  3 2019 with gcc 6.3.0
```

**Crash Core Dump**

Jun  4 14:13:21 opensips24egress /usr/local/opensips_proxy/sbin/opensips[16389]: CRITICAL:core:sig_usr: segfault in process pid: 16389, id: 41
Jun  4 14:13:21 opensips24egress kernel: [83292.491879] opensips[16389]: segfault at 28 ip 00007f405cd04584 sp 00007ffd4a8e8820 error 6 in tm.so[7f405cc97000+8d000]

See coredump here: https://pastebin.com/DVeVFsmr

**Describe the traffic that generated the bug**

In my test environment, I am sending ~100CPS of standard SIP INVITE.

**To Reproduce**

Crash is sporadic. Start OpenSIPS, and after 10-30mins of test traffic crash occurs.

**Relevant System Logs**

Segfault appears to be early in thread life cycle, and as such I don't see any meaningful logs from my script.

**OS/environment information**
 - Operating System: Debian 9
 - OpenSIPS installation: git

**Additional context**

Please let me know if you need any additional information to help debug.

**Comment by razvancrainea** [comment]
This should have been fixed in latest 2.4. Please pull the latest sources, try again and let us know if this is still happening. Cheers,

**Comment by john08burke** [comment]
You are correct, I pulled the code and have not gotten a segfault after several tests. Apologies for the duplicate crash report.

Is there a tentative release date in mind for 2.4.6?

**Comment by razvancrainea** [comment]
Depending on how we manage to close the current tickets, we are planning to release 2.4.6 next week, or the week after.
There's no problem for the duplicate report, luckily the issue has been solved :). Cheers!
