### ISSUE TITLE
Compilation fails with version 3.0: 'shm_block' undeclared

### ISSUE THREAD

**Issue by lukasbraach** [OpenSIPS/opensips#1725]
**Describe the bug**
When I start the compilation of the newest 3.0 release on Debian 8, the recipe for make target 'serialize.o' fails:
```
mem/../mem/shm_mem.h: In function ‘shm_get_frags’:
mem/../mem/shm_mem.h:755:23: error: ‘shm_block’ undeclared (first use in this function)
  return SHM_GET_FRAGS(shm_block);
                       ^
Makefile.rules:25: recipe for target 'serialize.o' failed
make: *** [serialize.o] Error 1
```
**To Reproduce**
Clone the GitHub repository with branch 3.0, configure with `make menuconfig` and install the required dependencies. Then start compilation with `make all`.

**Expected behavior**
the compilation should succeed

**OS/environment information**
 - Operating System: Debian 8.0
 - OpenSIPS installation: cloned from git (using branch 3.0)

**Additional context**
Compilation of OpenSIPS 2.4.5 LTS works flawlessly. Debian runs on a Raspberry Pi. Additionally I am quite unexperienced with OpenSIPS...

**Comment by liviuchircu** [comment]
Thanks for the report!  With @razvancrainea's help, we were able to reproduce this issue on an arm arch.  A fix will be available soon!
