### ISSUE TITLE
Can not find opensipsdbctl tool in version 3.0

### ISSUE THREAD

**Issue by anuranBarman** [OpenSIPS/opensips#1732]
I am following the documentation of how to deploy mysql database with opensips. In that a command line tool **opensipsdbctl** is mentioed which is not present in my case. 
My install directory was in /usr/local but that tool does not exist in /sbin. only availables files are the  executable opensips and osipsconfig. Where can I get this?

**Comment by bogdan-iancu** [comment]
The `opensipsdbctl` was deprecated and its functionality is now provide by the [opensips-cli](https://github.com/OpenSIPS/opensips-cli). Could you point out the 3.0 docs still mentioning the `opensipsdbctl` tool, so we can fix it ?

**Comment by anuranBarman** [comment]
I see. Here is the link of the documentation where it's still referring the opensipsdbctl
https://www.opensips.org/Documentation/Install-DBDeployment-3-0 
**Section 2: Create the database**

**Comment by bogdan-iancu** [comment]
OK, thank you , @razvancrainea will take care and update the page.

**Comment by razvancrainea** [comment]
Done, updated docs for both [3.0](https://www.opensips.org/Documentation/Install-DBDeployment-3-0) and [3.1](https://www.opensips.org/Documentation/Install-DBDeployment-3-1). Thanks for reporting it!

**Comment by ehrenmann1977** [comment]
opensips-cli does not exist also

**Comment by razvancrainea** [comment]
opensips-cli is a different project and can be found [here](https://github.com/OpenSIPS/opensips-cli)

**Comment by crami** [comment]
There is an other place mentioning this tool: https://www.opensips.org/Documentation/Tutorials-OpenSIPSFreeSwitchIntegration

**Comment by razvancrainea** [comment]
@crami that is fine - opensips prior version 3.0 was using opensipsdbctl - that tutorial is done based on OpenSIPS 1.8, when opensipsdbctl was the only tool available.
Starting with OpenSIPS 3.0 opensipsdbctl and opensipsctl tools have been deprecated and replaced by opensips-cli.

**Comment by Superredstone** [comment]
The following page still mentions opensipsdbctl: https://opensips.org/Documentation/Tutorials-OpenSIPSAsteriskIntegration
