### ISSUE TITLE
[CRASH]Segfault after update - Related to Dialog Pinging

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#1733]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d3162df
main.c compiled on 13:32:11 Jun 12 2019 with gcc 8
```

**Crash Core Dump**

Backtrace:
[opensips_options_crash_backtrace.txt](https://github.com/OpenSIPS/opensips/files/3283098/opensips_options_crash_backtrace.txt)

**Describe the traffic that generated the bug**

**To Reproduce**
1. Enable Dialog Pinging (we use OPTIONS)
2. Setup a call
3. Wait for Dialog ping to fire and crash opensips

**OS/environment information**
 - Operating System: Centos 7
 - OpenSIPS installation: git
 - other relevant information:

**System Log**
[ 2505.472837] opensips[5649]: segfault at 0 ip           (null) sp 00007ffd2650ece8 error 14 in opensips[400000+1e6000]

**Additional context**

Seems to be caused by this commit:
https://github.com/OpenSIPS/opensips/commit/1b3ff7be4ed9cc2fc82ba85305040f2f986885f6

We do NOT have dialog replication/clustering enabled.

**Comment by bogdan-iancu** [comment]
The issues was a missing backport from head/3.0 ( 65ae04c892d2869be4a56049adcea70666e97dc8 ). I just did the backport to 2.4 ( 072b7a6 ), please update and it should be fine.
