### ISSUE TITLE
[CRASH] 2.4.6 crashes when using dialog pinging with re-Invite

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1736]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: edef893c5
main.c compiled on 22:16:27 Jun 18 2019 with gcc 7
```

**Crash Core Dump**
[crash bt.txt](https://github.com/OpenSIPS/opensips/files/3306426/crash.bt.txt)

**Describe the traffic that generated the bug**

OpenSIPS crashes shortly after the first re-Invite ping is sent. The logs seem to indicate it may be one of the responses that is actually causing the crash, although it appears to be the sending process ID that is crashing.

**To Reproduce**

1. Start OpenSIPS
2. Run a single call with dialog and re-Invite pinging enabled.

**Relevant System Logs**

[crash logs.txt](https://github.com/OpenSIPS/opensips/files/3306435/crash.logs.txt)

**OS/environment information**
 - Operating System:  Docker amazonlinux:2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
This was fixed like a month ago by @liviuchircu via 072b7a678636c2a2bb90ad8bd567a6c610feeaf2

**Comment by bcnewlin** [comment]
Per my OpenSIPS version information provided with the ticket, the commit I was using when I encountered the crash already includes what you have indicated is the fix, yet I still got a crash.

**Comment by bcnewlin** [comment]
I see. The commit you linked was against another branch. This was only backported to 2.4 after the 2.4.6 release.
