### ISSUE TITLE
[BUG] add_path_received() not add received parameters in path head filed

### ISSUE THREAD

**Issue by tangshiixang** [OpenSIPS/opensips#1739]
My opensips version is 3.0. The client communicates with opensips through the tls, and the opensips forward register message to freeswitch over tcp. Before  forwarding, I use add_path_received(), this call success, but no received parameters in path head filed.

**Comment by bogdan-iancu** [comment]
@tangshiixang , please update from GIT and give it a try - a fix is now available. If you can confirm it, it would be great :)
Thanks for your report!

**Comment by tangshiixang** [comment]
@bogdan-iancu it's ok. Thanks for your work.
