### ISSUE TITLE
[BUG] 100 Trying not sent by t_newtran when async is invoked after

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1740]
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 60097425d
main.c compiled on 15:51:41 Jun 21 2019 with gcc 7
```

**Describe the bug**

The [t_newtran function](https://opensips.org/html/docs/modules/2.4.x/tm.html#func_t_newtran) is supposed to cause a 100 Trying to be send back to the originator. We have found that when this is called prior to an async query the 100 response is sometimes not sent. When the async function returns quickly, the error is only intermittent. If the async query times out, the 100 Trying is never sent.

**To Reproduce**

[This config script](https://pastebin.com/SC3ZWvnt) can be used to reproduce the issue consistently.

**Expected behavior**

The 100 Trying response should be sent back immediately after t_newtran invocation and should not be delayed or cancelled by subsequent async queries.

**Relevant System Logs**

[Here are the logs](https://pastebin.com/1c82e2Uh) generated from running the config script provided above.

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
Apologies, I realize now I had a misconfiguration. There is still some unexplained behavior happening, but this issue does not properly describe it.

**Comment by bogdan-iancu** [comment]
I love the self-closing tickets :)
