### ISSUE TITLE
[BUG] Fifo Reload Lua module does not apply configuration

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1745]
**OpenSIPS version you are running**
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3fe6c3804
main.c compiled on 23:53:01 Apr 12 2019 with gcc 7

**Describe the bug**
When using the opensipsctl fifo lua_reload command, configuration changes are not applied.

**To Reproduce**
1. Start OpenSIPS in Docker
2. I make changes to the code of the configuration file
3. I use the console I execute the command, opensipsctl fifo lua_reload
4. command result 200 xOK pid:: 19

**Expected behavior**
Result of restarting lua module new configuration

**Relevant System Logs**
no lua records in the journal

**OS/environment information**
 - Operating System: Debian GNU/Linux 9.9 (stretch)
 - OpenSIPS installation: git/source/

**Additional context**
Is there any other possibility to apply the configuration without restarting the service, now the open source is started in the background using the Docker container with the following command:
/usr/local/sbin/opensips -F -E /var/log/opensips/opensips.log -P /var/run/opensips/opensips.pid -m 512 -M 64 -u opensips -g opensips -f /usr/local/etc/opensips/extensions/opensips.cfg

**Comment by bogdan-iancu** [comment]
Let's keep this open, as it was not even investigated.
