### ISSUE TITLE
[BUG] rtpproxy sessions not deleted

### ISSUE THREAD

**Issue by fammollo** [OpenSIPS/opensips#1746]
**OpenSIPS version you are running**

```
version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 00:00:54 Oct 20 2016 with gcc 4.8.5
```

**Describe the bug**

Hello,

full occupation of sessions on rtpproxy happened yesterday (ERROR:rtpproxy:force_rtp_proxy_body: unhandled rtpproxy error: 71/72).
I looked for sessions on the rtpproxy that terminated only after reaching the maximum timeout without RTP, and I found at least two cases that seem to be related to bad SIP signalling.
We are using rtpproxy_engage (dialog.so is loaded and it is using the default value for dialog timeouts) so I expect that opensips deallocates sessions on the rtpproxy upon their destruction.

Best regards,
Fabrizio

**To Reproduce**

SIP traffic like in the log files I attached is received and processed.

**Expected behavior**

The sessions on the rtpproxy should terminate as expected, not only after the timeout expires.

**Relevant System Logs**

I am attaching the files related to the two cases but only the lines containing the SIP call-id, not the other ones also related to those two calls; if they are required, I can extract them, even though I don't think that those related to opensips  can be useful, because the log level was set to 2.

- First case:

opensips log:
[54323ff2-7b95-e911-9b25-0050569632e2@acnct7-cti1.opensips.log](https://github.com/OpenSIPS/opensips/files/3329418/54323ff2-7b95-e911-9b25-0050569632e2%40acnct7-cti1.opensips.log)

rtpproxy log:
[54323ff2-7b95-e911-9b25-0050569632e2@acnct7-cti1.rtpproxy.log](https://github.com/OpenSIPS/opensips/files/3329419/54323ff2-7b95-e911-9b25-0050569632e2%40acnct7-cti1.rtpproxy.log)

- Second case:

opensips log:
[fa159cfe-c495-e911-9b25-0050569632e2@acnct7-cti1.opensips.log](https://github.com/OpenSIPS/opensips/files/3329420/fa159cfe-c495-e911-9b25-0050569632e2%40acnct7-cti1.opensips.log)

rtpproxy log:
[fa159cfe-c495-e911-9b25-0050569632e2@acnct7-cti1.rtpproxy.log](https://github.com/OpenSIPS/opensips/files/3329421/fa159cfe-c495-e911-9b25-0050569632e2%40acnct7-cti1.rtpproxy.log)

**OS/environment information**
 - Operating System: CentOS Linux release 7.5.1804 (Core)
 - OpenSIPS installation: original sources + a few patches (mainly within the rest_client module)
 - other relevant information: 

**Additional context**

**Comment by razvancrainea** [comment]
From what I can see in the logs, OpenSIPS does indeed delete the session when BYE is received, but it immediately re-starts it due to sequential messages. From what I can see in the logs, you are sending or receiving INVITEs and ACK messages *after* BYE is sent. This seems to be some broken signalling, resulting in broken instructions sent from OpenSIPS to RTPProxy.
Does this happen for every call, or just for some weird traffic? Could you also provide a PCAP for the logs?

**Comment by fammollo** [comment]
Hello,

this seems to be a temporary problem that happened only yesterday, with an unusually very high number of incoming/concurrent calls. Unfortunately I am not able to provide you any capture or any other kind of log files.

By your opinion, with this kind of weird SIP traffic, the problem could be avoided with some kind of additional configuration?
Unfortunately I cannot shorten the timeout configured onto the rtpproxy (I know that it is very high).

Thank you and best regards,
Fabrizio

**Comment by razvancrainea** [comment]
IMO, if this happens only once in a while, there's no real issue :). It's just some extra resources stuck on rtpproxy (probably something like a session per hour vs thousands of correct ones).
Unfortunately I don't see any additional configuration that could sort this out, without affecting the legit traffic as well.
