### ISSUE TITLE
[FEATURE] opensips2.4.6 Proxy freeswitch the  phone can't get through.

### ISSUE THREAD

**Issue by yuexiajiayan** [OpenSIPS/opensips#1747]
i use opensips.cfg like this
log_level=4
sip_warning=0
log_stderror=no
log_facility=LOG_LOCAL0
log_name="opensips"
debug_mode=no
children=4
dns_try_ipv6=no
auto_aliases=no
listen=udp:192.168.0.2:6060
mpath="/usr/local//lib64/opensips/modules/"
 
loadmodule "db_mysql.so"
loadmodule "signaling.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "rr.so"
loadmodule "uri.so"
loadmodule "dialog.so"
loadmodule "maxfwd.so"
loadmodule "textops.so"
loadmodule "mi_fifo.so"
loadmodule "dispatcher.so"
loadmodule "load_balancer.so"
loadmodule "sipmsgops.so"
loadmodule "proto_udp.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo") 

modparam("dialog", "db_mode", 1)
modparam("dialog", "db_url", "mysql://opensips:opensipsrw@localhost/opensips") 

modparam("rr", "enable_double_rr", 1)
modparam("rr", "append_fromtag", 1)

modparam("tm", "fr_timeout", 2) 

modparam("dispatcher", "db_url", "mysql://opensips:opensipsrw@localhost/opensips")
modparam("dispatcher", "ds_ping_method", "OPTIONS")
modparam("dispatcher", "ds_ping_interval", 5)
modparam("dispatcher", "ds_probing_threshhold", 2)
modparam("dispatcher", "ds_probing_mode", 1)

modparam("load_balancer", "db_url", "mysql://opensips:opensipsrw@localhost/opensips")
modparam("load_balancer", "probing_method", "OPTIONS")
modparam("load_balancer", "probing_interval", 5)

route{
 
        if (!mf_process_maxfwd_header("10")) {
		        xlog("L_INFO", " 0 ");
                sl_send_reply("483","Too Many Hops");
                exit;
        }
 
        if (!has_totag()) {
		        xlog("L_INFO", " 1 ");
                record_route();
        }
        else {
		        xlog("L_INFO", " 2 ");
                loose_route();
                t_relay();
                exit;
        }
        if (is_method("CANCEL")) {
		        xlog("L_INFO", " CANCEL ");
                if ( t_check_trans() )
                        t_relay();
                exit;
        }
        if (is_method("INVITE")) {
		        xlog("L_INFO", "INVITE ");
                if (!load_balance("1","pstn","1")) {
                        send_reply("503","Service Unavailable");
                        exit;
                }
        }
        else if (is_method("REGISTER")) {
		        xlog("L_INFO", "REGISTER ");
                if (!ds_select_dst("1", "4")) {
                        send_reply("503","Service Unavailable");
                        exit;
                }
        }
        else {
				xlog("L_INFO", "405 ");
                send_reply("405","Method Not Allowed");
                exit;
        }
        if (!t_relay()) {xlog("L_INFO", "405 error ");
                sl_reply_error();
        }
}

=========================

INSERT INTO load_balancer(id, group_id, dst_uri, resources, probe_mode, description) VALUES ('1', '1', 'sip:ip:7050', 'vm=100;conf=100;transc=100;pstn=500', '1', 'FS1');

opensipsctl dispatcher addgw 1 sip:ip:7040 '' 0 50 'FS1' 'gg1'

=========================
and change freeswitch conf/vars.xml  domain=opensips public ip
1000 1001  reg ok
 but i use 1000 call 1001 show this：
(
 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 1(2368) [MI FIFO] terminated, still waiting for 7 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 2(2369) [time_keeper] terminated, still waiting for 6 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 3(2370) [timer] terminated, still waiting for 5 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 4(2371) [SIP receiver udp:192.168.0.2:6060 ] terminated, still waiting for 4 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 5(2372) [SIP receiver udp:192.168.0.2:6060 ] terminated, still waiting for 3 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 6(2373) [SIP receiver udp:192.168.0.2:6060 ] terminated, still waiting for 2 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 7(2374) [SIP receiver udp:192.168.0.2:6060 ] terminated, still waiting for 1 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:shutdown_opensips: process 8(2375) [Timer handler] terminated, still waiting for 0 more
Jun 27 20:29:07 ecs-sn3-large-2-linux-20190621115558 opensips[2366]: INFO:core:cleanup: cleanup
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips: INFO:core:fix_poll_method: using epoll as the IO watch method (auto detected)
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips: WARNING:core:fix_socket_list: could not rev. resolve 192.168.0.2
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: NOTICE:core:main: version: opensips 2.4.6 (x86_64/linux)
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:main: using 32 Mb of shared memory
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:main: using 2 Mb of private process memory
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: WARNING:core:init_reactor_size: shrinking reactor size from 65535 (autodetected via rlimit) to 6553 (limited by memory of 10% from 2Mb)
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: WARNING:core:init_reactor_size: use 'open_files_limit' to enforce other limit or increase pkg memory
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:init_reactor_size: reactor size 6553 (using up to 0.20Mb of memory per process)
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_CORE_THRESHOLD(0)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_CORE_SHM_THRESHOLD(1)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_CORE_PKG_THRESHOLD(2)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_MYSQL_CONNECTION(3)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:tm:mod_init: TM - initializing...
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:sl:mod_init: Initializing StateLess engine
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: NOTICE:signaling:mod_init: initializing module ...
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:rr:mod_init: rr - initializing
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:dialog:mod_init: Dialog module - initializing
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_DLG_STATE_CHANGED(4)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:maxfwd:mod_init: initializing...
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:textops:mod_init: initializing...
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_DISPATCHER_STATUS(5)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:load_balancer:mod_init: Load-Balancer module - initializing
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:evi_publish_event: Registered event <E_LOAD_BALANCER_STATUS(6)>
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:sipmsgops:mod_init: initializing...
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:mod_init: initializing UDP-plain protocol
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips[2443]: INFO:core:probe_max_sock_buff: using rcv buffer of 416 kb
Jun 27 20:31:06 ecs-sn3-large-2-linux-20190621115558 opensips: INFO:core:daemonize: pre-daemon process exiting with 0

Jun 27 20:31:14 ecs-sn3-large-2-linux-20190621115558 opensips[2448]:  1
Jun 27 20:31:14 ecs-sn3-large-2-linux-20190621115558 opensips[2448]: REGISTER
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2450]:  1
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2450]: INVITE
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2448]:  2
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2448]:  1
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2448]: INVITE
Jun 27 20:31:20 ecs-sn3-large-2-linux-20190621115558 opensips[2449]: INFO:core:parse_headers: bad header field
Jun 27 20:31:21 ecs-sn3-large-2-linux-20190621115558 opensips[2451]: INFO:core:parse_headers: bad header field
Jun 27 20:31:23 ecs-sn3-large-2-linux-20190621115558 opensips[2448]: INFO:core:parse_headers: bad header field
Jun 27 20:31:27 ecs-sn3-large-2-linux-20190621115558 opensips[2449]: INFO:core:parse_headers: bad header field
Jun 27 20:31:35 ecs-sn3-large-2-linux-20190621115558 opensips[2448]: INFO:core:parse_headers: bad header field
)

The phone can't get through.

cfg error?  nat?

**Comment by bogdan-iancu** [comment]
@yuexiajiayan , this tracker is for reporting mainly  bugs or feature requests. In your case, you are asking for help with your OpenSIPS configuration - and for such things, the best channel is the [OpenSIPS users mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).
