### ISSUE TITLE
[CRASH] 2.4.6 with TLS

### ISSUE THREAD

**Issue by telematico** [OpenSIPS/opensips#1752]
I noticed a crash in 2.4.6 version (installed using repository deb http://apt.opensips.org bionic 2.4-release) I think may be related to tls module.

**OpenSIPS version you are running**

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7

**Crash Core Dump**
Here is a paste with a BT full of the core file
[https://pastebin.com/UN8pJhNn](https://pastebin.com/UN8pJhNn)

**Describe the traffic that generated the bug**
I was able to reproduce the bug only with real traffic, after some minutes. I made stress tests with SIPp using TLS protocol and everything works fine.

**To Reproduce**
I only be able to reproduce the crash after some minutes of real traffic. With SIPp I couldn´t reproduce the issue. If you need it I can reproduce again by night and get a new core dump.

**Relevant System Logs**

**OS/environment information**
 - Operating System: ubuntu 18.04.2
 - OpenSIPS installation: from DEBS http://apt.opensips.org bionic 2.4-releases
 - other relevant information: 

**Additional context**

**Comment by wdoekes** [comment]
Same as #1590 perhaps?

**Comment by telematico** [comment]
update the sources to last github code seems to solve the issue. I close the ticket
