### ISSUE TITLE
[BUG] E_UL_CONTACT_INSERT not working when app is closed

### ISSUE THREAD

**Issue by plotic** [OpenSIPS/opensips#1753]
Hey guys, 

I am running opensisps 2.4.6.
I have 2 registered users on 2 iphones. 
I integrated the Event (based) Routing Module to support Push notification.

```
route[route_to_user] {
    t_newtran();
    t_wait_for_new_branches();
    $avp(filter) =  "aor="+$rU;
    notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)", "fork_call", "20");

    if (lookup("location"))
        route(relay);
    exit;
}

route[fork_call]  {
    usleep("1000");
    t_inject_branches("event");
}
```

In my first scenario i have 2 users online and registered Alice and Bob. I make a call Alice->Bob, the call gets established and everything is fine. Now i close the app on Bob's iphone and try calling Bob again from Alice . And i'm getting the error below and a 500 SIP/2.0 500 Internal Error 

```
ERROR:core:tcp_connect_blocking_timeout: timeout 99269 ms elapsed from 100000 s
ERROR:proto_tls:tls_sync_connect: tcp_blocking_connect failed
ERROR:proto_tls:proto_tls_send: connect failed
ERROR:tm:msg_send: send() to XX.XX.XX.XX:XXXX for proto tls/3 failed
ERROR:tm:t_forward_nonack: sending request failed
ERROR:tm:w_t_relay: t_forward_nonack failed
```

What i presume is that when the  `route[route_to_user] ` is called it locates the user and tries routing but it fails because the branch doesn't exists.

I checked the `location` table and i can see that it gets duplicated records for the same user. 
I understand that you can have multiple devices registered, but how to fix this problem ? Or is it a bug.
I also checked this issue https://github.com/OpenSIPS/opensips/issues/1573 it is kinda related to what i have, but i'm not sure it is the same.

Thanks

**Comment by vasilevalex** [comment]
This is not OpenSIPS issue. This is how all modern mobile OS work. They close network connection immediately as app becomes inactive. Of course OpenSIPS can't contact your app, as there is no TLS connection. You should use push to run app and after that send SIP request to it.

**Comment by plotic** [comment]
Thanks @vasilevalex  for the response. Maybe i miss-understood the purpose of event (based) routing. But wasn't it designed for this purpose?
Where you subscribe using  notify_on_event to get the event on new contact registrations for callee. So subscribe yourself meanwhile you wait for push to wake up the app and register the user. Once it is done it will t_inject_branches and continue with the call.

**Comment by bogdan-iancu** [comment]
@plotic - the `notify_on_event` stuff is just part of the Push Notification system. The instructs OpenSIPS to wait for new registration and to deliver the call (as additional branches) to those new registrations. The other mandatory component is to trigger a Push Notification to the mobile device to force the app to re-register. This is not part of OpenSIPS, it is something that you have to extra do - do you do something like this ?

**Comment by plotic** [comment]
Yes @bogdan-iancu i do send the push notification. I'm sorry i was not clear about it.
My issue is that when the remote is closed and caller tries to call it.
This error is taking place
```
ERROR:core:tcp_connect_blocking_timeout: timeout 99269 ms elapsed from 100000 s
ERROR:proto_tls:tls_sync_connect: tcp_blocking_connect failed
ERROR:proto_tls:proto_tls_send: connect failed
ERROR:tm:msg_send: send() to XX.XX.XX.XX:XXXX for proto tls/3 failed
ERROR:tm:t_forward_nonack: sending request failed
ERROR:tm:w_t_relay: t_forward_nonack failed

```
and also the caller receives error code - 500

**Comment by razvancrainea** [comment]
@plotic is the `XX.XX.XX.XX:XXXX` IP:port the public IP and port of the client? Can you check if it's the same value as the one the REGISTER was received from? If it's not, you should use the `fix_nated_contact()`/`fix_nated_register()` functions on the initial REGISTER, before `save()`.

**Comment by plotic** [comment]
@razvancrainea thanks for the response. yes it is public ip and from logs it looks that there are the same. Still I tried your approach and modified the configuration file, but i'm still getting the error. 
Can it be that if lookup in location succeeds
```
  if (lookup("location"))
        route(relay);
```
but the client is not available (e.g.the ios app was closed) i will get that error ? and if it is true, i need to remove the contact from location table and memory ?

**Comment by razvancrainea** [comment]
If the client closes the TCP/TLS connection, OpenSIPS will definitely not be able to access it. It has to re-register;
If for example you have a stale TLS registration (your client closed the connection without de-registering), then OpenSIPS might "believe" that the connection is still up, and will try to reach you - and when it doesn't, it shows that error.

I'm not sure what bothers you: the fact that you see the error, or that the call is closed due to that error, and OpenSIPS does not wait for the registration over the PN. If that's the case, you should call the[ `t_relay()`](https://opensips.org/html/docs/modules/2.4.x/tm.html#func_t_relay) function with the `0x2` flag, to prevent opensips from sending the error back.

**Comment by plotic** [comment]
Thanks @razvancrainea for your explanation. Yes, the thing that made me confused is the error. Now that you explain it, i understood it better. I'll try using 0x2 flag.
