### ISSUE TITLE
[BUG] dialog: DLGCB_LOADED callbacks are broken in 2.4+

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#1754]
**Describe the bug**

Commit 3ddae4344 moves dialog loading from `mod_init()` to `child_init()` and got backported all the way down to `2.4`.  The problem with this is that it breaks the `DLGCB_LOADED` "full & inline initialization" logic, where a module which calls `dlg_api.register_dlgcb(DLGCB_LOADED, ...)` will have their callback called `N` times, once per each dialog present in the hash table.

Now that the loading has been moved to `child_init()`, the `api.register_dlgcb(DLGCB_LOADED)` calls of various modules will receive `0` invocations of the callback during `mod_init()`, while dialog will not subsequently invoke their callback as it finally loading the dialogs.

**OS/environment information**
Issue specific to OpenSIPS 2.4+
Affected modules: `sst`, `uac`, `pua_dialoginfo`, `siprec`, `call_control`

**Comment by liviuchircu** [comment]
Personally, I suggest to revert that commit altogether.  I would much rather have my OpenSIPS restart and stay stuck until it can properly process SIP, rather than risking a slew of `"481 Call/Transaction Does Not Exist"` replies to `BYE` messages, along with a similar amount of max-duration dialogs each time I perform a restart in production.

But maybe I'm only seeing one side of the coin here.  Perhaps understanding the original motivation behind the mentioned commit (the commit only explains the WHAT not the WHY) will help steer towards the best solution.

**Comment by liviuchircu** [comment]
Alternatively, we could go for something like this:

```
diff --git a/modules/dialog/dlg_db_handler.c b/modules/dialog/dlg_db_handler.c
index 56f7d4171..bcf065169 100644
--- a/modules/dialog/dlg_db_handler.c
+++ b/modules/dialog/dlg_db_handler.c
@@ -724,6 +724,8 @@ static int load_dialog_info_from_db(int dlg_hash_size)
                                ref_dlg(dlg,1);
                        }
 
+                       run_load_callback_per_dlg(dlg);
+
                        next_dialog:
                        ;
                }
```

... where dialog remembers to invoke `DLGCB_LOADED` for each subscribing module during DB loading.  I'm still leaning towards the revert though: the less BYE's that we incorrectly reply with a `4XX` to, the better.

**Comment by razvancrainea** [comment]
Indeed, the report is true and the fix is correct. Thanks @liviuchircu for looking into this!

**Comment by liviuchircu** [comment]
Shall I open a separate issue for the newly introduced behavior mentioned in [comment #2](https://github.com/OpenSIPS/opensips/issues/1754#issuecomment-509282592), or do you think it's effects are negligible?

From a sysadmin point of view, the more stuff we throw into `child_init()`, the harder it is to have a way of telling when an OpenSIPS is fully restarted and ready to process traffic (so we can switch traffic back to it).  At least, previously, it stayed stuck in `systemctl start opensips`, which is quite desirable, if you think about it.
