### ISSUE TITLE
[BUG] Opensips crashes

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1758]
**OpenSIPS version you are running**
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3fe6c3804
main.c compiled on 02:05:58 Jul  9 2019 with gcc 7

**Crash Core Dump**
Core dump file:
https://yadi.sk/d/i16lEVRv_8su9g
Bt full file:
https://yadi.sk/d/S3Zry2hrOhtbng
**Describe the traffic that generated the bug**
As far as I understood from the dump, the error was caused by the search for the TO field: at the address of the memory cell at the time the alarm went through the switch

**To Reproduce**
The error is not reproduced at the moment, the circuit is under load, I am waiting for repeated crashes.

**Relevant System Logs**
I do not reset the full kernel file, the extract at the time of the fall from the log indicates the process segfault with the pida number

**OS/environment information**
Operating System: Debian GNU/Linux 9.9 (stretch)
OpenSIPS installation: git/source/

**Additional context**
A little later, there will be more dapmy and links to files and log file I post later.
I am waiting for any help thanks!

**Comment by bogdan-iancu** [comment]
@ilyinvv , have you spotted in the opensips log, just at the crash time, so "CRITICAL" level message ?

What you have there is a problem we are already aware of , resulting in memory corruption.

**Comment by ilyinvv** [comment]
Unfortunately now I can not recover the log messages, do not close the ticket, please, as soon as the next failure occurs, I will upload new files and analyze the log on Critical

**Comment by ilyinvv** [comment]
fall again, the problem of this dump is fully comparable with the dump above, I found the following error in the log before the crash:
CRITICAL: core: qm_free: freeing the pointer, first free: sip_msg.c: update_cloned_msg_from_msg (1269) - aborting
In a dump like:
  bm = {to_tag_val = {s = 0x1f <error: Cannot access memory at address 0x1f>, len = -1087084848}}
Link to dump file:
https://yadi.sk/d/d9NyvymA8MuY-Q

**Comment by bogdan-iancu** [comment]
@ilyinvv , such crashes looks similar to an older crash, which was fixed AFAIK. I wanted to check the version you have but the info is a bit confusing - it is reported version 2.4.6 (which was released on 11th of June 2019), but the revision number points to a commit from 15th of Nov 2018 ?!?!
How did you install opensips ? packages or local compiling ?
