### ISSUE TITLE
[BUG] sql_cacher does not release locks on error

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1760]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 02:34:54 Jul  9 2019 with gcc 7
```

**Describe the bug**

Through code review and testing we have found numerous places where the sql_cacher module fails to release locks in error cases, resulting in all attempted accesses from the script blocking forever.

We have also found that the write lock is obtained prior to the DB access which can cause very poor performance if the DB response is delayed or times out.

Lastly, the purpose of the versioning implementation in sql_cacher is not clear. Versions do not appear to be incremented during a timed reload, only for an MI reload. There appears to be no effort to remove or cleanup old versions of keys, which causes the cache to continually grow. Since the cache is always locked when the data is updated, it's unclear why versioning is needed; why can't the existing keys simply be removed before the new keys are inserted? If versioning is desired, then the write lock is unnecessary if the read code is simply updated to allow any newer entry version, not just an identical version to the cache.

**To Reproduce**

1. Start OpenSIPS and load an sql_cacher table
2. Cause a failure in the DB connection (remove the DB, stop network traffic, etc.)
3. Run the `sql_cacher_reload` MI command for the table
4. After the command times out, attempt to access the cache from the script. The script will block on the cache forever.

**Expected behavior**

Locks should be managed and released properly. Blocking locks should only be obtained once absolutely necessary.

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by clifjones** [comment]
Just to add, the testing was done with db_postgres but this should happen with other DB implementations.

**Comment by rvlad-patrascu** [comment]
Hi Ben,

I will look into the locking problems ASAP, but first let me clarify some aspects regarding versioning:
1) Indeed the version should be also incremented for the periodic reloads and not only for MI reloads. This is an issue and it should be fixed.
2) The cache will not grow indefinitely, as the keys are inserted with a configurable expire period and will be cleaned up by the cache DB if not reloaded.
3) "why can't the existing keys simply be removed before the new keys are inserted?" -> doing this would require iterating through all the cached keys and removing them one by one. There is no convenient way to do this so it is better to just leave the cache DB expire the keys.

**Comment by bcnewlin** [comment]
Thanks for the quick response.

1. Good to know. I wasn't sure if there was something different about the timed reloads that made that intentional.
2. This is true. I had not considered the expire interval. That makes the third point a bit moot.
3. I was thinking the `cache_remove_chunk` functionality could be used here, but I see now that is specific to the cachedb_local.

**Comment by bcnewlin** [comment]
I wanted to provide the error cases we believe we found from code review so you don't have to try to find them all yourself.

* In `load_entire_table`, the memory for `query_cols` is leaked in [several error cases](https://github.com/OpenSIPS/opensips/blob/master/modules/sql_cacher/sql_cacher.c#L764-L791).
* In `mi_reload`, `queries_lock` is potentially leaked [here](https://github.com/OpenSIPS/opensips/blob/master/modules/sql_cacher/sql_cacher.c#L1012).
* In `mi_reload`, the cache write lock is not released in the case of [reload errors](https://github.com/OpenSIPS/opensips/blob/master/modules/sql_cacher/sql_cacher.c#L1061-L1072). This is the biggest issue as it leaves the entire cache locked. Since the blocking locks have no timeouts, this will eventually (depending on how often you access the cache) block all OpenSIPS script processes.
* In `pv_get_sql_cached_value`, the cache read lock is leaked on error [here](https://github.com/OpenSIPS/opensips/blob/master/modules/sql_cacher/sql_cacher.c#L1760).

**Comment by rvlad-patrascu** [comment]
Thanks for the help!

"Any thoughts on moving the lock acquire until after the DB query?" -> This makes sense but I'll have to make sure no other concurrency issues may occur.

**Comment by bcnewlin** [comment]
Yes, the lock seems to be acquired before in order to facilitate updating the version key. However, that could be done after the update as if the DB update fails you don't want the version incremented as it will invalidate all existing data!

One other thing that we thought of is that with the versioning in place it should be possible to not require the write lock at all if there are no inter-dependencies in the data. For example, if I know that each key is independent and I am ok with potentially getting the new or older key during an update, then if you just change the [version check on the entry](https://github.com/OpenSIPS/opensips/blob/master/modules/sql_cacher/sql_cacher.c#L1312) to allow newer versions (`reload_version <= int_val`). Combined with moving the cache version update until after the keys have all been updated, this would make the write lock unnecessary.

Due to the knowledge about the data format this would likely have to be exposed as an option.

**Comment by bcnewlin** [comment]
Actually, I just realized that incrementing the cache version before the DB query and update is quite bad as if the update fails even if the lock is released properly the entire table will have been invalidated.

**Comment by rvlad-patrascu** [comment]
Indeed, your points are mostly correct. Although, the lock can't be dropped completely as it has to protect some changes to the in-memory structure for the caching entry.

"Due to the knowledge about the data format this would likely have to be exposed as an option." - I don't think I understand what you mean by this.

**Comment by bcnewlin** [comment]
I mean it would have to be the script writer's decision whether to allow a lock-less update. The data could have dependencies where allowing reads during the update could result in bad data. It might not be okay for consecutive reads of different keys to return one key from the old version and the other from the new version. So I don't think you could do it in all cases. The script writer would have to know that it is safe for their data and allow it via a module parameter I think.

**Comment by rvlad-patrascu** [comment]
I think the best approach would be to first fix the issues at hand, that we actually identified, and then see if the cacheDB inserts really need to be lock-less. I do agree though that the query to the SQL DB shouldn't  be done under the lock.

**Comment by bcnewlin** [comment]
Yes, I agree completely. I'm not even sure whether the lock-less mode would be worth implementing. I was just mentioning that the versioning system in place would allow it. Not necessarily pushing for it.

**Comment by clifjones** [comment]
Note: It appears that when on_demand is false, the version for the cache entries on a mi_reload is always the same value (0).  When on_demand is true, the version is incremented each reload.
