### ISSUE TITLE
[BUG] $du not honored by t_relay()

### ISSUE THREAD

**Issue by danpascu** [OpenSIPS/opensips#1761]
**OpenSIPS version you are running**

```
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 1ca0501eb
main.c compiled on  with gcc 8
```

**Describe the bug**

OpenSIPS will use a different protocol than the one in $du when calling t_relay()

**To Reproduce**

I have an account A that has a setting to divert to voicemail when busy. I register this account separately (not at the same time) from 2 different devices, D and E. In one case I register over TLS in the other over TCP like this:

D(A)  - (TLS) ->  Proxy
E(A)  - (TCP) ->  Proxy

I make a call to this account and then I refuse it with busy. I end up in the failure route where I notice I have a diversion for busy to voicemail, I replace the request URI with the voicemail URI, set $du to point to myself over TLS and call t_relay() to forward the message back to myself for further processing.

The code in the failure route is roughly:

$ru = voicemail_uri;
$du = "sip:self_IP;transport=tls"
t_relay();

What I notice is that for device D that received the INVITE over TLS, forwarding to self after diversion works OK, but for device E that used TCP, forwarding to self is done over TCP, despite $du specifying a TLS transport.

It looks like after a failure, t_relay will use the same transport as the original branch that failed used regardless of what is in $du.

**Expected behavior**

I expect $du to be honored regardless of what transport was used by the original failed branch.

**OS/environment information**
 - Operating System:  debian sid
 - OpenSIPS installation:  git

**Additional context**

If I try to use t_relay(0, "tls:self_IP") instead of setting $du, it works (it uses TLS as requested regardless of what the original transport of the branch was) but I see this warning in the logs:

WARNING:core:get_send_socket: protocol/port mismatch

**Comment by danpascu** [comment]
Something else I noticed is that no new Via header is added when forwarding to myself. The same set that was present in the INVITE that was sent to the device is present in the message that is forwarded to myself. Maybe this is the reason it complains or uses the wrong protocol to honor the top Via that is already there with a different protocol?

Isn't t_relay supposed to add a Via header? Also how would it work in this case. Should the top Via that was used on the branch to the device be removed and replaced with a new one that matches the ip/port/proto when forwarding to myself after failure?

**Comment by bogdan-iancu** [comment]
@danpascu , just before the suspicious `t_relay()` could you xlog the value of `$ru`, `$du`, `$fs` ?

**Comment by danpascu** [comment]
```
$du = sip:IP_OF_THIS_PROXY;transport=tls
$ru = sip:test_number@sip2sip.info
$fs = tcp:IP_OF_THIS_PROXY:5060
```

**Comment by danpascu** [comment]
Setting $fs = null right before t_relay fixes it, but shouldn't opensips reset $fs automatically when reaching the failure route?

**Comment by bogdan-iancu** [comment]
As the `failure_route` is basically a "resume" of the `request_route`, it inherits all the changes/setting done over the SIP msg in the `request_route`.

**Comment by danpascu** [comment]
Yes, but if the original was sent over tcp to some contact, it fails and now I have to send it over a different protocol decided by the new destination it won't work. The only case where it works is if the original and the new protocols are exactly the same.

What is the point of not automatically resetting it and having to always add $fs = null in my script because else it won't work in the majority of cases? I see no reason to preserve a forced socket when there is no correlation between the original branch and the new one. The reason this bites you in the back is because it's totally unexpected behavior.

**Comment by danpascu** [comment]
BTW, I did not set $fs in the main route. It is automatically set for me internally by t_relay() when it sends out to branches. I have 0 lines in the configuration where I set $fs (well until now when I'm forced to reset it in failure route).

**Comment by danpascu** [comment]
Thinking of it, is there a reason why $fs is not automatically reset when setting $du?

**Comment by bogdan-iancu** [comment]
There is no strong logical relation between them, in order to do so.

**Comment by danpascu** [comment]
Of course there is. $du decides the protocol at the destination while $fs decides the protocol at the source of the connection. You cannot have different protocols at the different ends of one connection, thus you enforce one over the other if they are different ($fs overwrites $du in this case).

Plus there is a second case whee this is totally wrong. Imagine the proxy has 2 different interfaces, one over a public interface and one over a private one. Let's say the original call goes over the public one to some user that refuses the call  and in failure route I set $du to point to the voicemail uri that is over a private internal network. Now not only the protocol might be different, but even the IP addresses are incompatible because I cannot reach the private IP destination with a public IP source.

**Comment by bogdan-iancu** [comment]
OK, there is something in between. Not a relation, but a conflict :) . Indeed, the $du and $fs should share the same transport protocol for SIP.
The [get_send_socket()][https://github.com/OpenSIPS/opensips/blob/master/forward.c#L145] function is taken care of that, by changing the outgoing socket if not matching the destination protocol . Do you see the DBG log from there (line 153) ?

**Comment by danpascu** [comment]
No I don't.

My protocol is stuck to whatever the failed branch set and is not cleared unless I do $fs = null in the script after setting $ds.

**Comment by bogdan-iancu** [comment]
Trying to recap : the socket is stuck to a TCP listener; the D-URI has a TLS indication; and the message is sent via TCP ? And there is the warning about a protocol conflict ?

**Comment by danpascu** [comment]
If I use $du, there is no warning, it just silently sends over TCP (taken from the stuck $fs).

The behavior depends on how I send it out:

0. Failed branch used TCP and the sending socket is stuck on TCP.
1. If I just set $du to TLS and don't reset $fs, them message is sent over TCP with no warning.
2. If I use t_relay(0, "tls:ip:port") and don't reset $fs, then message is sent over TLS but I see the warning I mentioned in the original post.

**Comment by bogdan-iancu** [comment]
@danpascu , after digging a bit more - when doing `t_relay()` from script, the [add_uac()](https://github.com/OpenSIPS/opensips/blob/518aca4d407c0c8fb7a4da17bb967382fd264ca8/modules/tm/t_fwd.c#L385) function calls `uri2proxy()` take the uri from RURI/DURI and a `forced_proto` from the socket (if any). Basically, if a socket with a different protocol is provided, the `uri2proxy()` will build a new destination with IP and port from URI and proto from the socket.
This explains what happens, why TCP is actually used - the forced socket overrides the protocol from the SIP URI.

Now, why the socket is still set in your failure route ? whatever settings you do in the request route (before creating the transaction) will be inherited by all future branches. I guess you do a lookup(location) in request route, setting a $fs,$du,$ru to a a first TCP endpoint. If this branch fails, when landing in failure route, all these values will still be set.

**Comment by danpascu** [comment]
But why would they be inherited by future branches? I doesn't make sense to preserve a socket that was used by a branch for future branches. Whatever lookup(location) has set was only valid for that destination in that particular branch. Once that branch is done and you decide to go somewhere else, that branch and all its settings should vanish and a new one should be created where you determine the new socket based on the new destination.

Besides which settings from which branch are preserved considering that parallel forking happens with different branches with different settings? I had one case where I had 2 devices registered one over TCP one over TLS, so lookup(location) obviously setup 2 branches with 2 different sockets, one TCP one TLS. Both replied with 486 Busy yet when I went to the failure route and diverted the call to voicemail, it tried to use the TCP socket despite the voicemail destination being TLS.

Here is what my code looks like in the failure route (there are some extra remove_hf, append_hf, settings avps and timers, but I cut them out for brevity):

```
    if (t_check_status("486")) {
        if (divert("busy")) {
            t_on_branch("BRANCH_RESET");
            t_on_failure("FAILED_DIVERT");

            resetbflag(TCP_NO_NEW_CONN_BFLAG);

            $du = "MYSELF";
            # $fs = null;

            if (!t_relay()) {
                t_reply(500, "Server internal error");
            }
            return;
        }
    }
```

`BRANCH_RESET` is an empty route which is only meant to reset the previously set branch route, because I could not find another way to clear a previously set branch route. `divert("busy")` is a function in a custom module that checks if the user has a diversion for busy and if it finds one it sets some avps, calls `clear_branches()` and `set_ruri()` and returns true.

This makes the things all the more confusing, because after `calling clear_branches()` I do not really expect any previous settings from a particular branch to survive.

Unless I comment out that `$fs = null` line, things will not work correctly, but I never set $fs myself in the call setup, why am I required to know it was set internally and clear it out manually myself? Why didn't `clear_branches()` remove all information about previous branches and start from scratch?

**Comment by bogdan-iancu** [comment]
Let me try to simplify the perception over branches.
1) whatever changes you do over the sip message **before** creating the transaction (so `t_newtran()` or the first `t_relay`) will be inherited by **all** the branches of that transaction. 
2) whatever changes you do in `branch_route` are local to that branch with 0 impact over any existing or future branch.
3) when resuming in failure route, you will "see" all the common changes over the transaction (see (1))

And note that `clear_branches()` clears any branches set to be used for the next relay(), it has nothing to do with the past branches.

**Comment by danpascu** [comment]
Except I never set $fs myself in the main route before t_relay(), so why am I inheriting something I never did (but opensips did internally)?

The simple fact that every time I set `$du` in the failure route I also needs to set `$fs = null` should indicate that something is wrong with it. IMO the sending socket should always be chosen based on the destination, not the other way around.

**Comment by bogdan-iancu** [comment]
@danpascu, whatever OpenSIPS does is a result of your script; OpenSIPS does not do anything by its own, but it follows YOUR script. I assume you are happy when the `lookup(location)` takes care and populates the socket for each branch in order to reflect the proper network interface :).
Now, the send socket has 2 purposes:
* forcing a specific transport protocol - the RURI has no transport indication, so you can use the socket to indicate a specific transport to be used
* selecting a specific interface, even if the same protocol - like when using private versus public interfaces or so.
So, there are good valid cases where **NEED** to set the socket, in order to control the mapping of the SIP traffic over your listening interfaces.

Now, to conclude this discussion - OpenSIPS wants to be a generic engine able to enable a large set of scenarios. Maybe you your case, the socket is irrelevant (or a burn to take care of), but in many other scenarios it s golden nugget. 

So far I fail to see a bug/issue. On the other hand, if you have a solution to improve the current way of managing the branches (parallel or serial) and their data (and still able to cover all the supported scenarios), I happy to listen.

**Comment by danpascu** [comment]
OpenSIPS does a lot of internal things on its own that I should not be required to be aware of. I do not have a problem with the fact that `lookup(location)` needs to set some sending socket based on where the device registered from. What I have a problem with is the fact that these internal settings spill out in the script. If it was something internal it should stay internal. In the failure route if you revert to the original state before `t_relay()`, it should be the state **I** set, not some state that includes internal side-effects of what I did.

The solution is pretty simple in my view. You need to decouple $fs from the internal forced socket. $fs should only be set from the script and overwrite whatever internal socket is chosen. When you revert the state, you preserve $fs that was set by me but erase any internally set socket. This make all the more sense considering that the sending socket should be determined based on the destination, not the other way around. The TCP sending socket was chosen by `lookup(location)` because it was the socket that matched the destination device based on where it registered from and was relevant for that branch only. I fail to see how that socket is relevant and needs to spill into the next destination that is chosen in the failure route.
