### ISSUE TITLE
[BUG]Significant memory consumption of open life during operation

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1762]
**OpenSIPS version you are running**
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3fe6c38
main.c compiled on 02:05:58 Jul 9 2019 with gcc 7

**Describe the bug**
The process of open storage uses too much memory and if it is not restarted, it can absorb all the memory allocated for the process in a day.

**To Reproduce**
1. Opensips startup line:
/usr/local/sbin/opensips -F -E /var/log/opensips/opensips.log -P /var/run/opensips/opensips.pid -m 3072 -M 512 -u root -g root -f /usr/local/etc/opensips/extensions/opensips.cfg -w /var/log/opensips
2. Number of processes displayed by the top command - 27
3. Worker, children=4
4. Opensipsctl fifo ps:
Process::  ID=0 PID=31 Type=attendant
Process::  ID=1 PID=33 Type=HTTPD 85.12.253.18:8008
Process::  ID=2 PID=34 Type=MI FIFO
Process::  ID=3 PID=35 Type=time_keeper
Process::  ID=4 PID=36 Type=timer
Process::  ID=5 PID=37 Type=SIP receiver udp:85.12.253.12:5060
Process::  ID=6 PID=38 Type=SIP receiver udp:85.12.253.12:5060
Process::  ID=7 PID=39 Type=SIP receiver udp:85.12.253.12:5060
Process::  ID=8 PID=40 Type=SIP receiver udp:85.12.253.12:5060
Process::  ID=9 PID=41 Type=SIP receiver udp:10.227.228.18:5060
Process::  ID=10 PID=42 Type=SIP receiver udp:10.227.228.18:5060
Process::  ID=11 PID=43 Type=SIP receiver udp:10.227.228.18:5060
Process::  ID=12 PID=44 Type=SIP receiver udp:10.227.228.18:5060
Process::  ID=13 PID=45 Type=SIP receiver udp:10.227.228.17:5060
Process::  ID=14 PID=46 Type=SIP receiver udp:10.227.228.17:5060
Process::  ID=15 PID=47 Type=SIP receiver udp:10.227.228.17:5060
Process::  ID=16 PID=48 Type=SIP receiver udp:10.227.228.17:5060
Process::  ID=17 PID=49 Type=TCP receiver
Process::  ID=18 PID=50 Type=TCP receiver
Process::  ID=19 PID=51 Type=TCP receiver
Process::  ID=20 PID=52 Type=TCP receiver
Process::  ID=21 PID=53 Type=TCP receiver
Process::  ID=22 PID=54 Type=TCP receiver
Process::  ID=23 PID=55 Type=TCP receiver
Process::  ID=24 PID=56 Type=TCP receiver
Process::  ID=25 PID=57 Type=Timer handler
Process::  ID=26 PID=58 Type=TCP main

**Expected behavior**
Operation Opensips router without rebooting once every 24 hours

**Relevant System Logs**
5. Dump of memory for the most loaded process in the middle of the working day:
Memory status (pkg)
qm_status (0x7f304afb3010)
heap size= 536870912
used= 75466616, used+overhead=262706144, free=274164768
max used (+overhead)= 263420376
total_bytes | num_allocations x file | func, line
32 | 1 x   [aaa_avps.h | parse_aaa_avps, line 91]
24 | 1 x [script_var.c | set_var_value, line 101]
320 | 1 x [reply.c | build_contact, line 240]
32 | 2 x [cfg.lex | oss_push_yy_state, line 1084]
48 | 1 x [db/db_res.c | db_new_result, line 92]
16 | 2 x [script_var.c | add_var, line 59] |  
1677720 | 1 x [io_wait.c | init_io_wait, line 568]
112 | 2 x [cfg.lex | oss_push_yy_state, line 1094]
96 | 1 x [pg_con.c | db_postgres_new_connection, line 57]
1168 | 28 x [sipmsgops.c | fixup_method, line 887]
64 | 2 x [rr_cb.c | register_rrcb, line 57]
117600 | 588 x [route_struct.c | mk_action, line 106]
1206352 | 8858 x [sipstate.c | siplua_lua_Alloc, line 83]
672 | 42 x [cfg.y | new_string, line 2703]
13906728 | 90243 x [pvar.c | pv_parse_format, line 4119]
144 | 1 x [db/db_res.c | db_allocate_columns, line 130]
24981112 | 707552 x [mod_fix.c | fixup_spve, line 948]
128 | 1 x [cfg.y | yyparse, line 534] |  
48 | 1 x [transformations.c | parse_transformation, line 2372]
336 | 1 x [avpops_db.c | add_db_url, line 109]
672 | 42 x [cfg.y | yyparse, line 999] |  
2232 | 41 x [evi/evi_params.c | evi_param_create, line 42]
408 | 1 x [address.c | init_address, line 304]
1128 | 42 x [mem/shm_mem.c | init_shm_post_yyparse, line 516]
5033160 | 1 x [io_wait.c | init_io_wait, line 559]
24 | 1 x [clusterer.c | gen_rcv_evs_init, line 2694]
80 | 1 x [cachedb/cachedb_id.c | new_cachedb_id, line 332]
3864 | 34 x [mod_fix.c | fixup_pvar, line 553]
56 | 1 x [auth.c | add_credential, line 97]
96 | 2 x [script_var.c | add_var, line 52] |  
0 | 1 x [dlg_db_handler.c | write_dialog_profiles, line 1220]
24 | 1 x [name_alias.c | add_alias, line 59] |  
8 | 1 x [dp_db.c | dp_add_connection, line 858]
8 | 1 x [auth.c | add_credential, line 154]
64 | 4 x [socket_info.c | fix_socket_list, line 643]
536 | 11 x [sr_module_deps.c | alloc_module_dep, line 54]
48 | 1 x [ipc.c | ipc_register_handler, line 120]
24 | 1 x [dlg_hash.c | state_changed_event_init, line 867]
80 | 1 x [mi/mi_trace.c | try_load_trace_api, line 55]
16 | 1 x [rtpengine.c | connect_rtpengines, line 1296]
960 | 8 x [db/db.c | db_do_init, line 287]
192 | 1 x [cachedb/cachedb.c | register_cachedb, line 165]
418776 | 1228 x [sipstate.c | siplua_lua_Alloc, line 88]
48 | 2 x [script_cb.c | insert_raw_processing_cb, line 220]
2160 | 27 x [pvar.c | pv_add_extra, line 4690]
24 | 2 x [cachedb/cachedb_id.c | dupl_string, line 45]
960 | 76 x [map.c | map_get, line 150] |  
32 | 1 x [map.c | map_create, line 79]
32 | 1 x [sipmsgops.c | get_pvs_header_value, line 331]
2516584 | 1 x [io_wait.c | init_io_wait, line 621]
24 | 1 x [mod_fix.c | fixup_sgp, line 781] |  
8 | 1 x [auth.c | add_credential, line 114]
80 | 4 x [socket_info.c | fix_socket_list, line 592]
352 | 4 x [bin_interface.c | bin_register_cb, line 391]
8192 | 1 x [mi_writer.c | mi_writer_init, line 49]
144 | 3 x [flags.c | get_flag_id_by_name, line 202]
2560 | 1 x [ul_mod.c | mod_init, line 404] |  
64 | 3 x [ut.c | parse_reply_codes, line 131]
32 | 1 x [auth_mod.c | generate_random_secret, line 204]
64 | 4 x [cfg.y | yyparse, line 514] |  
240 | 5 x [cfg.y | mk_listen_id, line 2685]
64 | 4 x [socket_info.c | new_sock_info, line 125]
960 | 4 x [socket_info.c | new_sock_info, line 119]
16848 | 162 x [cfg.y | yyparse, line 1456] |  
504 | 18 x [ds_fixups.c | set_list_from_string, line 146]
8 | 1 x [drouting.c | dr_init, line 1508] |  
128 | 1 x [net/net_tcp.c | tcp_init, line 1711] |  
17068496 | 805065 x [sipapi.c | l_siplua_moduleFunc, line 789]
352 | 8 x [script_cb.c | add_callback, line 60]
192 | 4 x [ip_addr.c | mk_net, line 54] |  
9600 | 1 x [mi/mi.c | register_mi_cmd, line 146]
1968 | 41 x [sr_module.c | register_module, line 150]
96 | 4 x [socket_info.c | fix_socket_list, line 722]
200 | 1 x [dlg_db_handler.c | write_dialog_vars, line 1170]
14392 | 257 x [route_struct.c | mk_elem, line 70] |  
24 | 1 x [udomain.c | ul_event_init, line 215]
1552 | 40 x [mod_fix.c | fixup_str, line 67] |  
24 | 1 x [udomain.c | ul_event_init, line 227]
96 | 4 x [cfg.y | yyparse, line 1175] |  
24 | 1 x [dlg_vals.c | fetch_dlg_value, line 181]
32 | 1 x [name_alias.c | add_alias, line 57] |  
24 | 1 x [acc.c | init_acc_evi, line 1094]
96640 | 12 x [db/db.c | db_do_init, line 325]
2880 | 43 x [mod_fix.c | fixup_regexp, line 310]
32 | 1 x [node_info.c | load_db_info, line 388]
32 | 1 x [cachedb_local.c | lcache_new_connection, line 269]
8 | 1 x [node_info.c | load_db_info, line 378]
16 | 1 x [drouting.c | dr_init, line 1683] |  
16 | 1 x [drouting.c | dr_init, line 1677] |  
112 | 2 x [permissions.c | get_pathname, line 309]
160 | 2 x [context.c | register_context_destroy, line 66]
167648 | 1309 x [cfg.lex | addstr, line 889] |  
64 | 1 x [db/db_id.c | new_db_id, line 256]
8 | 1 x [aaa_avps.h | parse_aaa_avps, line 133]
160 | 1 x [reg_mod.c | mod_init, line 376] |  
144 | 2 x [context.c | context_alloc, line 119]
8 | 1 x [pvar.c | pv_init_extra_list, line 4626]
128 | 1 x [cfg.y | yyparse, line 1519] |  
6144 | 1 x [xlog.c | buf_init, line 69] |  
8 | 1 x [dispatcher.c | partition_init, line 571]
16 | 1 x [io_wait.c | init_io_wait, line 576]
8 | 1 x [auth.c | add_credential, line 134]
8680 | 155 x [route_struct.c | mk_exp, line 54] |  
32 | 1 x [cachedb/cachedb.c | cachedb_do_init, line 638]
72 | 5 x [db/db_id.c | dupl_string, line 47]
8020520 | 174292 x [permissions.c | check_addr_fixup, line 1037]
1032 | 1 x [avpops.c | avpops_init, line 298]
4336 | 76 x [map.c | map_get, line 139] |  
80 | 2 x [pvar.c | new_pv_context, line 4765]
24 | 1 x [frd_events.c | frd_event_init, line 74]
155216 | 7499 x [mod_fix.c | fixup_uint, line 167]

**OS/environment information**
Operating System: Ubuntu 18.04.1 LTS (bionic)
OpenSIPS installation: git/source/

**Additional context**
When calculating the memory consumption statistics by dump, the consumption is approximately 75 MB, while the actual memory utilization rate is max used (+ overhead) = 263420376 (263 MB). From the statistics, I do not understand where the memory is consumed. Help me understand the statistics, and find the cause of memory consumption.

**Comment by bogdan-iancu** [comment]
@ilyinvv , the leak of pkg memory is related to the usage of OpenSIPS functions from LUA scripts.  Up to 2.4, the functions provided by OpenSIPS should had a free function to match the fixup function (for parameter conversion). But just a few functions do that :(....the, by doing the fixup at each LUA script execution, they leak memory.
Could you list the OpenSIPS functions you use from your LUA ?

BTW, the 3.0 has a different approach on how the functions are invoked (in regards to the param fixing) and there is no leak ;)

**Comment by ilyinvv** [comment]
I used all the features to the maximum in order to put the code in the loa script:
Here is a list:
check_address
ds_select_dst
pike_check_req
create_dialog
set_dlg_sharing_tag
remove_hf
append_hf
route_to_gw
lookup
nat_uac_test
fix_nated_register
fix_nated_contact
rtpengine_offer
topology_hiding_match
topology_hiding
Apparently it's time to upgrade to version 3

**Comment by ilyinvv** [comment]
Updated to version 3.0, when calling a function with parameters from the LUA, it is impossible to get the parameters:
Lua code:
moduleFunc (arg, "check_address",0,"192.168.1.1",5060,"udp");
Result in the log:
ERROR:core:pv_parse_spec: bad parameters
 unknown script variable 'p▒▒#0011V'
On version 2.4 it worked correctly like this:
moduleFunc (arg, "check_address","0","192.168.1.1","5060","udp");
or
local check_address = moduleFunc (arg,"check_address","0",source_ip,source_port,source_protocol);

**Comment by bogdan-iancu** [comment]
@ilyinvv, as this is a completly different issue (for a different version), please open a new report for it.

For the leak reported here, we will evaluate the "fixing" for the mentioned functions to determine which leaks or not, but understand that is a partial, local fix, not a global one - if you will use other script functions from LUA, the leak may appear again :(.

**Comment by ilyinvv** [comment]
created ticket 1766

**Comment by bogdan-iancu** [comment]
@ilyinvv , do still intend to use 2.4 with lua and these script functions ? if yes, we may consider adding the free_fixup functions for the functions you use. If not, we may simply close this ticket, as the problem was addressed in 3.0.
