### ISSUE TITLE
[BUG]Double INVITE when transferring a call

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1763]
**OpenSIPS version you are running**
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3fe6c38
main.c compiled on 02:05:58 Jul 9 2019 with gcc 7

**Describe the bug**
Double INVITE when transferring a call.
If subscriber A has dialed subscriber B, subscriber B puts caller A on hold and makes a call to subscriber C. The OpenSips system sends two INVITE to subscriber C. The telephone set of subscriber C to the second Invite responds with sip 482 request merged. Ultimately, this leads to the collapse of non-dialogue.

**To Reproduce**
In the process, OpenSips uses the following modules:
dialog (Creature dialogue), topology_hiding
dialog settings:
modparam ("dialog", "enable_stats", 1)
modparam ("dialog", "dlg_match_mode", 1)
modparam ("dialog", "db_mode", 3)
modparam ("dialog", "options_ping_interval", 30)
modparam ("dialog", "reinvite_ping_interval", 300)
modparam ("dialog", "dialog_replication_cluster", 1)
modparam ("dialog", "profile_replication_cluster", 1)
modparam ("dialog", "dlg_sharing_tag", "vip = active")
modparam ("dialog", "replicate_profiles_buffer", 1400)
modparam ("dialog", "replicate_profiles_check", 10)
modparam ("dialog", "replicate_profiles_timer", 10)
modparam ("dialog", "replicate_profiles_expire", 10)
Topology_hiding settings
modparam ("topology_hiding", "force_dialog", 0)
modparam ("topology_hiding", "th_contact_encode_passwd", "pqss")
modparam ("topology_hiding", "th_contact_encode_param", "info")

**Expected behavior**
ONE INVITE when sending package

**Relevant System Logs**
Pcap file:
https://yadi.sk/d/z0Wg_bcDjVs83w

**OS/environment information**
Operating System: Ubuntu 18.04.1 LTS (bionic)
OpenSIPS installation: git/source/

**Additional context**
I understand that I cannot influence the generation of the second Invita from the configuration file. I can try not to forward the 482 packet between subscribers B and C, but this solution does not look right.
I would like to hear the correct solution to this problem.

**Comment by razvancrainea** [comment]
From the PCAP trace you've sent I can notice that OpenSIPS does a parallel forking to the second destination, that's why there are two INVITEs. You should determine why there are two branches - probably two registrations from the same contact, etc.
Anyways, doesn't look like a bug, most likely a misconfiguration.
