### ISSUE TITLE
It is not possible to update OpenSips to version 3.0.   Lua moduleFunc function does not work

### ISSUE THREAD

**Issue by ilyinvv** [OpenSIPS/opensips#1766]
**OpenSIPS version you are running**
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: df7a4e77c
main.c compiled on 12:10:07 Jul 12 2019 with gcc 7

**Describe the bug**
Updated to version 3.0, when calling a function with parameters from the LUA, it is impossible to get the parameters:
Lua code:
moduleFunc (arg, "check_address",0,"192.168.1.1",5060,"udp");
Result in the log:
ERROR:core:pv_parse_spec: bad parameters
unknown script variable 'p▒▒#0011V'
On version 2.4 it worked correctly like this:
moduleFunc (arg, "check_address","0","192.168.1.1","5060","udp");
or
local check_address = moduleFunc (arg,"check_address","0",source_ip,source_port,source_protocol);

**To Reproduce**
usr/local/sbin/opensips -F -E /var/log/opensips/opensips.log -P /var/run/opensips/opensips.pid -m 512 -M 64 -u root -g root -f /usr/local/etc/opensips/extensions/opensips.cfg -w /var/log/opensips

**Expected behavior**
Correct work of the Loa ModuleFunc function

**Relevant System Logs**
Result in the log:
ERROR:core:pv_parse_spec: bad parameters
unknown script variable 'p▒▒#0011V'

**OS/environment information**
Операционная система: Ubuntu 18.04.1 LTS (bionic) 
Установка OpenSIPS: git / source /

**Comment by rvlad-patrascu** [comment]
Hello,

Although in OpenSIPS 3.0 the syntax for the script function calls has changed, in the Lua code you still have to use strings for all function arguments. Calling _moduleFunc_ as you did in 2.4 should fix the problem.
