### ISSUE TITLE
[CRASH] OpenSIPs crashes on start-up

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#1779]
**OpenSIPS version you are running**

```
version: opensips 3.0.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9b47639e3
main.c compiled on  with gcc 7
```

**Crash Core Dump**

OpenSIPs Crashes on Startup, please find the file here

https://bit.ly/2GtSrxs

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , you have a quite old revision of 3.0 (from 19th of May) - please first pull the latest git 3.0 version and give it try, to see if the crash is still there or not.

**Comment by syedrizwansrs** [comment]
Hi @bogdan-iancu its working on the latest version. Thank you
