### ISSUE TITLE
[FEATURE]FlatStore: Add total fields even in the case of failed call

### ISSUE THREAD

**Issue by ryanembregts** [OpenSIPS/opensips#1780]
I am using flatstore for cdrs, I see for a successful call i get below fields. 

**Total Fields count 11** 
`INVITE,c516ca39,rg3QD3Qtym0aQ,UwEvEj7_636EGoZC6kadsw..,200,OK,1564067518,0,1564067518,28,27531`

For a failed Call i get below cdrs. 
 
**Total Field count 7**
`INVITE,b25c5d61,,aEPOxIgjd5__0kOuROXCGA..,503,Service Unavailable,1564067458`

Due to missing fields some billing systems(cgrates) cannot parse them. It would be great if we can have equal fields count even in the case of failed cdrs like below. (For above cdr) 

`INVITE,b25c5d61,,aEPOxIgjd5__0kOuROXCGA..,503,Service Unavailable,1564067458,,,,`

Best Regards, 
Ryan

**Comment by razvancrainea** [comment]
Could you please tell us what version of OpenSIPS you are using? I am asking because those fields should be there in versions of OpenSIPS grater than 2.4.

**Comment by ryanembregts** [comment]
@razvancrainea Thanks for the reply I have just tested it on 
`version: opensips 3.0.0 (x86_64/linux)` 

It works fine for the transactions. But if you try to use `cdr` flag behavior is same.  Below are the cdrs that I get while setting flag like        
         create_dialog("B");
        # when routing via usrloc, log the missed calls also
        do_accounting("log|db","failed|cdr");

`INVITE|bd073064|BcNjBjZgKr89S|AZiSVPTpXzPQM1mbIrS5DQ..|200|OK|1564416247|3|1564416244|9|9268`
`INVITE|3c765d47||Px0vKZyC5aMpDtWTNy8XFw..|408|Request Timeout|1564416265`

Thanks again for your time.
