### ISSUE TITLE
[BUG] Siptrace module using HEP over TCP exhausts file descriptor limit when connection are closed/rejected

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1781]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 18:41:52 Jul 26 2019 with gcc 7
```

**Describe the bug**

We are experiencing an issue with the siptrace module using HEPv3 over TCP. What we are seeing is that when traffic increases, OpenSIPS is opening a much larger number of sockets to our capture server than we expect. We have our capture server configured to accept a maximum of 2048 connections.
 
We believe that the module is intended to share TCP connections to the capture server; something like one per process. We have found that if we increase traffic at a certain pace, OpenSIPS will attempt to open multiple connections per process and will exhaust the 2048 port limit on the server. When this happens, connections begin to fail and the max async messages (hep_async_max_postponed_chunks) is exceeded. We believe this causes the proto_hep module to switch to blocking TCP, as we see all OpenSIPS processes then block against siptrace for up to 5 minutes. The proto_hep TCP connect and send timeouts are set to the defaults, but these do not seem to be being honored for non-async connections.

Here is an example where a single OpenSIPS instance had attempted over 400 TCP connections to the capture server:
[https://pastebin.com/4jKQtZZY](https://pastebin.com/4jKQtZZY)

After this had been happening for a while, OpenSIPS began constantly logging a single line:
``` 
Jul 26 18:20:17 [7006] ERROR:core:handle_new_connect: failed to accept connection(24): Too many open files
```
I took a look at file descriptors on the system and found that OpenSIPS’ TCP Main thread has 65536 open file descriptors.
 ```
# opensipsctl ps
Process::  ID=0 PID=6981 Type=attendant
Process::  ID=1 PID=6983 Type=event-route handler
Process::  ID=2 PID=6984 Type=MI Datagram
Process::  ID=3 PID=6985 Type=MI Datagram
Process::  ID=4 PID=6986 Type=MI Datagram
Process::  ID=5 PID=6987 Type=time_keeper
Process::  ID=6 PID=6988 Type=timer
Process::  ID=7 PID=6989 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=8 PID=6990 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=9 PID=6991 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=10 PID=6992 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=11 PID=6993 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=12 PID=6994 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=13 PID=6995 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=14 PID=6996 Type=SIP receiver udp:10.32.18.155:5060
Process::  ID=15 PID=6997 Type=TCP receiver
Process::  ID=16 PID=6998 Type=TCP receiver
Process::  ID=17 PID=6999 Type=TCP receiver
Process::  ID=18 PID=7000 Type=TCP receiver
Process::  ID=19 PID=7001 Type=TCP receiver
Process::  ID=20 PID=7002 Type=TCP receiver
Process::  ID=21 PID=7003 Type=TCP receiver
Process::  ID=22 PID=7004 Type=TCP receiver
Process::  ID=23 PID=7005 Type=Timer handler
Process::  ID=24 PID=7006 Type=TCP main
 
# ls /proc/7006/fd/ | wc -l
65536
```
All of the other OpenSIPS process had hundreds of open FDs as well. It appears that when the HEP capture server started rejecting connections, the file descriptors for those sockets were leaked by OpenSIPS.
 
I captured a trap with the system in this state: [https://pastebin.com/H4M9eUSu](https://pastebin.com/H4M9eUSu)

**To Reproduce**

1. Start OpenSIPS
2. Start rapidly increasing traffic with HEP siptrace over TCP enabled
3. Inspect netstat output for number of connections being opened.

**Expected behavior**

OpenSIPS should open only one TCP socket to the capture server per process, or some reasonable proximity. OpenSIPS should release file descriptors for sockets that have been closed/rejected by the remote server.

**Relevant System Logs**

```
Jul 26 13:06:04 [7012] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7012] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7012] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7012] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7032] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7032] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7032] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7032] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7017] ERROR:siptrace:save_siptrace: Failed to duplicate with hep to <xx.xx.xx.com:9061>
Jul 26 13:06:04 [7017] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7017] ERROR:proto_hep:msg_send: send() to 10.32.198.140:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7017] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7017] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7027] ERROR:siptrace:save_siptrace: Failed to duplicate with hep to <xx.xx.xx.com:9061>
Jul 26 13:06:04 [7027] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7027] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7027] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7027] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7014] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7014] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7014] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7014] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7016] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7016] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7016] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7016] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7015] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7015] ERROR:proto_hep:msg_send: send() to 10.32.198.140:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7015] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7015] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7019] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7019] ERROR:proto_hep:msg_send: send() to 10.32.198.140:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7019] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7019] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jul 26 13:06:04 [7021] ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jul 26 13:06:04 [7021] ERROR:proto_hep:msg_send: send() to 10.32.244.31:9061 for proto hep_tcp/9 failed
Jul 26 13:06:04 [7021] ERROR:proto_hep:hep_tcp_send: failed to send
Jul 26 13:06:04 [7021] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
```

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
This issue does still occur. I can provide more information if needed.

**Comment by razvancrainea** [comment]
Can you get the output of `lsof -p $PID_OF_TCP_MAIN` when this happens?
Also, it would be helpful if you could compile opensips with the `-DDBG_STRUCT_HIST` and `-DDBG_TCPCON` flags, so we can get more information.

**Comment by bcnewlin** [comment]
Yes, I can get that. It will take just a little while.

**Comment by bcnewlin** [comment]
@razvancrainea I've compiled with the extra flags you requested, but how will you get any data from that? Do you need logs or a trap or is there some other command I need to run to dump the connection info?

**Comment by bcnewlin** [comment]
I have not been able to reproduce the extreme yet, though I am still trying. I have been monitoring the `lsof -p $PID_OF_TCP_MAIN`output during our traffic today, and the number of open FDs has been increasing steadily which implies a leak. I captured a sample here: https://pastebin.com/bemZ1gWa

**Comment by bcnewlin** [comment]
We set our capture server max connection down to essentially zero, and that did reproduce the TCP connection leak immediately. Open FDs for TCP main jumped by many hundred in just a few minutes, and has not gone back down even though we increased the capture server max connections again. I captured another `lsof`. This is on the same server as the last one.
https://pastebin.com/FSaRabbp

**Comment by razvancrainea** [comment]
I will try to reproduce this as well, to see if I can get more info. Will keep you updated.

**Comment by bogdan-iancu** [comment]
@bcnewlin , as I understand, the fd leak happens only in the TCP MAIN process and it seems to be directly correlated to the failures to write on the HEP conn.
The proto_hep module, upon a write failure, will mark the connection as bad (S_CONN_BAD) and return/release the connection to the TCP MAIN process, which will also close the conn corresponding socket in that process.
So:
1) do you see an 1-to-1 relation between the leaking fd's and the failed write ops ?
2) if you run the `list_tcp_conns` MI cmd (https://www.opensips.org/Documentation/Interface-CoreMI-2-4#toc5), do you still see any leaking at connection level ?
3) as per [this comment](https://www.opensips.org/Documentation/Interface-CoreMI-2-4#toc5), should I understand that the leak is 100% and fast reproducible if the capturing server rejects any HEP incoming connect??

**Comment by bcnewlin** [comment]
@bogdan-iancu We will have to reproduce to confirm 1 and 2 which will take a little bit. For 3, yes the leak seems to occur quickly and immediately if the capturing server simply rejects all TCP connections.

**Comment by bogdan-iancu** [comment]
From the initial post I noticed you use a really old 2.4 (7 months ago). Not sure if you updated in the mean while, but ideally you use one of the latest versions of 2.4, just to be sure you have all the fixes which were done in the mean while.

Now, regarding (3) - by rejecting you mean (a) not listening/accepting new conns or (b) accepting and immediately closing ? I'm asking as I could try to build this scenario as it is a fast way to reproduce the problem.

**Comment by bcnewlin** [comment]
Yes the version was old. We have upgraded since then but are not actively using TCP for HEP due to this issue right now. That is why it will take me a bit to reproduce, as I have to switch back to TCP. Reproduction attempts will be using our current version which is up to date.

In our reproduction the HEP server was listening but not accepting new connections as we had set the maximum number of connections allowed to 0.

**Comment by bogdan-iancu** [comment]
If listening but not doing accept, I guess this will translate (on the client side) into a timeout upon connect ? According to the logs you originally posted, I see a Broken pipe event while doing a `send()` - somehow this make me believe that the connect() was successful (and the accept on the other side), but the connection closed? I'm trying to figure this out, just to be able to reproduce the scenario.
BTW, by chance, you do not have a pcap showing the evolution of such a TCP conn ?

**Comment by bcnewlin** [comment]
@bogdan-iancu We are actually using OpenSIPS for the capture server as well and we got it to reject connections by setting `tcp_max_connections` to zero. So it would depend on how OpenSIPS responds to receiving a HEP TCP connection attempt in that case.

**Comment by bogdan-iancu** [comment]
@bcnewlin, I manage to reproduce the setup, but not the effect .
Here are the logs I get, the same as yours : 
```
Jan  7 18:27:12 [32385] ERROR:proto_hep:async_tsend_stream: Failed first TCP async send : (32) Broken pipe
Jan  7 18:27:12 [32385] ERROR:proto_hep:hep_tcp_send: failed to send
Jan  7 18:27:12 [32385] ERROR:proto_hep:msg_send: send() to 127.0.0.1:7777 for proto hep_tcp/9 failed
Jan  7 18:27:12 [32385] ERROR:proto_hep:send_hep_message: Cannot send hep message!
```

but there is no change in the number of fds, after several runs - not sure if this is good news or bad news :)
