### ISSUE TITLE
[BUG] sql_cacher does not handle empty DB tables properly

### ISSUE THREAD

**Issue by clifjones** [OpenSIPS/opensips#1784]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 12:13:13 Jul 30 2019 with gcc 7
```

**Describe the bug**

I was testing the sql_cacher fixes @rvlad-patrascu and found a corner case that results in outdated cache entries when a DB table is empty. 
**Note: I have fixed this bug.  See attached patch**
Please let me know if you would rather have a pull request to correct this.

**To Reproduce**

The error case can reproduced as follows:
1. Start OpenSIPS
2. Populate a DB table that is backed by sql_cacher with 1 or more rows.
3. Issue ```opensipsctl fifo sql_cacher_reload <cache ID>```
4. Check for cached DB entries.  (Should be there)
5. Delete all rows in the DB table used in step 2.
6. Issue ```opensipsctl fifo sql_cacher_reload <cache ID>``` again
7. Check for cached DB entries.  (Cache contains rows from step 2)

**Expected behavior**

The cache should be cleared of old entries upon ```sql_cacher_reload``` command.

**Relevant System Logs**

```
Jul 29 20:02:16 [332] WARNING:sql_cacher:load_entire_table: Table: inbound_map is empty!
```

**OS/environment information**
 - Operating System: Docker version 18.09.2, build 6247962
 - OpenSIPS installation: source
 - other relevant information: Bug exists in 2.4 and master

**Additional context**
I have produced a minimal patch against  the following commit of ```master```:
```
commit ff245d48e9ac1c90a805eaa9f7517646ddef9e0f (HEAD -> master, origin/master, origin/HEAD)
```

See attached patch.

[sql_cacher_073019.patch.txt](https://github.com/OpenSIPS/opensips/files/3446798/sql_cacher_073019.patch.txt)

**Comment by bogdan-iancu** [comment]
@clifjones , thanks for the detailed report and for the fix. I took the liberty to change a bit your patch, mainly to remove the warning log - I don't think is the case to have it there.
Please re-test the fix as committed (devel only), and upon your confirmation I will do the backport too.

**Comment by clifjones** [comment]
I just verified your patch and our tests pass using your proposed commit.

**Comment by bogdan-iancu** [comment]
Thanks @clifjones , backports done, closing here
