### ISSUE TITLE
[BUG] Possible bug in parse_uri

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1785]
Hi guys.

I was debugging drouting in latest 2.4 recently and found it parses uri like this ```sip:1.2.3.4;transport=tcp``` with port=0 instead of port=5060. Could you please check if this is parse_uri bug?

examples in dr_gateways table:
sip:1.2.3.4 parsed like host 1.2.3.4 and port 5060
sip:1.2.3.4;transport=tcp parsed like host 1.2.3.4 and port 0
sip:1.2.3.4:5060;transport=tcp parsed like host 1.2.3.4 and port 5060

isn't this a bug?
I saw this adding
```
LM_ERR("DEBUG [%s] [%d] [%s] [%d] [%d] [%d]\n", ip_addr2a(&pgwa->ips[j]), pgwa->ports[j], ip_addr2a(ip), port, pgwa->protos[j], proto);
```

in gw_matches_ip function right after "for" line.

to reproduce urls from above must be in dr_gateways table.

**Comment by bogdan-iancu** [comment]
@nikbyte , according to my checks, only the `sip:1.2.3.4:5060;transport=tcp` URI returns a non 0 port value in the parsed structure.
The `sip:1.2.3.4` URI (first example) reports 0 also.

**Comment by bogdan-iancu** [comment]
The parser works as expected, setting a `0` value if there is no port specified in the URI. The `sip_resolvehost()` function is the one that should translate the `0` value to the the default port value according to the transport protocol.
So, do you have the `proto_tcp.so` module loaded ?

**Comment by bogdan-iancu** [comment]
Upon further tests, I can confirm that the `0` port value will not be translated to the default value if the there is no module loaded and listener set for that given protocol.

**Comment by nikbyte** [comment]
Upon further tests, I can confirm that the 0 port value will not be translated to the default value if the there is no module loaded and listener set for that given protocol.

yes. I investigated the code more and it's exactly issue description for me.
Thank you for the explanation.

**Comment by nikbyte** [comment]
Just a note. in drouting.c

> if ( (pgwa->ports[j]==0 || port==0 || pgwa->ports[j]==port) &&

pgwa->ports[j]==0 condition is impossible because of sip_resolvehost() which replaces 0 with default port number.

**Comment by bogdan-iancu** [comment]
yes, it looks like, useless and harmless :)
