### ISSUE TITLE
[BUG] E_ACC_MISSED_EVENT copies params from previous E_ACC_CDR generated by another call

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#1786]
Hello,
E_ACC_MISSED_EVENT copies  duration,ms_duration,setuptime from previous call which was processed by current thread.

to repeat this bug please do the following things:

do_accounting("db|evi", "cdr|missed", "cdr");

startup_route {
        if (!subscribe_event("E_ACC_CDR", "xxxxx"))
                xlog("L_ERR","Cannot subscribe RabbitMQ to E_ACC_CDR\n");
        }
        if (!subscribe_event("E_ACC_MISSED_EVENT", "xxxxx))
                xlog("L_ERR","Cannot subscribe RabbitMQ to E_ACC_MISSED_EVENT\n");
        }
}

when 2 calls finished ( succesfull and missed ) I have the following events:

E_ACC_CDR
method::INVITE
from_tag::t5mj4cK0XB1ZD
to_tag::1176543519-3910217397-620759208-365339024
callid::f5c5b8b3-2fd0-1238-bdb5-56000208f33a
...
duration::41
ms_duration::41679
setuptime::10
created::1564754529

E_ACC_MISSED_EVENT
method::INVITE
from_tag::vQ7372m7QXD5m
to_tag::*rj50uFb2bIUE8bhW9myGxPEMT0htAAq
callid::fb84aea1-2fd0-1238-bdb5-56000208f33a
sip_code::487
sip_reason::Request Terminated
time::1564754583
..
duration::41
ms_duration::41679
setuptime::10
created::1564754529

Look at the repeting duration, duration,setuptime,created

**Comment by fedkis** [comment]
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 49b1efc
main.c compiled on 16:34:28 Aug  2 2019 with gcc 4.8.5

**Comment by bogdan-iancu** [comment]
@fedkis , so first you do a successful call (to get some duration and setup time) and after that you do a failed call to get some miss_call event ? And this event will "inherit" the values?

**Comment by fedkis** [comment]
Yes, first I made a successful call  , then I made a missed call and the values duration,setuptime,created were inherited. Probably only if the same thread is used because the inherit is not every time repeated.

**Comment by fedkis** [comment]
It is only connected to evi.  As for db , there isn't any problems with missed calls after successfull calls

**Comment by bogdan-iancu** [comment]
good catch @rvlad-patrascu  !
