### ISSUE TITLE
[CRASH] async rest call on call end causes core dump

### ISSUE THREAD

**Issue by rrevels** [OpenSIPS/opensips#1791]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: edef893c5
main.c compiled on 03:30:03 Jun 19 2019 with gcc 4.8.5

```

**Crash Core Dump**
https://pastebin.com/raw/AAzLGT1W

**Describe the traffic that generated the bug**
When using async rest calls while a SIP BYE message is being process I get core dumps.  I also get core dumps in another section of code than what is in the backtrace when doing async rest calls on negative final responses.

I do not get core dumps if I don't use the async method but only do the rest call.

I did not have this issue when using the 2.2 branch of opensips.

**To Reproduce**
1. Get BYE or negative final response to SIP call
2. Do message processing including an async rest call that succeeds
3. Check OpenSIPS crashed (if not every call then within 3 calls)

**Relevant System Logs**

**OS/environment information**
 - Operating System: cent os 7
 - OpenSIPS installation: compiled from source tarball
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@rrevels , try to pull the latest 2.4 (use nightly builds or GIT) and give it a try - the backtrace reminds me somehow of an old bug (potentially fixed).

**Comment by rrevels** [comment]
I pulled the latest build and ran my tests again.  The problem is resolved!  Thank you very much.

**Comment by bogdan-iancu** [comment]
Wow, this was an easy one :)

**Comment by rrevels** [comment]
I guess I spoke too soon.  The issue is not nearly as prevalent as before (and thus the reason im going to open a different report) but there is still an issue.

One question before I move on though, where are the nightly builds in tar file format?  I was able to pull the latest build via git but I can't seem to find a url link to a tar file.

**Comment by bogdan-iancu** [comment]
@rrevels , are the new backtraces similar to the original one ? if yes, we should reopen. If not, better open a new ticket.
In regards to the tar files - there are no official nightly tar files, but you can grab tar files from github, at any time you want - https://github.com/OpenSIPS/opensips/archive/2.4.zip

**Comment by rrevels** [comment]
Yep, that link was exactly what i need.  Thank you.

Yes, the backtrace looks pretty much the same.  I'll reopen this.

I can do the async rest call when the INVITE is first received, and the call completes, with no issue.  However, if I do the rest call async when the BYE is received then within the first 100 calls I get the core dump attached when I opened this report.  If I do the rest call not async when the BYE is processed I do not get a core dump (and this is my work-around for the moment).

**Comment by rrevels** [comment]
Oh, and the thing that is different now than last week is that, so far, I haven't gotten a core dump when doing async rest calls when the proxy handles negative final responses.   I was getting those as well on the 2.4.6 release.

**Comment by rrevels** [comment]
I have found that if I change the order of functions i call that I can avoid the core dump.  To produce a core the sequence of events is 

receive BYE
call t_relay
call async rest call
catch rest response and exit

to not produce a core i instead do

receive BYE
call async rest call
catch rest response
call t_relay
check rest response and exit

**Comment by rrevels** [comment]
I am closing this again as I still see the core dumps but many changes have occurred since I first opened this so I'm going to start fresh.
