### ISSUE TITLE
[BUG] uac_auth issue with ACK CSEQ 

### ISSUE THREAD

**Issue by ivanoff946** [OpenSIPS/opensips#1792]
Hello guys!

Latest opensips 3.0 (nightly).
I use topology hiding without dialog support, but together with uac_auth module. I have ACK CSeq issue.
INVITE ->  [CSeq 102]
401 <-
INVITE ->  [CSeq 103]
200 <-
ACK <-  [CSeq 102, but must be 103]
however if I don't use uac_auth module everything is ok, dialog looks like:
INVITE ->  [CSeq 102]
200 <-
ACK <-  [CSeq 102, the same as INVITE]

Thank you!

**Comment by bogdan-iancu** [comment]
@ivanoff946, could you check #1528 ? it looks similar / the same to me .

**Comment by ivanoff946** [comment]
Thank you, Bogdan. I tried the trick from #1528 and it doesn't work for me.

**Comment by bogdan-iancu** [comment]
@ivanoff946 , the original flow description is not 100% clear - like the ACK is in opposite direction to the INVITE :-/ .
Please upload a pcap taken from the OpenSIPS doing the uac_auth(), covering the incoming and outgoing traffic. Of course for a call where the ACK CSEQ is bogus :)
