### ISSUE TITLE
[BUG] cluster_check_addr doesn't support hostname resolution

### ISSUE THREAD

**Issue by pasanmdev** [OpenSIPS/opensips#1798]
**OpenSIPS version you are running**
```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6fa40aa12
main.c compiled on  with gcc 6.3.0

```

**Describe the bug**

clusterer module cluster_check_addr  doesn't support hostname if the sip_addr or url contains a hostname instead of an ip address.

Ex: - 
-[ RECORD 2 ]---+-------------------------------------
id              | 3
cluster_id      | 1
node_id         | 1
url             | bin:sipnode1.voip.com:5566
state           | 1
no_ping_retries | 3
priority        | 50
sip_addr        | sipnode1.voip.com
flags           | seed
description     | Node1

When I call cluster_check_addr("1", "$si") from node 2 for pkts coming from Node 1, function doesn't return success as it compares source ip against hostname string not the resolved one.

probably need to resolve addr before compare ?

**To Reproduce**

Set bin url or sip_add to a hostname instead of an IP address

**Expected behavior**
cluster_check_addr("1", "$si") should return success if pkts coming from source ip which matches the sip_addr or url hostname in clusterer table

**OS/environment information**
 - Operating System:  Debian 9
 - OpenSIPS installation:  debian package

**Comment by bogdan-iancu** [comment]
@pasanmdev, by design, the module is suppose to accept **only** IP addresses, noting else. You will have to DNS resolve your names before populating the `address` table .
So, this is not a BUG.

**Comment by pasanmdev** [comment]
@bogdan-iancu you mean cluster_check_addr function is design for handling ip addresses ?
because I can use a valid hostname in both sip_addr and url in clusterer table and module resolves them and they work fine. I'm also confused with "address" table here that's related to permissions module right ?
if sip_addr is only design to accept ip, it shouldn't accept hostname IMO :)
anyway Thanks , I'll keep this in mind.

**Comment by bogdan-iancu** [comment]
Sorry @pasanmdev , I have had cross read the initial post, thinking of the IP checking functions from the "permissions" module, and not from the "clusterer" module - even if your post is very clear on that.
Still, this is not a bug. If the `cluster_check_addr()` accepts only IPs for checking, this is it. The fact that you can provision the sip_addr as as hostname is not 100% relevant. What is relevant is the fact the OpenSIPS converts all provisioning data to IPs and internally operates with IPs. During runtime OpenSIPS is not aware of the hostnames anymore (the DNS resolution is done when provisioning data is loaded from DB).

**Comment by pasanmdev** [comment]
All good @bogdan-iancu , Thanks for the clarification :)
