### ISSUE TITLE
[BUG] Missing reply status code and reason in failure route

### ISSUE THREAD

**Issue by danpascu** [OpenSIPS/opensips#1803]
**OpenSIPS version you are running**

```
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT, DBG_LOCK
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 217613cc7
main.c compiled on  with gcc 8
```

**Describe the bug**

In the failure route this log line:

```
xlog("L_INFO", "In dialog $rm failed with $(<reply>rs) $(<reply>rr) ($ci)\n");
```

sometimes produces this output:

```
Aug 14 07:42:34 node15 ./opensips[10182]: In dialog NOTIFY failed with <null> <null> (e43a1aa3-8d79-4d20-ae41-b3cce302d6c1)

or

Aug 14 07:42:55 node15 ./opensips[10185]: In dialog INVITE failed with <null> <null> (77f21bf3-dee2-42dd-82fa-c3d144c10888)
```

**To Reproduce**

Not sure. It doesn't happen in all cases.

**OS/environment information**
 - Operating System:  Debian sid
 - OpenSIPS installation:  git

**Comment by bogdan-iancu** [comment]
@danpascu , without any additional information (how to reproduce, or some particularities of the problem) it is impossible to debug this issue (assuming that the printing is 100% of the time from a failure route.

Try to run that chunk of script in debug level ( use $log_level var) and see if you notice any dbg like:

`"Invalid %p pv context message"`
