### ISSUE TITLE
[CRASH] OpenSips Crashes during traffic

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#1808]
[CRASH] OpenSips Crashes during traffic

**OpenSIPS version you are running**

```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 69c12ff9e
main.c compiled on  with gcc 7
```

**Crash Core Dump**

https://bit.ly/2OYoI6I

**OS/environment information**
 - Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-52-generic x86_64)

**Comment by razvancrainea** [comment]
I believe I've narrowed down this issue. Will soon provide a fix for it.

**Comment by adamoverbeeke** [comment]
Thats great to hear. Please let me know if you need us to do anything.

**Comment by razvancrainea** [comment]
@adamoverbeeke did you manage to run with the commit a48aeca? Do you still experience the crash?

**Comment by bcnewlin** [comment]
@razvancrainea Adam is out on vacation. We are blocked from upgrading to any newer revisions of OpenSIPS due to #1779 and #1799 (via #1771). This has prevented us from testing a number of fixes that have been delivered recently.

**Comment by razvancrainea** [comment]
Commit 17430901 seems to have done the trick. Closing this ticket now.
