### ISSUE TITLE
[FEATURE] control the waiting for new branches in EBR

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#1811]
This is derived from #1235.

The problem : as it is, the EBR engine, via `t_wait_for_new_branches()` will wait for new branches (and delay the final response back to the caller) until the FR_INVITE timer hits. So, even if you had 2 branches, both completed with negative replys, nothing will be sent back to caller until FR_INVITE timer hits as opensips will wait for potential new injected branches. Bottom line, opensips has no idea for how many injected branches to wait, so it waits until FR_INVITE fires.

The solution: instruct OpenSIPS on how many branches are expected. Some options would be :

- when you do t_wait_for_new_branches(), to also say a max of branches to wait for. If all expected branches failed, the transaction will be closed without waiting for FR_INVITE timer. 

- when you do t_inject_branch() to set a new flag (via params) saying this is the last branch to inject, do not wait for any others. 

Thanks to @atrips for brainstorming on this.

**Comment by atrips** [comment]
Sorry for the noise about this one, just pinging.

**Comment by fgast** [comment]
Are there plans to backport this to 2.4.x?

**Comment by baklee** [comment]
I modified it to add the number of branches to 2.4.9 by referring https://github.com/OpenSIPS/opensips/commit/cff27be9c1ec9fd875484ed27d7cd2e567db02ce.

1. script 
$avp(branches) = $var(i);
t_wait_for_new_branches("$avp(branches)");

2. source
 modules/tm/t_fwd.c

-int add_phony_uac( struct cell *t)
+int add_phony_uac( struct cell *t, int br_flags)
 {
 	str dummy_buffer = str_init("DUMMY");
 	unsigned short branch;
 	t->uac[branch].request.my_T = t;
 	t->uac[branch].request.branch = branch;
 	t->uac[branch].flags = T_UAC_IS_PHONY;
+	t->uac[branch].br_flags = br_flags;
 
 	/* in invalid proto will prevent adding this retransmission buffer
 	 * to the retransmission timer (there is nothing to retransmit here :P */

modules/tm/t_fwd.h 

-int add_phony_uac( struct cell *t);
+int add_phony_uac( struct cell *t, int br_flags);

modules/tm/t_reply.c

 static inline int t_pick_branch( struct cell *t, int *res_code, int *do_cancel)
 {
+#define PHONY_NO_WAIT(_t,_b) \
+			(_t->uac[_b].br_flags && _t->uac[_b].br_flags<=_t->nr_of_outgoings)
 	int lowest_b, lowest_s, b, prio;
 	unsigned int cancelled;

	cancelled = was_cancelled(t);
 	*do_cancel = 0;
 	for ( b=t->first_branch; b<t->nr_of_outgoings ; b++ ) {
+		if ( (t->uac[b].flags & T_UAC_IS_PHONY) && (
 		/* skip PHONY branches if the transaction was canceled by UAC;
 		 * a phony branch is used just to force the transaction to wait for
 		 * more branches, but if canceled, it makes no sense to wait anymore;
 		 * Exception - do not ignore the branch if there is reply pushed
 		 * on that branch, like an internal timeout or so */
-		if ( (t->uac[b].flags & T_UAC_IS_PHONY) &&
-		(t->flags & T_WAS_CANCELLED_FLAG) &&
-		t->uac[b].last_received<299 )
+		(t->flags & T_WAS_CANCELLED_FLAG && t->uac[b].last_received<299)
+		||
+		/* also skip a PHONY branch if it has a true setting about how
+		 * many branches are to be waited. The max branch idx to be waited
+		 * is stored in the 'br_flags' flags of the uac */
+		PHONY_NO_WAIT(t,b)
+		))
 			continue;
 		/* skip 'empty branches' */
 		if (!t->uac[b].request.buffer.s) continue;

modules/tm/tm.c

 static int w_t_new_request(struct sip_msg* msg, char*, char*, 
 		char*, char*, char*, char*);
 static int w_t_inject_branches(struct sip_msg* msg, char *s_flags);
-static int w_t_wait_for_new_branches(struct sip_msg* msg);
+static int w_t_wait_for_new_branches(struct sip_msg* msg, char*);
 
 struct sip_msg* tm_pv_context_request(struct sip_msg* msg);
 struct sip_msg* tm_pv_context_reply(struct sip_msg* msg);


		0, REQUEST_ROUTE},
 	{"t_inject_branches",(cmd_function)w_t_inject_branches,2,fixup_inject,
 		0, REQUEST_ROUTE},
-	{"t_wait_for_new_branches",(cmd_function)w_t_wait_for_new_branches,0, 0,
+	{"t_wait_for_new_branches",(cmd_function)w_t_wait_for_new_branches,1, fixup_spve_null,
 		0, REQUEST_ROUTE},
 	{"t_anycast_replicate", (cmd_function)tm_anycast_replicate, 0, 0,
 		0, REQUEST_ROUTE},


-static int w_t_wait_for_new_branches(struct sip_msg* msg)
+static int w_t_wait_for_new_branches(struct sip_msg* msg, char* br_to_wait)
 {
+        str br_to_wait_s={NULL,0};
+        long counts;
+        int last_branch;
+
 	struct cell *t;
 
 	t=get_t();



-	if (add_phony_uac(t)<0) {
+        if(br_to_wait == NULL || fixup_get_svalue(msg, (gparam_p)br_to_wait, &br_to_wait_s)!=0) {
+                LM_ERR("Invalid time argument\n");
+                return -1;
+        }
+
+        counts = atol(br_to_wait_s.s);
+	last_branch = counts ? (t->nr_of_outgoings+counts+1) : 0;
+
+
+	if (add_phony_uac(t, last_branch)<0) {
 		LM_ERR("failed to add phony UAC\n");
 		return -1;
 	}

**Comment by baklee** [comment]
I modified it to add the number of branches to 2.4.9 by referring to the https://github.com/OpenSIPS/opensips/commit/cff27be9c1ec9fd875484ed27d7cd2e567db02ce.

1. Add script
'$avp(branches) = $var(i);'
't_wait_for_new_branches("$avp(branches)");'
2.Source Code
![image1](https://user-images.githubusercontent.com/42561619/120946036-10642900-c776-11eb-8a2c-f75e09890d00.png)
![image2](https://user-images.githubusercontent.com/42561619/120946110-4bfef300-c776-11eb-9c77-49454d997234.png)
![image3](https://user-images.githubusercontent.com/42561619/120946112-4e614d00-c776-11eb-9bd4-d5ae1f295a95.png)
![image4](https://user-images.githubusercontent.com/42561619/120946113-50c3a700-c776-11eb-846b-2126ae2956c2.png)
![image5](https://user-images.githubusercontent.com/42561619/120946115-528d6a80-c776-11eb-82f8-d156faf292cb.png)

**Comment by bogdan-iancu** [comment]
@fgast , no it will not be backported to 2.4 as this is not a fix to a bug/probile, but rather an enhancement.

**Comment by baklee** [comment]
@bogdan-iancu Thanks for your reply.

I'm concerned whether the modification doesn't have any other side effects.
I don't understand the logic well.
But I haven't found anything it while testing.

Also, there is one more issue .
If there are two callees, passing INVITE to one callee,
and the rest of the callee does not passing INVITE,

The 487 response to the caller's cancel goes up to timeout.
