### ISSUE TITLE
[BUG] b2b error processing retrasmiting ack after new INVITE

### ISSUE THREAD

**Issue by arttemk** [OpenSIPS/opensips#1812]
**OpenSIPS version you are running**

version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0

**Describe the bug**
b2b scenario retransmition ACK process with REINVITE After OK

SIP Messages Diagram
 
A <==> OpenSips <==> B

INVITE(Seq 1) => OpenSips => B Invite (Seq 2)
    OK (Seq1)    <=      OpenSips  <=    B (OK Seq 2)
                         resending OK after timeout 500ms
     OK (Seq1)    <=      OpenSips  <=    B (OK Seq 2)
..... 
    ACK (Seq1) =>  OpenSips =>ACK (Seq2)
    RE-INVITE (Seq 2) =>  OpenSips =>RE-INVITE (Seq 3)
    ACK (Seq 1) => OpenSips !!!! => ACK (Seq 3)
   But this is not this ACK Transaction for new INVITE !!!
     Decide that this ACK on INVITE (Seq 2)
     b2b_state as ESTABLISHED (from State B2B_MODIFIED)
                                  OpenSips !!!! <= OK (Seq3) 
                                      
**To Reproduce**
.... 
b2b scenario
A<=>OS<=>B

A send  OS => (INVITE SEQ 1)
OS send B (INVITE SEQ 2)

B answer to OS => OK (SEQ 2)
OS send A => OK (SEQ 1)
A wait 1000 ms
OS send A => OK (SEQ 1)

---- A send three packets very quickly
A  answer OS => ACK(SEQ 1)
A  send OS => INVITE(SEQ 2)
A  answer OS => ACK(SEQ 1)
 -- OS 
OS send B => ACK (SEQ2)
OS send Invite  B => ACK (SEQ3)
OS send B => ACK (SEQ3) !!!
--  
B send OS => OK (SEQ3)
....
OS nothing send 

**Expected behavior**
Expected behavior
we may Ignore ACK on SEQ that not current INVITE TRANSACTION

**Relevant System Logs**

**OS/environment information**
Debian 9
 - OpenSIPS installation: debs

**Additional context**

BTW: Small fix that help me (it's not recover all problem, just fix don't go to 
B2B_ESTABLISHED from B2B_MODIFIED, because we don't receive OK, and so ACK can not be here )
in file
modules/b2b_entities/dlg.c

-       if(method_value == METHOD_ACK && dlg->state == B2B_ESTABLISHED)
+       if(method_value == METHOD_ACK && (dlg->state == B2B_ESTABLISHED || dlg->state==B2B_MODIFIED))

maybe this is OK, but i'm not sure in case packet loss or other...

**Comment by bogdan-iancu** [comment]
@arttemk , IMHO, A is a bit broken in this scenario - why sending the RE-INVITE (Seq 2) BEFORE the second ACK (Seq 1) ?
A must be sure that the previous transaction completed (the initial INVITE) before starting a new one.
As he received two 200 OK for the initial INVITE, it must do first ACK for them, and only after that it is ok to start the re-INVITE transaction.

I'm not saying the B2B code fault-less, but the scenario is neither correct.

**Comment by arttemk** [comment]
A is a bit broken in this scenario - why sending the RE-INVITE (Seq 2) BEFORE the second ACK (Seq 1) ?

Phone send RE-INVITE AFTER he receive ACK, it's normal
 i try describe in another way

what happened on A side
A => SEND INVITE(1)
A <= RECEIVE OK (1)
Sleep(600ms)
A => SEND ACK (1)
A => SEND RE-INVITE(2)
A <= RECEIVE OK (1) As a retransmit because not receive ACK on first OK()
A => SEND ACK (1) as retransmit

what happened on OpenSips side (for leg A)

OS <= receive INVITE(1)
OS => send OK (1)
after 500 ms
OS => send OK (1) as retransmit
OS <= receive ACK(1)
OS <= receive RE-INVITE(2) (dialog state go to B2B_MODIFIED)
OS <= receive ACK(1) as retransmit
OS <= receive RE-INVITE(1) (dialog state go to B2B_ESTABLISHED) incorrect transition state


Simple way is (don't go to B2B_ESTABLISHED state from state B2B_MODIFIED, only from state B2B_CONFIRMED) 

More correct way is remember INVITE/REINVITE SEQ  for initiator B2B_MODIFIED
and don't go to B2B_ESTABLISHED if (ACK.SEQ!=INVITE.SEQ for initiator)
but it more complex because need more changes

**Comment by bogdan-iancu** [comment]
Do you have a SIPP scenario to reproduce this ?

**Comment by arttemk** [comment]
Thank you, i'll do it on monday
