### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bshirazi** [OpenSIPS/opensips#1814]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7

```

**Describe the bug**

In cachedb_local different group name overwrite each other.
**To Reproduce**

root@os24:~# opensipsctl fifo cache_store local:group2 taghi 123456ms
root@os24:~# opensipsctl fifo cache_store local:group3 taghi 66666666666666666
root@os24:~# opensipsctl fifo cache_fetch local:group3 taghi
key:: taghi
value:: 66666666666666666
root@os24:~# opensipsctl fifo cache_fetch local:group2 taghi
key:: taghi
value:: 66666666666666666

**Expected behavior**

root@os24:~# opensipsctl fifo cache_fetch local:group2 taghi
key:: taghi
value:: 1234ms
**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
Hi, @bshirazi!

Please configure separate collections for your `cachedb_local.so` module.  Below is an example output in OpenSIPS 3.0, once I configured each cache group/identifier with its own collection:

```
modparam("cachedb_local", "cachedb_url", "local:test1:///")
modparam("cachedb_local", "cachedb_url", "local:test2:///collection2")
```

```
(opensips-cli): mi cache_store local:test1 taghi 123456ms
"OK"
(opensips-cli): mi cache_store local:test2 taghi 66666666666666
"OK"
(opensips-cli): mi cache_fetch local:test1 taghi
{
    "key": "taghi",
    "value": "123456ms"
}
(opensips-cli): mi cache_fetch local:test2 taghi
{
    "key": "taghi",
    "value": "66666666666666"
}
```
