### ISSUE TITLE
[CRASH] 3.1-nightly Debian 10 Buster

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#1815]
**OpenSIPS version you are running**

```
root@f7cd3079b064:/cores# opensips -V
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 21348b39c
main.c compiled on  with gcc 8

```

**Crash Core Dump**
https://pastebin.com/RNaG5JNq

**Describe the traffic that generated the bug**
Can not start opensips default script.

**To Reproduce**

1. 
`docker run --ulimit core=99999999999:99999999999 --mount source=coredumps_volume,target=/cores --cap-add=SYS_PTRACE -it debian:buster /bin/bash`

2. 
```
apt-get update -y
apt install gnupg --no-install-recommends
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
echo "deb http://apt.opensips.org buster 3.1-releases" >/etc/apt/sources.list.d/opensips.list

```

3.
`apt-get update -y && apt-get install -y --no-install-recommends opensips*`

4. Just run opensips binary
`opensips`

**Relevant System Logs**
https://pastebin.com/EYZNuxB7

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: 3.1-nightly packages

Same procedure above with version 3.0-nightly
`echo "deb http://apt.opensips.org buster 3.0-releases" >/etc/apt/sources.list.d/opensips.list
`
is working as expected.

thank you
Vasilios Tzanoudakis

**Comment by liviuchircu** [comment]
Thank you for the awesome report, @vtzan!  This underlying issue was fixed in af1e4425
