### ISSUE TITLE
[FEATURE] use auth_ha1 field if set for remote registrations in uac_regiistrant to avoid plaintext passwords

### ISSUE THREAD

**Issue by kgalinurov** [OpenSIPS/opensips#1817]
I think it would be great port this feature from kamaillio to uac_regiistrant module. 
https://github.com/kamailio/kamailio/commit/9b501c49450646b47b740c7cc82a6a755f6f10f5
https://github.com/kamailio/kamailio/commit/163f73feb1f423270c3ecab7dec30b5d7cee0964
https://github.com/kamailio/kamailio/commit/3c980e1a820bd5981b8f68e393a8404131b49bec

**Comment by razvancrainea** [comment]
I've just encountered the same problem and I realized that this is already possible in OpenSIPS: you can specify ha1 passwords/hashes just as any password, but prefixing it with `0x` (i.e.`0x014cc383ef058c280d7f0bde8f0e6606`).
