### ISSUE TITLE
drouting: reload is broken in 3.0+

### ISSUE THREAD

**Issue by MayamaTakeshi** [OpenSIPS/opensips#1824]
**OpenSIPS version you are running**
```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9ab2494
main.c compiled on 14:11:16 Sep 10 2019 with gcc 4.9.2

```

**Crash Core Dump**
https://pastebin.com/5skx2Qj7

**Describe the traffic that generated the bug**
No traffic. Just use of opensips-cli

**To Reproduce**
1. Start OpenSIPS
2. Run: opensips-cli -x mi dr_reload

**OS/environment information**
 - Operating System: Debian 8
 - OpenSIPS installation: git 

**Additional context**
Other commands work, only dr_reload is failing:
```
[root@lab002141-basix-ban opensips-3.0]$ opensips-cli -x mi dr_gw_status
SQLAlchemy version:  1.3.3
{
    "Gateways": [
        {
            "ID": "0",
            "IP": "192.168.2.143",
            "State": "Active"
        },
        {
            "ID": "1",
            "IP": "192.168.2.142:6060",
            "State": "Active"
        }
    ]
}
[root@lab002141-basix-ban opensips-3.0]$ 
[root@lab002141-basix-ban opensips-3.0]$ opensips-cli -x mi dr_reload
SQLAlchemy version:  1.3.3
ERROR: communication exception for 'dr_reload' returned: 
ERROR: Is OpenSIPS running?
```

**Comment by liviuchircu** [comment]
It seems that in 3.0+, the mi_fifo module process does not have the routes of the script anymore due to [this logic](https://github.com/OpenSIPS/opensips/blob/master/pt.c#L315), so it now crashes while looking up the corresponding route of the `dr_rules.routeid` field of the `dr_rules` table during a `dr_reload`.

**Comment by bogdan-iancu** [comment]
As a completion here : the crash will happen only if a DR rule reference (in its definition) a script route (which is optional). Otherwise the reload work just fine,
