### ISSUE TITLE
[BUG] mid-registrar with multi-domain results strange Contact header / 3.0

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#1826]
**OpenSIPS version you are running**

```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9ab24947b
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**
Using mid-registrar in AoR mode in combination w/ modparam("usrloc", "use_domain", 1) results in Contact header as shown:

Contact: <sip:yxa%4086.4.14.104@10.236.95.110:5060>

**To Reproduce**
#### USeR LOCation module
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "working_mode_preset", "single-instance-no-db")
modparam("usrloc", "use_domain", 1)

loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2) /* 0 = mirror / 1 = ct / 2 = AoR */
modparam("mid_registrar", "outgoing_expires", 2592000)
modparam("mid_registrar", "min_expires", 60)
modparam("mid_registrar", "max_expires", 2592000)
modparam("mid_registrar", "max_contacts", 16)

**Comment by liviuchircu** [comment]
hey, @atrips !  That is the only way to generate unique contacts going into the main registrar layer.  Suppose your IP is `mid-registrar.com` and you serve two domains, with the following users:
* alice@atlanta.com
* alice@biloxi.com

The mid-registrar will generate the following unique contacts which will be presented further downstream:

* sip:alice%40atlanta.com@mid-registrar.com
* sip:alice%40biloxi.com@mid-registrar.com

A bit ugly, but perfectly valid from a SIP point of view.  Does this create any issues on your side?

**Comment by atrips** [comment]
Hello @liviuchircu, actually a chain of events happens :) FreeSWITCH as registrar accepts registration but when INVITE is generated back from FS to OpenSIPS it results to undecoded RURI like that:
```
INVITE sip:user@x.x.x.x@y.y.y.y;transport=tcp SIP/2.0
```
Result is that OpenSIPS in not happy at all with that request and responds with `400 bad r-uri`.

Currently I'm testing with FS but this setup should interact with multiple other 3th party implementations and I'm expecting issues there too.

**Comment by liviuchircu** [comment]
I understand.  Hopefully, you can find a way to disable the un-escaping behavior.

As a last resort, we could add some modparam that controls how the AoR is encoded.  For example, if we'd select the "base64" option for it instead of "url-encode", the advertised contact for `alice@atlanta.com` would then become `sip:YWxpY2VAYXRsYW50YS5jb20K@mid-registrar.com`, which should make any downstream element happy.

**Comment by atrips** [comment]
The problem with is that setup should work with 3th party implementations. I suppose I can disable un-escaping but it will not help me in general.

Second approach is available in SEMS and it works 50/50 by my experience unfortunately. My target is OpenSIPS to behave most possible like UA. Maybe I'm missing something in big picture but having contact like `alice@ip:port` and using `To:` in AoR lookup will be fine. Just another remark, contact like `alice@ip:port;uid=YWxpY2VAYXRs` is also working 50/50 :(

**Comment by liviuchircu** [comment]
I see nothing wrong with that.  The mid-registrar stores the original Contact under the original AoR, and advertises a locally generated Contact.  Please provide a pcap (email it to liviu@opensips.org if it contains sensitive data) if you have any signaling issues.

**Comment by atrips** [comment]
Thank you for the explanation. It was miss-understanding on my side.
