### ISSUE TITLE
WRONG relay in Sequential requests

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#1829]
I have problem with setup incoming call with TLS support:

UA with TLS supprt is registered. Here is information from AOR
   AOR:: 33341656
                Contact:: sip: 33341656  @192.168.1.106:50443;transport=TLS;ob Q=
                        Expires:: 260
                        Callid:: 554fdfd6ee794451942f693e40fbe362
                        Cseq:: 31813
                        User-agent:: MicroSIP/3.19.18
                        Received:: sip:39.121.145.121:50445;transport=TLS
                        State:: CS_SYNC
                        Flags:: 0
                        Cflags:: TLS RM_ONTO_FLAG SIP_PING_BFLAG NAT_BFLAG
                        Socket:: tls:83.21.101.114:5062
                        Methods:: 8063
                        SIP_instance:: <urn:uuid:00000000-0000-0000-0000-0000a350d2d0>

When make local call to this UA:
======= part ot Opensips script =====
if (lookup("location","m")) {
            .......
            xlog("L_ERR", "RELAY (INVITE) $rd:$rp du=$du ");
            t_relay();
}
============================
Information from log:
  RELAY (INVITE) 192.168.1.106:50433 du=sip:39.121.145.121:50445;transport=TLS

In this case Opensips send relay to Received field from AOR - sip:39.121.145.121:50445;transport=TLS

# Sequential requests
====== part ot Opensips script ======
if (has_totag()) {
          ........
           xlog("L_ERR", "RELAY (Sequential requests) $rd:$rp du=$du ");
           t_relay();
}
============================
Information from log:
  RELAY (Sequential requests) 192.168.1.106:50433 du=<null>
  ERROR:proto_tls:proto_tls_send: connect failed
  ERROR:core:msg_send: send() to 192.168.1.106:50433 for proto tls/3 failed
 
In Sequential requests Opensips try to send message to 192.168.1.106:50433 not for 39.121.145.121:50445. Why?

How to solve this problem?

**Comment by liviuchircu** [comment]
That is very good, but it only solved 50% of the problem, since it only fixes the UAC Contact, on the INVITE.  Do you use an `onreply_route` and do the same thing for the 200 OK Contact of the UAS?

**Comment by goup2010** [comment]
When add to onreply_route all is OK.
Thanks !
