### ISSUE TITLE
[BUG] "listen ... as ..." not honouring advertised address/port when listen on adapter intead of IP

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1837]
**OpenSIPS version you are running**
```
opensips 2.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 5.3.1
```
**Describe the bug**
When running Opensips behind NAT (in a Docker container), we used advertised_address and advertised_port to correctly modify messages with the external hostname/port.

For a single address we do this as follows;
NOTE: The ports need not match due to NAT, but are matched here for simplicity.
```
listen=tls:eth0:5061
advertised_address=sip.example.com
advertised_port=5061
```
This behaves as expected and Record-Route (et al) correctly show "sip.example.com:5061" for the address of the server.

When we run a server with multiple listen sockets, we modify the syntax as follows;
```
listen=tls:eth0:5061 as sip.example.com:5061
listen=tcp:eth0:5060 as sip.example.com:5060
```
This syntax fails e.g. because Record-Route header is not re-written to use the advertised address/port, so instead we get the internal NATd address in the Record-Route and ACK to 200 OK fails to be returned on answering a call because it's attempting to send to e.g. 172.18.0.2.

If the syntax is modified and the NATd IP is used instead of the adapter, it works correctly, **but, this is not practical because the address of the container is not known until the container starts, using the adapter is much more suitable**
This works:
```
listen=tls:172.18.0.2:5061 as sip.example.com:5061
listen=tcp:172.18.0.2:5060 as sip.example.com:5060
```

**To Reproduce**
1. Configure Opensips behind a NAT and listening as above in first adapter based example.
2. Make a call from Alice to Bob
3. Answer call on Bob
4. Bob does not enter the call, ACK to 200 OK is not delivered because Record-Route is a private address and has not been re-written.

**Expected behavior**
SIP packets should be re-written correctly when behind NAT whether the adapter is used or the IP is used, and not only in the latter case.

**Relevant System Logs**
N/A

**OS/environment information**
Ubuntu 16.04.5 in Official Docker image
Opensips 2.4.1 from apt.opensips.org Xenial repository

**Additional context**
N/A

**Comment by bogdan-iancu** [comment]
Thank for the report, @hamid-elaosta - could you confirm the committed fix, please?

**Comment by bogdan-iancu** [comment]
BTW, I just checked and this bug is not present in 3.0 and higher

**Comment by hamid-elaosta** [comment]
Thanks @bogdan-iancu I'll test asap. I'll try and test 3.0 also but I can't switch to it yet due to release process.

**Comment by hamid-elaosta** [comment]
@bogdan-iancu Quick question; Do these fixes make it into the nightlies? I'd like to test the fix and give you a response. I'm currently not able to build from source, but I can install from the apt repository.
