### ISSUE TITLE
[FEATURE][Clarification] Remove dedicated field extraction functions from tm/dlg

### ISSUE THREAD

**Issue by lemenkov** [OpenSIPS/opensips#1842]
Hello All,
Why we use a dedicated functions for callid/to_tag/etc extraction in tm module ([dlg.c](https://github.com/OpenSIPS/opensips/blob/f829eedda26ab87fc2cf31b52a0e87b7b920e96f/modules/tm/dlg.c#L687)) instead of accessing fields right from  `sip_msg* _m`? Note that we've parsed all the fields [right before](https://github.com/OpenSIPS/opensips/blob/f829eedda26ab87fc2cf31b52a0e87b7b920e96f/modules/tm/dlg.c#L682) so all of them should be properly initialized.

I looks like a leftover from SER times but maybe I am missing something?

**Comment by razvancrainea** [comment]
@lemenkov the `parse_headers` function only sets for each header the beginning and end, but does not parse the actual body of the header. Although for callid that's enough (as the body is the entire header, minus the CRLF at the end), for tags and others their bodies need to be explicitly parsed, to extract the useful information.
So I believe the confusion comes from the fact that `parse_headers` does not actually entirely parse all the SIP message's headers, it just separates each header from each other. The actual parsing is done by the dedicated functions.

**Comment by bogdan-iancu** [comment]
Getting to the bottom on this - the mentioned functions are from some obsolete & unused code - the `dlg_request_uas` and `new_dlg_uas` are not used anymore.
I suggest simply dropping the whole chunk of code, it is just ballast.

**Comment by razvancrainea** [comment]
I changed the tag to `question`, as I don't see any feature request yet for this. I will also drop the two functions, since they are not used any more.
Let us know if there's anything else we can clarify, otherwise please close the ticket.
