### ISSUE TITLE
[BUG] can't mode=challenge-callee in dlg_send_sequential

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#1844]
Hi there!

latest master (and 3.0.1 too), I had a look into dlg_req_within.c, mi_parse_mode(), and I still do not get it...

How do you call dlg_send_sequential in mi with a mode!=challenge|caller|callee

Eg, particularly, challenge-callee

Btw, documentation wrongly repeat challenge-caller for both cases

**Comment by razvancrainea** [comment]
@gmaruzz indeed, there's a small typo in the `mode` parser, where the `len` is incremented instead of deducted. Will push a fix now, thanks for reporting it!
