### ISSUE TITLE
[BUG] Route Type variable $rT does not correctly report some route types

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1846]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 15:07:59 Oct  4 2019 with gcc 7
```

**Describe the bug**

The $rT variable does not correctly report all route types.
* `startup_route` is reported as `request_route`.
* `event_route` is reported as the route type of the route that triggered the event when it is configured as synchronous. When run async it is reported as `request_route`
* `timer_route` is reported as `request_route`
* `error_route` is reported correctly 

**To Reproduce**

1. Start OpenSIPS
2. In startup_route, run `xlog("L_ALERT", "route type: $rT");`
3. Inspect logs
4. Notice route type is `request_route`

**Expected behavior**

The route type variable should support all distinct route types.

**Relevant System Logs**

N/A

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
@bcnewlin thanks for reporting this! I've just pushed a fix in the master branch, and I'd rather leave it here for a while to make sure this doesn't break any overzealous checks at runtime. I'm keeping this ticket open until we can confirm it's all good to backport.

**Comment by bcnewlin** [comment]
@razvancrainea Sounds good. Thanks for the quick fix!

**Comment by bcnewlin** [comment]
@razvancrainea Is this ready to port back?

**Comment by razvancrainea** [comment]
Did you manage to backport this and test it on your 2.4 yet? If not, I can create the backport, if you're able to deploy it and test everything is all right.

**Comment by bcnewlin** [comment]
Sorry, I didn't realize you were waiting on me for that. I will grab it and test and let you know.

**Comment by razvancrainea** [comment]
No worries, I was not waiting for you :). I was just waiting for anyone who was using this module to report if they see/run into any issues with this change.

**Comment by bcnewlin** [comment]
I tried to cherry-pick the commit and test with a patch, but several of the files have changed extensively between 2.4 and 3.0 and I don't have ready knowledge needed to fix the conflicts. If you can provide a backport patch I would be happy to test it.

**Comment by razvancrainea** [comment]
My apologies, I completely forgot to backport this. You can find [here](https://gist.github.com/razvancrainea/c138c97db24ac37e3abd074b6ddec1bb) the 2.4 backport of the 2ae5120 commit.

**Comment by bcnewlin** [comment]
Thanks, I have verified the fix with that patch.

**Comment by razvancrainea** [comment]
@bcnewlin as I am still reluctant to backport this in 2.4, since it might have some side effects, I will only leave it in the master, for 3.1 now.
If you need this fix, please keep the patch in your sources, if you're sure it doesn't affect your setup. Thanks for your help with this!
