### ISSUE TITLE
[FEATURE] add support to fetch $rl_count(name) value through Exported MI Functions

### ISSUE THREAD

**Issue by ryanembregts** [OpenSIPS/opensips#1847]
**Is your feature request related to a problem? Please describe.**

Currently, I see no simple way to get the value of $rl_count(name) from opensips. Either, i need to use some database or rest apis. It would be nice if we can get this value through jsonrcp request like we do to get the size of profile from dialog module

**Describe the solution you'd like**
Like, we get for dialog profile. 
`opensips-cli -x mi profile_get_size inbound_calls`

We can use same logic for $rl_count like below. 
`opensips-cli -x mi rl_count pipe_name`

**Implementation**
 
  - Component: ratelimit
  - Type: MI Functions
  - Name: MI command

**Describe alternatives you've considered**
Current, i am using redis for this. I store this value in redis and my webapplication  reads this from redis. 

Best, 
Ryan

**Comment by razvancrainea** [comment]
You can already do this using the `rl_list` [function](https://opensips.org/html/docs/modules/3.0.x/ratelimit.html#mi_rl_list), like `opensips-cli -x mi rl_list pipe_name`.

**Comment by ryanembregts** [comment]
Ah @razvancrainea sorry, i did miss those functions. Thanks. But when i try to execute the provided example i see below error. 

`root@home:/tmp# opensips-cli -x mi rl_list gw_10.0.0.1`
`ERROR: command 'rl_list' returned: -32000: Server error`

**Comment by razvancrainea** [comment]
Most likely you do not have the `gw_10.0.0.1` pipe defined, that's why you get an error. I admit it's not the best indication of that, but can you make sure it works with a pipe that you have actually defined?

**Comment by ryanembregts** [comment]
@razvancrainea you were right, it works as long as pipe exits but as soon pipe is destroyed we get above error. Thanks again. :)
