### ISSUE TITLE
[BUG] [flatstore cdrs] created time is misplaced for a successful call 

### ISSUE THREAD

**Issue by ryanembregts** [OpenSIPS/opensips#1853]
**OpenSIPS version you are running**

version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0

**Describe the bug**
I see for a successful call, `created` time is misplaced as compared to a failed call.

**To Reproduce**
#### ACCounting module
loadmodule "acc.so"
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
modparam("acc", "detect_direction", 0)
modparam("acc", "db_url", "flatstore:/etc/opensips/cdrs")

do_accounting("log|db","failed|cdr");

I see for successful calls we get `created` time at 7th location starting from 0.

`INVITE,gK002a001c,8ravmjS2BS0cg,826286136_133812697@67.67.130.45,200,OK,1570705611,5,1570705606,19,19102`

In failed cdrs we get `created` time at 6th location. 

`INVITE,gK04145291,KUQKFtQr8Xc4c,822354406_92210141@67.67.130.45,480,Temporarily Unavailable,1570705435`

**Expected behavior**
`created` time should be at the same location(6th) no matter if call was successful or failed. This will avoid a further check at cdrs parsing. (We just need to get 6th element for the created time instead of checking if call was failed or successful and getting created time from different locations based upon that. 

Best, 

Ryan

**Comment by rvlad-patrascu** [comment]
Hi @ryanembregts 

Technically speaking, the ``created`` acc field is not included for the failed transactions, only for successful calls, and represents the timestamp when the call was created (invite received). The 6th field, which is called ``time`` in acc module's terminology, is the timestamp when that acc record was created, for both types of accounting.

Maybe what would be useful to you is having the same number of fields written for 'cdr' and 'failed' accounting (see https://github.com/OpenSIPS/opensips/issues/1780).
