### ISSUE TITLE
[BUG] cr_reload_routes memory leak

### ISSUE THREAD

**Issue by wangduanduan** [OpenSIPS/opensips#1856]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ade908f
main.c compiled on 06:37:43 Jul 29 2019 with gcc 4.9.2
```

**Describe the bug**

cr_reload_routes memory leak。

opensips runing without any call or register, then i use ab to test the mi http api。

```
ab -n 10000 -c 10 "http://192.168.40.20:8888/mi/carrierroute/cr_reload_routes?arg="
```

the chart is `real_use_size` from the statistics。after the test ,  the real_use_size is never reduce。

![image](https://user-images.githubusercontent.com/16631306/66696501-28fd1100-ecff-11e9-8b17-c114c5fc6f2b.png)

i have a time_route, the time_route will cause the real_use_size grow slowly。

```
timer_route[wj_cr_reload, 10]{
    xlog("exec cr_reload_routes");
    exec_msg("opensipsctl fifo cr_reload_routes");
}
```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by wangduanduan** [comment]
yes, it is。shmem:real_used_size

**Comment by bogdan-iancu** [comment]
OK, to confirm (or not) the leak, please refer to https://opensips.org/Documentation/TroubleShooting-OutOfMem and try to grab a memory dump at shutdown.
