### ISSUE TITLE
How to over come this dlg-timer, tm-utimer,ul-timer and etc.

### ISSUE THREAD

**Issue by hpng6** [OpenSIPS/opensips#1858]
**OpenSIPS version you are running**
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: dac56fa49
main.c compiled on 01:05:00 Oct 15 2019 with gcc 7

**Describe the bug**
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 33508370 ms ago (now 33509290 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29041990 ms ago (now 29042100 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled 33448810 ms ago (now 33509290 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:timer_ticker: timer task <tm-timer> already scheduled 33508370 ms ago (now 33509290 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:timer_ticker: timer task <blcore-expire> already scheduled 33508370 ms ago (now 33509290 ms), skipping execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042090 ms ago (now 29042200 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509270 ms ago (now 33509390 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042190 ms ago (now 29042300 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509370 ms ago (now 33509490 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509470 ms ago (now 33509590 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042290 ms ago (now 29042400 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042390 ms ago (now 29042500 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509570 ms ago (now 33509690 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509670 ms ago (now 33509790 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042490 ms ago (now 29042600 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[3085]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 29042590 ms ago (now 29042700 ms), delaying execution
Oct 15 14:14:05 dzwxktdilukbnoup /usr/local/sbin/opensips[29918]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 33509770 ms ago (now 33509890 ms), delaying execution

**Comment by liviuchircu** [comment]
@hpng6 that looks like a deadlock, or even a crash.  Could you run `sudo opensips-cli  -x trap` and paste the output here, or send it to liviu@opensips.org ? Thanks!

**Comment by devangn** [comment]
Hello @liviuchircu 

# opensips -V
version: opensips 2.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 66114a66c
main.c compiled on 06:52:54 Dec 27 2018 with gcc 4.9.2

Having the almost same issue; getting continuous logs

# tail -f /home/opensips.log 
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <ul-timer> already scheduled for 60440 ms (now 1791362280 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <localcache-expire> already scheduled for 600630 ms (now 1791362280 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <tm-timer> already scheduled for 900 ms (now 1791362280 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <blcore-expire> already scheduled for 900 ms (now 1791362280 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362380 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362480 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362580 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362680 ms), it may overlap..
Oct 18 10:14:20 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362780 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362880 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791362980 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791363080 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791363180 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 200 ms (now 1791363270 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <ds-pinger> already scheduled for 10820 ms (now 1791363270 ms), it may overlap..
Oct 18 10:14:21 hostname /usr/local/sbin/opensips[14607]: WARNING:core:timer_ticker: timer task <dr-pinger> already scheduled for 30670 ms (now 1791363270 ms), it may overlap..

And share the trap logs to your email address, mentioned above.

**Comment by liviuchircu** [comment]
@devangn I replied on email.  Make sure to also install `opensips-dbg` package before running the trap command, otherwise it won't be able to extract any useful info.  Thanks!

**Comment by fenichelar** [comment]
@liviuchircu We are seeing the same issue. It occurs at a seemingly random time, i.e. days or weeks after the server has been running. Below is the `opensips.cfg` file. I will include the output of `sudo opensips-cli -x trap` shortly.


```
#### Configure core parameters
auto_aliases = no
children = 64
disable_503_translation = yes
disable_core_dump = yes
disable_dns_failover = yes
dns_try_naptr = no
dns_use_search_list = no
log_level = 3
log_stderror=no
open_files_limit = 8192
server_signature = no
tcp_connect_timeout = 1000
tcp_connection_lifetime = 100
tcp_keepalive = 1
tcp_keepcount = 20
tcp_keepidle = 5
tcp_keepinterval = 5
tcp_listen_backlog = 1024
tcp_max_connections = 65536
tcp_max_msg_time = 1

#### Setup listeners
listen = udp:*:5060
listen = tcp:*:5060
listen = tls:*:5061

#### Load modules
mpath = "/usr/lib/x86_64-linux-gnu/opensips/modules"
loadmodule "proto_udp.so"
loadmodule "proto_tcp.so"
loadmodule "proto_tls.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "signaling.so"
loadmodule "maxfwd.so"
loadmodule "rr.so"
loadmodule "options.so"
loadmodule "avpops.so"
loadmodule "sipmsgops.so"
loadmodule "uac.so"
loadmodule "uac_redirect.so"
loadmodule "cfgutils.so"
loadmodule "tls_mgm.so"

#### Configure modules
modparam("tm", "fr_timeout", 2)
modparam("tm", "fr_inv_timeout", 5)
modparam("tm", "onreply_avp_mode", 1)
modparam("tm", "restart_fr_on_each_reply", 1)
modparam("tls_mgm", "tls_method", "TLSv1_2")
modparam("tls_mgm", "ca_list", "/etc/opensips/tls/ca.pem")
modparam("tls_mgm", "tls_handshake_timeout", 1000)
modparam("tls_mgm", "tls_send_timeout", 1000)

#### Routing logic
route {
  if ($ml > 8192) {
    sl_send_reply("413", "Request Entity Too Large");
    return;
  }

  if (!mf_process_maxfwd_header("10")) {
    sl_send_reply("483", "Too Many Hops");
    return;
  }

  record_route();

  if (loose_route()) {
    if (is_method("INVITE")) {
      if (!t_relay("0x02")) {
        sl_reply_error();
      }
      return;
    } else if (is_method("ACK")) {
      if (!t_relay("0x02")) {
        sl_reply_error();
      }
      return;
    }
  } else {
    if (is_method("BYE")) {
      if (!t_check_trans()) {
        sl_send_reply("400", "Bad Request");
      }
      return;
    }
  }

  if (is_method("INVITE")) {
    sl_send_reply("100", "Trying");
    if (!t_check_trans()) {
      route(2);
    }
  } else if (is_method("ACK")) {
    if (t_check_trans()) {
      t_relay();
    }
  } else if (is_method("OPTIONS")) {
    sl_send_reply("200", "OK");
  } else {
    t_relay();
  }
}

route[2] {
  $T_fr_inv_timeout = null;
  $avp(identity) = null;

  t_on_reply("1");
  t_on_failure("1");

  remove_hf("P-Source-Device");
  append_hf("P-Source-Device: $si\r\n");

  $du = "sip:sip.clearip.com:5061;transport=tls";
  if (!t_relay()) {
    sl_send_reply("502", "Bad Gateway");
    exit;
  }
}

route[3] {
  if (next_branches()) {
    t_on_branch("1");
    t_on_reply("1");
    t_on_failure("1");
    t_relay();
  } else {
    t_reply("503", "Service Unavailable");
  }
}

onreply_route[1] {
  if (t_check_status("180") || t_check_status("183")) {
    $T_fr_inv_timeout = 100;
  }
}

failure_route[1] {
  if (t_check_status("3[0-9][0-9]")) {
    $avp(fromuri)=$fu;
    avp_subst("$avp(fromuri)", "/([^@]*@)[^;?> ]*(.*)/\1$Ri\2/");
    $avp(identity) = $(<reply>hdr(X-Identity));
    $avp(pai) = $(<reply>hdr(P-Asserted-Identity));
    get_redirects("*");
    set_count("$branch", "$var(branchcount)");
    if ($var(branchcount) > 0) {
      serialize_branches(0);
      route(3);
    } else {
      t_on_branch("1");
      t_on_reply("1");
      t_on_failure("1");
      t_relay();
    }
  } else if (t_check_status("486") || t_check_status("487") || t_check_status("6[0-9][0-9]")) {
    return;
  } else if (t_check_status("408")) {
    if (t_local_replied("last")) {
      route(3);
    }
  } else {
    route(3);
  }
}

branch_route[1] {
  uac_replace_from("$avp(fromuri)");

  if ($avp(identity) != null) {
    remove_hf("Identity");
    append_hf("Identity: $avp(identity)\r\n");
  }

  if ($avp(pai) != null) {
    remove_hf("P-Asserted-Identity");
    append_hf("P-Asserted-Identity: $avp(pai)\r\n");
  }
}
```
