### ISSUE TITLE
how use imc module script and function

### ISSUE THREAD

**Issue by hpng6** [OpenSIPS/opensips#1859]
i have tried with like below.
#loadmodule "imc.so"
#modparam("imc", "imc_cmd_start_char", "#")
#modparam("imc|usrloc", "db_url", "mysql://opensips:opensips@localhost/opensips")
#modparam("imc", "rooms_table", "rooms")
#modparam("imc", "rooms_table", "members")
#modparam("imc", "hash_size", 8)

and in route i put this
if(is_method("MESSAGE)
        && (uri=~ "sip:chat-[0-9]+@" || (uri=~ "sip:chat-manager@")
    imc_manager();

**Comment by bogdan-iancu** [comment]
Hey @hpng6! this tracker is for bug/crash/issue reports. For question on how to use  OpenSIPS, please use the users mailing list -> http://lists.opensips.org/cgi-bin/mailman/listinfo/users
