### ISSUE TITLE
[BUG] Load statistic not calculated properly

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1862]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 13:00:46 Oct 16 2019 with gcc 7
```

**Describe the bug**

We recently had a production issue where our servers were overwhelmed with UDP. Our UDP queue lengths grew very large and consequently all UDP processes were at 100% load. We have protections in place checking the system load to attempt to reject messages to reduce load, however we found the reported load statistics don't appear to be correct. Attached are several graphs of the load statistics as exported into our monitoring system. These are the `load1m` values, queried once per minute, for all processes. The values labeled `core` represent the base `load1m` statistic. The label `all` represents `load1m-all`. All other statistics are labeled with the process number.

What you can see is that all of our UDP processes are maxed out at 100%. This is expected as the UDP backlog was quite high. The `all` statistic seems to accurately represent the average of all processes, as there were several with no load. However, the `core` statistic never rose above ~5%. This cannot be correct, since `core` is a subset of `all` that is supposed to contain all of the processes that were at 100%. We have the same number of TCP processes as UDP, so even if all of our TCP processes were at 0 load, which they weren't, that should still result in a `core` load value of 50%.

![Screen Shot 2019-10-16 at 8 56 20 AM](https://user-images.githubusercontent.com/16745821/66922018-3b739500-eff4-11e9-82dc-bd5a050d83f2.png)
![Screen Shot 2019-10-16 at 8 55 58 AM](https://user-images.githubusercontent.com/16745821/66922024-3f071c00-eff4-11e9-8ab3-fc85994efee9.png)

**To Reproduce**

1. Start OpenSIPS
2. Generate enough SIP traffic to create load
3. Verify "core" load statistic is not correct.

**Expected behavior**

The core load statistics are documented to include all SIP message processing activities.

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
Let me double-check with you, to be sure I got your report right: the "all" label (in first chart) maps on `load1m-all` statistic and the "core" label to `load1m`. 
And while the "all" looks fine, the "core" is stuck around 5% ?

**Comment by bcnewlin** [comment]
@bogdan-iancu Yes, that is correct. Since the vast majority of the load was in our UDP message processes, I would expect `load1m` to be higher than `load1m-all`.

**Comment by bogdan-iancu** [comment]
yes, that will be the correct expectation, but not becuase of UDP. The difference between `load1m` and `load1m-all` is about the extra (non worker) procs like MI, RabbitMQ, etc.
Both TCP and UDP are covered by both.
Let me try to run some tests

**Comment by bcnewlin** [comment]
Yes, sorry, that is what I mean. Since the majority of our load at the time was in processes that should be counted by both, the large discrepancy between the two does not make sense.

**Comment by bogdan-iancu** [comment]
OK, I tried to reproduce the scenario:
* have 4 UDP workers
* have 4 TCP workers
* use fifo, http, datagram to create some extra procs

Process listing:
```Process::  ID=0 PID=26227 Type=attendant
Process::  ID=1 PID=26228 Type=MI FIFO
Process::  ID=2 PID=26229 Type=MI Datagram
Process::  ID=3 PID=26230 Type=HTTPD INADDR_ANY:8888
Process::  ID=4 PID=26231 Type=time_keeper
Process::  ID=5 PID=26232 Type=timer
Process::  ID=6 PID=26233 Type=SIP receiver udp:127.0.0.1:5060 
Process::  ID=7 PID=26234 Type=SIP receiver udp:127.0.0.1:5060 
Process::  ID=8 PID=26235 Type=SIP receiver udp:127.0.0.1:5060 
Process::  ID=9 PID=26236 Type=SIP receiver udp:127.0.0.1:5060 
Process::  ID=10 PID=26237 Type=TCP receiver
Process::  ID=11 PID=26238 Type=TCP receiver
Process::  ID=12 PID=26239 Type=TCP receiver
Process::  ID=13 PID=26240 Type=TCP receiver
Process::  ID=14 PID=26241 Type=Timer handler
Process::  ID=15 PID=26242 Type=TCP main
```

Used a very simple OpenSIPS script acting as UAS and generating fake load via `usleep`:
```
	if (!has_totag()) {
		t_newtran();
		usleep("300000");
		send_reply("200","OK");
	} else {
		if (is_method("ACK"))
			t_newtran();
		else
			send_reply("200","OK");
	}
	exit;
```
The `sipp` line:
```
sipp -sn uac 127.0.0.1 -m 100000 -d 2000 -r 5
```
The results, after some minutes (like ~4) to stabilize the load : 
```
load:load1m-proc-6:: 59
load:load:: 24
load:load1m:: 23
load:load1m-all:: 18
```

Which seems consistent.

BTW, using the latest 2.4 code from GIT.

**Comment by bcnewlin** [comment]
I can't argue with your results, they do seem correct. However, I also can't ignore our experience above which is clearly not correct. `load1m` cannot be at 5% when half of all the message receivers are at 100%. Perhaps an error is introduced when some processes get to 100% load?

I will try to reproduce on my end as well.

**Comment by bogdan-iancu** [comment]
I'm not saying you are wrong, I'm just trying to pin-point the trigger / essence of this issue :).

**Comment by bogdan-iancu** [comment]
do you use `auto_scaling` support ?

**Comment by bcnewlin** [comment]
Yes, I understand. We are on 2.4.6 which I do not believe has auto_scaling?

**Comment by bogdan-iancu** [comment]
True, my bad :P ....

**Comment by bcnewlin** [comment]
@bogdan-iancu Further testing on our end has identified this as a bug in a script we are using to convert the MI output to JSON. I will monitor but I no longer believe there is a bug in OpenSIPS.
