### ISSUE TITLE
[CRASH] segfault at f ip 00007f9e5751d059 sp 00007ffeb3fe4b40 error 4 in tm.so

### ISSUE THREAD

**Issue by homstr** [OpenSIPS/opensips#1865]
Hello all )))
We have an issue with 2.4.4. Please see information below. 
Thanks!
Regards, Alexey Borisov.

**OpenSIPS version you are running**
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a42226ccb
main.c compiled on 11:34:53 Mar  5 2019 with gcc 6.3.0

**Crash Core Dump**
https://www.dropbox.com/sh/b7yvlvw6w9sdu29/AAAbD_QmNhZg8BTbKp2Dm-6Ja?dl=0

**Relevant System Logs**
**
------------------------------------------------------------------------------------------------
/var/log/opensips.log

Oct 18 13:49:19 sipproxy2 /sbin/opensips[5476]: b2b_reply (B2B.237.6551799.1571399340)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5475]: b2b_reply (B2B.237.6551799.1571399340)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5475]: b2b_reply (B2B.237.6551799.1571399340)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5499]: b2b_request (A3EC74D61175400BDA9A0897@0270ffffffff)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5499]: b2b_request (A3EC74D61175400BDA9A0897@0270ffffffff)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5499]: b2b_request (A3EC74D61175400BDA9A0897@0270ffffffff)
Oct 18 13:49:19 sipproxy2 /sbin/opensips[5499]: b2b_request (A3EC74D61175400BDA9A0897@0270ffffffff)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5499]: CRITICAL:core:sig_usr: segfault in process pid: 5499, id: 21
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5499]: CRITICAL:core:sig_usr: segfault in process pid: 5499, id: 21
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5511]: b2b_request (557598285@78.136.128.65:5062)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5511]: b2b_request (557598285@78.136.128.65:5062)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5512]: b2b_reply (B2B.372.4761903.1571399315)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5512]: b2b_reply (B2B.372.4761903.1571399315)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5509]: b2b_request (557598285@78.136.128.65:5062)
Oct 18 13:49:20 sipproxy2 /sbin/opensips[5509]: b2b_request (557598285@78.136.128.65:5062)
Oct 18 13:49:21 sipproxy2 /sbin/opensips[5512]: Removing ISUP body in sequential requests to Dial Telecom...
Oct 18 13:49:21 sipproxy2 /sbin/opensips[5512]: Removing ISUP body in sequential requests to Dial Telecom...
Oct 18 13:49:27 sipproxy2 opensips: WARNING:core:solve_module_dependencies: module b2b_entities depends on module uac_auth, but it was not loaded!
Oct 18 13:49:27 sipproxy2 opensips: WARNING:core:solve_module_dependencies: module b2b_entities depends on module uac_auth, but it was not loaded!
-------------------------------------------------------------------------------------------------

/var/log/messages

Oct 18 13:46:57 sipproxy2 /sbin/opensips[5469]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled for 250665190 ms (now 250665200 ms), it may overlap..
Oct 18 13:49:20 sipproxy2 kernel: [248516.747650] opensips[5499]: segfault at f ip 00007f9e5751d059 sp 00007ffeb3fe4b40 error 4 in tm.so[7f9e574ea000+8d000]
Oct 18 13:49:27 sipproxy2 opensips: WARNING:core:solve_module_dependencies: module b2b_entities depends on module uac_auth, but it was not loaded!
Oct 18 13:49:27 sipproxy2 /sbin/opensips[9311]: WARNING:b2b_logic:b2bl_add_tuple: Failed to restore logic info for tuple:entity [349.0][1]

**OS/environment information**
 - Operating System: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 - OpenSIPS installation:  compiled from source code

**Comment by liviuchircu** [comment]
hey @homstr, looking at your 2.4.4, I would strongly advise upgrading to latest sources (the nightly apt packages are most stable IMO) and seeing if the issue persists.  There have been tons of fixes since March.

Also, in case you still get a corefile, could you open it with `gdb /usr/sbin/opensips <corefile>`, and then run `bt full` and upload the output on pastebin or send it to liviu@opensips.org?  Thanks!

**Comment by homstr** [comment]
Hi Liviu! Thanks for your responce )
You can find a coredump in the  dropbox link from a ticket. 
And i just sent it to you..
But you are right.. I have to install a latest update first.....

Thankyou again. And have a nice weekend.
