### ISSUE TITLE
[BUG] proto_smpp  (critical)

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips#1867]
**OpenSIPS version you are running**

```
[root@dev1-fr ~]# opensips -V
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 435890a06

```

**Describe the bug**

SMPP trunk connections setup two database fields get merged tougher

```
| password  | system_type |

``` 

**To Reproduce**

Example:
1. Start OpenSIPS
2. Provision database with smpp trunk settings 
3. Inspect traces on port 2775
4. Notice the password field get "SMPP" on the end always.
5. My provider is confirmed too.

**Expected behavior**

Expecting BIND command will be completed OK

**Relevant System Logs**

**OS/environment information**
 - Operating System:  --> Fedora 29
 - OpenSIPS installation: RPM
 -  Database PgSQL 10

![smpp-bug](https://user-images.githubusercontent.com/3235221/67236464-ad4a4500-f41f-11e9-824e-0346be051f73.png)

**Comment by volga629** [comment]
Waiting for reply from dev team

**Comment by volga629** [comment]
I am using PgSQL database.

**Comment by razvancrainea** [comment]
Am I right if I say your password is exactly 9-digits long?

**Comment by volga629** [comment]
yes

**Comment by razvancrainea** [comment]
OK, I've identified the bug, working on a fix.

**Comment by volga629** [comment]
thank you

**Comment by volga629** [comment]
Can you please provide diff when you are ready that I can apply to 3.0.1 stable release.

**Comment by razvancrainea** [comment]
It's worth mentioning that this is the reason why the SMPP 3.4 recommendations are to max 8 chars in the passwords, just to leave an extra char free for string termination :). But unfortunately we felt into this trap. Will update you when the fix is available.

**Comment by razvancrainea** [comment]
The patch above should sort out this issue. As I documented in the log, what your provider is asking is not entirely correct from SMPP pov. Please apply this patch on your sources and let me know if the problem is resolved. As soon as you confirm, I will backport the change to 3.0.

**Comment by volga629** [comment]
ok thank you  I will test right now

**Comment by volga629** [comment]
Ok I tested and link works as expected right now.
Here are tcpdump screenshot.

![SMPP-OK](https://user-images.githubusercontent.com/3235221/68496626-2cfe4f00-0229-11ea-99e8-5e16d69b2c08.png)

**Comment by volga629** [comment]
Thank you for fixing

**Comment by razvancrainea** [comment]
Perfect, thanks for testing and confirming! Backporting this now.
