### ISSUE TITLE
TLS errstack: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate

### ISSUE THREAD

**Issue by hpng6** [OpenSIPS/opensips#1868]
**OpenSIPS version you are running**
opensips-2.4.6

Oct 23 17:48:53 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_accept: New TLS connection from 183.83.225.236:16305 failed to accept
Oct 23 17:48:53 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
Oct 23 17:48:53 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_read_req: failed to do pre-tls reading
Oct 23 17:48:54 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Oct 23 17:48:54 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 73
Oct 23 17:48:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_accept: New TLS connection from 183.83.225.236:16306 failed to accept
Oct 23 17:48:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
Oct 23 17:48:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_read_req: failed to do pre-tls reading
Oct 23 17:50:20 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Oct 23 17:50:20 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 73
Oct 23 17:50:20 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_accept: New TLS connection from 183.83.225.236:16325 failed to accept
Oct 23 17:50:20 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
Oct 23 17:50:20 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_read_req: failed to do pre-tls reading
Oct 23 17:50:54 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
Oct 23 17:50:54 opensips /usr/local/opensips_proxy/sbin/opensips[4069]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 73
Oct 23 17:50:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_accept: New TLS connection from 183.83.225.236:16335 failed to accept
Oct 23 17:50:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate
Oct 23 17:50:54 opensips /usr/local/opensips_proxy/sbin/opensips[4063]: ERROR:proto_tls:tls_read_req: failed to do pre-tls reading

**Comment by razvancrainea** [comment]
Please avoid opening a ticket similar to a others . Closing as duplicate to #1876.

**Comment by hpng6** [comment]
> Please avoid opening a ticket similar to a others . Closing as duplicate to #1876.

Ok. Sorry...
