### ISSUE TITLE
[BUG] pua_dialoginfo data replication via the dialog cluster 

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#1869]
using pua_dialoginfo to generate BLF

if you have a call ongoing, and you failover in HA setup, entries in pua and presentity DB tables are not cleared when dialog ends on the newly active server.

also, presence (BLF) subscribers are not NOTIFYed when dialog is ended (so the BLF stay on)

expected behavior is:

when a call (dialog) continues to the other server in HA failover:
1) when the call is ended, delete presentity and pua entry from DB
2) send relevant NOTIFY to BLF subscribers

Seems the bug is something like the connection between the dialog module and the pua_dialoginfo module is lost after a HA failover, so when dialog ends, no action is taken in presence related stuff

**OpenSIPS version you are running**

version: opensips 3.0.1 (x86_64/linux)  
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: bc3a861b0
main.c compiled on  with gcc 6.3.0

**Comment by gmaruzz** [comment]
(also, after that a lot of wrong things happen, but they are all related to the fact that presence related things are not cleaned when dialog end on newly active server)

**Comment by bogdan-iancu** [comment]
hey @gmaruzz , the underlying problem is that the the pua hooks (over the dialog) are not replicate when the dialog is replicated between the servers.
Let me investigate more on this

**Comment by gmaruzz** [comment]
Thanks!

**Comment by gmaruzz** [comment]
ping stale bot, don't kill this one :)

**Comment by bogdan-iancu** [comment]
Hi @gmaruzz , after investigating more on the topic, I say this is more a feature request, than a bug. There is no statement that the PUA_xxxx will work in clustered env ;).
I will switch to "feature request" and work out a plan to achieve replication for the  dialog info data.

**Comment by gmaruzz** [comment]
:)

**Comment by gmaruzz** [comment]
nice and steady...

**Comment by bogdan-iancu** [comment]
Hi @gmaruzz , let me contradict myself here :grin: , with what I previously said [here](https://github.com/OpenSIPS/opensips/issues/1869#issuecomment-569289040). There is support for replicating the pua_dialoginfo data via the dialog replication - the pua_dialog info is stored into dlg_vals and passed via dialog replication to the backup server where the callbacks and data should be restored via the DLGCB_LOADED callback.
So, back to original, this is a bug :smile: 
I will do an HA setup do see what is going wrong here

**Comment by gmaruzz** [comment]
thanks! :)

**Comment by bogdan-iancu** [comment]
@gmaruzz, the ea18d829079ef58abeb6d71d00b231af675ea665 + ebb584e1e3b7b2d263f03e6cce526658e1b919ea commits are adding the clustering support for the PUA module, so this will fix the issue here, in the pua_dialoginfo. See https://opensips.org/html/docs/modules/3.2.x/pua.html#pua_clustering (note that the link may be invalid for a couple of hours, until the online docs are re-generated. Or check the README file, the Clustering chapter.

**Comment by bogdan-iancu** [comment]
btw, this will work only for 3.2, it will not be backported to 3.1 as it is more of a feature than a fix (after all :stuck_out_tongue: )

**Comment by gmaruzz** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f61b.png)
Thanks!!

**Comment by gmaruzz** [comment]
works on 3.3.4
