### ISSUE TITLE
Documentation/Manual-2-4 does not show installing from Packages

### ISSUE THREAD

**Issue by paulvi** [OpenSIPS/opensips#1870]
**OpenSIPS version you are running**

```
2.4.6
```

**Describe the bug**

Documentation at https://www.opensips.org/Documentation/Manual-2-4
does not show installing from Packages,  
e.g. Official OpenSIPS RedHat/CentOS/Fedora repository (by Nick Altmann)
https://www.opensips.org/Downloads/Downloads

Particularly, after 
`yum install opensips`  

It is not clear what is  [Install_Path]  
when reading https://www.opensips.org/Documentation/Install-DBDeployment-2-4

(
While if compiling from source,
[Install_Path]  would be path of cloned/downloaded sources
https://www.opensips.org/Documentation/Install-CompileAndInstall-2-4
)

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by paulvi** [comment]
P.S. One can check with `opensips]# rpm -ql opensips`, that

 `opensipsctlrc` file is under `/etc/opensips/` folder 

Yet, it should be explicitely said.

There are other issues with http://yum.opensips.org/packages.php?v=2.4 page.

**Comment by razvancrainea** [comment]
I've just documented these, thanks for pointing them out!
