### ISSUE TITLE
ERROR: database engine not loaded - tried 'MYSQL'

### ISSUE THREAD

**Issue by paulvi** [OpenSIPS/opensips#1872]
**OpenSIPS version you are running**

```
2.4.6
```

**Describe the bug**

Following https://www.opensips.org/Documentation/Install-DBDeployment-2-4

Could not configure db with either MySQL or PostgreSQL

MySQL (mariadb 5.5) installed as  
`yum install mysql`

PostgreSQL (v9.2) installed as  
`yum install postgresql-server postgresql-contrib`

Other option for Postgre woulf be below, but would not that require configuring exact
service name (e.g. `postgresql-11`)

https://www.postgresql.org/download/linux/redhat/

yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
yum install postgresql11
yum install postgresql11-server
/usr/pgsql-11/bin/postgresql-11-setup initdb
systemctl enable postgresql-11
systemctl start postgresql-11

**To Reproduce**

opensipsctlrc file, mostly leaving to defaults

```
## database type: MYSQL, PGSQL, ORACLE, DB_BERKELEY, DBTEXT, or SQLITE
## by default none is loaded
# If you want to setup a database with opensipsdbctl, you must at least specify
# this parameter.
DBENGINE=MYSQL

## database port (PostgreSQL=5432 default; MYSQL=3306 default)
# DBPORT=3306

## database host
DBHOST=localhost

## database name (for ORACLE this is TNS name)
DBNAME=opensipsdb

# database path used by dbtext, db_berkeley, or sqlite
# DB_PATH="/usr/local/etc/opensips/dbtext"

## database read/write user
DBRWUSER=opensipsdbrw

## password for database read/write user
DBRWPW="opensipsdbrw"

## engine type for the MySQL/MariaDB tabels (default InnoDB)
# MYSQL_ENGINE="MyISAM"

## database super user (for ORACLE this is 'scheme-creator' user)
# DBROOTUSER="root"

# user name column
# USERCOL="username"

```

**Expected behavior**

**Relevant System Logs**

```
[root@localhost /]# sudo /sbin/opensipsdbctl create
ERROR: could not load the script in /usr/lib64/opensips/opensipsctl/opensipsdbctl.mysql for database engine MYSQL
ERROR: database engine not loaded - tried 'MYSQL'
```

or

```
[root@localhost /]# /sbin/opensipsdbctl create
ERROR: could not load the script in /usr/lib64/opensips/opensipsctl/opensipsdbctl.pgsql for database engine PGSQL
ERROR: database engine not loaded - tried 'PGSQL'
```

**OS/environment information**
 - Operating System:  CentOS 7
 - OpenSIPS installation:  yum install 
 - other relevant information:

**Additional context**

**Comment by paulvi** [comment]
```
Installed:
  mysql-community-client.x86_64 0:5.7.28-1.el7      mysql-community-libs.x86_64 0:5.7.28-1.el7
  mysql-community-libs-compat.x86_64 0:5.7.28-1.el7 mysql-community-server.x86_64 0:5.7.28-1.el7

...
Complete!
[root@localhost ~]# systemctl start mysqld
[root@localhost ~]# systemctl status mysqld
● mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2019-10-27 20:56:36 EDT; 12s ago
...
Oct 27 20:56:32 localhost.localdomain systemd[1]: Starting MySQL Server...
Oct 27 20:56:36 localhost.localdomain systemd[1]: Started MySQL Server.
[root@localhost ~]# /sbin/opensipsdbctl create
ERROR: could not load the script in /usr/lib64/opensips/opensipsctl/opensipsdbctl.mysql for database engine MYSQL
ERROR: database engine not loaded - tried 'MYSQL'
[root@localhost ~]#
```

**Comment by paulvi** [comment]
P.S. `opensipsdbctl` was removed in 3.0
# https://github.com/OpenSIPS/opensips/issues/1732
so maybe not looked at.

Nevertheless 2.4.x is LTS version, and should get some fixes.

For example, https://www.opensips.org/Documentation/Install-DBDeployment-2-4
says 
> The opensipsdbctl tool can also be used for things like taking backups, doing restores, and more. If you want to see the capabilities and help manual for the opensipsdbctl tool, you can run it with no parameters :
> [Install_Path]/sbin/opensipsdbctl

However, I just get the same error

```
[root@localhost ~]# /sbin/opensipsdbctl
ERROR: could not load the script in /usr/lib64/opensips/opensipsctl/opensipsdbctl.mysql for database engine MYSQL
ERROR: database engine not loaded - tried 'MYSQL'
```

**Comment by razvancrainea** [comment]
Could you tell us how was OpenSIPS installed on your system?

**Comment by Nathuriga** [comment]
I am facing the same issue with opensips version (2.2.2-3build4)
```
./opensipsdbctl create
ERROR: could not load the script in /usr/lib/x86_64-linux-gnu/opensips/opensipsctl/opensipsdbctl.mysql for database engine MYSQL
ERROR: database engine not loaded - tried 'MYSQL'

```

I installed opensips with `apt-get install opensips`

**Comment by liviuchircu** [comment]
@Nathuriga I suspect you have broken packages, since that error signifies that the given `opensipsdbctl.mysql` file path is not present on your system.  And since `2.2` is no longer supported, I would advise installing `2.4` or `3.1` from the [official DEB packages](https://apt.opensips.org/), if possible.  The provided `opensipsctl` and `opensipsdbctl` tools within those packages work just fine.

**Comment by Jiyvn** [comment]
@liviuchircu 
I met the same issue with @Nathuriga, `opensips(2.2.2-3build4)` is installed via `apt`. I solved this issue by installing `opensips-mysql-module` (mentioned on [opensips-cli/module/database](https://github.com/OpenSIPS/opensips-cli/blob/master/docs/modules/database.md#database-schema-files))
![install-opensips-mysql-module](https://user-images.githubusercontent.com/73217816/103170923-0236e600-4883-11eb-9f22-27aa60a11950.jpg)
