### ISSUE TITLE
ERROR:presence:delete_phtable_query: Record not found [FEATURE]

### ISSUE THREAD

**Issue by hpng6** [OpenSIPS/opensips#1875]
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, F_MALLOC, USE_SHM_MEM, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: edef893c5
main.c compiled on 13:37:56 Oct 23 2019 with gcc 4.9.2

Error Report:- 
ERROR:presence:delete_phtable_query: Record not found [a.1572159982.712.5.4]
ERROR:presence:msg_presentity_clean: deleting from pres hash table
ERROR:presence:delete_phtable_query: Record not found [a.1572159982.712.4.0]
ERROR:presence:msg_presentity_clean: deleting from pres hash table

need presence to work, user online/offline status to show all remaining users

**Comment by bogdan-iancu** [comment]
Could you provide some details about the context of getting those errors?

**Comment by hpng6** [comment]
> Could you provide some details about the context of getting those errors?

do i send my cfg code?

**Comment by bogdan-iancu** [comment]
no, cfg is not really needed. Do you use any clustering for presence?  What is the presence scenario producing those errors? Is there a deterministic way to reproduce it ?
