### ISSUE TITLE
[BUG] TLS errstack: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by hpng6** [OpenSIPS/opensips#1876]
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, F_MALLOC, USE_SHM_MEM, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: edef893
main.c compiled on 13:37:56 Oct 23 2019 with gcc 4.9.2

**ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca

ERROR:proto_tls:tls_read_req: failed to do pre-tls reading**

**Comment by razvancrainea** [comment]
Could you tell us what version of libssl you are using?

**Comment by hpng6** [comment]
> Could you tell us what version of libssl you are using?

**OpenSSL 1.0.1t  3 May 2016**
built on: Wed Sep 25 17:53:16 2019
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/usr/lib/ssl"

**Comment by razvancrainea** [comment]
Are you sure your certificates are OK and trusted by your system? Could you double check they work with `openssl`? Check [this](https://www.opensips.org/Documentation/Tutorials-TLS-2-2#toc13) article for more information.
