### ISSUE TITLE
[CRASH] OpenSips Crashes on Startup

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#1877]
**OpenSIPS version you are running**

```
opensips -V
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 552cbbcef
main.c compiled on  with gcc 7
```

**Crash Core Dump**
please find crash data file here
http://shorturl.at/bsHJP

**Describe the traffic that generated the bug**

OpenSips crashes on startup

**Comment by bogdan-iancu** [comment]
In GDB, in frame 0, could you print `ul_dbf` value please?

**Comment by syedrizwansrs** [comment]
here is the info, thanks.
```
(gdb) frame 0
#0  0x0000000000000000 in ?? ()
(gdb) print ul_dbf
$1 = {cap = 825, use_table = 0x7fe44b9b5e80 <db_http_use_table>, init = 0x7fe44b9b4280 <db_http_init>, close = 0x7fe44b9b4c20 <db_http_close>, query = 0x7fe44b9b5d20 <db_http_query>,
  fetch_result = 0x0, raw_query = 0x0, free_result = 0x7fe44b9b4c80 <db_http_free_result>, insert = 0x7fe44b9b5d80 <db_http_insert>, delete = 0x7fe44b9b5db0 <db_http_delete>,
  update = 0x7fe44b9b5de0 <db_http_update>, replace = 0x0, last_inserted_id = 0x7fe44b9b5e40 <db_last_inserted_id>, insert_update = 0x7fe44b9b5e50 <db_insert_update>, async_raw_query = 0x0,
  async_resume = 0x0, async_free_result = 0x0}

**Comment by bogdan-iancu** [comment]
I see you use the db_http backend for usrloc, which has no support for raw SQL queries, as needed by usrloc.

Anyhow, the code is guilty for not checking the db backend capabilities, before start running queries.

**Comment by bogdan-iancu** [comment]
BTW, the support for raw SQL queries is needed only when running in SQL ONLY mode

**Comment by syedrizwansrs** [comment]
We have enabled raw SQL query & the Opensips runs fine until we run this command
`opensips-cli -x mi ul_show_contact location testdp`
Here is the core dump file: https://shorturl.at/dmQ78

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , I just applied a fix for the original problem (checking if the backend supports raw queries).
Still, for the second backtrace you posted, could you repost it as the link seems to expire or so.

**Comment by syedrizwansrs** [comment]
thanks for fix, here is the file.
[crash file.txt](https://github.com/OpenSIPS/opensips/files/3820435/crash.file.txt)

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , I just pushed a fix, please check it out.
