### ISSUE TITLE
[CRASH] OpenSIPS 2.4.6

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#1878]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 0a33e8b00
main.c compiled on 18:33:13 Oct 30 2019 with gcc 6.3.0
```

**Crash Core Dump**

opensips[12157]: segfault at 0 ip 00005642ae2d9bb0 sp 00007fffb9968be0 error 6 in opensips[5642ae1ae000+2be000]
opensips[12157]: ERROR:json:pv_add_json: Invalid parameter for deletion
opensips[12157]: ERROR:core:do_assign: setting PV failed
opensips[12157]: ERROR:core:do_assign: error at /etc/opensips/opensips_proxy.cfg:608
opensips[12157]: CRITICAL:core:sig_usr: segfault in process pid: 12157, id: 24
 
... 
... 
607 $json(ds_down) := "[]";
608 $json(ds_down[]) = $param(1); #param(1) => sip:192.168.20.125
...
...

See coredump here: https://pastebin.com/qpxtU89e

I also enabled QM_MALLOC, DBG_MALLOC and reproduced crash.

opensips[26615]: CRITICAL:core:qm_debug_frag: qm_*: fragm. 0x7f3f8f6e5980 (address 0x7f3f8f6e59b0) beginning overwritten(313a70697322202c)!

See coredump here: https://pastebin.com/hJ7fdjY4
See memdump here: https://pastebin.com/Phyu5nTH

Let me know if you need additional reporting.

**Describe the traffic that generated the bug**

UDP invites, around 100CPS.

**To Reproduce**

Crash is sporadic. After 5-10 mins of test traffic crash occurs.

**OS/environment information**
 - Operating System: Debian 9
 - OpenSIPS installation: git 2.4 nightly version

**Comment by bogdan-iancu** [comment]
@john08burke , do you still have the corefile and binaries for further investigation ?

The idea is to try to spot the culprit prev fragment (which does the overflow). The detection padding 0x313a70697322202c actually translates into `1:pos" ,` string....

**Comment by john08burke** [comment]
@bogdan-iancu, yes I still have the corefile and binaries. It seems to be something with the dst_uri of msg. It looks like some script level error might be causing a loop in setting of $du or something similar. I will take a look associated with this segfault and update you.
```
(gdb) frame 5
#5  0x0000558bea634356 in pv_set_dsturi (msg=0x7f3f8f6e4d50, param=0x7f3f8ee6a2f8, op=52, val=0x7ffdb80516e0) at pvar.c:2601
2601		if(set_dst_uri(msg, &val->rs)!=0)
(gdb) print val->rs
$1 = {s = 0x7f3f8f6e58a0 "sip:192.168.20.149", len = 18}
(gdb) print msg->dst_uri.s
$2 = 0x7f3f8f6e59b0 "92.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192.168.20.149\", \"sip:192"...
```

**Comment by john08burke** [comment]
I narrowed this down to setting $du from within a timer route. I substituted setting $du for a $var(...) as I was only setting $du for code reuse of sub-route.

If there is a use case for $du in timer route, I can help troubleshoot. Otherwise, feel free to close.

**Comment by bogdan-iancu** [comment]
Thanks @john08burke for pin pointing the problem. Setting $du in timer route is useless, as the timer route is outside the context of any SIP message. Still, it should not crash (I just checked the code)
Could you narrow down to the simplest timer_route that crashes OpenSIPS via a $du op?

**Comment by john08burke** [comment]
Here is a minimalist script that causes the crash. It happens usually within a few timer cycles.
```
####### Global Section ########
#### System settings
log_level=2
log_stderror=no
log_facility=LOG_LOCAL1
debug_mode=no

#### Interfaces
listen=udp:MY_IP:5060

####### Modules Section ########
mpath="OSIPS_MPATH"

#### LOAD modules
loadmodule "proto_udp.so"
loadmodule "json.so"
loadmodule "tm.so"

route {
    xlog("L_INFO","Useless script with timer route\n");
}

timer_route[SCHEDULE_PROBE, 10] {
    xlog("L_INFO", "SCHEDULE_PROBE:INFO\n");
    route(PROBE);
}

route[PROBE] {
    xlog("L_INFO", "PROBE:INFO\n");

    $json(probe) := "[]";
    $json(probe[]) = "sip:192.168.20.149";

    $du = $json(probe[0]);
    t_new_request("OPTIONS","$du","SBC PINGER sip:pinger@MY_IP","$du",,"$du");
}
```

**Comment by bogdan-iancu** [comment]
Thank you @john08burke , I managed to reproduce and fix the issue !!
