### ISSUE TITLE
[CRASH] Async HTTPS Crashes

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1879]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4e258b17f
main.c compiled on 21:13:52 Oct 30 2019 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/n3uw63e7

**Describe the traffic that generated the bug**

Async HTTPS call followed by a quick SIP negative response reproduces the crash consistently. This was found while testing the latest version for a possible fix for #1776 , but the crash still occurs.

**To Reproduce**

1. Start OpenSIPS with a config script that uses an async HTTPS call during processing.
2. Send a SIP message.
2. Relay the SIP message from the resume route after the HTTPS call.
3. Configure the downstream SIP server to return an immediate 5xx response.
4. OpenSIPS crashes after a number of these calls.

**Relevant System Logs**

```
Oct 30 21:59:10 [374] INFO:core:handle_sigs: child process 384 exited by a signal 11
Oct 30 21:59:10 [374] INFO:core:handle_sigs: core was generated
Oct 30 21:59:10 [374] INFO:core:handle_sigs: terminating due to SIGCHLD
Oct 30 21:59:10 [376] INFO:core:sig_usr: signal 15 received
Oct 30 21:59:10 [381] INFO:core:sig_usr: signal 15 received
Oct 30 21:59:10 [378] INFO:core:sig_usr: signal 15 received
Oct 30 21:59:10 [375] INFO:core:sig_usr: signal 15 received
Oct 30 21:59:10 [379] INFO:core:sig_usr: signal 15 received
Oct 30 21:59:10 [377] INFO:core:sig_usr: signal 15 received
```

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bcnewlin , this should have been fixed by 1743090195089759ae96584dbae6aa43be049d87 , so try an update and test again

**Comment by bcnewlin** [comment]
I think I posted the wrong OpenSIPS version output. I reproduced this test on a much newer version than what is showing on the ticket. I will re-test and confirm. Sorry for the confusion.

**Comment by bcnewlin** [comment]
I have retested and have not been able to reproduce. I must have mixed up my versions the first time. Thanks!

**Comment by bogdan-iancu** [comment]
should we close then ? :)

**Comment by bcnewlin** [comment]
Sorry, yes I will close.
