### ISSUE TITLE
Corrupted images in modules/seas/doc/images/

### ISSUE THREAD

**Issue by rgagnon24** [OpenSIPS/opensips#188]
All the images in the documentation folder for SEAS module are corrupted, and others might be in other modules.

I believe this is due to subversion or git properties being enabled on .gif and .png file types.

The original files need to be re-added after removing the properties from the files.  Current SVN properties show as:

svn:eol-style native
svn:keywords  Date
svn:ignore  *.d *.so *.o

Either .png and .gif need to be added to the ignore list, or just remove all the properties from any binary file.

**Comment by bogdan-iancu** [comment]
anyhow, the seas module is obsolete starting 3.1 and 99.9999999% unused in the prev versions
