### ISSUE TITLE
UPSERT is needed instead of INSERT into location table(PgSQL)

### ISSUE THREAD

**Issue by derkan** [OpenSIPS/opensips#1880]
**OpenSIPS version you are running**
```
version: opensips 2.2.7 (x86_64/freebsd)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_MALLOC, USE_UMUTEX_MUTEX
MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, select, kqueue.
git revision: 1df7195a1
main.c compiled on 19:41:45 Jul  3 2019 with gcc7 7.3.0
```

**Describe the bug**
Using userloc with PostgreSQL causes many `duplicate key value violates unique constraint "location_pkey"` errors in log files.

**To Reproduce**
Use userloc module with PostgreSQL and latter registrar messages will cause insert and logs will be in postgresql logfile.

**Expected behavior**
I've checked code and found this:
UPSERT should be used instead of INSERT

**Additional context**
At `https://github.com/OpenSIPS/opensips/blob/master/modules/usrloc/urecord.c#L371` 
```c
case 1: /* insert */
	if (db_insert_ucontact(ptr,ins_list,0) < 0) {
```
should be changed to:
```c
case 1: /* insert */
	if (db_insert_ucontact(ptr,ins_list,1) < 0) {
```
to run `UPSERT` instead of `INSERT` into location table.

If this change is OK, I can build a pull request for this.

Thanks.

**Comment by bogdan-iancu** [comment]
@derkan , by the way OpenSIPS works, it will know if INSERT or UPDATE has to be performed (as the primary storage of the registrations is in memory). So, there is no need of an UPSERT or REPLACE.
What DB mode do you use for the usrloc module ?

**Comment by derkan** [comment]
thanks for response @bogdan-iancu. I'm using PostgreSQL.

**Comment by bogdan-iancu** [comment]
I asked about the `db_mode` param in usrloc loc, not about the db backend :) -> https://opensips.org/html/docs/modules/2.2.x/usrloc.html#idp5669968

**Comment by derkan** [comment]
Oh!, my fault, here is `usrloc` configs:
 
```py
modparam("usrloc", "db_url", "postgres://....")
modparam("usrloc", "db_mode", 2)
modparam("usrloc", "timer_interval", 3)
modparam("usrloc", "contactid_column", "i_location")
```

**Comment by bogdan-iancu** [comment]
Is the database written by some other app rather than this particular OpenSIPS instance?

**Comment by dwilkie** [comment]
I'm receiving the same error, using postgres as well. I'm running OpenSIPS 3.3

Here's my usrloc configuration

```
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "working_mode_preset", "single-instance-sql-write-back")
modparam("usrloc", "db_url", DATABASE_URL)
```
