### ISSUE TITLE
[CRASH] Crash using rl_check

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1882]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 838349d58
main.c compiled on 22:07:52 Oct 31 2019 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/HFsHex04

**Describe the traffic that generated the bug**

Crash occurred on first message received while using the ratelimit module. I added the following ratelimit configuration to my script.

```
loadmodule "ratelimit.so"
modparam("ratelimit", "hash_size", 32)
modparam("ratelimit", "default_algorithm", "FEEDBACK")
modparam("ratelimit", "window_size", 2)
modparam("ratelimit", "slot_period", 1000)
```

and then called rl_check as below

```
rl_check("RL_PIPE_FEEDBACK", "1", "FEEDBACK");
rl_check("RL_PIPE_CPS", "1", "SBT");
rl_check("RL_PIPE_NETWORK", "1", "NETWORK");
```

**To Reproduce**

1. Start OpenSIPS with the above configuration.
2. Send a SIP message
3. Crash

**Relevant System Logs**

```
Oct 31 22:13:05 [361] CRITICAL:core:sig_usr: segfault in process pid: 361, id: 24
Oct 31 22:13:06 [370] CRITICAL:core:handle_tcp_worker: dead tcp worker 0 (EOF received), pid 361
Oct 31 22:13:06 [370] CRITICAL:core:handle_worker: dead child 24 (EOF received), pid 361
Oct 31 22:13:06 [336] INFO:core:handle_sigs: child process 361 exited by a signal 11
Oct 31 22:13:06 [336] INFO:core:handle_sigs: core was generated
Oct 31 22:13:06 [336] INFO:core:handle_sigs: terminating due to SIGCHLD
```

**OS/environment information**
 - Operating System:  Amazon Linux 2 in Docker
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
@razvancrainea Thanks for the quick fix! I've tested with your commit and it does stop the crash, however now OpenSIPS simply stops processing at the rl_check call. There are no logs or any other error indication, the process simply stops and the message seems to be dropped.

**Comment by bcnewlin** [comment]
Here are the logs when I send 2 INVITEs to the server that is calling rl_check as shown above: https://pastebin.com/72sMPu9R

**Comment by bcnewlin** [comment]
@razvancrainea I can also open a separate ticket for the issue with OpenSIPS hanging if you prefer.

**Comment by razvancrainea** [comment]
No need of a new ticket for now, let me investigate this and will get back to you with further instructions.

**Comment by razvancrainea** [comment]
Most likely one of the three `rl_check()` calls returns a value of `0`, which indicates that the script should halt. Can you comment all the calls, and uncomment them one by one, to  determine which algorithm determines the `0` value?

If none of these works, one of the algorithm makes OpenSIPS gets stuck in a loop - in that case, the output of `opensipsctl trap` would be very useful.

**Comment by bcnewlin** [comment]
You are right, it is the `NETWORK` call that is hanging. Here is the output of the trap: https://pastebin.com/nsnEiuGF.

**Comment by bcnewlin** [comment]
Further testing shows that my previous update is not entirely correct. While the `NETWORK` rl_check call is consistently hanging, the other `rl_check` calls do also frequently hang. It is just not quite so often. I am investigating to see if I can determine any specific scenarios that cause these other checks to fail. Anecdotally, it seems like it may be related to how long OpenSIPS has been running before `rl_check` is called, e.g. if a time_interval has elapsed yet.

**Comment by razvancrainea** [comment]
I've just pushed a commit to address this issue. Can you run your tests again and let me know if you still experience this issue?

**Comment by bcnewlin** [comment]
The issue appears to be resolved with this fix. Thanks!
