### ISSUE TITLE
[BUG]3.0: using pua_usrloc with mid_registrar crashes

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#1883]
**OpenSIPS version you are running**

```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: bc3a861b0
main.c compiled on  with gcc 6.3.0

```

**Describe the bug**

**To Reproduce**

Not always, but very often, crashes on register 
If not crashes, it sends NOTIFY

On unregister/expire, it does nothing: no crash no NOTIFY

`
/usr/sbin/opensips[32739]: CRITICAL:core:sig_usr: segfault in process pid: 32739, id: 33

 kernel: [912375.293317] opensips[32739]: segfault at c ip 00007f67501a05b5 sp 00007ffee4c82b10 error 4 in pua_usrloc.so[7f675019e000+5000]

usr/sbin/opensips[32706]: ERROR:pua_usrloc:ul_contact_publish: failed to send publish

/usr/sbin/opensips[32706]: CRITICAL:core:sig_usr: segfault in attendant (starter) process!

systemd[1]: opensips.service: Main process exited, code=killed, status=11/SEGV

kernel: [912375.304816] opensips[32706]: segfault at 2b ip 00007f674b5f2cda sp 00007ffee4c815d0 error 4 in tracer.so[7f674b5ed000+19000]

systemd[1]: opensips.service: Control process exited, code=exited status=1

systemd[1]: opensips.service: Unit entered failed state.
`
**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by gmaruzz** [comment]
I was fearing this question... :)
Must I install the *dbg* packages ?
Any script config line to indicate where to send the core, or link to how-to gdb bt?

**Comment by bogdan-iancu** [comment]
the `gdb` package :) . This might help with the process -> https://opensips.org/Documentation/TroubleShooting-Crash

**Comment by gmaruzz** [comment]
:D, thanks, I'll post here in a couple days
