### ISSUE TITLE
[CRASH] Segmentation Fault

### ISSUE THREAD

**Issue by homstr** [OpenSIPS/opensips#1885]
**OpenSIPS version you are running**

 opensips -V
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 15:13:10 Oct 29 2019 with gcc 6.3.0

```
```

**Crash Core Dump**
https://www.dropbox.com/s/of2y1b7g4cng0se/backtrace_of_core.txt?dl=0

**Describe the traffic that generated the bug**

**To Reproduce**

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 - OpenSIPS installation: from source
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Could you please re-compile OpenSIPS with memory debugging and generate a new core dump? You can follow these instructions:
https://www.opensips.org/Documentation/TroubleShooting-OutOfMem

**Comment by homstr** [comment]
Hi. Thank you for a such quick answer. 
Sure i will do this, and will be back, as soon as i will have the next crush 
:-)

**Comment by homstr** [comment]
iam back...
this is the messages cut of incedent 
https://www.dropbox.com/s/yz9bptn7dhi89ix/messages_opensips_memory_dump?dl=0
this is the backtrace of core dump file
https://www.dropbox.com/s/ndkjsw715s3pyhe/backtrace_of_core_2.txt?dl=0

**Comment by homstr** [comment]
part of opensips.log of that moment
https://www.dropbox.com/s/xlce1pr5nih2sqh/opensips.log_crash?dl=0

**Comment by razvancrainea** [comment]
Could you tell us exactly how you installed OpenSIPS so we can figure out what version you're using? Or preferably tell us the git revision you're running, if available.
