### ISSUE TITLE
Requesting back port of existing commit to version 2.4.x 

### ISSUE THREAD

**Issue by adamoverbeeke** [OpenSIPS/opensips#1886]
Please back port the following commit to **2.4.x**. We would like to use the **active_only** functionality of  **get_dlg_by_callid**. 

https://github.com/OpenSIPS/opensips/commit/76903e1d2fa966431cc45a521afcd183b33a60b4

**Comment by bogdan-iancu** [comment]
@adamoverbeeke , the project policy is to do backports (to stable versions) only for fixes, not for new features. Shortly, the commits adding new features (and not fixes) are not backported.
