### ISSUE TITLE
[CRASH] segfault when using async rest calls on BYE

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#1888]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 20:56:21 Nov  6 2019 with gcc 4.8.5

```

**Crash Core Dump**
https://pastebin.com/raw/j5mjTQsF

**Describe the traffic that generated the bug**
SIP calls that do a couple db queries and a rest call on INVITE and BYE.  When I use just rest_post rather than the async wrapper I have not seen a segfault to this point.  Using the async call results in a segfault on BYE message pretty quick.  However, I can use the async wrapper for the INVITE (including negative final responses) rest call seemingly without issue.

**To Reproduce**

1. Start OpenSIPS
2. Start SIP traffic with async rest calls on INVITE and BYE messages
3. Watch for re-transmissions as an indicator that opensips has crashed. 

**Relevant System Logs**
```CRITICAL:core:sig_usr: segfault in process pid: 30277, id: 7```
this is the only log message around the crash.

**OS/environment information**
 - Operating System: CENT OS 7
 - OpenSIPS installation: compiled from source from Nov 3
 - other relevant information:

**Additional context**
It is possible that a delayed response from the web server is also involved in this.  I will attempt to verify one way or the other and update this report.

**Comment by bogdan-iancu** [comment]
@rrevels-bw , we fixed some time ago (weeks) some similar issue, similar by scenario and also by the backtrace/crash.
Could you upgrade to the latest 2.4 code (git) and try again ?

**Comment by rrevels-bw** [comment]
I'm pretty sure that is the source I was using.  However, I have time today to verify that and run the test again so will go get started on that.

**Comment by bogdan-iancu** [comment]
When you do `opensips -V`, don't you get the git revision number ? this will pin point your exact version.

**Comment by rrevels-bw** [comment]
You are right of course.  Looks like I got into a fight with ansible about who was going to supply the build directory.  This time it came from git.

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4a639db
main.c compiled on 19:14:50 Nov 11 2019 with gcc 4.8.5


I am getting the same result with this build however.  I'll add another back trace from this run.

https://pastebin.com/raw/p2N4rfKm

**Comment by bogdan-iancu** [comment]
OK, so let's try to dig more - the crash seems to be triggered by some memory corruption, so please enabled the memory debugger, to get more info on this. How to compile-in the mem debugger, see https://opensips.org/Documentation/TroubleShooting-OutOfMem , the "How to handle it" chapter. 
No need for special cfg settings, just get it running again and wait to crash (again)

**Comment by rrevels-bw** [comment]
Sorry for delayed response.  I was out for a week.  I attached everything that happened during the crash rather than trying to filter only the memory logs.  The timer warning does precede a crash often but not always.

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c356966
main.c compiled on 14:40:15 Nov 19 2019 with gcc 4.8.5

Here is the log. 
https://pastebin.com/raw/R5A5Str3

I can provide the full backtrace as well if desired.  Here is the summary
https://pastebin.com/raw/UUQwQWhN

**Comment by rrevels-bw** [comment]
Oh, and I was running 100 cps and the crash happened while the INVITE counter was at 2468.  So, not right away (386 BYEs had been processed) but not too long into it either.

**Comment by rrevels-bw** [comment]
take it easy there stalebot.  this is still a work in progress.

**Comment by rrevels-bw** [comment]
When I turn on memory logging I get an assert rather than segfault.  End result is same.  Anyway, here are the last two lines for the thread that crashed.  I have a little bit of time to spend on this now so will let you know if I notice anything out of place in my core dump file.

2019-12-06T02:07:14.391877+00:00 proxy-01 /usr/local/opensips/sbin/opensips[8610]: shm_free(0x7f2721c9ca24), called from sip_msg.c: update_cloned_msg_from_msg(1169)

2019-12-06T02:07:14.392241+00:00 proxy-01 /usr/local/opensips/sbin/opensips[8610]: CRITICAL:core:qm_debug_frag: qm_*: fragm. 0x7f2721c9c9f4 (address 0x7f2721c9ca24) beginning overwritten(20455942f0f0f0f0)!

**Comment by rrevels-bw** [comment]
hmm, im fuzzy on how i got to _shm_free_unsafe from this block since both lengths are zero

(gdb) frame 5
#5  0x00007f271fcba98e in update_cloned_msg_from_msg (c_msg=0x7f2721c91938, msg=0x7f2760eca460)	at sip_msg.c:1169
(gdb) p	c_msg->new_uri
$21 = {s = 0x0,	len = 0}
(gdb) p	msg->new_uri
$22 = {s = 0x0,	len = 0}
(gdb) down
#4  0x00007f271fcb5150 in _shm_free_unsafe (ptr=0x7f2721c9ca24,	file=0x7f271fcd6090 "sip_msg.c", function=0x7f271fcd6b70 <__FUNCTION__.8355> "update_cloned_msg_from_msg", line=1169) at ../../mem/shm_mem.h:350

**Comment by rrevels-bw** [comment]
I wasn't able to determine what was modifying the shared memory in this call flow but I have found that I can avoid the segfault by not calling t_relay until the async call has ended.  I was already doing this on the INVITE as I needed the outcome of the rest call to determine how to continue call processing.  For BYE messages I just needed to do the rest call but wasn't particularly concerned with the outcome so was firing off the t_relay and then doing the async call when it returned.  

This doesn't fix the problem of course but it does bring me back to the question of if that call flow (doing the async rest call after t_relay on a message) is considered to be supported.

**Comment by bcnewlin** [comment]
Are you using `async` or `launch`? Async is intended to be used when you want to hold message processing to wait on the response (serial). If you want the rest call to be performed in parallel you should be using `launch`. https://www.opensips.org/Documentation/Script-Async-2-4#toc5

It sounds like you want to be using `async` on the INVITE, but should be using `launch` on the BYE.

That's not to say the crash shouldn't be fixed, but even if the crash is fixed you may see some undesired behavior using the functions the wrong way.

**Comment by rrevels-bw** [comment]
Somehow I totally overlooked the existence of launch.  I'm sure in a couple years I would have noticed it and wondered why I hadn't been using it all this time so thank you! for pointing it out to me.

**Comment by bogdan-iancu** [comment]
Hi @rrevels-bw , are you still able to reproduce the abort reported here https://github.com/OpenSIPS/opensips/issues/1888#issuecomment-562666466 ? If yes, could you get a full backtrace? it looks like there is a memory corruption that may be triggered by the usage the async call .

**Comment by rrevels-bw** [comment]
I will grab the latest code tomorrow and re-do the test(s) for this.  At the same time I will try using the launch function rather than async and see if I dont have better results with that.

**Comment by bogdan-iancu** [comment]
Thanks @rrevels-bw , waiting for your update

**Comment by rrevels-bw** [comment]
Using launch I was unable to cause a core dump went doing rest calls on BYE messages even with the revision I started testing with.  With code I downloaded and compiled this week I am also not able to produce a core dump using the async function with rest calls on BYE messages.  I am closing this bug report.
