### ISSUE TITLE
[BUG] Round-Robin does not appear to work properly with weights of 1 per server.

### ISSUE THREAD

**Issue by etmoonshade** [OpenSIPS/opensips#1889]
**OpenSIPS version you are running**
```
version: opensips 3.0.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 13:02:44 May 30 2019 with gcc 4.8.5
```

**Describe the bug**
Using round-robin (option "4" in select_domain) does not correctly round-robin between entries when using the dispatcher.

**To Reproduce**
Use the following dispatcher file, with the db_text DB driver:
```
id(int,auto) setid(int) destination(string) socket(string,null) state(int) weight(int) priority(int) attrs(string) description(string)
1:2:sip\:192.168.1.1\:5060::0:1:1:None:SERVER1
2:2:sip\:192.168.1.2\:5060::0:1:2:None:SERVER2
```
Use ```ds_select_domain(2,4,"f","default",2);``` or ```ds_select_domain(2,4,"f");``` in opensips.cfg for routing (both were tested, both fail with weights at 1 and succeed with weights at 2)

Send multiple calls to opensips server, and observe that they do not properly load balance.

**Expected behavior**
Incoming calls should hit both servers. Note that making the following modification (setting weights to 2) causes calls to go to both servers:

```
id(int,auto) setid(int) destination(string) socket(string,null) state(int) weight(int) priority(int) attrs(string) description(string)
1:2:sip\:192.168.1.1\:5060::0:2:1:None:SERVER1
2:2:sip\:192.168.1.2\:5060::0:2:2:None:SERVER2
```

**OS/environment information**
 - Operating System: CentOS 7 
 - OpenSIPS installation: Package from yum.opensips.org

**Additional context**
This doesn't appear to happen with larger dispatcher lists (currently we have a list of ~30 servers with multiple setids in production successfully load balancing,) but does happen with a 4-entry list:

```
id(int,auto) setid(int) destination(string) socket(string,null) state(int) weight(int) priority(int) attrs(string) description(string)
1:2:sip\:192.168.1.2\:5060::0:1:1:None:SERVER2
2:2:sip\:192.168.1.1\:5060::0:1:2:None:SERVER1
3:2:sip\:192.168.1.2\:5060::0:1:3:None:SERVER2
4:2:sip\:192.168.1.1\:5060::0:1:4:None:SERVER1
```
Modifying the order of this list doesn't appear to change the behavior - all calls just hit the first server in the list. Changing weights to 2 for all servers does, once again, cause it to round-robin correctly.

**Comment by bogdan-iancu** [comment]
@etmoonshade , I can confirm the bug (as per your description). The problem seems to have originated when migrating the module from 2.4 to 3.0 module interface. I will let @liviuchircu to sort this out.

**Comment by liviuchircu** [comment]
Thank you for the report, @etmoonshade.  The round robin logic is working fine once again, so please pull latest sources and enjoy!

**Comment by etmoonshade** [comment]
Pleased I could help @liviuchircu - I didn't build this config, so I'm glad I was able to provide the right information to get you where you needed to go. :+1:
