### ISSUE TITLE
[FEATURE] Allow python module to call core functions, not only modules functions

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1893]
I'm trying to set a variable from python module.
I tried to use pv_printf() core function for this.
However python module cannot run core functions, only modules functions.

It would be a good feature to allow python module to call core functions too.

**Comment by rvlad-patrascu** [comment]
Hi @nikbyte 
This is already possible on the master branch. Unfortunately, this could not be backported as a fix to 3.0 or below, as it involves a significant rework of the core functions interface.
