### ISSUE TITLE
[BUG] Inconsistent error responses for JSON-RPC

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#1894]
**OpenSIPS version you are running**
```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**
RPC commands give inconsistent responses that are difficult to parse consistently when writing interfaces for the management interface.

**To Reproduce**
Good behavior when sending a command that has a bad method returns an "error" object in the response json;
> note cache_load is a bad method  

Request:
```
{"jsonrpc":"2.0","method":"cache_load","id":0,"params":["local","testkey"]}
```
Response:
```
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}
```
Bad behavior when sending a good method, but error response is received due to a missing key;
```
{"jsonrpc":"2.0","method":"cache_fetch","id":0,"params":["local","testkedoesnotexist"]}
```
Response:
```
{"jsonrpc":"2.0","result":"Value not found","id":0}
```

**Expected behavior**
Errors should contain error objects so that they can be detected as errors
**Relevant System Logs**
N/A

**OS/environment information**
N/A

**Additional context**
I'm implementing a programming interface to the mi_fifo and inconsistent responses make it difficult to test consistently for error values.

**Comment by rvlad-patrascu** [comment]
Hi @hamid-elaosta 
Have you found other examples of such MI commands, besides `cache_fetch`, that do not properly include an "error" object in the response?

**Comment by hamid-elaosta** [comment]
@rvlad-patrascu I haven't found others yet but I'm still implementing my interface. I'll let you know when I find others.

**Comment by rvlad-patrascu** [comment]
If you find any other examples, please feel free to reopen this ticket or add a comment.
