### ISSUE TITLE
Memory leak on topology_hiding[BUG]

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#1898]
**OpenSIPS version you are running**

version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 00:00:54 Oct 20 2016 with gcc 4.8.5

```
```

**Describe the bug**

In production environment I'm using opensips that receives calls from a SIP Provider  and forwards them to an endpoint setting before forwarding the topology_hiding("U") directive.
If the endpoint rejects the INVITE, for example with a 503 Service Not Available, used memory by opensips is not freed generating a memory leak, and after some thousands of calls opensips exits running out of free shared memory.

**To Reproduce**

I ran a sipp script to emulate SIPProvider calls, and a sipp to always reject calls.

Before starting with the test opensips has the following status:
opensipsctl fifo get_statistics shmem:

shmem:total_size:: 33554432
shmem:used_size:: 3385864
shmem:real_used_size:: 3452264
shmem:max_used_size:: 3478176
shmem:free_size:: 30102168
shmem:fragments:: 1350

After 1000 calls is:
shmem:total_size:: 33554432
shmem:used_size:: 5081008
shmem:real_used_size:: 5223008
shmem:max_used_size:: 6231896
shmem:free_size:: 28331424
shmem:fragments:: 2660

I ran the same test commenting out the line with topology_hiding("U"); and after the 1000 calls test I got:
shmem:total_size:: 33554432
shmem:used_size:: 3385864
shmem:real_used_size:: 3496304
shmem:max_used_size:: 4738336
shmem:free_size:: 30058128
shmem:fragments:: 1350

Looking at used_size, 1000 calls carry out to a memory leak of 1.7MB
**Expected behavior**

To not have a constant increase of shared memory used.
**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
CentOS Linux release 7.5.1804 (Core)

**Additional context**

**Comment by razvancrainea** [comment]
@arovetto unfortunately OpenSIPS 2.2 is [no longer supported](https://www.opensips.org/About/AvailableVersions), so you're best chance to fix this is to update to the latest OpenSIPS 2.2 version, which is 2.2.8. If this is still not sorted out, try to update to 2.4 and check if this happens there too - if it does, reopen the ticket with updated information.
