### ISSUE TITLE
opensips 2.4.6 use mongodb(4.0 Version) segfault

### ISSUE THREAD

**Issue by ycxwoo** [OpenSIPS/opensips#1903]
mongo-cxx-driver.x86_64                 1.0.5-1.el7                    epel
mongo-cxx-driver-devel.x86_64           1.0.5-1.el7                    epel

opensips/modules/cachedb_mongodb/cachedb_mongodb_dbase.c  
function mongo_db_query_trans 1371 line 

VAL_STRING(cur_val) = bson_iter_utf8(&iter, NULL);
when string,  you use a lot of results later, segfault,The result here is unallocated memory

It is also recommended to use the returned length
uint32_t length;
const char *tmp_s = bson_iter_utf8(&iter, &length);

**Comment by liviuchircu** [comment]
Thank you for the report, @ycxwoo !  So I understand you are using the `db_cachedb.so` module?  Could you provide a bit more info on how to reproduce?  For example:

* what module you are using to talk to the `db_cachedb` abstraction layer
* how big is the dataset held in this module's table?
* Is the crash a 100% reproduce?  If yes, can you provide some SQL queries or a file to pre-populate the table and get it to crash on 1st try?

**Comment by Ozzyboshi** [comment]
i have a similar setup, i also run opensips 2.4.6 + mongodb and sometimes Opensips crashes , see #1895 .
At the moment I am not able to reproduce the crash but I thinks there is something wrong in 2.4 series.
