### ISSUE TITLE
[BUG] Undocumented dependency for db_postgres in 3.0

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1906]
Hi guys,

I've spent an hour trying to understand why my 2.4 script cannot work on 3.0.

Issue is:
> Nov 25 22:29:47 [28279] DBG:core:solve_module_dependencies: module db_postgres depends on module tls_mgm, but it was not loaded!

however this dependency is undocumented and packaging has no this dependency too.

is this dependency correct? if yes, please, fix doc and I'll patch packaging for this.
if no – please, fix db_postgres module to work without tls_mgm.

Thank you.

**Comment by liviuchircu** [comment]
Hi Nick,

If you look closer, that's just a debug message, which shouldn't affect the startup at all.  Why do you say "cannot work on 3.0"?  What is the exact stopper?

**Comment by nikbyte** [comment]
Thank you!
