### ISSUE TITLE
[BUG] mid_registrar_save() leaks SHM on REGISTER retransmission

### ISSUE THREAD

**Issue by viperlong** [OpenSIPS/opensips#1907]
**OpenSIPS version you are running**

opensips-2.4-release

**Describe the bug**

In mid_registar module ,in MID_REG_THROTTLE_CT mode when register  method has retransmissions, shm memory leak found.. I open the memory DBG,found mri_alloc alloc  times is equal to retransmissions times. this is  the shm memory dump show ：
  
2315096 : 9417 x [mid_registrar.c: mri_alloc, line 395]

**To Reproduce**

compile and start opensips 2.4 with memdump  , load mid_reigitar  use MID_REG_THROTTLE_CT mode . let opensips be a mid-registar. 
use sipp uac register to opensips(make a big traffic ) when sipp has a retransmission ,dump 
the opensips memory.
**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

this is my opensips.cfg route to register :

           if (is_method("REGISTER")) {
		mid_registrar_save("location");
		switch ($retcode) {
		case 1:
			if (!rl_check("pipe_REGISTER", "200")) {
				sl_send_reply("503", "Service Unavailable,Reach the limit");
				xlog("REGISTER  $hdr(Contact) (user=$rU,ip=$si,callid=$ci) is rejected\n");
			        exit;
			}
			$ru = "sip:"+$tU+"@"+$dd+":"+$dp;
			xlog("forwarding REGISTER to main registrar $ru (user=$rU,ip=$si,callid=$ci)\n");
			t_relay();
			break;
		case 2:
			xlog("absorbing REGISTER! $ru (user=$rU,ip=$si,callid=$ci)\n");
			break;
		default:
			xlog("failed to save registration! $ru (user=$rU,ip=$si,callid=$ci)\n");
		}
		exit;   
	}

**Comment by viperlong** [comment]
should I add a t_check_trans   function before mid_registrar_save("location") like this:
if ( t_check_trans() ) {
        exit;
}
it can check retransmissions and avoid the shm leak ,but I'm not sure this behavior is correct for opensips in MID_REG_THROTTLE_CT mode。

**Comment by liviuchircu** [comment]
Hey @viperlong!  For the moment, the `t_check_trans()` solution is 100% correct, since the mid-registrar currently expects you to call it, so I recommend you use it and forget about this leak.

However, since other users may run into the same problem since calling `t_check_trans()` may not obvious for everyone, I will work on adding some internal retransmission handling logic and only then close this ticket.

Cheers!
