### ISSUE TITLE
[FEATURE] Replicate some collections with clusterer

### ISSUE THREAD

**Issue by bshirazi** [OpenSIPS/opensips#1908]
Hi
Possibility to select some collections of cachedb_local  to be replicated with clusterer not all of them.

Regads
M.Shirazi

**Comment by bogdan-iancu** [comment]
1) the concept of `local` conflicts with the concept of `replication` :)

2) why don't you use any external noSQL engine as cache (mongo, redis, cassandra, memcached) ?

**Comment by bogdan-iancu** [comment]
Thanks to @rvlad-patrascu for pointing that the module already has clustering support, even if it makes no much sense for me (again, `cachedb_local` is intended to provide a simple and local caching).
So, to a certain point, the request may be considered valid.

**Comment by bshirazi** [comment]
Hi
Thank you @bogdan-iancu
Exact for same reason you told I prefer to replicate just one of my local cache db with clusterer.
