### ISSUE TITLE
[BUG] Can't get benchmark module data in 3.0

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1909]
> opensips-cli -x mi bm_poll_results
ERROR: command 'bm_poll_results' returned: -32000: Server error

what I'm doing wrong?

3.0 - latest git

**Comment by nikbyte** [comment]
loadmodule "benchmark.so"
modparam("benchmark", "enable", 1)
modparam("benchmark", "granularity", 0)

**Comment by nikbyte** [comment]
in logs:
ERROR:core:handle_mi_request: Command failed

**Comment by liviuchircu** [comment]
Fixed in 6bd19fcc96b9a0
