### ISSUE TITLE
[CRASH] Dispatcher Module with postgresql

### ISSUE THREAD

**Issue by fedorna** [OpenSIPS/opensips#1911]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 20:03:58 Nov 12 2019 with gcc 5.4.0
```

**Crash Core Dump**

https://pastebin.com/NbQgfLg9

**Describe the traffic that generated the bug**

Helped by the core file I checked postgresql logs and I saw that when the dispatcher function ds_flusher_routine was trying to update the database, another process we have was executing a ds_reload command via de UDP datagram MI. The dispatcher destination xxx.xx.xx.xxx:xxxxx that you see in the core file was indeed out of service because it was being upgraded, so openSIPS ds_flusher_routine tried to update the state for that destination, for six sets.

```
(gdb) frame 6
#6  0x00007fe3df236277 in ds_flusher_routine (ticks=<optimized out>, param=<optimized out>) at dispatch.c:797
797     dispatch.c: No such file or directory.
(gdb) p sql_buf
$1 = "update sbc_2_4.dispatcher set state=2 where setid=0 AND destination='sip:xxx.xx.xx.xxx:xxxxx'\000\062,q=-1.00     ,cseq=59,flags=0,cflags='6',user_agent='Z 3.9.32144 r32121',received=NULL,path=NULL,socket='"...
(gdb)
```
Just to mention, we are using sets 1 to 10 in dispatcher, but the update string had setid=0, there is something strange there.

**To Reproduce**

Not able to reproduce it...

**Relevant System Logs**

```
ERROR:db_postgres:db_postgres_val2str: destination STR buffer too short (have 65468, need 818878093)
ERROR:core:db_print_where: Error while converting value to string
ERROR:db_postgres:db_postgres_store_result: 0x7fe4064a0e30 - invalid query, execution aborted
ERROR:db_postgres:db_postgres_store_result: 0x7fe4064a0e30: PGRES_FATAL_ERROR
ERROR:db_postgres:db_postgres_store_result: 0x7fe4064a0e30:
WARNING:db_postgres:db_postgres_update: unexpected result returned
ERROR:dispatcher:ds_flusher_routine: DB update failed
```

**OS/environment information**
 - Operating System: 
Running in a docker container. Host: Ubuntu 14.04.3, Container: Ubuntu 16.04.6
 - OpenSIPS installation: 
git commit 25f9070ab7509a8ab186b69a1a7ee2d5aeb896bc
 - other relevant information:

**Additional context**

The syslog lines I've pasted appears 6 times (the dispatcher destination is in 6 different sets). We have ~ 7000 terminals registered in that openSIPS and we have two more openSIPS running like this one. Is the first time we have a crash regarding this issue, maybe it was a combination of ds_reload + destination state change that it won't happen again, but I wanted to report it just in case you figure out something.

I've pasted the memdump here: https://pastebin.com/0e9rDk1K

Thanks!!!

**Comment by bogdan-iancu** [comment]
Thanks @fedorna for the report, indeed there was a missing locking while flushing. This may have conflicted with an ongoing reload.
Let's keep an eye on this, please re-open if it happens again.

**Comment by fedorna** [comment]
thank you @bogdan-iancu !
