### ISSUE TITLE
[BUG] add_path_received(user) cannot pass a variable

### ISSUE THREAD

**Issue by YounianC** [OpenSIPS/opensips#1912]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
```

**Describe the bug**
add_path_received(user) cannot pass a variable，if i do add_path_received("$tU"), then i'll get this :
```
 <sip:1004@172.18.5.34:55661;transport=wss;fs_nat=yes;fs_path=sip%3A$tU%40172.18.5.32%3Br2%3Don%3Blr%2Csip%3A$tU%40172.18.5.32%3A8080%3Btransport%3Dws%3Br2%3Don%3Blr%3Breceived%3Dsip%3A172.18.5.34%3A55661>
```
_$tU@172.18.5.32_

and if i do `add_path_received($tU) ` i'll get ` bad arguments for command <add_path_received>`

**Expected behavior**
add_path_received($tU) and get `;fs_path=sip:1004@172.18.5.32`

**Relevant System Logs**
```
REGISTER sip:172.16.77.148:5060;transport=udp SIP/2.0
Via: SIP/2.0/UDP 172.18.5.32:5060;branch=z9hG4bK3953.e48dca53.0
Via: SIP/2.0/UDP 172.18.5.34:45060;received=172.18.5.34;branch=z9hG4bK-d8754z-6712116ece54dd6c-1---d8754z-;rport=45060
Max-Forwards: 69
Contact: <sip:1000@172.18.5.34:45060;rinstance=193c6a0d4af410ec;transport=udp>
To: <sip:1000@172.18.5.32:5060>
From: <sip:1000@172.18.5.32:5060>;tag=9238fd88
Call-ID: NzQxMDFhODRkZmJmYTVkZmFjMTllODgyOGZjNTM0MGM.
CSeq: 493 REGISTER
Expires: 3600
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO
User-Agent: Genesyslab.Sip.Endpoint 8.0.0.10 L-PSDK-Q-SIP-8-0.us.int.genesyslab.com-083010-021849   Genesyslab.Sip.Endpoint.Provider.CP 8.0.0.10 L-PSDK-Q-SIP-8-0.us.int.genesyslab.com-083010-021849
Content-Length: 0
Path: <sip:$tU@172.18.5.32;lr>
X-AUTH-IP: 172.18.5.34

```

**OS/environment information**
CentOS

**Comment by bogdan-iancu** [comment]
Hi @YounianC , this is a limitation of opensips pre 3.0 - not all functions take variables as parameters. It is not a bug, so there is nothing to be done for 2.4.
Just start using 3.0 version.

**Comment by YounianC** [comment]
Alright, i tried it on 3.0 and works fine. And if anyone need this on 2.4, try "append_hf" and add Path header by yourself `Path: <sip:1001@10.0.xxx.xxx;r2=on;lr>` 
 : )
