### ISSUE TITLE
[BUG] rl_check call does not update limit for FEEDBACK algorithm

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1915]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: aa89b8764
main.c compiled on 16:20:57 Dec 10 2019 with gcc 7
```

**Describe the bug**

According to [ratelimit module documentation](https://opensips.org/html/docs/modules/2.4.x/ratelimit.html#func_rl_check) calling the `rl_check` function with a limit value "changes/updates the limit". However, my testing has shown that for the FEEDBACK algorithm the limit is only set on the first call to `rl_check` and cannot be changed after.

**To Reproduce**

1. Start OpenSIPS with a config script using a rate limit pipe with the FEEDBACK algorithm. In order to change the limit value during running, I used a [shared variable](https://opensips.org/html/docs/modules/2.4.x/cfgutils.html#pv_shv) for the limit value.
2. Start traffic
3. Use the [MI command](https://opensips.org/html/docs/modules/2.4.x/cfgutils.html#mi_shv_set) to change the limit value.
4. Verify using `rl_list` that the limit value has not changed

**Expected behavior**

Either the FEEDBACK module should allow changing of the limit or the documentation should be updated to be explicit that it is not allowed for this algorithm.

Full Disclosure: I did not test whether any of the other algorithms have similar issues with changing the limit value.

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
Hi @bcnewlin, don't you get a warning into the log when changing the limit? 
`FEEDBACK limit should be the same for all pipes, but new limit XX differs - setting to XX`

I'm not an expert in the FEEDBACK alg, but according to the code, there is a special handling when comes to the limits for this alg, like it must be between 0 and 100, and it can be only one limit for all checks & pipes (using this alg).

But, I agree, this is not well documented.

So, I see it more like a missing documentation on the particularities of the FEEDBACK alg, rather than a bug.

**Comment by bcnewlin** [comment]
@bogdan-iancu Yes, I do see the error now. So it does seem this is intentional behavior and this is only a documentation issue. Thanks for investigating that.

**Comment by bcnewlin** [comment]
Thanks! Unfortunately when trying to pick up that backport I've run into an issue with the fix from 59400f778b633d43d6d9e7d33fba4658c9c7f4fd. :(

I'll open a separate ticket for that.

**Comment by bogdan-iancu** [comment]
@bcnewlin , the commit related to this ticket (  5fb5716 ) is just about docs being update, no code change. So, nothing critical with this one :)

**Comment by bcnewlin** [comment]
@bogdan-iancu Apologies, I left that comment on the wrong ticket.
