### ISSUE TITLE
STIR/SHAKEN implementation

### ISSUE THREAD

**Issue by imdrpn** [OpenSIPS/opensips#1916]
Hello ,can anyone guide me to how can i go further to develop demo for stir/shaken . i have gone through https://www.slideshare.net/slideshow/embed_code/key/Ly9vOqcKuML5Nq this document as well as module in opensips 3.1 documentation .but still i did not get how to fetch certificate(.pem) by using rest_client and doing authentication as well as verification using self managing model of stir shaken . ?

**Comment by bogdan-iancu** [comment]
@imdrpn , as this is a 100% usage question, not a bug, so please use the user's mailing list - http://lists.opensips.org/cgi-bin/mailman/listinfo/users.
Anyhow, a fast hint - use the `$identity(x5u)` to get the location of the certificate and simply use `rest_client()` on that.

**Comment by imdrpn** [comment]
sure ,thank you @bogdan-iancu
