### ISSUE TITLE
[FEATURE] Add encoding method to rest_client

### ISSUE THREAD

**Issue by spacetourist** [OpenSIPS/opensips#1919]
When interacting with remote web services using HTTP GET we do not currently have an encoding option which performs standard URL encoding. The existing transformations encode/decode space char to + which makes it difficult to handle all scenarios. 

A good example is transmission of URI data which is E164 encoded with the + character - this is often lost and replaced with a space.

The obvious implementation would be to add a specific transformation function which escaped in accordance with URL encoding rules however an implementation within rest_client module would also be acceptable to me. The benefit of this option is that we can leverage libcurl functions which perform exactly this. The idea would be to have an encode and decode method exported to the script so that individual param data and URL's can be encoded at the users discretion.

I wanted to have a go at OpenSIPs development and have created a basic implementation to illustrate the concept: https://github.com/spacetourist/opensips/commit/5ccf6cd02c323faac821b6cda867447e3e6b3347

Please note that this is my first attempt to implement anything in OpenSIPs and I am not a native C developer so I am very open to feedback/direction - in fact even if this is not a helpful contribution to this module any pointers would be a useful learning exercise. My attempt to use the curl_easy_escape() method required me to provide a curl handle, I wasn't sure if this was available globally in the module for this example re-initialises one just for the execution which seems very inefficient..

I understand that a similar unescape method and documentation would need to be added however I would appreciate a little feedback regarding suitability before proceeding to implement any further. 

Thanks!

**Comment by spacetourist** [comment]
Hello, I've been away so just wanted to catch up on this. Should I continue this patch and contribute a more complete implementation or should I wait for advise on the approach before proceeding? Cheers

**Comment by liviuchircu** [comment]
Hey, @spacetourist !  I took a look at your patch, and it looks really clean.  But to make things even more accessible at script level, how about if we make `rest_client` export an escaping transformation of its own, via the module transformation interface?  The [`sip_i`](https://opensips.org/html/docs/modules/3.1.x/sip_i.html#tran_isup.param) module exports such transformations -- you can grab some inspiration from there.

This would allow code such as:

```
rest_get("test.com?content=$(var(data){rest.escape})", ...)
```

... instead of the longer:

```
rest_escape_string($var(data), $var(escaped));
rest_get("test.com?content=$var(escaped)", ...)
```

What do you think?  My vote goes to option 1.

**Comment by spacetourist** [comment]
Yeah that looks good to me, my first attempt was to look into the core transformations and see if I could work out how to add a new one however I was scared off by the absence of the curl library. I had no idea that module level transformations were a thing so this sounds ideal!

I'll have a go at implementing it based on what I can find in the `sip_i` module and post a revised patch as soon as possible.

**Comment by spacetourist** [comment]
I have had a go at converting the encoding method to an exported transformation, please see https://github.com/spacetourist/opensips/commit/4d1d48d40f7f0f2e90849274a6d459bd31450a5a and let me know if this looks correct. I wasn't clear on exactly what the method input/output parameters were but I've had a good guess!

In particular I wasn't clear what tr_rest_parse.in was exactly - I've presumed it was the string contents of the transformation call but it looks like sip_i has code to parse/detect closing braces but nothing to detect opening braces? Any idea what trimming etc would be required to correctly parse the input?

Also I was unclear about the i/o for tr_rest_eval - I've left he subtype system in place from sip_i and have treated val->rs as my input_str from the previous implementation, overwriting val as an output. 

I'm sure some of this is wrong so looking for some pointers before I proceed. Once I've got the basics in place I'll go ahead and implement the decoder etc.

Cheers!

**Comment by liviuchircu** [comment]
This is awesome!  To answer your questions:

1. Regarding `tr_rest_parse.in`: as you well spotted, `in` holds the content within brackets.  The `sip_i` parser simply treats `TR_RBRACKET` as a last-resort max limit, in case it cannot find the number of transformation parameters it needs.  Just to be on the safe side and not encourage funky syntax, I would just return an error if we receive anything other than exactly 1 parameter.

2. Regarding `tr_rest_eval`: `val` is, indeed, an input/output parameter.

Did you get a chance to test it?  I would recommend using the [assert()](https://www.opensips.org/Documentation/Script-CoreFunctions-3-1#toc2) statement of `opensips.cfg` and write some tests, so you catch all corner-cases!  Also, you don't need any signaling to do them either -- you can write them in `startup_route` directly.

**Comment by spacetourist** [comment]
OK, I've made some progress here and have tested it successfully. Currently stuck getting to grips with C itself and could do with a couple of pointers. 

Here is the tested version: https://github.com/spacetourist/opensips/commit/81b19c094919c0c09242dc54b2f57b9889e49d99

Here is my startup route and output: https://gist.github.com/spacetourist/3e6782c77e451b66827e34ccd8b713b2

Looking good so far. Here are my questions:

- I need to free curl handle and/or the encoded variable. I want to be sure to do this correctly to prevent any memory leaking however I am not clear on how to do it. Issuing ```curl_free(encoded);``` at any point will unset the data causing the function to return an empty string. I know I need to copy it somehow but after trying a number of things and failing I'm reaching out for help!
- Curl init: should I be using a global handle rather than initialising one with each transformation? I see references to a handle in rest_client.c but I'm not clear on usage expectations.

Thanks for taking a look, feels like I'm getting there!

**Comment by spacetourist** [comment]
Found a moment to add unescape transformation and some documentation: https://github.com/spacetourist/opensips/compare/4c6c00e...d6e0e6c

Still not freeing memory as per above, cheers

**Comment by liviuchircu** [comment]
Hey, @spacetourist !  I understand your memory leak problem.  To address it, since the transformations interface currently does not free our returned buffer, it follows that we must give it a buffer that _should not_ be freed.  If you take a look at sip_i, [this is exactly how it does it](https://github.com/OpenSIPS/opensips/blob/master/modules/sip_i/sip_i.c#L712).

To avoid static strings and buffer sizes, I suggest you define a `static str out_buf;` in `tr_rest_eval()`, which start at `{NULL, 0}`.  During runtime, this buffer may be expanded as many times as needed, using `pkg_str_extend()`, and will be used to return the results without the need to be ever freed.  An example of this technique can be found [here](https://github.com/OpenSIPS/opensips/blob/master/lib/reg/path.c#L113).

Hope this helps.  Have a nice weekend!

**Comment by spacetourist** [comment]
Great @liviuchircu - I'll take some time to digest that and see if I can make it work. 

Regarding libcurl usage should I continue to instantiate on every method call and aim to free at the relevant exit points? 

Have a nice weekend too!

**Comment by liviuchircu** [comment]
If you want to optimize that, you do have the global CURL handle for sync requests, [here](https://github.com/OpenSIPS/opensips/blob/master/modules/rest_client/rest_methods.c#L57).  This handle is always initialized by the time any transformation is run.  So you could remove the `static` and use an `extern` declaration to make it visible in the `rest_client.c` file as well.

I peeked through the curl library and there is no need to call `curl_easy_reset()` before each call.  Once `curl_easy_init()` is done, we can reuse `sync_handle` indefinitely within `tr_rest_eval()`.

**Comment by spacetourist** [comment]
Quick update, I have patched it to use the global/extern sync_handle which appears to be working however my attempts to implement the static response string have all failed so far. 

I'm sure its something relatively trivial however the current code will crash reporting bad pointer address. Also when I'm attempting to run curl_free I'm still seeing it invalidate my response data. The joy of C for a newbie! I'll revisit when I find a moment :)
 https://github.com/spacetourist/opensips/blob/f1b34c5c65ebcedd84183e6a99cc514985f5fe4c/modules/rest_client/rest_client.c

**Comment by liviuchircu** [comment]
Almost there, @spacetourist!  Some feedback:

* [Here](https://github.com/spacetourist/opensips/blob/f1b34c5c65ebcedd84183e6a99cc514985f5fe4c/modules/rest_client/rest_client.c#L447), the `if` is redundant, so you can simplify the code.  If you look at `pkg_str_extend()`, [it does the check anyway](https://github.com/OpenSIPS/opensips/blob/master/ut.h#L902).  Moreover, since it's `static inline`, that thing will be blazing fast anyway, as there will be no actual function call!

* [And here](https://github.com/spacetourist/opensips/blob/f1b34c5c65ebcedd84183e6a99cc514985f5fe4c/modules/rest_client/rest_client.c#L456) is your bug.  `init_str()` will actually replace the `.s` member, which is NOT what you want.  You want to copy the entire cURL memory into our buffer, which you can achieve with `str_cpy()` instead, for example.

I haven't spotted anything else, nice work!

**Comment by spacetourist** [comment]
Amazing, thanks Liviu. Your advice has enabled me to make some progress, the `curl_free()` operation now completes without loss of the data however I needed to do this using `memcpy` to prevent additional type conversion - perhaps there was another option however this seemed to work!

I am left with one final complication - the returned strings have some sort of termination issue which causes the following behaviour:
 
```
$var(data) = "!";
xlog("ENCODED: \"$var(data)\" -> \"$(var(data){rest.escape})\" \n");
```

Prints:

```
Jan 31 10:16:46 [5450] ENCODED: "!" -> "%21Jan 31 10:16:46 [5450] DBG:rest_client:tr_rest_eval: curl_easy_escape '*' returns '%2A'
```

Is this a missing or unwanted null terminator? I am sure this is again a basic C issue however its very confusing for a non-C developer!!

https://github.com/spacetourist/opensips/blob/feature-libcurl-encode/modules/rest_client/rest_client.c

**Comment by liviuchircu** [comment]
Right, you forgot to update `output_buf.len` as well, so it's reusing some random `.len` from a previous call.  Here are two ways of fixing this:

```
str_cpy(&output_buf, _str(curl_out));
```

... or, you could also:

```
memcpy(output_buf.s, curl_out, strlen(curl_out)+1);
output_buf.len = strlen(curl_out);
```

**Comment by spacetourist** [comment]
OK, all looking good my side. I've gone ahead and raised a PR https://github.com/OpenSIPS/opensips/pull/1960

Let me know if there is anything I've overlooked etc.

Thanks again Liviu, couldn't have done it without you - I learnt a bunch!
