### ISSUE TITLE
ISUP malformed packet

### ISSUE THREAD

**Issue by korithi** [OpenSIPS/opensips#1921]
Hello,
I am facing a malformed isup packet on the invite message.

version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 4.9.2

if (is_method("INVITE")) {
        # to check if IP is permission table
		if (check_address("1","$si","$sp","$proto" )) {
			xlog("rafa: address allowed: $si - $sp - $proto - $rm  $rU\n");
			# route to specific dispatcher ID
			ds_select_dst("3", "0");
			ds_select_domain("3", "0");
			remove_hf("Content-Disposition");
			remove_hf("Allow-Events");
			#append_hf("P-Asserted-Identity: <sip:12345@10.84.35.249>\r\n");
					
			record_route();
			add_isup_part("IAM");

**Comment by bogdan-iancu** [comment]
Please share the a pcap showing the malformed outbound message.

**Comment by korithi** [comment]
Hi Bogdan,

Thank your for your feedback. I found out it was caused by missing parameters in RURI.
Already fixed it and it is working fine now.

Thanks
