### ISSUE TITLE
[FEATURE] Advertised_address as initialization parameter

### ISSUE THREAD

**Issue by Otoru** [OpenSIPS/opensips#1923]
To use opensips within docker, advertised_address is required to traverse NAT. Although we can use preprocessing to apply a sed or something similar to the script, I think it would be more elegant to be able to use advertised_address as an opensips boot parameter.

Ex:
`/sbin/opensips -F -E --advertised-address=192.168.1.1`

**Comment by Otoru** [comment]
Hi @stale,

I would also like a return rsrs

**Comment by razvancrainea** [comment]
Marking this as feature request.

Indeed, you can use sed as a pre-processing parameter to the script, and you will get the same behavior:
```
opensips -F -E -p 'sed s#ADVERTISED_IP#1.1.1.1#g' -f
```
where `ADVERTISED_IP` is a token in your config file.

**Comment by Otoru** [comment]
Yes, as I said in the opening message, I am using this parameter as a contour, the suggestion of leaving this setting as a parameter is to make it more elegant.
