### ISSUE TITLE
[BUG] Websocket key compute unsafe

### ISSUE THREAD

**Issue by hafkensite** [OpenSIPS/opensips#1928]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**

When a websocket request is received with a `Sec-WebSocket-Key` of more than 24 bytes, then the 'constant' `WS_GUID_KEY` is overwritten. This results in failed websocket handshakes, if even more even bytes are sent, the process crashes.

**To Reproduce**

1. Run an OpenSIPS instance with a listening ws socket.
2. Verify that the WS handshake is correct:

   ```bash
   curl -Ss -D - 'http://127.0.0.1/' -H 'Sec-WebSocket-Version: 13' -H 'Origin: null' -H 'Sec-WebSocket-Protocol: sip' -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" -H 'Connection: Upgrade' -H 'Upgrade: websocket' | grep Accept
   ```

   ```text
   Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
   ```

   This is the right response, the values match the [RFC](https://tools.ietf.org/html/rfc6455#section-1.3)

3. Send a long request:

   ```bash
   curl -Ss -D - 'http://127.0.0.1/' -H 'Sec-WebSocket-Version: 13' -H 'Origin: null' -H 'Sec-WebSocket-Protocol: sip' -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==A" -H 'Connection: Upgrade' -H 'Upgrade: websocket'  | grep Accept
   ```

   ```text
   Sec-WebSocket-Accept: ZTBAswqjc1aE487jOjKIwzwXV28=
   ```

4. Observe the response to short requests is wrong:

   ```bash
   curl -Ss -D - 'http://127.0.0.1/' -H 'Sec-WebSocket-Version: 13' -H 'Origin: null' -H 'Sec-WebSocket-Protocol: sip' -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" -H 'Connection: Upgrade' -H 'Upgrade: websocket'  | grep Accept
   ```

   ```
   Sec-WebSocket-Accept: YfoOE2W8tclsfOA3B+O13n49OM0=
   ```

   The first character of the `WS_GUID_KEY` value is now an `A'.

**Expected behavior**
I expect the [`memcpy`](https://github.com/OpenSIPS/opensips/blob/7d53b51763d706362d187caf662c0febf6721cba/modules/proto_ws/ws_handshake_common.h#L1000) to be safe against strings that are too large, and reject the bad request.

**Relevant System Logs**
None

**OS/environment information**

- Operating System: Debian 9
- OpenSIPS installation: Debian package
- other relevant information: none

**Additional context**
While trying to trigger the issue, I send a very long value. It caused OpenSIPS to crash and restart.

**Comment by hafkensite** [comment]
While reading the code, I'm wondering if this is guaranteed to be thread-safe. Couldn't it be that two handshakes overlap in the `ws_compute_key` function? Overwriting the `unsigned char ws_key_buf[64]`?

**Comment by wdoekes** [comment]
Yeap. Looks like the correct assessment to me.

If we look at the RFC 6455 (The WebSocket protocol), we see:
https://tools.ietf.org/html/rfc6455#section-4.1
```
The requirements for this handshake are as follows.
[...]
7.   The request MUST include a header field with the name
        |Sec-WebSocket-Key|.  The value of this header field MUST be a
        nonce consisting of a randomly selected 16-byte value that has
        been base64-encoded [...]
```
I.e. a `ceil(16 * / 6) * 8 == 24` bytes base64 encoded key.

For reference, Kamailio doesn't suffer from this, but accepts arbitrary sized keys instead:
https://github.com/kamailio/kamailio/blob/91e4e1772289f0a6a6f19ff88f5861072611b25f/src/modules/websocket/ws_handshake.c#L296..L297

The easiest fix for now, would be to reject keys that are not 24 bytes in length. Adding a comment about the 24-byte limit.

```patch
diff --git a/modules/proto_ws/ws_handshake_common.h b/modules/proto_ws/ws_handshake_common.h
index 47f59c1dd..032d3c180 100644
--- a/modules/proto_ws/ws_handshake_common.h
+++ b/modules/proto_ws/ws_handshake_common.h
@@ -912,10 +912,18 @@ static int ws_parse_req_handshake(struct tcp_connection *c, char *msg, int len)
 
 				str_trim_spaces_lr(hf->body);
 
-				/* the key is already in the buffer, so we can just copy it */
-				WS_KEY(c) = hf->body;
-
-				flags |= WS_KEY_F;
+				/* RFC-6455 4.1: Opening Handshake: Client Requirements
+				 * 7.  The request MUST include a header field with the name
+				 *     |Sec-WebSocket-Key|.  The value of this header field MUST be a
+				 *     nonce consisting of a randomly selected 16-byte value that has
+				 *     been base64-encoded (see Section 4 of [RFC4648]).  The nonce
+				 *     MUST be selected randomly for each connection. */
+				if (hf->body.len == 24) {
+					/* the key is already in the buffer, so we can just copy it */
+					WS_KEY(c) = hf->body;
+
+					flags |= WS_KEY_F;
+				}
 			} else if (hf->name.len == HDR_LEN("Sec-WebSocket-Version") &&
 					GET_LOWER(hf->name.s + 14) == 'v' &&
 					GET_LOWER(hf->name.s + 15) == 'e' &&
@@ -967,7 +975,7 @@ static int ws_parse_req_handshake(struct tcp_connection *c, char *msg, int len)
 		if (flags & WS_ORIGIN_F)
 			LM_ERR("Origin header not present!\n");
 		if (flags & WS_KEY_F)
-			LM_ERR("Sec-WebSocket-Key header not present!\n");
+			LM_ERR("Sec-WebSocket-Key header not present (or not 24 bytes)!\n");
 		if (flags & WS_VER_F)
 			LM_ERR("Sec-WebSocket-Version header not present!\n");
 		if (flags & WS_PROTO_F)
```
As for the impact:
> While trying to trigger the issue, I [sent] a very long value. It caused OpenSIPS to crash and restart.
- So, any size  in [0..23] would cause the setup to fail, as the wrong value would be hashed (including garbage from a previous call): not nice.
- Any size in [25..64] would overwrite the WS_GUID_KEY, breaking WS setup _on this particular worker_ for all the next connections: rather bad.
- Any size >64 would start overwriting other memory: really bad.

> Couldn't it be that two handshakes overlap in the ws_compute_key function?

No, as the memory is not shared among workers, and the instance is always used by a single handshake at a single time.

**Comment by wdoekes** [comment]
(And we can probably replace that `24` with `WS_KEY_LEN`.)
(And `ws_key_buf[64]` with `ws_key_buf[WS_KEY_LEN + WS_GUID_KEY + 1]`.)

**Comment by razvancrainea** [comment]
Indeed, the fact that there is no check regarding the length of the key is a bit troublesome. However, as the RFC states that the key *MUST* consist of 16-random bytes, thus the base64 representation is 24 bytes, I'm not sure it's worth handling other scenarios (for now). Thus the fix @wdoekes proposes seems OK.

Not sure, but have you ever seen a real-life implementation where the `Sec-WebSocket-Key` that does not consist of 24 bytes? If so, perhaps it's worth implementing a more complete solution, to make sure we handle those implementations too. I am not saying we shouldn't, just trying to figure out if it's worth the effort.

**Comment by wdoekes** [comment]
> Not sure, but have you ever seen a real-life implementation where the Sec-WebSocket-Key that does not consist of 24 bytes?

No, I have not. So I would indeed suggest using my fix and calling it a day.

Then again, I haven't seen that much websocket traffic, so you may want to consult someone else.

(I _have_ seen an implementation where the 24 bytes sent by the client is not 16-bytes-base64-encoded though (in opensips :stuck_out_tongue: where it is 18 bytes-base64-encoded).)

**Comment by razvancrainea** [comment]
Is it 18 bytes? I have to check that!

**Comment by razvancrainea** [comment]
@wdoekes  wow, you're absolutely right, I haven't thought about this when generating the key :)
I guess I need to fix that as well, thanks for pointing it out!
