### ISSUE TITLE
[REQUEST INFO + HELP] Dialog module + clusterer

### ISSUE THREAD

**Issue by Ozzyboshi** [OpenSIPS/opensips#1930]
Hello,

I am in trouble sharing dialogs across 4 different Opensips nodes deployed in different vms.
Issuing "opensipsctl fifo dlg_list" on each node I get very different results and I often find some dialog deleted on some machines but still opened/active in others.
I am using the clusterer module that should provide an interface to keep de dialogs aligned across multiple nodes, I have probably misconfigured something.
First of all it's not clear to me the role of the 'seed' in the cluster, i set all the cluster as  seeds using the flags column of the clusterer mysql table, is it correct or is only one seed expected to exist in a cluster?
Second, I set set_dlg_sharing_tag after create_dialog() in my opensips.cfg, I expected some sort of effect in the dialog data displayed by "opensipsctl fifo dlg_list" but this is not the case.
I read the docs but I at this point there is a strong possibility I didnt get the correct understanding of this 2 features and above all I need a consistent way to share dialogs.
Third : where can I find documentation about dialog state ids?
Thanks in advance for your help.

**Comment by rvlad-patrascu** [comment]
Hi @Ozzyboshi 

I will asume that you use OpenSIPS version 2.4.x.
If you have doubts about you configuration, you could share here the script snippets regarding the clusterer and dialog modules config. But to briefly answer your questions:
1. Basically, a "seed" node is a trusted source of data synchronization (at startup) in the cluster, even if it starts with an empty data set. Its' purpose is to help "bootstrap" the data sync process in the cluster. As such there are 2 approaches that make most sense:
    a. only 1 seed node in the cluster, for which you will have to trigger the sync manually via MI;
    b. every node is a seed, but you have to configure the `seed_fallback_interval` modparam of the clusterer module to some value different than 0. By doing this, every node will first try to sync, then will fall back to "synced" state after some time if no source is found.
2. `set_dlg_sharing_tag()` sets the "dlgX_shtag" dialog value, which should be displayed by the `dlg_list_ctx` MI command
3. check this variable's [doc](https://opensips.org/html/docs/modules/3.1.x/dialog.html#pv_DLG_status)

**Comment by Ozzyboshi** [comment]
thx for the clarification closing for now
