### ISSUE TITLE
[QUESTION] AUTH_AAA with custom RADIUS request attributes

### ISSUE THREAD

**Issue by alexonmd** [OpenSIPS/opensips#1938]
Hello, OpenSIPs team.

Used OpenSIPs version is 2.4

How I can send custom attributes in RADIUS requests using aaa_www_authorize() function?
Currently it sends hardcoded attributes, but it's not suitable in my case.
I tried to use AAA_RADIUS module function radius_send_auth(), but there is no any connection between functions of these modules (auth_aaa and aaa_radius).

Thanks.

**Comment by bogdan-iancu** [comment]
@alexonmd , if you use the `radius_send_auth()` function, you do not need anymore the auth_aaa module. Just be sure you send (in the input_set) all the RADIUS AVPS expected by the server during the auth process.

**Comment by bogdan-iancu** [comment]
For more question about how to use OpenSIPS, please better use the opensips user's mailing list [1], this tracker is more for development related issues.


[1] http://lists.opensips.org/cgi-bin/mailman/listinfo/users

**Comment by alexonmd** [comment]
Thank you, Bogdan.
