### ISSUE TITLE
[BUG] Config generator fails to save file on Debian 10

### ISSUE THREAD

**Issue by sdwru** [OpenSIPS/opensips#1942]
Fresh install using the same procedure I used to install on Debian 9 using the Debian 10 buster repository.  When I try generate a Residential script using `/usr/sbin/osipsconfig` it gives an error saying it failed to save the script.  Looks like the `/etc/opensips` folder permissions are ok.

**Comment by razvancrainea** [comment]
Do you have the `m4` tool installed? Also, are you using the latest version of OpenSIPS? If not, what version are you using?
PS: please adhere to the issue report template, this would spare us for these useless ping-pongs.

**Comment by powerpbx** [comment]
Thank you for the suggestion.  Turns out I was missing the `m4` package.  Perhaps that can be added as a dependency when installing from deb packages.

**Comment by sdwru** [comment]
Thank you for the suggestion. Turns out I was missing the m4 package. Perhaps that can be added as a dependency when installing from deb packages.

**Comment by mostafa0017** [comment]
2024, on Ubuntu 24.04 and this still got me running in circles, so yeah m4 should be an opensips deb dependency.
