### ISSUE TITLE
[BUG] lua libraries loading

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#1946]
Version: master 
Module:  lua 
Issue: Opensips loading lua libraries.
Description: 
Right now opensips preload lua libraries directly   luafoo_open funcs rather than using luaL_requiref.

Log:

```
Jan 24 17:24:35 dev1-fr /usr/sbin/opensips[26796]: siplua: encode:UTF16BE:fjhqqq
Jan 24 17:24:35 dev1-fr /usr/sbin/opensips[26796]: siplua: siplua error running function arg_function: /etc/opensips/scripts/convert.lua:15: attempt to index a nil value (global 'io')
Jan 24 17:24:35 dev1-fr /usr/sbin/opensips[26796]: DBG:core:destroy_index_avp: AVP with the specified index not found
```

Comment:
Calling the open func directly is no use to anybody since it's not actually storing the module table anywhere

Thank you for RhodiumToad helping troubleshoot.

**Comment by bogdan-iancu** [comment]
@volga629-1 , you mean `luaL_loadfile` versus `luaL_requiref`, right ? As `luaL_open` was replaced by `luaL_setfuncs` and it is a generic way on initializing the LUA lib, and it is not for loading the external LUA scripts as  `luaL_requiref`.....or maybe I'm missing something here

**Comment by volga629-1** [comment]
Hello @bogdan-iancu 
luaL_loadfile it just load file it not preload libraries like IO 

```
int luaL_loadfile (lua_State *L, const char *filename);
Loads a file as a Lua chunk. This function uses lua_load to load the chunk in the file named filename. If filename is NULL, then it loads from the standard input. The first line in the file is ignored if it starts with a #.

This function returns the same results as lua_load, but it has an extra error code LUA_ERRFILE if it cannot open/read the file.

As lua_load, this function only loads the chunk; it does not run it.
```

Here are example of our script 

```

function arg_function(str)
        local msg = tostring(AVP_get("msg"))
        local tool = tostring(AVP_get("tool"))
        local format = tostring(AVP_get("format"))
        if tool == "test" then
                xlog(tool .. ":" .. msg .. "\n")
                local handle = io.popen("python3 /etc/opensips/scripts/gsm_utf.py " .. "'" ..msg.. "'" .. " "..tool)
                local cmd_var = handle:read("*all")
                handle:close()
                xlog("Tested string ~> " .. cmd_var .. "\n")
                return AVP_set("test-str", cmd_var)
        else
                xlog(tool .. ":" .. format .. ":" .. msg .. "\n");
                local handle = io.popen("python3 /etc/opensips/scripts/gsm_utf.py " .. "'"..msg.. "'" .." "..tool.." "..format)
                local cmd_var = handle:read("*all")
                handle:close()
                if format == "GSM" then
                        cmd_var=cmd_var:match("b'(.+)'")
                        xlog("Formated GSM-7 bit string ~> " .. cmd_var .. "\n")
                end
                return AVP_set("formatted-msg", cmd_var)
        end
end

```

As you see  we use built it IO in order run same functionality from C level  we need preload all built in  system lua libraries with   luaL_requiref as is it sets the corresponding globals and initialize all required default tables.

```
luaL_requiref
[-0, +1, e]
void luaL_requiref (lua_State *L, const char *modname,
                    lua_CFunction openf, int glb);
Calls function openf with string modname as an argument and sets the call result in package.loaded[modname], as if that function has been called through require.

If glb is true, also stores the result into global modname.

Leaves a copy of that result on the stack.

```

**Comment by razvancrainea** [comment]
The global table was already loaded for all scripts, that's why it was working in lua5.1. However, starting from lua 5.2, these need to be loaded in a new table. I am committing a fix for this now. Please test ASAP and let us know if this solved your problem.

**Comment by razvancrainea** [comment]
I just realized that this report is a bit misleading, as you didn't specify the OpenSIPS version.
Can you confirm that this issue is happening in the master branch?

**Comment by volga629-1** [comment]
> I just realized that this report is a bit misleading, as you didn't specify the OpenSIPS version.
> Can you confirm that this issue is happening in the master branch?

That was on master branch, I specified in my first comment.  Thank you.

**Comment by razvancrainea** [comment]
Thanks, and can you confirm it works fine now?

**Comment by volga629-1** [comment]
Hello @razvancrainea 
I tested patch and didn't work I think library loading is different for lua 5.2 and 5.3 
It should use luaL_requiref load globals.

```
Jan 28 19:43:37 dev1-fr /usr/sbin/opensips[5118]: siplua: siplua error running function arg_function: /etc/opensips/scripts/convert.lua:14: attempt to index a nil value (global 'io')
```

**Comment by razvancrainea** [comment]
I am not sure how you're testing, but I've just used this small lua script:
```
function getVersion()
    local handle = io.popen("hostname")
    xlog(_VERSION .. " runing on " .. handle:read("*all"))                                                                                                                                                                                     
end
```
And got the following result:
```
siplua: Lua 5.3 runing on PC
```
As you can see I am using both the `io` package, as well as `xlog` from OpenSIPS package, and both work just fine.

I suspect there is a problem with your setup, or your lua script.
Not sure how `luaL_requiref` should be used and when/where - if you could issue a pull request with this, I can better understand where it should be located.

**Comment by volga629-1** [comment]
Can you try test script above ?  I applied you commit and generated rpm for dev . 
and that how I am test

from script level 

```
if(lua_exec("arg_function")) {
```

**Comment by razvancrainea** [comment]
I've just tested and the script works just fine.

**Comment by volga629-1** [comment]
how I can test what version of lua being compiled with

**Comment by RhodiumToad** [comment]
@volga629-1 : the commit linked above is not the one that fixes the issue, it's fixed by the immediately prior commit that replaces the faulty luaopen_* calls with luaL_openlibs.

**Comment by volga629-1** [comment]
I suspect  is missing patch for lua lib loading 

https://github.com/OpenSIPS/opensips/commit/c0e56659881861c3550a9c0fedb8caf6690de3b9.patch

I reapplied all lua patches, building new rpms

**Comment by volga629-1** [comment]
OK is has being fixed latest patch is resolve it.

Thank you @razvancrainea @RhodiumToad 

```
Jan 29 16:56:05 dev1-fr /usr/sbin/opensips[30427]: SMS_ROUTE_OUT: Found Body ~> 006b0061006b002000640065006c006100200061006e0064002000740068006500200066006f006c006c006f00770069006e0067
Jan 29 16:56:05 dev1-fr /usr/sbin/opensips[30427]: siplua: Lua 5.3 runing on dev1-fr.networklab.support
```

**Comment by volga629-1** [comment]
Issue has being resolve. Thank you for prompt fix.
