### ISSUE TITLE
[BUG] get_statistics shmem: blocks with Q_MALLOC_DBG

### ISSUE THREAD

**Issue by StellaTeam** [OpenSIPS/opensips#1950]
**OpenSIPS version you are running**

```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: dac56fa49
main.c compiled on  with gcc 8

```

**Describe the bug**

opensips-cli hangs on `opensips-cli -x mi get_statistics shmem:` since opensips is in Q_MALLOC_DBG mode

**To Reproduce**
Enable Q_MALLOC_DBG mode
Launch `opensips-cli -x mi get_statistics shmem:` on a regular basis (cron).
After a while, no reply and `opensips-cli` hangs.

**Expected behavior**
Normally opensips/opensips-cli should always return results..

**Relevant System Logs**
Nothing found.

**OS/environment information**
 Debian buster

**Additional context**

Please let me know if i can give any useful complementary information.

Thank you

**Comment by bogdan-iancu** [comment]
You are running a rather old version of OpenSIP (since 1st of Oct 2019) - try first to upgrade to latest 3.0.1 (note that tomorrow a new minor will be released) and check again your issue.

**Comment by StellaTeam** [comment]
Hi @bogdan-iancu 
I successfully upgraded to 3.0.2
```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7e8167853
main.c compiled on  with gcc 8

```

 but the problem is still there,
opensips_fifo_reply_XXXX file is created, never filled and opensips-cli stay blocked.

Please let me know how i can help to diagnose the issue.

Regards

**Comment by bogdan-iancu** [comment]
You mentioned that the blocking happens after a while (and not from the first). Please try these:
* be sure you have the opensips-dbg and gdb packages installed
* when the get_statistics block, run from a different console `opensips-cli -x trap`

**Comment by StellaTeam** [comment]
Hi @bogdan-iancu 

I followed your instructions, here are the console messages and the GDB trap file attached to this message.

Thank you.

```
root@ft-idc9:~# opensips-cli -x trap
41	../sysdeps/unix/sysv/linux/select.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
41	../sysdeps/unix/sysv/linux/select.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
29	../sysdeps/unix/sysv/linux/pause.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
41	../sysdeps/unix/sysv/linux/select.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
30	../sysdeps/unix/sysv/linux/epoll_wait.c: Aucun fichier ou dossier de ce type.
Trap file: /tmp/gdb_opensips_20200131_143920
```

[gdb_opensips_20200131_143920.zip](https://github.com/OpenSIPS/opensips/files/4139640/gdb_opensips_20200131_143920.zip)

**Comment by StellaTeam** [comment]
Another occurrence (the second one but i didn't kept traces of the previous one).
I hope this might be useful...

[gdb_opensips_20200201_174552.zip](https://github.com/OpenSIPS/opensips/files/4142803/gdb_opensips_20200201_174552.zip)

**Comment by bogdan-iancu** [comment]
The backtraces does not show any systemic blocking into OpenSIPS. Could you confirm that after the blocking on `shmem:`, you can actually run later (without aany restart) other MI commands ?

**Comment by StellaTeam** [comment]
Hi @bogdan-iancu 

I made new tests, and it seems opensips-cli does not block when called while the first one is blocked.
Do you think it might be more opensips-cli related or do you have any other idea on what can trigger this problem?

Regards

**Comment by StellaTeam** [comment]
Hello

There should have a problem somewhere in memory allocation as:
- i used opensips-cli to track memory consumption (because i already got several in the past) and i showed a leak, but opensips-cli never blocked
- i changed allocation mode to get more details on the leak, the leak seems to have disappeared but now opensips-cli blocks several times per day...

I don't know what i can do to help diagnose and solve, firstly, the blocking, then the leak (maybe the origin is the same - i have no idea).

Thank you

**Comment by StellaTeam** [comment]
Hello
The problem is still there, several times per day...
Waiting for instructions to help debugging the problem.

**Comment by StellaTeam** [comment]
Hello

The problem is still there, the leak seems to be around 2MB per day...
Despite all test i make i can't find from where the leak comes, but i have some more clues.

It seems the problem is between `shmem:used_size` and `shmem:real_used_size`.
While `used_size` is going up and down according to the server load, `real_used_size` not always reduces.

For example, on a production server on a short interval we have:

```
{     "shmem:total_size": 1073741824      "shmem:max_used_size": 8818080      "shmem:free_size": 1065661272      "shmem:used_size": 4089960      "shmem:real_used_size": 8080552      "shmem:fragments": 2695 }
 /usr/local/bin/opensips-cli -x mi get_statistics shmem: | tr ",\n" " "
{     "shmem:total_size": 1073741824      "shmem:max_used_size": 8818080      "shmem:free_size": 1065719544      "shmem:used_size": 4029720      "shmem:real_used_size": 8022280      "shmem:fragments": 2592 }
 /usr/local/bin/opensips-cli -x mi get_statistics shmem: | tr ",\n" " "
{     "shmem:total_size": 1073741824      "shmem:max_used_size": 8818080      "shmem:free_size": 1065661712      "shmem:used_size": 4083472      "shmem:real_used_size": 8080112      "shmem:fragments": 2738 } 
```
We well see `real_used_size` is almost twice `free_size`

Please let me know if i can provide anything to help better find where the leak is.

Regards

**Comment by StellaTeam** [comment]
Hello

This issue is about two problems, and that's probably the reason is stalls.

Moving `opensips-cli` from FIFO to HTTP stopped lockdowns, that's the first good point (even if i have no idea on the reasons of the blocking in FIFO mode).

For the memory leak, I made all tests i could to find the origin of the leak, as explained in wikis and forums, without success as there is no not-freed units.

According to everything i read and my understanding, the leak seems to be related to memory manager overheads that are not always freed.
As explained before, the leak seems to be between `used_size` and `real_used_size` (and my latests tests confirm that).
`used_size` is moving up and down, relative to server load, but `real_used_size` almost never reduce and quickly becomes double of `used_size` and beyond...
It is quite clear it is related to `F_MALLOC` as, moving to `Q_MALLOC_DBG` (used for debugging) makes it disappear.
I now should try to use `Q_MALLOC` to be sure of it (as DBG mode is no more useful).

That's not a problem for me if the leak stops thanks to `Q_MALLOC`, as my server load is not big enough to require `F_MALLOC`.
Moreover, if HTTP mode make `opensips-cli` work as expected, that's good for me.

That's just a shame these problems are not solved for anyone else who have the same problems and bigger needs.

I would be happy to give any details or logs that might help solving these problems.
If nobody cares, the issue will be closed by the robot...

Thank you

**Comment by liviuchircu** [comment]
Hey, @StellaTeam !

I recently made some fifo-related "discoveries" and I remembered this thread, so let me clarify a few things:

#### 1. Occasional blocking/stalling of the client after writing a command to the FIFO file

It looks like this is a limitation of the FIFO module -- I haven't studied the issue itself.  Nevertheless, it's easily reproducible: just start 3-4 consoles with:

    while true; do opensips-cli -x mi get_statistics shmem:; done

... and one (or more) of them should soon block.  Conclusion:  it looks like the FIFO module has a limitation of _"max 1 concurrent command"_.  For the time being, the quickest way to address this issue is by switching to "httpd" and "mi_http".

#### 2. Memory leak with `F_MALLOC` but not `Q_MALLOC`

There is no such thing (I am 99% sure, since the code hasn't changed in years).  On a worst case, F_MALLOC may be more susceptible to fragmentation (thus consuming a bit more memory than usual).  But this comes with benefits, since the fragmented memory chunks are readily available for any process requiring them.  Lastly, once memory usage gets past 70% (IIRC), F_MALLOC will be less wasteful and will start coalescing its memory fragments into larger chunks, as the fragments get freed.

My advice: don't even worry about memory leaks if your memory usage is at 4 MB / 1 GB.  Also notice how your all-time max used is only 8.8MB, which is less than 1%!  At these levels of memory usage (1% - 5%), OpenSIPS will oftentimes keep the memory fragmented, so it is better equipped to deal with bursts of traffic.

**Comment by StellaTeam** [comment]
Hi @liviuchircu 

Thank you for your reply.

About FIFO, using HTTP instead of it is what i've done, and since then, no more blocking problems.

About memory, your says make sense, and so already allocated chunks, waiting for reuse are non_free memory, and that's reported as well...
What seems strange to me is OpenSIPS doesn't reuse them and reallocate new chunks.  
I'm pretty sure our load is not growing every days, it is quite the same, but allocation still grows...
So, maybe the chunks reuse vs reallocation depends on system load, available memory or many other parameters (contention?).  
As our performance requirements are not too important compared to our setup F_MALLOC is not necessary and, on another side, we don't want to take risks to have a real leak somewhere in our setup,so for the time being we'll stay on Q_MALLOC with monitoring showing stable memory usage, that is quire reassuring ;-)

Thanks for your advices

**Comment by bogdan-iancu** [comment]
@liviuchircu, the reported blocking has nothing to do with the "max 1 concurrent commands" limitation. This limitation exists in almost al the MI backends (excepting datagram) because all of them are single process/threaded and all commands execution is serialized.
By switching to mi_http you still have the "max 1 concurrent commands" limitation.
I would say the blocking my be FIFO specific, but totally unrelated to your "max 1 concurrent commands" discovery.

**Comment by liviuchircu** [comment]
Fair enough, @bogdan-iancu, maybe my wording wasn't the best.  Here is another attempt:

* with "mi_fifo", you have "max 1 concurrent command.  Any more than this and the FIFO client *may block indefinitely*, without ever receiving a response"
* with the rest of the MI modules, you simply have "max 1 concurrent command.  Any more than this and you will simply have to wait until the currently executed command finishes"
