### ISSUE TITLE
[BUG] perl_exec_simple not returning

### ISSUE THREAD

**Issue by fgast** [OpenSIPS/opensips#1951]
**OpenSIPS version you are running**

```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**

While porting our configurations to 3.0 i noticed that the  perl_exec_sipmple functions does not return. 
Can be reproduced every time. 

**To Reproduce**
1. Configuration
opensips.cfg 
```
route[perl] {
	xlog("perl_exec_simple: test\n");
	perl_exec_simple("testfunc");
	xlog("perl_exec_simple done!\n");
}
startup_route {
	xlog("STARTUP!\n");
	route(perl);
}
```
test.pl: 
```
use strict;
use OpenSIPS qw ( log );
use OpenSIPS::Constants;
use OpenSIPS::Message;

sub testfunc {
    OpenSIPS::log( L_INFO, "Perl running....\n" );
    return 1;
}
```
2. Start OpenSIPS
3. Output: 
```
Jan 28 09:56:10 [26] STARTUP!
Jan 28 09:56:10 [26] perl_exec_simple: test
Jan 28 09:56:10 [26] DBG:perl:perl_exec_simple: running perl function "testfunc"
Jan 28 09:56:10 [26] INFO:core:XS_OpenSIPS_log: Perl running....
...
```

**Expected behavior**
Works on OpenSIPS 2.4 
```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

Output of same configuration:  
```
Jan 28 09:41:46 [27] STARTUP!
Jan 28 09:41:46 [27] perl_exec_simple: test
Jan 28 09:41:46 [27] DBG:perl:perl_exec_simple: running perl function "testfunc"
Jan 28 09:41:46 [27] INFO:core:XS_OpenSIPS_log: Perl running....
Jan 28 09:41:46 [27] perl_exec_simple done!
...
```

**OS/environment information**
 - Operating System: `Debian 9`
 - OpenSIPS installation:`debs`
 - Perl Version: `5.24.1-3+deb9u5`

**Additional context**

* This works for `perl_exec` if `testfunct` returns `1` on OpenSIPS 3.0 but not if `testfunc` returns `0`
* On 2.4 it works with `perl_exec` and `perl_exec_simple` on returning `0` or `1`

**Comment by rvlad-patrascu** [comment]
There was indeed a bug introduced when porting `perl_exec_simple` to OpenSIPS 3.0. But, note that `perl_exec` (unlike `perl_exec_simple` which doesn't propagate the return value from perl), can cause the script execution to halt, both on 2.4 and 3.0, if the perl function returns `0`. This behavior follows the OpenSIPS script functions return code conventions.
