### ISSUE TITLE
[CRASH] Opensips 3.0.2 segfault proto_wss.so

### ISSUE THREAD

**Issue by suharik71** [OpenSIPS/opensips#1956]
**OpenSIPS version you are running**

```
opensips -V
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 43d479221
main.c compiled on 03:18:22 Jan 30 2020 with gcc 4.8.5
```

**Crash Core Dump**

https://pastebin.com/eCW6DBBJ

**Describe the traffic that generated the bug**

**To Reproduce**
```
loadmodule "proto_wss.so"
modparam("proto_wss", "wss_port", 8088)
modparam("proto_wss", "wss_resource", "/wss")
modparam("proto_wss", "wss_handshake_timeout", 300)

loadmodule "tls_mgm.so"
modparam("tls_mgm", "server_domain", "dom1")
modparam("tls_mgm", "certificate", "[dom1]/certs/dom1/cert.pem")
modparam("tls_mgm", "private_key", "[dom1]/certs/dom1/privkey.pem")
modparam("tls_mgm", "tls_method", "[dom1]tlsv1_2")
modparam("tls_mgm", "verify_cert", "[dom1]0")
modparam("tls_mgm", "require_cert", "[dom1]0")
```

**Relevant System Logs**
```
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13296]: new branch at sip:1234123@wss-dev.vezet.ru
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5]: Received command 'offer' from 127.0.0.1:39214
янв 30 08:59:02 wss-dev rtpengine[24073]: NOTICE: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5]: Creating new call
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5]: Replying to 'offer' from 127.0.0.1:39214 (elapsed time 0.002095 sec)
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13292]: incoming reply
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13292]: incoming reply
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5]: Received command 'answer' from 127.0.0.1:45933
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5]: Replying to 'answer' from 127.0.0.1:45933 (elapsed time 0.000532 sec)
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13292]: ACC: transaction answered: timestamp=1580363942;method=INVITE;from_tag=ZQAwFyXeQdbb5iTxqPvz;to_tag=65bc6234-5b79-4aa8-8bb6-0fd6779782d8;call_id=d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5;code=200;reason=OK
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5 port 30187]: ICE negotiated: peer for component 1 is 10.23.96.219:60648
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5 port 30187]: ICE negotiated: local interface 10.23.13.16
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5 port 30187]: ICE negotiated: peer for component 2 is 10.23.96.219:64212
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13296]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13296]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 118
янв 30 08:59:02 wss-dev kernel: opensips[13296]: segfault at 34 ip 00007fcf043130de sp 00007ffebdb483e0 error 4 in proto_wss.so[7fcf04300000+1c000]
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13296]: CRITICAL:core:sig_usr: segfault in process pid: 13296, id: 12
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13305]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13305]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 97
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5 port 30186]: DTLS: Peer certificate accepted
янв 30 08:59:02 wss-dev rtpengine[24073]: INFO: [d5cad2f0-410f-6c2f-6821-4ba3baaf8bf5 port 30187]: DTLS: Peer certificate accepted
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13284]: INFO:core:handle_sigs: child process 13296 exited by a signal 11
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13284]: INFO:core:handle_sigs: core was not generated
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13284]: INFO:core:handle_sigs: terminating due to SIGCHLD
янв 30 08:59:02 wss-dev /usr/sbin/opensips[13285]: INFO:core:sig_usr: signal 15 received
```

**OS/environment information**
 - Operating System: Centos 7
 - OpenSIPS installation: opensips-yum-nightly
 - other relevant information:

**Additional context**

when you make a call from webrtc client sipml5 opensips falls into error.

**Comment by razvancrainea** [comment]
The core file you have dumped does not seem to correspond with your build. Check the `warning: exec file is newer than core file.` in the output.
Moreover, the line that points to the crash does not really make sense, i.e. it is very unlikely (almost impossible) to have crashed in that place.

Can this crash be reproduced by you? I've tried to do it, but for me it works just fine. If you can reproduce it, and make sure you are using the same `opensips` and `opensips-debug` packages version?

**Comment by suharik71** [comment]
New core dump https://pastebin.com/DXdLpTk9

and now use opensips version
opensips -V
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 0e25e055b
main.c compiled on 03:24:17 Feb  6 2020 with gcc 4.8.5

debug log contain
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6278]: INFO:core:probe_max_sock_buff: using snd buffer of 416 kb
фев 06 14:23:09 wss-dev kernel: opensips[6278]: segfault at 34 ip 00007f1d1e1b00de sp 00007ffd9979bad0 error 4 in proto_wss.so[7f1d1e19d000+1c000]
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6278]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 119
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6278]: CRITICAL:core:sig_usr: segfault in process pid: 6278, id: 12
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:handle_sigs: child process 6278 exited by a signal 11
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:handle_sigs: core was not generated
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:handle_sigs: terminating due to SIGCHLD
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6267]: INFO:core:sig_usr: signal 15 received
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 1(6267) [MI FIFO] terminated, still waiting for 19 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 4(6270) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 18 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 5(6271) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 17 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 6(6272) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 16 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 8(6274) [SIP receiver udp:10.23.13.16:5060] terminated, still waiting for 15 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 9(6275) [SIP receiver udp:10.23.13.16:5060] terminated, still waiting for 14 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 10(6276) [SIP receiver udp:10.23.13.16:5060] terminated, still waiting for 13 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 13(6279) [TCP receiver] terminated, still waiting for 12 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 15(6281) [TCP receiver] terminated, still waiting for 11 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 16(6282) [TCP receiver] terminated, still waiting for 10 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 17(6283) [TCP receiver] terminated, still waiting for 9 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 18(6284) [TCP receiver] terminated, still waiting for 8 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 19(6285) [TCP receiver] terminated, still waiting for 7 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 20(6286) [Timer handler] terminated, still waiting for 6 more
фев 06 14:23:09 wss-dev rtpengine[1304]: INFO: [9c446ddf-7f58-ecaa-902c-00400470751d port 30178]: DTLS: Peer certificate accepted
фев 06 14:23:09 wss-dev rtpengine[1304]: INFO: [9c446ddf-7f58-ecaa-902c-00400470751d port 30179]: DTLS: Peer certificate accepted
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6269]: INFO:core:sig_usr: signal 15 received
фев 06 14:23:09 wss-dev rtpengine[1304]: INFO: [9c446ddf-7f58-ecaa-902c-00400470751d port 30178]: DTLS-SRTP successfully negotiated
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 3(6269) [timer] terminated, still waiting for 5 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 7(6273) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 4 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 14(6280) [TCP receiver] terminated, still waiting for 3 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 21(6287) [TCP main] terminated, still waiting for 2 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6268]: INFO:core:sig_usr: signal 15 received
фев 06 14:23:09 wss-dev rtpengine[1304]: INFO: [9c446ddf-7f58-ecaa-902c-00400470751d port 30179]: DTLS-SRTP successfully negotiated
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 2(6268) [time_keeper] terminated, still waiting for 1 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:shutdown_opensips: process 11(6277) [SIP receiver udp:10.23.13.16:5060] terminated, still waiting for 0 more
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: INFO:core:cleanup: cleanup
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: ERROR:proto_wss:tls_write: TLS connection to 10.23.96.219:55016 write failed
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: ERROR:proto_wss:tls_write: TLS write error:
фев 06 14:23:09 wss-dev /usr/sbin/opensips[6266]: ERROR:proto_wss:tls_blocking_write: TLS failed to send data

crash occurs when calling

**Comment by razvancrainea** [comment]
I've just pushed a commit in the master branch for this. Could you please test against the master branch and let me know if you're still facing this issue?

**Comment by razvancrainea** [comment]
Actually I've just managed to reproduce and I can confirm the fix solves the crash. Closing the ticket now, if you're still facing problems, please re-open it.
