### ISSUE TITLE
[BUG] ucs2 smpp message is wrongly decoded.

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips#1957]
**OpenSIPS version you are running**

```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, EXTRA_DEBUG, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a9d07b55f
main.c compiled on 08:07:34 Jan 10 2020 with gcc 6.3.0

proto_smpp from master (31012020).
```

**Describe the bug**

When a message from a provider comes in in UCS2 the message is not properly decoded, I only receive part in rb.  
(additional question, how does opensips knows to what it needs to decode ? Best thing would be to have a parameter in the proto_smpp module) 
The length of the received message in tcp_conn is correct. 

SMS sent in : ê€ (net result is that the user receives an empty message )

log level 5 - log.

DBG:core:proto_tcp_read: read 59 bytes:
DBG:proto_smpp:smpp_parse_headers: received a complete message
DBG:proto_smpp:smpp_handle_req: completely received a message
DBG:proto_smpp:smpp_handle_req: Nothing more to read on TCP conn 0x7f4a718d2158, currently in state 0
DBG:proto_smpp:handle_smpp_msg: Received SMPP command 00000005
DBG:proto_smpp:handle_deliver_sm_cmd: Received deliver_sm command
DBG:proto_smpp:handle_submit_or_deliver_cmd: Received SMPP message#012FROM:#01101 01 33630545022#012TO:#01101 01 33757936423#012LEN:#0114
...
callid=68799728357bacff-16577@10.3.0.150: local_route : message generated by tm ru sip:33757936423@10.3.0.150:50131 rb 00ea 

the pcap is also attached. 

**To Reproduce**

send sms 'ê€'

**Expected behavior**

We expect to receive the full message body. 

**Relevant System Logs**

'''see above'''

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

    Operating System: Debian 9
    OpenSIPS installation: git clone https://github.com/OpenSIPS/opensips.git -b 3.0 opensips-3.0.1

**Additional context**

[received_message_from_provider.zip](https://github.com/OpenSIPS/opensips/files/4138905/received_message_from_provider.zip)

**Comment by razvancrainea** [comment]
I've just pushed a fix for this in the master branch. Could you please test and let me know if it sorts out your problem?

**Comment by razvancrainea** [comment]
Could you please confirm whether this fix solves your problem?

**Comment by johandeclercqdemocon** [comment]
Yeah, I will test tomorrow morning (friday is always upgrade and test day).

Op do 6 feb. 2020 om 09:16 schreef Răzvan Crainea <notifications@github.com

**Comment by volga629-1** [comment]
Hold on, not yet.
