### ISSUE TITLE
[BUG][Drouting] An empty prefix starts matching all the prefixes for that gateway

### ISSUE THREAD

**Issue by ryanembregts** [OpenSIPS/opensips#1961]
**OpenSIPS version you are running**

```
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**

**To Reproduce**

Example:
1. Just insert a row in dr_rules table with empty prefix
```
INSERT INTO `opensips`.`dr_rules`(`ruleid`, `groupid`, `prefix`, `timerec`, `priority`, `routeid`, `gwlist`, `attrs`, `description`) VALUES (3, '0', '', NULL, 0, NULL, '1', '100', NULL);
INSERT INTO `opensips`.`dr_gateways`(`id`, `gwid`, `type`, `address`, `strip`, `pri_prefix`, `attrs`, `probe_mode`, `state`, `socket`, `description`) VALUES (10, '1', 0, '20.20.30.40', 0, NULL, NULL, 0, 0, NULL, NULL);
```
2. Check any prefix matching using below fifo command
3. opensipsctl fifo dr_number_routing 0 4048004545
```
root@debian:/# opensipsctl fifo dr_number_routing 0 4048004545
Matched Prefix::
        GATEWAY:: 1
```

**Expected behavior**
An empty prefix was wrongly inserted into database but caused a lot calls being routed towards wrong gateways. This caused us quite money. 

Any protection offered by opensips here would be great. :)

Thanks for the awesome work.

**Comment by liviuchircu** [comment]
Logically speaking:

* `"123"` will match `123XXXXXXXX`
* `"12"` will match `12XXXXXXX`
* `"1"` will match `1XXXXXXXX`
* `""` will match `XXXXXXXXX`

This is a feature, not a bug, as the `""` prefix is meant to be used as a default routing fallback for the longest-prefix-match algorithm.  My question for you is:

*What did you expect to happen when you added the `""` rule?*  Nothing?  Something?  Auto-detection from OpenSIPS that it is an incorrect rule for your company and business logic, but not for others?

**Comment by ryanembregts** [comment]
@liviuchircu thanks for answering. PHP application wrongly inserted the empty prefix there and i was not sure that it was meant for default fallback. Protection should be in php application not in opensips which seems to be working great. Sorry for the fuss.
