### ISSUE TITLE
[FEATURE] Variable/s that contains current and parent route names

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#1963]
Hello,

Having variables that contains current and parent route name should be very useful for logging and statistics.

Regards

**Comment by liviuchircu** [comment]
One idea would be to have an indexed `$route` variable, which would behave (access-wise) exactly as an `$avp`, allowing you to inspect the entire stack.  So, for example, if we had a 5-route call, `A -> B -> C -> D -> E`, the new `$route` variable would behave like so:

```
"E" == $route == $(route[0]) == $(route[-5])
"D"  == $(route[1]) == $(route[-4])
"C"  == $(route[2]) == $(route[-3])
"B"  == $(route[3]) == $(route[-2])
"A"  == $(route[4]) == $(route[-1])
```

What do you people think?

**Comment by atrips** [comment]
Seems wise proposal and more generic.

As some common routes can be called on different places in the config.
My initial idea behind that was to have a logging template prefix in order to reproduce following log output:

```
L_XXX:route:C>D: some logging
L_XXX:route:A>D: some logging

xlog("L_DBG","$(route[1])>$(route[0]) some logging\n"); ## Perfectly fine to me
```

Another usage are stats like that:

```
routes.hit.C.D.enter++ // Called on top
routes.hit.C.D.exit++  // Called before retrun
routes.hit.C.D.fail++  // Called on error retrun
```

Is the statement "exactly as an $avp" means that loops will work too ? That will be great.

Maybe other people will comment too.

**Comment by atrips** [comment]
Hello, any chance for 3.1 release ?

**Comment by liviuchircu** [comment]
Tough call, @atrips.  Depending on how things progress, this may still be in the cards, but don't get your hopes up, though -- there's still plenty of work to be done on the calling API side, which _must_ be wrapped up!  Will keep you posted.

**Comment by atrips** [comment]
Thanks a lot @liviuchircu.

**Comment by atrips** [comment]
Sorry again @liviuchircu,

Any news about the feature request ?
