### ISSUE TITLE
[FEATURE] registrar/mid_registrar max AoR lenght to be set by modparam

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#1964]
Hello

It will be very useful if registrar and mid_registrar max AoR length to be set by modparam instead change MAX_AOR_LEN definitions.

Regards

**Comment by atrips** [comment]
Thanks @liviuchircu 

Is this patch affects registrar too ?

**Comment by liviuchircu** [comment]
Not yet.  I will put that on my TODO list as well ;)

**Comment by atrips** [comment]
Why in TODO ? I see that you like do such a things Friday evening ;)

Now serious, mid_registrar patch seems to work fine.
