### ISSUE TITLE
[FEATURE] Modparam that contains custom "callid_pv" instead SIP/default Call-Id for rtpngine module

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#1967]
My target topology:

```
UA1 --- AccessProxy --- Registrar
UA2 --- AccessProxy --/ 
UAx --- AccessProxy -/
```

UA1 .. UAx are different devices but they are sharing same username@domain/password. Both AccessProxy and Registrar are OpenSIPS. AccessProxy is dealing only w/ NAT and RTP relay if/when needed. Regstrat makes "forking" to AccessProxy. Problem I'm having w/ the current implementation (using Call-Id + to/extra/via) is that as far I understand is designed when forking is made on AccessProxy(in this case we have single call with multiple branches) but not on upstream proxy. When you make a call forking on "Regstrar" in my case, on "AccessGateway" we actualy having N calls sharing same Call-Id and that case at least I cannot found a way to handle it properly w/ current impelementation. With my limited knoledge of OpenSIPS programming I added just another "$avp" that overides SIP Call-Id for the rtpengine module. In my case on AccessProxy I set that "$avp" from config to SIP "Call-ID + branch". This solution seems to work well w/ no issues at all.

**Comment by razvancrainea** [comment]
This is already available - simply use the `callid` key in the rtpengine flags and rtpengine will use the specified callid.
