### ISSUE TITLE
[FEATURE] OpenSIPS 2.4 (3.0 ?) rtpengine module doesn't support the DTLS=passive option.

### ISSUE THREAD

**Issue by adomjan** [OpenSIPS/opensips#1968]
This feature was available in 2.2 versions.  

I applied on 2.4 again:
https://github.com/OpenSIPS/opensips/pull/429#event-249672127
and added the off, no options also.

This feature is mandatory for WSS clients.

**Comment by razvancrainea** [comment]
I am not sure I understand the report. Can you be more specific?
The option works just fine, I've just tested it.

**Comment by adomjan** [comment]
I'm sorry to bother you, I missed sg...

**Comment by razvancrainea** [comment]
No worries, you're not bothering me, I was just a bit confused about the report.
