### ISSUE TITLE
[BUG] The nathelper.cfg in examples is not compatible with 3.0.x

### ISSUE THREAD

**Issue by jamie-wearsafe** [OpenSIPS/opensips#1972]
**OpenSIPS version you are running**

```
3.0
```

**Describe the bug**
I am working through setting up opensips and finding that the examples in this repo only work for the previous versions of opensips. And in the Documentation for nathelper, there are no usage examples as there are for other modules such as the LDAP auth module.

**To Reproduce**
```sh
curl -sSLl -o opensips.cfg https://raw.githubusercontent.com/OpenSIPS/opensips/master/examples/nathelper.cfg
docker run --rm --name opensips-nathelper -v "$(pwd)/opensips.cfg:/etc/opensips/opensips.cfg:rw" --entrypoint="/usr/sbin/opensips"  opensips/opensips -C
```

I have tried to get it running, by changing the obvious syntax errors, but even after that it still is giving errors. And I am only 2 weeks into learning opensips config, so I can't get much further.

**Expected behavior**

Opensip examples in the examples directory work with the source code version that they are with to allow new opensips adopters to onboard themselves quickly.

**Relevant System Logs**
```
docker run --rm --name opensips-nathelper -v "$(pwd)/opensips.cfg:/etc/opensips/opensips.cfg:rw" --entrypoint="/usr/sbin/opensips"  opensips/opensips -C
Feb 13 15:57:02 [1] Traceback (last included file at the bottom):
Feb 13 15:57:02 [1]  0. /etc/opensips/opensips.cfg
Feb 13 15:57:02 [1] CRITICAL:core:yyerror: parse error in /etc/opensips/opensips.cfg:29:1-5: syntax error
Feb 13 15:57:02 [1] dns=no           # (cmd. line: -r)
Feb 13 15:57:02 [1] rev_dns=no      # (cmd. line: -R)
Feb 13 15:57:02 [1] port=5060
Feb 13 15:57:02 [1] ^~~~~
Feb 13 15:57:02 [1] children=4
Feb 13 15:57:02 [1] 
Feb 13 15:57:02 [1] CRITICAL:core:yyerror: parse error in /etc/opensips/opensips.cfg:29:1-5: 
Feb 13 15:57:02 [1] ERROR:core:parse_opensips_cfg: bad config file (2 errors)
Feb 13 15:57:02 [1] ERROR:core:main: failed to parse config file (null)
Feb 13 15:57:02 [1] NOTICE:core:main: Exiting....
```

**OS/environment information**
Using the opensips docker container.

**Comment by bogdan-iancu** [comment]
@jamie-wearsafe , thanks for the heads up, I just ported the nathelper.cfg to the 3.0 and 3.1 syntax. Please give it a try ;)
