### ISSUE TITLE
[BUG] not sending PRACK to the provisional reply  with Require: 100rel

### ISSUE THREAD

**Issue by mrsanvicente** [OpenSIPS/opensips#1978]
Hello,
I am describing an issue i currently have.
I am trying to enable PRACK response to provisional reply,  as it is described on b2b_entities module:     ... but is it not working.

modules/b2b_entities/dlg.c

/* PRACK handling */
/* if the provisional reply contains a
 * Require: 100rel header -> send PRACK */

**OpenSIPS version you are running**
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 21:06:38 Nov 11 2019 with gcc 4.8.5

**Describe the bug**

NO PRACK RECEIVED with Require: 100rel.

Opensips        ----     Destination
INVITE  ----------------->
<--------------------  100 Trying
<---------------------180 Ringing
<---------------------180 Ringing
<---------------------180 Ringing
<----------------------  CANCEL
ACK -------------------->

loadmodule "b2b_entities.so"
loadmodule "b2b_logic.so"
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 60)
modparam("tm", "pass_provisional_replies", 1)

loadmodule "topology_hiding.so"
modparam("topology_hiding", "force_dialog", 1)

 if ( is_method("INVITE")) {
                record_route();
                create_dialog("rR");
                topology_hiding("UD");
                rewritehostport("10.211.5.244:5060");
}

**To Reproduce**

TRACE of the message received

SIP/2.0 180 Ringing
Via: SIP/2.0/UDP 0.0.0.0:5060;received=x.x.x.x;branch=z9hG4bKa71c.7454f172.0
To: <sip:1999999999971@x.x.x.x.x:5060;user=phone>;tag=h7g4Esbg_72146097
From: 444444444 <sip:444444444@10.205.3.244:5060;user=phone>;tag=98413c56
Call-ID: df0e3b428c553939
CSeq: 1 INVITE
Contact: <sip:sgc_c@x.x.x.x;transport=udp>
Record-Route: <sip:x.x.x.x;transport=udp;lr>
Call-Info: <sip:+6645557867671@icscf.ld.tttt;user=phone>;purpose=call-completion;m=NR
Require: 100rel
RSeq: 1461252296
Content-Type: application/sdp
Content-Length: 216
Allow: INVITE, ACK, CANCEL, BYE, OPTIONS, PRACK, UPDATE

**Expected behavior**

Opensips        ----     Destination
INVITE  ----------------->
<--------------------  100 Trying
<---------------------180 Ringing
PRACK   ------------------->                                        ---THIS IS THE MESSAGE NEEDED---
<----------------------  200 OK
ACK -------------------->

*NO LOGS

CentOS Linux release 7.7.1908 (Core)
**Additional context**

**Comment by razvancrainea** [comment]
@mrsanvicente you're not using the `b2b_entities` module, you're just loading it. But your call is not 
engaged in B2B mode (using the B2B logic), but using the `topology_hiding` mode.
If you want to have OpenSIPS behave as a B2B, and reply a PRACK message to those provisional replies, you should use the [B2B topology hiding](https://opensips.org/docs/modules/3.0.x/b2b_logic.html#func_b2b_init_request). However, note that in B2B mode, the logic of your script will change a bit, as it will no longer run in proxy mode.

**Comment by mrsanvicente** [comment]
Hello @razvancrainea,
Thank you for your answer.  Actually i tried enabling top hiding,  which on the docs says " one predefined service that works without any scenario definition and for any type of dialog"

b2b_init_request("top hiding");

But after enabling, Opensips do not answer INVITES,   maybe because of the logic change you mention.
How can i troubleshoot this new logic?
My intention would be to have the opensips working as proxy and just having the PRACK to provisional messages  ( That is mandatory for interconecting with some SBC).

Any comments?

**Comment by razvancrainea** [comment]
I don't understand what "OpenSIPS do not answer INVITES". Maybe you can provide a PCAP of the call(s)?

**Comment by mrsanvicente** [comment]
Hello @razvancrainea ,

Please find attached 2 traces.


1) On the top-hiding1.pcap,   I have the line b2b_init_request("top hiding");, 

2) on NO-PRACK1.pcap, is the same configuration but #b2b_init_request("top hiding"); is commented.
[top-hiding1.zip](https://github.com/OpenSIPS/opensips/files/4234008/top-hiding1.zip)


Thank you

**Comment by razvancrainea** [comment]
@mrsanvicente you should check the logs to understand why the message is not forwarded. Or perhaps it is forwarded to a bad destination.
Nevertheless, this is not a bug. If you need more help, please post on our mailing list: http://lists.opensips.org/cgi-bin/mailman/listinfo/users

**Comment by mrsanvicente** [comment]
Thank you @razvancrainea , i will visit your mailing list.   

anyhow it is strange that just enabling the line #b2b_init_request("top hiding");   and opensips starts ok,   but after the new call opensips stops working,    

/usr/local/sbin/opensips[20363]: INFO:core:sig_usr: signal 15 received
/usr/local/sbin/opensips[20360]: INFO:core:shutdown_opensips: process 3(20363) [timer] terminated, still waiting for 19 more
