### ISSUE TITLE
[BUG] siprec module: Origin (o=) IP address is hardcoded to 0.0.0.0

### ISSUE THREAD

**Issue by MikhailKalashnikov** [OpenSIPS/opensips#1979]
**OpenSIPS version you are running**
```
# opensips -V
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 540d1a498
main.c compiled on  with gcc 4.9.2
```

**Describe the bug**
Origin (o=) IP address is hardcoded to 0.0.0.0.
According to this comment in [siprec_body](https://github.com/OpenSIPS/opensips/blob/master/modules/siprec/siprec_body.c#L478) origin format should be `o=- <timestamp> <version> IN IP4 <mediaip>`
But instead of mediaip 0.0.0.0 is [hardcoded](https://github.com/OpenSIPS/opensips/blob/master/modules/siprec/siprec_body.c#L485)

**Expected behavior**
<mediaip> is used for origin (o=) IP, if mediaip is defined

**Comment by razvancrainea** [comment]
Please let me know if this fixes your problem, and if it does, I will backport it down to 2.4.

**Comment by MikhailKalashnikov** [comment]
@razvancrainea I made my tests and the fix looks fine.
Thank you for this fix
