### ISSUE TITLE
Installation Ubuntu 18.04

### ISSUE THREAD

**Issue by andersoncatao** [OpenSIPS/opensips#1982]
Hello I`m tying to install Opensips 2.4.7 but I`m facing the following problem:

```
Linking opensips
main.o: In function `pthread_mutex_init':
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:32: undefined reference to `pthread_mutexattr_setpshared'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:26: undefined reference to `pthread_mutexattr_init'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:32: undefined reference to `pthread_mutexattr_setpshared'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:38: undefined reference to `pthread_mutexattr_destroy'
main.o: In function `pthread_rwlock_init':
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:64: undefined reference to `pthread_rwlockattr_setpshared'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:58: undefined reference to `pthread_rwlockattr_init'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:64: undefined reference to `pthread_rwlockattr_setpshared'
/usr/local/src/opensips-2.4.7/ssl_tweaks.h:70: undefined reference to `pthread_rwlockattr_destroy'
collect2: error: ld returned 1 exit status
Makefile.rules:38: recipe for target 'opensips' failed
make[1]: *** [opensips] Error 1
make[1]: Leaving directory '/usr/local/src/opensips-2.4.7'
```

Any tip why ?

**Comment by razvancrainea** [comment]
The report template we have spent so much time to built was not entirely useless. It was meant to help you provide us the information we need in order to debug your issue properly.
If you would have followed that template, you would have provided us a very important information, that is, the distribution you are using and the way you are trying to build opensips.

**Comment by ovidiusas** [comment]
Most likely pkg-config was not installed and proper linker flags for SSL_BUILDER were not set.

**Comment by liviuchircu** [comment]
Cheers for the bump, @ovidiusas!  A similar issue and its solution can be found in [this thread](https://github.com/OpenSIPS/opensips/issues/2088#issuecomment-619615001).
