### ISSUE TITLE
[FEATURE] Start a call from Opensips

### ISSUE THREAD

**Issue by moisesynfam** [OpenSIPS/opensips#1983]
**Is your feature request related to a problem? Please describe.**
I would like to know if it's possible to start a call via Opensips sort of like Asterisk's call files: https://wiki.asterisk.org/wiki/display/AST/Asterisk+Call+Files

**Describe the solution you'd like**

**Implementation**
 
  - Component: 
  - Type: 
  - Name: 

**Describe alternatives you've considered**

**Additional context**

**Comment by lemenkov** [comment]
No, it's not possible, you need a user agent first. Good news there are plenty of them. Take a look at @sipp just for the starters.

**Comment by moisesynfam** [comment]
I have never heard of SIPp before but I read it's a tool for testing and that's not specifically what I'm looking for. I want to find a way of automatically place calls via Opensips. My goal is to create a script or web interface where I can input a number I want to dial-out, then Opensips receives this number and my account and starts processing the call on my desk phone.

**Comment by lemenkov** [comment]
> My goal is to create a script or web interface where I can input a number I want to dial-out, then Opensips receives this number and my account and starts processing the call on my desk phone.

SIP calls from web interface can be implemented with [SIP.js](https://github.com/onsip/SIP.js) or [JsSIP](https://github.com/versatica/JsSIP).

**Comment by moisesynfam** [comment]
I know. I already do. I just want to automate a call to a desk phone.

**Comment by bogdan-iancu** [comment]
You can do this , not so nice like in Asterisk, but still you can - checks this ClikToCall script https://github.com/OpenSIPS/opensips/blob/3.0/examples/ctd.sh

**Comment by moisesynfam** [comment]
Thanks for the suggestion but running the script results in mi_fifo_server not being able to parse the first command.

` ERROR:mi_fifo:mi_fifo_server: cannot parse command: ctd_fifo_1471#012INVITE #012sip:44@192.168.2.16#012.#012.#012"From: <sip:controller@foo.bar>;tag=15829125411471#015#012Call-ID: 15829125411471.fifouacctd#015#012Contact: <sip:caller@!!>#015#012To: <sip:44@192.168.2.16>#015#012CSeq: 1 INVITE#015#012Content-Type: application/sdp#015#012"#012"v=0#015#012o=click-to-dial 0 0 IN IP4 0.0.0.0#015#012s=session#015#012c=IN IP4 0.0.0.0#015#012b=CT:1000#015#012t=0 0#015#012m=audio 9 RTP/AVP 8 0#015#012a=rtpmap:8 PCMA/8000#015#012a=rtpmap:0 PCMU/8000#015#012"`

Any idea why? I had never interacted with the fifo_server, so... a total newbie here.

**Comment by razvancrainea** [comment]
Unfortunately the click to dial script posted by @bogdan-iancu is outdated for OpenSIPS 3.0, as it relies on the old `opensipsctl` MI format. This needs to get ported to the new `opensips-cli` tool.

**Comment by moisesynfam** [comment]
And how can I port it ? can you point me in any direction? I know the new format uses JSON-RPC but I don't know port the commands from the script to JSON.

**Comment by moisesynfam** [comment]
I managed to port it using the mi_http module.

**Comment by razvancrainea** [comment]
@moisesynfam could you share your work with us, in case someone else needs it? Perhaps we can push it as an example in the source code. Thanks!

**Comment by moisesynfam** [comment]
I will, but there's a problem with my implementation. I don't know if it's an issue with the mi_http module or the Management Interface. Apparently I cannot make multiple requests at the same time but they are being queued up. Does anyone know if this can be changed?

**Comment by razvancrainea** [comment]
Unfortunately this is a limitation of the `httpd` module - only one MI request can be handled, as there's only one process handling requests.
What command are you using to trigger the call?

**Comment by moisesynfam** [comment]
I'm using the `t_uac_dlg` command. Do all the mi modules have this limitation?

**Comment by razvancrainea** [comment]
No all, mi_datagram and mi_fifo can run commands in parallel - you should give them a try if you want to make this behavior parallel.
We'll definitely give it a thought on how to enhance this behavior on all mi modules starting with the new OpenSIPS calling API in OpenSIPS 3.1.

**Comment by moisesynfam** [comment]
I managed to solve this using the mi_datagram module and a nodeJS app acting as the client/controller. 

[ctd-helper.txt](https://github.com/OpenSIPS/opensips/files/4558407/ctd-helper.txt)
