### ISSUE TITLE
[BUG]max_contacts not work in AOR mode of mid-registrar

### ISSUE THREAD

**Issue by hurrylu** [OpenSIPS/opensips#1984]
"Server": "OpenSIPS (3.0.1 (x86_64/linux))
```
```

Our scenario just allows one sip agent online, I want to use opensips as mid-reg proxy to backend FS clusters, I tried AOR working mode and set max_contacts to 1, supposed to only save the latest registering contact into table location, but seems not work,  what I missed or did wrong below?

loadmodule "mid_registrar.so"
modparam("mid_registrar", "mode", 2)
modparam("mid_registrar", "max_contacts", 1)
...
 if (is_method("REGISTER")) {
     mid_registrar_save("location");
     switch ($retcode) {
                case 1:
                        ds_select_dst(1, 4);
                        t_relay();
                        break;
                case 2:
                        break;
                default:
                        xlog("L_ERR", "failed to save registration! ($$ci=$ci)\n");
     }
 }
...

some logs here:
DBG:core:parse_msg: SIP Request:
DBG:core:parse_msg:  method:  <REGISTER>
DBG:core:parse_msg:  uri:     <sip:X.X.X.X>
DBG:core:parse_msg:  version: <SIP/2.0>
DBG:mid_registrar:mid_reg_save: saving to location...
DBG:mid_registrar:process_contacts_by_aor: AoR info: e_out=3600, lrts=1582594265...
DBG:mid_registrar:calc_contact_expires: expires: 120
DBG:mid_registrar:process_contacts_by_aor: found >> [ 120, 3600 ], e=120, e_out=3600
DBG:mid_registrar:mid_reg_ct_event: Contact callback (2): contact='sip:htcq5c52@172.16.x.x:4970;transport=ws'
DBG:mid_registrar:calc_max_ct_diff: ct - 3600 - 120 - -1
DBG:mid_registrar:calc_max_ct_diff: ct - 3600 - 120 - 3480
DBG:mid_registrar:calc_max_ct_diff: ct - 3600 - 120 - 3480
DBG:mid_registrar:calc_max_ct_diff: ct - 3600 - 120 - 3480
DBG:mid_registrar:calc_max_ct_diff: max diff: 3480
DBG:mid_registrar:process_contacts_by_aor: max diff: 3480, absorb until=1582597745, current time=1582595216
DBG:mid_registrar:build_contact: building contact ...
DBG:mid_registrar:build_contact: created Contact HF: Contact: <sip:htcq5c52@172.16.x.x:4970;transport=ws>;expires=120, <sip:qlqr2a7o@172.16.x.x:5004;transport=ws>;expires=113, <sip:53f94mp4@172.16.x.x:5012;transport=ws>;expires=3, <sip:0i57dd64@172.16.x.x:5016;transport=ws>;expires=113
DBG:mid_registrar:send_reply: contact buf: Contact: <sip:htcq5c52@172.16.x.x:4970;transport=ws>;expires=120, <sip:qlqr2a7o@172.16.x.x:5004;transport=ws>;expires=113, <sip:53f94mp4@172.16.x.x:5012;transport=ws>;expires=3, <sip:0i57dd64@172.16.x.x:5016;transport=ws>;expires=113

**Comment by liviuchircu** [comment]
Upon a first run of the tests, this seems to work:

```
SIP/2.0 503 Service Unavailable
Via: SIP/2.0/UDP 10.0.0.10:5077;received=10.0.0.10;rport=5077;branch=z9hG4bKeshlhxra
To: <sip:liviu@10.0.0.10:5060>;tag=28de.5635b9af5a877b100381b34bc86eacca
From: <sip:liviu@10.0.0.10:5060>;tag=tjtpe
Call-ID: gdwarxhlfkapghb@Holloway
CSeq: 587 REGISTER
P-Registrar-Error: Too many registered contacts
Server: OpenSIPS (3.1.0-dev (x86_64/linux))
Content-Length: 0
```

Can you provide a pcap with an example flow that is wrong, please?  You may ship it to liviu at opensips dot org if it contains sensible data.

**Comment by liviuchircu** [comment]
Ok, I understand what's happening now.  Sorry for the confusion, `max_contacts` was never a fully tested/working feature of mid-registrar until a few months ago, when we brought it up-to-date on `master` branch, along with other features (see 52eaaa0e9, a5a4bbaa0f8f, 6695b31df125, 3dec49a11d9).

However, the docs do actually mention a `max_contacts` module parameter, since they were inherited from registrar.  I'm not sure what's the best way to proceed here:

* fix the docs, so they are inline with the code
* fix the code, so it is inline with the docs

If you can run from `master` branch, the `max_contacts` feature will work.  This way, I will just clean up the `3.0` docs, so they match the code...
