### ISSUE TITLE
use mongoc_collection_command_simple memory leak

### ISSUE THREAD

**Issue by ycxwoo** [OpenSIPS/opensips#1985]
https://github.com/OpenSIPS/opensips/blob/2.4.7/modules/cachedb_mongodb/cachedb_mongodb_dbase.c

int mongo_con_raw_query(cachedb_con *con, str *qstr, cdb_raw_entry ***reply,
                        int expected_kv_no, int *reply_no)

if (!mongoc_collection_command_simple(MONGO_COLLECTION(con), &doc,
							  NULL, &rpl, &error)) {
	LM_ERR("raw query:\n'%.*s'\nfailed with: %d.%d: %s\n", qstr->len, qstr->s,
		   error.domain, error.code, error.message);
	ret = -1;
	stop_expire_timer(start, mongo_exec_threshold, "MongoDB raw query",
					  qstr->s, qstr->len, 0);
	goto out_err;
}

&doc   &rpl  need free memory

**Comment by liviuchircu** [comment]
Thank you for the report, @ycxwoo - confirming the issue, as a similar handling in `mongo_con_add()` actually ends up with a series of `bson_destroy()` operations.  Expect a fix soon!
