### ISSUE TITLE
[BUG] XML module can not acces element with a colon

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#1988]
Hi,

I'm having an issue with accessing XML elements with a colon in the name. I can access id attribute of device, but nothing below the gp:geopriv: 

```
--ssboundary-1_
Content-Type: application/pidf+xml
Content-ID: <+12345678@123.12.12.23>

<?xml version="1.0" encoding="UTF-8"?>
<presence xmlns="urn:ietf:params:xml:ns:pidf" xmlns:gp="urn:ietf:params:xml:ns:pidf:geopriv10" entity="pres:+12345678@123.12.12.23">
<device id="Test123">
<status>
<gp:geopriv>
<gp:location-info>
<gml:location>
<gml:Point srsName="urn:ogc:def:crs:EPSG::4258" xmlns:gml="http://www.opengis.net/gml">
<gml:pos>47.871 8.561</gml:pos>
</gml:Point>
</gml:location>
</gp:location-info>
<gp:usage-rules>
<gp:retransmission-allowed>no</gp:retransmission-allowed>
<gp:retention-expiry />
</gp:usage-rules>
</gp:geopriv>
</status>
<timestamp>2018-2-09T15:47:11Z</timestamp>
</device>
</presence>

--ssboundary-1_
```

    $xml(geolocation) = $rb(application/pidf+xml);

    xlog("XML: $xml(geolocation/presence/device/status/gp:geopriv/gp:location-info/gml:location/gml:Point/gml:pos.val)\n");
    xlog("XML: $xml(geolocation/presence/device/status/gp:geopriv/gp:location-info/gml:location/gml:Point.attr/srsName)\n");
    xlog("XML: $xml(geolocation/presence/device.attr/id)\n");
    xlog("XML: $xml(geolocation/presence.attr/entity)\n");

Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: DBG:core:pv_get_msg_body: --------mime is <196613>, idx=0
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: DBG:xml:get_node_by_path: Invalid path for xml var - no element named: <gp:geopriv>
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: DBG:xml:pv_get_xml: Element not found
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: XML: <null>
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: DBG:xml:get_node_by_path: Invalid path for xml var - no element named: <gp:geopriv>
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: DBG:xml:pv_get_xml: Element not found
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: XML: <null>
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: XML: Test123
Mar  3 14:38:16 dus-appsrvtest01 /usr/sbin/opensips[3964]: XML: pres:+12345678@123.12.12.23

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0

**Comment by xaled1** [comment]
Hi,
don't want to bug you ;) but do you have any news about the issue?

**Comment by xaled1** [comment]
Hi,
I added some debug Info
`static xmlNode *get_node_by_path(xmlNode *root, xml_element_t *path_el)
{
        xmlNode *cur;
        str n_name;
        int i;

        cur = root;
        while (path_el) {
                i = 0;
                while (cur) {
                        n_name.s = (char *)cur->name;
                        n_name.len = strlen(n_name.s);
                        LM_DBG("XML DEBUG: name: %s element: <%.*s> \n",
                                        n_name.s, path_el->tag.len, path_el->tag.s);
`
And see that the n_name.s in case of gp:geopriv gets truncated to just geopriv loosing gp: :

Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: presence element: <presence>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: text element: <device>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: device element: <device>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: text element: <status>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: status element: <status>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: text element: <gp:geopriv>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: XML DEBUG: name: geopriv element: <gp:geopriv>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:get_node_by_path: Invalid path for xml var - no element named: <gp:geopriv>
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: DBG:xml:pv_get_xml: Element not found
Mar  9 13:17:13 acct-test /usr/local/sbin/opensips[12114]: XML: <null>

**Comment by rvlad-patrascu** [comment]
Hi @xaled1 ,

Indeed the part of the node name before the colon is just the namespace prefix and is not taken into account when identifying the node by the `$xml` variable. I wouldn't say this is a bug (maybe a limitation in case there are conflicting names for nodes), as for example in your case you can simply discard the `gp:` or `gml:' prefixes.

**Comment by xaled1** [comment]
Hm, 
well, I did get further but the change from gp: to gml messes things up:

`xlog("XML: $xml(geolocation/presence/device/status/geopriv/location-info/location/Point/pos.val)\n");
    xlog("XML: $xml(geolocation/presence/device/status/geopriv/location-info/location/Point.attr/srsName)\n");
`

`Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: presence element: <presence>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG3: name: presence element: <device>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: text element: <device>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: device element: <device>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG3: name: device element: <status>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: text element: <status>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: status element: <status>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG3: name: status element: <geopriv>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: text element: <geopriv>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: geopriv element: <geopriv>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG3: name: geopriv element: <location-info>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: text element: <location-info>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: location-info element: <location-inf
o>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG3: name: location-info element: <location>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: text element: <location>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: XML DEBUG1: name: gml:location element: <location>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:get_node_by_path: Invalid path for xml var - no element named: <location
>
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: DBG:xml:pv_get_xml: Element not found
Mar  9 14:05:34 acct-test /usr/local/sbin/opensips[19454]: XML: <null>
`

**Comment by rvlad-patrascu** [comment]
Hello,
Testing this for myself, I see that the XML you're trying to parse is technically not valid, since the `gml` namespace is declared in the `Point` node, but is actually used before that, in the `location` node. Nevertheless, `libxml2` (which OpenSIPS uses for parsing) throws an error but still continues to parse the document, with the mention that `gml:` is no longer seen as a namespace prefix, but part of the `location` node name itself. As such, you can access paths with such nodes as following:

`xlog("XML: $xml(geolocation/presence/device/status/geopriv/location-info/gml:location/Point/pos.val)\n");`
