### ISSUE TITLE
[BUG] Generated opensips config doesn't work with opensip-cli

### ISSUE THREAD

**Issue by anexiole** [OpenSIPS/opensips#1989]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
```

**Describe the bug**

Generated opensips config doesn't work with opensip-cli (ie. run "opensip-cli -f <path to cfg file>").
To generate the config, I used 'make menuconfig' , which is the preferred way of generating an opensips config based on your ver 3.0 documentation

### 2 issues:

1.  Missing out on "[section]" tag in the stock generated config

1.  I added the "[section]" tag and the error of "File contains no section headers." dissappears but comes up with another error, DuplicateOptionError. This is because I have 2 aliases defined in the opensips.cfg file. This is because opensips-cli which uses python 3's configparser doens't allow for duplication option values. 

**To Reproduce**

1. install opensips 3.0
2. run "make menuconfig"
3. Generate any conf file. In my case, a residential file.
4. Install opensips-cli . Run "opensips -f  <path to the config file>"
5. Error is thrown as below:

> ✘ ⚡ root@localhost  /opt/opensips  ➦ 6a49622 ● opensips-cli -f etc/opensips_residential_2020-3-4_13:11:2.cfg
> Traceback (most recent call last):
> File "/usr/local/bin/opensips-cli", line 4, in
> import('pkg_resources').run_script('opensipscli==0.1.0', 'opensips-cli')
> File "/usr/lib/python3.6/site-packages/pkg_resources/init.py", line 654, in run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python3.6/site-packages/pkg_resources/init.py", line 1434, in run_script
> exec(code, namespace, namespace)
> File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/EGG-INFO/scripts/opensips-cli", line 9, in
> run_console()
> File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/EGG-INFO/scripts/opensips-cli", line 6, in run_console
> main.main()
> File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/main.py", line 77, in main
> shell = cli.OpenSIPSCLIShell(args)
> File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/cli.py", line 69, in init
> cfg.parse(cfg_file)
> File "/usr/local/lib/python3.6/site-packages/opensipscli-0.1.0-py3.6.egg/opensipscli/config.py", line 41, in parse
> self.config.read(in_file)
> File "/usr/lib64/python3.6/configparser.py", line 697, in read
> self._read(fp, filename)
> File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
> raise MissingSectionHeaderError(fpname, lineno, line)
> configparser.MissingSectionHeaderError: File contains no section headers.
> file: 'etc/opensips_residential_2020-3-4_13:11:2.cfg', line: 18
> 'log_level=3\n'
> ✘ ⚡ root@localhost  /opt/opensips  ➦ 6a49622 ● 

**Expected behavior**

1) Add the [section] tag at the top when new configs are generated 

[](https://docs.python.org/3.2/library/configparser.html )says

"A configuration file consists of sections, each led by a [section] header, followed by key/value entries"

2) Config elements (ie. aliases) which have several values are to be accepted. As to whether you will need to refactor the code's data structure/type, that's an implementation decision as that affects the opensips backend

**OS/environment information**
 - Operating System: Centos 7

**Comment by razvancrainea** [comment]
`opensips` and `opensips-cli` are two different tools that do different stuff. The first one is a SIP server, whereas the second one is a tool to control `opensips`.
OpenSIPS uses its own configuration file, in a C-like format. This is the script generated by `make menuconfig`. You can find more information [here](https://www.opensips.org/Documentation/Configure-File-3-1).
OpenSIPS CLI uses an ini-like script file, which contains different sections with key-value pairs. More information [here](https://github.com/OpenSIPS/opensips-cli#configuration).
You can't use the config generated for `opensips` in `opensips-cli`.
