### ISSUE TITLE
[BUG] remove_body_part() and Double Content-Length

### ISSUE THREAD

**Issue by pateldp** [OpenSIPS/opensips#1990]
**OpenSIPS version you are running**

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: edef893c5
main.c compiled on 23:26:34 Dec 14 2019 with gcc 4.8.5

**Describe the bug**
I want to remove the body part of request. So I used following statement
       remove_body_part("application/vnd.etsi.pstn+xml");
Successfully removed the body part but add two Content-Length Header instead of 1.

Please Refer Following Packets

Received Packet
------------------------------------------------------------

SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.185.122.222:5070;branch=z9hG4bK4e66.c51cdfd7.0
Call-ID: ZGJiODQ1ZDBhM2MwNzQxYThkMzNjNDNkYWI4OWVkODY.
From: <sip:101@ims.provider.in>;tag=aa622817
To: <sip:+91XXXXXXXXX@ims.provider.in>;tag=ab8bowab
CSeq: 2 INVITE
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,REGISTER,INFO,PRACK,SUBSCRIBE,NOTIFY,UPDATE,MESSAGE,REFER
Contact: <sip:10.232.130.170:5060;Dpt=81c8-400;Hpt=8ec2_16;CxtId=3;TRC=ffffffff-ffffffff>
Require: timer
Session-Expires: 1800;refresher=uac
P-Charging-Vector: icid-value="ibcf0.c9.e20af45c.4b98c3fb";orig-ioi=SIP_982312_AAACLOUD_XXXXXXXXX;term-ioi=scscf0.ims.provider.in
Content-Length: 753
Content-Type: multipart/mixed;boundary=ssboundary-1_

--ssboundary-1_
Content-Length: 316
Content-Type: application/vnd.etsi.pstn+xml
Content-Disposition: signal;handling=optional

<?xml version="1.0" encoding="UTF-8"?>
<PSTN>
  <ProgressIndicator>
    <ProgressOctet3>
      <CodingStandard>00</CodingStandard>
      <Location>0001</Location>
    </ProgressOctet3>
    <ProgressOctet4>
      <ProgressDescription>0000010</ProgressDescription>
    </ProgressOctet4>
  </ProgressIndicator>
</PSTN>

--ssboundary-1_
Content-Length: 211
Content-Type: application/sdp

v=0
o=- 458210061 458210061 IN IP4 10.232.130.180
s=SBC call
c=IN IP4 10.232.130.180
t=0 0
m=audio 58644 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=fmtp:101 0-15

--ssboundary-1_--

Sent Packet
------------------------------------------------------------

SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.102:55160;received=XXX.XX.XX.ZZ;rport=55160;branch=z9hG4bK-d8754z-88304e9bb9f13e04-1---d8754z-
Call-ID: ZGJiODQ1ZDBhM2MwNzQxYThkMzNjNDNkYWI4OWVkODY.
From: <sip:101@wpi.sipserver.in;transport=UDP>;tag=aa622817
To: <sip:01143792000@wpi.sipserver.in;transport=UDP>;tag=ab8bowab
CSeq: 2 INVITE
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,REGISTER,INFO,PRACK,SUBSCRIBE,NOTIFY,UPDATE,MESSAGE,REFER
Contact: <sip:XXX.XX.XX.ZZ:5070;did=0b6.cd83b401>
Require: timer
Session-Expires: 1800;refresher=uac
P-Charging-Vector: icid-value="ibcf0.c9.e20af45c.4b98c3fb";orig-ioi=SIP_982312_AAACLOUD_1204037500;term-ioi=scscf0.ims.provider.in
**Content-Length: 235
Content-Length: 211**
Content-Type: application/sdp

v=0
o=- 458210061 458210061 IN IP4 10.232.130.180
s=SBC call
c=IN IP4 XXX.XX.XX.ZZ
t=0 0
m=audio 17772 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:17773
a=ptime:20

**To Reproduce**

1. Just try to remove body part using above exported function for the packet which have multiple bodies.

**Expected behavior**

Expected Remove the body part and put only one Content-Length header

**Relevant System Logs**

**OS/environment information**
 - CentOS Linux release 7.6.1810 (Core)
 - Manual Packages

**Additional context**

I think the multipart Content-Type is not supported.
Content-Type: **multipart/mixed;boundary=ssboundary-1_**

**Comment by pateldp** [comment]
Hello Team,  could you please look into it?

**Comment by bogdan-iancu** [comment]
@pateldp , thank you for your report. Could you please confirm the above fix (it should be backportable to 2.4)

**Comment by pateldp** [comment]
Hello @bogdan-iancu 

Thanks, It is fixed.
