### ISSUE TITLE
[BUG] Topology Hiding not encode CallID + Wrong NOTIFY Routing

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#1991]
Hello

I am using opensips 2.4.7 git revision: c3d04de on Centos 7 OS, with topology hiding module.

On the same machine I have installed Asterisk 16 and RTPEngine 6.5
Both OpenSIPs and Asterisk are using the same Interface to bind their SIP Services with Public IP.
OpenSIPs is listening on 5060 UDP and 5061 TLS and Asterisk is listening on 5090 UDP.
Asterisk also has few SIP Registrations to an upstream carrier.

So the call flow is the following:

Inbound Call
Carrier (UDP:5060) -> (UDP:5090) Asterisk (UDP) -> (UDP:5060) OpenSIPs (TLS) -> (TLS:5061) Customer

Outbound Call
Customer (TLS) -> (TLS:5061) OpenSIPs (UDP) -> (UDP:5060) Asterisk (UDP) -> (UDP:5060) Carrier

I have the following situation.

On Outbound Calls (From Customer to OpenSIPs and then to Asterisk) the topology_hiding("C") does encode the CallID.

On Inbound Calls (From Carrier to Asterisk and then to OpenSIPs) the topology_hiding("C") does not encode the CallID.

Moreover, I found an issue for handling in-dialog NOTIFY messages. In case of REFER, which is passed to Asterisk, and following the 202 messages, a NOTIFY is generated from Asterisk with TO/FORM tags are reversed. At topology_hiding_match, I get a warning that "tight matching failed for NOTIFY", but even if matched, the NOTIFY is routed to contact address instead of Route Header of the original REFER message. Is there a way to overcome that?

Finally, I am not able to add any Route Header to INVITE packets after topology_hiding which is required from Customer's SBC for some reason. Is there a way to do that?

Sample Packets for CallID Issue.

INVITE from Asterisk to OpenSIPs

INVITE sip:+30111111111@1.1.1.1:5060;user=phone SIP/2.0
Via: SIP/2.0/UDP 1.1.1.1:5090;branch=z9hG4bK56a37379
Max-Forwards: 69
From: <sip:222222222@1.1.1.1:5090>;tag=as528b78ed
To: <sip:+3111111111@1.1.1.1:5060;user=phone>
Contact: <sip:222222222@1.1.1.1:5090>
Call-ID: 1c68f9341e46a94c7e69e20969952784@1.1.1.1:5090

INVITE from OpenSIPs to Customer SBC

INVITE sip:+30111111111@2.2.2.2 SIP/2.0
Via: SIP/2.0/TLS example.com:5061;branch=z9hG4bKc52c.da65cc93.0
Max-Forwards: 69
From: <sip:222222222@example.com>;tag=as528b78ed
To: <sip:+30111111111@example.com>
Contact: <sip:example.com:5061;transport=tls;did=c83.ab68bdb1>
Call-ID: 1c68f9341e46a94c7e69e20969952784@1.1.1.1:5090

Thank you for your support

**Comment by razvancrainea** [comment]
Hi, Antonis!

Are you sure you're calling topology_hiding() with the "C" parameter everywhere in your script, and you're not hitting a code where "C" is not used? Can you provide some debug logs from the case where the CallID does not get changed?

Regarding the NOTIFY, issue, if you're using topology hiding and the NOTIFY is indialog, then it should not have any Route headers. And it should go to the client - is this not happening? Could you share a pcap with the call + NOTIFY?

Best regards,
Răzvan

**Comment by apsaras** [comment]
Yes I very sure. Topology Hiding is called only once at the first Invite and the code is common for both directions. What debug level is required? 6?

As this is a TLS communication, I am using hep to capture it, and due to the fact that NOTIFY is not matched, homer does not show it. From what I understand, NOTIFY is routed to Contact Header URI instead of Record Route which in my case are different. Moreover, Record Route is defined at REFER message and not passed to Asterisk, hence NOTIFY does not have that information.

I can give you access the server in case you need it as it is in Lab environment.

**Comment by razvancrainea** [comment]
Hi, Antonis!

Yes, debug level 6 is required. So you're talking about the Callid that you see in Homer, that's the one that is not properly changed? Because if that's the case, that might be a problem related to the fact OpenSIPS builds the HEP package, not taking into account the changed callid. But in that case the request forwarded to your customer does have the masquerated Callid.

No need of server access now, just a pcap with the call should be OK to start. But I am not sure I follow the reason why the REFER and NOTIFYs have any Route or Record-Route headers - when running in topology hiding, those headers should not be present. Anyway, sending a PCAP would clarify things.

Best regards,
Răzvan

**Comment by apsaras** [comment]
Hello Razvan

Yes that is true. I can see the CallID masqueraded when call goes from Customer to Asterisk, so homer should trace it correct. moreover, the packet has all other info hidden (contact, removed record route etc)

Here is the pcap.

[HOMER5-3_5_2020 20_51_11.zip](https://github.com/OpenSIPS/opensips/files/4294587/HOMER5-3_5_2020.20_51_11.zip)

In that case NOTIFY was routed back to the initial peer and not to contact uri which seems correct, but I do not get any OK back from that peer. Should it be routed to the peer sent the REFER?

I am not able to reproduce the tight matching warning now which is strange. I will keep trying.

regards

**Comment by apsaras** [comment]
I manage to reproduce the issue with NOTIFY. This is happening when Customer dials out and ask for transfer (Outbound Call)

That is the log file

[opensips.txt](https://github.com/OpenSIPS/opensips/files/4294646/opensips.txt)

And that is the pcap

[HOMER53_5_2020 21_0_57.zip](https://github.com/OpenSIPS/opensips/files/4294701/HOMER53_5_2020.21_0_57.zip)

**Comment by apsaras** [comment]
Hello Razvan.

Is there a way to print out full sip message before leaving to interface? I want to make sure that the messages logged by homer are after full message manipulation and having TLS needs to be done via the script.

**Comment by razvancrainea** [comment]
Hi, Antonis!

The log you sent contains different calls than the one in the homer capture, therefore I can't correlate them.
In order to track the SIP messages leaving interface, best you can do is to use wireshark. You can follow [this tutorial](https://www.opensips.org/Documentation/Tutorials-TLS-2-2#toc13) for more information.

Best regards,
Răzvan

**Comment by apsaras** [comment]
Confirm that the issue with CallID is a hep issue. I found a similar ticket on git for that.

Regarding NOTIFY I will send you new Log file with trace. It seems to have different behavior based on direction so I will send both examples.

**Comment by apsaras** [comment]
Call from Customer -> OpenSIPs -> Asterisk -> Carrier.
Customer initiate Transfer 
Customer REFER -> OpenSIPs -> Asterisk
Asterisk 202 -> OpenSIPs -> Customer
Asterisk NOTIFY -> OpenSIPs (tight matching failed for NOTIFY)


[Trace_Log.zip](https://github.com/OpenSIPS/opensips/files/4306456/Trace_Log.zip)

**Comment by apsaras** [comment]
Hello.

I would like to re-open that ticket.

Attached is a similar case. NOTIFY after REFER does not get matched by dialog matching.

Here is the error

 WARNING:dialog:dlg_onroute: tight matching failed for NOTIFY with callid='Exelysis_TEAMS_VExVWkhAW0ZGVFNeRldIV1xIQllLNFxQQ0FUT0tdTEZHREY-'/63, ftag='as26dabb6a'/10, ttag='1c950551048'/11 and direction=0

WARNING:dialog:dlg_onroute: dialog identification elements are callid='140613252123520201108@91.217.155.72'/35, caller tag='1c950551048'/11, callee tag='as26dabb6a'/10

here is the trace (pass: opensips)


[NOTIFY-trace.zip](https://github.com/OpenSIPS/opensips/files/4671655/NOTIFY-trace.zip)

**Comment by nikbyte** [comment]
We're expecting the same issue.

**Comment by nikbyte** [comment]
@bogdan-iancu @razvancrainea 

I debugged this. It fails on dlg_th_callid_pre_parse().
The reason is MSG_SKIP_BITMASK.

I removed METHOD_NOTIFY from there and it's fixed now.

METHOD_NOTIFY can be in-dialog, that's why they must be out of this list.

**Comment by bogdan-iancu** [comment]
@nikbyte , thanks for the heads-up here and for the fix. Not sure if @apsaras will still be able to test, but I will shortly push the fix for this, it makes all the sense in the world.

**Comment by apsaras** [comment]
I will need some time to fire up a lab env to test it. Thank you @nikbyte and @bogdan-iancu  for your support.
