### ISSUE TITLE
[BUG] Unable to run opensips 3 using systemd (systemctl) on Debian Buster

### ISSUE THREAD

**Issue by sanbikinosaru** [OpenSIPS/opensips#1994]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**

Opensips3 failed to run on Debian buster using systemctl start/restart opensips

**To Reproduce**
1. Install opensips via apt-get install (as seen in youtube video for Debian Buster.) https://www.youtube.com/watch?v=P5Q25aAHj1c

2. Edit the necessary files.
3, systemctl start opensips

**Expected behavior**

**Relevant System Logs**

ERROR:core:parse_opensips_cfg: loading config file /etc/opensips/opensips.cfg: Permission denied
ERROR:core:main: failed to parse config file /etc/opensips/opensips.cfg

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-5-amd64
      Architecture: x86-64

**Additional context**

**Comment by liviuchircu** [comment]
I just installed a fresh Debian 10 VM and did the following:

```
apt update 
apt install gnupg
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
echo "deb https://apt.opensips.org buster 3.0-nightly" >/etc/apt/sources.list.d/opensips.list
apt update
apt install opensips
systemctl start opensips
systemctl status opensips
systemctl stop opensips
apt remove --purge opensips
systemctl daemon-reload
echo "deb https://apt.opensips.org buster 3.0-releases" >/etc/apt/sources.list.d/opensips.list
apt update
apt install opensips
systemctl status opensips
systemctl start opensips
systemctl status opensips
```

Both the `3.0` `nightly` and `releases` repositories worked well, with no errors.  If you can still reliably reproduce this, please re-open, along with the necessary steps.  Closing for now.
