### ISSUE TITLE
[FEATURE] Opensips+rtpengine as an end point playing music for caller

### ISSUE THREAD

**Issue by bshirazi** [OpenSIPS/opensips#1996]
**Is your feature request related to a problem? Please describe.**

With rtpengine_play_media function added in 3.1 it is possible to play media to one of the endpoints , but I like to use Opensips+rtpengine as an end point playing music for caller.
**Describe the solution you'd like**

 Opensips+rtpengine as an end point playing music for caller
**Implementation**
 
  - Component: 
  - Type: 
  - Name: 

As discussed in mailing list ,Razvan comments  may be "make sens in the scope of the Calling API feature that we are planning to devel for 3.1".

**Describe alternatives you've considered**

I see some efforts in mailing list trying to build/generate a 183 response inside script to simulate a dummy end point and then use rtpengine_play_media function.

Regards
M.Shirazi

**Comment by bshirazi** [comment]
Hi
I tried this method used with similar function(rtpproxy_stream2uac() of rtpproxy) with rtpengine without success:
[http://lists.opensips.org/pipermail/users/2016-January/033323.html](url)

Regards
M.Shirazi

**Comment by bshirazi** [comment]
Hi @razvancrainea 
Regarding recent discussion [here ](https://github.com/sipwise/rtpengine/issues/870)
it seems there is a workaround to play media with Opensips+rtpengine when there is no B party but I do not have enough knowledge to do it. Would you please take a look and advice me ?

Regards
Shirazi

**Comment by babarShahzad** [comment]
Hi @razvancrainea @bshirazi i am also looking for the same solution "when there is no bParty and play prompt to aParty and get dtmf" but i am unable to achieve this with Kamailio+RtpEngine.
any help or sample config would be appreciated.

**Comment by razvancrainea** [comment]
Unfortunately I didn't have much time to look into this, and tbh I've never done it. As soon as I clear my schedule a bit, I will give it a try to see if there's anything missing.

**Comment by babarShahzad** [comment]
> 
> 
> Unfortunately I didn't have much time to look into this, and tbh I've never done it. As soon as I clear my schedule a bit, I will give it a try to see if there's anything missing.

thanks i will be waiting for your response

**Comment by razvancrainea** [comment]
I've just tried a small snippet of code, and started playing back the message to the caller. Here's the snippet I used:
```
route[early_media] {
    rtpengine_offer();
    append_to_reply("Content-Type: application/sdp\r\n");
    $var(body) = $(rb{re.subst,/(IP4.).*/\1127.0.0.1/g}); # replace the IP in the body
    t_reply_with_body(183, "Session Progress", $var(body));
    rtpengine_play_media("totag=$ft file=/music-on-hold.wav");
}
```
I called this route on an initial INVITE.
In the meantime I will close this ticket, as there doesn't seem to be any issues with the code. If you need further details, let us use the opensips [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)

**Comment by truong-hua** [comment]
> I've just tried a small snippet of code, and started playing back the message to the caller. Here's the snippet I used:
> 
> ```
> route[early_media] {
>     rtpengine_offer();
>     append_to_reply("Content-Type: application/sdp\r\n");
>     $var(body) = $(rb{re.subst,/(IP4.).*/\1127.0.0.1/g}); # replace the IP in the body
>     t_reply_with_body(183, "Session Progress", $var(body));
>     rtpengine_play_media("totag=$ft file=/music-on-hold.wav");
> }
> ```
> 
> I called this route on an initial INVITE. In the meantime I will close this ticket, as there doesn't seem to be any issues with the code. If you need further details, let us use the opensips [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)

@razvancrainea I tried this solution and seem like it does not work with NAT. rtpengine did send rtp audio packets to the media port received in INVITE message. Do you have any solution for this?

**Comment by ot-i-to** [comment]
working example [https://sysinfo.pro/e/ru/VoIP/OpenSIPs/os_rtpengine_nat](https://github.com/sipwise/rtpengine/issues/url)
