### ISSUE TITLE
[FEATURE]the Pseudo Variables $fn and $fU support r/w

### ISSUE THREAD

**Issue by zhouboyong** [OpenSIPS/opensips#2032]
for now, the Pseudo Variables $fn and $fU is only read-only, in some cases, we need change the $fn and $fU multi times in a same transaction, for case load balance module on failure select next GW, some GWs need the request send the assigned fn and fU, so we wished the $fn and $fU can support read-write

**Comment by bogdan-iancu** [comment]
You can still use the uac_replace_from(), but of course, on time per branch/destination, so simply call the function from the branch_route. Keep the new FROM Username / Display into some AVPs until you get to the branch_route.
