### ISSUE TITLE
[FEATURE] CGRateS Module - Add support for array params

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2034]
**Is your feature request related to a problem? Please describe.**
When trying to use CGRateS Module I found out that all cgr_opt variables are treated like strings which was correct until the latest CGRateS version.
In CGRateS, AttributeIDs is an array and Opensips sent this out to cgrates as a string just like all the other variables.

```
$cgr_opt(GetAttributes) = 1;
$cgr_opt(Tenant) = "global_dids";
$cgr_opt(AttributeIDs) = $avp(didnumber)
async(cgrates_cmd("SessionSv1.AuthorizeEventWithDigest"), CHECK_DID_IN_CGRATES_REPLY);
```
**opensips Output:**
```
{
    "method": "SessionSv1.AuthorizeEventWithDigest",
    "id": 215739551,
    "params": [
        {
            "AttributeIDs": "[+302122228003]",
            "Tenant": "global_dids",
            "GetAttributes": true,
            "Event": {}
        }
    ]
}
```

**Describe the solution you'd like**
```
{
    "method": "SessionSv1.AuthorizeEventWithDigest",
    "id": 215739551,
    "params": [
        {
            "AttributeIDs": ["+302122228003"],   <---------
            "Tenant": "global_dids",
            "GetAttributes": true,
            "Event": {}
        }
    ]
}
```
I have tested this with CGRateS v.0.10 and Opensips 3.0.x-latest

Thank you in advance
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
@vtzan in order to implement this, I need to differentiate which values opensips should treat like arrays, and which as strings. Not sure how to do that, the only way I can think of is to specify an index when providing the value, something like:
```
$(cgr_opt(AttributeIDs)[0]) = "+302122228003"; # this will translate to ["+302122228003"]
```

**Comment by vtzan** [comment]
@razvancrainea I think this is the best approach so whatever variable CGRateS adds in the feature it should work out of the box.
Thank you

**Comment by vtzan** [comment]
Just a kindly reminder to keep this feature in the queue ;-)
thank you in advance for your support

Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Just pushed a commit for this - basically you will be able to push whatever json you want in a field using the `:=` operator. Please give it a try and if it works as expected, close the ticket.

**Comment by vtzan** [comment]
Dear @razvancrainea,

Sorry for the late reply on this. I needed some time to migrate to 3.2!
Its working Great!!!

Thank you very much 

Best Regards
Vasilios Tzanoudakis
