### ISSUE TITLE
[BUG]. Potentional CRASH of program in B2B scenario.

### ISSUE THREAD

**Issue by arttemk** [OpenSIPS/opensips#2048]
OpenSIPS version 2.4. (and others)

******
Potentional CRASH of program in B2B scenario.
******
code line
https://github.com/OpenSIPS/opensips/blob/590a19f11a7afa3fb4d60792be6886fd59183558/modules/b2b_logic/logic.c#L1721

In this place peer may be NULL, so it will be generate crash report.

file:
modules/b2b_logic/logic.c
method: 
b2b_logic_notify_request
line
peer->sdp_type = body->len ? B2BL_SDP_NORMAL : B2BL_SDP_LATE;
.

**To Reproduce**
in case if B2b on refer, leg A a send 2 REQUEST REFER.

Active B2B
then one leg
send REFER and after another REFER from this peer in one time.
may be other way, i realy don't know. 

not critical. 
just reproduce in client that send 2 REFER at one time

**Comment by razvancrainea** [comment]
Could you please indicate if the second REFER is a re-transmission, or a second REFER request?

**Comment by arttemk** [comment]
Could you please indicate if the second REFER is a re-transmission, or a second REFER request?

In my synthetic test it's NEW REFER

but in some case  i see when  re-transmission crash also similarly 
i put some comments in source like this

+                       if (peer == 0)
+                       {
+                               LM_ERR("PEER IS NULL skip\n");
+                               goto error;
+                       }
                        peer->sdp_type = body->len ? B2BL_SDP_NORMAL : B2BL_SDP_LATE;
and sometimes i see this in log, i suppose (i'm not sure :))  it's happens when other side doesn't response.
