### ISSUE TITLE
[BUG] Script stuck when doing Parallel asynchronous operations

### ISSUE THREAD

**Issue by tijmenNL** [OpenSIPS/opensips#2049]
**OpenSIPS version you are running**
```
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d8c15f8a3
main.c compiled on  with gcc 8
```

**Describe the bug**
The script does not continue after launch(exec()) is called

**To Reproduce**
xlog("L_INFO", "Before\n");
launch(exec('ls'));
xlog("L_INFO", "After\n");

**Expected behavior**
Continue with the script and display "After"

**Relevant System Logs**
-

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `manual package`

**Additional context**
-

**Comment by bogdan-iancu** [comment]
Good catch @tijmenNL , thank you !

**Comment by adigeo** [comment]
This indeed fixes the problem. 

However the optional route is not entered at the end of the script execution. 

For example result_route is not executed:

launch(exec('script'), result_route);
...

route[result_route] {
    xlog("L_INFO", "Script finished")
}

**Comment by bogdan-iancu** [comment]
let me test it

**Comment by bogdan-iancu** [comment]
OK, you came across an undocumented behavior - if there is no output variable set (in the exec function), OpenSIPS considers that you do not need the output and it will not wait for it. As there is no waiting for later data, there is no resuming (no FD to wait and resume on).
To get the route, just do:
`launch( exec('ls -la', , $var(out)), resume);`

**Comment by bogdan-iancu** [comment]
Docs improved to describe this behavior, closing here
