### ISSUE TITLE
[BUG] 100% cpu after exec opensipsctl fifo get_statistics all

### ISSUE THREAD

**Issue by wangduanduan** [OpenSIPS/opensips#2051]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:16:22 Sep  5 2019 with gcc 4.4.7
```

**Describe the bug**

I use crontab exec `opensipsctl fifo get_statistics all` every minute,  and some opensips process  will use cpu high 100%。after i remove the crontab job。opensips process still use 100% cpu。

in the /var/log/messages, many log like 

```
WARNING:core:timer_ticker: timer task <nh-timer> already scheduled for 408598810 ms (now 408599800
ms), it may overlap..
```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Can you run the `opensipsctl trap` command and send us the content of the resulted file?
