### ISSUE TITLE
[CRASH] Program terminated with signal SIGSEGV

### ISSUE THREAD

**Issue by MarcoHierl** [OpenSIPS/opensips#2052]
**OpenSIPS version you are running**

version: opensips 2.4.3 (x86_64/linux)
flags: STATS: On, SHM_EXTRA_STATS, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6d1eda3ed
main.c compiled on 10:11:35 Dec 17 2018 with gcc 6.3.0
```
```

**Crash Core Dump**
can be send if necessary

**Relevant System Logs**
Mar 17 12:12:13 sbc-welt-hh /usr/opensips/akt/sbin/opensips[13578]: INFO:core:handle_sigs: child process 13648 exited by a signal 11
Mar 17 12:12:13 sbc-welt-hh /usr/opensips/akt/sbin/opensips[13578]: INFO:core:handle_sigs: core was generated
Mar 17 12:12:13 sbc-welt-hh /usr/opensips/akt/sbin/opensips[13578]: INFO:core:handle_sigs: terminating due to SIGCHLD

**OS/environment information**
 - Operating System: Debian GNU/Linux 9

**Additional context**
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/opensips/akt/sbin/opensips...done.
[New LWP 13648]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/opensips/akt/sbin/opensips -P /var/run/opensips/opensips.pid -f /usr/opens'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8d5502e431 in update_cloned_msg_from_msg (c_msg=0x7f8d57e3d2f8, msg=0x7f8d679713f8) at sip_msg.c:1218
1218                            CLONE_LUMP_LIST( p, &(c_msg->add_rm), msg->add_rm);
(gdb) bt full
#0  0x00007f8d5502e431 in update_cloned_msg_from_msg (c_msg=0x7f8d57e3d2f8, msg=0x7f8d679713f8) at sip_msg.c:1218
        lump_tmp = 0x0
        l = 0x7f8d6796e898
        lump_anchor2 = 0x7f8d57daa4b0
        a = 0x28
        copy_mask = 0 '\000'
        l1_len = 648
        l2_len = 0
        l3_len = 0
        p = 0x7f8d57daa4c8 ";received=xx.xxx.xx.xxx;rport=5168;branch=z9hG4bKK1gjmFZ0pH2Ne\r\nFrom: \"+496xxxxx617469\" <sip:+496xxxxx617469@ic1lfire>;tag=KBrgr0p3H51Fj\r\nTo: <sip:+493741470170@aa.aaa.aaa.aa:5060>;tag=0UUHS0000030000"...
        add_rm_aux = 0x0
        body_lumps_aux = 0x0
        reply_lump_aux = 0x0
        body_bk = 0x0
        __FUNCTION__ = "update_cloned_msg_from_msg"
#1  0x00007f8d54ff8895 in do_t_cleanup (foo=0x7f8d679713f8, bar=0x0) at tm.c:778
        t = 0x7f8d599a97c8
#2  0x000056235b421a2c in exec_post_cb (msg=0x7f8d679713f8, cb=0x7f8d66e20360) at script_cb.c:180
No locals.
#3  0x000056235b421ab0 in exec_post_req_cb (msg=0x7f8d679713f8) at script_cb.c:198
No locals.
#4  0x000056235b433446 in receive_msg (
    buf=0x56235b81fce0 <buf> "INVITE sip:+49199D161197000002192@10.249.152.9 SIP/2.0\r\nVia: SIP/2.0/UDP 10.249.152.33:5060;branch=z9hG4bK7a57397e\r\nMax-Forwards: 36\r\nFrom: <sip:+35nnnnn44696@next-id.de>;tag=as6ba06c96\r\nTo: <sip:+491"..., len=1049, rcv_info=0x7ffed0635ef0, existing_context=0x0, flags=0) at receive.c:214
        ctx = 0x7f8d6796a720
        msg = 0x7f8d679713f8
        start = {tv_sec = 140245024690452, tv_usec = 140732394593920}
        rc = 3
        tmp = 0x0
        in_buff = {
          s = 0x56235b81fce0 <buf> "INVITE sip:+49199D161197000002192@10.249.152.9 SIP/2.0\r\nVia: SIP/2.0/UDP 10.249.152.33:5060;branch=z9hG4bK7a57397e\r\nMax-Forwards: 36\r\nFrom: <sip:+35nnnnn44696@next-id.de>;tag=as6ba06c96\r\nTo: <sip:+491"..., len = 1049}
        __FUNCTION__ = "receive_msg"
#5  0x000056235b546d59 in udp_read_req (si=0x7f8d66bbea08, bytes_read=0x7ffed0635fb8) at net/proto_udp/proto_udp.c:181
        ri = {src_ip = {af = 2, len = 4, u = {addrl = {140244130789642, 0}, addr32 = {563673354, 32653, 0, 0}, addr16 = {63754, 8600, 32653, 0, 0, 0, 0, 0},
              addr = "\n\371\230!\215\177\000\000\000\000\000\000\000\000\000"}}, dst_ip = {af = 2, len = 4, u = {addrl = {161020170, 0}, addr32 = {161020170, 0, 0, 0}, addr16 = {63754, 2456, 0, 0, 0, 0, 0,
                0}, addr = "\n\371\230\t", '\000' <repeats 11 times>}}, src_port = 5060, dst_port = 5060, proto = 1, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2,
              sa_data = "\023\304\n\371\230!\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 50195, sin_addr = {s_addr = 563673354}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {
              sin6_family = 2, sin6_port = 50195, sin6_flowinfo = 563673354, sin6_addr = {__in6_u = {__u6_addr8 = "\000\000\000\000\000\000\000\000\260\306?[#V\000", __u6_addr16 = {0, 0, 0, 0, 50864, 23359,
                    22051, 0}, __u6_addr32 = {0, 0, 1530906288, 22051}}}, sin6_scope_id = 3496174224}}, bind_address = 0x7f8d66bbea08}
        len = 1049
        buf = "INVITE sip:+49199D161197000002192@10.249.152.9 SIP/2.0\r\nVia: SIP/2.0/UDP 10.249.152.33:5060;branch=z9hG4bK7a57397e\r\nMax-Forwards: 36\r\nFrom: <sip:+35nnnnn44696@next-id.de>;tag=as6ba06c96\r\nTo: <sip:+491"...
        tmp = 0x56235b401e90 <pt_become_active+25> "H\213E\320H\211\301H\211\312H\211\320H\301\340\005H\211\302H)\312H\211\320H\301\340\006H)\320H\301\340\003H\001\310H\301\340\006H\211\302H\213E\330H\001\320H\211E\360H\213\r\367\017?"
        fromlen = 16
        p = 0x5b237
        msg = {
          s = 0x56235b81fce0 <buf> "INVITE sip:+49199D161197000002192@10.249.152.9 SIP/2.0\r\nVia: SIP/2.0/UDP 10.249.152.33:5060;branch=z9hG4bK7a57397e\r\nMax-Forwards: 36\r\nFrom: <sip:+35nnnnn44696@next-id.de>;tag=as6ba06c96\r\nTo: <sip:+491"..., len = 1049}
        __FUNCTION__ = "udp_read_req"
#6  0x000056235b5297b9 in handle_io (fm=0x7f8d66e67ca8, idx=0, event_type=1) at net/net_udp.c:261
        n = 0
        read = 0
        __FUNCTION__ = "handle_io"
---Type <return> to continue, or q <return> to quit---
#7  0x000056235b5280e6 in io_wait_loop_epoll (h=0x56235b840820 <_worker_io>, t=1, repeat=0) at net/../io_wait_loop.h:280
        ret = 1
        n = 1
        r = 0
        i = 0
        e = 0x7f8d66e67ca8
        ep_event = {events = 1531235447, data = {ptr = 0x5b3fc6b000005623, fd = 22051, u32 = 22051, u64 = 6575192440200779299}}
        fd = 32
        __FUNCTION__ = "io_wait_loop_epoll"
#8  0x000056235b52a105 in udp_start_processes (chd_rank=0x56235b80c07c <chd_rank>, startup_done=0x7f8d58179580) at net/net_udp.c:389
        si = 0x7f8d66bbea08
        pid = 0
        i = 31
        p = 1
        __FUNCTION__ = "udp_start_processes"
#9  0x000056235b493f3c in main_loop () at main.c:782
        chd_rank = 32
        startup_done = 0x7f8d58179580
        rc = 0
        __FUNCTION__ = "main_loop"
#10 0x000056235b496feb in main (argc=11, argv=0x7ffed0636298) at main.c:1439
        cfg_log_stderr = 1
        cfg_stream = 0x56235c190010
        c = -1
        r = 0
        tmp = 0x7ffed0637eb0 ""
        tmp_len = 0
        port = 194
        proto = 0
        protos_no = 1
        options = 0x56235b58a878 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 2679734642
        rfd = 4
        __FUNCTION__ = "main"
(gdb)
(gdb)

**Comment by razvancrainea** [comment]
This has been fixed in the latest 2.4.7, so please update your version to get this fix.
