### ISSUE TITLE
[BUG] notify_on_event and wait_for_event creates endless event subscription

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2054]
Hi all!
Our opensips:

version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 8322b64a9
main.c compiled on 04:49:28 Mar 17 2020 with gcc 4.8.5

Part of configuration:
       
        async( wait_for_event("E_UL_AOR_INSERT","$avp(w_filter)", "10"),  ON_EVENT);

Expected behavior:
        If subscribed event rises in 10 seconds after execution provided function (from routing script) - continue script execution from ON_EVENT route. If event rises later - do not execute ON_EVENT route.

Real behavior:
       If subscribed event rises after any period of time after provided function execution - continue script execution from ON_EVENT route.

In fact - given resume route fires even if event will be raised in a hour or so after subscribing to event.
After subscribing to E_UL_AOR_INSERT from script, seems it creates endless subscription to given event:

[root@sip-uat-reg-1]# opensipsctl fifo subscribers_list
Event:: E_UL_AOR_INSERT id=5
        Subscriber::  socket=routing:E_UL_AOR_INSERT expire=never

Could you please fix it somehow for 2.4 ?

**Comment by liviuchircu** [comment]
@bogdan-iancu the `sub->flags & EBR_SUBS_TYPE_NOTY` restriction from [this line](https://github.com/OpenSIPS/opensips/blob/master/modules/event_routing/ebr_data.c#L369) seems unnecessary, as it will cause `EBR_SUBS_TYPE_WAIT` subscriptions to live forever.  Maybe just remove it and the issue will be fixed?  Do you agree?

**Comment by bogdan-iancu** [comment]
@liviuchircu , I did some in depth checkings to be sure that removing the `EBR_SUBS_TYPE_WAIT` subscriptions will not produce any kind of leak in the async engine (via the async context). But good news, it seems not, so it should be safe to remove that condition.
