### ISSUE TITLE
[CRASH] OpenSIPS Process Crashed on websocket connection

### ISSUE THREAD

**Issue by indrodiyadhaval** [OpenSIPS/opensips#2055]
-- Opensips is listening on Websocket connection
-- When we do  a normal connection check on opensips it crash immediately and doesent provide any output to websocket connection.

**OpenSIPS version you are running**

version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7e8167853
main.c compiled on 11:03:37 Feb 26 2020 with gcc 8

**Crash Core Dump**
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114526]: ERROR:proto_wss:tls_conn_init: no TLS server domain found
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114526]: ERROR:proto_wss:wss_conn_init: Cannot initiate the conn
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114526]: ERROR:core:handle_io: failed to do proto 6 specific init for conn 0x7f0a25ce3200
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114525]: ERROR:proto_wss:tls_conn_init: no TLS server domain found
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114525]: ERROR:proto_wss:wss_conn_init: Cannot initiate the conn
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114525]: ERROR:core:handle_io: failed to do proto 6 specific init for conn 0x7f0a25ce3058
Mar 23 18:58:29 develCallServer /usr/local/sbin/opensips[114534]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f0a25ce33a8), first free: (null): (null)(0) - aborting!

Mar 23 18:58:43 develCallServer systemd-coredump[114552]: Process 114513 (opensips) of user 0 dumped core.
                                                          
                                                          Stack trace of thread 114513:
                                                          #0  0x00007f0a2b0398df raise (libc.so.6)
                                                          #1  0x00007f0a2b023cf5 abort (libc.so.6)
                                                          #2  0x00000000004d6525 fm_free (opensips)
                                                          #3  0x00007f0a2329a479 _shm_free (proto_wss.so)
                                                          #4  0x00007f0a232a95b9 ws_conn_clean (proto_wss.so)
                                                          #5  0x0000000000570c38 _tcpconn_rm (opensips)
                                                          #6  0x000000000057434f __tcpconn_lifetime (opensips)
                                                          #7  0x000000000057536d tcp_destroy (opensips)
                                                          #8  0x00000000004a8b79 cleanup (opensips)
                                                          #9  0x00000000004a9807 shutdown_opensips (opensips)
                                                          #10 0x00000000004a9e45 handle_sigs (opensips)
                                                          #11 0x00000000004ab17d main_loop (opensips)
                                                          #12 0x00000000004adcd8 main (opensips)
                                                          #13 0x00007f0a2b025873 __libc_start_main (libc.so.6)
                                                          #14 0x000000000041663e _start (opensips)

OS = Centos 8.1

**Comment by razvancrainea** [comment]
Could you please try the nightly build of OpenSIPS 3.0? I am pretty sure this has been fixed in commit 59e1e908. Cheers!
