### ISSUE TITLE
[BUG]goes_to_gw_1 function coding is not correct

### ISSUE THREAD

**Issue by zhouboyong** [OpenSIPS/opensips#2057]
**OpenSIPS version you are running**

version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
svn revision: 11795:12279M
main.c compiled on 18:35:32 Mar 25 2020 with gcc 4.8.5

**Describe the bug**
the function goes_to_gw  for modules drouting have a bug
the orignal code is:
static int goes_to_gw_1(struct sip_msg* msg, char * part, char* _type, char* flags_pv,
		char* gw_att)
{

	if(use_partitions) {
		gw_attrs_spec = (pv_spec_p)gw_att;
		return _is_dr_uri_gw(msg, part, flags_pv, (!_type ? -1 : *(int *)_type),
				GET_NEXT_HOP(msg));
	} else {
		gw_attrs_spec = (pv_spec_p)flags_pv;
		return _is_dr_uri_gw(msg, NULL, flags_pv, (!_type ? -1 : *(int *)_type),
				GET_NEXT_HOP(msg));
	}
}

but the correct code should is:
static int goes_to_gw_1(struct sip_msg* msg, char * part, char* _type, char* flags_pv,
		char* gw_att)
{

	if(use_partitions) {
		gw_attrs_spec = (pv_spec_p)gw_att;
		return _is_dr_uri_gw(msg, part, flags_pv, (!_type ? -1 : *(int *)_type),
				GET_NEXT_HOP(msg));
	} else {
		gw_attrs_spec = (pv_spec_p)flags_pv;
		return _is_dr_uri_gw(msg, NULL, _type, (!part ? -1 : *(int *)part),	// modify by byzhou
				GET_NEXT_HOP(msg));
	}
} 

you foggot to change the params order!!

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
I believe you are right - could you please open a pull request with this fix? Thanks!

**Comment by zhouboyong** [comment]
I try to open a pull request, but i donnt know how to do

**Comment by bogdan-iancu** [comment]
no worries, I will take care of this

**Comment by bogdan-iancu** [comment]
Thank you @zhouboyong , see 9c6664a3bb98020920f228a3da561db9bf24c9f2
