### ISSUE TITLE
[FEATURE] Add domain in usrloc event interface

### ISSUE THREAD

**Issue by atrips** [OpenSIPS/opensips#2062]
Hello,

I do not know how many people are using multiple location tables on single OpenSIPS instance but at least for me it will be useful if there is a way to catch/filter events based on there domain/location table too. This is directly related to RFC 8599 development.

Thank you.

**Comment by atrips** [comment]
I'm will give an example as my explanation above may not be very clear. For example we have have 2 types of subscribers: fixed and mobile. During the registration process they are stored in 2 different location tables: save("location_fix")/save("location_mobile"). In out case only events related to mobile subscribers need to be handled. Issue is that I cannot find an easy way distinguish events based on the location table.

**Comment by bogdan-iancu** [comment]
@atrips , I see your point, no need for extra argument :)
