### ISSUE TITLE
[BUG] The B2B refer scenario doesn't handled attended transfers

### ISSUE THREAD

**Issue by wluke** [OpenSIPS/opensips#2068]
The B2B refer scenario seems to fail when a REFER is referencing an existing call (attended transfer) in the Refer-To header, rather than needing to create a new one.
It sends a new invite rather than doing a re-INVITE on the existing call.

**Comment by bogdan-iancu** [comment]
@wluke please post the relevant information such as:

- the OpenSIPS version you are using 

- the pcap showing your test calls

- the opensips debug logs covering the whole testing
