### ISSUE TITLE
[BUG] @ wrongly considered as bad character in RURI parameter's values

### ISSUE THREAD

**Issue by StellaTeam** [OpenSIPS/opensips#2071]
Hello,

`
 ruri_add_param("phone-context=+33@domainname");
`
(even if the @ is escaped) produce errors like theses

```
Apr  9 15:18:21 [12606] ERROR:core:parse_uri: bad char '@' in state 11 parsed: <sip:1014@100.64.5.77;user=phone;phone-context=+33> (50) / <sip:1014@100.64.5.77;user=phone;phone-context=+33@domainname> (66)
Apr  9 15:18:21 [12606] ERROR:core:parse_sip_msg_uri: bad uri <sip:1014@100.64.5.77;user=phone;phone-context=+33@domainname>

```

But:
- according to my understanding of the RFCs, @ is not a forbidden character on RURI
- the French Telecom Federation requires using phone-context parameter in `+33@domainname` format
so, this limitation is probably an error in the code.

If i right, the error is located at https://github.com/OpenSIPS/opensips/blob/d89d0ec2db9a65ee77f995e554bc7300296621b5/parser/parse_uri.c#L406

If you agree, would you mind remove this limitation?

Regards

**Comment by vasilevalex** [comment]
Hi, @StellaTeam. How did you escaped `@` character? It should be escaped like `%40`

**Comment by StellaTeam** [comment]
Hi @vasilevalex thank you for your reply.

What you wrote make sense but in such case, that is no more escaping but encoding, isn't it?
According to my knowledge, encoding special characters are mostly in order to prevent any ambiguity (for example when parameter value contents a reserved character or a character used as separator).

In my case, ther is no ambiguity as phone-context is well separated from other parms.
Moreover i read nothing about such requirements and i worry about `%40` requested to bypass opensips checks not to be recognized/supported by Orange's (and any other carrier) switches.

In my example:

`<sip:1014@100.64.5.77;user=phone;phone-context=+33@domainname>`
would become 
`<sip:1014@100.64.5.77;user=phone;phone-context=+33%40domainname>`
 and will probably work for tests (because bypassing opensips checks) but will probably not be supported/recognized by facing switch

Here are all documents i found that makes no mention of any limitation in characters or encoding requirements in phone-context parameter as they do for some other attributes/parameters (or tel uri for example).

https://www.voip-info.org/sip-uri/
https://tools.ietf.org/rfc/rfc4967.txt
https://www.fftelecoms.org/app/uploads/2018/03/Version-2-1-interface-SIP-FFT-pour-interconnexion-voix_clean.pdf
https://tools.ietf.org/html/rfc3261

Regards

**Comment by vasilevalex** [comment]
@StellaTeam you several times mentioned rfc3261, but why didn't you read it? https://tools.ietf.org/html/rfc3261#section-25.1
There is clear description, what symbols are allowed for uri parameters, what is escaped symbol. And I call it "escaping" just because the same word is used in RFC.
```
uri-parameters    =  *( ";" uri-parameter)
uri-parameter     =  transport-param / user-param / method-param
                     / ttl-param / maddr-param / lr-param / other-param
other-param       =  pname [ "=" pvalue ]
pname             =  1*paramchar
pvalue            =  1*paramchar
paramchar         =  param-unreserved / unreserved / escaped
param-unreserved  =  "[" / "]" / "/" / ":" / "&" / "+" / "$"
unreserved  =  alphanum / mark
mark        =  "-" / "_" / "." / "!" / "~" / "*" / "'"/ "(" / ")"
escaped     =  "%" HEXDIG HEXDIG
```
So you can easily find, that `@` should be escaped as `%40` Section 19.1.3 (https://tools.ietf.org/html/rfc3261#section-19.1.3) even has several similar examples

**Comment by StellaTeam** [comment]
Hi @vasilevalex 

Thank you very much for your reply. Your references are very clear.

I now understood where i was messing, and found the reason in Section 19.1.6 (https://tools.ietf.org/html/rfc3261#section-19.1.6).

My `phone-context` is not an URI parameter but, because it is a "conversion" of a tel URI, it is a part of the userpart, and so, should be appened to `$tU` and not added through `ruri_add_param`.

That's a special case, and i was confused by the presence of the coma, which is not a parameters delimiter when in userpart of URI (and we're in userpart until `@` hasn't been found - the reason why it should be escaped in all other cases). 

Everything is now clear and working.

Sorry for the disturb and thank you for your help.
