### ISSUE TITLE
[BUG] BYE with Route header can not pass topology_hiding_match()

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#2084]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT, ENCRYPT-CFG
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 5f9afd357
main.c compiled on  with gcc 7
```

**Describe the bug**

Hello guys! Please help with this problem.
We use topology_hiding without dialog module. And i attach simple patch for `topo_hiding_logic.c` - it helps me to found where is problem happened:
[test-topology_hiding.txt](https://github.com/OpenSIPS/opensips/files/4517344/test-topology_hiding.txt)
I see that when opensips receive BYE request with header Route, then this BYE can not pass through topology_hiding_match() here (in `topo_hiding_logic.c`):

```
if (check_self(&r_uri->host,r_uri->port_no ? r_uri->port_no : SIP_PORT, 0) == 1 && msg->route == NULL) {
```

I see, that BYE with Route header pass through first condition:
```
check_self(&r_uri->host,r_uri->port_no ? r_uri->port_no : SIP_PORT, 0) == 1
```
But can not pass through second condition:
```
msg->route == NULL
```
If i remove Route header from BYE request, when request pass through both conditions correctly.

**To Reproduce**

1) initial INVITE comes through opensips with tm, topology_hiding, but without dialog.
2) calling topology_hiding() for initial INVITE.
3) send BYE with Route header from A side to openisps.

**Expected behavior**

Expected behavior: opensips must correctly process BYE with Route header and pass it through topology_hiding_match().

**Relevant System Logs**

For BYE without Route header:
```
Apr 22 15:23:11 [27487] DBG:sipmsgops:has_totag: totag found
Apr 22 15:23:11 [27487] DBG:core:pv_get_dsturi: no destination URI
Apr 22 15:23:11 [27487] DBG:core:parse_headers: flags=ffffffffffffffff
Apr 22 15:23:11 [27487] DBG:core:parse_headers: flags=200
Apr 22 15:23:11 [27487] DBG:topology_hiding:topology_hiding_match: BEFORE check_self
Apr 22 15:23:11 [27487] DBG:core:grep_sock_info_ext: checking if host==us: 12==12 &&  [1.1.1.26] == [2.2.2.196]
Apr 22 15:23:11 [27487] DBG:core:grep_sock_info_ext: checking if port 5060 matches port 5060
Apr 22 15:23:11 [27487] DBG:core:grep_sock_info_ext: checking if host==us: 12==12 &&  [1.1.1.26] == [1.1.1.26]
Apr 22 15:23:11 [27487] DBG:core:grep_sock_info_ext: checking if port 5060 matches port 5060
Apr 22 15:23:11 [27487] DBG:topology_hiding:topology_hiding_match: check_self passed
Apr 22 15:23:11 [27487] DBG:topology_hiding:topology_hiding_match: msg_route passed
Apr 22 15:23:11 [27487] DBG:topology_hiding:topology_hiding_match: We found param in R-URI with value of XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

For BYE with Route header:
```
Apr 22 15:25:34 [27484] DBG:sipmsgops:has_totag: totag found
Apr 22 15:25:34 [27484] DBG:core:pv_get_dsturi: no destination URI
Apr 22 15:25:34 [27484] DBG:core:parse_headers: flags=ffffffffffffffff
Apr 22 15:25:34 [27484] DBG:core:parse_headers: flags=200
Apr 22 15:25:34 [27484] DBG:topology_hiding:topology_hiding_match: BEFORE check_self
Apr 22 15:25:34 [27484] DBG:core:grep_sock_info_ext: checking if host==us: 12==12 &&  [1.1.1.26] == [2.2.2.196]
Apr 22 15:25:34 [27484] DBG:core:grep_sock_info_ext: checking if port 5060 matches port 5060
Apr 22 15:25:34 [27484] DBG:core:grep_sock_info_ext: checking if host==us: 12==12 &&  [1.1.1.26] == [1.1.1.26]
Apr 22 15:25:34 [27484] DBG:core:grep_sock_info_ext: checking if port 5060 matches port 5060
Apr 22 15:25:34 [27484] DBG:topology_hiding:topology_hiding_match: check_self passed
Apr 22 15:25:34 [27484] DBG:topology_hiding:topology_hiding_match: check_self do not passed
```

**OS/environment information**
 - Operating System:  Ubentu
 - OpenSIPS installation:  source
 - other relevant information:

**Additional context**

Please check this! Thank you!

**Comment by kertor** [comment]
Hello guys!
Any news about this issue?

**Comment by bogdan-iancu** [comment]
@kertor , I think there is something wrong with your SIP flow - if your OpenSIPS does TH (with or without dialog), there should be no BYE with `Route` headers (as OpenSIPS is acting as SIP end point when doing TH, so no Route should get to it).
