### ISSUE TITLE
[BUG] error in decoding smpp when the sender address is alphanumeric. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips#2085]
**OpenSIPS version you are running**

```
 ./opensips  -V
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, EXTRA_DEBUG, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a9d07b55f
main.c compiled on 08:30:23 Feb  7 2020 with gcc 6.3.0
```

**Describe the bug**

you send an sms in smpp with alphanumeric sender, the result is an empty from header. 

**To Reproduce**

send sms with alphanumeric sender. 

**Expected behavior**

to have a from header with the alpha numeric part in display name  and a from user part as sms or so:  "xxx yyyyy"  <sip:sms@domain>

**Relevant System Logs**

syslog : 

Apr 24 08:32:11 hendrix /data/opensips/sbin/opensips[6325]: ERROR:core:parse_from_header: bad from header
Apr 24 08:32:11 hendrix /data/opensips/sbin/opensips[6325]: ERROR:core:pv_get_from_attr: cannot parse From header
Apr 24 08:32:11 hendrix /data/opensips/sbin/opensips[6325]: callid=15688ac24f855169-6325@10.3.0.150: local_route : message generated by tm ru sip:33757936423@10.3.0.150:58605 rb Test from alphanumeric sender fu <null> tu sip:33757936423@10.3.0.150:58605 ct <null>

pcap in text : 

Short Message Peer to Peer, Command: Deliver_sm, Seq: 39, Len: 84
    Length: 84
    Operation: Deliver_sm (0x00000005)
    Sequence #: 39
    Service type: (Default)
    Type of number (originator): Alphanumeric (0x05)
    Numbering plan indicator (originator): Unknown (0x00)
    Originator address: xxxx yyyyyy
    Type of number (recipient): International (0x01)
    Numbering plan indicator (recipient): ISDN (E163/E164) (0x01)
    Recipient address: 3357936423
    .... ..00 = Messaging mode: Default SMSC mode (0x0)
    ..00 00.. = Message type: Default message type (0x0)
    00.. .... = GSM features: No specific features selected (0x0)
    Protocol id.: 0x00
    Priority level: GSM: None      ANSI-136: Bulk         IS-95: Normal (0x00)
    Scheduled delivery time: Immediate delivery
    Validity period: SMSC default validity period
    .... ..01 = Delivery receipt: Delivery receipt requested (for success or failure) (0x1)
    .... 01.. = Message type: SME delivery acknowledgement requested (0x1)
    ...0 .... = Intermediate notif: No intermediate notification requested (0x0)
    .... ...0 = Replace: Don't replace (0x0)
    Data coding: 0x00
    Predefined message: 0
    Message length: 29
    Message: 546573742066726f6d20616c7068616e756d657269632073...

**OS/environment information**
 - Operating System:  debian 9
 - OpenSIPS installation:  3.01 with proto_smpp from master. 
 - other relevant information:

**Additional context**

**Comment by johandeclercqdemocon** [comment]
reopening on Razvan's request.

**Comment by razvancrainea** [comment]
Hi, @johandeclercqdemocon !

Unfortunately I couldn't fix this using your idea (have the name in the Display Name), however I encoded the source and destination in the username. Therefore we will still use a valid SIP message, but you will need to URL decode the username to get the actual value.
Let me know if that works for you, or whether there are any limitations I haven't forseen. If there are none, feel free to close the ticket.

Best regards,
Răzvan
