### ISSUE TITLE
[CRASH] Error in the Clusterer Database Module Causes OpenSips to Crash

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#2086]
**OpenSIPS version you are running**
```
opensips -V
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: eabdd2d10
main.c compiled on  with gcc 7

```
**Crash Core Dump**
Please find crash data file here
https://drive.google.com/file/d/150XGvsz7irykbgVaq4As8U-7mlA3o0bm/view?usp=sharing

**Comment by liviuchircu** [comment]
Hey, Rizwan!  I invested some time in trying to reproduce this, but to no avail.  The backtrace is useful, but I couldn't reverse-engineer into a way of reproducing it - it's quite a strange setup!

Could you provide a minimal `opensips.cfg` file and/or DB provisioning query that makes it crash, so we can speed this up?  Thanks!
