### ISSUE TITLE
[BUG] unable to compile latest 3.0 on  debian buster amd64

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips#2088]
**OpenSIPS version you are running**

```
latest 3.0 from github. 

```

**Describe the bug**

unable to compile :  (just standard, no extra modules)

/usr/bin/ld: main.o: in function `pthread_mutex_init':
/usr/src/opensips_3_0/ssl_tweaks.h:32: undefined reference to `pthread_mutexattr_setpshared'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:26: undefined reference to `pthread_mutexattr_init'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:32: undefined reference to `pthread_mutexattr_setpshared'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:38: undefined reference to `pthread_mutexattr_destroy'
/usr/bin/ld: main.o: in function `pthread_rwlock_init':
/usr/src/opensips_3_0/ssl_tweaks.h:64: undefined reference to `pthread_rwlockattr_setpshared'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:58: undefined reference to `pthread_rwlockattr_init'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:64: undefined reference to `pthread_rwlockattr_setpshared'
/usr/bin/ld: /usr/src/opensips_3_0/ssl_tweaks.h:70: undefined reference to `pthread_rwlockattr_destroy'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.rules:39: opensips] Error 1
make[1]: Leaving directory '/usr/src/opensips_3_0'

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System:  buster, amd64
 - OpenSIPS installation:  from github, latest 3.0
 - other relevant information: the system has openssl 1.1.1

**Additional context**
 I think that somewhere in the make file -pthread is missing

**Comment by johandeclercqdemocon** [comment]
I don't know if this helps but on on stretch, there is no issue (using same settings).

**Comment by liviuchircu** [comment]
Hey, @johandeclercqdemocon, this is how I set up a fresh Debian 10 VM and had no issues building the `master` branch `opensips` binary:

```
apt install bison lynx debhelper dpatch xsltproc flex gcc make pkg-config libdb-dev uuid-dev libjson-c-dev default-libmysqlclient-dev libncurses5-dev libpcre3-dev libssl-dev docbook-xsl docbook-xml html2text
```

Let me know if this helps, otherwise please provide more details on how to reproduce, as I can easily re-create a bare Debian 10 system.  Thank you!

**Comment by johandeclercqdemocon** [comment]
your packet selection does the job.  Thanks for the swift assistance.

**Comment by dennys9415** [comment]
hi, I have the same problem but with the version 1.8 and the solution above didn't work.
This Error is 1 Makefile.rules.36

`/root/opensips-1.8.3-tls/timer.c:510: undefined reference to `inc_init_timer'
/usr/bin/ld: transformations.o: in function `tr_eval_ip':
/root/opensips-1.8.3-tls/transformations.c:1205: undefined reference to `resolvehost'
/usr/bin/ld: db/db_query.o: in function `db_do_insert':
/root/opensips-1.8.3-tls/db/db_query.c:289: undefined reference to `cleanup_rows'
collect2: error: ld returned 1 exit status
make: *** [Makefile.rules:36: opensips] Error 1
`

**Comment by johandeclercqdemocon** [comment]
I would suggest to use 3.3
