### ISSUE TITLE
[BUG] Using HP_MALLOC causes invalid memory statistics

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2089]
**OpenSIPS version you are running**

```
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, NO_DEBUG, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a627750df
main.c compiled on 23:31:19 Apr 24 2020 with gcc 7
```

**Describe the bug**

When the HP_MALLOC memory manager is enabled, the Core shared memory (shmem) statistics show more memory used than the total memory size. The free_size reported is also not correct.

**To Reproduce**

1. Compile OpenSIPS with HP_MALLOC define
2. Start OpenSIPS
3. Run `opensipsctl fifo get_statistics shmem:`
4. See invalid memory stats

**Expected behavior**

Used memory should not exceed total memory size.

**Relevant System Logs**

The following is from OpenSIPS compiled with HP_MALLOC and run with `-m 1024`.
```
# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 134217728
shmem:used_size:: 171649896
shmem:real_used_size:: 173901648
shmem:max_used_size:: 173901680
shmem:free_size:: 18446744073669867696
shmem:fragments:: 1820
```

The following is from OpenSIPS compiled with F_MALLOC and run with `-m 1024`.
```
# opensipsctl fifo get_statistics shmem:
shmem:total_size:: 134217728
shmem:used_size:: 86941968
shmem:real_used_size:: 87014920
shmem:max_used_size:: 87014928
shmem:free_size:: 47202808
shmem:fragments:: 1634
```

**OS/environment information**
 - Operating System:  Docker amazonlinux:2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
Hey, @bcnewlin, the `2.4` HP_MALLOC should be fully working now, both from a functionality and from a monitoring point of view (statistics).  I have given it a good amount of stress testing and it behaved nicely.  Do let me know if you notice any more inconsistencies.  Cheers!

**Comment by bcnewlin** [comment]
@liviuchircu Thank you! I will check it out!

**Comment by bcnewlin** [comment]
@liviuchircu Looks like it's working great!
