### ISSUE TITLE
B2B accounting CDR

### ISSUE THREAD

**Issue by korithi** [OpenSIPS/opensips#2094]
Hello,
I am using opensips 2.4. 
I would like to account cdr's with duration. As per documentation it says that getting duration value is based on using dialog module. 
I my scenario opensips is being used as B2B and can't rely on dialog module.
How can I get duration in such case for both sides of the call, or even for one if possible?
My scenario is B2B with "refer".

Thanks and regards,
Rafael

**Comment by korithi** [comment]
Hi guys,
Can you please help?
Thanks,

**Comment by korithi** [comment]
Can you please tell me how do I catch the Invite's 200OK response on the A_side in a b2b scenario/call center?

Thanks,

**Comment by bogdan-iancu** [comment]
@khoegh , the B2B engine does not have CDR accounting support. Still, you can do transaction based accounting, for the UAC and UAS sides involved in the B2B session and aggregate the logs to get real CDR info.
Still note that the accounting for UAC transaction was introduced starting OpenSIPS 3.1.
