### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AnjanIpc** [OpenSIPS/opensips#2097]
**OpenSIPS version you are running**

```
version: opensips 1.11.5-tls (x86_64/linux)
```

**Describe the bug**

```
sometimes opensips is not logging. we are seeing some instance where opensips is not writing any logs after the system comes up.
```
**To Reproduce**

```
we are not sure how to reproduce. we are seeing in some servers opensips is not writing any logs when the system comes up.
```
**Expected behavior**

```
opensips should write the logs.
```
**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
```
system is running on RHEL6 (Red Hat Enterprise Linux Server release 6.5 (Santiago)). Openesips is working as a proxy for us.
```
**Additional context**

our log config is defined as below
cat /etc/logrotate.d/ipc_logs
size 100M
rotate 300
compress
compresscmd /etc/opt/ipc/log_comp
missingok
sharedscripts
copytruncate

Please help us ASAP on this. without this logs it is very difficult to debug the issue.

**Comment by AnjanIpc** [comment]
Can anyone help on this ?

**Comment by liviuchircu** [comment]
hey, @AnjanIpc!  `1.11` is unmaintained for quite some time now, please upgrade to a [supported release](https://www.opensips.org/About/AvailableVersions).  Cheers!

**Comment by AnjanIpc** [comment]
Hi liviuchircu,
 we are not expecting any fix for older version but just want to know if there were any known issue as we have already upgraded later opensips version in our newer version.

But, The customer with older versions wants to make sure if this is known issue in current version and after upgrade, this issue will be fixed for sure.

Can you please confirmed that ?

Thanks,
Anjan

**Comment by liviuchircu** [comment]
I haven't heard of this "limited logging" OpenSIPS problem until now, not even with OpenSIPS 1.11.  So my best guess is that your RedHat-based system may be the cause of this.  Because on paranoid RedHat/CentOS, the syslog is configured to be less tolerant than in Debian-based distros, so if you log to much into it, it will start dropping your logs.

See [this article](https://www.thegeekdiary.com/how-to-disable-or-extend-system-logging-rate-limit-on-centos-rhel-7/) for more details on syslog ratelimiting.  I hope it's related to your problem and you fix it.

Best regards,
Liviu

**Comment by AnjanIpc** [comment]
Thanks for the quick response.
As mentioned earlier, my OS is RHEL6 (Red Hat Enterprise Linux Server release 6.5 (Santiago)).
As per the link, you mentioned, this talks about RHEL7.
and i dont see the parameter "SystemLogRateLimitInterval " and "SystemLogRateLimitBurst" at "/etc/rsyslog.conf" in my system.

Thanks,
Anjan

**Comment by liviuchircu** [comment]
OK, then please follow the [RHEL6 article](https://www.thegeekdiary.com/how-to-disable-or-extend-system-logging-rate-limit-on-centos-rhel-6/).

**Comment by AnjanIpc** [comment]
We are using syslog-ng and the references you suggested are for rsyslog. 
Do you think the same can help here or any other suggestion please ?

Thanks,
Anjan

**Comment by AnjanIpc** [comment]
Hi liviuchircu,
Any suggestion will be highly appreciated.

Thanks,
Anjan

**Comment by liviuchircu** [comment]
Hi, @AnjanIpc, I have little to no experience with RHEL6 or `syslog-ng`, so I cannot help much.  I suggest you try reproducing this issue in a lab environment using a fresh OpenSIPS version, such as `2.4` and RHEL packages from the [YUM repo](https://yum.opensips.org/).  If you can reproduce this bug, please open a new ticket.

Cheers!
