### ISSUE TITLE
[BUG] Private memory will run out eventually on Regular Expression Transformations

### ISSUE THREAD

**Issue by zedatgithub** [OpenSIPS/opensips#2099]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 03:15:28 Jan 29 2020 with gcc 4.4.7
```

**Describe the bug**

Private memory will run out eventually on Regular Expression Transformations

https://www.opensips.org/Documentation/Script-Tran-3-1#re.subst

**To Reproduce**

Start OpenSIPS with the below configuration file

```
udp_workers=1
listen=udp:0.0.0.0:5060
mpath="/usr/lib64/opensips/modules"
loadmodule "sl.so"
loadmodule "proto_udp.so"
route {
    $var(reg) = "/\|_\|/ /g";
    $var(reg_input_1)  = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s";
    $var(reg_output_1) = $(var(reg_input_1){re.subst,$var(reg)});
    $var(reg_input_2)  = "Lorem|_|Ipsum|_|is|_|simply|_|dummy|_|text|_|of|_|the|_|printing|_|and|_|typesetting|_|industry.|_|Lorem|_|Ipsum|_|has|_|been|_|the|_|industry's|_|standard|_|dummy|_|text|_|ever|_|since|_|the|_|1500s";
    $var(reg_output_2) = $(var(reg_input_2){re.subst,$var(reg)});
    exit;
}
```

**Expected behavior**

In the above example memory usage should not increase just stay at same 

**Relevant System Logs**

**OS/environment information**
 - Operating System: Centos 6
 - OpenSIPS installation: https://yum.opensips.org/3.0/releases/el/6/x86_64/

**Additional context**

http://zed.ro/i/re872.mp4

**Comment by liviuchircu** [comment]
hey @zedatgithub!  OpenSIPS `1.6.4` is no longer maintained for 10 years now.  Please consider upgrading to a [supported, modern version](https://www.opensips.org/About/AvailableVersions).  Your problem might just as well go away by doing so.

Cheers!

**Comment by zedatgithub** [comment]
it was wrong copy paste of version section only from a different test server

if you look the video and the .cfg you see it use {re.subst which at 1.6 even was not available

**Comment by liviuchircu** [comment]
I changed your code to:

```
loadmodule "mi_fifo.so"
max_while_loops=1000000

route {
    $var(i) = 0;

    while (true) {
        $var(reg) = "/\|_\|/ /g";
        $var(reg_input_1)  = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s";
        $var(reg_output_1) = $(var(reg_input_1){re.subst,$var(reg)});
        $var(reg_input_2)  = "Lorem|_|Ipsum|_|is|_|simply|_|dummy|_|text|_|of|_|the|_|printing|_|and|_|typesetting|_|industry.|_|Lorem|_|Ipsum|_|has|_|been|_|the|_|industry's|_|standard|_|dummy|_|text|_|ever|_|since|_|the|_|1500s";
        $var(reg_output_2) = $(var(reg_input_2){re.subst,$var(reg)});
        $var(r) = $var(i) % 10000;
        if ($var(r) == 0)
            xlog("XXX now at: $var(i)\n");
        $var(i) = $var(i) + 1;
    }

    exit;
}
```

And there is no leak.  `opensips-cli -x mi get_statistics pkmem:` shows constant memory usage, on `master` branch.  Do you have different results on your setup?

**Comment by zedatgithub** [comment]
On your provided setup no memory leak

on a centos 7 cant replicate the bug and cant reach that server where i took that sample leak

will re investigate and get back

**Comment by liviuchircu** [comment]
Please re-open if you confirm the issue, @zedatgithub.  Cheers!

**Comment by rrevels-bw** [comment]
This will leak pkg memory in a heartbeat.  On 2.4 anyway.  I suspect 3.x may do the same.  I had no problem if using a static value for the index of $(avp(destination)[$avp(offset)])

I was sending 200 cps and could watch package memory drop.

route[0]
{
        $avp(index) := 0;
        $avp(destination) := "192.168.1.42";
        $avp(destination) = "192.168.2.42";
        $avp(destination) = "192.168.3.42";
        $avp(offset) := 1;
        while( $avp(index) < 10 )
        {
                $avp(foo) := "sip:+19198779880@{<DESTINATION1>}:5060";
                $avp(regex_replace) := '/\\{<DESTINATION3>}/$(avp(destination)[$avp(offset)])/';
                $avp(foo) = $(avp(foo){re.subst, $avp(regex_replace)});
                $avp(regex_replace) := '/\\{<DESTINATION1>}/$(avp(destination)[$avp(offset)])/';
                $avp(foo) = $(avp(foo){re.subst, $avp(regex_replace)});
                $avp(regex_replace) := '/\\{<DESTINATION2>}/$(avp(destination)[$avp(offset)])/';
                $avp(foo) = $(avp(foo){re.subst, $avp(regex_replace)});
                $avp(index) = $avp(index) + 1;
        }
        sl_send_reply("408", "no one home");
        drop;
        return(0);
}

**Comment by rrevels-bw** [comment]
looks like this editor borked my code.  let me try that again

`        while( $avp(index) < 10 )
        {
                $avp(foo) := "sip:+19198779880@{<DESTINATION1>}:5060";
                $avp(regex_replace) := '/\\{<DESTINATION3>}/$(avp(destination)[1])/';
                $avp(notfoo) = $(avp(foo){re.subst, $avp(regex_replace)});

                $avp(regex_replace) := '/\\{<DESTINATION1>}/$(avp(destination)[0])/';
                $avp(notfoo) = $(avp(foo){re.subst, $avp(regex_replace)});

                $avp(regex_replace) := '/\\{<DESTINATION2>}/$(avp(destination)[2])/';
                $avp(notfoo) = $(avp(foo){re.subst, $avp(regex_replace)});

                $avp(index) = $avp(index) + 1;
        }
`

**Comment by rrevels-bw** [comment]
Oh, one last thing.  This was the line that looked to be causing it

2022-02-22T17:47:27.309476+00:00 sbc-ib-proxy-01 /usr/local/opensips/sbin/opensips[11502]:   10557328 : 96882 x [pvar.c: pv_parse_index, line 3184]
