### ISSUE TITLE
[CRASH] Get crash in proto_wss.so  (opensips 3.0.2)

### ISSUE THREAD

**Issue by stevenchiu7311** [OpenSIPS/opensips#2100]
HI guys,
Need your help for this issue
I encountered crash and get demsg as following  

[Tue May  5 06:29:53 2020] opensips[6222]: segfault at 34 ip 00007f51cf9318bd sp 00007ffec5dd2310 error 4 in proto_wss.so[7f51cf91f000+20000]

opensips version:
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7e8167853
main.c compiled on 20:25:50 May  4 2020 with gcc 7

And run as system daemon like this
/sbin/opensips -P /var/run/opensips/opensips.pid -m 512 -M 8 -u opensips -g opensips -f /etc/opensips/opensips.cfg -w /corefiles

My corefile and opensips excutable in google dirve
https://drive.google.com/drive/folders/177Go8CeskbdsAP45ZE-jV-OMIiKr2sBY

Also paste its trace
#0  0x00007f51cf9318bd in ws_connect (fd=0x7ffec5dd2384, to=0x7ffec5dd25a0, send_sock=<optimized out>) at proto_wss.c:410
410		if (WS_TYPE(c) != WS_NONE) {
(gdb) bt
#0  0x00007f51cf9318bd in ws_connect (fd=0x7ffec5dd2384, to=0x7ffec5dd25a0, send_sock=<optimized out>) at proto_wss.c:410
#1  proto_wss_send (send_sock=<optimized out>, buf=<optimized out>, len=<optimized out>, to=0x7ffec5dd25a0, id=<optimized out>) at proto_wss.c:490
#2  0x000055b20d748668 in msg_send (send_sock=0x7f51f211c348, proto=6, to=0x7ffec5dd25a0, id=<optimized out>, 
    buf=0x7f51f2330828 "ACK sip:103.11.73.244:443;transport=wss;did=713.3eaffdb4 SIP/2.0\r\nCall-ID: bd1be5fe-0629-4a1e-9bc0-fbdefbbdb03b\r\nCSeq: 117402 ACK\r\nFrom: \"2070025\" <sip:2070025@mcc5lt.m800.com>;tag=613ddef8\r\nTo: \"2720"..., len=<optimized out>, msg=0x7f51f23005c0) at forward.h:123
#3  0x000055b20d74a67e in forward_request (msg=msg@entry=0x7f51f23005c0, p=p@entry=0x7f51f2304a38) at forward.c:372
#4  0x00007f51d13777d6 in t_relay_to (p_msg=p_msg@entry=0x7f51f23005c0, proxy=0x7f51f2304a38, proxy@entry=0x0, flags=flags@entry=0) at t_funcs.c:238
#5  0x00007f51d13b1651 in w_t_relay (p_msg=0x7f51f23005c0, flags=0x0, proxy=<optimized out>) at tm.c:1226
#6  0x000055b20d712d79 in do_action (a=a@entry=0x7f51f2155cc8, msg=msg@entry=0x7f51f23005c0) at action.c:1979
#7  0x000055b20d71aab4 in run_action_list (a=<optimized out>, msg=msg@entry=0x7f51f23005c0) at action.c:176
#8  0x000055b20d769da8 in eval_elem (e=0x7f51f2155dd8, msg=0x7f51f23005c0, val=0x0) at route.c:588
#9  0x000055b20d769889 in eval_expr (e=0x7f51f2155dd8, msg=0x7f51f23005c0, val=0x0) at route.c:912
#10 0x000055b20d7698c9 in eval_expr (e=0x7f51f2155e28, msg=0x7f51f23005c0, val=0x0) at route.c:928
#11 0x000055b20d7698b5 in eval_expr (e=0x7f51f2155e78, msg=msg@entry=0x7f51f23005c0, val=val@entry=0x0) at route.c:933
#12 0x000055b20d7126c1 in do_action (a=a@entry=0x7f51f2156108, msg=msg@entry=0x7f51f23005c0) at action.c:1207
#13 0x000055b20d71aab4 in run_action_list (a=<optimized out>, msg=0x7f51f23005c0) at action.c:176
#14 0x000055b20d71ae7a in run_actions (a=<optimized out>, msg=<optimized out>) at action.c:141
#15 0x000055b20d71682a in do_action (a=a@entry=0x7f51f2137ba8, msg=msg@entry=0x7f51f23005c0) at action.c:862
#16 0x000055b20d71aab4 in run_action_list (a=<optimized out>, msg=msg@entry=0x7f51f23005c0) at action.c:176
#17 0x000055b20d717781 in do_action (a=a@entry=0x7f51f2137dc8, msg=msg@entry=0x7f51f23005c0) at action.c:1225
#18 0x000055b20d71aab4 in run_action_list (a=<optimized out>, msg=msg@entry=0x7f51f23005c0) at action.c:176
#19 0x000055b20d717781 in do_action (a=a@entry=0x7f51f213ca58, msg=msg@entry=0x7f51f23005c0) at action.c:1225
#20 0x000055b20d71aab4 in run_action_list (a=<optimized out>, msg=0x7f51f23005c0) at action.c:176

Thank you~

**Comment by razvancrainea** [comment]
Same bug as #1956 
Please update to a nightly build until we get a new release with the fix.
