### ISSUE TITLE
[BUG] LB/dialog module decreases lb count below 0

### ISSUE THREAD

**Issue by billsimon** [OpenSIPS/opensips#2102]
**OpenSIPS version you are running**

```
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**

In a redundant proxy environment two opensips servers are using a shared redis for caching of load balancer & dialog.

The routing script selects a back-end media server using lb.

In some unknown situation there is a miscount of dialogs and we have not been able to figure out that reason or reproduce it. But it happens every few weeks.

In some cases there is a critical problem though when opensips decrements the LB counter below zero:

```
# opensipsctl fifo lb_list
Destination:: sip:server9 id=9 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: conf/s max=85 load=4294967262
		Resource:: pstn/s max=200 load=0
Destination:: sip:server11 id=11 group=1 enabled=yes auto-reenable=on
	Resources:: 
		Resource:: conf/s max=85 load=4294967262
		Resource:: pstn/s max=200 load=0
...
```

as you can see the counter rolls over when decremented below 0, and then it is stuck in this state: no more calls will be sent to the server because load number is huge.

**Expected behavior**

Prevent LB/dialog modules from decrementing counters below zero, as this never makes any sense.

**Comment by billsimon** [comment]
This bug remains valid. Keep open.

**Comment by bogdan-iancu** [comment]
thank you @billsimon for your patience here. Is there a way for you to reproduce this issue (even if not controlled) ?

You mentioned using REDIS for sharing  - do you share there the profiles / resources from LB? IF so, is there any way to switch to BIN + Clustering replication for the profiles / resources from LB ?

**Comment by billsimon** [comment]
We have not been able to reproduce the issue in lab nor capture it in the live environment.

Yes, we are sharing profiles/resources and dialogs by redis. I have not considered the clusterer module. I have used redis for years and did not explore anything else. I will look into it. Thank you.

**Comment by bogdan-iancu** [comment]
The BIN (clustering) sharing of the profile is more reliable and error-safe as it is 100% opensips-to-opensips, without involving other entities that may keep state/data and break the sync.

IF you cannot reproduce or provide more data, there is not much we can do here - if we agree on that, please close the ticket and feel free to re-open or open a new one is some more data will be available in the future.

**Comment by billsimon** [comment]
I cannot provide any more data but do suggest that the logic of load balancer module should not allow resource count to go below zero. Could that logic be implemented as a fail-safe?

**Comment by bogdan-iancu** [comment]
Sound like a good & simple idea, but actually not so easy to do with shared counter via noSQL - without getting into details, into noSQL the counter value is aggregated from multiple sources, so you never know which party is publishing wrong date or if the aggregation at noSQL level is faulty (like old coutner value without corresponding ongoing calls).
This is the main reason why we replaced the noSQL based sharing with the BIN based replication.

**Comment by billsimon** [comment]
OK, I understand. We will transition to BIN/cluster for this. Thank you.
