### ISSUE TITLE
[CRASH] CGRateS with cgrates_acc() crashes OpenSIPS

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2103]
**OpenSIPS version you are running**
```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 20ffc6c8c
main.c compiled on 13:55:31 Apr 29 2020 with gcc 8
```

**Crash Core Dump**
https://pastebin.com/yW95wBF2 & https://pastebin.com/JpnFgUnm

**Describe the traffic that generated the bug**
On 2 cpu cores 5 GB RAM when trying 10-15 CPS then after some seconds there is HIGH CPU
and then the CRASH

**To Reproduce**
Example:
1. Enable CGRateS with cgrates_acc using

```
if (!has_totag()) {
			...
			# first session - authorize the user
			$cgr_opt(Tenant) = $fd; # set the From domain as a tenant
			$cgr(RequestType) = "*prepaid"; # do prepaid accounting
			if (!cgrates_auth("$fU", "$rU")) {
				sl_send_reply("403", "Forbidden");
				exit;
			}

			# second session - authorize the carrier
			$(cgr_opt(Tenant)[carrier]) = $td;
			$(cgr(RequestType)[carrier]) = "*postpaid";
			if (!cgrates_auth("$tU", "$fU", "carrier")) {
				# use a different carrier
				return;
			}

			# if everything is successful start accounting on both
			cgrates_acc("cdr", "$fU", "rU");
			cgrates_acc("cdr", "$tU", "$fU", "carrier");
		}
```
2. Start traffic 10-20-30 CPS
3. Check OpenSIPS HIGH CPU after some seconds and then its a matter of time OpenSIPS to crash

If I disable cgrates_acc everything works perfectly!!!

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git

Thank you in advance for your support

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
I have verified the same issue on latest 3.1 too.

Thanks
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

This Just a reminder to keep this issue open.
This issue makes cgrates module impossible to be used for generating cdrs.

thank you in advance
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Hi, @vtzan !

Both core dumps that you posted show a crash during OpenSIPS shut down, not the actual cause that generate the core dumps. Can you please check if there are any other core files, and paste that output?

Best regards,
Răzvan

**Comment by vtzan** [comment]
Dear @razvancrainea, 

thank you for your response. I have updated to the latest 3.1 to check again this issue.

```
version: opensips 3.1.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c0754d81f
main.c compiled on 11:21:13 Jun  8 2020 with gcc 8
```

And when enabling cgrates_acc function like this to generate Customer & Supplier CDRs: 
```
# Customer CDRs Generation
cgrates_acc("cdr|missed", "$avp(user_auth_db_target)","$avp(replaced_to)");

# Supplier CDRs Generation
cgrates_acc("cdr|missed", "$avp(replaced_to)", "$avp(user_auth_db_target)", "carrier");
```

I can only make one successful call and then Opensips hangs with multiple error messages like this below:

`ERROR:cgrates:io_watch_del: [TCP_worker] trying to delete already erased entry 573 in the hash(-1, 0, (nil)) )`

& many many logs like these below (using debug 6) ...... seems something is not cleared on that request or something...

```
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: DBG:cgrates:cgrc_async_read: 65 more bytes to process in the new request: [{"method":"SessionSv1.GetActiveSessionIDs","params":[""],"id":3}#012]
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: DBG:cgrates:cgrates_process: Processing JSON-RPC: { "method": "SessionSv1.GetActiveSessionIDs", "params": [ "" ], "id": 3 }
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: DBG:cgrates:cgrates_process: treating JSON-RPC as a request
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: INFO:cgrates:cgrates_process_req: Received new request method=SessionSv1.GetActiveSessionIDs param=0x55b644119590
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: DBG:cgrates:cgrates_process_req: sending json response: { "error": null, "result": [ ], "id": 3 }
Jun  8 12:59:08 SIP-1-AWS-VL-NEW edge[4814]: DBG:cgrates:cgrc_send: Successfully sent 41 bytes
```

during that time doing ngrep on port 2014 which is cgrates sessions port I see many many never ending requests from opensips --> CGRates
```
T 2020/06/08 12:58:11.366435 127.0.0.1:46970 -> 127.0.0.1:2014 [AP] #152872
{ "error": null, "result": [ ], "id": 3 }
#
T 2020/06/08 12:58:11.366469 127.0.0.1:46970 -> 127.0.0.1:2014 [AP] #152873
{ "error": null, "result": [ ], "id": 3 }
#
T 2020/06/08 12:58:11.366504 127.0.0.1:46970 -> 127.0.0.1:2014 [AP] #152874
{ "error": null, "result": [ ], "id": 3 }
#
T 2020/06/08 12:58:11.366541 127.0.0.1:46970 -> 127.0.0.1:2014 [AP] #152875
{ "error": null, "result": [ ], "id": 3 }
#
T 2020/06/08 12:58:11.366575 127.0.0.1:46970 -> 127.0.0.1:2014 [AP] #152876
{ "error": null, "result": [ ], "id": 3 }
```

and finally there is no crash right now but still have to restart opensips service to make a new call again.

thank you in advance for your support.
Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear @razvancrainea,

Please let me know if you need any further information on this issue. 
I can provide you ssh access to dev box to see the issue live if you like.

Thank you in advance for your support
Best Regards
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Hey, @vtzan ! I currently have a huge backlog to catch up with, but as soon as I get to this ticket, I will let you know if I need further details. Cheers!

**Comment by vtzan** [comment]
Hi @razvancrainea,

Sure no problem. I see very good things happening the last few months ;-)

Best Regards
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Figured out the issue, will soon come with a fix.

**Comment by razvancrainea** [comment]
I've just pushed a fix for this in the master branch. The case I addressed was related to the `SessionSv1.GetActiveSessionIDs` request from CGRateS, so I am not sure this was the initial report. Any chance you could give it another try with the master branch and let me know if you find any other issues?

**Comment by vtzan** [comment]
Dear @razvancrainea,

I am not really sure if this fixed something it seems that it fixed some never ending looping but I am not very sure. Let me describe the issue.

1. A calls B and B answers the phone and hungs up.
2. A trying to call B. A stays trying for 30 secs and then B rings and answers the phone. 
I think during that 30 sec there is an opensips restart (no core dump) but cause of debug 6 can't figure that out.

during that second call attempt with the 30sec delay I have collected the following logs:

https://pastebin.com/Wqs22XRB
cgarates port 2014 ngrep show multiple requests. don't know if this is the way it works --> https://pastebin.com/D2Ps6JRd

**tm config**
```
#### Transaction Module
loadmodule "tm.so"
modparam("tm", "wt_timer", 2)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)
modparam("tm", "fr_timeout", 10)
modparam("tm", "fr_inv_timeout", 30)
```

Please let me know if I can give you more information on this.

thank you in advance
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Unfortunately I can't find anything relevant in the first log, and the second owe just proves it works just fine, nothing abnormal in any of them.
You can check though if opensips restarts by storing opensips pids before the call, and after the call.

**Comment by vtzan** [comment]
Dear @razvancrainea,

Thank you for your reply.
I have checked that Opensips doesn't restart. But after each successful / answered  if I immediately try to make a second call, opensips needs 30 sec to reach the other side.
If I restart opensips then I can immediately call fast again.

If I disable the lines below everything works fine on every call :
```
cgrates_acc("cdr|missed", "$avp(user_auth_db_target)","$avp(replaced_to)");
cgrates_acc("cdr|missed", "$avp(replaced_to)", "$avp(user_auth_db_target)", "carrier");
```

Do have any idea how to debug further this case?

thank you in advance for your support
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
If you could provide me the DBG call logs for the second call, I can look into this.

**Comment by vtzan** [comment]
Dear @razvancrainea 

Please check your email. 

Thank you

**Comment by vtzan** [comment]
Thank you @razvancrainea !

This Issue is fixed!
The second problem with the delay I had was caused by a miss configuration on my side.

Best Regards
Vasilios Tzanoudakis
