### ISSUE TITLE
Topology Hiding: in 200 OK reply to an UPDATE message, contact of callee is replaced with the contact advertised to caller.

### ISSUE THREAD

**Issue by dioris-moreno** [OpenSIPS/opensips#2108]
**OpenSIPS version you are running**

```
version: opensips 3.1.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: dfe7b05
main.c compiled on 15:22:58 May 10 2020 with gcc 4.8.5
```

**Describe the bug**
When using topology hiding with dialogs, and the caller sends an UPDATE in-dialog message, in the 200 OK reply, OpenSIPS replaces the Contact header of the callee with the contact advertised to caller. The next message sent by caller cannot be relayed to callee and the call is terminated.

**To Reproduce**

1. Start OpenSIPS with a WebSocket-Udp configuration using Topology Hiding and Dialog Module.
2. Call from jsSIP to a user agent in UDP. jsSIP sends UPDATE methods by default.
3. After 45 seconds jsSIP sends the first UPDATE and the invalid callee_contact could be checked with:

```
opensips-cli -x mi dlg_list_ctx
```

**Expected behavior**
Contact of the callee should not be changed.

**Relevant System Logs**
Attached you can find a debug file of the test and trace files for both, caller and callee. Public IPs and domains have been changed. The following extract from the debug file shows the 200 OK reply, and the lines where the contact of the callee is replaced. We have added additional debug logs prefixed with TOPOH: to dlg_handlers.c in order to get more information.

```
May 10 01:56:14 [15601] DBG:core:build_res_buf_from_sip_res: copied size: orig:390, new: 583, rest: 212 msg=
SIP/2.0 200 OK
Via: SIP/2.0/WSS 75lov53a3gne.invalid;branch=z9hG4bK9492754
Call-ID: l2ihqnh92349u1ujd0mn
From: "AgentA" <sip:AgentA@sip.lsvon.net>;tag=ea1spnig9o
To: <sip:500@sip.lsvon.net>;tag=68ec15eb-149c-4898-9a36-d9f868ce26a4
CSeq: 4667 UPDATE
Session-Expires: 90;refresher=uac
Require: timer
Contact: <sip:X.did.fef.4a261cb4@10.132.40.116:8080;transport=ws>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub
Server: Asterisk PBX 16.9.0
Content-Length:  0

May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: TOPOH: contact_hdr <Contact: <sip:X.did.fef.4a261cb4@10.132.40.116:8080;transport=ws> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: TOPOH: advertised contact <Contact: <sip:X.did.fef.4a261cb4@10.132.40.116> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: TOPOH: dialog contact <sip:10.132.104.184:5060> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: TOPOH: message contact <sip:X.did.fef.4a261cb4@10.132.40.116:8080;transport=ws> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: Replacing old contact <sip:10.132.104.184:5060> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:dialog:dlg_update_contact: Updated contact to <sip:X.did.fef.4a261cb4@10.132.40.116:8080;transport=ws> for dialog 0x7fc6eb4e9c20 on leg 1
May 10 01:56:14 [15601] DBG:core:parse_headers: flags=ffffffffffffffff
```

The **if condition** in line 1289 of dlg_handlers.c is never met, and it must be in this case in order to skip the contact update.

```
if ((dlg->mod_flags & TOPOH_ONGOING) &&
        str_strcmp(&dlg->legs[leg].adv_contact, &contact_hdr) == 0) {
    LM_DBG("skip updating topo hiding advertised contact\n");
    return 0;
}
```

This condition is never met due to it is comparing the contact advertised to caller with the contact advertised to callee, and in this particular case they are not equal because transports are different. We made a small change just for testing and it worked, the contact update was skipped in 200 OK reply and the call flowed as it should.

```
str adv_hdr;
int peer_leg;

if (dlg->mod_flags & TOPOH_ONGOING) {
    if (leg == DLG_CALLER_LEG)
        peer_leg = callee_idx(dlg);
    else
        peer_leg = DLG_CALLER_LEG;
    adv_hdr.s = dlg->legs[peer_leg].adv_contact.s;
    adv_hdr.len = dlg->legs[peer_leg].adv_contact.len;
    if (str_strcmp(&adv_hdr, &contact_hdr) == 0) {
        LM_DBG("skip updating topo hiding advertised contact\n");
        return 0;
    }
}
```

**OS/environment information**

- Operating System: CentOS Linux 7.8.2003
- Caller: jsSIP 3.3.6
- Callee: Asterisk 16.9

**Additional context**
This behavior was found in a testing lab. We were working on a High-Availability Master-Backup cluster using keepalived. We were using jsSIP 3.3.6 as caller and Asterisk 16.9 as callee during these tests. The configuration is working fine when topology hiding is not used. jsSIP is connecting to OpenSIPS through WSS using Nginx as a WebSocket Proxy, and OpenSIPS communicates to Asterisk through UDP.

[callee_trace.txt](https://github.com/OpenSIPS/opensips/files/4606034/callee_trace.txt)
[caller_trace.txt](https://github.com/OpenSIPS/opensips/files/4606035/caller_trace.txt)
[debug.txt](https://github.com/OpenSIPS/opensips/files/4606060/debug.txt)

**Comment by razvancrainea** [comment]
This is correct - the contact presented by the user is stored in the `leg`'s structure, whereas the contact advertised to him is stored in the peer's `leg` structure - therefore the peer should be checked. I will soon push a fix for this - please re-test if possible with the latest code.

**Comment by dioris-moreno** [comment]
Hi @razvancrainea, 
I haven't tested yet, but I checked your commit and it seems the issue is fixed. 
Thanks
