### ISSUE TITLE
[BUG] The commit 298b090 breaks dispatcher module.

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#2110]
Hi All,
The commit 298b0901188ecaf970abe0656f07f7d441b2519a breaks dispatcher module.
I compiled by gcc версия 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)
Opensips branch 3.0

ERROR:core:sr_load_module: could not open module </usr/local/opensips-3/lib64/opensips/modules/dispatcher.so>: /usr/local/opensips-3/lib64/opensips/modules/dispatcher.so: undefined symbol: tmb

**Comment by liviuchircu** [comment]
Thank you for the report, @fedkis !  Taking care of this ASAP
