### ISSUE TITLE
[BUG]OpenSIPS as B2BUA - Invite with History-Info Problem

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2116]
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c9e61269f
main.c compiled on 12:56:11 May 16 2020 with gcc 8
```

**Describe the bug**
When OpenSIPS run as B2BUA and  an INVITE with the following History-Info hits the B2BUA
OpenSIPS doesn't respond and all!!! 

Here is the History-Info header that when I removed it from another opensips instance running as proxy then OpenSIPS B2BUA responded correctly and passed the call to the order side.

`History-Info: <sip:+30XXXXXXXX@sipdomain;user=phone?Reason=SIP%3Bcause%3D302%3Btext%3D%22Moved%20Temporarily%22>;index=1,<sip:+30XXXXXXXX@sipdomain;user=phone;cause=302?Reason=SIP%3Bcause%3D302%3Btext%3D%22Moved%20Temporarily%22>;index=1.1,<sip:+30XXXXXXXX@sipdomain;user=phone;cause=302>;index=1.1.1.`

**To Reproduce**
1) Create an OpenSIPS Instance as a B2BUA Only.
2) Allow custom_headers
`modparam("b2b_logic", "custom_headers", "P-Asserted-identity;Privacy;Diversion;History-Info;")
`
3) Apply a simple topology_hiding function

```
route[topology_hiding] {
	if(is_method("INVITE") && !has_totag() ) {
    		b2b_init_request("top hiding");
		exit;
    }
}
```

**Expected behavior**
OpenSIPS should pass the Call to the other side.

**Relevant System Logs**
Sorry I could collect more logs during this problem I had from the the B2BUA Instance as it its on production execpt from this one below 

```
ERROR:b2b_entities:b2be_db_insert: Sql insert failed
ERROR:core:db_do_insert: error while submitting query
```
which had to do with tag0 column which had smaller length and I did this to fix it : `alter table b2b_entities MODIFY tag0 char(255);` does this have to do with B2BUA not passing the call to the other side?

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git

thank you in advance

**Comment by rvlad-patrascu** [comment]
Hi @vtzan,

I couldn't reproduce this issue using that History-Info header. I also tried to use a from tag longer than 64 characters in order to trigger that DB error but still the call would work properly. Did you encounter the problem anymore after changing the DB column ?

**Comment by vtzan** [comment]
Dear @rvlad-patrascu,

I will close this issue. DB Alter for column size fixed the problem.

The second issue of b2bua not responding as I was describing in first place was with udp packet size > 1500 that didn't reached b2bua in network level. So were fine from opensips side ;-)

Best Regards
Vasilios Tzanoudakis
