### ISSUE TITLE
[BUG] Bad dialog json returns if several branches in callees 

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#2120]
Hello,
Function  static char *dlg_get_json_out(struct dlg_cell *dlg,int ctx,int *out_len) returns broken json if multiple callees in dialog:

        memcpy(p,",\"callees\":[",11);
        p+=11;
        DEC_AND_CHECK_LEN(len,11);

should be changed  to
        memcpy(p,",\"callees\":[",12);
        p+=12;
        DEC_AND_CHECK_LEN(len,12);

and json array must be closed by "]"

        memcpy(p,"]",1);
        p+=1;
        DEC_AND_CHECK_LEN(len,1);

Otherwise 'callee' : {'tag':""....},{'tag':""}

I found this error in 3.0.2
Thank you

**Comment by bogdan-iancu** [comment]
Thank you @fedkis , you are right - it is surprising how two bugs (the wrong initial len and the missing `]`) were compensating one each other, resulting in a valid json for one callee case.
