### ISSUE TITLE
[BUG] Stop media confused with start media

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#2121]
Hello,
Please fix the function rtpengine_stopmedia_f in rtpengine.c in master

static int rtpengine_stopmedia_f(struct sip_msg* msg, str *flags, pv_spec_t *spvar)
{
        return rtpe_function_call_simple(msg, OP_START_MEDIA, flags, spvar);
}

**Comment by bogdan-iancu** [comment]
The fix sounds logic to me :)
