### ISSUE TITLE
[BUG] use_workers paramеtеr doesn't work for SCTP

### ISSUE THREAD

**Issue by olegans1972** [OpenSIPS/opensips#2125]
**OpenSIPS version you are running**

version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cffc724
main.c compiled on 11:44:31 Apr 22 2020 with gcc 4.8.5

**Describe the bug**

I set next lines (opensips.cfg):

listen=sctp:192.168.50.11:5060 use_workers 2
listen=sctp:192.168.50.11:5070 use_workers 2
listen=sctp:192.168.50.11:5080 use_workers 2

**To Reproduce**

systemctl restart opensips

**Expected behavior**

https://www.opensips.org/Documentation/Script-CoreParameters-3-0
"USE_WORKERS n" - to set a different number of workers for this interface only (for UDP, SCTP and HEP_UDP interfaces only). This will override the global

**Relevant System Logs**

logs:
май 28 08:42:24 xx-spx-1 opensips[20100]: WARNING:core:new_sock_info: number of workers per non UDP <192.168.50.11> listener not supported -> ignoring...
май 28 08:42:24 xx-spx-1 opensips[20100]: WARNING:core:new_sock_info: number of workers per non UDP <192.168.50.11> listener not supported -> ignoring...
май 28 08:42:24 xx-spx-1 opensips[20100]: WARNING:core:new_sock_info: number of workers per non UDP <192.168.50.11> listener not supported -> ignoring...
май 28 08:42:24 xx-spx-1 opensips[20100]: INFO:proto_hep:get_hep_id_by_name: hep id <homer> not found!
май 28 08:42:24 xx-spx-1 opensips[20100]: INFO:core:fix_poll_method: using epoll as the IO watch method (auto detected)
май 28 08:42:24 xx-spx-1 opensips[20100]: Listening on
май 28 08:42:24 xx-spx-1 opensips[20100]: udp: 10.10.31.11 [10.10.31.11]:5060
май 28 08:42:24 xx-spx-1 opensips[20100]: sctp: 192.168.50.11 [192.168.50.11]:5060
май 28 08:42:24 xx-spx-1 opensips[20100]: sctp: 192.168.50.11 [192.168.50.11]:5070
май 28 08:42:24 xx-spx-1 opensips[20100]: sctp: 192.168.50.11 [192.168.50.11]:5080
май 28 08:42:24 xx-spx-1 opensips[20100]: hep_udp: 192.168.50.11 [192.168.50.11]:6060
май 28 08:42:24 xx-spx-1 opensips[20100]: Aliases:
май 28 08:42:24 xx-spx-1 opensips[20100]: sctp: VMS-STAGE:5060

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

I also wanted to clarify if I assign 2 worker to a specific interface. Does this mean that they will be used only for this interface and no longer for any other?

And let's say these workers got into overload and fell. Will they affect to all opensips? 

And in such cases it would be useful to be able to restart fallen workers without restarting all opensips

**Comment by bogdan-iancu** [comment]
Thank you @olegans1972 , problem fixed !
