### ISSUE TITLE
[BUG]  record_route() select IP

### ISSUE THREAD

**Issue by wangduanduan** [OpenSIPS/opensips#2128]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:16:22 Sep  5 2019 with gcc 4.4.7
```

**Describe the bug**

A is opensips,  ip 172.20.1.105 has a public ip 1.2.3.4
B is opensips, 172.20.1.106 has no public ip。

when invite from A to B, I use record_route()。but it add A's public IP 1.2.3.4:18627。

A and B is in same network, should record_route() add A's inner ip 172.20.1.105?  

```
listen=udp:172.20.1.105:18627 as 1.2.3.4:18627
```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
If a listener has an `advertised` IP (the `as 1.2.3.4` statement), it will use it **all** the time no matter what the destination IP is (private, public).
In your case, OpenSIPS A will all the time use `1.2.3.4` as its identity, in`VIA` or `Record-Route` hdrs.
