### ISSUE TITLE
[BUG]log hep proto type issue

### ISSUE THREAD

**Issue by bibace** [OpenSIPS/opensips#2137]
**OpenSIPS version you are running**
Version: 3.0.2

```
```

**Describe the bug**
use
trace("tid", "d","sip|xlog" ,"");

to send logs to heplify server

but in heplify-server and homer webapp, the xlog packets were saved to hep_proto_35_default_*, which is used for rtp.

I have contacted sipcapture, and I was told it's opensip hep module issue.

for logs, the hep proto type shoudl be 100 (0x64), not 35

Would like to know if any solutions.

**Comment by bogdan-iancu** [comment]
Thanks @bibace for the report.
