### ISSUE TITLE
mid_registrar_save() not forwarding REGISTER in aor throttling mode after unregister

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#2138]
Similar issue to #1805 

`calc_max_ct_diff` for aor throttling needs to ignore deleted contacts.
https://github.com/OpenSIPS/opensips/blob/519013bab5cdc5d9815c14b498d9a1d7f8021343/modules/mid_registrar/save.c#L2217

Also, is this suppose to count deleted contacts?
https://github.com/OpenSIPS/opensips/blob/519013bab5cdc5d9815c14b498d9a1d7f8021343/modules/mid_registrar/save.c#L2310

**Comment by ar45** [comment]
@liviuchircu I submitted a PR OpenSIPS#2138 for 3.0 which. is what I'm using. I believe it can be picked to 3.1 easily as the changes are minimal.

**Comment by liviuchircu** [comment]
Fixed by Aron in #2152.
