### ISSUE TITLE
[FEATURE]  sipp registered

### ISSUE THREAD

**Issue by gushenjie** [OpenSIPS/opensips#2142]
Log in with the same sipp account, can the former send a message to the client prompting for repeated login, mainly used for single sign-on

**Comment by razvancrainea** [comment]
Could you please provide more details about the expected outcome? TBH I don't understand exactly what this feature request is for.

**Comment by gushenjie** [comment]
Okay, for example, my account is sip: jack@192.168.2.70:5060, I use this account to log in on a desktop browser, and then I also log in to the account on another browser, I hope I You can receive a message on the first computer, for example, you have logged in on another account, at this time my upper layer redirects the content on the first PC to exit




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Răzvan Crainea"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 晚上9:58
收件人:&nbsp;"OpenSIPS/opensips"<opensips@noreply.github.com&gt;;
抄送:&nbsp;". o坏﹏楠孩"<791127866@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [OpenSIPS/opensips] [FEATURE]  sipp registered (#2142)





 
Could you please provide more details about the expected outcome? TBH I don't understand exactly what this feature request is for.

**Comment by razvancrainea** [comment]
This can already be achieved when you're saving the contacts. Check out the `c` and `f` flags of the [save()](https://opensips.org/docs/modules/3.1.x/registrar.html#func_save) function.

**Comment by gushenjie** [comment]
Sorry, I know to understand your answer. It can be pointed out in detail that setting this parameter in opensips.cfg can achieve my above requirements. Please help me, thanks
![image](https://user-images.githubusercontent.com/10531802/84886194-a9fa7c80-b0c6-11ea-9990-04fbb26d35dc.png)。

**Comment by gushenjie** [comment]
The effect I want to achieve is that the same sipp account can only be used on one terminal, the latest logged-in sipp account will overwrite the previous one, and the previous sipp account will receive the message of repeated logins

**Comment by razvancrainea** [comment]
You should use `save("location", "fc1");` - this will overwrite the previous contact.
There is however no standard way of informing the old contact that it has been removed from the registrar. What you can do is to catch the event of a [deleted contact](https://opensips.org/docs/modules/3.1.x/usrloc.html#event_E_UL_CONTACT_DELETE) and do your own logic of informing the SIP application about the deletion.

**Comment by gushenjie** [comment]
First of all, thank you for your patience and guidance. I used the save ("location", "fc1") method you said. But can I monitor where the deleted contacts are under guidance, is it used in the opensips.cfg file? Can you demonstrate, thank you very much

**Comment by gushenjie** [comment]
I have tried many ways here, but still have not achieved the function I want, can you give me a sample code? Thank you very much

> You should use `save("location", "fc1");` - this will overwrite the previous contact.
> There is however no standard way of informing the old contact that it has been removed from the registrar. What you can do is to catch the event of a [deleted contact](https://opensips.org/docs/modules/3.1.x/usrloc.html#event_E_UL_CONTACT_DELETE) and do your own logic of informing the SIP application about the deletion.

I have tried many ways here, but still have not achieved the function I want, can you give me a sample code? Thank you very much

**Comment by gushenjie** [comment]
I have tried many ways here, but still have not achieved the function I want, can you give me a sample code? Thank you very much
