### ISSUE TITLE
rr_param ;did= is missing in record_route 

### ISSUE THREAD

**Issue by varghesepaul** [OpenSIPS/opensips#2148]
Issue only in 3.1.0-beta

The dialog id in record route doesn't have any rr_param  ( ;did=) 
Currently : 
Record-Route: <sip:10.201.17.76;r2=on;lr6b91.9064b111>

Expected  
Record-Route: <sip:10.201.17.76;r2=on;lr**;did=**6b91.9064b111>

**OpenSIPS version you are running**

```
3.1.0-beta
```

**Describe the bug**
In 3.1.0-beta branch , we are passing only dialog_id , not with the rr_param. 
https://github.com/OpenSIPS/opensips/blob/3.1/modules/dialog/dlg_handlers.c#L168
	if (dlg_get_did_buf(dlg, &id) < 0)
		return -1;
Here the id is always dialogid --> 6b91.9064b111 not the buf ( it have ;did=) 
	if (d_rrb.add_rr_param( req, &id)<0) {
		LM_ERR("failed to add rr param\n");
		return -1;
	}

**To Reproduce**
1. create_dialog()
2. record_route()

**Expected behavior**
Record-Route: <sip:10.201.17.76;r2=on;lr;did=6b91.9064b111> 

Since the lr is appended with dialogid, client side not able to parse the route parameter.

**Comment by bogdan-iancu** [comment]
Thank you @varghesepaul for the report, the fix is available in the git repo.
