### ISSUE TITLE
[BUG]CRITICAL:permissions:subnet_table_insert: subnet table is full

### ISSUE THREAD

**Issue by fluke87** [OpenSIPS/opensips#2149]
A feature was found in the operation of the permissions module. The module loads no more than 128 entries from the address / table
This restriction only applies to subnet entries of type 0.0.0.0/0

Entries of address type with a prefix of 32 are not subnect to restriction.

Is it possible to remove restrictions from subnect entries or is this a mistake?

I created a question here, since the intended functionality does not actually work.

OpenSIPS v3.0.2. Install from APT repos opensips site
Postgresql v9.4
OS Debian 10

Sincerely, Alexander

**Comment by bogdan-iancu** [comment]
@fluke87 , by implementation, the module works with limited number of subnets. This limit is pre-defined, at compile time, to 128 , see https://github.com/OpenSIPS/opensips/blob/3.0/modules/permissions/hash.h#L105.

If you want to change it, you need to alter the sources and re-compile.

This is not a bug, but a lack of flexibility in how many subnets may be handled. If you want, you can open a feature request to try to make it configurable.
