### ISSUE TITLE
The "received" string in location table should not be null

### ISSUE THREAD

**Issue by robdyck** [OpenSIPS/opensips#2154]
**OpenSIPS version you are running**

```version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 424e247d6
main.c compiled on 12:50:25 Mar  6 2020 with gcc 9

```

**Describe the bug**

The "received" string is only stored if a NAT check is done. If the NAT check is not done, for instance in the IPV6 context, then a call to a GRUU subscriber cannot be routed.

**To Reproduce**

        if ($af == "INET") {
        if (nat_uac_test(2)) {
                if (is_method("REGISTER")) {
                        fix_nated_register();
                        setbflag(bf_NAT);
                } else {
                        fix_nated_contact();
                        setflag(mf_NAT);
                }
        }
        } # end of if ($af == "INET")

**Expected behavior**

Call routes to the GRUU subscriber.

**Relevant System Logs**

Jun 24 10:09:34 [1682250] Branch index is 0 
Jun 24 10:09:34 [1682250] 
Jun 24 10:09:34 [1682250] The IPV6 related flags are mf_INVITE_FROM_IPV6 mf_SRC_WS and bf_IPV6_CONTACT bf_CALLEE_IPV6 bf_DST_WS
Jun 24 10:09:34 [1682250] IPV6 to IPV6, rtpproxy not required
Jun 24 10:09:34 [1682250] Set up the reply route
Jun 24 10:09:34 [1682250] return from per_branch_ops
Jun 24 10:09:34 [1682250] DBG:core:mk_proxy: doing DNS lookup...
Jun 24 10:09:34 [1682250] DBG:core:sip_resolvehost: no port, has proto -> do SRV lookup!
Jun 24 10:09:34 [1682250] DBG:core:get_record: lookup(_wss._tcp.1mkfmvkg7s37.invalid, 33) failed
Jun 24 10:09:34 [1682250] DBG:core:sip_resolvehost: no valid SRV record found for _wss._tcp.1mkfmvkg7s37.invalid, trying A record lookup...
Jun 24 10:09:34 [1682250] CRITICAL:core:mk_proxy: could not resolve hostname: "1mkfmvkg7s37.invalid"
Jun 24 10:09:34 [1682250] ERROR:tm:uri2proxy: bad host name in URI <sip:d34p4lqm@1mkfmvkg7s37.invalid;transport=wss>
Jun 24 10:09:34 [1682250] ERROR:tm:t_forward_nonack: failure to add branches

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
Compiled from git source

**Additional context**

**Comment by bogdan-iancu** [comment]
If there is a must for your scenario to have the `received` populated, be sure you call `fix_nated_contact();` - in your case, GRUU is detected during the registration, just use the function
