### ISSUE TITLE
[BUG] How to edit database_admin_url?

### ISSUE THREAD

**Issue by CodingForGame** [OpenSIPS/opensips#2156]
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 16:52:20 Jun 30 2020 with gcc 9

I don`t want to install mysql in local,so How to edit database_admin_url？

When I run this script " database create ",it shows "please provide or fix the 'database_admin_url'"

**Comment by liviuchircu** [comment]
hey @CodingForGame !  The [configuration docs](https://github.com/opensips/opensips-cli#configuration) should be of help here.  TL;DR: one way to do it is via the `~/.opensips-cli.cfg` file:

```
[default]
database_admin_url: mysql://root@127.0.0.1 # this will still ask for password
# database_admin_url: mysql://root:myrootpassword@127.0.0.1 # no prompt!
```
