### ISSUE TITLE
How should I deploy database correctly？

### ISSUE THREAD

**Issue by CodingForGame** [OpenSIPS/opensips#2158]
version: opensips 3.0.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cf2c4903f
main.c compiled on 13:26:24 Jul  1 2020 with gcc 9

I had already include db_mysql module,and I edit opensips.cfg:

`
loadmodule "db_mysql.sp”
loadmodule "auth.so"
loadmodule "auth_db.so"
modparam("usrloc", "db_mode", 2)
modparam("auth", "calculate_ha1", yes)
modparam("auth_db", "password_column", "password")
if (!www_authorize(“192.168.1.103”, "subscriber")) {
  www_challenge("192.168.1.103", "0");
  break;
};
`

bun it doesn`t work , nothing shows

`
-> opensips reastart
  Listening on 
             udp: 127.0.0.1 [127.0.0.1]:5060
  Aliases: 

 ->vim /usr/local/etc/opensips/opensips.cfg
 ->opensips restart
 ->opensips restart
 ->opensips restart
 `

I guess that's the problem 

`if (!www_authorize(“192.168.1.103”, "subscriber")) {
  www_challenge("192.168.1.103", "0");
  break;
};`

**Comment by bogdan-iancu** [comment]
@CodingForGame , for usage issues/question the appropriate channel is [user's mailing list ](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)

**Comment by CodingForGame** [comment]
Sorry ，I am unfamiliar with issues/question and [user's mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)，and don`t kown how to use it.

But I still eager to know how to solve the problem
