### ISSUE TITLE
[FEATURE] Digest authentication on a DB side

### ISSUE THREAD

**Issue by andr-04** [OpenSIPS/opensips#2159]
Hello. I'm new with OpenSIPS. I have a stored function in a database which accepts `username`, `realm`, `ha2`, `nonce` and `digest_response`. Basing on this and the raw password stored in a database, it calculates inside `ha1` and `digest_reference` to compare with `digest_response` and returns the verdict: passed or not.

This approach gives a high-security level as a benefit. How it can be used with OpenSIPS? Thanks.

**Comment by bogdan-iancu** [comment]
@andr-04, you can easily do this right now. After you use the www|proxy_challenge() function and you get the request with the credentials, just use the avp_db_query() function (avpops module) to run your SQL procedure with the parameters extracted from the SIP request.
