### ISSUE TITLE
[CRASH] Usrloc segfault in parsing wrong db response

### ISSUE THREAD

**Issue by adrien-martin** [OpenSIPS/opensips#2161]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

Also happens with version 2.4.8, 3.0.3 and 3.1.0.

**Crash Core Dump**

https://gist.github.com/adrien-martin/259f0670c69dc5730654adbd0412cde6 (for 2.4.6, can get one for 2.4.8 if useful).

Gdb shows an error in modules/usrloc/dlist.c:203
The query is ```select received, contact, socket, cflags, path, contact_id from location where expires > <timestamp> and contact_id % 30 = <part_id>```)

But it looks more like an answer to :
```select contact_id,contact,expires,q,callid,cseq,flags,cflags,user_agent,received,path,socket,methods,last_modified,sip_instance,kv_store,attr from location where username='username' order by q``` which is also sent to the database, for the re-registrations i think.

```val = ROW_VALUES(row) + 3; /* cflags */``` has a type of DB_DOUBLE and a value of -1 (q) and first row is contact_id.

**Describe the traffic that generated the bug**

No calls.
Seems related to the expiration of some registrations (all of them use UDP).

**To Reproduce**

The crash seems to happen in the periodic usrloc cleanup when parsing the answer to :
```select received, contact, socket, cflags, path, contact_id from location where expires > <timestamp> and contact_id % 30 = <part_id>```
It only happen after I enabled `tls_mgm` in db mode (same database).

**Relevant System Logs**

```
/usr/sbin/opensips[16613]: CRITICAL:core:handle_worker: dead child 22 (EOF received), pid 16610
/usr/sbin/opensips[16613]: CRITICAL:core:handle_tcp_worker: dead tcp worker 6 (EOF received), pid 16610
/usr/sbin/opensips[16556]: INFO:core:handle_sigs: child process 16610 exited by a signal 11
/usr/sbin/opensips[16556]: INFO:core:handle_sigs: core was generated
/usr/sbin/opensips[16556]: INFO:core:handle_sigs: terminating due to SIGCHLD
/usr/sbin/opensips[16589]: INFO:core:sig_usr: signal 15 received
/usr/sbin/opensips[16591]: INFO:core:sig_usr: signal 15 received
/usr/sbin/opensips[16590]: INFO:core:sig_usr: signal 15 received
```

**OS/environment information**
 - Operating System:  Debian 9 (Stretch)
 - OpenSIPS installation:  Debian package from apt.opensips.org stretch 2.4-release
 - other relevant information:

**Additional context**

Usrloc is configured in DB mode :
```
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "6")
modparam("usrloc", "working_mode_preset", "sql-only")
modparam("usrloc", "regen_broken_contactid", 1)
```

It is a Postgresql database.

Edit : tests with versions 3.0.3, 3.1.0-beta and 3.1.0.

**Comment by adrien-martin** [comment]
While testing some TLS configurations I see i only happen when tls_mgm is using the database.

**Comment by adrien-martin** [comment]
As a co-worker pointed out, this looks quite similar to #1579.
But we are not using any SQL nor TCP proxy.
The setup does not use clusterer module either.

**Comment by adrien-martin** [comment]
> Any updates here? No progress has been made in the last 15 days, marking as stale. Will close this issue if no further updates are made in the next 30 days.

Please don't close, the crash still occurs.

**Comment by adrien-martin** [comment]
In the Postgresql server's log, the query present in the crash dump is sent 2-15s before the crash happen.
In a pcap dump there are 2 queries sent at the same time (before any response or even TCP ACK).
The queries are :
```
select received, contact, socket, cflags, path, contact_id from location where expires > timestamp and contact_id % 30 = 0
delete from location where expires<timestamp+1 AND expires!=0
```
Could it be a concurrency problem in using the libpq, maybe just with usrloc ?



[Crash_Usrloc_TLS_Postgresql.tar.gz](https://github.com/OpenSIPS/opensips/files/5095483/Crash_Usrloc_TLS_Postgresql.tar.gz)

**Comment by liviuchircu** [comment]
@adrien-martin I've been looking at this issue for quite a while now, but failed to see any obvious pattern.  Having not worked with `db_postgres` for the most part, I have little intuition on its connection management logic...

Still, the symptoms seem to hint at some sort of conflict between processes and their PG connections.  Here is a crazy example:  what if a Postgres connection was incorrectly shared between two OpenSIPS processes, maybe created at `mod_init()` and inherited from there?  For the most part, it would work fine!  But, sometimes, when the processes would concurrently push their queries, the results would get mixed up, potentially leading to segfaults due to unexpected data.

So the follow-up question would be:  can we refute the above or is it actually what's going on?

**Comment by adrien-martin** [comment]
I don't know how to refute of validate this with data, but i would say that it would make sense.
Especially about the `tls_mgm` db connection, no queries in this module trigger the crash but it does not happen when not using the database.
I better understand #1579/https://github.com/OpenSIPS/opensips/commit/4c29eedc3dbdd9e74781cd81f626b64c71a4e16d too.

All modules use the same database settings (same `modparam("...|...", "db_url", ...)`).
Complete list of modules using this database are: sip_trace|tls_mgm|auth_db|permissions|domain|acc|usrloc|drouting|avpops.
All of them seem to call `db_func_t.init` one way or another.
Both `netstat` and `pg_stat_activity` show only one connection.
```
# opensipsctl ps
Process::  ID=0 PID=19701 Type=attendant
Process::  ID=1 PID=19702 Type=MI FIFO
Process::  ID=2 PID=19703 Type=time_keeper
Process::  ID=3 PID=19704 Type=timer
Process::  ID=4 PID=19705 Type=SIP receiver udp:0.0.0.0:5060
Process::  ID=5 PID=19706 Type=SIP receiver udp:0.0.0.0:5060
Process::  ID=6 PID=19707 Type=SIP receiver udp:0.0.0.0:5060
Process::  ID=7 PID=19708 Type=SIP receiver udp:0.0.0.0:5060
Process::  ID=8 PID=19709 Type=TCP receiver
Process::  ID=9 PID=19710 Type=TCP receiver
Process::  ID=10 PID=19711 Type=TCP receiver
Process::  ID=11 PID=19712 Type=TCP receiver
Process::  ID=12 PID=19713 Type=TCP receiver
Process::  ID=13 PID=19714 Type=TCP receiver
Process::  ID=14 PID=19715 Type=TCP receiver
Process::  ID=15 PID=19716 Type=TCP receiver
Process::  ID=16 PID=19717 Type=Timer handler
Process::  ID=17 PID=19718 Type=TCP main
```

**Comment by adrien-martin** [comment]
I was wrong about the probing of TCP/TLS drouting gateways, it still trigger without.
Happen also when only listening on UDP.
Enabling/disabling `tls_mgm` db mode still has an impact tough.

Updating the first message.

**Comment by liviuchircu** [comment]
Hey, @adrien-martin!  Thank you for your find -- the code seems to confirm our hypothesis so far!  Would you mind trying out this patch for `tls_mgm` on latest OpenSIPS `2.4`, so that it doesn't create any process-shared DB connections anymore?  Thanks!

```
git apply <(base64 -d <<EOF | gzip -dc
H4sIAHhhPl8AA41UUW/aMBB+Jr/i2gcEmECAFooqJrR2D5PoOlXr26TIiR1iERxkG8rW8t93NgEC
Zd3yYp/vO999353DRJKA70+FAdqe52yZcd02mQ7n0/lubcUQ/d3nCcn4Gq4HNxFPBl3Wag17nWHQ
v4kS6ARB/+rK833/o9s9QsiHGcZj8DvBsNkHYpcBjMceaEONiCFOqYKGxbJ8ToUM6WoBI/j2PJnc
erCHCWkAMEMopDC1VS5Y/dYjZWeciqxwW1tROUPIu/gsp2wXv3Na0zkZ10blv079NthWOOUmTKlk
OqUzHhox5/lyX4wl2etfIzvS6/cdSYxXy9jAVpmQrxe5Mhp26whePajsSDUBoN0osGBPBM3Ebywg
l5AsZew2jTaGBBZbfBiiuF7kUvMTVIlQE1HF9gjkn1614Mp3QroCjrCkclD4H1DYuNZt+47T5Bo/
7HWbw60oe1GPG+rkwK/KeBJqtQrNfNEEZ8WZ2FpuUjRXK66KgdHFIUK4NLvDet3dpbhZKolV2IJI
pcIwKkpacZZrXmNRmLLMzhE63H4/eMRGI8lMyBmYlMP9ZyhuhhdhUnfG10IbIaegYyUWZg+wCth4
kUDtTL1QrcL7U0vPKmA16wadntUM10Gz8x+iFTQDZLmxREvoc8/CI6/I2ZZ34R5eFC5V1tLw9gYX
NYuATyPoWNMZoxF8f3q8Cx8e758nX1BZUillJGiiUm4IUKU4l5KXhsZlqe3lLRrg6qkektfrlgje
O3kI756+/qhdJlRknIHJD0+BA6OGRhQn/ZDlp7zcdrDUalLZuLJKRW5K/5Lzz93DAv4AhxOwE04F
AAA=
EOF
)
```

**Comment by liviuchircu** [comment]
Excellent!  I suggest we backport it immediately so it makes it into today's nightly, as the bug was pretty serious.  Thank you for your patience and watchful eyes on this issue!

**Comment by adrien-martin** [comment]
Thanks for your help!
