### ISSUE TITLE
[FEATURE] RE-INVITE support on siprec module

### ISSUE THREAD

**Issue by pateldp** [OpenSIPS/opensips#2167]
**Is your feature request related to a problem? Please describe.**

While working as a siprec client. It creates a problem when the siprec server sends the re-invite as a refresher. The siprec server expect the response on that and timeout after few seconds and send BYE and stops the recording.

**Describe the solution you'd like**

The siprec module should handle the within dialog requests for the dialog which is generated by siprec  module and response accordingly.

**Implementation**
 
  - Component: `b2b_entities` module, `siprec` module 
  - Type: 
  - Name: 

**Describe alternatives you've considered**

**Additional context**

**Comment by razvancrainea** [comment]
This has been implemented in ec6b5c4e0e714a7fc81d215950a33a6b7b72dee0.
