### ISSUE TITLE
[BUG] Rate cacher incorrectly lists carriers that don't have rates

### ISSUE THREAD

**Issue by osgjps** [OpenSIPS/opensips#2169]
```
root@opensips-dev:~/gitroot/opensips# opensips -V
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ac2329474
main.c compiled on 15:57:37 Jul 10 2020 with gcc 9
```

**Describe the bug**

If a rate table does not have a rate for a particular prefix, it is still listed in the list of vendors to use.
**To Reproduce**

Ratesheet 1 for vendor1 has a rate for 1855, price 0.00
Ratesheet 2 for vendor2 does not have have a rate for 1855
Client rate sheet has a rate for 1855, price 1.00.

The debug from the Opensips console reads:

Jul 10 19:56:50 [16547] INFO:rate_cacher:bulk_cost_based_fetching: Client price is 1.000000
Jul 10 19:56:50 [16547] INFO:rate_cacher:bulk_cost_based_fetching: Vendor vendor2 price is 0.000000
Jul 10 19:56:50 [16547] XXX - Out of the vendor1,vendor2 carriers, we should only use vendor1,vendor2 in the provided order

**Expected behavior**

Vendor2 should be listed, but vendor1 should not.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Ubuntu 19.10
 - OpenSIPS installation: Git checkout
 - other relevant information:

**Additional context**

**Comment by osgjps** [comment]
I believe the bug surfaces because of this block in bulk_cost_based_fetching():
`
		ret = get_rate_price_prefix(carr_it->trie,dnis,&dst_matched_len);
		if (ret == NULL) {
			/* no price found for carrier, do not use it */
			unlock_bucket_read( carr_entry->lock );
			result[i] = 0;
			continue;
		}
`
That sets the rate for that particular vendor to 0 and that will almost always pass the "is this route profitable or at least break even" test.

I changed the line to read:
`
result[i] = 9999999;
`
to set the cost of the route ridiculously high, but I'm not sure if that's the proper way of solving this issue.

**Comment by vladpaiu** [comment]
Hello,

Thanks for reporting this. 
That looks to me to be the easiest fix - committed.

Regards,
Vlad
