### ISSUE TITLE
Clustering presence service in active-active mode with load balancer in-front deletes subscriptions incorrectly

### ISSUE THREAD

**Issue by bhanukarumudi** [OpenSIPS/opensips#2170]
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6bc6517
main.c compiled on 00:21:36 Jun 30 2020 with gcc 4.8.5

**Describe the bug**
opensips cluster created in active-active mode with different sharing tags. When there is a publish for a user, both the active opensips servers are trying to send notify. Of this only one server is the owner of the sharing tag and not the other. The notify sent by the other active who is not owner of the sharing tag is not able to sent the notify via load balancer and after few re-transmissions is deleting the subscription from active watcher table incorrectly. If I don't use load balancer and use direct physical IP, it works fine.

**To Reproduce**

1. Start opensips1 whose presence sharing_tag is 'A'
2. Start opensips2 whose presence sharing_tag is 'B'
3. Connect 2 client via loadbalancer(nginx in my case) and lets say both are connected to opensips1 whose tag is 'A'
4. Each user subscribed for the other's presence
5. At this state, all looks good.
6. Change the status of one of the user and see than both opensips1 & opensips2 are trying to send notify to the client. Opensips2 is not the owner of the subscription and still is receiving replicated publish and trying to send notify that fails and hence deleting that entry from active_watchers table. There by this subscription is lost.

**Expected behavior**
In cluster mode, the non-owner is not suppose to sent notify for the publish

**Relevant System Logs**
Sharing selected lines only to reduce the amount
Jun 30 14:56:52 [27597] DBG:presence:handle_replicated_publish: replicated PUBLISH for 1000 / 10.207.232.168
Jun 30 14:56:52 [27597] DBG:core:bin_pop_str: Popped: 'presence' [8]
Jun 30 14:56:52 [27597] DBG:presence:search_event: start event= [presence]
Jun 30 14:56:52 [27597] DBG:core:bin_pop_str: Popped: 'a.1593543281.26230.3.1' [22]
Jun 30 14:56:52 [27597] DBG:presence:handle_replicated_publish: Updating presentity
Jun 30 14:56:52 [27597] DBG:presence:get_subs_db: querying database table = active_watchers
Jun 30 14:56:52 [27597] DBG:presence:get_subs_db: found 1 dialogs
Jun 30 14:56:52 [27597] DBG:core:grep_sock_info: checking if host==us: 12==12 &&  [10.207.234.5] == [10.207.234.8]
Jun 30 14:56:52 [27597] DBG:core:grep_sock_info: checking if port 5060 matches port 5060
Jun 30 14:56:52 [27597] DBG:presence:printf_subs:
Jun 30 14:56:52 [27597] INFO:presence:publ_notify: notify
Jun 30 14:56:52 [27597] DBG:presence:update_shtable: record not found in hash table
Jun 30 14:56:52 [27597] DBG:presence:notify: record not found in subs htable
Jun 30 14:56:52 [27597] INFO:presence:send_notify_request: NOTIFY sip:1001@10.207.232.168 via sip:1001@10.207.232.168:52076;ob on behalf of sip:1000@10.207.232.168 for event presence, to_tag=97cb-7779dc186d049b765743a002e5bf08af, cseq=4
Jun 30 14:56:52 [27597] DBG:presence:next_turn_phtable: new current turn is 2 for <sip:1000@10.207.232.168>
Jun 30 14:56:52 [27597] DBG:proto_bin:bin_read_req: tcp_read_req end
Jun 30 14:56:52 [27599] DBG:tm:utimer_routine: timer routine:4,tl=0x7f0accab2f98 next=(nil), timeout=128000000
Jun 30 14:56:52 [27599] DBG:tm:retransmission_handler: retransmission_handler : request resending 
Jun 30 14:56:53 [27599] DBG:tm:retransmission_handler: retransmission_handler : done
Jun 30 14:56:53 [27600] DBG:core:handle_worker: read response= 7f0accab27f8, 1, fd -1 from 14 (27597)
Jun 30 14:56:53 [27597] DBG:clusterer:do_action_trans_5: Sent ping to node [1]
Jun 30 14:56:53 [27597] DBG:proto_bin:bin_read_req: Using the global ( per process ) buff
Jun 30 14:56:53 [27597] DBG:proto_bin:bin_parse_headers: received a COMPLETE message
Jun 30 14:56:54 [27599] DBG:presence:msg_presentity_clean: cleaning expired presentity information
Jun 30 14:56:54 [27599] DBG:db_mysql:has_stmt_ctx: ctx found for presentity
Jun 30 14:56:56 [27599] DBG:presence:delete_db_subs: delete subs
Jun 30 14:56:56 [27599] DBG:db_mysql:db_mysql_do_prepared_query: conn=0x7f0ace7624b0 (tail=139684390182112) MC=0x7f0ace75fda8
Jun 30 14:56:56 [27599] DBG:db_mysql:db_mysql_do_prepared_query: new query=|delete from active_watchers where presentity_uri=? AND event=? AND to_tag=?|
Jun 30 14:56:56 [27599] DBG:tm:final_response_handler: done

**OS/environment information**
 - Operating System: RHEL7
 - OpenSIPS installation: 2.4 latest source from git
 - other relevant information:

**Additional context**

**Comment by bhanukarumudi** [comment]
Hi , Followed the workflow using the logs see that in presence/notify.c, there are methods receiving sh_tags as arguments and its coming as null sometimes in a cluster environment.

Made below changes in my local copy and it started working. Could you please check if this is the issue?

int get_subs_db(str* pres_uri, pres_ev_t* event, str* sender,
                subs_t** s_array, int* n, str **sh_tags)
{
        sh_tags = is_presence_cluster_enabled() ? get_all_active_shtags() : NULL;   -----------> added this in this function

AND

subs_t* get_subs_dialog(str* pres_uri, pres_ev_t* event, str* sender, str **sh_tags)
{
        sh_tags = is_presence_cluster_enabled() ? get_all_active_shtags() : NULL;   ----------->added this in this other function

**Comment by bogdan-iancu** [comment]
@bhanukarumudi , I agree, there is something strange over there.....

**Comment by bogdan-iancu** [comment]
I'm not sure I 100% understand your scenario. If you use a LB in front of multiple presence servers, how comes that the a publish triggers actions on BOTH presence servers ??
In the LB scenario, the sh_tag controls only the actions takes by the presence themselves, as notifying the subscription upon a timeout <- is this self triggered action and not an action triggered by an external event, like receiving a PUBLISH.
Also, in the LB scenario, it is assumed that only ONE presence server receives a  PUBLISH and that presence server (despite the sh_tag settings) is responsible in updating all the subscription as it is the only one aware of that publishing.

So, could you explain me how comes that you have two opensips servers reacting for a single PUBLISH ?

**Comment by bhanukarumudi** [comment]
Hi, sorry for delay in response. somehow the notifications email missed my attention.

I also do not understand what the publish is being received by both severs and action is being taken by both.
This is a publish being received externally. This is not self triggered.

Here also, I see that only 1 server is receiving the publish from external client via LB. This server is taking action as well as it is replicating the publish to the peer active opensips server who is also trying to take action on publish though it doesnt own the sharing tag and ending up deleting the entry in active watchers table after few attempts to send the notifications out.

**Comment by bhanukarumudi** [comment]
@bogdan-iancu, Could you please check and let me know if you need any additional details?.

**Comment by bhanukarumudi** [comment]
@bogdan-iancu, Could you please check and let me know if you need any additional details?.

**Comment by bhanukarumudi** [comment]
This is still an issue. How can we reopen this item?
