### ISSUE TITLE
[BUG] send tcp message use fixed port

### ISSUE THREAD

**Issue by wangduanduan** [OpenSIPS/opensips#2174]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:16:22 Sep  5 2019 with gcc 4.4.7
```

**Describe the bug**
User --UDP--> ProxyA --TCP--> ServerB

ProxyA:
```
listen=udp:192.168.60.101:18628
listen=tcp:192.168.60.101:18627
```

i want ProxyA user fixed tcp port proxy message to ServerB:

so i use $fs.

```
$fs = "tcp:192.168.60.101:18627"
t_relay();
exit;
```

but opensips always ***use random tcp port*** send message to ServerB。is this normal ? 

Thanks!

**To Reproduce**

**Expected behavior**
send tcp message use fixed port

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@wangduanduan , this is how TCP works. All the time when a new TCP connection is created, an ephemeral port is assigned by OS as source port.
It is not a bug, it is normal TCP.
