### ISSUE TITLE
[BUG] mid-registrar lookup does not show all branches in request route

### ISSUE THREAD

**Issue by ryan-netizen** [OpenSIPS/opensips#2175]
**OpenSIPS version you are running**

```
version: opensips 3.0.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 16:18:49 Jun 30 2020 with gcc 4.8.5
```

**Describe the bug**

**To Reproduce**
Example:
1. Configure mid-registrar
2. Register multiple(2 to 3) contacts per AOR. 
3. After lookup and iterate over branches using below code
```
$var(i) = 0;
while ($(branch(socket)[$var(i)]) != null) {
    xlog("branch flags $(branch(flags)[$var(i)]) and $(branch(socket)[$var(i)]) \n");
    $var(i) = $var(i) + 1;
}
```
4. You would notice that above loop would not give you total branches. In my test i have registered 4 devices to single AOR. 
So, in request route i only see 3 logs
```
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: branch flags  and udp:10.152.0.6:11037
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: branch flags  and udp:10.152.0.6:11037
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: branch flags  and udp:10.152.0.6:11037
```

But in branch route i can see all(4) of branches. 
```
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: INFO:[R-CORE-BRANCH:1994d268750770ee1dcf631e21731af6@sip01.com.au] -> for unknown with flags delay  with sip:687-demo@10.13.0.11 and sip:29.32.19.22:5060
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: INFO:[R-CORE-BRANCH:1994d268750770ee1dcf631e21731af6@sip01.com.au] -> for unknown with flags   with sip:687-demo-0x5637b581e060@182.97.49.177:37733 and sip:182.97.49.177:37733
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: INFO:[R-CORE-BRANCH:1994d268750770ee1dcf631e21731af6@sip01.com.au] -> for unknown with flags   with sip:687-demo-0x55bc323a7440@207.38.65.299:47883 and sip:207.38.65.299:47883
Jul 16 20:05:19 m-kserver-1 /usr/sbin/opensips[19526]: INFO:[R-CORE-BRANCH:1994d268750770ee1dcf631e21731af6@sip01.com.au] -> for unknown with flags   with sip:687-demo-0x562bb104ea10@207.38.67.51:60318 and sip:207.38.67.51:60318
```
5. But in branch route you would be able to see all the branches

**Expected behavior**
Branches should be visible in request route like they are in branch route

**Comment by liviuchircu** [comment]
Hey, @ryan-netizen!  This is a classic OpenSIPS gotcha, since the `$branch` variable only lets you access branch indexes `1` - `3`, since they were _appended_ in addition to the "default" branch, at index `0`.  The properties of branch `0`, being the default branch, which is naturally present despite not doing any `append_branch()` or `mid_registrar_lookup()` operations are accessed with a separate set of variables, such as:

* `$ru`
* `$du`
* `$socket_out`

**Comment by liviuchircu** [comment]
To give you another example:  if `mid_registrar_lookup()` only produces 1 contact (thus OpenSIPS will only fork out 1 branch), the `$branch` variable shouldn't display any data at all, and you would only notice changes within `$ru`, `$du` and `$socket_out`.

**Comment by ryan-netizen** [comment]
@liviuchircu sorry for coming late here and thanks for the detailed explanation. I performed some testing just to build my opensips knowledge. So, Lets say if I had two contacts per AOR, after mid-registrar lookup i saw, my $ru, $du was populated with first contact params, and second contact param i was able to get through $branch(with index 0) variable in request route. 

**In request route the branch values get at index 0, shows up at index 1 inside branch route. And values in $ru and $du inside request route are available at index 0 inside branch route.** 

Are not both contradicting ? Sorry for my lack to knowledge here.

**Comment by liviuchircu** [comment]
hey, @ryan-netizen, you pretty much got it right.

Regarding your branch route observation: from the looks of it, the branch data is destroyed internally during `t_relay()`, since it populated its outgoing branches, so the branch set should be reset.  It follows that the `$branch` variable won't print out much within a `branch_route` (which, in turn, is invoked during `t_relay()`, after the above cleanup), nor should it be used in the first place, since it's too late to manipulate your branch set -- it's already being forked out!

**Comment by ryan-netizen** [comment]
@liviuchircu thank you much appreciated. 
Based upon your above explanation, i wanted to ask, what route should be used to remove branches for a specific user-agent. 
And i also think snippet at below link if used in request route would miss the branch0(populated with $ru and $du). Because it would be executed for if lookup results into more then 2 contacts, and for only branch1. 

https://www.opensips.org/Documentation/Script-CoreFunctions-3-1#toc29
