### ISSUE TITLE
[BUG] ERROR:proto_wss:ws_process: Made 4 read attempts but message is not complete yet - closing connection

### ISSUE THREAD

**Issue by wangduanduan** [OpenSIPS/opensips#2182]
**OpenSIPS version you are running**

```
version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:16:22 Sep  5 2019 with gcc 4.4.7
```

**Describe the bug**

i user jssip with webrtc to connect opensips.

jssip register to opensips is succeed, but when jssip make call, opensips will log error, and the websocket connection will be closed.

```
ERROR:proto_wss:ws_process: Made 4 read attempts but message is not complete yet - closing connection
```

and when i use wireshark to capture the tcp packets, it show opensips send TCP RESET to my compute.

**To Reproduce**

**Expected behavior**

WebSocket will not disconnected.

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
This is not a bug, just a configuration problem. Make sure to tune the [wss_max_msg_chunks](https://opensips.org/docs/modules/3.1.x/proto_wss.html#param_wss_max_msg_chunks) according to your needs.

**Comment by wangduanduan** [comment]
thank you, it work. @razvancrainea
