### ISSUE TITLE
[CRASH] 2.4.7 Segfault

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2186]
**OpenSIPS version you are running**

```
$ opensips -V
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6e2f1d2e2
main.c compiled on 19:33:06 Jul  7 2020 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/VhJbVa27

**Describe the traffic that generated the bug**

Unknown

**To Reproduce**

Not reproduced

**Relevant System Logs**

https://pastebin.com/QXDgSsGj

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
Just happened again.

Backtrace: https://pastebin.com/2eSGy8yh
Logs: https://pastebin.com/UVhzrxjS

**Comment by bogdan-iancu** [comment]
Hi Ben,

The backtraces are indicated a memory corruption.....there is no clue where the corruption happened or which part of the code is responsible for that. 

To get a lead on this, you need to enable the memory debugger, preferable QM_MALLOC + DBG_MALLOC - see [here](https://opensips.org/Documentation/TroubleShooting-OutOfMem) instructions on how to do it.

**Comment by bcnewlin** [comment]
Bogdan,

This only happened in our production environment. Are there any concerns enabling such debugging in production? I may have asked this before.

**Comment by bogdan-iancu** [comment]
The change may translate into (1) more CPU being used and (2) more memory being used. I would do a +50% to be sure.
