### ISSUE TITLE
[CRASH] Siptrace crash on bad header

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2187]
**OpenSIPS version you are running**

```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 8f98bc0ab
main.c compiled on 21:44:47 Jul 27 2020 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/wkAn7YXJ

**Describe the traffic that generated the bug**

Message received with an invalid header that appears prior to the Via header in the message.

**To Reproduce**

[This SIPp UAC](https://pastebin.com/nUJSMu92) will reproduce the crash consistently as long as `sip_trace` is called from the `error_route`.

**Relevant System Logs**

https://pastebin.com/1VjNQjUC

**OS/environment information**
 - Operating System:  Docker amazonlinux:2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bcnewlin , could you validate this fix please?

**Comment by bcnewlin** [comment]
Bogdan,

I've confirmed that does fix the crash. Thank you!

Now that the crash is not stopping processing, I am seeing another strange behavior with this particular message. With the example SIPp UAC I provided that has a bad To header, I cannot send a 400 reply. The SL module errors and won't send ([logs](https://pastebin.com/h2xGvgde)). However, with [this SIPp UAC](https://pastebin.com/xDBW5H6C) which is identical except the From header is bad, it works fine.

Maybe it's failing trying to add a tag to the To header for the reply? If so, I'm not sure what could be done about it to be honest.

I can open this as a separate issue if you'd prefer.

**Comment by bogdan-iancu** [comment]
Ben, what function do you in the `error_route` for sending the reply ?

**Comment by bcnewlin** [comment]
We are using `send_reply` from the signaling module, which calls `sl_send_reply` as there is no transaction.

**Comment by bogdan-iancu** [comment]
@bcnewlin , in order to send a final reply, as per RFC3261, OpenSIPS is trying to add a to-tag param (if not present in the request).
In the original UAC scenario, the TO was broken, unparsable, so opensips is not able to build the reply.
With the second UAC scenario , the FROM is broken, but TO looks ok. And as From is not by default parsed (TO body is) and also FROM does not need to be changed, it is not parsed. So even if broken, the FROM will be simply mirrored.

**Comment by bcnewlin** [comment]
Yes, that's what I figured is that the reply could not be sent because the to-tag could not be added. I don't think there is any solution to that without breaking spec.
