### ISSUE TITLE
Opensips3.0 Highly Availability of progress call?

### ISSUE THREAD

**Issue by amitpaltech** [OpenSIPS/opensips#2189]
Hello guys,
           hope all of you are fine.

My primarily requirement is to recover the Progress call(Ring) in failover  between two opensips vm.
I am new to opensips previously I was working with freeswitch which is not provide the same. 
By my  understanding with opensips this can be achieved by two node   HA in clustered environment.
**I have done clustering configuration on both server , please find the attached configuration file of both node.**

**when I shift the  floating IP (keepalived) during progress call following error are received on current control server**

Jul 31 04:42:20 primary /usr/local/sbin/opensips[25687]: WARNING:registrar:save_aux: unsupported flag i
Jul 31 04:42:20 primary /usr/local/sbin/opensips[25687]: WARNING:registrar:save_aux: unsupported flag p
Jul 31 04:42:27 primary /usr/local/sbin/opensips[25687]: WARNING:registrar:save_aux: unsupported flag i
Jul 31 04:42:27 primary /usr/local/sbin/opensips[25687]: WARNING:registrar:save_aux: unsupported flag p
Jul 31 04:42:38 primary /usr/local/sbin/opensips[25687]: new branch at sip:1001@192.168.20.254:53984;ob
Jul 31 04:42:39 primary /usr/local/sbin/opensips[25687]: incoming reply
Jul 31 04:42:39 primary /usr/local/sbin/opensips[25687]: incoming reply
Jul 31 04:42:48 primary snmpd[434]: error on subcontainer 'ia_addr' insert (-1)
Jul 31 04:42:52 primary systemd[1]: Stopping Keepalive Daemon (LVS and VRRP)...
Jul 31 04:42:52 primary Keepalived[8320]: Stopping
Jul 31 04:42:52 primary Keepalived_vrrp[8322]: VRRP_Instance(main) sent 0 priority
Jul 31 04:42:53 primary Keepalived_healthcheckers[8321]: Stopped
Jul 31 04:42:54 primary Keepalived_vrrp[8322]: Stopped
Jul 31 04:42:54 primary Keepalived[8320]: Stopped Keepalived v1.3.2 (12/03,2016)
Jul 31 04:42:54 primary systemd[1]: Stopped Keepalive Daemon (LVS and VRRP).
Jul 31 04:42:54 primary systemd[1]: Starting Keepalive Daemon (LVS and VRRP)...
Jul 31 04:42:54 primary Keepalived[26458]: Starting Keepalived v1.3.2 (12/03,2016)
Jul 31 04:42:54 primary Keepalived[26458]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Jul 31 04:42:54 primary Keepalived[26458]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 31 04:42:54 primary systemd[1]: Started Keepalive Daemon (LVS and VRRP).
Jul 31 04:42:54 primary Keepalived[26460]: Starting Healthcheck child process, pid=26461
Jul 31 04:42:54 primary Keepalived[26460]: Starting VRRP child process, pid=26462
Jul 31 04:42:54 primary Keepalived_healthcheckers[26461]: Initializing ipvs
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Registering Kernel netlink reflector
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Registering Kernel netlink command channel
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Registering gratuitous ARP shared channel
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Unable to load ipset library - libipset.so.3: cannot open shared object file: No such file or directory
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: Using LinkWatch kernel netlink reflector...
Jul 31 04:42:54 primary Keepalived_vrrp[26462]: VRRP_Instance(main) Entering BACKUP STATE
Jul 31 04:42:54 primary Keepalived_healthcheckers[26461]: Registering Kernel netlink reflector
Jul 31 04:42:54 primary Keepalived_healthcheckers[26461]: Registering Kernel netlink command channel
Jul 31 04:42:54 primary Keepalived_healthcheckers[26461]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 31 04:42:55 primary Keepalived_healthcheckers[26461]: Using LinkWatch kernel netlink reflector...
Jul 31 04:43:01 primary CRON[26472]: (root) CMD ((cd /var/www/html/opensips-cp/; /usr/bin/php cron_job/get_opensips_stats.php))
Jul 31 04:43:01 primary cron[3787]: 2020-07-31 04:43:01 non-existent configuration file(s): /etc/exim4/exim4.conf:/var/lib/exim4/config.autogenerated
Jul 31 04:43:01 primary CRON[26471]: (root) MAIL (mailed 121 bytes of output but got status 0x0001 from MTA#012)
Jul 31 04:43:09 primary /usr/local/sbin/opensips[25699]: ERROR:core:proto_udp_send: sendto(sock,0x7f9e8091b1b0,414,0,0x7f9e80917a90,16): Network is unreachable(101) [192.168.20.254:53984]
Jul 31 04:43:09 primary /usr/local/sbin/opensips[25699]: ERROR:tm:msg_send: send() to 192.168.20.254:53984 for proto udp/1 failed
Jul 31 04:43:09 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 100 ms ago (now 1272680 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 190 ms ago (now 1272770 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 290 ms ago (now 1272870 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 380 ms ago (now 1272960 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 470 ms ago (now 1273050 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 570 ms ago (now 1273150 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 660 ms ago (now 1273240 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: new branch at sip:1001@192.168.20.254:53984;ob
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: ERROR:core:proto_udp_send: sendto(sock,0x7f9e8091bda0,1107,0,0x7f9e80917bc8,16): Network is unreachable(101) [192.168.20.64:5060]
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:msg_send: send() to 192.168.20.64:5060 for proto udp/1 failed
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:t_forward_nonack: sending request failed
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:w_t_relay: t_forward_nonack failed
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**core:proto_udp_send: sendto(sock,0x7f9e845310d0,431,0,0x7f9e809178f0,16): Network is unreachable(101) [192.168.20.254:43130]
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:msg_send: send() to 192.168.20.254:43130 for proto udp/1 failed
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25686]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 760 ms ago (now 1273340 ms), delaying execution
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**core:proto_udp_send: sendto(sock,0x7f9e8091b1b0,414,0,0x7f9e80917a90,16): Network is unreachable(101) [192.168.20.254:53984]
Jul 31 04:43:10 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:msg_send: send() to 192.168.20.254:53984 for proto udp/1 failed
Jul 31 04:43:11 primary /usr/local/sbin/opensips[25699]: **ERROR:**core:proto_udp_send: sendto(sock,0x7f9e7fe9db80,431,0,0x7f9e809178f0,16): Network is unreachable(101) [192.168.20.254:43130]
Jul 31 04:43:11 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:msg_send: send() to 192.168.20.254:43130 for proto udp/1 failed
Jul 31 04:43:11 primary /usr/local/sbin/opensips[25699]: **ERROR:**core:proto_udp_send: sendto(sock,0x7f9e8091b1b0,414,0,0x7f9e80917a90,16): Network is unreachable(101) [192.168.20.254:53984]
Jul 31 04:43:11 primary /usr/local/sbin/opensips[25699]: **ERROR:**tm:msg_send: send() to 192.168.20.254:53984 for proto udp/1 failed
Jul 31 04:43:12 primary /usr/local/sbin/opensips[25699]: **ERROR:**core:proto_udp_send: sendto(sock,0x7f9e7fe9db80,431,0,0x7f9e809178f0,16): Network is unreachable(101) [192.168.20.254:43130]
Jul 31 04:43:12 primary /usr/local/sbin/opensips[25699]: **ERROR**:tm:msg_send: send() to 192.168.20.254:43130 for proto udp/1 failed
Jul 31 04:43:13 primary /usr/local/sbin/opensips[25699]: **ERROR**:core:proto_udp_send: sendto(sock,0x7f9e8091b1b0,414,0,0x7f9e80917a90,16): Network is unreachable(101) [192.168.20.254:53984]
Jul 31 04:43:13 primary /usr/local/sbin/opensips[25699]: **ERROR**:tm:msg_send: send() to 192.168.20.254:53984 for proto udp/1 failed
Jul 31 04:43:14 primary /usr/local/sbin/opensips[25699]: **ERROR**:core:proto_udp_send: sendto(sock,0x7f9e7fe9db80,431,0,0x7f9e809178f0,16): Network is unreachable(101) [192.168.20.254:43130]
Jul 31 04:43:14 primary /usr/local/sbin/opensips[25699]: **ERROR**:tm:msg_send: send() to 192.168.20.254:43130 for proto udp/1 failed

and on backUP  server we received following error

Jul 31 04:42:20 secondary /usr/local/sbin/opensips[28370]: **CRITICAL:usrloc:receive_ucontact_insert: #012>>> replicated ct insert: differring rlabels! (ci: 'aa4cb20add5b6b50MTg0YzVlODc0NTBiZGU1ZGJiYmNmYjY1MDc0MjIwMzI.')#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues**

**can you suggest me what is missing by me , what is required to done to achieve this requirement.**

**pls find attached opensips configuration script for both node.**
[opensips_residential_node1.txt](https://github.com/OpenSIPS/opensips/files/5004245/opensips_residential_node1.txt)
[opensips_residential_node2.txt](https://github.com/OpenSIPS/opensips/files/5004246/opensips_residential_node2.txt)

**Comment by bogdan-iancu** [comment]
@amitpaltech , OpenSIPS does not replicate transaction state or dialogs before being answered. The dialog replication starts only after the call is established.

**Comment by amitpaltech** [comment]
> @amitpaltech , OpenSIPS does not replicate transaction state or dialogs before being answered. The dialog replication starts only after the call is established.

Dear bogdan,
                    Thanks bogadan for your kind response. 
                   is any other way to achieve my requirement with opensips? I want to recover Ringing call while floating IP move to another opensips instance. is the  opensips have the capability to achieve this?
please reply me asap. I am waiting for your response.

**Comment by bogdan-iancu** [comment]
no, this is not possible

**Comment by amitpaltech** [comment]
> no, this is not possible
Hi,
Can you suggest an alternate mechanism to achieve replication of transaction state.  Can you guide how it can be achieved in OpneSip or is there a mechanism to get commercial support to achieve the desired objective. Do you think it can be achieved using Kamillio. I have a customer who wants high availability for ringing calls and calls that in process of being set up.
