### ISSUE TITLE
Information Regarding Progress Call Recovery(Recover UN-Answered Call in Redundancy )

### ISSUE THREAD

**Issue by amit1576** [OpenSIPS/opensips#2191]
Hello Team,

I need one info, Can OpenSIPS recover ringing call in redundancy. Active calls is getting recovered with OpenSIPS 3.0 , but i am facing problem with Ringing call as calls continue to ring after virtual ip shifting.

Can we achieve it by OpenSIPS or not ?

Thanks in advance.

**Comment by bogdan-iancu** [comment]
No, you cannot do that with OpenSIPS
