### ISSUE TITLE
[BUG]:Memory leak

### ISSUE THREAD

**Issue by fluke87** [OpenSIPS/opensips#2197]
Background. Link to the previous bug ticket ( https://github.com/OpenSIPS/opensips/issues/2149 )

We followed your recommendation and changed the parameter from 128 to 32000. (  https://github.com/OpenSIPS/opensips/blob/3.0/modules/permissions/hash.h#L105 )

After compilation and launch, we began to observe a memory leak.
We suspect that the leak occurs when the MI calls the address_reload or subnet_reload command after adding new records to the database.

The version of systems and assemblies in the link of the previous ticket

**Comment by bogdan-iancu** [comment]
@fluke87 , please follow the steps [here](https://opensips.org/Documentation/TroubleShooting-OutOfMem) in order to get a memory dump and to confirm (or not) the leak. It may simply some memory de-fragmentation issue, not a leak

**Comment by fluke87** [comment]
[mem_dump_after_adress_reload_reload.log](https://github.com/OpenSIPS/opensips/files/5088354/mem_dump_after_adress_reload_reload.log)
[mem_dump_after_start.log](https://github.com/OpenSIPS/opensips/files/5088355/mem_dump_after_start.log)

**Comment by fluke87** [comment]
> @fluke87 , please follow the steps [here](https://opensips.org/Documentation/TroubleShooting-OutOfMem) in order to get a memory dump and to confirm (or not) the leak. It may simply some memory de-fragmentation issue, not a leak

We made 2 dumps. The first one after the start and the second after 1 hour of work and several executed commands MI address_reload

**Comment by bogdan-iancu** [comment]
So, originally you had:

> 145136 : 4275 x [hash.c: subnet_table_insert, line 401]
> 205272 : 4275 x [hash.c: subnet_table_insert, line 378]

and after the reloads:

> 10677384 : 256480 x [hash.c: subnet_table_insert, line 401]
> 412424 : 8548 x [hash.c: subnet_table_insert, line 378]

How many subnets (not IPs!!!) do you have in DB ? also, do you remember the number of reloads you did ?

**Comment by fluke87** [comment]
> So, originally you had:
> 
> > 145136 : 4275 x [hash.c: subnet_table_insert, line 401]
> > 205272 : 4275 x [hash.c: subnet_table_insert, line 378]
> 
> and after the reloads:
> 
> > 10677384 : 256480 x [hash.c: subnet_table_insert, line 401]
> > 412424 : 8548 x [hash.c: subnet_table_insert, line 378]
> 
> How many subnets (not IPs!!!) do you have in DB ? also, do you remember the number of reloads you did ?

4276 subnets
10 reloads

**Comment by bogdan-iancu** [comment]
Maybe there are 4275 subnets , as per the mem records:
>  145136 : 4275 x [hash.c: subnet_table_insert, line 401]

After the reloads:
256480 / 4275 =~60
8548 / 4275 =~2

I assume the number of DB records in constant during the full set of reload ?

**Comment by fluke87** [comment]
"I assume the number of DB records in constant during the full set of reload ?"

yes

**Comment by fluke87** [comment]
it is assumed that 1 entry could be added in a short period of time, by our external application

**Comment by fluke87** [comment]
> Maybe there are 4275 subnets , as per the mem records:
> 
> > 145136 : 4275 x [hash.c: subnet_table_insert, line 401]
> 
> After the reloads:
> 256480 / 4275 =~60
> 8548 / 4275 =~2
> 
> I assume the number of DB records in constant during the full set of reload ?

can you confirm the problem?

**Comment by bogdan-iancu** [comment]
@fluke87 , could you test the fix I just did ?

**Comment by fluke87** [comment]
> @fluke87 , could you test the fix I just did ?

The problem is no longer observed. Your patch has fixed the problem. Close
