### ISSUE TITLE
db_mysql error while installaling opensips

### ISSUE THREAD

**Issue by devopsram2020** [OpenSIPS/opensips#2199]
Compiling row.c
In file included from row.c:29:0:
my_con.h:36:2: error: unknown type name ‘my_bool’
  my_bool null;
  ^
my_con.h:42:2: error: unknown type name ‘my_bool’
  my_bool null;
  ^
my_con.h:43:2: error: unknown type name ‘my_bool’
  my_bool error;
  ^
make[1]: *** [row.o] Error 1
make[1]: Leaving directory `/usr/local/src/opensips-2.3.2/modules/db_mysql'
make: *** [modules] Error 2

**Comment by bogdan-iancu** [comment]
what version on libmysqlclient do you use ?

**Comment by bogdan-iancu** [comment]
BTW, I noticed you use 2.3 version which is no longer supported. Please upgrade to 2.4, ideally 3.0/3.1. If you still experience the issue, open a new ticket here.
