### ISSUE TITLE
SIPREC Content-Length in wrong position.

### ISSUE THREAD

**Issue by woodwardgn** [OpenSIPS/opensips#2200]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 58804282f
main.c compiled on 09:05:48 Aug  6 2020 with gcc 8

```

**Describe the bug**

Hi,

I am interop testing SIPREC on a product I am developing and have tested successfully on Audiocodes and Cisco.

There is a problem I have discovered with SIPREC OpenSIPS whereas the Content-Length header is in the wrong position e.g:

CSeq: 2 INVITE
Call-ID: B2B.167.3677880.1596705322
Max-Forwards: 70
Content-Length: 2163
User-Agent: OpenSIPS (3.1.0 (x86_64/linux))
Require: siprec
Content-Type: multipart/mixed;boundary=OSS-unique-boundary-42
Contact: <sip:172.16.20.50:5060;transport=tcp>

.. Because the Content-Length is not positioned last and underneath the Contact Header, the Content Length of 2163 bytes   truncates the message (SIPREC XML) short. Should the Content-Length be positioned correctly underneath all the other SIP headers, then the length of 2163 would actually be right. The invite is truncated by exactly the same number of bytes as the wrongly position headers as demonstrated below.

This is what should be located above the Content-Length header but is below:

 User-Agent: OpenSIPS (3.1.0 (x86_64/linux))
Require: siprec
Content-Type: multipart/mixed;boundary=OSS-unique-boundary-42
Contact: <sip:172.16.20.50:5060;transport=tcp>

This is the truncated SIPREC XML fragment that gets cut off after byte 2163:

Q47Tm6QhQm3yvTH7g==">
		<send>44G7VCEeQTOovYqBEF5xIw==</send>
		<recv>H9ZKRMGhQJi6ye/CYfLxCw==</recv>
	</participantstreamassoc>
</recording>
--OSS-unique-boundary-42--

**To Reproduce**

I took a default OpenSIPS config file and added the following. It is very easy to reproduce and the result is consistent.

if (is_method("INVITE")) {
                if (sstCheckMin(1)) {
                        xlog("L_ERR", "422 Session Timer Too Small reply sent.\n");
                        exit;
                }
                create_dialog();
                rtpproxy_engage("sei");
                 siprec_start_recording("sip:192.168.20.80:5060;transport=tcp",, "$var(caller)", "$var(callee)");
                 do_accounting("log");
        }

The problem certainly exists with SIP TCP and TLS. Have not tested UDP as yet.

**Expected behavior**

I would expect to see a trace like the following with the Content Length at the bottom of the headers:

CSeq: 2 INVITE
Call-ID: B2B.167.3677880.1596705322
Max-Forwards: 70
User-Agent: OpenSIPS (3.1.0 (x86_64/linux))
Require: siprec
Content-Type: multipart/mixed;boundary=OSS-unique-boundary-42
Contact: <sip:172.16.20.50:5060;transport=tcp>
Content-Length: 2163

**Relevant System Logs**

The same result is produced on Debian 10 and Centos 7.

**Additional context**
I have attached a file showing the truncated SIP invite - its easier to see it.
[ingress.txt](https://github.com/OpenSIPS/opensips/files/5034019/ingress.txt)

Thank you 
Garry

**Comment by bogdan-iancu** [comment]
The position of a header within the SIP msg is irrelevant. Should I understand that your report is more about the wrong value of the Contact-Len hdr, rather than its position ?

**Comment by woodwardgn** [comment]
Hi, Well usually you would have the Content Length at the bottom of the headers..that then marks the start of the body. An alteration of the Content-Length value would equally get around the problem. In the SIP RFC 7.5 Framing SIP Messages. It states:
"The Content-Length header field value is used to locate the end of
      each SIP message in a stream.  It will always be present when SIP
      messages are sent over stream-oriented transports."

"The Content-Type and Content-Length refer to the message body"

At the moment the Content-Length is taking into account he SIP headers beneath it which it should not. Putting the Content-Length under all other headers will fix the issue and then content length will calculate perfectly.

Thanks for looking at this.

**Comment by woodwardgn** [comment]
no planned solution so far. thanks

**Comment by razvancrainea** [comment]
@woodwardgn the SIP message you attached does not contain a complete SIPREC body - it appears as it had been truncated by your tracing tool, as the XML SIPREC body is not full. Could you please attach a full SIP message, as it was generated by OpenSIPS?

**Comment by woodwardgn** [comment]
Hi. Exactly. The SIP message is truncated by OpenSIPS. Please see ingress.txt for the full/original message. You will see that the message has been truncated by the same amount of bytes of SIP headers placed underneath the Content-Length. If the Content-Length was positioned underneath all the SIP headers then the SIP Message would be OK and complete. I have tried to explain this best I can in the original message.

Thanks


[ingress.txt](https://github.com/OpenSIPS/opensips/files/5148941/ingress.txt)

**Comment by razvancrainea** [comment]
I am 98% sure that OpenSIPS does not truncate the message, as there's no logic in OpenSIPS to even be able to do so. Perhaps somebody on the path is altering the message due to fragmentation or something.
Could you please trace a pcap on the OpenSIPS machine?

**Comment by woodwardgn** [comment]
Hi. Here is the pcap trace attached. Its show the entire SIPREC XML...... But if you calculate the Content-length it only takes you to this position shown below which ends up truncated. 

INVITE sip:192.168.20.80:5060;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 172.16.20.50:5060;branch=z9hG4bKf865.85b34c06.0
To: sip:192.168.20.80:5060;transport=tcp
From: <sip:192.168.20.80:5060;transport=tcp>;tag=0d85520d5efa86a6b4763a18b85e7bd5-ce21
CSeq: 2 INVITE
Call-ID: B2B.167.7644731.1598863942
Max-Forwards: 70
Content-Length: 2163
User-Agent: OpenSIPS (3.1.0 (x86_64/linux))
Require: siprec
Content-Type: multipart/mixed;boundary=OSS-unique-boundary-42
Contact: <sip:172.16.20.50:5060;transport=tcp>

--OSS-unique-boundary-42
Content-Type: application/sdp

v=0
o=- 1598863943 0 IN IP4 127.0.0.1
s=-
c=IN IP4 127.0.0.1
t=0 0
m=audio 6003 RTP/AVP 8 101
a=rtcp:16101 IN IP4 172.16.20.222
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=label:1
a=sendonly
m=audio 6004 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=label:2
a=sendonly

--OSS-unique-boundary-42
Content-Type: application/rs-metadata+xml
Content-Disposition: recording-session

<?xml version="1.0" encoding="UTF-8"?>
<recording xmlns='urn:ietf:params:xml:ns:recording:1'>
	<datamode>complete</datamode>
	<session session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<sipSessionID>8978faa1745e41a3b0bdf9fd1d18c8b5</sipSessionID>
	</session>
	<participant participant_id="DCVNOqazTZiQZQqq1FFiXA==">
<null>
	</participant>
	<participant participant_id="MZS2M9aGQxiadmwnhErB3w==">
<null>
	</participant>
	<stream stream_id="iRyHM9BZTmuAGIVW04h+zw==" session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<label>1</label>
	</stream>
	<stream stream_id="FJeW5gxeS3yC6lS90HkpfA==" session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<label>2</label>
	</stream>
	<sessionrecordingassoc session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<associate-time>2020-08-31T09:52:23+0100</associate-time>
	</sessionrecordingassoc>
	<participantsessionassoc participant_id="DCVNOqazTZiQZQqq1FFiXA==" session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<associate-time>2020-08-31T09:52:23+0100</associate-time>
	</participantsessionassoc>
	<participantsessionassoc participant_id="MZS2M9aGQxiadmwnhErB3w==" session_id="1M9adbpoT9+SDMwaxhQ7CA==">
		<associate-time>2020-08-31T09:52:23+0100</associate-time>
	</participantsessionassoc>
	<participantstreamassoc participant_id="DCVNOqazTZiQZQqq1FFiXA==">
		<send>iRyHM9BZTmuAGIVW04h+zw==</send>
		<recv>FJeW5gxeS3yC6lS90HkpfA==</recv>
	</participantstreamassoc>
	<participantstreamassoc participant_id="MZS2M9

.. Above is where Content-Length of 2163 bytes will take you.

**Comment by razvancrainea** [comment]
Note that there is no pcap attached, kindly make sure to attach it.

**Comment by woodwardgn** [comment]
Apologies - here it is.
[opensipVsSIPREC.pcap.zip](https://github.com/OpenSIPS/opensips/files/5149711/opensipVsSIPREC.pcap.zip)

**Comment by razvancrainea** [comment]
In the attached pcap you can see that the body's length is exactly `2163`, as the `Content-Length` header indicates.
