### ISSUE TITLE
[BUG] tm: t_check_status does not work if  onreply_route is armed in branch_route 

### ISSUE THREAD

**Issue by fgast** [OpenSIPS/opensips#2201]
**OpenSIPS version you are running**

```
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, EXTRA_DEBUG, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 07:16:14 Aug  3 2020 with gcc 6.3.0
```
(also with 3.1 - not checked other versions)

**Describe the bug**
If t_check_status(..) is used in an onreply_route which is armed by a branch_route, it generates an error and the status is not evaluated.

```
 ERROR:tm:t_check_status: unsupported route_type 8
```

**To Reproduce**
Can be reproduced 100% of the time. 

1. Config sample:
```
route[relay] {
	if (is_method("INVITE")) {
		t_on_branch("per_branch_ops");
	}

	if (!t_relay()) {
		send_reply(500,"Internal Error");
	}
	exit;
}

branch_route[per_branch_ops] {
	xlog("new branch at $ru\n");
	t_on_reply("branch_onreply");
}

onreply_route[branch_onreply] {
	xlog("brach onreply\n");
	if (t_check_status("302")) {
		xlog("302 on branch reply\n");
	}
}
```
2. Place call, respond with 302...

**Expected behavior**
- status is evaluated in t_check_status, no error. 

**Relevant System Logs**
```
Aug  6 10:17:24 [2026] new branch at sip:aaaa@127.0.0.1:6666;ob
Aug  6 10:17:24 [2026] brach onreply
Aug  6 10:17:24 [2026] ERROR:tm:t_check_status: unsupported route_type 8   <<< this is for 100 Trying from client
Aug  6 10:17:31 [2025] brach onreply
Aug  6 10:17:31 [2025] ERROR:tm:t_check_status: unsupported route_type 8   <<< this is for 302 from client
```

**OS/environment information**
 - Operating System: `Debian 9`
 - OpenSIPS installation: `git`

**Additional context**
- Documentation states that function can be used on REQUEST_ROUTE, ONREPLY_ROUTE, FAILURE_ROUTE and BRANCH_ROUTE.
- the function does _not_ have a case for BRANCH_ROUTE  in the switch(route_types) https://github.com/OpenSIPS/opensips/blob/94cec754036861be9ed4281bd3f04b1fbe516ea4/modules/tm/tm.c#L905-L927
- It works on a failure_route if it is armed within a branch_route. 
- I am not sure if this is caused by the missing case or some deeper problem (shouldn't the route type be 'ONREPLY_ROUTE' at this point?) or is it just a bug in the documentation ( i don't think so because of https://github.com/OpenSIPS/opensips/blob/94cec754036861be9ed4281bd3f04b1fbe516ea4/modules/tm/tm.c#L211-L213 )

**Comment by bogdan-iancu** [comment]
Thank you @fgast for the report, I managed to reproduce the problem and also ti identify the cause. It seems the problem was introduced with 2ae51207a9  and affects only the "per-branch" onreply route (and not the per-transaction branch route).
