### ISSUE TITLE
Re-Homing between OpenSIPS and Freeswitch

### ISSUE THREAD

**Issue by amit1576** [OpenSIPS/opensips#2202]
Dear Team.

I have read about one excellent feature of OpenSIPS i.e. **Re-homing**. I have one question can Re-Homing be possible between OpenSIP and FreeSwitch. Means Calls starts on OpenSIPS and i can move it to FreeSwitch.

Thanks in advance.

**Comment by razvancrainea** [comment]
This tracker is for bugs/feature-requests. For usage questions, please use our [Mailing List](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).
