### ISSUE TITLE
[BUG] Bad URI when using Topology Hiding

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#2203]
We are running Opensips 2.4.8 Git commit 2aa0f807e8086db67ce79288234439dc1eaf609a (the hp_malloc backport fixes) with topology hiding enabled and force_dialog enabled.

Occasionally we are seeing the failure of sequential requests from the Callee to Caller side when t_relay() is called with the following error messages appearing in the logs:

`2020-08-04T22:47:20.500650-07:00 proxy3 /usr/sbin/opensips[574375]: ERROR:core:parse_uri: uri too short: <sip> (3)
2020-08-04T22:47:20.501159-07:00 proxy3 /usr/sbin/opensips[574375]: ERROR:core:parse_sip_msg_uri: bad uri <sip>
2020-08-04T22:47:20.501227-07:00 proxy3 /usr/sbin/opensips[574375]: ERROR:tm:new_t: uri invalid
2020-08-04T22:47:20.501276-07:00 proxy3 /usr/sbin/opensips[574375]: ERROR:tm:t_newtran: new_t failed`

The problem does not seem to be with the actual sip signalling, as we call sipmsg_validate() earlier in the script (before topology_hiding_match()) with the flags "shrmftc". However later in the script after topology_hiding_match() is called t_relay() fails with the above log. So it appears something with the restoration of the topology hiding from the dialog is failing somehow.

We end up replying to the request with a 475 Bad URI generated by sl_reply_error() after t_relay().

I also noticed that when this happens the call will not generate a cdr accounting, but the dialog does end as any further request no longer match topology_hiding_match().

I can provide captures privately.

**Comment by bogdan-iancu** [comment]
I suspect the dialog module is learning some bogus SIP URI as contact, during the call. And when the next in-dialog requests has to be routed, the bogus URI is to be used, so the above errors.
Could you provide capture + logs (debug) ?

**Comment by rrb3942** [comment]
Just updating that we have not been able to reproduce this manually which makes getting debug logs difficult, although we still see it occurring in logs and captures.

What does seem to be a common thread is that the first sequential hunt fails and then the call connects on a subsequent attempt.

**Comment by rrb3942** [comment]
@bogdan-iancu I emailed you directly with some debug logs and captures.

**Comment by bogdan-iancu** [comment]
Hi @rrb3942 , sorry for dropping the ball here. If you upgrade to the latest 2.4.9, do you still have this issue ?

**Comment by rrb3942** [comment]
Still seeing this under 2.4.9

I managed to work around it by saving the contacts to a dialog variable and restoring that as the ruri whenever '$ru' is NULL on in the script.

**Comment by bogdan-iancu** [comment]
@rrb3942 , I still have the pcap and logs you sent me last year - are they still valid in showing the case here ? I can dig into that.

**Comment by rrb3942** [comment]
@bogdan-iancu Yes, that capture and logs should still be valid.

**Comment by bogdan-iancu** [comment]
Hi @rrb3942 , could you confirm this issue is still valid with 3.1 or 3.2 ? (I know you reported it for 2.4, but this is EOL now)
