### ISSUE TITLE
[CRASH] segfault in tls_mgm.so

### ISSUE THREAD

**Issue by ronildo-quadros** [OpenSIPS/opensips#2204]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 58804282f
main.c compiled on 20:14:53 Aug  5 2020 with gcc 4.8.5
```

**Crash Core Dump**

https://drive.google.com/file/d/1ZGqSQCtT2UNksNelQ3cqleyXQXGOewrn/view?usp=sharing
**Describe the traffic that generated the bug**

pre-daemon process exit with -1
Aug  5 18:07:36 voxlnks opensips: INFO:tls_mgm:mod_load: openssl version: OpenSSL 1.0.2k-fips  26 Jan 2017
Aug  5 18:07:36 voxlnks kernel: opensips[14218]: segfault at 7f698662c250 ip 00007f6186419ba9 sp 00007fff1ae4b170 error 4 in tls_mgm.so[7f61863ff000+29000]
Aug  5 18:07:36 voxlnks opensips: INFO:core:fix_poll_method: using epoll as the IO watch method (auto detected)
.....
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: CRITICAL:core:sig_usr: segfault in attendant (starter) process!
Aug  5 18:07:36 voxlnks opensips: INFO:core:daemonize: pre-daemon process exiting with -1
**To Reproduce**

**Relevant System Logs**

```Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: INFO:tls_mgm:mod_init: initializing TLS management
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: INFO:tls_mgm:mod_init: disabling compression due ZLIB problems
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: INFO:tls_mgm:check_for_krb: KRB5 cipher KRB5-IDEA-CBC-SHA found
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: INFO:tls_mgm:init_tls_dom: Processing TLS domain 'dom1'
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: NOTICE:tls_mgm:init_tls_dom: No EC curve defined
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: INFO:tls_mgm:get_ssl_ctx_verify_mode: client verification activated. Client certificates are NOT mandatory.
Aug  5 18:07:36 voxlnks /usr/local/sbin/opensips[14218]: NOTICE:tls_mgm:init_tls_dom: no crl for tls, using none```
**OS/environment information**
 - Operating System: <!-- (example: `Debian 9`) -->Linux voxlnks.com 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - OpenSIPS installation: <!-- (example: `git`/`source`/`debs`/`manual packages`) -->`source`
 - other relevant information:
OpenSSL 1.0.2k-fips  26 Jan 2017
**Additional context**
<!-- Add any other context about the problem here. -->
[Extract from opensips.cfg]
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm","server_domain", "dom1")
modparam("tls_mgm","match_ip_address", "[dom1]*")
modparam("tls_mgm", "match_sip_domain", "[dom1]voxlnks.com")
modparam("tls_mgm","verify_cert", "[dom1]1")
modparam("tls_mgm","require_cert", "[dom1]0")
modparam("tls_mgm","tls_method", "[dom1]SSLv1")
modparam("tls_mgm","certificate", "[dom1]/root/ServerCertificates/2019/www_voxlnks_com.crt")
modparam("tls_mgm","private_key", "[dom1]/root/ServerCertificates/2019/voxlnks.key")
modparam("tls_mgm", "ca_dir", "[dom1]/root/ServerCertificates/2019")
modparam("tls_mgm","ca_list", "[dom1]/root/ServerCertificates/2019/GlobeSSLDVCertificationAuthority2.crt")

**Comment by rvlad-patrascu** [comment]
Hi @ronildo-quadros ,

Please open the core file with gdb and the opensips executable and run `bt full`.

**Comment by ronildo-quadros** [comment]
Here it is.
Best Regards.
[GDB_BT_FULL.log](https://github.com/OpenSIPS/opensips/files/5091581/GDB_BT_FULL.log)

**Comment by rvlad-patrascu** [comment]
Can you run `p *d` in gdb and also post the configuration for the tls_mgm module ?

**Comment by ronildo-quadros** [comment]
Reading symbols from /usr/local/sbin/opensips...done.
[New LWP 14218]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/sbin/opensips -w /tmp'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f6186419ba9 in init_tls_dom (d=0x7f618bbb2c20) at tls_mgm.c:1257
1257			d->ctx[i] = SSL_CTX_new(ssl_methods[d->method - 1]);
(gdb) p *d
$1 = {name = {s = 0x7f618bbb2ce8 "dom1", len = 4}, flags = 1, match_domains = 0x7f618bbb2da0, match_addresses = 0x7f618bbb2d20, 
  ssl_ex_index = 0, ctx = 0x7f618bf17110, ctx_no = 9, verify_cert = 1, require_client_cert = 0, crl_check_all = 0, cert = {
    s = 0x7f618daf564e "/root/ServerCertificates/2019/www_voxlnks_com.crt", len = 49}, pkey = {
    s = 0x7f618daf585e "/root/ServerCertificates/2019/voxlnks.key", len = 41}, crl_directory = 0x0, ca = {
    s = 0x7f618daf5c7e "/root/ServerCertificates/2019/GlobeSSLDVCertificationAuthority2.crt", len = 67}, dh_param = {s = 0x0, len = 0}, 
  tls_ec_curve = 0x0, ca_directory = 0x7f618daf5a6e "/root/ServerCertificates/2019", ciphers_list = 0x0, refs = 1, lock = 0x7f618bbb29c8, 
  method = 4294967295, method_max = 4294967295, next = 0x0}
(gdb) 
==================================================================================================
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("tls_mgm","server_domain", "dom1")
modparam("tls_mgm","match_ip_address", "[dom1]*")
modparam("tls_mgm", "match_sip_domain", "[dom1]voxlnks.com")
modparam("tls_mgm","verify_cert", "[dom1]1")
modparam("tls_mgm","require_cert", "[dom1]0")
modparam("tls_mgm","tls_method", "[dom1]SSLv1")
modparam("tls_mgm","certificate", "[dom1]/root/ServerCertificates/2019/www_voxlnks_com.crt")
modparam("tls_mgm","private_key", "[dom1]/root/ServerCertificates/2019/voxlnks.key")
modparam("tls_mgm", "ca_dir", "[dom1]/root/ServerCertificates/2019")
modparam("tls_mgm","ca_list", "[dom1]/root/ServerCertificates/2019/GlobeSSLDVCertificationAuthority2.crt")
==================================================================================================
Best Regards,
Ronildo

**Comment by rvlad-patrascu** [comment]
I've pushed a fix for the crash but nevertheless you were using a bad value for the `tls_method` modparam: `SSLv1`, which should instead have been:  `TLSv1`.

**Comment by ronildo-quadros** [comment]
Hi,
Thanks for the fix, and for pointing to the modparm error I left behind during the many attempts of circumventing the crash.
Best Regards.
