### ISSUE TITLE
topology_hiding / Contact header

### ISSUE THREAD

**Issue by overload08** [OpenSIPS/opensips#2206]
Hi there.

Is it normal that topology_hiding broke the port in Contact header ?

I should have : Contact: <sip:0033123456789@12.34.56.78:5060>
I have : I should have : Contact: <sip:0033123456789@12.34.56.78;xyz=e01.1b16f46>

**Comment by bogdan-iancu** [comment]
Do you mean that the port is missing in the contact URI after TH ? This is perfectly legitimate and correct - port may be missing if the default is used. And 5060 is the default UDP port.
