### ISSUE TITLE
[BUG] Opensips send 477 failed for BYE message from Freeswitch

### ISSUE THREAD

**Issue by huongbn** [OpenSIPS/opensips#2207]
- I'm using Opensips v2.4.8
- OS: Debian 9
- Freeswitch: 1.10.3 
I'm using Opensips in front of Freeswitch cluster. It as a SBC register proxy for Websocket. I'm using JsSIP client to test WSS, but when I cancel call, Opensips not send ACK for BYE message and call is continue hangup.
![Screen Shot 2020-08-11 at 17 36 59](https://user-images.githubusercontent.com/33228286/89887912-4e95c800-dbf9-11ea-8888-39e065901862.png)

**Comment by bogdan-iancu** [comment]
This is not a bug report, it is more a usage / configuration issue, so please address it via the [opensips user's mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)
