### ISSUE TITLE
[CRASH] OpenSIPS 3.1 crashes on a forward() with no parameters.

### ISSUE THREAD

**Issue by bambyster** [OpenSIPS/opensips#2210]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 57caa6c03
main.c compiled on 15:31:44 Aug  5 2020 with gcc 7
```

**Crash Core Dump**

https://drive.google.com/file/d/1RymrSOLaJv214_KyGLGPLDvjRafWeikL/view?usp=sharing

**Describe the traffic that generated the bug**

Just any simple call.

**To Reproduce**

1. Create a configuration like this:
```
route {
    forward();
}

```
2. Start OpenSIPS.
3. Send a call.
4. Check OpenSIPS crashed.

**Relevant System Logs**

```Aug 12 15:25:14 [19335] CRITICAL:core:sig_usr: segfault in process pid: 19335, id: 4```

**OS/environment information**
 - Operating System: 
Ubuntu 18.04, FreeBSD 11
 - OpenSIPS installation: 
source
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bambyster , please confirm the fix.

**Comment by bambyster** [comment]
The opensips after this fix works properly. Thank you!
