### ISSUE TITLE
[BUG] Locally generated BYE does not honor existing CSeq space

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2211]
**OpenSIPS version you are running**

```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d17d0ed6c
main.c compiled on 21:09:22 Aug 10 2020 with gcc 7
```

**Describe the bug**

Locally generated BYEs from dialog timeouts do not honor the existing CSeq space of the SIP dialog, which is not conforming to spec. They are always sent with CSeq 1. This may affect other or all locally generated requests, like OPTIONS or INVITE pings; I'm not sure.

**To Reproduce**

1. Start OpenSIPS
2. Connect a call and set $DLG_timeout to a low value
3. Wait for the dialog timeout to occur
4. Verify the BYE from OpenSIPS has CSeq 1

**Expected behavior**

In-dialog requests must have increasing CSeq numbers.

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Docker, amazonlinux:2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bcnewlin, there is a lot of logic in the `dialog` module for pushing the right `cseq` in the generated BYE requests. What is the dialog setup in your case - any pinging in-dialog, any sequential requests ?
Do you have a pcap to show the problem?

**Comment by bcnewlin** [comment]
@bogdan-iancu We are not using dialog pinging; I have not verified whether those CSeq numbers are correct. The scenario I'm seeing this in is when the `$DLG_timeout` expires and OpenSIPS sends a BYE to both sides of the call. That BYE seems to always have a CSeq value of 1.

[Here is a pcap](https://pastebin.com/7XaAeNXD) of the issue. OpenSIPS is at `203.0.113.3`. [Here are the logs](https://pastebin.com/Vz3tvgaK).

**Comment by bcnewlin** [comment]
As far as I know this has not been resolved. Do you need more info from me?

**Comment by bogdan-iancu** [comment]
@bcnewlin , I ran several tests with the BYE generation, but I was not able to observe the issue your reported. 
Please try the followings:
* start a call, preferable with INVITE having a Cseq higher than 1 (use a SIPP scenario for that)
* set the "B" flag for the dialog and be sure you have a quite long timeout for the dialog
* while the dialog is up, run `opensipsctl fifo dlg_list_ctx` command (and paste here the output)
* using the `opensipsctl fifo dlg_end_dlg` command, terminate the call and observe the generated BYE
* be sure you get a pcap/trace with the whole call
* be sure you get the opensips logs in level 4

**Comment by bcnewlin** [comment]
@bogdan-iancu The bad cseq number is only on the upstream BYE sent from OpenSIPS to the caller. The downstream BYE has the correct cseq to the callee.

dlg_list_ctx: https://pastebin.com/nXFbuaef
OpenSIPS logs: https://pastebin.com/eZVjkZxx
tcpdump: https://pastebin.com/GUahtZpt

**Comment by bogdan-iancu** [comment]
thanks for the info @bcnewlin , let me check it

**Comment by bogdan-iancu** [comment]
@bcnewlin , false alarm, I say everything is just fine here.
Keep in mind that inside a dialog you have 2 cseq numbers, one managed/used by caller (and increased each time the caller sends something to callee) and one managed/used by calles (and increased each time the callee sends something to caller) . The two values may be totally different, there is no connection between them.

In your test, the caller cseq is 500, so the BYE sent to callee (in behalf of caller) had 501. But the callee side never generated any request back to caller and opensips assumes the minimum of 1 when sending the BYE to caller, in behalf of the callee.

To confirm this, you can enhance your scenario and insert a re-INVITE+200+ACK sequence from the callee side (after call setup) with a 300 cseq for example. And in this case, the BYE to caller will have 301.

**Comment by bcnewlin** [comment]
@bogdan-iancu You are right, it does work with the re-invite. I could swear it used to be both directions getting the CSeq 1 but all those old traces have expired and I don't still have a copy.

Apologies for the wasted time.
