### ISSUE TITLE
[CRASH] Opensips 2.4.7 Segfault

### ISSUE THREAD

**Issue by abieuzent** [OpenSIPS/opensips#2215]
**OpenSIPS version you are running**
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9e1fcc915
main.c compiled on 15:39:34 Mar 25 2020 with gcc 6.3.0

**Crash Core Dump**
https://pastebin.com/b76c3dNZ

**OS/environment information**
Debian 9
Opensips installed from source

Unable to reproduce and no idea what is the source.

**Comment by razvancrainea** [comment]
Any chance you could re-post the core dump, as it has been deleted :(.

**Comment by abieuzent** [comment]
Yes i have it : 

https://pastebin.com/XZmTb9KV

Thanks

**Comment by razvancrainea** [comment]
Most likely you are experiencing a consequence of a double free, or something. Any chance you could run with memory debugging?
Also, please consider updating to 2.4.8, as it is very likely that the problem has already been solved.

**Comment by abieuzent** [comment]
Thanks for the reply, we planned to migrate to 3.0.3 next week 😉

 

Regards

 

De : Răzvan Crainea <notifications@github.com>
Répondre à : OpenSIPS/opensips <reply@reply.github.com>
Date : jeudi 15 octobre 2020 à 14:46
À : OpenSIPS/opensips <opensips@noreply.github.com>
Cc : abieuzent <alain.bieuzent@free.fr>, Author <author@noreply.github.com>
Objet : Re: [OpenSIPS/opensips] [CRASH] Opensips 2.4.7 Segfault (#2215)

 

Most likely you are experiencing a consequence of a double free, or something. Any chance you could run with memory debugging?
Also, please consider updating to 2.4.8, as it is very likely that the problem has already been solved.
