### ISSUE TITLE
[BUG]can't use this function db_get_user_group(URI, AVP)

### ISSUE THREAD

**Issue by lanxiaolin-sz** [OpenSIPS/opensips#2219]
**OpenSIPS version you are running**

```
2.4.8
```

**Describe the bug**

I want to add a communication rule that only allows users in the same group to communicate.
but I can't use this function db_get_user_group(URI, AVP).

The idea now is to find out if the users of "FROM" and "TO" are in the same group and then restrict it further, but I find that I can't use the function db_get_user_group.
Looking at the source code, I also found no implementation of the function db_get_user_group.
**To Reproduce**

1. vim opensips.cfg
2.add codes to main route
if (is_method("INVITE")) {
   if (db_get_user_group("Request-URI", "$avp(10)")) {
      xdbg("User $ru belongs to $(avp(10)[*]) group(s)\n");
    }
}
**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: CentOS Linux release 7.8.2003 (Core)
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
Can you elaborate on what you mean when you say you "can't use" the function? Does OpenSIPS fail to start with an error? Does the function log an error? Is it just not returning the expected result? If any of these, can you provide the logs?

The function is implemented [here](https://github.com/OpenSIPS/opensips/blob/2.4.8/modules/group/re_group.c#L130). It's mapped to that function via the command export [here](https://github.com/OpenSIPS/opensips/blob/2.4.8/modules/group/group_mod.c#L143). I am using it in my 2.4.8 config without issue, though I am passing the URI as a variable, not using one of the static values as you are. That's not to say there is no issue, just that the function is certainly implemented and can be called.

**Comment by lanxiaolin-sz** [comment]
I'm sorry to confuse you, but I didn't get the desired result when I used the function.

data in my table grp is:
```
+----+----------+----------------+------+---------------------+
| id | username | domain   | grp  | last_modified       |
+----+----------+----------------+------+---------------------+
|  1 | 10001    | 47.105.1.10 | oic  | 2020-08-20 20:39:33 |
|  2 | 10002    | 47.105.1.10 | oic  | 2020-08-20 20:40:21 |
|  3 | 10003    | 47.105.1.10 | oic  | 2020-08-20 20:40:21 |
|  4 | 10004    | 47.105.1.10 | oic2 | 2020-08-20 20:40:21 |
+----+----------+----------------+------+---------------------+
```

**sip:10001@47.105.1.10 invite  sip:10002@47.105.1.10**

1. when I use  

```
if(db_is_user_in("$ru","oic")){
    xlog("user is in group oic");
}

```
it work. and the log is: user is in group oic


2. when I use function 'db_get_user_group',
```
if (is_method("INVITE")) {
                if(db_get_user_group("$ru","$avp(10)")){
                    xlog("user group is $(avp(10)[*])");
                }else{
                    xlog("can't get $ru 's group \n");
                }
}
```
The log is "can''t get sip:10001@47.105.1.10 's group.

Can you show me your code block for using scripts

**Comment by bcnewlin** [comment]
Per the [documentation](https://opensips.org/docs/modules/2.4.x/group.html#func_db_get_user_group) this function is "used for regular expression based group membership, using DB support". That means it does not use the default `grp` table, it uses the [re_table](https://opensips.org/docs/modules/2.4.x/group.html#param_re_table) which by default is not defined. In our config we have defined `re_table` as `re_grp` and we populate the group data there.

**Comment by lanxiaolin-sz** [comment]
> Per the [documentation](https://opensips.org/docs/modules/2.4.x/group.html#func_db_get_user_group) this function is "used for regular expression based group membership, using DB support". That means it does not use the default `grp` table, it uses the [re_table](https://opensips.org/docs/modules/2.4.x/group.html#param_re_table) which by default is not defined. In our config we have defined `re_table` as `re_grp` and we populate the group data there, then you can use this function.

Thank you very much. Have a nice day.
