### ISSUE TITLE
[CRASH] OpenSIPs 3.0.3 latest nightly

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#2220]
**OpenSIPS version you are running**
```
version: opensips 3.0.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7ee0bf40d
main.c compiled on  with gcc 7
```

**Crash Core Dump**

https://pastebin.com/F0LnhxpK

**Describe the traffic that generated the bug**

This problem only seems to happen under high load.

**To Reproduce**
Start OpenSIPS
Start traffic
After about 10 minutes of 750+ active dialogs the problem happens.

**OS/environment information**
 - Operating System: Ubuntu 18.04.5 LTS
 - OpenSIPS installation: debs

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , I suspect something corrupts the memory (under load) - the crash happens due a corrupted  `post_processing_cb_list` list, which is a quite static list (it does not change at all during runtime).
So, 

1. do you use some other modules/code not part of the official repo?
2. do you still have the core file, so we can double check the `post_processing_cb_list` list, maybe we can spot how it gets corrupted.
