### ISSUE TITLE
opensips-2.4.8 rabbitmq memory leak

### ISSUE THREAD

**Issue by ycxwoo** [OpenSIPS/opensips#2230]
Attached is my test procedure
[test.docx](https://github.com/OpenSIPS/opensips/files/5139888/test.docx)

**Comment by ycxwoo** [comment]
In addition, my rebbitmq server is stopped

**Comment by razvancrainea** [comment]
OpenSIPS has its own memory manager that uses system memory, but never releases it back. That's probably what you're trying to show us, but tbh, it is not very clear.
Is there any chance you could run the same setup under valgrind to see exactly what are those "leaked" memory chunks?

PS: in the future, please provide more details about what you are tracking, what you are expecting and what is going wrong. It is very hard to induce that from a document that has a few pictures on it. A guide through your troubleshooting process would be more helpful.

**Comment by ycxwoo** [comment]
Hello, I have been testing for another hour, and now the memory is up to 40%

top - 17:54:26 up 283 days,  6:38,  3 users,  load average: 0.01, 0.05, 0.07
Tasks: 134 total,   1 running, 133 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.3 sy,  0.0 ni, 99.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.2 st
KiB Mem :  1858972 total,    79904 free,  1036692 used,   742376 buff/cache
KiB Swap:  4063228 total,  4037928 free,    25300 used.   606420 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                               
 77412 root      20   0 10.672g 768388    636 S   0.0 41.3   0:15.33 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 72095 root      20   0  267076 142720 142412 S   0.0  7.7   4:37.74 /usr/lib/systemd/systemd-journald                                                                                                                                     
 72083 root      20   0  440304  73080  71556 S   0.0  3.9   1:11.18 /usr/sbin/rsyslogd -n                                                                                                                                                 
 77432 root      20   0 2195040   7864   5684 S   0.0  0.4   0:24.18 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77435 root      20   0 2195040   6628   4484 S   0.0  0.4   0:06.76 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77410 root      20   0 2195040   6500   5240 S   0.0  0.3   0:00.05 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77416 root      20   0 2195040   6360   4216 S   0.0  0.3   0:04.72 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77417 root      20   0 2195040   6104   3960 S   0.0  0.3   0:03.75 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77419 root      20   0 2195040   6104   3960 S   0.0  0.3   0:03.67 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024                                                                                             
 77440 root      20   0 2195040   6104   3960 S   0.0  0.3   0:03.11 /home/ycx/opensips/sbin/opensips -P /var/run/opensips.pid -M 1024 -m 1024  

I looked at the source code
./opensips-2.4.8/modules/event_rabbitmq/rabbitmq_send.c +366

In the function "rmq_reconnect", when "Cannot Open AMQP Socket"(line 374) occurs, the rmqp needs to be released, but the if decision in the rmq_destroy_param function makes it fail to be released

`static int rmq_reconnect(evi_reply_sock *sock)
{
    rmq_params_t * rmqp = (rmq_params_t *)sock->params;
#if defined AMQP_VERSION_v04
    amqp_socket_t *amqp_sock;
#endif
    int socket;

    if (!rmqp || !(rmqp->flags & RMQ_PARAM_RKEY)) {
        LM_ERR("not enough socket info\n");
        return -1;
    }
    if (!(rmqp->flags & RMQ_PARAM_CONN) || !rmqp->conn) {
        /* init new connection */
        if (!(rmqp->conn = amqp_new_connection())) {
            LM_ERR("cannot create new connection\n");
            return -1;
        }
#if defined AMQP_VERSION_v04
        amqp_sock = amqp_tcp_socket_new(rmqp->conn);
        if (!amqp_sock) {
            LM_ERR("cannot create AMQP socket\n");
            goto destroy_rmqp;
        }
        socket = amqp_socket_open_noblock(amqp_sock, sock->address.s,
            sock->port, &conn_timeout_tv);
        if (socket < 0) {
            LM_ERR("cannot open AMQP socket\n");
            goto destroy_rmqp;
        }
#else
`
`void rmq_destroy_param(rmq_params_t *rmqp)
{
    if (!rmqp)
        return;
    if (rmqp->conn && rmqp->flags & RMQ_PARAM_CONN) {
        if (rmqp->flags & RMQ_PARAM_CHAN) {
            rmq_error("closing channel",
                    amqp_channel_close(rmqp->conn, rmqp->channel,
                        AMQP_REPLY_SUCCESS));
        }
        rmq_error("closing connection",
                amqp_connection_close(rmqp->conn, AMQP_REPLY_SUCCESS));
        if (amqp_destroy_connection(rmqp->conn) < 0)
            LM_ERR("cannot destroy connection\n");
    }

    rmqp->flags &= ~(RMQ_PARAM_CONN|RMQ_PARAM_CHAN);
}

`

I don't understand the logic, the above code is my guess

**Comment by razvancrainea** [comment]
Could you please apply this patch and let us know if it sorts out your issue?

```
diff --git modules/event_rabbitmq/rabbitmq_send.c modules/event_rabbitmq/rabbitmq_send.c
index 2a6f06f95..c1b6e5f93 100644
--- modules/event_rabbitmq/rabbitmq_send.c
+++ modules/event_rabbitmq/rabbitmq_send.c
@@ -291,6 +291,7 @@ static int rmq_reconnect(evi_reply_sock *sock)
 		socket = amqp_socket_open_noblock(amqp_sock, sock->address.s,
 			sock->port, &conn_timeout_tv);
 		if (socket < 0) {
+			amqp_connection_close(rmqp->conn, AMQP_REPLY_SUCCESS);
 			LM_ERR("cannot open AMQP socket\n");
 			goto destroy_rmqp;
 		}

```

**Comment by razvancrainea** [comment]
Hi, @ycxwoo ! Are there any updates after applying the patch?
