### ISSUE TITLE
[consultation]How to destroy tls connection in the script?

### ISSUE THREAD

**Issue by lanxiaolin-sz** [OpenSIPS/opensips#2234]
[consultation]
Hi, Can you please tell me How to destroy tls connection in the script?

I want to use TLS for two-way authentication in the project, but I cannot bind my personal certificate to a specific user. That is to say, there may be a situation where I use a valid certificate to cheat authentication and then log in with someone else's user password.

if ($tls_peer_subject_cn!=$fU)
{
**Here could be script to destroy tls connect**
exit;
}

Any Suggestions?

**Comment by lanxiaolin-sz** [comment]
When I use the function [destroy_tls](https://opensips.org/docs/modules/2.4.x/tls_mgm.html#idp31300352)，It did not work。the log was ”unknow command 《destroy_tls》“

**Comment by razvancrainea** [comment]
You cannot forcefully terminate a stream connection from the script.
For further questions, please use our [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).
