### ISSUE TITLE
Invite with authorization header fwd/load balancer

### ISSUE THREAD

**Issue by korithi** [OpenSIPS/opensips#2235]
Hello,

I have an opensips proxy in the middle of client and server and I am using it for load balancing, with load balancer module.
I send the invite from client to server and server sends 401 and require authentication. Client sends ack and then sends the second invite with the credentials. 
My problem is that the second invite goes again in a random server selected by the load balancer. I want that second invite with the authorization header to go on the same server that requested the nonce challange.
How can I achieve this?

Thanks

**Comment by razvancrainea** [comment]
When the 401 reply comes, you can store in a [local cache](https://opensips.org/docs/modules/3.1.x/cachedb_local.html) a mapping between the callid and the actual server chosen. When the second INVITE is sent, you should deliver the call the the server in cache.
For followups regarding this topic, please use our [users mailing lists](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).
