### ISSUE TITLE
[BUG] Dynamic sip tracing not enabled on creation

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#2240]
**OpenSIPS version you are running**
```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 11:12:50 Sep  4 2020 with gcc 8
```

**Describe the bug**
Hi team,

If I have in the script:
```
#### HEP module
loadmodule "proto_hep.so"
modparam("proto_hep", "hep_id", "[hep_dst] <ip>:<port>; transport=udp; version=3")
#### SIP Tracing module
loadmodule "tracer.so"
modparam("tracer", "trace_on", 0)
modparam("tracer", "trace_id", "[test]uri=hep:hep_dst")
```
and in several places of routing script:
`trace("test", "t");`

Tracing is disabled by default and it's very seldom when I want to enable it to get all the SIP traffic to HEP server or to DB. But of course, I can enable it with 'opensips-cli -x mi trace mode=on'
And I have opensips-cli and it's relatively often, when I want to trace some IP-address or user using console without enabling global tracing. I can create dynamic tracing, but OpenSIPS does not send anything to dynamically created destinations, as global tracing is disabled.
So how to use these short-living dynamic tracings without enabling all the statically configured destinations?

**To Reproduce**
1. Use module `tracer`, but set `trace_on=0`. Several static tracing destinations (to HEP, DB), which are used very seldom.
2. Start `opensips-cli` and use command `trace` to create dynamic tracing ID.
3. Nothing comes from OpenSIPS

**Expected behavior**
Dynamic tracing ID should be enabled by default without globally enabling all possible destinations.

**OS/environment information**
 - Operating System: CentOS Linux release 8.2.2004 (Core)
 - OpenSIPS installation: `git`
 - other relevant information:

**Comment by vasilevalex** [comment]
waiting for review

**Comment by razvancrainea** [comment]
Hi, @vasilevalex !

Thanks for refreshing the status of the ticket!
The way I see it, there is indeed a buggy behavior the fact that the `opensips-cli trace` is waiting for traffic, even if OpenSIPS "knows" it will never come. In order to fix this, I can add an extra check in opensips to decline any `trace_start` when tracing is disabled - but I am not sure that is what you want.
Most likely (and I totally agree with) that tracing should be temporary started for the filtered traffic, correct? If that's the case, the module was indeed not intended to work like this, so this should probably transformed into a feature request.
So in order to sort out this bug, I see two action points:

Best regards,
Răzvan

**Comment by vasilevalex** [comment]
Hi @razvancrainea , can you please look at my PR - it is not enabling global tracing, but adds condition to check, if any of dynamic tracing exists. But when dynamic tracing is deleted (opensips-cli stopped tracing), so OpenSIPS will just continue working with tracing disabled.

**Comment by razvancrainea** [comment]
I did see the #2241 PR, but TBH I didn't initially fully understand exactly what it was solving. Now that I look at it, I suspect it is not fully OK, as it will temporary enable all tracing (for all endpoints), not just for the traffic filtered dynamical - isn't that true?

**Comment by vasilevalex** [comment]
@razvancrainea may be I missed something... I'll check. But what do you think, is this approach correct? I mean temporary enable only dynamic tracing endpoints.

**Comment by vasilevalex** [comment]
@razvancrainea I've rechecked the changes. When going through `trace_list` (static entries) it always checks `(it->traceable && !(*it->traceable))` and during init stage this flag is set to the value of global `trace_on`. And I also made tests and I have traces in opensips-cli, but have nothing send over hep.

**Comment by vasilevalex** [comment]
up

**Comment by vasilevalex** [comment]
up

**Comment by razvancrainea** [comment]
Just pushed a fix for this, could you please check if sorts out your problem?

**Comment by vasilevalex** [comment]
Thanks @razvancrainea . Now both static and dynamic tracing works fine.
