### ISSUE TITLE
[QUESTION]How to make a call selection?

### ISSUE THREAD

**Issue by lanxiaolin-sz** [OpenSIPS/opensips#2245]
Can you help me answer this question?

Background: There are multiple users in a group; our system has multiple groups.
![image](https://user-images.githubusercontent.com/68832207/92686593-8d3faf00-f36c-11ea-8eaa-c1677b04a335.png)

**Are there any modules in opensips2.4.8 that can help** realize the following scenarios:
When a user (UF) dials to a group G, the mobile phones of all users in the group G are invited, and when one of the users (UR) accepts the invitation, the other user terminals stop being invited.
After that, UF talks with UR normally.

### The process is as follows:
**1.User UF INVITE group G:**
![image](https://user-images.githubusercontent.com/68832207/92686242-d93e2400-f36b-11ea-9445-0ff3a0fa8d2f.png)
**2.Cell phones of all users in group G ring:**
![image](https://user-images.githubusercontent.com/68832207/92686265-e78c4000-f36b-11ea-9050-d8380f0ef089.png)
**3.User B accepts the call**
![image](https://user-images.githubusercontent.com/68832207/92686290-ef4be480-f36b-11ea-860e-4cd46d2cc913.png)
**4.Other users stop ringing**
![image](https://user-images.githubusercontent.com/68832207/92686390-23bfa080-f36c-11ea-90b9-7719bcb32808.png)
**5.User UF and User B start a conversation**
![image](https://user-images.githubusercontent.com/68832207/92686405-291ceb00-f36c-11ea-8724-e7e79dc70a3b.png)

Hope to get your reply. Thank you.

**Comment by bogdan-iancu** [comment]
@lanxiaolin-sz , that is call parallel SIP forking and openspis does support it. All you need is to use TM module, with `append_branch(URI)` in order to add all the destinations before doing `t_relay()`. But again, it is 100% scripting.
