### ISSUE TITLE
[BUG] IPv6 addresses in path received parameter are not enclosed in brackes.

### ISSUE THREAD

**Issue by hafkensite** [OpenSIPS/opensips#2247]
**OpenSIPS version you are running**
```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0
```

**Describe the bug**
When calling the `add_path_received` method of the path module, the IP address is added using a simple snprintf. That results in an invalid path when the IP is of the INET6 family.

**To Reproduce**
1. Start OpenSIPS with a config that uses `add_path_received` and listens on IPv6
2. Send SIP messages using an IPv6 client
3. Notice the route headers of forwarded messages
4. Observe that the path will look like `Path: <sip:[2001:DB8:1478:1:E6F1:A1A7:CF92:22]:6060;r2=on;lr;received=sip:2001:DB8:1478:1:204:13FF:FE7D:2A60:39645>`

**Expected behavior**
The path to be properly formatted, by having `[` `]` around them. 
`Path: <sip:[2001:DB8:1478:1:E6F1:A1A7:CF92:22]:6060;r2=on;lr;received=sip:[2001:DB8:1478:1:204:13FF:FE7D:2A60]:39645>`

**Relevant System Logs**
None

**OS/environment information**
Debian 9 using self build debs

**Possible fix**
I did some tweaking of path.c, and did get the expected output with this patch. I assume it can be done much prettier, but am not that deep into C and the OpenSIPS way of doing string manipulation.

``` diff
--- a/lib/path.c
+++ b/lib/path.c
@@ -114,14 +114,20 @@ static int build_path(struct sip_msg* _m, struct lump* l, struct lump* l2,
                goto out4;
 
        src_ip = ip_addr2a(&_m->rcv.src_ip);
-       rcv_addr.s = pkg_malloc(4 + IP_ADDR_MAX_STR_SIZE + 7 +
+       rcv_addr.s = pkg_malloc(4 + 2 + IP_ADDR_MAX_STR_SIZE + 7 +
                PATH_ESC_TRANS_PARAM_LEN + 4); /* sip:<ip>:<port>(\0|[%3btransport%3dxxxx]) */
        if (!rcv_addr.s) {
                LM_ERR("no pkg memory left for receive-address\n");
                goto out5;
        }
-       rcv_addr.len = snprintf(rcv_addr.s, 4 + IP_ADDR_MAX_STR_SIZE + 6,
+       if ((&_m->rcv.src_ip)->af == AF_INET6) {
+               rcv_addr.len = snprintf(rcv_addr.s, 4 + 2 + IP_ADDR_MAX_STR_SIZE + 6,
+                               "sip:[%s]:%u", src_ip, _m->rcv.src_port);
+       } else {
+               rcv_addr.len = snprintf(rcv_addr.s, 4 + IP_ADDR_MAX_STR_SIZE + 6,
                                "sip:%s:%u", src_ip, _m->rcv.src_port);
+       }
+
        switch (_m->rcv.proto) {
        case PROTO_TCP:
                memcpy(rcv_addr.s+rcv_addr.len, PATH_ESC_TRANS_PARAM "tcp",
```

**Comment by bogdan-iancu** [comment]
Thank you @hafkensite for the report. Also your fix is more than fine ;), it is the one I pushed on GIT.

**Comment by bogdan-iancu** [comment]
@hafkensite related to the same code, could you please test the e1347ebe47984492f5a7d383ef00559ce41da8be + 72e4b9d4f85ed5f8a745811fd47f6a2d02a6a993 (latest 2.4 code) ? I pushed a fix for supporting all the SIP transport protocols when building the received param. Thank you
