### ISSUE TITLE
[BUG] The presence body gets corrupted when multiple PUBLISHes for same presentity is delivered in short time.

### ISSUE THREAD

**Issue by GouthamPMadhava** [OpenSIPS/opensips#2249]
**OpenSIPS version you are running**

```
2.4.5
```

**Describe the bug**
The presence body gets corrupted when multiple PUBLISHes for same presentity is delivered in short time and continues to add an extra body for all PUBLISHes resulting in multiple bodies in NOTIFY..

**To Reproduce**
1. Start OpenSIPS as presence server
2. Send SIP PUBLISHes to publish the state of prentities
3. Ensure to send multiple PUBLISHes within few miliseconds
4. Inspect traces to see multiple published bodies are bundled up in to SIP NOTIFY
5. Continue to send PUBLISH but not too fast like in point 3.
6. Inspect traces to see that one of the states is stuck in every NOTIFY body

**Expected behavior**

The NOTIFYs OpenSIPs presence server generates should reflect exact information that is being published by UAC.

**Relevant System Logs**

**OS/environment information**
 - Operating System: RHEL 7.2
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**
Attached schreenshot has the pcap and opensips log in debug. Packet 46 is the first occurrence of OpenSIPs trying to bundle up multiple published bodies of a presentity sip:2601@ipc.com. Every NOTIFY for the presentity afterwards will have an extra body with status as BUSY. I checked the presentity table in Mongo DB and it always contains the single body from latest PUBLISH, however, the NOTIFYs continues to have this extra status. So, clearly its some corruption in cache level.

Request you to share some insight. Thanks a lot in advance!

![image](https://user-images.githubusercontent.com/71355516/93293773-c0dc6800-f7b6-11ea-8863-61ea163ae416.png)

**Comment by GouthamPMadhava** [comment]
Does anyone have any suggestion/questions/update on this issue. It'll greatly help as this issue is a major risk and hinder our for our coming release.

**Comment by bogdan-iancu** [comment]
@GouthamPMadhava , you mentioned some pcap file, but I do not see it here - could you upload it again ?

**Comment by GouthamPMadhava** [comment]
Thank you for the response @bogdan-iancu . Sorry for missing attachment. Let me know if you need any additional information. Thanks in advance!
[presence_status_corruption_filtered.zip](https://github.com/OpenSIPS/opensips/files/5313243/presence_status_corruption_filtered.zip)

**Comment by GouthamPMadhava** [comment]
Hi @bogdan-iancu Sorry for asking again but it's inevitable. Did you get any chance to help us out? Curious and eager to know. Thanks again in advance!

**Comment by GouthamPMadhava** [comment]
Anyone have any suggestions/updates? Please do let me know if one needs any additional information.

**Comment by GouthamPMadhava** [comment]
Thanks a lot @bogdan-iancu for your response!
Yes, PUBLISHes are being sent by the same device to same presentity. Let me take a look at Etag suggestion and get back.
Will also try reproducing the issue (without Etag fix) and get you the output of pres_phtable_list. Hope that works.

**Comment by GouthamPMadhava** [comment]
I have double checked the Etag suggestion you made and we do use the SIP-Etag from 200 OK of PUBLISH in the next PUBLISH. OpenSIPs is sending different Etag for every PUBLISH and we are using the new SIP-Etag from 200OK of latest PUBLISH. However, you might be noticing the same Etag in couple of PUBLISHes due to the fact that it's sending multiple PUBLISHes within short span of time. Hope this clarifies.

**Comment by GouthamPMadhava** [comment]
Hi @bogdan-iancu 

Simulated burst of 5 PUBLISHes through SIPp. Attached zip has the pcap for the same and you'll see NOTIFY with person and note tags. Below is the output of pres_phtable_list.

bash-4.2# /opt/ipc/opensips/opensipsctl fifo pres_phtable_list
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.34.81.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.33.60.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.33.59.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.31.28.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.32.33.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.29.28.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.33.58.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.33.57.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.34.80.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.34.79.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.25.16.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.29.27.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.27.17.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.34.78.0
pres_uri:: sip:1001@172.29.109.129 event=1 etag_count=1 etag=a.1603850558.33.56.0
pres_uri:: sip:24301-1@ipc.com event=1 etag_count=21 etag=a.1603850558.29.26.20
bash-4.2#

Regards,
Goutham Prasad
[OpenSIPs_2249_20201028.zip](https://github.com/OpenSIPS/opensips/files/5454409/OpenSIPs_2249_20201028.zip)

**Comment by vkuzmenok** [comment]
@bogdan-iancu 
Bogdan, we did more testing related to the issue. 
When we try to use etag from the initial 200 OK, we are getting 412 response, which is expected and complies with RFC.
Once we get 412 the response, following the RFC we send another PUBLISH without the SIP-If-Match tag. Since opensips still has a record for the presentity with another etag, the PUBLISH without etag causes a duplicate record at the opensips end.
Is there a way opensips can handle PUBLISH without SIP-If-Match differently or at least when NOTIFY is generated using only the latest publish from the DB?

**Comment by bogdan-iancu** [comment]
@vkuzmenok , is this issue still a valid one? if yes, please re-open.
