### ISSUE TITLE
[BUG] CentOS packages don't work

### ISSUE THREAD

**Issue by lnicola** [OpenSIPS/opensips#2256]
Sorry if this isn't the proper place to report packaging bugs, but I didn't see a more suitable repo in the GitHub org, nor an email address on https://yum.opensips.org/.

The OpenSIPS 3.1 CentOS `opensips-cli` packages don't work:

 - on CentOS 7, the stable package wants e.g. `python3-sqlalchemy`, but EPEL has `python34-sqlalchemy` and `python36-sqlalchemy`
 - on CentOS 8, the stable package wants `python3-sqlalchemy-utils`, which isn't in the repo
 - on CentOS 8, the nightly package wants `python36-sqlalchemy`, but only `python3-sqlalchemy` is available
 - on CentOS 7, the nightly package seems to work

Bonus: 3.1 isn't available on hub.docker.com.

**Comment by volga629-1** [comment]
You need enable nightly repo to intall opensips-cli. That issue has being addressed.

**Comment by lnicola** [comment]
Thanks, I mentioned that the CentOS 7 nightly seems to install. However:

```
[root@042c7ac128b1 /]# opensips-cli -x database create
Traceback (most recent call last):
  File "/usr/bin/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/bin/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/lib/python3.6/site-packages/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 242, in cmdloop
    ret = self.run_command(self.command[0], command, params)
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 357, in run_command
    return mod[0].__invoke__(cmd, params)
  File "/usr/lib/python3.6/site-packages/opensipscli/module.py", line 36, in __invoke__
    return f(params)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/database.py", line 365, in do_create
    admin_url = self.get_admin_db_url(db_name)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/database.py", line 287, in get_admin_db_url
    engine = osdb.get_db_engine()
  File "/usr/lib/python3.6/site-packages/opensipscli/db.py", line 815, in get_db_engine
    engine = osdb.get_url_driver(cfg.get('database_url'))
  File "/usr/lib/python3.6/site-packages/opensipscli/db.py", line 884, in get_url_driver
    return make_url(url).drivername.lower()
NameError: name 'make_url' is not defined
```

**Comment by volga629-1** [comment]
Check python dependencies.

**Comment by jiml-n2net** [comment]
I am having the same result on CentOS 8.  I used a download of the current master branch to build an rpm from the spec file. I  checked the python dependencies and all of the requested packages have been installed as per https://github.com/OpenSIPS/opensips-cli/blob/master/docs/INSTALLATION.md.

**Comment by bogdan-iancu** [comment]
Let me get involved here the person maintaining the RPM repos, @nikbyte

**Comment by razvancrainea** [comment]
It looks like you're missing the `sqlalchemy_utils` package.

Best regards,
Răzvan

**Comment by jiml-n2net** [comment]
There is no sqlalchemy_utils in CentOS 7 or 8, even with the EPEL repository added.

**Comment by razvancrainea** [comment]
Yup, that's unfortunate, but you can still install them using `pip` as [instructed](https://github.com/OpenSIPS/opensips-cli/blob/master/docs/INSTALLATION.md#red-hat--centos).

**Comment by razvancrainea** [comment]
I did found an rpm [here](https://fedora.pkgs.org/33/fedora-x86_64/python3-sqlalchemy-utils-0.34.2-5.fc33.noarch.rpm.html). I will try to give it a shot and if everything works fine I will kindly ask @nikbyte to include it in our repository.

**Comment by volga629-1** [comment]
You can try http://ftpsrv01.networklab.ca/ that  fedora server rpm. Right now we use fedora server 32 stable.


cat /etc/yum.repos.d/networklab.repo 

```
[networklab-F32-Server]
name = VoIP - NetworkLab
baseurl = http://ftpsrv01.networklab.ca/fedora/32/RPMS/$basearch
enabled = 1
protect = 0
gpgcheck = 1
gpgkey = http://ftpsrv01.networklab.ca/fedora/32/RPMS/keys/RPM-GPG-KEY-NetworkLab-F32-Server

[networklab-F32-Server-noarch]
name = VoIP Noarch - NetworkLab
baseurl = http://ftpsrv01.networklab.ca/fedora/32/RPMS/noarch
enabled = 1
protect = 0
gpgcheck = 1
gpgkey = http://ftpsrv01.networklab.ca/fedora/32/RPMS/keys/RPM-GPG-KEY-NetworkLab-F32-Server
```

**Comment by nikbyte** [comment]
Still in plans to fix soon.

**Comment by lnicola** [comment]
No, bot, this is not stale.

**Comment by davidlawson83** [comment]
@lnicola I had the same issue as you but if I run opensips-cli and specify the python version it works 

`python3 /usr/bin/opensips-cli  -x database create`

**Comment by nikbyte** [comment]
What version do you have installed?

**Comment by davidlawson83** [comment]
@nikbyte 

CentOS Linux release 7.9.2009 (Core)
OpenSIPS CLI 0.1.0

**Comment by nikbyte** [comment]
Show me please also python packages installed:
```rpm -qa|grep python|sort```

**Comment by davidlawson83** [comment]
> Show me please also python packages installed:
> `rpm -qa|grep python|sort`

`rpm -qa|grep python|sort
audit-libs-python-2.8.5-4.el7.x86_64
dbus-python-1.1.1-9.el7.x86_64
libselinux-python-2.5-15.el7.x86_64
libsemanage-python-2.5-14.el7.x86_64
libxml2-python-2.9.1-6.el7.5.x86_64
MySQL-python-1.2.5-1.el7.x86_64
newt-python-0.52.15-4.el7.x86_64
policycoreutils-python-2.5-34.el7.x86_64
python-2.7.5-90.el7.x86_64
python3-3.6.8-18.el7.x86_64
python36-asn1crypto-0.24.0-7.el7.noarch
python36-cffi-1.9.1-3.el7.x86_64
python36-cryptography-2.3-2.el7.x86_64
python36-idna-2.10-1.el7.noarch
python36-mysql-1.3.12-2.el7.x86_64
python36-ply-3.9-2.el7.noarch
python36-pycparser-2.14-2.el7.noarch
python36-pyOpenSSL-17.3.0-1.el7.noarch
python36-six-1.14.0-2.el7.noarch
python36-sqlalchemy-1.1.3-3.el7.x86_64
python3-devel-3.6.8-18.el7.x86_64
python3-libs-3.6.8-18.el7.x86_64
python3-pip-9.0.3-8.el7.noarch
python3-rpm-generators-6-2.el7.noarch
python3-rpm-macros-3-34.el7.noarch
python3-setuptools-39.2.0-10.el7.noarch
python-chardet-2.2.1-3.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-dateutil-1.5-7.el7.noarch
python-decorator-3.4.0-3.el7.noarch
python-gobject-base-3.22.0-1.el7_4.1.x86_64
python-iniparse-0.4-9.el7.noarch
python-IPy-0.75-6.el7.noarch
python-kitchen-1.1.1-5.el7.noarch
python-libs-2.7.5-90.el7.x86_64
python-linux-procfs-0.4.11-4.el7.noarch
python-perf-3.10.0-1160.6.1.el7.x86_64
python-pycurl-7.19.0-19.el7.x86_64
python-pyudev-0.15-9.el7.noarch
python-rpm-macros-3-34.el7.noarch
python-schedutils-0.4-6.el7.x86_64
python-srpm-macros-3-34.el7.noarch
python-urlgrabber-3.10-10.el7.noarch
rpm-python-4.11.3-45.el7.x86_64`

**Comment by nikbyte** [comment]
Guys, I installed minimized CentOS Linux release 7.9.2009 (Core), then installed epel-release and opensips-cli after it. Everything works well as expected.

```

**Comment by nikbyte** [comment]
Guys, I installed minimized CentOS Linux release 7.9.2009 (Core), then installed epel-release and opensips-cli after it. Everything works well as expected.

```
opensips-cli --help
usage: /bin/opensips-cli [OPTIONS]

OpenSIPS CLI interactive tool

positional arguments:
  command               the command to run

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  -d, --debug           enable debugging
  -f [FILE], --config [FILE]
                        used to specify a configuration file
  -i [INSTANCE], --instance [INSTANCE]
                        choose an opensips instance
  -o [KEY=VALUE], --option [KEY=VALUE]
                        overwrite certain values in the config
  -x, --execute         run the command in non-interactive mode
  ```
  
  ```
  # opensips-cli
Welcome to OpenSIPS Command Line Interface!
(opensips-cli):
```

I really have no idea what to fix for you or how can I help.

**Comment by lnicola** [comment]
@nikbyte which OpenSIPS repo did you use? 3.1, release?

**Comment by nikbyte** [comment]
Yes, I used 3.1. Do you want me to try another one?

**Comment by lnicola** [comment]
How did you install it? I get (on `centos:7):

```
[root@28d4340b11f7 /]# yum install https://yum.opensips.org/3.1/releases/el/8/x86_64/opensips-yum-releases-3.1-6.el8.noarch.rpm 
Loaded plugins: fastestmirror, ovl
opensips-yum-releases-3.1-6.el8.noarch.rpm                                                                                                                                                  | 8.1 kB  00:00:00     
Examining /var/tmp/yum-root-MNLp4P/opensips-yum-releases-3.1-6.el8.noarch.rpm: opensips-yum-releases-3.1-6.el8.noarch
Marking /var/tmp/yum-root-MNLp4P/opensips-yum-releases-3.1-6.el8.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package opensips-yum-releases.noarch 0:3.1-6.el8 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================================================================================
 Package                                              Arch                                  Version                                   Repository                                                              Size
===================================================================================================================================================================================================================
Installing:
 opensips-yum-releases                                noarch                                3.1-6.el8                                 /opensips-yum-releases-3.1-6.el8.noarch                                2.2 k

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total size: 2.2 k
Installed size: 2.2 k
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by opensips-yum-releases-3.1-6.el8.noarch
RPM needs to be updated
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2021-01-08.16-00.6djMzC.yumtx
```

**Comment by nikbyte** [comment]
but you're installing el8 repository. install el7 one.

**Comment by nikbyte** [comment]
`yum install https://yum.opensips.org/3.1/releases/el/7/x86_64/opensips-yum-releases-3.1-6.el7.noarch.rpm`

**Comment by lnicola** [comment]
Oh, right. That was a botched `Ctrl-C`, sorry. Can you try?

```
[root@28d4340b11f7 /]# opensips-cli -x database create
Traceback (most recent call last):
  File "/usr/bin/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/bin/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/lib/python3.6/site-packages/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 242, in cmdloop
    ret = self.run_command(self.command[0], command, params)
  File "/usr/lib/python3.6/site-packages/opensipscli/cli.py", line 357, in run_command
    return mod[0].__invoke__(cmd, params)
  File "/usr/lib/python3.6/site-packages/opensipscli/module.py", line 36, in __invoke__
    return f(params)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/database.py", line 367, in do_create
    admin_url = self.get_admin_db_url(db_name)
  File "/usr/lib/python3.6/site-packages/opensipscli/modules/database.py", line 287, in get_admin_db_url
    engine = osdb.get_db_engine()
  File "/usr/lib/python3.6/site-packages/opensipscli/db.py", line 815, in get_db_engine
    engine = osdb.get_url_driver(cfg.get('database_url'))
  File "/usr/lib/python3.6/site-packages/opensipscli/db.py", line 892, in get_url_driver
    return make_url(url).drivername.lower()
NameError: name 'make_url' is not defined
```

**Comment by nikbyte** [comment]
This is not a repository issue. Everything next ask in another ticket or in users list.
As far as I understand this is related to your configuration file (database_url) option.

**Comment by nikbyte** [comment]
There is no repository issue anymore. Double checked. That's why I'm closing it.

**Comment by lnicola** [comment]
It's not a missing option (`database_url`), it's a missing _function_, which should have been imported from a (probably missing) `sqlalchemy` dependency:

```py
    from sqlalchemy.engine.url import make_url
```

**Comment by nikbyte** [comment]
I checked. This is because centos doesn't have sqlalchemy_utils library.
You can install it via pip, for example and have it working.

**Comment by lnicola** [comment]
Shouldn't that be included in the OpenSIPS  repo, like other dependencies presumably are? I don't think "install our RPMs, then hunt missing dependencies on pip" is a good experience.
