### ISSUE TITLE
[BUG] OpenSIPS fails to start - systemd type=forking using sipcapture.so

### ISSUE THREAD

**Issue by ghmj2417** [OpenSIPS/opensips#2259]
**OpenSIPS version you are running**

```
2.4.8
3.0.3
3.1.0
```

**Describe the bug**

OpenSIPS will fail to start when using systemd with type=forking when trying to use module `sipcapture.so`.

**To Reproduce**

Use a default opensips.cfg and add
```
loadmodule "db_mysql.so"
loadmodule "proto_hep.so"
loadmodule "sipcapture.so"

listen=hep_udp:127.0.0.1:9060
listen=hep_tcp:127.0.0.1:9060
```
Use default opensips.service systemd file

Try to start opensips `systemctl start opensips`

**Expected behavior**

OpenSIPS will start

**Relevant System Logs**

This is the only log entry that shows useful information `opensips: INFO:core:daemonize: pre-daemon process exiting with -1`.

I am not familiar with c language but I added some logging and found that in `daemonize.c/int wait_status_code(char *code)` the last proc from `daemonize.c/int wait_for_all_children(void)` will always return `rc = 0` and `code = 0 byte` whereas all of the other procs return `rc = 1` and `code = 1 byte`.

This is how I discovered where within daemonize it was exiting. Sorry about the crudity of the logs.  As I mentioned, I am not familiar with c.

With `loadmodule "sipcapture.so"` in the config
```
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 18
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 19
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 14:53:05 myhost /usr/local/sbin/opensips[30959]: INFO:sipcapture:child_init: pre db_url.s
Sep 24 14:53:05 myhost /usr/local/sbin/opensips[30959]: INFO:sipcapture:child_init: post db_url.s
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 20
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status rc 0
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: read code 0 (0 byte)
Sep 24 14:53:05 myhost opensips: INFO:core:wait_status_code: wait_status error!
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret -1
Sep 24 14:53:05 myhost opensips: INFO:core:wait_for_all_children: uh oh found an error!
Sep 24 14:53:05 myhost opensips: INFO:core:daemonize: daemonize rc -1
Sep 24 14:53:05 myhost opensips: INFO:core:daemonize: pre-daemon process exiting with -1
```

Without `loadmodule "sipcapture.so"` in the config
```
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 16
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 17
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 18
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: procs_no iter 19
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status code 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status end
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status retry
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status_code status_pipe 5
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: wait_status rc 1
Sep 24 15:19:41 myhost opensips: INFO:core:wait_status_code: read code 0 (1 byte)
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: wait_for_all iter ret 0
Sep 24 15:19:41 myhost opensips: INFO:core:wait_for_all_children: wait_for_children return 0
Sep 24 15:19:41 myhost opensips: INFO:core:daemonize: daemonize rc 0
Sep 24 15:19:41 myhost opensips: INFO:core:daemonize: pre-daemon process exiting with 0
```

**OS/environment information**
 - Operating System: Amazon Linux 2
 - OpenSIPS installation: git or opensips yum repo (both have the problem)
 - other relevant information:

**Additional context**

When I change the systemd type to simple, OpenSIPs can start.
OpenSIPs will start if I execute from shell `/usr/sbin/opensips -f /etc/opensips/opensips.cfg -m 1024 -M 64`
Do not experience this with 2.3.6

**Comment by ghmj2417** [comment]
Do you need anymore information for this issue?

**Comment by razvancrainea** [comment]
@ghmj2417 yes, could you please set the log level to `6` and start again? Thanks!

**Comment by ghmj2417** [comment]
@razvancrainea I don't think this is going to tell you anything about the specific proc returning a -1.  You may need add additional logging around the methods I identified in the issue but I am not completely sure.

Additional logs with log_level set to 6
https://pastebin.com/TMEVzSAv

**Comment by ghmj2417** [comment]
Were those logs beneficial or do we need to setup additional logging?

**Comment by ghmj2417** [comment]
Anything else I can provide?

**Comment by ghmj2417** [comment]
Well I went ahead and 'fixed' it so I could at least start the service.  In `daemonize.c`, method `int wait_for_all_children(void)` I changed the for loop `for (i=0;i<procs_no;i++)` to `for (i=0;i<procs_no-1;i++)` (I also tested `for (i=1;i<procs_no;i++)` and that also worked).  Is this the correct way of fixing it? No idea but I can start the service now.

**Comment by razvancrainea** [comment]
I've just got some time to check this out and I managed to reproduce this issue and figure out the problem. However a fix is not that straight forward, and I need to think this through. If you can do the `-1` trick (the one you already did), that should be fine. Alternatively, enable the [raw_ipip_capture_on](https://opensips.org/docs/modules/3.1.x/sipcapture.html#param_raw_ipip_capture_on) feature.
Will keep this posted until I figure out how to sort this out.

**Comment by ghmj2417** [comment]
Thanks @razvancrainea.  I'll continue to use my workaround until this is fixed.

**Comment by gmaruzz** [comment]
+1

**Comment by gmaruzz** [comment]
btw, with 2.4.6 debian packages it was (and still is) working
I tried 2.4.9 in another install, now I have a lot less of my already gone hair... :)

**Comment by ghmj2417** [comment]
Any update?  Should I continue to use my workaround or is there a different option I should test?

**Comment by razvancrainea** [comment]
@ghmj2417 just figured out a solution, will soon push a fix for the `sipcapture` module as well. Any chance you could run a test with the master patch? Thanks!

**Comment by razvancrainea** [comment]
@ghmj2417 awesome - can you please apply the latest commit of master (065784586cd83fd6af53c7121763edcfa2ca999e) in your source code and run another test? Thanks!

**Comment by ghmj2417** [comment]
@razvancrainea Tested successfully on version 3.1.1 using commit (https://github.com/OpenSIPS/opensips/commit/065784586cd83fd6af53c7121763edcfa2ca999e).  OpenSIPS started successfully using type=forking with sipcapture module.

**Comment by razvancrainea** [comment]
Thanks for checking this out, back-porting now!
