### ISSUE TITLE
LB load count

### ISSUE THREAD

**Issue by korithi** [OpenSIPS/opensips#2266]
Hello guys
OpenSIPS (3.1.0 (x86_64/linux)) installed from repository on Debian 10.

I have configured and using opensips as a load balancer.
Actually I noticed that the load is not displayed properly when I run 
mi lb_list
**"id": 12,
            "group": 1,
            "enabled": "yes",
            "auto-reenable": "on",
            "Resources": [
                {
                    "name": "calls",
                    "max": 1000,
                    "load": 0
**

In older versions of opensips I have configured load balancer too, I could see the load on each gateway.
Is there smth I might have missed?

Thank you!
Rafael

**Comment by bogdan-iancu** [comment]
What is the exact version of your opensips (do an `opensips -V`) ?
And to be sure I understand correctly, what is the problem with the displaying? is is a bit difficult to guess from the listing you did.

**Comment by korithi** [comment]
Hi Bogdan,

version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

I do have a load balancer applied and the resources are only calls. Normally I think I should see the load when I execute "mi lb_list" but the load is usually 0 on each gateway.

Actually I have these calls on the proxy as per below, but the still the load on lb_list is 0 in all gateways. Even when I have more calls it is the same. 
(opensips-cli): mi get_statistics active_dialogs
{
    "dialog:active_dialogs": 15
}
(opensips-cli): mi get_statistics earcly_dialogs
{}
(opensips-cli): mi get_statistics early_dialogs
{
    "dialog:early_dialogs": 194

I wrote to you because I see in the media servers I have behind the proxy that the distribution of calls is not equal when I use load balancer. Is there any way I can troubleshoot or check the call distribution?
Another question: does the load status in lb module includes early dialogs too, or just active dialogs?

Thanks,
Rafael

**Comment by korithi** [comment]
Hi Bogdan,

Is there any suggestion?

Thanks,
Rafael
