### ISSUE TITLE
[BUG] cgrates.so hang cgrates_acc after cgrates_auth

### ISSUE THREAD

**Issue by barnabyritchley** [OpenSIPS/opensips#2271]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**

When running opensips with cgrates, opensips hangs on cgrates_acc() function.  Running the same script in debug mode (debug_mode=yes), everything works as expected.  As soon as debug_mode is disabled, the hang starts.

The last message seen when not running debug is:

```
DBG:cgrates:w_cgr_acc: engaging accounting for all branches!
DBG:cgrates:cgr_new_acc_ctx: new acc ctx=0x7fe2aa6705b8
```

When running in debug mode, script continues on to 

```
DBG:cgrates:w_cgr_acc: engaging accounting for all branches!
DBG:cgrates:cgr_new_acc_ctx: new acc ctx=0x7fa473c129b0
DBG:cgrates:cgr_new_acc_ctx: init ref=1 ctx=0x7fa473c129b0
DBG:cgrates:cgr_ref_acc_ctx: general ctx ref=2 ctx=0x7fa473c129b0
DBG:cgrates:w_cgr_acc: session info tag= acc=003830-9A2A dst=+447779330921 mask=FFFFFFFF
DBG:cgrates:cgr_ref_acc_ctx: tm ref=3 ctx=0x7fa473c129b0
INFO:SCRIPT: CGRateS: Call Accounting Started
```

Ive attached two logs - one where the script hangs with debug mode disabled, and another where debug mode is enabled and everything continues as normal.

**To Reproduce**

Script block is as follows:

```
route [main_route] {
		# Configure CGrates
		$cgr_opt(GetMaxUsage) = 1;
		$cgr_opt(GetAttributes) = 1;
		$cgr_opt(Tenant) = 'customerName';

		$cgr(FromUser) = $fU;
		$cgr(RequestType) = "*prepaid";

		$avp(contract_id) = '003422-HBDF';

		if (!async(cgrates_auth($avp(contract_id), $rU), resume_cgr_auth)) {
			sl_send_reply(503, "Service Unavailable");
			exit;
		}
}

route [resume_cgr_auth] {
	if ($rc != 1) {
		xlog("INFO:SCRIPT: CGRateS: Call not authorized: code=$cgrret!\n");
		send_reply(403, "Forbidden");
		exit;
	}
	xlog("INFO:SCRIPT: CGRateS: Call authorized\n");

	$var(idx) = 0;
	while ($(cgr_ret(AttributesDigest){s.select,$var(idx),,}) != NULL) {
		$avp($(cgr_ret(AttributesDigest){s.select,$var(idx),,}{s.select,0,:}))
			= $(cgr_ret(AttributesDigest){s.select,$var(idx),,}{s.select,1,:});
		$var(idx) = $var(idx) + 1;
	}


	cgrates_acc("cdr|missed", $avp(contract_id), $rU);
	xlog("INFO:SCRIPT: CGRateS: Call Accounting Started\n");
}

```

**Expected behavior**

**Relevant System Logs**

[opensips-debug-working.txt](https://github.com/OpenSIPS/opensips/files/5312579/opensips-debug-working.txt)
[opensips-debug-hang.txt](https://github.com/OpenSIPS/opensips/files/5312580/opensips-debug-hang.txt)

**OS/environment information**
 - Operating System: Debian 10.5
 - OpenSIPS installation: apt repo
 - other relevant information:

**Additional context**

**Comment by barnabyritchley** [comment]
After a bit more digging, I decided to set the tcp_workers to match what happens in debug mode.

Amazingly, setting the tcp_workers to anything other than 8 works.  As soon as I set the tcp_workers to 8 the script hangs as above.

Does anyone have any idea on what could be causing this behaviour?  We are using OpenSIPS with TLS, Clusterer and CGRateS - im wondering whether we are hitting resource problem with TCP based modules?

**Comment by vtzan** [comment]
Dear @barnabyritchley ,

Could you please re-test by running opensips with Q MALLOC only and let us know?

Vasilios Tzanoudakis

**Comment by barnabyritchley** [comment]
Hi @vtzan 
When starting opensips with

```
/usr/sbin/opensips -f /etc/opensips/opensips.cfg -m 1024 -M 96 -a Q_MALLOC
```

the problem is not produced (same as if I change the tcp_workers to anything other than 8).  Using the same config and starting without the allocator the problem is back again.

Let me know if theres any other tests to try.

Barny.

**Comment by barnabyritchley** [comment]
@vtzan do you need anything more from me to help progress this further?

**Comment by razvancrainea** [comment]
Hi, @barnabyritchley !

This definitely looks like a memory corruption. If this does not happen with Q_MALLOC, can you replicate it and then run `opensips-cli -x trap`?

Best regards,
Răzvan

**Comment by vtzan** [comment]
> Hi, @barnabyritchley !
> 
> This definitely looks like a memory corruption. If this does not happen with Q_MALLOC, can you replicate it and then run `opensips-cli -x trap`?
> 
> Best regards,
> Răzvan

Dear @razvancrainea,

I have sent you a private email with some traps regarding this issue.
I can reproduce it anytime in case you need any further information on this.

Best Regards
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Issue is still there, I will update with more traces soon.
