### ISSUE TITLE
[BUG] topology_hiding:topo_callid_post_raw: could not parse resulted sip message: HEP3

### ISSUE THREAD

**Issue by netaskd** [OpenSIPS/opensips#2273]
**OpenSIPS version you are running**
```
3.1.0
git revision: 3319120fb
```

**Describe the bug**
I see that it was described here https://github.com/OpenSIPS/opensips/commit/7ada147dd074b6bd058e5e0e67fac6ad55613f27
I have a lot of this messages in my log, but don't have any idea why it happens. Google point out only on this commit )
In my case it happens when topology_hidding() was called (with create dialog a/b) for initial requests and trace() called after that with capturing transactions and dialogs ("td"). When I just trace messages ("m") it does not show this errors.
Maybe author @lemenkov could provide some hint/idea what it can be?
Ps. Of course I understand that it's homer proto v3, but why it incomes to topology_hiding logic?

**To Reproduce**
```
  # inside initial requests logic
  if (!$DLG_status) {
    if (!create_dialog() || !topology_hiding("C")) {
      xlog("L_ERR","[TH] $rm - $C(rx)can NOT create hide topology!$C(xx)\n");  
      exit;
    }    
    # we can trace dialog only after creation, otherwise the dialog has not be created.
    trace("hid", "mtd", "sip|xlog");
   ...
```

**Relevant System Logs**
```
ERROR:topology_hiding:topo_callid_post_raw: could not parse resulted sip message: HEP3
```

**OS/environment information**
 - Operating System: Centos 7
 - OpenSIPS installation: nightly rpm

**Comment by lemenkov** [comment]
Hello!
I must admit I didn't dig too deep but I suspect it has something with topology hiding module. Anyway this one is harmless although annoying.

**Comment by netaskd** [comment]
@lemenkov thanks for the answer
@bogdan-iancu could the commit https://github.com/OpenSIPS/opensips/commit/d59715ec3614c5c9d5afb40aa17704d86fca6021 bring the issue?

**Comment by lemenkov** [comment]
Should be reopened. The issue is still valid and PR is waiting for review (see #2316 ).

**Comment by bogdan-iancu** [comment]
Thanks @lemenkov , the PR was accepted, issue solved :)

**Comment by netaskd** [comment]
@bogdan-iancu Looks like this https://github.com/OpenSIPS/opensips/pull/2316 still open ;)

**Comment by bogdan-iancu** [comment]
@netaskd , right, may bad, I forgot I asked for some minor changes. But the fix is there and shortly it will be pushed on the repo.
