### ISSUE TITLE
[BUG] Opensips worker stuck at 100% and Opensips stop responding to requests with rtpengine recording

### ISSUE THREAD

**Issue by ivlovric** [OpenSIPS/opensips#2278]
**OpenSIPS version you are running**

```
Tried with 3.0, 3.0.3 and 3.1 as well

version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 10:55:25 Oct  2 2020 with gcc 4.8.5
```

**Describe the bug**

When using rtpengine with rtpengine recording as we need to record such calls (siprec calls that we proxy over Opensips to satisfy Opensips proxy nature and route to simple UAS that just answers the call), after short period of time with relatively low cps (5 - 10), SIP worker whether it is TCP or UDP loads to 100% and gets stuck while Opensips at that time doesn't process any SIP requests at all. Only after service restart all is good again.
We find one correlation which is amount od rtpengine "metadata" content when calling rtpengine. More of content, quicker Opensips worker gets stuck and Opensips stop processing any additional requests. 
For example with additional rtpengine metadata and 10 CPS tcp worker is stuck after cca 100 calls but without additional rtpengine metadata with 10 CPS it is stuck after cca 1000 calls

All calls that get routed are correctly recorded on rtpengine recording till point of Opensips described issue above.
commands to rtpengine are: **offer** with metadata and recording on SIP INVITE, **answer** on SIP 200 ok and **delete** on SIP BYE and are all correctly closed and no hanged or uncleared rtpengine sessions are observed.

Regarding rtpengine, we tried latest 9.0.1.1, older branches 8 and 7 with same behaviour on Opensips but with 9.0.1.1 confirmed working with another sip stack that is using same rtpengine on same machine with same scenario.

EDIT:
During load of 10CPS when all still works, server cpu load doesn't get above cca 25% (4 cores)
Rtpengine and recording is on same server

flow that is correctly initiated and terminated with rtpengine annotations
<img width="728" alt="Screenshot 2020-10-06 at 13 48 56" src="https://user-images.githubusercontent.com/37185376/95304592-2935db00-0885-11eb-94c0-74de416f3987.png">

worker stuck
![image](https://user-images.githubusercontent.com/37185376/95301863-7748df80-0881-11eb-9161-bc72552bdb38.png)

**To Reproduce**

1. Start SIPP scenario with media (5 cps, 10 cps)
2. Opensips as simple proxy with rtpengine recording
2. Observe load with htop, track sngrep and tail of opensips log

Relevant part of configuration script:
[opensips-relevant-part.txt](https://github.com/OpenSIPS/opensips/files/5339034/opensips-relevant-part.txt)

**Expected behavior**

Opensips SIP worker should not get stuck on 100% load and Opensips should continue processing SIP requests

**Relevant System Logs**

There is nothing observable in logs that should indicate ERROR or WARNING that correlates with experienced issue

**OS/environment information**
Operating System: Centos 7 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OpenSIPS installation: compiled from source
rtepegine and components: compiled from source

**Additional context**

**Comment by razvancrainea** [comment]
Could you please run `opensips-cli trap` when OpenSIPS is stuck, and post the output somewhere?

**Comment by ivlovric** [comment]
Sure, Razvan, thanks!

Here is opensips-cli trap
[gdb_opensips_20201013_125304.txt](https://github.com/OpenSIPS/opensips/files/5371468/gdb_opensips_20201013_125304.txt)

And htop as well if it can be relevant.
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/37185376/95864154-4d9e2580-0d65-11eb-8044-70b9d0474fa7.png">

**Comment by razvancrainea** [comment]
Any particular errors in the logs?
Taking a look at the script you provided, I noticed that in the `RTPANSWER` route you're doing an `offer` - this shouldn't cause the behavior, but I just thought I should point it out.

Also, I was wondering if you could do two subsequent traps after it blocks, within a couple of seconds between them, and post them over.

**Comment by ivlovric** [comment]
Thanks!
I changed that ```offer``` in ```RTPANSWER``` route to ```answer``` as it should be as initially said, but without luck.

Please find attached last part of opensips log when it happened and couple of ```trap``` commands at point when it is stuck and at point it is just getting to be stuck.

[at_time_worker_in_process_of_hanging.zip](https://github.com/OpenSIPS/opensips/files/5380137/at_time_worker_in_process_of_hanging.zip)
[after_worker_hang.zip](https://github.com/OpenSIPS/opensips/files/5380139/after_worker_hang.zip)
[opensips-tail-500-on-stuck.txt](https://github.com/OpenSIPS/opensips/files/5380140/opensips-tail-500-on-stuck.txt)

Thanks a lot

**Comment by razvancrainea** [comment]
when the process is stuck, can you attach to it with gdb and run the following commands:

```

**Comment by ivlovric** [comment]
Yes, this is the output. After command ```continue``` nothing happens after that. Tried couple times for same stuck process
[opensips-gdb-stuck.txt](https://github.com/OpenSIPS/opensips/files/5407138/opensips-gdb-stuck.txt)

Thanks a lot!

**Comment by razvancrainea** [comment]
The process is gets stuck in a `write` syscall - this usually happens when the other party (in this case rtpengine) does not read the messages sent by OpenSIPS. Can you also check the status of rtpengine during those stuck periods?

**Comment by ivlovric** [comment]
There is nothing relevant that can be observed in rtpengine log. Here is one example when that happened. Logs are visible from opensips and rtpengine components.
thanks!
[rtpengine_rtpengrec_message_log_opensipsstuck.txt](https://github.com/OpenSIPS/opensips/files/5609162/rtpengine_rtpengrec_message_log_opensipsstuck.txt)

**Comment by ivlovric** [comment]
But since same rtpengine on same machine is working with other sip proxy we decided to go that way from this point on.
