### ISSUE TITLE
Can mid-registrar and nat-traversal model be used in the same opensips server at the same time??

### ISSUE THREAD

**Issue by openspring** [OpenSIPS/opensips#2302]
Do we have some examples？
I did not find any examples of this in google

**Comment by openspring** [comment]
@ibc @nud

**Comment by ibc** [comment]
> @ibc @nud

Please don't mention people.

**Comment by bogdan-iancu** [comment]
Yes, you can use them together - keep in mind that mid-registrar acts more or less as the `registrar` module, so looks for something like that. Sometimes you do not find examples for everything, so it is up to you to put pieces together.
As this tracker is more the development issues, and not usage questions, I will close this ticket and I advice to push such question to the [the user's mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users)
