### ISSUE TITLE
[BUG] package (private) memory leak when params used in t_relay calls.

### ISSUE THREAD

**Issue by Sigmast-Michael** [OpenSIPS/opensips#2304]
**OpenSIPS version you are running**

```
version: opensips 3.0.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 16:18:49 Jun 30 2020 with gcc 4.8.5
```

**Describe the bug**
If the second argument to the t_relay call is parameter from a route call an new call to mk_proxy is made and not released.
Over time the package memory is exhausted.

**To Reproduce**
Example:
1. In a script you would normally call t_relay with a fixed destination create a route to wrap t_relay 

\# Takes 2 arguments the name of the service for logging
\# the destination to relay too
route[relay_to_service] {
if (!t_relay( , "$param(2)")) {
    send_reply(503, "Service Unavailable");
    exit;
  } 
}

1. Run opensips with the -a Q_MALLOC_DBG 
2. Send traffic that will trigger the wrapped call to t_relay.
3. use opensips-cli to log the processes pkg memory mi mem_pkg_dump pid=<pid> log_level=2
4. Notice the number of calls to mk_proxy increase with every call.

5080352 : 78035 x [proxy.c: mk_proxy, line 202]

**Expected behavior**
I'd expect either a complaint that a param can not be used with t_relay.
Or the mk_proxy to be released.

**Comment by bogdan-iancu** [comment]
thank you @Sigmast-Michael for the report, it should be fixed now!

**Comment by Sigmast-Michael** [comment]
Thank you!
