### ISSUE TITLE
[FEATURE] RabbitMQ Support for SSL

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2306]
**Is your feature request related to a problem? Please describe.**
For Opensips to be able to work with managed RabbitMQ instances (offered as SaaS by third parties) support for SSL is mandatory. Cloud providers that are offering RabbitMQ as a service are only offering amps (ssl) endpoints to connect to.
I have tested both AWS & Cloudamqp and they offer only secure endpoints.

**Describe the solution you'd like**
Support for SSL in RabbitMQ & RabbitMQ Consumer modules

**Describe alternatives you've considered**
The only alternative that I am using right now is to create my own RabbitMQ cluster to be able to work without SSL support inside my VPC.

Thank you in advance
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
thanks @rvlad-patrascu I will try it ASAP and let you know.

**Comment by sobomax** [comment]
Hey Vlad, this change broke automatic builds. Please fix.

https://github.com/sippy/opensips/runs/1540765453?check_suite_focus=true#step:4:770


rmq_servers.c:237:14: error: implicit declaration of function
'amqp_ssl_socket_get_context'

It checks for version >= 0.4, while amqp_ssl_socket_get_context() has been
added into 0.9.

https://rabbitmq-c.docsforge.com/master/api/amqp_ssl_socket_get_context/

-Max
