### ISSUE TITLE
[BUG] opensips-cli -x mi reload_routes fail once => fail forever

### ISSUE THREAD

**Issue by perwx3** [OpenSIPS/opensips#2312]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 16:07:25 Jul 22 2020 with gcc 8
```

**Describe the bug**
If opensips.cfg contains errors when doing 'opensips-cli -x mi reload_routes', then reload_routes will always return error until opensips is restarted, even if syntax is corrected. Fail once -> fail forever.

**To Reproduce**
Example:
1. Start OpenSIPS with a healty opensips.cfg
2. Add an syntax error to your opensips.cfg file and save. (E.g. change an 'exit' call to 'brexit')
3. Do opensips-cli -x mi reload_routes
4. You will get an error since the config is faulty: 'ERROR: command 'reload_routes' returned: 500: reload failed'
5. Edit opensips.cfg again and restore to a healty config. Save.
6. Do opensips-cli -x mi reload_routes again. At this point you will get error again, even though the config is correct. reload_routes will fail forever until you do a restart opensips.  

**Expected behavior**
If syntax is correct then a reload_routes should reload config correctly.

**OS/environment information**
64-bit CentOS 8 on VMWare cluster
opensips-3.1.0-1.el8.x86_64 (installed via yum and official opensips repo)

**Comment by vasilevalex** [comment]
The same as #2243 . Fixed with https://github.com/OpenSIPS/opensips/pull/2244
