### ISSUE TITLE
[FEATURE] hot-reload TLS certificates

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#2322]
**Is your feature request related to a problem? Please describe.**
We have a requirement to deploy OpenSIPS with short lived TLS certificates (for example; 1 day). The service which issues the certificates does so automatically, and will update the files on disk. We'd like to be able to reload the certificates from disk with the updated ones without terminating the OpenSIPS server or existing connections.

**Describe the solution you'd like**
Either an automatic hot-reload capability, or a management interface command, for example on `tls_mgm` to reload the certificates from disk.

**Implementation**
  - Component: `tls_mgm` module
  - Type: function (?)
  - Name: `tls_cert_reload` (?) There is an existing `tls_reload` which requires a database.

**Describe alternatives you've considered**
The alternative we've considered and which may be necessary until a better solution is available is using inotify to watch the certificate cert/key files on the filesystem and issue a SIGINT or SIGTERM and start the service again once it has gracefully shutdown. This is not ideal as it leaves us with a period of time without service and the effects of various signals on ongoing calls, or new calls during this period is currently unknown.

**Additional context**
It is becoming increasingly popular, and even necessary for some customers, to use short-lived TLS certificates; regardless of whether this time is 1 hour, 1 week or 1 year, it is beneficial to be able to automate the reloading of the certificates where systems are in place to automatically issue these updated certificates. The same applies for certificate revocation and not just for expiry.

If an exiting, alternative option is available, which avoids server restart, we are open to that too. This request is simply a suggested implementation given no knowledge of a suitable existing or alternative solution.

**Comment by rvlad-patrascu** [comment]
Hi @hamid-elaosta ,

Have you considered storing the certificates in a database and making use of the `tls_reload` MI command? In this case OpenSIPS would not load the certificates from disk but you can use the same idea of monitoring the files and triggering a DB update followed by `tls_reload`, when the certificates are updated.

**Comment by hamid-elaosta** [comment]
@rvlad-patrascu Thank you for the suggestion. I wasn't sure if this was the purpose/capability of the database reload function. I'll try it out immediately and see if there are any other issues with this approach.

**Comment by hamid-elaosta** [comment]
I've implemented a solution which involves watching the filesystem for changes to the certificate files using inotify on Linux. The code which detects it loads the certificates into the database and uses the mi_fifo with a naive implementation to call tls_reload on the OpenSIPS server.

Although it is functional, it isn't the cleanest solution and requires an additional deamon to run and monitor the certificates, it's also dependent on _how_ the certificates change (which events are watched for).

I still believe this is a valid feature for integration directly into OpenSIPS.

**Comment by bogdan-iancu** [comment]
@hamid-elaosta, the TLS certifications handling is outside OpenSIPS's scope - there are many ways you can get your certificates, many ways to update them, many ways to push them to your OpenSIPS platform. This is why OpenSIPs tries to provide a simple and generic way of using the certs, via DB.

**Comment by hamid-elaosta** [comment]
@bogdan-iancu Thank you for the response. Although I agree that the DB provides a generic mechanism, and that there are many ways to load the certificates, the feature I'm suggesting is loading the changes without user-interaction, perhaps as a flag in tls_mgm to detect and reload when the DB or files change?

Once certificates are updated using any mechanism, DB, filesystem, or otherwise, it is useful for OpenSIPS to be able to detect either the content of the database table change or the changed certificates on the filesystem without need to call the MI.

It is the reloading of the certificates into memory that is the issue at hand, and not updating the certificates themselves in the DB or filesystem. Doing this requires custom code to instruct OpenSIPS via MI to reload the certificates, and this is not inline with general practice in cloud environments such as Kubernetes. The popular tools such as cert-manager cannot instruct your workload to reload certificates, it can only place them, I have already discussed this with the developers of cert-manager on Slack.

We, in house have already updated our services and code to detect certificate changes and hot-reload without downtime which works very well under Kubernetes.

I hope that clarifies, and I'm happy to discuss further if you are willing. I think this functionality fits extremely well with the goals of OpenSIPS 3.2 and the cloud and clustering changes coming.

**Comment by bogdan-iancu** [comment]
Such event "pulling" is a bit expensive (especially if you do it via DB) - I still think that the most appropriate way to do it is via an external mechanism that may monitor the master copy of the certificate and, upon change, to upload it into DB and fire a reload.

**Comment by hamid-elaosta** [comment]
@bogdan-iancu Understood. Is it possible to force a reload from within config? We could use an event then to trigger the reload. Using the MI (mi_json, mi_fifo) is a non-trivial amount of code/work to implement; we have already solved the problem but I'm looking for a clean solution, and I think it somehow benefits everyone who wishes to run under Kubernetes.

**Comment by bogdan-iancu** [comment]
This is something we plan to add in 3.2 :)

**Comment by hamid-elaosta** [comment]
@bogdan-iancu Thanks for taking time to discuss and Happy New Year to you and the team!

**Comment by bogdan-iancu** [comment]
thank you too @hamid-elaosta
