### ISSUE TITLE
[BUG] Carrierroute module memory leak

### ISSUE THREAD

**Issue by aldotms70** [OpenSIPS/opensips#2328]
**OpenSIPS version you are running**

```
all version
```

**Describe the bug**

Memory leak in module carrierroute when reloading routes and crash when insert a route with non digit character.

**To Reproduce**

Every reload of routes.
The process doesn't free the route_tree_item structures.
If the route o failure_route define a scan_prefix containing a digit different from 0 to 9, the process crash.

**Expected behavior**

At the end of function destroy_route_tree_item need a line with:
shm_free(route_tree_item);
If route contains an invalid character in scan_prefix, the route should be skipped and logged with error.

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@aldotms70 , I would strongly suggest to use the [Dynamic routing](https://opensips.org/html/docs/modules/3.1.x/drouting.html) module which does the same, maybe even more. The Carroerroute module in not properly maintained :(
