### ISSUE TITLE
[BUG] Fraud Detection total_calls does not seems to reset after interval/mid-night

### ISSUE THREAD

**Issue by ryan-netizen** [OpenSIPS/opensips#2332]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**
I see total_calls counter does not reset after the passage of fraud detection interval but keeps on increasing over the period. 

**To Reproduce**

1. Just enter one record inside mongodb having some time interval
```
db.getCollection("fraud_detection").insert( {
    _id: ObjectId("5fca4e93202f00000c0063b4"),
    ruleid: NumberInt("1"),
    profileid: NumberInt("1"),
    prefix: "1",
    "start_hour": "08:00",
    "end_hour": "08:45",
    daysoftheweek: "Mon-Sun",
    "cpm_warning": NumberInt("0"),
    "cpm_critical": NumberInt("0"),
    "call_duration_warning": NumberInt("0"),
    "call_duration_critical": NumberInt("0"),
    "total_calls_warning": NumberInt("0"),
    "total_calls_critical": NumberInt("0"),
    "concurrent_calls_warning": NumberInt("2"),
    "concurrent_calls_critical": NumberInt("2"),
    "sequential_calls_warning": NumberInt("0"),
    "sequential_calls_critical": NumberInt("0")
} );
```
2. If you made a call between this interval you will see total_calls counter getting increased. Which is correct.
3. But after the passage of interval if you check stats by making rpc call you will see total_count there but not set to zero. 
```
opensips-cli -x mi show_fraud_stats user='2005' prefix='1'
{
    "cpm": 2,
    "total_calls": 2,
    "concurrent_calls": 0,
    "seq_calls": 2
}

```
4. And next day during the same interval if you make a call, total_count will keep on increasing. 
5. This prevents to correctly use the total_count stats. 

**Expected behavior**
1. total_calls should be reset after the passage of interval or at mid-night

Thanks for making this tool so powerful and great. Highly appreciated. 

Ryan

**Comment by liviuchircu** [comment]
Hey, @ryan-netizen!  Thanks for the report, let's discuss it a bit.

First of all, by design, all stats will only reset on a _(user, prefix) match_, per the following C code:

```
    if (se->stats.last_matched_time == 0 || se->stats.last_matched_rule != rule->id                                   
            || then.tm_yday != now.tm_yday || then.tm_year != now.tm_year) {                                          
        se->stats.cpm = 0;                                                                                            
        se->stats.total_calls = 0;                                                                                    
        se->stats.concurrent_calls = 0;                                                                               
        se->stats.seq_calls = 0;                                                                                      
        se->interval_id++;                                                                                            
        itv_reset = 1;                                                                                                
    }
```

There is no timer process or logic which resets them automatically.  Notice how the stats of each "(user, prefix)" pair are reset when either:

* matching for the 1st time
* matching a new rule (different than the last matched one)
* matching on a new day
* matching on a new year

So I think the "total_calls" are reset just like the other ones.  Do you still think it's not behaving as expected?

**Comment by ryan-netizen** [comment]
@liviuchircu thank you so much for taking time and checking this. I was not sure that these stats gets reset upon matching the next day not after out side of configured interval automatically. I can confirm that stats do reset as they should the next day after matching.  

Thanks again for your time.
