### ISSUE TITLE
[BUG] invalid matching mode 0

### ISSUE THREAD

**Issue by 98oi98** [OpenSIPS/opensips#2337]
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 229ec0793
main.c compiled on 17:47:19 Nov 30 2020 with gcc 4.8.5

questions:
when setting  matching_mode parameter with 0 opensips can't start 

opensips.cfg:

loadmodule "usrloc.so"
modparam("usrloc", "matching_mode", 0)
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "working_mode_preset", "single-instance-sql-write-back")

logs:

DBG:core:init_mod: initializing module rest_client
Dec  9 12:29:34 [6] DBG:rest_client:mod_init: Initializing...
Dec  9 12:29:34 [6] INFO:rest_client:mod_init: Module initialized!
Dec  9 12:29:34 [6] DBG:core:init_mod: initializing module usrloc
Dec  9 12:29:34 [6] DBG:usrloc:mod_init: initializing
Dec  9 12:29:34 [6] INFO:usrloc:ul_init_locks: locks array size 512
Dec  9 12:29:34 [6] ERROR:usrloc:ul_init_globals: invalid matching mode 0
Dec  9 12:29:34 [6] ERROR:usrloc:mod_init: failed to init globals
Dec  9 12:29:34 [6] ERROR:core:init_mod: failed to initialize module usrloc
Dec  9 12:29:34 [6] ERROR:core:main: error while initializing modules
Dec  9 12:29:34 [6] INFO:core:cleanup: cleanup
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: tm_shutdown : start
Dec  9 12:29:34 [6] DBG:tm:unlink_timer_lists: emptying DELETE list for set 0
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: emptying hash table
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: releasing timers
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: removing semaphores
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: destroying callback lists
Dec  9 12:29:34 [6] DBG:tm:tm_shutdown: tm_shutdown : done
Dec  9 12:29:34 [6] DBG:core:shm_mem_destroy: destroying the shared memory lock
Dec  9 12:29:34 [6] NOTICE:core:main: Exiting....

**Comment by liviuchircu** [comment]
Thank you for the catch, @98oi98!  I just pushed a fix for this!
