### ISSUE TITLE
[CRASH]The application crashed when the OPENSips (2.2.8) RTPEngine_offer () method included the parameter SDES-off

### ISSUE THREAD

**Issue by JaydenSam** [OpenSIPS/opensips#2347]
route[rtpengine_offer] {

        if (isflagset(SRC_WS) && isbflagset(DST_WS)){
                xlog("$cfg_line 11111111111");
                $var(rtpengine_flags) = "ICE=force-relay DTLS=passive";
        }
        else if (isflagset(SRC_WS) && !isbflagset(DST_WS)){
                xlog("$cfg_line 22222222222");
                $var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove";
        }
        else if (!isflagset(SRC_WS) && isbflagset(DST_WS)){
                xlog("$cfg_line  33333333333");
                $var(rtpengine_flags) = "UDP/TLS/RTP/SAVPF ICE=force SDES-off";
                #$var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove";
                #$var(rtpengine_flags) = "SDES-off";
        }
        else if (!isflagset(SRC_WS) && !isbflagset(DST_WS)){
                xlog("$cfg_line 4444444444");
                $var(rtpengine_flags) = "RTP/AVP replace-session-connection replace-origin ICE=remove";

        }
        rtpengine_offer("$var(rtpengine_flags)");
}

-----------------------------------------------------------------------------------------
Dec 16 17:30:49 localhost ./opensips[31182]: new branch at sip:k4vh46du@10.1.10.70:51660;transport=ws
Dec 16 17:30:49 localhost ./opensips[31182]: DBG:core:parse_headers: flags=ffffffffffffffff
Dec 16 17:30:49 localhost ./opensips[31182]: DBG:core:decode_mime_type: Decoding MIME type for:[application/sdp]
Dec 16 17:30:49 localhost ./opensips[31182]: 495 branch_route_sdp
Dec 16 17:30:49 localhost ./opensips[31182]: 557  33333333333
Dec 16 17:30:49 localhost ./opensips[31182]: DBG:core:parse_headers: flags=40
Dec 16 17:30:49 localhost ./opensips[31182]: DBG:core:parse_headers: flags=ffffffffffffffff
Dec 16 17:30:49 localhost ./opensips[31182]: DBG:rtpengine:check_content_type: type <application/sdp> found valid
Dec 16 17:30:49 localhost ./opensips[31200]: DBG:core:io_wait_loop_epoll: [TCP_main] EPOLLHUP on IN ->connection closed by the remote peer!
Dec 16 17:30:49 localhost ./opensips[31200]: CRITICAL:core:receive_fd: EOF on 20
Dec 16 17:30:49 localhost ./opensips[31200]: DBG:core:handle_worker: dead child 11, pid 31182 (shutting down?)
Dec 16 17:30:49 localhost ./opensips[31200]: DBG:core:io_watch_del: [TCP_main] io_watch_del op on index 11 20 (0x68bcc0, 20, 11, 0x0,0x1) fd_no=37 called
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:handle_sigs: status = 134
Dec 16 17:30:49 localhost ./opensips[31170]: INFO:core:handle_sigs: child process 31182 exited by a signal 6
Dec 16 17:30:49 localhost ./opensips[31170]: INFO:core:handle_sigs: core was generated
Dec 16 17:30:49 localhost ./opensips[31170]: INFO:core:handle_sigs: terminating due to SIGCHLD
Dec 16 17:30:49 localhost ./opensips[31199]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31198]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31197]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31196]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31195]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31194]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31193]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31184]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31181]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31186]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31189]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31190]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31188]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31191]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31187]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31183]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31185]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31192]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31176]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31177]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31180]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31179]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31178]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31175]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31174]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31173]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31172]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31200]: INFO:core:sig_usr: signal 15 received
Dec 16 17:30:49 localhost ./opensips[31170]: INFO:core:cleanup: cleanup
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:pool_remove: connection still kept in the pool
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:pool_remove: connection still kept in the pool
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:uac_auth:mod_destroy: done
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:uac_registrant:mod_destroy: done
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:pool_remove: connection still kept in the pool
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: tm_shutdown : start
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:unlink_timer_lists: emptying DELETE list for set 0
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: emptying hash table
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: releasing timers
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: removing semaphores
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: destroying callback lists
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tm:tm_shutdown: tm_shutdown : done
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:tls_mgm:mod_destroy: entered
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:proto_wss:tls_update_fd: New fd is 34
Dec 16 17:30:49 localhost ./opensips[31170]: ERROR:proto_wss:tls_write: TLS connection to 10.1.10.70:51660 write failed
Dec 16 17:30:49 localhost ./opensips[31170]: ERROR:proto_wss:tls_write: TLS write error:
Dec 16 17:30:49 localhost ./opensips[31170]: ERROR:proto_wss:tls_blocking_write: TLS failed to send data
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:proto_wss:tls_conn_clean: entered
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:proto_wss:tls_update_fd: New fd is 46
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:shm_mem_destroy: destroying the shared memory lock
Dec 16 17:30:49 localhost ./opensips[31170]: DBG:core:handle_sigs: terminating due to SIGCHLD

**Comment by JaydenSam** [comment]
no parameter SDS-off  is OK.

**Comment by razvancrainea** [comment]
Unfortunate OpenSIPS 2.2 is no longer [supported](https://www.opensips.org/About/AvailableVersions).
Please upgrade your OpenSIPS to one of the supported versions, most likely this issue was fixed. If not, please provide info regarding the new core dump.
