### ISSUE TITLE
Opensips token basis authentication 

### ISSUE THREAD

**Issue by binesh46** [OpenSIPS/opensips#2353]
**Is your feature request related to a problem? Please describe.**
Hello all! I am new to opensips. I following two requirements which i am not able to implement. Your guidance will be helpful.
Requirement: 
 1. I am trying to authenticate hardphone users on basis of username and password. 
 2. I am trying to authenticate a mobile app (softphone) users on the basis of a username and token basis. Authentication will be done on a remote server.
 Both these requirements are on the same opensips server. 
If any further details are required, please mention accordingly.

Thank you !

**Describe the solution you'd like**
I want to fulfil both requirement mentioned above. 

**Implementation**
 

**Describe alternatives you've considered**
using auth_jwt token implementation

**Comment by bogdan-iancu** [comment]
For questions or advises on how to use opensips, please use the public mailing list -> http://lists.opensips.org/cgi-bin/mailman/listinfo/users
