### ISSUE TITLE
[help] compile error

### ISSUE THREAD

**Issue by rotjian** [OpenSIPS/opensips#2354]
I use aws as opensips server.( gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) There is a problem when I compile source file now. It didn't happen before. When it compile to module TM t_reply.c file. The process will stop. When I use the command gcc -c t_reply.c, I got the following error:

In file included from ../../evi/../locking.h:65,
                 from ../../evi/event_interface.h:31,
                 from ../../evi/evi_modules.h:30,
                 from ../../ut.h:40,
                 from t_reply.c:71:
../../evi/../lock_ops.h:298:2: error: #error "no locking method selected"
  298 | #error "no locking method selected"
      |  ^~~~~
../../evi/../lock_ops.h:411:2: error: #error "no lock set method selected"
  411 | #error "no lock set method selected"
      |  ^~~~~
In file included from ../../evi/../mem/shm_mem.h:52,
                 from ../../evi/../lock_alloc.h:55,
                 from ../../evi/../locking.h:66,
                 from ../../evi/event_interface.h:31,
                 from ../../evi/evi_modules.h:30,
                 from ../../ut.h:40,
                 from t_reply.c:71:
../../evi/../mem/common.h:33:2: error: #error "no memory allocator selected"
   33 | #error "no memory allocator selected"
      |  ^~~~~
In file included from ../../evi/../lock_alloc.h:55,
                 from ../../evi/../locking.h:66,
                 from ../../evi/event_interface.h:31,
                 from ../../evi/evi_modules.h:30,
                 from ../../ut.h:40,
                 from t_reply.c:71:
../../evi/../mem/shm_mem.h:189: warning: "SHM_INFO" redefined
  189 | #define SHM_INFO               gen_shm_info
......     
any help will be appreciated, many thanks!

**Comment by bogdan-iancu** [comment]
@rotjian, that is not the intended way to compile OpenSIPS's sources. You MUST use the "make" support in order to properly compile. If you want to compile only one module, do `make modules modules=modules/tm`
Again, DO NOT COMPILE manually some files, as it will not work.
