### ISSUE TITLE
register problem

### ISSUE THREAD

**Issue by Zzij** [OpenSIPS/opensips#2359]
- Operating System:  centos 7.5
 - OpenSIPS installation:  make source
 - OpenSIPS version：1.11.9

hi 
   i met some problem with register. when i use the same ip and port  to register twice , the database has two records.  when i register one more ,  i can't register.  This is to simulate re-register.  why not remove the first (oldest) one?

**Comment by bogdan-iancu** [comment]
@Zzij , 1.11 is outdated for years. Better use 2.4 or 3.1 (recommended).
Also note that this tracker is more for reporting code-related issues (crashes, bugs, misbehavior).  For usage questions, better use public mailing list -> http://lists.opensips.org/cgi-bin/mailman/listinfo/users

**Comment by Zzij** [comment]
ok  i will take a look. thanks
