### ISSUE TITLE
[CRASH] Opensips crash on January 4th 

### ISSUE THREAD

**Issue by adamoverbeeke** [OpenSIPS/opensips#2361]
**OpenSIPS version you are running**
```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a88a57479
main.c compiled on 02:25:11 Dec 30 2020 with gcc 7
```

**Crash Core Dump**

https://paste.ubuntu.com/p/gh2wTJdZVG/

**Describe the traffic that generated the bug**

Normal call traffic, mix of UDP, TCP and TLS. Crash happened mid day. 

**To Reproduce**

No. This crash happened on its own. No reproduction. 

**Relevant System Logs**

**OS/environment information**
- Amazon Linux 2

**Additional context**

```
ERROR:proto_tls:tls_print_errstack: TLS errstack: error:140E0197:lib(20):func(224):reason(407)
ERROR:proto_tls:tls_conn_shutdown: something wrong in SSL: 1, 9, Bad file descriptor
```

**Comment by bcnewlin** [comment]
This may be related to #2321.

**Comment by bogdan-iancu** [comment]
@adamoverbeeke , thanks for the report. I noticed you use a bit of an old version, so first of all please update to the latest 2.4 (the 2.4.9)  and check again.

**Comment by adamoverbeeke** [comment]
Closing ticket. We upgraded to 2.4.9 and added the debugging.
This may be related to #2321.
