### ISSUE TITLE
auth_db -- Authentication failure due to password column sticky to 'password'

### ISSUE THREAD

**Issue by JeffreyVIP** [OpenSIPS/opensips#2365]
Hi Sir
conditions:
- password colum of subscriber table in db is blank.
- auth_db parameters are set to use ha1 hashed password in script, but from the log, opensips always select password column from subscriber table, seems the auth_db paramter has no effect.
- latest opensips 3.1 branch version. commit ID = 3f58031efb18a995ac1b660abf295a47338b1b63
when put real plain text password into the 'password' column, the authentication succeed.

```
modparam("auth_db", "calculate_ha1", 0)
modparam("auth_db", "password_column", "ha1")
```

```

Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_submit_query: 0x7f0f96806c58 PQsendQuery(select password from subscriber where username='1001' AND domain='shanghai.iptcloud.com')
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:core:db_new_result: allocate 48 bytes for result set at 0x7f0f968088f8
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_store_result: 0x7f0f96806c58 PQresultStatus(PGRES_TUPLES_OK) PQgetResult(0x55d7c42a8110)
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_get_columns: 1 columns returned from the query
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:core:db_allocate_columns: allocate 28 bytes for result columns at 0x7f0f968088a8
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_get_columns: RES_NAMES(0x7f0f968088b0)[0]=[password]
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_get_columns: use DB_STRING result type
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_convert_rows: allocate for 1 columns 8 bytes in row buffer at 0x7f0f96808868
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:core:db_allocate_rows: allocate 48 bytes for result rows and values at 0x7f0f96808720
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f0f96806c58,0,0)=[], zero len
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_convert_rows: allocated 0 bytes for row_buf[0] at 0x7f0f96806df8
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_convert_rows: [0][0] Column[password]=[]
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_str2val: converting STRING []
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:db_postgres_convert_rows: freeing row buffer at 0x7f0f96808868
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:db_postgres:free_query: PQclear(0x55d7c42a8110) result set
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:auth_db:get_ha1: HA1 string calculated: d8f06b1eedc0a16b5934af4df9511f50
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:auth:check_response: our result = '99901dbddcc8d5b281bcbfd5997ec960'
Jan 10 18:45:34 opensipsdev opensips[30015]: Jan 10 18:45:34 [30050] DBG:auth:check_response: authorization failed
```

**Comment by bogdan-iancu** [comment]
@JeffreyVIP , the log ```DBG:auth_db:get_ha1: HA1 string calculated: d8f06b1eedc0a16b5934af4df9511f50``` pops only if the `calculate_ha1` is enabled.
So, your `auth_db` acts as if `calculate_ha1` is ON / 1 - please double check your config, maybe the `calculate_ha1` modparam is redefined later

**Comment by JeffreyVIP** [comment]
@bogdan-iancu 
Double checked many times, that's the oddity.

**Comment by bogdan-iancu** [comment]
@JeffreyVIP , are you sure your opensips is running the right cfg file? Besides the logs show that the HA1 is actually calculated (so the `calculate_ha1` has no impact), the logs also show that the `password` column is loaded, not the `ha` as per setting.
Instead of considering 2 bugs in a quite old and stable code, I rather suspect you are using the wrong cfg or you have some wrong/duplicate settings.

**Comment by JeffreyVIP** [comment]
@bogdan-iancu 
Yes, you are right !!!

Configuration file is correct, it is due to hangup issue with daemon service restart(maybe due to frequent service restart when making test).

After killall opensips and start opensips again, it is working as expected now.

Thanks for the response.
Please close the issue.

**Comment by JeffreyVIP** [comment]
@bogdan-iancu 
Yes, you are right !!!

Configuration file is correct, it is due to hangup issue with daemon service restart(maybe due to frequent service restart when making test).

After killall opensips and start opensips again, it is working as expected now.

Thanks for the response.
Please close the issue.
