### ISSUE TITLE
[BUG]tls_mgm:load_certificate: unable to load certificate file

### ISSUE THREAD

**Issue by JeffreyVIP** [OpenSIPS/opensips#2366]
Hi Sir
Tried to build latest 3.1 branch on Debian 10.7.0, but stop at certificate loading issue.
Followed exactly the same build method on Debian 9.13, on which is successful.
Seems it is about the compatiblity with OpenSSL version on Debian 10.7.0
In the begining, the error message lead me to think it is file permission issue, but actually it is not.

BTW, what's the recommended debian version for OpenSIPs version 3.1?
Thanks.

Debian 10.7.0	OpenSSL 1.1.1d  10 Sep 2019
Debian 9.13.0	OpenSSL 1.1.0l  10 Sep 2019

```
Jan  9 12:03:57 opensipsdev opensips[29173]: Jan  9 12:03:57 [29190] ERROR:tls_mgm:load_certificate: unable to load certificate file '/etc/opensips/tls/user/user-cert.pem'
Jan  9 12:03:57 opensipsdev opensips[29173]: Jan  9 12:03:57 [29190] ERROR:tls_mgm:init_tls_domains: Failed to init TLS domain 'default'
Jan  9 12:03:57 opensipsdev opensips[29173]: Jan  9 12:03:57 [29190] ERROR:core:init_mod: failed to initialize module tls_mgm
Jan  9 12:03:57 opensipsdev opensips[29173]: Jan  9 12:03:57 [29190] ERROR:core:main: error while initializing modules

```

**Comment by razvancrainea** [comment]
@JeffreyVIP are there any errors above the `unable to load certificate file`?
Both Debian versions are recommended for using with OpenSIPS 3.1. I've been using OpenSIPS with OpenSSL: 1.1.1d  for a while without any problems, on both ArchLinux and Debian 10.

**Comment by JeffreyVIP** [comment]
@razvancrainea 
Good day!
Thanks for the response.
Similar log as below, full logs relates to tls_mgm module.

```
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] DBG:core:init_mod: initializing module tls_mgm
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] INFO:tls_mgm:mod_init: initializing TLS management
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] INFO:tls_mgm:mod_init: disabling compression due ZLIB problems
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] INFO:tls_mgm:init_tls_dom: Processing TLS domain 'default'
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] DBG:tls_mgm:init_tls_dom: no DH params file for tls domain 'default' defined, using default '(null)'
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] NOTICE:tls_mgm:init_tls_dom: No EC curve defined
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] DBG:tls_mgm:init_tls_dom: cipher list null ... setting default
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] INFO:tls_mgm:get_ssl_ctx_verify_mode: client verification activated. Client certificates are NOT mandatory.
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] NOTICE:tls_mgm:init_tls_dom: no CA dir for tls 'default' defined, using default '/etc/pki/CA/'
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] NOTICE:tls_mgm:init_tls_dom: no crl for tls, using none
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] DBG:core:count_module_procs: modules require 2 extra processes
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] ERROR:tls_mgm:load_certificate: unable to load certificate file '/tmp/tls/user/user-cert.pem'
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] ERROR:tls_mgm:init_tls_domains: Failed to init TLS domain 'default'
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] ERROR:core:init_mod: failed to initialize module tls_mgm
Jan 11 15:10:17 opensipsdev opensips[464]: Jan 11 15:10:17 [502] ERROR:core:main: error while initializing modules
```

**Comment by JeffreyVIP** [comment]
@razvancrainea
After made below changes to the source code for troubleshooting, below error printed:

**error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak**



```
 static int load_certificate(SSL_CTX * ctx, char *filename)
 {
        if (!SSL_CTX_use_certificate_chain_file(ctx, filename)) {
+               unsigned long lerr = ERR_peek_last_error();
+                char lstr[150];
+               ERR_error_string(lerr,lstr);
+               LM_ERR("error== %s", lstr);
+               ERR_clear_error();
+
+
                LM_ERR("unable to load certificate file '%s'\n",
```

**Comment by JeffreyVIP** [comment]
It seems it is due to the default cert used md5 hash algorithm, instead of SHA1.
OpenSSL 1.1.0 has introduced a new feature called security level.


`The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export cipher suites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any cipher suite using MD5 for the MAC is also prohibited.`

**Comment by JeffreyVIP** [comment]
OK, the root cause is found.

It is time to update default certs digest algorithm from SHA1 to SHA256 now.




Temporary workaround is to re-generate the certs from SHA1 Digest Algorithm to SHA256.
Tested and confirms it works now.


```
(opensips-cli-test): tls userCERT
Output directory (default: '/etc/opensips/tls/user/'): 
Output cert file (default: 'user-cert.pem'): 
Output key file (default: 'user-privkey.pem'): 
Output CA list file (default: 'user-calist.pem'): 
User certificate, key or CA list file already exists, overwrite? [y/n] (default: 'y'): 
CA cert file (default: '/etc/opensips/tls/rootCA/cacert.pem'): 
CA key file (default: '/etc/opensips/tls/rootCA/private/cakey.pem'): 
Website address (CN) (default: 'www.opensips.org'): 
Country (C) (default: 'RO'): 
State (ST) (default: 'Bucharest'): 
Locality (L) (default: 'Bucharest'): 
Organization (O) (default: 'OpenSIPS'): 
Organisational Unit (OU) (default: 'Project'): 
Certificate validity (seconds) (default: '315360000'): 
RSA key size (bits) (default: '4096'): 
Digest Algorithm (default: 'SHA1'): SHA256
```

**Comment by liviuchircu** [comment]
Thanks for the accurate report, @JeffreyVIP!  This is now fixed in https://github.com/OpenSIPS/opensips-cli/commit/572d2db15.

**Comment by ovidiusas** [comment]
> @razvancrainea
> After made below changes to the source code for troubleshooting, below error printed:
> 
> **error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak**
> 
> ```
>  static int load_certificate(SSL_CTX * ctx, char *filename)
>  {
>         if (!SSL_CTX_use_certificate_chain_file(ctx, filename)) {
> +               unsigned long lerr = ERR_peek_last_error();
> +                char lstr[150];
> +               ERR_error_string(lerr,lstr);
> +               LM_ERR("error== %s", lstr);
> +               ERR_clear_error();
> +
> +
>                 LM_ERR("unable to load certificate file '%s'\n",
> ```

Hey @liviuchircu  and @razvancrainea. It would be good to integrate the above extra error log for easier future troubleshooting. I see that 3.2 already has this functionality built in, but it would be nice to have it in 3.1 as well as it is still a supported version.

**Comment by liviuchircu** [comment]
Good catch, @ovidiusas, I actually tested with 3.2 and it looked good, so I assumed ...
