### ISSUE TITLE
[BUG] TLS connections reuse do not find existing connection when cert_check_on_conn_reusage is set

### ISSUE THREAD

**Issue by adrien-martin** [OpenSIPS/opensips#2369]
**OpenSIPS version you are running**

```
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3982bec9c
main.c compiled on  with gcc 6.3.0
```
NB: commit e41465513c01a61b3ed33ad4eb71f91585a391a4 is backported onto 2.4.9 (upstream Debian packaging).
No other meaningful commit is present.

**Describe the bug**

We are testing e41465513c01a61b3ed33ad4eb71f91585a391a4 with 2.4.9 to prevent TLS connection reuse when multiple client certificates are used with one TLS destination.

It seems to create more connections than needed.

And when receiving a call from this TLS destination, if we route a BYE from Opensips towards this TLS destination, no connection is found.
Then a new connection is created.
After that it try to re-find the dialog but it was set to state DLG_STATE_DELETED before searching for the connection, so no dialog is found.

**To Reproduce**

```modparam("proto_tls", "cert_check_on_conn_reusage", 1)```

A TLS gateway used with 2 client domains/certificates.
A call from the TLS gateway toward an UDP gateway.
A BYE from UDP gateway toward TLS gateway.

A configuration using ```dialog``` to handle calls (we use ```topology_hiding```).

NB: some connections are created by drouting pinger (not sure if relevant).

**Expected behavior**

One TCP/TLS connection per client domain.
Reuse of existing connection on BYE.

**Relevant System Logs**

Debug logs without cert_check_on_conn_reusage:
[ok.log](https://github.com/OpenSIPS/opensips/files/5815676/ok.log)

Debug logs with cert_check_on_conn_reusage:
[ko.log](https://github.com/OpenSIPS/opensips/files/5815674/ko.log)

**OS/environment information**

Debian Stretch.

**Additional context**

In e41465513c01a61b3ed33ad4eb71f91585a391a4 the diff on net/proto_tcp/proto_tcp.c is weird :
```&c``` and ```NULL``` seem to be inverted in the last call to tcp_conn_get.
NB: we also tested after switching these.

**Comment by rvlad-patrascu** [comment]
Hi @adrien-martin ,

You will also need to backport commit 5821702. But, as commit e414655 was only intended for versions 3.0+ in the first place, I cannot guarantee that it will work and there isn't anything else I'm missing.

**Comment by adrien-martin** [comment]
Hi and thanks @rvlad-patrascu,

Sorry i only found #1651.
Gonna test this.
Was "the rework that changed the storage of the context to be per-process" introduced in 3.0+ or before?

**Comment by c-leroy** [comment]
I think it is not relevant, the interesting part is about passing dom instead of dom->ctx I guess.
Change on tls_mgm should be discarded for this context (2.4.x).

**Comment by rvlad-patrascu** [comment]
It was backported to 2.4 as well in commit c283e2a, so 5821702 is definitely necessary for your purpose.

**Comment by c-leroy** [comment]
I see no call to SSL_set_ex_data in 2.4.x...

**Comment by rvlad-patrascu** [comment]
@c-leroy

You are right,  the `SSL_set_ex_data` calls were introduced for another functionality some time later than 2.4 and the fix in 5821702 conveniently used that, since in 3.0 and beyond the SSL extra data was available. But I think the issue that 5821702 tires to fix is still there, in 2.4, and has to be fixed in a different way.

**Comment by rvlad-patrascu** [comment]
Of course, we are talking in the context of trying to properly backport e414655 to 2.4

**Comment by adrien-martin** [comment]
So I tried with a backport of 582170270c3e0e41d539108b640552ae3cb23cfd, without the part using ```SSL_set_ex_data``` in modules/tls_mgm/tls_conn_ops.h.
New connections are still created.

Beyond that I found an error in the configuration file we have, ```client_domain_avp``` was not set for the in-dialog requests.
Fixing that helps routing the BYE, but this does not change the behavior about connections.

**Comment by rvlad-patrascu** [comment]
@adrien-martin 

I think it's best if I try to do myself a proper backport of 5821702. Maybe you can then test that patch and if it all goes well, I can push the complete fix (including e414655) on public 2.4.

**Comment by rvlad-patrascu** [comment]
Hi @adrien-martin ,

Can you please try the following patch ?
[0001-tls-fix-certificate-matching-when-reusing-connection.patch.txt](https://github.com/OpenSIPS/opensips/files/5826687/0001-tls-fix-certificate-matching-when-reusing-connection.patch.txt)

**Comment by adrien-martin** [comment]
Hi @rvlad-patrascu,

This patch works fine with 2.4.
According to the debug logs and ```netstat```, only one connection is present.

Thank you very much, and sorry to have opened this while it was already fixed in 3.0+.

**Comment by rvlad-patrascu** [comment]
No problem @adrien-martin , I think it's worth having the fix on 2.4 too. Thanks for confirming the patch! I will push the backports to 2.4 soon.

**Comment by c-leroy** [comment]
@rvlad-patrascu Aside for that, did you had a look to "Additional context" comment of this issue, regarding e41465513c01a61b3ed33ad4eb71f91585a391a4?

**Comment by rvlad-patrascu** [comment]
Thanks for reminding about that @c-leroy ! It was indeed a possible crash.

**Comment by adrien-martin** [comment]
Hi @rvlad-patrascu,

I'm not sure this is the right place to ask that, but it is related:

Is there a way to find a dialog for a CANCEL?
The purpose would be to retrieve the TLS client domain when routing a CANCEL to the TLS destination.
Without the TLS client domain a new TLS connection is created too, some destinations do not like that.

Due to the hop-by-hop nature, i'm not sure ```topology_hiding_match``` and ```match_dialog``` are intended to be used with CANCEL.

**Comment by adrien-martin** [comment]
Whoops, after reading the code i understood that dialog is searched from a transaction variable.
```match_dialog``` can be used after t_check_trans for CANCEL.

**Comment by bogdan-iancu** [comment]
@adrien-martin , at INVITE time, how do you select the TLS client domain? Do you force the selection with an AVP? or ? I'm asking as you could do the same at the CANCEL time

**Comment by adrien-martin** [comment]
We use an AVP matching tls_mgm's ```client_domain_avp``` and set a similar dialog variable to restore the same AVP for in-dialog requests.
That's why i tried to do the same with CANCEL, but it works now.
The client domain itself is computed from a value in an header of initial INVITE and an SQL table.

```cert_check_on_conn_reusage``` is quite powerful but it need a consistent usage of dialog for all request that could generate a connection.

**Comment by bogdan-iancu** [comment]
@adrien-martin , just to be sure, you say you got it working for CANCEL too, right?

**Comment by adrien-martin** [comment]
Yes, i used ```match_dialog("DID_NONE")``` after ```t_check_trans``` and the variables handling to restore ```client_domain_avp```.
Was something new to me, our topology_hiding/dialog config is somewhat recent, the CANCEL was not handled with it.

**Comment by bogdan-iancu** [comment]
Indeed, that will do it. It is not the nicest approach, but there is no other way to link the CANCEL to the INVITE, in terms of custom data.
