### ISSUE TITLE
[BUG] REGISTER problem when using save() method with "f" flag

### ISSUE THREAD

**Issue by Shidersz** [OpenSIPS/opensips#2372]
### OpenSIPS version you are running

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 867fb320a
main.c compiled on 10:49:32 Nov  6 2020 with gcc 8
```

### Describe the bug

When handling a **REGISTER** request with the `save()` method and the `fc1` flags:

```tcl
# Save contact internally, the argument 'location' is the name of the
# database table that stores the contacts. The 'f' (force registration) flag
# is used to force the registration of NEW contacts even if the maximum
# number of contacts is reached. In such a case, older contacts will be
# removed to make space to the new ones, without exceeding the maximum
# allowed number.

if (! save("location", "fc1")) {
    # Send back an error reply describing the nature of the last internal
    # error.
    sl_reply_error();
    exit;
}
```

I get more than **1** contact per **AOR** in the `location` table of the database, for example, when registering two softphones with the same username and domain. For what I have understood, it should store only one contact, the last one that have been sent with a **REGISTER** request and delete any other existing contact on the database for that **AOR**, as per explained on the [save() documentation and the f flag](https://opensips.org/docs/modules/3.1.x/registrar.html#func_save). Even more, if I remove the **f** flag to get `save("location", "c1")` the latest **REGISTER** won't succeed, since `c1` flag restricts to only one contact per `AOR` (note this one is an expected behavior). However, the `f` flag is not working as documented, it enables new registrations for an existing **AOR** but do not deletes the previous ones.

### To Reproduce

1. Start OpenSIPS
2. Register a first Softphone with a sip uri like: username@my.domain.com
3. Register a second Softphone with the same sip uri: username@my.domain.com
4. Review the `location` table of the database.

### Expected behavior

The call to `save("location", "fc1")` should accept a new `REGISTER` having a new **contact** for an existing **AOR** and delete previously existing contacts for that **AOR**, leaving only one on the `location` table of the database.

### Relevant System Logs

At next, you can see an example of the `location` table after receiving two `REGISTER` from different softphones and the same `AOR`:

```sh
MariaDB [opensips]> select contact_id, username, domain, contact, expires, callid, user_agent from location;
+------------+----------+-----------------+-----------------------------------------------------------------------+------------+--------------------------+-----------------------------------+
| contact_id | username | domain          | contact                                                               | expires    | callid                   | user_agent                        |
+------------+----------+-----------------+-----------------------------------------------------------------------+------------+--------------------------+-----------------------------------+
|        162 | 1000     | my.domain.com   | sip:1000@181.99.71.249:38463;transport=UDP;rinstance=c0170f0c5f811628 | 1610761869 | w5dxiuaeR4lVDzlTVaFxbw.. | Z 5.4.9 rv2.10.11.7               |
|        163 | 1000     | my.domain.com   | sip:1000@181.99.71.249:5060;transport=udp                             | 1610761949 | EK2n94GVCx               | Linphone/3.12.0 (belle-sip/1.6.3) |
+------------+----------+-----------------+-----------------------------------------------------------------------+------------+--------------------------+-----------------------------------+
```

My expectations were to only have the record with `contact id=163`, since it was part of the last **REGISTER** request received.

### OS/environment information
 - Operating System: CentOS Linux release 8.2.2004 (Core) 
 - OpenSIPS installation: git clone https://github.com/OpenSIPS/opensips.git -b 3.1 opensips_3_1

### Additional context

The **REGISTRAR MODULE** configuration is:

```tcl
loadmodule "registrar.so"
modparam("registrar", "max_contacts", 1)
modparam("registrar", "received_avp", "$avp(received_nh)")
modparam("registrar", "tcp_persistent_flag", "TCP_FLAG")
```

The **USRLOC MODULE** configuration is:

```tcl
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "working_mode_preset", "sql-only")
modparam("usrloc", "db_url", "mysql://some-database-url")
```

I'm also using the **NATHELPER** module and methods `fix_nated_contact()` and  `fix_nated_register()` when a device is detected behind a NAT, just in case.

If you need further information, just ask. Also, I'm interested in any workaround that can be used from the routing script in order to get it work at expected.

Thanks in advance!

**Comment by Shidersz** [comment]
Hi, for the moment I have ended with the next workaround on the routing script to handle the desired logic:

```tcl
# Check if the device is already registered (the AOR already exists). The
# $tu (TO uri) is used as the default AOR of the device.

if (is_registered("location")) {
    # (1) HANDLE UNREGISTERs
    # Now, check if the device wants to unregister (a register with
    # expires = 0). In this case, we remove the AOR of the device.

    if ($ct.fields(expires) == "0" || $hdr(Expires) == "0") {
        remove("location", $tu);
        send_reply(200, "Unregister OK");
        exit;
    }

    # (2) HANDLE NEW CONTACT
    # Check if the device wants to register a new contact. The AOR already
    # exists, but the contact for that AOR is a new one. In this case, we
    # just remove the AOR with the old contact and leave the save() method
    # in charge to store the new contact.

    if (! is_contact_registered("location")) {
        remove("location", $tu);
    }
}

# Save contact internally, the argument 'location' is the name of the
# database table that stores the contacts. The 'c1' flag will restrict to
# 1 the number of contacts per AOR.

if (! save("location", "c1")) {
    # Send an error reply describing the nature of the last internal error.
    sl_reply_error();
    exit;
}
```

However, I'm still looking for an elegant solution, since from the documentation of the `save()` method I understood that the `fc1` flag should handle the situation **(2)**. Also, the `save()` method shouldn't be handling the situation **(1) UNREGISTER** too?

Maybe, I'm missing something on one of the modules configuration...
So, any help is welcome.

**Comment by bogdan-iancu** [comment]
Hi @Shidersz , what if you change the working mode in usrloc to something else, like `modparam("usrloc", "working_mode_preset", "single-instance-sql-write-through")`, do you still have the problem ?

**Comment by Shidersz** [comment]
Hi @bogdan-iancu , in a quick test using the modes `single-instance-sql-write-through` or `single-instance-sql-write-back` all appears to work nicely. One question: the timer that flush the data from memory to database when using `single-instance-sql-write-back` is configured with the parameter [timer_interval](https://opensips.org/docs/modules/3.1.x/usrloc.html#param_timer_interval)?

**Comment by rsanting** [comment]
Hi @bogdan-iancu we are in the process of testing our code on opensips 3.1 and we are running into this same issue.

We want to use sql_only mode because we have multiple opensips instances with the same database. In opensips 2.4 everything works fine with sql_only but in 3.1 old contacts are not being deleted in sql_only mode with max_contacts=1. Is there an update on this issue or additional logging that we could provide? It's a blocker for our upgrade.

**Comment by hafkensite** [comment]
Some observations of the issue @rsanting and me are experiencing. The debug logs when a second registration is processed:
```
DBG:usrloc:get_ucontact: using ct matching mode 1
DBG:usrloc:get_ucontact: failed to match any existing contacts
DBG:registrar:update_contacts: overflow on inserting new contact -> removing <sip:126680001@172.20.0.10:5076;transport=UDP>
DBG:usrloc:delete_ucontact: deleting contact 'sip:126680001@172.20.0.10:5076;transport=UDP'
```
So the [delete_ucontact](https://github.com/OpenSIPS/opensips/blob/3.1.1/modules/usrloc/urecord.c#L904) method is called. But no SQL query is executed.
As far as I can tell `st_delete_ucontact` returns zero.

The `sql_wmode` seems to be set to `SQL_NO_WRITE` if `db_mode` is 3 or [`working_mode_preset` is `sql-only`](https://github.com/OpenSIPS/opensips/blob/3.1.1/modules/usrloc/ul_mod.c#L590).

**Comment by liviuchircu** [comment]
Hi, all!

As @wdoekes accurately pointed out, this bug is specific to the `"sql-only"` mode and is present on **all** OpenSIPS 3.1+ versions.  It was introduced by me in 3a1f9c1e2, while attempting to fix a different issue.

Thanks to @wdoekes, this should now be fixed!  Be sure to pull latest sources and give it a try -- the deletes should go though now.

Cheers!
