### ISSUE TITLE
[BUG] RTPENGINE marked offline on call error

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2376]
Hello Everyone,
Rtpengine produce error unknown call-id when opensips is making rtpengine node as offline.
Originator protocol WSS

Version

```
[root@vprx01 opensips]# opensips -V
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 58804282f
main.c compiled on 00:00:00 Dec 31 2020 with gcc 10

```

Protocol Error In Rtpengine is valid opensips should not quit.

```
Jan 20 00:07:34 vprx01 rtpengine[279596]: WARNING: [s5i1v16abjk19knjua89]: Protocol error in packet from 127.0.0.1:16010: Unknown call-id [d13:media-address13:1.1.1.1:file37:/etc/opensips/scripts/Eslop018000.wav18:transport-protocol17:UDP/TLS/RTP/SAVPF7:call-id20:s5i1v16abjk19knjua8913:received-froml3:IP412:72.139.93.26e8:from-tag10:qr2h69589n7:command10:play media]

```

Opensips side error

```

[root@vprx00 ~]# tail -f /var/log/opensips/opensips.log | grep rtp
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:send_rtpe_command: timeout waiting reply from a RTP proxy
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:send_rtpe_command: proxy <udp:127.0.0.1:2223> does not respond, disable it
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:52 vprx00 /usr/sbin/opensips[2696762]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696755]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696755]: ERROR:rtpengine:rtpe_function_call: no available proxies
```
Any help thank you.

**Comment by gmaruzz** [comment]
have you already done an rtpengine_offer and/or rtpengine_answer ?

**Comment by volga629-1** [comment]
I though you use before offer or in between offer and and answer.

**Comment by gmaruzz** [comment]
(never used rtpengine_play myself, but from your error rtpengine seems to not know about the call... I would try to use rtpengine_play after an offer)

**Comment by volga629-1** [comment]
I think it more related too 

```
[root@vprx00 ~]# tail -f /var/log/opensips/opensips.log | grep rtp
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:send_rtpe_command: timeout waiting reply from a RTP proxy
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:send_rtpe_command: proxy <udp:127.0.0.1:2223> does not respond, disable it
Jan 20 15:44:51 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:52 vprx00 /usr/sbin/opensips[2696762]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696771]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696755]: ERROR:rtpengine:rtpe_function_call: no available proxies
Jan 20 15:44:53 vprx00 /usr/sbin/opensips[2696755]: ERROR:rtpengine:rtpe_function_call: no available proxies

```

**Comment by volga629-1** [comment]
Here are the answer from rtpengine devs

```
So you're sending an answer for a call ID that hasn't seen an offer first. That's a usage error but doesn't explain why it would stop responding. It would simply return an error and then keep going. Unless OpenSIPS sees the error as a reason to disable this instance of rtpengine and then you don't have any left to use. I can't help with OpenSIPS.
```

**Comment by razvancrainea** [comment]
The error indicates that rtpengine does not send a reply, thus a timeout, not a call error. This means that most likely rtpengine did not process the offer command at all, therefore when the `play` command reaches the server, he's not aware of any command.
You should investigate why the `offer` call timed out. You might want to try create a pcap capture of the communication between opensips and rtpengine, that would be helpful.

Best regards,
Razvan

**Comment by volga629-1** [comment]
@razvancrainea  Based on rtpengine comments opensips should not quit on this error, because this is not control plan error this is call error. I noticed that opensips is not differentiate between typo of errors. On this error it should continue and not trigger timeout.  
And missing offer sometimes happens we added extra flag to have better  check of this situation, but that no fix original issue.


````
I am think opensips mistakenly marking as offline meaning call error is counts as control protocol error and then it set rtpengine offline
```

**Comment by razvancrainea** [comment]
What is the error are referring to?
All I can see in the logs you sent is that opensips did not get *any* reply from rtpengine (either error or success), hence it times out. I double check and the only case when OpenSIPS disables rtpengine is when no reply is received, never on errors.

**Comment by volga629-1** [comment]
Unknown Call-ID that call error, not  health check. Opensips should  only  check  rtpengine health check.

**Comment by razvancrainea** [comment]
We're not disabling rtpengine due to that error, it was disabled due to the timeout.

**Comment by volga629-1** [comment]
@razvancrainea  What you think about  idea introduce configurable module parameter for ping/pong timeout ?

**Comment by razvancrainea** [comment]
@volga629-1 this is exactly what the [rtpengine_tout](https://opensips.org/docs/modules/3.1.x/rtpengine.html#param_rtpengine_tout) parameter does.
