### ISSUE TITLE
[BUG] devel / 3.2: Error: 'Multiple primary key defined'

### ISSUE THREAD

**Issue by kuuse** [OpenSIPS/opensips#2379]
Hi,

I cloned the Opensips sources...

    git clone https://github.com/OpenSIPS/opensips.git

... and it compiled with no issues.

Here is the version:

    ./build/sbin/opensips -V
    version: opensips 3.2.0-dev (x86_64/linux)
    flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC,     DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
    ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
    poll method support: poll, epoll, sigio_rt, select.
    git revision: 5b551ba35
    main.c compiled on 11:10:30 Jan 19 2021 with gcc 9

I am running Ubuntu:

    lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.1 LTS
    Release:	20.04
    Codename:	focal

When I then ran:

    opensips-cli -x database create

I got the following error:

    File "/usr/local/lib/python3.8/dist-packages/mysqlclient-1.3.14-py3.8-linux-x86_64.egg/MySQLdb/connections.py", line 280, in query
        _mysql.connection.query(self, query)
    sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1068, 'Multiple primary key defined')
    [SQL: CREATE TABLE cachedb (
        id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
        keyname CHAR(255) PRIMARY KEY NOT NULL,
        value TEXT(512) NOT NULL,
        counter INT(10) DEFAULT 0 NOT NULL,
        expires INT(10) UNSIGNED DEFAULT 0 NOT NULL,
        CONSTRAINT cachedbsql_keyname_idx UNIQUE (keyname)
    ) ENGINE=InnoDB]
    (Background on this error at: http://sqlalche.me/e/e3q8)

Removing **PRIMARY KEY** from the following line

https://github.com/OpenSIPS/opensips/blob/master/scripts/mysql/cachedb_sql-create.sql#L4

fixed the issue for me.

Best Regards,
Johan Kuuse

**Comment by bogdan-iancu** [comment]
My bad, let me fix it asap

**Comment by kuuse** [comment]
Thanks for a quick fix! :-)
