### ISSUE TITLE
[BUG] Siprec Contact Header "+sip.src"

### ISSUE THREAD

**Issue by jofiy** [OpenSIPS/opensips#2383]
**OpenSIPS version you are running**

version: opensips 2.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 44afc4a15
main.c compiled on 10:27:01 Oct 28 2020 with gcc 4.4.7

version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

```
```

**Describe the bug**

The contact parameter "+sip.src" is not generated when recording started.

According to rfc7866 (6.1.1): 
The SRC MUST include the "+sip.src" feature tag in the Contact URI, defined in this specification as an extension to [RFC3840  <https://tools.ietf.org/html/rfc3840>], for all RSs.

**To Reproduce**

siprec_start_recording("sip:srs.test:5060");

**Expected behavior**

The contact parameter "+sip.src" is generated.

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

CentOS 6, CentOS 7, Debian 10.

**Additional context**

**Comment by razvancrainea** [comment]
The report is valid, looking to fix it.
