### ISSUE TITLE
[BUG] profile_list_dlgs does not return local dialogs when shared profile is used

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#2385]
**OpenSIPS version you are running**
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 892c2ee47
main.c compiled on 19:25:28 Jul  1 2020 with gcc 8

**Describe the bug**
We are using shared profile with value for Concurrent Call Limit between two OpenSIPs running in active active mode. The profile name is cclimit and the profile value is the customer id ie 5574. For no-SQL we use Redis. We try to debug an issue with wrong counting of concurrent calls and we need to know the dialogs which are counted to each OpenSIPs.

When we run 
opensipsctl fifo list_all_profiles

we get

cclimit:: 1

but when we run

opensipsctl fifo profile_list_dlgs cclimit 5547

we get 

404 Profile not found

**To Reproduce**

1. Create a shared profile with value between two OpenSIPs.
2. Make a Call
3. Execute the above mi command

**Expected behavior**
Return the local dialogs

**Relevant System Logs**
none

**OS/environment information**
Debian 10

**Additional context**
none

**Comment by bogdan-iancu** [comment]
hey @apsaras , in your opensips configuration, do yo share the dialogs too, or only the profiles ?

**Comment by apsaras** [comment]
Only the profile.

**Comment by apsaras** [comment]
loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 7200)
modparam("dialog", "db_mode", 0)
modparam("dialog", "profiles_with_value", "cclimit/s")
modparam("dialog", "cachedb_url", "redis:dialog://XXXXX:6379/3")


get_profile_size("cclimit/s","$avp(profile)","$avp(cclimitcurrent)");

if($(avp(cclimitcurrent){s.int}) >= $(avp(profilelimit){s.int}))
{
                send_reply("503", "No More Channels Available");
                exit;
}
set_dlg_profile("cclimit/s","$avp(profile)");

**Comment by bogdan-iancu** [comment]
As the dialog themselves are not replicated, you cannot list them from anywhere else than the opensips which created them.

BTW, when you do the MI call, the name of the profile must be with the `/s`, like:

`opensipsctl fifo profile_list_dlgs cclimit/s 5547`

**Comment by apsaras** [comment]
I knew the fist part but didnt know the /s part. Its working now.

The main issue I have is that the counter at redis is not correct most probably due to a restart of OpenSIPs. Is there a way to re-sync the Redis Counter?

**Comment by apsaras** [comment]
My thought is that you should write distinct values at redis for each OpenSIPs and combine them at the application level. In that way you always update the value with the running counter of each opensips and gets the total by adding them toggether.

ie 
cclimit_5547_1 10
cclimit_5547_2 11

so the get_profile_size will resulut with the sum of cclimit_5547_1 and cclimit_5547_2
and the set_dlg_profile will update the cclimit_5547_1 from OpenSIPs 1 and cclimit_5547_2 from OpenSIPs 2

**Comment by bogdan-iancu** [comment]
Sharing the profiles via noSQL became deprecated due reasons similar to the ones mentioned by you. The correct way to share the profile is via the binary interface (clustering support) - see https://opensips.org/html/docs/modules/2.4.x/dialog.html#dialog-profiling and use `/b` instead of `/s` -> this support is able to resync and to recover when a node goes down. Even more, it is much faster as it does not suffer from the bottleneck of the nosql DB

**Comment by apsaras** [comment]
Thank you @bogdan-iancu . Will try it.

I am sorry for wrong reporting.
