### ISSUE TITLE
[CRASH]OpenSIPS [version-2.4.9] crashed when it could not connect to the database!

### ISSUE THREAD

**Issue by JaydenSam** [OpenSIPS/opensips#2386]
![image](https://user-images.githubusercontent.com/37436679/105830330-52c76d80-6000-11eb-94c5-438972ab6a3c.png)
![image](https://user-images.githubusercontent.com/37436679/105830347-5955e500-6000-11eb-82eb-c5db744d7b54.png)

The logs are displayed in the form of pictures, 
Dear friend, could you please help me to see what caused it !
Thank you very much!!

**Comment by JaydenSam** [comment]
Jan 24 22:00:04 localhost ./opensips[22054]: CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (1927): Connection was killed
Jan 24 22:00:04 localhost ./opensips[22054]: ERROR:usrloc:db_insert_ucontact: inserting contact in db failed
Jan 24 22:00:04 localhost ./opensips[22054]: ERROR:usrloc:wb_timer: inserting contact into database failed
Jan 24 22:00:04 localhost ./opensips[22054]: INFO:db_mysql:switch_state_to_disconnected: disconnect event for 0x7f0ec293f138
Jan 24 22:00:04 localhost ./opensips[22054]: INFO:db_mysql:reset_all_statements: resetting all statements on connection: (0x7f0ec293f2a0) 0x7f0ec293f138
Jan 24 22:00:04 localhost ./opensips[22054]: ERROR:db_mysql:db_mysql_connect: driver error(2002): Can't connect to MySQL server on '127.0.0.1' (115)
Jan 24 22:00:04 localhost ./opensips[22054]: INFO:db_mysql:connect_with_retry: temporary re-connect failure for 0x7f0ec293f138
Jan 24 22:00:04 localhost ./opensips[22054]: CRITICAL:core:sig_usr: segfault in process pid: 22054, id: 14
Jan 24 22:00:05 localhost ./opensips[22084]: CRITICAL:core:handle_worker: dead child 14 (EOF received), pid 22054
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:handle_sigs: child process 22054 exited by a signal 11
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:handle_sigs: core was generated
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jan 24 22:00:05 localhost ./opensips[22038]: INFO:core:sig_usr: signal 15 received
Jan 24 22:00:05 localhost ./opensips[22040]: INFO:core:sig_usr: signal 15 received
Jan 24 22:00:05 localhost ./opensips[22039]: INFO:core:sig_usr: signal 15 received
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 1(22038) [MI FIFO] terminated, still waiting for 27 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 2(22039) [time_keeper] terminated, still waiting for 26 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 3(22040) [timer] terminated, still waiting for 25 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 4(22041) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 24 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 5(22042) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 23 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 6(22043) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 22 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 7(22044) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 21 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 8(22045) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 20 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 9(22046) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 19 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 10(22047) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 18 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 11(22048) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 17 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 12(22049) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 16 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 13(22050) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 15 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 15(22055) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 14 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 16(22056) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 13 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 17(22058) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 12 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 18(22059) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 11 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 19(22060) [SIP receiver udp:10.20.0.107:5090 ] terminated, still waiting for 10 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 20(22062) [TCP receiver] terminated, still waiting for 9 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 21(22063) [TCP receiver] terminated, still waiting for 8 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 22(22064) [TCP receiver] terminated, still waiting for 7 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 23(22065) [TCP receiver] terminated, still waiting for 6 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 24(22066) [TCP receiver] terminated, still waiting for 5 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 25(22067) [TCP receiver] terminated, still waiting for 4 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 26(22069) [TCP receiver] terminated, still waiting for 3 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 27(22071) [TCP receiver] terminated, still waiting for 2 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 28(22072) [Timer handler] terminated, still waiting for 1 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:shutdown_opensips: process 29(22084) [TCP main] terminated, still waiting for 0 more
Jan 24 22:00:05 localhost ./opensips[22037]: INFO:core:cleanup: cleanup
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:db_mysql:db_mysql_connect: driver error(2002): Can't connect to MySQL server on '127.0.0.1' (115)
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:db_mysql:db_mysql_new_connection: initial connect failed
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:core:db_do_init: could not add connection to the pool
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:usrloc:destroy: failed to connect to database
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:proto_wss:tls_write: TLS connection to 183.62.134.100:49444 write failed
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:proto_wss:tls_write: TLS write error:
Jan 24 22:00:05 localhost ./opensips[22037]: ERROR:proto_wss:tls_blocking_write: TLS failed to send data

**Comment by bogdan-iancu** [comment]
Hi @JaydenSam , is your report still valid?

**Comment by JaydenSam** [comment]
Hello! brother，This issue has been fixed with the updated version，I'm so thankful to all of you。Did you just call me from America？













--Jayden 

博学之，审问之，慎思之，明辨之，笃行之。




At 2021-07-21 17:51:06, "Bogdan Andrei IANCU" ***@***.***> wrote:

Hi @JaydenSam , is your report still valid?
