### ISSUE TITLE
[BUG] - RTPEngine Module not read db_default_url 

### ISSUE THREAD

**Issue by Otoru** [OpenSIPS/opensips#2390]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**

I am using the RTPEngine module and when trying to load apply the command `opensips-cli -x mi rtpengine_reload` I get the following error:

``
ERROR: rtpengine: mi_reload_rtpengines: Dynamic loading of rtpengines not enabled
``

In fact I do not have the paramether `db_url` defined in the module, but I do have `db_default_url` with my script file. Shouldn't the RTPEngine module use this data to read the information?

**To Reproduce**

1. Start opensips with db_default_url and rtpengine loaded (without db_url).
2. Call rtpengine_reload in opensips-cli

**Expected behavior**

I expected RTPEngine to read the settings present in the database using `db_default_url`.

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Debian Buster
 - OpenSIPS installation:  debs in apt repository.
 - other relevant information: N/A

**Additional context**

**Comment by liviuchircu** [comment]
Already discussed in https://github.com/OpenSIPS/opensips/issues/2117#issuecomment-655592712.  This module may run without a DB at all, so inheriting the `db_default_url` is not a good idea for neither rtpproxy or rtpengine.

**Comment by Otoru** [comment]
A possible improvement would be to have a `db_mode` flag on the modules informing whether or not we want to work with a database, but for what we currently have this answer makes total sense. 

Thanks @liviuchircu for the feedback, it helped me hold a little more 😄
