### ISSUE TITLE
[CRASH] OpenSIPS [version-3.1.0] crashed when SIPREC SRC rejects reInvite 

### ISSUE THREAD

**Issue by MikhailKalashnikov** [OpenSIPS/opensips#2398]
**OpenSIPS version you are running**

```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 8db0645
main.c compiled on 07:05:55 Sep 21 2020 with gcc 4.8.5

```

**Crash Core Dump**
I follow this link https://www.opensips.org/Documentation/TroubleShooting-Crash but no core dump was generated

**Describe the traffic that generated the bug**

**To Reproduce**

I use OpenSIPS as SIPREC SRC. 
This problem occurs if we receive reInvite, OpenSIPS sends it to SIPREC SRS, but SIPREC SRS responses with failure status 400.
Then when OpenSIPS receives BYE, it crashes

I attached pcap with callflow, my OpenSIPS config, sipp XML to reproduce.

[siprec_crash.zip](https://github.com/OpenSIPS/opensips/files/5932522/siprec_crash.zip)

Example:
1. Start OpenSIPS
2. Start sipp which emulates SIPREC SRS
```
sipp -sf ./sipp.d/uas_siprec_srs_w_reinvite.xml -m 1 -t u1 192.168.31.56:5083 -p 5090 -i 192.168.31.56 -mi 192.168.31.56
```

3. Start sipp which emulates a call

```
sipp -sf ./sipp.d/siprec_test_call.xml -m 1 -t u1 192.168.31.56:5083 -p 5091 -i 192.168.31.56 -mi 192.168.31.56
```

4. OpenSIPS crashes after BYE

**Relevant System Logs**
[siprec_crash.log](https://github.com/OpenSIPS/opensips/files/5932503/siprec_crash.log)

**OS/environment information**
 - Operating System: CentOS, Ubuntu

**Comment by razvancrainea** [comment]
Will try to replicate this and update back.

**Comment by razvancrainea** [comment]
Code was added in the latest master to handle re-INVITEs, currently rejecting them due to the lack of logic. In the future I will try to implement the necessary behavior. In the meantime, I will backport the logic back to 3.1 as well.
