### ISSUE TITLE
[BUG] 3.1.1 dispatcher in cluster (active-passive) try to ping even when does not "own" the cluster tag, eg passive

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2400]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux) GIOVANNI
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 15d05306d
main.c compiled on  with gcc 6.3.0

```

**Describe the bug**

dispatcher in cluster, active-passive
the passive opensips try to ping dispatcher destinations, or at least it checks the socket for pinging, even if it does NOT "own" that service (dispatcher has the cluster tag, and passive does not own the cluster tag, only active owns the cluster tag)
Then, it print error:
<pre>
ERROR:core:proto_udp_send: sendto(sock,0x7f08527d99f8,524,0,0x7f08527dd4b8,16): Invalid argument(22) [192.168.23.155:5060]
CRITICAL:core:proto_udp_send: invalid sendtoparameters#012one possible reason is the server is bound to localhost and#012attempts to send to the net
ERROR:tm:msg_send: send() to 192.168.23.155:5060 for proto udp/1 failed
ERROR:tm:t_uac: attempt to send to 'sip:192.168.23.155:5060' failed
</pre>

**To Reproduce**

put 2 opensips in active/passive cluster
put dispatcher module into cluster
configure dispatcher to ping destinations
do a failover
the "passive" opensips will print errors, because it does not have the Virtual (floating) ip address and socket

**Expected behavior**

the "passive" opensips do not do anything related to pinging dispatcher destinations

**Relevant System Logs**

<pre>
ERROR:core:proto_udp_send: sendto(sock,0x7f08527d99f8,524,0,0x7f08527dd4b8,16): Invalid argument(22) [192.168.23.155:5060]
CRITICAL:core:proto_udp_send: invalid sendtoparameters#012one possible reason is the server is bound to localhost and#012attempts to send to the net
ERROR:tm:msg_send: send() to 192.168.23.155:5060 for proto udp/1 failed
ERROR:tm:t_uac: attempt to send to 'sip:192.168.23.155:5060' failed
</pre>

**OS/environment information**
 - debian 9
 - debs compiled from source
 - other relevant information:

**Additional context**

**Comment by bferreirq** [comment]
Hi,
Someone have some news about this BUG ?
_Regards,_

**Comment by bogdan-iancu** [comment]
Hey @gmaruzz , what is the value of the `cluster_sharing_tag` modparam for the dispatcher module ? Also, after the "switching" please run on each server (original active, original backup) this command and past here the output : `opensips-cli -x mi clusterer_list_shtags`

**Comment by gmaruzz** [comment]
tag is:
<pre>
modparam("clusterer", "sharing_tag", "service/1=backup")
</pre>

on active:
<pre>
(opensips-cli): mi clusterer_list_shtags
[
    {
        "Tag": "service",
        "Cluster": 1,
        "State": "active"
    }
]
</pre>
on passive:
<pre>
(opensips-cli): mi clusterer_list_shtags
[   
    {   
        "Tag": "service",
        "Cluster": 1,
        "State": "backup"
    }
]   
</pre>

**Comment by gmaruzz** [comment]
^ I just edited the previous ^

**Comment by bogdan-iancu** [comment]
so, the "passive" shows the service tag as "backup", but you it still trying to send ping out ?

Nevertheless, in the original configuration, when the original backup was "backup", it was not trying to send the pings ?

**Comment by gmaruzz** [comment]
no more on latest
