### ISSUE TITLE
[CRASH] 3.1.1 latest

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2405]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux) GIOVANNI
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 15d05306d
main.c compiled on  with gcc 6.3.0

```

**Crash Core Dump**

https://pastebin.com/uiszb93x

**Describe the traffic that generated the bug**

Latest git for 3.1.1. I have coredump, if needed I can send it
crashes very very often, since some days... Like each 5 min, or ten... 
Before, same configuration, was not crashing. 

**To Reproduce**

**Relevant System Logs**

Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7339]: CRITICAL:core:sig_usr: segfault in process pid: 7339, id: 15
Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 100 ms ago (now 46890 ms), delaying execution
Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 190 ms ago (now 46980 ms), delaying execution
Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 290 ms ago (now 47080 ms), delaying execution
Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 390 ms ago (now 47180 ms), delaying execution
Feb 17 20:38:05 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 490 ms ago (now 47280 ms), delaying execution
Feb 17 20:38:06 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 590 ms ago (now 47380 ms), delaying execution
Feb 17 20:38:06 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 690 ms ago (now 47480 ms), delaying execution
Feb 17 20:38:06 lxc151 /usr/sbin/opensips[7328]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 790 ms ago (now 47580 ms), delaying execution
Feb 17 20:38:11 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 20:38:11 lxc151 systemd[1]: opensips.service: Failed with result 'exit-code'.

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
compiled debs on debian 9

**Additional context**

**Comment by gmaruzz** [comment]
<pre>
grep exited /var/log/syslog | grep code
...
...
Feb 17 20:27:54 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 20:28:57 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 20:31:00 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 20:32:33 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 20:38:11 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 20:41:21 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 20:45:58 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 20:49:30 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 20:52:33 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 20:56:36 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 21:06:41 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 21:12:14 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 21:17:47 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 21:24:22 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 21:31:24 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 21:38:58 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 21:47:00 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 21:56:03 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Feb 17 22:05:06 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Feb 17 22:14:39 lxc151 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a


</pre>

**Comment by gmaruzz** [comment]
ok, I believe I found the crash cause.

I was trying to have a more accurate hep trace(), that include ACKs to negative replies.

so, I *NOT* loaded the sl.so module (stateless support) and created a transaction at main request route begin

It works very well, the trace is perfect, including those ACKs, but... it crashes very often :))

this sparks CRASH:
<pre>
#loadmodule "sl.so"
modparam("tm", "auto_100trying", 0)

route { 
        t_newtran();

        if (!has_totag()) {
                if(is_method("INVITE") ) {
                        trace("sngrep", "D");
                        trace("homer", "D");
                        send_reply(100, "Trying Hard");
                }
        } else {
                match_dialog();
        }
</pre>

this sparks JOY (albeit, trace has no ACKs to negative replies):

<pre>
loadmodule "sl.so"
modparam("tm", "auto_100trying", 0)

route { 
        #t_newtran();

        if (!has_totag()) {
                if(is_method("INVITE") ) {
                        trace("sngrep", "D"); 
                        trace("homer", "D"); 
                        send_reply(100, "Trying Hard");
                }
        } else {
                match_dialog();
        }


</pre>

**Comment by gmaruzz** [comment]
and this *SPARKS REAL JOY* (ACKs are traced, and seems NO crash):


<pre>
loadmodule "sl.so"
modparam("tm", "auto_100trying", 0)

route { 
        t_newtran();

        if (!has_totag()) {
                if(is_method("INVITE") ) {
                        trace("sngrep", "D"); 
                        trace("homer", "D"); 
                        send_reply(100, "Trying Hard");
                }
        } else {
                match_dialog();
        }
   ...

</pre>

**Comment by sobomax** [comment]
tb->next seems to be b0rken (0x200000001 is not even a valid aligned pointer.
```
void free_to(struct to_body* tb)
{
        if (tb) {
                free_to( tb->next );
```
```
(gdb) bt full
#0  free_to (tb=0x200000001) at parser/parse_to.c:85
        __FUNCTION__ = "free_to"
#1  0x0000557febceabb3 in free_to (tb=0x7f56ae62ce90) at parser/parse_to.c:85
        __FUNCTION__ = "free_to"
```
@gmaruzz can you up to the function free_to() and do print *tb?

**Comment by sobomax** [comment]
P.S. It seems coming via this code, could also be helpful to step up into clean_hdr_field() and do print *hf:
```
                case HDR_PAI_T:
                        free_to(hf->parsed);
```

**Comment by gmaruzz** [comment]
any news on this one? need more info from me?

**Comment by gmaruzz** [comment]
I will reopen if is still in latest
