### ISSUE TITLE
v3.1 ERROR: path '/usr/share/opensips' to OpenSIPS DB scripts does not exist!

### ISSUE THREAD

**Issue by lglhust** [OpenSIPS/opensips#2406]
opensips V3.1 and opensips-cli are installed successfully, but when to create db by opensips-cli, error occured. The tables in opensips database are empty. 

When check us opensips-cli, the result is belows:
/home/opensips-cli/etc# opensips-cli -x diagnose sql
ERROR: Failed to subscribe for JSON-RPC events
ERROR: Is the event_stream.so OpenSIPS module loaded?

In  opensips.cfg, i added modules like below，but nothing changed：

loadmodule "event_stream.so"
modparam("event_stream", "sync_mode", yes)
loadmodule "event_xmlrpc.so"
modparam("event_xmlrpc", "use_struct_param", 1)

/home/opensips-cli/etc#   opensips-cli -f /home/opensips-cli/opensipscli/opensips-cli.cfg -x database create opensips -d

DEBUG: using config file /home/opensips-cli/etc/opensips-cli.cfg
DEBUG: Loaded module 'database'
DEBUG: Loaded module 'diagnose'
DEBUG: Loaded module 'instance'
DEBUG: Loaded module 'mi'
DEBUG: sent command ':opensips_fifo_reply_30224:{"jsonrpc": "2.0", "id": "6402", "method": "which", "params": []}'
DEBUG: Loaded module 'tls'
DEBUG: Loaded module 'trace'
DEBUG: Loaded module 'trap'
DEBUG: Loaded module 'user'
DEBUG: running in non-interactive mode '['database', 'create', 'opensips']'
DEBUG: running command 'create' '['opensips']'
DEBUG: db_name: 'opensips'
DEBUG: admin DB URL: 'mysql://root:1234@localhost'
DEBUG: connecting to mysql://root:1234@localhost
DEBUG: check database URL 'mysql://root:1234@localhost/opensips'
DEBUG: DB does not exist
DEBUG: Create Database 'opensips' for dialect 'mysql' ...
DEBUG: success
DEBUG: DB URL: 'mysql://opensips:opensipsrw@localhost'
DEBUG: connecting to mysql://opensips:opensipsrw@localhost/opensips
INFO: connected to DB, 'opensips' user is already created
DEBUG: connecting to mysql://opensips:opensipsrw@localhost/opensips
DEBUG: check database URL 'mysql://opensips:opensipsrw@localhost/opensips'
DEBUG: DB 'opensips' exists
ERROR: path '/usr/share/opensips' to OpenSIPS DB scripts does not exist!

 I have created a opensips-cli config file with all the details like below:

[default]
log_level: WARNING
prompt_name: opensips-cli
prompt_intro: Welcome to OpenSIPS Command Line Interface!
prompt_emptyline_repeat_cmd: False
history_file: ~/.opensips-cli.history
history_file_size: 1000
output_type: pretty-print
communication_type: fifo
fifo_file: /tmp/opensips_fifo
database_modules: All
database_admin_url: mysql://root:1234@localhost
database_url: mysql://opensips:opensipsrw@localhost
database_name: opensips
database_schema_path: /usr/share/opensips

what's wrong with me?

**Comment by liviuchircu** [comment]
Hi, did you install the `opensips-mysql-module` package, per the [opensips-cli database module documentation](https://github.com/OpenSIPS/opensips-cli/blob/master/docs/modules/database.md#database-schema-files)?

**Comment by lglhust** [comment]
Thanks.
I found the error just now:
I should to change database_schema_path from "/usr/share/opensips"  to  "/usr/local/share/opensips ", then it works. 

Another question ,does opensipsv3.1 support  ims call ?

**Comment by liviuchircu** [comment]
3.1 has no IMS-oriented features.  There are ongoing plans to include some IMS-related work (namely: diameter support) in the upcoming 3.2 release, though.
