### ISSUE TITLE
[BUG] v3.1 ruri format error

### ISSUE THREAD

**Issue by lglhust** [OpenSIPS/opensips#2408]
I want to try call between tow sip client A and B:
user A:   <sip:310080120073500@ims.mnc008.mcc310.3gppnetwork.org>
user B:   <sip:310080120073501@ims.mnc008.mcc310.3gppnetwork.org>

Both of them REGISTER success. When user A send sip call to user B, B cannot receive invite msg.
some of the sip invite info details is as bellows:

Request-Line: INVITE tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org SIP/2.0
From: <sip:310080120073500@ims.mnc008.mcc310.3gppnetwork.org>;tag=qCfcb3I
To: "310080120073501"<tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org>

The opensips server return error: 
       509 status: 476 Unresolvable destination (476/TM)

It seems that opensips cannot resolve the ruri format: "tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org",so it cannot
find the callee. I guess there should be something wrong in opensips.cfg , but i have no idea how to modify the file.
Although it's a simple ims call , i think if the server can parse the ruri correctly and send the call to the callee, the call will be ok.

Here is some log details:

Feb 19 17:01:39 server-10-164 opensips[22371]: new branch at tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:run_trans_callbacks: trans=0x7fb2fd55a890, callback type 4, id 2 entered
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:dialog:dlg_update_contact: Using the same contact <sip:310080120073500@10.45.0.51:5060> for dialog 0x7fb2fd5563c8 on leg 0
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:mk_proxy: doing DNS lookup...
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:str2ip6: too few colons in []
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:sip_resolvehost: no port, no proto -> do NAPTR lookup!
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:get_record: lookup(, 35) failed
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:sip_resolvehost: no valid NAPTR record found for , trying direct SRV lookup...
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:get_record: lookup(_sip._udp., 33) failed
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:sip_resolvehost: no valid SRV record found for _sip._udp., trying A record lookup...
Feb 19 17:01:39 server-10-164 opensips[22371]: CRITICAL:core:mk_proxy: could not resolve hostname: ""
Feb 19 17:01:39 server-10-164 opensips[22371]: ERROR:tm:uri2proxy: bad host name in URI <tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org>
Feb 19 17:01:39 server-10-164 opensips[22371]: ERROR:tm:t_forward_nonack: failure to add branches
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:t_relay_to: t_forward_nonack returned error
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:MD5StringArray: MD5 calculated: f66b526735246880b0b428a61a466037
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:parse_headers: flags=ffffffffffffffff
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:run_trans_callbacks: trans=0x7fb2fd55a890, callback type 64, id 0 entered
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set str hash_entry='938'
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set str hash_id='1923664727'
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set str callid='tBfcb3Iqg@10.45.0.51'
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set str from_tag='qCfcb3I'
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set str to_tag=''
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set int old_state=1
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:evi_param_set: set int new_state=5
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:core:destroy_avp_list: destroying list (nil)
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:dialog:next_state_dlg: dialog 0x7fb2fd5563c8 changed from state 1 to state 5, due event 4
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:dialog:dlg_onreply: dialog 0x7fb2fd5563c8 failed (negative reply)
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:cleanup_uac_timers: RETR/FR timers reset
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:set_timer: relative timeout is 500000
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:insert_timer_unsafe: [4]: 0x7fb2fd55a9d8 (958900000)
Feb 19 17:01:39 server-10-164 opensips[22371]: DBG:tm:insert_timer_unsafe: [0]: 0x7fb2fd55aa08 (963)

**Comment by lglhust** [comment]
In fact , tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org is same with  
             tel:310080120073501@ims.mnc008.mcc310.3gppnetwork.org

How to configure it to a right way, does it need a patch in code ?

**Comment by bogdan-iancu** [comment]
Hi @lglhust , even if a `tel` uri is recognized and parsed by OpenSIPS, such a URI is not routable - you cannot do `t_relay()` on it, as it has no domain into it.

What you should do, if a `tel` uri received , is to covert it (script) level into a SIP uri - in your case to use username/number as username and the "phone-context" param as host/domain part.

Basically to get from `tel:310080120073501;phone-context=ims.mnc008.mcc310.3gppnetwork.org` to `sip:310080120073501@ims.mnc008.mcc310.3gppnetwork.org`
