### ISSUE TITLE
[BUG] Dispatcher pvar_algo_pattern

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2413]
**OpenSIPS version you are running**

```
devel, 3.1
```

**Describe the bug**
Starting in 3.1, using dispatcher module with algorithm 9 (pvar_algo) appears to be broken. Looking through the logs I see reference to algo 10 even though 9 is being used: `ERROR:dispatcher:ds_select_dst: No hash_route param provided`.

It looks like when algo 10 was added, `break` statement was missed for algo 9.

Snippet from 3.1:
https://github.com/OpenSIPS/opensips/blob/a98b3b5e009865cb1bd8e86d4a8e42d44a8a84cc/modules/dispatcher/dispatch.c#L1734-L1760

**Comment by liviuchircu** [comment]
Good catch, @john08burke, your suggested fix was on the spot!
