### ISSUE TITLE
[FEATURE]It is recommended to write the registration status to the database table of the UAC Registrant module

### ISSUE THREAD

**Issue by zhouboyong** [OpenSIPS/opensips#2414]
When the number of registered users of this module exceeds a certain number, use reg_ List function to read the registration status will return failure. In version 2.4.9, when the number exceeds 2400, reg_list is called will return an internal error

It is recommended to write the registration status to the database table of the UAC Registrant module

**Implementation**
 
  - Component: 
  - Type: 
  - Name: 

**Describe alternatives you've considered**

**Additional context**

**Comment by bogdan-iancu** [comment]
@zhouboyong , what MI backend do you use in OpenSIPS when calling the "reg_list" function ?

**Comment by telegant** [comment]
@bogdan-iancu  does prometheus module support monitoring uac_register state or any other function
