### ISSUE TITLE
[FEATURE][cachedb_redis] the redis uri auto recognization for the last slash

### ISSUE THREAD

**Issue by ChrisZhangJin** [OpenSIPS/opensips#2416]
**Opensips:2.4 branch**
**mod: cachedb_redis**

**Is your feature request related to a problem? Please describe.**

i forgot adding the last slash for the redis uri, which causing the the url parsing error.
after i added it, it turned out to be OK.

the redis uri is like this:
``` 
redis:group1://:devxxxxxx@172.31.180.127:6379/
````
sometimes the last slash would be forgotten unfortunately
``` 
redis:group1://:devxxxxxx@172.31.180.127:6379
````

Here is the log segment for parsing error when last slash was missing.
![log segment](https://user-images.githubusercontent.com/14982377/108963975-d636b600-76b5-11eb-8481-6b1aabab2658.png)

**Describe the solution you'd like**

so i hope:
if even the last slash is forgotten to be added, the parsing process could be working fine compatibly

**Implementation**
None

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ChrisZhangJin** [comment]
one more question, can it be done that hidding the redis password(plain text) in log in the debug mode?

**Comment by liviuchircu** [comment]
Thank you for the report, @ChrisZhangJin -- I can confirm the issue.  A fix will be available soon, including the "masked" password fix, which sounds more than reasonable.
