### ISSUE TITLE
[BUG] db_sqlite can't load whole table on opensips initalization

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#2418]
Hi opensips team,

if use db_sqlite with sql_cache, it can't load data on opensips start.

In log I see
```
DBG:db_sqlite:db_sqlite_convert_rows: no rows returned from the query
ERROR:sql_cacher:load_entire_table: Failure to issue query to SQL DB: sqlite:///var/spool/opensips.db
ERROR:sql_cacher:cache_init_load: Failed to cache the entire table: mytable
```

For sql_cache it works if set on_demand option to 1.

So, issue is only when opensips starts.

**Comment by bogdan-iancu** [comment]
@nikbyte , is this report still valid for 3.1 or 3.2 ?
