### ISSUE TITLE
Incorrect Parsing of RURI with IPv6 [BUG]

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#2422]
**OpenSIPS version you are running**
version: opensips 2.4.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 947d254
main.c compiled on 15:32:25 Feb 27 2021 with gcc 4.8.5

**Describe the bug**
I am testing IPv6 on OpenSIPs 2.4 with Asterisk 13 as a call generator. The issue I pointed is a parsing issue of RURI at OpenSIPs.

I am not sure if IPv6 on RURI should be within brackets (Asterisk is sending it without) but the result is that RURI is not parsed.

Error Log:

Feb 27 15:47:54 esbc /sbin/opensips[41731]: ERROR:core:parse_uri: bad port in uri (error at char d in state 8) parsed: <sip:5353@fdba:8>(15) /<sip:5353@fdba:8d4a:6fa6::2019> (29)
Feb 27 15:47:54 esbc /sbin/opensips[41731]: ERROR:core:parse_sip_msg_uri: bad uri <sip:5353@fdba:8d4a:6fa6::2019>
Feb 27 15:47:54 esbc /sbin/opensips[41731]: ERROR:core:pv_get_ruri_attr: failed to parse the R-URI

Invite coming from Asterisk

15:40:34.654298 IP6 fdba:8d4a:6fa6::1014.5060 > fdba:8d4a:6fa6::2019.5060: SIP: INVITE sip:5353@fdba:8d4a:6fa6::2019 SIP/2.0
f....s.@...Jo..............Jo......... ......s[.INVITE sip:5353@fdba:8d4a:6fa6::2019 SIP/2.0
Via: SIP/2.0/UDP [fdba:8d4a:6fa6::1014]:5060;branch=z9hG4bK37fcb106
Max-Forwards: 70
From: "Anonymous" <sip:anonymous@anonymous.invalid>;tag=as4a24ad86
To: <sip:5353@fdba:8d4a:6fa6::2019>
Contact: <sip:anonymous@[fdba:8d4a:6fa6::1014]:5060>
Call-ID: 6f9e27714071ea752d538bea178e8673@[fdba:8d4a:6fa6::1014]:5060
CSeq: 102 INVITE
User-Agent: Exelysis UCS
Date: Sat, 27 Feb 2021 13:40:34 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces
Content-Type: application/sdp
Content-Length: 264

v=0
o=exelysis 2141253568 2141253568 IN IP6 fdba:8d4a:6fa6::1014
s=Exelysis UCS
c=IN IP6 fdba:8d4a:6fa6::1014
t=0 0
m=audio 14632 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

**OS/environment information**
Centos 7 latest
OpenSIPs installed from git

**Comment by liviuchircu** [comment]
Hi, @apsaras!

Looking at the RFC 3261 specs for a SIP URI:

```
SIP-URI          =  "sip:" [ userinfo ] hostport
                    uri-parameters [ headers ]
hostport         =  host [ ":" port ]
host             =  hostname / IPv4address / IPv6reference
IPv6reference  =  "[" IPv6address "]"
```

In other words, when building a SIP URI with an IPv6 hostname, the `[` and `]` enclosing square brackets become mandatory.  So I consider that OpenSIPS is doing nothing wrong here, it has no obligation to parse such non-compliant input.  Closing.
