### ISSUE TITLE
Question about b2b_logic code

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#2424]
Hi team,

Inspecting b2b_logic code, I found next part in b2bl_bridge_msg() code:
```
/* update tuple context values with the new ones set in request route */
for (v = local_ctx_vals; v; v = v->next) {
    v->next = tuple->vals;
    tuple->vals = v;
}
```

Is this correct?

Because you're adding new ctx to existing ctx. And what if in request route there are added ctx with the same names which are already exist in the tuple?

**Comment by rvlad-patrascu** [comment]
Hi @nikbyte ,

You are right, we should also check for existing key names when adding the new values (and overwrite the old values, if necessary). I will flag this issue as a bug. Other than that I think the code is correct, it just appends the context values set previously in the request route, before calling `b2b_bridge_request()`, to the values of the current session.
