### ISSUE TITLE
[FEATURE] stir_shaken: populate $identity variable after calling stir_shaken_auth() function

### ISSUE THREAD

**Issue by ccppprogrammer** [OpenSIPS/opensips#2440]
**Is your feature request related to a problem? Please describe.**

It is not possible to access the newly created `Identity` structure after calling stir_shaken_auth() function as only [only lump is added](https://github.com/OpenSIPS/opensips/blob/68806c4b079c7601941785decc9824cfe78c3d27/modules/stir_shaken/stir_shaken.c#L827).
So, for example, I can't add the generated `Identity` value to reply message when `OSIPS` is acts as a `redirect server` and replies with `302 Moved Temporarily` instead of relaying `INVITE`.

**Describe the solution you'd like**

It would be great if `$identity` variable was populated after a successful call of `stir_shaken_auth()` function.
Then it will be possible to access all subnames of the `$identity` variable for further processing.
For example, add the content of `$identity` variable to `t_reply_with_body()` or with `append_to_reply()` and reply with `302 Moved Temporarily` message.

**Comment by ccppprogrammer** [comment]
Hello @rvlad-patrascu !
Any news on this? 
I can't use `STIR/SHAKEN` module without this feature as I need access to the generated `Identity` structure.

**Comment by rvlad-patrascu** [comment]
Hi @ccppprogrammer ,

Check out the new parameter to the `stir_shaken_auth()` function that allows you to specify the Identity header to be appended to replies or even return it via an output variable.
