### ISSUE TITLE
[BUG] opensips 3.0 and 3.1 change Call-ID in responses (if default "DLGCH_" prefix using in Call-ID of request)

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#2443]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 1f04ed427
main.c compiled on 15:14:12 Mar 24 2021 with gcc 9
```

**Describe the bug**

Scheme:
`SIPP -> opensips balancer -> PBX`

Opensips balancer accept Initial INVITE with Call-ID below and pass it to PBX in chain.
```
Call-ID: DLGCH_dkgGWjJwZWNiRFEMY2RkYndJSFYyfmV+KRYHCmR9ZWIqQFRd
```
PBX response with 401 to opensips. Opensips receive 401 response and send it to SIPP.
But in this response opensips insert call-id which is different from original Call-ID:
```
Call-ID: 98c4a950-44b0-4189-8a75-ffbd7451e013
```

"DLGCH_" - This is default value of "th_callid_prefix" parameter.
Anyway, is it correct that opensips change Call-ID in responses?

**To Reproduce**

1. use in initial INVITE Call-ID from example above.
2. balancer have simple configuration. Topology Hiding without Dialog module:
```
########################################################################
loadmodule "topology_hiding.so"
########################################################################
modparam("topology_hiding", "th_contact_encode_passwd", "any password")
modparam("topology_hiding", "th_contact_encode_param", "did")

route[INVITE] {
        send_reply(100, "Trying");
        $T_fr_timeout = 10;
        $du = "sip:2.2.2.2:5096";
        t_on_reply("ON_REPLY");
        topology_hiding();
        route(RELAY);
}

onreply_route[ON_REPLY] {
    if ($rs =~ "2[0-9][0-9]") {
        remove_hf_glob("X-*");
    }
}

route[RELAY] {
    if (!t_relay()) route(LOCAL_REPLY, 408, "Request Timeout");
    exit;
}
```

**Expected behavior**

opensips will not change Call-ID in responses.

**Relevant System Logs**

Logs and pcap attached.

[logs-of-the-problem-call.txt](https://github.com/OpenSIPS/opensips/files/6199611/logs-of-the-problem-call.txt)
[fixed_test-call-filtered.zip](https://github.com/OpenSIPS/opensips/files/6199613/fixed_test-call-filtered.zip)

**OS/environment information**
 - Operating System: Ubuntu 20.04.2 LTS 
 - OpenSIPS installation: from repository "deb https://apt.opensips.org focal 3.1-releases" 
 - other relevant information:

**Additional context**

Thank you!

**Comment by razvancrainea** [comment]
You should try to setup your own [th_callid_prefix](https://opensips.org/docs/modules/3.1.x/topology_hiding.html#param_th_callid_prefix), as OpenSIPS believes it has been generated by him, and "decodes" the callid.

**Comment by razvancrainea** [comment]
I actually only read the initial report - I've noticed that you figured out the prefix - this is actually how OpenSIPS should behave when the same prefix is used by two instances, so it is not a bug. The documentation kindly ask you to make sure you change the value if you have a setup where multiple OpenSIPS instances are chained.
