### ISSUE TITLE
ACK loop when using topology_hiding

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2444]
**OpenSIPS version you are running**
```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 02:22:09 Mar 25 2021 with gcc 8
```

**Describe the bug**
When using topology_hiding module with the `U` flag, a UAS generated re-INVITE breaks the routing for the subsequent ACK.  UAC generated re-INVITEs route normally.  The misrouting may more broadly encompass UAS generated subsequent requests, but I only tested INVITE.  Engaging topology_hiding module with any combination of the `D`/`C` flags routes as expected.

It appears that the issue may fall in the processing of the 200 OK from re-INVITE, as the logs indicate that the contact is incorrectly being replaced with the proxy's contact:
```
Mar 25 02:38:06 [56] DBG:dialog:dlg_update_contact: Found unparsed contact [sip:192.168.1.18;did=e3b.ed552933]
Mar 25 02:38:06 [56] DBG:dialog:dlg_update_contact: Replacing old contact <sip:1000@192.168.1.12:5060> for dialog 0x7ff015e1f5a8 on leg 0
Mar 25 02:38:06 [56] DBG:dialog:dlg_update_contact: Updated contact to <sip:192.168.1.18;did=e3b.ed552933> for dialog 0x7ff015e1f5a8 on leg 0
```
where:
**UAC:**   192.168.1.12:5060
**Proxy:** 192.168.1.18:5060
**UAS:**   192.168.1.12:5070

Here are the full debug logs with associated network capture and minimal config: 
[opensips_failure.zip](https://github.com/OpenSIPS/opensips/files/6201735/opensips_failure.zip)

**To Reproduce**
Use `topology_hiding("U")` method on initial INVITE and send re-INVITE from UAS. The ACK from second INVITE will loop. You can use minimal config that I attached above to reproduce.

**Expected behavior**
ACK should be routed to UAC based upon UAC's Contact header.

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git (just built w/ nightly 3.1)

**Comment by john08burke** [comment]
I had some time today to narrow down the regression via `git bisect`. It appears the issue was introduced in this commit a41a859f4c6f78d899b8b79ad49e150ad9d54145.

**Comment by john08burke** [comment]
While the above commit (a41a859f4c6f78d899b8b79ad49e150ad9d54145) was the commit that my unit test cases for TH started to break, I don't believe it is a regression per se but rather exposed an underlying issue.  It appears that that the topology_hiding module isn't properly processing the Contact header on the 2xx reply for any target refresh requests.

per RFC3261 12.2.1.2:
```
   When a UAC receives a 2xx response to a target refresh request, it
   MUST replace the dialog's remote target URI with the URI from the
   Contact header field in that response, if present.
```

In my test environment (pcap attached earlier), the UAC was sending initial INVITE with `Contact: <sip:1000@192.168.1.12:5060>` then later replying with 200 on re-INVITE without username `Contact: <sip:192.168.1.12:5060>`. Since I was using `U` flag, OpenSIPS caught the contact change via the condition in a41a859f4c6f78d899b8b79ad49e150ad9d54145 and caused a routing loop.  It seems this is due to topology_hiding module in general is not updating the remote URI on target refresh replies regardless of flags.

Here is a minimalistic example: [opensips_target_refresh.zip](https://github.com/OpenSIPS/opensips/files/6213717/opensips_target_refresh.zip)

UAS reply to initial INVITE:
```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.18:5060;branch=z9hG4bK64b6.af52fa1.0
From: <sip:1000@192.168.1.12:5060>;tag=TUKGZzpJiyyB
To: <sip:9000@192.168.1.18:5060>;tag=mSRmGOhDPQVI
Call-Id: OSESfHlKuScINgUJjdOEGTrZinPCIWsTBLgu
Cseq: 1 INVITE
Contact: <sip:192.168.1.12:5070>
Content-Type: application/sdp
Content-Length: 204
```

UAS update contact in reply to re-INVITE:
```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.18:5060;branch=z9hG4bK34b6.c6f0d791.0
From: <sip:1000@192.168.1.12:5060>;tag=TUKGZzpJiyyB
To: <sip:9000@192.168.1.18:5060>;tag=mSRmGOhDPQVI
Call-Id: OSESfHlKuScINgUJjdOEGTrZinPCIWsTBLgu
Cseq: 2 INVITE
Contact: <sip:192.168.1.13:5090>
Content-Type: application/sdp
Content-Length: 204
```

However OpenSIPS continues to route sequential requests to original Contact (**<sip:192.168.1.12:5070>**) instead of updated Contact (**<sip:192.168.1.13:5090>**).

**Comment by razvancrainea** [comment]
Hi, John!

Thanks for the detailed report - the problem is, indeed, not a regression, but an underlying issue. The fact that the Contact changes, along with the `U` flag, generates a new Contact, one that the dialog module is not aware. And, since it is not aware (although it does point to himself), it updates its internal data with it, and results in the looping you are experiencing.
Unfortunately a fix is not that straight forward - I will give it some thought and get back to you as soon as I have some ideas.

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Hi, John!

I've just create a quick patch to see if this fixes your scenarios. Can you please apply it and run again your tests?

[th-update-dialog.txt](https://github.com/OpenSIPS/opensips/files/6258565/th-update-dialog.txt)

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Actually forget about my previous patch, as that was just a hack - can you run a few tests with the patch I've just pushed in master (50858e8a). Thanks!

**Comment by john08burke** [comment]
Hey @razvancrainea, thanks for the quick patch! I was able to cherry-pick it down to 3.1 and all my tests passed, which included a test case to confirm the sequential routing change w/ updated contact.

If needed I can run against master, but I was having some issues getting the wolfssl module to compile. My test env hasn't quite made the move yet to 3.2 :smile:

**Comment by razvancrainea** [comment]
No need to run against master, code is more or less the same, so cherry-picking should suffice. I will now backport it everywhere.
Thanks for reporting and testing this!
