### ISSUE TITLE
[CRASH] core dump in next_branches --> search_next_avp in 2.4.9 (nightly build as of march 5th)

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#2446]
**OpenSIPS version you are running**

```
version: opensips 2.4.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 21:22:53 Mar  5 2021 with gcc 4.8.5

```

**Crash Core Dump**

https://pastebin.com/raw/WPBd27jq

**Describe the traffic that generated the bug**

INVITE sent to remote server which responded with 300 and opensips crashed in next_branches.  We have seen this in fail-over scenarios after getting a negative response as well.  Always in next_branches.  It is very intermittent.  We sometimes will run at high volumes for weeks without having a crash. 

**To Reproduce**

1.  start opensips
2. start traffic
3. run for week to month
4. get core dump in next_branches function randomly after having called it thousands of times per day previous.

**Relevant System Logs**

```2021-03-25T18:04:51.776626+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4490]: ERROR:tm:w_t_relay: t_forward_nonack failed
2021-03-25T18:04:59.222669+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4490]: INFO:tm:t_forward_nonack: discarding fwd for a cancelled transaction
2021-03-25T18:04:59.223038+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4490]: ERROR:tm:w_t_relay: t_forward_nonack failed
2021-03-25T18:05:04.727529+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4480]: INFO:tm:t_forward_nonack: discarding fwd for a cancelled transaction
2021-03-25T18:05:04.727831+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4480]: ERROR:tm:w_t_relay: t_forward_nonack failed
2021-03-25T18:05:06.866238+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4487]: CRITICAL:core:sig_usr: segfault in process pid: 4487, id: 9
2021-03-25T18:05:10.465386+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4474]: INFO:core:handle_sigs: child process 4487 exited by a signal 11
2021-03-25T18:05:10.465834+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4474]: INFO:core:handle_sigs: core was generated
2021-03-25T18:05:10.466281+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4474]: INFO:core:handle_sigs: terminating due to SIGCHLD
2021-03-25T18:05:10.466658+00:00 sbc-proxy-01 /usr/local/opensips/sbin/opensips[4477]: INFO:core:sig_usr: signal 15 received
```
**OS/environment information**
 - Operating System: CentOS 7
 - OpenSIPS installation: manual download source from git nightly build
 - other relevant information:

**Additional context**

**Comment by liviuchircu** [comment]
Hi, @rrevels-bw!

There seems to be some SHM corruption going on, however we have some some interesting info to look at, which may quickly point to the root cause of the issue:

Within Call-ID `4460886_128161837@192.168.1.112` (if you still happen to have the SIP trace), where `+19198784684` dials `+13368787407`, do you happen to have any indication as to what the following number could mean: `52219256`?  Any information is good information!

**Comment by liviuchircu** [comment]
Also, within the `gdb` session, could you run the following two commands and provide the output?  Thanks!

```
f 0
x/40c (char *)&avp - 20
```

**Comment by rrevels-bw** [comment]
That series of numbers appears to be the called number of another call happening at the same time as the call with the call-id you called out. The first digit and last digit and prepend +1 are missing from the 10 digit e164 number.

(gdb) x/40c (char *)&avp - 20
Address requested for identifier "avp" which is in register $rax

**Comment by liviuchircu** [comment]
Thanks - that's unfortunate, let's see if we can get in through the window!  The below code should print out the memory area we're looking for (basically, 20 bytes to the left and right of that `52219256` number):

```
frame 2
set $i = avp
set $stop = 0
while (!$stop)
  if ($i.next == 0x3635323931323235)
    x/40c (char *)&$i.next - 20
    set $stop = 1
  else
    set $i = $i.next
  end
end
```

**Comment by rrevels-bw** [comment]
(gdb) frame 2
#2  0x000000000049966f in next_branches (msg=msg@entry=0x7f609e1209c0 <faked_req.11049>) at serialize.c:406
406     return (search_next_avp(avp, NULL)==NULL)?2:1;
(gdb) set $i = avp
(gdb) set $stop = 0
(gdb) while (!$stop)
 >  if ($i.next == 0x3635323931323235)
  >    x/40c (char *)&$i.next - 20
  >    set $stop = 1
  >  else
  >    set $i = $i.next
  >  end
 >end
0x7f60a9e363a4: 96 '`'  127 '\177'  0 '\000'    0 '\000'    0 '\000'    0 '\000'    0 '\000'    0 '\000'
0x7f60a9e363ac: 0 '\000'    0 '\000'    0 '\000'    0 '\000'    60 '<'   115 's' 105 'i' 112 'p'
0x7f60a9e363b4: 58 ':'  43 '+'  49 '1'  51 '3'  53 '5'  50 '2'  50 '2'  49 '1'
0x7f60a9e363bc: 57 '9'  50 '2'  53 '5'  54 '6'  51 '3'  64 '@'  49 '1'  57 '9'
0x7f60a9e363c4: 50 '2'  46 '.'  49 '1'  54 '6'  56 '8'  46 '.'  50 '2'  49 '1'

**Comment by liviuchircu** [comment]
Looking good!  So far we know that _some code_ is writing the `"<sip:+13522192563@192.168.21..."` string in a place where it shouldn't, corrupting an AVP chain.  Let's print out 100 more bytes to the right, just so we have the full string that is being written - maybe knowing the string will give us a better hint as to what it is and who's writing it:

```
frame 2
set $i = avp
set $stop = 0
while (!$stop)
  if ($i.next == 0x3635323931323235)
    x/140c (char *)&$i.next - 20
    set $stop = 1
  else
    set $i = $i.next
  end
end
```

**Comment by rrevels-bw** [comment]
its going to take me a while to chase this down so figured i would get a second opinion before going into it.  is there a chance for corruption if this section of code runs in one thread from serialize_branches while next_branches is running in another thread?

	if (clean_before)
		destroy_avps( 0/*type*/, serial_avp, 1/*all*/);
