### ISSUE TITLE
[BUG] Mid Registrar lookup consistency 

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2454]
Version
```
[root@vprx01 opensips]# opensips -V
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 58804282f
main.c compiled on 00:00:00 Dec 31 2020 with gcc 10

````

Issue:
Multi device registration impossible to route consistently in dialog  method  like  ACK  with topology hiding   and mid registrar.

Scenario:

![opensips](https://user-images.githubusercontent.com/59034879/113072394-5791d480-919d-11eb-90f9-8fe93313bb67.png)

Logs

I will send directly to email all required PCAP.

Expected result: 
Lookup will find all saved results and ACK will be routed to proper end point.

**Comment by volga629-1** [comment]
Is any additional information is require ?
This issue start be critical.

**Comment by volga629-1** [comment]
Please @liviuchircu  allocate some time to check this issue is really affecting sip flows.
As you can see on trace Re-INVITE was send to wrong location. This extension contain multiply  registered devices 


![Lookup-failed-Re-INVITE](https://user-images.githubusercontent.com/59034879/117370632-0f9d5600-ae9d-11eb-8f2f-38d8e2b68a0c.png)

**Comment by volga629-1** [comment]
@liviuchircu  Can you please allocate some time and check this issue. It start to be critical and affect many calls.
If you will need full log I will send you to email.

With change 

```
        if(is_method("ACK")) {
                mid_registrar_lookup("location");
        } else {
                mid_registrar_lookup("location", "m");
        }

```


Here are debug where location is find all the records, but it never fork to to all destinations 


```
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [RELAY] [ACK] redis data set result tcp_105_asteriskantioquia.colpbx.com
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 37 bytes for row_buf[6] at 0x7f2bf7b6e650
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:core:comp_scriptvar: str 29 : tcp
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][6] Column[to_tag]=[86d5-61aa27af00f5cf40d57637c81dc1df2a]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [RELAY] [ACK] matched transport tcp / for user 105
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,7)=[5qncghh2vpu9q9vqqool]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [RELAY] [ACK] matched transport tcp
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 20 bytes for row_buf[7] at 0x7f2bf86f9e18
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [RELAY] [ACK] In dialog ACK didn't match R-URI schema [sip:105@asteriskantioquia.colpbx.com] correcting from [sip:105@asteriskantioquia.colpbx.com]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][7] Column[callid]=[5qncghh2vpu9q9vqqool]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:core:cachedb_store: from script [redis] - with grp [loc-sub]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,8)=[1]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 1 bytes for row_buf[8] at 0x7f2bf7d31d20
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][8] Column[local_cseq]=[1]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:cachedb_redis:redis_set: set loc-sub to sip:105@asteriskantioquia.colpbx.com - status = 5 - OK
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,9)=[], zero len
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:cachedb_redis:redis_set: set loc-sub to expire in 250 s -
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 0 bytes for row_buf[9] at 0x7f2bf7d31d58
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [CONTACT_LOOKUP] [ACK] looking up [sip:105%40asteriskantioquia.colpbx.com@10.30.100.61:5060]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][9] Column[record_route]=[]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:core:unescape_user: unescaped string is <105@asteriskantioquia.colpbx.com>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,10)=[sip:qk044gj0@5hghbcokn56l.invalid;transport=wss]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:select_contacts: ct: sip:105-bb891e46ab15108ec459c9e370d31df1@216.93.246.120:5060;transport=TCP
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 47 bytes for row_buf[10] at 0x7f2bf7b6a9c0
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:select_contacts: ct: sip:105-e073cfd2ac7a339db591afb751629efa@216.93.246.120:5060;transport=TCP
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][10] Column[contact]=[sip:qk044gj0@5hghbcokn56l.invalid;transport=wss]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:select_contacts: ct: sip:105@190.7.146.188:1973;rinstance=feb50720c2f6688c;transport=tcp
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,11)=[1610327932]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:select_contacts: ct: sip:105@190.7.146.188:17790;rinstance=feb50720c2f6688c;transport=tcp
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 10 bytes for row_buf[11] at 0x7f2bf863ebf0
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:select_contacts: ct: sip:105@190.7.146.188:2519;rinstance=648d03da4762d0e9;transport=tcp
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][11] Column[expires]=[1610327932]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:push_branch: setting msg R-URI <sip:105-bb891e46ab15108ec459c9e370d31df1@216.93.246.120:5060;transport=TCP>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,12)=[], zero len
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:push_branch: setting branch R-URI <sip:105-e073cfd2ac7a339db591afb751629efa@216.93.246.120:5060;transport=TCP>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 0 bytes for row_buf[12] at 0x7f2bf7d31ba8
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:push_branch: setting branch R-URI <sip:105@190.7.146.188:1973;rinstance=feb50720c2f6688c;transport=tcp>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: [34][12] Column[reason]=[]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:push_branch: setting branch R-URI <sip:105@190.7.146.188:17790;rinstance=feb50720c2f6688c;transport=tcp>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: PQgetvalue(0x7f2bf7ec7698,34,13)=[wss:190.248.157.5:8443]
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: DBG:mid_registrar:push_branch: setting branch R-URI <sip:105@190.7.146.188:2519;rinstance=648d03da4762d0e9;transport=tcp>
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370708]: DBG:db_postgres:db_postgres_convert_rows: allocated 22 bytes for row_buf[13] at 0x7f2bf86f9d00
May  6 22:21:11 vprx01 /usr/sbin/opensips[3370707]: [CONTACT_LOOKUP] [ACK] Contact found [sip:105-bb891e46ab15108ec459c9e370d31df1@216.93.246.120:5060;transport=TCP]
```





As you can see Re-INVITE ( Session Timer Expired) in  dialog is forked to all destinations, but when come to ACK it not.  

![ACK-multi-leg-call](https://user-images.githubusercontent.com/59034879/117395564-8f8fe400-aece-11eb-864d-9a0f6e0f42fe.png)

**Comment by liviuchircu** [comment]
Apologies for slowing down on this issue during the last month, @volga629-1, but things have been very busy.  I understand your scenario and problem (thanks for the info!), just need to find some time to attempt to reproduce it.

**Comment by volga629-1** [comment]
Thank you. In order to see traffic in pcap you need add filter for sip protocol in wireshark port 5084. Otherwise it display only UDP protocol. Regard NAT we apply on initial INVITE since internal leg behind topology hiding.

**Comment by volga629-1** [comment]
Wireshark Preference 
![Wireshark-preferences](https://user-images.githubusercontent.com/59034879/117735156-4fc94500-b1cb-11eb-9646-72ae0c96da25.png)

**Comment by volga629-1** [comment]
I can send you configuration file to help reproduce the issue.

**Comment by liviuchircu** [comment]
@volga629-1: I fixed my `topology_hiding("C")` scenario as well.  Since my call was looping on the mid-registrar, I cannot call `topology_hiding("C")` twice, because that confuses the Call-ID detection logic (see the [`th_callid_prefix`](https://opensips.org/docs/modules/3.1.x/topology_hiding.html#param_th_callid_prefix) docs -- it should be unique on each pass).  So the solution was to use the `"C"` flag only on the outbound leg, towards the phones, similar to how you are doing it.

So I'm waiting for more ideas from your side on how to reproduce the problem.  In my opinion, the ACK should naturally route using just `match_dialog()`, then `t_relay()`.

**Comment by liviuchircu** [comment]
Before I forget, do also consider going for a `3.1.0` to `3.1.2` update.  It's a significant difference, we're talking almost a full year worth of fixes throughout all modules.

**Comment by volga629-1** [comment]
Thank you.

I sent you configuration file just to have easy to compare.  
Please check [RELAY] section.
As you can see if in use 

```
topology_hiding("UC")

```

For initial INVITE I have to use $ru correction too, other wise INVITE contact lookup will fail before parallel forking.
**I will try  add th_callid_prefix.** 
In dialog methods I never was be able route properly from one leg to another without alter $ru. 
Right now I am use 

```if(topology_hiding_match()) {
````
and that not enough to route.

Upgrade, I am waiting for 3.2. Right now is version 3.1

After I added log line 

```
May 11 09:20:08 vprx01 /usr/sbin/opensips[3370720]: [IN_DIALOG] [ACK] in dialog ACK with dialog ID => [881.953c7b66]
May 11 09:20:08 vprx01 /usr/sbin/opensips[3370720]: [IN_DIALOG] ACK loose-routed to $ru=sip:16580300@10.30.100.48:5160;transport=udp, $du=<null>
May 11 09:20:08 vprx01 /usr/sbin/opensips[3370720]: [ACK] Set path header ip ~> 61
May 11 09:20:08 vprx01 /usr/sbin/opensips[3370720]: [RELAY] [ACK] sending call ~> sip:16580300@10.30.100.48:5160;transport=udp over udp:10.30.100.61:5060 for 106039MGExOTI3ZjE4ZWQ4OGZkZDliZDNmODQ1NTAxMjU4ZjE

```

**Comment by liviuchircu** [comment]
> As you can see $ru always private leg and without alter via location I didn't found other method to sent it right direction.

Then try to add the following logic to your call flow (in a form or another), on all `mid_registrar_lookup()` requests:

```
t_on_reply("nat_handling");
```

... then, during replies:

```
route [nat_handling] {
    if (!$hdr(Record-Route) && nat_uac_test(97)) {
        xlog("[$ci] INFO: 200 OK source endpoint is NAT'ed, fixing Contact\n");
        fix_nated_contact();
    }
}
```

... notice how we don't fix the Contact if the endpoint is a SIP proxy, doing record routing.  This should fix the ACK routing.

**Comment by volga629-1** [comment]
> match_dialog()

I am not 100% sure how work match_dialog()  ( in general should find dialog based did= value )  Is it will replace some header ?
Right now I am use, and that not enough to route properly.  

```
if(topology_hiding_match()) {
````

**Comment by liviuchircu** [comment]
> I am not 100% sure how work match_dialog()

It's easier to think of them like this: `topology_hiding_match() > match_dialog() > loose_route()`.  Each function does a bit more than the other, in a concentric fashion, with `topology_hiding_match()` being the "strongest" of all, being able to even match non-dialog topology hiding header params (e.g. the `;vst=` and `;vsp=` parameters, if you use them).

I am awaiting the results for `fix_nated_contact()` properly called on a 200 OK: pcap + config file + script log showing the new `$ru` and `$du` values before investing any more time here.

**Comment by volga629-1** [comment]
After I added nat reply snippet I disabled temporary  all location lookup for ACK method  and ACK never reached end user.
Then I return everything back with location lookup and ACK flows OK. 

Please check you inbox for pcap.

**Comment by liviuchircu** [comment]
Thanks for the pcaps.  Can you look in the logs and find the log we added, for the "Call-no-ACK-12May2021.pcap" call?  What do the new URIs look like, after `topology_hiding_match()`?

**Comment by volga629-1** [comment]
```
May 12 09:21:18 vprx01 /usr/sbin/opensips[3370707]: [IN_DIALOG] ACK loose-routed to $ru=sip:123@201.233.195.100:59659;rinstance=8c230912e5e7e7a5;transport=tcp, $du=<null>
May 12 09:21:19 vprx01 /usr/sbin/opensips[3370711]: [IN_DIALOG] ACK loose-routed to $ru=sip:123@201.233.195.100:59659;rinstance=8c230912e5e7e7a5;transport=tcp, $du=<null>

````
Call-ID :  220a40a3-2dd0-123a-8781-001a4a160165
And no NAT log entry on 200 OK.

**Comment by liviuchircu** [comment]
But this is perfect, that `fix_nated_contact()` worked!! Why is the ACK not heading to TCP 201.233.195.100:59659 in the pcap?  Do you do some more changes after `topology_hiding_match()` and change the `$ru` again somehow?

**Comment by liviuchircu** [comment]
Actually, if you look at frame #8, the Contact is not even NAT'ed, so this should work without `fix_nated_contact()`.  Still, same question applies: are you doing some more changes?  Where does the ACK go to?

**Comment by volga629-1** [comment]
NO we not doing any $ru changes regard  ACK. As I stated before I disabled all lookups or sections for ACK.  It went straight to RELAY.

**Comment by volga629-1** [comment]
This section which I changed for test ACK. I disabled all $ru changes or location lookup for ACK.


```
                if(is_method("INVITE|UPDATE") && !isflagset("FLAG_BRIA_PUSH")) {
                        # Updaing R-URI
                        $ru = $tu;
                }
                # To client
                if(is_method("BYE|INFO|NOTIFY|CANCEL") && !isflagset("FLAG_BRIA_PUSH")) {
                        # Updating R-URI
                        $ru = $tu;
                }
                #if(is_method("ACK") && $avp(ruri)!=NULL) {
                #        xlog("[RELAY] [$rm] ACK with ~> [$ru] from Invite 200 OK\n");
                #        $ru = $avp(ruri);
                #}
                #if(is_method("INVITE|UPDATE|BYE|ACK|CANCEL|NOTIFY|INFO|OPTIONS") && $rU=~"%40") {
                if(is_method("INVITE|UPDATE|BYE|CANCEL|NOTIFY|INFO|OPTIONS") && $rU=~"%40") {
                        xlog("[RELAY] [$rm] testing original [$ru]\n");
                        route(CONTACT_LOOKUP);
                # We want exclude ACK rewrite toward Bria Push Server
                } else if(!is_method("ACK") && !isflagset("FLAG_BRIA_PUSH")) {
                        xlog("[RELAY] [$rm] didn't match R-URI schema [$ru] correcting from [$tu]\n");
                        $ru = "sip:" + $tU + "%40" + $td + "@" + $td;
                        route(CONTACT_LOOKUP);
                } #else if(isflagset("FLAG_ACK_IN_DIALOG") && !isflagset("FLAG_BRIA_PUSH")) {
                   #     xlog("[RELAY] [$rm] In dialog ACK didn't match R-URI schema [$ru] correcting from [$tu]\n");
                        #$ru = "sip:" + $tU + "%40" + $td + "@" + "10.30.100.61" + ":" + "5060";
                        #route(CONTACT_LOOKUP);
                #}
                if(is_method("ACK") && $avp(ua_orig_trns)==NULL) {
                        #  TCP applied 
                        $var(src_socket) = "tcp" + ":" + $avp(req_ip) + ":" + "5084";
                }
```

**Comment by volga629-1** [comment]
Here are good example of the issue. 
As you can see IN_DIALOG after if(topology_hiding_match()) { $ru is correct , but when arrive to the t_relay log line 

```
        xlog("[RELAY] [$rm] sending call ~> $ru over $socket_out for $ci\n");
        if(!t_relay()) {
                send_reply(500, "Internal Error");
                exit;
        }
```

Request URI is incorrect or restored to original state. I checked 10 times configuration file and can't find where or how $ru got changed.

```
May 12 12:52:59 vprx01 /usr/sbin/opensips[3370705]: ERROR:presence:publ_notify: Could not send notify for presenceMay 12 12:53:00 vprx01 /usr/sbin/opensips[3370726]: OnReply_Route2: [INVITE] Direction: [Client ~> FS] source IP 190.7.146.188
May 12 12:53:00 vprx01 /usr/sbin/opensips[3370713]: [IN_DIALOG] [ACK] in dialog ACK with dialog ID => [e91.f0d49997]
May 12 12:53:00 vprx01 /usr/sbin/opensips[3370713]: [IN_DIALOG] ACK loose-routed to $ru=sip:105@190.7.146.188:36029;transport=tcp, $du=<null>
May 12 12:53:00 vprx01 /usr/sbin/opensips[3370713]: [ACK] Set socket ip ~> 5
**May 12 12:53:00 vprx01 /usr/sbin/opensips[3370713]: [RELAY] [ACK] sending call ~> sip:105%40asteriskantioquia.colpbx.com@10.30.100.61:5060 over tcp:190.248.157.5:5084 for b845d9ca-2ded-123a-0788-00163e18d969**

````

**Comment by liviuchircu** [comment]
It's starting to look like a scripting bug.  Maybe missing { } in `if` block, tricky tab alignment, etc.  The `$ru` doesn't just change by itself... follow the flow step-by-step, add **as many debugging** `xlog()` and find what changes it :)

**Comment by volga629-1** [comment]
I done the job what you mention. The script looks ok or I didn't found any problem yet.

**Comment by liviuchircu** [comment]
In your cfg file, in route `RELAY`, on this `else` branch:

```
        if(isflagset("FLAG_FROM_PEER")) {
                route(SET_SOURCE_SOCKET_TO_PBX);
                $var(src_socket) = "udp" + ":" + $avp(req_ip) + ":" + "5060";
        } else {
          ...
        }
```

... I can see **5 (five!)** logical `if` blocks where you manually set the `$ru`, like this:

```
if (...) {
    $ru = $tu;
}
```

Put an `xlog()` after each `if` and see where the `$ru` get changed before the final `t_relay()`.  It's that simple...

**Comment by volga629-1** [comment]
Correct. I done that, none of them match ACK to replace $ru.
I pasted log above 

That only line it get match which is last line.

```
*May 12 12:53:00 vprx01 /usr/sbin/opensips[3370713]: [RELAY] [ACK] sending call
```

**Comment by liviuchircu** [comment]
Please provide your last version of the script via email, with all `xlog()` included, so I can review it with another pair of eyes :) This really feels like a programming mistake, I'm afraid.

**Comment by volga629-1** [comment]
Latest config sent  to you email.

**Comment by liviuchircu** [comment]
You can place the `xlog()`s better, so we get closer to understanding **what** changes the `$ru`.  For example:

```
                if(is_method("INVITE|UPDATE") && !isflagset("FLAG_BRIA_PUSH")) {
                        # Updaing R-URI
                        $ru = $tu;
                }
                xlog("L_INFO", "XXX [RELAY] [$rm] $$ru is now $ru\n");

                # To client
                if(is_method("BYE|INFO|NOTIFY|CANCEL") && !isflagset("FLAG_BRIA_PUSH")) {
                        xlog("[RELAY] [$rm] Replacing with ~> [$ru] where are is not match FLAG_BRIA_PUSH\n");
                        # Updating R-URI
                        $ru = $tu;
                }
                xlog("L_INFO", "XXX [RELAY] [$rm] $$ru is now $ru\n");
```

Using this technique, we will _restrict_ the possible code which can change it, until we find the **exact** statement.  The `$ru` cannot change out of thin air, it has to be something we do in the script.  For example, maybe `is_method()` has a bug and it doesn't work as we expect, who knows? :)

Also, you can pause this logging at any time using `opensips-cli -x mi log_level 2` (NOTICE-level logging).

**Comment by volga629-1** [comment]
OK I will change to L_INFO. 
Is log_level=3 is not mean global level set to INFO ?

**Comment by volga629-1** [comment]
I tested the log lines with changes and ACK is not matching any sections with $ru change. I will try get some call debug to try understand what happened from log level 4.

**Comment by liviuchircu** [comment]
OK, then which code block changes it?  Your scripting logic is literally:

```
topology_hiding_match()
xlog("GOOD $ru\n");
block_1;
block_1;
block_1;
block_1;
block_1;

```

**Comment by volga629-1** [comment]
Here fresh log. R-URI format restored not from code. I disabled all the ACK section.


```
May 14 08:49:07 vprx01 /usr/sbin/opensips[3370719]: OnReply_Route2: [INVITE] Direction: [Client ~> FS] source IP 190.7.146.188

May 14 08:49:07 vprx01 /usr/sbin/opensips[3370710]: [IN_DIALOG] [ACK] in dialog ACK with dialog ID => [50a.a656e706]
May 14 08:49:07 vprx01 /usr/sbin/opensips[3370710]: [IN_DIALOG] ACK loose-routed to $ru=sip:105@190.7.146.188:44099;transport=tcp, $du=<null>
May 14 08:49:07 vprx01 /usr/sbin/opensips[3370710]: [ACK] Set socket ip ~> 5
May 14 08:49:07 vprx01 /usr/sbin/opensips[3370710]: [RELAY] [ACK] sending call ~> **sip:105%40asteriskantioquia.colpbx.com@10.30.100.61:5060** over tcp:190.248.157.5:5084 for fc2ae0fa-2f5d-123a-0788-00163e18d969

**Comment by liviuchircu** [comment]
I said everything in my above comment.  If you are unable to add 1 x `xlog()` after each logical step (block), **as I've asked you to do 5 times now**, I cannot do anything more here, and I will stop replying.

**Comment by volga629-1** [comment]
But there are 5 xlogs entries in each logical block.  I am not understand what you referring too ?

**Comment by liviuchircu** [comment]
Put them **outside** the block, after each `route(BRIA_XXX)`, `if (xxx)` and `if (yyy)`.  I don't care what's _in_ the block, the idea is what the value of `$ru` is after a block.  Do you see what I mean?

**Comment by liviuchircu** [comment]
Hey, @volga629!  Also, since I see you changed your `xlog()` calls to use `L_INFO`, make sure to also set the global `xlog_level = 3`, otherwise the messages won't be printed...

PS: this is also controllable via `opensips-cli -x mi xlog_level 3`, without a restart

**Comment by liviuchircu** [comment]
Any updates here, @volga629-1?  Did you manage to understand where your R-URI got changed and is the ACK routing correctly now?

**Comment by volga629-1** [comment]
Hello Liviu,
I tested with logs outside of each block and still not not be able find where $ru is changed. I want to enable debug on call and test, but waiting fo maintenance window . 

volga629

**Comment by liviuchircu** [comment]
Keep in mind that you should also set `xlog_level = 3`, otherwise the xlog("L_INFO"...) will never print!  Are you sure that is not a problem?
