### ISSUE TITLE
Help with collect calls and SIP-i

### ISSUE THREAD

**Issue by Otoru** [OpenSIPS/opensips#2461]
> This is not a problem, it is a call for help

I use the SIP-i module and at that moment I need to set the "Collect call request" bit. Could someone give me an example of how to do this in opensips?

**Comment by Otoru** [comment]
Reading some documentation on the internet I understood that "Collect call request" is a specific bit of "Forward call indicators", but the same error if having to use `$isup_param(Forward call indicators | Collect call request)` I have syntax error.

**Comment by rvlad-patrascu** [comment]
As far as I can tell from the ITU-T Rec Q.763 document, there is a "Collect call request" ISUP parameter, but I don't see such a field in "Forward call indicators" (and this is why OpenSIPS does not support it as a subfield).

**Comment by Otoru** [comment]
I must be consulting the wrong sources. I will close the issue because you have already given me a good direction. Thank you!
