### ISSUE TITLE
dialog.so module fails loading

### ISSUE THREAD

**Issue by FlyingDutchfrog** [OpenSIPS/opensips#2462]
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ac2ce9960
main.c compiled on 11:41:53 Apr  9 2021 with gcc 9

```

**Describe the bug**
I get an error when trying to restart openSIPS with the dialog module loaded in the .cfg file.

**To Reproduce**
1. Load the module with the line `loadmodule "dialog.so"`
    (TM- and RR-Modules are loaded properly to meet dependencies)
2. use `create_dialog();`, `store_dlg_value("foo", "bar");` in the .cfg
3. `service opensips restart` on shell

**Relevant System Logs**
syslog shows this error on attempted restart:
`failed to load module dialog.so#012`

and also:
`ERROR:core:sr_load_module: could not open module </usr/local/lib64/opensips/modules/dialog.so>: /usr/local/lib64/opensips/modules/dialog.so: undefined symbol: get_dummy_sip_msg`

**OS/environment information**
 - Operating System: Linux ip-xxx-xxx-xxx-xxx 5.4.0-1041-aws #43-Ubuntu SMP Fri Mar 19 22:06:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
Updated and upgraded linux und freshly compiled openSIPS with `make clean` and `make menuconfig`. Error persists.

**Comment by liviuchircu** [comment]
Hey, @FlyingDutchfrog!  It looks like your `opensips` binary and `dialog.so` module are out of sync.  Perhaps you have also installed `opensips` by packages and the `service opensips restart` command is picking up some left-over `/usr/sbin/opensips` binary that takes precedence?

Regarding the error itself: it means that the `dialog.so` file is newer than the `opensips` binary.

**Comment by FlyingDutchfrog** [comment]
Hi @liviuchircu! Thanks for the quick reply! Appearently I really did install opensips via package at some point in the past and totally forgot about it. It works now. Many thanks!
