### ISSUE TITLE
[BUG] BYE from dialog timer causes error logs

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2464]
**OpenSIPS version you are running**

```
version: opensips 2.4.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 53244e53e
main.c compiled on 17:28:10 Apr  9 2021 with gcc 7
```

**Describe the bug**

We use `$DLG_timeout` to limit calls to a maximum time and also to disconnect calls that don't receive a proper ACK. When the timer pops a BYE is sent to both ends of the call. We do some handling of the BYE in `local_route` and arm both reply and failure routes for the BYE. A recent change has caused error logs to appear on the response to the BYE in our reply route. It appears the topology_hiding module has callbacks loaded which are firing and attempting to call fix_route_dialog on the now terminated dialog and causing errors. The errors are not present on Git commit 3bed2f312db4dd109952cac922000d690ae492d4 from Dec 2020.

**To Reproduce**

1. Start OpenSIPS
2. Place a call and set $DLG_timeout
3. In local_route, arm a reply route
3. Allow call to time out
4. See errors on BYE response

**Expected behavior**

The errors are unexpected, but it's not clear if any of the attempted processing is actually necessary.

**Relevant System Logs**

```
Apr  9 18:38:00 [439] ERROR:dialog:fix_route_dialog: Script error - validate function before having a dialog
Apr  9 18:38:00 [439] ERROR:topology_hiding:topo_dlg_onroute: Failed to fix the SIP request according to dialog info 
```

**OS/environment information**
 - Operating System:  amazonlinux:2 on Docker
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment]
I should clarify that it's always the *second* BYE reply that gets the error, not the first. The topology_hiding callback appears to be triggered on both, but the second time the dialog is no longer valid.

**Comment by bogdan-iancu** [comment]
@bcnewlin , thanks for the report, this may be also related to adding the new support for `DUMMY` SIP requests.

Here is a fix, if you could validate it.

```
diff --git a/action.c b/action.c
index b0198c344..0bdc27d2a 100644
--- a/action.c
+++ b/action.c
@@ -2234,6 +2234,13 @@ static const char *_sip_msg_buf =
 static struct sip_msg* dummy_static_req= NULL;
 static int dummy_static_in_used = 0;
 
+int is_dummy_sip_msg(struct sip_msg *req)
+{
+       if (req && req->buf==_sip_msg_buf)
+               return 0;
+       return -1;
+}
+
 struct sip_msg* get_dummy_sip_msg(void)
 {
        struct sip_msg* req;
diff --git a/action.h b/action.h
index 4c0c44d27..203f717d8 100644
--- a/action.h
+++ b/action.h
@@ -69,5 +69,6 @@ void __script_trace(char *class, char *action, struct sip_msg *msg,
 
 struct sip_msg* get_dummy_sip_msg(void);
 void release_dummy_sip_msg( struct sip_msg* req);
+int is_dummy_sip_msg(struct sip_msg *req);
 
 #endif
diff --git a/modules/topology_hiding/topo_hiding_logic.c b/modules/topology_hiding/topo_hiding_logic.c
index bbf7ce382..932cf8a6b 100644
--- a/modules/topology_hiding/topo_hiding_logic.c
+++ b/modules/topology_hiding/topo_hiding_logic.c
@@ -1038,7 +1038,7 @@ static void topo_dlg_onroute (struct dlg_cell* dlg, int type,
        /* we also may end up here via TERMINATE event triggered by internal
         * dlg termination -> the requests we have here are dummy, so nothing
         * to be done */
-       if (req->via1==NULL) {
+       if (is_dummy_sip_msg(req)==0) {
                LM_DBG("dummy request identified, skipping...\n");
                return;
        }
```

**Comment by bcnewlin** [comment]
@bogdan-iancu Thank you! I have verified this does stop the errors in these cases.

**Comment by bogdan-iancu** [comment]
Super, let me have it committed

**Comment by bcnewlin** [comment]
@bogdan-iancu I'm seeing this same issue occurring again in 3.2.

```
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f953b30a0
main.c compiled on 21:33:41 Nov 12 2021 with gcc 7
```

**Comment by bcnewlin** [comment]
The newly referenced commit does not seem to have impacted this regression.

```
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7193c5d8d
main.c compiled on 19:04:46 Nov 15 2021 with gcc 7
```

**Comment by bogdan-iancu** [comment]
Hey @bcnewlin , indeed, I had the wrong issue ID in the commits, they were actually related to #2681  - unfortunately I cannot remove the refs here :(
