### ISSUE TITLE
[BUG] geoip module do not work on 2.4.9, it works correctly in 2.4.6 (says cannot open database file)

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2465]
**OpenSIPS version you are running**

```
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by gmaruzz** [comment]
( I tested with both type of databases, old and new. Is not that. Btw, 2.4.6 works with old type databases, the one installed via debian packages, not the new type, to be downloaded from website after registration)

**Comment by razvancrainea** [comment]
Hi, @gmaruzz!

I suspect that OpenSIPS 2.4.6 was built against the old (libGeoIP) library, whereas the new 2.4.9 is built against the new (libmaxminddb) library. These two formats are not compatible - libGeoIP works with the old format, whereas libmaxminddb works with the new format. Hence the failure to load the old database type, only the new one is available.

Best regards,
Răzvan

**Comment by gmaruzz** [comment]
I actually tested with both, but probably there is some snafu there :)

**Comment by gmaruzz** [comment]
keepalive :)

**Comment by gmaruzz** [comment]
update to satisfy bot

**Comment by bogdan-iancu** [comment]
Hi @gmaruzz , have you tested agaist 3.1 or 3.2 ? (2.4 is EOL now)

**Comment by gmaruzz** [comment]
nope, I use it only in a 2.4 env (homer 5)

**Comment by bogdan-iancu** [comment]
should we close it for now and open a new if the this issue pops up again ?

**Comment by gmaruzz** [comment]
sigh...
yes!
