### ISSUE TITLE
[BUG] B2B not considering the Max-Forwards headers on A-leg

### ISSUE THREAD

**Issue by homstr** [OpenSIPS/opensips#2471]
**OpenSIPS version you are running**

version: opensips 2.4.6 (x86_64/linux)

We faced a BUG that the setting of the MAX-FORWARDS parameter do not pass when using the B2B logic
We have found that when using the B2B module, this counter starts counting again from the initial value of 70, which leads to looping of calls in the network.

example from trace

in the input of opensips we have
```
INVITE sip:543174317@94.241.67.137 <mailto:sip%3A543174317@94.241.67.137> SIP/2.0
*Max-Forwards: 18*
Via: SIP/2.0/UDP 94.241.67.136:5062;rport;branch=z9hG4bK759843122
From: <sip:212232435@94.241.67.136:5062 <http://sip:212232435@94.241.67.136:5062>>;tag=298433023
To: <sip:543174317@94.241.67.137 <mailto:sip%3A543174317@94.241.67.137>>
Call-ID: 752394752@94.241.67.136:5062 <http://752394752@94.241.67.136:5062>
CSeq: 3633945 INVITE
User-Agent: YATE/6.2.1
Contact: <sip:212232435@94.241.67.136:5062 <http://sip:212232435@94.241.67.136:5062>>
Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, PRACK, INFO
Supported: 100rel
Content-Type: multipart/mixed;boundary=734768646_1362544590
Content-Length: 443
```
but on the output there is:
```
INVITE sip:543174317@94.241.67.137 <mailto:sip%3A543174317@94.241.67.137> SIP/2.0
Via: SIP/2.0/UDP 94.241.67.137:5060;branch=z9hG4bK5e7e.38ff3a06.0
To: sip:543174317@94.241.67.137 <mailto:sip%3A543174317@94.241.67.137>
From: <sip:212232435@94.241.67.136:5062 <http://sip:212232435@94.241.67.136:5062>>;tag=153c35a5fde4948908525582635dfe04
CSeq: 3633946 INVITE
Call-ID: B2B.506.2825450.1617906940
*Max-Forwards: 70*
Content-Length: 185
User-Agent: OpenSIPS (2.4.6 (x86_64/linux))
Content-Type: application/sdp
Supported: 100rel
Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, PRACK, INFO
Contact: <sip:94.241.67.137:5060 <http://94.241.67.137:5060>>
```
The module documentation says that this header should be passed from the dialog of one side to the other side.
Max-Forwards (it is decreased by 1)

Thanks in advance, with regards, Alexey Homstr,
Please tell if you will need any further information-

**To Reproduce**
for call routing we using function 
b2b_init_request("top hiding");

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
 - OpenSIPS installation: source
 - other relevant information:

**Comment by bogdan-iancu** [comment]
Let's see if 3.2 suffers of this issue or not...

**Comment by bogdan-iancu** [comment]
@rvlad-patrascu , could you test and confirm (or not) this report ?
