### ISSUE TITLE
[BUG] Stir/Shaken memory leak

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2472]
**OpenSIPS version you are running**
```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 02:22:09 Mar 25 2021 with gcc 8
```

**Describe the bug**
I am using the STIR/SHAKEN module to sign calls, but have some failing tests that indicate a memory leak within the module.  The only function being called from this module that I'm using in the config file is `stir_shaken_auth(...)`. The leak can be easily reproduced via this [minimal config](https://github.com/OpenSIPS/opensips/files/6313196/minimal.txt).

The graphs below demonstrate the leak, where `stir_shaken_auth()` is being called from the script. I wrapped the function call in a `$shv(...)` so that I could toggle signing on/off for the test.  As you can see, the memory reported by OpenSIPS reaches steady-state but memory reported by the docker container leaks when calling `stir_shaken_auth()` but is constant when not calling `stir_shaken_auth()`. I stopped traffic and OpenSIPS (as expected) reports very little memory usage after calls dropped off.

The results of the tests indicate a leak outside of OpenSIPS memory management. Could be openssl integration but I haven't been able to narrow it down. Any ideas/help appreciated!

**OpenSIPS Container Statistics**
![opensips_container](https://user-images.githubusercontent.com/36895232/114766375-f258ea00-9d2b-11eb-8f91-f498ad48b5ac.png)

**OpenSIPS Process Statistics**
![opensips_process](https://user-images.githubusercontent.com/36895232/114766684-511e6380-9d2c-11eb-9c1f-c13e1ad3cb91.png)

**To Reproduce**
1. Start OpenSIPS with provided minimal config.
2. Start traffic.
3. OpenSIPS will report normal memory use, but host memory leaks.

**Expected behavior**
Expecting that host memory use will reach steady-state.

**OS/environment information**
 - Operating System: debian 10

**Comment by john08burke** [comment]
I am going to test out the below patch tonight, but I believe I found a couple missing openssl `BIO_free(...)` calls.  It seems to have fixed the leak in my initial testing.

[stir-shaken-leak.txt](https://github.com/OpenSIPS/opensips/files/6313965/stir-shaken-leak.txt)

**Comment by liviuchircu** [comment]
hey, @john08burke!  Since I already had the OpenSIPIt'01 STIR/SHAKEN setup available, I was able to do the following:

* confirm the memory leak in `stir_shaken_auth()`, due to the BIO struct
* confirm both of your fixes - I see no more issues after applying your patch
* check both `stir_shaken_verify()` and `$identity` as well - they both behaved nicely from the get-go, no leaks

Could you open up a Pull Request for `master` branch with your exact patch, so we can get it merged?  Alternatively, I could push it on your behalf -- just let me know!

**Comment by john08burke** [comment]
Hey @liviuchircu! My overnight tests came back clean as well.  Please just push it when you get a chance.  Thanks for the quick response and verification!
