### ISSUE TITLE
[BUG] HEP tracing not working when call terminated via dialog module

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2480]
**OpenSIPS version you are running**
```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 16:01:37 Apr 21 2021 with gcc 8
```

**Describe the bug**
HEP tracing fails when manually ending call via `dlg_end_dlg` mi command.  When the mi command is executed the following logs are reported and no tracing happens.  I am using the latest `3.1` branch.

```
Apr 21 17:47:52 [57] CRITICAL:tracer:proto2str: unsupported proto 0
Apr 21 17:47:52 [57] CRITICAL:tracer:proto2str: unsupported proto 0
Apr 21 17:47:52 [57] ERROR:tracer:pipport2su: bad protocol 
Apr 21 17:47:52 [57] ERROR:tracer:save_siptrace: Failed to duplicate with hep to <192.168.1.29:6061>
```
Here is a [minimal script](https://github.com/OpenSIPS/opensips/files/6352968/minimal.txt) that you can use to reproduce the issue.

**To Reproduce**
1. Start OpenSIPS with provided minimal script
2. Send one call
3. Terminate call via `dlg_end_dlg` command.
4. Observe logs citing tracer error

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `git latest 3.1 branch`

**Comment by john08burke** [comment]
Forgot to include in the original issue, but here are the debug logs:

[debug.log](https://github.com/OpenSIPS/opensips/files/6353069/debug.log)

**Comment by bogdan-iancu** [comment]
@john08burke , could you give a try to the latest 3.1 (latest git or night builds) to see if the problem is still there ? some fixes were done lately, maybe it is already fixed.

**Comment by john08burke** [comment]
Hey @bogdan-iancu, I just gave it a re-test and the issue is still present.

You can also reproduce the behavior by letting the dialog timeout:
```
modparam("dialog","default_timeout",10)
...
route {
    ...
    create_dialog("B");
    ...
}
```

Here is a minimal script with the dialog timeout: 
[minimal.txt](https://github.com/OpenSIPS/opensips/files/6857650/minimal.txt)

**Comment by bogdan-iancu** [comment]
@john08burke , could you confirm this report is still valid with the latest 3.1 code ?

**Comment by john08burke** [comment]
@bogdan-iancu, sorry for the delay I missed this. The issue is still reproducible on latest 3.1.

**Comment by bogdan-iancu** [comment]
hold your horses......
