### ISSUE TITLE
PKG memory is not freed

### ISSUE THREAD

**Issue by cicahrad** [OpenSIPS/opensips#2486]
**OpenSIPS version you are running**
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

and using this modules:
loadmodule "httpd.so"
loadmodule "signaling.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "rr.so"
loadmodule "maxfwd.so"
loadmodule "sipmsgops.so"
loadmodule "mi_fifo.so"
loadmodule "db_mysql.so"
loadmodule "avpops.so"
loadmodule "drouting.so"
loadmodule "acc.so"
loadmodule "dialog.so"
loadmodule "mi_http.so"
loadmodule "uac.so"
loadmodule "proto_udp.so"
loadmodule "rtpengine.so"
loadmodule "proto_hep.so"
loadmodule "tracer.so"
loadmodule "cfgutils.so"
loadmodule "topology_hiding.so"
loadmodule "textops.so"

**Describe the bug**
Running OpenSIPS private memory get increase day by day as traffic 
are passed. When is PKG is full I get this error:
ERROR:core:qm_malloc: not enough free pkg memory (17936 bytes left, need 536), please increase the "-M" command line paramete
and then my log is flooded by messages: ERROR:rtpengine:send_rtpe_command: error converting bencode to iovec
then I must restart OpenSIPS and all start from begining.

I did try change memory allocator from F_MALLOC to Q_MALLOC but i run same issue. Now I run Q_MALLOC_DBG and in dump I saw that increase memory use is in  msg_parser.c
opensips[3696]:    23896520 : 23336 x [parser/msg_parser.c: rewrite_ruri, line 1077]

I'm not sure if this can be configuration issue or bug.

**To Reproduce**
**Expected behavior**
Free PKG mememory
**Relevant System Logs**
Full PKG dump of process consumingthe most memmory:
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:  dumping summary of all alloc'ed. fragments:
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: ----------------------------------------------------
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: total_bytes | num_allocations x [file: func, line]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: ----------------------------------------------------
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:           8 : 1 x [script_var.c: set_var_value, line 101]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        2400 : 30 x [pvar.c: pv_add_extra, line 5207]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:           8 : 1 x [ut.c: parse_reply_codes, line 135]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          32 : 4 x [script_var.c: add_var, line 59]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:     1048576 : 1 x [io_wait.c: init_io_wait, line 568]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         304 : 1 x [dlg_vals.c: fetch_dlg_value, line 176]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 3 x [cfg.y: yyparse, line 508]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          96 : 3 x [socket_info.c: fix_socket_list, line 665]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          64 : 2 x [rr_cb.c: register_rrcb, line 57]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          72 : 1 x [transformations.c: tr_eval_nameaddr, line 2335]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        3648 : 4 x [parser/parse_from.c: parse_from_header, line 61]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         288 : 6 x [parser/parse_to.c: parse_to_param, line 287]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         432 : 28 x [map.c: map_get, line 155]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         192 : 3 x [cfg.y: mk_listen_id, line 2280]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1064 : 19 x [route_struct.c: mk_exp, line 53]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:     4194304 : 1 x [io_wait.c: init_io_wait, line 559]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:           8 : 1 x [pvar.c: pv_init_extra_list, line 5143]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:       19864 : 191 x [cfg.y: yyparse, line 1564]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         104 : 1 x [transformations.c: tr_parse_sparam, line 2649]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        2144 : 19 x [route.c: fix_actions, line 1329]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         320 : 2 x [re.c: subst_parser, line 300]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         192 : 4 x [script_var.c: add_var, line 52]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        8528 : 4 x [dbase.c: alloc_new_prepared_stmt, line 528]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          24 : 1 x [dlg_hash.c: state_changed_event_init, line 1024]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         104 : 2 x [sl_cb.c: register_slcb, line 61]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          32 : 1 x [map.c: map_create, line 84]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          80 : 2 x [pvar.c: new_pv_context, line 5282]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          32 : 1 x [transformations.c: tr_eval_uri, line 1002]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          80 : 3 x [socket_info.c: fix_socket_list, line 759]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          96 : 1 x [mi/mi_trace.c: try_load_trace_api, line 53]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 3 x [socket_info.c: new_sock_info, line 126]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:      110008 : 979 x [parser/contact/contact.c: parse_contacts, line 190]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 1 x [transformations.c: tr_eval_paramlist, line 2068]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1968 : 41 x [transformations.c: parse_transformation, line 2471]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 2 x [script_cb.c: insert_raw_processing_cb, line 220]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          40 : 1 x [ut.h: pkg_str_extend, line 914]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         256 : 4 x [mod_fix.c: fixup_regcomp, line 55]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:           8 : 1 x [drouting.c: dr_init, line 1718]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          32 : 1 x [transformations.c: tr_parse_sparam, line 2663]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:       87040 : 677 x [cfg.lex: addstr, line 786]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        9648 : 1 x [route.c: new_sroutes_holder, line 95]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         448 : 8 x [data_lump.c: del_lump, line 352]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         800 : 25 x [transformations.c: tr_parse_sparam, line 2687]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:     1572864 : 1 x [io_wait.c: init_io_wait, line 621]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:           8 : 1 x [rtpengine.c: connect_rtpengines, line 1478]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:       12264 : 219 x [route_struct.c: mk_elem, line 69]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         128 : 2 x [re.c: subst_parser, line 285]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          80 : 3 x [socket_info.c: fix_socket_list, line 614]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          96 : 2 x [flags.c: get_flag_id_by_name, line 202]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         104 : 1 x [my_con.c: db_mysql_new_connection, line 148]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         336 : 3 x [db/db.c: db_do_init, line 314]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         856 : 5 x [db/db.c: db_do_init, line 352]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         768 : 18 x [acc_extra.c: add_extra, line 155]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          72 : 3 x [cfg.y: yyparse, line 1295]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        4104 : 1 x [xlog.c: buf_init, line 124]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         864 : 3 x [socket_info.c: new_sock_info, line 119]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:       19616 : 152 x [pvar.c: pv_parse_format, line 4636]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          24 : 1 x [acc.c: init_acc_evi, line 1149]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:      140112 : 1 x [pvar.c: init_pvar_support, line 154]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         192 : 4 x [sr_module_deps.c: _alloc_module_dep, line 64]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         872 : 1 x [tracer.c: parse_siptrace_id, line 592]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         304 : 6 x [script_cb.c: add_callback, line 60]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         128 : 1 x [prefix_tree.c: init_prefix_tree, line 54]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          32 : 2 x [re.c: subst_parser, line 309]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          64 : 2 x [transformations.c: tr_parse_string, line 2886]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        5744 : 166 x [mod_fix.c: alloc_gp, line 72]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          64 : 2 x [dr_cb.c: register_dr_cb, line 116]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:    23896520 : 23336 x [parser/msg_parser.c: rewrite_ruri, line 1077]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          16 : 2 x [acc_logic.c: _do_acc_fixup, line 1151]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          24 : 1 x [acc.c: init_acc_evi, line 1142]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          72 : 1 x [db/db_id.c: new_db_id, line 272]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         168 : 3 x [parser/parse_param.c: parse_params, line 370]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         448 : 14 x [transformations.c: tr_parse_nparam, line 2609]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 1 x [ipc.c: ipc_register_handler, line 126]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1752 : 34 x [evi/evi_params.c: evi_param_create, line 43]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         152 : 1 x [../../ut.h: pkg_str_extend, line 914]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         912 : 1 x [transformations.c: tr_eval_nameaddr, line 2355]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:       94984 : 383 x [route_struct.c: mk_action, line 105]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1272 : 1 x [my_con.c: db_mysql_new_connection, line 157]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         224 : 3 x [context.c: register_context_destroy, line 66]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1672 : 28 x [map.c: map_get, line 144]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         184 : 2 x [context.c: context_alloc, line 119]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         368 : 9 x [sipmsgops.c: fixup_parse_hname, line 669]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         640 : 7 x [route.c: fix_expr, line 1047]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         160 : 1 x [acc_extra.c: add_tag, line 111]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:         152 : 7 x [sipmsgops.c: fixup_method, line 727]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          16 : 1 x [io_wait.c: init_io_wait, line 576]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          72 : 5 x [db/db_id.c: dupl_string, line 47]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1056 : 22 x [sr_module.c: register_module, line 151]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        1168 : 4 x [dbase.c: get_new_stmt_ctx, line 473]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          16 : 1 x [drouting.c: route2_carrier, line 3475]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:        5720 : 1 x [mi/mi.c: register_mi_cmd, line 155]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          96 : 2 x [cfg.y: yyparse, line 2125]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:          48 : 1 x [acc.c: init_acc_evi, line 1135]
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: ----------------------------------------------------
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]:  dumping free list stats :
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   2. fragments no.:     5, unused:     0#012#011#011 bucket size:        16 -        16 (first        16)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   3. fragments no.:    10, unused:     0#012#011#011 bucket size:        24 -        24 (first        24)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   6. fragments no.:   137, unused:     0#012#011#011 bucket size:        48 -        48 (first        48)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   7. fragments no.:    12, unused:     0#012#011#011 bucket size:        56 -        56 (first        56)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   8. fragments no.:     2, unused:     0#012#011#011 bucket size:        64 -        64 (first        64)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=   9. fragments no.:    35, unused:     0#012#011#011 bucket size:        72 -        72 (first        72)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  10. fragments no.:     2, unused:     0#012#011#011 bucket size:        80 -        80 (first        80)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  11. fragments no.:    12, unused:     0#012#011#011 bucket size:        88 -        88 (first        88)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  24. fragments no.:     1, unused:     0#012#011#011 bucket size:       192 -       192 (first       192)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  30. fragments no.:     3, unused:     0#012#011#011 bucket size:       240 -       240 (first       240)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  42. fragments no.:     1, unused:     0#012#011#011 bucket size:       336 -       336 (first       336)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash=  90. fragments no.:     2, unused:     0#012#011#011 bucket size:       720 -       720 (first       720)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash= 114. fragments no.:     4, unused:     0#012#011#011 bucket size:       912 -       912 (first       912)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash= 128. fragments no.:     1, unused:     0#012#011#011 bucket size:      1024 -      1024 (first      1024)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash= 307. fragments no.:     1, unused:     0#012#011#011 bucket size:      2456 -      2456 (first      2456)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: hash= 2059. fragments no.:     1, unused:     0#012#011#011 bucket size:  16777216 -  33554432 (first  18356544)
Apr 26 07:58:56 voip-gw3 /usr/sbin/opensips[3696]: -----------------------------

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: debs
 - other relevant information:

**Additional context**
I include grafana graph of PKG memory
![opensips_pkg](https://user-images.githubusercontent.com/47259797/116037235-1986b400-a668-11eb-84a8-a43c84f87f92.png)

**Comment by liviuchircu** [comment]
Hey, @cicahrad!  You did the right steps - unless you have some accumulating transactions issue (e.g. make sure to also check that this statistic doesn't keep on growing: `opensips-cli -x mi get_statistics inuse_transactions`), then we are dealing with a PKG memleak.

If so, could you share your `opensips.cfg` or a minimal version of it here or to "liviu at opensips dot org"?  Basically, it's important to understand how you're invoking `sethost()`, `sethostport()`, `setuser()`, `setuserpass()`, `setport()`, `prefix()`, `strip()` or `strip_tail()`.  All of these functions use the same, lower-level `rewrite_uri()` function which seems to be correct, so the leak must be somewhere in the upper layers of the code.

**Comment by cicahrad** [comment]
Hey @liviuchircu,
 inuse transactions are dynamically

 changing up and down see attached graph. Configuration file is also attache.

Thank you

![opensips_inuse](https://user-images.githubusercontent.com/47259797/116091709-65a41980-a6a5-11eb-8489-b2b7e5774d4d.png)

[opensips.cfg.txt](https://github.com/OpenSIPS/opensips/files/6377467/opensips.cfg.txt)

**Comment by cicahrad** [comment]
Just came to my mind: I have two more server whit OpenSIPS.  And i did upgrade them from version 2.x to 3.1 and also i replace RTP Proxy to RTP Engine and after this update i have similar problem, but they don't happen often because RTP Engine is used only in few call by day. But on sever where i did report problem, RTP Engine is used on every call. So maybe problem can be in RTP Engine module when modificate of SDP. But i can be completly wrong.

**Comment by liviuchircu** [comment]
The `branch_route` PKG memory leak strikes again, it seems :) This bug was already fixed [here](https://github.com/OpenSIPS/opensips/commit/97c6bc78a34ed7ff47ea993b8bf843f700428cc5), in January.  Please stay tuned for the upcoming `3.1.2` release, announced for May 6th, which will include this fix.

Alternatively, use the "nightly" 3.1 packages, or just build directly from the `3.1` git branch.  Cheers!

**Comment by cicahrad** [comment]
I update to nightly and memory leak is gone. Thank you for helping me!
