### ISSUE TITLE
Make runtime errors include config line number

### ISSUE THREAD

**Issue by kingsleytart** [OpenSIPS/opensips#2492]
**Is your feature request related to a problem? Please describe.**

Sometimes it is not obvious where in a long opensips.cfg file a runtime error occurs, eg:

Apr 28 15:20:18 proxy-b /usr/sbin/opensips[12735]: ERROR:core:get_cmd_fixups: Variable in param [2] is not a string
Apr 28 15:20:18 proxy-b /usr/sbin/opensips[12735]: ERROR:core:do_action: Failed to get fixups for command <dp_translate>

**Describe the solution you'd like**

Runtime errors to show the config file line number which generated the error. If this is not possible, show the name of the route function where the error occurred.

**Implementation**
  - Component: `core`

**Describe alternatives you've considered**

I've used script_trace() but the output was very verbose so it did not really help. Eventually I resorted to using xlog() in strategic places in order to home in on the cause of the error. But ... these actions require a restart of OpenSIPS; this is OK in a dev environment but not so good in a live one.

**Additional context**

Nothing relevant to add.

**Comment by liviuchircu** [comment]
Thanks for the report, @kingsleytart - I agree that the user experience is not very friendly around those runtime fixup errors.  I've just pushed a fix for this on `master` branch.  Are you able to try it on your `3.1` setup and see if it gets the job done in your case as well?  Once all is good, I would backport it to `3.1` as well, since it looks to be a significant improvement.

**Comment by kingsleytart** [comment]
Hi,

Thanks - that was quick!

I'm not sure how easily I can do that as I didn't compile from source.
I set it up on a debian buster server by doing "apt-get install
opensips".

I could try setting up another machine and compiling from source if
that helps? Though I have to admit it's not something I do very often.
Is there a URL I can git clone the source from, including your patch?

Cheers,
Kingsley.

**Comment by liviuchircu** [comment]
This should suffice:

```
# clone "3.1" branch
git clone https://github.com/OpenSIPS/opensips.git -b 3.1 opensips-3.1

# cherry-pick the fix into your 3.1 branch
cd opensips-3.1
git cherry-pick -x 78dd040af361c3

# build and install to /usr/local
make -j && sudo make install

# in your opensips.cfg, change the 'mpath' to /usr/local/lib64/opensips/modules
```

**Comment by kingsleytart** [comment]
Thanks. I will see whether I can do that. My employer is keeping me quite busy on this. Will let you know how I get on.

**Comment by liviuchircu** [comment]
Hey, @kingsleytart!  Since tomorrow is release day, I will backport a _safer_ version of this patch to 3.1 (so only the file + line number get printed) and will close this issue.  Cheers!

**Comment by liviuchircu** [comment]
Also, by this point, the commit is already backported.  So just pull latest code with a `git pull --rebase` on your `3.1` branch or just install the `3.1.2` release!

**Comment by kingsleytart** [comment]
By the way, I just did an update on my debian box and this upgraded the opensips core and a couple of modules. I don't know whether this includes your fix?

```
# opensips -V
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

The reason I ask is because I'm now seeing config file and line numbers in some (but not all) runtime error messages where they had not been there before, which is a definite improvement. The new bits are on the "Failed to get fixups" error. Those errors didn't give me a file and line number before:

```
/usr/sbin/opensips[21116]: ERROR:core:eval_elem: Invalid operator : 6 
/usr/sbin/opensips[21116]: WARNING:core:do_assign: no value in right expression at /etc/opensips/opensips.cfg:627
/usr/sbin/opensips[21116]: ERROR:core:get_cmd_fixups: Variable in param [1] is not a string
/usr/sbin/opensips[21116]: ERROR:core:do_action: Failed to get fixups for command <is_present_hf> in /etc/opensips/opensips.cfg, line 619
```


It doesn't bother me but the format differs to the line number in the above warning though, ie "/etc/opensips/opensips.cfg, line 619" instead of "/etc/opensips/opensips.cfg:619".

**Comment by kingsleytart** [comment]
You must have sent your message while I was typing mine :)
