### ISSUE TITLE
[CRASH] b2b_logic: segfault

### ISSUE THREAD

**Issue by denyspozniak** [OpenSIPS/opensips#2494]
**OpenSIPS version you are running**

```
[root]# opensips -V
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6703ab5
main.c compiled on 18:11:08 Apr 29 2021 with gcc 4.8.5
```

**Crash Core Dump**

[syslog_gdb.txt](https://github.com/OpenSIPS/opensips/files/6401620/syslog_gdb.txt)
[opensips_cfg.txt](https://github.com/OpenSIPS/opensips/files/6401626/opensips_cfg.txt)

**Describe the traffic that generated the bug**

```
I'm trying to figure out how the b2b_logic module works. The goal is to build a simple sbc.
As far as I understand, this script should re-send the SIP INVITE back to the originator.
```

**OS/environment information**
 - Operating System:  `CentOS Linux release 7.8.2003 (Core)`
 - OpenSIPS installation: `Compiled from master`

**Comment by rvlad-patrascu** [comment]
Hi @denyspozniak ,

This crash has been fixed in debf908, please pull the latest sources and try again.
