### ISSUE TITLE
[BUG] dr_reload not noticing change of partition definition

### ISSUE THREAD

**Issue by kingsleytart** [OpenSIPS/opensips#2526]
**OpenSIPS version you are running**

```
version: opensips 3.1.2 (x86_64/linux)                                                                                                         
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT                                     
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**
I changed the name of `drd_table`, `drg_table` and `drc` table in the `dr_partitions` table and then ran `opensips-cli -x mi dr_reload` but saw the following error in the opensips log:

`WARNING:drouting:parse_destination_list: destination ID <gw1> was not found`

But after restarting OpenSIPS, calling the same dr_reload command does not give the error.

**To Reproduce**

1. create a gateway called gw1 in `dr_gateways`
2. run the following SQL:

```
CREATE TABLE x_dr_custom_carriers LIKE dr_carriers;
CREATE TABLE x_dr_custom_gateways LIKE dr_gateways;
CREATE TABLE x_dr_custom_groups LIKE dr_groups;
CREATE TABLE x_dr_custom_rules LIKE dr_rules;
INSERT INTO  dr_partitions SET
  partition_name='custom',
  db_url='mysql://opensips:YOURPASSWORD@localhost/opensips',
  drd_table='x_dr_custom_gateways',
  drr_table='x_dr_custom_rules',
  drg_table='x_dr_custom_groups',
  drc_table='x_dr_custom_carriers',
  ruri_avp=NULL,
  gw_id_avp=NULL,
  gw_priprefix_avp=NULL,
  gw_sock_avp=NULL,
  rule_id_avp=NULL,
  rule_prefix_avp=NULL,
  carrier_id_avp=NULL;
INSERT INTO version (table_name,table_version) SELECT 'x_dr_custom_gateways',table_version FROM version WHERE table_name='dr_gateways';
INSERT INTO version (table_name,table_version) SELECT 'x_dr_custom_rules',table_version FROM version WHERE table_name='dr_rules';
INSERT INTO version (table_name,table_version) SELECT 'x_dr_custom_groups',table_version FROM version WHERE table_name='dr_groups';
INSERT INTO version (table_name,table_version) SELECT 'x_dr_custom_carriers',table_version FROM version WHERE table_name='dr_carriers';
```

Insert a rule into x_dr_custom_rules specifying gw1, eg by doing

`INSERT INTO x_dr_custom_rules SET groupid=1,prefix='441234567890',priority=1,gwlist='gw1',description='gw1 test number';`

but don't create any records in the other x_custom_* tables.

Ensure the following is in opensips.cfg:
```
modparam("drouting", "use_partitions", 1)
modparam("drouting", "db_partitions_url", "mysql://opensips:YOURPASSWORD@localhost/opensips")
modparam("drouting", "db_partitions_table", "dr_partitions")
```

Restart opensips.

Realise I only wanted separate partitions for rules but wanted all partitions to use the same gateways, so ran this SQL to change the table names in the "custom" partition:

` UPDATE dr_partitions SET drd_table='dr_gateways',drg_table='dr_groups',drc_table='dr_carriers' WHERE id=2;`

then run `opensips-cli -x mi dr_reload` and observe error in opensips.log.

Restart OpenSIPS.

run `opensips-cli -x mi dr_reload` and observe error is no longer written to opensips.log.

**Expected behavior**

The drouting module to reload without that error.

**Relevant System Logs**

```
May 17 15:25:22 bt-ipx-proxy-b /usr/sbin/opensips[31956]: INFO:drouting:dr_reload_cmd: dr_reload MI command received!
May 17 15:25:22 bt-ipx-proxy-b /usr/sbin/opensips[31956]: INFO:drouting:dr_reload_data_head: loading drouting data!
May 17 15:25:22 bt-ipx-proxy-b /usr/sbin/opensips[31956]: INFO:drouting:dr_reload_data_head: loading drouting data!
May 17 15:25:22 bt-ipx-proxy-b /usr/sbin/opensips[31956]: WARNING:drouting:parse_destination_list: destination ID <gw1> was not found
```

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `debs`
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@kingsleytart , maybe the docs are not 100% clear, but the partition table is not reload-able. So, this is not a bug.
