### ISSUE TITLE
[FEATURE] prometheus: add ability to provide custom stats in addition to the default ones

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#2527]
In addition to the default stats provided by OpenSIPS, custom stats can be defined inside the config. In order to expose custom stats from the config, the prometheus module should export some functionality for defining and exporting these custom stats.

At least a gauge metric should be implemented in the first step.

We could impose that a gauge metric is predefined as a module parameter along with it's labels, so when the gauge metric is exported from the config via a function, we know exactly how it should look. Gauge metrics could be dynamically created leading to more flexible, not sure if it's really necessary.

Example of gauge metric definition:
`modparam("prometheus", "gauge_name", "[gauge_name] [gauge_list_labels_definition]"`

Example for exporting a gauge metric:
`prometheus_gauge_set("[gauge_name]", "gauge_value", "[gauge_list_labels_set]")`
or
`prometheus_gauge_set("[gauge_name] [gauge_list_labels_set]", "gauge_value")`

The number of elements in the gauge_list_labels_definition must match the number of elements in the gauge_list_labels_set.
The order of elements in the gauge_list_labels_definition must match the order of elements in the gauge_list_labels_set.
This will allow for strict label checking when exporting a gauge.

More info about prometheus metrics:
[https://prometheus.io/docs/concepts/metric_types/](url)

**Comment by razvancrainea** [comment]
So currently one can define custom variables using the `variable` [parameter](https://opensips.org/docs/modules/3.2.x/statistics.html#param_variable) in the statistics module, and if you set the `no_reset` flag, it will turn then into `gauge` stats.
So I guess the only remaining thing would be to be able to add custom labels to these, right?

**Comment by ovidiusas** [comment]
Yup, that would work!

**Comment by razvancrainea** [comment]
I've just added the `labels` parameter, which has a different behavior, but can be used to provide custom labels to statistics starting from their name.
