### ISSUE TITLE
[BUG] MariaDB schema creation sets wrong data type for dr_rules.groupid

### ISSUE THREAD

**Issue by kingsleytart** [OpenSIPS/opensips#2528]
**OpenSIPS version you are running**

Running 3.1.2 now but I noticed this with 3.1. I've since upgraded it with apt-get so I don't have the original version data any more.

```
```

**Describe the bug**

The dynamic routing module's do_routing() function expects an INT as the groupid but the DB has been created with the associated DB field (dr_rules.groupid) as a char(255). Whilst this is harmless, it's misleading.

I used the tool that came with OpenSIPS to create the DB structures, so this is what needs to be changed (if it hasn't already been fixed in 3.1.2).

**Comment by kingsleytart** [comment]
Adding to this, if I change the datatype of the DB field to an INT, then OpenSIPS complains and refuses to start. But if I pass a string into the do_routing() function's groupid parameter, OpenSIPS complains about that too.

So, for now I have reduced the size of the groupid field in the DB to 10 chars, as I need to use it as a DB foreign key, so having it as CHAR(255) was not sensible.

**Comment by bogdan-iancu** [comment]
@kingsleytart , things are right, no issue here. The group ID is indeed an integer (and accepted as interger by the do_routing() function), but in dr_rules, the groupid fields is actually holding a list (comma separated) of group IDs - a rule may be part of multiple groups in the same time. This is why the field in varchar.

**Comment by kingsleytart** [comment]
Oh OK, that makes sense, thanks.
