### ISSUE TITLE
Agent 'in call' state (call center scenario)

### ISSUE THREAD

**Issue by korithi** [OpenSIPS/opensips#2530]
Hi guys,

version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

I am using opensips as a call center scenario and set up some queues in it.
I do have noticed a problem when calls are failing reaching the agents or calls are missing Bye messages due to communication issues for example.
The state of that agent in such case stays 'in call'. I know that the status is related to the data in the table cc_calls, and in such case the call I am talking about is still in the db table. If I delete this record and restart opensips the state of the agent becomes 'free'.

Now my question is, how can I avoid having unavailable agents and without restarting opensips and cleaning data from the db?
Sometimes communication issues might happen and I could end up having a lot of unavailable agents.

Thank you!

**Comment by korithi** [comment]
Hi guys,

Can you please help on this?

thanks,

**Comment by korithi** [comment]
Hi

I would appreciate a suggestion.

Thanks in advance,

**Comment by bogdan-iancu** [comment]
@korithi , I think this issue should be escalated to the B2B layer, to expose some new MI command to force, from within OpenSIPS side, the termination of a B2B leg or B2B session. I don't think this is something we can do at callcenter level

**Comment by korithi** [comment]
Hi @bogdan-iancu

Thank you for your feedback. Looking forward to have this feature in the B2B. It is important to have control over the hung calls.

Regards

**Comment by korithi** [comment]
Hi @bogdan-iancu 

Is there a work around I can manage these calls in b2b layer?
Restarting the opensips is not an option and in such case the call-center functionality it is impossible to use.

Thanks and regards,

**Comment by bogdan-iancu** [comment]
@rvlad-patrascu is to devel a the new MI cmd in b2b_logic for terminating the a whole B2B session from outside OpenSIPS

**Comment by prathibhacdac** [comment]
With opensips 3.5, I'm facing the same issue.
