### ISSUE TITLE
Mid registrar strange issue

### ISSUE THREAD

**Issue by dimebage** [OpenSIPS/opensips#2536]
Dear team ,
While testing mid_registrar module i faced an strange case , opensips receive Register packet from client A with username of 1000
then it forwards the register to our main registrar which is freeswitch if credential is correct freeswitch  sends 200 ok and mid registrar save the AOR so far it is ok But if another device sends the Register packet with the same username but wrong password the freeswitch rejects the register packet which is correct behavior as password is wrong , also opensips sends 403 back to client but mid_registrar  still saves the contact which is really wrong .
The working mode of module  is 2 which is AOR throttling.
This becomes a security issue as it should not save the contact  of the same user if the credential  is wrong .
We were not noticing the issue for sometimes because we were not limiting the number of contact  per user but after we limit it to 1 using C1F flag we notice that due to said issue  when wrong credential  is provided  mid_registrar delete the first contact which was authenticated correctly and replace it with contact of the same username which has sent wrong credential .
The client with wrong credential has also received 403 forbidden .
The opensips version is 3.1 and we are using default example of mid_registrar module .

> 
     # Check results
    route(checkresults);
    $avp(real_client_ip)=$si;
    $avp(extra_ct_params)=";real_ip="+$si;
    fix_nated_register();
    add_rcv_param();
    xlog("L_INFO", "INFO: Route decision: Forwarding this request to $avp(destino) with forced socket $avp(ifacesalida)");
    mid_registrar_save("location","c1f");
    switch ($retcode) {
        case 1:
            xlog("L_INFO", "INFO: Forwarding REGISTER to main registrar ($$ci=$ci)");
            $socket_out=$avp(ifacesalida);
            $ru = $avp(destino);
            #if (!ds_select_dst("1", "0") ) {
            #    xlog("L_NOTICE","Inside dispatcher for regs");
            #   send_reply("500","Unable to route");
            #   exit;
            #}
            t_on_reply("Check_Return_code_for_register");
            t_relay();
            break;
        case 2:
            xlog("L_INFO", "INFO: absorbing REGISTER! ($$ci=$ci)");
            break;
        default:
            xlog("L_ERR", "ERROR: failed to save registration! ($$ci=$ci)");
            exit;
    }
    exit;

Regards

**Comment by liviuchircu** [comment]
Hey @dimebage and thanks for the report!

I did some quick tests and this "store contact on 401 reply" condition did not reproduce on `3.1` or above.  Moreover, the mid-registrar has built-in code that will only save the contact during a reply if the status code is <= 300 (see [this code](https://github.com/OpenSIPS/opensips/blob/master/modules/mid_registrar/save.c#L1784)).  So please specify a way to reproduce this bug or try to update to latest `3.1` and see if the issue re-occurs.

So unless further updated, I will mark the report as _invalid_, to help everyone else following it.
