### ISSUE TITLE
[BUG] Parameter <rule_attrs_avp> not found in module <drouting> - can't set

### ISSUE THREAD

**Issue by MosinAnton** [OpenSIPS/opensips#2537]
**Describe the bug**
Can't set _rule_attrs_avp_ parameter (https://opensips.org/docs/modules/3.1.x/drouting.html#param_rule_attrs_avp)

**OpenSIPS version you are running**

```
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 539ab0b3a
main.c compiled on 04:56:19 May 13 2021 with gcc 4.8.5

```

**Comment by bogdan-iancu** [comment]
thanks @MosinAnton  for the report, it looked like a documentation error (some leftovers form older versions) - the `rule_attrs_avp` modparam does not exists for a long time, it was replaced by the `rule_attrs_pvar` parameter for the [`do_routing()`](https://opensips.org/docs/modules/3.1.x/drouting.html#func_do_routing) function
