### ISSUE TITLE
[BUG/FEATURE] 3.1 presence mi cmd: passive MUST NOT send NOTIFY on expiration, like mi nh_enable_ping 0

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2539]
3.1: in an active-passive setup, clustered and/or with shared DB, passive tries to send NOTIFYs for expired subs, this is wrong: passive machine is not supposed to send out stuff (does not even find the socket to send it out, btw, in a floating ip active/passive setup)

**Is your feature request related to a problem? Please describe.**

Huuuuuuuuuuuuuuuuuuuuuuge number of error messages in passive

**Describe the solution you'd like**

mi enable_presence 0

**Describe alternatives you've considered**

demote error messages to debug level

**Additional context**

<pre>

Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:printf_subs: #012#011[pres_uri]= sip:6596@acmeinc.cloud.itsp.com#012#011[to_user]= 6596#011[to_domain]= acmeinc.cloud.itsp.com#012#011[w_user]=
 6598#011[w_domain]= acmeinc.cloud.itsp.com#012#011[event]= dialog#012#011[status]= active#012#011[expires]= 1622750417#012#011[callid]= 3136323237303235303834383337-eytoqot3mqlx#011[local_cseq]=20#012#011[to_tag]= f84e-2dde4
122a39962247483d114be960a5f#011[from_tag]= 5nic7x21gs#012#011[contact]= sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j#011[record_route]=
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:update_db_subs: Found expired record
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:handle_expired_subs: send timeout NOTIFY's out
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:send_notify_request: enter: have_body=0 force_null=1 dialog info:
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:printf_subs: #012#011[pres_uri]= sip:6596@acmeinc.cloud.itsp.com#012#011[to_user]= 6596#011[to_domain]= acmeinc.cloud.itsp.com#012#011[w_user]=
 6598#011[w_domain]= acmeinc.cloud.itsp.com#012#011[event]= dialog#012#011[status]= terminated#012#011[expires]= 0#012#011[callid]= 3136323237303235303834383337-eytoqot3mqlx#011[local_cseq]=20#012#011[to_tag]= f84e-2dde4122a3
9962247483d114be960a5f#011[from_tag]= 5nic7x21gs#012#011[contact]= sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j#011[record_route]=
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:build_str_hdr: state = terminated
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:send_notify_request: headers:#012Event: dialog#015#012Contact: <sip:presence@194.153.76.13:5070>#015#012Subscription-State: terminated;reason=timeout#015#012
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:presence:build_dlg_t: CONTACT = sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:t_uac: next_hop=<sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:mk_proxy: doing DNS lookup...
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:t_uac: sending socket is 194.153.76.13
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:print_request_uri: sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:run_local_route: building sip_msg from buffer
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_msg: SIP Request:
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_msg:  method:  <NOTIFY>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_msg:  uri:     <sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_msg:  version: <SIP/2.0>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_via_param: found param type 232, <branch> = <z9hG4bK408a.b45cddd7.0>; state=16
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_via: end of header reached, state=5
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: via found, flags=ffffffffffffffff
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: this is the first via
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_to_param: tag=5nic7x21gs
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:_parse_to: end of header reached, state=29
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:_parse_to: display={}, ruri={sip:6598@acmeinc.cloud.itsp.com}
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:get_hdr_field: <To> [64]; uri=[sip:6598@acmeinc.cloud.itsp.com]
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:get_hdr_field: to body [<sip:6598@acmeinc.cloud.itsp.com>]
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:get_hdr_field: cseq <CSeq>: <21> <NOTIFY>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:get_hdr_field: content_length=0 
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:get_hdr_field: found end of header
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=78
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:pv_get_msg_body: no message body
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=ffffffffffffffff
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:pv_get_msg_body: no message body
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_to_param: tag=f84e-2dde4122a39962247483d114be960a5f
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:_parse_to: end of header reached, state=29
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:_parse_to: display={}, ruri={sip:6596@acmeinc.cloud.itsp.com}
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:parse_headers: flags=40
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tracer:sip_trace_instance: sip_trace called
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tracer:is_id_traced: trace=on dyn=off
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tracer:pipport2su: proto 17, host 194.153.76.13 , port 5070
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tracer:pipport2su: proto 17, host 194.153.76.13 , port 5070
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:proto_hep:add_hep_chunk: Chunk with (id=17; vendor=0) not found! Creating!
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:proto_hep:add_hep_chunk: Hep chunk with (id=17; vendor=0) successfully built!
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:core:mk_proxy: doing DNS lookup...
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:proto_hep:hep_udp_send: sendto(sock,0x7f3a5eb8a8c8,684,0,0x7f3a5e291560,16): Network is unreachable(101)
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:proto_hep:msg_send: send() to 127.0.0.1:9070 for proto hep_udp/8 failed
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:proto_hep:send_hep_message: Cannot send hep message!
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:tracer:send_trace_proto_duplicate: failed to forward message to destination!
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:tracer:save_siptrace: Failed to duplicate with hep to <127.0.0.1:9070>
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:core:proto_udp_send: sendto(sock,0x7f3a3e7b5280,538,0,0x7f3a3ebdbfb0,16): Network is unreachable(101) [79.55.86.17:44606]
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:tm:msg_send: send() to 79.55.86.17:44606 for proto udp/1 failed
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: ERROR:tm:t_uac: attempt to send to 'sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j' failed
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:set_timer: relative timeout is 500000
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:insert_timer_unsafe: [4]: 0x7f3a3ebdbfd8 (3001000000)
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: DBG:tm:insert_timer_unsafe: [0]: 0x7f3a3ebdc008 (3030)
Jun  3 12:01:55 proxy-02 /usr/sbin/opensips[9675]: INFO:presence:send_notify_request: NOTIFY sip:6598@acmeinc.cloud.itsp.com via sip:6598@79.55.86.17:44606;nat=yes;line=5kdp8o0j on behalf of sip:6596@acmeinc.cloud.itsp.com for event dialog, to_tag=f84e-2dde4122a39962247483d114be960a5f, cseq=21
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: DBG:tm:utimer_routine: timer routine:4,tl=0x7f3a3ebdbfd8 next=(nil), timeout=3001000000
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: DBG:tm:retransmission_handler: retransmission_handler : request resending (t=0x7f3a3ebdbdb8, NOTIFY si ... )
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: ERROR:core:proto_udp_send: sendto(sock,0x7f3a3e7b5280,538,0,0x7f3a3ebdbfb0,16): Network is unreachable(101) [79.55.86.17:44606]
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: ERROR:tm:msg_send: send() to 79.55.86.17:44606 for proto udp/1 failed
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: DBG:tm:set_timer: relative timeout is 1000000
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: DBG:tm:insert_timer_unsafe: [5]: 0x7f3a3ebdbfd8 (3002000000)
Jun  3 12:01:56 proxy-02 /usr/sbin/opensips[9678]: DBG:tm:retransmission_handler: retransmission_handler : done

etc etc etc...............................

</pre>

**Comment by gmaruzz** [comment]
attaching log pasted before: 
[caca.log](https://github.com/OpenSIPS/opensips/files/6594216/caca.log)

**Comment by bogdan-iancu** [comment]
Hey @gmaruzz , please post here all the settings you have for the `presence` module. Also, are you sure that the "backup" OpenSIPS instance has the sharing tag in "backup" state? and also, are you sure the subscription was tagged (when created) with that sharing tag  (as param of `handle_subscribe()`) ?

**Comment by gmaruzz** [comment]
the log caca.log I attached was taken with presence *NOT* clustered

I found that the problem is both with presence setup to be clustered (as in your question) *and also* with presence set to NOT be clustered, but other things (dialogs, usrloc, nathelper, etc) are shared, and active/passive uses same external DB. Yes, definitely passive is always in backup state (always checked) and sharing tag used when handle_subscribe

This is why I tried with presence NOT clustered, to see if something changes. Very little.

please see below the settings related to the already attached (presence NOT clustered) log (caca.log). (you can see commented the changes I made since when presence was clustered )

tomorrow I will attach a new log with presence clustered

<pre>
loadmodule "presence.so"
loadmodule "presence_xml.so"
loadmodule "presence_mwi.so"
loadmodule "presence_dialoginfo.so"
loadmodule "pua.so"
loadmodule "pua_dialoginfo.so"
#loadmodule "pua_usrloc.so"
loadmodule "xcap.so"
modparam("presence", "db_url", "postgres://database:password@127.0.0.1:6432/freeswitch")
#modparam("presence", "cluster_id", 1)
modparam("presence", "mix_dialog_presence", 1)
modparam("presence", "fallback2db", 0)
modparam("presence", "end_sub_on_timeout", 1)
modparam("presence", "clean_period", 100)
modparam("presence", "db_update_period", 100)
modparam("presence", "max_expires_publish", 3600)
modparam("presence", "max_expires_subscribe", 3600)
modparam("presence", "notify_offline_body", 1)
modparam("presence_xml","force_active",1)
modparam("pua", "db_url", "postgres://database:password@127.0.0.1:6432/freeswitch")
modparam("pua_dialoginfo","presence_server","sip:192.172.27.10:5060")
modparam("pua_dialoginfo", "publish_on_trying", 1)
modparam("pua", "min_expires", 120)
modparam("pua", "default_expires", 3600)
modparam("xcap", "db_url", "postgres://database:password@127.0.0.1:6432/freeswitch")
loadmodule "proto_bin.so"
loadmodule "clusterer.so"
modparam("clusterer", "db_mode", 1)
modparam("clusterer", "db_url", "postgres://database:password@127.0.0.1:6432/freeswitch")
modparam("clusterer", "seed_fallback_interval", 2)

                        #handle_subscribe(,"service");
                        handle_subscribe();


</pre>

**Comment by gmaruzz** [comment]
it was due to DB and not clustering
invalid/wrong
closing this
