### ISSUE TITLE
[BUG] tls_wolfssl: unable to verify certificates

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#2541]
**OpenSIPS version you are running**

```
version: opensips 3.2.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7168e1d8c
main.c compiled on 20:23:53 Jun  3 2021 with gcc 9

```

**Describe the bug**
Tested same config with `tls_openssl` and `tls_wolfssl`.
The openssl version is able to verify certs, while wolfssl fails to verify same certs.

**To Reproduce**
Establish a tls connection to an endpoint with a valid certificate using openssl, the swap openssl with wolfssl.

**OS/environment information**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by rvlad-patrascu** [comment]
Hi @ovidiusas,

Can you post some debug logs to see what is the actual verification error? Also, do you by any chance use x509 version 1 certificates? wolfssl is more strict than openssl in this regard and requires v3 certs.

**Comment by ovidiusas** [comment]
The issue was fixed for outgoing tls connections.
However, for incoming tls connections, the library is complaining about not receiving a certificate.
```
INFO:tls_wolfssl:_wolfssl_tls_accept: client did not present a TLS certificate
```

This works ok with openssl.
Also, the modparams for tls_mgm are set to 1 for `veryfy_cert` and `require_cert`.

**Comment by rvlad-patrascu** [comment]
Hi @ovidiusas ,

As I can't seem to reproduce this myself can you apply the following debugging patch, re-compile tls_wolfssl and post the logs related to accepting a connection ?
[wolfssl_accept_debug.patch.txt](https://github.com/OpenSIPS/opensips/files/6679309/wolfssl_accept_debug.patch.txt)

**Comment by rvlad-patrascu** [comment]
Hi @ovidiusas,

I don't think any changes in the latest 3.2 code could impact the certificate verification.
It looks like the connection is accepted and the peer is successfully verified though:
`INFO:tls_wolfssl:_wolfssl_tls_accept: New TLS connection from 52.114.14.70:4352 accepted`
`INFO:tls_wolfssl:_wolfssl_is_peer_verified: peer is successfully verified... done`.

You are probably trying to get some info about the peer certificate via the `$lts_` variables, which is not available when TLS  session tickets are used for the connection (wolfSSL does not cache the certificate).

I would conclude that this is a slight limitation when using wolfSSL but not a bug.

**Comment by ovidiusas** [comment]
Hi @rvlad-patrascu, you are right, the peer is verified.
Here are some additional info.

The first incoming tls connection looks ok and I am able to get $tls_ vars:
```
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: New TLS connection from 52.114.14.70:4152 accepted
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: new TLS connection from 52.114.14.70:4152 using ECDHE-RSA-AES256-GCM-SHA384
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: local socket: 182.70.116.150:5061
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:tls_dump_cert_info: tls_accept: client TLS certificate subject: /CN=sip.pstnhub.microsoft.com, issuer: /C=US/O=Microsoft Corporation/CN=Microsoft RSA TLS CA 01
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_update_fd: New fd is 90
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_update_fd: New fd is 90
Dec 14 04:08:05 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_read: 511 bytes read
```

On the second incoming connection, this is what I get (no $tls_ vars - see the missing INFO:tls_wolfssl:tls_dump_cert_info: tls_accept:):
```
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: New TLS connection from 52.114.14.70:4153 accepted
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: new TLS connection from 52.114.14.70:4153 using ECDHE-RSA-AES256-GCM-SHA384
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_accept: local socket: 182.70.116.150:5061
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_update_fd: New fd is 91
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_tls_update_fd: New fd is 91
Dec 14 04:08:44 voip2101 o[32495]: INFO:tls_wolfssl:_wolfssl_read: 512 bytes read
```

I assume that the second tls session was setup using a session ticket.
Is there a way to disable session tickets?
Or is there a way to correlate a new tls connection (established using a TLS session key) with the parent session (that was established without a session key)?

**Comment by bogdan-iancu** [comment]
OK, let's close , please take care of opening the feature request.

**Comment by ovidiusas** [comment]
Feature request #2736 was created.
