### ISSUE TITLE
[BUG] tls_wolfssl: warning about certificate directory during startup

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#2545]
**OpenSIPS version you are running**
Latest opensips 3.2.

**Describe the bug**
During init, wolfssl is complaining about:
```
WARNING:tls_wolfssl:load_ca_dir: unable to load ca directory '/etc/ssl/certs' (ret=0)
```

**To Reproduce**
Start opensips with ssl support:
 - set `ca_dir` modparam to `[domain]/etc/ssl/certs`

**Additional context**
```
$ ls -l /etc/ssl/
total 32
drwxr-xr-x 2 root root 16384 May  6 11:45 certs
-rw-r--r-- 1 root root 10909 Apr 20  2020 openssl.cnf
drwx------ 2 root root  4096 Apr 20  2020 private
```
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by rvlad-patrascu** [comment]
Hello @ovidiusas ,

I'm not able to reproduce this. Can you apply this debugging patch, re-compile tls_wolfssl and post the logs around opensips startup time ?
[wolfssl_cadir_debug.patch.txt](https://github.com/OpenSIPS/opensips/files/6679337/wolfssl_cadir_debug.patch.txt)

**Comment by ovidiusas** [comment]
It turns out that a few certs were expired in the `/etc/ssl/certs/` directory. Once I removed them, the warning was gone.
It seems that all the valid certs are loaded and the expired one are discarded. Maybe all that we need to do is to document this.
