### ISSUE TITLE
[BUG] --enable-aesni in WolfSSL, outbound msg client decrypt error.

### ISSUE THREAD

**Issue by WangHoi** [OpenSIPS/opensips#2547]
OS: centos7 x86_64 with cpu(intel-xeon) support AES-NI
Version: opensips 3.2 branch, wolfssl with --enable-aesni --enable-intelasm

See also:
https://github.com/OpenSIPS/opensips/issues/2546

Handshake and server decrypt passed.
Client decrypt will fail.

Re-produce:

openssl s_client -CAfile=cacert.pem -connect 192.168.6.51:5080

140454140679552:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:ssl/record/ssl3_record.c:676:

or 

sipp

**Comment by rvlad-patrascu** [comment]
Hi @WangHoi ,

Does this happen when using `F_MALLOC`, similarly to the other issue? If so, can you check the fix that @liviuchircu pushed ?
