### ISSUE TITLE
[FEATURE] - Raise an Event on WSS/WS disconection

### ISSUE THREAD

**Issue by kaduww** [OpenSIPS/opensips#2554]
**Is your feature request related to a problem? Please describe.**
It's not possible to "know" when the user closes the websocket client, such as browser tab.

This feature request is about raising an event when Opensips detects the websocket connection goes down.

As WS/WSS connections are not only used by registered users, it could have a bflag on usrloc module to identify what user have disconnected, if it's a registered user.

  - Component: proto_wss, proto_ws (could be usefull in proto_tcp and proto_tls too)
  - Type: module's parameter/event
  - Name: raise_event_on_disconection

**Describe alternatives you've considered**
Now I'm using the remove_on_timeout_bflag parameter from nathelper to identify the user who doesn't reply to SIP ping, but it takes much time to get it.

**Additional context**
Freeswitch implements it on mod_verto, when a verto client disconnects, a client_disconnect event is raised from mod_verto and we're able to take the action we need.

**Comment by bogdan-iancu** [comment]
Addressed by @vladpaiu via 55a67e3704131fc0c7ef1b751d327e5be946c3f7
