### ISSUE TITLE
[BUG] b2b_logic : bye not forwarded to B2B leg. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips#2555]
**OpenSIPS version you are running**

```
version: opensips 3.2.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cdf25709a
main.c compiled on 10:02:03 May 28 2021 with gcc 8

```

**Describe the bug**

When using b2b, when you make a call between 2 registered users and you hangup from the originator (the non B2B processed side) then the bye is not sent to the B2B'd leg; the module seems to think that the BYE is sent out but it is not.   Do note that the opposite  direction.  I attached a very simple config file and a syslog : in the syslog you will find 2 calls : the first one with hangup from b2b leg is working; the second with hangup from non B2B'd side eats up the bye 
[conf+syslog.zip](https://github.com/OpenSIPS/opensips/files/6677805/conf%2Bsyslog.zip)
does work. 
**To Reproduce**

- deploy the attached config file. 
- register 2 entities. 
- make a call between them
- hangup from originator
- The destinee's call will remain open. 
**Expected behavior**

**Relevant System Logs**

Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:core:comp_scriptvar: str 29: BYE
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_logic:b2bl_search_entity: Key [B2B.21.347.1624021144]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_logic:b2b_mark_todel: 0x7f52b89a5260
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_logic:_b2b_pass_request: Send request [BYE] to peer [B2B.422.941139.1624021144]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_entities:b2b_parse_key: hash_index = [422]  - local_index= [941139]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_entities:b2b_search_htable_next_dlg: entering with start=(nil), table=0x7f52b8958b08, hash=422, label=941139 
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_entities:b2b_search_htable_next_dlg: searching  callid 25[B2B.422.941139.1624021144]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_entities:b2b_search_htable_next_dlg: searching   totag 37[ef403cb27fdc40232b5fb2516f6156a7-cdb7]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: DBG:b2b_entities:b2b_search_htable_next_dlg: searching fromtag 8[ce3a6537]
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: ERROR:b2b_entities:b2b_send_request: Can not send request [BYE] for entity type [1] for dlg[0x7f52b89c8780]->[B2B.422.941139.1624021144] in terminated state
Jun 18 08:59:09 debian10opensips31 /data/opensips/sbin/opensips[4876]: 
**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@johandeclercqdemocon , is this report this valid with the latest 3.2 release ?
