### ISSUE TITLE
[CRASH] Opensips crashes in command codec_delete_re(".*")

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#2560]
**OpenSIPS version you are running**

```
version: opensips 3.0.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f54164f2d
main.c compiled on  with gcc 9
```

**Describe the traffic that generated the bug**

Problem SDP:
```
      v=0
      o=TEST 1585854646 1585854648 IN IP4 1.1.1.1}
      s=TEST
      c=IN IP4 1.1.1.1}
      t=0 0
      m=audio 29024 RTP/AVP 18 8 0 101
      a=fmtp:18 annexb=no
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-16
      a=silenceSupp:off - - - -
      a=ptime:20
      a=sendrecv
```
But looks like codec_delete_re(".*") crashes for any SDP.

**To Reproduce**

It is very easy to reproduce:
1. Start OpenSIPS
2. Start SIP traffic (SIPP for example). Must be enough simple scenario and 20-50 CPS.
3. Call command codec_delete_re(".*") for 200 ok responses.
4. Opensips will crahes under load.

**Relevant System Logs**

Opensips do not provide relevant logs.

**OS/environment information**
 - Operating System: Ubuntu 20.04.2 LTS

Could you check it please? Thank you!

**Comment by razvancrainea** [comment]
Unfortunately 3.0.5 is no longer supported, we strongly advise you to upgrade to one of the [supported versions](https://www.opensips.org/About/AvailableVersions) - there are high chances this is fixed there.
Closing this one, please re-open if one of the supported versions badly behave.

Best regards,
Răzvan
