### ISSUE TITLE
[BUG] sipmsg_validate fails for valid hostnames

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#2563]
**OpenSIPS version you are running**
```
version: opensips 3.2.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 07:39:46 Jul  1 2021 with gcc 8
```

**Describe the bug**
sipmsg_validate uses `check_hostname` function. In commit b03cb41a3155623ba15bbde582e46f1f55864f70 macro IS_ALPHANUM() was removed, but replaced with `_isxdigit` which has of course less characters to be considered valid.

**To Reproduce**
1. Start OpenSIPS
2. Use sipmsg_validate() for any SIP request containing any characters from `g` to `z` in domain name.
3. Function returns false

**Expected behavior**
names must be valid

**Relevant System Logs**
Jul  5 07:43:30 dev04 opensips[4667]: DBG:sipmsgops:check_hostname: invalid character in hostname: v[118]
Jul  5 07:43:30 dev04 opensips[4667]: DBG:sipmsgops:w_sip_validate: message does not comply with SIP RFC3261 : (invalid domain for 'To' header)

**OS/environment information**
 - Operating System: `CentOS Linux release 8.4.2105`
 - OpenSIPS installation: `git`

**Comment by vasilevalex** [comment]
Hi @liviuchircu, something different than `_isxdigit` should be used.

**Comment by liviuchircu** [comment]
Hey @vasilevalex, thanks for the catch... it seems I thought I saw a pattern and made the simplification, but I actually introduced a regression.  A fix is on its way!
