### ISSUE TITLE
[CRASH] OpenSIPS 3.1 - CGRateS Module

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2571]
Dear Team,

I just came accross this crash after making a test call through my dev system.

**OpenSIPS version you are running**

```
root@ip-10-100-0-21:~# /usr/local/opensips/sbin/opensips -V
version: opensips 3.1.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 51643e897
main.c compiled on 16:11:13 Jul  8 2021 with gcc 8
```

**Crash Core Dump**
https://pastebin.com/ZRg8GmLU

**Describe the traffic that generated the bug**
Just tried to make a regular test call after many hours of inactivity (it seems that Monday didn't start well ;-) )

**To Reproduce**
After restarting OpenSIPS and tried some calls again after that I didn't had any problems, It might need some time who knows. 
I will keep an eye on it and let you know.

**Relevant System Logs**
```
Jul 12 08:01:17 [3260] CRITICAL:core:sig_usr: segfault in process pid: 3260, id: 6
Jul 12 08:01:20 [3253] NOTICE:presence:destroy: destroy module ...
Thank you for running opensips
```

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git

thank you in advance for your support

Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Hi, Vasilios!

It looks like OpenSIPS got a CGRateS reply on a request it didn't ask for. Do you happen to have any logs for that call?
Nevertheless, I will add some checks to make sure next time it won't crash, but it would be interesting to understand what happenend.

Best regards,
Răzvan

**Comment by vtzan** [comment]
Hi @razvancrainea,

Thank you for your reply and the fix. I think this came up while testing a scenario with a load balancer in front of 2 CGRateS sessions instances having the same db as a backend. I did that only for testing as it doesn't seem to fit in this case. So maybe what happened is that a reply came back to opensips from the second instance while opensips had an open connection with the first one? I will close this for now and let you know if this happens again in a normal working way ;-) 

thank you very much for time on this case.

Best Regards
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Yes, that's very much likely what has happened. I've pushed a fix to prevent it from crashing, but, as you've probably already noticed, if you're going to use it like so, you'll probably have trouble on the active node, since it will miss the reply.
Thanks for the report and for the detailed explanation.

Cheers,
Răzvan Crainea
