### ISSUE TITLE
[BUG] is_registered does not seem to retrieve saved bflags

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#2573]
**OpenSIPS version you are running**

```
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6298c80
main.c compiled on 06:29:59 Jun 14 2021 with gcc 4.8.5
```

**Describe the bug**
On REGISTER I perform
```            
               setbflag("TESTFLAG");
               if (!save("location","rc1")){
```
On INVITE
```
       if (is_registered("location")) {
                xlog("L_NOTICE", "[$ci] , check flags:[$bf $mf]");
                t_on_branch("branchtest");   ### in branchtest I print the same $bf $mf.
                if(isbflagset("TESTFLAG")){
```

**To Reproduce**
Set a bflag on REGISTER.
Try to retrieve the BFlag on an INVITE via is_registered()
Then try to print the flags or do an isbflagset. This will give empty result.

**Expected behavior**
Expected is that I can use the isbflagset on the INVITE to check on flags i set during REGISTER.

**Relevant info**
is_registered confirmed matching.
$bf returns the flag data before save(location)
Flag is visible via ul_dump on the corresponding AOR/contact. on the Cflags row.

**OS/environment information**
Centos

**Comment by bogdan-iancu** [comment]
Hi @hydrosine , I don't think this is a bug, as there is no documentation or mentioning that the function should return the bflags.
As per readme:
`The function returns true if an AOR is registered, false otherwise. The function does not modify the message being process. `
So, the bflag are not suppose to be updated as that is a "change over the message".

IMO, the current behavior is correct.

**Comment by hydrosine** [comment]
Hi Bogdan,

I've mainly based this possibility on the flags documentation.
Possibly I interpreted it wrong.

To quote the 3.1 docs example: https://www.opensips.org/Documentation/Script-Flags-3-1

`   if (is_method("REGISTER")) {
      # the branch flags (including "NAT_BFLAG") will be saved into location
      save("location");
      exit;
   } else {
      # lookup will load the branch flag from location
      if (!lookup("location")) {
         sl_send_reply("404","Not Found");`

This example sketches the scenario I try to perform as well. Flags are saved on REGISTER via save() in location, and are retrieved on INVITE via the lookup.

**Comment by bogdan-iancu** [comment]
Hi @hydrosine , let's agree we disagree - I see noting in the mentioned docs that the `is_registered()` function may return the branch flags :)
On the other hand, I agree with your scenario, it make sense - so, I suggest to re-pack this report into rather a Feature Requests and move the discussion there, like if how the bflags should be returned if multiple contacts....
