### ISSUE TITLE
[BUG] auto-scaling failure

### ISSUE THREAD

**Issue by cc3283** [OpenSIPS/opensips#2575]
**OpenSIPS version you are running**

# /usr/sbin/opensips -V
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 229ec0793
main.c compiled on 19:29:24 Jan  8 2021 with gcc 9

```
```

**Describe the bug**

Hello,  
 
Ran across this in my syslogs, so far I have not been able to determine if it’s actually affecting calls as our service is not based on live calls.  Here is the full message:
 

Jul 16 08:25:49  opensips[553787]: CRITICAL:core:fork_dynamic_udp_process: cannot fork UDP process
Jul 16 08:25:49 opensips[553787]: ERROR:core:do_workers_auto_scaling: failed to fork new process for group 1 (current 5 procs)
Jul 16 08:37:26 opensips[553787]: CRITICAL:core:internal_fork: #012>>> no free process slot found while trying to fork again#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012

My profiling config:
 
auto_scaling_profile = PROFILE_A
     scale up to 30 on 30% for 4 cycles within 5
     scale down to 5 on 18% for 10 cycles
 
 a low percentage of these messages a day, about ~200 out of  ~5200000 Subscribe / Notify messages a day per site.  Seeing these at both sites.

**To Reproduce**

Cause undetermined, and unable to reproduce at will.   
**Expected behavior**

**Relevant System Logs**

Jul 16 08:25:49  opensips[553787]: CRITICAL:core:fork_dynamic_udp_process: cannot fork UDP process
Jul 16 08:25:49 opensips[553787]: ERROR:core:do_workers_auto_scaling: failed to fork new process for group 1 (current 5 procs)
Jul 16 08:37:26 opensips[553787]: CRITICAL:core:internal_fork: #012>>> no free process slot found while trying to fork again#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
 
 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by bogdan-iancu** [comment]
Hi @cc3283, what do you think is more acceptable for you : (a) I provide a small patch to trigger a stop + coredump when the BUG happens, so I can investigate the core file (I should have all the info I need there) or (b) I provide a patch to try to print (without crashing opensips) as much info as possible when the BUG happens (but we will be limited to the printed info, so multiple iterations may be required here) ?

**Comment by bogdan-iancu** [comment]
Hi @cc3283 , here is the patch:

```
diff --git a/pt.c b/pt.c
index 6af76a9f8..fe32fae9d 100644
--- a/pt.c
+++ b/pt.c
@@ -182,6 +182,7 @@ void set_proc_attrs( char *fmt, ...)
 
        /* for sure the process is running */
        pt[process_no].flags |= OSS_PROC_IS_RUNNING;
+       LM_NOTICE("AUTOSCALING: process %d is running now\n",process_no);
 }
 
 
@@ -203,6 +204,7 @@ void reset_process_slot( int p_id )
        pt[p_id].pg_filter = NULL;
        pt[p_id].desc[0] = 0;
        pt[p_id].flags = 0;
+       LM_NOTICE("AUTOSCALING: process %d not running anymore\n",p_id);
 
        pt[p_id].ipc_pipe[0] = pt[p_id].ipc_pipe[1] = -1;
        pt[p_id].ipc_sync_pipe[0] = pt[p_id].ipc_sync_pipe[1] = -1;
@@ -247,7 +249,11 @@ int internal_fork(char *proc_desc, unsigned int flags,
        for( ; new_idx<counted_max_processes ; new_idx++)
                if ( (pt[new_idx].flags&OSS_PROC_IS_RUNNING)==0 ) break;
        if (new_idx==counted_max_processes) {
-               LM_BUG("no free process slot found while trying to fork again\n");
+               LM_BUG("no free process slot found while trying to fork again, "
+                       "all %d running\n",counted_max_processes);
+               for( new_idx=1 ; new_idx<counted_max_processes ; new_idx++)
+                       LM_NOTICE("AUTOSCALING: process %d, pid %d, type %d, desc <%s>, flags %d\n",
+                               new_idx, pt[new_idx].pid, pt[new_idx].type, pt[new_idx].desc, pt[new_idx].flags );
                return -1;
        }
 
@@ -281,6 +287,7 @@ int internal_fork(char *proc_desc, unsigned int flags,
 
        pt[new_idx].pid = 0;
        pt[new_idx].flags = OSS_PROC_IS_RUNNING;
+       LM_NOTICE("AUTOSCALING: process %d is set as running\n",new_idx);
 
        if ( (pid=fork())<0 ){
                LM_CRIT("cannot fork \"%s\" process (%d: %s)\n",proc_desc,
```

The logs specific to the issue are tagged with "AUTOSCALING" and printed on "NOTICE" level (so be sure you log level is at least 2. 
So, with the patch, get your opensips running and ideally try to preserve all the "AUTOSCALING" logs from the beginning to the point of the error/bug.
For any clarifications, just let me know.

**Comment by cc3283** [comment]
Not yet!

**Comment by cc3283** [comment]
Having an issue applying the patch, diff -u pt,c -i pt.patch

**Comment by cc3283** [comment]
Did not mean to close this issue, just applied the patch

**Comment by cc3283** [comment]
having an issue applying the patch:
$ patch -u pt.c -i pt.patch

patching file pt.c

Hunk #1 FAILED at 182.

Hunk #2 FAILED at 203.

Hunk #3 FAILED at 247.

Hunk #4 FAILED at 281.

4 out of 4 hunks FAILED -- saving rejects to file pt.c.rej

**Comment by cc3283** [comment]
HI Bogdan,

i'm running 3.1.1

**Comment by bogdan-iancu** [comment]
@cc3283 , do you have any update here ?

**Comment by cc3283** [comment]
Hi Bogdan,  No sorry, with the holidays here It got put on the back
burner.  I had left off unable to apply the patch. I will try and resume it
this week and get back to you.

Thanks,
Cory

**Comment by bogdan-iancu** [comment]
Hi @cc3283 , any chance to get to the bottom of this ?

**Comment by cc3283** [comment]
Hi Bogdan,
I've been pulled away from this for a while.  I will eventually get back to
the issue.  But wondering if at this point if we should close this and when
i get back to it i should start with an upgrade?

Thanks,
Cory

**Comment by ankogan** [comment]
I've got the same error for Timer process, opensips 3.2.9:

Apr  7 05:37:07 g5node1 /usr/sbin/opensips[60764]: NOTICE:core:do_workers_auto_scaling: score 2/3 -> forking new proc in group 3 (with 1 procs)
Apr  7 05:37:07 g5node1 /usr/sbin/opensips[60764]: CRITICAL:core:internal_fork: #012>>> no free process slot found while trying to fork again#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
Apr  7 05:37:07 g5node1 /usr/sbin/opensips[60764]: CRITICAL:core:fork_dynamic_timer_process: cannot fork Timer handler process
Apr  7 05:37:07 g5node1 /usr/sbin/opensips[60764]: ERROR:core:do_workers_auto_scaling: failed to fork new process for group 3 (current 1 procs)
Apr  7 05:37:08 g5node1 /usr/sbin/opensips[60764]: NOTICE:core:do_workers_auto_scaling: score 2/3 -> forking new proc in group 3 (with 1 procs)
Apr  7 05:37:08 g5node1 /usr/sbin/opensips[60764]: CRITICAL:core:internal_fork: #012>>> no free process slot found while trying to fork again#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
Apr  7 05:37:08 g5node1 /usr/sbin/opensips[60764]: CRITICAL:core:fork_dynamic_timer_process: cannot fork Timer handler process
Apr  7 05:37:08 g5node1 /usr/sbin/opensips[60764]: ERROR:core:do_workers_auto_scaling: failed to fork new process for group 3 (current 1 procs)

**Comment by ankogan** [comment]
Hello,
the same error happened, 3.2.17

**Comment by bogdan-iancu** [comment]
The 3.2 version is no longer maintain, I would advice to move to 3.4 and see if the issues still occurs.
