### ISSUE TITLE
opensips 3.1.3 + rtpengine mr9.2

### ISSUE THREAD

**Issue by wenyuanZZ** [OpenSIPS/opensips#2578]
https://github.com/sipwise/rtpengine/issues/1319

when I use rtpengine_offer()   rtpengine_answer() ,I want to use flag of ICE=optional .
But, opensips 3.1.3 log says:
ERROR:rtpengine:parse_flags: error processing flag `ICE' (value 'optional'): invalid value
How to solve it? which ver of opensips support this rtpengine flag?

**Comment by wenyuanZZ** [comment]
> [sipwise/rtpengine#1319](https://github.com/sipwise/rtpengine/issues/1319)
> 
> when I use rtpengine_offer() rtpengine_answer() ,I want to use flag of ICE=optional .
> But, opensips 3.1.3 log says:
> ERROR:rtpengine:parse_flags: error processing flag `ICE' (value 'optional'): invalid value
> How to solve it? which ver of opensips support this rtpengine flag?

who can answer me, plz.  ths, very much.

**Comment by razvancrainea** [comment]
This has been fixed in commit 4a90daeede6d33fe33a867d19b8fe2d11ece97d7. Please update to the latest OpenSIPS 3.1 version, either through `git` or `nightly` build.
