### ISSUE TITLE
[BUG]  opensips-3.2-release  user register errors

### ISSUE THREAD

**Issue by telegant** [OpenSIPS/opensips#2586]
env:
Debian 10 

install:
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 049AD65B
echo "deb https://apt.opensips.org buster 3.2-releases" >/etc/apt/sources.list.d/opensips.list
echo "deb https://apt.opensips.org buster cli-nightly" >/etc/apt/sources.list.d/opensips-cli.list

apt-get -y update -qq && apt-get -y install opensips opensips-cli
apt-get -y install opensips-mysql-module opensips-restclient-module

opensipscli -x user add 8001@cc.com 8001 

register error: 

ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now

opensips        | Jul 27 11:10:54 [27] DBG:core:get_hdr_field: cseq <CSeq>: <2> <REGISTER>
opensips        | Jul 27 11:10:54 [27] DBG:core:get_hdr_field: content_length=0
opensips        | Jul 27 11:10:54 [27] DBG:core:get_hdr_field: found end of header
opensips        | Jul 27 11:10:54 [27] DBG:core:receive_msg: After parse_msg...
opensips        | Jul 27 11:10:54 [27] DBG:core:receive_msg: preparing to run routing scripts...
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=ffffffffffffffff
opensips        | Jul 27 11:10:54 [27] DBG:maxfwd:is_maxfwd_present: value = 70 
opensips        | Jul 27 11:10:54 [27] DBG:sipmsgops:has_totag: no totag
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=78
opensips        | Jul 27 11:10:54 [27] DBG:tm:t_lookup_request: start searching: hash=3580, isACK=0
opensips        | Jul 27 11:10:54 [27] DBG:tm:matching_3261: RFC3261 transaction matching failed
opensips        | Jul 27 11:10:54 [27] DBG:tm:t_lookup_request: no transaction found
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=200
opensips        | Jul 27 11:10:54 [27] DBG:rr:find_first_route: No Route headers found
opensips        | Jul 27 11:10:54 [27] DBG:rr:loose_route: There is no Route HF
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=ffffffffffffffff
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=ffffffffffffffff
opensips        | Jul 27 11:10:54 [27] DBG:core:comp_scriptvar: int 20: 3600 / 0
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=ffffffffffffffff
opensips        | Jul 27 11:10:54 [27] DBG:auth:pre_auth: nonce index= 2
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: conn=0x7f8127dbdd98 (tail=140192696227256) MC=0x7f8127dbd650
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: new query=|select password,rpid from subscriber where username=? AND domain=?|
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:re_init_statement:  query  is <select password,rpid from subscriber where username=? AND domain=?>, ptr=(nil)
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:mysql_raise_event: MySQL status has not changed: connected
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: new statement(0x7f8127dbfa80) on connection: (0x7f8127dbdd98) 0x7f8127dbd5b8
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: set values for the statement run
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_val2bind: added val (0): len=4; type=254; is_null=0
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_val2bind: added val (1): len=6; type=254; is_null=0
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: doing BIND_PARAM in...
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:mysql_raise_event: MySQL status has not changed: connected
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: prepared statement has 2 columns in result
opensips        | Jul 27 11:10:54 [27] DBG:db_mysql:db_mysql_do_prepared_query: doing to BIND_PARAM out ...
opensips        | Jul 27 11:10:54 [27] DBG:core:db_new_result: allocate 48 bytes for result set at 0x7f8127dc0530
opensips        | Jul 27 11:10:54 [27] ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now
opensips        | Jul 27 11:10:54 [27] DBG:core:db_free_rows: freeing 0 rows
opensips        | Jul 27 11:10:54 [27] DBG:core:db_free_result: freeing result set at 0x7f8127dc0530
opensips        | Jul 27 11:10:54 [27] ERROR:auth_db:get_ha1: failed to query database
opensips        | Jul 27 11:10:54 [27] DBG:core:MD5StringArray: MD5 calculated: 8c790150b069244de2aac27c0907b114
opensips        | Jul 27 11:10:54 [27] DBG:core:parse_headers: flags=ffffffffffffffff

**Comment by liviuchircu** [comment]
Hi, @telegant!  A similar issue has been reported in #2593, and a fix is on the way.  Cheers!
