### ISSUE TITLE
how to collect statistic of Opensips

### ISSUE THREAD

**Issue by AnjanIpc** [OpenSIPS/opensips#2587]
**OpenSIPS version you are running**

```
version: opensips 2.4.4 (x86_64/linux)
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: Redhat linux
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**
I want opensips statistics. I am running below set up commands but not getting the value.
Please let me know, if the commands are OK or suggest if any other cmmands have to use to get teh statitics.

opensipsctl fifo get_statistics rcv_requests
opensipsctl fifo get_statistics rcv_replies
opensipsctl fifo get_statistics fwd_requests
opensipsctl fifo get_statistics fwd_replies
opensipsctl fifo get_statistics drop_requests
opensipsctl fifo get_statistics drop_replies
opensipsctl fifo get_statistics load-all
opensipsctl fifo get_statistics total_size
opensipsctl fifo get_statistics waiting_udp
opensipsctl fifo get_statistics waiting_tcp

Thanks,
Anjan

**Comment by AnjanIpc** [comment]
Can someone help me  with this ??

**Comment by razvancrainea** [comment]
In order for us to help you, you need to provide us as much information as you have: are there any errors in the logs? when running the commands, you're saying you're not getting the value - it would be **very** useful to know **what** you get. Also, the full output of `opensips -V` (as suggested in the template) would be very useful as well.
