### ISSUE TITLE
compiling sipmysql error

### ISSUE THREAD

**Issue by burne-muz** [OpenSIPS/opensips#2588]
when make install
make[1]: entering directory /home/admin/opensips-2.4.3/modules/lua
compiling sipapi.c
compiling siplua.c
compiling sipmysql.c
sipmysql.c:55:3: error: unknown type name 'my_bool'
    my_bool *is_null; /*param 'is null' array */
sipmysql.c: in function 'l_sipmysql_connect':
sipmysql.c:69:3: error: unknown type name 'my_bool'
    my_bool reconnect = 1;
infile included from sipmysql.c:27:0:
sipmysql.c:375:66: error: 'my_bool' undeclared (first use in this function)
     o_stmt->is_null = pkg_malloc(o_stmt->param_count * sizeof(my_bool));

make[1]: *** [sipmysql.o] error 1

opensips v2.4.3
mysql v8.0.24
CentOS 7.4.1708

**Comment by bogdan-iancu** [comment]
@burne-muz , the 2.4 version is no longer maintain. Please go for 3.1 or 3.2 versions.
