### ISSUE TITLE
Opensips as SBC for MS Teams

### ISSUE THREAD

**Issue by VoipTerminator1** [OpenSIPS/opensips#2589]
Hi 
I can see the TLS connection is being established with MS servers. But getting following error in logs where OS trying to send Options packets but during this it gets
DBG:proto_tls:proto_tls_send: no open tcp connection found, opening new one
Any help will be appreciated.

Here is full log
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_msg: SIP Request:
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_msg: method:
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_msg: uri: sip:sip2.pstnhub.microsoft.com
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_msg: version: <SIP/2.0>
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=ffffffffffffffff
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_via_param: found param type 232, = <z9hG4bKf04a.b90a2864.0>; state=16
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_via: end of header reached, state=5
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: via found, flags=ffffffffffffffff
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: this is the first via
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:_parse_to: end of header reached, state=9
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:_parse_to: display={}, ruri={sip:sip2.pstnhub.microsoft.com}
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:get_hdr_field: [32]; uri=[sip:sip2.pstnhub.microsoft.com]
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:get_hdr_field: to body [sip:sip2.pstnhub.microsoft.com#15#012]
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:get_hdr_field: cseq : <14>
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:get_hdr_field: content_length=0
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:get_hdr_field: found end of header
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=ffffffffffffffff
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=78
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=ffffffffffffffff
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG™️run_local_route: Change in local route -> rebuilding buffer
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=2000
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:parse_headers: flags=ffffffffffffffff
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:extract_ftc_hdrs: flags = 15
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:extract_ftc_hdrs: hdr 2 extracted as <To: sip:sip2.pstnhub.microsoft.com#15#012>
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:extract_ftc_hdrs: hdr 1 extracted as <From: sip:sbc.com;tag=18bc3d90336c8efb57e37a2b9b811e43-5dc8#15#012>
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:extract_ftc_hdrs: hdr 8 extracted as <Call-ID: 063fc45145f47e38-10076@104.248.14.215#15#012>
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:proto_tls:proto_tls_send: no open tcp connection found, opening new one
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:probe_max_sock_buff: getsockopt: snd is initially 16384
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:probe_max_sock_buff: using snd buffer of 416 kb
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:init_sock_keepalive: TCP keepalive enabled on socket 5
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:print_ip: tcpconn_new: new tcp connection to: 52.114.76.76
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:core:tcpconn_new: on port 5061, proto 3
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:proto_tls:tls_conn_init: Creating a whole new ssl connection
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:tls_mgm:tls_find_client_domain: found TLS client domain: sbc.expertflow.com
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:proto_tls:tls_conn_init: Setting in CONNECT mode (client)
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:proto_tls:proto_tls_send: sending via fd 5...
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10076]: DBG:proto_tls:tls_update_fd: New fd is 5
Aug 4 21:43:38 debian10-openSIP /usr/sbin/opensips[10079]: DBG:core:handle_worker: read response= 7f4c840245f8, 2, fd 98 from 11 (10076)

**Comment by bogdan-iancu** [comment]
Hi @VoipTerminator1 , this tracker is for reporting bugs and requesting features, it is not for asking help on how to use OpenSIPS - for such purposes please use the users mailing list here http://lists.opensips.org/cgi-bin/mailman/listinfo/users
