### ISSUE TITLE
[BUG]ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by masudmuborakshohi** [OpenSIPS/opensips#2593]
**OpenSIPS version you are running**

```
version: opensips 3.2.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 2c5c19627
main.c compiled on 16:59:16 Aug  6 2021 with gcc 8

```

**Describe the bug**

```
The application starts without errors and warnings, but when I try to register through the softphone, I get the following error in the logs:
   ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now
   ERROR:auth_db:get_ha1: failed to query database

```

**To Reproduce**

```
Steps to reproduce the behavior:
register
```

**Expected behavior**

```
normal registration.
```

**Relevant System Logs**
```
ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now
ERROR:auth_db:get_ha1: failed to query database
ERROR:db_mysql:db_mysql_store_result: driver error: Commands out of sync; you can't run this command now
ERROR:auth_db:get_ha1: failed to query database
```

**OS/environment information**
 - Operating System:  `Debian 10 buster`
 - OpenSIPS installation: `git`

**Additional context**
```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 72
Server version: 10.5.12-MariaDB-1:10.5.12+maria~buster mariadb.org binary distribution
```

**Comment by liviuchircu** [comment]
Hi, @masudmuborakshohi!  I managed to reproduce the issue, thanks for the info!  Aiming to push the fix soon, ideally before tomorrow's `3.2.1` minor release.

**Comment by liviuchircu** [comment]
As a preliminary conclusion, it looks like commit c0c49788a introduced a regression that is causing this.  More info to follow, the next step is to take a closer look at each change introduced...

**Comment by liviuchircu** [comment]
This should be fixed now on `3.2` git head.  Let me know if you run into other issues here, otherwise: happy hacking!

**Comment by masudmuborakshohi** [comment]
I installed a new minor release and I get this on startup:
root@debian:/usr/local/etc/opensips# systemctl status opensips
● opensips.service - LSB: Start the OpenSIPS SIP server
   Loaded: loaded (/etc/init.d/opensips; generated)
   Active: active (exited) since Tue 2021-08-17 15:55:38 +05; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15376 ExecStart=/etc/init.d/opensips start (code=exited, status=0/SUCCESS)

Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 13(15419) [TCP receiver] terminated, still waiting for 8 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 17(15426) [Timer handler] terminated, still waiting for 7 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 9(15411) [TCP receiver] terminated, still waiting for 6 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 18(15428) [TCP main] terminated, still waiting for 5 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 8(15409) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 4 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 4(15404) [timer] terminated, still waiting for 3 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 11(15416) [TCP receiver] terminated, still waiting for 2 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 16(15425) [TCP receiver] terminated, still waiting for 1 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:shutdown_opensips: process 7(15408) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 0 more
Aug 17 15:55:39 debian /usr/local/sbin/opensips[15395]: INFO:core:cleanup: cleanup

**Comment by liviuchircu** [comment]
Did you go for the `nightly` 3.2 repository or the `3.2-releases` one?  Because `nightly` is the only way you can obtain the fix via packages right now.  Otherwise, the `3.2.1` release is not yet there, it will be pushed today, so you can upgrade to it tomorrow.

**Comment by masudmuborakshohi** [comment]
Yes I used this command :)
git clone https://github.com/OpenSIPS/opensips.git -b 3.2 opensips-3.2
If it is stable then why did sockets stop listening to openips?
sudo netstat -tulpn | grep LISTEN  I check with this command, there is no openips.

**Comment by liviuchircu** [comment]
What errors are there before these shutdown logs?  OpenSIPS may abort startup due to various reasons...

**Comment by masudmuborakshohi** [comment]
The point is that there were no errors.

**Comment by liviuchircu** [comment]
This is just partial `systemd` output... please provide the entire suite of logs (from startup to shutdown) using your preferred technique (e.g. `journalctl -xe`, etc.)

**Comment by masudmuborakshohi** [comment]
Here you are [https://fex.net/ru/s/srzry8p](url)

**Comment by liviuchircu** [comment]
It appears your OpenSIPS is crashing during startup, see this sequence:

```
Aug 17 16:24:16 localhost /usr/local/sbin/opensips[16412]: NOTICE:drouting:dr_load_routing_info: loaded 1 gateways in partition 'Default'
Aug 17 16:24:16 localhost /usr/local/sbin/opensips[16412]: NOTICE:drouting:dr_load_routing_info: loaded 0 carriers in partition 'Default'
Aug 17 16:24:16 localhost /usr/local/sbin/opensips[16412]: NOTICE:drouting:dr_load_routing_info: loaded 1 rules in partition 'Default'
Aug 17 16:24:16 localhost /usr/local/sbin/opensips[16412]: CRITICAL:core:sig_usr: segfault in process pid: 16412, id: 5
```

Can you obtain a corefile and backtrace from process `16412`, for example?  See [this guide](https://www.opensips.org/Documentation/TroubleShooting-Crash) if you need help on how to generate it.  Thanks!

PS: I suggest you open a separate issue here, as this crash looks unrelated to the db_mysql issue.

**Comment by masudmuborakshohi** [comment]
Ok I'll try, thank you for your help and your time.

**Comment by telegant** [comment]
@masudmuborakshohi  it looks enable dynamic routing module

**Comment by masudmuborakshohi** [comment]
And how do I enable? 
####  DYNAMMIC ROUTING module
loadmodule "drouting.so"
modparam("drouting", "db_url",
        "mysql://opensips:opensipsrw@localhost/opensips") # CUSTOMIZE ME

**Comment by telegant** [comment]
@masudmuborakshohi  I also got the same error，disable the drouting module and try again

**Comment by masudmuborakshohi** [comment]
@telegant That's right, but what if I need this module?)

**Comment by liviuchircu** [comment]
Hi, @masudmuborakshohi!  There was, indeed, a crash in the "drouting" module, which is now fixed.  So please pull latest sources, rebuild and try again.  OpenSIPS should properly start now :-)

Cheers!

**Comment by masudmuborakshohi** [comment]
@liviuchircu Thank you very much, everything starts up. One request, please make sure that the opensips 3.2.1 branch does not give errors during installation from menuconfig, as it is now in the head branch.
