### ISSUE TITLE
[CRASH] OpenSIPs 3.1.4 latest Stable - dr_cluster_sync

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#2606]
**OpenSIPS version you are running**

```
version: opensips 3.1.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7

```

**Crash Core Dump**

https://pastebin.com/sHPeeuZb

**Describe the traffic that generated the bug**

**To Reproduce**

1. Start OpenSIPS
2. Check OpenSIPS crashed

**OS/environment information**
 - Operating System: Ubuntu 18.04.5 LTS
 - OpenSIPS installation: Debs Stable release

**Comment by liviuchircu** [comment]
Hi, @syedrizwansrs!  Indeed, a fixed for this regression was just pushed in 4b87fa2abfc9.  So on the hopes that you are using the `nightly` repo, please wait for tomorrow's packages, update again and the bug should be gone.

However, lots of people may be using the `3.1` and `3.2` minor release repos, so we may have to re-point the latest tags or make a new release, just to fix this issue.  Closing here for now.
