### ISSUE TITLE
[BUG] B2B impossible to modify SDP for replies

### ISSUE THREAD

**Issue by vasilevalex** [OpenSIPS/opensips#2607]
**OpenSIPS version you are running**
```
version: opensips 3.2.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 14:42:35 Aug 11 2021 with gcc 4.8.5
```

**Describe the bug**
If we use RTPEngine in B2B mode, we can modify SDP in local_route for outgoing requests. But `b2b_handle_reply` from `script_reply_route` does not use SDP from rtpengine_answer(). So SDP in outgoing replies always passed as it was received in original reply. Even if we call RTPEngine in `onreply_route` (which is executed before b2b reply route) and it returns modified SDP, it is still ignored and only original SDP is used.

**To Reproduce**
Example:
1. Start OpenSIPS with b2b_logic module and RTPEngine
2. Start traffic which requires SDP modification in both requests and replies
3. Check SDP in replies

**Expected behavior**
b2b_handle_reply() should use modified SDP returned by rtpengine_answer. Or b2b_handle_reply should allow to pass SDP as function parameter.

**OS/environment information**
 - Operating System: `CentOS Linux release 7.9.2009 (Core)`
 - OpenSIPS installation: `git`

**Comment by vasilevalex** [comment]
up

**Comment by vasilevalex** [comment]
up

**Comment by vasilevalex** [comment]
@rvlad-patrascu I will definitely try this. But it would be nice to have this working in this amazing module.

**Comment by bogdan-iancu** [comment]
@vasilevalex , please re-create this as a feature request
