### ISSUE TITLE
[BUG] Memory leak when querying sqlite module.

### ISSUE THREAD

**Issue by aniketkuwarvonage** [OpenSIPS/opensips#2608]
**OpenSIPS version you are running**

Version : 2.2.5 and 2.4.9

version: opensips 2.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 355a035b4
main.c compiled on 15:02:28 May 10 2021 with gcc 8

version: opensips 2.4.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a11653539

**Describe the bug**
OpenSIPS process leaks memory when running lb_reload [ load balancer ] or dr_load [ dynamic routing  command ] when reading from sqlite db.
Since the problem is in the sqlite module , leak could happen in other scenarios which are querying sqlite.

**To Reproduce**
Use sqlite db to store the load_balancer table.
Run lb_reload  openSIPS command in a loop or large number of times.

**Expected behavior**
OpenSIPS process should not leak memory.

**Relevant System Logs**
Running lb_reload in while loop for small time interval with DBG_MALLOC enabled and then restarting opensips prints below in logs :

14429056 : **652** x [res.c: db_sqlite_allocate_rows, line 275]

This indicates there are 652 allocations present in memory and not freed till opensips was restarted. They consumed close to 14MB of memory.

Here is data from server running opensips2.4.9 after 12 hour test :

185151352 : **230437** x [res.c: db_sqlite_allocate_rows, line 275]

There are 230437 entries and total leaked memory was 176 MB

**OS/environment information**
 - Operating System: Debian ( buster )
 - OpenSIPS installation: compiled version of an opensips fork with some patches back ported packages packaged in .deb files and installed as binary.

**Suggested solution and Open Questions**
Would below change be right way to address the issue :
https://github.com/Vonage/h2o-opensips/compare/feature/upgrade_2.4.9...Vonage:hotfix/sqlite_leak

If the result set is already present , free both rows and values.  Created a new function because we do not want to free the result structure itself (*_r ). New function is doing almost same thing as 
db_sqlite_free_result but we do not want to modify the connection in the new function. Also we do not want to free up the result structure.

Open Question :
Is it safe to assume that the result structure that comes in fetch query function of sqlite was always allocated using sqlite’s db_sqlite_allocate_rows and not db_allocate_rows

**Additional context**

**Root Cause :**

At high level , leak occurs when load balancer module queries sqlite interface to get the results. Lb module calls query function of sqlite DB interfaces.

Query function of sqlite allocates memory for rows and values by using db_sqlite_allocate_rows which allocates memory in two separate chunks :

```
   /* first allocate the rows */
   res->rows = (struct db_row*)pkg_malloc(rows * (sizeof(db_row_t)));

   /* and then the values */
   res->rows[0].values = pkg_malloc(rows * sizeof(db_val_t) * RES_COL_N(res));
```

After lb module gets the initial set of results , it then again calls the fetch query function of the sqlite module to see if there are more results are available

Fetch query function check if the result structure is previously allocated. If yes , it frees up the previously created rows and values.

This is when problem occurs , when memory is freed , sqlite calls generic  / core db free rows function :

```
   } else {
       /* free old rows */
       if(RES_ROWS(*_r)!=0)
           db_free_rows(*_r);
       RES_ROWS(*_r) = 0;
       RES_ROW_N(*_r) = 0;
   }

db free rows function frees memory allocated only for rows and NOT for values.

   if (RES_ROWS(_r)) {
       for(i = 0; i < RES_ROW_N(_r); i++)
           db_free_row(&(RES_ROWS(_r)[i]));
 
       LM_DBG("freeing rows at %p\n", RES_ROWS(_r));
       pkg_free(RES_ROWS(_r));
       RES_ROWS(_r) = NULL;
   }
```

**That causes a leak as rows[0].values are never freed.**

Generic db free function would work only for modules allocating memory using generic Db allocate function : 

```
int db_allocate_rows(db_res_t* _res, const unsigned int rows)
{
   unsigned int i;
 
   RES_ROWS(_res) = (struct db_row*)pkg_malloc
       (rows * (sizeof(db_row_t) + sizeof(db_val_t) * RES_COL_N(_res)) );
   if (!RES_ROWS(_res)) {
       LM_ERR("no memory left\n");
       return -1;
   }
```

Above function allocates memory for rows and columns altogether and hence generic db free function would work. But for sqlite since rows and values are allocated using separate calls to pkg_malloc , free function should take care of freeing those structures separately.

Load Balancer code analysis  : 
 
From load balancer code , we first call lb_dbf.query which will call db_sqlite_query
And then we call fetch_result which will call db_sqlite_fetch_result
Although we call free_result towards end of function..because 
Fetch_result already freed up rows as mentioned above free_result is essentially a no op.

```
int lb_db_load_data( struct lb_data *data)
{
 
   } else {
       if ( lb_dbf.query( lb_db_handle, 0, 0, 0, columns, 0, 5, 0, &res)<0) {
           LM_ERR("DB query failed\n");
           return -1;
       }
   }
 
   if (res == NULL || RES_ROW_N(res) == 0) {
       LM_WARN("table \"%.*s\" empty\n", lb_table_name.len,lb_table_name.s );
       return 0;
   }
 
   LM_DBG("%d records found in %.*s\n",
       RES_ROW_N(res), lb_table_name.len,lb_table_name.s );
   n = 0;
 
  
           /* add the destinaton definition in */
           if ( add_lb_dsturi( data, id, group, uri, resource, flags)<0 ) {
               LM_ERR("failed to add destination %d -> skipping\n",n);
               continue;
           }
           n++;
       }
       if (DB_CAPABILITY( lb_dbf, DB_CAP_FETCH)) {
           if(lb_dbf.fetch_result(lb_db_handle, &res, no_rows)<0) {
               LM_ERR( "fetching rows (1)\n");
               return -1;
           }
       } else {
           break;
       }
   } while(RES_ROW_N(res)>0);
 
   lb_dbf.free_result(lb_db_handle, res);
   res = 0;

```

**Comment by aniketkuwarvonage** [comment]
@bogdan-iancu , @liviuchircu , @razvancrainea : Hope you are doing good. Did anyone get a chance to look at this ticket. There is a suggested fix I came up with and worked during the testing.
https://github.com/Vonage/h2o-opensips/compare/feature/upgrade_2.4.9...Vonage:hotfix/sqlite_leak. 

Would appreciate your feedback.

Thanks in advance.

**Comment by aniketkuwarvonage** [comment]
@razvancrainea : Sure , I will create a PR

**Comment by aniketkuwarvonage** [comment]
@razvancrainea  : PR - https://github.com/OpenSIPS/opensips/pull/2654

Thanks

**Comment by aniketkuwarvonage** [comment]
@bogdan-iancu , @liviuchircu , @razvancrainea , Can you please take a look at the PR to fix this issue : https://github.com/OpenSIPS/opensips/pull/2654

**Comment by razvancrainea** [comment]
@aniketkuwarvonage thanks for the patch, it has been pushed in all branches.

**Comment by aniketkuwarvonage** [comment]
Thanks a lot @razvancrainea and @liviuchircu for reviewing the changes and merging.
