### ISSUE TITLE
opensips 3.1.3 can not load proto_tls.so

### ISSUE THREAD

**Issue by wenyuanZZ** [OpenSIPS/opensips#2621]
I have install openssl 1.1.1, and I make opensips 3.1.3 like:
make include_modules="db_mysql proto_tls"  prefix="/opt/opensips-3.1.3"  install
in opensips.cfg:
loadmodule "proto_tls.so"

When I run opensips,it failed. The log says:
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: WARNING:core:new_sock_info: number of workers per non UDP-based <10.101.29.1> listener not supported -> ignoring...
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:sr_load_module: could not open module </opt/opensips-3.1.3/lib64/opensips/modules/proto_tls.so>: /opt/opensips-3.1.3/lib64/opensips/modules/proto_tls.so: undefined symbol: SSL_SESSION_get_master_key
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:load_module: failed to load module
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: Traceback (last included file at the bottom):
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips:  0. /opt/opensips-3.1.3/etc/opensips/opensips.cfg
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.3/etc/opensips/opensips.cfg:138:13-14: failed to load module proto_tls.so#012
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: loadmodule "cachedb_local.so"
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: #loadmodule "cachedb_redis.so"
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: loadmodule "proto_tls.so"
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: ^~
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: 
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: ######################################################################
Sep  4 16:36:04 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:parse_opensips_cfg: bad config file (1 errors)
Is this a bug of opensips 3.1.3? Or I need which version of openssl?
Who can tell me, plz, ths.

**Comment by wenyuanZZ** [comment]
Even I update to opensips 3.1.5,it still fail. the log says:
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: WARNING:core:new_sock_info: number of workers per non UDP-based <10.101.29.1> listener not supported -> ignoring...
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:sr_load_module: could not open module </opt/opensips-3.1.5/lib64/opensips/modules/proto_tls.so>: /opt/opensips-3.1.5/lib64/opensips/modules/proto_tls.so: undefined symbol: SSL_SESSION_get_master_key
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:load_module: failed to load module
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: Traceback (last included file at the bottom):
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips:  0. /opt/opensips-3.1.5/etc/opensips/opensips.cfg
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.5/etc/opensips/opensips.cfg:138:13-14: failed to load module proto_tls.so#012
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: loadmodule "cachedb_local.so"
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: #loadmodule "cachedb_redis.so"
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: loadmodule "proto_tls.so"
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ^~
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: loadmodule "tls_mgm.so"
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: 
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:sr_load_module: could not open module </opt/opensips-3.1.5/lib64/opensips/modules/tls_mgm.so>: /opt/opensips-3.1.5/lib64/opensips/modules/tls_mgm.so: undefined symbol: OPENSSL_sk_num
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:load_module: failed to load module
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.5/etc/opensips/opensips.cfg:139:13-14: failed to load module tls_mgm.so#012
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:set_mod_param_regex: no module matching proto_tls found
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.5/etc/opensips/opensips.cfg:351:19-20: Parameter <tls_max_msg_chunks> not found in module <proto_tls> - can't set
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.5/etc/opensips/opensips.cfg:352:1-6: syntax error
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: CRITICAL:core:yyerror: parse error in /opt/opensips-3.1.5/etc/opensips/opensips.cfg:352:1-6: 
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:parse_opensips_cfg: bad config file (5 errors)
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: ERROR:core:main: failed to parse config file /opt/opensips-3.1.5/etc/opensips/opensips.cfg
Sep  5 00:44:31 vmeet-flexisip-dev-10-101-29-1 opensips: NOTICE:core:main: Exiting....

Can u help me, plz, ths to u liv.

**Comment by wenyuanZZ** [comment]
@liviuchircu

**Comment by rvlad-patrascu** [comment]
Hi @wenyuanZZ ,

Are you still having this issue? If so, it may be the case that you compiled opensips with an older version of openssl and updated openssl later. Or that the version of the installed openssl library does not match that of the development files (eg. `libssl` and `libssl-dev`).
