### ISSUE TITLE
[FEATURE] Fuzzer integration into OpenSips with OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [OpenSIPS/opensips#2625]
Hi! I am proposing to integrate fuzzing into OpenSIPS by way of OSS-Fuzz. OSS-Fuzz is a free service run by Google that enables fuzzing of important open source projects. The goal is to find reliability and security issues that may exist by writing fuzzers for OpenSIPS and then have OSS-Fuzz run the fuzzers continuously. 

We integrated Kamailio into OSS-Fuzz earlier this year  (see here for the initial integration https://github.com/google/oss-fuzz/pull/5279) and it has reaped nice results - so I thought it would make sense to also get OpenSIPS in as well. In this PR on the OSS-Fuzz repo https://github.com/google/oss-fuzz/pull/6420 I suggest an initial integration of OpenSIPS. I created two simple fuzzers targeting the parsing code which should give some initial results.

In order to integrate I only need one or more emails that will be receiving bug reports whenever bugs are found by the fuzzers. These emails should be affiliated with a Google account such that you can see the detailed reports (like stack traces and reproducing cases) on https://oss-fuzz.com 

At the moment I put the fuzzers in the OSS-Fuzz repository, but we can also move these upstream down the line if you are happy with getting fuzzing into OpenSIPS.

Let me know if you like the idea and would like to get integrated.

**Comment by liviuchircu** [comment]
Hey, @DavidKorczynski!  This sounds awesome, please enrol "liviu {at} opensips {dot} org" for any crash reports generated by the tool.  Let me know if you need any help with calling the parsing functions or any other info around the C project itself.

Mid/long-term, both myself and a few other core developers (Bogdan, Vlad & Răzvan) also like the idea of getting this automation merged into the OpenSIPS codebase, although it is not quite clear what the integration will look like (GH Actions?  some other tool?).

**Comment by DavidKorczynski** [comment]
Wonderful @liviuchircu - the project is now ready to get merged in on the OSS-Fuzz side and will update you when it finally gets merged in. 

Many of the fuzzers look a lot like unit-tests, so what we could do is place them in a location similar to tests. In Kamailio we put all of the fuzzers in a folder `mics/fuzz` and then include the build scripts in the OSS-Fuzz repositories. We can do something similar here? 

OSS-Fuzz will run the fuzzers continuously so in that sense it is not strictly needed to run the fuzzers by way of the CI, however, we can also set that up down the line.

**Comment by liviuchircu** [comment]
In OpenSIPS, unit tests are typically placed in a `test/` directory next to the `.c` file under test.  [This document](https://docs.google.com/document/d/151R7QPADGnzSxtj7FFADGBdbZjsApnkkumiVwl2GmtE/edit?usp=sharing) describes the convention in more detail.

Does OSS-Fuzz require a single directory as entry point to the project, or can it deal with multiple ones?  For example, if you were to fuzz the `parser/` and `cachedb/` codebases, then the fuzz code would be split in two: `parser/test/fuzz/` and `cachedb/test/fuzz/`.

If the above structure is not possible, we can alternatively throw all fuzz tests under `test/fuzz/`, to make OSS-Fuzz happy.

**Comment by liviuchircu** [comment]
Thanks!  I can confirm that both the access and the OSS-Fuzz integration work well.  Let me come back to you after reading through all the provided data.

**Comment by liviuchircu** [comment]
By my understanding, we should be done here, right @DavidKorczynski?

* all OpenSIPS fuzzers are available under `oss-fuzz/projects/opensips`.
* for any future changes on the OSS-Fuzz side (including new maintainers), just open up PRs to [google/oss-fuzz](https://github.com/google/oss-fuzz)

**Comment by DavidKorczynski** [comment]
You're right. Thanks @liviuchircu !
