### ISSUE TITLE
[FEATURE] Prometheus: custom label names and label values

### ISSUE THREAD

**Issue by cicahrad** [OpenSIPS/opensips#2629]
Hi,

it would be nice have option create own label name and values for prometheus exporter. Label name and value will be dynamically filled. This labels can be used later in grafana for grouping or selecting only part of metric and so on. 

exported metric will looks like: **opensips_METRIC_NAME{LABEL1="VALUE1" LABEL2="VALUE2" ... } VALUE**

and for updating command can looks like this: **update_stat("METRIC_NAME(LABEL1:$var(dynamic_val1),LABEL2:$var(dynamic_val2),..)", 1);** 

or in json

**$json(METRIC_NAME/LABEL1)=$var(dynamic_val1)
$json(METRIC_NAME/LABEL2)=$var(dynamic_val2)
.
$json(METRIC_NAME/LABELx)=$var(dynamic_valx)
update_stat("$json(METRIC_NAME)", 1);**

Thank you
Stepan

**Comment by razvancrainea** [comment]
I've just added the `labels` parameter, which has a different behavior, but can be used to provide custom labels to statistics starting from their name.
