### ISSUE TITLE
MSILO "no TLS client domain found" error

### ISSUE THREAD

**Issue by zjacky0992** [OpenSIPS/opensips#2630]
When m_dump() is called in "REGISTER":

            	if (m_dump()) {
                	xlog("MSILO: offline messages dumped - if they were");
            	}else{
                	xlog("MSILO: no offline messages dumped");
            	}; 
It can dump the message from the database but can't send the message. Here is the log:

Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_msg:  method:  <MESSAGE>
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_msg:  uri:     <sip:10000@xxx.com:5061;transport=tls>
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_msg:  version: <SIP/2.0>
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_headers: flags=ffffffffffffffff
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_via_param: found param type 232, <branch> = <z9hG4bKe0c6.787dad54.0>; state=16
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_via: end of header reached, state=5
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_headers: via found, flags=ffffffffffffffff
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_headers: this is the first via
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_to_param: transport=tls
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:_parse_to: end of header reached, state=29
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:_parse_to: display={}, ruri={sip:10000@xxx.com:5061}
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:get_hdr_field: <To> [50]; uri=[sip:10000@xxx.com:5061] 
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:get_hdr_field: to body [sip:10000@xxx.com:5061]
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:get_hdr_field: cseq <CSeq>: <10> <MESSAGE>
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:get_hdr_field: content_length=78
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:get_hdr_field: found end of header
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_headers: flags=ffffffffffffffff
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:parse_headers: flags=78
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:proto_tls:proto_tls_send: no open tcp connection found, opening new one
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:probe_max_sock_buff: getsockopt: snd is initially 16384
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:probe_max_sock_buff: using snd buffer of 416 kb
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:init_sock_keepalive: TCP keepalive enabled on socket 119
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:print_ip: tcpconn_new: new tcp connection to: 47.117.116.205
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:tcpconn_new: on port 5061, proto 3
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:proto_tls:tls_conn_init: Creating a whole new ssl connection
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:proto_tls:tls_conn_init: no TLS client domain found
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:core:tcp_conn_new: failed to do proto 3 specific init for conn 0x7f0559e116b8
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: DBG:core:tcpconn_destroy: destroying connection 0x7f0559e116b8, flags 0018
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:proto_tls:tls_sync_connect: tcp_conn_create failed, closing the socket
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:proto_tls:proto_tls_send: connect failed
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:tm:msg_send: send() to 142.107.16.203:5061 for proto tls/3 failed
Sep 18 17:29:55 sipserver /usr/sbin/opensips[9794]: ERROR:tm:t_uac: attempt to send to 'sip:10000@xxx.com:5061;transport=tls' failed

**Comment by bogdan-iancu** [comment]
This is not a bug, but a mis-usage / mis-configuration . Beside the topic is under discussion on the [mailing list](https://github.com/OpenSIPS/opensips/issues/2448), so let close here and continue over there.
