### ISSUE TITLE
opensips not responding

### ISSUE THREAD

**Issue by AnjanIpc** [OpenSIPS/opensips#2633]
**OpenSIPS version you are running**

version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a42226ccb
main.c compiled on 21:38:53 Apr 27 2021 with gcc 4.4.7

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
RHEL 6
 - other relevant information:

**Additional context**
i looked at the forum and it says the issue is already fixed with "**OpenSIPS v2.4.3 segfault - TCP worker crash**" but it is not saying, which version it is fixed.

Its bit urgent for me to know, in which version, it is fixed ?
Can someone pls answer to my query ASAP.

**Comment by AnjanIpc** [comment]
Can anyone let me know the fixed version of opensips please ?

**Comment by razvancrainea** [comment]
2.4.5
