### ISSUE TITLE
[CRASH] opensips 3.2.2 segfault with rtp_relay.so

### ISSUE THREAD

**Issue by Hyleoss** [OpenSIPS/opensips#2641]
**OpenSIPS version you are running**

version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

**Crash Core Dump**

https://pastebin.com/GdRPJtTm

**Describe the traffic that generated the bug**

Was making a test call with the new rtp_relay module, opensips seems to crash after relaying the first INVITE 
![image](https://user-images.githubusercontent.com/91903480/135885082-0130bf78-c7a7-4fd0-a37c-9e625e32f841.png)

Got no problem when disabling the rtp_relay module and only using rtpengine.

**To Reproduce**

1. Start OpenSIPS with rtp_relay module, here is how I use rtp_relay in main route.

```
if (is_method("INVITE")) {
                if ( !create_dialog("B") ) {
                        send_reply(500,"Internal Server Error");
                        exit;
                }
                do_accounting("db","cdr|missed");
                rtp_relay_engage("rtpengine");
}
```

2. Start traffic (made with 1 sipp uac and 1 sipp uas)

3. Check OpenSIPS crash when receiving reply from remote server

**Relevant System Logs**
`Oct  4 17:22:01 OSF-IT-V-OPENSIPS-LAB-1 kernel: [182296.775266] opensips[26053]: segfault at ffffffffffffff60 ip 00007f8990f2d2a0 sp 00007fff5a5b4ac8 error 5 in rtp_relay.so[7f8990f23000+e000]`

```
Oct  4 17:26:10 OSF-IT-V-OPENSIPS-LAB-1 opensips[26386]: INFO:rtpengine:rtpe_test: rtp proxy <udp:XXX.XXX.XXX.XXX:XXXX> found, support for it enabled

Oct  4 17:26:10 OSF-IT-V-OPENSIPS-LAB-1 opensips: INFO:core:daemonize: pre-daemon process exiting with 0

Oct  4 17:26:12 OSF-IT-V-OPENSIPS-LAB-1 opensips[26374]: NOTICE:drouting:dr_load_routing_info: loaded 6 gateways in partition 'Default'

Oct  4 17:26:12 OSF-IT-V-OPENSIPS-LAB-1 opensips[26374]: NOTICE:drouting:dr_load_routing_info: loaded 1 carriers in partition 'Default'

Oct  4 17:26:12 OSF-IT-V-OPENSIPS-LAB-1 opensips[26374]: NOTICE:drouting:dr_load_routing_info: loaded 150003 rules in partition 'Default'

Oct  4 17:26:23 OSF-IT-V-OPENSIPS-LAB-1 opensips[26377]: new branch at sip:+XXXXXXXXXXX@XXX.XXX.XXX.XXX

Oct  4 17:26:23 OSF-IT-V-OPENSIPS-LAB-1 opensips[26376]: incoming reply

Oct  4 17:26:23 OSF-IT-V-OPENSIPS-LAB-1 opensips[26376]: CRITICAL:core:sig_usr: segfault in process pid: 26376, id: 7

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26375]: new branch at sip:+XXXXXXXXXXX@XXX.XXX.XXX.XXX

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26375]: incoming reply

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26375]: CRITICAL:core:sig_usr: segfault in process pid: 26375, id: 6

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26369]: INFO:core:handle_sigs: child process 26376 exited by a signal 11

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26369]: INFO:core:handle_sigs: core was generated

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26369]: INFO:core:handle_sigs: terminating due to SIGCHLD

Oct  4 17:26:24 OSF-IT-V-OPENSIPS-LAB-1 opensips[26373]: INFO:core:sig_usr: signal 15 received
```

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: from apt on sourcelist deb https://apt.opensips.org buster 3.2-releases
 - RTPENGINE server information is stored in db

**Comment by Hyleoss** [comment]
Hello,
I compiled Opensips 3.2.2 from GIT source today, and got no segfault when using the exact same config file, but IP for RTP isn't changed in SDP for rtpproxy/engine IP. Seems like the rtp_relay module is doing nothing at all.

I replaced 

    rtp_relay_engage("rtpengine"); 

line with 

    rtpengine_use_set(0);
    rtpengine_offer();

and the IP is correctly changed in the SDP.
Maybe I misunderstanded how to use the new module.

Gonna make some other test.

Best regards,

**Comment by bogdan-iancu** [comment]
Hi @Hyleoss , the backtrace points to a possible memory corruption - could you try to run OpenSIPS with memory debugging (edit /etc/default/opensips (on Debian) or /etc/sysconfig/opensips (on Red Hat), and specify the OPTIONS="-a Q_MALLOC_DBG" command-line option for the opensips binary). And let's see how this affects.

**Comment by bogdan-iancu** [comment]
@Hyleoss , @razvancrainea just correctly pointed out that the backtrace is from a crash happening at shutdown, see:
```
#41 0x00005588fc2b5527 in shutdown_opensips (status=status@entry=139) at shutdown.c:249
```
What we need is the backtrace of the actual crash at runtime (this second crash at shutown may simply be a side effect). See https://opensips.org/Documentation/TroubleShooting-Crash

**Comment by Hyleoss** [comment]
Indeed, sorry about that, should be better with this one :

https://pastebin.com/1PEB8Cdt

**Comment by saurabhcchopra1992** [comment]
Opensips Team, Is this issue resolved? Didn't see much of progress here

**Comment by bogdan-iancu** [comment]
@Hyleoss , thanks for the backtrace, finally rhere is something we can work on, let us investigate.

**Comment by razvancrainea** [comment]
@Hyleoss is this reproducing every single time you are running the test? Also, are you setting any information in your `$rtp_relay` variable?

**Comment by razvancrainea** [comment]
I've done some changes in the code - can you pick the latest master/3.2 branches and try again your scenarios?

**Comment by Hyleoss** [comment]
Yes, every time I runned the test I got the same error.
I don't have access to my lab this week, gonna try it next monday, thanks for your reply !

**Comment by Hyleoss** [comment]
@razvancrainea I just installed the latest 3.2 branches and everything seems to work now, no crash and my RTP IP is correctly changed in SDP, thanks a lot !

**Comment by sasmita11** [comment]
Can you please mention here which version of opensips you are using . 

opesnips -V 
version: opensips 3.2.3 (x86_64/linux)

What's the version you have installed ?

**Comment by Hyleoss** [comment]
Here is the version :

 opensips 3.2.3 (x86_64/linux)
git revision: fb82bacce (was the latest nightly available at the time)
