### ISSUE TITLE
[CRASH] media_session_unref

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2645]
**OpenSIPS version you are running**

```
version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 563a78533
main.c compiled on 12:06:23 Oct  1 2021 with gcc 8
```

**Crash Core Dump**
https://pastebin.com/kZBurdPp

**To Reproduce**
I really do not have a way to reproduce it but this happened many times as I was playing around with dialog variables
and music on hold using `rtpengine_play_media("from-tag=$tt file=/data/moh/moh.wav");` to solve some re-invite 
issues with rtpengine_offer/rtpengine_answer

**Relevant System Logs**

```
Oct  7 09:00:36 ip-10-100-0-21 edge[1801]: NOTICE:presence:destroy: destroy module ...
Oct  7 09:00:36 ip-10-100-0-21 edge[1801]: CRITICAL:core:sig_usr: segfault in attendant (starter) process!
```

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git

thank you in advance
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
I have just found out that OpenSIPS crashes when you have `media_exchange.so` loaded and you exit with `ctrl+c `when OpenSIPS is running on the foreground 

bt full --> [here](https://pastebin.com/yMLwb50q)
and --> [here](https://pastebin.com/yefB4fEb)

thank you in advance
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Ping

Στις Δευ, 15 Νοε 2021, 08:40 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by vtzan** [comment]
Ping

Στις Τετ, 1 Δεκ 2021, 08:41 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by razvancrainea** [comment]
Still looking into it.
