### ISSUE TITLE
[BUG] no shared cipher error related TLS

### ISSUE THREAD

**Issue by woowadragonchan** [OpenSIPS/opensips#2646]
After configuring tls, the following error occurs when running. What is the cause?

> Version : OpenSIPS 2.4
> OS : Ubuntu LTS 18.04

<img width="1115" alt="스크린샷 2021-10-08 오후 6 56 28" src="https://user-images.githubusercontent.com/44791087/136537077-07f14efe-3cd7-4db5-a562-d3716f68e9c8.png">

**Comment by rvlad-patrascu** [comment]
Hi @woowadragonchan ,

It looks like the client and the opensips server could not agree on the set of supported ciphers so it's most likely not an issue on opensips's side.
