### ISSUE TITLE
[BUG] b2b_entities - b2b_prescript_f: No dialog found on method=UPDATE

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2647]
```
version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b5e78e547
main.c compiled on 09:23:05 Oct  8 2021 with gcc 8
```

**Describe the bug**
Firstly I don't know if this is a bug or a feature request.

I am using `b2b_entities` module with `rtpengine_play_media("from-tag=$tt file=/data/moh/moh.wav");`
to enable Music on Hold functionality and its working great when a re-negotiation is happening using METHOD_INVITE but
when trying to test with [http://tryit.jssip.net/](http://tryit.jssip.net/) i figured out that JsSIP uses METHOD_UPDATE for re-negotiation.

I know that JsSIP has a way to change that behaviour (https://jssip.net/documentation/3.8.x/api/session/#method_renegotiate) back to Re-Invite but I thought It would be nice for OpenSIPS b2b_entities to work with UPDATE methods too for sdp renegotiation.

**To Reproduce**
1. Start OpenSIPS with WSS support
2. connect 2 users using http://tryit.jssip.net/
3. Make A call
4. Press HOLD button and session is terminated.

**Relevant System Logs**
`Oct  8 10:33:09 ip-10-100-0-21 edge[404]: ERROR:b2b_entities:b2b_prescript_f: No dialog found, callid= [B2B.23.3688092.1633689181], method=UPDATE`

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: git

Thank you in advance for your support
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Ping

Στις Τρί, 9 Νοε 2021, 08:40 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by vtzan** [comment]
Ping

Στις Παρ, 26 Νοε 2021, 08:40 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by vtzan** [comment]
Ping

Στις Κυρ, 12 Δεκ 2021, 08:40 ο χρήστης github-actions[bot] <
***@***.***> έγραψε:

**Comment by rvlad-patrascu** [comment]
Hi @vtzan ,

Is this issue still actual on the latest 3.2? If it's still the case, can you post the full debug logs for such a call?

**Comment by vtzan** [comment]
Hi @rvlad-patrascu thanks for your reply. 
Let me test again with 3.3 as I am now on this release.

**Comment by vtzan** [comment]
This seems to work on 3.3.
thank you
