### ISSUE TITLE
[BUG] array-out-of-bound access in `sigcapture`?

### ISSUE THREAD

**Issue by Cossack9989** [OpenSIPS/opensips#2671]
I noticed that an array-out-of-bound access may be in [modules/sipcapture/sipcapture.c](https://github.com/OpenSIPS/opensips/blob/master/modules/sipcapture/sipcapture.c#L1803)

```c=
if (ri->proto < PROTO_UDP || ri->proto >= PROTO_OTHER) {
	LM_ALERT("Invalid proto!Maybe a new one was added %d\n",
		ri->proto);
	return -1;
}
SET_PVAL_STR(res, hep_net_protos[ri->proto]);
```
`hep_net_protos` is defined as 
```c=
static str hep_net_protos[]={
	/* want same index as in opensips enum */
	{NULL, 0},
	str_init("UDP"),
	str_init("TCP"),
	str_init("TLS"),
	str_init("SCTP"),
	str_init("WS"),
	str_init("WSS"),
	str_init("BIN"),
	str_init("HEP_UDP"),
	str_init("HEP_TCP"),
	{NULL, 0}
};
```
its length is 11.
When `ri->proto` squals `PROTO_SMPP`(11), `SET_PVAL_STR(res, hep_net_protos[ri->proto])` will access `hep_net_protos[11]` and lead to an array-out-of-bound access.

**Comment by bogdan-iancu** [comment]
@Cossack9989 , that's a good catch.  IMHO, the [hep_net_protos](https://github.com/OpenSIPS/opensips/blob/master/modules/sipcapture/sipcapture.c#L400) local array should be replaced with the more generic and safer function [get_proto_name()](https://github.com/OpenSIPS/opensips/blob/master/net/trans.h#L122). Not 100% if the naming of the protocols is the same and if that something that really matters on the Homer side.

**Comment by bogdan-iancu** [comment]
_180 Ringing...._
Currently checking with @adubovikov to be sure there are no side-effects while replacing the local array with the `get_proto_name()` fucntion....
