### ISSUE TITLE
[CRASH] opensips 3.1.6 crashes in dialog module

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#2675]
**OpenSIPS version you are running**

```
version: opensips 3.1.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 41d57ac56
main.c compiled on  with gcc 9
```

**Crash Core Dump**

Link to core with trace: https://disk.yandex.ru/d/t4f-gXs0yROC7g

**Describe the traffic that generated the bug**

Not sure what is, but looks like this problem with dialogue replication.

**To Reproduce**

**Relevant System Logs**

Dmesg:
```
[Sat Nov  6 17:47:51 2021] opensips[656290]: segfault at 90 ip 00007f2ac23741cf sp 00007ffcc8d3dc70 error 4 in dialog.so[7f2ac2312000+69000]
```

**OS/environment information**
 - Operating System:  Ubuntu 20.04.3 LTS

**Additional context**

**Comment by nikbyte** [comment]
Some note: dlg_hash.h is patched on our side (not related to this issue), 489 line in core is 479 line in unpatched file.

**Comment by nikbyte** [comment]
Would be good to solve...

**Comment by kertor** [comment]
UP

**Comment by nikbyte** [comment]
UP

**Comment by nikbyte** [comment]
up

**Comment by rvlad-patrascu** [comment]
This is the same crash as #2651.
