### ISSUE TITLE
[BUG] The client's certificate succeeds in registering in the TLS environment.

### ISSUE THREAD

**Issue by woowadragonchan** [OpenSIPS/opensips#2677]
> Version : 2.4.11
> OS : Ubuntu LTS 18.4

**The client succeeds in registering in a TLS environment without a certificate.** (The server's certificate is using self-signed)

Is this a BUG? Is this a normal flow? Is this an abnormal flow?
Or is only the register successful, and is there a security problem?

The following figure shows the log that the client's certificate does not exist.

<img width="481" alt="스크린샷 2021-11-09 오후 8 50 44" src="https://user-images.githubusercontent.com/44791087/140920793-50f0b494-8ee1-4c27-89e3-afe7a33facef.png">

Thank you.

**Comment by rvlad-patrascu** [comment]
Hi @woowadragonchan ,

Clients are not required to present a certificate, unless the `require_cert` modparam from `tls_mgm` is set. Feel free to reopen the ticket if that is the case, otherwise this is not a bug.
