### ISSUE TITLE
[BUG] B2B logic does not resolve PV for PRACK

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#2686]
**OpenSIPS version you are running**
3.2

```
```

**Describe the bug**
When trying to read $b2b_logic.key in b2b_request-route (for received b2b requests) for a PRACK request, opensips does not resolve the PV:

xlog("L_INFO","B2B($b2b_logic.key) [rx] $rm $ru from $si ($ci)\n");

Leads to:

B2B(<null>) [rx] PRACK sip:10.61.63.74 from 10.61.63.80 (sat.940.460463.1636799255)

Debug log shows:

DBG:b2b_logic:get_ctx_tuple: b2b_logic key not set in b2b_entities context
DBG:b2b_logic:pv_get_b2bl_key: Unable to get the tuple from the current context

We also noticed, when doing "b"-tracing (tracing b2b automatically using "b"-mode in opensips 3.2), the received PRACK requests are not traced. Likely this is because of the same reason.

**Comment by xaled1** [comment]
Hi, 
could you provide some feedback on the issue?

**Comment by xaled1** [comment]
Do you have any update? 
Thanks.

**Comment by xaled1** [comment]
Any progress on this bug?

**Comment by bogdan-iancu** [comment]
@rvlad-patrascu will take a look as part of the beta fixing for 3.3 ;)

**Comment by rvlad-patrascu** [comment]
Hi @xaled1 

Can you please open a different issue for the b2b tracing problem? It does not seem to be related to this.
