### ISSUE TITLE
[BUG] BYE from dialog timer causes error logs

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2690]
**OpenSIPS version you are running**

```
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7193c5d8d
main.c compiled on 19:04:46 Nov 15 2021 with gcc 7
```

**Describe the bug**

This appears to be a regression of #2464 .

We use $DLG_timeout to limit calls to a maximum time and also to disconnect calls that don't receive a proper ACK. When the timer pops a BYE is sent to both ends of the call. We do some handling of the BYE in local_route and arm both reply and failure routes for the BYE. A recent change has caused error logs to appear on the response to the BYE in our reply route. It appears the topology_hiding module has callbacks loaded which are firing and attempting to call fix_route_dialog on the now terminated dialog and causing errors. 

**To Reproduce**

1. Start OpenSIPS
2. Place a call and set $DLG_timeout
3. In local_route, arm a reply route
4. Allow call to time out
5. See errors on BYE response

**Expected behavior**

The errors are unexpected, but it's not clear if any of the attempted processing is actually necessary.

**Relevant System Logs**

```
Nov 17 15:29:02 [432] ERROR:dialog:fix_route_dialog: Script error - validate function before having a dialog
Nov 17 15:29:02 [432] ERROR:topology_hiding:topo_dlg_onroute: Failed to fix the SIP request according to dialog info 
```

**OS/environment information**
 - Operating System:  amazonlinux:2 on Docker
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@bcnewlin here is a fix for you to test. It is a more generic approach than in #2464 

````
diff --git a/modules/topology_hiding/topo_hiding_logic.c b/modules/topology_hiding/topo_hiding_logic.c
index d379e943b..0665a9c27 100644
--- a/modules/topology_hiding/topo_hiding_logic.c
+++ b/modules/topology_hiding/topo_hiding_logic.c
@@ -1036,11 +1036,10 @@ static void topo_dlg_onroute (struct dlg_cell* dlg, int type,
                return;
        }
 
-       /* we also may end up here via TERMINATE event triggered by internal
-        * dlg termination -> the requests we have here are dummy, so nothing
-        * to be done */
-       if (is_dummy_sip_msg(req)==0) {
-               LM_DBG("dummy request identified, skipping...\n");
+       /* filter out the case we end up here for local UAC request (one VIA), as
+        * there is no relaying to follow, so nothing to be done here */
+       if (req->via2==NULL) {
+               LM_DBG("uac/dummy request identified, skipping...\n");
                return;
        }
 
````

**Comment by bogdan-iancu** [comment]
@ovidiusas reported some regression here, reopening for a deeper analysis

**Comment by bogdan-iancu** [comment]
OK, the initial commit was reverted, and a new one was pushed, see 02c6ed9eaa3751623f19ed160dc802e11862df3d . I did several tests on my side, but if you could also validate it ;)
