### ISSUE TITLE
Opensips 3.2.3 : Not able to find Automake 1.14.1 version that supports rhel7 software

### ISSUE THREAD

**Issue by sujalasura** [OpenSIPS/opensips#2694]
Hi, 
We are planning to upgrade opensips to 3.2.3. When we compile it on rhel7 servers, we are seeing below errors:

 [exec] autoreconf: running: automake --add-missing --copy --force-missing
     [exec] configure.ac:28: error: require Automake 1.14.1, but have 1.14
     [exec] autoreconf: automake failed with exit status: 1
     [exec] configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
     [exec] make[1]: Leaving directory `/opt/bld/fetch/bldtest3jbe1/dev_dev_core1_full_build/appliance/apps/opensips/obj/opensips-3.2.3/modules/tls_wolfssl'
     [exec] make[1]: *** [lib/lib/libwolfssl.a] Error 1
     [exec] make: *** [modules] Error 2

We tried to look for the required automake version that supports rhel7 environment, but couldn't find any.

Could you please help us how can we move forward with this error. How can we compile opensips 3.2.3 on rhel7 server ?

Thanks
Sujala

**Comment by vasilevalex** [comment]
```
diff --git a/modules/tls_wolfssl/lib/wolfssl/configure.ac b/modules/tls_wolfssl/lib/wolfssl/configure.ac
index 36fcc6d19..4da0fcc8a 100644
--- a/modules/tls_wolfssl/lib/wolfssl/configure.ac
+++ b/modules/tls_wolfssl/lib/wolfssl/configure.ac
@@ -25,7 +25,7 @@ AC_CANONICAL_HOST
 AC_CANONICAL_TARGET
 AC_CONFIG_MACRO_DIR([m4])
 
-AM_INIT_AUTOMAKE([1.14.1 -Wall -Werror -Wno-portability foreign tar-ustar subdir-objects no-define color-tests])
+AM_INIT_AUTOMAKE([1.13.4 -Wall -Werror -Wno-portability foreign tar-ustar subdir-objects no-define color-tests])
 m4_ifdef([AM_SILENT_RULES],[AM_SILENT_RULES([yes])])
 
 AC_ARG_PROGRAM
```

**Comment by sujalasura** [comment]
@vasilevalex 
Could you please clarify on your above comment? I'm not able to understand on what you are trying to suggest.


Thanks
Sujala

**Comment by vasilevalex** [comment]
@sujalasura apply this patch and build opensips on rhel7.

**Comment by sujalasura** [comment]
@vasilevalex  Thank you. That solved our issue.
