### ISSUE TITLE
[BUG] t_check_status does not work on anonym onreply_route{...}

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2705]
**OpenSIPS version you are running**

```version: opensips 3.1.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 553603552
main.c compiled on  with gcc 8


```

**Describe the bug**

seems to me it does not work on an onreply_route with no name (eg, catchall)
MAYBE I'M LOST IN SPACE...

**To Reproduce**

onreply_route {
if ( t_check_status("200") ) {
xlog("L_ERROR", "JOY $rs");
} else {
xlog("L_ERROR", "NO JOY $rs");
}
}

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
`t_check_status` is a TM (transactional) function. In the generic `onreply_route` there is no transaction state at all. So, the function (as any TM functions or other functions relying on the transaction state) will not work, by design.
Maybe you should use `$rs` to access the reply status code ?

**Comment by gmaruzz** [comment]
yep, that's what I've done...
I suspected something similar (eg, no transaction state in generic onreply_route) tried to check on documentation, but was not able to find it out

maybe is worth to put it explicitly 

Anyway, thanks, it makes perfect sense

**Comment by bogdan-iancu** [comment]
It should be clearly stated here https://www.opensips.org/Documentation/Script-Routes-3-2#toc4, I will take care, thanks for the point ;)
