### ISSUE TITLE
[CRASH]3.2.3-1 crash in tracer: double free (when tracing two times, different hep trace destinations)

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2710]
**OpenSIPS version you are running**

```
# opensips -V
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 6.3.0


```

**Crash Core Dump**

<pre>

root@voip01:/etc/opensips# gdb /usr/sbin/opensips /tmp/core.17165 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git 
Copyright (C) 2016 Free Software Foundation, Inc. 
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html> 
This is free software: you are free to change and redistribute it. 
There is NO WARRANTY, to the extent permitted by law.  Type "show copying" 
and "show warranty" for details. 
This GDB was configured as "x86_64-linux-gnu". 
Type "show configuration" for configuration details. 
For bug reporting instructions, please see: 
<http://www.gnu.org/software/gdb/bugs/>. 
Find the GDB manual and other documentation resources online at: 
<http://www.gnu.org/software/gdb/documentation/>. 
For help, type "help". 
Type "apropos word" to search for commands related to "word"... 
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/lib/debug/.build-id/ac/03f3f26749c3d578106838f2c18a5ff9b33365.debug...done. 
done. 
[New LWP 17165] 
 
warning: Unexpected size of section `.reg-xstate/17165' in core file. 
[Thread debugging using libthread_db enabled] 
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". 
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'. 
Program terminated with signal SIGSEGV, Segmentation fault. 
 
warning: Unexpected size of section `.reg-xstate/17165' in core file. 
#0  0x00007fe1d4ebb676 in strlen () from /lib/x86_64-linux-gnu/libc.so.6 
(gdb) bt full 
#0  0x00007fe1d4ebb676 in strlen () from /lib/x86_64-linux-gnu/libc.so.6 
No symbol table info available. 
#1  0x00007fe1d4e83da8 in vfprintf () from /lib/x86_64-linux-gnu/libc.so.6 
No symbol table info available. 
#2  0x00007fe1d4f322b6 in __vfprintf_chk () from /lib/x86_64-linux-gnu/libc.so.6 
No symbol table info available. 
#3  0x00007fe1d4f1ee28 in __vsyslog_chk () from /lib/x86_64-linux-gnu/libc.so.6 
No symbol table info available. 
#4  0x00007fe1d4f1f322 in __syslog_chk () from /lib/x86_64-linux-gnu/libc.so.6 
No symbol table info available. 
#5  0x000055bfb3d3b5c8 in syslog (__fmt=0x55bfb3e29908 "CRITICAL:core:%s: freeing already freed %s pointer (%p), first free: %s: %s(%ld) - aborting!\n", __pri=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/syslog.h:31
No locals.
#6  fm_free (fm=<optimized out>, p=<optimized out>, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/f_malloc_dyn.h:237
        f = <optimized out>
        n = <optimized out>
        __FUNCTION__ = "fm_free"
#7  0x00007fe1b6803250 in _shm_free (file=<optimized out>, line=<optimized out>, function=<optimized out>, ptr=<optimized out>) at ../../net/../mem/shm_mem.h:448
No locals.
#8  free_trace_info_shm (param=0x7fe1c44a19c0) at tracer.c:1357
        info = 0x7fe1c44a19c0
        it = <optimized out>
        next = 0x7fe1c449b9d0
        __FUNCTION__ = "free_trace_info_shm"
#9  0x00007fe1ba498beb in empty_tmcb_list (head=0x7fe1ba6d5460 <tmcb_pending_hl>) at t_hooks.c:53
        cbp = 0x7fe1c449f368
        cbp_tmp = <optimized out>
        __FUNCTION__ = "empty_tmcb_list"
#10 0x00007fe1ba4872bb in do_t_cleanup (req=0x7fe1d4101030, bar=<optimized out>) at tm.c:692
        t = <optimized out>
        __FUNCTION__ = "do_t_cleanup"
#11 0x000055bfb3c850f1 in exec_post_cb (cb=0x7fe1d3eae9f0, msg=0x7fe1d4101030) at script_cb.c:180
No locals.
#12 exec_post_req_cb (msg=msg@entry=0x7fe1d4101030) at script_cb.c:198
No locals.
#13 0x000055bfb3c907d4 in receive_msg (buf=0x55bfb41d7760 <buf> "CANCEL sip:1016@acmeinc.voip.loquacetest.cloud;user=phone SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.1.31:47650;branch=z9hG4bK-lz23jj6kwf1e;rport\r\nFrom: \"nems 1010\" <sip:1010@acmeinc.voip.loquacetest.cloud>;ta"..., len=<optimized out>, rcv_info=rcv_info@entry=0x7ffe7aec4c10, existing_context=existing_context@entry=0x0, msg_flags=msg_flags@entry=0) at receive.c:219
        ctx = 0x7fe1d41024e8
        msg = 0x7fe1d4101030
        start = {tv_sec = 140607899386648, tv_usec = 6}
        rc = <optimized out>
        old_route_type = <optimized out>
        in_buff = {s = 0x55bfb41d7760 <buf> "CANCEL sip:1016@acmeinc.voip.loquacetest.cloud;user=phone SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.1.31:47650;branch=z9hG4bK-lz23jj6kwf1e;rport\r\nFrom: \"nems 1010\" <sip:1010@acmeinc.voip.loquacetest.cloud>;ta"..., len = 771}
        __FUNCTION__ = "receive_msg"
#14 0x000055bfb3df4586 in udp_read_req (si=<optimized out>, bytes_read=<optimized out>) at net/proto_udp/proto_udp.c:186
        ri = {src_ip = {af = 2, len = 4, u = {addrl = {998388818, 140607899397624}, addr32 = {998388818, 0, 3555028472, 32737}, addr16 = {13394, 15234, 0, 0, 28152, 54245, 32737, 0}, addr = "R4\202;\000\000\000\000\370m\345\323\341\177\000"}}, dst_ip = {af = 2, len = 4, u = {addrl = {3340360031, 0}, addr32 = {3340360031, 0, 0, 0}, addr16 = {55647, 50969, 0, 0, 0, 0, 0, 0}, addr = "_\331\031\307", '\000' <repeats 11 times>}}, src_port = 47650, dst_port = 5070, proto = 1, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\272\"R4\202;\000\000\000\000\000\000\000"}, sin = {sin_family = 2,
              sin_port = 8890, sin_addr = {s_addr = 998388818}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 8890, sin6_flowinfo = 998388818, sin6_addr = {__in6_u = {__u6_addr8 = "\000\000\000\000\000\000\000\000\360\272\356\323\002\000\000", __u6_addr16 = {0, 0, 0, 0, 47856, 54254, 2, 0}, __u6_addr32 = {0, 0, 3555638000, 2}}}, sin6_scope_id = 0}}, bind_address = 0x7fe1d3e45700}
        len = <optimized out>
        buf = "CANCEL sip:1016@acmeinc.voip.loquacetest.cloud;user=phone SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.1.31:47650;branch=z9hG4bK-lz23jj6kwf1e;rport\r\nFrom: \"nems 1010\" <sip:1010@acmeinc.voip.loquacetest.cloud>;ta"...
        fromlen = 16
        p = <optimized out>
        msg = {s = 0x55bfb41d7760 <buf> "CANCEL sip:1016@acmeinc.voip.loquacetest.cloud;user=phone SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.1.31:47650;branch=z9hG4bK-lz23jj6kwf1e;rport\r\nFrom: \"nems 1010\" <sip:1010@acmeinc.voip.loquacetest.cloud>;ta"..., len = 771}
        __FUNCTION__ = "udp_read_req"
#15 0x000055bfb3dd0f5f in handle_io (idx=<optimized out>, event_type=<optimized out>, fm=<optimized out>) at net/net_udp.c:272
        n = <optimized out>
        read = 21951
#16 io_wait_loop_epoll (repeat=0, t=1, h=<optimized out>) at net/../io_wait_loop.h:308
        ret = 1
        n = 1
        r = 0
        i = <optimized out>
        e = 0x7fe1d3eed190
        ep_event = {events = 3020642304, data = {ptr = 0x100005500, fd = 21760, u32 = 21760, u64 = 4294989056}}
        fd = <optimized out>
        curr_time = 5
#17 0x000055bfb3dd60d6 in udp_start_processes (chd_rank=<optimized out>, startup_done=<optimized out>) at net/net_udp.c:497
        si = 0x7fe1d3e45700
        p_id = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "udp_start_processes"
#18 0x000055bfb3c61c5f in main_loop () at main.c:227
        startup_done = 0x0
        chd_rank = 6
        last_check = 0
        rc = <optimized out>
        chd_rank = 6
#19 main (argc=<optimized out>, argv=<optimized out>) at main.c:916
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffe7aec5eae ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x55bfb3e1f698 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        ret = -1
        seed = 83027891
        __FUNCTION__ = "main"
(gdb)

</pre>

**Describe the traffic that generated the bug**

exactly reproducible:

A calls B
A CANCEL call before B answers
crash

crash happens if I have a double hep trace (eg: one that goes to a local sngrep and one to a remote homer).

bt full included is from a run where duble trace is in main route, local route and onreply_local route (so, three double hep traces, all in all)

if I have only one hep trace destination (so, no doble traces, just three single traces, one in main, one in local, one in onreply_local) crash do not happens.

**To Reproduce**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
Debian 9, installed from pkgs

**Additional context**

**Comment by razvancrainea** [comment]
Yes, very likely to be a duplicate of #2531

**Comment by gmaruzz** [comment]
i close this one, let's continue on #2531
