### ISSUE TITLE
module auth_jwt not in available list of packages OpenSIPS 3.2 Debian/unbuntu

### ISSUE THREAD

**Issue by jonhvoxbox** [OpenSIPS/opensips#2711]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by jonhvoxbox** [comment]
I notice it is not available on the list of available deb packages and wondered if its possible to add as this would be great for container based deployments.

**Comment by jonhvoxbox** [comment]
Sorry to add context I would like to deploy this within a container so would be great to install from packages as apposed to sources.

Thanks!

**Comment by bogdan-iancu** [comment]
100 Trying....

**Comment by nikbyte** [comment]
Building of auth_jwt has enabled for all opensips and it's already available in nightly builds except Debian Stretch.
