### ISSUE TITLE
[BUG] not enough free pkg memory

### ISSUE THREAD

**Issue by xiaoluweiba** [OpenSIPS/opensips#2715]
**OpenSIPS version you are running**

```
version: opensips 3.1.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 60d62837e
main.c compiled on 22:11:16 Dec 14 2021 with gcc 9
```

**Describe the bug**

opensips[140642]: ERROR:core:qm_malloc: not enough free pkg memory (149536 bytes left, need 384), please increase the "-M" command line parameter!
opensips[140642]: ERROR:core:build_res_buf_from_sip_req: out of pkg memory; needs 380

get_statistics: 
{
    "shmem:total_size": 536870912,
    "shmem:max_used_size": 28595920,
    "shmem:free_size": 516126704,
    "shmem:used_size": 16089968,
    "shmem:real_used_size": 20744208,
    "shmem:fragments": 144012,
    "rpmem:rpm_total_size": 0,
    "rpmem:rpm_used_size": 0,
    "rpmem:rpm_real_used_size": 0,
    "rpmem:rpm_fragments": 0,
    "rpmem:rpm_max_used_size": 0,
    "rpmem:rpm_free_size": 0,

PS: system memory space is enough

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by xiaoluweiba** [comment]
how can i debug pkg mem? I found nnly one child process's memory has been declining, the others will not

**opensips-cli -x mi mem_pkg_dump <pid>** show

Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: Memory status (pkg):
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: qm_status (0x7fb103fff010):
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]:  heap size= 67108864
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]:  used= 4837488, used+overhead=5285488, free=61823376
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]:  max used (+overhead)= 5387584
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]:  dumping free list stats :
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=   2. fragments no.:    75, unused:     0#012#011#011 bucket size:        32 -        32 (first        32)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=   3. fragments no.:    62, unused:     0#012#011#011 bucket size:        48 -        48 (first        48)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=   4. fragments no.:     5, unused:     0#012#011#011 bucket size:        64 -        64 (first        64)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=   5. fragments no.:     9, unused:     0#012#011#011 bucket size:        80 -        80 (first        80)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=   8. fragments no.:     1, unused:     0#012#011#011 bucket size:       128 -       128 (first       128)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=  15. fragments no.:     1, unused:     0#012#011#011 bucket size:       240 -       240 (first       240)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=  21. fragments no.:     1, unused:     0#012#011#011 bucket size:       336 -       336 (first       336)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash=  57. fragments no.:     1, unused:     0#012#011#011 bucket size:       912 -       912 (first       912)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash= 154. fragments no.:     1, unused:     0#012#011#011 bucket size:      2464 -      2464 (first      2464)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: hash= 1036. fragments no.:     1, unused:     0#012#011#011 bucket size:  33554432 -  67108864 (first  61812880)
Dec 20 08:22:54 eu-Frankfurt-proxy-1 opensips[2695340]: -----------------------------

**Comment by bogdan-iancu** [comment]
@xiaoluweiba , please take a look at https://opensips.org/Documentation/TroubleShooting-OutOfMem

**Comment by xiaoluweiba** [comment]
> @xiaoluweiba , please take a look at https://opensips.org/Documentation/TroubleShooting-OutOfMem

hi, @bogdan-iancu 

1. **start opensips**：opensips -P /var/run/opensips.pid -m512 -M64 -a Q_MALLOC_DBG
2. set memdup=1 on opensips.cfg
3. find leak pid from opensips-ctl -x mi ps
4. opensips-cli -x mi mem_pkg_dump $pid

only list
opensips[1456085]: Memory status (pkg):
opensips[1456085]: qm_status (0x7feab921d010):
opensips[1456085]:  heap size= 67108864
opensips[1456085]:  used= 4401280, used+overhead=4661440, free=62447424
opensips[1456085]:  max used (+overhead)= 4666512
opensips[1456085]:  dumping free list stats :
opensips[1456085]: hash= 317. fragments no.:     1, unused:     0#012#011#011 bucket size:      5072 -      5072 (first      5072)
opensips[1456085]: hash= 1036. fragments no.:     1, unused:     0#012#011#011 bucket size:  33554432 -  67108864 (first  62442352)
opensips[1456085]: -----------------------------
![image](https://user-images.githubusercontent.com/14882870/146860518-cfa6f04e-ea22-43d3-ad5d-e627e0ceb15d.png)

**Comment by bogdan-iancu** [comment]
That's not the output of the Q_MALLOC with DBG :(, there is something wrong there, you should see something like https://pastebin.com/KJVb9Y75

**Comment by tvandergeer** [comment]
> set memdup=1 on opensips.cfg

Shouldn't that be `memdump=1` (missing 'm')?

**Comment by bogdan-iancu** [comment]
> > set memdup=1 on opensips.cfg
> 
> Shouldn't that be `memdump=1` (missing 'm')?

I think it is just a typo here, otherwise opensips will not even start as it will not recognize that parameter.

**Comment by tvandergeer** [comment]
I see this issue happening on our 3.1.1 setup as well. It happens over the course of 2 to 3 weeks of operation.
Actually thought that @bogdan-iancu was investigating this. Might be related to #2726 as well?

**Comment by bogdan-iancu** [comment]
@tvandergeer , a mem dump will be the relevant one, together with the shm mem stats.

**Comment by tvandergeer** [comment]
@bogdan-iancu Yes, this morning I've set it up on one of our nodes on the production environment. Will report back when I've gathered the results

**Comment by tvandergeer** [comment]
Hi,

We got a crash on the opensips node I set up for memory logging. See [here for the full dump in opensips.log](https://gist.github.com/tvandergeer/ae8433ce87c75d6d6765dc1f63efe24f). It crashed on a worker with PID 59.

During the past 2 weeks I've had 3 times that I paused all call processing on that node and (after 20 minutes rest) ran the dump commands through the mi interface. I've noticed that on several workers an increasing amount of memory was allocated. These are the important parts of the dump for PID 59. See the differences between Feb 8 and Feb 14:
```
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:           8 : 1 x [transformations.c: tr_eval_re, line 1954]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:      176152 : 1826 x [parser/contact/contact.c: parse_contacts, line 190]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        1584 : 33 x [transformations.c: parse_transformation, line 2471]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        1040 : 10 x [transformations.c: tr_parse_nparam, line 2571]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          48 : 2 x [script_cb.c: insert_raw_processing_cb, line 220]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          72 : 1 x [ut.h: pkg_str_extend, line 914]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:         384 : 6 x [mod_fix.c: fixup_regcomp, line 55]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          64 : 2 x [transformations.c: tr_parse_sparam, line 2663]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:       80920 : 621 x [cfg.lex: addstr, line 786]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        9648 : 1 x [route.c: new_sroutes_holder, line 95]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:       68456 : 1123 x [data_lump.c: del_lump, line 352]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:     1383296 : 26566 x [t_fwd.c: pre_print_uac_request, line 169]
Feb  8 08:22:57 ip-10-1-2-189 /usr/local/sbin/opensips[59]:     2013264 : 1 x [io_wait.c: init_io_wait, line 621]
```

```
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:           8 : 1 x [transformations.c: tr_eval_re, line 1954]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:      417792 : 4328 x [parser/contact/contact.c: parse_contacts, line 190]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        1584 : 33 x [transformations.c: parse_transformation, line 2471]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        1040 : 10 x [transformations.c: tr_parse_nparam, line 2571]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          48 : 2 x [script_cb.c: insert_raw_processing_cb, line 220]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          72 : 1 x [ut.h: pkg_str_extend, line 914]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:         384 : 6 x [mod_fix.c: fixup_regcomp, line 55]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:          64 : 2 x [transformations.c: tr_parse_sparam, line 2663]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:       80920 : 621 x [cfg.lex: addstr, line 786]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:        9648 : 1 x [route.c: new_sroutes_holder, line 95]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:      148272 : 2437 x [data_lump.c: del_lump, line 352]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:     3108544 : 59597 x [t_fwd.c: pre_print_uac_request, line 169]
Feb 14 10:42:30 ip-10-1-2-189 /usr/local/sbin/opensips[59]:     2013264 : 1 x [io_wait.c: init_io_wait, line 621]
```

So it looks like the memory is not released in `parse_contacts`, `del_lump` and `pre_print_uac_request`. 

Other PIDs show similar increases

Does this provide any insights on what might be causing issues for us?
(I can share more dumps when requested)

**Comment by tvandergeer** [comment]
Hi @bogdan-iancu, did you see my findings? Is there anything that comes to mind that could be causing this?

**Comment by bogdan-iancu** [comment]
Hi @tvandergeer , `pre_print_uac_request` looks the best candidate from far. In your branch route, do you have some logic to change the RURI of the request?

**Comment by tvandergeer** [comment]
Hi @bogdan-iancu , thanks for your response! 
We have some logic to change the RURI (by assigning a new value to $ru), but we're doing that on the main route and on the on_reply route. These routes do have conditional branches. E.g.
```
if( $avp(is_anonymous) == 1 ) t_on_branch("privacyheader");
```

But there's no RURI modification done in any of these branch routes.

We do have a use case that the $ru is modified multiple times in a dialog. We use this when a destination returns an error, we modify the RURI to a new (fallback) destination. Could this be causing the issue?

**Comment by bogdan-iancu** [comment]
I see.... could you paste here your branch route? or PM it to me if too sensitive.

**Comment by tvandergeer** [comment]
Hi @bogdan-iancu ,

These are the branch routes:
```
# Created a branch so the header is not appended on the main route. See notes in textops documentation:
#   Headers which are added in main route cannot be removed in further routes (e.g. failure routes). 
#   So, the idea is not to add there any headers that you might want to remove later. To add headers 
#   temporarely use the branch route because the changes you do there are per-branch.
branch_route[privacyheader] {
    append_hf("Privacy: id\r\n","From");
    append_hf("P-Asserted-Identity: tel:+$(avp(from_user){s.substr,2,0})\r\n","From");
}

branch_route[pid_sip_header] {
  if( $avp(used_trunk) == 'TRUNK_NAME' ){
    append_hf("P-Asserted-Identity: <sip:+$(avp(from_user){s.substr,2,0})@$(var(request_uri_host))>\r\n","From");
  }
}

# Another branch route to change the SIP INVITE so an extra Diversion header is added
# This is required by <trunk_provider_x> to be able to circumvent issues with Telco's that don't accept calls when caller and callee are their own customers
branch_route[diversionheader] {
    # pick a random number in the range xxxxxxx2590 to xxxxxxx2599 and use it in the Diversion header
    $var(r1) = $RANDOM;
    $var(divnum) = "xxxxxxx8259" + $(var(r1){s.substr,-1,1});
    xlog("Adding Diversion header for <trunk_prodiver_x>: $(var(divnum))");
    append_hf("Diversion: <sip:$(var(divnum))@ringcredible>;reason=unconditional\r\n","To");

    if($avp(is_anonymous) == 1){
      append_hf("Privacy: id\r\n","From");
      append_hf("P-Asserted-Identity: <sip:+$(avp(from_user){s.substr,2,0})@$(var(request_uri_host))>\r\n","From");
    }
}
```
Actually replaced the name of one of our trunk providers with `TRUNK_NAME` and with <trunk_provider_x>. And obfuscated a phone number with xxxxxxx.

These branches are called from route[1] like this:
```
        if( $avp(is_anonymous) == 1 ) {
          t_on_branch("privacyheader");
        }else{
          t_on_branch("pid_sip_header");
        }
```
And
```
t_on_branch("diversionheader");
```

**Comment by tvandergeer** [comment]
A quick update on this: we've upgraded OpenSIPS to v3.2.7 but the issue is still there. Any ideas in what area we need to search for a solution?
