### ISSUE TITLE
[BUG]mysql connecter timeout process error for mysql 8

### ISSUE THREAD

**Issue by zbyslb** [OpenSIPS/opensips#2721]
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 00:44:43 Dec 23 2021 with gcc 8

Starting from MySQL 8.0.24, when the connection between the client and the MySQL server is deleted by the server due to timeout, the returned error code is modified to:ER_CLIENT_INTERACTION_TIMEOUT. And in opensips3.2.4(as in other versions), there are only three types of MySQL connection failure: CR_SERVER_GONE_ERROR、CR_SERVER_Lost and CR_COMMANDS_OUT_OF_SYNC, other errors will not be retried. See dbase.c for details(the function is:wrapper_single_mysql_stmt_prepare). For descriptions of new MySQL connecter errors, see https://dev.mysql.com/doc/relnotes/connector-cpp/en/news-8-0-24.html

**Comment by zbyslb** [comment]
Can't you deal with such an obvious problem

**Comment by zbyslb** [comment]
How could there be no response

**Comment by bogdan-iancu** [comment]
Patience is a virtue. Please understand this is free work, where people are doing their best in allocating resources. Also keep in mind that we welcome any Pull Request, if you are in such a big hurry.

**Comment by vladpaiu** [comment]
Fixed in 16d73398c35bf8e6582a19393ff88ca184d95f6c
