### ISSUE TITLE
[BUG] After upgrading from 3.1.1 to 3.1.7 , I started to get  WARNING:core:fm_malloc: not enough contiguous free pkg memory

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#2726]
Hello All,
After upgrading from 3.1.1 to 3.1.7 ,I started to get the following errors all the time. After restarting, the same result in 1-2 hours

Jan 11 19:36:29 sip opensips[14271]: WARNING:core:fm_malloc: not enough contiguous free pkg memory (463579368 bytes left, need 2280), attempting defragmentation... please increase the "-M" command line parameter!
Jan 11 19:36:29 sip opensips[14271]: WARNING:core:fm_malloc: not enough contiguous free pkg memory (463579368 bytes left, need 2280), attempting defragmentation... please increase the "-M" command line parameter!
Jan 11 19:36:29 sipopensips[14271]: WARNING:core:fm_malloc: not enough contiguous free pkg memory (463579424 bytes left, need 2312), attempting defragmentation... please increase the "-M" command line parameter!
Jan 11 19:36:29 sip opensips[14271]: WARNING:core:fm_malloc: not enough contiguous free pkg memory (463579424 bytes left, need 2264), attempting defragmentation... please increase the "-M" command line parameter!
Jan 11 19:36:29 sip opensips[14271]: WARNING:core:fm_malloc: not enough contiguous free pkg memory (463579416 bytes left, need 2272), attempting defragmentation... please increase the "-M" command line parameter!

[root@sopensips]# opensips-cli -x mi get_statistics free_size
{
    "shmem:free_size": 2142860392
}
[root@opensips]# opensips-cli -x mi get_statistics real_used_size
{
    "shmem:real_used_size": 4602352
}

Any ideas ?

Thank you!

**Comment by fedkis** [comment]
-M was increased many times but no effect

 /usr/local/opensips-3.1/sbin/opensips -P /var/run/opensips.pid -f /usr/local/opensips-3.1/etc/opensips/opensips.cfg -u opensips -M 512 -m 2048

**Comment by liviuchircu** [comment]
Hi, there is only one commit, introduced in `3.1.3`, which could have changed the behavior so dramatically:

```
F_MALLOC: Always perform an O(1) defragmentation on free()
Changes:
    * remove the "memory space" runtime computation, as well as the 95%
	defragmentation "start threshold" (better performance!)
    * change the defragmentation heuristic from O(N) to O(1).  This way,
        we avoid any performance issues caused by _too much_
	defragmentation

The main idea is to get rid of the dreaded "not enough shared memory,
attempting defragmentation..." state, where SHM performance goes down
dramatically, to the point where SIP traffic processing may stall.

(cherry picked from commit fb9a377)
```

Are you able to revert it and re-test?  If not, try switching the PKG memory to the Q_MALLOC allocator, which performs more fragment coalescing, using the `-k Q_MALLOC` command-line argument for `opensips`.  Your OpenSIPS will use maybe +10% CPU compared to `F_MALLOC`, but the symptoms should go away.

Meanwhile, I will think about this problem and try to come up with a definitive solution.

**Comment by fedkis** [comment]
Yes , I think so.
 I have already reverted it back. 
 I am testing now

Date:   Tue Jan 11 19:47:22 2022 +0200

    Revert "F_MALLOC: Always perform an O(1) defragmentation on free()"

    This reverts commit b433bd0b37a635ede7d6fdc4460af02e8eb368fe.

**Comment by fedkis** [comment]
On my other server after upgrading from 3.1.1 to 3.2.4 with completely other configuration, I also started getting a similar error dialog:internal_mi_print_dlg after 1 day of working. This server receives many mi  http commands. Looks like the problem is massive

Jan 11 20:04:25 sip1 opensips[165339]: ERROR:core:qm_malloc_dbg: not enough free pkg memory (461888568 bytes left, need 1864), please increase the "-M" command line parameter!
Jan 11 20:04:25 sip1 opensips[165339]: ERROR:dialog:internal_mi_print_dlg: not enough mem to allocate: 465
Jan 11 20:04:25 sip1 opensips[165339]: ERROR:core:qm_malloc_dbg: not enough free pkg memory (461888568 bytes left, need 1408), please increase the "-M" command line parameter!
Jan 11 20:04:25 sip1 opensips[165339]: ERROR:dialog:internal_mi_print_dlg: not enough mem to allocate: 350
Jan 11 20:04:25 sip1 opensips[165339]: ERROR:core:qm_malloc_dbg: not enough free pkg memory (461888568 bytes left, need 2232), please increase the "-M" command line parameter!
Jan 11 20:04:25 sip1 opensips[165339]: ERROR:dialog:internal_mi_print_dlg: not enough mem to allocate: 556

**Comment by fedkis** [comment]
Hi Liviu,
After testing I found out the following things:

1. First bug is related to b433bd0b37a635ede7d6fdc4460af02e8eb368fe. After I reverted it back in 3.1.7/3.2.4 , the bug fixed.
2.  The second bug internal_mi_print_dlg doesn't exist in 3.1.7 , that means it has appeared in 3.2 branch.  I have no idea what to try. Do you have any advice ?

**Comment by ankogan** [comment]
> 2\. The second bug internal_mi_print_dlg doesn't exist in 3.1.7 , that means it has appeared in 3.2 branch.  I have no idea what to try. Do you have any advice ?

I have the same behaviour on 3.2.9

**Comment by liviuchircu** [comment]
Hi, guys!

We have been debating a couple of approaches to this problem, although it is not clear whether they will solve your specific MI / dialog-printing related fragmentation problem, which is difficult to reproduce.  I have implemented and even stress-tested one of them successfully (no regressions) but before we push it, could you possibly give the patch a test as well, just to confirm it solves your specific fragmentation problem?

The patch can be found [here](https://gist.github.com/liviuchircu/be9396c7238fb59dc4633859b1d36494).

**Comment by ankogan** [comment]
Hi!
I've patched the opensips on one of my servers, checking...

**Comment by ankogan** [comment]
> Hi! I've patched the opensips on one of my servers, checking...
Hi!
Haven't seen such a message for a week. Patch is working, thanks!
I'm going to apply it to all servers.

**Comment by tvandergeer** [comment]
This looks promising. I've been following this issue, because it looks like [this issue](https://github.com/OpenSIPS/opensips/issues/2715) (previously linked here too)
In our case we're using MI as well, but in the other issue it was identified by @bogdan-iancu as a possible issue with rewriting the RURI. What do you think, could it be valuable to try this patch in our setup as well?

**Comment by liviuchircu** [comment]
Hey, @tvandergeer!  I took at look at that PKG memory leak issue... it doesn't seem related to this one.  Here, the problem is that OpenSIPS functions normally, even after getting the _"WARNING:fm_malloc:..."_ logs, however every time they occur, the associated de-fragmentation operation will impact performance and may cause some degree of stalling, which is undesirable...

**Comment by starlein** [comment]
I am not sure if this has been fully resolved.
It crashed after 5 times running mi command `reload_routes` in few minutes. 
Also having cron every minute running few mi commands to gather profiles load.
No other issues even under heavy load. Shared Memory or Pkg Memory usage always below 20%.

```
kernel: opensips[4860]: segfault at 0 ip 00007f3dd1eb18c1 sp 00007ffc7e8179c8 error 4 in libc-2.17.so[7f3dd1d42000+1c4000]
kernel: Code: 2e 0f 1f 84 00 00 00 00 00 31 c0 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 48 31 c0 89 f9 83 e1 3f 66 0f ef c0 83 f9 30 77 1d <f3> 0f 6f 0f 66 0f 74 c1 66 0f d7 d0 85 d2 0f 85 4e 02 00 00 48 89

INFO:core:reload_routing_script: reparsing routes from </etc/opensips/opensips.cfg> file
WARNING:core:fm_malloc: not enough contiguous free pkg memory (17776 bytes left, need 128), attempting defragmentation... please increase the "-M" command line parameter!
ERROR:core:fm_malloc: not enough free pkg memory (17776 bytes left, need 128), please increase the "-M" command line parameter!
CRITICAL:core:addstr: lex:addstr: memory allocation error
CRITICAL:core:sig_usr: segfault in process pid: 4860, id: 2
INFO:core:handle_sigs: child process 4860 exited by a signal 11
INFO:core:handle_sigs: core was not generated
INFO:core:handle_sigs: terminating due to SIGCHLD
INFO:core:sig_usr: signal 15 received
INFO:core:sig_usr: signal 15 received
INFO:core:sig_usr: signal 15 received
INFO:core:shutdown_opensips: process 1(4859) [event_stream Sender] terminated, still waiting for 11 more
INFO:core:shutdown_opensips: process 3(4861) [time_keeper] terminated, still waiting for 10 more
INFO:core:shutdown_opensips: process 4(4862) [timer] terminated, still waiting for 9 more
INFO:core:shutdown_opensips: process 13(4871) [TCP main] terminated, still waiting for 8 more
INFO:core:shutdown_opensips: process 5(4863) [SIP receiver udp:X.X.X.X:5060] terminated, still waiting for 7 more
INFO:core:shutdown_opensips: process 9(4867) [TCP receiver] terminated, still waiting for 6 more
INFO:core:shutdown_opensips: process 12(4870) [Timer handler] terminated, still waiting for 5 more
INFO:core:shutdown_opensips: process 10(4868) [TCP receiver] terminated, still waiting for 4 more
INFO:core:shutdown_opensips: process 11(4869) [Timer handler] terminated, still waiting for 3 more
INFO:core:shutdown_opensips: process 6(4864) [SIP receiver udp:X.X.X.X:5060] terminated, still waiting for 2 more
INFO:core:shutdown_opensips: process 7(4865) [SIP receiver udp:X.X.X.X:5060] terminated, still waiting for 1 more
INFO:core:shutdown_opensips: process 8(4866) [SIP receiver udp:X.X.X.X:5060] terminated, still waiting for 0 more
```

CentOS 7 using precompiled packages from yum repo.
