### ISSUE TITLE
[BUG] Registrar `max_contacts` Not Respected

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2727]
**OpenSIPS version you are running**
```
version: opensips 3.1.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 19:11:08 Jan 11 2022 with gcc 8
```

**Describe the bug**
When setting the module param `max_contacts` within the Registrar module, the value is not used if the script writer does not include flags when calling `save`.  For example: `save("location",,"test-user@test.domain")` will not limit the number of contacts under an AOR, even if global `max_contacts` is set.

**To Reproduce**
1. Set `modparam("registrar", "max_contacts", 1)`
2. Call `save(...)` without any flags
3. Send multiple REGISTERs with the same AOR
4. `mi ul_dump` will show all contacts are successfully saved under AOR. Likewise, you will get 200 OK response for all REGISTERs.

**Expected behavior**
Global `max_contacts` should be enforced even if flags aren't used, and UAC should receive back 503 in case of exceeded contacts.

**Proposed solution**
Here is a [patch](https://github.com/OpenSIPS/opensips/files/7849433/registrar-diff.txt) that seems to solve the issue.  It appears that max contacts is only set if flag parsing is done.

**OS/environment information**
 - Operating System: `Debian 11`
 - OpenSIPS installation: `nightly build -- currently 3.1.7`

**Comment by bogdan-iancu** [comment]
Thanks @john08burke for the patch. I will push it to GIT, but keep in mind that the fix must be extended to mid_registrar too, as it is also using the `reg_parse_save_flags()` function, see https://github.com/OpenSIPS/opensips/blob/master/modules/mid_registrar/save.c#L2530
