### ISSUE TITLE
[CRASH] Segmentation Fault 3.2.3

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2728]
**OpenSIPS version you are running**

```
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f32089b8c
main.c compiled on 03:23:36 Dec 24 2021 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/G5fLbxVa

**Describe the traffic that generated the bug**

No specific traffic pattern identified.

**To Reproduce**

Not able to reproduce at this time.

**Relevant System Logs**

https://pastebin.com/tning49h

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
The crash is related to the P-Asserted-Identity header (the received one) internal parsing. And this is done if using $ai variable in script or the sip_i, stir_shaken, sipcapture, osp and emergency modules
What's your case here ?

**Comment by bcnewlin** [comment]
We do access $ai in the script. We do not use any of the listed modules.

**Comment by bogdan-iancu** [comment]
OK, do you do it before / after any serial forking (failure route) ? or before any async script operation ?

**Comment by bcnewlin** [comment]
It is accessed before any forking/branching and also before any async functions. We do use both forking and async functions.

**Comment by bogdan-iancu** [comment]
do you access it also within failure route or after async ?

So you see any relation between the crash and getting to a point where this $ai is actually used?

**Comment by bogdan-iancu** [comment]
@bcnewlin , the posted backtrace shows the double free upon a timeout in TM (no final response), leading to an internal 408 which triggered the failure route.
I can extract from the corefile relevant info to identify the call if you want that. Maybe the SIP flow will give more info on how the double-free happened ; maybe a double passing via failure route??

**Comment by bcnewlin** [comment]
I don't need the call info for myself. It would depend on whether you have what you need or if you need me to try to reproduce the issue. With the call information (ideally the SIP Call-ID?) I can examine the call that was being processed and see if there is anything unusual or different about it in hopes of reproducing.

**Comment by bogdan-iancu** [comment]
OK, let;s try this:

```
f 12
p t
p t->callid
````

That should give you the callid. You can PM me the SIP capture of that call.

**Comment by bcnewlin** [comment]
Well this is quite interesting. I had assumed the SIP message in the backtrace was a fake one because it is an OPTIONS ping from the OpenSIPS instance, and our instances are not configured to send any OPTIONS pings. However, it is not a faked message. The instance did send a multiple OPTIONS pings within seconds of each other, all to the same destination. It appears they were triggered by the dispatcher module, as that is the only module that hosts the target of the ping.

I will need to investigate why OPTIONS pings were enabled for the module when we upgraded from 2.4 to 3.2 without making any changes to that module.

I have also sent the trace to you @bogdan-iancu, though this changes my answer a bit. We do have a failure route, which is triggering since there is no response to the OPTIONS, and we do use the event framework to raise an async event from the failure route. However, none of those paths access $ai and we still do not use any of the other modules you mentioned.

**Comment by bcnewlin** [comment]
I have figured out how the dispatcher pings were enabled. It was an old feature accidentally left enabled only in this environment.

**Comment by bcnewlin** [comment]
In reviewing our logs for the OPTIONS transaction, it looks like the seg fault probably occurred during processing of the event raised from the failure route. We have an xlog that prints in the failure_route after the event is raised which is present in the logs. We also have an xlog prints in the `event_route` is not.

The `event_route` only exists for logging. The other target of the raised event is a flatstore DB path.

While we don't access $ai, these are all the other OpenSIPS variables accessed by the code in the course of raising the event from the failure route:
```
$T_id
$T_branch_idx
$ci
$rm
$mf
$(<reply>rs)
$(<reply>rr)
$T_reply_code
```

**Comment by bogdan-iancu** [comment]
@bcnewlin, what puzzles me is the point of crash. As per your original post, the BT shows the crash in a double free of the parsed PAI hdr, after running the failure route for OPTIONS. Still you claim there is no such PAI hdr......and somehow I think this is the key of solving this issue.
So, hoping you still have the corefile, could you do:
```
f 9
p faked_req.len
p faked_req.buf
p faked_req.buf+50
p faked_req.buf+100
```
and keep doing +50 until you spot the end end of the buffer or you hit the upper limit `faked_req.len`.

Even more, in the same frame:
```
p faked_req.pai
p *faked_req.pai
p faked_req.pai->body
p (struct to_body*)faked_req.pai->parsed
p *((struct to_body*)faked_req.pai->parsed)
```

Let's see these by now.

**Comment by bcnewlin** [comment]
Here you go: https://pastebin.com/4zaWhWuZ

**Comment by bogdan-iancu** [comment]
Thank you @bcnewlin  and sorry for the delay here :(. The buffer of the fake SIP msg looks ok, and strangely, the PAI holder is empty.
Could you do a bit more printing from gdb:
```
f 7
p *hdr
````
I want to be sure there is about PAI hdr indeed.

BTW, this was one time crash, no idea about what could cause it (as traffic, flow, etc), right ?

**Comment by bcnewlin** [comment]
Here you go:

```
(gdb) f 7
#7  0x00007fe88f10cd9d in clean_msg_clone (msg=0x7fe88f388d40 <faked_req>, max=0x7fe894e0ef90, min=<optimized out>) at sip_msg.h:100
100	sip_msg.h: No such file or directory.
(gdb) p *hdr
$1 = {type = HDR_FROM_T, name = {
    s = 0x7fe894e0e7e7 "From: <sip:pcv-sipproxy-forward@10.27.14.100>;tag=ec8b90c75355aae82eb8c210619ba686-b3e3\r\nCSeq: 14 OPTIONS\r\nCall-ID: 5b2bfa627bfd8e73-9259@10.27.14.100\r\nMax-Forwards: 70\r\nContent-Length: 0\r\n\r\n", len = 4}, body = {
    s = 0x7fe894e0e7ed "<sip:pcv-sipproxy-forward@10.27.14.100>;tag=ec8b90c75355aae82eb8c210619ba686-b3e3\r\nCSeq: 14 OPTIONS\r\nCall-ID: 5b2bfa627bfd8e73-9259@10.27.14.100\r\nMax-Forwards: 70\r\nContent-Length: 0\r\n\r\n", len = 81}, len = 89, parsed = 0x7fe8d495ed60, next = 0x7fe8d497ac50, sibling = 0x0}
```

This has only occurred one time and we do not know the specific scenario that caused it as the environment is used for various low traffic at all times. It appears to have been coincident with the use of OPTIONS pinging from the dispatcher module, which we only use when a destination is disabled and only in this one environment, so it is not a common occurrence. So to me that seems like the most likely culprit.

**Comment by bogdan-iancu** [comment]
ha, ha, I'm glad I asked, as the lines (as per BT) pointing to PAI hdr were wrong indication. It seem after all to be FROM hdr related. Could we do in frame 9:

```
f 9
p faked_req.from
p *faked_req.from
p faked_req.from->body
p (struct to_body*)faked_req.from->parsed
p *((struct to_body*)faked_req.from->parsed)
```
Thanks, Bogdan

**Comment by bcnewlin** [comment]
```
(gdb) f 9
#9  run_failure_handlers (t=<optimized out>) at t_reply.c:612
612	t_reply.c: No such file or directory.
(gdb) p faked_req.from
$1 = (struct hdr_field *) 0x7fe8d497ac08
(gdb) p *faked_req.from
$2 = {type = HDR_FROM_T, name = {
    s = 0x7fe894e0e7e7 "From: <sip:pcv-sipproxy-forward@10.27.14.100>;tag=ec8b90c75355aae82eb8c210619ba686-b3e3\r\nCSeq: 14 OPTIONS\r\nCall-ID: 5b2bfa627bfd8e73-9259@10.27.14.100\r\nMax-Forwards: 70\r\nContent-Length: 0\r\n\r\n", len = 4}, body = {
    s = 0x7fe894e0e7ed "<sip:pcv-sipproxy-forward@10.27.14.100>;tag=ec8b90c75355aae82eb8c210619ba686-b3e3\r\nCSeq: 14 OPTIONS\r\nCall-ID: 5b2bfa627bfd8e73-9259@10.27.14.100\r\nMax-Forwards: 70\r\nContent-Length: 0\r\n\r\n", len = 81}, len = 89, parsed = 0x7fe8d495ed60, next = 0x7fe8d497ac50, sibling = 0x0}
(gdb) p faked_req.from->body
$3 = {
  s = 0x7fe894e0e7ed "<sip:pcv-sipproxy-forward@10.27.14.100>;tag=ec8b90c75355aae82eb8c210619ba686-b3e3\r\nCSeq: 14 OPTIONS\r\nCall-ID: 5b2bfa627bfd8e73-9259@10.27.14.100\r\nMax-Forwards: 70\r\nContent-Length: 0\r\n\r\n", len = 81}
(gdb) p (struct to_body*)faked_req.from->parsed
$4 = (struct to_body *) 0x7fe8d495ed60
(gdb) p *((struct to_body*)faked_req.from->parsed)
$5 = {error = 13, body = {s = 0x4500000001 <error: Cannot access memory at address 0x4500000001>, len = 11164544}, uri = {
    s = 0x6 <error: Cannot access memory at address 0x6>, len = 11164551}, display = {s = 0x34 <error: Cannot access memory at address 0x34>, len = 11164604},
  tag_value = {s = 0x7 <error: Cannot access memory at address 0x7>, len = 1}, parsed_uri = {user = {s = 0x7fe8d4979aa8 "2022-01-11T11:43:56.115170Z",
      len = 0}, passwd = {s = 0x7fe8d49755c8 "", len = -728277448}, host = {
      s = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, len = -728278888}, port = {s = 0x0, len = -728278768}, params = {
      s = 0x7fe8d49755c8 "", len = -728279368}, headers = {s = 0x7fe8d4975988 "\030", len = -728277088}, port_no = 25800, proto = 54423, type = 32744,
    transport = {s = 0x0, len = 0}, ttl = {s = 0x0, len = -728277208}, user_param = {
      s = 0x7fe8d4975e38 "io 24052 RTP/AVP 0 96 101 102\r\na=rtpmap:96 opus/48000/2\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=rtpmap:102 telephone-event/48000\r\na=fmtp:102 0-15\r\na=sendrecv\r\n", len = 0}, maddr = {s = 0x0, len = 0}, method = {s = 0x0, len = 0}, lr = {s = 0x0, len = 0}, r2 = {
      s = 0x0, len = 0}, gr = {s = 0x0, len = 0}, pn_provider = {s = 0x0, len = 0}, pn_prid = {
      s = 0x7fe8d4975eb0 "2 telephone-event/48000\r\na=fmtp:102 0-15\r\na=sendrecv\r\n", len = 0}, pn_param = {s = 0x0, len = 0}, pn_purr = {s = 0x0,
      len = 0}, transport_val = {s = 0x0, len = 0}, ttl_val = {s = 0x0, len = 0}, user_param_val = {s = 0x0, len = 0}, maddr_val = {s = 0x0, len = 0},
    method_val = {s = 0x0, len = 0}, lr_val = {s = 0x0, len = 0}, r2_val = {
      s = 0xaa5d8f <buf+527> "r-Agent: purescale-sip-zombie (ind-carrier-vpn)\r\nContent-Length: 0\r\nx-gcv-cnv-id: 9c39ff1a-a867-49dd-9832-38d003dbd3b9\r\n\r\n", len = 11165071}, gr_val = {s = 0x400000002 <error: Cannot access memory at address 0x400000002>, len = 637981458}, pn_provider_val = {s = 0x0, len = 2},
    pn_prid_val = {s = 0x640e1b0a <error: Cannot access memory at address 0x640e1b0a>, len = 0}, pn_param_val = {
      s = 0x113c4951e <error: Cannot access memory at address 0x113c4951e>, len = 0}, pn_purr_val = {
      s = 0x2606d3121e950002 <error: Cannot access memory at address 0x2606d3121e950002>, len = 0}, u_name = {{
        s = 0x1 <error: Cannot access memory at address 0x1>, len = 5586045}, {s = 0x7fe8d490dea0 "i", len = 11164544}, {
        s = 0x3c1 <error: Cannot access memory at address 0x3c1>, len = -728273816}, {s = 0x26 <error: Cannot access memory at address 0x26>,
        len = -728427936}, {s = 0x15 <error: Cannot access memory at address 0x15>, len = -1}, {s = 0x7fe8d490dea0 "i", len = 0}, {s = 0x0, len = 0}, {
        s = 0xaa5b8b <buf+11> " Not Found\r\nVia: SIP/2.0/UDP 10.27.14.100:5060;branch=z9hG4bKbf04.1a58c892.0;i=cb123cb\r\nVia: SIP/2.0/TCP 10.25.190.208:5060;rport=53640;received=34.203.96.250;branch=z9hG4bK916561214SU5JTi9pM3NpcC4t_1"..., len = 11}, {s = 0x0, len = 0}, {
        s = 0xaa5b97 <buf+23> "Via: SIP/2.0/UDP 10.27.14.100:5060;branch=z9hG4bKbf04.1a58c892.0;i=cb123cb\r\nVia: SIP/2.0/TCP 10.25.190.208:5060;rport=53640;received=34.203.96.250;branch=z9hG4bK916561214SU5JTi9pM3NpcC4t_1683067006_\r\n"..., len = 17}}, u_val = {{
        s = 0xaa5ba9 <buf+41> "0.27.14.100:5060;branch=z9hG4bKbf04.1a58c892.0;i=cb123cb\r\nVia: SIP/2.0/TCP 10.25.190.208:5060;rport=53640;received=34.203.96.250;branch=z9hG4bK916561214SU5JTi9pM3NpcC4t_1683067006_\r\nTo: <sip:131750000"..., len = 4}, {
        s = 0xaa5bae <buf+46> "14.100:5060;branch=z9hG4bKbf04.1a58c892.0;i=cb123cb\r\nVia: SIP/2.0/TCP 10.25.190.208:5060;rport=53640;received=34.203.96.250;branch=z9hG4bK916561214SU5JTi9pM3NpcC4t_1683067006_\r\nTo: <sip:13175000000@vo"..., len = 13}, {s = 0x0, len = 0}, {
        s = 0x1000113c4 <error: Cannot access memory at address 0x1000113c4>, len = 11164590}, {s = 0xd <error: Cannot access memory at address 0xd>,
        len = 0}, {s = 0x0, len = 0}, {s = 0x0, len = 0}, {s = 0x0, len = 0}, {s = 0x0, len = 0}, {s = 0x0, len = 0}}, u_params_no = 0}, param_lst = 0x0,
  last_param = 0x0, next = 0x0}
  ```

**Comment by bcnewlin** [comment]
Bumping to remove the stale label.

**Comment by bcnewlin** [comment]
@bogdan-iancu Have you had any chance to look further into this?

**Comment by bcnewlin** [comment]
Bumping to remove the stale label.

**Comment by bogdan-iancu** [comment]
In process of validating the fix
