### ISSUE TITLE
[FEATURE] SIPREC and media_exchange with RTPEngine (RTPEngine "subscribe request" support)

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2732]
**Is your feature request related to a problem? Please describe.**
Right now opensips only support SIPREC with rtpproxy mediarelay. It would be great if SIPREC will be supported while using rtpengine, or, at least if rtpengine's "subscribe request" feature will be supported (rtpengine support added to media_exchange module).

**Describe the solution you'd like**
Rtpengine now have "subscribe request" feature which allows to fork media from call participants to some destination using offer/answer model. It ideally fits for situations when its required to fork media to SIP-capabe destinations (like functions provided by media_exchange module) and could be used for SIPREC implementation.

Link to feature:
https://github.com/sipwise/rtpengine#subscribe-request-message
https://github.com/sipwise/rtpengine#subscribe-answer-message
https://github.com/sipwise/rtpengine#unsubscribe-message

**Comment by razvancrainea** [comment]
Thanks for the request @achalkov, this is actually work in progress :).

**Comment by achalkov** [comment]
glad to hear, @razvancrainea  :)
any ETA for that (or maybe open sips version) ?

**Comment by razvancrainea** [comment]
It should be available in the new release (3.3).

**Comment by achalkov** [comment]
great, thank you. we are looking forward to see new features :)

**Comment by razvancrainea** [comment]
Commit 0df4c3e introduces support for this, and can be used with all `media_fork_*` functions.
