### ISSUE TITLE
[CRASH] OpenSIPs 3.2.4 latest Stable

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#2733]
**OpenSIPS version you are running**

```
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7

```

**Crash Core Dump**

https://pastebin.com/JhuZGr4E

**Describe the traffic that generated the bug**

We noticed Opensips in locked state with 100% CPU Utilisation.

**OS/environment information**
 - Operating System: Ubuntu 18.04.6 LTS
 - OpenSIPS installation: debs

**Comment by razvancrainea** [comment]
Do you see any errors in your logs?
Can you still open the old crash dump, to inspect it with gdb?

Best regards,
Răzvan
