### ISSUE TITLE
[FEATURE] Diameter <-> Json converter

### ISSUE THREAD

**Issue by fedkis** [OpenSIPS/opensips#2738]
Hello All!
I see Opensips added support of Freediameter library.
Do you have any plan to make a  simple Diameter <-> Json converter like Kamailio implemented https://www.kamailio.org/docs/modules/devel/modules/ims_diameter_server.html ?
Now I am parsing Diameter directly in Python but working with Json would make it easier. This would give a new market to opensips

If yes , then the dream of having HSS requests/responses over rest api would come true:)

**Comment by fedkis** [comment]
Diameter <-> Json converter

**Comment by liviuchircu** [comment]
Hi, @fedkis!  This issue dodged my radar somehow -- yes, the "JSON-based Diameter packets" feature is on the list and should make it into 3.3.

**Comment by liviuchircu** [comment]
This feature successfully made it into 3.3, check out the new [dm_send_request()](https://opensips.org/docs/modules/3.4.x/aaa_diameter.html#func_dm_send_request) function.
