### ISSUE TITLE
[CRASH] in 3.2.4 using RTP_relay and RTPEngine with wrong options

### ISSUE THREAD

**Issue by telematico** [OpenSIPS/opensips#2740]
**OpenSIPS version you are running**

```
Official DEB packaes for Debian 11
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10
```

**Crash Core Dump**

                Stack trace of thread 461045:
                #0  0x00007f03c3d7f4b2 n/a (rtp_relay.so + 0x54b2)
                #1  0x00007f03c3d863fa n/a (rtp_relay.so + 0xc3fa)
                #2  0x00007f03c470893c run_trans_callbacks (tm.so + 0x3193c)
                #3  0x00007f03c47166e2 relay_reply (tm.so + 0x3f6e2)
                #4  0x00007f03c4717425 reply_received (tm.so + 0x40425)
                #5  0x0000557283f4ac08 forward_reply (opensips + 0x49c08)
                #6  0x0000557283f88a6f receive_msg (opensips + 0x87a6f)
                #7  0x00007f03c47688c5 n/a (proto_wss.so + 0xd8c5)
                #8  0x000055728408ce0a n/a (opensips + 0x18be0a)
                #9  0x000055728408e4d3 tcp_worker_proc_loop (opensips + 0x18d4d3)
                #10 0x0000557284086656 tcp_start_processes (opensips + 0x185656)
                #11 0x0000557283f20d66 main (opensips + 0x1fd66)
                #12 0x00007f03e07d7d0a __libc_start_main (libc.so.6 + 0x26d0a)
                #13 0x0000557283f215fa _start (opensips + 0x205fa)
**Describe the traffic that generated the bug**

**To Reproduce**

Send an invite and receive answer using rtp_relay and retngine moduleswith wrong options in variables.
In my example I use the wrong option transcode-PCMU (right is transcode=PCMU)
      $rtp_relay = "rtcp-mux-offer ICE=force transcode-PCMU transcode=PCMA transcode=G722 SDES=off UDP/TLS/RTP/SAVP";
      $rtp_relay_peer = "rtcp-mux-demux ICE=remove RTP/AVP";
     rtp_relay_engage("rtpengine");

The crash happens when response is received (CANCEL or 200 OK) not in provisional replys (100 or 180)

rtpengine module is configured in this case using new protocol:
modparam("rtpengine", "rtpengine_sock", "udp:10.x.x.x:22222")

**Relevant System Logs**

Opensips log says:
```
ERROR:rtpengine:parse_flags: error processing flag `transcode-PCMU': no more memory
CRITICAL:core:sig_usr: segfault in process pid: 461045, id: 13
```

**OS/environment information**
 - Operating System:  Debian 11 in AWS
 - OpenSIPS installation:  Official DEB packages
 - other relevant information:
Using WSS and wolfSSL
**Additional context**

**Comment by telematico** [comment]
Sorry for not be very clear in the original report. 
Examining the full BT ( [https://pastebin.com/QU3SBpWk](https://pastebin.com/QU3SBpWk) ) I see the real problem is rtp_relay is trying to free a session and produces a crash.
It happens after a negative response to 200 OK. In this case the response is 488 because non-compatible codecs

**Comment by razvancrainea** [comment]
Unfortunately the core dump is no longer available :(. Can you re-run the test and provide a new backtrace?
