### ISSUE TITLE
unable to register a user

### ISSUE THREAD

**Issue by 123srikanth** [OpenSIPS/opensips#2747]
Hi there, I have installed opensips on a aws instance and I have generated the resedential scripts to route the calls. In opensips.cfg file I have given socket as socket=udp:172.31.10.74:5060 and HTTPD module as modparam("httpd", "ip", "127.0.0.1") but I'm not able to register any user with any softphones. The user I'm creating is alice@172.31.10.74 with domain as 172.31.10.74 which is the private ip of the instance. Can someone help me to figure out where I'm making a mistake, as I'm not able to route the calls unless the users are registered.

**Comment by ovidiusas** [comment]
Please post your questions on the user mailing list: users@lists.opensips.org. The issues tracker is for bugs.
