### ISSUE TITLE
[CRASH] error: Cannot access memory at address 0x6172623b30363035

### ISSUE THREAD

**Issue by farmorg** [OpenSIPS/opensips#2754]
**OpenSIPS version you are running**

```
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b7c9aa588
main.c compiled on 13:54:35 Feb 17 2022 with gcc 9
```

**Crash Core Dump**

Attached

**Describe the traffic that generated the bug**

Unsure but using TLS/SIP & UDP/SIP

**To Reproduce**

1. Start OpenSIPS
2. Attempt a call which never completes
3. Cancel failed call
4. Wait a few seconds
5. Watch log

**Relevant System Logs**

```CRITICAL:core:sig_usr: segfault in process pid: 74460, id: 11```
```WARNING:core:utimer_ticker: utimer task <tm-utimer> already scheduled 170 ms ago (now 110130 ms), delaying execution```

**OS/environment information**
 - Operating System: `Ubuntu 20.04.3 LTS'
 - OpenSIPS installation: `git`
[crash-1.txt](https://github.com/OpenSIPS/opensips/files/8089494/crash-1.txt)

**Comment by bogdan-iancu** [comment]
Hi @farmorg , based on the backtrace info, it seems you hit some memory allocation issue (it looks like a double free). You use an older 3.2 version, the current one is 3.2.5 (see https://www.opensips.org/About/Version-3-2-x).
Try first to upgrade to latest 3.2.5 and see if the crash still occurs (as I remember some meanwhile fix in that area)

**Comment by bogdan-iancu** [comment]
@farmorg , let's close it for now as I see no way to investigate further - please do the upgrade to latest 3.2 and if the issue pops up again, open a new report. Thanks!
