### ISSUE TITLE
Is there an Lua example?

### ISSUE THREAD

**Issue by hance2010** [OpenSIPS/opensips#2769]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Implementation**
 
  - Component: 
  - Type: 
  - Name: 

**Describe alternatives you've considered**

**Additional context**

```
#opensips3.2.5
#opensips.cfg
...
loadmodule "lua.so"
modparam("lua", "luafilename", "/etc/opensips/opensips.lua")

route {
    ...
    lua_exec("luatest");
}

#opensips.lua
function luatest()
    local id = getpid()   --  siplua: siplua error running function luatest: /etc/opensips/opensips.lua:7: attempt to call global 'getpid' (a nil value)
end




```

**Comment by razvancrainea** [comment]
Could you please advise what version of lua you are using?

**Comment by hance2010** [comment]
debian10,
lua5.1

**Comment by razvancrainea** [comment]
Did you sort this out? If so, can you please detail the solution, in case someone else hits the same issue? Thanks!
