### ISSUE TITLE
[FEATURE] SIPREC - Failover between multiple SRS not working when SRS down

### ISSUE THREAD

**Issue by SlowHusky** [OpenSIPS/opensips#2772]
**Is your feature request related to a problem? Please describe.**

Yes,

In SIPREC module the feature of failover between multiple SRS servers does not work correctly.

After a test, we've found that the OpenSIPS will not try the next SRS in the list if the SRS tried does not answer at all (unreachable / turned off / malfunctioning ).

In the SIPREC Module documentation we read in section 1.4 of the document:
The siprec module supports failover between multiple SRS servers - when calling the siprec_start_recording() function, one can provision more SRS URIs, separated by comma. In this case, OpenSIPS will try to use them in the same order specified, one by one, until either one of them responds with a positive reply (200 OK), or the response code is one of the codes matched by the skip_failover_codes regular expression. In the latter case the call is not recorded at all.

Test carried out with:

- Opensips 3.1.7
- SIPREC Module 3.1.7

**Describe the solution you'd like**

When a SRS does not reply to INVITE from OpenSIPS (SRC) OpenSIPS must try the following SRS in the list of Servers.

**Implementation**
 
  - Component:  SIPREC Module
  - Type:  Function

**Comment by razvancrainea** [comment]
Can you please provide DEBUG logs for this behavior?

**Comment by SlowHusky** [comment]
[opensipslog.txt](https://github.com/OpenSIPS/opensips/files/8223695/opensipslog.txt)
![SnapshotFailedSiprecCall](https://user-images.githubusercontent.com/11680580/157670202-9aba5260-7b7e-47e3-ad85-3192f0288bf3.png)

**Comment by razvancrainea** [comment]
This has been most likely sorted out in a970903. If the problem persists, please re-open the ticket with new information.
