### ISSUE TITLE
[BUG] uac_registrant wrong proposal on ERROR log

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2775]
**OpenSIPS version you are running**
```
version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9a0a3b728
main.c compiled on 18:37:54 Mar  5 2022 with gcc 10
```

I have configured Opensips to register to a remote SIP Server and as I was playing around with "Expires" value I figured out that if I put "100" as an expiry value on db the ERROR on logs should say **increase** not **decrease**  ;-)

**Relevant System Logs**

`ERROR:uac_registrant:load_reg_info_from_db: Please **decrease** timer_interval=[100] - requested expires=[100] to small for AOR=[sip:+XXXXX@XXXXXXX]`

Thanks alot guys

Vasilios Tzanoudakis

**Comment by vasilevalex** [comment]
The log message is correct. uac_registrant sends bulks of REGISTER messages every `timer_interval` and if "Expires" is less or equal to "timer_interval", so the registration will expire faster, then next REGISTER message is sent. That's why you need to *decrease* `timer_interval` to send messages more often.

**Comment by vtzan** [comment]
Dear @vasilevalex ,

Great! That makes sense now. I misunderstood 😕 that I had to play with timer_interval for some reason. Thanks alot for pointing that out.

Regards 

Vasilios Tzanoudakis
