### ISSUE TITLE
[BUG] Memory Leak - $DLG_timeout

### ISSUE THREAD

**Issue by HichamINOX** [OpenSIPS/opensips#2788]
Hi,

in my scenario i tried to avoid dialog stuck in state 3, waiting ACK.

I start a dialog with $DLG_timeout=5; when the timeout dlg_on_timeout("session_ack_check");
  route[session_ack_check] 
         {
             if ($DLG_status==4 && $DLG_lifetime < 10)
                     {
                      $DLG_timeout = 7200;
                     }               
          }

When I use this simple code, all dialogs stuck in memory in state 5 and not destroyed. no matter what db_mode used,until the shm is 100% used.

Questions :   How to manage properly a missing ACK ?

OS/environment information : Debian 9.13
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f4c0726c8

**Comment by liviuchircu** [comment]
Hi, @HichamINOX!  Version `3.1.0` is from **a long** time ago (July 2020), so that's almost two years worth of fixes you're missing out on there.  I strongly suggest upgrading to `3.1.8` (or `3.1.9` after Wednesday), and seeing if you can still reproduce the bug.

Regarding your general question on ACK / dialog timeout management:  it's enough to:

1. set a low `$DLG_timeout` on initial INVITE (`5` seconds is perfect, just like you did)
2. on ACK, simply bump the `$DLG_timeout` to a normal value, say `7200` seconds.

But, still, the `dlg_on_timeout()` logic should never leak memory or dialogs.  If you can still reproduce that one, then we have a bug on our hands.

Cheers!

**Comment by HichamINOX** [comment]
Hi @liviuchircu 

I tested with "version: opensips 3.2.5" the problem seems to be fixed in this version, in version 3.1 I can reproduce the problem only with increasing $DLG_timeout, the bug it's not related to dlg_on_timeout.

Regarding my question on ACK:
I think dlg_on_timeout is necessary, if we have RE-INVITE i think we well increase timeout as long as there are RE-INVITE and ACK's, is not easy to manage.

in my opinion a dialogue in state 3 which remains until the general timeout,  it's not supposed to happen, it would have been better if it managed by Opensips with a specific timeout parameter.

Thanks for your help.

**Comment by HichamINOX** [comment]
Hi @liviuchircu 

Sorry for my previous feedback, my tests are incorrects. Finally I was able to reproduce the problem with version 3.2.5.

When i use `dlg_on_timeout()` the call stuck in state:5, the value of `$DLG_timeout` is weird when I log it after timeout trigerred.

 if ($DLG_status==4 && $DLG_lifetime < 10)
        {
        xlog("Debug: Increase timeout from [$DLG_timeout]\n");
        $DLG_timeout = 7200;
        xlog("Debug: Increase timeout To [$DLG_timeout]\n");
        }
 Apr 19 15:42:19 ip- /usr/sbin/opensips[23069]: Debug: Increase timeout from [18446744073709551595]
Apr 19 15:42:19 ip- /usr/sbin/opensips[23069]: Debug: Increase timeout To [7200]

**Comment by ankogan** [comment]
Hello!
I confirm the issue - I have shared memory leak when set $DLG_timeout in dlg_on_timeout() route.
Version is 3.2.5, but I made diffs with master - there are no changes affected the issue...

**Comment by bogdan-iancu** [comment]
@HichamINOX , @ankogan , can any of you post a minimal cfg snippet that reproduces this leak ?

**Comment by liviuchircu** [comment]
Hi all,

This seems to be an issue, indeed, as I managed to reproduce on 1st try.  Just use something like:

```
route {
    ...

    if (is_method("INVITE")) {
        record_route();
        create_dialog("B");
        do_accounting("log", "cdr|failed");

        $DLG_timeout = 1;

        sethostport("127.0.0.1:7050");

        dlg_on_timeout("dlg_timeout");
    } else {
        sl_send_reply(501, "Not Implemented");
        exit;
    }

    route(relay);
}

route [dlg_timeout]
{
    xlog("XXX dlg timeout route:  $DLG_status / $DLG_lifetime / $DLG_timeout\n");

    if ($DLG_status == 4 && $DLG_lifetime < 10) {
        xlog("XXX prolonging with 2 hours\n");
        $DLG_timeout = 7200;
    }
}
```

Notice that the xlog() prints the following, which means that the `$DLG_timeout` has a negative value for some reason (`-7`), at the time of the internally triggered timeout:

```
Sep  6 15:56:42 [150796] XXX dlg timeout route:  4 / 2 / 18446744073709551589
Sep  6 15:56:42 [150796] XXX prolonging with 2 hours
```

**Comment by ankogan** [comment]
@bogdan-iancu here it is:
`...
modparam("cfgutils", "varset", "no_ack_timeout=i:5")
...
route {
...
    # Process initial INVITE
    if( is_method( "INVITE" ))
    {
...
        if(!create_dialog("EB")) {
            t_reply(400, "Bad request");
            xlog("L_INFO", "<--exit-- route[]: $ci $rm");
            exit;
        }
        $DLG_timeout = $var(no_ack_timeout);
        dlg_on_timeout( "no_ack_timeout" );
...
}

route[ no_ack_timeout ] {
    xlog("L_INFO", "--> route[ no_ack_timeout ] $ci");

    if($DLG_status >= 4) {
        $DLG_timeout = 7200;
    }
    xlog("L_INFO", "<-- route[ no_ack_timeout ] $ci");
}
`

**Comment by bogdan-iancu** [comment]
@HichamINOX , @liviuchircu , thanks for the info here, I managed to reproduce and finally fix the issue - the backports are also available.
