### ISSUE TITLE
A possible commucation deadlock

### ISSUE THREAD

**Issue by ryancaicse** [OpenSIPS/opensips#2789]
Hi, in the below code, it is possible for the thread to signal first and, later, the thread goes to the waiting site forever without signal notified anymore. 
https://github.com/OpenSIPS/opensips/blob/1f55d05c2b786ee8cca227ff367d49145bed51a4/modules/aaa_diameter/aaa_impl.c#L194-L196

https://github.com/OpenSIPS/opensips/blob/1f55d05c2b786ee8cca227ff367d49145bed51a4/modules/aaa_diameter/aaa_impl.c#L1242-L1244

**To avoid this problem, the recommended usage of thread_cond_signal and thread_cond_wait would be**

```
pthread_mutex_t count_lock;
pthread_cond_t count_nonzero;
unsigned count;

decrement_count()
{
    pthread_mutex_lock(&count_lock);
    while (count == 0)
        pthread_cond_wait(&count_nonzero, &count_lock);
    count = count - 1;
    pthread_mutex_unlock(&count_lock);
}

increment_count()
{
    pthread_mutex_lock(&count_lock);
    if (count == 0)
        pthread_cond_signal(&count_nonzero);
    count = count + 1;
    pthread_mutex_unlock(&count_lock);
}
```

**Comment by ryancaicse** [comment]
@liviuchircu Could you take a look? Thanks

**Comment by liviuchircu** [comment]
Thank you for the suggestion, @ryancaicse - that's a perfectly valid race condition you caught there.  And your fix was spot on!
