### ISSUE TITLE
opensips crash on receipt of a PUBLISH message

### ISSUE THREAD

**Issue by jonhvoxbox** [OpenSIPS/opensips#2793]
**OpenSIPS version you are running**

version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 209218c91
main.c compiled on 10:43:24 Mar 29 2022 with gcc 10

```
```

**Crash Core Dump**

**Describe the traffic that generated the bug**

**To Reproduce**

**Relevant System Logs**

**OS/environment information**
 - Operating System: <!Debian 11 Bullseye container-->
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by jonhvoxbox** [comment]
Its now creating core dumps, I will add shortly. It seems to be due to an invalid PUBLISH header but useful to know.

**Comment by jonhvoxbox** [comment]
Please find the Crash core dump here;
https://pastebin.com/X0NsCHUR

**Comment by jonhvoxbox** [comment]
Again it is caused when a PUBLISH message is sent to opensips. I assume its an issue with the PUBLISH message itself and its format potentially?

**Comment by bogdan-iancu** [comment]
@jonhvoxbox , the code responsible for the crash looks a bit odd to me. Is there a way to reproduce this crash? or at leas to try a fix ?

**Comment by bogdan-iancu** [comment]
BTW, do you still have the corefile for further investigation ?
