### ISSUE TITLE
[BUG] no more nonces can be generated

### ISSUE THREAD

**Issue by dronord** [OpenSIPS/opensips#2800]
**OpenSIPS version you are running**
version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 00:41:16 Feb 24 2022 with gcc 4.8.5

**Describe the bug**
Couldn't find 'WWW-Authenticate' in 401

**To Reproduce**
sipp -r 4000 REGISTERs auth through db.
option -r 4000 - rate 4000 requests in second

**Relevant System Logs**
ERROR:auth:challenge: no more nonces can be generated

**OS/environment information**
 - Operating System: centos 7.9.2009
 - OpenSIPS installation: yum.opensips.org

One more question. Can't install opensips from yum.opensips.org for centos 8.
dnf install opensips error: nothing provides libm.so.6(GLIBC_2.29)(64bit) needed by opensips-3.2.5-1.el8.x86_64
in 8 last version glibc-2.28-196.el8.x86_64
what about centos 9?)

**Comment by bogdan-iancu** [comment]
@dronord , what the is the "nonce_expire" value you have set? As it looks like your testing rate exhausts the pool of nonce-indexes. Like if you use the 30 secs default value, at a 4000 authentications per second, means you need 30 * 4000 = 120 000 nonce-indexes. And the pre-configured value in OpenSIPS is 100 000, see [here](https://github.com/OpenSIPS/opensips/blob/3.2/modules/auth/auth_mod.h#L35).
So, you can change that and recompile or you can [disable the nonce re-usage check](https://opensips.org/html/docs/modules/3.2.x/auth.html#idp5903488) during your test.

**Comment by bogdan-iancu** [comment]
Is #2802 related to this/you ?

**Comment by dronord** [comment]
Thanks you guys!
