### ISSUE TITLE
[FEATURE] Topology Hiding never use dialog module

### ISSUE THREAD

**Issue by Josh-vxt** [OpenSIPS/opensips#2801]
**Is your feature request related to a problem? Please describe.**  

The original problem was that SIP Route headers were not updated on re-Invites by our media server (Asterisk) and websocket clients.
This lead us to the solution of using the topo_hiding module which has fixed that problem as all route information is now encoded in the contact header.

However, we are wanting to use the load_balancer module which requires the dialog module. Having the dialog module loaded changes the behaviour of the topo_hiding module to store information within a dialog instead of on the contact header - which we do not want.
We have several border Sip routers that operate statelessly with very little use of dialogs. We do not use or intend to use dialog replication as that just adds more complexity to these routers than needed.
 

**Describe the solution you'd like**

Some way to disable dialog support in topo_hiding, so the contact header is always used to store route information.

**Implementation**

Currently I think the best implementation would be to add a new parameter for the topo_hiding module. Perhaps similar to [force_dialog](https://opensips.org/html/docs/modules/3.2.x/topology_hiding.html#param_force_dialog), however named something like `never_use_dialog`.

**Describe alternatives you've considered**

An alternative solution is to disable the dialog module - however that isn't possible if you use the load_balancer or other modules that depend on the dialog module being loaded

Another solution is to use dialog replication however that adds more complexity which we do not want to have in our stateless routers.

**Context**

We have some C experience and could definitely help out with writing the pull request that implements this feature

**Comment by bogdan-iancu** [comment]
As I understand, you have to use the dialog module because of the load-balancing module, right? If so,  isn't the load-balancing and the TH applied over the same calls?

**Comment by Josh-vxt** [comment]
That is correct.

However we want to use the topo_hiding module as if it wasn't using the dialog module (so all routing information is stored in the contact header).
This means we can have an INVITE transaction processed by one of our routers and a BYE transaction processed by another.

**Comment by bogdan-iancu** [comment]
Maybe I'm missing something, but something does not make sense here. IF you are using the LB module, it requires the dialog module, so it requires to have the INVITE and BYEs of the same call on the same machine. Otherwise the dialog module will not work, and sequentially the LB module will not work.
So this "we can have an INVITE transaction processed by one of our routers and a BYE transaction processed by another" conflicts with doing LB.

**Comment by Josh-vxt** [comment]
Ahh okay that could be a problem, we might have misinterpreted how much the load-balancer module actually relies on the dialog module. In our testing it seemed to work okay with even when we had an INVITE processed by one router and a BYE with another. Is there a particular problem that could arise from doing it this way?

Do you think a better approach will be to enable some form of dialog replication between the sip routers, perhaps with the [clusterer](https://opensips.org/docs/modules/3.2.x/clusterer.html) module? 

P.s. Thanks for your help, we are rather new to Opensips still and are in the process of expanding our infrastructure to be more fault tolerant

**Comment by bogdan-iancu** [comment]
@Josh-vxt , depends on what you are trying to achieve here... of course, using dispatcher will remove the need of keeping a dialog state. But how comes you may have requests landing on different LB/dispatcher OpenSIPS boxes ? another dispatcher in front ? anycast ? or ?

**Comment by Josh-vxt** [comment]
We use a [Google TCP Proxy Load-balancer](https://cloud.google.com/load-balancing/docs/tcp) which has an anycast IP in front of it. It proxies traffic to the closest Sip router in one of the Google's regions. We use TCP for all of our Sip signalling.

However it is possible that during either server updates or due to a fault, one of our Sip routers could die. This would cause traffic to get redirected to the next closest one, which would hopefully be able to take over. If this happens within a transaction then we have accepted that there is not much that can be done.
Although it is much more likely to happen during a dialog, and that is why we might have different transactions hitting different Sip routers.

Another possibility is that a user/upstream-server is located perfectly between two Google regions and so it's a lottery which Sip router will receive the traffic.

Let me know if there is any more information that might be relevant and thanks again for your help.

**Comment by bogdan-iancu** [comment]
just an idea - if you want to do accurate balancing (and not simple dispatching), you will have to use the LB module (in order to count the calls). Further, what you can do, is to put the dialogs (of all the LB servers) into a cluster, for sharing - just give it a try, it may be something useful.
For now, as per its topic, I will close this ticket as invalid
