### ISSUE TITLE
[CRASH] opensips 3.2.4  crash two times at one B2BUA call to IMS

### ISSUE THREAD

**Issue by Zsm1982** [OpenSIPS/opensips#2813]
OpenSIPS version you are running

version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a5d8ba8
main.c compiled on 17:37:24 Feb 15 2022 with gcc 4.8.5

https://pastebin.com/TxaaNx9e

https://pastebin.com/2NpMZeSM 

Describe the traffic that generated the bug

Open the B2BUA mode of opensips,and this crash is triggered when no one answers

To Reproduce

reproducible,This bug reappeared for two consecutive days

OS/environment information

OS Vesion :CentOS Linux release 7.5.1804 (Core)
Kernel: 3.10.0-862.el7.x86_64

OpenSIPS installation: git

other relevant information:

**Comment by bogdan-iancu** [comment]
@Zsm1982 , are you using both b2b and dialog modules in the same time (for the same call) ??

**Comment by Zsm1982** [comment]
No，I only use b2b modules&nbsp; in the same time (for the same call).
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;the&nbsp;enclosure is the opensips scripts
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, May 2, 2022 09:10 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [OpenSIPS/opensips] [CRASH] opensips 3.2.4  crash two times at one B2BUA call to IMS (Issue #2813)

&nbsp;



 
@Zsm1982 , are you using both b2b and dialog modules in the same time (for the same call) ??
