### ISSUE TITLE
Fix handling dialog info XML documents with multiple dialog elements

### ISSUE THREAD

**Issue by dsandras** [OpenSIPS/opensips#2815]
The attached 1.8.x patch fixes problems where xml documents with multiple dialog documents in the body would not be part of the notifications due to the xml node being unlinked by opensips.

Please consider applying it to the current branches.

```
--- opensips-1.8.5-tls.orig/modules/presence_dialoginfo/notify_body.c	2014-07-02 15:52:03.000000000 +0200
+++ opensips-1.8.5-tls/modules/presence_dialoginfo/notify_body.c	2022-04-21 10:19:12.602391869 +0200
@@ -119,6 +119,7 @@
 	xmlNodePtr p_root= NULL;
 	xmlDocPtr* xml_array ;
 	xmlNodePtr node = NULL;
+       xmlNodePtr next_node = NULL;
 	char *state;
 	int winner_priority = -1, priority ;
 	xmlNodePtr winner_dialog_node = NULL ;
@@ -213,7 +214,8 @@
 				goto error;
 			}
 			if (p_root->children) {
-			for (node = p_root->children; node; node = node->next) {
+                       for (node = p_root->children; node; node = next_node) {
+                               next_node = node->next;
 				if (node->type == XML_ELEMENT_NODE) {
 					LM_DBG("node type: Element, name: %s\n", node->name);
 					/* we do not copy the node, but unlink it and then add it ot the new node
```

**Comment by dsandras** [comment]
--- opensips-1.8.5-tls.orig/modules/presence_dialoginfo/notify_body.c	2014-07-02 15:52:03.000000000 +0200
+++ opensips-1.8.5-tls/modules/presence_dialoginfo/notify_body.c	2022-04-21 10:19:12.602391869 +0200
@@ -119,6 +119,7 @@
 	xmlNodePtr p_root= NULL;
 	xmlDocPtr* xml_array ;
 	xmlNodePtr node = NULL;
+       xmlNodePtr next_node = NULL;
 	char *state;
 	int winner_priority = -1, priority ;
 	xmlNodePtr winner_dialog_node = NULL ;
@@ -213,7 +214,8 @@
 				goto error;
 			}
 			if (p_root->children) {
-			for (node = p_root->children; node; node = node->next) {
+                       for (node = p_root->children; node; node = next_node) {
+                               next_node = node->next;
 				if (node->type == XML_ELEMENT_NODE) {
 					LM_DBG("node type: Element, name: %s\n", node->name);
 					/* we do not copy the node, but unlink it and then add it ot the new node

**Comment by bogdan-iancu** [comment]
Thank you @dsandras for this contribution. Just to be sure I got it right, the function `xmlUnlinkNode` used inside the loop will clear the "next" member, breaking the looping, right ?

**Comment by dsandras** [comment]
Hi @bogdan-iancu, yes, that's correct.

**Comment by bogdan-iancu** [comment]
reference to the code in the new versions is https://github.com/OpenSIPS/opensips/blob/master/modules/presence_dialoginfo/notify_body.c#L215

**Comment by bogdan-iancu** [comment]
Thank you @dsandras

**Comment by dsandras** [comment]
My pleasure @bogdan-iancu :)
