### ISSUE TITLE
[CRASH] Segmentation fault, sipcapture.c

### ISSUE THREAD

**Issue by ghmj2417** [OpenSIPS/opensips#2828]
**OpenSIPS version you are running**

```
version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 765e3470f
main.c compiled on 02:51:26 May  1 2022 with gcc 7version: opensips 3.2.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 765e3470f
main.c compiled on 02:51:26 May  1 2022 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/5Px5muat

**Describe the traffic that generated the bug**

HEP Traffic

**To Reproduce**

Don't know how to reproduce yet.  From my perspective it was just normal HEP traffic.

**Relevant System Logs**

```
May  4 07:15:09 [26525] CRITICAL:core:sig_usr: segfault in process pid: 26525, id: 13
```

**OS/environment information**
 - Operating System: Amazon Linux 2
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@ghmj2417 , please first upgrade to latest 3.2, meaning 3.2.6, to be sure you have all the fixes. Also I see the code around the crash point did change between 3.2.3 and 3.2.6, so there are chances to already have the fix.
So, upgrade and see if the crash occurs again.

**Comment by ghmj2417** [comment]
@bogdan-iancu We deployed 3.2.5 which I think has the changes you are referencing.  However, we encountered a lot of segfaults on a daily basis and had to rollback to 3.2.3.  I do not have any of the core files for 3.2.5 at this time.  But I do know the issue was related to HEP.  I can build and deploy 3.2.6 in our test environment but I don't know if we will hit any issues like we did in production with 3.2.5.  And to circle back to 3.2.3, are you saying the only way to receive assistance on the segfault is to upgrade to 3.2.6?  3.2.3 has been very stable for us so I am very hesitant with going to 3.2.6 especially since we encountered issues with 3.2.5.

**Comment by ghmj2417** [comment]
`"But I do know the issue was related to HEP."`
I guess I can't guarantee this 100% but this box is mainly used as a HEP server.  We do utilize the tracer module so it could have been that.

I'll go ahead and push 3.2.6 to our test environment and see if we can get anymore segfaults.

**Comment by ghmj2417** [comment]
Closing this issue.  Started building from 3.2 branch and encountered segfaults.  Will open new issue.
