### ISSUE TITLE
Add rport in VIA from local_route

### ISSUE THREAD

**Issue by rroiss** [OpenSIPS/opensips#2833]
Hi, 
following up to the issue #797 (https://github.com/OpenSIPS/opensips/issues/797#issue-134317923)
I am facing the same problem using the siprec module.
My SIPREC server has a public IP and my opensips is behind a NAT.
Without adding rport, the SIPREC server sends the response to port 5060, instead of the NATTED port.
Neither force_rport() nor add_local_rport() seems to work.
Is there any other way to set the rport?

I'm using OpenSIPS 3.2.4
Thanks.

**Comment by bogdan-iancu** [comment]
@rroiss , just to be sure, you are talking about using the force_rport() from local_route, right ? If so, this is expected not to work as the function is designed to add the rport to the *received* VIA hdr.
Still, the add_local_rport() func is the right one, but checking its implementation I see it works only when proxying requests, not when generating as UAC.... The change is decent, I will put it on the todo list

**Comment by bogdan-iancu** [comment]
@rroiss , could you please test this fix:
```
diff --git a/modules/tm/uac.c b/modules/tm/uac.c
index 61490835e..49545f658 100644
--- a/modules/tm/uac.c
+++ b/modules/tm/uac.c
@@ -248,8 +248,10 @@ static int run_local_route( struct cell *new_cell, char **buf, int *buf_len,
                        }
                }
 
-               /* if interface change, we need to re-build the via */
-               if (new_send_sock && new_send_sock != dialog->send_sock) {
+               /* if interface change or new VIA related flags were added,
+                * we need to re-build the via */
+               if ( (new_send_sock && new_send_sock != dialog->send_sock)
+               || req->msg_flags&FL_FORCE_LOCAL_RPORT ) {
 
                        LM_DBG("Interface change in local route -> "
                                "rebuilding via\n");
```

**Comment by bogdan-iancu** [comment]
@rroiss , any chances for testing that patch ?

**Comment by bogdan-iancu** [comment]
OK, I took the time to quickly test it and the fix is now on git, with all the backports.
