### ISSUE TITLE
[BUG] CSeq not incremented on ACK after sequential request w/auth

### ISSUE THREAD

**Issue by Matt-Hapner** [OpenSIPS/opensips#2835]
**OpenSIPS version you are running**

```
version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d2c4bebc4
main.c compiled on 01:23:54 Apr 13 2022 with gcc 7
```

**Describe the bug**

This bug is related to https://github.com/OpenSIPS/opensips/issues/1969, but in this scenario, the CSeq fails to be incremented in the ACK after a sequential invite is challenged with auth and responded to correctly.

The timeline:
(initial request/response)
- OpenSIPs receives INVITE (CSeq 500)
- OpenSIPs proxies INVITE to UAS (CSeq 500)
- OpenSIPs receives 200 response (CSeq 500)

(sequential invite in the opposite direction)

- OpenSIPs receives sequential INVITE from original UAS (CSeq 600)
- OpenSIPs proxies sequential INVITE to original UAC (CSeq 600)
- OpenSIPs receives 401 response (CSeq 600)
- OpenSIPs sends INVITE with Authentication (CSeq 601)
- OpenSIPs receives 200 response (CSeq 601)
- OpenSIPs proxies 200 to original UAS (Cseq 600)
- OpenSIPs receives ACK (Cseq 600)
- OpenSIPs proxies ACK to original UAC (CSeq **600** - should be **601**)

A PCAP has been attached for this scenario. The original UAC is at ip 203.0.113.5, the original UAS is at ip 203.0.113.6, and the OpenSIPs proxies are at 203.0.113.3 (stateless proxy) and 203.0.113.4 (stateful proxy). 

**To Reproduce**

The SIPp UAC/UAS scenarios have been attached which will reproduce the error.

We are using the dialog and topology_hiding modules as well as the uac_auth module for auth. It was mentioned in the linked ticket that the uac_auth module is intended to _to be used for auth'ing the initial requests, not sequential ones_. Is this a true statement? It is not infrequent that a BYE or INVITE sequential request is challenged and will need to be responded to with auth information loaded in.

**Expected behavior**

The ACK response should have the same CSeq as the invite sent in response to the auth challenge.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Docker amazonlinux:2
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

Since we are still running OpenSIPs 2.4 in our production environments, we would also like a back port patch for this fix if at all possible as our migration to OpenSIPs 3 is still underway. OpenSIPs 2.4 version:
```
version: opensips 2.4.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6d151d121
main.c compiled on 17:46:01 Apr 28 2022 with gcc 7
```

[cseq_bug.zip](https://github.com/OpenSIPS/opensips/files/8718820/cseq_bug.zip)

**Comment by razvancrainea** [comment]
@Matt-Hapner I've prepared a patch for OpenSIPS 3.2 - are you able to run a few tests and confirm it fixes your issue?
[uac_auth_seq_cseq.txt](https://github.com/OpenSIPS/opensips/files/8762525/uac_auth_seq_cseq.txt)

**Comment by Matt-Hapner** [comment]
@razvancrainea All of the tests have passed. Thanks for the quick turnaround! Please keep me updated with the status of the back-port patch.

**Comment by razvancrainea** [comment]
@Matt-Hapner here is the patch for 2.4: [uac_auth_seq_cseq_2.4.txt](https://github.com/OpenSIPS/opensips/files/8770057/uac_auth_seq_cseq_2.4.txt)

**Comment by Matt-Hapner** [comment]
@razvancrainea thanks, I will perform the same testing on the patch and report back the results

**Comment by Matt-Hapner** [comment]
Tests are passing as expected, thanks for the work @razvancrainea and @bogdan-iancu! I'll let one of you handle the closure of this ticket.

**Comment by benceszigeti** [comment]
Hi @razvancrainea!

Our tests mentioned above by @Matt-Hapner are failing when we are on master (v3.4, 581a4b8) — ACK does not have the proper CSeq (600 instead of 601). The fixing patch attached to this ticket for v3.2 conflicts with 80ff319 (#1071), so we can not apply it. Has the fix been delivered to the master branch as well?
