### ISSUE TITLE
[BUG] has_body_part requires content-lenght header

### ISSUE THREAD

**Issue by hafkensite** [OpenSIPS/opensips#2839]
**OpenSIPS version you are running**
```
version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 86bb46c
main.c compiled on  with gcc 8
```

**Describe the bug**
The `has_body_part` function returns -1 when the `content-length` header is not found. This was documented until the multi-part support was added in 2.3.0.
RFC 3261 mentions that the header SHOULD be used, and MUST be used when a stream-based protocol (such as TCP) is used. This suggest that the content-length header is optional when UDP is used.

**To Reproduce**
Use `has_body_part` in a configuration and send a message which does have SDP, but does not have the content-length header.

**Expected behavior**
If the RFC allows the header to be missing, I expect OpenSIPS to also respect that.

**Relevant System Logs**
-

**OS/environment information**
 - Debian 9
 - OpenSIPS installation: manual packages

**Additional context**

**Comment by bogdan-iancu** [comment]
point taken, let me see what can be done here, without breaking too much :)

**Comment by bogdan-iancu** [comment]
I have some WIP here, let me put more time into this to complete it.
