### ISSUE TITLE
[FEATURE] Add timestamp column for user based and aliases tables

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2847]
Hello Everyone,
Can you please add time stamp columns for user based and alias tables. That require for security and change management  process.

last_modified  should work 

```
ALTER TABLE dbaliases ADD COLUMN last_modified timestamp without time zone DEFAULT now();
ALTER TABLE dbaliases ALTER COLUMN last_modified SET NOT NULL ;

```

**Comment by razvancrainea** [comment]
You can always add arbitrary columns to the tables, as long as OpenSIPS does not use/need them, I don't see a reason why they should be in the schema file. Or am I missing something?

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in progress.

**Comment by volga629-1** [comment]
in progress.

**Comment by bogdan-iancu** [comment]
As not directly used by OpenSIPS, let's not pollute the DB schema.
