### ISSUE TITLE
[BUG] OpenSIPS 3.3.0-beta - cgrates_engine --> tcp_connect_blocking_timeout

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#2850]
Dear Team,

Recently cgrates_engine added support for fqdn --> https://github.com/OpenSIPS/opensips/commit/367e03142be1f7199bb98ec8d3268647fb9d33e1

but when an engine is down and then up OpenSIPS doesn't reconnect to that engine correctly and it shows :

```
Jun  5 11:46:09 [124] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
Jun  5 11:46:09 [124] ERROR:core:tcp_sync_connect_fd: tcp_blocking_connect failed
Jun  5 11:46:09 [123] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
Jun  5 11:46:09 [123] ERROR:core:tcp_sync_connect_fd: tcp_blocking_connect failed
Jun  5 11:46:09 [123] ERROR:cgrates:cgrc_conn: cannot connect to cgr-sess-disp-z1.cgrates:2014
Jun  5 11:46:09 [124] ERROR:cgrates:cgrc_conn: cannot connect to cgr-sess-disp-z1.cgrates:2014
Jun  5 11:46:09 [125] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
Jun  5 11:46:09 [125] ERROR:core:tcp_sync_connect_fd: tcp_blocking_connect failed
Jun  5 11:46:09 [125] ERROR:cgrates:cgrc_conn: cannot connect to cgr-sess-disp-z1.cgrates:2014
Jun  5 11:46:09 [110] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
Jun  5 11:46:09 [125] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
Jun  5 11:46:09 [110] ERROR:core:tcp_sync_connect_fd: tcp_blocking_connect failed
Jun  5 11:46:09 [125] ERROR:core:tcp_sync_connect_fd: tcp_blocking_connect failed
Jun  5 11:46:09 [125] ERROR:cgrates:cgrc_conn: cannot connect to cgr-sess-disp-z1.cgrates:2014
Jun  5 11:46:09 [110] ERROR:cgrates:cgrc_conn: cannot connect to cgr-sess-disp-z1.cgrates:2014
Jun  5 11:46:09 [123] ERROR:core:tcp_connect_blocking_timeout: [server=10.100.4.129:2014] (99) Cannot assign requested address
```

**OpenSIPS version you are running**
```
version: opensips 3.3.0-beta (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cbcdbbc88
main.c compiled on 10:00:43 Jun  3 2022 with gcc 8
```

**Describe the bug**
OpenSIPS is configured with 2  cgrates_engines and when the first engine is down for the next ~30sec the next engine (backup) receives 1) the second opensips request , 2) the 4th request , 3) the 6th request and so on...  Then after about 30secs the backup engine receives all the requests. 

After that I bring up the first node again, Opensips starts immediately sending requests to that node as it should, but the errors above continue without stopping....

Finally I decide to take down both engines and bring up the second one only. OpenSIPS doesn't send any request to the second node at all. Then I bring up the first node and still Opensips doesn't send out any request to any of the cgrates_engines.

```
modparam("cgrates", "cgrates_engine", "CGRATES_SESSIONS_ENDPOINT_A")
modparam("cgrates", "cgrates_engine", "CGRATES_SESSIONS_ENDPOINT_B")
modparam("cgrates", "max_async_connections", 20)
modparam("cgrates", "retry_timeout", 2)

# TCP/IP settings
tcp_accept_aliases      = no
tcp_max_connections     = 10000
tcp_keepalive           = yes
tcp_keepinterval        = 10

and 

cat /proc/sys/net/ipv4/tcp_keepalive_probes 
9
```

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: git

Thank you in advance

Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Although I did test this thoroughly, I did see this error as well in production. I will see if I can replicate it and get back to you, hopefully with a fix.

**Comment by vtzan** [comment]
Dear @razvancrainea ,

I got similar error with CGRateS instance running on 127.0.0.1:2014 by the time CGRateS instance restarted.

```
 ERROR:core:tcp_connect_blocking_timeout: [server=127.0.0.1:2014] (99) Cannot assign requested address
 ERROR:core:tcp_connect_blocking_timeout: [server=127.0.0.1:2014] (99) Cannot assign requested address
```

Thank you in advance

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Just to keep this open. Problem is still there on latest 3.3 ;-(

**Comment by vtzan** [comment]
tested again with latest 3.3 commit. same results.

**Comment by liviuchircu** [comment]
Hi, guys!  Could these issues be related to commit https://github.com/OpenSIPS/opensips/commit/96252b61fe22d62b584357e5d134a805a1b59433?  In short: if you have at least one TCP-related listener (BIN, TCP, TLS, etc.), in your config, then here is, indeed, a different problem to be analyzed here.  Otherwise, please pull latest code and the behavior should improve!

**Comment by vtzan** [comment]
Dear team, problem is still here.
