### ISSUE TITLE
[BUG] Topology hiding clarification

### ISSUE THREAD

**Issue by abrown-etal** [OpenSIPS/opensips#2851]
**OpenSIPS version you are running**
Any

**Describe the bug**
Hi, I am looking for some clarification regarding the expected behavior of  the topology hiding module.

When making an outbound call, via a proxy with topology enabled, I expect the record-route header to be removed on both the outbound `INVITE` and the inbound `200 OK` response.

This is not the case as I only see it being removed on the `INVITE` and not the `200 OK`. This behavior is caused by the following block of code:
https://github.com/OpenSIPS/opensips/blob/c9903d88aea1e77b8c5bfc2847d9065d9f0f8e2b/modules/topology_hiding/topo_hiding_logic.c#L1196-L1223

Removing this block of code produces the behavior I expect, that is; the record-route header is removed for all messages.

This leads me to one of the following conclusions:

- My expectation of how topology hiding works is incorrect
- My expectation is correct but there are devices that need a record-route and this is a work around
- Its just a bug.

Given the block of code has existed since the addition of topology hiding to the dialogue module, I feel this block of code exists for a very good reason and I would very much like to understand why. 

I am talking about a very simple call setup here. Just an `INVITE`, `TRYING`, `RINGING`, `OK` sequence.

Topology hiding is often presented as a solution to enhance security by hiding network information. This behavior seems to contradict that.

Can anyone clarify what the expected behavior is for this module?

**Comment by razvancrainea** [comment]
I don't see any issues with this. The 200 OK should not have all the Record-Route headers dropped, only the ones that had been added in the path between the proxy and UAS. However, it *must* contain all the Route headers advertised from UAC to proxy, otherwise those proxied would have been taken out of route, which is not correct.
