### ISSUE TITLE
[BUG] uac_registrant hard-coded to use expires path param instead of Expires header

### ISSUE THREAD

**Issue by sreeram-narayanan** [OpenSIPS/opensips#2853]
**OpenSIPS version you are running**

```
version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ce8cda891
main.c compiled on 19:27:07 May 31 2022 with gcc 6.3.0
```

**Describe the bug**

In uac_registrant, the module is hard-coded to use "expires" as a path param in the Contact header. This prevents us from setting "Expires" header.

```

	if (1) {
		/* adding exiration time as a parameter */
		memcpy(p, expires_param.s, expires_param.len);
		p += expires_param.len;
	} else {
		/* adding exiration time as a header */
		memcpy(p, CRLF, CRLF_LEN); p += CRLF_LEN;
		memcpy(p, expires_hdr.s, expires_hdr.len);
		p += expires_hdr.len;
	}

```

**To Reproduce**

uac_registrant always uses expires path param instead of Expires header.

**Expected behavior**

This can be made configurable by using a mod_param.

**Relevant System Logs**

Not relevant.

**Comment by okhowang** [comment]
According https://www.rfc-editor.org/rfc/rfc2543#section-4.2.6
> A server MAY choose any duration for the registration lifetime.
   Registrations not refreshed after this amount of time SHOULD be
   silently discarded. Responses to a registration SHOULD include an
   Expires header ([Section 6.20](https://www.rfc-editor.org/rfc/rfc2543#section-6.20)) or expires Contact parameters ([Section](https://www.rfc-editor.org/rfc/rfc2543#section-6.13)
   [6.13](https://www.rfc-editor.org/rfc/rfc2543#section-6.13)), indicating the time at which the server will drop the
   registration. If none is present, one hour is assumed. Clients MAY
   request a registration lifetime by indicating the time in an Expires
   header in the request. A server SHOULD NOT use a higher lifetime than
   the one requested, but MAY use a lower one. A single address (if
   host-independent) MAY be registered from several different clients.

`uac_registrant` should read `Expires` header too.

**Comment by bogdan-iancu** [comment]
The initial report was about the choice of the `uac_registrant` module to set `expires` to the Contact, rather than as a standalone hdr. Which is perfectly valid from RFC perspective, it is not a bug. 
Now, @okhowang, in your follow up, you talk about something different, about how the expires is to READ from the registration reply (and not about pushing the expires in the registration request).
