### ISSUE TITLE
[BUG] ?FEATURE? send Push Notification (PN)  for MESSAGEs too (not just for INVITEs)

### ISSUE THREAD

**Issue by gmaruzz** [OpenSIPS/opensips#2864]
at this moment, in TM, the function t_wait_for_new_branches returns ERROR if method is not INVITE

that I see as wrong, because both INVITE and MESSAGE need to be transmitted immediately, so they need PN, so they need to activate t_wait_for_new_branches and be resent after client has re-registered

if this is not a bug, definitely I would like to see this as a feature

I modified and recompiled source, and it works with both INVITE and MESSAGE allowed, with no visible (to me) side effects

ANY version

**Comment by gmaruzz** [comment]
bau

**Comment by gmaruzz** [comment]
bau

**Comment by sobomax** [comment]
Giovanni, maybe I don't understand the logic but that change does not seem
right to me as MESSAGE transaction is stateless and as such can have no
branches. Please elaborate on your usage scenario.

-Maksym

**Comment by gmaruzz** [comment]
mmmmh, the gist of the problem is:

a MESSAGE is incoming to OpenSIPS for a PUSH-registered contact (supposedly not-reachable)

would be nice that OpenSIPS sends a PN to the contact, so the contact re-registers and make himself reachable, so OpenSIPS then will send the MESSAGE to him

end result: we ensure same reachability via Push-Notification to both calls and instant messages  (what the end user would expect)
