### ISSUE TITLE
[BUG]opensips 3.2.6 CPU reach 100%

### ISSUE THREAD

**Issue by zbyslb** [OpenSIPS/opensips#2866]
**OpenSIPS version you are running**

version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 00:37:02 Apr 21 2022 with gcc 8

**Describe the bug**

Jul 13 15:26:08 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 7960 ms ago (now 23829410 ms), delaying execution

When this log begins to appear, the CPU utilization of opensips will increase sharply, and finally reach 100%
**To Reproduce**

Run opensips for a period of time, and there are continuous calls.

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by zbyslb** [comment]
Jul 13 15:26:01 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 990 ms ago (now 23822440 ms), delaying execution
Jul 13 15:26:02 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 1990 ms ago (now 23823440 ms), delaying execution
Jul 13 15:26:03 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 2990 ms ago (now 23824440 ms), delaying execution
Jul 13 15:26:04 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 3980 ms ago (now 23825430 ms), delaying execution
Jul 13 15:26:05 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 4980 ms ago (now 23826430 ms), delaying execution
Jul 13 15:26:06 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 5970 ms ago (now 23827420 ms), delaying execution
Jul 13 15:26:07 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 6970 ms ago (now 23828420 ms), delaying execution
Jul 13 15:26:08 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 7960 ms ago (now 23829410 ms), delaying execution
Jul 13 15:26:09 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 8960 ms ago (now 23830410 ms), delaying execution
Jul 13 15:26:10 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 9950 ms ago (now 23831400 ms), delaying execution
Jul 13 15:26:11 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 10950 ms ago (now 23832400 ms), delaying execution
Jul 13 15:26:12 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 11950 ms ago (now 23833400 ms), delaying execution
Jul 13 15:26:13 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 12940 ms ago (now 23834390 ms), delaying execution
Jul 13 15:26:14 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 13940 ms ago (now 23835390 ms), delaying execution
Jul 13 15:26:15 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 14930 ms ago (now 23836380 ms), delaying execution
Jul 13 15:26:16 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 15930 ms ago (now 23837380 ms), delaying execution
Jul 13 15:26:17 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 16930 ms ago (now 23838380 ms), delaying execution
Jul 13 15:26:18 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 17920 ms ago (now 23839370 ms), delaying execution
Jul 13 15:26:19 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 18920 ms ago (now 23840370 ms), delaying execution
Jul 13 15:26:20 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 19910 ms ago (now 23841360 ms), delaying execution
Jul 13 15:26:21 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 20910 ms ago (now 23842360 ms), delaying execution
Jul 13 15:26:22 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 21900 ms ago (now 23843350 ms), delaying execution
Jul 13 15:26:23 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 22900 ms ago (now 23844350 ms), delaying execution
Jul 13 15:26:24 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 23900 ms ago (now 23845350 ms), delaying execution
Jul 13 15:26:25 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 24890 ms ago (now 23846340 ms), delaying execution
Jul 13 15:26:26 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 25890 ms ago (now 23847340 ms), delaying execution
Jul 13 15:26:27 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 26880 ms ago (now 23848330 ms), delaying execution
Jul 13 15:26:28 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 27880 ms ago (now 23849330 ms), delaying execution
Jul 13 15:26:29 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 28880 ms ago (now 23850330 ms), delaying execution
Jul 13 15:26:30 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 29870 ms ago (now 23851320 ms), delaying execution
Jul 13 15:26:31 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 30870 ms ago (now 23852320 ms), delaying execution
Jul 13 15:26:32 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 31870 ms ago (now 23853320 ms), delaying execution
Jul 13 15:26:33 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 32860 ms ago (now 23854310 ms), delaying execution
Jul 13 15:26:34 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 33860 ms ago (now 23855310 ms), delaying execution
Jul 13 15:26:35 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 34850 ms ago (now 23856300 ms), delaying execution
Jul 13 15:26:36 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 35850 ms ago (now 23857300 ms), delaying execution
Jul 13 15:26:37 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 36850 ms ago (now 23858300 ms), delaying execution
Jul 13 15:26:38 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 37840 ms ago (now 23859290 ms), delaying execution
Jul 13 15:26:39 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 38840 ms ago (now 23860290 ms), delaying execution
Jul 13 15:26:40 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 39830 ms ago (now 23861280 ms), delaying execution
Jul 13 15:26:41 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 40830 ms ago (now 23862280 ms), delaying execution
Jul 13 15:26:42 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 41830 ms ago (now 23863280 ms), delaying execution
Jul 13 15:26:43 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 42820 ms ago (now 23864270 ms), delaying execution
Jul 13 15:26:44 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 43820 ms ago (now 23865270 ms), delaying execution
Jul 13 15:26:45 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 44820 ms ago (now 23866270 ms), delaying execution
Jul 13 15:26:46 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 45810 ms ago (now 23867260 ms), delaying execution
Jul 13 15:26:47 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 46810 ms ago (now 23868260 ms), delaying execution
Jul 13 15:26:48 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 47810 ms ago (now 23869260 ms), delaying execution
Jul 13 15:26:49 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 48800 ms ago (now 23870250 ms), delaying execution
Jul 13 15:26:50 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 49800 ms ago (now 23871250 ms), delaying execution
Jul 13 15:26:51 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 50790 ms ago (now 23872240 ms), delaying execution
Jul 13 15:26:52 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 51790 ms ago (now 23873240 ms), delaying execution
Jul 13 15:26:53 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 52780 ms ago (now 23874230 ms), delaying execution
Jul 13 15:26:54 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 53780 ms ago (now 23875230 ms), delaying execution
Jul 13 15:26:55 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 54770 ms ago (now 23876220 ms), delaying execution
Jul 13 15:26:56 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 55770 ms ago (now 23877220 ms), delaying execution
Jul 13 15:26:57 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 56760 ms ago (now 23878210 ms), delaying execution
Jul 13 15:26:58 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 57760 ms ago (now 23879210 ms), delaying execution
Jul 13 15:26:58 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 58760 ms ago (now 23880210 ms), delaying execution
Jul 13 15:26:59 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 59750 ms ago (now 23881200 ms), delaying execution
Jul 13 15:27:00 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 60740 ms ago (now 23882190 ms), delaying execution
Jul 13 15:27:01 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 61740 ms ago (now 23883190 ms), delaying execution
Jul 13 15:27:02 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 62730 ms ago (now 23884180 ms), delaying execution
Jul 13 15:27:03 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 63730 ms ago (now 23885180 ms), delaying execution
Jul 13 15:27:04 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 64720 ms ago (now 23886170 ms), delaying execution
Jul 13 15:27:05 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 65720 ms ago (now 23887170 ms), delaying execution
Jul 13 15:27:06 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 66710 ms ago (now 23888160 ms), delaying execution
Jul 13 15:27:07 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 67710 ms ago (now 23889160 ms), delaying execution
Jul 13 15:27:08 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 68710 ms ago (now 23890160 ms), delaying execution
Jul 13 15:27:09 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 69700 ms ago (now 23891150 ms), delaying execution
Jul 13 15:27:10 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 70700 ms ago (now 23892150 ms), delaying execution
Jul 13 15:27:11 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 71690 ms ago (now 23893140 ms), delaying execution
Jul 13 15:27:12 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 72690 ms ago (now 23894140 ms), delaying execution
Jul 13 15:27:13 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 73680 ms ago (now 23895130 ms), delaying execution
Jul 13 15:27:14 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 74670 ms ago (now 23896120 ms), delaying execution
Jul 13 15:27:15 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 75670 ms ago (now 23897120 ms), delaying execution
Jul 13 15:27:16 [79] WARNING:core:timer_ticker: timer task <dlg-timer> already scheduled 76670 ms ago (now 23898120 ms), delaying execution

**Comment by zbyslb** [comment]
Jul 13 15:26:01 [79] WARNING:core:timer_ticker: timer task \<dlg-timer\> already scheduled 990 ms ago (now 23822440 ms), delaying execution

**Comment by rvlad-patrascu** [comment]
Hi @zbyslb 

Can you do a `opensips-cli -x trap` and post the resulting trap file?
