### ISSUE TITLE
[BUG] Contact wrongly restored in brach route (unable to deliver BYE from B side - 476 Unresolvable destination (476/TM))

### ISSUE THREAD

**Issue by gwozniak** [OpenSIPS/opensips#2871]
**OpenSIPS version you are running**

```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 2e8224c
main.c compiled on 20:09:40 Jan 31 2021 with gcc 4.4.7
```

**Describe the bug**

Hi I received ticket from production system that some calls are not disconnected correctly.
I started digging problem and found that it appears in scenario:
- INVITE from A with contact uri without brackets "<" , ">", situation is allowed in RFC when no params nor display  is present eg. "Contact:sip:375295517154@sbc.windmobile.pl"
- there is failure in first relay (5xx response) and we are making second relay to another peer, call to second peer is established
-  new transaction comes from B side (here BYE)
- opensips restores Contact but domain part of URI is removed so it tries to resolve 375295517154 as FQDN and fails with 476 Unresolvable destination (leg opensips -> B is disconnected)
- leg A -> opensips stucks until A side notices smth is wrong (dialog is removed from memory and DB in previous step)

**To Reproduce**

1. Start OpenSIPS
2. Start traffic using contact without "<",">" around uri
3. Make failure of first relay
4. Make second relay and establish call
5. Send BYE from B side in second RELAY
6. Observe problem with resolving FQDN in logs: *CRITICAL:core:mk_proxy: could not resolve hostname: "375295517154"*

**Expected behavior**

Delivery of new B transaction to A peer (like in case with "<", ">" in contact header).

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Centos 6
 - OpenSIPS installation: compiled from sources (git)
 - other relevant information: I added some additional LM_DBG entries to orginal source code (diff appended).
 - other relevant information: I checked sources of tm module for 3.1 and it looks that bug should be there (no difference in function fix_fake_req_headers inside t_msgbuilder.h)

**Additional context**
I'm attaching sip traces, logs and sqls (dialog's values from DB where contact for NOK scenario misses FQDN part) for NOK and OK scenario.

**Comment by gwozniak** [comment]
[https://mega.nz/file/vL4y3ZTI#1E7OoFnn_bYc-DB2B9hvLkSgWuxkNh_8HdFsAnln02Y](url)

**Comment by gwozniak** [comment]
Password for logs archive: EXSGLOB-177

**Comment by bogdan-iancu** [comment]
@gwozniak , you say
 ```
opensips restores Contact but domain part of URI is removed so it tries to resolve 375295517154 as FQDN and fails with 476 Unresolvable destination (leg opensips -> B is disconnected)
```
By default OpenSIPS is not touching the Contact hdr, unless you use some script functions for that - are you doing topo hiding, or fixing contact? how comes the contact gets changed by opensips ?

**Comment by gwozniak** [comment]
@bogdan-iancu  - yes we are using topo higding:

`loadmodule "topology_hiding.so"`
`modparam("topology_hiding", "force_dialog", 1)`

and in route
`topology_hiding("U");`

**Comment by gwozniak** [comment]
@bogdan-iancu  hi do you need something more to analyze the issue ? maybe whole opensips script and global configs ?
