### ISSUE TITLE
[BUG]Under extreme network conditions, the recvmsg function is blocked on Linux system calls for a long time and does not return

### ISSUE THREAD

**Issue by zbyslb** [OpenSIPS/opensips#2874]
**OpenSIPS version you are running**

version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 00:37:02 Apr 21 2022 with gcc 8

**Describe the bug**

in opensips3.2.6, when the registered users reach about 300 and the number of concurrent calls is about 300, sometimes t_relay will be failed after receiving the BYE message, Once this scenario occurs, it will continue to appear until the system resources are fully occupied

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

in the script, I added print information to the process of calling the function t_relay of each request message. in the process of forwarding the BYE message, there was no result returned after calling the function t_relay

Jul 20 11:01:59 [12552] DBG:tm:t_lookup_request: no transaction found
Jul 20 11:01:59 [12552] DBG:tm:run_reqin_callbacks: trans=0x7fee7c9d93f0, callback type 1, id 0 entered
Jul 20 11:01:59 [12552] DBG:core:mk_proxy: doing DNS lookup...
Jul 20 11:01:59 [12552] DBG:core:build_req_buf_from_sip_req: extra param added: <;rport>
Jul 20 11:01:59 [12552] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 20 11:01:59 [12552] DBG:tm:set_timer: relative timeout is 500000
Jul 20 11:01:59 [12552] DBG:tm:insert_timer_unsafe: [4]: 0x7fee7c9d9610 (13171800000)
Jul 20 11:01:59 [12552] DBG:tm:insert_timer_unsafe: [0]: 0x7fee7c9d9640 (13181)
Jul 20 11:01:59 [12552] DBG:tm:t_relay_to: new transaction fwd'ed
Jul 20 11:01:59 [12552] send message BYE success with 192.168.0.2 for ci:5273abf7-1caa-5d1f-8e5b-52540026761f@cs-5d5d9494c9-nbk8r
Jul 20 11:01:59 [12683] received reply sipcode:200 with method:BYE for ci:5273abf7-1caa-5d1f-8e5b-52540026761f@cs-5d5d9494c9-nbk8r
Jul 20 11:01:59 [12683] received message BYE with ci:9c8e7806-1daa-5d1f-97c5-5254008f22fa@cs-5d5d9494c9-c52ck
Jul 20 11:01:59 [12683] start send message BYE for ci:9c8e7806-1daa-5d1f-97c5-5254008f22fa@cs-5d5d9494c9-c52ck
Jul 20 11:01:59 [12683] DBG:tm:t_newtran: transaction on entrance=0xffffffffffffffff
Jul 20 11:01:59 [12683] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 20 11:01:59 [12683] DBG:core:parse_headers: flags=78
Jul 20 11:01:59 [12683] DBG:tm:t_lookup_request: start searching: hash=59848, isACK=0
Jul 20 11:01:59 [12683] DBG:tm:matching_3261: RFC3261 transaction matching failed
Jul 20 11:01:59 [12683] DBG:tm:t_lookup_request: no transaction found
Jul 20 11:01:59 [12683] DBG:tm:run_reqin_callbacks: trans=0x7fee7d5bbd18, callback type 1, id 0 entered
Jul 20 11:01:59 [12683] DBG:core:mk_proxy: doing DNS lookup...
Jul 20 11:01:59 [12683] DBG:core:parse_headers: flags=2000
Jul 20 11:01:59 [12683] DBG:core:build_req_buf_from_sip_req: extra param added: <;rport>
Jul 20 11:01:59 [12683] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 20 11:01:59 [12683] DBG:core:tcp_conn_get: con found in state 0
Jul 20 11:01:59 [12683] DBG:core:tcp_conn_get: tcp connection found (0x7fee7cd277b0), acquiring fd
Jul 20 11:01:59 [12683] DBG:core:tcp_conn_get: c= 0x7fee7cd277b0, n=16, Usock=946

    xlog("L_WARN", "start send message $rm for ci:$ci\n");
    if(is_method("BYE")) {
        $log_level = 4; 
    }
    t_on_reply("handle_nat");
    if (!t_relay()) {
        xlog("L_WARN", "send message $rm failed with $socket_out(ip) for ci:$ci\n");
        rtpengine_delete();
        send_reply(500, "Internal Error");
        if($avp(next) == 0) {
            acc_evi_request("500 Internal Error");
        }
    } else {
        xlog("L_WARN", "send message $rm success with $socket_out(ip) for ci:$ci\n");
    }
    if(is_method("BYE")) {
        $log_level = NULL; 
    }

I found that all call funciton t_relay fail to be sent to users registered using TCP

**Additional context**

**Comment by zbyslb** [comment]
Jul 20 11:02:29 [12555] received message BYE with ci:7a1e8518-1daa-5d1f-9515-5254008b0c26@cs-5d5d9494c9-6csk6
Jul 20 11:02:29 [12555] start send message BYE for ci:7a1e8518-1daa-5d1f-9515-5254008b0c26@cs-5d5d9494c9-6csk6
Jul 20 11:02:29 [12555] DBG:tm:t_newtran: transaction on entrance=0xffffffffffffffff
Jul 20 11:02:29 [12555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 20 11:02:29 [12555] DBG:core:parse_headers: flags=78
Jul 20 11:02:29 [12555] DBG:tm:t_lookup_request: start searching: hash=51347, isACK=0
Jul 20 11:02:29 [12555] DBG:tm:matching_3261: RFC3261 transaction matching failed
Jul 20 11:02:29 [12555] DBG:tm:t_lookup_request: no transaction found
Jul 20 11:02:29 [12555] DBG:tm:run_reqin_callbacks: trans=0x7fee7d3f2e60, callback type 1, id 0 entered
Jul 20 11:02:29 [12555] DBG:core:mk_proxy: doing DNS lookup...
Jul 20 11:02:29 [12555] DBG:core:parse_headers: flags=2000
Jul 20 11:02:29 [12555] DBG:core:build_req_buf_from_sip_req: extra param added: <;rport>
Jul 20 11:02:29 [12555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 20 11:02:29 [12555] DBG:core:tcp_conn_get: con found in state 0
Jul 20 11:02:29 [12555] DBG:core:tcp_conn_get: tcp connection found (0x7fee7cb780e0), acquiring fd
Jul 20 11:02:29 [12555] DBG:core:tcp_conn_get: c= 0x7fee7cb780e0, n=16, Usock=896
Jul 20 11:02:29 [12555] DBG:core:tcp_conn_get: after receive_fd: c= 0x7fee7cb780e0 n=8 fd=1299
Jul 20 11:02:29 [12555] DBG:core:proto_tcp_send: sending via fd 1299...
Jul 20 11:02:29 [12555] DBG:core:tsend_stream_async: Async successful write from first try on 0x7fee7cb780e0
Jul 20 11:02:29 [12555] DBG:core:proto_tcp_send: after write: c= 0x7fee7cb780e0 n/len=553/553 fd=1299
Jul 20 11:02:29 [12555] DBG:tm:insert_timer_unsafe: [0]: 0x7fee7d3f30b0 (13211)
Jul 20 11:02:29 [12555] DBG:tm:t_relay_to: new transaction fwd'ed
Jul 20 11:02:29 [12555] send message BYE success with 192.168.0.2 for ci:7a1e8518-1daa-5d1f-9515-5254008b0c26@cs-5d5d9494c9-6csk6

**Comment by zbyslb** [comment]
The above DBG log is printed when it is successfully sent

**Comment by zbyslb** [comment]
The problem should be in this line of code:
n=receive_fd(unix_tcp_sock, &c, sizeof(c), &fd, MSG_WAITALL);

**Comment by zbyslb** [comment]
again:
	ret=recvmsg(unix_socket, &msg, flags);
	if (ret<0){
		if (errno==EINTR) goto again;
		if ((errno==EAGAIN)||(errno==EWOULDBLOCK)) goto error;
		LM_CRIT("recvmsg on %d failed: %s\n", unix_socket, strerror(errno));
		goto error;
	}
	if (ret==0){
		/* EOF */
		LM_DBG("EOF on %d\n", unix_socket);
		goto error;
	}
	if (ret<data_len){
		LM_WARN("too few bytes read (%d from %d) trying to fix...\n",
				ret, data_len);
		/* blocking recv_all */
		n=recv_all(unix_socket, (char*)data+ret, data_len-ret, MSG_WAITALL);
		if (n>=0) ret+=n;
		else{
			ret=n;
			goto error;
		}
	}

**Comment by zbyslb** [comment]
If the errno returned by the system is continuously equal to EINTR, it will cause an endless loop

**Comment by zbyslb** [comment]
For TCP, if accept processing is performed, EINTR can indeed retry, but for receiving data, EINTR should not retry indefinitely

**Comment by zbyslb** [comment]
This is an obvious problem and mistake!!

**Comment by zbyslb** [comment]
Jul 22 09:44:55 [1555] received message BYE with ci:78db708e-a4ab-5d1f-86a4-5254001a4b81@cs-5d5d9494c9-lkvrl
Jul 22 09:44:55 [1555] current size in closingcall profile is:108
Jul 22 09:44:55 [1555] start send message BYE for ci:78db708e-a4ab-5d1f-86a4-5254001a4b81@cs-5d5d9494c9-lkvrl
Jul 22 09:44:55 [1555] DBG:tm:t_newtran: transaction on entrance=0xffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=78
Jul 22 09:44:55 [1555] DBG:tm:t_lookup_request: start searching: hash=12390, isACK=0
Jul 22 09:44:55 [1555] DBG:tm:matching_3261: RFC3261 transaction matching failed
Jul 22 09:44:55 [1555] DBG:tm:t_lookup_request: no transaction found
Jul 22 09:44:55 [1555] DBG:tm:run_reqin_callbacks: trans=0x7f14feefd668, callback type 1, id 0 entered
Jul 22 09:44:55 [1555] DBG:core:mk_proxy: doing DNS lookup...
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=2000
Jul 22 09:44:55 [1555] DBG:core:build_req_buf_from_sip_req: extra param added: <;rport>
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: con found in state 0
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: tcp connection found (0x7f14fede3010), acquiring fd
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: c= 0x7f14fede3010, n=16, Usock=938
Jul 22 09:44:55 [1555] DBG:core:receive_fd: recvmsg:1-------------1

**Comment by zbyslb** [comment]
I tried to modify the code of the function receive_fd in the file tcp_passfd.c and add printing information:
again:
    LM_DBG("recvmsg:1-------------1\n");
    ret=recvmsg(unix_socket, &msg, flags);
	if (ret<0){
        LM_DBG("recvmsg:1-----errno is%d\n", errno);
		if (errno==EINTR) goto again;
		if ((errno==EAGAIN)||(errno==EWOULDBLOCK)) goto error;
		LM_CRIT("recvmsg on %d failed: %s\n", unix_socket, strerror(errno));
		goto error;
	}
	if (ret==0){
		/* EOF */
		LM_DBG("EOF on %d\n", unix_socket);
		goto error;
	}
	if (ret<data_len){
		LM_WARN("too few bytes read (%d from %d) trying to fix...\n",
				ret, data_len);
		/* blocking recv_all */
		LM_DBG("recvmsg:1-------------2\n");
        n=recv_all(unix_socket, (char*)data+ret, data_len-ret, MSG_WAITALL);
		if (n>=0) ret+=n;
		else{
			ret=n;
			goto error;
		}
	}

**Comment by zbyslb** [comment]
When opensips cannot successfully forward bye messages, the printed information is as follows:
Jul 22 09:44:55 [1555] received message BYE with ci:78db708e-a4ab-5d1f-86a4-5254001a4b81@cs-5d5d9494c9-lkvrl
Jul 22 09:44:55 [1555] current size in closingcall profile is:108
Jul 22 09:44:55 [1555] start send message BYE for ci:78db708e-a4ab-5d1f-86a4-5254001a4b81@cs-5d5d9494c9-lkvrl
Jul 22 09:44:55 [1555] DBG:tm:t_newtran: transaction on entrance=0xffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=78
Jul 22 09:44:55 [1555] DBG:tm:t_lookup_request: start searching: hash=12390, isACK=0
Jul 22 09:44:55 [1555] DBG:tm:matching_3261: RFC3261 transaction matching failed
Jul 22 09:44:55 [1555] DBG:tm:t_lookup_request: no transaction found
Jul 22 09:44:55 [1555] DBG:tm:run_reqin_callbacks: trans=0x7f14feefd668, callback type 1, id 0 entered
Jul 22 09:44:55 [1555] DBG:core:mk_proxy: doing DNS lookup...
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=2000
Jul 22 09:44:55 [1555] DBG:core:build_req_buf_from_sip_req: extra param added: <;rport>
Jul 22 09:44:55 [1555] DBG:core:parse_headers: flags=ffffffffffffffff
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: con found in state 0
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: tcp connection found (0x7f14fede3010), acquiring fd
Jul 22 09:44:55 [1555] DBG:core:tcp_conn_get: c= 0x7f14fede3010, n=16, Usock=938
Jul 22 09:44:55 [1555] DBG:core:receive_fd: recvmsg:1-------------1

**Comment by zbyslb** [comment]
It can be seen that when using MSG_WAITALL parameter as flag parameters, the recvmsg function may be blocked for a long time and will not return.

**Comment by zbyslb** [comment]
again:
    LM_DBG("recvmsg:1-------------1\n");
    ret=recvmsg(unix_socket, &msg, flags);
	if (ret<0){
        LM_DBG("recvmsg:1-----errno is%d\n", errno);
		if (errno==EINTR) goto again;
		if ((errno==EAGAIN)||(errno==EWOULDBLOCK)) goto error;
		LM_CRIT("recvmsg on %d failed: %s\n", unix_socket, strerror(errno));
		goto error;
	}
	if (ret==0){
		/* EOF */
		LM_DBG("EOF on %d\n", unix_socket);
		goto error;
	}
	if (ret<data_len){
		LM_WARN("too few bytes read (%d from %d) trying to fix...\n",
				ret, data_len);
		/* blocking recv_all */
		LM_DBG("recvmsg:1-------------2\n");
        n=recv_all(unix_socket, (char*)data+ret, data_len-ret, MSG_WAITALL);
		if (n>=0) ret+=n;
		else{
			ret=n;
			goto error;
		}
	}

#ifdef HAVE_MSGHDR_MSG_CONTROL
	LM_DBG("recvmsg:1-------------3\n");
    cmsg=CMSG_FIRSTHDR(&msg);
	if ((cmsg!=0) && (cmsg->cmsg_len==CMSG_LEN(sizeof(new_fd)))){
		if (cmsg->cmsg_type!= SCM_RIGHTS){
			LM_ERR("msg control type != SCM_RIGHTS\n");
			ret=-1;
			goto error;
		}
		if (cmsg->cmsg_level!= SOL_SOCKET){
			LM_ERR("msg level != SOL_SOCKET\n");
			ret=-1;
			goto error;
		}
		LM_DBG("recvmsg:1-------------4\n");
        *fd = get_unaligned_int(CMSG_DATA(cmsg));
	}else{
		/*
		LM_ERR("no descriptor passed, cmsg=%p,len=%d\n",
			cmsg, (unsigned)cmsg->cmsg_len); */
		*fd=-1;
		/* it's not really an error */
	}
#else
	LM_DBG("recvmsg:1-------------5\n");
    if (msg.msg_accrightslen==sizeof(int)){
		*fd=new_fd;
	}else{
		/*LM_ERR("no descriptor passed, accrightslen=%d\n",
			msg.msg_accrightslen); */
		*fd=-1;
	}
#endif

**Comment by zbyslb** [comment]
Before calling recvmsg, I try to set the TCP socket read timeout parameter to 1 second, and add the following code in line 530 of the file net_tcp.c:
setsockopt(unix_tcp_sock, SOL_SOCKET, SO_RCVTIMEO, (char *)&timeout, sizeof(struct timeval));

The definition of timeout parameter is
struct timeval timeout={1,0};

When I set the read timeout mechanism for recvmsg function, the forwarded message will not be blocked for a long time

**Comment by zbyslb** [comment]
For this problem, I grabbed the log, tried to add print information to the code, and located the error of the function. Why there was no response.

**Comment by zbyslb** [comment]
sipphone<->router(use nat based on port)<->opensips

**Comment by zbyslb** [comment]
The recvmsg() call applies to sockets, regardless of whether they are in the connected state, except for TCP sockets, which must be connected. This call returns the length of the data received. If data is not available for socket s, and s is in blocking mode, the recvmsg() call blocks the caller until data arrives.

**Comment by zbyslb** [comment]
The recvmsg() call applies to sockets, regardless of whether they are in the connected state, except for TCP sockets, which must be connected. This call returns the length of the data received. If data is not available for socket s, and s is in blocking mode, the recvmsg() call blocks the caller until data arrives.

**Comment by zbyslb** [comment]
@bogdan-iancu

**Comment by zbyslb** [comment]
I have submitted the modified code, and my modified code has been online for nearly two months, running normally. It's strange to me that you don't correct such obvious mistakes. The recvmsg function may not return for a long time under your use conditions

**Comment by zbyslb** [comment]
You may think that recvmsg will return immediately as soon as any end closes the tcp connection, which is correct in most cases. But have you considered the case of multi-level NAT? Have you considered the case where one end of the mobile network has exited, but the tcp connection at the other end is still fake? This is the extreme network condition I mentioned.

**Comment by zbyslb** [comment]
You may think that recvmsg will return immediately as soon as any end closes the tcp connection, which is correct in most cases. But have you considered the case of multi-level NAT? Have you considered the case where one end of the mobile network has exited, but the tcp connection at the other end is still fake? This is the extreme network condition I mentioned.

**Comment by zbyslb** [comment]
Do you really not understand the working mechanism of tcp, or do you have other considerations

**Comment by zbyslb** [comment]
For tcp, any blocking call without considering the timeout is extremely bad behavior

**Comment by zbyslb** [comment]
When the TCP connection is fake, the signal mechanism will not be generated in some scenarios

**Comment by zbyslb** [comment]
When the TCP connection is not active, no packets will arrive

**Comment by zbyslb** [comment]
You can tell me the reason why the existing code will not block for a long time.

**Comment by bogdan-iancu** [comment]
@zbyslb , the overall picture is more complex than it looks. You need to understand how the whole TCP layer works in opensips, in order to understand what is happening in that `receive_fd` function and should be the fix.
The mentioned function is used by any OpenSIPS worker process in order to acquire a TCP connection from the TCP Main process. So it takes care of an inter-process communication - and by design, this kind of communication (from a worker to TCP Main) never blocks, as the TCP Main is able to always answer back on spot.
IMO, the problem you experience is in a totally different place, and your change is just a quick hack that actually discards useful traffic rather than fixing the problem.
Now, to understand the nature of the blocking , the most useful will be to grab and attach here the output of `opensips-cli -x trap` - it is important to see what the TCP Main proc is doing, while the worker process is waiting for its answer.

**Comment by zbyslb** [comment]
I directly used the strace command to track the tcp worker process and the tcp main process. When the problem occurs, the main process works normally. It is processing other tasks, but the current abnormal worker process has been waiting for the return of recvmsg for more than 1 day

**Comment by zbyslb** [comment]
The biggest problem is that when the tcp worker process is waiting for the return of the recvmsg, no matter whether the main process works normally, the worker process is blocked after calling the recvmsg, and nothing can be done subsequently. When multiple worker processes are blocked, how can the system schedule them

**Comment by zbyslb** [comment]
My modification method is relatively original, but after my repeated tests (my call concurrency is greater than 1000, and the test time exceeds 1 month), the system works very normally, and the system resource consumption is very small

**Comment by zbyslb** [comment]
@bogdan-iancu

**Comment by zbyslb** [comment]
I have another question here. Based on your existing implementation mechanism, what is the significance of long waiting.

**Comment by bogdan-iancu** [comment]
In order to investigate further, I still need that `opensips-cli -x trap` output - are you willing to provide it ?
