### ISSUE TITLE
[BUG] Cannot create dialog from failure route after migrating from 2.3 branch to 3.3

### ISSUE THREAD

**Issue by fsantulli** [OpenSIPS/opensips#2875]
We've been used to structure the config files in sub-routes to avoid code redundancy.

After moving to 3.3.0 stable, we've noticed that script could not startup cause dialog with error:
_ERROR:core:check_actions: script function "create_dialog" (types=1) does not support route type (2)_

Once updated the config files to check the errors we've noticed that create_dialog was correctly working in sub-routes but not when them have been called by failure route (branch and others fits too).

Maybe the original route behaviour changed since 2.3, so modules could better understand from which route the function call propagates.

The issue we have at the moment is that we cannot handle some kinds of call forwards (on unavailable for example) as we have to keep the original dialog from which the calls originate, and generate a newer one for the forwarded call, including the forwarding details, and also match the user call limits according to active calls and database.

_Should we have to push a patch to allow Dialog to be called outside REQUEST_ROUTE, restoring the original working mode, or is there any other opportunity for achieve the same functionality?_

**Comment by fsantulli** [comment]
`--- a/modules/dialog/dialog.c
+++ b/modules/dialog/dialog.c
@@ -179,7 +179,7 @@
 static cmd_export_t cmds[]={
 	{"create_dialog", (cmd_function)w_create_dialog, {
 		{CMD_PARAM_STR|CMD_PARAM_OPT,0,0}, {0,0,0}},
-		REQUEST_ROUTE},
+		REQUEST_ROUTE|ONREPLY_ROUTE|FAILURE_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"set_dlg_profile", (cmd_function)w_set_dlg_profile, {
 		{CMD_PARAM_STR,0,0},
 		{CMD_PARAM_STR|CMD_PARAM_OPT,0,0}, {0,0,0}},
@@ -219,9 +219,9 @@
 		{CMD_PARAM_VAR,fixup_check_var,0}, {0,0,0}},
 		REQUEST_ROUTE|FAILURE_ROUTE|ONREPLY_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"validate_dialog",(cmd_function)w_validate_dialog, {{0,0,0}},
-		REQUEST_ROUTE},
+		REQUEST_ROUTE|FAILURE_ROUTE|ONREPLY_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"fix_route_dialog",(cmd_function)w_fix_route_dialog, {{0,0,0}},
-		REQUEST_ROUTE},
+		REQUEST_ROUTE|FAILURE_ROUTE|ONREPLY_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"get_dialog_info",(cmd_function)w_get_dlg_info, {
 		{CMD_PARAM_STR,0,0},
 		{CMD_PARAM_VAR,fixup_check_avp,0},
@@ -248,10 +248,10 @@
 		ALL_ROUTES},
 	{"match_dialog",  (cmd_function)w_match_dialog, {
 		{CMD_PARAM_STR|CMD_PARAM_OPT,fixup_mmode,0}, {0,0,0}},
-		REQUEST_ROUTE},
+		REQUEST_ROUTE|FAILURE_ROUTE|ONREPLY_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"set_dlg_sharing_tag", (cmd_function)w_set_dlg_shtag, {
 		{CMD_PARAM_STR,0,0}, {0,0,0}},
-		REQUEST_ROUTE},
+		REQUEST_ROUTE|FAILURE_ROUTE|ONREPLY_ROUTE|BRANCH_ROUTE|LOCAL_ROUTE},
 	{"load_dialog_ctx",(cmd_function)load_dlg_ctx, {
 		{CMD_PARAM_STR,0,0},
 		{CMD_PARAM_STR|CMD_PARAM_OPT,fixup_lmode,0}, {0,0,0}},`

**Comment by fsantulli** [comment]
Bump

**Comment by bogdan-iancu** [comment]
@fsantulli , OpenSIPS 2.3 also allows the `create_dialog()` ONLY from REQUEST route, as all the later versions, including 3.3. So nothing changed there, maybe the check became better ;)

Anyhow, IMO it makes no sense to use the function in other places than the REQUEST route. When using the dialog support, you should decide if creating a dialog or not from the very beginning. You MUST not use the dialog support as a something to substitute the accounting part - the dialog is for keeping track of the SIP calls, while if you want to have data on CF scenarios, better use ACC module with multi-leg accounting support.
