### ISSUE TITLE
[BUG] RTP Relay - SDP body duplication

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2879]
**OpenSIPS version you are running**

```
version: opensips 3.2.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:46:18 Jun 22 2022 with gcc 8
```

**Describe the bug**
Good day, team!
We are trying to use RTP Relay module instead of pure rtpengine manual handling and it seems like we have a bug:
When I'm trying to engage RTP Relay module (by rtp_relay_engage()) from request route - everything is ok, but when I'm trying to engage it from branch route - it inserts SDP body 2 times consequently to the message.
Like that:

v=0
o=CiscoSystemsCCM-SIP 677762544 1 IN IP4 RTPENGINE_ADDRESS
s=SIP Call
c=IN IP4 RTPENGINE_ADDRESS
b=TIAS:64000
b=AS:64
t=0 0
a=cisco-mari:v1
a=cisco-mari-rate
m=audio 30230 RTP/AVP 8 9 18 104 105 111 101
a=trafficclass:conversational.audio.aq:admitted
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:104 G7221/16000
a=fmtp:104 bitrate=32000
a=rtpmap:105 G7221/16000
a=fmtp:105 bitrate=24000
a=rtpmap:111 X-ULPFECUC/8000
a=fmtp:111   max_esel=1420;m=8;max_n=32;FEC_ORDER=FEC_SRTP
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30231
v=0
o=CiscoSystemsCCM-SIP 677762544 1 IN IP4 RTPENGINE_ADDRESS
s=SIP Call
c=IN IP4 RTPENGINE_ADDRESS
b=TIAS:64000
b=AS:64
t=0 0
a=cisco-mari:v1
a=cisco-mari-rate
m=audio 30230 RTP/AVP 8 9 18 104 105 111 101
a=trafficclass:conversational.audio.aq:admitted
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:104 G7221/16000
a=fmtp:104 bitrate=32000
a=rtpmap:105 G7221/16000
a=fmtp:105 bitrate=24000
a=rtpmap:111 X-ULPFECUC/8000
a=fmtp:111   max_esel=1420;m=8;max_n=32;FEC_ORDER=FEC_SRTP
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=rtcp:30231

Here is how I'm setting up my variables and engaging rtp relay:

````
route[INVITE] {
...
        $dlg_val(rtp_s) = "RTP/AVP replace-origin replace-session-connection ICE=remove";
        $dlg_val(rtp_d) = "RTP/AVP replace-origin replace-session-connection ICE=remove";
        route(RELAY);
...
}

route[RELAY] {
...
        t_on_branch("ON_BRANCH");
        t_relay();
        exit;
}

branch_route[ON_BRANCH] {
            $var(rtpdir_i) = "in-iface=external out-iface=internal ";
            $var(rtpdir_e) = "in-iface=internal out-iface=external ";
         

            $var(rtppar_s) = $dlg_val(rtp_s);
            $var(rtppar_d) = $dlg_val(rtp_d);

            $rtp_relay = $var(rtpdir_i) + $var(rtppar_s);
            $rtp_relay_peer = $var(rtpdir_e) + $var(rtppar_d);

            rtp_relay_engage("rtpengine",  1);

}
````

Speaking shortly - I'm setting $rtp_relay as string "**in-iface=external out-iface=internal RTP/AVP replace-origin replace-session-connection ICE=remove**" and $rtp_relay_peer as string "**in-iface=internal out-iface=external RTP/AVP replace-origin replace-session-connection ICE=remove**" and engaging module. 

**To Reproduce**
Setting up configuration like mine should be enough, I hope.

**Expected behavior**
SDP body should not be duplicated.

**OS/environment information**
 - Operating System: RHEL8
 - OpenSIPS installation: yum repo, stable version of 3.2.7
 - other relevant information:

**Comment by achalkov** [comment]
still require attention

**Comment by razvancrainea** [comment]
Are you calling `rtp_engine_engage()` twice?
Is this happening with the latest release?

**Comment by achalkov** [comment]
no, i'm calling rtp_engine_engage() only once. 
That was tested on 3.2.7 (and on every version from 3.2.4 - always the same behavior). I'll test on 3.2.8 a bit later and return with feedback

**Comment by achalkov** [comment]
@razvancrainea looks like still reproducing on 

version: opensips 3.2.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:02:39 Aug 17 2022 with gcc 8
