### ISSUE TITLE
[BUG] RTP Relay - error deleting mediasession on BYE

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2880]
**OpenSIPS version you are running**

```
version: opensips 3.2.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:46:18 Jun 22 2022 with gcc 8
```

**Describe the bug**
Good day, team!
Found another bug while trying to implement rtp relay module instead of manual rtpengine handling:

rtp relay not deleting media session from rtpengine on BYE|CANCEL received.

What I'm doing:
1. set up variables (both $rtp_relay and $rtp_relay_peer). 
2. engage rtp relay (rtp_relay_engage() - from request route or from branch route - got the same error)
3. call (common "INVITE-100-200-ACK-BYE-200" sequence)
4. got error in log and session without deletion mark on rtpengine

$rtp_relay set as "in-iface=external out-iface=internal RTP/AVP replace-origin replace-session-connection ICE=remove"
$rtp_relay_peer set as "in-iface=internal out-iface=external RTP/AVP replace-origin replace-session-connection ICE=remove"

**To Reproduce**
1.Set up config as it described in #2879 
2.Call

**Expected behavior**
session should be deleted from rtpengine on BYE or CANCEL

**Relevant System Logs**

```
Aug  2 17:19:13:661071 DEV-opensips /usr/sbin/opensips[103390]:DBG:rtpengine:parse_flags: replace-origin not supported for 3 op
Aug  2 17:19:13:661107 DEV-opensips /usr/sbin/opensips[103390]:DBG:rtpengine:parse_flags: replace-session-connection not supported for 3 op
Aug  2 17:19:13:661141 DEV-opensips /usr/sbin/opensips[103390]:ERROR:rtpengine:parse_flags: error processing flag `': no more memory
```

**OS/environment information**
 - Operating System: RHEL8
 - OpenSIPS installation: yum repo, stable version of 3.2.7
 - other relevant information:

**Comment by achalkov** [comment]
still require attention

**Comment by achalkov** [comment]
still reproducing on latest build

version: opensips 3.2.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:02:39 Aug 17 2022 with gcc 8

**Comment by razvancrainea** [comment]
This is a good idea, but I believe it will only solve half of the problem - having a list for the delete.
The second problem is passing a flag that is not being used at all by RTPengine in the delete command, i.e. transcoding flags. In 3.3 we sorted this out by adding a new node for specifying flags of rtpengine, but in 3.2 we did not have this mechanism.
That is why, at this point, I believe the best idea would be to avoid passing any flags to the delete command. This will be backwards compatible, as before now, even if you specify them, they would not be taken into account. Do you have other ideas, or do you see any downsides of this approach?

**Comment by okhowang** [comment]
we do not mean to pass flag to `delete` command.
when using `rtpengine_manage`, script may not known what command will be sent to rtpengine, but only a flag was passed to `rtpengine_manage`.
`rtp_relay_engage` has same problem, only `$rtp_relay` and `$rtp_relay_peer` was used.
