### ISSUE TITLE
[BUG] call_center & agent reject 

### ISSUE THREAD

**Issue by guestus** [OpenSIPS/opensips#2886]
**OpenSIPS version you are running**
```
version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 612e7a1fe
main.c compiled on 13:59:34 Jul 28 2022 with gcc 7
```
In the test enviroment i have one queue (flow) and two online agents (A and B, for example).
When call processed to queue and agent A rejects call (by busy or decline) the call_center dosn't proceed to next agent (B) and drop queue call whith same reason (busy or decline). 
Since 3.2 there is no .scripts xml configuration.
Is any additional configuration on b2b_logic needed?

**Comment by rvlad-patrascu** [comment]
Hi @guestus,

This has been fixed on master in commit 6e1ffc3, as well as backported to all the supported versions.
