### ISSUE TITLE
[BUG] Call not terminated until FR_INV_TIMEOUT expires if t_wait_for_new_branches() was calling in main route

### ISSUE THREAD

**Issue by man1207** [OpenSIPS/opensips#2891]
**OpenSIPS version you are running**
version: opensips 3.2.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 9

**Describe the bug**
I call t_wait_for_new_branches() in main route by example from https://opensips.org/html/docs/modules/3.2.x/event_routing.html#idp5535408
Two devices register their contacts and OS injects two branches
Then one device reject call by 486 BUSY.
I call t_wait_no_more_branches() and then call t_cancel_branch("a") in ONREPLY_ROUTE
But caller still waiting until FR_INV_TIMEOUT expires. 

**To Reproduce**
1. Add Push Notification EBR functionality to script form https://opensips.org/html/docs/modules/3.2.x/event_routing.html#idp5535408
2. Make call
3. Register two contacts to create two branches
4. Reject call by first device with 486 BUSY
5. Call t_wait_no_more_branches() in ONREPLY_ROUTE and then cancell second branch by t_cancel_branch("a")
6. Call at all will not terminated but should.

**Expected behavior**
Call should terminated if t_wait_no_more_branches() was called and cancelled all pending/ongoing non-2xx branches.

**Comment by bogdan-iancu** [comment]
Same discussion on the mailing list....

**Comment by bogdan-iancu** [comment]
Let me review the report and the provided patch

**Comment by bogdan-iancu** [comment]
Thank you @man1207 for the all the details and explanations here - very useful and helpful.
I agree with your solution, still I do not feel comfortable with moving `t_wait_no_more_branches()` AFTER the `t_forward_nonack()`, as this may open the gates for signaling races - having the max branch set after the INVITE is out and maybe a reply back !
So, please check the attached patch with a slightly different approach on the fix, but same main idea.
[opensips_3_3_wait_no_more_branches_fix.patch.txt](https://github.com/OpenSIPS/opensips/files/9558339/opensips_3_3_wait_no_more_branches_fix.patch.txt)

**Comment by man1207** [comment]
@bogdan-iancu Oh, sure! Your fix keeps `t_wait_no_more_branches()` BEFORE `t_forward_nonack()` and at the same time allows to call `t_wait_no_more_branches()` in Push Notification scenario properly.
Your patch seems to be great solution.

**Comment by bogdan-iancu** [comment]
OK @man1207 , let me know if the patch passes all your tests :)

**Comment by man1207** [comment]
> Any updates here? No progress has been made in the last 15 days, marking as stale. Will close this issue if no further updates are made in the next 30 days.

It is ongoning. I'm making tests

**Comment by man1207** [comment]
> OK @man1207 , let me know if the patch passes all your tests :)

@bogdan-iancu I made tests. All working as expected. I think that you can apply patch to master.
