### ISSUE TITLE
After "404 not found" occurs, can you continue to call again for a period of time?

### ISSUE THREAD

**Issue by August1023** [OpenSIPS/opensips#2894]
I want to realize that after "404 not found" or when the required record is not found in the location table, I can continue to call again for a period of time instead of returning the 404 status to the client immediately. Can this function be implemented in opensips.cfg? If so, which function should I use? Thank you.

**Comment by razvancrainea** [comment]
No issue here, please open a discussion on our [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

**Comment by August1023** [comment]
It seems to be inactive.
