### ISSUE TITLE
[BUG] tcp_connect_blocking_timeout

### ISSUE THREAD

**Issue by aofei0721** [OpenSIPS/opensips#2895]
[root@izwz93eh8zpwhsv9zo4gw9z sbin]# ./opensips -V
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9e1fcc915
main.c compiled on 15:06:32 Dec 14 2020 with gcc 4.8.5

**Describe the bug**
my jssip3.3.6 browser client Register on opensips 2.4.7, i make call to opensips forward to a gateway to my phone. when my phone hangup ,the bye single cann't send to my jssip browser  client. conversely，when the jssip browser hangup，my phone can recevie the bye single and hangup normal。the bye single uri contain public address.    the log:
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:core:tcp_connect_blocking_timeout: connect timed out, 4077 us elapsed out of 5000 us
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:proto_ws:ws_sync_connect: tcp_blocking_connect failed
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:proto_ws:ws_connect: connect failed
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:proto_ws:proto_ws_send: connect failed
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:tm:msg_send: send() to XX.XX.XX.140:14911 for proto ws/5 failed
Aug 18 14:59:06 izwz93eh8zpwhsv9zo4gw9z ./opensips[28422]: ERROR:tm:t_forward_nonack: sending request failed
Aug 18 14:59:11 izwz93eh8zpwhsv9zo4gw9z ./opensips[28420]: DBG:tm:timer_routine: timer routine:0,tl=0x7f9881fd3bd0 next=(nil), timeout=382
Aug 18 14:59:11 izwz93eh8zpwhsv9zo4gw9z ./opensips[28420]: DBG:tm:timer_routine: timer routine:2,tl=0x7f9881fd3a00 next=0x7f9881fb8488, timeout=382

and i see the issue #1679,i set tcp_connect_timeout=5 or tcp_connect_timeout=300 in config file ,it still doesn't work。

**Expected behavior**
i Expected the bye single can send to browser normal.

**OS/environment information**
 - Operating System: centos 7.9
 - OpenSIPS installation: source

**Comment by razvancrainea** [comment]
You should never connect to a browser using WS, it will never work. You should make sure of this by setting the [tcp_no_new_conn_bflag](https://www.opensips.org/Documentation/Script-CoreParameters-2-4#toc72) on requests/replies going to a WSS client.
All you can do is make sure you call [fix_nated_contact](https://opensips.org/docs/modules/2.4.x/nathelper.html#func_fix_nated_contact) on all requests/replies coming from the WSS client, and make sure the client does not close the connection. If it does, and does not re-open it, you're out of options.
Nevertheless, if there really is a bug, please consider updating your OpenSIPS instance to the latest [2.4](https://www.opensips.org/About/Version-2-4-x) version. If the problem still persists, please ask for help on our [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

**Comment by aofei0721** [comment]
i  connect to a browser using WSS，i don't know why it change to ws? i also had set tcp_no_new_conn_bflag = TCP_NO_CONNECT.Also i had call fix_nated_contact function on all request/replies. and the client does not close the connection,because send the bye single port is the same to the register and invite.

**Comment by bogdan-iancu** [comment]
and are you setting the bflag `TCP_NO_CONNECT` when saving a registration that came via WS(S)?
