### ISSUE TITLE
[CRASH] Segmentation fault

### ISSUE THREAD

**Issue by anki-genesys** [OpenSIPS/opensips#2896]
**OpenSIPS version you are running**

version: opensips 2.4.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6d151d121
main.c compiled on 18:00:11 Aug 16 2022 with gcc 7

**Crash Core Dump**

https://pastebin.com/V8XT55Q6

**Comment by anki-genesys** [comment]
Crash occurred again on  25th Aug 2022.

Crash Core Dump
https://pastebin.com/LNFZy7Vs
https://pastebin.com/0wXPRSDv

This crash occurs when SIP traffic over TLS.

**Comment by bogdan-iancu** [comment]
@anki-genesys , 2.4 is no longer supported for quite some time. Please upgrade to 3.2 or 3.3
