### ISSUE TITLE
[BUG] E_CLUSTERER_REQ_RECEIVED - event not raised, and more

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2899]
**OpenSIPS version you are running**

```
version: opensips 3.2.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 17:02:39 Aug 17 2022 with gcc 8
```

**Describe the bug**
I'm trying to send generic clusterer request via cluster_broadcast_req() function and catch it on another node(s) on event  E_CLUSTERER_REQ_RECEIVED, but event not raises.
On sender side - function returns 1 (successful), on receiver side - I can see received request, but  seems like values are mixed up, and no event rises.

Code on sender side:
```
cluster_broadcast_req(1, "C_GLOBAL", $var(req_tag));
$var(retcode) = $retcode;
xlog("L_INFO", "[DEBUG] bin retcode = [$var(retcode)], tag = [$var(req_tag)]\n");
```

Code on receiver side:

```
event_route[E_CLUSTERER_REQ_RECEIVED] {
    xlog("L_INFO", "[DEBUG] clusterer request received\n");
}
```
proto_bins over tls_openssl for communication between nodes. 

On sender side we have this log entry:
```
Aug 24 16:02:38 opensips-dev1 /usr/sbin/opensips[3822444]:[DEBUG] bin retcode = [1], tag = [1-1-JJNxIrvkM4YDk5NyOfQD5etn]
```

On receiver side - this:

```
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:clusterer:bin_rcv_cl_extra_packets: received clusterer message from: NODE1_ADDR:53555 with source id: 1 and cluster id: 1
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:clusterer:handle_cl_gen_msg: Received generic clusterer message
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:bin_pop_str: Popped: '1-1-JJNxIrvkM4YDk5NyOfQD5etn' [28]
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:bin_pop_str: Popped: 'C_GLOBAL' [8]
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:evi_param_set: set int cluster_id=1
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:evi_param_set: set int src_id=1
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:evi_param_set: set str msg='1-1-JJNxIrvkM4YDk5NyOfQD5etn'
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:evi_param_set: set str tag='C_GLOBAL'
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:get_dummy_sip_msg: reusing the static sip msg 0x7ff4b2f2bf58
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:release_dummy_sip_msg: cleaning the static sip msg 0x7ff4b2f2bf58
Aug 24 16:02:38 opensips-dev2 /usr/sbin/opensips[3929165]:DBG:core:destroy_avp_list: destroying list (nil)
```

As you can see - receiver interprets sender's tag as msg, and sender's msg as tag.
And most important that after this - no event is raised on receiver side, which makes impossible to fetch received data.

**To Reproduce**
use provided code in config, call sender's part on some event (for example - on received call), check logs

**Expected behavior**
event raised on receiver side, received msg values are available in event route

**OS/environment information**
 - Operating System: RHEL8
 - OpenSIPS installation: opensips yum repo (stable)

**Comment by rvlad-patrascu** [comment]
Hi @achalkov ,

I've just fixed the mixed up parameters but regarding the event not being raised, you've probably just forgot to load the `event_route` module. I did the same thing when trying to reproduce this :) But feel free to reopen the issue if it's not case.

**Comment by achalkov** [comment]
@rvlad-patrascu yeah really :) 
Many thanks for quick fix!

**Comment by achalkov** [comment]
maybe makes sense to add some checks which will prevent opensips start when event_route used in routing script without module loaded?  Really easy to forgot that this module exists :)
