### ISSUE TITLE
[FEATURE] cachedb_local replication - per-collection options

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2901]
**Is your feature request related to a problem? Please describe.**
cachedb_local is a great tool to work with data, which should be shared across processing. In some cases we could want to replicate its content between opensips nodes inside the cluster, but there is a problem - in cases, when we have very intensive cachedb_local usage (store/modify/fetch data multiple times on every call), if replication is enabled - opensips replicates all this operations to cluster, which could produce unnecessary load and traffic, while we might want to replicate only some of this operations.

**Describe the solution you'd like**
It would be great to get ability to set up replication for every existent collection. For example - enable replication for collections one and two, and disable replication for collection 3. If so - we'd be able to use non-replicatable collections for intensive operations with local data and replicatable collections to share data from them to the cluster. 

**Implementation**
 
  - Component: cachedb_local module

**Comment by rvlad-patrascu** [comment]
This is already possible since opensips 3.3, via the [cache_collections](https://opensips.org/docs/modules/3.3.x/cachedb_local.html#param_cache_collections) modparam, by using the `/r` suffix.
