### ISSUE TITLE
OPTIONS message with nathelper

### ISSUE THREAD

**Issue by InnovateAsterisk** [OpenSIPS/opensips#2905]
**Is your feature request related to a problem? Please describe.**
When the nathelper module sends an OPTIONS message, it doesn't contain the username in the request uri. My client is rejecting the options packets as saying that they are not for this client (correctly).

I'm busy reading the RFC's but either OpenSIPS isn't operating correctly, or i am not understanding this. It appears not necessary for the request line to contain a username, fine, but when it does, it should be relayed to the client, also fine. However in the case that the registration is actually directly from client-to-OpenSIPS (using registrar module), the nathelper sipping functions are treating the OpenSIPS server as the proxy and omitting the username. The RFC says that if the username is present in the request rui, it should be relayed to the client, but in this direct client-to-server arrangement, the OPTIONS packet that OpenSIPS generates, appears incorrect. (Or at least I cant set it) 

**Describe the solution you'd like**
When registration occurs directly on OpenSIPS (not proxied), the nathelper sipping message (when sipping_method = "OPTIONS") must send the username in the request line.

from
```
OPTIONS sip:1.2.3.4:34308;transport=ws SIP/2.0
Via: SIP/2.0/WS 1.2.3.4:8080;branch=z9hG4bK50ed41e2
From: sip:hello@1.2.3.4;tag=96b215f1
To: sip:5.6.7.8:34308;transport=ws
Call-ID: fca4fea1-50ed41e2-40e@172.31.25.159
CSeq: 1 OPTIONS
Max-Forwards: 70
Content-Length: 0
```
to
```
OPTIONS sip:username@1.2.3.4:34308;transport=ws SIP/2.0
Via: SIP/2.0/WS 1.2.3.4:8080;branch=z9hG4bK50ed41e2
From: sip:hello@1.2.3.4;tag=96b215f1
To: sip:5.6.7.8:34308;transport=ws
Call-ID: fca4fea1-50ed41e2-40e@172.31.25.159
CSeq: 1 OPTIONS
Max-Forwards: 70
Content-Length: 0
```

**Comment by volga629-1** [comment]
Feature request ticket is open here are.

https://github.com/OpenSIPS/opensips/issues/2165

**Comment by InnovateAsterisk** [comment]
Since this is full of debate around the interpretation of the RFC, and currently found under nathelper maybe the sipping setting should be copied over to the registrar module:

```
modparam("registrar", "sipping_interval", 120)
modparam("registrar", "sipping_method", "OPTIONS")
modparam("registrar", "sipping_from", "sip:hello@172.31.25.159")
```

Should you select both, then two different options messages can be sent, satisfying a proxy route, and a direct registration. except the above mentioned option packet would contain the username and the contact, so that the message can be fully interpreted and responded to (as is the point of an OPTIONS message), not just to keep the nat connections open.

**Comment by bogdan-iancu** [comment]
let's continue this on #2165
