### ISSUE TITLE
[CRASH] opensips terminates by calling abort() in unref_dlg_unsafe()

### ISSUE THREAD

**Issue by MayamaTakeshi** [OpenSIPS/opensips#2906]
**OpenSIPS version you are running**
```
[root@lab002167-basix-ban opensips-3.2]$ /usr/local/src/git/opensips-3.2/opensips -V
version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f380dc59e
main.c compiled on 22:54:51 Jul  1 2022 with gcc 8
```

**Crash Core Dump**
https://pastebin.com/A17qzD3x

**Describe the traffic that generated the bug**

I was load testing with INVITE. Traffic was not high. About 20 CPS. Crash happened after 40 days.

**To Reproduce**
This is not reproducible at will. It happened only once so far (I have another load testing environment and it is running fine after 70 days)

**Relevant System Logs**
Sorry, by the time I noticed the crash, opensips logs were already rotated and lost.

**OS/environment information**
 - Operating System:  Debian GNU/Linux 10 \n \l
 - OpenSIPS installation: build from github source
 - other relevant information:

**Comment by razvancrainea** [comment]
Please upgrade to the latest OpenSIPS 3.2 sources, and if the crash is still happening, provide an updated crash dump.

**Comment by MayamaTakeshi** [comment]
OK. I have upgraded to commit 5e42e9422b43bf754568d76c6921f27609a89333.
I have started 5 load test environments with it.
If opensips 3.2 doesn't crash after 3 months I will close this ticket.
Thanks.
