### ISSUE TITLE
[CRASH] CRITICAL:core:qm_free_dbg: freeing already freed pointer

### ISSUE THREAD

**Issue by SteveAyre** [OpenSIPS/opensips#2907]
**OpenSIPS version you are running**

```version: opensips 3.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7b981f6c9
main.c compiled on  with gcc 10
```

**Crash Core Dump**

https://gist.github.com/SteveAyre/c614630929cb697d36f22c275c6df501

**Describe the traffic that generated the bug**
Production SIP traffic using OpenSIPS and RTP Engine.

**To Reproduce**
No specific steps - intermittent error on production traffic.

**Relevant System Logs**
```Sep  9 10:14:47 [105] CRITICAL:core:qm_free_dbg: freeing already freed pointer, first free: h_table.c: free_cell(163) - aborting```
https://gist.github.com/SteveAyre/c7a2f5037345027ce5996a6461a89daf

**OS/environment information**
OpenSIPS built from source installed in Debian Bullseye docker container.

**Comment by SteveAyre** [comment]
Do you need any more information to investigate this?

**Comment by SteveAyre** [comment]
Backtrace for another similar crash
https://gist.github.com/SteveAyre/93f5bccf1981b5f60971b77575bf011f

This crashes in qm_debug_frag (different point), but this is called by qm_free_dbg (same function call).

**Comment by RobWMoore** [comment]
we still encounter this issue. Commenting to keep alive.

**Comment by RobWMoore** [comment]
Hey Liviu, Yeah we're going to give it a go on 3.3.2 and see if we can reproduce. we'll raise a new issues if we find a problem

**Comment by palmtown** [comment]
Hello Community,

Please note that I am experiencing this error on 3.3.3-1 as show below.  I experienced it trying to start OpenSIPS and it fails to start. 

Jan  1 18:58:27 /usr/sbin/opensips[4762]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f12d2b42a58), first free: (null): (null)(0) - aborting!

**Comment by palmtown** [comment]
In addition to trying to restart OpenSIPS, when OpenSIPS receive an inbound call, it cashes.  I think this is related to an issue I posted at https://github.com/OpenSIPS/opensips/issues/2979.
