### ISSUE TITLE
in-memory caching behaviour in Opensips Module

### ISSUE THREAD

**Issue by ishvaram** [OpenSIPS/opensips#2910]
There are some inbuilt APIs available with the modules like dispatcher/ presence that internally cache the details in-memory. but whenever the new entry gets added into the address table/dispatcher table it doesn't read from DB and caches it in memory, Opensips service restart is mandatory for this.

Ideally, if there is an entry in cache return from the cache, if not query DB and cache that as well so the subsequent requests can be served from cache. 
```
ds_next_dst
ds_select_dst
ds_select_domain
ds_next_domain
check_address
.. and so on.
```

This should be done across all modules wherever we use in-built cache though

**Comment by liviuchircu** [comment]
Hi, @ishvaram!  Did you try the [MI Functions](https://opensips.org/html/docs/modules/3.3.x/dispatcher.html#exported_mi_functions) of the dispatcher module?  You can access them via `opensips-cli` (opensips-cli -x mi ds_reload), or Control Panel "dispatcher" tool, or even using `curl` with JSON-RPC).

So any time you change the DB, you should send a reload command, to trigger the re-caching, without disrupting ongoing calls or requiring a full restart.
