### ISSUE TITLE
[BUG] registrar function lookup with flag 'r' (bRanch lookup) fails if no contacts are found for one of the AORs

### ISSUE THREAD

**Issue by MayamaTakeshi** [OpenSIPS/opensips#2917]
**OpenSIPS version you are running**
```
$ ./opensips -V
version: opensips 3.3.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 8686647ae
main.c compiled on 18:20:40 Sep 28 2022 with gcc 10

```
**Describe the bug**

The first AOR that results in zero contacts will cause lookup() to return with -1 (LOOKUP_NO_RESULTS):

https://github.com/OpenSIPS/opensips/blob/8686647ae87a7968a939894ecabb2d457c3f79d8/lib/reg/lookup.c#L128

even if other AORs were or might be found with contacts.

**Expected behavior**
lookup("location", "r") should not abort iteration and should only return LOOKUP_NO_RESULTS if no contacts are found for all AORs.

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: git

**Additional context**
It might turn out this behavior is intentional.
If so, I would switch this to a feature request to have a flag to permit to instruct lookup() to not abort iteration in case of branch lookup.

**Comment by liviuchircu** [comment]
Hi, @MayamaTakeshi and thanks for the report!  This definitely looks like a bug, as the whole point of the `"r"` `lookup()` flag is to expand `N` Addresses-of-Record into `M` contacts.  I don't see a need for special handling on the edge-case where an individual AoR from your "expansion list" has `0` contacts (... so what? :-) ).

Also, I don't see how backporting this all the way down to `3.1` may break things for our users, as it is tricky to control _which_ AoR (positionally-wise) has `0` contacts, so you stop the iteration.  So I think the fix will only do good for everyone.

Let me reproduce the issue and develop the fix, so we can close things out here.

**Comment by liviuchircu** [comment]
@MayamaTakeshi: I just pushed a preliminary fix on `master` branch, as it was pretty straightforward.  Let me know if you can test it and give some feedback.  Meanwhile, I try to do some testing of my own.

**Comment by MayamaTakeshi** [comment]
@liviuchircu: I tested latest commit 02ddcc6 and could confirm the issue was solved. Thanks.
