### ISSUE TITLE
[BUG] siplua error attempt to call global function 'xlog' 

### ISSUE THREAD

**Issue by ot-i-to** [OpenSIPS/opensips#2924]
**OpenSIPS version you are running**
version: opensips 3.3.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on with gcc 10

Linux os-rtp 5.10.0-18-amd64 https://github.com/OpenSIPS/opensips/issues/1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
Description: Debian GNU/Linux 11 (bullseye)
```
```

**Describe the bug**
Calling xlog function in lua script results in error 
`Oct 12 13:28:24 os-rtp osTEST[14172]: siplua: siplua error running function info: /etc/opensips/script/app.lua:15: attempt to call global 'xlog' (a nil value)`

**To Reproduce**
--- /etc/opensips/script/app.lua
```
function run()
    xlog (" ----> TEST <----");
end
```

--- opensips.cfg
```
...
lua_exec("run");
...
```

**Expected behavior**
**Relevant System Logs**
--- opensips.log
```
...
Oct 12 13:28:24 os-rtp osTEST[14172]: siplua: siplua error running function info: /etc/opensips/script/app.lua:15: attempt to call global 'xlog' (a nil value)
...
```

**Comment by razvancrainea** [comment]
Can you please the lua version you are using?
