### ISSUE TITLE
[BUG ] 3.3.1 - RTP Relay - wrong ifaces order from branch route

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2926]
**OpenSIPS version you are running**

```
version: opensips 3.3.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 998d1e757
main.c compiled on 01:17:47 Oct 12 2022 with gcc 8
```

While calling rtp_relay_engage() from branch route - rtpengine ifaces are set in wrong order.

Lets say we have iface intarnal with ip 192.168.0.1 and iface seg_test with ip 8.8.8.8 on our rtpengine. 
Lets set $rtp_relay as "in-iface=internal out-iface=seg_test" and $rtp_relay_peer as "in-iface=seg_test out-iface=internal", so while relaying initial INVITE - SDP c-line should contain 8.8.8.8 (as it is out interface facing to callee side) and while relaying 200 OK - SDP c-line should contain 192.168.0.1 (as it is out interface facing to caller). 

That should look like:
```
For INVITE: A  -> (192.168.0.1)RTPEngine(8.8.8.8)  -> B
For 200 OK: A  <- (192.168.0.1)RTPEngine(8.8.8.8)  <- B
```
If we call rtp_relay_engage() from branch route - ifaces are seems mixed up and while relaying initial INVITE - we are sending 192.168.0.1 (which is iface=internal) and while relaying 200 OK  - we are sending 8.8.8.8 (which is iface=seg_test). That is, obviously, not correct.

And it looks like:
```
For INVITE: A  -> (8.8.8.8)RTPEngine(192.168.0.1)  -> B
For 200 OK: A  <- (8.8.8.8)RTPEngine(192.168.0.1)  <- B
```

While calling rtp_relay_engage() from request route - everything is ok, interfaces are set in correct order, so bug reproducing only while calling rtp_relay_engage() from branch route.

**To Reproduce**
```
$rtp_relay = "RTP/AVP replace-origin replace-session-connection ICE=remove in-iface=internal out-iface=seg_test";
$rtp_relay_peer = "RTP/AVP replace-origin replace-session-connection ICE=remove in-iface=seg_test out-iface=internal";
rtp_relay_engage("rtpengine", 1);
```

**Expected behavior**
Interfaces are set in correct order.

**Relevant System Logs**
No related information in logs.

**OS/environment information**
RHEL8

**Additional context**

**Comment by razvancrainea** [comment]
Hi, Artem!

The report is absolutely valid: according to the [documentation](https://opensips.org/docs/modules/3.3.x/rtp_relay.html#pv_rtp_relay), when using the `$rtp_relay` variable in either request route or branch route, it should provision the properties of the caller.
However, according to my initial idea, and how it is implemented in the code, the `$rtp_relay` variable used in branch route provisions the properties of the callee (on that specific branch). The way it is supposed to work is like this: in request route, where you don't have (all the time) all the information about the destination, but only about the caller, you set the interface for the caller: `$rtp_relay = "internal";`. Then, when you start forking, and reach branch_route, you should have information about the callee, so you would be setting the interface for the callee, using the same variable: `$rtp_relay = "seg_test";`. So in normal circumstances, `$rtp_relay` should be the only needed variable. At least that was the initial plan :).

To get to the bottom of this, I would say the correct "fix" would be to clarify the documentation. Unless you argue about changing the code :).

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Yes, your logic is correct. The syntax is not, but let's just call it a "pseudo-code", and it is OK.
