### ISSUE TITLE
[BUG] E_CORE_TCP_DISCONNECT not firing on UAC TCP registration disconnect

### ISSUE THREAD

**Issue by rsmck** [OpenSIPS/opensips#2928]
**OpenSIPS version you are running**

```
version: opensips 3.3.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 13:43:21 Aug 17 2022 with gcc 4.8.5
```
and
```
version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9f14bb0
main.c compiled on 14:22:15 Oct 17 2022 with gcc 4.8.5
```

**Describe the bug**

The `event_route[E_CORE_TCP_DISCONNECT]` block is not called when a TCP session disconnects.

**To Reproduce**
1. Configure opensips with `uac_registrant` module to make registrations to another host using TCP and a simple event_route[E_CORE_TCP_DISCONNECT] block containing an xlog() or similar.
2. Kill the connection (e.g. kill the SIP UA process on the other host)
3. The event_route[E_CORE_TCP_CONNECT] is not called

**Expected behavior**

Given the following configuration in opensips.cfg;
```
event_route[E_CORE_TCP_DISCONNECT] {
    xlog("TCP connection from $param(src_ip):$param(src_port) to $param(dst_ip):$param(dst_port) has dropped \n");
}
```
I would expect to see a log entry of the form above when the TCP connection closes.

**Relevant System Logs**

On starting opensips, the event appears to be correctly registered 
```
Oct 17 14:01:58 [7869] DBG:event_route:child_init: Registering event E_CORE_TCP_DISCONNECT
Oct 17 14:01:58 [7869] DBG:event_route:scriptroute_parse: route is <E_CORE_TCP_DISCONNECT> idx 1
Oct 17 14:01:58 [7869] DBG:core:evi_event_subscribe: added new subscriber for event 5
```

On closing the TCP session the folioing logo entries are observed (showing the call to tcpconn_release);
```
Oct 17 13:59:55 [7618] DBG:core:tcp_read_req: Using the global ( per process ) buff
Oct 17 13:59:55 [7618] DBG:core:tcp_read: EOF on 0x7fa6c8917fb0, FD 4
Oct 17 13:59:55 [7618] DBG:core:tcp_read_req: EOF received
Oct 17 13:59:55 [7618] DBG:core:io_watch_del: [TCP_worker] io_watch_del op on index 0 4 (0x989440, 4, 0, 0x10,0x3) fd_no=5 called
Oct 17 13:59:55 [7618] DBG:core:tcpconn_release:  releasing con 0x7fa6c8917fb0, state -1, fd=-1, id=659647175
Oct 17 13:59:55 [7618] DBG:core:tcpconn_release:  extra_data (nil)
Oct 17 13:59:55 [7621] DBG:core:handle_tcp_worker: response= 7fa6c8917fb0, -1 from tcp worker 0 (0)
Oct 17 13:59:55 [7621] DBG:core:tcpconn_destroy: destroying connection 0x7fa6c8917fb0, flags 0038
```

**OS/environment information**
 - Operating System: Consistent with CentOS EL7 and and Debian 9
 - OpenSIPS installation: Yum Repos and Compile from git HEAD at 9f14bb0

**Additional context**
Inspecting `mi list_tcp_conns` before killing the TCP session shows the connection as expected, inspecting the same output after killing the TCP session shows an empty array for Connections;

```
{
    "Connections": []
}
```

**Comment by rsmck** [comment]
To provide a little more information on this `evi_probe_event(EVI_TCP_DISCONNECT)` is returning false in `tcp_disconnect_event_raise` despite the config containing a reference to `Registering event E_CORE_TCP_DISCONNECT`

**Comment by rsmck** [comment]
Found a fix in the form of a workaround. I note that the evi_event_subscribe identified it as event 5 yet the definition in `evi/evi_core.h` is event 4.

Changing `evi/evi_core.h:34` to `#define EVI_TCP_DISCONNECT	5` results in the event_route[] being called as expected. 

Should these IDs perhaps be declared starting at 1 not 0? (in which case would this means that the other E_CORE_ events would also not function correctly?

**Comment by vladpaiu** [comment]
Hello,

Confirming the core events get indexed starting from 1 - looking into this.

**Comment by rsmck** [comment]
Ah, excellent, thanks. So this should be as simple as changing the #defines in evi_core.h to 
```
#define EVI_THRESHOLD_ID              1
#define EVI_SHM_THRESHOLD_ID    2
#define EVI_PKG_THRESHOLD_ID    3
#define EVI_PROC_AUTO_SCALE_ID  4
#define EVI_TCP_DISCONNECT	5
```

Which works as expected. Thanks :)
