### ISSUE TITLE
[FEATURE] control RTPEngine via http/https or ws/wss

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#2933]
**Is your feature request related to a problem? Please describe.**

Right now we have ability to control rtpengine instances only through UDP and UNIX-socket based communications (using ng control protocol). However - rtpengine supports ng-control over http/https and ws/wss. Ability to control rtpengine instances through http (and especially https) and ws (and especially wss) will allow us to build much more secure infrastructures based on TLS. For example - right now its not possible to define some ACL on rtpengine side which will control who can establish NG-connections to control rtpengine and who not, without involving network filters and firewalls (iptables, etc). Adding ability to connect over https/wss will allow us to take full control on that aspect of communication.

**Describe the solution you'd like**

Add ability to chose transport for NG-connection to rtpengine besides UDP and UNIX-socket. Add ability to establish secure connections.

**Implementation**
 
Component: rtpengine module

**Additional context**

It would be especially great if we'll get ability to manage keys/certs for NG-connections over TLS right from rtpengine module, not involving tls_mgm configuration directly.

**Comment by volga629-1** [comment]
Feature request is right here are. 

#2296
