### ISSUE TITLE
[FEATURE]several SIP phones with same SIP account ring together and hang up asynchronous

### ISSUE THREAD

**Issue by MyZyl** [OpenSIPS/opensips#2934]
Hi，friends, 

for example, phone A/B configured with the same SIP account.  when phone C call the sip account , phone A/B will ring at the same time. At the ringing state, when A hang up the call, C will be terminated by opensips. is there a way to let B still calling instead of terminated?

**Comment by razvancrainea** [comment]
What you are describing is the default mechanism in OpenSIPS, and unless you are doing something else (like cancelling onging branches), it works like you mentioned. Unless you're hitting a bug - in that case, you should open a Bug report with detailed information about how it works, and provide as much information as possible. In the meantime, I will close this Feature Request.
