### ISSUE TITLE
[CRASH] on startup with auth secret param defined

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#2935]
**OpenSIPS version you are running**

```
version: opensips 3.2.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d2496fed5
main.c compiled on 14:19:53 Aug 30 2022 with gcc 4.8.5

```

**Crash Core Dump**

This is short:
(gdb) bt full
#0  0x00007f08fe12c387 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f08fe12da78 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f08fe1251a6 in __assert_fail_base () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f08fe125252 in __assert_fail () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f088f5939cc in dauth_noncer_init (pub=0x7f08fa3da518) at dauth_nonce.c:247
        self = 0x7f08fa3da518
        key = 0x1b924d0 "supersecret"
        __FUNCTION__ = "dauth_noncer_init"
        __PRETTY_FUNCTION__ = "dauth_noncer_init"
#5  0x00007f088f58dd81 in mod_init () at auth_mod.c:234
        stmp = {s = 0xffffffffffffffff <Address 0xffffffffffffffff out of bounds>, len = 5023329}
        __FUNCTION__ = "mod_init"

**Describe the traffic that generated the bug**

happens on startup
**To Reproduce**

set modparam for auth module
   modparam("auth", "secret", "supersecret")
attempt to start
**Relevant System Logs**

**OS/environment information**
 - Operating System:   Cent OS 7
 - OpenSIPS installation:  rpm created from source
 - other relevant information:

**Additional context**

**Comment by rrevels-bw** [comment]
i can get it to load when i set a secret of 32 chars length.  havent tried running a call yet to make sure everything else is happy with that.

**Comment by sobomax** [comment]
Richard, you are right. This parameter is expected to be 32-characters long, I've converted DASSERT into proper check and updated the documentation, hope it helps. Thanks for reporting!

**Comment by rrevels-bw** [comment]
Works for me.  Thank You!
