### ISSUE TITLE
[CRASH] OpenSIPS 3.2 crash while removing the shared memory

### ISSUE THREAD

**Issue by Badareenadh** [OpenSIPS/opensips#2938]
Open Sips service has crashed while cloning the SIP message for incoming call in the shared memory.  

Could you please verify the issue.

Version:

3.2

Core dump Link:

https://drive.google.com/file/d/1PKJE3tKRPNvtaMwFl5ztnAJh8DVAv9d8/view?usp=sharing

OS:

Oracle 8.4

Traffic details:

Combination of UDP and TLS.

**Comment by razvancrainea** [comment]
Please adhere to the reporting template - at least that would have indicated us the exact version of OpenSIPS you were using.

**Comment by Badareenadh** [comment]
Sorry for the delay response.

Please find the opensips version details.

version: opensips 3.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
svn revision: 1:2M
main.c compiled on 17:33:43 Sep 30 2022 with gcc 8
