### ISSUE TITLE
[BUG] b2b_init_request generated To header does not contain <> when using "top hiding" on 3.3.2

### ISSUE THREAD

**Issue by brandonrobinson5060** [OpenSIPS/opensips#2940]
Hey guys,

As mentioned in https://github.com/OpenSIPS/opensips/issues/2843 , I'm also seeing issues where a UAS can not parse the message with the To uri not being surrounded in <>.  

**OpenSIPS version you are running**

```
version: opensips 3.3.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 11
```

**Describe the bug**
When invoking the b2b_init_request, the To header generated doesn't have the <>.  And while this may be perfectly legal, some UAs can't handle this and not allowing us to use certain routes.  

I've tried a multitude of things such as:

1. passing through the To header in modparam("b2b_logic", "custom_headers", "To")
     Result: duplicate To headers on UAC side and remove_hf isn't removing anything
2. Tried b2b_init_request("top hiding", "p") to preserve To header.  
     Result: ust preserves the URI, but not the <>
3. Tried uac_replace_to - 
     Result: this seems to be ignored
4. Tried subst
     Result: this seemed to be ignored

Any help that can be provided would be appreciated. 
Thanks.
Brandon

**Comment by ivanortizfierro** [comment]
I have that same problem with B2B, HELP!

Any idea will be highly appreciated.

Thanks.
Ivan

**Comment by bogdan-iancu** [comment]
Not sure what should we do here, as the problem you report in a crass violation of the RFC basic SIP grammar by other implementations...I'm not really happy with the idea of forcing the angle brackets all the time, just to cope with broken implementations...sounds like opening pandor's box..

**Comment by bogdan-iancu** [comment]
Let's follow on #2843 , which at least is a valid report
