### ISSUE TITLE
[CRASH]  Opensips core dumps when rtpengine module is loaded with lua module

### ISSUE THREAD

**Issue by ryan-netizen** [OpenSIPS/opensips#2947]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10

```

**Crash Core Dump**
```
root@vultr:/etc/opensips/cdrs# gdb core
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"0x7ffdce9c77d0s": not in executable format: file format not recognized
(gdb) bt full
No stack.
(gdb)

```

**Describe the traffic that generated the bug**

As soon as I try to enable rtpengine module with lua module inside the opensips.cfg, opensips core dumps instantly with below logs. 

Nov 04 14:50:42 vultr systemd[1]: Starting OpenSIPS is a very fast and flexible SIP (RFC3261) server...
Nov 04 14:50:42 vultr opensips[870484]: INFO:core:fix_poll_method: using epoll as the IO watch method (auto detected)
Nov 04 14:50:42 vultr opensips[870484]: Listening on
Nov 04 14:50:42 vultr opensips[870484]:              udp: 127.0.0.1 [127.0.0.1]:5060
Nov 04 14:50:42 vultr opensips[870484]:              hep_udp: 127.0.0.1 [127.0.0.1]:9099
Nov 04 14:50:42 vultr opensips[870484]: Aliases:
Nov 04 14:50:42 vultr opensips[870484]:              hep_udp: localhost:9099
Nov 04 14:50:42 vultr opensips[870484]:              udp: 127.0.0.1.vultrusercontent.com:5060
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: NOTICE:core:main: version: opensips 3.2.9 (x86_64/linux)
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: NOTICE:core:main: using 64 MB of shared memory, allocator: F_MALLOC
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: NOTICE:core:main: using 4 MB of private process memory, allocator: F_MALLOC
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: WARNING:core:init_reactor_size: shrinking reactor size from 262144 (autodetected via rlimit) to 10485 (limited by memory of 10% from 4Mb)
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: WARNING:core:init_reactor_size: use 'open_files_limit' to enforce other limit or increase pkg memory
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:init_reactor_size: reactor size 10485 (using up to 0.40Mb of memory per process)
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_CORE_THRESHOLD(0)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_CORE_SHM_THRESHOLD(1)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_CORE_PKG_THRESHOLD(2)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_CORE_PROC_AUTO_SCALE(3)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:mod_init: initializing UDP-plain protocol
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:tm:mod_init: TM - initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:sl:mod_init: Initializing StateLess engine
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: NOTICE:signaling:mod_init: initializing module ...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:db_postgres:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:rr:mod_init: rr - initializing
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:maxfwd:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:sipmsgops:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:dialog:mod_init: Dialog module - initializing
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_DLG_STATE_CHANGED(4)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:topology_hiding:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:acc:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_ACC_EVENT(5)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_ACC_CDR(6)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_ACC_MISSED_EVENT(7)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_DISPATCHER_STATUS(8)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:ratelimit:mod_init: Ratelimit module - initializing ...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:permissions:parse_config_file: file not found: /etc/opensips/permissions.allow
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:permissions:mod_init: default allow file (/etc/opensips/permissions.allow) not found => empty rule set
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:permissions:parse_config_file: file not found: /etc/opensips/permissions.deny
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:permissions:mod_init: default deny file (/etc/opensips/permissions.deny) not found => empty rule set
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:uac:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:auth:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:auth_db:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:usrloc:ul_init_locks: locks array size 512
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_AOR_INSERT(9)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_AOR_DELETE(10)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_INSERT(11)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_UPDATE(12)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_DELETE(13)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_REFRESH(14)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:core:evi_publish_event: Registered event <E_UL_LATENCY_UPDATE(15)>
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:registrar:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: siplua: mod_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: siplua: mod_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:uac_registrant:load_reg_info_from_db: loading [2] records from db
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: NOTICE:cachedb_redis:mod_init: initializing module cachedb_redis ...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:dialplan:mod_init: initializing module...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:cfgutils:mod_init: no hash_file given, disable hash functionality
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:cfgutils:mod_init: module initialized, pid [870486]
Nov 04 14:50:42 vultr /usr/sbin/opensips[870486]: INFO:tracer:mod_init: initializing...
Nov 04 14:50:42 vultr /usr/sbin/opensips[870496]: CRITICAL:core:sig_usr: segfault in process pid: 870496, id: 1
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: siplua: Lua state opened
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: siplua: Lua state opened
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:42 vultr /usr/sbin/opensips[870505]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870505]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870505]: siplua: Lua state opened
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:42 vultr /usr/sbin/opensips[870503]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870503]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870503]: siplua: Lua state opened
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:42 vultr /usr/sbin/opensips[870497]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:42 vultr /usr/sbin/opensips[870498]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:42 vultr /usr/sbin/opensips[870506]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870506]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870506]: siplua: Lua state opened
Nov 04 14:50:42 vultr /usr/sbin/opensips[870505]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:42 vultr /usr/sbin/opensips[870504]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870504]: siplua: child_init
Nov 04 14:50:42 vultr /usr/sbin/opensips[870504]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870503]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870503]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870505]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870505]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870505]: WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 150000 us delay in execution
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870503]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870506]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870506]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870506]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870504]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870504]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870504]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: siplua: child_init
Nov 04 14:50:43 vultr systemd[1]: Started OpenSIPS is a very fast and flexible SIP (RFC3261) server.
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: siplua: child_init
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: siplua: Lua state opened
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: siplua: siplua file /etc/opensips/opensips.lua successfully reloaded
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: INFO:rtpengine:rtpe_test: rtp proxy <udp:localhost:2223> found, support for it enabled
Nov 04 14:50:43 vultr opensips[870484]: INFO:core:daemonize: pre-daemon process exiting with 0

Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:handle_sigs: child process 870496 exited by a signal 11
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:handle_sigs: core was generated
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:handle_sigs: terminating due to SIGCHLD
Nov 04 14:50:43 vultr /usr/sbin/opensips[870497]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870498]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870503]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870504]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870506]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870507]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870511]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870513]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870516]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870517]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 4(870501) [time_keeper] terminated, still waiting for 12 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 5(870502) [timer] terminated, still waiting for 11 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870505]: DIGEST-MD5 common mech free
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 14(870517) [Timer handler] terminated, still waiting for 10 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 13(870516) [SIP receiver hep_udp:127.0.0.1:9099] terminated, still waiting for 9 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 9(870506) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 8 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 6(870503) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 7 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 12(870513) [SIP receiver hep_udp:127.0.0.1:9099] terminated, still waiting for 6 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 10(870507) [SIP receiver hep_udp:127.0.0.1:9099] terminated, still waiting for 5 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 11(870511) [SIP receiver hep_udp:127.0.0.1:9099] terminated, still waiting for 4 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 7(870504) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 3 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 8(870505) [SIP receiver udp:127.0.0.1:5060] terminated, still waiting for 2 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 3(870498) [MI FIFO] terminated, still waiting for 1 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:shutdown_opensips: process 2(870497) [HTTPD 127.0.0.1:8880] terminated, still waiting for 0 more
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: INFO:core:cleanup: cleanup
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: siplua: destroy
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: siplua: destroy
Nov 04 14:50:43 vultr /usr/sbin/opensips[870486]: NOTICE:cachedb_redis:destroy: destroy module cachedb_redis ...
Nov 04 14:50:43 vultr systemd[1]: opensips.service: Main process exited, code=exited, status=139/n/a
Nov 04 14:50:43 vultr systemd[1]: opensips.service: Failed with result 'exit-code'.

**To Reproduce**
1. I see when I try to load lua module with rtpengine module, opensips fails to start. 
2. But if i disable either rtpengine or lua module, opensips starts just fine

**Additional context**
```
rtpengine --version
Version: 10.5.2.6-1~bpo11+1
```
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

Please, let me know if more information is required. 

Thanks for the great application.

**Comment by ryan-netizen** [comment]
keep-alive

**Comment by liviuchircu** [comment]
hey, @ryan-netizen!  If you still have the `core` file, please provide the path to the `opensips` binary to the `gdb` command (example below), otherwise the `bt full` will not display anything, as you can see:

```
gdb /usr/sbin/opensips core
```

**Comment by liviuchircu** [comment]
Are you using some kind of custom build or self-compiled set of `opensips` binary and/or `.so` modules?  If yes, please delete all binaries and do a full rebuild, after which the bug should go away.

**Comment by liviuchircu** [comment]
Oh, never mind, actually!  This looks like a bug in `rtpengine_notify_process()`, as it's scanning a non-NULL terminated string in search for the `:` port separator.  A fix will be available soon! :)
