### ISSUE TITLE
[CRASH] in next_branches intermittently 

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#2950]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e2fd673d9
main.c compiled on 04:01:29 Oct 29 2022 with gcc 4.8.5
```
**Crash Core Dump**

https://pastebin.com/cv8sEqj9
**Describe the traffic that generated the bug**

UDP sip getting 300 response and doing failover if final destination does not accept call
There is an async rest call in the call flow as well but we have no reason to suspect that is involved in the issue.
**To Reproduce**

1. Start opensips
2. start traffic
3. see large and small volumes of traffic for up to 10 days with no issue
4. suddenly - core dump always in next_branches
5. no log messages of running low or out of memory of any type.
**Relevant System Logs**

no logs, relevant or otherwise, generated on the thread that crashed immediately preceding the crash.
```
2022-11-07T16:41:26.942761+00:00  /usr/local/opensips/sbin/opensips[116153]: INFO:tm:t_forward_nonack: discarding fwd for a cancelled transaction
2022-11-07T16:41:26.943134+00:00  /usr/local/opensips/sbin/opensips[116153]: ERROR:tm:w_t_relay: t_forward_nonack failed
2022-11-07T16:41:59.190303+00:00  /usr/local/opensips/sbin/opensips[116153]: CRITICAL:core:sig_usr: segfault in process pid: 116153, id: 20
2022-11-07T16:42:06.304469+00:00  /usr/local/opensips/sbin/opensips[116114]: INFO:core:handle_sigs: child process 116153 exited by a signal 11
```
**OS/environment information**
 - Operating System:  Cent OS 7
 - OpenSIPS installation:  manual build
 - other relevant information:
We saw this (seemingly) same crash with opensips 2.4 but have so far been unable to reproduce it in a lab environment.
**Additional context**

**Comment by liviuchircu** [comment]
Hi, @rrevels-bw!  You seem to be using the `3.2.9` minor release package and not some other custom build, correct?  If so, could you `gzip` the corefile and send it to liviu@opensips.org?

**Comment by rrevels-bw** [comment]
We are indeed using the 3.2.9 minor release now.  : >
We have an automated process that blows away the core file after the
backtrace is generated but are working on setting it aside long enough to
grab one.  Will get it to you on the next one.  Thank you for your
attention!

**Comment by rrevels-bw** [comment]
And yeah, looks to be pretty much the same as 2446.

**Comment by liviuchircu** [comment]
Thank you for the patience and all your help in troubleshooting this rare "99% it works, but 1% it doesn't" type of unsafe SHM reading bug, @rrevels-bw!  The issue was identical to the one in #2446, as the backtraces from both codebases point to the same `search_next_avp()` function call, which was the object of the fix:

```
    return 2;
done:
    return (search_next_avp(avp, NULL)==NULL)?2:1;     <---------------------
error1:
    destroy_avp(avp);
```

Cheers!  I will take care of the backports, probably going to do it on `2.4` as well as an exception, since that's where you first ran into it!

**Comment by rrevels-bw** [comment]
Thank you so much!  Sorry it took so long to get enough data to you to troubleshoot this.
