### ISSUE TITLE
[CRASH] Segfault crash with rtp_relay and b2b module

### ISSUE THREAD

**Issue by devoxy1** [OpenSIPS/opensips#2952]
Hello Dev team!

I've been experiencing crash with segfault using rtp_relay module with b2b configurations.
I have simple setup with opensips and b2b using Refer scenario. I would like to use rtpengine to relay media through it. Based on my reading it can't be done with rtpengine module directly because replies like 183/200 are not handled correctly and IP is not changed. So i tried rtp_relay module as it should handle all replies based on description.

_Asterisk --> proxy --> Opensips with B2B -- > provider SBC_
   
```
route {
...
if (!has_totag()) {
                b2b_server_new("caller");
                b2b_client_new("callee", "$ru",,,,$avp(b2b_hdrs),$avp(b2b_hdr_bodies));

                # initialize B2B session
                b2b_init_request("refer", "a");
                exit;
        }
...
}

```
Without `rtp_relay_engage` line everything works fine. I make call, opensips receives it, create new leg and call is established.
However if i put `rtp_relay_engage("rtpengine",0)` like this

```
...
                b2b_client_new("callee", "$ru",,,,$avp(b2b_hdrs),$avp(b2b_hdr_bodies));
                rtp_relay_engage("rtpengine",0);
                # initialize B2B session
                b2b_init_request("refer", "a");
                exit;
...
}

```
opensips starts ok but once i make the call it crashes with segfault before creating second leg. This happens everytime, it can be easily reproduced.
I also tried several other versions as i found reports on similar issue (https://github.com/OpenSIPS/opensips/issues/2641). Version 3.2 doesn't crash, it changes IP in INVITE's SDP but doesn't replace IP in 183/200 replies. I'm not very familiar with rtp_relay module, may be i'm setting it up incorrectly.

**Version**
_version: opensips 3.3.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: ea206a4ad
main.c compiled on 16:48:56 Nov  9 2022 with gcc 9_

**Crash Core Dump**
I uploaded 2 files - one with opensips log in debug mode and the other one backtrace from gdb done based on guide under troubleshooting section. Please let me know if anything else is needed:
https://file.io/KfKTA0EzZ14f

**To Reproduce**
1. Start OpenSIPS with b2b and rtp_relay modules loaded and `rtp_relay_engage("rtpengine")` in the main route.
2. Make call from Asterisk or any endpoint top opensips via b2b_init_script
3. Check OpenSIPS crashed upon receiving invite and 

**Relevant System Logs**
Based on gdb log `__FUNCTION__ = "rtp_relay_b2b_tm_req"` causes crash.

**OS/environment information**
 - _Operating System:_ Ubuntu 20.04.5 LTS
 - _OpenSIPS installation:_ source tar.gz
 - _other relevant information:_ All IP address and numbers in logs are changed for security reasons.

Any help would be much appreciated.
Thank you!

**Comment by devoxy1** [comment]
up

**Comment by razvancrainea** [comment]
Unfortunately the core files are no longer available. Can you please re-share them?
Also, have you tried with the latest OpenSIPS version?

**Comment by devoxy1** [comment]
> Unfortunately the core files are no longer available. Can you please re-share them? Also, have you tried with the latest OpenSIPS version?

Hello razvancrainea,

I uploaded them again, here you go https://file.io/Nkv9g3dyoZva
I tried with all latest versions on the moment of creating this post, including development  3.4.
If there were any commits for past months i haven't tried them. Should i do it?

Thanks

**Comment by razvancrainea** [comment]
@devoxy1 it appears you are loading both dialog and b2b modules, correct?
I've just pushed a possible fix for your setup - can you please re-test and let me know how it goes?

**Comment by devoxy1** [comment]
@razvancrainea I did a test - all looks good, no crash on startup and i can see IPs are changed in SDP on both legs, including 200 OK, voice is going through rtpengine server. 
Thank you very much! :)

**Comment by razvancrainea** [comment]
Awesome, thanks for confirming the fix!
