### ISSUE TITLE
[BUG] Can't get TLS SNI working in OpenSIPS 3.3

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#2963]
**OpenSIPS version you are running**
```
version: opensips 3.3.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7cde17d
main.c compiled on  with gcc 4.9.2
```

**Describe the bug**

**To Reproduce**
It works with next section:
```
modparam("tls_mgm", "server_domain", "default")
modparam("tls_mgm", "certificate", "[default]cert1.pem")
modparam("tls_mgm", "private_key", "[default]cert1.key.pem")
modparam("tls_mgm", "ca_list", "[default]ca1.pem")
modparam("tls_mgm", "match_ip_address", "[default]8.8.8.8:5061")

modparam("tls_mgm", "verify_cert", "[default]0")
modparam("tls_mgm", "require_cert", "[default]0")
modparam("tls_mgm", "ciphers_list", "[default]ALL:!NULL:!LOW:!RC4:-SHA:!3DES:AES256-SHA")
modparam("tls_mgm", "tls_method", "[default]TLSv1_2")
```

If add an additional section:
```
modparam("tls_mgm", "server_domain", "mobile")
modparam("tls_mgm", "certificate", "[mobile]cert2.pem")
modparam("tls_mgm", "private_key", "[mobile]cert2.key.pem")
modparam("tls_mgm", "ca_list", "[mobile]ca2.pem")
modparam("tls_mgm", "match_ip_address", "[mobile]8.8.8.8:5061")
modparam("tls_mgm", "match_sip_domain", "[mobile]test.com")

modparam("tls_mgm", "verify_cert", "[mobile]0")
modparam("tls_mgm", "require_cert", "[mobile]0")

modparam("tls_mgm", "ciphers_list", "[mobile]ALL:!NULL:!LOW:!RC4:-SHA:!3DES:AES256-SHA")
modparam("tls_mgm", "tls_method", "[mobile]TLSv1_2")
```

Then test.com certificate works properly, but default one stops to work with WolfSSL error in log.
Order of sections in configuration file makes no difference.

**Expected behavior**
OpenSIPS provides cert2 if gets connection for test.com (using SNI) and provides default certificate (cert1) in any other case.

**Relevant System Logs**
```
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23185]: DBG:core:handle_new_connect: new connection: 0x7f13b7324f50 1077 flags: 001c
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23185]: DBG:core:send2worker: to tcp worker 0 (0/131) load 0, 0x7f13b7324f50/1077 rw 1
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:proto_tls:proto_tls_conn_init: looking up TLS server domain [8.8.8.8:5061]
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:tls_mgm:tls_find_server_domain: found TLS server domain: mobile
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:tls_wolfssl:_wolfssl_tls_conn_init: Creating a whole new ssl connection
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:tls_wolfssl:_wolfssl_tls_conn_init: Setting in ACCEPT mode (server)
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:core:handle_io: We have received conn 0x7f13b7324f50 with rw 1 on fd 1079
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:core:io_watch_add: [TCP_worker] io_watch_add op (1079 on 933) (0x99d4c0, 1079, 19, 0x7f13b7324f50,1), fd_no=5/10485
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:proto_tls:tls_read_req: Using the global ( per process ) buff
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:tls_wolfssl:_wolfssl_tls_update_fd: New fd is 1079
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: DBG:tls_mgm:tls_sni_cb: Switched to TLS server domain: default due to SNI
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: ERROR:tls_wolfssl:_wolfssl_tls_accept: New TLS connection from 4.4.4.4:59240 failed to accept
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: ERROR:tls_wolfssl:_wolfssl_tls_accept: TLS accept error: -501, can't match cipher suite
Dec  6 00:20:28 ereg02 /usr/sbin/opensips[23152]: ERROR:proto_tls:tls_read_req: failed to do pre-tls handshake!
```

**OS/environment information**
 - Operating System: Debian 8
 - OpenSIPS installation: from deb package

**Comment by nikbyte** [comment]
Still actual.

**Comment by nikbyte** [comment]
still actual.

**Comment by rvlad-patrascu** [comment]
Hi @nikbyte ,

A few questions here as I cannot seem to reproduce the issue myself:
1) Does this work if you change the library to openssl?
2) Is any other servername actually provided in the ClientHello message when you try to connect to the default domain? Can you maybe experiment with the `openssl s_client` tool and use the `-noservername` option?
3) Can you try to skip `ciphers_list` modparam for the default domain?

**Comment by nikbyte** [comment]
Hi @rvlad-patrascu .

Thanks, I'll reproduce it again and come back with an additional info.

**Comment by nikbyte** [comment]
@rvlad-patrascu 

I installed latest 3.3 from official repo (3.3.3~20230114~1dd733fec-1).

Created certificates:
```
openssl req -x509 -sha256 -days 1825 -newkey rsa:2048 -keyout ca1.key.pem -out ca1.pem
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -CA ca1.pem -CAkey ca1.key.pem -keyout cert1.key.pem -out cert1.pem

openssl req -x509 -sha256 -days 1825 -newkey rsa:2048 -keyout ca2.key.pem -out ca2.pem
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -CA ca2.pem -CAkey ca2.key.pem -keyout cert2.key.pem -out cert2.pem
```

First cert CN is cert1.com, 2nd cert CN is cert2.com

Using openssl I made 4 tests for each library:

For cert1.com:
```openssl s_client -showcerts -servername cert1.com -connect 8.8.8.8:5061```

For cert2.com:
```openssl s_client -showcerts -servername cert2.com -connect 8.8.8.8:5061```

For unknown.com:
```openssl s_client -showcerts -servername unknown.com -connect 8.8.8.8:5061```

Without cert (mac os openssl has no separate option, but checking openssl debug I can confirm it sends no domain name with these parameters):
```openssl s_client -showcerts -connect 8.8.8.8:5061```

Results with both libraries and only one domain in configuration:
Request cert1.com, answer: cert1.com
Request cert2.com, answer: cert1.com
Request unknown.com, answer: cert1.com
Request no domain, answer: cert1.com

Results with openssl library and both domains in configuration:
Request cert1.com, answer: cert1.com
Request cert2.com, answer: cert2.com
Request unknown.com, answer: cert1.com
Request no domain, answer: cert1.com

Results with wolfssl library and both domains in configuration:
Request cert1.com, error
Request cert2.com, answer: cert2.com
Request unknown.com, error
Request no domain, error

Commenting out of ciphers doesn't change behavior.

**Comment by nikbyte** [comment]
Issue fixed with https://github.com/OpenSIPS/opensips/commit/8a133125929575d26a935bad8eb5e27074c3a3d7. Thanks.
