### ISSUE TITLE
Auto detect new tls certificate or support a MI function to reload the certificate / private key config

### ISSUE THREAD

**Issue by truong-hua** [OpenSIPS/opensips#2969]
**Is your feature request related to a problem? Please describe.**
A SSL cert will be expired in may be 3 months or a year. Currently, if we use non-db mode tls_mgm, there is no way for us to reload or update new cert/private key without restarting the OpenSIPS

**Describe the solution you'd like**
MI function `tls_reload` will compare and detect any change in certification and private key and ca and load the new version if updated.

**Implementation**
  - Component: tls_mgm

**Comment by bogdan-iancu** [comment]
@truong-hua , for such scenarios (certs being update), the db mode should be used (which supports reload).

**Comment by truong-hua** [comment]
thank @bogdan-iancu , let's say that if we do not update anything in the database but just the cert/key files, will the reload also really reload the cert/key files (as there is nothing changed in the database).

I will try it. Btw, having reload for file mode I think is still reasonable as some time people still would like something that is easier to use in stead of deploying a database for just this purpose.

**Comment by vasilevalex** [comment]
> thank @bogdan-iancu , let's say that if we do not update anything in the database but just the cert/key files, will the reload also really reload the cert/key files (as there is nothing changed in the database).
There are no files. cert and key are raw data in DB. And mi tls_reload of course read them from DB and updates.

> I will try it. Btw, having reload for file mode I think is still reasonable as some time people still would like something that is easier to use in stead of deploying a database for just this purpose.
Use SQLite, it's not hard to deploy

**Comment by truong-hua** [comment]
Another thing worth talking is that other cert provisioning service like certbot/letsencrypt (and many others) will work with file mode, cert auto renew will work too easily without extra works.

**Comment by vasilevalex** [comment]
> Another thing worth talking is that other cert provisioning service like certbot/letsencrypt (and many others) will work with file mode, cert auto renew will work too easily without extra works.

Try certbot with `--deploy-hook`
