### ISSUE TITLE
[BUG] Privacy: user;id with semicolon ";" throws an error by opensips

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#2973]
Hi,

it seams like opensips does not like incoming Privacy: user;id with semicolon ";" throwing following error:

Dec 19 06:16:08 app /usr/sbin/opensips[31113]: ERROR:core:parse_list_hdr: parse error in list hdr body [user;id] around position 4
Dec 19 06:16:08 app /usr/sbin/opensips[31113]: ERROR:sipmsgops:list_hdr_has_val: failed to parse body <user;id> as CSV for hdr <Privacy>

    INVITE sip:+987654321;npid=0@test.com;user=phone SIP/2.0\r\n
    Via: SIP/2.0/TCP 1.2.3.4:5060;branch=z9hG4bK2a1ca4e9b1508cd8324e08b5b7665b24.c905de7d\r\n
    Max-Forwards: 63\r\n
    To: <sip:+987654321@test.com;user=phone>\r\n
    From: <sip:+123456789@test.com;user=phone>;tag=207d2237\r\n
    Call-ID: d69b08980a6c0def@1.2.3.4\r\n
    Contact: <sip:EDGE004@2.3.4.5:5060;transport=tcp>\r\n
    Supported: histinfo\r\n
    CSeq: 38285038 INVITE\r\n
    Allow: ACK, BYE, CANCEL, INFO, INVITE, OPTIONS, REGISTER, UPDATE\r\n
    P-Asserted-Identity: <sip:+123456789;npid=0@test.com;user=phone;ixtp=182>\r\n
    P-Early-Media: supported\r\n
    Privacy: user;id\r\n

version: opensips 3.1.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

Privacy-hdr  =  "Privacy" HCOLON priv-value *(";" priv-value) 
   priv-value   =   "header" / "session" / "user" / "none" / "critical" 
                    / token

**Comment by razvancrainea** [comment]
According to the documentation, the  [`list_hdr_has_option` function](https://opensips.org/docs/modules/3.3.x/sipmsgops.html#func_list_hdr_has_option) parses CSV (comma separated values) lists, thus the separator of the fields has to be `,` to use this function, not `;`. Thus, this is not a bug - if you want to parse semicolon separated values, you can use other mechanisms, such as the [`param.exist` transformation](https://www.opensips.org/Documentation/Script-Tran-3-3#param.exist).

**Comment by xaled1** [comment]
Got it, thanks!
