### ISSUE TITLE
[BUG] CRASH - CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f12d2b42a58), first free: (null): (null)(0) - aborting!

### ISSUE THREAD

**Issue by palmtown** [OpenSIPS/opensips#2979]
**OpenSIPS version you are running**

```
version: opensips 3.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 11
```

**Describe the bug**

**To Reproduce**
1. Start OpenSIPS
2. Make an inbound call to a phone registered to OpenSIPS with tls_openssl loaded.

**Expected behavior**

**Relevant System Logs**

Jan  1 19:46:01 /usr/sbin/opensips[7040]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f01e0416e40), first free: 2.16.840.1.101.3.4.1.21: AES-192-ECB(17179869184) - aborting!
Jan  1 19:46:06 systemd[1]: opensips.service: Main process exited, code=exited, status=134/n/a
Jan  1 19:46:06systemd[1]: opensips.service: Failed with result 'exit-code'.

**OS/environment information**
 - Operating System: Ubuntu 22.04.1 LTS
 - OpenSIPS installation: debx
 - other relevant information:

**Additional context**
Also, notice that OpenSIPs will hang starting, or restarting.  Gets stuck with status activating or deactivating.

**Comment by palmtown** [comment]
After further testing, it appears to be happening with the tls_openssl module.  If I make a call to a registered phone, OpenSIPS crash.  The error log is below:

Jan  1 22:57:55 /usr/sbin/opensips[11349]: CRITICAL:core:fm_free: freeing already freed shm pointer (0x7f5ca9a305c0), first free: (null): (null)(0) - aborting!
Jan  1 22:57:55 /usr/sbin/opensips[11342]: DBG:core:handle_sigs: OpenSIPS exit status = 134
Jan  1 22:57:55 /usr/sbin/opensips[11342]: INFO:core:handle_sigs: child process 11349 exited by a signal 6
Jan  1 22:57:55  /usr/sbin/opensips[11342]: INFO:core:handle_sigs: core was generated
Jan  1 22:57:55 /usr/sbin/opensips[11342]: INFO:core:handle_sigs: terminating due to SIGCHLD

**Comment by palmtown** [comment]
I verified the issue doesn't occur in 3.1.13-1, however, present in 3.3.3.

**Comment by liviuchircu** [comment]
Hi, @palmtown!  I noticed your last message, which matched an exact crash I was looking into (_"freeing already freed shm pointer ... first free: (null): (null)(0) - aborting!"_), so I assigned myself here.  Now that I fully read the context, your abort happens with TLS + 1 single call, while mine is related to mid-dialog requests and some strange Contact updating race condition...

Anyway, could you share a small _opensips.cfg_ snippet that reproduces it?  Can you reliably trigger it on just 1 call?

**Comment by palmtown** [comment]
Hello @liviuchircu,

First, thanks for adding your information and looking into this.  Secondly, I'd be more than happy to share.  I've pasted the TLS configuration I am using, however, can share other parts that you may need to troubleshoot.  In terms of reliably triggering, I can trigger it within 10 minutes or less in 3.3.3.  

Also, what I've noticed is that when I restart OpenSIPS, sometimes it will fail to start and give a similar error.  Therefore, I've seen it in different scenarios.  Lastly, I'm also open to jumping on a meeting/desktop sharing session and work together to resolve.

Here's the TLS config:

loadmodule "tls_openssl.so"
loadmodule "tls_mgm.so"

modparam("tls_mgm", "client_domain", "default")
modparam("tls_mgm", "certificate", "[default]/etc/opensips/tls/cert.pem")
modparam("tls_mgm", "private_key", "[default]/etc/opensips/tls/key.pem")
modparam("tls_mgm", "ca_list", "[default]/etc/opensips/tls/ca.pem")
modparam("tls_mgm", "ca_dir", "[default]/etc/ssl/certs")
modparam("tls_mgm", "require_cert", "[default]1")
modparam("tls_mgm", "verify_cert", "[default]1")
modparam("tls_mgm", "tls_method", "[default]TLSv1-")
modparam("tls_mgm", "match_ip_address", "[default]*")
modparam("tls_mgm", "match_sip_domain", "[default]*")

modparam("tls_mgm", "server_domain", "default")
modparam("tls_mgm", "certificate", "[default]/etc/opensips/tls/cert.pem")
modparam("tls_mgm", "private_key", "[default]/etc/opensips/tls/key.pem")
modparam("tls_mgm", "ca_list", "[default]/etc/opensips/tls/ca.pem")
modparam("tls_mgm", "ca_dir", "[default]/etc/ssl/certs")
modparam("tls_mgm", "require_cert", "[default]1")
modparam("tls_mgm", "verify_cert", "[default]1")
modparam("tls_mgm", "tls_method", "[default]TLSv1-")
modparam("tls_mgm", "match_ip_address", "[default]*")
modparam("tls_mgm", "match_sip_domain", "[default]*")

loadmodule "proto_udp.so"
loadmodule "proto_tcp.so"
loadmodule "proto_tls.so"
loadmodule "proto_wss.so"
loadmodule "proto_ws.so"

modparam("proto_tls", "tls_max_msg_chunks", 8)
modparam("proto_tls", "tls_send_timeout", 400)
modparam("proto_tls", "tls_handshake_timeout", 1000)
modparam("proto_tls", "tls_async", 0)  # I've tried setting this to 0 based on my research, however, same issue.

**Comment by palmtown** [comment]
Also, note that I tried switching to tls_wolfssl, and I did not experience the crashing or prolong restarts, however, my phone would not register.  During TLS negociation, my phone gives an error **Unknown CA**.  I use the exact same confirmation, simply commenting out tls_opensips and loading tls_wolfssl, but with tls_wolfssl I can't register.  I tried install the CA on the phone, still generates the same error.

**Comment by palmtown** [comment]
Hello @liviuchircu ,

I just got it OpenSIPS 3.3.3 working with tls_wolfss.  The fix was to put the CA cert inside of the cert file.  So far, no crash and restarts are normal.  I'll have to continue testing to ensure this works for my scenario, however, early indications show some issue with tls_openssl.
