### ISSUE TITLE
[BUG]  The usrloc module has not exported 3 Statistics

### ISSUE THREAD

**Issue by Dup4** [OpenSIPS/opensips#2984]
**OpenSIPS version you are running**

- master

**Describe the bug**

https://opensips.org/docs/modules/3.3.x/usrloc.html#exported_statistics

https://github.com/OpenSIPS/opensips/blob/211a63c9b2ccac346dfc57bca2ede71d286e9989/modules/usrloc/ul_mod.c#L249-L252

I can see from the documentation that the usrloc module exports a total of 4 pieces of statistics.

- `users`
- `contacts`
- `expires`
- `registered_users`

but I can see from the code that only one statistics is exported, `registered_users`.

So I'd like to ask if the documentation is not up to date or if the code is not implemented.

**Comment by razvancrainea** [comment]
According to the documentation, the first 3 statistics are displayed per domains. Therefore, the name of the statistic is prefixed by it's domain (i.e. `location`). You can find below an example of output:

```
$ opensips-cli -x mi get_statistics usrloc:
{
    "usrloc:registered_users": 0,
    "usrloc:location-users": 0,
    "usrloc:location-contacts": 0,
    "usrloc:location-expires": 0
}
```
