### ISSUE TITLE
[BUG] Stateless trace and B2B trace are using conflict message flag `FL_USE_SIPTRACE`

### ISSUE THREAD

**Issue by truong-hua** [OpenSIPS/opensips#2992]
**OpenSIPS version you are running**

```
version: opensips 3.2.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**
The stateless reply trace is using flag `FL_USE_SIPTRACE` here https://github.com/OpenSIPS/opensips/blame/master/modules/tracer/tracer.c#L1049 and the B2B trace is also use that flag https://github.com/OpenSIPS/opensips/blame/master/modules/tracer/tracer.c#L1040. So when the `FL_USE_SIPTRACE` flag is toggle by the stateless reply trace (actually it's always on), the B2B trace is activated also.

In my script, I only would like to trace at transaction level, so I used `trace("traceid", "t");` and in the system log, there is always B2B trace related logs and currently it seem like B2B trace is always activated unless I remove the b2b module from load.

It causes more bug as scripts want to trace at transaction level, so it clean up instances when the transaction was done and later on b2b transaction would like to access the instances memory again.

I'm guessing a potential risk that if we use `trace("traceid", "b")` (B2B trace) in the script in the environment that b2b module is loaded but never using, is there a memory leak scenario because no b2b `f_freep` (`free_trace_info_b2b` in 3.3.0) will be called to clean up? This is another question and I haven't verify it yet.

**To Reproduce**
* Load b2b module
* Call `trace("traceid", "t");
* Check the log and b2b trace is also activated due to conflict of flag `FL_USE_SIPTRACE`

**Expected behavior**
Allow to trace at transaction level only even b2b module is loaded.

**Workaround solution**
Never activate trace level less than b2b if b2b module is loaded.

**Comment by rsmck** [comment]
This appears to still be an issue with the current master, not limited to 3.2;

```version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a90ef109a
main.c compiled on 14:06:17 Jan 19 2023 with gcc 10```

I didn't realise at first it was related to transactional tracing as I was seeing it with `trace("tid"`) however if I limit the scope of trace to b2b `trace("tid","b")` then it prevents the crash so thanks, that's an acceptable workaround for me for now but it would be useful to have transaction level tracing alongside b2b tracing.

**Comment by truong-hua** [comment]
Yes, it affect all current versions until the PR #2994 be approved
