### ISSUE TITLE
[FEATURE] Dialog deletion delay

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#2996]
Hello Everyone,
This is feature request to introduce  dialog deletion delay variable.
This variable  will allow delay deletion of dialog by 5 sec as example.

Use case 

This check bellow is sort hit and miss, because  BYE or CANCEL is delayed by few second, but dialog is removed and call still valid.

Code example 

```
                # INFO CSTA without transaction close the call right a way 
                if(is_method("BYE|NOTIFY")) {
                        if($DLG_status==null || $DLG_status=="5") {
                                xlog("[IN_DIALOG] [$rm] [$cfg_line] No DID $DLG_did match closing call [$rs] Call-ID $ci Source IP $si\n");
                                sl_send_reply(481,"Call/Transaction Does Exist");
                                exit;
                        }
                }
```

Screenshot

<img width="1319" alt="Screenshot 2023-01-19 at 9 13 18 AM" src="https://user-images.githubusercontent.com/59034879/213464823-631ef2cb-2cd0-48c3-a11b-47a71417cb47.png">

**Comment by bogdan-iancu** [comment]
Done via a2fefe4db14fbadd4e068160dc63a3b5751ade53
