### ISSUE TITLE
[BUG] b2b module sends ACK to 100 Trying from B Leg

### ISSUE THREAD

**Issue by rsmck** [OpenSIPS/opensips#2998]
I believe this may be a bug, it's certainly _unexpected_ behaviour as I wouldn't typically expect an ACK in response to a 100 (or any 1xx code)

**OpenSIPS version you are running**
```
version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a90ef109a
main.c compiled on 14:06:17 Jan 19 2023 with gcc 10
```

**Describe the bug**
When bridging a call using b2b module, when a 100 Trying response is received from the B leg, OpenSIPS responds with an `ACK` (which would not be expected for a provisional reply)

**To Reproduce**
Relevant route block contains;
```
b2b_server_new("b2bs");
b2b_client_new("b2bc", $var(b2b_dest), "sip:$avp(b2b_dest_u)");
b2b_init_request("b2b_test", "", "b2b_test_request", "b2b_test_reply");
```
When a call is made and a 100 Trying is received, OpenSIPS ACKs this message.

**Expected behavior**

Do not expect an ACK to a 100 Trying (or provisional response) 

**OS/environment information**
 - Operating System: Debian 11 
 - OpenSIPS installation: source (git)

**Comment by rvlad-patrascu** [comment]
Hi @rsmck 

Can you post a pcap and full debug logs for such a call?
