### ISSUE TITLE
NOTIFications can only be done on existing TCP connections

### ISSUE THREAD

**Issue by dsandras** [OpenSIPS/opensips#30]
If the TCP connection is down, or if the NOTIFY comes from a redundant server, then it will not work. The phone will not be notified of this, and its subscriptions will have to expire leaving it in an unconsistant state for a while. This looks dramatic to us.

See:
https://github.com/OpenSIPS/opensips/pull/17

Reporting it here so that everyone knows there is a problem. I suppose that the new async TCP code will allow reverting that commit.

**Comment by bogdan-iancu** [comment]
This will be addressed starting 3.1 by the upcoming "tcpconn_mgm" module
