### ISSUE TITLE
[BUG] Defining __USE_MISC has undefined behaviour

### ISSUE THREAD

**Issue by jwakely** [OpenSIPS/opensips#3005]
This is a bug:

https://github.com/OpenSIPS/opensips/blob/d919285009aae706539b9874ed551fe4ceecd9c3/modules/lua/sipdatetime.c#L20-L24

The `__USE_MISC` macro is for glibc's internal use, not for you to define. If you want `timegm` then you should define `_DEFAULT_SOURCE` (since glibc 2.19) or `_BSD_SOURCE` (for glibc 2.19 and earlier) before including any glibc headers. Do not include some headers then mess with glibc's internal macros and expect anything after that to be in a consistent state.

**Comment by razvancrainea** [comment]
@jwakely thanks for reporting it, will soon push a fix for this!
