### ISSUE TITLE
[BUG] [v3.3] OpenSIPS cannot compile if wolfssl module is enabled

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#3007]
**OpenSIPS version you are running**
Latest 3.3

**Describe the bug**
OpenSIPS compilation with wolfssl mdules enabled fails

`The command '/bin/sh -c make clean && TLS=1 FASTER=1 make -j2 prefix=/usr/local/opensips all include_modules="uuid tls_wolfssl tls_openssl mi_http cachedb_cassandra rabbitmq_consumer event_rabbitmq rabbitmq b2b_logic cgrates compression db_mysql dialplan regex json httpd proto_tls proto_wss presence presence_dialoginfo presence_mwi presence_xml rest_client tls_mgm xcap xcap_client"`

**To Reproduce**
enable wolfssl module and compile

**Relevant System Logs**
log summary:

```
----------------------------------------------------------------------
wolfssl.c: In function '_wolfssl_is_peer_verified':
wolfssl.c:223:18: warning: implicit declaration of function 'wolfSSL_get_verify_mode'; did you mean 'wolfSSL_CTX_get_verify_mode'? [-Wimplicit-function-declaration]
  223 |    verify_mode = wolfSSL_get_verify_mode(_WOLFSSL_READ_SSL(ssl));
      |                  ^~~~~~~~~~~~~~~~~~~~~~~
      |                  wolfSSL_CTX_get_verify_mode
wolfssl_config.c: In function 'load_ca_dir':
wolfssl_config.c:438:32: error: 'WOLFSSL_LOAD_FLAG_IGNORE_BAD_PATH_ERR' undeclared (first use in this function); did you mean 'WOLFSSL_LOAD_FLAG_IGNORE_ERR'?
  438 |   WOLFSSL_LOAD_FLAG_IGNORE_ERR|WOLFSSL_LOAD_FLAG_IGNORE_BAD_PATH_ERR)) !=
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                WOLFSSL_LOAD_FLAG_IGNORE_ERR
wolfssl_config.c:438:32: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [../../Makefile.rules:29: wolfssl_config.o] Error 1
ERROR: Building tls_wolfssl module failed!
make[1]: *** [Makefile:187: modules/tls_wolfssl] Error 2
make[1]: *** Waiting for unfinished jobs....
Building presence_xml module succeeded
make[1]: Leaving directory '/usr/src/opensips'
----------------------------------------------------------------------
```

The problem is with this commit : https://github.com/OpenSIPS/opensips/commit/2db919d1c11904caf4d926ae1be26bd052a5deec
before this OpenSIPS compiles successfully 

Full logs --> [here](https://pastebin.com/Eimeeap4)

**OS/environment information**
 - Operating System: debian:bullseye
 - OpenSIPS installation: 3.3 latest git code

**Comment by rvlad-patrascu** [comment]
Hi @vtzan 

We've recently updated the wolfssl lbirary to a newer version so make sure to do a `git submodule update` and `make clean` before rebuilding.

**Comment by vtzan** [comment]
Dear @rvlad-patrascu,

Thank you for your reply. 

I am using 

`git clone --recursive https://github.com/OpenSIPS/opensips.git
`

inside docker container while compiling opensips and have double checked that this commit : https://github.com/OpenSIPS/opensips/commit/2db919d1c11904caf4d926ae1be26bd052a5deec
breaks the compilation. Before that its working fine.

Thank you in advance for your time on this case.

Best Regards
Vasilios Tzanoudakis

**Comment by rvlad-patrascu** [comment]
Hi @vtzan ,

This seems strange since the only way that commit could break compilation is if you were still using the older wolfssl version.

Does running the following in the opensips source dir return anything?
`grep -nrH "WOLFSSL_LOAD_FLAG_IGNORE_BAD_PATH_ERR" ./modules/tls_wolfssl/lib/include/`

**Comment by vtzan** [comment]
Dear @rvlad-patrascu,

Thank you for your reply. 

I searched a little deeper and here is what I found. 
As you already know latest wolfssl version with all security fixes is 5.5.4.
According to https://tracker.debian.org/pkg/wolfssl 5.5.4 version for Debian is only available on testing / unstable so to be able to compile successfully I had to switch to debian:bookworm. (unstable) 

So if someone wants to compile manually on a debian:stable could you please share if there are
extra configure options --> ./configure --XXX --XXXX for wolfssl library just to be sure that there would be no surprises later while running OpenSIPS?

thank you in advance

Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
compilation if working fine using debian wolfssl package from backports.

**Comment by rvlad-patrascu** [comment]
Hi @vtzan ,

Just want to mention that installing wolfssl from packages is not the intended approach with the tls_wolfssl module, as the wolfssl library code is included in the opensips tree. This should prevent issues like this one with unavailable/incompatible wolfssl packages etc.

**Comment by vtzan** [comment]
Dear @rvlad-patrascu,

Yes indeed you are right. I will use lib from the opensips source tree.

Thanks for reminding me that.

Best regards 
Vasilios Tzanoudakis
