### ISSUE TITLE
[CRASH] OpenSIPS v3.3

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#3014]
**OpenSIPS version you are running**
```
version: opensips 3.3.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 620b278ad
main.c compiled on 22:57:24 Feb 13 2023 with gcc 12
```

**Crash Core Dump**
https://pastebin.com/rd7k4He4

**Describe the traffic that generated the bug**

**To Reproduce**
Sorry but the only thing that I can say here is that I was playing with push notifications
https://opensips.org/docs/modules/3.3.x/event_routing.html#idp3124912

**Relevant System Logs**

**OS/environment information**
 - Operating System: Debian:bookworm
 - OpenSIPS installation: git

Thank you in advance for your time.
Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

I just got another CRASH with latest opensips 3.3 code --> https://pastebin.com/rS86F9WU.
The error now is 

`error: Cannot access memory at address
`

Could you please take a look? I think this is something to do with push notification as this the only thing I have added and testing the last few days.

thank you in advance for your support.
Best Regards

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Another crash log : https://pastebin.com/RnDxc58R

Thanks in advance
Vasilios Tzanoudakis

**Comment by digipigeon** [comment]
Hey @vtzan 

We are experiencing similar symptoms with 3.2.11 and 3.2 nightly. (3.2.10 is stable)

Soon as this issue happens apport balloons in memory so just investigate further to rule out that causing memory exhaustion and see if there is an underlying problem.

BTW: Vasilios, pastebin link is not available.

Regards Jonathan
