### ISSUE TITLE
[BUG] rtpproxy n failes for reinvites

### ISSUE THREAD

**Issue by medeanwz** [OpenSIPS/opensips#3017]
**OpenSIPS version you are running**

```
version: opensips 3.1.13 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a1c4d0c43
main.c compiled on 19:36:53 Feb  6 2023 with gcc 8

```

**Describe the bug**

rtpproxy_offer("nfroc") command throws an error as soon as "n" flag is added. error only happens for reinvites (INVITE with totag). Error message says: ERROR:rtpproxy:force_rtp_proxy_body: Failed to get dialog
If I remove n flag, the error is gone.

**To Reproduce**

1. Start rtpproxy and opensips
2. Configure rtpproxy_offer/answer with "nfroc" flags
3. While call is connected, send a reinvite
4. Notice error log

**Expected behavior**

No errors is exptected, and also call should be terminated when there is a ping timeout

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:
OS: CentOS 8.5

**Additional context**

**Comment by sobomax** [comment]
"ERROR:rtpproxy:force_rtp_proxy_body: Failed to get dialog" do you have dialog module loaded? It is mandatory to use this feature.

**Comment by medeanwz** [comment]
Yes, indeed. dialog module is loaded, and working. Also I don't get this error for initial invites (only for reinvite)/

**Comment by razvancrainea** [comment]
@medeanwz are you calling `rtpproxy_offer` after `loose_route`? are you sure that the dialog was indeed matched?

**Comment by medeanwz** [comment]
No, I have not done that. It wasn't in the documents :) I will do a match_dialog before rtpproxy_offer to see if it will fix the problem, and report back.

**Comment by medeanwz** [comment]
This below seems to have fixed the problem. My understanding is that calling match_dialog matches the dialog and that makes n flag work correctly when looking for dialog.

                if (has_totag()) {
                    if(!match_dialog()) xlog("L_WARN", "$ci|route|dialog not matched\n");
                }
                    if(!rtpproxy_offer("nfrocie")) xlog("L_WARN", "$ci|route|rtpproxy_offer failed: $mb\n");
