### ISSUE TITLE
[BUG] memory leak in rad.c/rad_create_message

### ISSUE THREAD

**Issue by medeanwz** [OpenSIPS/opensips#3019]
**OpenSIPS version you are running**

```
version: opensips 3.1.13 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a1c4d0c43
main.c compiled on 19:36:53 Feb  6 2023 with gcc 8
```

**Describe the bug**

opensips-cli -x mi mem_pkg_dump PID shows highest memory usage in modules/aaa_radius/rad.c rad_create_message:
   message = (aaa_message*) pkg_malloc (sizeof(aaa_message));

This seems to be caused by "modules/acc/acc.c", in acc_aaa_request I see both proto.create_aaa_message and further down proto.destroy_aaa_message (where one allocates and other frees), while in acc_aaa_cdrs function I only see proto.create_aaa_message and no destroy...

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by medeanwz** [comment]
Since I didn't hear back, I went ahead and fixed the bug. It is interesting that this has been from the very first version (i checked as far back as I could).
acc.c line 1048 we need to destroy the radius message:

error:
        if (locked)
                accX_unlock(&ctx->lock);
+        proto.destroy_aaa_message(conn, send);

Feel free to add this fix to the next versions :)

**Comment by bogdan-iancu** [comment]
@medeanwz , can you provide a patch file with your fix please?

**Comment by medeanwz** [comment]
[patch.txt](https://github.com/OpenSIPS/opensips/files/11271359/patch.txt)

Uploaded and I can confirm that this fixed the memory leak issue.

**Comment by bogdan-iancu** [comment]
thank you @medeanwz
