### ISSUE TITLE
[CRASH] OpenSIPS Crash - Cannot access memory at address

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#3024]
The OpenSIPs crashes on the 3.2.11 stable version, as soon as the server starts to receive traffic opensips crashes with out of memory error. 
We can reproduce this issue on demand, I have attached the crash files including the relevant syslog files.

**OpenSIPS version you are running**

```
version: opensips 3.2.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 9

```

**Crash Core Dump**

Please find the memory dump file [here](https://drive.google.com/file/d/14XsbmRlLXigdWwVNgc96kdn2wIPJ9Wut/view?usp=sharing)

**Describe the traffic that generated the bug**

**To Reproduce**

1. Start OpenSIPS
2. Start traffic
3. Check OpenSIPS crashed

**Relevant System Logs**
Logs file from [here ](https://drive.google.com/file/d/1dKCf069SR1WaDJPcCye0__vllYIRU2PA/view?usp=share_link)

**OS/environment information**
 - Operating System: Ubuntu 20.04.5 
 - OpenSIPS installation: git 

Please let us know if you need any more details. thanks

Regards
Rizwan

**Comment by bogdan-iancu** [comment]
Could you try the latest 3.2.12 (released last week) to see if you still have this problem ?

**Comment by syedrizwansrs** [comment]
@bogdan-iancu I have just finished testing this, and I can confirm we don't experience this problem anymore on the latest 3.2.12 release. thank you
