### ISSUE TITLE
[BUG]  load balance module generating log errors - get_dst_load: bug - cannot find request resource in dst and unable to calculate free resources

### ISSUE THREAD

**Issue by recourse** [OpenSIPS/opensips#3026]
**OpenSIPS version you are running**

```
version: opensips 3.2.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10

```

**Describe the bug**

Opensips starts to generate the following log entries as load balancing resources are used to their configured resource limits. 
CRITICAL:load_balancer:get_dst_load: bug - cannot find request resource in dst
WARNING:load_balancer:lb_route: initial call of LB - skipping destination 1003 <sip:10.201.2.10:5060> - unable to calculate free resources
repeated many thousands of times.   The generation of these log messages seems odd as, is this really a bug as the log message states?    

**To Reproduce**

This issue appears on all our production proxies once the customers fill up their load balance resources. 

**Expected behavior**

Not generate these log messages either at all or at a different syslog level

**OS/environment information**
 - Operating System: Debian 11.5 
 - OpenSIPS installation:  apt.opensips.org 
 - other relevant information:

**Comment by bogdan-iancu** [comment]
@recourse , that log points to a bug indeed - during the LB process a destination was selected without meeting the required resources.

What triggers this issue? a reload? a failover in LB? do you have any hint?

**Comment by recourse** [comment]
Hi Bogdan,

I'm not sure why this is firing off.   At first I thought it was due to reaching the resource limits as configured for each load balance destination but that isn't the case.   Tho it does appear that it only happens when the overall proxy is under a higher load.


This is the lb config section in our script and its not throwing the xlog so load balancing is successful.

        lb_reset();
        if(!lb_start_or_next(LB_INGRESS_CALLS, "$avp(product)")) {
                xlog("--[$ci] Load balance NOT successful, Load balance tags used are [$avp(product)]");
                send_reply(503, "Resources Unavailable");
                exit;
        }
