### ISSUE TITLE
[BUG] avp_db_query() returns null value as "<null>"

### ISSUE THREAD

**Issue by ankogan** [OpenSIPS/opensips#3027]
**OpenSIPS version you are running**
```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 4096, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: dac56fa49
main.c compiled on  with gcc 4.9.2
```

**Describe the bug**
avp_db_query("select max(x) from test", "$avp(x)") returns "\<null\>" in $avp(x) in case the test table is empty.
DB == postgres 15

**Expected behavior**
$avp(x) == null

**Comment by razvancrainea** [comment]
This is the expected behavior, as an `avp` cannot have the `NULL` value. This however was not properly documented, I've just pushed a commit to fix it. Thanks for your report!
