### ISSUE TITLE
[BUG] topology_hiding: conflict between fix_nated_contact() and topology_hiding()

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#3029]
**Describe the bug**
On initial INVITE, if `fix_nated_contact()` is called before `topology_hiding("UN")`, the changes made by `fix_nated_contact()` are visible.
If `fix_nated_contact()` is called after `topology_hiding("UN")`, the changes made by `fix_nated_contact()` are lost.

This is true for in dialog requests if `fix_nated_contact()` is called before and after `topology_hiding_match()`.

**To Reproduce**
A simple config will expose the issue:
```
...
loadmodule "topology_hiding.so"
...
route {
...
  if (has_totag()) {
    xlog("L_INFO","[$mi] before topology_hiding_match() ru=[$ru]\n");
    if (topology_hiding_match()) {
      xlog("L_INFO","[$mi] after topology_hiding_match() ru=[$ru]\n");
    }
  }
...
  # initial INVITE
  topology_hiding("UN");
  fix_nated_contact(";ata=cisco");
...
}
```

INVITE in:
```
INVITE sip:240@192.168.2.61 SIP/2.0
Contact: <sip:241@192.168.2.94:5063>
```
INVITE out:
```
INVITE sip:240@192.168.2.2 SIP/2.0
Contact: <sip:241@192.168.2.61;thinfo=VG9JbzAdIFthZ2UvYVZxWmFXa31mQWlbeUFgV2BGVBo0H3lFaVN9YmJXfl1tQmFbZmNiXw-->
```
BYE from callee in:
```
BYE sip:241@192.168.2.61;thinfo=VG9JbzAdIFthZ2UvYVZxWmFXa31mQWlbeUFgV2BGVBo0H3lFaVN9YmJXfl1tQmFbZmNiXw-- SIP/2.0
```
BYE from callee out:
```
BYE sip:241@192.168.2.94:5063 SIP/2.0
```
If `fix_nated_contact(";ata=cisco")` is called before `topology_hiding()`, the RURI of outgoing BYE has the "ata=cisco" parameter set.

This affects all opensips versions.

**Comment by ovidiusas** [comment]
@bogdan-iancu , what about `topology_hiding_match()`?
For the `fix_nated_contact()/topology_hiding()` dance we can leave with this limitation.
For the `fix_nated_contact()/topology_hiding_match()` it's not that easy. We want to apply changes to the Contact header after we have a match on the received in-dialog request.
```
...
loadmodule "topology_hiding.so"
...
route {
...
  if (has_totag()) {
    if (topology_hiding_match()) {
      ...
      fix_nated_contact(";ata=cisco");
      ...
    }
  }
...

}
```

**Comment by bogdan-iancu** [comment]
I'm afraid it is 100% the same situation, as the `topology_hiding_match()` func does matching + `topology_hiding()` . So either try to move the `fix_nated_contact()` before the matching, either try to use dialog based TH

**Comment by liviuchircu** [comment]
Hi Ovidiu/Bogdan!

Isn't this the same known issue as documented in [#2172](https://github.com/OpenSIPS/opensips/issues/2172#issuecomment-658783502)?  Basically, 1/4 combinations of `topology_hiding()` with `fix_nated_contact()` and brackets/no-brackets Contact will not work.  The other 3/4 work just fine.  If so, maybe we should close this one as a duplicate.
