### ISSUE TITLE
[BUG] xlog_level can't set minus

### ISSUE THREAD

**Issue by chenyw11** [OpenSIPS/opensips#3035]
opensips version is **3.2.5**

**When I set xlog_level=-1，opensips can't startup.**

This is the log:
Mar 15 15:28:00 [161] Traceback (last included file at the bottom):
Mar 15 15:28:00 [161]  0. /usr/local//etc/opensips/opensips.cfg
Mar 15 15:28:00 [161] CRITICAL:core:yyerror: parse error in /usr/local//etc/opensips/opensips.cfg:9:12-13: syntax error
Mar 15 15:28:00 [161] 
Mar 15 15:28:00 [161] log_level=-1
Mar 15 15:28:00 [161] xlog_level=-1
Mar 15 15:28:00 [161] ^~
Mar 15 15:28:00 [161] log_stderror=no
Mar 15 15:28:00 [161] log_facility=LOG_LOCAL0
Mar 15 15:28:00 [161] CRITICAL:core:yyerror: parse error in /usr/local//etc/opensips/opensips.cfg:9:12-13: number expected
Mar 15 15:28:00 [161] CRITICAL:core:yyerror: parse error in /usr/local//etc/opensips/opensips.cfg:9:13-14:
Mar 15 15:28:00 [161] ERROR:core:parse_opensips_cfg: bad config file (3 errors)
Mar 15 15:28:00 [161] ERROR:core:main: failed to parse config file (null)
Mar 15 15:28:00 [161] NOTICE:core:main: Exiting....   

In [cfg.y](https://github.com/OpenSIPS/opensips/blob/3.2.5/cfg.y), I saw:
![image](https://user-images.githubusercontent.com/102004099/225248458-fb413685-3fcf-4188-aa03-e97ffea96e77.png)
Should it be changed to **XLOG_LEVEL EQUAL snumber** ?

**Comment by bogdan-iancu** [comment]
It looks like that's fixed for a while -> https://github.com/OpenSIPS/opensips/blob/3.2/cfg.y#L1064 , try getting the latest 3.2
