### ISSUE TITLE
[BUG] nameaddr.param,foo doesn't work any more

### ISSUE THREAD

**Issue by jes** [OpenSIPS/opensips#3040]
**OpenSIPS version you are running**

Latest master from git.

**Describe the bug**

Using `nameaddr.param,foo` does not work, always gives "\<null\>". It can be worked around by using `nameaddr.0.param,foo`. I believe the bug was introduced in b32b7ff48968ed9f5a1c5910f210ef1fc1d583bc

**To Reproduce**

This example lifted from the documentation is meant to give "dat43h", but gives "\<null\>"

```
$var(foo)='"test" <sip:test@opensips.org>;tag=dat43h;private=yes';
$var(bar)=$(var(foo){nameaddr.param,tag});
xlog("$var(bar)\n");
```

**Expected behavior**

I expected it to print "dat43h".

**Relevant System Logs**

```Mar 24 16:40:16 [30145] ERROR:core:tr_eval_nameaddr: invalid index type: 1; integer expected```

**OS/environment information**
 - Operating System: CentOS 7
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by jes** [comment]
Yes, I'm pretty sure this is still a bug.

**Comment by bogdan-iancu** [comment]
@jes , thanks for the report. Please test the fix I just pushed.

**Comment by jes** [comment]
Yep, looks good to me, thanks!
