### ISSUE TITLE
[BUG] Calling rtpproxy_engage() twice breaks the SDP

### ISSUE THREAD

**Issue by nud** [OpenSIPS/opensips#3042]
**OpenSIPS version you are running**

```
version: opensips 3.2.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10
```

**Describe the bug**

When calling `rtpproxy_start_recording()` twice, opensips will break the SDP by adding the IP twice in the c line, the port twice in the m line, and adds rtpproxy:yes twice with an extra white line.

For instance:

```
v=0
o=- 1680072849 1680072849 IN IP4 10.0.0.4
s=Polycom IP Phone
c=IN IP4 10..0.0.510.0.0.5
t=0 0
a=sendrecv
m=audio 6316463164 RTP/AVP 9 8 18
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=nortpproxy:yes

a=nortpproxy:yes
```

The mistake was swiftly found and fixed in our script, but I think it should not result in a broken SDP.

**To Reproduce**

1. Call `start_rtpproxy_recording()` twice in your opensips script
2. Make a call
3. Check the INVITE SDP in the pcap trace between opensips and the callee.

**Expected behavior**

I don't have any strong opinion about the nortpproxy:yes line being duplicated, but IMO the IP address should be correct.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: APT package from https://apt.opensips.org bullseye/3.2-releases

**Comment by razvancrainea** [comment]
The `rtpproxy_start_recording()` function doesn't perform any changes to the SDP, so I am pretty sure this is not the culprit.
The behavior you are facing is most likely due to calling `rtpproxy_offer` and/or `rtpproxy_answer` twice - can you confirm?

Best regards,
Răzvan

**Comment by nud** [comment]
Hi @razvancrainea,

This is the route that was mistakenly being called twice:

```
route[RECORD_CALL_ENGAGE] {
  # Filter codecs so we only allow the ones we are able to transcode afterwards.
  # We keep "telephone-event", otherwise RTP2833 DTMFs would not work (trunks).
  codec_delete_except_re("PCMA|PCMU|G722|G729|telephone-event");

  # Start recording.
  {{ logTemplate.log("RECORD_CALL: recording; Call-ID: $ci") }}
  rtpproxy_engage("r");
  store_dlg_value("rec", "1");
  rtpproxy_start_recording();
  cache_store("redis:group1", "rtpproxy:records:$ci", "$Ts {{ server.name }} $avp(rec_caller) $avp(rec_callee) $param(1)", 14400); # 4H TTL
}
```

So I guess you are right, `rtpproxy_engage` is being called twice too.

**Comment by razvancrainea** [comment]
If you are calling `rtpproxy_engage` twice, then this is expected - you should avoid doing that.
