### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PratikPatel2801** [OpenSIPS/opensips#3044]
Hello 

I want to make my opensips listen as wss same like FreeSWITCH but facing issue with opensips :

I am working on opensips with wss and tls configuration but facing below Error :
[140010946856256:error:1409445C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required:../ssl/record/rec_layer_s3.c:1543:SSL alert number 116](url)

openssl s_client -connect [abc.com:7443](http://abc.com:7443/) -servername [abc.com](http://abc.com/)
In opensips.cfg code :

https://pastebin.com/Bn9fc70Z

**Comment by razvancrainea** [comment]
This is not a bug, but rather a misusage and/or misconfiguration. The error clearly says what is the problem.
