### ISSUE TITLE
[FEATURE] tcp support for connection between opensips and rtpengine

### ISSUE THREAD

**Issue by jeevantexo** [OpenSIPS/opensips#3045]
**Is your feature request related to a problem? Please describe.**

Observing udp signaling packets getting fragmented if we use udp connection between opensips and rtpengine.  Seems like rtpengine or any other module do not provide support for TCP connections with RTP engine.

**Describe the solution you'd like**
Is there any way we can make the connection between opensips and rtpenngine over udp.

**Comment by volga629-1** [comment]
@jeevantexo  This ticket to track progress 

https://github.com/OpenSIPS/opensips/issues/2296
