### ISSUE TITLE
[BUG] JSONRPC invalid buffer check

### ISSUE THREAD

**Issue by Integration-IT** [OpenSIPS/opensips#3047]
Manual JSONRPC to some API are successfully run, but the returned function code is error 3 with a non empty buffer but an empty ret_var.
The answer is considered as invalid.

Request:
```
{"id":6228264,"jsonrpc":"2.0","method":"APIerSv1.Ping","params":[{"Tenant":"monkeytester"}]}
```
Answer:
```
{"id":6228264,"result":"Pong","error":null}
```

Why: [https://github.com/OpenSIPS/opensips/blob/master/modules/jsonrpc/jsonrpc.c#L341](url)
```
	aux = cJSON_GetObjectItem(obj, "error");
	if (aux) {
		/* return the entire error */
		vret->rs.s = cJSON_Print(aux);
		vret->rs.len = strlen(vret->rs.s);
		vret->flags = PV_VAL_STR;
		LM_DBG("Error got from JSON-RPC: %s!\n", buffer);
		ret = -3;
		goto end;
	}
```

After comment this code part and use this code part at script level:
```
jsonrpc_request("127.0.0.1:2012", "APIerSv1.Ping", "[{\"Tenant\":\"monkeytester\"}]", $var(ret));
$json(foo) := $var(ret);
xlog("SCRIPT:DBG: [TIMER ROUTE PICKER] | JSON-RPC command returned $json(foo).\n");
```
```
SCRIPT:DBG: [TIMER ROUTE PICKER] | JSON-RPC command returned Pong.
```

**Comment by bogdan-iancu** [comment]
@Integration-IT , could you test the fix I just pushed, to see if it solved that strange JSOB reply you have?

**Comment by bogdan-iancu** [comment]
done, backported all the way to 3.2
