### ISSUE TITLE
[BUG] stir_shaken: Failed to load private key from buffer (positive return from stir_shaken_auth)

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#3050]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**

Using STIR/SHAKEN we have a scenario where when using the `stir_shaken_auth` function it returns with a positive response, however fails to sign the call.

This is accompanied by the error in the logs:

```
Apr  4 18:39:56 /usr/sbin/opensips[23752]: ERROR:stir_shaken:load_pkey: Failed to load private key from buffer
Apr  4 18:39:56 /usr/sbin/opensips[23752]: ERROR:stir_shaken:w_stir_auth: Failed to load private key
```

**To Reproduce**

1. Start OpenSIPS.
2. Setup STIR/SHAKEN, all params are cached in JSON in local cache.
3. Calls initially work correctly as expected
4. Some unknown event happens, sorry we dont know the trigger.
5. The problem occurs on all future calls.

**Expected behavior**

1. The call SHOULD be signed with STIR/SHAKEN and the fault should not happen.
2. If an error such as 'Failed to load private key' occurs, the response of `stir_shaken_auth` should be negative to then allow us to not progress the call.

**Relevant System Logs**

```
Apr  4 18:39:56 /usr/sbin/opensips[23752]: ERROR:stir_shaken:load_pkey: Failed to load private key from buffer
Apr  4 18:39:56 /usr/sbin/opensips[23752]: ERROR:stir_shaken:w_stir_auth: Failed to load private key
```

**OS/environment information**
 - Operating System: Ubuntu 20.04
 - OpenSIPS installation: packages
 - other relevant information:

**Additional context**

**Comment by rvlad-patrascu** [comment]
Hi @digipigeon ,

The `ERROR:stir_shaken:load_pkey: Failed to load private key from buffer` error indicates that openssl was not able to parse the private key buffer provided to `stir_shaken_auth()`. If you have the key in a local cache, maybe at some point it  changes to something invalid, otherwise there is not much that could go wrong in the stir_shaken module.

In terms of the error being propagated by `stir_shaken_auth()` to the script, it looks highly unlikely the function would return success if it fails to load the private key. Are you sure you are checking the error code properly?

**Comment by digipigeon** [comment]
This is the code that we have

```
		$var(stir_shaken_rc) = stir_shaken_auth($json(r/stir_shaken/attest), $json(r/stir_shaken/origid), $json(cert/cert), $json(cert/key), $json(cert/x5c), $json(r/cli), $json(r/dest_number));

		if (!$var(stir_shaken_rc)) {
			switch ($var(stir_shaken_rc)) {
				case -1:
					$var(stir_shaken_err) = "Internal error";
					break;
				case -2:
					$var(stir_shaken_err) = "Identity header already exists";
					break;
				case -3:
					$var(stir_shaken_err) = "Failed to derive identity from SIP message because the URI is not a telephone number";
					break;
				case -4:
					$var(stir_shaken_err) = "Date header value is older than local policy for freshness";
					break;
				case -5:
					$var(stir_shaken_err) = "Unsupported 'ppt' or 'alg' Identity header parameter";
					break;
				case -6:
					$var(stir_shaken_err) = "Date header value is older than local policy for freshness";
					break;
				case -7:
					$var(stir_shaken_err) = "The Date header value does not fall within the certificate validity";
					break;
				case -8:
					$var(stir_shaken_err) = "Invalid certificate";
					break;
				case -9:
					$var(stir_shaken_err) = "Signature does not verify successfully";
					break;
			}

			send_reply(500, "STIR SHAKEN Attestation Failed");
			xlog("L_INFO","$ci ($cfg_file) STIR SHAKEN Auth Failed: $var(stir_shaken_err)");
			exit;
		}
```

Please let me know if you see any reason why it may not have worked as expected.

**Comment by digipigeon** [comment]
Hello @rvlad-patrascu 

Thanks for identifying the fault in the logic, it seemed that was the cause of the problem.
