### ISSUE TITLE
[CRASH] OpenSIPS crashes with mid_registrar and proto_tls

### ISSUE THREAD

**Issue by FurretUber** [OpenSIPS/opensips#3052]
**OpenSIPS version you are running**

```
version: opensips 3.2.11 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 10
```

**Crash Core Dump**
https://mega.nz/file/ooghiZhK#yXLIfdzOEP4n9L2tdXQwMZ2XxjN-iHcjEI7MrncCKjQ

**Describe the traffic that generated the bug**

A REGISTER attempt from a softphone, while OpenSIPS is configured to use the mid_registrar and proto_tls modules.
**To Reproduce**

1. Start OpenSIPS;
2. Try to REGISTER the softphone;
3. OpenSIPS crashes. 
**Relevant System Logs**
[Compressed file with details](https://github.com/OpenSIPS/opensips/files/11174359/openSIPS-crash-arq.tar.gz)

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: deb [signed-by=/usr/share/keyrings/opensips-org.gpg] https://apt.opensips.org bullseye 3.2-releases
 - other relevant information: there is an Asterisk running on the same machine.

**Additional context**
Interestingly, the Asterisk that OpenSIPS is forwarding the REGISTER to does receive the REGISTER and successfully REGISTERs the endpoint for a a few milliseconds, so the communication did arrive the Asterisk and Asterisk did receive the data necessary to REGISTER.
Another thing I have noticed is that, if I change the `$ru` to use `sips:` instead of `sip:` on the line 186 of `opensips.cfg` there is no crash. But then, no INVITE works normally (would have to edit the softphone to use `sips:` instead of `sip:`, but this change on the softphones is not viable).

[This file](https://github.com/OpenSIPS/opensips/files/11174359/openSIPS-crash-arq.tar.gz) has additional logs and the configuration that triggered the crash (an attempt was made).
While on this setup the Asterisk and OpenSIPS are on the same machine, it's possible that they could be located in different machines, this is why TLS is being used.

**Comment by bogdan-iancu** [comment]
@FurretUber , using gdb, could you run:
```
p *mri
p mri->ct_mappings
```

Thanks!

**Comment by FurretUber** [comment]
```
(gdb) p *mri
$1 = {main_reg_uri = {s = 0x7ffff5326e70 "sip:sip-server.zondeneia.com:5066i2\365\377\177", len = 33}, main_reg_next_hop = {s = 0x0, len = 0}, ct_uri = {s = 0x0, len = 0}, to = {
    s = 0x7ffff532fd10 "sip:5000@sip-server.zondeneia.com", len = 33}, from = {s = 0x7ffff53186e8 "sip:5000@sip-server.zondeneia.com", len = 33}, callid = {s = 0x7ffff532fcb0 "gWlbPv~IO1", len = 10}, 
  last_cseq = 0, reg_flags = 0, star = 0, expires = 0, expires_out = 7200, last_reg_ts = 0, skip_dereg = 0, max_contacts = 0, ct_mappings = {prev = 0x7ffff532f7e8, next = 0x7ffff532f7e8}, dom = 0x7ffff52f49b8, 
  aor = {s = 0x7ffff532e368 "5000\377\177", len = 4}, ownership_tag = {s = 0x0, len = 0}, cmatch = {mode = CT_MATCH_NONE, match_params = 0x0}, user_agent = {s = 0x0, len = 0}, ul_flags = 0, cflags = 0, 
  pn_provider_state = 0x0, pending_replies = 1, tm_lock = 0x7ffff5326e20}
(gdb) p mri->ct_mappings
$2 = {prev = 0x7ffff532f7e8, next = 0x7ffff532f7e8}

```

**Comment by bogdan-iancu** [comment]
Let's get @liviuchircu as a second pair of eyes here
