### ISSUE TITLE
How to forcibly log out of the previous extension number(opensips version 2.2)

### ISSUE THREAD

**Issue by xiaosenweng** [OpenSIPS/opensips#3055]
hello sir
    
    On laptop A, log in at extension 1001. Then, when I want to log in to extension 1001 on laptop B, how do I configure it so that the system can forcibly log out of the extension number of laptop A?

**Comment by bogdan-iancu** [comment]
See https://opensips.org/html/docs/modules/3.2.x/registrar.html#func_save - use a combination of `c1` (max one contact) and `f` (override existing contacts) flags.
