### ISSUE TITLE
[CRASH] OpenSIPS crashes when attempting to remove the RTPEngine dataset from the rtpengine database via db_http

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#3056]
**OpenSIPS version you are running**

```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Crash Core Dump**

[CoreDump](https://drive.google.com/file/d/1Nl8HLP1NITtDb84fWCF7GUrFWyiLu_Nz/view?usp=sharing)

**Describe the traffic that generated the bug**

**To Reproduce**
1. Start OpenSIPS
2. Remove the RTPEngine dataset via db_http
3. Check OpenSIPS crashed

**OS/environment information**
 - Operating System: 18.04.6 LTS

**Additional context**
OpenSIPS crashes when we were to remove a set from the rtpengine database, when loading via db_http

**Comment by liviuchircu** [comment]
Just pushed the goods to `master` branch, @syedrizwansrs, after my own tests were successful.  It's all yours!

**Comment by bogdan-iancu** [comment]
@syedrizwansrs have you managed to test, so we can do the backports and close here ?
