### ISSUE TITLE
[BUG] IP address log lines can't handle 2 different IP addresses

### ISSUE THREAD

**Issue by jes** [OpenSIPS/opensips#3062]
**OpenSIPS version you are running**

```
version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6faf77b
main.c compiled on 14:58:32 Mar 24 2023 with gcc 4.8.5
```

Problem exists on latest master as well.

**Describe the bug**
The problem is code like:
```
LM_DBG( "Successfully connected from interface %s:%d to %s:%d!\n",
   ip_addr2a( &c->rcv.src_ip ), c->rcv.src_port,
   ip_addr2a( &c->rcv.dst_ip ), c->rcv.dst_port );
```

The ip_addr2a function writes to a static buffer and returns a pointer to that buffer. That means the second call to ip_addr2a overwrites the IP address from the first call.

I’m not sure what the ideal solution would be.

I have a bodge in mind, whereby we have N static buffers available and cycle through them. This would make it work for the special case of log lines with a small number of IP addresses, and wouldn’t harm any other cases, but it has the downside that the same bug is still basically lurking ready to be triggered, and will be 10x harder to find later because it will appear to work.

Another option would be to fastidiously comb over every log output that calls ip_addr2a twice and split it into 2 separate outputs, but that seems worse to me.

If it would be helpful as a starting point, I can make a pull request for  the "N static buffers" solution.

**Comment by bogdan-iancu** [comment]
Yes, there is a list of know functions that use internal buffers. Where did you find that LM_DBG in the code ?

**Comment by jes** [comment]
There are quite a few instances of code like that. Here's a list of the most obvious examples (from `grep -rn %s:%d.*%s:%d`):

```
modules/proto_tls/proto_tls.c:530:			LM_DBG("Successfully connected from interface %s:%d to %s:%d!\n",
modules/proto_msrp/msrp_common.c:461:		LM_DBG("Accepted connection from %s:%d on interface %s:%d!\n",
modules/proto_msrp/msrp_common.c:627:		LM_DBG( "Successfully connected from interface %s:%d to %s:%d!\n",
net/proto_tcp/proto_tcp.c:419:			LM_DBG( "Successfully connected from interface %s:%d to %s:%d!\n",
net/proto_tcp/proto_tcp.c:491:			LM_DBG( "Successfully connected from interface %s:%d to %s:%d!\n",
net/proto_tcp/proto_tcp.c:659:		LM_DBG("Accepted connection from %s:%d on interface %s:%d!\n",
```

**Comment by jes** [comment]
What do you think about the solution of giving ip_addr2a two separate static buffers and having it alternate between them?

Or alternatively would you prefer to split the offending log outputs into 2 separate calls to LM_DBG?

Or something else?

**Comment by bogdan-iancu** [comment]
@jes , I did a fix on trunk, please give it a try. I used the same approach (of multiple rotating buffers) we already have for [int2str()](https://github.com/OpenSIPS/opensips/blob/master/ut.h#L275). If ok, I will do the backport.

**Comment by jes** [comment]
Looks good to me, thanks!
