### ISSUE TITLE
Issue with "Reload on Server" on OpenSIPS Control Panel 8.3.2

### ISSUE THREAD

**Issue by razvanzeces** [OpenSIPS/opensips#3071]
Hello,

I've just installed a fresh OpenSIPS Server on Debian 10. 

Everything it's OK, until I have to setup anything on the OpenSIPS CP, version 8.3.2.

When I hit the Reload on Server, after I modify some changes on Domains, or any other tab that has the Reload on Server button, it just hangs on Sending to json:127.0.0.1:8888/mi and it's not displaying the Success green message....

What should I check? Am I doing something wrong?

Any help it's greatly appreciated!

**Comment by razvanzeces** [comment]
When trying to run mi ps or mi which from opensips-cli, I get the following error:

root@adapter01:~# opensips-cli mi ps
Welcome to CLI!
(cli): mi ps
ERROR: fifo file /tmp/opensips_fifo does not exist!
ERROR: Is OpenSIPS running?
(cli): mi which
ERROR: fifo file /tmp/opensips_fifo does not exist!
ERROR: Is OpenSIPS running?
(cli):

===

OpenSIPS it's working, as per:

root@adapter01:~# systemctl status opensips
● opensips.service - OpenSIPS is a very fast and flexible SIP (RFC3261) server
   Loaded: loaded (/lib/systemd/system/opensips.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2023-04-30 21:45:40 EDT; 4s ago
     Docs: man:opensips
  Process: 32385 ExecStart=/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 32388 (opensips)
    Tasks: 9 (limit: 2359)
   Memory: 12.9M
   CGroup: /system.slice/opensips.service
           ├─32388 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32389 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32390 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32391 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32392 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32393 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32394 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           ├─32395 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4
           └─32396 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 64 -M 4

Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:evi_publish_event: Registered event <E_UL_CONTACT_REFRESH(9)>
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:evi_publish_event: Registered event <E_UL_LATENCY_UPDATE(10)>
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:registrar:mod_init: initializing...
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:acc:mod_init: initializing...
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:evi_publish_event: Registered event <E_ACC_EVENT(11)>
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:evi_publish_event: Registered event <E_ACC_CDR(12)>
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:evi_publish_event: Registered event <E_ACC_MISSED_EVENT(13)>
Apr 30 21:45:40 adapter01.host.local /usr/sbin/opensips[32388]: INFO:core:mod_init: initializing UDP-plain protocol
Apr 30 21:45:40 adapter01.host.local opensips[32385]: INFO:core:daemonize: pre-daemon process exiting with 0
Apr 30 21:45:40 adapter01.host.local systemd[1]: Started OpenSIPS is a very fast and flexible SIP (RFC3261) server.
root@adapter01:~#

**Comment by razvanzeces** [comment]
Based on the Text that's shown up when hitting Reload - Sending MI command: domain_reload, I think it's like using opensips-cli, but there's no domain_reload MI cmd:

root@adapter01:~# opensips-cli
Welcome to CLI!
(cli): mi
-j                cache_remove      events_list       kill              list_tcp_conns    mem_rpm_dump      pwd               reset_statistics  t_hash            t_uac_dlg         ul_dump           ul_rm_contact     uptime            xlog_level
arg               cache_store       get_statistics    list_blacklists   log_level         mem_shm_dump      raise_event       shm_check         t_reply           ul_add            ul_flush          ul_show_contact   version
cache_fetch       event_subscribe   help              list_statistics   mem_pkg_dump      ps                reload_routes     subscribers_list  t_uac_cancel      ul_cluster_sync   ul_rm             ul_sync           which
(cli): mi s
shm_check         subscribers_list
(cli): mi subscribers_list
{
    "Events": []
}
(cli):

**Comment by AlijiEmmanuel-dev** [comment]
First of all make sure you are using the right version of opensips cp, if using opensips 3.3  your should use cpanel 9.3.3. Read the cpanel docs to make sure your version is the right appropriate version for your opensips.

**Comment by bogdan-iancu** [comment]
@razvanzeces , the MI commands are provided by the OpenSIPS modules you have loaded in the cfg. The "domain_reload" cmd is provided by the "domain"  modules, so be be sure you have it loaded.
