### ISSUE TITLE
tls client mode only without own certificate

### ISSUE THREAD

**Issue by manojmth** [OpenSIPS/opensips#3073]
Had an use case where opensips needs to act as a sip tls client whether it initiates or responds to communication from a certain peer. Only use the peer certificate for tls without presenting its own. Peer will authenticate opensips using digest auth. Is this possible?

**Comment by bogdan-iancu** [comment]
It depends on the other party if it will require OpenSIPS to present or not a certificate, so not something to control from your side.

**Comment by manojmth** [comment]
Thanks
