### ISSUE TITLE
fm_malloc: not enough free shm memory

### ISSUE THREAD

**Issue by AnjanIpc** [OpenSIPS/opensips#3075]
**OpenSIPS version you are running**

```OpenSIPS version: opensips 2.4.4 (x86_64/linux)
```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: RHEL 6
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

Can you please let   me know, what is the issue here ?

**Comment by AnjanIpc** [comment]
OpenSIPS version: opensips 2.4.4 (x86_64/linux)

**Comment by razvancrainea** [comment]
OpenSIPS 2.4 is no longer supported - your best chance is to update to the latest 2.4 available, and if this does not fix, upgrade to one of the supported versions. If this still happens in one of the supported versions, please follow [this](https://www.opensips.org/Documentation/TroubleShooting-OutOfMem) intructions.

**Comment by AnjanIpc** [comment]
Thanks for getting back .
Can you please confirm, if this issue was present in Version 2.4 and fixed in later versions ?
so that we can upgrade .
The reason i am asking is, this is in Production and Customer has asked this question . Once confirmed only, they will allow us to upgrade.

Thanks

**Comment by AnjanIpc** [comment]
Thanks for your response.
This issue is not reproduced. we see once on the Production system.
I am attaching the opensips logs from Production for your reference.

[opensips.zip](https://github.com/OpenSIPS/opensips/files/11430862/opensips.zip)

From the log, you can see , **2023-03-19T17:27:54.000+01:00** [local2] [err] T /usr/sbin/opensipsInternal[37441]: ERROR:core:fm_malloc: not enough free shm memory (0 bytes left, need 5048), please increase the "-m" command line parameter!

our config has -m set to 512 . "-m 512 "

Thanks.

**Comment by liviuchircu** [comment]
It looks like you're doing too many SIP transactions to fit in `512 MB` of shm.  Try `2 GB` and behavior should improve.

```
2023-03-20T02:09:53.000+01:00 [local2] [err] T /usr/sbin/opensipsInternal[37380]: ERROR:core:fm_malloc: not enough free shm memory (4688 bytes left, need 6720), please increase the "-m" command line parameter!
2023-03-20T02:09:53.000+01:00 [local2] [err] T /usr/sbin/opensipsInternal[37380]: ERROR:tm:new_t: out of mem
2023-03-20T02:09:53.000+01:00 [local2] [err] T /usr/sbin/opensipsInternal[37380]: ERROR:tm:t_newtran: new_t failed
```

**Comment by AnjanIpc** [comment]
@liviuchircu , Thank you so much for your quick response.
But as per customer, this system is used by very few users and no load on the system.
so we believe, there will not be so many Txn.

Do you think of anything else, which might have caused this. ?
