### ISSUE TITLE
Clarification on " #3075"

### ISSUE THREAD

**Issue by AnjanIpc** [OpenSIPS/opensips#3079]
OpenSIPS version: opensips 2.4.4 (x86_64/linux)
RHEL 6

Thanks for getting back on #3075  .
Can you please confirm, if this issue was present in Version 2.4 and fixed in later versions ? so that we can upgrade .
The reason i am asking , this is in Production and Customer has asked this question . Once  they confirmed that this issue is resolved in higher opensips version ,only then they will allow us to upgrade.

So can you please confirm ?

Thanks

**Comment by liviuchircu** [comment]
Hello, @AnjanIpc!  Please do not open a new issue just to ask a follow-up question -- the discussion can be continued in #3075 for a few more replies even if it's closed :)  And participants will be emailed of replies, etc.

**Comment by AnjanIpc** [comment]
oh..sorry about that.
I have already raised this concern on #3075 yesterday even it was closed but didnt get a response.
so i thought of creating a new one.

Thanks for clarifying.
If possible, can you please answer to my queries on #3075.

waiting for your feedback.
Thanks,
