### ISSUE TITLE
How could I modify the gcc parameters?

### ISSUE THREAD

**Issue by miszuoer** [OpenSIPS/opensips#3083]
I want to add -fprofile-arcs -ftest-coverage to gcc flags, so as to get .gcno files, but the makefile is so complicated, can anybody help me? Thanks a lot!

**Comment by razvancrainea** [comment]
@miszuoer you can you try adding `CC_EXTRA_OPTS=-ftest-coverage` either in Makefile.conf, either prior your `make` command. Let me know if this works for you.

**Comment by miszuoer** [comment]
I added this gcc parameter in the Makefile.conf，and it works. Thanks a lot!
