### ISSUE TITLE
[CRASH] b2b_init_request

### ISSUE THREAD

**Issue by mirkobrankovic** [OpenSIPS/opensips#3089]
**OpenSIPS version**
```
version: opensips 3.4.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 81dd95f15
main.c compiled on 10:15:15 May 12 2023 with gcc 10
```

**Crash Core Dump**
https://pastebin.com/qp6AZqab

**Describe the traffic that generated the bug**
B2B server module

**To Reproduce**
Generate 10 calls per second, sometimes it crashes after 2000-3000 but on some occasions at 400 calls done correctly. 
interesting routing block:
```
...
b2b_server_new("caller", "sip:$rU@$socket_in(ip):$socket_in(port);transport=$socket_in(proto)");
b2b_client_new("callee", "<sip:$var(ru_translated)@$dd:$dp>", "<sip:$dd:$dp>", "", "sip:sbc1@$socket_out(ip):$socket_out(port);transport=$socket_out(proto)", $avp(hdrs), $avp(hdrs_values));
b2b_init_request("sbc");
...
```

**Relevant System Logs**

Opensips starts timing out on b2b_init_request with error:
```
May 12 11:38:18 [5331] DBG:tm:t_unref: UNREF_UNSAFE: [0x7fdb5f7c7458] after is 1
May 12 11:38:18 [5331] DBG:b2b_entities:_server_new: It is a retransmission, drop
May 12 11:38:18 [5331] shm_free(0x7fdb5f7ad430), called from server.c: _server_new(102)
May 12 11:38:18 [5331] freeing frag. 0x7fdb5f7ad400 alloc'ed from dlg.c: b2b_dlg_copy(419)
May 12 11:38:18 [5331] ERROR:b2b_logic:b2b_process_scenario_init: failed to create new b2b server instance
```

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: source
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment]
@mirkobrankovic , the BT you posted here shows an INVITE (most probably an initial one, as it has Record-Route hdrs in it) going via the OpenSIPS script and crashing into some send_reply(100 Trying)...and indeed, it is in some tracing stuff...
What kind of tracing do you do from script?
Also, do you still have the core file for further investigations?

**Comment by mirkobrankovic** [comment]
@bogdan-iancu sorry for late reply, I didn't get notifications about this.
we were using HEP encapsulated ones and sending them to Homer capture node:

Similar to docs example:
```
modparam("proto_hep", "hep_id",  "[hid]10.10.10.10")
modparam("tracer", "trace_id", "[tid]uri=hep:hid")
```
