### ISSUE TITLE
Received PRACK requests are not traced

### ISSUE THREAD

**Issue by xaled1** [OpenSIPS/opensips#3094]
We also noticed, when doing "b"-tracing (tracing b2b automatically using "b"-mode in opensips 3.2), the received PRACK requests are not traced. Likely this is because of the same reason.

**Comment by xaled1** [comment]
Follow up from https://github.com/OpenSIPS/opensips/issues/2686

**Comment by xaled1** [comment]
bump

**Comment by bogdan-iancu** [comment]
@xaled1 , I just tried your scenario, doing tracing to SIP destination (easier to test with ;) ):
```
loadmodule "tracer.so"
modparam("tracer", "trace_on", 1)
modparam("tracer", "trace_id", "[sngrep]uri=sip:127.0.0.1:9")
```
and in script:
```
	if (is_method("INVITE")) {
		if (!lookup("location","m")) {
			t_reply(404, "Not Found");
			exit;
		}
		trace("sngrep", "b");
		b2b_init_request("top hiding");
		exit;
	}
```
Now, making a call I get for the caller side (:5059 is the caller, :5060 is OpenSIPS and :9 are the traced messages)
![Screenshot_2023-06-23_19-11-33](https://github.com/OpenSIPS/opensips/assets/3973594/ecdce4b2-d382-46ce-b83a-3e73cc812454)

as you can see the PRACK is traced too. Using the latest 3.2
