### ISSUE TITLE
[BUG] 3.4 Auto Scaling Cycle wrong cycle factor

### ISSUE THREAD

**Issue by Integration-IT** [OpenSIPS/opensips#3099]
Hi Teams,

Version : 3.4.

auto_scaling_cycle : The number of seconds defining a auto-scaling cycle - the auto-scaling engine, at each cycle, is evaluating the internal load of the groups and decided if more processes needs to be created or if existing processes need to be terminated.

Setup:
```
auto_scaling_cycle=1

auto_scaling_profile=PROFILE_SIP_ULTRALOW
 scale up to 3 on 70% for 3 cycles within 5
 scale down to 2 on 50% for 5 cycles

auto_scaling_profile=PROFILE_SIP_LOW
 scale up to 10 on 70% for 3 cycles within 5
 scale down to 5 on 20% for 5 cycles

auto_scaling_profile=PROFILE_SIP_MEDIUM
 scale up to 30 on 70% for 3 cycles within 5
 scale down to 8 on 20% for 5 cycles

auto_scaling_profile=PROFILE_SIP_HIGH
 scale up to 50 on 70% for 3 cycles within 5
 scale down to 8 on 20% for 5 cycles
```

Config check (focus on delay) :
```
opensips -ddddd -C -c /usr/local/etc/opensips/opensips.cfg

DBG:core:create_auto_scaling_profile: profile <PROFILE_SIP_ULTRALOW> created UP [max=3, th=70%, check 3/5] DOWN [min=2, th=50%, check 5, delay=50]
DBG:core:create_auto_scaling_profile: profile <PROFILE_SIP_LOW> created UP [max=10, th=70%, check 3/5] DOWN [min=5, th=20%, check 5, delay=50]
DBG:core:create_auto_scaling_profile: profile <PROFILE_SIP_MEDIUM> created UP [max=30, th=70%, check 3/5] DOWN [min=8, th=20%, check 5, delay=50]
DBG:core:create_auto_scaling_profile: profile <PROFILE_SIP_HIGH> created UP [max=50, th=70%, check 3/5] DOWN [min=8, th=20%, check 5, delay=50]
```

Manual check (focus on logs) :
My E_CORE_PROC_AUTO_SCALE EVENT ROUTE, for a scale down due to low trafic, is called exactly 50 secondes after a restart.

The "auto_scaling_cycle" value is interpreted 10 times during profile setup.

**Comment by bogdan-iancu** [comment]
See the "delay" value (of 50) from the profile listing in `DBG:core:create_auto_scaling_profile` - to prevent quick ups and downs, the downscaling has a delay factor. This delay kicks in:
* after startup
* after a scale up 
Once the delay is cleared, the
