### ISSUE TITLE
[CRASH] OpenSIPS 3.3 instance as B2B 

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#3107]
**OpenSIPS version you are running**
```
version: opensips 3.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 475050cd6
main.c compiled on 09:05:51 May 30 2023 with gcc 10

```

**Crash Core Dump**
https://pastebin.com/dMNDu3Wc

**Describe the traffic that generated the bug**
After about 30-40 minutes and load of 200 calls opensips crashes

**To Reproduce**
1. Start OpenSIPS --> /usr/local/opensips/sbin/opensips -a Q_MALLOC_DBG -m 4096 -M 2048 
2. Start traffic
3. Check OpenSIPS crashed after some minutes and 100-200 concurrent calls

```
-rw-------  1 root root 6446034944 May 31 10:14 core.opensips.50.sbc2.1685517268
-rw-------  1 root root 6445961216 May 31 10:00 core.opensips.77.sbc2.1685516423
-rw-------  1 root root 6445961216 May 31 10:22 core.opensips.82.sbc2.1685517714
-rw-------  1 root root 6445961216 May 31 11:49 core.opensips.84.sbc2.1685522960
-rw-------  1 root root 6445961216 May 31 11:52 core.opensips.87.sbc2.1685523109
-rw-------  1 root root 6446034944 May 31 09:51 core.opensips.88.sbc2.1685515877
```

**Relevant System Logs**
no logs or errors 

**OS/environment information**
 - Operating System: Debian 11 Docker
 - OpenSIPS installation: git
 - other relevant information:

b2bua configs files will be sent privately.

thank you in advance.

Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

I forgot to send you kernel messages that are appearing on crash:
```
[Thu Jun  1 12:11:56 2023] traps: opensips[650] general protection ip:7fd12203e830 sp:7ffff07fe0b0 error:0 in b2b_entities.so[7fd122030000+3c000]
[Thu Jun  1 12:26:02 2023] opensips[7269]: segfault at 10 ip 00007f8c303581a7 sp 00007ffe8cb79540 error 6 in dialog.so[7f8c30328000+8a000]
```

Thank you in advance
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
Hi, Vasilios!

It looks like you are mixing dialog with b2b_entities dialogs in your script, and this is not supported and most likely lead to crashes. 
So a first approach for you would be to make sure that you don't create dialogs for calls that go through B2B (and the other way around). If you are 100% sure you are not doing this, there might be a "hidden feature" that creates the dialog, or simply some mishandling in the code that creates it itself - we should investigate that, but first, please double check you're not creating dialogs on calls that are handled by B2B.
Secondly, opensips should not crash, in any scenario - I will look into this separately.

**Comment by vtzan** [comment]
Dear @razvancrainea ,

Thank you for your reply. Yes 100% sure that I am not creating dialogs for those calls. just using route_to_carrier(https://opensips.org/html/docs/modules/3.3.x/drouting.html#func_route_to_carrier) to receive gw_attrs_pvar so this is the reason I am loading the dialod module. I have sent config files to @bogdan-iancu.

I still have traces and I can re-enable core dumps if you want to dig further.

thanks alot for your time on this.
Best Regards

Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
@vtzan right, I see that you call `trace` with the `d` flag, which essentially creating the dialog to be traced. You don't really need the dialog module to load the carrier's/gateway's attributes though, not sure why you loaded it.

**Comment by vtzan** [comment]
Dear @razvancrainea, thank you for your time looking the issue.

If you have seen in the script, I am also using load_balancer module just to use dr_match which requires dialog module to be loaded. 

But I can achieve similar functionality using  drouting so yes I have disabled dialog module completely now and see how it goes.

I will close this issue for now. 

Thank you once again for your time on this.
Best Regards

Vasilios Tzanoudakis
