### ISSUE TITLE
[BUG] Memory leak on 3.3 - not enough free shm memory

### ISSUE THREAD

**Issue by syedrizwansrs** [OpenSIPS/opensips#3111]
**OpenSIPS version you are running**

```
version: opensips 3.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 475050cd6
main.c compiled on  with gcc 11
```

**Describe the bug**

Upon deploying OpenSIPS 3.3, we observed a memory leak occurring during the traffic. This leak leads to a gradual depletion of available memory, eventually impacting the system's stability and performance. In contrast, the same setup running OpenSIPS 3.2 exhibits no such memory leak.

**To Reproduce**

Example:
1. Start OpenSIPS
2. Start traffic
3. Keep the traffic running for 30+ Mins
4. The memory start to shoot up.

**Relevant System Logs**

I have attached the relevant logs that capture the memory leak issue, along with any associated error messages or warnings, for your thorough investigation.

Please see the [Logs](https://drive.google.com/file/d/1XmFDvcihIe4m90E9sKPjnlBZ8zjSjGZF/view?usp=sharing) here.

**OS/environment information**
 - Operating System: Ubuntu 22.04.2 LTS
 - OpenSIPS installation: debs

**Comment by bogdan-iancu** [comment]
@syedrizwansrs , the logs shows a lot of memory being allocated by TM related artifacts. But something tells me that the TM is not really so buggy in terms of mem management :). So, I would rather suspect that transactions simply pile up into your opensips. Could you check the [inuse_transactions](https://opensips.org/html/docs/modules/3.3.x/tm.html#stat_inuse_transactions) statistics ? Maybe some async or TCP is blocking the transactions.
