### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xunlujiehuo** [OpenSIPS/opensips#3113]
opensips -v
2.4.7 

```
```

**Describe the bug**
I registered the Cisco 7821 model phone to opensips, and it was successfully registered, but when I used opensipsctl cisco_restar <uri> it returned an error, and opensips did not send the NOTIFY message, which confuses me, I Tried many ways, I think it's a bug。

Here is my registration info 

[root@localhost sbin]# opensipsctl   ul show 
Domain:: location hash_size=16384
    AOR:: 8001@192.168.1.14
        Contact:: sip:48d0dd82-9773-4177-a3ac-5ca42fab5c8b@192.168.1.134:51998;transport=tcp Q=
            ContactID:: 1611866454134993950
            Expires:: 255
            Callid:: 00451d6b-7a0c000f-44daaee2-508faba1@192.168.1.134
            Cseq:: 479
            User-agent:: Cisco-CP7821/10.3.1
            State:: CS_SYNC
            Flags:: 0
            Cflags:: 
            Socket:: tcp:192.168.1.14:5060
            Methods:: 4294967295
            SIP_instance:: <urn:uuid:00000000-0000-0000-0000-00451d6b7a0c>

Here is the command I tried
[root@localhost sbin]# opensipsctl cisco_restart sip:192.168.1.134:51998 
400
[root@localhost sbin]# opensipsctl cisco_restart sip:8001@192.168.1.134:51998 
400
[root@localhost sbin]# opensipsctl cisco_restart sip:8001@192.168.1.14:5060 
400
[root@localhost sbin]# 
[root@localhost sbin]# 
[root@localhost sbin]# opensipsctl cisco_restart sip:192.168.1.14:5060 
400
[root@localhost sbin]# opensipsctl cisco_restart sip:48d0dd82-9773-4177-a3ac-5ca42fab5c8b@192.168.1.134:51998;transport=tcp
400

In the log, I found that the message was not sent out, only the call of the mi_fifo part did not have the core and the call of the tm part, I do not understand what went wrong

this is the log
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <NOTIFY>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <sip:8001@192.168.1.14:5060>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <From: sip:daemon@localhost.localdomain>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <To: <sip:8001@192.168.1.14:5060>>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Event: check-sync>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Contact: <sip:daemon@!!>>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_node: end of input tree
Jun 15 09:22:31 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_fifo_server: done parsing the mi tree
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <NOTIFY>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <sip:192.168.1.14:5060>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <From: sip:daemon@localhost.localdomain>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <To: <sip:192.168.1.14:5060>>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Event: check-sync>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Contact: <sip:daemon@!!>>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_node: end of input tree
Jun 15 09:22:38 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_fifo_server: done parsing the mi tree
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <NOTIFY>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <sip:48d0dd82-9773-4177-a3ac-5ca42fab5c8b@192.168.1.134:51998>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <From: sip:daemon@localhost.localdomain>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <To: <sip:48d0dd82-9773-4177-a3ac-5ca42fab5c8b@192.168.1.134:51998>>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Event: check-sync>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <Contact: <sip:daemon@!!>>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <.>
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_parse_node: end of input tree
Jun 15 09:22:54 localhost /usr/local/sbin/opensips[26258]: DBG:mi_fifo:mi_fifo_server: done parsing the mi tree

I sincerely hope someone can help me out.

**Comment by bogdan-iancu** [comment]
@xunlujiehuo , actually the `t_uac_dlg` returns a `400 Too few or too many arguments`  as it expects 5 to 6 params,  while the `cisco_restart` from opensipsctl is passing the `t_uac_dlg` params in a bogus way.
Shortly, the `cisco_restart` is broken. And 2.4 is obsolete, so not to be fixed (by the way, the opensipsctl tool is also obsolete)
