### ISSUE TITLE
[BUG] incorrect call-id in reply after failed topology_hiding_match()

### ISSUE THREAD

**Issue by ankogan** [OpenSIPS/opensips#3119]
**OpenSIPS version you are running**
```
# opensips -V
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 4096, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**
A reply for the in-dialog request from callee has an incorrect call-id in case of topology_hiding_match() failed. The reply is sent with a decoded call-id.

**To Reproduce**
Script code:
```
if(has_totag() && !topology_hiding_match())
    t_reply(481, "Call/Transaction Does Not Exist");
```
Request:
```
BYE sip:127.0.0.1;did=231.26d28f31 SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5090
From: <sip:11#254733100602??254733100604@127.0.0.1:5090;user=phone>;tag=5047SIPpTag011
To: "18034080837" <sip:18034080837@127.0.0.1:5060;user=phone>;tag=5223SIPpTag001
Call-ID: MYDLGCHHfl1QXGF6EGJ9R0tefXl+Yg--
Cseq: 2 BYE
Content-Length: 0
```
Response:
```
SIP/2.0 481 Call/Transaction Does Not Exist
Via: SIP/2.0/UDP 127.0.0.1:5090
To: "18034080837" <sip:18034080837@127.0.0.1:5060;user=phone>;tag=5223SIPpTag001
From: <sip:11#254733100602??254733100604@127.0.0.1:5090;user=phone>;tag=5047SIPpTag011
Call-ID: 1-5223@127.0.0.1
Cseq: 2 BYE
Content-Length: 0 
```

**Expected behavior**
OpenSIPS should send call-id the same as in request, Call-ID: MYDLGCHHfl1QXGF6EGJ9R0tefXl+Yg--

**OS/environment information**
 - Operating System: Debian 10
 - OpenSIPS installation: manual packages

**Comment by vladpaiu** [comment]
Hello,

Do you have a full SIP trace here ?

I'm curious if the BYE in this case is a re-transmission which gets 'double' handled let's say, and in this case it's OpenSIPS that's generating the 481 because the dialog was already terminate / no longer exists, and thus the wrong callid gets propagated ?

**Comment by ankogan** [comment]
Hello, this is the BYE received after the dialog had already been terminated. 481 was sent by t_reply() from script mentioned above.

**Comment by ankogan** [comment]
Hello, any updates?

**Comment by ankogan** [comment]
Hi, any updates here?

**Comment by ankogan** [comment]
Hi, any updates?

**Comment by ankogan** [comment]
Hi, any updates?

**Comment by ankogan** [comment]
Please reopen
