### ISSUE TITLE
[CRASH] b2b_logic: Ignoring unexpected '=' inside URI header value

### ISSUE THREAD

**Issue by devoxy1** [OpenSIPS/opensips#3124]
Hello!

Opensips crashes when receiving incorrect headers in REFER and trying to compose INVITE from it. I have a call made from asterisk to proxy server via opensips with b2b setup:

asterisk ---> opensips ---> kamailio

Call establishes successfully and then Asterisk sends REFER to transfer the call. It seems opensips doesn't like Refer-To header, throws an error `Ignoring unexpected '=' inside URI header value`, creates new leg from Refer-To and then segfaults. This happens every time.

**OpenSIPS version you are running**

```
version: opensips 3.4.0-rc1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 7f5e08319
main.c compiled on 16:03:54 Jul 10 2023 with gcc 9
```

**Crash Core Dump**
Crash. log and REFER message can be found here: https://file.io/cRhJdcDaz9Vo

**Describe the traffic that generated the bug**
INVITE message with incorrect headers composed from REFER.

**To Reproduce**

1. Start OpenSIPS
2. Make a call
3. Opensips receives REFER to transfer the call with incorrect Refer-To header
4. Opnesips composes new INVITE from Refer-To header 
5. Opensips segfaults

**Relevant System Logs**
 ```
 opensips[119316]: ERROR:core:parse_uri_headers: Ignoring unexpected '=' inside URI header value
```

**OS/environment information**
 - Operating System: Operating System: Ubuntu 20.04.5 LTS
 - OpenSIPS installation: source
 - other relevant information:

**Additional context**
I'm not sure that the Refer-To is incorrect as it works fine with asterisk, for example. It seems that opensips doesn't like parameters in refer-to. Anyways it shouldn't be crashing but just throwing an error.

**Comment by devoxy1** [comment]
Hello @bogdan-iancu!

Sorry for delay, i re-uploaded files, please check here https://file.io/mil72pW360Nw

**Comment by bogdan-iancu** [comment]
@devoxy1 , using gdb, could you do:
```
f 1
p e->key
p key->s
p key->len
```

**Comment by devoxy1** [comment]
@bogdan-iancu,

The old dump seems to be lost, i reproduced the issue and got new dump, hope this works too. Please see details of commands below:

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...
[New LWP 144664]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -w /run/opensips -P /run/opensips/opensips.pid -m 256 -M 256'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd0715fe5ca in b2bl_search_entity (tuple=0x7fd074cc6308, key=0x7fd074dad968, src=1, head=0x7ffec55dded0) at records.c:398
398                                     if (e->key.len == key->len &&
(gdb) f 1
#1  0x00007fd071608ccb in b2b_add_dlginfo (key=0x7ffec55de070, entity_key=0x7fd074dad968, src=1, dlginfo=0x7ffec55de230, param=0x0) at logic.c:165
165             entity = b2bl_search_entity(tuple, entity_key, src, &ent_head);
(gdb) p e->key
No symbol "e" in current context.
(gdb) p key->s
$1 = 0x7fd08560fab8 "2939.0"
(gdb) p key->len
$2 = 6
(gdb) 
```

**Comment by bogdan-iancu** [comment]
right, this new core seems a bit different, so also do :+1: 
```
f 0
p e
p e->key
```

**Comment by devoxy1** [comment]
@bogdan-iancu 

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/opensips...

warning: exec file is newer than core file.
[New LWP 144664]
Core was generated by `/usr/sbin/opensips -w /run/opensips -P /run/opensips/opensips.pid -m 256 -M 256'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd0715fe5ca in ?? ()
(gdb) f 0
#0  0x00007fd0715fe5ca in ?? ()
(gdb) p e
No symbol "e" in current context.
(gdb) p e->key
No symbol "e" in current context.
```

**Comment by devoxy1** [comment]
Up

**Comment by devoxy1** [comment]
Still actual

**Comment by devoxy1** [comment]
Up

**Comment by devoxy1** [comment]
Still actual

**Comment by bogdan-iancu** [comment]
Sorry @devoxy1 for dropping this :( .... What is the latest corefile you have here ? could you re-post the full bracktrace for it to have it as a restarting point ?

**Comment by bogdan-iancu** [comment]
ok, let's do that, closing for now
