### ISSUE TITLE
[BUG] pua_usrloc generated PUBLISHes expire too soon

### ISSUE THREAD

**Issue by wdoekes** [OpenSIPS/opensips#3125]
Hi!

I was looking into adding `pua_usrloc` support, and I noticed the following:
- the pua_set_publish() works
- the save() function does a callback and pua_usrloc creates a PUBLISH with state "open"
- unfortunately, sometimes the PUBLISH gets revoked (expires=0) before it should

This means that a REGISTERed account with 300 sec expiry could be:
- open for 4 minutes
- closed for 30 seconds
- open again, for 4 minutes
- closed for 30 seconds

The culprit is here:
https://github.com/OpenSIPS/opensips/blob/c4c376484cdbefa9eb8da84dfb0a011a07ddb27d/modules/pua/pua.c#L722

There is an expiry check that finds expired records, but considers them expired not after `expiry`, but after `expiry - update_period`.

This means that if I have an `update_period` of 100, a PUBLISH could expire at 201 seconds instead of 300 seconds, leaving the account closed for 99 seconds (or slightly shorter, because a reREGISTER happens a slight bit sooner before the 300 seconds are reached).

This was observed with a slightly patched opensips 1.11, but the source code looks unchanged in this regard.

### Some samples

```
2023-07-10 15:54:30.527324 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH
  PUBLISH sip:account@example.com SIP/2.0
  Via: SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bKcc6b.bb512862.0
  To: sip:account@example.com
  From: <sip:account@example.com>;tag=a462b97e06dee59660cc4c0c71d2f101-d867
  CSeq: 10 PUBLISH
  Call-ID: 371349c34929d242-2545@1.2.3.4
  Max-Forwards: 70
  Content-Length: 329
  Event: presence
  Expires: 91
  Content-Type: application/pidf+xml
  
  <?xml version="1.0"?>
  <presence xmlns="urn:ietf:params:xml:ns:pidf" xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model" xmlns:rpid="urn:ietf:params:xml:ns:pidf:rpid" xmlns:c="urn:ietf:params:xml:ns:pidf:cipid" entity="account@example.com"><tuple id="0x7ffdfafc2370"><status><basic>open</basic></status></tuple></presence>
```
^- initial publish (at REGISTER time)
```
2023-07-10 15:55:58.586209 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH
  PUBLISH sip:account@example.com SIP/2.0
  Via: SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bK95b.d68a78c7.0
  To: sip:account@example.com
  From: <sip:account@example.com>;tag=a462b97e06dee59660cc4c0c71d2f101-7ec0
  CSeq: 10 PUBLISH
  Call-ID: 2e3ffad21e0595eb-26610@1.2.3.4
  Max-Forwards: 70
  Content-Length: 0
  Event: presence
  Expires: 91
  SIP-If-Match: a.1672655999.4522.26883.0
```
^- a refresh, using SIP-If-Match and an expiry of 91 again

```
2023-07-10 15:56:15.083314 1.2.3.4:5060 > 1.2.3.4:5060 10 PUBLISH
  PUBLISH sip:account@example.com SIP/2.0
  Via: SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bK0056.a72b2c87.0
  To: sip:account@example.com
  From: <sip:account@example.com>;tag=a462b97e06dee59660cc4c0c71d2f101-0387
  CSeq: 10 PUBLISH
  Call-ID: 2e3ffad21e0595ed-26835@1.2.3.4
  Max-Forwards: 70
  Content-Length: 0
  Event: presence
  Expires: 0
  SIP-If-Match: a.1672655999.4522.26884.1
```
^- an expiry, using SIP-If-Match. but this is way to soon

A clearer view of the behaviour is seen when looking at the times between these publishes:
```
      0.0      2023-07-10 15:54:30.527324 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 329 <-b- 91
    +88.058885 2023-07-10 15:55:58.586209 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 91
    +16.497105 2023-07-10 15:56:15.083314 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 0
```
`a = content-length` and `b = expires`

At `15:56:15` the timer runs the cleanup (according to `update_period`): in this case there is a record that _should_ expire at `15:57:29` but it gets pruned 74 seconds earlier.

----

As far as I understand, for pua_usrloc, we don't want the subtraction of `update_period` here. If `update_period` is run too seldom, I'd rather have an account be "open" for too long than have it ping-pong between open and closed.

I removed the `- update_period` and then we see this *improved* behaviour:
```
      0.0      2023-07-10 16:07:43.104534 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 329 <-b- 91
    +88.056975 2023-07-10 16:09:11.161509 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 91
    +88.063074 2023-07-10 16:10:39.224583 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 91
    +88.053532 2023-07-10 16:12:07.278115 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 91
(removed network from phone, next publish should be an expiry)
   +106.613514 2023-07-10 16:13:53.891629 1.2.3.4:5060 > 1.2.3.4:5062 10 PUBLISH <-a- 0 <-b- 0
```
Sure, the final expired PUBLISH is now a bit late (18 seconds), but I don't see that as an issue.

----

Thoughts?

Cheers,
Walter Doekes
OSSO B.V.

**Comment by bogdan-iancu** [comment]
Hey @wdoekes , this it yet another victim of the timer inaccuracy - but this time the problem is not in how the timers are implemented in OpenSIPS, but in how the pua module is using the timer support ;).
The timer routine that is registered by the pua module is registered to be triggered each `update_period` interval - so this is the granularity of the check (done by pua). And because this check is not really too often, the expiring is not really   realtime. And to avoid the situation where the presentity expires later than it should (because the timer checked it later), pua prefers to expire the presentities a bit sooner - whatever presentity will expire in the `[now, now+update_period]` interval, will expire now.
The fix you did there will go in the other extreme  - presentities may expires later than intended, later with up to `update_period` time.....
Depending on the pua module on top, some may be advantaged or dis-advantaged by a earlier or later expiring....to there is not right solution in this direction.

What I suggest here is to move the pua expiring timer to 1 second to get a check more closer to realtime...and we can see how to optimize the walking thru the full hash, once every second...

**Comment by wdoekes** [comment]
Hey @bogdan-iancu,
thanks for looking into this.

> Depending on the pua module on top, some may be advantaged or dis-advantaged by a earlier or later expiring....

Yea. That's what I thought too.

Although: the presence server will have its own expiry mechanism, right? I would say/think that expirying the PUBLISH isn't mandatory at all.

Maybe for other servers? But I would assume that the opensips presence server will NOTIFY everyone of the expired Event when the PUBLISH expires. And then it could remove any knowledge of the PUBLISH.

> What I suggest here is to move the pua expiring timer to 1 second to get a check more closer to realtime...and we can see how to optimize the walking thru the full hash, once every second...

For the instance where I'm using it, pua_usrloc would be the only one using pua, so I can just patch it. And I don't have enough traffic on it yet to see whether running the timer every second is harmful.

Maybe a small warning in the docs near update_period is the most appropriate fix until there is a better resolution...

**Comment by bogdan-iancu** [comment]
Hi @wdoekes , indeed, that's a good point, if a PUBLISH with 0 expires is actually necessary or not. As PUBLISHes are time/expiring driven, there should be be no need for a an PUBLISH 0 as time as as the presentity is deleted according to the negotiated `expire` value. A PUBLISH 0 will be required only of the pua module would like to terminate the presentity ahead of the negotiated `expire` value. 
Of course, I will have to doublecheck this with the RFC3903, to be sure we are not breaking anything.

In regards to the timer value, changing it to 1 may have some performance impact as the the timer routine is actually walking thru the full hash checking for expired elements - there is no ordered list to quickly fetch the expired ones (like in TM or Dialog modules).

But a game changer may be if a we can get rid of the PUBLISH 0 and keep a larger timer interval - this will safe a lot of resources.
