### ISSUE TITLE
cgrates_acc.c core dump when 936 calls from same number in 2 minutes hit OpenSIPS

### ISSUE THREAD

**Issue by jonhvoxbox** [OpenSIPS/opensips#3126]
**OpenSIPS version you are running**

```
```

**Crash Core Dump**

**Describe the traffic that generated the bug**

**To Reproduce**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Comment by razvancrainea** [comment]
Please update the ticket with all the information required in the template, and also attach a backtrace.

**Comment by jonhvoxbox** [comment]
Hi @razvancrainea seems to be a copy paste issue. 

Let me try and add in the next comment. All the details there.

**Comment by jonhvoxbox** [comment]
**OpenSIPS version you are running**
version: opensips 3.2.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 40290bc41
main.c compiled on  with gcc 8


**Crash Core Dump**

https://www.dropbox.com/scl/fi/nkht6pwr96lf0chm66a6o/CoreDumpOutput11July2023.txt?rlkey=hd3t4n4xg7adoi265uzrya89p&dl=0



**Describe the traffic that generated the bug**

936 call attempts from 17604625559 to 197099939XX range  from an Ingress Carrier, caused a spike in traffic and for openSIPS to core and failover.
The traffic stopped and returned to normal after a failover via keepalived when the core occurred.




**Relevant System Logs**

Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7781]: SCRIPT: Using Cached Call Recording Setting of 0 and Chanel Limit of 66 for CUST-123456 [1617]
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7781]: SCRIPT: Route: check_channel_usage [1564]
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7781]: SCRIPT: Number of calls from CUST-123456 is 10 [1567]
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7781]: SCRIPT: Channel limit for CUST-123456 is 66 [1568]
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:handle_sigs: child process 7779 exited by a signal 11
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:handle_sigs: core was generated
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7776]: INFO:core:sig_usr: signal 15 received
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7777]: INFO:core:sig_usr: signal 15 received
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 4(7773) [MI Datagram] terminated, still waiting for 56 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 6(7775) [MI FIFO] terminated, still waiting for 55 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 7(7776) [time_keeper] terminated, still waiting for 54 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 8(7777) [timer] terminated, still waiting for 53 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 26(7795) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 52 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 24(7793) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 51 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 25(7794) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 50 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 28(7797) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 49 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 23(7792) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 48 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 45(7814) [TCP receiver] terminated, still waiting for 47 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 21(7790) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 46 more
Jul 11 16:12:56 sgw01 /usr/sbin/opensips[7769]: INFO:core:shutdown_opensips: process 22(7791) [SIP receiver udp:8.8.8.8:5060] terminated, still waiting for 45 more

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation:

**Comment by razvancrainea** [comment]
Thanks! Could you please open the core dump with gdb and run:
```
f 0
p *ctx
p *ctx->sessions
```

**Comment by jonhvoxbox** [comment]
Hi @razvancrainea  is this what you wanted;

Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fc527d9db63 in cgr_dlg_callback (dlg=0x7fc53a96f800, type=32, _params=0x7fc5280b5060 <params>) at cgrates_acc.c:1314
1314
(gdb) f 0
#0  0x00007fc527d9db63 in cgr_dlg_callback (dlg=0x7fc53a96f800, type=32, _params=0x7fc5280b5060 <params>) at cgrates_acc.c:1314
1314
(gdb) p *ctx
$1 = {ref_no = 119, ref_lock = 2, engaged = 0, start_time = 140485066685240, answer_time = 30, duration = 980445555, sessions = 0x3935353532363430, link = {prev = 0x3535322e38373140,
    next = 0x38372e33362e}}
(gdb) p *ctx->sessions
Cannot access memory at address 0x3935353532363430

Thanks

Jon

**Comment by jonhvoxbox** [comment]
hi @razvancrainea  hope you are well? Any update on this issue please?

thanks

Jon

**Comment by razvancrainea** [comment]
Unfortunately not yet, did not get any spare time to look into it. As soon as I get, I will come back with updates.

**Comment by jonhvoxbox** [comment]
Thanks @razvancrainea  just wanted to stop the bot! Appreciate your comments to this point. Jon

**Comment by jonhvoxbox** [comment]
Hi @razvancrainea  any updates here?

Thanks

Jon
