### ISSUE TITLE
[BUG] OpenSIPS does not add header "Route" in automatically generated ACK (in transaction with negative response).

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#3131]
**OpenSIPS version you are running**

```
version: opensips 3.3.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c8182aa92
main.c compiled on  with gcc 11
```

**Describe the bug**

OpenSIPS does not add automatically header "Route" in ACK request in case with reINVITE+491 response transaction.
Case with frames from pcap:
1) **Good initial transaction.** In initial INVITE to callee do not exist headers "Record-Route/Route", it is okay - FRAME 1 in pcap;
2) **Good initial transaction.** Callee responds with 200ok with header- FRAME 9 in pcap:
```
Record-Route: <sip:user11@1.1.1.216:39000;lr>
```
3) **Good initial transaction.** OpenSIPS automatically add header "Route" in ACK to callee, all good - FRAME 12 in pcap:
```
Route: <sip:user11@1.1.1.216:39000;lr>
```
All good here, "Route" added correctly.

4) **Bad seq transaction.** Caller send reINVITE to callee. OpenSIPS automatically add header "Route" in reINVITE - FRAME 14 in pcap:
```
Route: <sip:user11@1.1.1.216:39000;lr>
```
5) **Bad seq transaction.** Callee respond with 491 response, header "Record-Route" exist - FRAME 16 in pcap:
```
Record-Route: <sip:user11@1.1.1.216:39000;lr>
```
6) **Bad seq transaction.** OpenSIPS automatically generate ACK to callee and send it to callee, but "Route" header is missing here - FRAME 17 in pcap:
```
ACK sip:1.1.1.216:39000;transport=UDP SIP/2.0
Via: SIP/2.0/UDP 1.1.1.110:5060;branch=z9hG4bK6f74.e516f787.0;tmid=1
From: "17"<sip:17@internal.voip.sip>;tag=c907674c
Call-ID: qADJ-jrIV5Tm5BpcbfOJZQ..
To: <sip:user1@example.com>;tag=54823SIPpTag011
CSeq: 2 ACK
Max-Forwards: 70
Content-Length: 0
```
As i can understand, we have these sequential of actions:
1) OpenSIPS sends reINVITE to callee with auto-adding Route;
2) OpenSIPS receives negative reply with "Record-Route";
3) OpenSIPS automatically and quickly generates ACK, where "Route" missed and send it to callee and close this transaction between OpenSIPS and callee;
4) OpenSIPS proxy 491 response to caller and process transaction between OpenSIPS and caller.

**To Reproduce**

1) Call from Caller to Callee through OpenSIPS and establish SIP dialog;
2) Send reINVITE from Caller to Callee;
3) Callee asnwer with negative response, where present header "Record-Route";
4) OpenSIPS receive negative response with "Record-Route", next OpenSIPS generate ACK without added "Route" and send it to Callee;
5) After this, OpenSIPS will proxy negative response next to Caller.

**Expected behavior**

OpenSIPS will adding "Route" in automatically generated ACK on negative responses.

**Relevant System Logs**

Debug logs and pcap attached:
[miss_route_final_logs.txt](https://github.com/OpenSIPS/opensips/files/12079523/miss_route_final_logs.txt)
[miss_route_final.zip](https://github.com/OpenSIPS/opensips/files/12079526/miss_route_final.zip)

**OS/environment information**
 - Operating System: Ubuntu 22
 - OpenSIPS installation: source from git
 - other relevant information:

**Additional context**

Thank you!

**Comment by bogdan-iancu** [comment]
As per RFC3261, Route is not required in ACK for negative replies, as ACK'ing the negative replies is a hop-by-hop process, not an end-2-end.

**Comment by kertor** [comment]
Hello @bogdan-iancu , thank you for quick response.
I also check RFC 3261 and i found this in section "17.1.1.3 Construction of the ACK Request":
```
17.1.1.3 Construction of the ACK Request

 This section specifies the construction of ACK requests sent within
   the client transaction.  A UAC core that generates an ACK for 2xx
   MUST instead follow the rules described in Section 13.
...

   If the INVITE request whose response is being acknowledged had Route
   header fields, those header fields MUST appear in the ACK.  This is
   to ensure that the ACK can be routed properly through any downstream
   stateless proxies.
```
So, we have here:
1) reINVITE with Route:
```
INVITE sip:1.1.1.216:39000;transport=UDP SIP/2.0
Route: <sip:user11@1.1.1.216:39000;lr>
...
```
2) But we have ACK without "Route".

In RFC3261 "17.1.1.3 Construction of the ACK Request" we can see, that if INVITE had Route header fields, then ACK **also must contain it.**

If i am wrong, could you please direct me to section, where discribed ACK building on negative responses?
Thank you!

**Comment by kertor** [comment]
Hello @bogdan-iancu !
Yes, it helps. Now i see "Route" header in local generated ACK request (transaction with 491 response).

**Comment by bogdan-iancu** [comment]
OK, thanks for confirmation - I will have to tune that condition to cover this TH + Route case too.

**Comment by nikbyte** [comment]
@bogdan-iancu it's still actual, maybe you have some updates?

**Comment by kertor** [comment]
UP

**Comment by nikbyte** [comment]
Still actual.

**Comment by nikbyte** [comment]
It's still actual. @bogdan-iancu do you have idea how to fix it properly to have it in project code?

**Comment by nikbyte** [comment]
up

**Comment by kertor** [comment]
up

**Comment by nikbyte** [comment]
UP

**Comment by bogdan-iancu** [comment]
Could you revert the previous change and apply (and test) this patch (providing a better fix) please
[opensips_3_4_ACK_Route_fix.patch.txt](https://github.com/OpenSIPS/opensips/files/13602307/opensips_3_4_ACK_Route_fix.patch.txt)
