### ISSUE TITLE
[BUG] ul_dump over JSON-RPC occasionally hangs

### ISSUE THREAD

**Issue by leedm777** [OpenSIPS/opensips#3134]
**OpenSIPS version you are running**

```
$ /usr/local/sbin/opensips -V
version: opensips 3.2.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4ef2e323b
main.c compiled on 19:26:24 May  9 2023 with gcc 8
```

**Describe the bug**

We are using `ul_dump` over JSON-RPC to sync up SIP registration status. Intermittently the response will hang, resulting in a client timeout. The hanging HTTP connection seems to respond as soon as another HTTP request comes in, but by that time the client has timed out and is no longer listening.

I observed a timeout in a packet capture, and saw the following flow:

```mermaid
sequenceDiagram
    participant C1 as Req1
    participant S as OpenSIPS
    participant C2 as Req2
    C1 ->> S: POST {"jsonrpc":"2.0","method":"ul_dump","id":1}
    S ->> C1: 200 OK, no body content
    Note over C1,S: Req1 Times Out
    C2 ->> S: POST {"jsonrpc":"2.0","method":"ul_dump","id":1}
    S ->> C1: body for Req1
    S ->> C2: 200 OK
    S ->> C2: body for Req 2
```

**To Reproduce**

1. Start OpenSIPS
2. Poll `curl -v -s -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"ul_dump\",\"id\":1}" -H 'content-type: application/json' http://localhost:8888/json/ul_dump`

**Expected behavior**

Should respond with body content immediately after the 200 OK response.

**Relevant System Logs**

There are no logs from OpenSIPS during any of these requests.

**OS/environment information**
 - Operating System:  Debian 10
 - OpenSIPS installation:  git
 - other relevant information: There's very little registered on this proxy yet; the `ul_dump` response is less than 5 kbytes.

**Additional context**

Relevant OpenSIPS config:

```
# http stuff 
loadmodule "httpd.so"
loadmodule "mi_html.so"
loadmodule "mi_http.so"
   
modparam("mi_http", "root", "json")
```

**Comment by razvancrainea** [comment]
According to the Debian repository[1] for Debian 10 (buster), you are using libmicrohttpd12 version 0.9.62, which is known to be broken [2]. You need to bump your libmicrohttpd to at least 0.9.72 to get this fixed. If this does not work either, please re-open the ticket with the version you are experiencing issues with.

[1] https://packages.debian.org/buster/libmicrohttpd12
[2] https://opensips.org/docs/modules/3.3.x/httpd.html#dependencies_libs

Best regards,
Răzvan
