### ISSUE TITLE
[BUG] b2b_logic: reINVITE race during transfer not handled correctly

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#3137]
During transfer procedure, if the transferee is initiating a reINVITE while opensips is in the process of media negotiation, the call fails.
Here's a diagram showing the call flow:
```
caller         b2b       transferor    transferee
  |----INVITE-->|             |             |
  |             |---INVITE--->|             |
  |             |<--200-------|             |
  |<---200------|             |             |
  |----ACK----->|             |             |
  |             |---ACK------>|             |
  |             |<--REFER-----|             |
  |             |---202------>|             |
  |             |-----------------INVITE--->|
  |             |<----------------200-------|
  |             |-----------------ACK------>|
  |<-reINVITE---|                           |
  |----200----->|                           |
  |             |---------------reINVITE--->|
  |             |<----------------491-------|
  |<---ACK------|-----------------ACK------>|
  |<---BYE------|                           |
  |----200----->|                           |
  |             |<--------------reINVITE----|
  |             |-----------------400------>|
  |             |<----------------ACK-------|
```
The transfer is initiated via:
`b2b_bridge("caller", "transferee", , "notify,rollback-failed,no-late-sdp");`

The second reINVIE (from opensips to transferee) is rejected by transferee with 491 Request Pending.
Opensips should not drop the call on the caller side and should accept the reINVITE from the transferee.
This issue is present in the latest stable (3.4).
Also, we need to take in consideration the following race: reINVITE from transferee receoved before 200 OK from caller:
```
caller         b2b       transferor    transferee
  |----INVITE-->|             |             |
  |             |---INVITE--->|             |
  |             |<--200-------|             |
  |<---200------|             |             |
  |----ACK----->|             |             |
  |             |---ACK------>|             |
  |             |<--REFER-----|             |
  |             |---202------>|             |
  |             |-----------------INVITE--->|
  |             |<----------------200-------|
  |             |-----------------ACK------>|
  |<-reINVITE---|                           |
  |             |<--------------reINVITE----|
  |----200----->|                           |
  |<---ACK------|-----------------200------>|
  |             |-----------------ACK------>|
```

**Comment by bogdan-iancu** [comment]
Hi @ovidiusas , maybe is just Friday, but I don't understand what's the race. From the transferee perspective, as a result of the REFER, he gets an initial INVITE (looking at the first diagram). This transaction is completed (there is a 200 OK and ACK for it). So, why the 491 for the first re-INVITE the transferee receives? (as there is no ongoing transaction on his side at the very moment)....

**Comment by ovidiusas** [comment]
For simplicity, I didn't intermix the signalling between the b2b/opensips and transferee.
There is a collision between the first reINVITE from b2b and the first reINVITE from transferee. The transferee is receiving the the reINVITE from b2b after it initiated it's own reINVITE.

Here's a more accurate diagram:
```
caller         b2b       transferor    transferee
  |             |---------------reINVITE--->|
  |             |<--------------reINVITE----|
  |             |<----------------491-------|
  |             |-----------------400------>|
  |<---ACK------|-----------------ACK------>|
  |<---BYE------|                           |
  |----200----->|                           |
  |             |<----------------ACK-------|
```
The order of the reINVITE from transferee and 491 is arbitrary.

**Comment by ovidiusas** [comment]
Same issue for bridging with hold.

**Comment by bogdan-iancu** [comment]
@ovidiusas, please send me off-ticket a pcap showing the issue - it will be much simpler to understand
