### ISSUE TITLE
[master] db_text crash on shutdown (in mem debug mode)

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#314]
Replication method: dialog ("pPB", db_mode=1) with db_text backend. Create an ongoing call, gracefully shutdown OpenSIPS (killall opensips), and db_text should crash with:

Aug 26 17:31:47 [31079] CRITICAL:core:qm_free: freeing already freed pointer, first free: dbt_tb.c: dbt_table_free(263) - abortingAug 26 17:31:47 [31079] CRITICAL:core:qm_free: freeing already freed pointer, first free: dbt_tb.c: dbt_table_free(263) - aborting

#0  0x00002aca0d54a425 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00002aca0d54db8b in __GI_abort () at abort.c:91
#2  0x000000000051a67b in qm_free (qm=<optimized out>, p=0x2aca128f6460, file=<optimized out>, func=<optimized out>, line=<optimized out>) at mem/q_malloc.c:460
#3  0x00002aca10c3cea4 in dbt_table_free (_dtp=0x2aca128f6390) at dbt_tb.c:248
#4  0x00002aca10c355b4 in dbt_db_del_table (_dc=0x2aca128f10f0, _s=0x2aca0f275a30, sync=0) at dbt_lib.c:251
#5  0x00002aca10c364d3 in dbt_db_get_table (_dc=0x2aca128f10f0, _s=0x2aca0f275a30) at dbt_lib.c:297
#6  0x00002aca10c30d08 in dbt_update (_h=0x2aca0db3f9e0, _k=0x7fff8be411c0, _o=0x0, _v=0x7fff8be40e80, _uk=<optimized out>, _uv=0x7fff8be41060, _n=1, _un=11) at dbt_base.c:481
#7  0x00002aca0f020c87 in dialog_update_db (ticks=<optimized out>, param=<optimized out>) at dlg_db_handler.c:1430
#8  0x00002aca0f00e38c in mod_destroy () at dialog.c:951
#9  0x00000000004c20ba in destroy_modules () at sr_module.c:378
#10 0x000000000043fb5a in cleanup (show_status=1) at main.c:394
#11 0x0000000000440594 in handle_sigs () at main.c:522
#12 0x0000000000417e9e in main_loop () at main.c:1081
#13 main (argc=<optimized out>, argv=<optimized out>) at main.c:1615

**Comment by ionutrazvanionita** [comment]
38522f1b0f09fab72379557c5dbdf9be9bb7c118
