### ISSUE TITLE
[CRASH] opensips 3.3 crashes periodically on route_params_release()

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#3141]
Hello,

I'm expecting periodical crashes on latest-latest for this moment opensips 3.3.

```
#0  route_params_release (params_no=2, params=0x0) at action.c:518
        p = <optimized out>
#1  do_action (a=a@entry=0x7f56c0d95030, msg=msg@entry=0x7f56c1006c80) at action.c:798
```

```
(gdb) f 1
#1  do_action (a=a@entry=0x7f56c0d95030, msg=msg@entry=0x7f56c1006c80) at action.c:798
798	in action.c
(gdb) p params
$6 = (pv_value_t *) 0x0
(gdb) p params_no
$7 = 2
```

OS: ubuntu22

Please help to understand how better to debug this.

**Comment by razvancrainea** [comment]
@nikbyte is it always crashing in the very same point?

**Comment by nikbyte** [comment]
@razvancrainea it's always the same. but I found today that it's related to out of pkmemory situation and maybe not so critical... however it shouldn't crash even in case of out of memory.

**Comment by razvancrainea** [comment]
@nikbyte you're absolutely right, it should not crash, even in case of out of memory. But is there a general pkg memory problem, or it happens only in one spot, i.e. when the params are allocated?
