### ISSUE TITLE
[BUG] Unable to enable secure renegotiation option in WolfSSL from OpenSIPs 3.2.2

### ISSUE THREAD

**Issue by Ravi140185** [OpenSIPS/opensips#3143]
We are getting issue with OpenSIPs using TLS library “WolfSSL” when clients using OpenSSL 3.0.  we are getting Pre TLS handshake Errors . Please check and let us know  what can be done to resolve this issue.

ERROR:tls_wolfssl:_wolfssl_tls_accept: New TLS connection [0x7f1276c51740] from 202.65.142.206:51053 failed to accept
ERROR:tls_wolfssl:_wolfssl_tls_accept: TLS accept error: -313, received alert fatal error , connection [0x7f1276c51740]
ERROR:proto_tls:tls_read_req: failed to do pre-tls handshake!
INFO:core:tcp_trigger_report: Connection [0x7f1276c51740] is getting release because of [Read error]

To address above issue we are trying to enable “secure-renegotiation” from WolfSSL end   but when we enable this , we are getting following error from WolfSSL library 

error "WRITE DUP and SECURE RENEGOTIATION cannot both be on"

so we disabled “WRITE DUP” and enabled “SECURE RENEGOTIATION” , and compilation is getting succeeded but  OpenSIPs unable to load  WolfSSL module as it is using “WRITE DUP” functions in WolfSSL module .

ERROR:core:sr_load_module: could not open module  tls_wolfssl.so: undefined symbol: wolfSSL_write_dup
ERROR:core:load_module: failed to load module

Software versions used :

OpenSIPs : 3.2.2
Embedded WolfSSL: 4.7.1

**Comment by Ravi140185** [comment]
Still we didn't got any update on the issue reported. Waiting on it.

**Comment by razvancrainea** [comment]
when you say `so we disabled “WRITE DUP” and enabled “SECURE RENEGOTIATION”`, you mean you changed the wolfssl library compile flags? Because, of course, that's not enough, OpenSIPS code still needs to be adapted.
But I believe this is not a bug, but rather a missing functionality, or am I missing something?

**Comment by Ravi140185** [comment]
Yes, we changed Wolfssl library compile flags because current version of WolfSSL 4.7.1 in 3.2.2 Opensips is not supporting OpenSSL 3.0 client.

We finally upgraded our OpenSIPs to 3.2.13 which has WolfSSL  5.4.0 . With this upgrade our issue resolved. OpenSSL 3.0 clients are able to connect to OpenSIPs properly on TLS.

**Comment by razvancrainea** [comment]
Perfect, so I guess we are cool to close this one. Thanks for updating us!
