### ISSUE TITLE
[BUG] autoscaling: newly started processes don't inherit log_level

### ISSUE THREAD

**Issue by ankogan** [OpenSIPS/opensips#3146]
**OpenSIPS version you are running**
```
version: opensips 3.2.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 4096, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**
Processes started by autoscaling use log_level from the config. It'is much better to inherit the level set by `opensips-cli -x -- mi log_level X` command.
It's important for debuging calls on a high load - when I enable debug, the load increases and autoscaling starts processes without log_level=4, and it's annoying to do `opensips-cli -x -- mi log_level 4` command several times until the number of processes become stable.

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `manual packages`

**Comment by bogdan-iancu** [comment]
@ankogan please see the above commit, give it a try and confirm the fix. Once I have the confirmation, I will do the backporting.

**Comment by ankogan** [comment]
> @ankogan please see the above commit, give it a try and confirm the fix. Once I have the confirmation, I will do the backporting.

I confirm it works for me. I tested it on my own 3.2.9 build
