### ISSUE TITLE
ERROR:tls_mgm:load_tls_library: No TLS library module loaded

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3150]
**OpenSIPS version you are running**

```
version: opensips 3.5.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9376d60c7
main.c compiled on 06:47:18 Aug 11 2023 with gcc 11
```

**Describe the bug**
**while running systemctl status opensips the following error occurs:**
```
ERROR:tls_mgm:load_tls_library: No TLS library module loaded
Aug 14 09:05:15 ip-172-31-34-24 /sbin/opensips[89067]: ERROR:core:init_mod: failed to initialize module tls_mgm
Aug 14 09:05:15 ip-172-31-34-24 /sbin/opensips[89067]: ERROR:core:main: failed to initialize modules!
```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Ubuntu22
 - source
 -

**Additional context**

**Comment by bogdan-iancu** [comment]
@prathibhacdac , for questions or usage issues you may have with OpenSIPS, it is highly recommended to use the [user's](http://lists.opensips.org/cgi-bin/mailman/listinfo/users) mailing list. The tracker here is 100% for coding related work.

**Comment by bogdan-iancu** [comment]
anyhow, the logs are quick self explanatory :
```
ERROR:tls_mgm:load_tls_library: No TLS library module loaded
```
if you would have read the documentation on the tls_mgm module
https://opensips.org/html/docs/modules/3.4.x/tls_mgm.html#idp5522064

**Comment by prathibhacdac** [comment]
I've loaded the module in /lib64/opensips/modules. Still getting the above error.

**Comment by razvancrainea** [comment]
As @bogdan-iancu said, you don't need just to load the module, but also read the documentation.
