### ISSUE TITLE
[BUG] : db_perlvdb.so not loading in ubuntu 22.04 

### ISSUE THREAD

**Issue by varghesepaul** [OpenSIPS/opensips#3152]
**OpenSIPS version you are running**

```
 opensips -V
version: opensips 3.1.16 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b75cefb25
```

cat /etc/issue
Ubuntu 22.04.2 LTS \n \l

**Describe the bug**
Aug 14 18:06:16 [33] ERROR:core:sr_load_module: could not open module </usr/lib/x86_64-linux-gnu/opensips/modules/db_perlvdb.so>: /usr/lib/x86_64-linux-gnu/opensips/modules/db_perlvdb.so: undefined symbol: valdata
Aug 14 18:06:16 [33] ERROR:core:load_module: failed to load module
Aug 14 18:06:16 [33] Traceback (last included file at the bottom):

db_perlvdb.so undefined symbol valdata. We are seeing this issue while upgrading our OS to ubuntu. The issue not showed in debian10. Surprisingly the valdata function is not linked to db_pervdb.so in debain.

In debain:10,

grep valdata db_perlvdb.so ( not matching any function name) 

In ubuntu:22.04 

grep valdata db_perlvdb.so
grep: db_perlvdb.so: binary file matches

Can you please help us to resolve the issue?

**Comment by varghesepaul** [comment]
Tried with opensips 3.2.13 as well and facing the same issue.

 opensips -V
version: opensips 3.2.13 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 737311796

Aug 14 18:33:48 [35] ERROR:core:sr_load_module: could not open module </usr/lib/x86_64-linux-gnu/opensips/modules/db_perlvdb.so>: /usr/lib/x86_64-linux-gnu/opensips/modules/db_perlvdb.so: undefined symbol: valdata
Aug 14 18:33:48 [35] ERROR:core:load_module: failed to load module

**Comment by razvancrainea** [comment]
Did you install OpenSIPS from the official [apt repo](apt.opensips.org), or you compiled it by yourself?
