### ISSUE TITLE
[CRASH] v3.3 as B2BUA - core:qm_free_dbg: freeing already freed pointer ... aborting

### ISSUE THREAD

**Issue by vtzan** [OpenSIPS/opensips#3155]
**OpenSIPS version you are running**
```
version: opensips 3.3.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 0e04fc214
main.c compiled on 19:06:42 Aug 11 2023 with gcc 10
```

**Crash Core Dump**
https://pastebin.com/Qp34FX3T

**Describe the traffic that generated the bug**

After making 4-5 calls then opensips after some secs will crash.

**To Reproduce**
1. Start OpenSIPS as b2bua. 
2. make 4-5 calls 
3. Check OpenSIPS crashed

**Relevant System Logs**
`CRITICAL:core:qm_free_dbg: freeing already freed pointer, first free: parser/msg_parser.c: free_sip_msg(856) - aborting
`

**OS/environment information**
 - Operating System: Debian 11.7
 - OpenSIPS installation: git

Config can be shared privately if needed.

Thank you in advance
Vasilios Tzanoudakis

**Comment by vtzan** [comment]
Dear Team,

I looked a little bit at it this issue and it seems `set_global_address` causing it. ( this instance in on AWS )

I searched the code and found that `set_global_address` was freed in many places 

```
modules/tm/sip_msg.h:39:                                shm_free_bulk((_msg)->set_global_address.s);\
modules/tm/sip_msg.h:70:                                shm_free((_msg)->set_global_address.s);\
modules/tm/t_msgbuilder.h:350:          pkg_free(faked_req->set_global_address.s);
modules/tm/t_msgbuilder.h:380:          pkg_free(faked_req->set_global_address.s);
parser/msg_parser.c:856:                pkg_free(msg->set_global_address.s); 
```

so I took the change and removed the last one for the `parser/msg_parser.c` using this patch :

```
--- msg_parser.c        2023-08-16 13:00:11.425935329 +0300
+++ msg_parserPatched.c 2023-08-16 13:14:49.596795033 +0300
@@ -852,8 +852,6 @@
                msg_callback_process(msg, MSG_DESTROY, NULL);
        if (msg->new_uri.s)
                pkg_free(msg->new_uri.s);
-       if (msg->set_global_address.s)
-               pkg_free(msg->set_global_address.s);
        if (msg->set_global_port.s)
                pkg_free(msg->set_global_port.s);
        if (msg->dst_uri.s)
```

I made some calls and opensips didn't crash but I not so sure that this is the right fix here.

Thank you in advance for your support.
Vasilios Tzanoudakis

**Comment by razvancrainea** [comment]
@vtzan removing those lines will very likely result in a pkg leak, so I am pretty sure this is not the right way :)
Are you using the `set_advertised_address` function in your config? Because that's the only way that variable can be populated.

**Comment by vtzan** [comment]
> @vtzan removing those lines will very likely result in a pkg leak, so I am pretty sure this is not the right way :)
> Are you using the `set_advertised_address` function in your config? Because that's the only way that variable can be populated.

Yes I use set_advertised_address

Thanks

**Comment by vtzan** [comment]
bug still exists. thanks

**Comment by vtzan** [comment]
After adding another socket listener on the b2bua instance for internal routing :

```
socket=udp:PRIVATE_IP:65071 as PRIVATE_IP:65071 <-- for internal  routing inside the same box
socket=udp:PRIVATE_IP:SIP_BIND_PORT as ADVERTISED_IP_ADDRESS <-- for external routing
```

and using  [force_send_socket](https://www.opensips.org/Documentation/Script-CoreFunctions-3-3#toc16) my problem was solved.

I will let the admins to decide to close this issue or not.

Thank you
Vasilios Tzanoudakis

**Comment by bogdan-iancu** [comment]
@vtzan , the `free` your removed is actually the only 100% legitimate one :). Are you still able to reproduce the crash? we could explore the other 3 cases where that field is freed.

**Comment by vtzan** [comment]
Hi @bogdan-iancu, 

After using force_socket option I didn't had any more crashes but after some millions of production calls b2bua instance was up but I  remeber correctly a part of the script was stopped working correctly and didn't return correct data from db I think that was : `do_routing(0,,,$var(rule_attr),$var(vendor_gw))` and didn't return correct results but I am not sure now.

I don't remember well but this was only on production traffic that happenned. On my sipp performance tests I was able to push more that 500k calls without issue (maybe the issue was triggering different prefixes on dynamic rule matching but our sipp was only testing 1 prefix.

So I just stayed with opensips as proxy facing the carrier and kept only that and runs solid for ~1 month now. Sorry but I don't have match information because when the issue happened we rolled back to the old system and then I changed opensips config on proxy mode immediatelly so that I can have latest OpenSIPS version up and running.

**Comment by vtzan** [comment]
Hi @bogdan-iancu,

Thank you for your time on this. In proxy mode I only use those 2 lines
```
socket=udp:PRIVATE_IP:SIP_BIND_PORT as ADVERTISED_IP_ADDRESS:SIP_BIND_PORT
socket=udp:PRIVATE_IP:SIP_BIND_PORT_IN as ADVERTISED_IP_ADDRESS:SIP_BIND_PORT_IN
```
Thanks
