### ISSUE TITLE
fm_malloc: not enough free shm memory, please increase the "-m" command line parameter! - Urgent: memory leak in  OPS 3.3

### ISSUE THREAD

**Issue by plsappino** [OpenSIPS/opensips#3159]
Issue:   Aug 20 20:13:57 /usr/sbin/opensips[26459]: WARNING:core:fm_malloc: not enough contiguous free shm memory (526879408 bytes left, need 65592), attempting defragmentation... please increase the "-m" command line parameter!
Aug 20 20:13:57  /usr/sbin/opensips[26459]: ERROR:core:fm_malloc: not enough free shm memory (526879408 bytes left, need 65592), please increase the "-m" command line parameter!

**OpenSIPS version you are running**
version: opensips 3.3.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9240b7aea
main.c compiled on 23:19:38 Aug 15 2023 with gcc 10

Machine: AMZ EC2: Debian 11.  3.75 GB RAM, 50 GB storage

Opensips config:
"S_MEM": "512",
"P_MEM": "24",
"OPEN_FILES_LIMIT": "200000",

We have been using opensips version 2.4 and recently moved to version 3.3. 
We have tried different combinations of s_mem, p_mem & open files but we still keep getting the same memory error without even running any calls through it.  It is a brand new server spun at AWS.  The error is not meaningful because it says there is more memory available than that is needed.  526879408 bytes left, need 65592

We have read these links but didn't solve the issue:
https://www.opensips.org/Documentation/Development-Manual-MM-3-3
https://blog.opensips.org/2019/03/21/containing-memory-related-issues-in-an-easy-way-with-opensips-3-0/
https://www.mail-archive.com/users@lists.opensips.org/msg40440.html 
https://www.opensips.org/Documentation/TroubleShooting-OutOfMem

I would appreciate some guidance as to what should be the s_mem, p_mem & openfileslimit for correct functioning of version 3.3

**Comment by bogdan-iancu** [comment]
As per https://www.opensips.org/Documentation/TroubleShooting-OutOfMem , have you extracted a memory dump to show the leak?

**Comment by plsappino** [comment]
[opensips.log](https://github.com/OpenSIPS/opensips/files/12553414/opensips.log)
Memory dump attached.

**systemctl status opensips**
● opensips.service - OpenSIPS is a very fast and flexible SIP (RFC3261) server
     Loaded: loaded (/lib/systemd/system/opensips.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-09-07 20:58:24 UTC; 17min ago
       Docs: man:opensips
    Process: 1970 ExecStart=/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m $S_MEMORY -M $P_MEMORY $OPTIONS (code=exited, status=0/SUCCESS)
   Main PID: 1972 (opensips)
      Tasks: 30 (limit: 2350)
     Memory: 313.3M
        CPU: 5.061s
     CGroup: /system.slice/opensips.service
             ├─1972 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1973 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1974 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1975 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1976 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1977 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1978 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1979 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1980 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1981 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1982 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1983 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1984 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1985 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1986 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1987 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1988 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1989 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1990 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1991 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1992 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1993 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1994 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1995 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1996 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1997 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1998 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─1999 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             ├─2000 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG
             └─2001 /usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg -m 512 -M 32 -a Q_MALLOC_DBG

**Comment by plsappino** [comment]
close

**Comment by bogdan-iancu** [comment]
@plsappino, have you sorted out ? good to close ?
