### ISSUE TITLE
[EROOR] failed to accept connection(24): Too many open files

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3161]
**OpenSIPS version you are running**

```
version: opensips 3.5.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9376d60c7
main.c compiled on 06:47:18 Aug 11 2023 with gcc 11
```

**Describe the bug**

while starting opensips using the command: systemctl start opensips and checking the status using systemctl status opensips throws the following errors:

ERROR:core:handle_new_connect: failed to accept connection(24): Too many open files
CRITICAL:core:sig_usr: segfault in attendant (starter) process!

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment]
Please provide the [CoreDump](https://www.opensips.org/Documentation/TroubleShooting-Crash) of the crashed process.
