### ISSUE TITLE
[BUG]core:yyerror: parse error in //etc/opensips/opensips.cfg:182:12-14: syntax error

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3163]
**OpenSIPS version you are running**

```
opensips-3.5
```

**Describe the bug**

```
:core:yyerror: parse error in //etc/opensips/opensips.cfg:182:12-14: syntax error
Aug 22 04:27:42 [220811] CRITICAL:
Aug 22 04:27:42 [220811] CRITICAL:      # check if the clients are using WebSockets or WebSocketSecure
Aug 22 04:27:42 [220811] CRITICAL:      if (proto == WS || proto == WSS)
Aug 22 04:27:42 [220811] CRITICAL:      ^~~

```
**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by prathibhacdac** [comment]
Waiting for the support.

**Comment by prathibhacdac** [comment]
bare word <proto> found, command calls need '()'

**Comment by prathibhacdac** [comment]
Aug 31 04:14:49 [339966] CRITICAL:Traceback (last included file at the bottom):
Aug 31 04:14:49 [339966] CRITICAL: 0. //etc/opensips/opensips.cfg
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:12-14: syntax error
Aug 31 04:14:49 [339966] CRITICAL:
Aug 31 04:14:49 [339966] CRITICAL:      # check if the clients are using WebSockets or WebSocketSecure
Aug 31 04:14:49 [339966] CRITICAL:      if (proto == "WS" || proto == "WSS")
Aug 31 04:14:49 [339966] CRITICAL:      ^~~
Aug 31 04:14:49 [339966] CRITICAL:              setflag(SRC_WS);
Aug 31 04:14:49 [339966] CRITICAL:
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:12-14: bare word <proto> found, command calls need '()'
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:12-14: bad command!)
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:16-17: bad command!)
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:18-20: bad command!)
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:27-29: bare word <proto> found, command calls need '()'
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:27-29: bad command: missing ';'?
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:31-32: bad command!)
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:183:32-33: bad command!)
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:184:17-18: bad arguments for command <setflag>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:193:17-23: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:193:23-24: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:194:13-19: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:194:19-20: bad arguments for command <setbflag>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:239:16-22: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:239:22-23: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:239:38-44: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:239:44-45: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:241:21-27: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:241:27-28: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:241:44-50: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:241:50-51: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:243:22-28: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:243:28-29: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:243:44-50: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:243:50-51: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:245:22-28: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:245:28-29: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:245:45-51: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:245:51-52: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:257:16-22: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:257:22-23: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:257:38-44: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:257:44-45: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:259:21-27: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:259:27-28: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:259:44-50: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:259:50-51: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:261:22-28: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:261:28-29: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:261:44-50: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:261:50-51: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:263:22-28: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:263:28-29: bad arguments for command <isflagset>
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:263:45-51: syntax error
Aug 31 04:14:49 [339966] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:263:51-52: bad arguments for command <isbflagset>
Aug 31 04:14:49 [339966] ERROR:core:parse_opensips_cfg: bad config file (46 errors)
Aug 31 04:14:49 [339966] ERROR:core:main: failed to parse config file (null)
Aug 31 04:14:49 [339966] NOTICE:core:main: Exiting....

**Comment by razvancrainea** [comment]
Please check the migration documentation - the `proto` variable has been [dropped](https://www.opensips.org/Documentation/Migration-3-2-0-to-3-3-0#toc4) in OpenSIPS 3.2.

Please do not open any bug reports any more if you are not 100% it is a bug in OpenSIPS and not something you are missing: if you need help, please ask for it in the [OpenSIPS Users mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

**Comment by prathibhacdac** [comment]
I asked in the users mailing list but not received any reply,

**Comment by prathibhacdac** [comment]
> Please check the migration documentation - the `proto` variable has been [dropped](https://www.opensips.org/Documentation/Migration-3-2-0-to-3-3-0#toc4) in OpenSIPS 3.2.

This is not updated in the documentation
