### ISSUE TITLE
[BUG] b2b_logic custom_headers do not work for provisional SIP responses

### ISSUE THREAD

**Issue by Farid-19** [OpenSIPS/opensips#3173]
**OpenSIPS version you are running**

```
version: opensips 3.4.0-rc1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: c64766a85
main.c compiled on  with gcc 10
```

**Describe the bug**

We use B2B to create a dialog between the caller and the callee. See code sample below: 
```
modparam("b2b_entities", "script_req_route", "b2b_request")
modparam("b2b_entities", "script_reply_route", "b2b_reply")
modparam("b2b_logic", "script_req_route", "b2b_logic_request")
modparam("b2b_logic", "script_reply_route", "b2b_logic_reply")
modparam("b2b_logic", "b2bl_from_spec_param", "$var(b2b_from)")
modparam("b2b_logic", "custom_headers", "X-TEST")

route {
        b2b_server_new("caller");
        b2b_client_new("callee");
        b2b_init_request("test_dialog");
}

route[b2b_request] {
    xlog("L_INFO", "[B2B-REQUEST:$ci] [$rm] > from entity: $b2b_logic.entity(id)\n");
    if ($b2b_logic.entity(id) == "callee") {
        append_hf("X-TEST: $ci\r\n");
    }
}

route[b2b_reply] {
    xlog("L_INFO", "[B2B-REPLY:$ci] [$rs $rm] > from entity: $b2b_logic.entity(id)\n");
    
    if ($b2b_logic.entity(id) == "callee") {
        append_hf("X-TEST: $ci\r\n");
    }
}

route[b2b_logic_request] {
    xlog("L_INFO", "[B2B-LOGIC-REQUEST:$ci] [$rm] > from entity: $b2b_logic.entity(id)\n");
    b2b_pass_request();
}

route[b2b_logic_reply] {
    xlog("L_INFO", "[B2B-LOGIC-REPLY:$ci] [$rs $rm] > received reply from entity: $b2b_logic.entity(id)\n");
    
    if ($b2b_logic.entity(id) == "callee") {
        append_hf("X-TEST: $ci\r\n");
    }
    
    b2b_handle_reply();
}
```

In the reply routes, we try to append a custom header to the response back to the caller using `append_hf()`. However this doesn't seem to work for calls when the callee responds with a provisional response first, for example with **183 Session In Progress** or **180 Ringing**. If the callee responds directly with a 200 OK instead of provisional response, then it works.

Are we missing something in our code? Or is this a bug within b2b dialogs? If you need more additional information, please let me know.

**Expected behavior**

The custom header defined in ``modparam("b2b_logic", "custom_headers", "X-TEST") should be included in provisional SIP responses.

**OS/environment information**
 - Operating System:  `Debian 11 Bullseye`
 - OpenSIPS installation:  `debs`
 - other relevant information:

**Additional context**

We need to append a custom header so we can use `Heplify` to combine the callee leg in 1 SIP Trace.

**Comment by Farid-19** [comment]
any updates?

**Comment by Farid-19** [comment]
Hi @bogdan-iancu ,

Thanks for your reply and the explanation. Now that part is clear, how can we make sure that we can append extra headers before we call `b2b_handle_reply()`? Or does this not work as we thought?

**Comment by bogdan-iancu** [comment]
Unfortunately there is no mechanism right now to add custom hdrs to the replies.
