### ISSUE TITLE
Cannot fix read connection

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3184]
**OpenSIPS version you are running**

```
version: opensips 3.3.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 98a8b0344
main.c compiled on 05:33:36 Sep  3 2023 with gcc 11
```

**Crash Core Dump**

**Relevant System Logs**

```
ERROR:tls_openssl:openssl_tls_accept: New TLS connection from 14.139.183.221:59966 failed to accept
Sep 11 10:02:51 ip-172-31-34-24 /usr/sbin/opensips[287604]: ERROR:tls_openssl:tls_print_errstack: TLS errstack: error:0A0000BF:SSL routines::no protocols available
Sep 11 10:02:51 ip-172-31-34-24 /usr/sbin/opensips[287604]: ERROR:proto_wss:wss_read_req: cannot fix read connection
```

**Comment by prathibhacdac** [comment]
when using openssl instead of wolfssl, I get the following error:

ERROR:tls_openssl:openssl_tls_accept: New TLS connection from 14.139.183.221:49567 failed to accept
Sep 11 11:43:53 ip-172-31-34-24 /usr/sbin/opensips[289468]: ERROR:tls_openssl:tls_print_errstack: TLS errstack: error:0A000416:SSL routines::sslv3 alert certificate unknown
Sep 11 11:43:53 ip-172-31-34-24 /usr/sbin/opensips[289468]: ERROR:proto_wss:wss_read_req: cannot fix read connection

**Comment by razvancrainea** [comment]
Not an OpenSIPS issue - the error points clearly that there is a problem with the certificate, it is unknown.

**Comment by prathibhacdac** [comment]
I've used the lets encrypt certificate. Then also I'm getting the certificate related issues.
