### ISSUE TITLE
Not getting audio and video

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3186]
**OpenSIPS version you are running**

```
3.3
```

**Describe the bug**

```
Not getting audio and video of the remote peer.
```

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by prathibhacdac** [comment]
In internal network, audio and video are working. But when one client is behind symmetric NAT and another client is in external network, there is no audio and video. I'm using opensips with rtpproxy.

**Comment by prathibhacdac** [comment]
Error in opensips log:

ERROR:rtpproxy:rtpproxy_offer_answer: no available proxies

**Comment by prathibhacdac** [comment]
After about 30 seconds the call gets disconnect both in internal n/w and external n/w.

**Comment by prathibhacdac** [comment]
Can someone help me resolve this issue?

**Comment by prathibhacdac** [comment]
The sample configuration file in https://www.opensips.org/Documentation/Tutorials-WebSocket-3-3 is not working.

**Comment by razvancrainea** [comment]
There is no documentation showing a bug in OpenSIPS, hence I am closing this ticket.

Please open a ticket only when you are sure there is a bug in OpenSIPS and you can point exactly where OpenSIPS misbehaves. If you can't do that, please address on the mailing list.

**Comment by AlijiEmmanuel-dev** [comment]
Have you installed RTP proxy on the server. I suggest you use RTPEnging instead of RTP Proxy. 
Past your opensips.cfg file here lets take a look.

**Comment by prathibhacdac** [comment]
i am using rtpengine.
[opensips.cfg.rtpengine.txt](https://github.com/OpenSIPS/opensips/files/12708250/opensips.cfg.rtpengine.txt)

**Comment by prathibhacdac** [comment]
Websocket connection is not getting established.

**Comment by prathibhacdac** [comment]
when I use require_cert and verify cert 1, web socket connection is not getting established. If i use require cert 0 and verify cert 0, there is no audio/video.

**Comment by prathibhacdac** [comment]
@AlijiEmmanuel-dev Any updates?

**Comment by prathibhacdac** [comment]
The above error is resolved by downgrading libssl package to [libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb](http://us.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb)

Steps tor resolve the issue:

wget http://us.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.20_amd64.deb
sudo rm /usr/lib/x86_64-linux-gnu/libssl.so.3
sudo ldconfig

Now I'm getting the following error:

ERROR:nathelper:fix_nated_contact_f: SCRIPT BUG - second attempt to change URI Contact
 /usr/sbin/opensips[79297]: DBG:auth:build_auth_hf: 'WWW-Authenticate: Digest realm="3.109.60.109", nonce="JpRJrzqUB4SoHGTMGHf9MrxnPJsn6kp7ERa0MuERRhMA", qop="auth"#015#012'
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_write: TLS connection to 14.139.183.221:64352 write failed (5:-1:9)
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_write: TLS write error:
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_blocking_write: TLS failed to send data
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_write: TLS connection to 14.139.183.221:64353 write failed (5:-1:9)
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_write: TLS write error:
/usr/sbin/opensips[79292]: ERROR:tls_openssl:openssl_tls_blocking_write: TLS failed to send data
