### ISSUE TITLE
[BUG/FEATURE?] Missing or wrong Branch information in local triggered error routes

### ISSUE THREAD

**Issue by thuroc** [OpenSIPS/opensips#3188]
**OpenSIPS version you are running**
```
version: opensips 3.4.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 28e74a456
main.c compiled on 08:58:53 Aug 16 2023 with gcc 12
```

**Describe the bug**
I'm currently trying to build a new system that can call multiple branches simultaneously. The managing of the branches works so far, but I have a problem that I haven't been able to work around after a few days of trying and testing.

If I start several parallel branches and they run (all) into a local timeout, the $bavp variables are either NULL or only filled with the information from the first branch, but not with the $bavp data from the branch that is currently timed out.

If opensips triggered the a local error, I can no longer find out which of the active branches caused this problem.

I've also tryed all of the $T_* Variables, but with the same result. All of these variables are ether NULL or filled with the data from the first startet branch.

**To Reproduce**
```
route {
	# ...
	
	t_on_branch("default_branch");
        t_on_reply("default_onreply");
        t_on_failure("default_onfailure");
	
	append_branch("sip:123456789@server_a", "0.99");
	append_branch("sip:123456789@server_b", "0.99");
	append_branch("sip:123456789@server_c", "0.99");
	
	# I Need this, there could be some servers with lower qvalue
	serialize_branches(1);
	
	# Remove the current call from the branches, we will only call the appended branches
	next_branches();
	
	t_relay();
}

branch_route[default_branch] {
	$bavp(branch_id) = $rd;
	# set up the call ...
}

### All branches timed out with no anwer / local 408 ###

failure_route[default_onfailure] {

	if (t_local_replied("all")) {
		# The bavp is always set to NULL or "server_a", never server b or c
		xlog(":: $ci :: Error in branch to $bavp(branch_id)");
	}
}
```

**Expected behavior**

I expect that in the failure_route the bavp variables are still assigned to the branch that triggered the error.

**Comment by bogdan-iancu** [comment]
@thuroc , if I understand correctly it is about the timeout internally generated by OpenSIPS (not a received one). IF so, the timeout is at transaction level (the whole transaction times out while trying to establish) . The timeout is NOT at the branch level, so there is no branch to be "advertised" in failure route.

**Comment by thuroc** [comment]
Hello @bogdan-iancu, yes, thats right, it's an internally generated timeout by opensips. But not the whole transaction is timed out, only 1 (or in worst case multiple) branches within this transaction.

If i send the call to 3 different trunks with a parallel branching, the onfailure route would be triggered 3 times if all destinations have a timeout. And thats fine and exactly what i expected.

My problem at this point is that in the onfailure route I can't determine exactly which of these parallel called trunks has a problem. I can't respond to it with dynamic failover routing or even manage separate limits for these 3 trunks.

I would need some way to determine exactly which of the parallel called destinations has just been aborted. Do you have a tip for me on how I could do this in opensips?

**Comment by thuroc** [comment]
Hello Bogdan, i've made an possible real life example of our routing to explain my problem in more detail.

If we got a call to a number, our backend API generate a dynamic routing for this call.

Each of the possible destinations has its own fallback routing, channel limits, sip/rtp configuration and so on.

https://imgur.com/a/Tnw9MVO

Let's assume that the sip account in the picture has a timeout and the customer pbx trunk also. No failover routing should now be started with the SIP account, but it should be with the PBX trunk.

Now, I always have to be able to determine exactly which of the previously started legs in the branch route is currently having a timeout in the failure route so that I can then carry out the appropriate reaction to it (channel limit down, stop the RTP leg, ...).

**Comment by bogdan-iancu** [comment]
ups, let's ignore the above commit reference as it's bogus :(

**Comment by bogdan-iancu** [comment]
@thuroc , I guess by leg you mean branches for a transaction. In case of parallel forking, all ongoing branches are responding to the same timeout (as it is at the transaction level) and the failure route will be called only one time !!! The failure route is also at transaction level, not per branch. So even if you do parallel forking to 3 destinations, if you hit an internal timeout for the transaction, there will be only one failure route.
