### ISSUE TITLE
[BUG] b2b_logic: transferor hangs (doesn't get disconnected) during cancelled transfer

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#3195]
**OpenSIPS version you are running**
```
opensips 3.4
```

**Describe the bug**
If a blind transfer is initiated in b2b mode and the caller hangs up before the transfer is completed, the transferor gets stuck (it is not disconnected).
It seems that the code is expecting the the transfer to be completed *successfully* before disconnecting the transferor.

**Comment by ovidiusas** [comment]
The transfer is initiated with the following bridge flags: "notify,rollback-failed,no-late-sdp".

**Comment by razvancrainea** [comment]
Can you please run again the scenario with the latest code?
