### ISSUE TITLE
[BUG] b2b_logic: call transfer aborted if transferor disconnects during transfer

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#3196]
**OpenSIPS version you are running**
```
opensips 3.4
```

**Describe the bug**
If the transferor hangs up during the transfer process (while transferee's phone is ringing results in transfer being aborted.
The transfer procedure should continue regardless of the status of the transferor.

Example call flow:
[https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cuipph/7960g_7940g/sip/8_0/english/administration/guide/8_0/sipaxb80.html#wp1006827](url)
```
caller         b2b       transferor    transferee
  |----INVITE-->|             |             |
  |             |---INVITE--->|             |
  |             |<--200-------|             |
  |<---200------|             |             |
  |----ACK----->|             |             |
  |             |---ACK------>|             |
  |             |<--REFER-----|             |
  |             |---202------>|             |
  |             |-----------------INVITE--->|
  |             |<--BYE-------|             |
  |             |---200------>|             |
=== the call transfer should continue ===
=== the transferor should continue to receive notifications ===
```

**Comment by razvancrainea** [comment]
Can't we achieve this through the script, i.e. not ending the dialog?
