### ISSUE TITLE
Ran out of ports

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3201]
[core] Failed to get 2 consecutive ports on interface 43.204.228.99 for media relay (last error: Cannot assign requested address)
[1695291108.980651] ERR: [lhcn6aaa55fv5ufk7h6f]: [core] Failed to get 2 consecutive ports on all locals of logical 'default'
[1695291108.980952] ERR: [lhcn6aaa55fv5ufk7h6f]: [core] Error allocating media ports
[1695291108.981255] ERR: [lhcn6aaa55fv5ufk7h6f]: [core] Destroying call
[1695291108.983013] WARNING: [lhcn6aaa55fv5ufk7h6f]: [control] Protocol error in packet from 172.31.34.24:36025: Ran out of ports [d3:sdp8646:v=0

**Comment by prathibhacdac** [comment]
[rtpengine]

table = 0
# no-fallback = false
### for userspace forwarding only:
# table = -1

### a single interface:
# interface = 123.234.345.456
### separate multiple interfaces with semicolons:
# interface = internal/12.23.34.45;external/23.34.45.54
### for different advertised address:
# interface = 12.23.34.45!23.34.45.56

#interface = any

interface=43.204.228.99!172.31.3.229
#interface=172.31.3.229


listen-ng = 172.31.3.229:2223
# listen-tcp = 25060
# listen-udp = 12222

### interface for HTTP, WS and Prometheus
# listen-http = 9101
listen-http = 172.31.3.229:2225

# listen-https = localhost:2226
# https-cert =
# https-key =

listen-cli = 172.31.3.229:2224

timeout = 60
silent-timeout = 3600
tos = 184
# control-tos = 184
# delete-delay = 30
# final-timeout = 10800
# endpoint-learning = heuristic
# reject-invalid-sdp = false
port-min = 10000
port-max = 20000
# max-sessions = 5000

# software-id = rtpengine
# max-load = 5
# max-cpu = 90
# max-bandwidth = 10000000
# scheduling = default
# priority = -3
# idle-scheduling = idle
# idle-priority = 10

recording-dir = /var/spool/rtpengine
recording-method = proc

**Comment by razvancrainea** [comment]
Not an OpenSIPS issue, please do not open tickets on this tracker unless it is an issue with OpenSIPS and you can say exactly what is not working.
