### ISSUE TITLE
mi_fifo / mi_http fail to reload data

### ISSUE THREAD

**Issue by syco** [OpenSIPS/opensips#321]
Hi,
I'm using version 1.11, from the yum repo.
I tried changing the data in load_balancer and address table, then reload with:
opensipsctl fifo lb_reload
opensipsctl fifo address_reload

result was:
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: INFO:load_balancer:mi_lb_reload: "lb_reload" MI command received!
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: ERROR:db_unixodbc:db_unixodbc_submit_query: rv=-1. Query= select id,group_id,dst_uri,resources,probe_mode from load_balancer 
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: ERROR:core:db_do_query: error while submitting query - [select id,group_id,dst_uri,resources,probe_mode from load_balancer ]
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: ERROR:load_balancer:lb_db_load_data: DB query failed
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: ERROR:load_balancer:load_lb_data: failed to load data from DB
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: CRITICAL:load_balancer:lb_reload_data: failed to load load-balancing info
Sep  4 08:38:15 opensipstest /usr/sbin/opensips[2276]: CRITICAL:load_balancer:mi_lb_reload: failed to load load balancing data

Sep  4 08:38:28 opensipstest /usr/sbin/opensips[2276]: ERROR:db_unixodbc:db_unixodbc_submit_query: rv=-1. Query= select ip,grp,mask,port,proto,pattern,cprefix,id from address 
Sep  4 08:38:28 opensipstest /usr/sbin/opensips[2276]: ERROR:core:db_do_query: error while submitting query - [select ip,grp,mask,port,proto,pattern,cprefix,id from address ]
Sep  4 08:38:28 opensipstest /usr/sbin/opensips[2276]: ERROR:permissions:reload_address_table: failed to query database

Using mi_http produces the same output.
I can see that the db is not hit at all, let me know if I you need any other informations.

**Comment by ionutrazvanionita** [comment]
@syco Configured mysql to work with unixodbc. OpenSIPS starts ok. First, i tested with load_balancer empty table, inserted into the table. The lb_reload function provides only the first line from your output
INFO:load_balancer:mi_lb_reload: "lb_reload" MI command received!
and then lb_list function shows all new data has been found. Then started openSIPS with data in the table, added more data, reloaded and still works fine. Are you sure you didn't do something wrong when configuring unixodbc? If you are sure, can you be more specific and provide us with more information about the scenario?

**Comment by syco** [comment]
Hi,
after apdating to the lastest (1 month ago) git, I didn't have this problem
again.
I consider it resolved, unfortunately I don't have that specific setup
anymore to do more tests.
Regards

*Alberto Rinaudo*
 mob (UK):
* +44 (0) 741 496 5674 *e-mail  :
* alberto.rinaudo@gmail.com <alberto.rinaudo@gmail.com> *skype   :*
a.rinaudo*
