### ISSUE TITLE
[BUG] tls_wolfssl doesn't work with opensips 3.2.14 and 3.4.1 but works with opensips 3.3.7

### ISSUE THREAD

**Issue by FedorKiselev76** [OpenSIPS/opensips#3213]
Sep 27 15:27:14 sip2 opensips[306652]: INFO:tls_wolfssl:_wolfssl_tls_accept: New TLS connection from 2001:818:EAD3:FF00:XXXX:XXXX:XXXX:XXXX:57869 accepted
Sep 27 15:27:14 sip2 opensips[306652]: ERROR:tls_wolfssl:_wolfssl_tls_write: TLS connection to 2001:818:EAD3:FF00:XXXX:XXXX:XXXX:XXXX:57869 write failed (0:-1:0)
Sep 27 15:27:14 sip2 opensips[306652]: ERROR:tls_wolfssl:_wolfssl_tls_write: TLS write error: 0, ok
Sep 27 15:27:14 sip2 opensips[306652]: ERROR:tls_wolfssl:_wolfssl_tls_blocking_write: TLS failed to send data

**Describe the bug**

opensips 3.2.14 and 3.4.1 doesn't work with tls_wolfssl compiled on centos 8 and 9 stream but opensips 3.3.7 with tls_wolfssl works well.  In the meantimes tls_openssl works successfully with all versions.

**To Reproduce**

Please compile opensips 3.2.14 on centos 8 stream and turn on tls_wolfssl

**Comment by FedorKiselev76** [comment]
#loadmodule "tls_openssl.so"
loadmodule "tls_wolfssl.so"

loadmodule "tls_mgm.so"

modparam("tls_mgm", "server_domain", "xxx")
modparam("tls_mgm", "match_ip_address", "[xxx]*")
modparam("tls_mgm", "match_sip_domain", "[xxx]*")

modparam("tls_mgm", "certificate","[xxx]/usr/local/opensips-3.2/etc/opensips/tls/server/server-cert.pem")
modparam("tls_mgm", "private_key","[xxx]/usr/local/opensips-3.2/etc/opensips/tls/server/server-privkey.pem")

modparam("tls_mgm", "require_cert", "[xxx]0")
modparam("tls_mgm", "verify_cert", "[xxx]0")
modparam("tls_mgm", "tls_method", "[xxx]TLSv1_2")

loadmodule "proto_tls.so"
modparam("proto_tls", "tls_async", 0)

**Comment by razvancrainea** [comment]
This should have been fixed by commit b1654b0445b526783a2ff3684c60234a35eb20c7. Please check with the latest 3.4/3.2 and re-open the ticket if it is not working properly.
