### ISSUE TITLE
rtpengine_delete()

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3217]
I guess is because all the tests you have been doing have been creating more ports that are not being deleted after end of call, If port is the problem I suggest you restart RTP-Engine and also make sure you tear down RTP engine session after you have ended all calls. This can be done with `rtpengine_delete()`.
Add this before the end of the has to tag if statement.
```
 if (is_method("CANCEL|BYE")) {
		# do accounting even if the transaction fails, you can omit this.
		do_accounting("db","failed");
		# This is done to make sure all RTP-engine sessions in the dialogue are closed.
		rtpengine_delete();
	}
```

_Originally posted by @AlijiEmmanuel-dev in https://github.com/OpenSIPS/opensips/issues/3191#issuecomment-1723775229_

**Comment by prathibhacdac** [comment]
I've done this. Yet I'm unable to resolve. Can you @AlijiEmmanuel-dev pls help?

**Comment by prathibhacdac** [comment]
Now I don't have the ports issue. There is no audio and video in the web to web call.

**Comment by AlijiEmmanuel-dev** [comment]
Change your RTP Engine log level to seven, send all the logs over as txt

**Comment by prathibhacdac** [comment]
I am not seeing any other lig entries other than the ones posted here for rtpengine

**Comment by AlijiEmmanuel-dev** [comment]
I suggest you upgrade opensips to version 3.3 or 3.4. this is not to say the other versions are not working, they work just fine.

Check your syslog for RTPEngine logs. If you don't get RTP Engine logs check to make sure opensips communicate with RTP Engine.

**Comment by AlijiEmmanuel-dev** [comment]
> I am using opensips-2.4 for testing purpose. Earlier I checked with opensips-3.5 also. Got the same result.
> 
> In the below command, 172.31.12.214 is my private IP and 15.206.253.117 is my public_IP.
> 
> rtpengine --interface=public/172.31.12.214\!15.206.253.117 --foreground --listen-ng=172.31.12.214:2225 table=0 -m 30000 -M 40000 --log-level=7
> [1696421402.402929] ERR: [core] FAILED TO CREATE KERNEL TABLE 0 (No such file or directory), KERNEL FORWARDING DISABLED
> [1696421433.241561] ERR: [531cla9065vnaem8s1i6 port 30000]: [rtcp] SRTCP output wanted, but no crypto suite was negotiated
> 
> Inward ports 30000 to 40000 is opened and all the outgoing ports are open.

I suggest you configure RTP Engine from it config file.

**Comment by prathibhacdac** [comment]
In

[rtpengine]

table = 0
# no-fallback = false
### for userspace forwarding only:
# table = -1

### a single interface:
interface = 198.154.99.201
### separate multiple interfaces with semicolons:
# interface = internal/12.23.34.45;external/23.34.45.54
### for different advertised address:
# interface = 12.23.34.45!23.34.45.56

#interface = any



listen-ng = 135.554.129.241:2223
# listen-tcp = 25060
# listen-udp = 12222

### interface for HTTP, WS and Prometheus
# listen-http = 9101
listen-http = 135.554.129.241:2225

# listen-https = localhost:2226
# https-cert =
# https-key =`

Here 135,x,x,x is it public ip?

**Comment by prathibhacdac** [comment]
rtpengine error log:
[rtpengine-error.log](https://github.com/OpenSIPS/opensips/files/12812028/rtpengine-error.log)

**Comment by prathibhacdac** [comment]
Now, I've moved to opensips-3.4, I see these errors in syslog w.r.t rtpengine:
ERROR:rtpengine:select_rtpe_node: script error -no valid set selected
ERROR:rtpengine:rtpe_function_call: no available proxies

**Comment by prathibhacdac** [comment]
@AlijiEmmanuel-dev can you shre your opensips.cfg file?

**Comment by prathibhacdac** [comment]
Tried various commands:

 /usr/bin/rtpengine -p /var/run/rtpengine.pid -i public/172.31.12.214\!15.206.253.117 in-iface=172.31.12.214 out-iface=15.206.253.117 -n 127.0.0.1:2223 -m 41000 -M 55000 --delete-delay=0 -f -E

 /usr/bin/rtpengine -p /var/run/rtpengine.pid -i 15.206.253.117 in-iface=172.31.12.214 out-iface=15.206.253.117 -n 127.0.0.1:2223 -m 41000 -M 55000 --delete-delay=0 -f -E

But none is working.

**Comment by AlijiEmmanuel-dev** [comment]
Are you testing on a remote server or local server, either case check if RTPEngine is starting properly. On a freshly installed RTP Engine, only change the socket i.e interface and port it is bound to from the config file, leave everything else the same.

Don't use the command line. Use systemctl and config to start rtpengine

**Comment by prathibhacdac** [comment]
I'm using the amazon ec2 debian instance.

**Comment by AlijiEmmanuel-dev** [comment]
The problem here is the NAT handling, usually in cloud environments, you have two IP addresses, internal and external. Make sure RTPEngine uses the external as it's interface.
Else, opensips will be able to reach the internal RTP Engine but your SIP or Web phones would not, therefore no video and audio will be forwarded to RTP Engine for relay.

**Comment by prathibhacdac** [comment]
> The problem here is the NAT handling, usually in cloud environments, you have two IP addresses, internal and external. Make sure RTPEngine uses the external as it's interface. Else, opensips will be able to reach the internal RTP Engine but your SIP or Web phones would not, therefore no video and audio will be forwarded to RTP Engine for relay.

I'm using the external IP address as the interface address.

**Comment by prathibhacdac** [comment]
This is the error in syslog:

Failed to get 2 consecutive ports on interface 15.206.253.117 for media relay (last error: Cannot assign requested address)
ERR: [e0c6s93u16ckshfa7r40]: [core] Error allocating media ports
WARNING: [e0c6s93u16ckshfa7r40]: [control] Protocol error in packet from 127.0.0.1:37564: Ran out of ports [d3:sdp2736:v=0
DBG:rtpengine:rtpe_function_call: proxy reply: d6:result5:error12:error-reason16:Ran out of portse
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Ran out of ports
WARNING: [e0c6s93u16ckshfa7r40]: [control] Protocol error in packet from 127.0.0.1:37564: Unknown call-id [d3:sdp3086:v=0
DBG:rtpengine:rtpe_function_call: proxy reply: d6:result5:error12:error-reason15:Unknown call-ide
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Unknown call-id
WARNING: [e0c6s93u16ckshfa7r40]: [control] Protocol error in packet from 127.0.0.1:37564: Unknown call-id [d3:sdp3086:v=0
DBG:rtpengine:rtpe_function_call: proxy reply: d6:result5:error12:error-reason15:Unknown call-ide
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Unknown call-id
WARNING: [e0c6s93u16ckshfa7r40]: [control] Protocol error in packet from 127.0.0.1:37564: Unknown call-id [d3:sdp3086:v=0
 DBG:rtpengine:rtpe_function_call: proxy reply: d6:result5:error12:error-reason15:Unknown call-ide
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Unknown call-id
WARNING: [e0c6s93u16ckshfa7r40]: [control] Protocol error in packet from 127.0.0.1:37564: Unknown call-id [d3:sdp3086:v=0
DBG:rtpengine:rtpe_function_call: proxy reply: d6:result5:error12:error-reason15:Unknown call-ide
ERROR:rtpengine:rtpe_function_call: proxy replied with error: Unknown call-id

**Comment by AlijiEmmanuel-dev** [comment]
Restart RTP Engine, send your opensips config script and RTP Engine config script

**Comment by AlijiEmmanuel-dev** [comment]
send to my email.

**Comment by prathibhacdac** [comment]
> our opensips config script and RTP Engine config script

your email ID?

**Comment by prathibhacdac** [comment]
> > our opensips config script and RTP Engine config script
> 
> your email ID? 
Unable to get your email ID from github.

**Comment by AlijiEmmanuel-dev** [comment]
alijiemmanuel.dev@gmail.com

**Comment by prathibhacdac** [comment]
> [alijiemmanuel.dev@gmail.com](mailto:alijiemmanuel.dev@gmail.com)

Mail sent.

**Comment by prathibhacdac** [comment]
Is this portion of code correct?

if (!is_method("REGISTER")) {
                if (!is_myself("$fu")) {
                        # if caller is not local, then called number must be local
                        if (!is_myself("$rd")) {
                                send_reply(403,"Rely forbidden");
                                exit;
                        }
                }
        }

 if (!is_myself("$rd")) {
                append_hf("P-hint: outbound\r\n");
                route(relay);
        }
