### ISSUE TITLE
[BUG] opensips doesn't use $socket_out for in-dialog requests had come before the dialog is confirmed

### ISSUE THREAD

**Issue by ankogan** [OpenSIPS/opensips#3246]
**OpenSIPS version you are running**
```
 ~/sipp/tests # opensips -V
version: opensips 3.2.15 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 4096, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 94115b861
main.c compiled on  with gcc 8
```

**Describe the bug**
Opensips incorrectly routes in-dialog requests while the dialog is in early state.
I create a dialog in INVITE transaction and set $socket_out to route it through particular socket. After that, if I receive in-dialog INFO message after 183 but before 200 on INVITE, t_relay() doesn't route it throught socket set previously to $socket_out, as it does after dialog is confirmed. And I have to explicitly set $socket_out for it if $DLG_status < 4.

**Comment by ankogan** [comment]
Hi! Any updates?

**Comment by ankogan** [comment]
Hi! Any updates?

**Comment by ankogan** [comment]
Hi! Any news here?

**Comment by bogdan-iancu** [comment]
Could you share a pcap /trace showing the issue ?

**Comment by bogdan-iancu** [comment]
@ankogan , if there is no way to reproduce this issue, there is not much we can do at this point. Consider closing it if you have no more input (of course, you can open a new report if the issue re-surface)
