### ISSUE TITLE
[BUG] ERROR:b2b_logic:term_entity: preparing ctx for request failed

### ISSUE THREAD

**Issue by BTa7BxrHYn** [OpenSIPS/opensips#3259]
**OpenSIPS version you are running**

```version: opensips 3.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: f74b210d5
main.c compiled on 00:00:00 May 18 2022 with gcc 11
```

**Describe the bug**

A call that lasts longer
"b2b_logic", "max_duration" does not complete.
an error occurs:
```
Nov 28 18:20:26 alt-lab-scpd2 /usr/sbin/opensips[2810091]: INFO:b2b_logic:b2bl_clean: Found expired tuple [498.0]: delete and send BYEs
Nov 28 18:20:26 alt-lab-scpd2 /usr/sbin/opensips[2810091]: ERROR:b2b_logic:term_entity: preparing ctx for request failed, entity [B2B.498.7573631.1701184773.1656493924]
Nov 28 18:20:26 alt-lab-scpd2 /usr/sbin/opensips[2810091]: ERROR:b2b_logic:term_entity: preparing ctx for request failed, entity [B2B.23.316.1701184780.1552283418]
```
DBG:tm:delete_cell also does not work.
```
Nov 28 18:34:59 alt-lab-scpd2 /usr/sbin/opensips[2810089]: DBG:tm:delete_handler: removing 0x7efc1c1874a8
Nov 28 18:34:59 alt-lab-scpd2 /usr/sbin/opensips[2810089]: DBG:tm:delete_cell: delete_cell 0x7efc1c1874a8: can't delete -- still reffed (1)

```

**To Reproduce**

The incoming call is assigned to a pending event, a b2b session is established, the pending call is connected to one of the entities using b2b_bridge_request. The call lasts longer than the max_duration timeout.

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Centos 9 
 - OpenSIPS installation:  self-build rpm
 
**Additional context**

[opensips.log](https://github.com/OpenSIPS/opensips/files/13490139/opensips.log)

**Comment by BTa7BxrHYn** [comment]
up

**Comment by BTa7BxrHYn** [comment]
still relevant

**Comment by razvancrainea** [comment]
Can you check if this is happening with the latest git code? Make sure it contains commit 5d90a34b40
