### ISSUE TITLE
[BUG] Higher OpenSIPS UDP workers load after upgrade to v3.4.2

### ISSUE THREAD

**Issue by 11qeq11** [OpenSIPS/opensips#3265]
**OpenSIPS version you are running**

```console
$ sudo docker exec -it opensips opensips -V
version: opensips 3.4.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on  with gcc 10
```

**Describe the bug**

This may be not exactly a bug, but rather a question regarding version `3.4.2`.

I noticed that since the upgrade from 3.1.9 to 3.4.2 (also OpenSIPS was migrated to Docker), UDP workers load have clear spike:

![image](https://github.com/OpenSIPS/opensips/assets/78615840/197475b3-7931-487b-b2ad-29ee03bbc398)

As well as UDP queue looks rather large after the upgrade:

![image](https://github.com/OpenSIPS/opensips/assets/78615840/88d646ea-5958-4b88-8648-02395e3b6772)

This may have gone unnoticed but as a result, sometimes we observe 100% CPU usage and while OpenSIPS wasn't logging any error - responses were not coming from UDP ports, as well as `'{ "jsonrpc": "2.0", "id": "1", "method": "sr_get_status", "params": ["core"] }'` wasn't returning anything, or was, but with a huge delay. Changing log level to `4` doesn't seem to provide any insight either, on the contrary, due to the enormous logs amount, even more CPU resources are being used.

This "stuck" behaviour might last for just tens of seconds, sometimes a couple of minutes.

**To Reproduce**

I'm not sure yet what will be the exact scenario, I couldn't replicate it with simply spamming UDP port with `sipp`, all workers are overloaded but still responsive.

**Expected behavior**

We were able to mostly mitigate the problem on "hanging" service by reducing the number of other CPU consuming services on the same machine where CPU is running, so we almost don't see "hanging" of service anymore, but higher UDP workers load and UDP queue is still visible, I suppose that this can be mitigated by more workers.

So my question are:

- **Is it expected that UDP workers on version `3.4.2` are more resources consuming?** 
- **Can I justify adding of more UDP workers by the fact of update alone?**

I'd greatly appreciate any insight of what could've gone wrong, I understand that there's generally not much info, but I'd like to exclude a possibility of application's resources demand growth.

**Relevant System Logs**

**OS/environment information**
 - Operating System: CentOS7
 - OpenSIPS installation: Docker installation

**Additional context**

OpenSIPS is processing 600+ records in registrant with 120sec expiry interval, 700+ in location, almost all re-register with 300sec, around 80 active calls in peak. Previously, 2 cores with 4 GB RAM was enough to handle it.

**Comment by bogdan-iancu** [comment]
@11qeq11 , it is not clear from your report - the spikes you mentioned do appear during some test you do with SIPP ? Or when OpenSIPS is idle from traffic  perspective ?

**Comment by bogdan-iancu** [comment]
The workers may handle either traffic related jobs, either timer based jobs. If you say the traffic is not the reason, it may be the timer jobs (which jobs are, it depends on your cfg/modules).
What you can do is to try to do a `opensips-cli -x trap` while experiencing such spikes (try several traps at seconds interval) - maybe this will give us a hint in terms of what OpenSIPS is doing/processing

**Comment by 11qeq11** [comment]
In between/after upgrades, we did not observe higher traffic, which could cause higher load. Generally, no unrelated to the upgrade itself changes were done, the only thing which may be related, but probably not, is that we added monitoring to cURL `/mi` HTTP endpoint and gather stats from `"method": "sr_get_status", "params": ["core"]`, which runs each 2s.

In regard to UDP queue, even adding more workers doesn't seem to help, we just see random UDP queue spikes whereas number of requests/replies stays the same.

> The workers may handle either traffic related jobs, either timer based jobs.

I was thinking about this too, but isn't there a dedicated worker per timer-based jobs? Or can other workers handle some time work too? Either way, thanks for the suggestions, I'll try to provide more info with `trap`.

**Comment by 11qeq11** [comment]
Hm, indeed, I see TM retransmissions stats which appeared only after upgrade.
![image](https://github.com/OpenSIPS/opensips/assets/78615840/375736bc-ba31-4d3c-956e-d4e24b6fad72)

**Comment by bogdan-iancu** [comment]
retransmissions are the result of unresponsive SIP UAS's, not related to the actual upgrade IMHO. Maybe the can try to identify the UAS's that trigger the retransmissions ....so maybe we can understand why they do appear

**Comment by 11qeq11** [comment]
Hi @bogdan-iancu, coming back with some updates.

> retransmissions are the result of unresponsive SIP UAS's, not related to the actual upgrade IMHO.

Well, most likely yes, but OpenSIPS 3.1.x seems to just ignore these metrics, they're not listed in [exported_statistics](https://opensips.org/html/docs/modules/3.1.x/tm.html#exported_statistics). So, that's why I see these only after upgrade.

---

Now, to TM retransmissions themselves:

 Our HA scheme is based on using IP-sharing with `net.ipv4.ip_nonlocal_bind = 1`, so OpenSIPS can silently bind to IP even if it's not on the machine, and we observe high. It looks like high TM retransmissions rate is present on all "backup" machines, where OpenSIPS is bind to non-local IP. 

Also, aside generally higher CPU consumption that was reported in this issue, once in exactly 7h, both "active" and "backup" machines have high load spike just for several minutes, but not simultaneously.

- opensips-cli -x trap during low load, no SIP traffic:

[gdb_opensips_20231212_161925.txt](https://github.com/OpenSIPS/opensips/files/13651091/gdb_opensips_20231212_161925.txt)
[gdb_opensips_20231212_161528.txt](https://github.com/OpenSIPS/opensips/files/13651092/gdb_opensips_20231212_161528.txt)
[gdb_opensips_20231212_162130.txt](https://github.com/OpenSIPS/opensips/files/13651090/gdb_opensips_20231212_162130.txt)

- opensips-cli -x trap during high load, no SIP traffic:

[gdb_opensips_20231212_163737.txt](https://github.com/OpenSIPS/opensips/files/13651093/gdb_opensips_20231212_163737.txt)
[gdb_opensips_20231212_163415.txt](https://github.com/OpenSIPS/opensips/files/13651094/gdb_opensips_20231212_163415.txt)

Perhaps, SIP transaction saved in memory while OpenSIPS is "active" can't be properly retransmitted and just being stuck in memory? I don't see any memory-related problems, though. Interesting that even restarting docker container with opensips doesn't drop "retransmissions" rate, it will be the same.

**Comment by 11qeq11** [comment]
I think that we can close it, high TM retransmission rate is probably caused by the master/backup setup we're using, when one OpenSIPS is bind to IP he doesn't really own, while still try to send some SIP requests and maintain usual activity. To be exact, all issues with load and timeouts from active OpenSIPS were resolved by:

- Removing CPU intense 3rd-party applications from the same machine where OpenSIPS resides;
- Adding a bit more (+2 virtual cores) CPU resources to machines with the highest demand;
- Adding a bit more (+2-4) workers to both UPD and Timer jobs;

Cluster seems stable now, so I don't see much point in digging this further, @bogdan-iancu thanks for the help!
