### ISSUE TITLE
[BUG] tracer / re-invites causing loose_route load to grow over time

### ISSUE THREAD

**Issue by nathanleyton** [OpenSIPS/opensips#3271]
**OpenSIPS version you are running**

```
version: opensips 3.2.15 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 6cfb172f0
main.c compiled on  with gcc 8
```

**Describe the bug**
We initially noticed when using tracer module, re-invites for session timers were causing exponential increase in load on opensips process that was not CPU load. We use the benchmark module, and debug logs to capture more information. It turns out that as we were tracing using a domain name the issue was more visible as we didn't have DNS Cache and each re-invite causes more DNS lookups than the previous. Using the IP reduces the issue enough that is it no longer maxing out an one process and causing call drops on timers, however looking at the debug logs and benchmark I can see the issue is still there. The time was being eaten up in the loose_route. The most simple log was when I remove hep and everything else, and just send sip to an external IP address. These are the repeating logs:-

Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off
Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off
Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off
Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off
Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off
Dec 12 11:34:38 [142] DBG:core:mk_proxy: doing DNS lookup...
Dec 12 11:34:38 [142] DBG:core:get_out_socket: socket determined: 0x7f2e07e87d38
Dec 12 11:34:38 [142] DBG:tracer:is_id_traced: trace=on dyn=off

Each re-invite these logs grow and grow in the loose_route and more time is consumed per call to loose_route than the last.

Our config:
#### HEP Module
loadmodule "proto_hep.so"
modparam("proto_hep", "hep_id", "[hep_tracer1]LISTEN_IP1:SIPTRACE_HEP_PORT; transport=udp; version=3")

#### SIP Tracing
loadmodule "tracer.so"
modparam("tracer", "trace_on", 1)
modparam("tracer", "trace_id",  "[hep1]uri=hep:hep_tracer1")

and we call trace like this

trace("hep1", "t", "sip|xlog");

One side is TLS and the other UDP and I don't know if this is specific to TLS / UDP or not. 

**Expected behavior**
I would expect to only see those logs duplicated for the number of messages and not to grow over timer / more re-invites. I would also expect loose_route load time not to grow. 

Thanks

**Comment by petekelly** [comment]
Just confirming I have seen this in action too... it seems to be something that happens for *all* in-dialog requests.

Unsure if it's related to TLS only but the DNS lookups to the "hep" location seem to exponentially increase with each in-dialog request that arrives, resulting in reinvites that take seconds to proxy through OpenSIPS.

I'd note that this is not easily seen in regular calls which only have a BYE as their single other request so it could be prevalent?

**Comment by petekelly** [comment]
Just keeping this alive, it is still an issue

**Comment by bogdan-iancu** [comment]
@petekelly , the culprit DNS lookups are for the HEP destination, right ? and they are more and more (escalating) with the number of in-dialog requests, right ?
