### ISSUE TITLE
[BUG] ERROR:rest_client:_resume_async_http_req: async GET timed out

### ISSUE THREAD

**Issue by windicted** [OpenSIPS/opensips#3286]
**OpenSIPS version you are running**

```
version: opensips 3.3.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 4302d5729
main.c compiled on  with gcc 10
```

**Describe the bug**

Any attempt to use async `rest_get` function for GETting HTTP endpoint in the request route ends up with a timeout. Since the previous version of OpenSIPS (i.e. version 3.3.8) works properly, it seems that the bug came up in attempt to fix #3239, or to be more specific it appeared in https://github.com/OpenSIPS/opensips/commit/1ea1852ed79ba4b79cba39643e1274eed509081b:
https://github.com/OpenSIPS/opensips/blob/1ea1852ed79ba4b79cba39643e1274eed509081b/modules/rest_client/rest_methods.c#L1072-L1074
The `_resume_async_http_req` function sets `async_status` to `ASYNC_CONTINUE` and returns `1` if `mrc == CURLM_OK && running` condition is true, whereas it should continue the loop (as it was in 3.3.8).

**To Reproduce**
1. Start OpenSIPS with the script which loads `rest_client` module and use async `rest_get` function for GETing http://example in the request route.
2. Send INVITE to OpenSIPS

**Expected behavior**

The async `rest_get` function of `rest_client` module gets content of http://example.

**Relevant System Logs**

Here are all messages printed by `rest_client` module during an attempt to GET http://example.com with async `rest_get` function:
```
Jan 20 12:14:23 [275496] DBG:rest_client:w_async_rest_get: async rest get http://example.com 0x7fdcc0979220 0x7fdcc0979428 0x7fdcc0979638
Jan 20 12:14:23 [275496] DBG:rest_client:get_multi: multi pool size is now 1
Jan 20 12:14:23 [275496] DBG:rest_client:start_async_http_req: perform code: 0, handles: 1
Jan 20 12:14:23 [275496] DBG:rest_client:start_async_http_req: ongoing transfer on fd 83
Jan 20 12:14:23 [275496] DBG:rest_client:start_async_http_req: >>> add fd 83 to ongoing transfers
Jan 20 12:14:23 [275496] DBG:rest_client:_resume_async_http_req: resume async processing...
Jan 20 12:14:23 [275496] DBG:rest_client:_resume_async_http_req: perform result: 0, running: 1 (break: 0)
Jan 20 12:14:42 [275496] DBG:rest_client:_resume_async_http_req: resume async processing...
Jan 20 12:14:42 [275496] ERROR:rest_client:_resume_async_http_req: async GET timed out, URL: http://example.com/
Jan 20 12:14:42 [275496] DBG:rest_client:del_transfer: del fd 83
Jan 20 12:14:42 [275496] DBG:rest_client:_resume_async_http_req: download finished, but an HTTP status is not available (timed_out: 1)
Jan 20 12:14:42 [275496] DBG:rest_client:_resume_async_http_req: HTTP response code: 0
```

**OS/environment information**
 - Operating System:  `Debian 11`
 - OpenSIPS installation:  `debs` from `deb https://apt.opensips.org bullseye 3.3-releases`

**Comment by liviuchircu** [comment]
Thank you for the report, @windicted.  Indeed, there is a big regression here, affecting the "OK" async case.  In short, it seems that `curl_multi_perform` does *not complete* the GET request on a 1st call, which is the assumption of the "async timeouts" patch:  _"do a perform, then wait for activity on the socket (the HTTP reply)"_.

So to satisfy all conditions (make the "OK" case work, while keeping things async), I'm afraid that unless we can find a _guaranteed_ way to determine when the GET request is fully written on the network (perhaps there is a useful `curl_easy_getinfo()`?), async libcurl seems to be only possible with a `1` second granularity, by setting the minimum reactor timeout (`1` second), then re-adding the cURL descriptor into the reactor on each in-between timeout, until the combined duration adds up to the global timeout.
