### ISSUE TITLE
[BUG] B2BUA authentication from AVPs does not work

### ISSUE THREAD

**Issue by BTa7BxrHYn** [OpenSIPS/opensips#3290]
**OpenSIPS version you are running**

```
opensips -V
version: opensips 3.4.3 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9f5a598a7
main.c compiled on 00:00:00 May 18 2022 with gcc 11

```

**Describe the bug**

AVP-based authentication doesn't seem to work.
```
modparam("uac_auth","auth_username_avp","$avp(user_avp)")
modparam("uac_auth","auth_password_avp","$avp(passw_avp)")
modparam("uac_auth","auth_realm_avp","$avp(realm_avp)")


loadmodule "b2b_entities.so"
modparam("b2b_entities", "db_mode", 0)
modparam("b2b_entities", "server_hsize", 9)
modparam("b2b_entities", "client_hsize", 9)
#modparam("b2b_entities", "script_req_route", "b2b_entities_request")
#modparam("b2b_entities", "script_reply_route", "b2b_entities_reply")

loadmodule "b2b_logic.so"
modparam("b2b_logic", "db_mode", 0)
modparam("b2b_logic", "hash_size", 9)
modparam("b2b_logic", "contact_user", 0)
modparam("b2b_logic", "cleanup_period", 60)
modparam("b2b_logic", "max_duration", 30)

modparam("b2b_logic", "b2bl_from_spec_param", "$var(b2bl_from)")

route{
        if (is_method("OPTIONS") && is_myself("$rd") ) {
                     send_reply(200,"OK");
                     exit;
        };

        if (!mf_process_maxfwd_header(10)) {
               send_reply(483,"Too Many Hops");
               exit;
        };

        if (is_method("REGISTER") && is_myself("$rd") ) {
                     send_reply(200,"OK");
                     exit;
        };


        t_check_trans();

        if (is_method("INVITE") && !has_totag()) {
                $avp(user_avp) = "123231";
                $avp(passw_avp) = "12132312";
                $avp(realm_avp) = "opensips.org";
                $du = "sip:193.162.143.161:8060;user=phone";
                b2b_init_request("top hiding");
        }
        exit;
}

```

**To Reproduce**

Call flow endpoint -> opensips b2bua -> ISP

According to the equation, when you configure the parameters of the uac_auth module, and receive a response to invite 401 or 407, a second INVITE with authorization should be automatically sent. Instead, however, the dialogue simply ends

**Expected behavior**

**Relevant System Logs**

[opensips.log](https://github.com/OpenSIPS/opensips/files/14036350/opensips.log)

**OS/environment information**
 - Operating System: 
 Centos 9
 - OpenSIPS installation: 
 manual packages from opensips-3.4.3.20240116.9f5a598a7

**Comment by BTa7BxrHYn** [comment]
Hello. Thank you very much for the clarification. 

According to the documentation, I want to set up outgoing call authorization using the following module: 
```
modparam("uac_auth","auth_username_avp","$avp(user_avp)") modparam("uac_auth","auth_password_avp","$avp(passw_avp)") modparam("uac_auth","auth_realm_avp","$avp(realm_avp)") 

loadmodule "b2b_entities.so" 
loadmodule "b2b_logic.so" 
```

With this setup 
```
$avp(user_avp) = "123231"; 
$avp(passw_avp) = "12132312"; 
$avp(realm_avp) = "opensips.org"; 
$du = "sip:193.162.143.161:8060; user=phone"; 
b2b_init_request("top hiding") 

```
However, in response to 401, b2b responds to ack, no further repetition occurs

**Comment by razvancrainea** [comment]
You are using the wrong credentials - according to the logs, your 401 sends credentials for the `asterisk` realm, whereas you provide credentials for the `opensips.org` realm. Since we cannot find suitable credentials, we simply relay the message, as there's nothing we can do about that realm.
Nevertheless, this is not an OpenSIPS bug, but rather a provisioning/setup one, so I am closing the ticket. Please follow up for more information on the [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).
