### ISSUE TITLE
Opensips as frontend proxy server  and Asterisk as backend registrar server

### ISSUE THREAD

**Issue by E2-Sterlin** [OpenSIPS/opensips#3301]
Is it possible to configure opensips as the frontend proxy server and Asterisk as the backend registrar server to handle RFC8599 for the flutter WebRTC client?

**Comment by razvancrainea** [comment]
Yes.
This issue tracker is only for bug reports and feature requests - usage inquiries should be addressed on the [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

Best regards,
Răzvan
