### ISSUE TITLE
event_route: opensips fails to start due to hardcoded routes for events

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#334]
Routes for handling events are require to have the same name as the event that is subscribed to it.
The following config works fine:
```
startup_route{
    subscribe_event("E_CORE_THRESHOLD", "route:E_CORE_THRESHOLD");
}

event_route[E_CORE_THRESHOLD] {
    xlog("L_INFO", "E_CORE_THRESHOLD\n");
}
```

This config doesn't:
````
startup_route{
    subscribe_event("E_CORE_THRESHOLD", "route:E_CORE_THRESHOLD_ROUTE");
}
...
event_route[E_CORE_THRESHOLD_ROUTE] {
    xlog("L_INFO", "E_CORE_THRESHOLD_ROUTE\n");
}
```

ERROR:event_route:child_init: Event E_CORE_THRESHOLD_ROUTE not registered
ERROR:core:init_mod_child: failed to initializing module event_route, rank 1

**Comment by razvancrainea** [comment]
Hi, Ovidiu!

Does the current behavior satisfy you, or you have a scenario where you _need_ to register a different event route for a specific event?

Best regards,
Răzvan

**Comment by ovidiusas** [comment]
Everything seems to be fine. The docs should be updated to reflect the fact that subscription is required **only** for external applications:
http://www.opensips.org/Documentation/Script-CoreFunctions-2-1#toc54
Also, the docs should mention that the declaration of an event_route automatically triggers a subscription (no need to call subscribe_event):
http://www.opensips.org/Documentation/Script-Routes-2-1#toc9

**Comment by razvancrainea** [comment]
Thanks for the feedback, Ovidiu, I updated both doc pages.
