### ISSUE TITLE
[BUG]Dialoges stucks in state 5

### ISSUE THREAD

**Issue by dimebage** [OpenSIPS/opensips#3343]
Hi
When calling and immediately cancelling, the call is ended but dlg_list shows the dialog stuck in state 5. this over time leads to memory leak as dialoges are never cleared

**OpenSIPS version you are running**
root@SBC:~# opensips -V
version: opensips 3.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 036d02961
main.c compiled on  with gcc 10

**Describe the bug**
Just loading b2b module without even using it cause this issue.

**To Reproduce**
install opensips 3.4 
load b2b module
caller cancel the call or calle does not answer the call

**Expected behavior**
The dialoge must be cleared from active dialouge list.

**Relevant System Logs**
Mar 13 15:15:37 : DBG:tm:timer_routine: timer routine:3,tl=0x7f1c861d06e0 next=(nil), timeout=26
Mar 13 15:15:37 : DBG:tm:delete_handler: removing 0x7f1c861d0630
Mar 13 15:15:37 : DBG:tm:delete_cell: delete_cell 0x7f1c861d0630: can't delete -- still reffed (-1)
Mar 13 15:15:37 : DBG:tm:set_timer: relative timeout is 2
Mar 13 15:15:37 : DBG:tm:insert_timer_unsafe: [3]: 0x7f1c861d06e0 (28)
Mar 13 15:15:37 : DBG:tm:delete_handler: done
Mar 13 15:15:39 : DBG:tm:timer_routine: timer routine:3,tl=0x7f1c861d06e0 next=(nil), timeout=28
Mar 13 15:15:39 : DBG:tm:delete_handler: removing 0x7f1c861d0630
Mar 13 15:15:39 : DBG:tm:delete_cell: delete_cell 0x7f1c861d0630: can't delete -- still reffed (-1)
Mar 13 15:15:39 : DBG:tm:set_timer: relative timeout is 2
Mar 13 15:15:39 : DBG:tm:insert_timer_unsafe: [3]: 0x7f1c861d06e0 (30)
Mar 13 15:15:39 : DBG:tm:delete_handler: done

**OS/environment information**
 - Operating System: root@SBC:~# lsb_release  -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by asolovjov** [comment]
Yes, this is easily reproducable. Dialog are stuck after CANCEL if you just load b2b_entities.so

**Comment by bogdan-iancu** [comment]
DO NOT USE the  both b2b and dialog modules !

**Comment by dimebage** [comment]
Thank you for the reply bogdan, but :
1- The issue does not exist up to opensips 3.2 that we have reverted back to and is working fine.
2- How do we get list of active calls without dialoge module?
3- Your suggestion looks work around rather than solving the actual issue.
Anyway appreciate your devotion the keeping opensips going on it is serving our projects great.

**Comment by asolovjov** [comment]
> DO NOT USE the both b2b and dialog modules !

Media_exchange module has both dialog and b2b_entities in dependencies and won't load without it https://opensips.org/docs/modules/3.4.x/media_exchange.html 
b2b functions aren't used in the script in this case but dialogs get stuck

**Comment by dimebage** [comment]
Any plan to fix this issue or we should keep using 3.2 version until a fix ?
