### ISSUE TITLE
[CRASH]using lookup() with ua-filtering crash

### ISSUE THREAD

**Issue by feiyingcheung** [OpenSIPS/opensips#3356]
**OpenSIPS version you are running**
opensips 3.4.4

**Crash Core Dump**
0x00007fe632280e11 in select_contacts (msg=0x7fe6344476e8, contacts=0x7fe632766528, flags=64, sip_instance=0x7fffab12bb00, call_id=0x7fffab12baf0, ua_re=0x7fe634437508, max_latency=0, ret=0x7fffab12bb18)
    at lookup.c:260
260				regexec(ua_re, ct->user_agent.s, 1, &ua_match, 0))
(gdb) p *ua_re
$5 = {__buffer = 0x0, __allocated = 0, __used = 224, __syntax = 16843462, __fastmap = 0x0, __translate = 0x0, re_nsub = 0, __can_be_null = 0, __regs_allocated = 0, __fastmap_accurate = 1, __no_sub = 0, 
  __not_bol = 0, __not_eol = 0, __newline_anchor = 0}

!!!!The ua_re->__buffer is NULL.

**Describe the traffic that generated the bug**
Using lookup() command with “ua-filtering” flag, the secondary hit lookup() would crash on lookup.c->select_contacts()->regexec(). 
The first lookup() would call refree() (at lib/reg/lookup.c line 212)  to release the ua_re，the secondary lookup() would use the  "freed" ua_re.

Just remove the refree() (at lib/reg/lookup.c line 212), The Crash is Fixed. I think the ua_re should be freed in reg_fixup_free_lookup_flags()

**To Reproduce**
1.base on default opensips.cfg
--        if (!lookup("location","method-filtering")) {
++      if (!lookup("location","ua-filtering=/MicroSIP/")) {

2.ua1 and ua2 reg to opensips
3.ua1 call ua2 , end the call
4.ua1 call ua2 again, crash.

**OS/environment information**
 - Operating System: CentOS7.9
 - OpenSIPS installation: git

**Comment by bogdan-iancu** [comment]
@feiyingcheung , could you verify the fix I just did and confirm?

**Comment by feiyingcheung** [comment]
fix thanks！BR！

> @feiyingcheung , could you verify the fix I just did and confirm?
