### ISSUE TITLE
[BUG] opensips-cli installation instructions produce errors when using python3

### ISSUE THREAD

**Issue by NormB** [OpenSIPS/opensips#3357]
**OpenSIPS version you are running**

```
opensips-cli master branch - Issues with more details https://github.com/OpenSIPS/opensips-cli/issues/122
```

**Describe the bug**

The installation instructions produce errors when using Python3.

**To Reproduce**

Perform a source based installation on a system with Python3 (or with Python3 as the default).

**Expected behavior**

It is expected that the installation completes without an error.

**Relevant System Logs**

See: https://github.com/OpenSIPS/opensips-cli/issues/122

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by NormB** [comment]
bump

**Comment by bogdan-iancu** [comment]
Please open this under the CLI project here https://github.com/OpenSIPS/opensips-cli/issues
