### ISSUE TITLE
[BUG] Restarting a node in the cluster produces a "programming bug" error

### ISSUE THREAD

**Issue by NormB** [OpenSIPS/opensips#3358]
**OpenSIPS version you are running**

```
Running the master branch
```

**Describe the bug**

After rebooting a node in the cluster the following messages are produced:
```
Apr  9 12:58:57 [45] NOTICE:[E_CLUSTERER_NODE_STATE_CHANGED] Cluster ID[1] Node ID[1686046221] New State[1]
Apr  9 12:58:57 [45] INFO:clusterer:handle_pong: Node [1686046221] is UP
Apr  9 12:59:02 [45] CRITICAL:usrloc:receive_ucontact_insert:
>>> differring rlabels (1 vs. 0, ci: '1_1241261897@10.69.15.62')
It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
```

At the same time, a different node in the cluster produced the following error. Note the different (ci variable).
```
Apr  9 12:58:57 [45] NOTICE:[E_CLUSTERER_NODE_STATE_CHANGED] Cluster ID[1] Node ID[1686046221] New State[1]
Apr  9 12:58:57 [45] INFO:clusterer:handle_pong: Node [1686046221] is UP
Apr  9 12:59:02 [45] CRITICAL:usrloc:receive_ucontact_insert:
>>> differring rlabels (1 vs. 0, ci: '1_1241261897@10.69.15.62')
It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
```

**To Reproduce**

Restarting a node in the cluster produces this error. I am not positive of the exact sequence of events that leads up to the error. However, endpoints may register to any of the nodes in the cluster. Will running in debug mode provide enough information? I should be able to turn on debug mode until the error happens again.

**Expected behavior**

See above

**Relevant System Logs**

See above

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

debian:bookworm

**Additional context**

**Comment by NormB** [comment]
Changing log_level=4 didn't produce anything useful to assist in diagnosing the problem

```
Apr  9 14:52:23 [45] NOTICE:[E_CLUSTERER_NODE_STATE_CHANGED] Cluster ID[1] Node ID[1686046221] New State[1]
Apr  9 14:52:23 [45] INFO:clusterer:handle_pong: Node [1686046221] is UP
Apr  9 14:52:43 [45] CRITICAL:usrloc:receive_ucontact_insert:
>>> differring rlabels (1 vs. 0, ci: '1_1241261897@10.69.15.62')
It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

Apr  9 14:56:49 [14] DBG:mi_fifo:mi_fifo_callback: got mi response = [0x55a25691f270]
Apr  9 14:56:50 [45] DBG:proto_bin:bin_read_req: Using the global ( per process ) buff
Apr  9 14:56:50 [45] DBG:proto_bin:bin_parse_headers: received a COMPLETE message
Apr  9 14:56:50 [45] DBG:proto_bin:bin_handle_req: completely received a message
Apr  9 14:56:50 [45] DBG:proto_bin:bin_handle_req: Nothing more to read on TCP conn 0x7f00fca8c378, currently in state 0
```

**Comment by NormB** [comment]
These are the relevant parameters that are set.

Is the problem perhaps related to the "matching_mode=1" (contact & callid matching) setting?

I don't recall the reason we enabled it. Going to test with it set to 0 (contact matching).

```
modparam("usrloc", "location_cluster", 1)
modparam("usrloc", "restart_persistency", "sync-from-cluster")
#modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "cluster_mode", "full-sharing")
modparam("usrloc", "matching_mode", 1)
modparam("usrloc", "use_domain", 1)
```

**Comment by NormB** [comment]
Perhaps this is related https://github.com/OpenSIPS/opensips/issues/3354

**Comment by Lt-Flash** [comment]
We only have these settings and still getting the errors:

```
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "working_mode_preset", "full-sharing-cluster")
modparam("usrloc", "use_domain", 0)
modparam("usrloc", "location_cluster", 1)
```

**Comment by Lt-Flash** [comment]
Still occurs every day.

**Comment by Lt-Flash** [comment]
Looks like this happens only upon restart of the cluster and when usrloc already has records for the contacts that other servers trying to push into usrloc. Upon restart there's a total mess and heaps of these error messages but after a while the cluster calms down.

What I also noticed is that setting 'flags=seed' to only one specific node and removing all modparams that override default cluster timeouts and seed timeout helps too.

**Comment by Lt-Flash** [comment]
Still an issue, restart of one node causes troubles on other nodes and restarted node can't get usrloc data.

**Comment by Lt-Flash** [comment]
Still an issue.
