### ISSUE TITLE
[BUG] Presence NOTIFY generated internally by OpenSIPS does not include complete XML content

### ISSUE THREAD

**Issue by NormB** [OpenSIPS/opensips#3362]
**OpenSIPS version you are running**

```
Running master branch
```

**Describe the bug**

After a multi-line phone has subscribed to an event (BLF) on a line of another phone, a subscription is created.
When the subscribed to line goes off-hook (or answers a call) a NOTIFY is internally generated by OpenSIPS.

The XML content of the NOTIFY is only partially built as show here:

```
Content-Type: application/dialog-info+xml

<?xml version="1.0"?>
<dialog-info xmlns="urn:ietf:params:xml:ns:dialog-info" version="0"           state="full" entity="sip:1000@example.com"/>

```

Enabling DEBUG logging shows that the same error message is produced in two spots about no record existing in the hash_table.

notify_body.c / build_dialoginfo():
```
	if (pres_contains_presence(&pres_uri) < 0) {
		LM_DBG("No record exists in hash_table\n");
		goto error;
	}
```

notify.c / get_p_notify_body()
```
if( !etag && p== NULL)
	{
		LM_DBG("No record exists in hash_table\n");
		if(!fallback2db)
		{
			/* we do not have the presentity */
```

The command "opensips-cli -x mi subs_phtable_list" does indicate that the subscription exists.
The command "opensips-cli -x mi pres_phtable_list" does show that the presentity table is empty (so, it makes sense that the error is being triggered).

It is possible that opensips.cfg is not correctly populating the presentity table.  The phones, even after a reboot do not send PUBLISH requests to OpenSIPS. However, given that handle_subscribe()/handle_publish() take very few parameters, I don't think this is the case.

The mix_dialog_presence setting is enabled.

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by NormB** [comment]
69.x.x.x == OpenSIPS IP
Line 701 == Call Park defined on a Yealink phone

* An active call can be "parked" on Line 701.
* The process of "parking" will cause the Yealink to send a REFER to OpenSIPS
* OpenSIPS will route the REFERed INVITE to Asterisk.
* Asterisk has a dynamically created parking lot that is named 701
* Asterisk receives the call to 701 and successfully parks it.

The Line 701 does not register with OpenSIPS.
Because Asterisk is using a dynamically created parking lot for 701, Asterisk does not send a PUBLISH to OpenSIPS when a call is actively parked.
Without a PUBLISH from Asterisk, it seems that OpenSIPS is not able to correctly create a NOTIFY to be sent back to the Yealink.

The high-level flow is

Signaling:
```
Yealink (call park configured like 701) <--> OpenSIPS <--> Asterisk (dynamic parking lot for 701)
```
Media:
```
Yealink (call park configured like 701) <--> RTPEngine <--> Asterisk (dynamic parking lot for 701)
```

Example NOTIFY with XML incomplete:
```
2024/04/25 15:40:03.360303 69.x.x.x:5060 -> 69.y.y.y:65477
NOTIFY sip:1104@69.y.y.y.y:65477 SIP/2.0
Via: SIP/2.0/UDP 69.x.x.x:5060;branch=z9hG4bK4454.ce546f51.0
To: <sip:1104@planet.net>;tag=1134174125
From: <sip:701@planet.net>;tag=7e82.b19aad77fc293c42bed084c68bfd8583
CSeq: 72 NOTIFY
Call-ID: 0_1134261060@10.z.z.z
Max-Forwards: 70
Content-Length: 143
User-Agent: OpenSIPS (3.5.0-dev (x86_64/linux))
Event: dialog
Contact: <sip:presence@69.x.x.x>
Subscription-State: active;expires=30
Content-Type: application/dialog-info+xml

<?xml version="1.0"?>
<dialog-info xmlns="urn:ietf:params:xml:ns:dialog-info" version="71"          state="full" entity="sip:701@planet.net"/>


```

**Comment by bogdan-iancu** [comment]
That XML is a fully formatted complete XML and it may be a response to an initial SUBSCRIBE if there are no calls for the subscriber user – as RFC says that a NOTIFY must be sent when a new subscription is created, if there is no actual presence data to be sent, such a info-less XML is sent – like “I hear you, but no info to provide”
