### ISSUE TITLE
[BUG] Dialog callbacks not being called for reply in early dialog

### ISSUE THREAD

**Issue by tijmenNL** [OpenSIPS/opensips#3366]
**OpenSIPS version you are running**

```
1.11+git20170503.d3782be,  but probably still present/applies to current trunk
```

**Describe the bug**

SDP address is not rewritten by Mediaproxy in a 200 OK for UPDATE (early dialog) before 200 OK for INVITE in the following flow for a call with 100rel enabled: 

...
caller <- 183 with early media (callee)
caller -> PRACK
caller <- 200 OK for PRACK
caller <- UPDATE (with SDP, address gets rewritten)
caller -> 200 OK for UPDATE (with SDP, address is not rewritten)
caller <- 200 OK for INVITE
caller -> ACK
...

**To Reproduce**
Follow the above scenario

**Expected behavior**
The mediaproxy module subscribes to DLGCB_RESPONSE_FWDED | DLGCB_RESPONSE_WITHIN and neither is called for the 200 OK for UPDATE in early dialog. In the 'normal' OpenSIPS logic we get to the dialog reply route. 

I checked with full debug mode on and I don't see DBG:dialog:run_dlg_callbacks in this case.

On the 200 OK for INVITE I see:
DBG:dialog:push_reply_in_dialog: 0x7f10b9021280 totag in rpl is <127.0.0.1alUtKGp-08100+1+70bc00b2+c2592c3> (41)
..
DBG:dialog:run_dlg_callbacks: dialog=0x7f10b9021280, type=256

**Relevant System Logs**

**OS/environment information**
 - Operating System: Debian 10

**Comment by bogdan-iancu** [comment]
Is an UPDATE (sequential request) legal in early state ??

**Comment by tijmenNL** [comment]
I think so. 

See https://www.rfc-editor.org/rfc/rfc3311#section-5.1 and https://www.rfc-editor.org/rfc/rfc3311#section-8 the example. However in this case the callee sends the UPDATE.

**Comment by tijmenNL** [comment]
Please reopen, nothing is changed
