### ISSUE TITLE
[BUG] When quickly using jsonrpc client to request opensips mi httpd service, sometimes the results cannot be obtained immediately

### ISSUE THREAD

**Issue by gao114882** [OpenSIPS/opensips#3369]
**OpenSIPS version you are running**

```
[root@opensips opensips]# ./opensips -V 
version: opensips 3.3.10 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 08:54:55 Apr 16 2024 with gcc 4.8.5
```

**Describe the bug**

 When I used opensips-cli to request opensips mi cache_store through http, I found that when calling the request quickly, the result cannot be returned  immediately。

[root@localhost ~]# opensips-cli -x mi cache_store local test1 a       //right
"OK"
[root@localhost ~]# opensips-cli -x mi cache_store local test1 a      //right
"OK"
[root@localhost ~]# opensips-cli -x mi cache_store local test1 a    //right
"OK"
[root@localhost ~]# opensips-cli -x mi cache_store local test1 a       //wrong, can't get result.

^C^C
[root@localhost ~]# 

then, I create a jsonrpc http client with golang， the situation is the same, besides opensips logs is same。 

**To Reproduce**

**Expected behavior**

**Relevant System Logs**

Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: START *** cls=(nil), connection=0x2812330, url=/mi, method=POST, versio=HTTP/1.1, upload_data[0]=(nil), *con_cls=(nil)
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: running MHD_create_post_processor
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: pr=[0x7faf27e5a4d0] pp=[(nil)] p_list=[0x7faf27e5a528]
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: START *** cls=(nil), connection=0x2812330, url=/mi, method=POST, versio=HTTP/1.1, upload_data[120]=0x28125df, *con_cls=0x7faf27e5a4d0
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: NOT a regular POST :o)
Apr 22 14:57:15 [9] DBG:httpd:getConnectionHeader: key=[User-Agent] value=[Go-http-client/1.1]
Apr 22 14:57:15 [9] DBG:httpd:getConnectionHeader: Content-Length=120
Apr 22 14:57:15 [9] DBG:httpd:getConnectionHeader: Content-Type=application/json
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: got ContentType [3] with len [120]: {"jsonrpc":"2.0","method":"cache_store","params":["local","test111111","a"],"id":"d52f95cb-4950-4982-9bac-2fdced2b6b09"}
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: START *** cls=(nil), connection=0x2812330, url=/mi, method=POST, versio=HTTP/1.1, upload_data[0]=(nil), *con_cls=0x7faf27e5a4d0
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: normalised_url=[]
Apr 22 14:57:15 [9] DBG:mi_http:mi_json_answer_to_connection: START *** cls=(nil), connection=0x2812330, url=, method=POST, version=HTTP/1.1, upload_data[120]=0x7faf27e5a5b1, *con_cls=0x7faf27e5a528
Apr 22 14:57:15 [9] DBG:mi_http:mi_http_run_mi_cmd: got command=cache_store
Apr 22 14:57:15 [9] DBG:core:cachedb_store: from script [local] - no grp
Apr 22 14:57:15 [9] DBG:mi_http:mi_http_run_mi_cmd: got mi response = [0x281a790]
Apr 22 14:57:15 [9] DBG:mi_http:mi_json_answer_to_connection: building on page
Apr 22 14:57:15 [9] DBG:httpd:answer_to_connection: MHD_create_response_from_data [0x7faea083c010:75]

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by gao114882** [comment]
still exists

**Comment by liviuchircu** [comment]
Hello @gao114882 and thanks for the report!  Your problem strongly resembles a well-known issue around libmicrohttpd that is fully documented [here](https://opensips.org/docs/modules/3.5.x/httpd.html#dependencies_libs).

In short, make sure you have at least libmicrohttpd `0.9.72` running on your system, past which the HTTPD server should no longer block.  The core problem is related to a bug in the library, between versions `0.9.53 - 0.9.71`.  Closing as "solved" for now.

**Comment by gao114882** [comment]
thinks, I should read the opensips module more Carefully。
