### ISSUE TITLE
nathelper: track SIP OPTIONS reply time

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#337]
It would be good to track how long it takes for a SIP reply to come back to OpenSIPS by having access to:
 - SIP OPTIONS request send timestamp;
 - SIP OPTIONS reply received timestamp.
Since this is per binding, the two timestamps could be saved in the in memory usrloc table.

**Comment by ionutrazvanionita** [comment]
Hi @ovidiusas. We've done the basics[0] and we would like future improvements to be discussed in a separate issue. I will close this one. 

[0] http://lists.opensips.org/pipermail/users/2015-October/032728.html
