### ISSUE TITLE
[BUG] PUA - pua.c does not have the logic to insert or update the DB with the cluster_sharing_tag

### ISSUE THREAD

**Issue by NormB** [OpenSIPS/opensips#3377]
**OpenSIPS version you are running**

```
version: opensips 3.5.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: e58da5e15
main.c compiled on 17:20:31 Apr 26 2024 with cc 12
```

**Describe the bug**

The Presence User Agent module is defined as follows:
```
loadmodule "pua.so"
modparam("pua", "db_table", "pua")
modparam("pua", "db_url", "xxx")
modparam("pua", "cluster_id", 1)
modparam("pua", "cluster_sharing_tag", "1")
```
A review of the "pua" table in the database shows that the "sharing_tag" column is not populated.

A review of pua.c shows that the code to perform a DB insert or update does not include the "sharing_tag" column.

**To Reproduce**

**Expected behavior**

It is expected that the "sharing_tag" column in the "pua" table is populated with the correct "cluster_sharing_tag".

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by NormB** [comment]
On a related note, the active_watchers table has a "sharing_tag" column that is also not populated.

**Comment by bogdan-iancu** [comment]
@NormB , could you please check the above fix if solves the problem for you too? If so, I will do the backport.

**Comment by NormB** [comment]
Confirmed that the fix correctly populates the pua.sharing_tag column.

**Comment by bogdan-iancu** [comment]
backports to 3.4 and 3.2 done, thank you @NormB
