### ISSUE TITLE
[BUG] debian package builder fails when pkg build limit list does not include BERKELEY

### ISSUE THREAD

**Issue by rrevels-bw** [OpenSIPS/opensips#3389]
**OpenSIPS version you are running**

```
opensips_3.2.18-1  (no running install yet)
```

**Describe the bug**

When using a limited package build list that does not include BERKELEY like this:
`make deb DEBBUILD_EXTRA_OPTIONS="-uc -us" INSTALL_PREFIX='/usr/local/opensips' BUILD_MODPKG_LIST='MYSQL RADIUS REGEX DIALPLAN JSON HTTP REST_CLIENT PROMETHEUS KAFKA' `

the package build process fails with:
```
# move binaries of opensips-berkeley-module to opensips-berkeley-bin
mkdir -p /opt/build/opensips/debian/opensips-berkeley-bin//usr/local/opensips/
mv /opt/build/opensips/debian/opensips-berkeley-module//usr/local/opensips/sbin \
	/opt/build/opensips/debian/opensips-berkeley-bin//usr/local/opensips/
mv: cannot stat '/opt/build/opensips/debian/opensips-berkeley-module//usr/local/opensips/sbin': No such file or directory
make[2]: *** [debian/rules:365: override_dh_auto_install] Error 1

```

This does not happen if BERKELEY is added to the list

**To Reproduce**

1. git clone https://github.com/OpenSIPS/opensips.git -b 3.2
2. cd opensips/
3. make deb-orig-tar
4. make deb DEBBUILD_EXTRA_OPTIONS="-uc -us" INSTALL_PREFIX='/usr/local/opensips' BUILD_MODPKG_LIST='MYSQL RADIUS REGEX DIALPLAN JSON HTTP REST_CLIENT PROMETHEUS KAFKA'

**Expected behavior**

build doesnt fail

**Relevant System Logs**

**OS/environment information**
 - Operating System:  Debian 12.5
 - OpenSIPS installation:  
 - other relevant information:

**Additional context**

This isn't a bug but I'm also wondering if there is a make command line option to instruct the deb build process to give me the single package with all modules built included or i have to modify the rules and control files and such.

**Comment by rrevels-bw** [comment]
actually, nevermind that Additional context question.   it looks like im getting what i want just using what i have already.

**Comment by razvancrainea** [comment]
@rrevels-bw you're right, if the Berkeley packages are not built, they should not interfere with the other packages.
I will soon push a fix for this on all branches.

**Comment by rrevels-bw** [comment]
Thank You!
