### ISSUE TITLE
drouting limits prefixes to digits 0-9 only

### ISSUE THREAD

**Issue by mark-webster** [OpenSIPS/opensips#339]
This is not very useful. Alphanumeric SIP user fields are very common, and what about E.164 numbers with '+' prefix? Even OpenSER 1.x supported alphanumeric prefixes.

Please can we:
- alter the check for "IS_DECIMAL_DIGIT" in modules/drouting/prefix_tree.c
- increase PTREE_CHILDREN to 40
- use a look-up table to map 0123456789abcdefghijklmnopqrstuvwxyz+-%

_ to values 0-39

If you prefer, I can submit a patch?
https://gist.github.com/mark-webster/f876a71b7a9cdbfcd6f2

Thanks!

Edit: or maybe implement prefix lookup as a http://en.wikipedia.org/wiki/Trie

**Comment by bogdan-iancu** [comment]
This was addressed by bd61ef3bf1479b41d579e29152f87e997d9d0886

**Comment by peteroyle** [comment]
> This was addressed by [bd61ef3](https://github.com/OpenSIPS/opensips/commit/bd61ef3bf1479b41d579e29152f87e997d9d0886)

Hi @bogdan-iancu, thanks for coding this up! Does that commit have a PR, or some other way I can track its eventual merging into a master/version branch please?

**Comment by bogdan-iancu** [comment]
@peteroyle, that commit is already part of the upcoming 3.1 release.

**Comment by peteroyle** [comment]
OK thanks for clarifying, I was looking for it in the 2.x branches (wishful thinking 😉)
