### ISSUE TITLE
[BUG]OpenSIPS 3.2 Acc module, extra_fields set value failed

### ISSUE THREAD

**Issue by nwaycn** [OpenSIPS/opensips#3398]
**OpenSIPS version you are running**
```
```
version: opensips 3.2.18 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: b887624
main.c compiled on 03:46:29 May 22 2024 with gcc 4.8.5
```

```

**Describe the bug**
When I configured in my configuration file opensips.cfg
```
modparam("acc", "extra_fields", "db:src_user->src_user; src_domain->src_domain;  dst_user->dst_user;  dst_domain->dst_domain; record_file->record_file") 

###And after I received the INVITE message
                
do_ accounting ("db", "cdr");
        
$acc_extra (src_user)=$fU;
$acc_extra (src_domain)=$fd;
$acc_extra (dst_user)=$rU;
$acc_extra (dst-domain)=$rd;
$acc_extra (record_file)=$var (record_full_path);
```

The following error occurred when reloading the configuration file

```
May 27 21:54:44 localhost opensips[15307]: ERROR:acc:pv_parse_acc_extra_name: tag <src_user> not declared in modparam section!
May 27 21:54:44 localhost opensips[15307]: ERROR:core:pv_parse_spec: pvar "acc_extra" has an invalid name param [src_user]
May 27 21:54:44 localhost opensips[15307]: ERROR:core:pv_parse_spec: wrong char [)/41] in [$acc_extra(src_user)] at [19 (5)]
May 27 21:54:44 localhost opensips[15307]: CRITICAL:core:yyerror: parse error in /root/nway_opensips.cfg:452:17-37: unknown script variable
May 27 21:54:44 localhost opensips[15307]: ERROR:core:parse_opensips_cfg: bad config file (1 errors)
May 27 21:54:44 localhost opensips[15307]: ERROR:core:reload_routing_script: parsing failed, abording
```

**Comment by bogdan-iancu** [comment]
1) remove the space you have between the `$acc_extra` and the brackets. 
2) see the typo in the `dst-domain` versus `dst_domain`

Tested and it works for me
