### ISSUE TITLE
[BUG] drop_requests statistic growing when used with b2b_init_request

### ISSUE THREAD

**Issue by gjonikas** [OpenSIPS/opensips#3416]
**OpenSIPS version you are running**
```
3.3.2
```

**Describe the bug**

I'm using b2b to bridge two calls together. 

The packets that b2b generates ends up going through local_route and receive.c receive_msg() function, where due to `rc == SCB_DROP_MSG`, drp_reqs is incremented by 1.

```
		if (rc == SCB_DROP_MSG) {
			update_stat( drp_reqs, 1);
			goto end; /* drop the message */
		}
```

I think this behavious is confusing because drop_requests statistic going up seems like an error case, whereas it happens normally when used with b2b.

**To Reproduce**
use b2b_init_request and check drop_requests statistic 

**Expected behavior**
a normal call that succeeded should not increase the statistic

**Additional context**
If this behaviour is as expected, it would be very useful if we could update the docs to call this out

**Comment by bogdan-iancu** [comment]
I agree that this is not right, but I would say that the base of the transaction implementation (like a reply being dropped as consumed by other module) is not correct.
IMHO I would either remove this statistic (as it is confusing) , either try to hook it to the "drop" script statement.
