### ISSUE TITLE
[BUG] B2BUA does not add < > brackets in generated To-Headers for reponses (for requests this was fixed, cf. issue 2843)

### ISSUE THREAD

**Issue by bhoeneis** [OpenSIPS/opensips#3419]
## Summary Feature Request Description

The bug described in https://github.com/OpenSIPS/opensips/issues/2843 has not been fixed for replies. I run into a case with a 407 reply (to an INVITE request, via B2BUA), where he SIP-URI of the  To Header Field is still not enclosed in angle brackets (<....>) as in the following example (A calls B via a B2BUA):

- In (from B): `To: <sip:0123456789@example.com>;tag=8e14b31b8709851a3d139fba84110914.5f1bdd99` 
- Out: (to A) `To: sip:0123456789@example.com;tag=B2B.256.222.1718881474.159853479`

## Reproduce Behavior:

- Relevant Parts of Configuration:

  ```
  [...]
  loadmodule "b2b_entities.so"
  loadmodule "b2b_logic.so"
  modparam("b2b_entities", "script_req_route", "b2b_request")
  modparam("b2b_entities", "script_reply_route", "b2b_reply")
  modparam("b2b_logic", "custom_headers", "Proxy-Authenticate;Test")

  route{
      [...]
      if (  is_method("INVITE") && !has_totag() ) {
          b2b_init_request("top hiding");
          exit;
      } 
      [...]
  }

  route[b2b_request] {
      xlog("b2b_request ($ci)\n");
  }

  route[b2b_reply] {
     xlog("b2b_reply ($ci)\n");
  }

  [...]
  ```
- Steps to reproduce behavior
  1. Start OpenSIPS (containing above B2BUA "top hiding" configuration)
  2. A sends an INVITE to B
  3. Proxy sends back a "407 Proxy Authentication Required" response 
  4. Inspect traces
  5. Look at the To Header Field

## Expected behavior

- In (from B): `To: <sip:0123456789@example.com>;tag=8e14b31b8709851a3d139fba84110914.5f1bdd99` 
- Out: (to A) `To: <sip:0123456789@example.com>;tag=B2B.256.222.1718881474.159853479`

## Observed behavior

- In (from B): `To: <sip:0123456789@example.com>;tag=8e14b31b8709851a3d139fba84110914.5f1bdd99` 
- Out: (to A) `To: sip:0123456789@example.com;tag=B2B.256.222.1718881474.159853479`

## Relevant System Logs

N/A

## OS/environment information

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

$ uname -a
Linux imp-test 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ opensips -V
version: opensips 3.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 099e771b3
main.c compiled on  with gcc 13
```

## Additional context

- Related Bug report: https://github.com/OpenSIPS/opensips/issues/2843
- Related Commit: https://github.com/OpenSIPS/opensips/commit/9af192693f419751ff3fc704d5286274752171b1

Note that this bug appears to have been fixed only for requests, but not replies

**Comment by bogdan-iancu** [comment]
could you post (or PM me) a sip capture showing all the SIP req/rpl getting in and out of OpenSIPS B2B? I'm asking as the B2B entities module is sending the replies (back to UAC) into a transactional way, by using TM (which uses the transaction of the originally received INVITE)

**Comment by bhoeneis** [comment]
This is not really a bug, as it is correct according to RFC 3261. However, in the past I met badly programmed UAs that would justify adding angle brackets (<....>) as many UAs do.

I therefore amended the (automatic) qualification in the issue title from BUG to FEATURE.
