### ISSUE TITLE
[FEATURE] Can uac_auth using realm in challenge instead of specific by user

### ISSUE THREAD

**Issue by okhowang** [OpenSIPS/opensips#3428]
**Describe the solution you'd like**
I'm using `uac_auth` for authenticate to some other service.
the realm parameter is necessary now. I need to set realm in module parameters or AVP.
But in the real world, the realm may change even with the same service (by some incorrect setup, maybe). 

**Implementation**
 
  - Component: `uac`
  - Type: func
  - Name: `uac_auth`
`uac_auth` can got a flag indicate that using realm in UAS 401/407 response instead of specific by user.

**Describe alternatives you've considered**
there is no func in script which can parse realm from authenticate header.
I must use regex to get realm from response header (it looks ugly).

**Additional context**

**Comment by bogdan-iancu** [comment]
Shouldn't [$ar](https://www.opensips.org/Documentation/Script-CoreVar-3-5#ar) five you the info you need ?

**Comment by okhowang** [comment]
`$ar` `$ad` is for Authorization header which is the part of SIP request.
the issue is about how `uac_auth` handle `WWW-Authenticate`/`Proxy-Authenticate` header in SIP response.

**Comment by bogdan-iancu** [comment]
That's correct, indeed. Nevertheless, the grammar for the Authorization and Authentication hdrs looks the same, IMHO

**Comment by okhowang** [comment]
but there is no builtin variable like $ar $ad for WWW-Authenticate/Proxy-Authenticate header in SIP response.

**Comment by okhowang** [comment]
How about this
> uac_auth can got a flag indicate that using realm in UAS 401/407 response instead of specific by user.

for example
```
if (t_check_status("401|407") {
    uac_auth("AUTO_REALM");
}
```
