### ISSUE TITLE
[BUG] There may be a problem with revision 3.4.6

### ISSUE THREAD

**Issue by XNXSIL** [OpenSIPS/opensips#3436]
**OpenSIPS version you are running**

```
version: opensips 3.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 40206eeef
main.c compiled on  with gcc 10
```

**Describe the bug**

apt-get installs version 3.4.6 and reports an error when starting. `CRITICAL:core:version_control: module version control system revision mismatch for drouting core: 40206eeef module: ab10b68`. The revision 40206eeef is on 3.5. The latest revision of 3.4.6 is ab10b68
**To Reproduce**

1. Patch drouting.so on git 3.4.6 tag
2. apt-get install opensips=3.4.6-1
3. start opensips

**Comment by XNXSIL** [comment]
version: opensips 3.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 3a7a2bdfb
main.c compiled on  with gcc 10

3.4.1 Have the same problem，3a7a2bdfb revision is in  3.1 tag

**Comment by XNXSIL** [comment]
In the makefile, @echo $(THISREVISION) shows ab10b68. Is it because the git version is wrong when packaging?

**Comment by razvancrainea** [comment]
Can you send us the output of the following commands:
```
opensips -V
dpkg -l opensips
```

Also, what do you mean by "Patch drouting.so"?

**Comment by XNXSIL** [comment]
`opensips -V
`
version: opensips 3.4.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 40206eeef
main.c compiled on  with gcc 10

`dpkg -l opensips`
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================
ii  opensips       3.4.6-1      amd64        very fast and configurable SIP server


The revision of drouting.so generated by make modules="modules/drouting" in the 3.4.6 branch is ab10b68, but the revision of the deb package is 40206ee. This causes the compiled drouting.so library to fail to load properly. When starting opensips, an error message "revision mismatch" is displayed

**Comment by razvancrainea** [comment]
@XNXSIL you may be right, I think the building/deb system is "inheritting" leaked git information from other branches. Searching for a fix now, will update here when available.

**Comment by razvancrainea** [comment]
I've just fixed the building system to properly propagate the version for stable releases, thanks for pointing the issue out.
I've now rebuilt all supported affected versions. You should get a 3.4.6-2 with the correct version.
Thanks again for spotting the issue and reporting it!

**Comment by XNXSIL** [comment]
3.4.7 also has this problem, please help to check it
