### ISSUE TITLE
[FEATURE] Rtpengine keepalive function 

### ISSUE THREAD

**Issue by volga629-1** [OpenSIPS/opensips#3440]
Hello Everyone,
I have small request to add rtpengine function to test if rtpengine node is alive from script level.
Might be as improvement will be possible to use  $avp(setid) or  mod params.

New function

Options 
1. rtpengine control socket ip
2. result avp 
3.  amount probes to send ( default 2)  

```
option 1 
$avp(rtp_ip) = "10.10.10.1";
rtpengine_probe("$avp(rtp_ip)","$avp(probe)",2);
if($avp(probe)>=0) {
      xlog("[RTP_PROBE] Rtpengine probe failed with return values $$avp(probe) | $avp(probe)\n");
}
```

**Comment by volga629-1** [comment]
In progress

**Comment by volga629-1** [comment]
in progress

**Comment by volga629-1** [comment]
in progress

**Comment by razvancrainea** [comment]
Starting with OpenSIPS 3.6, using the new [ping_enabled](https://opensips.org/docs/modules/3.6.x/rtpengine.html#param_rtpengine_ping_enabled) parameter you can constantly ping each RTPEngine node, and catch when it is disabled using the [E_RTPENGINE_STATUS](https://opensips.org/docs/modules/3.6.x/rtpengine.html#event_E_RTPENGINE_STATUS) event. Can't you use these mechanisms to implement your functionality?

**Comment by volga629-1** [comment]
Hello @razvancrainea ,
How will be possible to detect fail state in event route ?

**Comment by volga629-1** [comment]
in progress
