### ISSUE TITLE
[BUG] natping_tcp makes fragmented packets wrong

### ISSUE THREAD

**Issue by firestation** [OpenSIPS/opensips#3454]
Hi, seems i found some bug in TCP/TLS cases. 

In short: when natping_tcp and "natping_interval" enabled, opensips makes TCP packets fragmented even it's less 1500. But, also, as i understood it makes wrong fragmentation. 

To reproduce this bug you just need Alice(udp) and Bob(tcp) on vanilla opensips server configuration.
then add nathelper with  "natping_tcp" and "natping_interval" options enabled. 
then most of call to from Alice to Bob will cause error on Bob side. 
if bob is pjsip :  "Error processing 914 bytes packet from TCP x.x.x.x:5061 : PJSIP syntax error exception when parsing 'Request Line' header on line 1 col 1:" and does not respond any on sip level. 
if bob is baresip: it will return "400 Bad" 

in both cases sngrep will show correctly TCP SIP messages sended to Bob.  
Wireshark show 2 packets: first with 58 data and then SIP packet with info "Continuation Data". 

I have tested it on 3.3 and 3.4 Opensips from official repo. 
OS is oracle 9 and oracle 8, also tested on Debian 12 - the same issue

**Comment by firestation** [comment]
It's not related on network level, because i have tested on local interface(127.x.x.x) also.

**Comment by bogdan-iancu** [comment]
@firestation , OpenSIPS does not do any fragmentation - this is done by the TCP/IP stack at OS level (and not application level).
BTW, do you have [the SIP Ping enabled](https://opensips.org/html/docs/modules/3.4.x/nathelper.html#param_sipping_bflag)  ?
