### ISSUE TITLE
Crash when receiving 180 (RING)

### ISSUE THREAD

**Issue by Guima-tip** [OpenSIPS/opensips#3475]
**OpenSIPS version you are running**

version: opensips 3.1.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 41d57ac56
main.c compiled on 15:01:31 Nov  3 2021 with gcc 6.3.0

**Describe the bug**

Opensips crash when receving 180 (RING) with Message Body  MIME Type: multipart/mixed, Boundary: OSS-unique-boundary-42 
**To Reproduce**

**Expected behavior**

**Relevant System Logs**

**OS/environment information**
 - Operating System: Debian 9
 - OpenSIPS installation: git clone https://github.com/OpenSIPS/opensips.git -b 3.1 opensips-3.1

**Additional context**

**Comment by bogdan-iancu** [comment]
Could you please provide a full complete backtrace of the crash (see https://opensips.org/Documentation/TroubleShooting-Crash) ?
