### ISSUE TITLE
[BUG]usrloc replication error: differring rlabels (0 vs. 1, ci: 'b7b3f2f3-38f32b64@192.168.10.87')

### ISSUE THREAD

**Issue by mdu113** [OpenSIPS/opensips#3523]
Hello, 

I've recently migrated my system to 2-node usrloc full-sharing cluster. Now occasionally I receive the following error on the receiving side:

CRITICAL:usrloc:receive_ucontact_insert: 
>>> differring rlabels (0 vs. 1, ci: 'b7b3f2f3-38f32b64@192.168.10.87')
It seems you have hit a programming bug.

Config is standard:
#### Clusterer Module
loadmodule "clusterer.so"
modparam("clusterer", "my_node_id", 2)
modparam("clusterer", "db_mode", 0)
modparam("clusterer", "sharing_tag", "vip1/1=backup")
modparam("clusterer", "seed_fallback_interval", 10)
modparam("clusterer", "my_node_info", "cluster_id=1, url=bin:x.x.83.70:5555, flags=seed")
modparam("clusterer", "neighbor_node_info", "cluster_id=1,node_id=1,url=bin:x.x.83.69:5555")
#
#### USeR LOCation module
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT_BFLAG")    #NAT bflag saved in usrloc, used to indicate nat
modparam("usrloc", "desc_time_order", 1)        #location records are kept timestamp ordered. most recent 1st
modparam("usrloc", "cseq_delay", 10)
modparam("usrloc", "hash_size", 14)                                             #2^14 - 16356 hash entries
modparam("usrloc", "location_cluster", 1)
modparam("usrloc", "cluster_mode","full-sharing")
modparam("usrloc", "working_mode_preset", "full-sharing-cluster")

Opensips version:
root@csp-p1n2:~# /usr/local/opensips3/sbin/opensips -V
version: opensips 3.4.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: cd02af8d9
main.c compiled on 13:57:28 Nov 18 2024 with gcc 5.5.0

Please let me know if you need any other info.
Thanks,
Michael Ulitskiy

**Comment by liviuchircu** [comment]
Hi @mdu113!  This issue has been fixed and backported down to `3.4` branch, to become available via release packaging for `3.4.10` minor release within a couple weeks from today.
