### ISSUE TITLE
dispatcher: broken max results in multilist mode

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#359]
ds_select_domain/dst is not working with max results in multilist mode:
ds_select_domain(" 101,  100", "1 , 4  ", "F M 5 9")

ERROR:dispatcher:get_flags_int_value: Invalid flags PV value
ERROR:dispatcher:w_ds_select: Invalid value in flags PV

Mixing the flag(s) with max results is very confusing.
It would be better to have distinct arguments for flags and max results.

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/000ff3402fa63ffa0e2b4916db103d1763dc9fba
