### ISSUE TITLE
Multiple route parameters bug

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#361]
Supposing we have our `test_route` and we want to pass two pseudo-vars:

```
route(test_route, $fU, $rp);
```

This will fail with:
Oct 16 17:35:01 [30466] CRITICAL:core:yyerror: parse error in config file etc/mine.config, line 270, column 28-32: syntax error
Oct 16 17:35:01 [30466] CRITICAL:core:yyerror: parse error in config file etc/mine.config, line 270, column 32-33: bad routeargument

From the looks of it, the bug seems to be located in the parser, specifically in the code that parses a "SCRIPTVAR" token (cfg.lex +823). The parsing looks too simple, and it seems to fail to detect the comma, thus causing a pv parsing error!

To reinforce the above statement, note that `route(test_route, $fU)` actually works.

Version: 1.8+

**Comment by nud** [comment]
FYI the same problem happens with 1.11
