### ISSUE TITLE
avpops: Allow a per query timeout in milliseconds

### ISSUE THREAD

**Issue by brettnem** [OpenSIPS/opensips#363]
For some specific in call queries, I need to specify a timeout. Basically, if I don't get a result in Xms, then give up and continue as if the database returned an errored resultset. I know there is timeout_interval, however, that is an integer value and is for each retry. I'm requesting an overall timeout.

It may also be useful to return something specific to indicate the result is empty due to a timeout. 

Use case here is for call routing lookups. If the lookup doesn't return in Xms, the call isn't routable, Excessive PDD isn't acceptable and I'd rather fail the call then hang children waiting for a response.

**Comment by razvancrainea** [comment]
This thread is quite old, and indeed it is not that easy to implement the feature. I will close the ticket for now, and if there are any specific issues that can be solved with this, please re-open the ticket.
