### ISSUE TITLE
nathelper: double oldmediaip attribute while fix_nated_sdp()

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#377]
If fix_nated_sdp() is called with flags that require rewrite of media IP (c=) and origin IP (o=) then oldmediaip attribute is added twice.

We should have different attributes to distinguish between the two replaced IPs or keep the same attribute with an extra value:
 - for connection IP:
   - a=oldcmediaip=IP
   - a=oldmediaip=IP;c
 - for origin IP:
   - a=oldomediaip=IP
   - a=oldmediaip=IP;o

Also, we should have flags to control the addition of this attribute.  In some cases we don't need the old value and we want to keep the size of the SDP small.

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/01a1bfe010b69d7dce3cb2851bb45dad584d255d
