### ISSUE TITLE
load_credentials parameter does not work properly when AVP is not specified

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#385]
If the AVP name is not specified in the load_credentials parameter, the wrong AVP is populated, namely the last one used. That's because `avp_name` is not properly reset after each iteration.

**Comment by ionutrazvanionita** [comment]
Indeed avp_name was not restored after parsing an elemenet of the list, so the old known value for an avp was used. https://github.com/OpenSIPS/opensips/commit/b69ae3258faff194c28a6277d52fa318c24ed37a

**Comment by bogdan-iancu** [comment]
Is the fix tested and complete ? if so you should consider cherry-picking it all the way back to 1.8
