### ISSUE TITLE
Dispatcher strange balancing

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#387]
Hi,

I have a dispatcher group with 30 destinations. When all are active the spreading of load is good.
When I disable one of these destinations through opensipsctl fifo ds_set_state. 
One seemingly random destination gets double the load that is normally handled by one destination, instead of the load being spread over to all remaining destinations. When i re-activate the destination the load on the one destination is back to normal. 
If i disable more than one destination this also seems to be true, I've had one occasion in which one destination got triple the normal load.
So it seems the balancing is borked when i disable a destination.

I'm using the ds_select_domain with algorithm 0.
version: opensips 1.10.3-notls (x86_64/linux)
git revision: 13a3a4c

If you need any more information please tell.

**Comment by bogdan-iancu** [comment]
Hi @hydrosine , there is an extensive fix available on master branch see (444b680) - I did several tests, but if you could do the same, it will be great. 
I know the report is for 1.11.x - if you cannot do the backport, let me know and I will do it for you. But before doing an official fix on 1.11, I want to have your confirmation that my fix id addressing your problems.

**Comment by bogdan-iancu** [comment]
Hi @hydrosine  - any feedback ?

**Comment by hydrosine** [comment]
woops completely missed it. I'll be back with results soon.

**Comment by hydrosine** [comment]
I can't figure out how to apply the patch on my opensips,
I'm at 1.10.3 git revision: 13a3a4c

I could also upgrade to 1.11

**Comment by liviuchircu** [comment]
Backported to 1.11 (4cb026c8) and also tested with Call-ID hashing algorithm 0. Behaved well in all corner-cases. @hydrosine, please re-open should you find any further issues.

**Comment by hydrosine** [comment]
Re-opening.

1.10.4 release, 2 april 2015 tar.gz from website.
Case: 2 sets of 30 destinations. None inactive.
Algorithm 0, so hash over call-id.

Observed behaviour after around 36 hours.
First destination had at some point 600 channels,
second destination 300 - 400
third 200
fourth 100
fifth 60
and this keeps going till the twelfth, fourteenth destination, all destinations after that didn't seem to handle any calls.

All calls initially get dispatched to the first location until this one can no longer handle it, then the failure_route kicks in and dispatches to the following location. I have logs to back up this behaviour.

My development environment is not large enough to simulate with this many destinations.

As this is 1.10.4 maybe remove the backport from it? I don't know if this is 1.10.4 only or also exists in 11 and 2.1.

**Comment by hydrosine** [comment]
Re-opening.

1.10.4 release, 2 april 2015 tar.gz from website.
Case: 2 sets of 30 destinations. None inactive.
Algorithm 0, so hash over call-id.

Observed behaviour after around 36 hours.
First destination had at some point 600 channels,
second destination 300 - 400
third 200
fourth 100
fifth 60
and this keeps going till the twelfth, fourteenth destination, all destinations after that didn't seem to handle any calls.

All calls initially get dispatched to the first location until this one can no longer handle it, then the failure_route kicks in and dispatches to the following location. I have logs to back up this behaviour.

My development environment is not large enough to simulate with this many destinations.

As this is 1.10.4 maybe remove the backport from it? I don't know if this is 1.10.4 only or also exists in 11 and 2.1.

**Comment by bogdan-iancu** [comment]
@liviuchircu  will do some tests to see what's going on

**Comment by bogdan-iancu** [comment]
I was able to reproduce the problem, working on it now.

**Comment by bogdan-iancu** [comment]
Actually, false alarm (I did not reproduce it), my setup was a bit wrong. 
I created a set with 6 destinations and pushed thousands of calls to it - all where properly dispatched (randomly according to call-id).
If I go back to your report: should I understand that everything is ok in the first 36 hours and after that you have a dispatching hitting all the time the first destinations ? Have you checked with "ds_list" what is the status of your destinations ?

**Comment by hydrosine** [comment]
It started happening when the call volume was rising in the morning. on a busier day
The day before was a very calm day in which the load was handled by only one destination. (checked this via the logs) only the first in the list is used. no other machines are hit by opensips.

Monitoring has not triggered any loss of destinations, so all where Active at the time of the error happening, 2 destinations had an Inactive status, but they where in another group.

Failover only started happening when the First destination in the list was too loaded to respond within the 2 second timeout that's set.

I can share you some screens and or configs on IRC.

**Comment by hydrosine** [comment]
So what i have so far observed on opensips 2.1.1:
using 500 invites 0,2 seconds apart using hash over call-id (alg 0) and ds_select_domain("1||2||5","0","FS").
Only thing i switched between restarts was the group in the ds_select_domain.

30 destinations in dispatcher grp2: Only 3 unique!! destinations are used. the first 3. split: 225,227,48
49 destinations in dispatcher grp1. Only 1 unique destination is used. only the first. split: 500
4 destinatiosn in dispatcher grp5. All 4 used. split: 103,85,99,113

So something is still not correct. I have not found out on which number of destinations it breaks, but i guess somewhere between 6 and 30!

**Comment by hydrosine** [comment]
Found out that it is caused by a wrongly structured mysql view based on the dispatcher table.

In our view of the dispatcher the weight column had a structure of VARCHAR. While this is an INT on the default dispatcher table.

To replicate the issue, simply change in the dispatcher table structure the weight from INT(11) to VARCHAR(11).

in both cases there was 1 in the weight column.
