### ISSUE TITLE
MyISAM no longer default

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#399]
The opensipsdbctl with MySQL currently uses MyISAM by default, Which is strange as MySQL moved away from MyISAM in version 5.5

I suggest to let the choice be made by the MySQL server. Or make it an explicit option.

**Comment by hydrosine** [comment]
I would like to add that if one uses a galera cluster.
MyISAM support is not really good in it and can make the cluster crash :)

**Comment by bogdan-iancu** [comment]
OK, we will review which is the best approach - to allow by default the server to chose the engine, but still to have the possibility to force (without editiing files) a specific engine at install time.
