### ISSUE TITLE
usrloc module do not sync correctly DB with memory

### ISSUE THREAD

**Issue by ferrored** [OpenSIPS/opensips#402]
I'm using MySQL v.5.5, Ubuntu 14.04 and openSIPS 1.11.3-TLS (revision: eb9bad1) with the following settings for the module usrloc:

modparam("usrloc", "db_mode", 2) 
modparam("usrloc", "timer_interval", 60) 
modparam("usrloc", "desc_time_order", 1)
modparam("usrloc", "matching_mode", 0) 

The REGISTER messages are processed with the function "save("location","v"))".

I notice that if the UAC changes the call-id header in the REGISTER message (respect to the previous REGISTER messages), the contact and call-id values are updated correctly in memory, but the record in the "location" table (in particular the expires and callid columns) isn't updated (flushed from memory) at the end of the timer interval.
In few words, the timer doesn't flush the modified contact from memory to database, and as a consequence it doesn't delete the contact when it expires.

Thanks in advance

**Comment by ferrored** [comment]
Note:  1.11.2-tls  git revision: ed698c5   works with no problems

**Comment by bogdan-iancu** [comment]
Actually it doesn't work in ed698c5 - the callid is not updated in DB, if you check closer (only the rest of the fields).
Anyhow, please test my fix  - even if it is on master branch, you can take the patch (https://github.com/OpenSIPS/opensips/commit/2fdeba6fa8ee56d256e465f63317785798f7826d.patch) and apply it on 1.11. Let me know if it works for you and I will do the official porting to 1.11 too.

Thanks and regards,
Bogdan

**Comment by ferrored** [comment]
I applied the patch on 1.11 and it works.

Thanks
  Piero

**Comment by bogdan-iancu** [comment]
Thank you @ferrored  - I did all the relevant backports for this fix, closing....
