### ISSUE TITLE
B2B module ignores compact contact-type header (c)

### ISSUE THREAD

**Issue by bbuitenhuis** [OpenSIPS/opensips#403]
the b2b modules adds an new header:
Content-Type: application/sdp

without deleting/updating the existing (compact) header:
c: application/sdp

**Comment by ionutrazvanionita** [comment]
Try applying this patch https://gist.github.com/ionutrazvanionita/688a4c832049997ca62e. Hope it solves your problem!

**Comment by bogdan-iancu** [comment]
@ionutrazvanionita , the best approach is to actually parse ehdrs in a SIP-wise manner : 
                /* use SIP parser to look at what is in the FIFO request */
		memset( &tmp_msg, 0, sizeof(struct sip_msg));
		tmp_msg.len = hdrs->len;
		tmp_msg.buf = tmp_msg.unparsed = hdrs->s;
		if (parse_headers( &tmp_msg, HDR_EOH_F, 0) == -1 )
			return init_mi_tree( 400, "Bad headers", 11);

(see modules/tm/tm.c +473 )

**Comment by bbuitenhuis** [comment]
I believe the bug only occurs in the b2b module. Or is the root cause in tm?

**Comment by ionutrazvanionita** [comment]
@bbuitenhuis It has nothing to do with the tm module, it was only a hint about how to approach the problem!

**Comment by bbuitenhuis** [comment]
I see! Needed coffee ;-)
Thanks!

**Comment by ionutrazvanionita** [comment]
Try this new patch https://gist.github.com/ionutrazvanionita/5b3e722deaeca775acf7, which parses the headers SIP-wisely, which should solve any problem concerning Content-Type parsing.

**Comment by bbuitenhuis** [comment]
@ionutrazvanionita I've patched the patch, but didn't resolve the issue.
In the message still both c: and content-type: headers are present.

I've make sure the patch really patched.
Any thoughts?

**Comment by ionutrazvanionita** [comment]
@bbuitenhuis sorry did a little mistake when searching for the Content-Type header. Try this one https://gist.github.com/ionutrazvanionita/1857e3b27d5c1e4906c1.
