### ISSUE TITLE
OpenSIPs Crash when using db_http module

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#405]
Hi

I have the following env
Debian 64bit
OpenSIPs 1.11.3-notls

I am using MemCached and db_http in order to resolve number portability with the following script

modparam("avpops", "db_url", "5 http://x.x.x.x/services")
modparam("avpops","avp_table","GetNumberRouting")
modparam("cachedb_memcached", "cachedb_url","memcached:first://x.x.x.x/")
modparam("cachedb_memcached", "cachedb_url","memcached:second://x.x.x.y/")
modparam("cachedb_memcached", "exec_threshold", 150000)
modparam("db_http", "SSL", 0)
..........
xlog("Check if the number is in portability cache [$avp(num)]");
if(!cache_fetch("memcached:first","$avp(num)",$avp(net)))
{
   xlog("[$avp(num)] Not in cache 1. Query cache 2.");
   if(!cache_fetch("memcached:second","$avp(num)",$avp(net)))
   {
     xlog("[$avp(num)] Not in cache 2. Doing Query to DB_HTTP");
     avp_db_query("$avp(num)","$avp(net)","5");
   }
}

If the number can not be found at Memcached 1, new query sent to Memcached 2 and if not found there as well, third query is sent to db_http resource.

When happens that I get the following

Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: Check if the number is in portability cache [211xxxxxx]
Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: DBG:core:cachedb_fetch: from script [memcached] - with grp [first]
Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: [211xxxxxx] Not in cache 1. Query cache 2.
Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: DBG:core:cachedb_fetch: from script [memcached] - with grp [second]
Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: [211xxxxxx] Not in cache 2. Doing Query to DB_HTTP
Jan 29 23:12:03 opensips1 /sbin/opensips[5002]: DBG:avpops:ops_dbquery_avps: query [211xxxxxx]
Jan 29 23:12:03 opensips1 /sbin/opensips[5064]: CRITICAL:core:receive_fd: EOF on 10
Jan 29 23:12:03 opensips1 /sbin/opensips[5064]: DBG:core:handle_ser_child: dead child 3, pid 5002 (shutting down?)
Jan 29 23:12:03 opensips1 /sbin/opensips[5064]: DBG:core:io_watch_del: io_watch_del op on index -1 10 (0x822ec0, 10, -1, 0x0,0x1) fd_no=95 called
Jan 29 23:12:03 opensips1 /sbin/opensips[5064]: INFO:core:sig_usr: signal 15 received
Jan 29 23:12:03 opensips1 /sbin/opensips[5061]: INFO:core:sig_usr: signal 15 received
Jan 29 23:12:03 opensips1 /sbin/opensips[5058]: INFO:core:sig_usr: signal 15 received
Jan 29 23:12:03 opensips1 /sbin/opensips[5060]: INFO:core:sig_usr: signal 15 received
Jan 29 23:12:03 opensips1 /sbin/opensips[5063]: INFO:core:sig_usr: signal 15 received

**Comment by bogdan-iancu** [comment]
Hi @apsaras , do you get any core file on this crash ?

**Comment by apsaras** [comment]
Hello Bogdan

No I do not have. The problem solved by changing at db_http.c the line int cap_raw_query = 0; to int cap_raw_query = 1;

Even if I set raw query at the opensips.conf it seems to be ignored.

Regards

**Comment by liviuchircu** [comment]
The bug is apparently obvious, and a fix is on its way. Before applying the fix however, could you please re-test this:
    "modparam("db_http", "cap_raw_query", 1)"

It really should solve the problem. Although it's masking the real issue underneath, it should at least prevent the crash from happening!

**Comment by liviuchircu** [comment]
UPDATE (this will be funny, fixed in OpenSIPS 2.1): Make sure "loadmodule db_http.so" and its modparams are placed before "loadmodule avpops.so". This should at least provide a crash-free environment!

**Comment by liviuchircu** [comment]
I have committed the above-mentioned patch. It basically forces you to do a modparam("db_http", "cap_raw_query", 1), otherwise OpenSIPS won't start. If there are any more issues, please re-open this thread.
