### ISSUE TITLE
SQLite3 database support - Feature Request

### ISSUE THREAD

**Issue by anto** [OpenSIPS/opensips#409]
Is there any plan to natively support SQLite3 database?

I have actually already asked the exact same question almost 6 years ago (http://lists.opensips.org/pipermail/users/2009-August/007746.html), but I got no straight answer as to whether there is a plan to do that or the main reason why there is no plan to do that. Due to my confusions as to which one between OpenSIPS and Kamailio to choose, since then I didn't even start to use any of those. 

I know Kamailio have SQLite module, but I don't want to use it. So it would be great if at least I get the straight answer about the main reason why SQLite database is not supported in OpenSIPS.

Thanks in advance for any responses

**Comment by opensips-github** [comment]
On 02/04/2015 07:49 PM, anto wrote:
>
> Is there any plan to natively support SQLite3 database?
>

"native" ... no.  By a module, not that I know of, there are many 
database modules, one of which will likely suit your needs.
>
> I have actually already asked the exact same question almost 6 years 
> ago 
> (http://lists.opensips.org/pipermail/users/2009-August/007746.html), 
> but I got no straight answer as to whether there is a plan to do that 
> or the main reason why there is no plan to do that. Due to my 
> confusions as to which one between OpenSIPS and Kamailio to choose, 
> since then I didn't even start to use any of those.
>
> I know Kamailio have SQLite module, but I don't want to use it.
>

umm.... ok?

**Comment by anto** [comment]
Thanks. I know there are several database modules supported in OpenSIPS. I thought that I was clearly expressing myself that I want to use SQLite3 database.

**Comment by opensips-github** [comment]
A lot of times people think they need to do some thing a certain way.  I 
suggest you say what you want to do, and people will tell you how you 
can do it, instead of you trying to tell people how you want to do some 
thing in a system you seem to know little about.

I saw your post from several years ago - there are already many router 
distros that have embedded opensips instances... so like i said, tell us 
what you are trying to do... not how you want to do it.

**Comment by anto** [comment]
Sorry. I don't think you can help in this case, because what I want to is to have a good SIP Proxy with SQLite database. So far I have been using Asterisk but that is not pure SIP Proxy. I hope this is clearly explained what I want.

**Comment by opensips-github** [comment]
OpenSips is the best sip proxy that exists, your arbitrary requirement 
of sqlite is not relevant.  Explain why sqlite is important to you, or 
go away.

**Comment by anto** [comment]
If you are not a developer or somebody who is competence enough to answer my question, I suggest to shut your mouth.

**Comment by opensips-github** [comment]
You have not answered the question... what are you trying to do, why is 
sqlite important to you.

I answered your initial question - there is no sqlite support, and no 
plans for it.  That said, I am certain opensips can do what you want as 
it is extremely flexible and capable with its existing modules.

**Comment by anto** [comment]
I don't think you are representing the developers of OpenSIPS project. So I will just wait for the answer from them.

**Comment by opensips-github** [comment]
ok ... good luck

**Comment by bogdan-iancu** [comment]
@anto , I strongly suggest to stay in the limits of well behaving and to be polite with the people here. We are a community and people do try to help one each other, as best as they can. Sometimes their help may be useful, sometime not, but this is not a reason to mistreat them.

Now, answering your question - there is no implementation for sqllite as there was no strong demand for it so far and we preferred to focus our resources on more "demanded" things.

**Comment by anto** [comment]
Sorry Bogdan for being childish. But I really had to react the same way as any arrogant people who tell me to "GO AWAY", just because of I was asking question. If I would have asked for help in any setup or configuration, I definitely do not do that here in your project's github issue tracking.

And thanks a lot for your answer, which is quite fair and good enough for me.

**Comment by bogdan-iancu** [comment]
@anto there is no reason to close the ticket, the feature request is valid and drop by drop it will get significant in demand :).

**Comment by anto** [comment]
I was not sure whether I should close or leave this opened. Since there was no label assigned to it before, I thought I better close it to make your issue tracking list shorter. So thanks a lot Bogdan to consider my request as a valid feature request.

**Comment by bogdan-iancu** [comment]
It is almoast ready ;)

**Comment by anto** [comment]
Thanks a lot Bogdan.

Please just take your time as I am not in a hurry :)

I am at the moment holding any installations on all my servers (some VPS' and barebones) that are now running on Debian, until Devuan is being released and my servers switch to it.

Cheers,

Anto

**Comment by etamme** [comment]
Is it possible to include the sqlite-pcre stuff with some build flag, that way the REGEX command is exposed.

**Comment by ionutrazvanionita** [comment]
@etamme Ok. It will be there.

**Comment by vladpaiu** [comment]
Closing - this has been committed on 2.2
