### ISSUE TITLE
transport=sctp not working

### ISSUE THREAD

**Issue by jamesabravo** [OpenSIPS/opensips#413]
Opensips does not seem to support 'transport=sctp'. I tracked this down to two missing 'case PROTO_SCTP' statements in modules/tm/ut.h .  I can send a patch if someone can tell me how to upload one?

**Comment by bogdan-iancu** [comment]
Hi @jamesabravo. If creating a pull request is too complicated, upload your patch on gist here and post the link.
Thanks, Bogdan

**Comment by jamesabravo** [comment]
Sorry, I went for the easy option and uploaded a patch at
https://gist.github.com/jamesabravo/bf928caea09fdb1496b2

**Comment by bogdan-iancu** [comment]
Thank you @jamesabravo , I push you patch on 1.1, 1.0 and 1.8 versions.
The 2.1 (devel) is completely different and for the moment I push the patch on the transport-interface branch.
