### ISSUE TITLE
Problems when receiving binary content using SCTP

### ISSUE THREAD

**Issue by jamesabravo** [OpenSIPS/opensips#419]
If sctp_server_rcv_loop() in sctp_server.c receives a 0-terminated packet it removes the 0.
This causes problems with binary content when it ends with a 0.

Enabling NO_ZERO_CHECKS would fix this issue but would also change the behaviour of bin_receive_loop() in bin_interface.c which also uses the define.

I believe removing the section in sctp_server_rcv_loop() is the right move. 
If your interested, I've uploaded a patch at: 
https://gist.github.com/jamesabravo/c0e88a4af34c091c7b57

**Comment by bogdan-iancu** [comment]
Hi @jamesabravo , thanks for the fix. The NO_ZERO_CHECKS checks were dropped in 2.1 as they does not make too much of a sense anymore.
So, I completely removed them from 1.11, 1.10 and 1.8 too.

Thanks and regards,
Bogdan

**Comment by jamesabravo** [comment]
Thanks.

Are u sure about removing lines 377-383 in udp_server.c ? You probably know
the code a lot better then be, I was just concerned that probing packets
(usually 4 zero's) will upset things further ok?

**Comment by bogdan-iancu** [comment]
@jamesabravo you saved me !!! thank you !! my intention was to remove the define only, not the code inside of it.....guess I need a coffee ;).

Best Regards, Bogdan

**Comment by jamesabravo** [comment]
You and be both. Take care
