### ISSUE TITLE
core timer delay warnings on master 

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#421]
running on master commit f3ed4db9903d85cba7d7d491c931b550e29932d1

I am getting repeated logs with the following warning:

 WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 100000 us delay in execution

This is a centos7 kvm using kvm clock.  The machine is currently processing no traffic at all.

I am running the following config https://github.com/etamme/federated-sip/tree/2.1-config/core

**Comment by bogdan-iancu** [comment]
@etamme, whatever the script is, you should not get such errors, especially without the traffic. Is that the only kind of warn you get from the timer subsystem ?
Do you get that message in a consistent way or from time to time ?

**Comment by etamme** [comment]
@bogdan-iancu the warnings happen all the time, but I can not see any particular interval to them.

I did 'grep timer /var/log/opensips' and made a gist of the last 24 hours https://gist.github.com/etamme/a75198a5590c22bfa574

This box is litereally sitting idle - I have one UA that I am registering via TCP, but the warnings were occurring before I even enabled tcp.

**Comment by bogdan-iancu** [comment]
Hi @etamme  - is there any chance to get access to that server for troubleshooting ? This will be the fastest way to get this solved.
Thanks, Bogdan

**Comment by bogdan-iancu** [comment]
Issue fixed by commit 90c410c - after all there was a bogus warning message (in false reports on timer delays).
Many thanks to @etamme  for the support !

**Comment by apsaras** [comment]
Hello

I have the same issue with latest release. 

opensips 2.1.2 (x86_64/linux)

/sbin/opensips[6443]: WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 30000 us delay in execution

Running on CentOS 6 64bit on VMware. No traffic on the box

Thank you.

**Comment by bogdan-iancu** [comment]
@apsaras , no traffic, nothing and it starts spitting that warn ?

**Comment by apsaras** [comment]
Yes. No traffic at all.
