### ISSUE TITLE
xlog_buf_size and xlog_force_color are no longer documented anywhere

### ISSUE THREAD

**Issue by rshpount** [OpenSIPS/opensips#422]
I cannot find documentation for xlog_buf_size and xlog_force_color anywhere past version 1.6.3, even though they still seems to be supported. Is this documentation omission or are they being deprecated?

**Comment by bogdan-iancu** [comment]
Hi @rshpount - it seems they are not documented in the Global Parameter section. Thank you for the heads up, we will fixit asap.

**Comment by liviuchircu** [comment]
Updated *Global Parameter* and *Escape Sequences* sections all the way down to OpenSIPS 1.8. Thank you for reporting!
