### ISSUE TITLE
strange behavior use_next_gw 

### ISSUE THREAD

**Issue by Edwin-Hoff** [OpenSIPS/opensips#425]
I see a strange behaviour using the route_to_carrier and use_next_gw function:

Installed on Debian opensips and opensips-mysql-module version 1.11.3-1-dee7da41

If I use a sip client whichs adds :5060 to the ruri and I receive a 503 Service unavailable from the first gateway, then the ruri sent to the next gateway (using the use_next_gw() function) is mixed up. The first prefix is still there preceded by the prefix from the next gateway with the original number four digets short.

Let me explain:

The way it works ok (note, no :5060)

INVITE sip:31206655443@mysipserver.org SIP/2.0 -> INVITE sip:123431206655443@10.20.30.40 SIP/2.0
                                               <- 503 Service unavailable
                                               -> INVITE sip:876531206655443@20.30.40.50 SIP/2.0

The problem i see (note, :5060)

INVITE sip:31206655443@mysipserver.org SIP/2.0 -> INVITE sip:123431206655443@10.20.30.40 SIP/2.0
                                               <- 503 Service unavailable
                                               -> INVITE sip:876512343120665@20.30.40.50 SIP/2.0

So I notice the first prefix is still there: 8765 1234 3120665
I can reproduce this by using a 3CX soft client (then it goes wrong).

Here below the output of 'opensipsctl dr show'

dr gateways
+----+------+------+---------------+-------+------------+-------+------------+-------+--------+-------------+
| id | gwid | type | address       | strip | pri_prefix | attrs | probe_mode | state | socket | description |
+----+------+------+---------------+-------+------------+-------+------------+-------+--------+-------------+
|  1 | 1    |    1 | 10.20.30.40   |     0 | 1234       | NULL  |          0 |     0 | NULL   | Gateway A   |
|  2 | 2    |    2 | 20.30.40.50   |     0 | 8765       | NULL  |          0 |     0 | NULL   | Gateway B   |
+----+------+------+---------------+-------+------------+-------+------------+-------+--------+-------------+
dr groups
+----+----------+--------+---------+-------------+
| id | username | domain | groupid | description |
+----+----------+--------+---------+-------------+
|  1 | .*       | .*     |       1 | Inbound     |
|  2 | .*       | .*     |       2 | Outbound    |
+----+----------+--------+---------+-------------+
dr carriers
+----+-----------+--------+-------+-------+-------+---------------------------+
| id | carrierid | gwlist | flags | state | attrs | description               |
+----+-----------+--------+-------+-------+-------+---------------------------+
|  1 | 1         | 1,2    |     0 |     0 | NULL  | Carrier A                 |
|  2 | 2         | 2,1    |     0 |     0 | NULL  | Carrier B                 |
+----+-----------+--------+-------+-------+-------+---------------------------+
dr rules
+--------+---------+------------+---------+----------+---------+--------+-------+-------------+
| ruleid | groupid | prefix     | timerec | priority | routeid | gwlist | attrs | description |
+--------+---------+------------+---------+----------+---------+--------+-------+-------------+
|      1 | 1       | 4165555555 |         |        0 | NULL    | 1      | NULL  | Inbound     |
|      2 | 2       | 4165555555 |         |        0 | NULL    | 1      | NULL  | Outbound    |
+--------+---------+------------+---------+----------+---------+--------+-------+-------------+

I tested a quick 'fix' which works:

$ru = "sip:" + $rU + "@" + $rd;

        if(route_to_carrier("$avp(droute)"))
        {

**Comment by bogdan-iancu** [comment]
@Edwin-Hoff , after you successfully do route_to_carrier(), could you print all the destinations as set.
First, set the ruri_avp (see  http://www.opensips.org/html/docs/modules/1.11.x/drouting.html#id294025) : 
   modparam("drouting", "ruri_avp", '$avp(dr_ruri)')
and after route_to_carrier(), print all those avps:
   `xlog("current destination is $ru, next available are $(avp(dr_uri)[*])\n"); `
And let's see what you have.

**Comment by Edwin-Hoff** [comment]
OK, I changed the code and added the xlog header. First I tried without the 'fix' ($ru = "sip:" + $rU + "@" + $rd;) and than I tried with the 'fix' so you can see the difference.

 ### $ru = "sip:" + $rU + "@" + $rd;
 if(route_to_carrier("$avp(droute)"))
        {
		xlog("L_ERROR", " INFO : current destination is $ru, next available are $(avp(dr_ruri)[*])\n");



### $ru = "sip:" + $rU + "@" + $rd;
INFO : current destination is sip:123431208110001@41.127.34.19, next available are sip:876512343120811@212.5.221.223, sip:876512343120811@212.5.221.224

$ru = "sip:" + $rU + "@" + $rd;
INFO : current destination is sip:123431208110001@41.127.34.19, next available are sip:876531208110001@212.5.221.223, sip:876531208110001@212.5.221.224

**Comment by bogdan-iancu** [comment]
@Edwin-Hoff , thanks for the logs, useful information - let me do some debugging.

**Comment by vladpaiu** [comment]
Hello,

I have just committed a fix for this ( 8e2cad2b3ca78cbfe1394be1f629b4153b860ff7 ).
Please pull the newest sources, recompile and hopefully the issue should be gone.

Best Regards,
Vlad
