### ISSUE TITLE
fraud_detection: calls_per_minute issue

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#432]
*calls_per_minute* does not seem to be updated properly.

Let sipp fire 1 cps at OpenSIPS. The *calls_per_minute* statistic of our destination should never exceed 60 in this scenario.

**Comment by ionutrazvanionita** [comment]
hi @liviuchircu . check this PR https://github.com/OpenSIPS/opensips/pull/665

**Comment by liviuchircu** [comment]
Fixed in #665
