### ISSUE TITLE
$rtpstat pvar in rtpengine is empty

### ISSUE THREAD

**Issue by rgagnon24** [OpenSIPS/opensips#434]
After successful call with rtpengine proxying the RTP, an attempt to log, or insert the value of $rtpstat into a header does not work.  The content is blank.

```
...
if (has_totag()) {
   if (loose_route() || topology_hiding_match()) {
      if (is_method("INVITE")) {
         record_route();
      }
      if (is_method("CANCEL|BYE")) {
         append_hf("x-rtp-statistics: $rtpstat\r\n");
         rtpengine_delete();
      }
   }
   route(relay);
} else {
   ...
}
...
```

The header appears in the BYE, but there is nothing following the colon.

**Comment by opensips-github** [comment]
The function calls that populate the rtpstat pvar are not properly set 
up at the moment.  I will work on getting a pull request together with a 
fix.
-Eric
