### ISSUE TITLE
2.1 TLS read_fd: no fd read bug

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#438]
I set up TLS and registered a single UA via tls.  I got the following error.

    Mar 19 14:31:53 alpha /usr/local/sbin/opensips[28491]: CRITICAL:core:handle_io: 
    >>> read_fd:no fd read

    It seems you have hit a programming bug.
    Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

see the following [gist](https://gist.githubusercontent.com/etamme/5c0fc8f0358a62e082e3/raw/d9180c1aab6bfde79ae0228a0c613c665e0de166/gistfile1.txt) for more complete log output.

**Comment by bogdan-iancu** [comment]
Fixed by commit 9ee509
