### ISSUE TITLE
Bug - StartTLS in LDAP module fail to start

### ISSUE THREAD

**Issue by gremaudc** [OpenSIPS/opensips#441]
Hello everybody, 

I just installed the 2.1 RC for testing purpose and I try to use the LDAP module with the new startTLS option. For testing, I want to use the built-in certificate with the LDAP module. I already use this certificate with the tls_proto and it works fine but when I try with LDAP module, I have the following error : 

ERROR:ldap:ldap_connect: cannot start tls! Check certificates and keyfile path and access rights

I think it could be a bug because I don't really understand how it could be a path or rights problem if the same path and same file are used in the residential script with tls_proto.

thanks

**Comment by ionutrazvanionita** [comment]
@gremaudc My mistake for the error message, but it is also possible to be a problem from the ldap server or the opensips ldap configuration file. Did you check the slapd log to see if there are any problems there? Are you sure youre slapd is configured properly for StartTLS?

**Comment by ionutrazvanionita** [comment]
@gremaudc https://github.com/OpenSIPS/opensips/commit/6036215ab07de371361b73b4c63fd77a22c06fd4 . Modified the module to geta proper error message when TLS fails to start.

**Comment by ionutrazvanionita** [comment]
I will close the issue. I consider that the "bug" was because the error message was misleading. Now you will get a proper error message which may help you solve the problem.
