### ISSUE TITLE
force_send_socket now requires proto? in d29cd9d (devel)

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#447]
version: opensips 2.2-dev (x86_64/linux)
git revision: d29cd9d

Unable to get force_send_socket to work without a proto. While it should be optional according to docs.
Working syntax in 1.10/1.11: (yes with quotes)
 force_send_socket("12.12.21.12");

Output in devel:
Apr  1 14:12:32 SRV-DEV-HPROXY-1 opensips: CRITICAL:core:yyerror: parse error in config file //etc/opensips/opensips.cfg, line 445, column 32-33: syntax error
Apr  1 14:12:32 SRV-DEV-HPROXY-1 opensips: CRITICAL:core:yyerror: parse error in config file //etc/opensips/opensips.cfg, line 445, column 33-34: bad argument, [proto:]host[:port] expected

The following syntaxes do not work (also tried with quotes). While they should in my opinion:
 force_send_socket(12.12.21.12);
 force_send_socket(12.12.21.12:5060);

Working:
force_send_socket(udp:12.12.21.12);
force_send_socket(udp:12.12.21.12:5060);

**Comment by bogdan-iancu** [comment]
It is not a bug, and it is not trunk only (2.1 too). It is a side effect of the grammar changes during protocol rework.
I think it is even better now as it forces you to give exact description of the interface/listener you want to use (it is not protocol ambigous anymore).

**Comment by hydrosine** [comment]
Then the documentation should be updated!

http://www.opensips.org/Documentation/Script-CoreFunctions-2-1#toc16

**Comment by liviuchircu** [comment]
Also corrected the documentation. Thanks for the report, @hydrosine ! The devil is always in the details...
