### ISSUE TITLE
fix_nated_sdp appends two extra oldmediaip attributes

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#449]
Adding oldmediaip attribute should be controlled by a flag (0x16).
If the flag is present, the attribute should be appended only once (controlled by 'preserve' param of 'alter_mediaip' function).
(imported from SF, created by Ovidiu Sas)

**Comment by ionutrazvanionita** [comment]
Hi @ovidiusas, i don't know whether you took into consideration #377  when you opened this issue. 'oldmediaip' doesn't exist anymore as you requested. What is more, what are you trying to say with 'once more'? Would you like that if you already have an oldmediaip(oldcip and oldoip now), the ip that's inside to be replaced with the new one? Please provide some more details about this isue, maybe some examples.

**Comment by ovidiusas** [comment]
Initiallly, the oldmediaip did not make any distinction between c and o lines and if both were changed the oldmediaip attribute was added twice.
With #377 the oldmediaip attribute was replaced by two new attributes and there for there's no more duplication.

I don't see in documentation the new proposed flag. It would be good to be able to control the addition of this new attributes and by default turn them off.
