### ISSUE TITLE
SIPMSGOPS: sip_msg_validate 

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#450]
Why sip_msg_validate passes Contact: in REGISTER like this?
Contact: <sip:user@domain:10501:20367;rinstance=86d960eb37116caa>

So adding a new flag to force Contact URI validation ??

(imported from SF, reported by Nick Altmann)

**Comment by liviuchircu** [comment]
This has been already added in 2.1 by @tallicamike (f8e210e8). Closing as invalid.
