### ISSUE TITLE
2.x sqlite module errors out: ERROR:db_sqlite:str_strstr: bad parameters

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#451]
Full debug log is available at:
https://gist.githubusercontent.com/etamme/b8148792f97746956f12/raw/e7eb57af6b1e6f943c63eddbbc5fbf8113cef783/sqlite%20errors

**Comment by etamme** [comment]
I added some logs for query_holder and searched_str, it looks like query holder is empty 

DBG:avpops:ops_dbquery_avps: query [select tran_strip, tran_prefix, tran_user, tran_domain, tran_port, tran_add_header,tran_strip_port from translations where (from_username='eric' or from_username IS NULL) and from_domain='voipphreaker.com' and (match_user_agent like 'Grandstream GXP1610 1.0.0.38%' or match_user_agent IS NULL )  and ('7000' regexp match_regex or match_regex IS NULL) order by tran_priority limit 1]
 DBG:db_sqlite:db_copy_rest_of_count: XXX query_holder: 
 DBG:db_sqlite:db_copy_rest_of_count: XXX searched_str: from
 ERROR:db_sqlite:str_strstr: bad parameters

**Comment by etamme** [comment]
I looked into this further last night and found that db_sqlite_submit_dummy_query() is never actually being called, and as a result query_holder is never set.

**Comment by ionutrazvanionita** [comment]
@eamme fixed https://github.com/OpenSIPS/opensips/commit/82648c210b13dfa36894165c1fee58c642b8391d
