### ISSUE TITLE
Incoming TLS request gets outbound proto set to TLS

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#452]
I am making an initial request from a TLS UA to a "off network" domain that should simply t_relay per RFC3263.

The request has no port, and is not a sips URI so I do not know why it is being assumed that it has a "proto" set.

See full debug 4 trace at:

https://gist.githubusercontent.com/etamme/f776aa8c9045358c2b17/raw/b3e9211a3f16a429f9125f04cd2540d0624334fb/proto

**Comment by etamme** [comment]
I believe this is related to the initial request coming in with a port 5061 on it, even though I strip that by setting $rp="";

Here is a trace from a UA that does not include the port on the initial request line:

https://gist.githubusercontent.com/etamme/13ec00e78d585083100f/raw/ad5120e10ce86e6930785b4a6dfe2db8c8532bc3/gistfile1.txt

**Comment by bogdan-iancu** [comment]
Following some investigation, the difference in behaviour comes from the presence (or lack) of a pre-loaded Route header. This header points to a TLS interface, making opensips (while handling the preload route) to force a TLS send socket . According to #420, if no proto is dictated by RURI, the one from forced socket is used.

**Comment by etamme** [comment]
This issue is only occuring when there is a route header, an example route header from on of the UA experiencing the issue is:

Route: <sip:alpha.uphreak.com:5061;lr>

**Comment by etamme** [comment]
resolved by b8c0740a63f80577bff8314b4cf0e17867a1fda4
