### ISSUE TITLE
ERROR:httpd:answer_to_connection: oom while allocating post_request structure

### ISSUE THREAD

**Issue by bhakimi** [OpenSIPS/opensips#454]
i think there is a memory leak of some sort, at first it works, i keep sending json requests to monitor opensips using zabbix, after so many requests, syslog gets filled with this error

ERROR:httpd:answer_to_connection: oom while allocating post_request structure

**Comment by ovidiusas** [comment]
Please provide the version of Opensips that you are using.

**Comment by bhakimi** [comment]
opensips-1.11.3

**Comment by rgagnon24** [comment]
Looks like it could be something that was fixed on March 6, 2015 in master for non-POST requests.

Is Zabbix using GET or POST ?

**Comment by bhakimi** [comment]
k let me try and see what happens

**Comment by ovidiusas** [comment]
This was fixed on 1.11.4.
If the issue still persists, please re-open.

**Comment by bhakimi** [comment]
correct, 1.11.4 has fixed the issue, thank you guys

**Comment by IgorKonstantinov** [comment]
@bhakimi Hello. Can you make a rep with you zabbix opensips monitor? 
Thanks!

**Comment by bhakimi** [comment]
Email me to Bobby at convoso.com
