### ISSUE TITLE
db_sqlite segfaults on avb_dbquery 100% of the time

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#455]
back trace from core file: https://gist.githubusercontent.com/etamme/f19270e0757a07519af8/raw/022530cc5b1628f668b3e3a6c9f8f67c88b41460/db_sqlite

**Comment by ionutrazvanionita** [comment]
fixed https://github.com/OpenSIPS/opensips/commit/7bedddda2adbe700a1b7d896a0bcbf7cfd754821
