### ISSUE TITLE
acc_created_avp_id in 2.1 acc

### ISSUE THREAD

**Issue by digipigeon** [OpenSIPS/opensips#460]
I believe something is not quite right with the 94cf5dd commit in the 2.1 branch, specifically regarding the internal acc_created_avp_id variable.

I get the following three errors:
Apr 13 09:49:43 li443-44 /usr/sbin/opensips[14456]: ERROR:core:new_avp: invalid AVP name!
Apr 13 09:49:43 li443-44 /usr/sbin/opensips[14456]: ERROR:core:add_avp: Failed to create new avp structure
Apr 13 09:49:43 li443-44 /usr/sbin/opensips[14456]: ERROR:acc:acc_onreq: failed to add created avp value!

This happens regardless of me setting:

modparam("acc", "acc_created_avp_name", "call_created_avp")

The problem causes an error and subsequently prevents any CDR's from been generated.

**Comment by razvancrainea** [comment]
Can you confirm you are not using a DB backend for dumping CDRs, but something else such as Radius, log or events?

**Comment by digipigeon** [comment]
I am not using a database, I am using events.

**Comment by razvancrainea** [comment]
I just committed a fix on the master branch. Can you give it a try?

**Comment by digipigeon** [comment]
Yes, this has resolved the issue, thank you.
