### ISSUE TITLE
Message format error for rtpproxy timeout notification

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#469]
Having configured the rtpproxy module based on the instructions (here: http://opensips.com.br/wiki/index.php?title=Oopensips_Nat_script_with_RTPPROXY_-_English) with the addition of a unix socket for timeout notification

When a timeout occurs, the notification is sent to opensips which results a format error.

```
Apr 17 13:51:50 sip2 rtpproxy[7194]: INFO:process_rtp:0lwTwepnRcMCQaFcHCR5Qn1YwTAO0jKx: session timeout
Apr 17 13:51:50 sip2 /usr/sbin/opensips[7359]: DBG:rtpproxy:timeout_listener_process: Timeout detected on call [1#012]
Apr 17 13:51:50 sip2 /usr/sbin/opensips[7359]: ERROR:rtpproxy:timeout_listener_process: Wrong formated message received from rtpproxy [1]
Apr 17 13:51:50 sip2 rtpproxy[7194]: INFO:remove_session:0lwTwepnRcMCQaFcHCR5Qn1YwTAO0jKx: RTP stats: 918 in from callee, 1428 in from caller, 2346 relayed, 0 dropped
Apr 17 13:51:50 sip2 rtpproxy[7194]: INFO:remove_session:0lwTwepnRcMCQaFcHCR5Qn1YwTAO0jKx: RTCP stats: 4 in from callee, 8 in from caller, 12 relayed, 0 dropped
Apr 17 13:51:50 sip2 rtpproxy[7194]: INFO:remove_session:0lwTwepnRcMCQaFcHCR5Qn1YwTAO0jKx: session on ports 12154/16986 is cleaned up
```
This has been tested with opensips 1.11.3 (LTS) and opensips 2.0rc1 each against rtpproxy 1.2 and rtpproxy 2.0.0, all built from source.

rtpproxy command line:

```
rtpproxy -i -T 10 -s 'unix:/var/run/opensips/rtpproxy.sock' -n 'unix:/var/run/opensips/rtpproxy_notify.sock' -l <server public ip> -m 10000 -M 20000 -d 'DBUG' -u opensips:opensips
```

opensips config section:
```
loadmodule "nathelper.so"
loadmodule "dialog.so"
loadmodule "rtpproxy.so"

modparam("nathelper", "natping_interval", 10)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "received_avp", "$avp(received_nh)")

modparam("rtpproxy", "rtpproxy_sock", "unix:/var/run/opensips/rtpproxy.sock")
modparam("nathelper","force_socket", "unix:/var/run/opensips/rtpproxy.sock")
modparam("rtpproxy", "rtpp_notify_socket", "unix:/var/run/opensips/rtpproxy_notify.sock")

```

**Comment by razvancrainea** [comment]
Hamid, I just committed master@c26a4a34fcf790741918224ce9557eb4d1f51edf. Can you checkout the master branch and give it a test?

**Comment by hamid-elaosta** [comment]
Just to respond to the comment above, for future reference; As discussed in IRC. With the commit above, opensips no longer complains of a message format error, however, calls are not terminated. @razvancrainea indicated that the notify tag is being lost on call set-up when it should be sent to rtpproxy.

**Comment by hamid-elaosta** [comment]
Commit cb9f46ba80ccb4da9f362e4c686be6e497d0ee9e by @razvancrainea has solved this issue now. Many thanks.
