### ISSUE TITLE
ERROR:proto_tls:_tls_read: SYSCALL error -> (0) <Success>

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#470]
Using master from commit 24341a06cd18ed32f4d818729122e154e7db520f I am getting odd error logs from the TLS module.

Apr 17 11:04:08 alpha /usr/local/sbin/opensips[18512]: ERROR:proto_tls:_tls_read: SYSCALL error -> (0) <Success>
Apr 17 11:04:08 alpha /usr/local/sbin/opensips[18512]: ERROR:proto_tls:_tls_read: TLS connection to 50.198.204.238:42846 read failed
Apr 17 11:04:08 alpha /usr/local/sbin/opensips[18512]: ERROR:proto_tls:_tls_read: TLS read error: 5

**Comment by ionutrazvanionita** [comment]
Hello, fixed with commit b7db0809de2ff5c237cfceda23dc8bd1cc357ed4 . Try testing it and please close it if everything ok!
