### ISSUE TITLE
dbtext module (when interacting with dispatcher) load order of rows does not match dbtext file

### ISSUE THREAD

**Issue by jockmckechnie** [OpenSIPS/opensips#479]
Greetings;

On OpenSIPS v1.8.5 (presumed still present in 1.8.7):

Given a dbtext dispatcher database of the following:

id(int,auto) setid(int) destination(string) socket(string,null) flags(int) weight(int) attrs(string) description(string)
0:1:sip\:192.168.55.9\:5060::0:1:'':'handler01'
1:1:sip\:192.168.55.8\:5060::0:1:'':'handler02'

When the database is loaded into dispatcher the order unexpectedly gets sorted by the 'destination' field. No amount of changing the 'id' value will get the order altered from an apparent alpha sort of the 'destination' field, ala:

SET_NO:: 1
SET:: 1
         URI:: sip:192.168.55.8
         URI:: sip:192.168.55.9

Using dispatcher in a 'fail over' mode requires the data to be loaded from disk in a specific order and this is not possible with this fault present, unfortunately. If it could remain sorted by the 'id' field, or the on-disk order (I'm not sure which is easiest to implement), then it can be reliably configured in the correct order to solve the issue.

Thank you!

**Comment by jockmckechnie** [comment]
If you REVERSE the order of the entries in the db_text dispatcher file (put row 1 before row 0) it will load in the correct order. I could have sworn I tested this, but apparently not. I'll let you decide if you want to act on this oddity or simply close it out as it is "fixable" if you know the secret.

**Comment by bogdan-iancu** [comment]
@jockmckechnie , in 1.8 version, the dispatcher module does rely on the ordering provided by the DB (as return when querying the whole table).  If you use other engine, like mysql, you will get the same ordering in memory as in the DB - BTW, could you just double check that ??
This is why in 2.1 there is an explicit priority column, to avoid relying on the DB engine.

**Comment by bogdan-iancu** [comment]
@jockmckechnie , indeed, the problem was in the db_text driver - while returning the query result, the rows were in revert order . I fixed this problem in all active OpenSIPS versions.
