### ISSUE TITLE
rest_get doesn't return information about error

### ISSUE THREAD

**Issue by philevans** [OpenSIPS/opensips#480]
In the documentation for rest_get in the rest_client module, the example suggests that if an error is returned such as a 403 or a 404, the rest_get call will return false, and you will still have access to the return code and body:

    # Example of querying a REST service to get the credit of an account
    
    if (!rest_get("http://getcredit.org/?ruri=$fU", "$var(credit)", "$var(ct)", "$var(rcode)")) {
      xlog("Error code $var(rcode) in HTTP GET!\n");
      send_reply("403", "Not registered");
      exit;
    }

However this does not work for me, and the OpenSIPS log just shows an error, and none of the PVs are populated with the return code or body.  Looking at the code, I see CURLOPT_FAILONERROR is set, which means it just fails outright of a response code >=400 is returned.  Also as far as I can tell even if this wasn't set, the code would then just incorrectly suggest the call returned OK and populate the PVs.  It needs to do a bit of both, and return a false from the function, but still fill in the PVs.

I am just wondering if this is something I am not doing right, or if this is indeed a bug.

**Comment by jarrodb** [comment]
@philevans please try this patch #481

**Comment by liviuchircu** [comment]
Reviewed the fix. Merged and backported -> 1.10. Keeping this open until we confirm everything works ok with the async versions.

**Comment by jarrodb** [comment]
I was able to verify the `async(rest_client(...), resume)` returns `$var(rcode)` of 404 with the following route:

```
route [resume] {
        if ($rc < 0) {
                xlog("Error code $var(rcode) in HTTP GET!\n");
                send_reply("403", "GET Forbidden");
                exit;
        }
}
```

```
Apr 24 16:20:18 localhost opensips[2141]: Error code 404 in HTTP GET!
```

**Comment by liviuchircu** [comment]
Looks clean. Closing.
