### ISSUE TITLE
opensipsdbctl postgresql port issue

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#485]
There seems to be a problem with the opensipsdbctl create when you try to create postgresql database. The script tries 3306 port instead of 5432

opensipsdbctl create
PGSQL password for postgres:
INFO: creating database ewisbc ...
psql: could not connect to server: Connection refused
        Is the server running on host "mydb" (1.1.1.6) and accepting
        TCP/IP connections on port 3306?
ERROR: Creating database failed!

Adding 

DBPORT=5432

to the opensipsctlrc solves the problem.

**Comment by razvancrainea** [comment]
Solved by @jarrodb in 6340435c9ee7d8c2d6d1fd00f480fd4958a7a154
