### ISSUE TITLE
(1.11.x) max_contacts is ignored

### ISSUE THREAD

**Issue by bbuitenhuis** [OpenSIPS/opensips#492]
I don't have any proof or logs to back this up. But with the latest version LTS: 1.11.4 , this variable looks ignored. With git revision: 80793b7 (version 1.11.2) this problem won't occur.

**Comment by bogdan-iancu** [comment]
@bbuitenhuis , I checked the history for both usrloc and registrar modules and I found no changes related to the max_contacts.
Now, are you referring to max_contacts the module parameter or to the save() function param ?
What db mode do you use for usrloc ?
And by "ignored" you mean whatever value you set, it does nothing ? like keep accepting whatever number of contacts per AOR ?

**Comment by bbuitenhuis** [comment]
@bogdan-iancu , we are using the following parameters:
modparam("registrar", "max_contacts", 1)

In the test I'm using:
modparam("usrloc", "db_mode",3)

With "ignored" mean that save() is adding multiple contacts to the location database, and from my point of view is ignoring the max_contacts.

**Comment by bogdan-iancu** [comment]
Do you use multiple OpenSIPS instances over the same location table ?

**Comment by bbuitenhuis** [comment]
@bogdan-iancu No its only one OpenSips instance that is using this table/database.

**Comment by bogdan-iancu** [comment]
Just tested and, as expected, I get:
May  7 14:23:22 [22609] INFO:registrar:update_contacts: too many contacts for AOR <test>, max=1
Second registration was declined and nothing added to DB.

**Comment by bogdan-iancu** [comment]
@bbuitenhuis , do you have any updates or info on this ?

**Comment by bbuitenhuis** [comment]
@bogdan-iancu No sorry, I can replicate this anymore (with a fresh installation).
I think we can close this issue for now.

**Comment by bogdan-iancu** [comment]
ok @bbuitenhuis , let's close it then...
