### ISSUE TITLE
acc_evi_request error - cannot find created avp

### ISSUE THREAD

**Issue by danbogos** [OpenSIPS/opensips#495]
Hi,

I am trying to use acc_evi_request()  in a config like this:

```
if (is_method("INVITE")) {
		# create dialog with timeout
		if ( !create_dialog("B") ) {
			send_reply("500","Internal Server Error");
			exit;
		}
		setflag(CDR);
		acc_evi_request("DIALOG_START");
```

I have subscribed to E_ACC_EVENT from outside but instead of event, I can only see this in syslog:
```
May  3 11:24:37 OsipsDev1 /usr/sbin/opensips[2995]: ERROR:acc:get_timestamps: cannot find created avp
May  3 11:24:37 OsipsDev1 /usr/sbin/opensips[2995]: ERROR:acc:acc_evi_request: cannot get timestamps
```

Tried both defaults and to configure `modparam("acc", "acc_created_avp_name", "created_avp")`.

Ta,
DanB

**Comment by razvancrainea** [comment]
Hi, Dan!

Are you using the latest RC2 version? There was a bug related to this, but should have been solved in 3ac458f968a0503f55cc23a18ab61b7ffd90ae0e.

Best regards,
Răzvan

**Comment by danbogos** [comment]
Hey Răzvan,

Thanks for your answer.

I am using latest commit in branch 2.1 (59d7d48291c789d68cd88f7fc5e7c7db674f0ce3). Is that not rc2?
```
commit 59d7d48291c789d68cd88f7fc5e7c7db674f0ce3
Author: Jarrod Baumann <j@rrod.org>
Date:   Thu Apr 30 11:44:59 2015 -0500

root@OsipsDev1:/usr/local/src/opensips/opensips_2_1# git status
# On branch 2.1

```
Ta,
DanB

**Comment by razvancrainea** [comment]
Hi, Dan!

Indeed, I double checked and this is a different issue.
The problem is that you are setting the CDR flag, before running the acc_evi_request(). That's why the function thinks it needs some CDR-based information, that it doesn't have.
However, the two functions are independent and they should not influence each-other.
I will create a fix on the master branch - is there any chance you could checkout and test it?

Thanks,
Răzvan

**Comment by danbogos** [comment]
Great, thanks! 
Will test it and let you know about results!

Cheers,
DanB

**Comment by razvancrainea** [comment]
Just committed the fix 89eb9dc5f9f30e07ff8a40cd1b1c000f8eaf33f0

**Comment by danbogos** [comment]
Hi Răzvan,

Unfortunately your commit does not appear to solve my problem.

Running with the latest master, same issue:
```
May  5 09:42:51 OsipsDev1 /usr/sbin/opensips[23403]: ERROR:acc:get_timestamps: cannot find created avp
May  5 09:42:51 OsipsDev1 /usr/sbin/opensips[23403]: ERROR:acc:acc_evi_request: cannot get timestamps

root@OsipsDev1:/etc# opensips -V
version: opensips 2.1-rc2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 59d7d48
main.c compiled on 18:49:24 May  2 2015 with gcc 4.7
```

Thanks,
DanB

**Comment by danbogos** [comment]
Hi Răzvan,

Please hold for the moment since it appears there was something wrong with my packages.

DanB

**Comment by danbogos** [comment]
Hi Răzvan,

After properly upgrading packages (from branch 2.1 to master) I confirm that the issue is now gone. Thanks a lot for your fast support!

DanB
