### ISSUE TITLE
Permission module partition support

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#501]
Feature request.

Have the possibility to pull data (groups) from different tables, just like the dispatcher module has.

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/84b4e7ea35b584c3f29f56db3e2bd152a8ee6bdc . This commit provides partition support for permissions module. Any kind of feedback would be appreciated!

**Comment by hydrosine** [comment]
I'm having trouble defining the table_name.
I tried both the syntax as in dispatcher module.  the quoted example in the permissions docs gave the same output.
below first the modparam and the output in log.
modparam("permissions", "partition", "group4_part: db_url=mysql://u:p@ip/proxydev; table_name = address2;")
ERROR:core:db_check_table_version: invalid version 0 for table table_name found, expected 5

And yes i added address2 to the version table! but it seems to find table_name as value.

**Comment by bogdan-iancu** [comment]
@hydrosine , please one a separate ticket (a bug report) for this. The feature request issue is to be closed now.
