### ISSUE TITLE
usrloc with matching mode 'contact only' may leak in DB

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#503]

**Comment by ferrored** [comment]
I would like to ask you if the "duplicate error" is related to issue #503:

CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (1062): Duplicate entry 'prove-si.unimib.it-sip:prove@IP-7c22475a-ac9cde33-4447' for key 'account_contact_idx'
proxysiptest /sbin/opensips[23345]: ERROR:core:db_do_update: error while submitting query

**Comment by bogdan-iancu** [comment]
This should have been addressed by the migration (in 2.2) to contact_id (uuid) key for contacts - this new key is used both in DB and in memory, so they are in full sync, with no chances of leaking
