### ISSUE TITLE
EventRoute blocking sip listening

### ISSUE THREAD

**Issue by danbogos** [OpenSIPS/opensips#504]
Hey Guys,

Not really an emergency but for the record, when using the dialog variable in event route, it will get opensips server unresponsive.

Following route will reproduce it:
```
event_route[E_DLG_STATE_CHANGED] {
	fetch_event_params("new_state=$var(new_state)");
	if $var(new_state) == 3 {
		$avp(dialog_start) = "cgr_reqtype";
		$avp(dialog_start) = $avp(cgr_reqtype);
		$avp(dialog_start) = "callid";
		$avp(dialog_start) = $ci;
		$avp(dialog_start) = "from_tag";
		$avp(dialog_start) = $ft;
		$avp(dialog_start) = "cgr_account";
		$avp(dialog_start) = $avp(cgr_account);
		$avp(dialog_start) = "cgr_subject";
		$avp(dialog_start) = $avp(cgr_subject);
		$avp(dialog_start) = "cgr_destination";
		$avp(dialog_start) = $avp(cgr_destination);
		$avp(dialog_start) = "created";
		$avp(dialog_start) = $Ts;
		$avp(dialog_start) = "dialog_id";
		$avp(dialog_start) =  $DLG_did;
		raise_event("E_CGR_DIALOG_START", $avp(auth_keys), $avp(auth_vals));
	}
}
```

**Comment by bogdan-iancu** [comment]
You may create a deadlock because of triggering an event from an event route....We will investigate, thanks for reporting

**Comment by razvancrainea** [comment]
Hi, Dan!

I've just pushed a fix on the master branch for this issue. Can you give it a test and let us know if everything is ok?

Thanks,
Răzvan

**Comment by danbogos** [comment]
Hey @razvancrainea 

Thanks for this.

I can confirm that the route does not longer block.

```
U 2015/05/17 13:44:12.159061 127.0.0.1:60731 -> 127.0.0.1:2020
E_CGR_DIALOG_START
dialog_id::375:33756007
created::1431863052
```

The only question I would have here is whether there are no chance to add some other $avps (or at least dialog variables maybe)?

This small event was generated out of the following template (obviously the other vars missing):
```
event_route[E_DLG_STATE_CHANGED] {
    fetch_event_params("new_state=$var(new_state)");
    if $var(new_state) == 3 {
        $avp(dialog_start_keys) = "cgr_reqtype";
        $avp(dialog_start_values) = $avp(cgr_reqtype);
        $avp(dialog_start_keys) = "callid";
        $avp(dialog_start_values) = $ci;
        $avp(dialog_start_keys) = "from_tag";
        $avp(dialog_start_values) = $ft;
        $avp(dialog_start_keys) = "cgr_account";
        $avp(dialog_start_values) = $avp(cgr_account);
        $avp(dialog_start_keys) = "cgr_subject";
        $avp(dialog_start_values) = $avp(cgr_subject);
        $avp(dialog_start_keys) = "cgr_destination";
        $avp(dialog_start_values) = $avp(cgr_destination);
        $avp(dialog_start_keys) = "created";
        $avp(dialog_start_values) = $Ts;
        $avp(dialog_start_keys) = "dialog_id";
        $avp(dialog_start_values) =  $DLG_did;
        raise_event("E_CGR_DIALOG_START", $avp(dialog_start_keys), $avp(dialog_start_values));
    }
}
```

Other than this the bug should be gone I think

Thanks,
DanB

**Comment by razvancrainea** [comment]
Hi, Dan!

Indeed, currently there is no way to add extra information to the events raised. We'll have to find a different mechanism to do that, so if you really need this, open a new feature request.
In the meantime, I will close this bug as it is solved.

PS: have you tried using the dialog variables ($dlg_val()) to store your information and catch it in event route?

Best regards,
Răzvan

**Comment by danbogos** [comment]
@razvancrainea, thanks the ticket is solved, I can confirm. Did not look yet at $dlg_val() but it is a good pointer, thanks!
