### ISSUE TITLE
‘io_wait_h’ has no member named ‘epfd’

### ISSUE THREAD

**Issue by narunask** [OpenSIPS/opensips#505]
`Make` very quickly spawns following error message and terminates..   

    # make
    bison -d -b cfg cfg.y
    flex cfg.lex
    Compiling action.c
    Compiling async.c
    Compiling bin_interface.c
    Compiling blacklists.c
    Compiling context.c
    Compiling core_stats.c
    Compiling crc.c
    Compiling daemonize.c
    Compiling data_lump.c
    Compiling data_lump_rpl.c
    Compiling dprint.c
    Compiling dset.c
    Compiling errinfo.c
    Compiling error.c
    Compiling flags.c
    Compiling forward.c
    Compiling io_wait.c
    In file included from io_wait.c:45:0:
    io_wait.h: In function ‘io_watch_add’:
    io_wait.h:351:3: warning: implicit declaration of function ‘LM_BUG’ [-Wimplicit-function-declaration]
    io_wait.h:355:2: error: ‘io_wait_h’ has no member named ‘epfd’
    io_wait.h:355:2: error: ‘io_wait_h’ has no member named ‘epfd’
    make: *** [io_wait.o] Error 1

I've tried [opensips-2.1.0.tar.gz](http://opensips.org/pub/opensips/2.1.0/src/opensips-2.1.0.tar.gz) as well as `github` version.

My system is wheezy:

    # uname -rv
    3.16-0.bpo.2-amd64 #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21)

Though I had much better luck with [opensips-2.1-rc2.tar.gz](http://opensips.org/pub/opensips/2.1.0/src/opensips-2.1-rc2.tar.gz), which is just half in size of the final release and I would like to know why?

`rc2` terminates later:

    Compiling evi/event_interface.c
    Compiling evi/evi_core.c
    Compiling evi/evi_params.c
    Compiling evi/evi_transport.c
    Compiling cachedb/cachedb.c
    Compiling cachedb/cachedb_id.c
    Compiling cachedb/cachedb_pool.c
    Compiling net/net_tcp.c
    Compiling net/net_tcp_proc.c
    In file included from net/../reactor_defs.h:39:0,
                     from net/../reactor.h:38,
                     from net/net_tcp_proc.c:28:
    net/../io_wait.h: In function ‘io_watch_add’:
    net/../io_wait.h:351:3: warning: implicit declaration of function ‘LM_BUG’ [-Wimplicit-function-declaration]
    In file included from net/../reactor.h:38:0,
                     from net/net_tcp_proc.c:28:
    net/../reactor_defs.h: At top level:
    net/../reactor_defs.h:45:22: error: field ‘ri’ has incomplete type
    net/net_tcp_proc.c: In function ‘handle_io’:
    net/net_tcp_proc.c:114:4: warning: implicit declaration of function ‘async_resume_f’ [-Wimplicit-function-declaration]
    net/net_tcp_proc.c:173:20: error: ‘process_no’ undeclared (first use in this function)
    net/net_tcp_proc.c:173:20: note: each undeclared identifier is reported only once for each function it appears in
    net/net_tcp_proc.c:179:12: error: ‘protos’ undeclared (first use in this function)
    net/net_tcp_proc.c: In function ‘tcp_worker_proc’:
    net/net_tcp_proc.c:289:7: error: ‘io_poll_method’ undeclared (first use in this function)
    make: *** [net/net_tcp_proc.o] Error 1

Any advice would be appreciated.

Thanks

**Comment by bogdan-iancu** [comment]
Hi @narunask , what gcc version do you have (gcc -v) ? On my system (3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015), the compiling is ok.

**Comment by liviuchircu** [comment]
Managed to replicate. It seems that HAVE_SIGIO_RT is undefined on your platform, hence some headers are not included.

**Comment by liviuchircu** [comment]
So, there are two problems:

* one is in the build system, since it cannot properly parse "3.16-0.bpo.2-amd64" (notice the first dash - it doesn't expect it).
* the other one is in the header structure, since OpenSIPS should compile even on older Linux systems.
