### ISSUE TITLE
dialplan: WARNING: a load command already generated, aborting reload...

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#510]
If the httpd module is loaded along with the dialplan and mi_fifo module, the following warning shows up.
```
WARNING:dialplan:dp_load_db: a load command already generated, aborting reload...
```
It looks like the dialplan data is loaded by the MI FIFO process and the warning is generated by the HTTPD process.  This is reproducible in trunk and 2.1.

**Comment by razvancrainea** [comment]
Hi, Ovidiu!

Is the data actually loaded simultaneously from the two engines FIFO and HTTPD? How do you reproduce this?

Best regards,
Răzvan

**Comment by ovidiusas** [comment]
It's happening at start up every single time.

**Comment by ionutrazvanionita** [comment]
fa14431830bde1c8ede30bf77a609197e7d002fa && 6164d1c3cab077957e91118c8094cfa97b2bfc7b loads data in child_init and then closes the connection; in mi_child_init it is done only the connect part

**Comment by bogdan-iancu** [comment]
@ovidiusas , could you test on your side and confirm the fix - so we can do the backport to 2.1 too.

**Comment by ovidiusas** [comment]
It is working fine now: the db data is loaded by the first receiver process.
It would be nice if the the load could be distributed over the receivers in a round robin fashion: first module takes the first receiver, second module that loads a db takes the next receiver and so on.
It would improve the startup time is really big tables are cached into memory.

**Comment by bogdan-iancu** [comment]
@ovidiusas, yes and no. YES: indeed it will make the startup faster ; NO: the whole idea is to avoid blocking the SIP processing while loading, so we need to be sure that some procs are still left untouched by the init and available for handling SIP traffic.
Please open a separate feature request on this topic.
