### ISSUE TITLE
dialplan: improper partiton parameter parsing

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#511]
The example that is given in the docs doesn't work.
If a space is inserted before and after the last ';', then the parameter is properly parsed.
Non working definition:
````
modparam("dialplan", "partition", " part2 : table_name = dialplan ; db_url = mysql://user:passwb@localhost/db;")
````
Working definition:
````
modparam("dialplan", "partition", " part2 : table_name = dialplan ; db_url = mysql://user:passwb@localhost/db ; ")
````

The parsing should be more flexible with respect to spaces.

Also, it seems that the name of the partition is stored with an extra space at the end of the partition name and dp_reload doesn't work for a non "default" partition.

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/7846e63d1e803484d130604acc0e6798240f3587 changed the pasing logic a little bit; split the attributes into tokens "TYPE=VALUE;", and the parsed each token, TYPE and VALUE.

**Comment by ovidiusas** [comment]
Tested OK.
