### ISSUE TITLE
dialplan: mask username:password for db_url in dp_show_partition

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#512]
The dp_show_partition MI command displays the database connection URL for each partition.
For security purposes, we need to mask the username and pasword:
````
mysql://xxxx:xxxx@localhost/opensips
````

**Comment by eseanucristian** [comment]
Hi Ovidiu,

I've masked only the password. Would you like me to mask the  username also ?

**Comment by ovidiusas** [comment]
There's no need to mask the username.
Thanks for taking care of it.

--ovidiu

**Comment by razvancrainea** [comment]
Thanks for this patch Cristi! Closing the ticket.
