### ISSUE TITLE
E_ACC_EVENT not generated from local_route

### ISSUE THREAD

**Issue by danbogos** [OpenSIPS/opensips#515]
Hey Guys,

I am having some hard time trying to record BYEs for calls which are disconnected from outside the signaling (eg: via dlg_end_dlg mi command).

I have tried setting CDR flag, evi_flag, evi_missed_flag and even call the acc_evi_request() manually in the route. There was no event triggered.

I should mention that I am using latest master of today.

Bellow an example of configuration:
```
modparam("acc", "evi_flag", "CDR")
modparam("acc", "evi_missed_flag", "CDR")
...
local_route {
	if (is_method("BYE") ) {
		setflag(CDR);
		acc_evi_request("LOCAL_DISCONNECT"); #FixMe
	}
}
```

And the network capture for events:
```
U 2015/05/17 14:52:59.015958 127.0.0.1:44151 -> 127.0.0.1:8020
:dlg_end_dlg:
311
1582574523


#
U 2015/05/17 14:52:59.016792 127.0.0.1:8020 -> 127.0.0.1:44151
200 OK

#
U 2015/05/17 14:52:59.029577 127.0.0.1:59830 -> 127.0.0.1:2020
E_DLG_STATE_CHANGED
hash_entry::311
hash_id::1582574523
old_state::3
new_state::5
```

Thanks in advance for any kind of tip.

DanB

**Comment by ionutrazvanionita** [comment]
hi @danbogos . fixed with https://github.com/OpenSIPS/opensips/commit/453ad339840526eb6ef3a66b976739739dd2d8d7. the problem was that the event wasn't updated depending on the flags you set in script

**Comment by danbogos** [comment]
Thank you! Will come back if issues found. Until then you can close the ticket.

DanB
