### ISSUE TITLE
drouting gw_priprefix_avp returns null

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#518]
Hello

The gw_priprefix_avp, after doing do_routing always returns null

modparam("drouting", "gw_priprefix_avp", '$avp(gw_priprefix)')

 if(!do_routing("$avp(rgid)",,,"$avp(rule_attrs)","$avp(gw_attrs)"))
                {
                        send_reply("500","No Route Found");
                        exit;
                }
                xlog("My PRI Prefix: $avp(gw_priprefix)"); <-- That returns null

OpenSIPs 2.1.0

**Comment by bogdan-iancu** [comment]
Thank you @apsaras - I found and fix the problem. Please update from GIT and give it another try.
