### ISSUE TITLE
CSeq header not being incremented correctly after uac_auth for ACKs

### ISSUE THREAD

**Issue by philevans** [OpenSIPS/opensips#524]
On an INVITE, after performing a uac_auth and then sending the second INVITE to the UAS with the correct authorization header, the CSeq on the UAS side is correctly incremented as per the RFC.  The CSeq header is also correctly rewritten on the UAS side on a CANCEL request.  However the header does not appear to be being rewritten for ACKs.  This causes incorrect behaviour because as far as the UAS is concerned the CSeq does not match up, as it is using the original CSeq from the UAC side, rather than the incremented CSeq for the second INVITE on the UAS side.

This behaviour is seen on OpenSIPS 2.1.0, GIT revision b365aed.  It can be reproduced at will by performing a uac_auth() followed by a t_relay(), and observing the subsequent ACK.

**Comment by stefancn** [comment]
Any work arounds ....

**Comment by razvancrainea** [comment]
Can you please try this with OpenSIPS 2.4. This should be fixed in the latest code.
