### ISSUE TITLE
NULL support in cachedb raw interface

### ISSUE THREAD

**Issue by jayesh1017** [OpenSIPS/opensips#525]
The cachedb raw queries currently ignores the NULL values that gets returned from a NoSQL Database. For eg. if you do the following:
cache_raw_query("redis:myRedis", "HMGET MYKEY one two three", "$avp(result)");
And if the the key "two" doesn't exist in redis, the avp array element 1 does not return with a NULL value, instead the value at element 2 is substituted at element 1 and if we do value matching in the script it has possibilities of error.
It'll be great, if NULL returns back so that value matching of array elements in $avp(result) is done properly.

**Comment by vladpaiu** [comment]
Hello,

This has been fixed in the master branch ( thanks to Jarrodb ) - please update your sources and retest.

Best Regards,
Vlad
