### ISSUE TITLE
Feature Request: in acc allow setting variables for *_extra_bye after loose_route

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#526]
Currently if you use the *_extra_bye options in the Acc module you must make sure that the variables are set before calling loose_route or they are not populated.

This can be problematic if you need to access data associated with the dialog (such as a $dlg_val) for calculations or other processing to populate those values. Making it so that they can be populated after calling loose_route (such as the change made to $DLG_timeout in 1.11) would make this much easier and more intuitive.

**Comment by vladpaiu** [comment]
Hello,

This can be achieved now by using the dialog exported events ( see http://www.opensips.org/html/docs/modules/2.1.x/dialog.html#id297207 )
By using the event_route module (  http://www.opensips.org/html/docs/modules/2.1.x/event_route#id293506 ) and declaring a script route as route[E_DLG_STATE_CHANGED] , you will be able to detect when the dialog switches from the 4 state ( established ) to state 5 ( ended ) - the route will get called before the accounting is done, thus allowing you to populate your variables.

Best Regards,
Vlad

**Comment by rrb3942** [comment]
Hey Vlad,

Thank you for the response. That will work great for me.

I still think that it is a bit  unintuitive that any variables after calling loose_route don't get accounted for, as loose_route tends to be one of the very first calls that will be made on a request with a totag (which a BYE is pretty much guaranteed to have).

The documentation should at least mention this, as I know it was not obvious to me when I first attempted to use it.

Thanks for your help.

**Comment by rrb3942** [comment]
Pretty sure this is all taken care of with the new accounting variables and changes.
