### ISSUE TITLE
evi: no script feedback on failure to deliver events

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#536]
If an event is handled in async mode and there is a failure in the event delivery mechanism, there's no script feedback about the failure.  The raise_event() will return no errors (the event is pushed ok through the opensips internal socket to the transport specific module).  If the transport specific module fails to deliver the event, the event is lost and there's no script feedback.

An option would be to create an evi failure route where failed events will be presented.
Another option would be to raise an internal E_EVI_FAILURE event and present the failed event in it's associated event route.

**Comment by bogdan-iancu** [comment]
This should be addressed by the new event_virtual module:
http://lists.opensips.org/pipermail/news/2015-September/000429.html
