### ISSUE TITLE
RTPEngine SDP Re-Invite Issue

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#542]
Hello

I am not sure if that is a feature that has to be implemented or a feature that is not working.

I am using RTPEngine for RTP handling on a mhomed environment. Initialy I was tried to use the rtpengine_manage which didn't work for me so now I am using offer, delete and answer.

The problem I have now is when the carrier or customer sends re-invite to renegotiate codecs in fax transmission. How should I handle such case? If not handled, carrier's Public RTP IP is passed to the internal interface back to customers on the internal network and the OK coming from customer to OpenSIPs with the Internal SDP of the customer, is forwarded as it is to the carrier.

Thank you for your help

**Comment by opensips-github** [comment]
Do not delete the sesssion.  Simply answer/offer again.  RTPengine will 
update the monologues.  The session is still the same dialog so don't 
delete it.  I am using RTPengine and have no issues with re-invites.

see my my federated SIP server config 
<https://github.com/etamme/federated-sip/blob/master/core/opensips.cfg.erb> 
for example usage.

-Eric
