### ISSUE TITLE
Permission module partition support broken

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#544]
I'm having trouble defining the table_name.
I tried the syntax as in dispatcher module. the quoted example in the permissions docs don't work.
below first the modparam and the output in log.
modparam("permissions", "partition", "group4_part: db_url=mysql://u:p@ip/proxydev; table_name = address2;")
ERROR:core:db_check_table_version: invalid version 0 for table table_name found, expected 5

And yes i added address2 to the version table! but it seems to find table_name as value.

**Comment by ionutrazvanionita** [comment]
@hydrosine https://github.com/OpenSIPS/opensips/commit/c2fd6c89bd732fdd002458f8a18effce6797f40c sorry.  you were right. assigned by mistake to the table name the value "table_name"

**Comment by hydrosine** [comment]
Works!
Thanks :+1:
