### ISSUE TITLE
loose_route returns TRUE for an in-dialog single consumed Route header

### ISSUE THREAD

**Issue by gergelypeli** [OpenSIPS/opensips#550]
Happened with 1.11.3, but the relevant code seems to be the same even in the master branch.

According to the docs of loose_route:

2. If the request in inside a dialog ( has a to-tag ), loose-routing was used ($ru is end-point) and Route contains only the local proxy, the function returns FALSE.

But it returns true in this case. The suspicious code is in loose.c/after_loose(), which contains:

        LM_DBG("No next URI found!\n");
        status = (preloaded ? NOT_RR_DRIVEN : RR_DRIVEN);

Within a dialog "preloaded" is false, so this sets the return status to RR_DRIVEN, which is true. The expected return value is false, since the forwarding in this case is not based on Route-s, but on the RURI.

**Comment by bogdan-iancu** [comment]
@gergelypeli , the true/false returned by loose_route() does not limit to "using RURI or not", but to "applying the loose Route mechanism or not".
As time as your incoming request had a Route header (pointing to your server), the loose Route mechanism was applied (to identify and strip the local Route and to decide to route further based on RURI).

So, the doc seems to be  a bit ambiguous / bogus, I will take care of this.

**Comment by gergelypeli** [comment]
OK, then a documentation fix would suffice, and I'll use isdsturiset for this.

**Comment by bogdan-iancu** [comment]
@gergelypeli, the docs were updated (see the above commits), the online docs are regenerated during the nights, so give them a bit of a time to be updated.
Thanks and regards, Bogdan

**Comment by bogdan-iancu** [comment]
You can also do : 
    if ($du==NULL) {} else {}

$du is destination URI
