### ISSUE TITLE
tcp read error on 1.11.5

### ISSUE THREAD

**Issue by seanchann** [OpenSIPS/opensips#551]
Hi:
    I use 1.11.5 with tcp. 
    in my log allways have some error like this:
    Jun 11 15:32:24 ivoip /usr/sbin/opensips[8067]: CRITICAL:core:handle_io: empty fd map
Jun 11 15:32:24 ivoip /usr/sbin/opensips[8063]: ERROR:core:tcp_read_req: bad request, state=0, error=2 buf:#012#012parsed:#012
Jun 11 15:32:24 ivoip /usr/sbin/opensips[8067]: CRITICAL:core:handle_io: empty fd map
Jun 11 15:32:24 ivoip /usr/sbin/opensips[8063]: ERROR:core:io_watch_del: trying to delete already erased entry 30 in the hash(0, 0, (nil)) )
Jun 11 15:32:24 ivoip /usr/sbin/opensips[8067]: CRITICAL:core:handle_io: empty fd map
^CJun 11 15:32:24 ivoip /usr/sbin/opensips[8063]: ERROR:core:tcp_read_req: bad request, state=0, error=2 buf:#012#012parsed:#012 

  once this error occur, the error info will not stop write to log util  i force stop opensips.

**Comment by seanchann** [comment]
i guess it occur when some tcp connecction have some data will be read, but  this connection Suddenly disconnected  by client.

**Comment by seanchann** [comment]
by  a way， I run  opensips  in a  docker container

**Comment by seanchann** [comment]
Is there any way to avoid this problem temporarily?

**Comment by bogdan-iancu** [comment]
@seanchann , any way to reproduce the kind of errors you get ?

**Comment by seanchann** [comment]
Hi:
    here have some information about this bug.  
    use pjsip as sip client.  pjsip will sent "\r\n"  for tcp keepalive.
    In opensips logs :
    "/usr/sbin/opensips[264]: ERROR:core:tcp_read_req: bad request, state=0, error=2 buf:#012#012parsed:#012" 
    I assume when tcp read "\r\n" from sip client and  abnormal disconnect tcp, then may be have quit logic for this loop, so opensips log allways wirte that log forever

**Comment by razvancrainea** [comment]
Have you tried using the tcp_crlf_drop parameter?
```modparam("proto_tcp", "tcp_crlf_drop", 1)```

**Comment by bogdan-iancu** [comment]
@seanchann , indeed, that is the TCP CRLF ping pong for keep alive purposes and OpenSIPS does support it.
I will repeat my question - is there a way to predictably reproduce this ? it will really help me in debugging.

**Comment by seanchann** [comment]
Hi bogdan：
   I will test it again to reproduce it. thank you!

**Comment by seanchann** [comment]
Hi:
  Here is my test order：
  1. I  sent  100  messages to dest user(eg. 1000), 1000 not online, so message store into silo table.
   2. when 1000 sent register to opensips， dump all message to 1000.
   3. when message sent to 1000,  kill sip client.

  Log described above will reappear.

  by the way， in opensips 1.11 not have modparam("proto_tcp", "tcp_crlf_drop", 1)

**Comment by bogdan-iancu** [comment]
@seanchann , is this report still valid with the latest 1.11 ?

**Comment by seanchann** [comment]
@bogdan-iancu   sorry, too long time. it not repeat on new version

**Comment by bogdan-iancu** [comment]
Thanks @seanchann , I'm closing this ticket.
