### ISSUE TITLE
mi_xmlrpc_ng & mi_json answer bug with pua_publish

### ISSUE THREAD

**Issue by dsandras** [OpenSIPS/opensips#552]
It seems mi_xmlrpc_ng & mi_json can not build the XMLRPC or JSON answer when the modules are used together with pua_publish.

Jun 11 15:55:45 golgoth05 opensips[31577]: DBG:mi_json:mi_json_answer_to_connection: got an async reply                                                                                                                                        
Jun 11 15:55:45 golgoth05 opensips[31577]: DBG:httpd:answer_to_connection: MHD_create_response_from_callback
Jun 11 15:55:45 golgoth05 opensips[31577]: ERROR:mi_json:mi_json_flush_data: Unexpected NULL mi handler!

This "Unexpected NULL mi handler" when building the module response to the query happens with both modules.

Attached is a script that reproduces the error. The system should probably return a 500 Internal Server error. Please note that when I submit a wrong XML document using mi_json through a command-line telnet, it seems to work. But both XMLRPC and mi_json trigger the bug when being invoked from a PHP script. Perhaps there is a timing issue or something similar.

**Comment by dsandras** [comment]
<?php
$extension = "754";
$realm = "ds.local.beip.be";
$enable_tcp = true;

$uri = "sip:$extension@$realm";
if ($enable_tcp)
        $uri .= ';transport=tcp';
$etag = '.';
$id = "754-web";
$status = "away";
$extended_status = "Belgian Beer Rocks";
$ttl = "3600";

$xml = "<?xml version='1.0' encoding='UTF-8'?>
<presence xmlns='urn:ietf:params:xml:ns:pidf'
xmlns:dm='urn:ietf:params:xml:ns:pidf:data-model'
xmlns:rpid='urn:ietf:params:xml:ns:pidf:rpid'
entity='pres:{{ $extension }}@{{ $realm }}'>
<tuple{{ if $id }} id='{{ $id }}'{{ /if }}>
<status><basic>open</basic></status>
<contact priority='1'>sip:{{ $extension }}@{{ $realm }}</contact>
<note>{{ $extended_status|escape }}</note>
</tuple>
<dm:person id='{{ $id }}-pid'>
<rpid:activities><rpid:{{ $status }}/></rpid:activi";

$args = array ($uri, $ttl, 'presence', 'application/pidf+xml', $etag, '.', $xml);
$path = implode ($args, ',');

$ch = curl_init ();
curl_setopt ($ch, CURLOPT_URL,
             "http://127.0.0.1:8011/json/pua_publish?params=" . urlencode ($path));
curl_setopt ($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt ($ch, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($ch, CURLOPT_HTTP_VERSION, 1.1); 
curl_setopt($ch, CURLOPT_HTTPHEADER, array ("Accept: application/json"));
curl_setopt($ch, CURLOPT_TIMEOUT, 2);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$s = curl_exec ($ch);
echo $s . " ici \n";

curl_close ($ch);
?>

**Comment by bogdan-iancu** [comment]
Working with @dsandras off list to reproduce this error.

**Comment by mqandeel** [comment]
Dears, I'm getting this issue even when mi_xmlrpc_ng is loaded alone without any other mi module (fifo, http, json...). I'm running opensips 2.1 on Ubuntu 14.04 LTS.

**Comment by bogdan-iancu** [comment]
@dsandras , the problem was narrowed down to mi_json module when handling ASYNC MI commands. I'm trying to reach @shimaore (the author of the module) to sort this out.
In the mean while, should I try a patch for make mi_json to run all MI commands in SYNC mode (to avoid the existing problem with ASYNC) ? Does it make sense ?

**Comment by dsandras** [comment]
Hi Bogdan, following @mqandeel, xmlrpc-ng would suffer of the same bug.
From my point of view, things could be done in SYNC mode... Thanks for having a look !

**Comment by bogdan-iancu** [comment]
@dsandras, not so sure about @mqandeel report (if indeed related to this or something completely different) as the error you reported is 100% generated by mi_json:

Jun 11 15:55:45 golgoth05 opensips[31577]: ERROR:**mi_json**:mi_json_flush_data: Unexpected NULL mi handler!

and mi_json has nothing to do with mi_xmlrpc.

**Comment by dsandras** [comment]
Indeed. But I am not sure if it is a bug in mi_json or in the sublayer shared by all mi modules actually.

**Comment by bogdan-iancu** [comment]
Hi @dsandras , Hi @mqandeel - I found the problem and fixed it. The fixes are available not on GIT for all maintained versions.

Thank you a lot for your report and support !

**Comment by dsandras** [comment]
Hi Bogdan,
I see the changes are only done in mi_xmlrpc_ng code files. Does that
mean that the equivalent bug in mi_json is still present or does
mi_json use the same code ?
Thanks,
Le mardi 18 août 2015 à 03:47 -0700, Bogdan Andrei IANCU a écrit :
> Hi @dsandras , Hi @mqandeel - I found the problem and fixed it. The
> fixes are available not on GIT for all maintained versions.
> Thank you a lot for your report and support !
> —
> Reply to this email directly or view it on GitHub.
-- 
Damien Sandras <dsandras@seconix.com>

**Comment by bogdan-iancu** [comment]
@dsandras , both modules were fixed. There is a set of commits for each module. Regards, Bogdan

**Comment by dsandras** [comment]
Oh great!
Thanks for the clarification!
Le mardi 18 août 2015 à 12:30 -0700, Bogdan Andrei IANCU a écrit :
> @dsandras , both modules were fixed. There is a set of commits for
> each module. Regards, Bogdan
> —
> Reply to this email directly or view it on GitHub.
-- 
Damien Sandras <dsandras@seconix.com>
