### ISSUE TITLE
validate_dialog() mismatch for escaped characters

### ISSUE THREAD

**Issue by MaxMuehlbronner** [OpenSIPS/opensips#553]
Opensips version is 1.11.5.

It seems like the validate_dialog function fails at comparing uris containing escaped characters with non-escaped uris. E.g. :

/sbin/opensips[1687]: ERROR:dialog:dlg_validate_dialog: failed to validate remote contact: dlg=[sip:1041#33674375192@109.11.34.21:5060] , req=[sip:1041%2333674375192@109.11.34.21:5060]

The function returns -2  (invalid remote target) in this case.

**Comment by ionutrazvanionita** [comment]
fixed with https://github.com/OpenSIPS/opensips/commit/49efaa9c53242985ffa3c0ea81a8ee1d19dd2555.  before comparing the whole uri, the user field of the uri is unescaped

**Comment by ionutrazvanionita** [comment]
Hi @MaxMuehlbronner, I am going to close the issue since it's fixed. Please feel free to reopen it if you think it doesn't solve your problem!
