### ISSUE TITLE
Cannot use unset_dlg_profile() in a named route called from onreply_route

### ISSUE THREAD

**Issue by nud** [OpenSIPS/opensips#554]
Hello,

- You cannot put unset_dlg_profile in a "normal" route (route[FOO])
- You cannot call a named onreply_route from another onreply_route()
- You cannot use more than one named onreply_route using t_on_reply()

This makes it effectively impossible to split a huge onreply_route into several subroutes if you want to use unset_dlg_profile().

Maybe there should be a onreply_route() function to call onreply_route(), or the check for route type at startup time should be more relaxed somehow.

This happend using opensips 1.8

**Comment by bogdan-iancu** [comment]
Hi @nud ,

1) you can use it from any named route, as time as that named route is triggered from a Failure, On-Reply or Branch route.

2) that's a non sense which is not allowed (to call a onreply_route from a different onreply_route) - only named routes (route[subrutine]) can be used as sub-routes.

3) no, only one onreply_route is allowed (as you have a single main route for requests). As the onreply_route may take decision on discarding the reply, it is impossible (from logical perspective) to chain multiple onreply_routes.  A simple and elegant approach is to use an onreply_route[] with flags and subroutines (named flags) to signalize and handle different tasks - arm the reply route, and depending on the flow in main route, set different flags; flags to be checked in onreply_route.

Let me know your thoughts.

PS: 1.8 became recently unsupported (end-of-life), consider upgrading to 1.11

**Comment by nud** [comment]
Well, as a matter of fact, in 1.8 the "script compiler" errors out at startup time if I use unset_dlg_profile in a named route, even if it is only called from an onreply_route. Did it change after 1.8 or did I miss something? Because apparently you think it should work.

The two other points were not so much a complain than to explain how the observed behaviour is a problem. We'd just like to be able to split reply routes into several parts but right now opensips won't allow us.

We will be upgrading for the next versions of the BeIP product, but right now we are stuck with 1.8 for various reasons...

**Comment by bogdan-iancu** [comment]
@nud , Indeed, testing your case with 1.8 throws that error :O .....  So you are right, there is something broken in there.

**Comment by bogdan-iancu** [comment]
@nud, I made a work around, so the unset function will work now via named routes.

I tested (for 1.8 even) and works, so I will close this ticket. But I will open a new one about the broken route checking.

Many thanks, Bogdan
