### ISSUE TITLE
Fails to build with gcc 5.1 - opensips-1.10.5

### ISSUE THREAD

**Issue by ondrejj** [OpenSIPS/opensips#555]
GCC 5.1 has different processing of inline functions. With gcc -fgnu89-inline opensips builds find, but this is not default for Fedora 22.

**Comment by lemenkov** [comment]
Related information. A ticket dedicated to that issue:

* https://bugzilla.redhat.com/show_bug.cgi?id=1190820

I've tried to fix the issue in a lemenkov/opensips@e06d0587b2b91ae8749450d031a32116da0b7b67 but the proposed patch was incomplete and later we were hit by a similar issues:

* https://bugzilla.redhat.com/show_bug.cgi?id=1221213

Further reading about a new approach to inline:

* http://www.greenend.org.uk/rjk/tech/inline.html
* https://gcc.gnu.org/gcc-5/porting_to.html (see "Different semantics for inline functions")
* http://www.drdobbs.com/the-new-c-inline-functions/184401540

**Comment by bogdan-iancu** [comment]
Wrongly closed by a mis-reference of this issue in the commit for #556

**Comment by lemenkov** [comment]
Thanks, @razvancrainea !
