### ISSUE TITLE
Topology Hidding Not translate back Contact Header on Reply

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#556]
Hello

I have a mhomed border OpenSIPs and I am using topology_hiding(C) for both directions. At the internal network I have an OpenSIPs with Topology Hiding as well

The Problem I have is that the Contact sent to Carrier originating the call from my border OpenSIPs is the encoded one.

Example

Carrier INVITE:
Call-ID: 557AECAE-01779381@hiqpcu-mgi-021
Contact: <sip:17.5.1.4:5060;transport=udp>

Border OpenSIPs INVITE to Proxy
Call-ID: SBC_VlpZLyAgNSxOX0NSRFtQW14uBgwSBAoWQh8CGk9TUV4=
Contact: <sip:172.17.99.98;did=96.85aa6734>

Proxy Reply to Border with Session Progress
Call-ID: SBC_VlpZLyAgNSxOX0NSRFtQW14uBgwSBAoWQh8CGk9TUV4=
Contact: <sip:172.17.99.2;did=d98.b4d594e6>

Border Forward to Carrier the Session Progress
Call-ID: 557AECAE-01779381@hiqpcu-mgi-021
Contact: <sip:6.5.8.8;did=96.85aa6734>

As you can see CallIDs are translated correct but Contact is not, starting from internal Proxy.

Is that a bug or do I have something wrong?

**Comment by bogdan-iancu** [comment]
Hi @apsaras - so the contact in the "Border Forward to Carrier the Session Progress" should be 172.17.99.98, right ?  Does this 6.5.8.8 have any relevance for you ??

**Comment by bogdan-iancu** [comment]
A patch is under testing by @apsaras ...waiting for a confirmation on the fix.

**Comment by bogdan-iancu** [comment]
Fixed by commit d171b7a
