### ISSUE TITLE
db_get_user_group() does not return group

### ISSUE THREAD

**Issue by miha-** [OpenSIPS/opensips#558]
Hi,

I am trying to use db_get_user_group() for getting group but it fails. For the same URI (using $fu) I am getting results with db_is_user_in().

br
miha

**Comment by bogdan-iancu** [comment]
@miha- , maybe the docs are not 100% clear, but this function is to be used for regexp-based groups, againsr the re_grp table (and not against the group table).
Is this what you are testing ?

**Comment by bogdan-iancu** [comment]
@miha- , any comment ? otherwise I will close this as 95% I think you are mis using the function.

**Comment by bogdan-iancu** [comment]
@miha, if my answer did not solve your issue, please reopen the ticket.

**Comment by miha-** [comment]
Bogdan tnx. You can close it, I was out of office and that is whay I did not replay to you sooner.

br
miha

**Comment by bogdan-iancu** [comment]
Thx @miha- , already closed :)
