### ISSUE TITLE
ds_select_dst may put "probing" destinations in the failover list

### ISSUE THREAD

**Issue by gergelypeli** [OpenSIPS/opensips#564]
This is a minor issue, just encountered it recently. When ds_select_dst picks a destination, it is always an "active" one. But the candidates for failover are just "not inactive". This means that a destination currently in probing state is never picked directly, but can be picked for failover.

So if the first server chosen just became unreachable, we'd try another one that we already know to be unreachable, which is a bit weird. I'd suggest only using "active" destinations for the failovers, too.

Happened in 1.11.3, but the situation seems to be the same in the master branch.

**Comment by bogdan-iancu** [comment]
Hi @gergelypeli - that makes a lot of sense, we will look into a fast fix. 
Thank you, Bogdan

**Comment by bogdan-iancu** [comment]
Hi @gergelypeli , Indeed, only the INACTIVE flags was set, not the PROBING too. I make the necessary fixes in trunk, 2.1 and 1.11 branches.

Thanks and regards,
Bogdan
