### ISSUE TITLE
Add MI command to see cached dr rules

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#567]
DR Rules in drouting module has no command to dump/verify dr rules loaded by opensips. Especially in scenarios where the rules have already been changed in the database but not reloaded by opensips, it is difficult to debug why calls have been routed to some dst.

If the data set might be too large to be dumped, maybe it would be useful to have a way to restore the rules to the database, or maybe some other command to dump the output and paginate it.
Or maybe some command to search for a pattern and return its associated rule.

```
opensipsctl dr rules_status 1:50     # return first 50 records

opensipsctl fifo dr_rules_search 011      # return all rules matching prefix 011

+--------+---------+-------------+---------+----------+---------+-------------------------------------------+-------+--------------------+
| ruleid | groupid | prefix      | timerec | priority | routeid | gwlist                                    | attrs | description        |
+--------+---------+-------------+---------+----------+---------+-------------------------------------------+-------+--------------------+
|      1 | 0       | 011972      |         |        0 | NULL    | carrier1,carrier2,intlCarrier             | NULL  | Israel numbers     |
|      2 | 0       | 01144       |         |        0 | NULL    | londonCarrier,intlCarrier                 | NULL  | UK                 |
|      3 | 0       | 011         |         |        2 | NULL    | londonCarrier,intlCarrier                 | NULL  | All Others         |
```

**Comment by ionel-cerghit** [comment]
Hello,

We already have a MI function that prints the matched prefix along with the list of the gateways / carriers to which a number would be routed.

http://www.opensips.org/html/docs/modules/2.1.x/drouting.html#id296773

Would this be enough for your use purposes?

Regards 
Ionel

**Comment by ar45** [comment]
Yes.

**Comment by ar45** [comment]
Although it would still be useful to be able to dump to a file for later debugging. Although one can just do a core dump to debug, I still this useful.
