### ISSUE TITLE
xlog - add option to prefix log messages with log level

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#568]
Just like the core log messages it would be nice to have a option to have xlog statements prefix the Log Level to the logs.

**Comment by nikbyte** [comment]
Why not to do it by configuring syslog?

**Comment by liviuchircu** [comment]
Not really sure if I understood right, but if you're asking for this:

    xlog("L_INFO", "Hi, this is INFO level debug\n");

then it has been in OpenSIPS since forever.

**Comment by ar45** [comment]
@liviuchircu the log level now only controls at which level it should be emitted.  After the message is logged there is no way to know what level that came from.  Having the log level in the message helps you analyze the logs more easily.

**Comment by liviuchircu** [comment]
Very useful. I would also like to suggest adding the "current_route" to the log line.

**Comment by ar45** [comment]
Then it would make more sense to have a global param to set the common template format for all xlog messages, something like

```
xlog_format = "[%L_LEVEL - %ROUTE_TYPE(%ROUTE_NAME) Line:%LINE_NO] %MSG"

xlog("L_ERR", "Failed to route to PSTN attempt($avp(relay_count))\n");
```

resulting in a syslog message like
```
Jul  7 05:49:52 hostname opensips[31929]: [ERR - failure_route(HANDLE_FAILURE) Line:954] Failed to route to PSTN attempt(3)
```

**Comment by ar45** [comment]
related to #663

**Comment by ionel-cerghit** [comment]
Is https://github.com/OpenSIPS/opensips/pull/915 ok for the basic feature?
