### ISSUE TITLE
Opensips 2.1 crash on mysql reconnect using Async(avp_db_query(..),resumeroute)

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#572]
Information I currently have is only from log.
Will enable core dumping and attach if i have it.

version: opensips 2.1.0 (x86_64/linux)
git revision: d3409fe

Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: INFO:db_mysql:switch_state_to_disconnected: disconnect event for 0x7fa900c79130
Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: INFO:db_mysql:reset_all_statements: reseting all statements on connection: (0x7fa900c72df8) 0x7fa900c79130
Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: INFO:db_mysql:connect_with_retry: re-connected successful for 0x7fa900c79130
Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: CRITICAL:tm:io_watch_add: #012>>> [UDP_worker] BUG trying to overwrite entry 12 in the hash(12, 16, 0x7fa8fb87db90,1) with (12, 16, 0x7fa8fb8797a0,1)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: ERROR:tm:t_handle_async: failed to add async FD to reactor -> act in sync mode
Jul 13 16:47:17 DEV-RIK-5 /sbin/opensips[19426]: CRITICAL:db_mysql:db_mysql_async_raw_resume: #012>>> no conn match for fd 12#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues#012
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19413]: INFO:core:handle_sigs: child process 19426 exited by a signal 6
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19413]: INFO:core:handle_sigs: core was generated
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19413]: INFO:core:handle_sigs: terminating due to SIGCHLD
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19425]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19423]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19422]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19421]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19420]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19419]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19418]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19417]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19416]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19415]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19424]: INFO:core:sig_usr: signal 15 received
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19413]: INFO:core:cleanup: cleanup
Jul 13 16:47:20 DEV-RIK-5 /sbin/opensips[19413]: NOTICE:event_route:destroy: destroy module ...

**Comment by liviuchircu** [comment]
Commit 244140c fixed a bug where this exact type of bug would occur for all bad queries (bad syntax / bad semantics ...)

Could you please update your sources to latest 2.1 first? Thanks

**Comment by hydrosine** [comment]
Update to git revision: 7c0b087

I will report back tomorrow.

**Comment by hydrosine** [comment]
triggered several reconnects, no crashes :)
