### ISSUE TITLE
Cryptic error messages when json.so is not loaded

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#574]
If you happen to forget to load the **json.so** module, you will run into this kind of mess:

Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: pvar "json"(inner_name) not found
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: wrong char [j/106] in [$json(json_res)] at [6 (5)]
Jul 15 11:04:10 ip-172-31-4-47 opensips: CRITICAL:core:yyerror: parse error in config file /usr/local/etc/opensips/opensips.cfg, line 375, column 12-27: unknown script variable
Jul 15 11:04:10 ip-172-31-4-47 opensips: CRITICAL:core:yyerror: parse error in config file /usr/local/etc/opensips/opensips.cfg, line 375, column 46-47: invalid left operand in assignment
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: pvar "json"(inner_name) not found
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: wrong char [j/106] in [$json(json_res/pop)] at [6 (5)]
Jul 15 11:04:10 ip-172-31-4-47 opensips: CRITICAL:core:yyerror: parse error in config file /usr/local/etc/opensips/opensips.cfg, line 376, column 45-64: unknown script variable
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: pvar "json"(inner_name) not found
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: wrong char [j/106] in [$json(json_res/uri)] at [6 (5)]
Jul 15 11:04:10 ip-172-31-4-47 opensips: CRITICAL:core:yyerror: parse error in config file /usr/local/etc/opensips/opensips.cfg, line 381, column 38-57: unknown script variable
Jul 15 11:04:10 ip-172-31-4-47 opensips: ERROR:core:pv_parse_spec: pvar "json"(inner_name) not found

**Comment by bogdan-iancu** [comment]
@liviuchircu , that will happen when you try to use any Variable exported by a module (not provided by core) without loading that particular module. 
It is not particular to  json module only.
