### ISSUE TITLE
B2B + uac_auth - corrupted INVITE packet

### ISSUE THREAD

**Issue by DMOsipov** [OpenSIPS/opensips#577]
I have OpenSIPS packages installed on Debian Wheezy.
* opensips 2.1.0-2~1.gbp4480d1
* opensips-b2bua-module 2.1.0-2~1.gbp4480d1

OpenSIPS works as outbound proxy for SIP-agents in local network and implements B2B topology hiding scenario.
Additionally it performs UAC authentication against destination SIP-server.

If local_route is NOT specified in the opensips.cfg then everything works as expected. OpenSIPS sends INVITE towards destination server, receives "407 Proxy Authentication Required" and sends INVITE once again using credentials specified in uac_auth.credential parameter.

But if local_route is specified and not empty then second INVITE packet is not correct. Seems this is an issue with memory buffers management because there is some garbage in the packet (see trace below).

In the config and in the SIP trace below 
* 192.168.56.4 - OpenSIPS implementing B2B topology hiding + UAC authentication
* 192.168.56.3 - destination SIP server requiring authentication

Here is my opensips.cfg
```
debug=4
log_stderror=no
log_facility=LOG_LOCAL1
children=4
auto_aliases=no
listen=udp:192.168.56.4:5060
mpath="/usr/lib/opensips/modules/"
loadmodule "proto_udp.so"
modparam("proto_udp", "udp_port", 5060)
loadmodule "sipmsgops.so"
loadmodule "db_text.so"
loadmodule "uac_auth.so"
modparam("uac_auth","credential","9000:192.168.56.3:1234")
loadmodule "tm.so"
modparam("tm", "pass_provisional_replies", 1)
modparam("tm", "onreply_avp_mode", 1)
loadmodule "b2b_entities.so"
modparam("b2b_entities", "script_req_route", "b2b_request")
modparam("b2b_entities", "script_reply_route", "b2b_reply")
loadmodule "b2b_logic.so"

route[b2b_request] {
    xlog("L_INFO", "[b2b_request] method=$rm, uri=$ru, contact=$ct, call_id=$ci, src_address=$si:$sp, dst_address=$Ri:$Rp");
}

route[b2b_reply] {
    xlog("L_INFO", "[b2b_reply] method=$rm, status=$rs, contact=$ct, call_id=$ci, src_address=$si:$sp, dst_address=$Ri:$Rp");
}

local_route {
    xlog("L_INFO", "[local] method=$rm, uri=$ru, contact=$ct, call_id=$ci, src_address=$si:$sp, dst_address=$Ri:$Rp");
}

route {
    xlog("L_INFO", "[default] method=$rm, uri=$ru, contact=$ct, call_id=$ci, src_address=$si:$sp, dst_address=$Ri:$Rp");

    if (is_method("INVITE")) {
        b2b_init_request("top hiding");
    }
}
```

This is corrupted INVITE packet send after "407 Proxy Authentication Required" (the line after Proxy-Authorization header is a corrupted data that can not be parsed by destination SIP server) 
```
U 192.168.56.4:5060 -> 192.168.56.3:5060
INVITE sip:123@192.168.56.3 SIP/2.0.
Via: SIP/2.0/UDP 192.168.56.4:5060;branch=z9hG4bK31d2.39c97747.0.
To: sip:123@192.168.56.3.
From: <sip:9000@192.168.56.3>;tag=09ce71be7287589c0ed1c8fd51287ec7.
CSeq: 3 INVITE.
Call-ID: B2B.69.303482.
Max-Forwards: 70.
Content-Length: 234.
User-Agent: OpenSIPS (2.1.0 (x86_64/linux)).
Proxy-Authorization: Digest username="9000", realm="192.168.56.3", nonce="55ae22ae0000001d82d430b449995b7c1e5668ac9af40114", uri="sip:123@192.168.56.3", response="9cab361d24060fde3ca9c3eebac97b70", algorithm=MD5.
.......................x.......................................................x[......................B2B.69.303482sip:123@192.168.56.3sip.
000@192.168.56.3472439456 1 IN IP4 10.0.0.42.
s=X-Lite release 4.8.4 stamp 76590.
c=IN IP4 10.0.0.42.
t=0 0.
m=audio 58914 RTP/AVP 9 8 0 84 101.
a=rtpmap:84 speex/16000.
a=rtpmap:101 telephone-event/8000.
a=fmtp:101 0-15.
a=sendrecv.
```

**Comment by bogdan-iancu** [comment]
@DMOsipov, this happens due a poor implementation of the b2b auth in combination with usage of local route (for b2b INVITEs). Unfortunately the fix is not trivial - to be honest, I do not even have a straight solution to this.
Nevertheless, I will try to come up with a something on this.

Regards,
Bogdan

**Comment by bogdan-iancu** [comment]
Hi @DMOsipov , there is a fix available for testing, here is it : https://gist.github.com/bogdan-iancu/a5446fa8ff5d9676796e
If you could give it a try and provide feedback, it will be great.

Thanks,
Bogdan

**Comment by DMOsipov** [comment]
Hi Bogdan, 
Thanks a lot for a fix.
I will check and give my feedback.

**Comment by DMOsipov** [comment]
Hi Bogdan,

Sorry for delay with the answer.
According to patch name I assumed that it is suitable for opensips 1.11.
I've checked the patch with release 1.11 and it fixed the issue.
Thanks a lot ! 

Should I check it with 2.1 as well ?

Best regards,
Dmitry

**Comment by bogdan-iancu** [comment]
Hi @DMOsipov ! Thanks for the testing, I uploaded the fix on dev, 2.1, 1.11 and 1.8 branches.

**Comment by korithi** [comment]
Hi Bogdan,

I am testing this on release 2.4.7 and no luck.
Does this really works?
Thanks!

**Comment by korithi** [comment]
Hi Bogdan,

Just found my issue. After debugging I saw that it was not executing the uac_auth function because it could not find the realm sent by the provider in the avp. It was a typo of the realm name.
By the way is it a way to get the realm value from the header on the 401 message that providers send? I need to put it in the avp and use in the script.
Thank you!
