### ISSUE TITLE
modules/lua/sipmemcache.c uses libmemcache instead of libmemcached

### ISSUE THREAD

**Issue by nud** [OpenSIPS/opensips#580]
cachedb modules use libmemcached, but the lua module uses libmemcache instead.

Apart from being two different libraries doing the same thing, the problem is that Debian Jessie doesn't package libmemcache anymore, so the lua module cannot be built anymore.

**Comment by razvancrainea** [comment]
The lua module has been ported to memcached. Closing the ticket now.
