### ISSUE TITLE
$json assign operators ("=" and ":=")

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#583]
Is there a use case for the simple assign operator **"="** when using $json variables? (does it make sense to use it at all?)

As I see things, forcing the script writer to remember to use **:=** is a bit unnecessary, and the default $json assign **"="** operator should parse the input by default.

**Comment by bogdan-iancu** [comment]
@liviuchircu , the '=' operator is used to write a field into the json object, while the ':=' operator is used to instantiate the whole json object from a string representation.
