### ISSUE TITLE
How to get the size of avp?

### ISSUE THREAD

**Issue by was4444** [OpenSIPS/opensips#585]
Hi there,
How can I get the size of result when use avp_db_query?
Thanks.

**Comment by bogdan-iancu** [comment]
Hi @was4444 - you mean after getting an avp back as a result of the query, how do you get the length of the string in that AVP ? or ?

**Comment by was4444** [comment]
Hi @bogdan-iancu, 
Not the length of string, but the **count** of results that strored in AVP.
I don't know if it's safe to use $(avp(foo)[10]) without knowing the count of it.

**Comment by bogdan-iancu** [comment]
@was4444 , it is safe to do overflow of the index - you will simply get a null value back.

To actually count the number of values the AVP holds, see the set_count() function:
     http://www.opensips.org/html/docs/modules/2.1.x/cfgutils.html#id293905

**Comment by was4444** [comment]
Thanks @bogdan-iancu , you really help me a lot.
I should really upgrade to the latest version.

**Comment by bogdan-iancu** [comment]
@was4444, this function is available in 1.11 and older versions too. no need to upgrade in order to use it.
