### ISSUE TITLE
crash issue in tcpconn_add_alias (2.1)

### ISSUE THREAD

**Issue by dbeskoek** [OpenSIPS/opensips#589]
During running a sipp-scenario against an opensips2.1  doing tls<->udp traversing we are able to easily crash this opensips within seconds. As soon as we disable tcp_accept_aliases the crashes are gone. We are heavily generating new tls-sessions (around 1000 per second), so we will reuse source-ports. Maybe this forces this segfault.

gdb(bt full):
```
#0  0x000000000059a2bf in tcpconn_add_alias (id=<error reading variable: Cannot access memory at address 0x7ffefb7b78b8>, port=5067,
    port@entry=<error reading variable: Cannot access memory at address 0x7ffefb7b78b8>, proto=<error reading variable: Cannot access memory at address 0x7ffefb7b78b8>) at net/net_tcp.c:766
        c = 0x7ff422570658
        hash = 0
        a = <optimized out>
        __FUNCTION__ = "tcpconn_add_alias"
```

**Comment by bogdan-iancu** [comment]
Hi @dbeskoek , are you using the latest 2.1 code from GIT ? 

can you recompile without optimization (see Makefile.defs, line 722, removing -O9) and check in the corefile the a variable ?

Regards, Bogdan

**Comment by dbeskoek** [comment]
Hi Bogdan, yes, latest 2.1code from GIT was used. requested output:

```
#0  0x000000000052247a in tcpconn_add_alias (id=1358, port=5063, proto=3) at net/net_tcp.c:766
        c = 0x7f311a308470
        hash = 938
        a = 0x7f31115f35d8
        __FUNCTION__ = "tcpconn_add_alias"
```

**Comment by bogdan-iancu** [comment]
@dbeskoek , could you do a "list" in gdb, to see what is your line 766 ? In my case it is a LM_WARN : 
    LM_WARN("alias already present and points to another connection "
            "(%d : %d and %d : %d)\n", a->parent->id,  port, c->id, port);

Is this correct ?

**Comment by dbeskoek** [comment]
thats correct:
```
761             LM_ERR("no connection found for id %d\n",id);
762             return -1;
763     error_sec:
764             TCPCONN_UNLOCK(id);
765             LM_WARN("possible port hijack attempt\n");
766             LM_WARN("alias already present and points to another connection "
767                             "(%d : %d and %d : %d)\n", a->parent->id,  port, c->id, port);
768             return -1;
769     }
770
```

**Comment by bogdan-iancu** [comment]
ok, try printing in gdb the vars: a,  a->parent, c

**Comment by dbeskoek** [comment]
```
(gdb) p a
$1 = (struct tcp_conn_alias *) 0x7f31115f35d8
(gdb) p a->parent
$2 = (struct tcp_connection *) 0x0
(gdb) p c
$3 = (struct tcp_connection *) 0x7f311a308470
```

**Comment by bogdan-iancu** [comment]
ok, so a->parent->id is crashing...let me check on it

**Comment by bogdan-iancu** [comment]
Is there any chance to get direct access to the corefile (ssh?) the debugging gets a bit more complex at this stage.

**Comment by bogdan-iancu** [comment]
@dbeskoek , I sent you on last Friday, by email, a patch to be tested. Any luck with that ?

**Comment by dbeskoek** [comment]
sorry, for the delay. I did several tests with the patch, all of them were fine, no crash appears. I reverted to GIT-version and the crash occurs again. Patch is working :-)

**Comment by bogdan-iancu** [comment]
Great @dbeskoek , especially that the faulty line was the log line itself, not the useful code. I will commit and backport asap
Thanks and regards, Bogdan
