### ISSUE TITLE
perl_exec() does not accept variable as a parameter

### ISSUE THREAD

**Issue by wayback87** [OpenSIPS/opensips#594]
perl_exec() function of OPENSIPS Perl API does not accept variable as a parameter. Thiis is feature request to add support for variable to be passed as a parameter to perl_exec() function.

**Comment by ionutrazvanionita** [comment]
hi @wayback87 . try https://github.com/OpenSIPS/opensips/commit/3d91beb27b69e5b1d83d96b1998856f81f995ce1
