### ISSUE TITLE
dispatcher module PVAR(9) algorithm and send() function

### ISSUE THREAD

**Issue by hd16861686** [OpenSIPS/opensips#604]
Hello all,
I know dispatcher is a stateless load balancer, from its document I get that PVAR(9) algorithm can select a destination the load of each destination, and param pvar_algo_pattern is used by the algorithm to specify the pseudovariable pattern used to detect the load of each destination. but I want to know how dispatcher detect the real-time load of each destination?   and what's the load considered? registered user number or call session number?

another issue about send() function. from some mail before in opensips.org, I got this function is a stateless function for sending a request out but without adding any VIA in the request, So the hop doing send() will be invisible for the replies also (the replies will bypass this hop as there is no VIA for it), but I also find the parameter of this function  is mandatory and can not be missed, so how can I use send() function with dispatcher ds_select_dst function together?  because I really want make my dispatcher invisible except for the initial request..

**Comment by razvancrainea** [comment]
The purpose of the dispatcher 9th algorithm is to allow you to load balance destinations based on any indices you want. For example, if you want to balance them based on their load (how many calls it has), you can do something like this:

```
modparam("dispatcher", "pvar_algo_pattern", "$stat(load_%u)")
...
# new call in script
ds_select_domain("0", "9");
# $dd contains the selected destination - we have to increase the load
update_stat("load_$rd", "+1");
```

>  but I also find the parameter of this function is mandatory and can not be missed

the destination in `send(destination)` is indeed a variable field that does not support pseudo-variables, so you can't use this function.

However, you can use the `forward()`[1] function, that sends the message to the message to the `$rd` in a stateless mode.

[1] http://www.opensips.org/Documentation/Script-CoreFunctions-2-1#toc18
