### ISSUE TITLE
Compilation error on RH6

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#606]
I've seen that since version 2.1 of Opensips there is a blocking compilation error on RH6.
The error launching "make" is the following:

```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_mysql '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_postgres '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_oracle '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_berkeley '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_text '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep _radius '
```
I've investigated the isssue and I discovered that is caused by the command "module" that was introduced by RedHat since version 6.

The code causing the conflict is the follow in Makefile: 
```
    102 ifneq ($(module),)
    103         modules:=$(addprefix modules/, $(module))
    104 endif
```

On RH6, instead of expanding that variable, it executes the module command.

A simple workaround is to launch, instead of make, the following:
```make module=```

It will be appreciated if you would fix the issue

Thank you

Alessandro Rovetto

**Comment by bogdan-iancu** [comment]
@arovetto , thanks for your investigation and report . We will fix this asap.

**Comment by razvancrainea** [comment]
I just compiled on Centos 6.5 and RH 6.4 and I don't see that error.
Can you please send me the make version and the exact output of your command?

**Comment by arovetto** [comment]
I'm using Red Hat Enterprise Linux Server release 6.3 (Santiago).
My make version is 3.81.

The error I get is the following:

[root@dev-c2m-el6 opensips-2.1.0]# make modules
which: no lynx in (/opt/reitek/ct6/bin:/opt/reitek/ct6/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/bin/X11:/usr/local/bin:/usr/java/bin:/usr/local/kde/bin:/usr/java2/bin:/usr/ccs/bin:/usr/java/j2re1.4.2_08/bin:.:/home/oracle/product/11.2.0/dbhome_1/bin:/home/reicom/bin:/usr/local/berkeleydb/bin:/usr/local/openldap/bin:/usr/local/openldap/sbin)
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_mysql '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_postgres '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_oracle '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_berkeley '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep db_text '
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`}| grep _radius '
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `for r in modules/() modules/{ modules/eval modules/`/usr/bin/modulecmd modules/bash modules/`'
make: *** [modules] Error 1

The error is cause by the name conflict with the "module" command that is installed on my server, I think it is coming from RPM:
environment-modules-3.2.7b-6.el6.i686

Is it installed on your server, too?

If it can help you, running "module" I get the following:

[root@dev-c2m-el6 opensips-2.1.0]# module
cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.7 2009-07-30 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
        -H|--help               this usage info
        -V|--version            modules version & configuration options
        -f|--force              force active dependency resolution
        -t|--terse              terse    format avail and list format
        -l|--long               long     format avail and list format
        -h|--human              readable format avail and list format
        -v|--verbose            enable  verbose messages
        -s|--silent             disable verbose messages
        -c|--create             create caches for avail and apropos
        -i|--icase              case insensitive
        -u|--userlvl <lvl>      set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
        + add|load              modulefile [modulefile ...]
        + rm|unload             modulefile [modulefile ...]
        + switch|swap           [modulefile1] modulefile2
        + display|show          modulefile [modulefile ...]
        + avail                 [modulefile [modulefile ...]]
        + use [-a|--append]     dir [dir ...]
        + unuse                 dir [dir ...]
        + update
        + refresh
        + purge
        + list
        + clear
        + help                  [modulefile [modulefile ...]]
        + whatis                [modulefile [modulefile ...]]
        + apropos|keyword       string
        + initadd               modulefile [modulefile ...]
        + initprepend           modulefile [modulefile ...]
        + initrm                modulefile [modulefile ...]
        + initswitch            modulefile1 modulefile2
        + initlist
        + initclear


Thank you very much,

**Comment by razvancrainea** [comment]
I tried to install the module command but still can't replicate this behavior.
Can you check whether the latest code (2.1.1) still has this problem?

**Comment by arovetto** [comment]
Version 2.1.1 hasn't  the problem. Thank you

**Comment by razvancrainea** [comment]
Since 2.1.0 has been replaced by 2.1.1 and in this version works, I will close this issue.
