### ISSUE TITLE
Messages are cut by opensips after the UAC AUTH Module usage

### ISSUE THREAD

**Issue by xxReaper** [OpenSIPS/opensips#628]
Hi, here is the situation, Opensips sends an invite to Freeswitch:

   INVITE sip:5f0913d5@2.2.215.38:5080 SIP/2.0
   Via: SIP/2.0/UDP 2.2.215.38:5060;branch=z9hG4bK0a13.9337d911.0
   To: sip:5f0913d5@2.2.215.38:5080
   From: <sip:0970282928@2.2.215.38:5080>;tag=db8569aa98c1d18305c6a77cb692291a
   CSeq: 4 INVITE
   Call-ID: B2B.471.458138
   Max-Forwards: 70
   Content-Length: 968
   User-Agent: OpenSIPS (1.11.3-notls (x86_64/linux))
   Contact: <sip:2.2.215.38:5060>
   Content-Type: application/sdp
   X-Additional-ID: campaign_308
   X-Record-Call: 1
   
   v=0
   o=FreeSWITCH 1441189586 1441189587 IN IP4 2.2.215.38
   s=FreeSWITCH
   c=IN IP4 2.2.215.38
   t=0 0
   a=msid-semantic: WMS KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot
   m=audio 22198 RTP/SAVPF 116 8 101 13
   a=rtpmap:116 opus/48000/2
   a=fmtp:116 useinbandfec=1; usedtx=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=20; maxptime=20; samplerate=48000
   a=rtpmap:8 PCMA/8000
   a=rtpmap:101 telephone-event/8000
   a=fingerprint:sha-256 0F:6F:6A:E3:BB:AD:14:56:E7:9E:F6:E7:54:B6:AA:D2:18:B7:93:0B:3F:51:B7:2A:13:5F:0B:A9:EF:0D:4D:1F
   a=rtcp-mux
   a=rtcp:22198 IN IP4 2.2.215.38
   a=ssrc:2045511480 cname:n8WvcYUSdtMQmWwf
   a=ssrc:2045511480 msid:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot a0
   a=ssrc:2045511480 mslabel:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot
   a=ssrc:2045511480 label:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ota0
   a=ice-ufrag:oFcnFIZ86kMQb19o
   a=ice-pwd:0WK3LvLPPov1aR7pm9CSIrQF
   a=candidate:9565237517 1 udp 659136 2.2.215.38 22198 typ host generation 0
   a=ptime:20

Freeswitch reply 407

Opensips use the credentials with UAC AUTH module and re-sends the invite with auth:

INVITE sip:5f0913d5@2.2.215.38:5080 SIP/2.0
   Via: SIP/2.0/UDP 2.2.215.38:5060;branch=z9hG4bK1a13.e3a8f07.0
   To: sip:5f0913d5@2.2.215.38:5080
   From: <sip:0970282928@2.2.215.38:5080>;tag=db8569aa98c1d18305c6a77cb692291a
   CSeq: 5 INVITE
   Call-ID: B2B.471.458138
   Max-Forwards: 70
   Content-Length: 968
   User-Agent: OpenSIPS (1.11.3-notls (x86_64/linux))
   Proxy-Authorization: Digest username="opensips", realm="2.2.215.38", nonce="5552395d-a8fc-4ba2-a14d-8ecdb383a824", uri="sip:5f0913d5@2.2.215.38:5080", qop=auth, nc=00000001, cnonce="3226146401", response="579fa547b7ff862b049ff38372593beb", algorithm=MD5
   X-Additional-ID: campaign_308
   X-Record-Call: 1
   
   Additional-ID: campaign_308
   X-Record-Call: 1
   
   v=0
   o=FreeSWITCH 1441189586 1441189587 IN IP4 2.2.215.38
   s=FreeSWITCH
   c=IN IP4 2.2.215.38
   t=0 0
   a=msid-semantic: WMS KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot
   m=audio 22198 RTP/SAVPF 116 8 101 13
   a=rtpmap:116 opus/48000/2
   a=fmtp:116 useinbandfec=1; usedtx=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=20; maxptime=20; samplerate=48000
   a=rtpmap:8 PCMA/8000
   a=rtpmap:101 telephone-event/8000
   a=fingerprint:sha-256 0F:6F:6A:E3:BB:AD:14:56:E7:9E:F6:E7:54:B6:AA:D2:18:B7:93:0B:3F:51:B7:2A:13:5F:0B:A9:EF:0D:4D:1F
   a=rtcp-mux
   a=rtcp:22198 IN IP4 2.2.215.38
   a=ssrc:2045511480 cname:n8WvcYUSdtMQmWwf
   a=ssrc:2045511480 msid:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot a0
   a=ssrc:2045511480 mslabel:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ot
   a=ssrc:2045511480 label:KxUCidczQoI3M2jQ3Cj689GMDxvOT0ota0
   a=ice-ufrag:oFcnFIZ86kMQb19o
   a=ice-pwd:0WK3LvLPPov1aR7pm9CSIrQF
   a=candidate:9565237517 1 udp 659136 178.62

The end is being cut it should look like:

a=candidate:9565237517 1 udp 659136 2.2.215.38 22198 typ host generation 0
   a=ptime:20

It is not MTU as whatever the size of the invite, it is allways cut after the auth usage.

How can i resolve this ?

**Comment by bogdan-iancu** [comment]
The fix to be tested is available under https://gist.github.com/bogdan-iancu/a5446fa8ff5d9676796e .
Waiting for your feedback @xxReaper !

Thanks and regards,
Bogdan

**Comment by bogdan-iancu** [comment]
Hi @xxReaper  ! The fix was uploaded on dev, 2.1, 1.11 and 1.8 branches.
