### ISSUE TITLE
opensips 2.1 not starting with "avp_db_query" and without "db_url" param

### ISSUE THREAD

**Issue by pavigor** [OpenSIPS/opensips#637]
I tried to use **avp_db_query()** without *db_url* specification (only db_default_url), but opensips don't want to start without this parameter. At the same time there is no any debug information in log why it don't want to start.

**Comment by bogdan-iancu** [comment]
Hi @pavigor , this looks like the same issue as #644 . I will close your report and continue the investigation on #644 (as more info is provided there.)
Thanks and regards, Bogdan
