### ISSUE TITLE
Post failure route issues

### ISSUE THREAD

**Issue by soulofmischief87** [OpenSIPS/opensips#645]
I am using opensips 2.2-dev git revision: 0faac6a and I am seeing issues when sending a request to second  route for failover purpose(AS server) When the source is a WS client. I am using sipjs version 0.7.1

within this 2nd route i'm specifying (sip:ip:port) but opensips is sending this request as a websocket. 

which concludes in this error:

CRITICAL:proto_ws:ws_server_handshake

Only when the request  goes from the failure route to the failover route. In the event that I route the request directly to the 2nd route upon failure to find the AOR entry for the user from the main route.  Opensips does send the request go to AS server as a sip request. Another note to add is that opensips does not revert the ruri . In the case of sipjs it utilizes a random string for contact entries upon registration. Opensips uses this as the ruri when making the request it does not revert them upon failure route consequently the request reaches  failover route with this ruri as well. Can I use  revert_uri();

in this case? within the failover route?

What can be done over the fact that the request is being sent to the AS server as a ws?

Here is a debug log of the issue.

https://drive.google.com/file/d/0B1yz74eTHZFPV0Q0NmtObmw1aEU/view?usp=sharing

**Comment by razvancrainea** [comment]
This seems to be a scripting issue. Before sending the request to the 2nd AS, you should use the force_send_socket() function with the proper outgoing interface (TCP, UDP, whatever).
