### ISSUE TITLE
Opensips Crash, presentity Module

### ISSUE THREAD

**Issue by Madkonix** [OpenSIPS/opensips#646]
Hi Guys,

One of our opensips server crashed yesterday, our failover worked as planned but we would like to let you know in case there is a known a issue related to it or a fix we can already apply.

Here are the information relative to the opensips version we are using : 
version: opensips 1.11.5-notls (x86_64/linux)
flags: STATS: On, USE_IPV6, USE_TCP, DISABLE_NAGLE, USE_MCAST, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 02e886f
main.c compiled on 10:04:44 Sep  2 2015 with gcc 4.4.7

And the link to the infoe we extracted from the crash dump :
http://pastebin.com/xe14R4fN

Thank you,
Mamadou Koné

**Comment by razvancrainea** [comment]
It looks like OpenSIPS crashed due to an ```abort()``` call.

Can you check the logs if there are any errors?

Best regards,
Răzvan

**Comment by Madkonix** [comment]
Hi Răzvan,

Here are the individual errors that happened from 10min before the crash to 10min after : 

==================================================
ERROR:core:parse_first_line: at line 0 char 10: 
ERROR:core:parse_first_line: at line 0 char 13: 
ERROR:core:parse_first_line: bad request first line
ERROR:core:parse_first_line: parsed so far: 
ERROR:core:parse_msg: message=<>
ERROR:core:receive_msg: Unable to parse msg received from [10.132.112.114:5060]
ERROR:core:receive_msg: Unable to parse msg received from [10.132.112.210:5060]
ERROR:pua:publ_cback_func: No record found
ERROR:pua_usrloc:ul_publish: failed to send publish
ERROR:acc:acc_db_request: failed to insert into database
ERROR:core:db_do_delete: error while submitting query
ERROR:core:db_do_insert: error while submitting query
ERROR:core:db_do_update: error while submitting query
ERROR:core:parse_first_line: at line 0 char 11: 
ERROR:core:parse_first_line: at line 0 char 13: 
ERROR:core:parse_first_line: at line 0 char 16: 
ERROR:core:parse_first_line: at line 0 char 20: 
ERROR:core:parse_first_line: at line 0 char 5: 
ERROR:core:parse_first_line: bad request first line
ERROR:core:parse_first_line: parsed so far: 
ERROR:core:parse_msg: message=<>
ERROR:core:receive_msg: Unable to parse msg received from [10.132.112.114:5060]
ERROR:core:receive_msg: Unable to parse msg received from [10.132.112.210:5060]
ERROR:db_mysql:connect_with_retry: permanent re-connect failure for 0x7ffb16c57f38
ERROR:db_mysql:db_mysql_connect: driver error(2003): Can't connect to MySQL server on 'mysqlserver' (4)
ERROR:db_mysql:db_mysql_do_prepared_query: failed to create new context
ERROR:db_mysql:re_init_statement: failed to reconnect before trying mysql_stmt_prepare()
ERROR:presence:delete_db_subs: sql delete failed
ERROR:presence:get_stored_info: wrong sequence number;received: 1367 - stored: 1367
ERROR:presence:handle_publish: when updating presentity
ERROR:presence:handle_subscribe: getting stored info
ERROR:presence:handle_subscribe: in update_subscription
ERROR:presence:insert_subs_db: unsuccessful sql insert
ERROR:presence:update_db_subs: deleting expired information from database
ERROR:presence:update_presentity: inserting new record in database
ERROR:presence:update_presentity: No E_Tag match [a.1442606770.16919.5217.312]
ERROR:presence:update_presentity: updating published info in database
ERROR:presence:update_subscription: failed to insert subscription in database
ERROR:presence:update_subscription: updating subscription in database table
ERROR:presence:update_subs_db: updating presence information
ERROR:pua:pua_db_delete: Sql delete failed
ERROR:pua:publ_cback_func: No record found
ERROR:pua_usrloc:ul_publish: failed to send publish
==================================================

Thank you,
Mamadou

**Comment by razvancrainea** [comment]
Can you separate the logs before and after the crash? Perhaps the time is useful.

**Comment by Madkonix** [comment]
Hi Răzvan,
Here is a more detailed output of the logs : http://pastebin.com/mStnXxcB
The last error message before the crash is the one at 15:02:12 (Line 50).
Thank you,

**Comment by Madkonix** [comment]
Hi Răzvan,

Did you find anything ?

Thank you,
Mamadou Koné

**Comment by razvancrainea** [comment]
Unfortunately I still can't see anything. Can you tell me what debug 
level are you running?
Also, are you sure that the core you have posted the logs for is the 
only one? Are you also generating pid-based core files (use "echo 1 > 
/proc/sys/kernel/core_uses_pid").

Best regards,

Răzvan Crainea
OpenSIPS Core Developer
http://www.opensips-solutions.com

**Comment by bogdan-iancu** [comment]
Same as #854 which was already fixed. Closing....
