### ISSUE TITLE
B2B module and voicemail

### ISSUE THREAD

**Issue by dsanders11** [OpenSIPS/opensips#647]
I'm currently trying to use the B2B refer scenario (from the tutorial) for inbound calls. After advice from @bogdan-iancu on the user mailing list I fixed the natted SDP issue I was having, but now I've broken the ability to send calls to voicemail.

Previously I was using the same method as in the residential script under menuconfig: changing the destination and relaying in the `failure_route` if status was 486 or 408.

This however does not work in the B2B reply route when set. Two issues I've found.

1) Can't use `ds_select_domain` due to an error about the URI being wrong (it's using the status code for some reason)

```
Sep 23 12:08:06 [42508] DBG:dispatcher:w_ds_select: ds_select: 2 4 1000 1 1
Sep 23 12:08:06 [42508] DBG:dispatcher:ds_select_dst: set [2], using alg [4], size [1], used size [1], active size [1]
Sep 23 12:08:06 [42508] DBG:dispatcher:ds_select_dst: hash [0], candidate [0], weight sum [100]
Sep 23 12:08:06 [42508] DBG:dispatcher:ds_select_dst: candidate is [0]
Sep 23 12:08:06 [42508] DBG:dispatcher:ds_select_dst: using destination [0]
Sep 23 12:08:06 [42508] ERROR:core:parse_uri: uri too short: <486> (3)
Sep 23 12:08:06 [42508] ERROR:core:do_action: bad uri <486>, dropping packet
Sep 23 12:08:06 [42508] ERROR:dispatcher:ds_update_dst: error while setting host
Sep 23 12:08:06 [42508] ERROR:dispatcher:ds_select_dst: cannot set dst addr
```

2) If the address is manually provided instead, the `t_relay` fails next:

```
Sep 23 12:46:17 [43981] CRITICAL:tm:w_t_relay: unsupported route type: 4
```

Route type 4 being an `onreply_route`.

I have a sneaking suspicion that the first problem is also due to using `ds_select_dst` in an `onreply_route`, as it's not listed as a supported route type.

Would it be difficult to add a `script_failure_route` parameter to `b2b_entities` to handle this situation? I don't see how voicemail could work with a B2B scenario otherwise.

**Comment by dsanders11** [comment]
On further investigation, it is possible to set the `t_on_failure` route in `local_route` (this B2B stuff hurts the head a little) and get the same voicemail behavior as before.

It works, it's just a bit awkward because you lose all context in `local_route` about the leg (all the logic leading up to deciding which failure route to set). I'm setting custom headers and telling B2B to pass them so that I can get context, but it's not the most robust.

**Comment by bogdan-iancu** [comment]
Hi @dsanders11 , is here anything left to be reported ? I noticed you managed to find the answers by yourself :)
