### ISSUE TITLE
running out of pkg_mem

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#651]
running on master commit 72926c21780712fabd00a86dafeb292fde656b28

Every few days my https://github.com/etamme/federated-sip server runs out of pkg_mem.

It is a very low traffic box so I definitely think something is leaking some where.  I will post logs the next time it happens.

**Comment by bogdan-iancu** [comment]
@etamme , have you tried to enable the memory debugging:
    http://www.opensips.org/Documentation/TroubleShooting-OutOfMem
And fire a USR1 signal to the process complaining of lack of memory in order to force it to do a mem dump ? Some patterns in the used memory may reveal the problem.

**Comment by opensips-github** [comment]
I am seeing something that I suspect is similar.  This reply is going to be
lite on details but next I'll go refresh the source from git and turn on
the memory debugging and send updates.

I have a proxy running git branch 2.1.  It is reloading the address table
from a cron every minute and handling a call per day or less.  The fifo
process starts complaining about not having memory in a days time and after
that the first time I run the address reload command from the console the
opensips core dumps.

The core happened at line 132 in address.c

I did have the memory log on but did not have the memory debugging enabled
so suspect all the logs I have are unhelpful.

I'll send more info as I get it.

**Comment by opensips-github** [comment]
FYI make clean and make realclean don't clean up the
modules/cachedb_cassandra directory which leads to an undefined symbol
error on startup because I wasn't paying attention.

[root@opensips-dev-01.lab1 opensips-2-git]# tree |grep "\.o"
├── curses.out
│   ├── dictionary.opensips
│   │   ├── cachedb_cassandra_dbase.o
│   │   ├── cassandra_constants.o
│   │   ├── Cassandra.o
│   │   ├── cassandra_types.o
│   ├── opensipsctl.oracle
│   ├── opensipsdbctl.oracle
│   ├── opensipsdbfunc.oracle

**Comment by etamme** [comment]
hey @bogdan-iancu I actually have an entirelog from startup to shutdown of this happening - its not very verbose though.

basically i set up a cronjob to search the log fork pkg mem warnings - as soon as it detects one it kills opensips and makes a back up of the log, then starts opensips again, this is kind of a cheap way to keep things running as well as catch it in the act.

The full log is available at the following link:

https://owncloud.uphreak.com/index.php/s/ql8qPgJD2vEqtTQ

**Comment by 46labs** [comment]
Bogdan,

This just hit us too...we are running a considerable amount of traffic though. However, interestingly enough it did not pop up until the async leak was fixed. This did not happen before async dbops was enabled. That might help narrow this down. It does not drop a core....just starts scrolling no pkg memory left.

**Comment by bogdan-iancu** [comment]
@etamme , the log is a bit irrelevant - the only way to get at the bottom of this is to enable the memory debugging and allow memory dump - and your script, upon mem warn/err, should do a SIGUSR1 to that process (to see how the pkg mem is consumed).

**Comment by razvancrainea** [comment]
Hey Eric!

Any more issues with the latest version of OpenSIPS master?

Thanks,
Răzvan

**Comment by bogdan-iancu** [comment]
@etamme , any updates here ? There were several mem leaks fixed since your report and we want to know if the leak still happens for you.

**Comment by bogdan-iancu** [comment]
OK, closing now...if you have updated, please reopen.
