### ISSUE TITLE
topology_hiding + 302 response

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#656]
if you are using topology hiding and the UAS sends a 302, the data (new $ru) in the Contact header is not persisted to the UAC, meaning topology hiding is not valid in a scenario where a 302 may be found.

It would be useful (even if it was a per module setting or per transaction flag) to allow the full Contact header (or headers) sent by the UAS back to the UAC

**Comment by petekelly** [comment]
Hi, is this something that might be considered soon?

**Comment by bogdan-iancu** [comment]
Hi @petekelly - you mean to preserve the original Contact (as inserted by UAS) if a 3xx reply is pssing through TH ?

**Comment by petekelly** [comment]
Hi @bogdan-iancu! - Yes, and multiple Contact headers too if multiple are sent

**Comment by bogdan-iancu** [comment]
@petekelly , could you please test this via commit ea1eb62 ? If it does the trick for you, I can do a backport.
Thanks, Bogdan

**Comment by petekelly** [comment]
@bogdan-iancu not sure it is working 100% correctly. This is the reply from downstream to the topoh proxy (4 new URI's in Contact)

```
U 2016/04/07 07:07:07.349480 127.0.0.1:5066 -> 127.0.0.1:5065
SIP/2.0 302 Moved Temporarily.
Via: SIP/2.0/UDP 127.0.0.1:5065;branch=z9hG4bK6214.c4b8e4a.0.
From: "1000" <sip:1000@178.62.99.160>;tag=eKZ0vHBv0HjKm.
To: <sip:111;phone-context=+44@bla>;tag=92f5ffb840e560010ba1c8b8c154a11a.e976.
Call-ID: b55afc58-7753-1234-69ba-0401b01dc101.
CSeq: 89677549 INVITE.
Contact: sip:URI2@178.62.99.160:5060.
Contact: sip:URI3@178.62.99.160:5060.
Contact: sip:URI4@178.62.99.160:5060.
Contact: <sip:URI1@178.62.99.160:5060>.
Server: OpenSIPS (2.2-dev (x86_64/linux)).
Content-Length: 0.
```

The topoh server discards top URI and puts itself in place:

```
U 2016/04/07 07:07:07.349980 127.0.0.1:5065 -> 178.62.99.160:5060
SIP/2.0 302 Moved Temporarily.
Via: SIP/2.0/UDP 178.62.99.160;received=178.62.99.160;rport=5060;branch=z9hG4bKmjyBKZ6XKQ3aS.
From: "1000" <sip:1000@178.62.99.160>;tag=eKZ0vHBv0HjKm.
To: <sip:111;phone-context=+44@bla>;tag=92f5ffb840e560010ba1c8b8c154a11a.e976.
Call-ID: b55afc58-7753-1234-69ba-0401b01dc101.
CSeq: 89677549 INVITE.
Contact: <sip:127.0.0.1:5065;thinfo="VG9LbzAdIFsGAR1dEF50TH5XYX1tVn5edURqVGNlZH1QGicEalBhZHpffl9tRWpUY2Vh">.
Contact: sip:URI3@178.62.99.160:5060.
Contact: sip:URI4@178.62.99.160:5060.
Contact: <sip:URI1@178.62.99.160:5060>.
Server: OpenSIPS (2.2-dev (x86_64/linux)).
Content-Length: 0.
```


I would expect it to maintain all 4 Contact URI's

**Comment by bogdan-iancu** [comment]
Hi @petekelly , it looks like we have 2 bugs here:
1) the original one, to avoid TH on contacts in 3xx replies - and it looks like it still does it.
2) if multiple contacts are returned in a reply, only the first one is TH.

I will try to reproduce 1)

**Comment by petekelly** [comment]
Hi @bogdan-iancu did you have any success at all?

**Comment by bogdan-iancu** [comment]
@petekelly , there was the case of TH without dialog, case which still had to be fixed. Please try again

**Comment by arttemk** [comment]
Hello @bogdan-iancu  !

I've try this fix, but in case when phone send first SIP package in dialog Trying (or Ringing) like this

```
###
T 10.0.200.123:5060 -> 10.0.200.38:34515 [AP]
SIP/2.0 100 Trying.
Via: SIP/2.0/TCP 10.0.200.38:5060;branch=z9hG4bK3e5a.0604ef87.0.
From: <sip:2000@10.0.200.38>;tag=71fcc5b8eae9e3728bb6559c090b659f-8dee.
To: <sip:t49g@10.0.200.123:5060>;transport=TCP.
Call-ID: B2B.190.6828881.1500576383.
CSeq: 2 INVITE.
User-Agent: Yealink SIP VP-T49G 51.22.0.5.
Content-Length: 0.
```

and next SIP Package is Moved

```
##
T 10.0.200.123:5060 -> 10.0.200.38:34515 [AP]
SIP/2.0 302 Moved Temporarily.
Via: SIP/2.0/TCP 10.0.200.38:5060;branch=z9hG4bK3e5a.0604ef87.0.
From: <sip:2000@10.0.200.38>;tag=71fcc5b8eae9e3728bb6559c090b659f-8dee.
To: <sip:t49g@10.0.200.123:5060>;transport=TCP;tag=1458348720.
Call-ID: B2B.190.6828881.1500576383.
CSeq: 2 INVITE.
Contact: <sip:new@10.0.200.38:5060;transport=TCP>.
User-Agent: Yealink SIP VP-T49G 51.22.0.5.
Diversion: <sip:t49g@10.0.200.123:5060>;reason=unconditional.
Content-Length: 0.
```

On another b2b leg Contact was replaced

```
U 10.0.200.38:5060 -> 10.0.200.40:7060
SIP/2.0 302 Moved Temporarily.
Via: SIP/2.0/UDP 10.0.200.40:7060;received=10.0.200.40;branch=z9hG4bK-524287-1---5e02bd7f10afed5c29c5a738e4e;rport=7060.
To: <sip:t49g@gamma.ivcs.su>;tag=B2B.400.328.1500576383.
From: <sip:2000@10.0.200.38>;tag=27c95c08.
Call-ID: aWKZj0pb2z7P-Q5Bf8wbOg...
CSeq: 1 INVITE.
Orig-User-Agent: Yealink SIP VP-T49G 51.22.0.5.
Orig-Call-ID: B2B.190.6828881.1500576383.
Contact: <sip:10.0.200.38:5060>.
Server: OpenSIPS (2.2.4 (x86_64/linux)).
Content-Length: 0

```

**Comment by bogdan-iancu** [comment]
@arttemk , you claim that if you have a 100 before the 302, the 302 will be modified by TH. But if there is a direct 302 (without 100 reply), the contact in 302 is not changed by TH. Is this correct ??
