### ISSUE TITLE
mi_json timeout on answer to pua_publish

### ISSUE THREAD

**Issue by dsandras** [OpenSIPS/opensips#657]
Hi,

Issue #552 was recently fixed, but I fear not all problems are gone.

We are experiencing several cases where the json call over http times out with no answer being given after a few seconds.

The easiest way to reproduce it is to trigger a PUBLISH to publish some state, then to send a PUBLISH with expires=0. I can reproduce the problem 100% of the time doing so.

Looking at the attached opensips.log, you will see that the PUBLISH with expires=0 works, but that there is no answer from mi_json:
Sep 28 14:16:48 golgoth05 opensips[3980]: DBG:mi_json:mi_json_run_mi_cmd: got mi_rpl=[0xffffffffffffffff]
Sep 28 14:16:48 golgoth05 opensips[3980]: DBG:mi_json:mi_json_answer_to_connection: got an async reply

Then nothing more.

**Comment by dsandras** [comment]
Log is here:
http://www.ekiga.net/misc/callserver.txt

**Comment by dsandras** [comment]
Hi,

Here is a php code snippet that reproduces the problem very quickly:
http://www.ekiga.net/misc/dirty_test.php.txt

**Comment by dsandras** [comment]
After a while, opensips needs to be restarted, all mi_json operations are concluded by a timeout.

Result is:
root@golgoth05:~# php dirty_test.php 
0:
Published OK with etag a.1445258272.3016.1.0
1:
Failure (curl): Operation timed out after 2000 milliseconds with 0 bytes received
<presence xmlns="urn:ietf:params:xml:ns:pidf"
         xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model"
         xmlns:rpid="urn:ietf:params:xml:ns:pidf:rpid"
         entity="pres:754@ds.local.beip.be">
          <tuple id="754-web">
            <status><basic>closed</basic></status>
          </tuple>
        </presence>

**Comment by bogdan-iancu** [comment]
@dsandras, many thanks for the report and for the script - it was very handy to reproduce the problem.
The fix is now available on all OpenSIPS versions . Once again, many thanks for your support for OpenSIPS ;)
