### ISSUE TITLE
Add macro to get the file and line number in the script

### ISSUE THREAD

**Issue by ar45** [OpenSIPS/opensips#663]
It would be nice to have a way to get the file and line number within the opensips script `FILE` for the file when using `include_file` and `import_file`, and `LINE` for the line number. which can then be used in in xlog statements and in sip messages. This would make it easier to debug issues and script changes.

Also while thinking of this feature it comes to my mind that it also help to have a macro eg `SCRIPT_MD5` and `SCRIPT_SHA1` which would hold the hashed sum of the script, so we can compere revisions when logging multiple instances of opensips and you forgot to update one instance with  yor new config :)

**Comment by ionel-cerghit** [comment]
Hi,

Functionality added in pull request https://github.com/OpenSIPS/opensips/pull/700 
Does it satisfy your needs?

**Comment by ar45** [comment]
Thanks, that does the job.
