### ISSUE TITLE
Re-INVITE pinging

### ISSUE THREAD

**Issue by vladpaiu** [OpenSIPS/opensips#668]
Implement Re-INVITE pinging within dialog with OpenSIPS

**Comment by razvancrainea** [comment]
Hi, Vlad! If I am not mistaken, this is implemented in c0f25f796ce3f3ba3066a6d6553bef1ef3823904, right? If it is, please close the ticket.

Thanks!
Răzvan

**Comment by vladpaiu** [comment]
Hello,

Indeed, this was added with that commit and a couple of following ones. 
Closing,

Best Regards,
Vlad
