### ISSUE TITLE
SNMP Tables not populated

### ISSUE THREAD

**Issue by dsandras** [OpenSIPS/opensips#669]
We have working SNMP support in 2.1:
root@golgoth05:~/beip-bx# snmpwalk -v 2c -c beip localhost openserSIPEntityType.0
OPENSER-SIP-COMMON-MIB::openserSIPEntityType.0 = BITS: 38 proxyServer(2) redirectServer(3) registrarServer(4) 

However, tables remain desperately empty:
root@golgoth05:~/beip-bx# snmptable -Ci -v 2c -c beip localhost  openserSIPStatusCodesTable
OPENSER-SIP-COMMON-MIB::openserSIPStatusCodesTable: No entries

root@golgoth05:~/beip-bx# snmptable -Ci -v 2c -c beip localhost openserSIPContactTable  
SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPContactTable

 index openserSIPContactDisplayName openserSIPContactURI openserSIPContactLastUpdated openserSIPContactExpiry openserSIPContactPreference
   1.1                  DefaultUser          DefaultUser                0-0-0,0:0:0.0           0-0-0,0:0:0.0                       -0.01

root@golgoth05:~/beip-bx#  snmptable -Ci -v 2c -c beip localhost openserSIPRegUserTable
SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPRegUserTable

 index openserSIPUserUri openserSIPUserAuthenticationFailures
     1       DefaultUser                                    0

**Comment by dsandras** [comment]
This was tested against V2.1.1.

**Comment by dsandras** [comment]
The problem is the same with V1.8.5.

**Comment by ionutrazvanionita** [comment]
Hi @dsandras ,

I set up snmpd  and, having one user registered, I get the following output from
**opensipsctl**

```
[hxnnd] fork (master)$ ./scripts/opensipsctl fifo ul_dump
Domain:: location table=512 records=1
        AOR:: bob
                Contact:: sip:80132769@127.0.0.1:46620 Q=
                        Expires:: 546
                        Callid:: 2JKs14ny4GDLnMteS2BVzARtWsq9NBtz
                        Cseq:: 6
                        User-agent:: Blink 1.4.2 (Linux)
                        State:: CS_NEW
                        Flags:: 0
                        Cflags:: 
                        Socket:: udp:127.0.0.1:5060
                        Methods:: 4294967295
                        SIP_instance:: <urn:uuid:213b88c5-4ba2-4260-b768-120a9214bcb9>

```
**RegUserTable**
```
[hxnnd] fork (master)$ snmptable -v2c -Ci -c public localhost OPENSER-SIP-SERVER-MIB::openserSIPRegUserTable
SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPRegUserTable

 index openserSIPUserUri openserSIPUserAuthenticationFailures
     1       DefaultUser                                    0
     2               bob                                    0
```
**ContactLastUpdated**

```
[hxnnd] fork (master)$ snmptable -v2c -Ci -c public localhost OPENSER-SIP-SERVER-MIB::openserSIPContactTable
SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPContactTable

 index openserSIPContactDisplayName         openserSIPContactURI openserSIPContactLastUpdated openserSIPContactExpiry openserSIPContactPreference
   1.1                  DefaultUser                  DefaultUser                0-0-0,0:0:0.0           0-0-0,0:0:0.0                       -0.01
   2.1 sip:80132769@127.0.0.1:46620 sip:80132769@127.0.0.1:46620         2016-5-27,14:15:11.0    2016-5-27,14:25:11.0 
```

So everything is working ok there. As concerns  **openserSIPStatusCodesTable**, the implementation is different  and it looks like that table should be populated from outside OpenSIPS. If it helps you in any
way, you can access those statistics using the mi interface:

```
[hxnnd] fork (master)$ ./scripts/opensipsctl fifo get_statistics snmpstats:
snmpstats:100_in:: 0
snmpstats:100_out:: 0
snmpstats:180_in:: 0
snmpstats:180_out:: 0
snmpstats:181_in:: 0
snmpstats:181_out:: 0
snmpstats:182_in:: 0
snmpstats:182_out:: 0
snmpstats:183_in:: 0
snmpstats:183_out:: 0
snmpstats:200_in:: 0
snmpstats:200_out:: 4
snmpstats:202_in:: 0
snmpstats:202_out:: 0
snmpstats:300_in:: 0
snmpstats:300_out:: 0
snmpstats:301_in:: 0
snmpstats:301_out:: 0
snmpstats:302_in:: 0
snmpstats:302_out:: 0
snmpstats:305_in:: 0
snmpstats:305_out:: 0
snmpstats:380_in:: 0
snmpstats:380_out:: 0
snmpstats:400_in:: 0
snmpstats:400_out:: 0
snmpstats:401_in:: 0
snmpstats:401_out:: 0
snmpstats:402_in:: 0
snmpstats:402_out:: 0
snmpstats:403_in:: 0
snmpstats:403_out:: 0
snmpstats:404_in:: 0
snmpstats:404_out:: 0
snmpstats:405_in:: 0
snmpstats:405_out:: 0
snmpstats:406_in:: 0
snmpstats:406_out:: 0
snmpstats:407_in:: 0
snmpstats:407_out:: 0
snmpstats:408_in:: 0
snmpstats:408_out:: 0
snmpstats:410_in:: 0
snmpstats:410_out:: 0
snmpstats:413_in:: 0
snmpstats:413_out:: 0
snmpstats:414_in:: 0
snmpstats:414_out:: 0
snmpstats:415_in:: 0
snmpstats:415_out:: 0
snmpstats:416_in:: 0
snmpstats:416_out:: 0
snmpstats:420_in:: 0
snmpstats:420_out:: 0
snmpstats:421_in:: 0
snmpstats:421_out:: 0
snmpstats:423_in:: 0
snmpstats:423_out:: 0
snmpstats:480_in:: 0
snmpstats:480_out:: 0
snmpstats:481_in:: 0
snmpstats:481_out:: 0
snmpstats:482_in:: 0
snmpstats:482_out:: 0
snmpstats:483_in:: 0
snmpstats:483_out:: 0
snmpstats:484_in:: 0
snmpstats:484_out:: 0
snmpstats:485_in:: 0
snmpstats:485_out:: 0
snmpstats:486_in:: 0
snmpstats:486_out:: 0
snmpstats:487_in:: 0
snmpstats:487_out:: 0
snmpstats:488_in:: 0
snmpstats:488_out:: 0
snmpstats:491_in:: 0
snmpstats:491_out:: 0
snmpstats:492_in:: 0
snmpstats:492_out:: 0
snmpstats:494_in:: 0
snmpstats:494_out:: 0
snmpstats:500_in:: 0
snmpstats:500_out:: 0
snmpstats:501_in:: 0
snmpstats:501_out:: 0
snmpstats:502_in:: 0
snmpstats:502_out:: 0
snmpstats:503_in:: 0
snmpstats:503_out:: 73
snmpstats:504_in:: 0
snmpstats:504_out:: 0
snmpstats:505_in:: 0
snmpstats:505_out:: 0
snmpstats:513_in:: 0
snmpstats:513_out:: 0
snmpstats:600_in:: 0
snmpstats:600_out:: 0
snmpstats:603_in:: 0
snmpstats:603_out:: 0
snmpstats:604_in:: 0
snmpstats:604_out:: 0
snmpstats:606_in:: 0
snmpstats:606_out:: 0
```

**Comment by dsandras** [comment]
Hi,
I will only be able to test in a few days (at worse beginning of July).
If it is easy for you, can you try with db_mode=2 (no cache, DB only) ?
this is the only specificity we are using.
Thanks,
Le vendredi 27 mai 2016 à 04:33 -0700, Ionut Ionita a écrit :
> Hi @dsandras ,
> I set up snmpd and, having one user registered, I get the following
> output from
> opensipsctl
> [hxnnd] fork (master)$ ./scripts/opensipsctl fifo ul_dump
> Domain:: location table=512 records=1
>         AOR:: bob
>                 Contact:: sip:80132769@127.0.0.1:46620 Q=
>                         Expires:: 546
>                         Callid:: 2JKs14ny4GDLnMteS2BVzARtWsq9NBtz
>                         Cseq:: 6
>                         User-agent:: Blink 1.4.2 (Linux)
>                         State:: CS_NEW
>                         Flags:: 0
>                         Cflags:: 
>                         Socket:: udp:127.0.0.1:5060
>                         Methods:: 4294967295
>                         SIP_instance:: 
> b768-120a9214bcb9>
> 
> RegUserTable
> [hxnnd] fork (master)$ snmptable -v2c -Ci -c public localhost
> OPENSER-SIP-SERVER-MIB::openserSIPRegUserTable
> SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPRegUserTable
> 
>  index openserSIPUserUri openserSIPUserAuthenticationFailures
>      1       DefaultUser                                    0
>      2               bob                                    0
> ContactLastUpdated
> [hxnnd] fork (master)$ snmptable -v2c -Ci -c public localhost
> OPENSER-SIP-SERVER-MIB::openserSIPContactTable
> SNMP table: OPENSER-SIP-SERVER-MIB::openserSIPContactTable
> 
>  index openserSIPContactDisplayName         openserSIPContactURI
> openserSIPContactLastUpdated openserSIPContactExpiry
> openserSIPContactPreference
>    1.1                  DefaultUser                  DefaultUser     
>            0-0-0,0:0:0.0           0-0-
> 0,0:0:0.0                       -0.01
>    2.1 sip:80132769@127.0.0.1:46620 sip:80132769@127.0.0.1:46620     
>     2016-5-27,14:15:11.0    2016-5-27,14:25:11.0 
> So everything is working ok there. As concerns
> openserSIPStatusCodesTable, the implementation is different and it
> looks like that table should be populated from outside OpenSIPS. If
> it helps you in any
> way, you can access those statistics using the mi interface:
> [hxnnd] fork (master)$ ./scripts/opensipsctl fifo get_statistics
> snmpstats:
> snmpstats:100_in:: 0
> snmpstats:100_out:: 0
> snmpstats:180_in:: 0
> snmpstats:180_out:: 0
> snmpstats:181_in:: 0
> snmpstats:181_out:: 0
> snmpstats:182_in:: 0
> snmpstats:182_out:: 0
> snmpstats:183_in:: 0
> snmpstats:183_out:: 0
> snmpstats:200_in:: 0
> snmpstats:200_out:: 4
> snmpstats:202_in:: 0
> snmpstats:202_out:: 0
> snmpstats:300_in:: 0
> snmpstats:300_out:: 0
> snmpstats:301_in:: 0
> snmpstats:301_out:: 0
> snmpstats:302_in:: 0
> snmpstats:302_out:: 0
> snmpstats:305_in:: 0
> snmpstats:305_out:: 0
> snmpstats:380_in:: 0
> snmpstats:380_out:: 0
> snmpstats:400_in:: 0
> snmpstats:400_out:: 0
> snmpstats:401_in:: 0
> snmpstats:401_out:: 0
> snmpstats:402_in:: 0
> snmpstats:402_out:: 0
> snmpstats:403_in:: 0
> snmpstats:403_out:: 0
> snmpstats:404_in:: 0
> snmpstats:404_out:: 0
> snmpstats:405_in:: 0
> snmpstats:405_out:: 0
> snmpstats:406_in:: 0
> snmpstats:406_out:: 0
> snmpstats:407_in:: 0
> snmpstats:407_out:: 0
> snmpstats:408_in:: 0
> snmpstats:408_out:: 0
> snmpstats:410_in:: 0
> snmpstats:410_out:: 0
> snmpstats:413_in:: 0
> snmpstats:413_out:: 0
> snmpstats:414_in:: 0
> snmpstats:414_out:: 0
> snmpstats:415_in:: 0
> snmpstats:415_out:: 0
> snmpstats:416_in:: 0
> snmpstats:416_out:: 0
> snmpstats:420_in:: 0
> snmpstats:420_out:: 0
> snmpstats:421_in:: 0
> snmpstats:421_out:: 0
> snmpstats:423_in:: 0
> snmpstats:423_out:: 0
> snmpstats:480_in:: 0
> snmpstats:480_out:: 0
> snmpstats:481_in:: 0
> snmpstats:481_out:: 0
> snmpstats:482_in:: 0
> snmpstats:482_out:: 0
> snmpstats:483_in:: 0
> snmpstats:483_out:: 0
> snmpstats:484_in:: 0
> snmpstats:484_out:: 0
> snmpstats:485_in:: 0
> snmpstats:485_out:: 0
> snmpstats:486_in:: 0
> snmpstats:486_out:: 0
> snmpstats:487_in:: 0
> snmpstats:487_out:: 0
> snmpstats:488_in:: 0
> snmpstats:488_out:: 0
> snmpstats:491_in:: 0
> snmpstats:491_out:: 0
> snmpstats:492_in:: 0
> snmpstats:492_out:: 0
> snmpstats:494_in:: 0
> snmpstats:494_out:: 0
> snmpstats:500_in:: 0
> snmpstats:500_out:: 0
> snmpstats:501_in:: 0
> snmpstats:501_out:: 0
> snmpstats:502_in:: 0
> snmpstats:502_out:: 0
> snmpstats:503_in:: 0
> snmpstats:503_out:: 73
> snmpstats:504_in:: 0
> snmpstats:504_out:: 0
> snmpstats:505_in:: 0
> snmpstats:505_out:: 0
> snmpstats:513_in:: 0
> snmpstats:513_out:: 0
> snmpstats:600_in:: 0
> snmpstats:600_out:: 0
> snmpstats:603_in:: 0
> snmpstats:603_out:: 0
> snmpstats:604_in:: 0
> snmpstats:604_out:: 0
> snmpstats:606_in:: 0
> snmpstats:606_out:: 0
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Damien Sandras <dsandras@seconix.com>

**Comment by bogdan-iancu** [comment]
@dsandras , DB only is 3, not 2. Still, DB-only mode has some know limitations - like expire callbacks do not work. Because of that, the SNMP part also does not work, as SNMP relies on the usrloc callbacks (AOR created and destroyed ) in order to keep its parallel list with the registered AORs. So, if mode 3 -> no expire callbacks -> no list in SNMP.

**Comment by dsandras** [comment]
Hi Bogdan, I have limited network access currently, but we are indeed
using db_mode=3. Thus it explains it all...
I guess you can close this bug report in that case... Thanks for the
feedback !
Le lundi 30 mai 2016 à 03:13 -0700, Bogdan Andrei IANCU a écrit :
> @dsandras , DB only is 3, not 2. Still, DB-only mode has some know
> limitations - like expire callbacks do not work. Because of that, the
> SNMP part also does not work, as SNMP relies on the usrloc callbacks
> (AOR created and destroyed ) in order to keep its parallel list with
> the registered AORs. So, if mode 3 -> no expire callbacks -> no list
> in SNMP.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Damien Sandras <dsandras@seconix.com>
