### ISSUE TITLE
opensipsctl fifo ds_list show weight and priority and docs improvement

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#672]
Make the `fifo ds_list` command output more information.

Currently missing is information about *Priority* and *Weight*.

In general I think the documentation about these 2 values is lacking. How they work and what they do.
So my feature requests/suggestions are as follows:

- Add weight and priority output to `fifo ds_list`
- Describe how to use *Weight* in docs. I have now put 1 on every destination (for equal balance) what if i put 2 on others? what would happen. or does it need to have a total of 100 to work?
- Describe what priority is, and how to use it. is this ordering for how `fifo ds_list` outputs it's data? maybe usefull for proto 8(first entry in set)?

**Comment by hydrosine** [comment]
Also having the description in `fifo ds_list` would also be nice!

**Comment by ionel-cerghit** [comment]
Hi,

Feature implemented in https://github.com/OpenSIPS/opensips/pull/748 .
Does it satisfy you needs?

**Comment by hydrosine** [comment]
Looks good, all info there!
Replicated the issue i had in #387 And it's immediately visible!
