### ISSUE TITLE
opensipsctl statistics inconsistent formatting

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#673]
Hi,
I parse the output from `opensipsctl fifo get_statistics all`
How i do this is to split all values on the : character.
Every value looks as the following.

    pkmem:11-real_used_size:: 388768
    Module : ValueName : EMPTY: Value

And then there is this one! Which has one more : than all other values.

    load:udp:192.168.1.1:5060-load:: 0

Could you make this more consistent? I suggest picking an other delimiter than : so ip:port combinations don't add to this.

**Comment by razvancrainea** [comment]
The format is consistent:
`Module : StatName :: Value`

**Comment by hydrosine** [comment]
Hmm missed that this one is closed.

I do not agree that it is consistent. This is only true for the load statistics.
Load statistics are suddenly formatted as follows

Module : Proto : Ip : port-statname : : value

pkmem:24-fragments:: 8
load:udp:185.47.2.231:5060-load:: 0

**Comment by razvancrainea** [comment]
Actually the only inconsistencies would appear if the name of the statistic contains `::`. Luckily we don't have this in opensips, so you could use the following logic, parsing the row from left to right:
1. search for `:` - this token represents the `Module`
2. search for `::` - this represents the `StatName`
3. everything else is the `Value`

Indeed, we used `:` to delimiter those tokens, but if we would have used something else, we would probably have the same problems with other statistics. So I think this is acceptable.

Best regards,
Răzvan
