### ISSUE TITLE
ACK propagated with wrong CSeq number

### ISSUE THREAD

**Issue by pwakano** [OpenSIPS/opensips#680]
Problem: Transfer scenario causes Opensips to use the wrong CSeq number to propagate an ACK.
Scenario: Call is established, in-dialog pings are sent, user does a blind transfer which causes the transmission of a Re-Invite immediately followed by an Update. These requests are answered but the ACK for the Re-Invite gets propagated with the CSeq number of the Update and not with the CSeq of the correponding Re-Invite.

Reference: http://lists.opensips.org/pipermail/users/2015-October/032859.html

**Comment by vladpaiu** [comment]
Hello,

Please try applying the attached patch against your 1.11 sources and let me know how that goes.

[dialog_ACK_cseq.txt](https://github.com/OpenSIPS/opensips/files/18317/dialog_ACK_cseq.txt)

Best Regards,
Vlad

**Comment by pwakano** [comment]
Hi Vlad!

Just tested your patch and it works! The Ack is not forwarded with the wrong CSeq anymore!
Thank you very much for the excellent support!!

Patrick

**Comment by vladpaiu** [comment]
Hello,

Committed the fix for this on 1.11, 2.1 and master. If you want, remove the patch and update your sources to the latest 1.11 .

Closing.

Best Regards,
Vlad
