### ISSUE TITLE
B2BUA topology hiding not processing replies

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#686]
We are seeing instances where the B2BUA is not processing replies for a call even though it will continue to retransmit the initial INVITE.

When this happens we do see an error such as 'ERROR:b2b_entities:b2b_tm_cback: No dialog found reply 503 for method INVITE' appear in the log, but opensips continues to retransmit the INVITE and will not send an ACK.

Eventually the B2BUA will send a 408 to the client for the call.

I can provide a capture privately.

Opensips Version:
version: opensips 1.11.5-notls (x86_64/linux)
flags: STATS: On, USE_IPV6, USE_TCP, DISABLE_NAGLE, USE_MCAST, SHM_MEM, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: fc1a2eb
main.c compiled on 13:37:03 May 15 2015 with gcc 4.9.1

**Comment by bogdan-iancu** [comment]
@rrb3942 , do you have any parallel forking involved in the scenario ?

**Comment by rrb3942** [comment]
Closing because this is old and stale. We no longer use the B2B module, and I don't know if this is still an issue.
