### ISSUE TITLE
Arch Linux: 'osipsconfig' Failure

### ISSUE THREAD

**Issue by Alexander-Shukaev** [OpenSIPS/opensips#687]
Hello,

```
Config generated : /usr/etc/opensips/opensips_residential_2015-10-29_0
:2:3.cfg =  FAILED. Press any key to continue
```

I've seen similar problems reported previously.  It seems like there was a (build-time) fix for this, so that `osipsconfig` will attempt to generate configurations into the appropriate directory.  For instance, on Arch Linux, that should be `/etc/opensips` as `/usr/etc` does not even exist.  Is there any problem with the corresponding [`PKGBUILD`](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensips)?  Should something be added there to resolve the above issue?

**Comment by razvancrainea** [comment]
The `PREFIX` variable in the [`PKGBUILD`](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensips) seems to be `/usr`, therefore the generated config file will be generated relative to that path.

If you take a closer look, on line [68](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensips#n68), the packager moves the configuration file to the `/etc/` directory. Perhaps we should find a different way to set the configs.

**Comment by razvancrainea** [comment]
This should be resolved now. If so, please close this issue.
