### ISSUE TITLE
Possible bug in 2.1 implementation of force_send_socket

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#690]
I am trying to relay a SUBSCRIBE message onwards to another proxy using the force_send_socket() function to force the use of TLS.

The relay is working as expected, however OpenSIPS is not populating the Record-Route headers correctly on relay. Instead of using the TLS port it is putting the TCP listen port into the Record-Route:

e.g.

OpenSIPS is configured thusly:

~~~~~
listen=udp:1.2.3.4:5060
listen=tcp:1.2.3.4:5060
listen=ws:1.2.3.4:10080
listen=tls:1.2.3.4:5061
~~~~~

I am using force_send_socket to ensure the relay uses tls:

~~~~~
force_send_socket(tls:1.2.3.4:5061);
~~~~~

OpenSIPS sends out the request from port 5061(and via TLS) as expected

~~~~~
T 2015/11/04 12:14:30.294673 1.2.3.4:5061 -> 5.6.7.8:41904
~~~~~

However the Record-Route that OpenSIPS adds is seemingly using the incorrect port, and indeed I see inbound TLS requests to port 5060 afterwards

~~~~~
Record-Route: <sip:1.2.3.4:5060;transport=tls;r2=on;lr;ftag=79mm8laopq>.
~~~~~

Is this a misunderstanding on my part about how to use force_send_socket, or a potential bug?

**Comment by petekelly** [comment]
Not sure if this is related, but if OpenSIPS receives an INVITE as a TLS UAS then the bug also occurs in the Contact generated by OpenSIPS:
~~~~~
Contact: <sip:1.2.3.4:5060;transport=tls;did=872.61496c02> #should be 5061
~~~~~

**Comment by razvancrainea** [comment]
Hi, Pete!

Unfortunately I have to give you the usual first answer: I am unable to replicate this.
Any chance you could privately send me the debug logs for these calls?

Best regards,
Răzvan

**Comment by petekelly** [comment]
Hi Razvan, I have emailed the logs. Hope they make sense :)

Pete

**Comment by razvancrainea** [comment]
This was a script issue. Closing it.
