### ISSUE TITLE
Add ability to provide db_id to avp_db_query() as either $var or $avp

### ISSUE THREAD

**Issue by mishehu** [OpenSIPS/opensips#694]
Spoke with Vlad-Paiu about this.  Currently avp_db_query() requires that the db_id (3rd param) be a constant.  By allowing for avp_db_query() to use a $var and $avp, it would allow simplified iteration across an arbitrary number of avpops db urls as defined by the user, and keep from unnecessarily duplicating code.

If it wouldn't be too much trouble, could this functionality please be added?  Much thanks in advance.

**Comment by ionutrazvanionita** [comment]
@mishehu would you need both string and int values for the db id in a variable?
I mean it's enough to have something like

```
$var(id)=1;
avp_db_query(...., "$var(id)");
```

or you would also need something like

```
$var(id) = "1";
avp_db_query(...., "$var(id)");
```

**Comment by mishehu** [comment]
@ionutrazvanionita - As far as how I'm going to use it, I will be using only an integer value.  But to be honest, maybe other people will find it useful to accept a string as well?  I'm not sure.  Integer is fine for me, but I'll defer to your better judgment.  :-)

**Comment by ionutrazvanionita** [comment]
That's why i asked, because i didn't know how you will use it. Anyhow, i made it work both use. Please check if everything is ok https://github.com/OpenSIPS/opensips/commit/8a512731df99621025744aaa25b17931759b91d4

**Comment by EcosystemDev** [comment]
This works great

**Comment by mishehu** [comment]
Yep, it's working great for us, thanks for making the change!

**Comment by mishehu** [comment]
@ionutrazvanionita :  There seems to be a problem at the current time.  We're using this patch on the 2.1 branch, and it doesn't look like it was backported to 2.1.  Can you please verify?  The patch you previously provided works for 4 out of 5 hunks.  There is an avpops.c.rej that I'm attaching.  This wa done against commit 0a642c5e8ba315453c064c174f7ae86b8ecdb1a2 .  Thanks!
[avpops.c.rej.txt](https://github.com/OpenSIPS/opensips/files/94835/avpops.c.rej.txt)

**Comment by ionutrazvanionita** [comment]
@mishehu done https://github.com/OpenSIPS/opensips/commit/d0f5c3d48d26aa9f9b50ac15905a959b6058a913

**Comment by mishehu** [comment]
Sorry, missed closing this out for you.  :-)
