### ISSUE TITLE
OpenSIPS - crash if sip session timer is enabled

### ISSUE THREAD

**Issue by sjap** [OpenSIPS/opensips#695]
Hello,

I see something strange with my opensips setup. If i enable sip session timer the and after a few min and 2-3 re-invites opensips crashes. And actually core dumps. I can repeat that just starting opensips again and make a call and wait.

Nov 10 10:12:34 opensips-1a /sbin/opensips[4421]: INFO:core:handle_sigs: child process 4429 exited by a signal 11
Nov 10 10:12:34 opensips-1a /sbin/opensips[4421]: INFO:core:handle_sigs: core was generated
Nov 10 10:12:34 opensips-1a /sbin/opensips[4421]: INFO:core:handle_sigs: terminating due to SIGCHLD

[Nov10 10:12] opensips[4429]: segfault at 0 ip 00000000004b30c3 sp 00007ffe0c1fcd10 error 6 in opensips[400000+189000]
[  +0.291733] opensips[4421]: segfault at 8 ip 00007fcf5ab66a87 sp 00007ffe0c1ff220 error 4 in dialog.so[7fcf5ab46000+56000]

I'm running:

version: opensips 2.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 00:00:26 Aug 29 2015 with gcc 4.8.3

**Comment by razvancrainea** [comment]
Can you post a stack trace for the core generated?

Thanks,
Răzvan

**Comment by sjap** [comment]
[root@opensips-1a /]# gdb opensips core.4421
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/sbin/opensips...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 4421]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/sbin/opensips -P /var/run/opensips.pid'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fcf5ab66a87 in unref_dlg () from /usr/lib64/opensips/modules/dialog.so
Missing separate debuginfos, use: debuginfo-install opensips-2.1.1-1.el7.x86_64
(gdb) bt full
#0  0x00007fcf5ab66a87 in unref_dlg () from /usr/lib64/opensips/modules/dialog.so
No symbol table info available.
#1  0x00007fcf5fcfd863 in empty_tmcb_list () from /usr/lib64/opensips/modules/tm.so
No symbol table info available.
#2  0x00007fcf5fcdf44e in free_cell () from /usr/lib64/opensips/modules/tm.so
No symbol table info available.
#3  0x00007fcf5fce179b in free_hash_table () from /usr/lib64/opensips/modules/tm.so
No symbol table info available.
#4  0x00007fcf5fcd43d5 in tm_shutdown () from /usr/lib64/opensips/modules/tm.so
No symbol table info available.
#5  0x000000000049315c in destroy_modules ()
No symbol table info available.
#6  0x000000000048f171 in cleanup ()
No symbol table info available.
#7  0x000000000048fc42 in handle_sigs ()
No symbol table info available.
#8  0x0000000000419455 in main ()
No symbol table info available.

Is this useful for you?

**Comment by razvancrainea** [comment]
Please update to the latests 2.1 sources and try again.

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Is this still happening after an update?

Thanks,
Răzvan

**Comment by sjap** [comment]
Sorry, I forgot to close the ticket. - I haven't seen the crash after the
upgrade.

On Thu, May 26, 2016 at 10:56 AM, Răzvan Crainea <notifications@github.com>
wrote:

> Is this still happening after an update?
>
> Thanks,
> Răzvan
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSIPS/opensips/issues/695#issuecomment-221815250>
>



-- 
/Søren
