### ISSUE TITLE
Wrong rule selected in dialplan translation when both string and regexp rules are matched

### ISSUE THREAD

**Issue by paolodepa** [OpenSIPS/opensips#696]
Let's say we are translating a destination matching two dialplan rules, the first working on exact string match and the second working on regexp match: I'm getting selected the exact match rule ONLY IF its priority is bigger (>) than the regexp rule; the regexp rule is selected otherwise.
I would have expected the opposite behaviour.

I'm facing this issue on 1.11.5 version but, looking at  the source code, the problem should be present also in 2.1.X.
In detail, I suppose that replacing this code snippet into the function "translate" (dp_repl.c):

        /* pick the rule with lowest table index if both match and prio are equal */
        if ((string_res | regexp_res) == 0) {
                if (rulep->pr < rrulep->pr) {
                        rulep = rrulep;

with:

        /* pick the rule with lowest table index if both match and prio are equal */
        if ((string_res | regexp_res) == 0) {
                if (rrulep->pr < rulep->pr) {
                        rulep = rrulep;

would make the job.

**Comment by bogdan-iancu** [comment]
@paolodepa, if there is no clear ordering based on priorities, there is no "expected" behavior . To avoid any overlapping or incertitude, use priorities

**Comment by paolodepa** [comment]
@bogdan-iancu that's exactly the reason why I submited this issue: the "expected" behaviour should be to select the lowest priority rule, regardless of the type of matching (regexp vs exact), isn't it?

Instead "I'm getting selected the exact match rule ONLY IF its priority is bigger (>) than the regexp rule".

BTW, working side by side with @Parantido, I know that his reworking in 2.1.2 and subsequent versions fixes this issue.

**Comment by bogdan-iancu** [comment]
@paolodepa, that;s my point - there is not expected behavior in such case. And we strongly advice to solve such conflicts with priorities and not with "expected" behavior.
I do not remember to have in docs any statements of a such expected behavior - if I'm missing something here, please correct me.
Yes, I'm aware of the patches from @Parantido and we have scheduled them to be reviewed for 2.3 release.

**Comment by paolodepa** [comment]
Neither I could find any specification in the docs on the priority field in dialplan module, unless of arbitrarily supposing it to be similar to the same field in cc_flows table, which is ascending (lower value means higher priority).

You are telling me instead that the priority order has to be considered descending into the dialplan module (at least in this piece of code), right?

**Comment by liviuchircu** [comment]
Thank you for reporting this inconsistency and suggesting a fix, @paolodepa - this issue has been fixed on all OpenSIPS versions above and including `1.11`.
