### ISSUE TITLE
proto_tls problem

### ISSUE THREAD

**Issue by cepehutu** [OpenSIPS/opensips#702]
Have a problem with proto_tls on 2.1(tried 2.2dev - same problem) on AWS

Need help

Nov 24 16:40:51 front-1 opensips_log[26563]: INFO:core:probe_max_sock_buff: using snd buffer of 509 kb
Nov 24 16:40:51 front-1 opensips_log[26563]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 26
Nov 24 16:40:51 front-1 opensips_log[26563]: ERROR:core:tcp_connect_blocking: timeout 99199 ms elapsed from 100000 s
Nov 24 16:40:51 front-1 opensips_log[26563]: ERROR:proto_tls:tls_sync_connect: tcp_blocking_connect failed
Nov 24 16:40:51 front-1 opensips_log[26563]: ERROR:proto_tls:proto_tls_send: connect failed
Nov 24 16:40:51 front-1 opensips_log[26563]: ERROR:tm:msg_send: send() for proto 3 failed
Nov 24 16:40:51 front-1 opensips_log[26563]: ERROR:tm:t_forward_nonack: sending request failed

**Comment by bogdan-iancu** [comment]
@cepehutu , the log says your OpenSIPS tries to connect to destination, but it fails as the destination does not accept the connection.
