### ISSUE TITLE
alaw -> g723 transcoding issue on opensips 1.10beta

### ISSUE THREAD

**Issue by MikeXY** [OpenSIPS/opensips#71]
I`ve tried to make some tests with sangoma D500 and opensips. I used as softphone sipLite.
All the tests were fine with gsm, alaw, ulaw,g729 but with g723 failed to create  Transcoding Session.
Used codecs for this test : alaw - > g723

Here is a strace : http://pastebin.com/STEvBt3d
Here is a debug log from opensips : http://pastebin.com/uKqDsWK4

Thank you.

**Comment by liviuchircu** [comment]
Closing for now, as we really do not have access to a D-series card anymore, so it's difficult to make progress on this matter.
