### ISSUE TITLE
validate_dialog() does not work with TH

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#710]
It fails with cseq checking as the matched leg is probably invalid/not set

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/pull/733 . Since the fix in str2int(return -1 if given string is an empty string "")  and the prev_cseq was an empty string most of the times, the cseq check was failing. Added a new check on r_cseq if prev_cseq is not set.

**Comment by bogdan-iancu** [comment]
fixed by #733
