### ISSUE TITLE
crashing while copying new GeoLiteCity.dat file

### ISSUE THREAD

**Issue by achalkov** [OpenSIPS/opensips#720]
version: opensips 2.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 21b2728
main.c compiled on 02:46:31 Nov 24 2015 with gcc 4.4.7
With mmgeoip enabled and checking mmg_lookup() for every REGISTER and INVITE request.

I have something around 1000 REGISTERs and 250 INVITEs per second, when i copying new GeoLiteCity.dat file instead of old geoip DB file, opensips just crashes. 
After that - it starts successfully with new file.

**Comment by bogdan-iancu** [comment]
When opensips crashed, did you get some error messages ? do you have a a core file ?

**Comment by achalkov** [comment]
I did not have any unusual error message (only errors like "child process xxxxx exit by signal 7"), and unfortunately this time i updated geoip, corefile was lost. Its really hard to reproduce this error because not hard loaded opensips dont crashes. Unfortunately i cant allow my main hard loaded opensips to crash, so when i'll update my geoip DB next time, i'll try to save corefile for you.

**Comment by ionutrazvanionita** [comment]
Hi @achalkov, added https://github.com/OpenSIPS/opensips/commit/66def87b49e34c260bbf736a814e8f3399489c15 (https://github.com/OpenSIPS/opensips/commit/0735d51dec6f224c38c8970011d31ca4757253e8 for 2.1 branch). Now you have cache type parameter. Choose between STANDARD(read from file, slower) and MEM_CACHE_CHECK(faster, store file in memory) and you won't get segfault anymore
