### ISSUE TITLE
Dispatcher configuration error for Presence Server

### ISSUE THREAD

**Issue by suryaveerc** [OpenSIPS/opensips#740]
Hi, 

I have installed the presence server (1.8.3) in a docker container on a VM and that's working fine. Now, on same VM I have installed the dispatcher in a second container. 

Both containers are able to PING each other but dispatcher is not sending the requests to the listed presence server.

I am using a dbtext module to store the destination sets. Below is the dispatcher table 

id(int,auto) setid(int) destination(str) socket(str) flags(int) weight(int) attrs(str) description(str) 
1:0:sip\:sa@172.17.0.5\:15060:NULL:0:1:"":"" 

**and some parts of the dispatcher cfg:**
listen=udp:172.17.0.6:5060 
loadmodule "dispatcher.so" 
modparam("dispatcher", "db_url", 
        "text:///usr/local/opensips/etc/dispatcher") # CUSTOMIZE ME 
route{ 
        if (!mf_process_maxfwd_header("10")) { 
                sl_send_reply("483","Too Many Hops"); 
                exit; 
        } 
      if ( !ds_select_dst("1","4") ) { 
         send_reply("500","No Destination available"); 
         exit; 
        } 
        t_on_failure("GW_FAILOVER"); 
        route(RELAY); 
} 

**The server_name portion from the presence server cfg:**
modparam("presence", "server_address", "sip:sa@172.17.0.5:15060")

**Server startup log:**

Dec 30 06:15:39 [23185] DBG:db_text:dbt_result_new: new res with 6 cols 
Dec 30 06:15:39 [23185] DBG:core:db_new_result: allocate 48 bytes for result set at 0x7f7a0364e8b0 
Dec 30 06:15:39 [23185] DBG:core:db_allocate_columns: allocate 168 bytes for result columns at 0x7f7a0364e8f8 
Dec 30 06:15:39 [23185] DBG:core:db_allocate_rows: allocate 208 bytes for result rows and values at 0x7f7a0364e9b8 
Dec 30 06:15:39 [23185] DBG:core:grep_sock_info: checking if host==us: 4==10 &&  [NULL] == [172.17.0.6] 
Dec 30 06:15:39 [23185] DBG:core:grep_sock_info: checking if host==us: 4==10 &&  [NULL] == [172.17.0.6] 
Dec 30 06:15:39 [23185] ERROR:dispatcher:ds_load_db: socket <NULL> is not local to opensips (we must listen on it) -> ignoring it
Dec 30 06:15:39 [23185] DBG:core:mk_proxy: doing DNS lookup... 
Dec 30 06:15:39 [23185] DBG:dispatcher:add_dest2list: first gw ip addr [172.17.0.5]:15060 
Dec 30 06:15:39 [23185] DBG:dispatcher:add_dest2list: dest [0/1] <sip:sa@172.17.0.5:15060>
Dec 30 06:15:39 [23185] DBG:dispatcher:reindex_dests: found [1] dest sets 
Dec 30 06:15:39 [23185] DBG:core:db_free_columns: freeing result columns at 0x7f7a0364e8f8 
Dec 30 06:15:39 [23185] DBG:core:db_free_rows: freeing 1 rows 
Dec 30 06:15:39 [23185] DBG:core:db_free_row: freeing row values at 0x7f7a0364e9c8 
Dec 30 06:15:39 [23185] DBG:core:db_free_row: EXITDec 30 06:15:39 [23185] DBG:core:db_free_rows: freeing rows at 0x7f7a0364e9b8 .

**The log when I send a SIPP request:** 

Dec 30 06:18:45 [23189] DBG:core:parse_msg: SIP Request: 
Dec 30 06:18:45 [23189] DBG:core:parse_msg:  method:  <PUBLISH>
Dec 30 06:18:45 [23189] DBG:core:parse_msg:  uri:     <sip:service-1@172.17.0.6>
Dec 30 06:18:45 [23189] DBG:core:parse_msg:  version: <SIP/2.0>
Dec 30 06:18:45 [23189] DBG:core:parse_headers: flags=2 
Dec 30 06:18:45 [23189] DBG:core:parse_via_param: found param type 232, <branch> = <z9hG4bK-39688-1-0>; state=16 
Dec 30 06:18:45 [23189] DBG:core:parse_via: end of header reached, state=5 
Dec 30 06:18:45 [23189] DBG:core:parse_headers: via found, flags=2 
Dec 30 06:18:45 [23189] DBG:core:parse_headers: this is the first via 
Dec 30 06:18:45 [23189] DBG:core:receive_msg: After parse_msg... 
Dec 30 06:18:45 [23189] DBG:core:receive_msg: preparing to run routing scripts... 
Dec 30 06:18:45 [23189] DBG:core:parse_headers: flags=100 
Dec 30 06:18:45 [23189] DBG:maxfwd:is_maxfwd_present: value = 20 
Dec 30 06:18:45 [23189] ERROR:dispatcher:ds_get_index: destination set [1] not found 
Dec 30 06:18:45 [23189] ERROR:dispatcher:ds_select_dst: destination set [1] not found 
Dec 30 06:18:45 [23189] DBG:core:parse_headers: flags=8 
Dec 30 06:18:45 [23189] DBG:core:parse_to: end of header reached, state=10 
Dec 30 06:18:45 [23189] DBG:core:parse_to: display={sut}, ruri={sip:service-1@172.17.0.6} 
Dec 30 06:18:45 [23189] DBG:core:get_hdr_field: <To> [32]; uri=[sip:service-1@172.17.0.6] 
Dec 30 06:18:45 [23189] DBG:core:get_hdr_field: to body [sut <sip:service-1@172.17.0.6>
] 
Dec 30 06:18:45 [23189] DBG:core:parse_headers: flags=ffffffffffffffff 
Dec 30 06:18:45 [23189] DBG:core:get_hdr_field: cseq <CSeq>: <1> <PUBLISH>
Dec 30 06:18:45 [23189] DBG:core:get_hdr_field: content_length=607 
Dec 30 06:18:45 [23189] DBG:core:get_hdr_field: found end of header 
Dec 30 06:18:45 [23189] DBG:core:check_ip_address: params 172.17.0.1, 127.0.1.1, 0 
Dec 30 06:18:45 [23189] DBG:core:destroy_avp_list: destroying list (nil) 
Dec 30 06:18:45 [23189] DBG:core:receive_msg: cleaning up 
Dec 30 06:18:45 [23190] DBG:core:parse_msg: SIP Request: 
Dec 30 06:18:45 [23190] DBG:core:parse_msg:  method:  <BYE>
Dec 30 06:18:45 [23190] DBG:core:parse_msg:  uri:     <sip:service-1@172.17.0.6>
Dec 30 06:18:45 [23190] DBG:core:parse_msg:  version: <SIP/2.0>
Dec 30 06:18:45 [23190] DBG:core:parse_headers: flags=2 
Dec 30 06:18:45 [23190] DBG:core:parse_via_param: found param type 232, <branch> = <z9hG4bK-39688-1--1>; state=16 
Dec 30 06:18:45 [23190] DBG:core:parse_via: end of header reached, state=5 
Dec 30 06:18:45 [23190] DBG:core:parse_headers: via found, flags=2 
Dec 30 06:18:45 [23190] DBG:core:parse_headers: this is the first via 
Dec 30 06:18:45 [23190] DBG:core:receive_msg: After parse_msg... 
Dec 30 06:18:45 [23190] DBG:core:receive_msg: preparing to run routing scripts... 
Dec 30 06:18:45 [23190] DBG:core:parse_headers: flags=100 
Dec 30 06:18:45 [23190] DBG:core:parse_to_param: tag=246a5d4fbef8342456a1a597e7170548.feec 
Dec 30 06:18:45 [23190] DBG:core:parse_to: end of header reached, state=29 
Dec 30 06:18:45 [23190] DBG:core:parse_to: display={sut}, ruri={sip:service-1@172.17.0.6} 
Dec 30 06:18:45 [23190] DBG:core:get_hdr_field: <To> [74]; uri=[sip:service-1@172.17.0.6] 
Dec 30 06:18:45 [23190] DBG:core:get_hdr_field: to body [sut <sip:service-1@172.17.0.6>] 
Dec 30 06:18:45 [23190] DBG:core:get_hdr_field: cseq <CSeq>: <2> <BYE>
Dec 30 06:18:45 [23190] DBG:maxfwd:is_maxfwd_present: value = 70 
Dec 30 06:18:45 [23190] ERROR:dispatcher:ds_get_index: destination set [1] not found 
Dec 30 06:18:45 [23190] ERROR:dispatcher:ds_select_dst: destination set [1] not found 
Dec 30 06:18:45 [23190] DBG:core:parse_headers: flags=ffffffffffffffff 
Dec 30 06:18:45 [23190] DBG:core:get_hdr_field: content_length=0 
Dec 30 06:18:45 [23190] DBG:core:get_hdr_field: found end of header 
Dec 30 06:18:45 [23190] DBG:core:check_ip_address: params 172.17.0.1, 127.0.1.1, 0 
Dec 30 06:18:45 [23190] DBG:core:destroy_avp_list: destroying list (nil) 
Dec 30 06:18:45 [23190] DBG:core:receive_msg: cleaning up 

**scenario file**
<?xml version="1.0" encoding="ISO-8859-1" ?> 
<scenario name="publish">
  <send start_rtd="1">
    <![CDATA[ 
      PUBLISH sip:[service]-[call_number]@172.17.0.6 SIP/2.0 
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch] 
      Max-Forwards: 20 
      From: [service] <sip:[service]-[call_number]@172.17.0.6>;tag=[call_number] 
      To: sut <sip:[service]-[call_number]@172.17.0.6> 
      Call-ID: [call_id] 
      CSeq: 1 PUBLISH 
      Expires: 3600 
      Event: presence 
      Content-Length: [len] 
      User-Agent: Sipp v1.1-TLS, version 20061124 
<truncated xml> 
  </send> 
  <recv response="200" rtd="1" crlf="true"> 
  </recv> 
<ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/> 
</scenario> 

**SIPP command**

./sipp 172.17.0.6 -sf publish.xml -m 1 

Thanks, 
Surya

**Comment by bogdan-iancu** [comment]
Also answered on mailing list, the set id id DB does not match the set id in ds_select in cfg -> configuration error.
