### ISSUE TITLE
repeated proto_wss error messages in logs

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#741]
on master commit 968a4e004ebf85687f864b885a1ad5dc6632f41a

I've enabled proto_wss and have a client registered.  I see the following proto_wss errors in the logs on a repeating basis - this is at debug 4.

https://gist.github.com/etamme/ef1a049ffd50fd67ea6e#file-proto_wss-errors-L25

The log messages appear about every 4 minutes, so I suspect some kind of connection timeout is triggering.

No immediate issue is apparent, just the error in the logs.

**Comment by etamme** [comment]
I am happy to call this closed if you guys are.

**Comment by razvancrainea** [comment]
Apologies, I missed this. It looks like the client tries to close the connection after it times out, but the write fails. More or less this looks like a legit behavior. You can close the ticket if there are no other issues with it.
