### ISSUE TITLE
Memory leak/out of memory when using proto_wss

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#743]
Running master commit 968a4e004ebf85687f864b885a1ad5dc6632f41a

I have 2 UDP clients registered, 1 WSS client registered.  Over time ~2 hours opensips fails to accept WSS handshakes and the logs show that it has run out of memory.

```
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:core:handle_io: We have received conn 0x7f88de89b080 with rw 1 on fd 31
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:core:io_watch_add: [TCP_worker] io_watch_add op (31 on 6) (0x879880, 31, 19, 0x7f88de89b080,1), fd_no=2/2086
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:proto_wss:tls_update_fd: New fd is 31
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:proto_wss:ws_server_handshake: Using the global ( per process ) buff
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:proto_wss:tls_update_fd: New fd is 31
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: WARNING:core:fm_malloc: Not enough free memory (189384), will attempt defragmentation
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: ERROR:core:fm_malloc: Defragmentation unsuccessful
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: ERROR:proto_wss:ws_server_handshake: No more mem for dynamic con request buffer
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: ERROR:proto_wss:wss_read_req: cannot complete WebSocket handshake
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:core:io_watch_del: [TCP_worker] io_watch_del op on index 0 31 (0x879880, 31, 0, 0x10,0x3) fd_no=3 called
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:core:tcpconn_release:  releasing con 0x7f88de89b080, state -2, fd=-1, id=30
Jan  5 12:42:26 voipphreaker /usr/local/opensips/sbin/opensips[9887]: DBG:core:tcpconn_release:  extra_data 0x7f88de899458
```

**Comment by razvancrainea** [comment]
Hi Eric!

I guess the number from `Not enough free memory (189384)` is something you added for debugging, right? Is it the memory it is trying to allocate?
Also, have you tried running with memory debugging?

Thanks,
Răzvan

**Comment by etamme** [comment]
Hey Raz,

I did not add any log output for debugging - this is vanilla master runing at debug 4.

I have not tried running with memory debugging - i will compile with that turned on.

**Comment by etamme** [comment]
Hey again Raz,

I recompiled with -DDBG_QM_MALLOC and set memlog=1 in my script config.  I started seeing the out of memory errors again today: https://gist.github.com/etamme/38feb119e60fe8c85606

I then restarted the proxy, but unfortunately I did not get any memory dump in the logs on restart - not sure why.

**Comment by etamme** [comment]
Hey Raz,

I cought opensips when it ran out of memory again and sent SIGUSR1 to all the PID's to get them to dump memory.

Here is the log before the memory dump, showing the out of memory

```
Jan  8 13:52:57 voipphreaker /usr/local/opensips/sbin/opensips[12073]: INFO:core:probe_max_sock_buff: using snd buffer of 509 kb
Jan  8 13:52:57 voipphreaker /usr/local/opensips/sbin/opensips[12073]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 41
Jan  8 13:52:59 voipphreaker /usr/local/opensips/sbin/opensips[12065]: WARNING:core:fm_malloc: Not enough free memory (106904), will attempt defragmentation
Jan  8 13:52:59 voipphreaker /usr/local/opensips/sbin/opensips[12065]: ERROR:core:fm_malloc: Defragmentation unsuccessful
Jan  8 13:52:59 voipphreaker /usr/local/opensips/sbin/opensips[12065]: ERROR:proto_wss:ws_server_handshake: No more mem for dynamic con request buffer
Jan  8 13:52:59 voipphreaker /usr/local/opensips/sbin/opensips[12065]: ERROR:proto_wss:wss_read_req: cannot complete WebSocket handshake
```

and here is the memory dump 

https://gist.github.com/etamme/050e335725a19c0d9e60

**Comment by etamme** [comment]
A little more info - the proxy seems to be handling other protocol (UDP) messages without issue.  The specific PID is the only one that appears to be having some issues.  All UDP traffic is working without issue.

**Comment by liviuchircu** [comment]
`-DDBG_QM_MALLOC` was restructured (see https://github.com/OpenSIPS/opensips/pull/736), so it does not have any impact anymore on master.

In short, each of the 3 current stable allocators now has its debugging version, available through `-DDBG_MALLOC`. Readability of the entire fragment dump was improved as well.

**Comment by etamme** [comment]
I recompiled with -DBG_MALLOC as suggested by liviu.

I started the proxy, opened a few tabs to register webrtc clients over wss, closed the tabs and repeated the process till the proxy ran out of memory.  I then sent sigusr1 signals to all the pids and got the following log output.

https://gist.github.com/etamme/d1d96c08ea68f9873e40

**Comment by razvancrainea** [comment]
Hi, Eric!

I see a lot of memory used by the structures that store the connections. Could you try to list all connections just before running out of memory and let me know how many active connections you have? You can use `opensipsctl fifo list_tcp_conns`.

 Also, how many children are you using?

Thanks,
Răzvan

**Comment by etamme** [comment]
I am only using 2 children.  

I will try to get it to run out of memory again and see how many active connections there are.

**Comment by etamme** [comment]
Hey Raz,

I repeated my previous test: open few tabs, close them, repeat. but I dumped the statistics, and did a list_tcp_conns between each test.  All the tcp conns seem to tear down properly, but pkg memory use does grow over time.  As you can see by the connection number in my gist, I had to open 144 connections to get it to fail this time, but i could see the pkg mem increasing across several processes each time i did a fifo getstatists.

Here is the gist: https://gist.github.com/etamme/f2a1c3da0706e1d4ee8c

I had a single tab open with a single wss registration, I dumped the stats and did a list_tcp_cons, then I opened a new tab which failed to handshake because the pid ran out of memory.

**Comment by razvancrainea** [comment]
Hey Eric! Just committed a possible fix for this. Can you please give it a try and let me know if that's ok.
Thanks!

**Comment by etamme** [comment]
Awesome Raz!  I'll do a pull/rebuild and let you know.

**Comment by etamme** [comment]
This definitely seems to help, after 145 connections, all pids are using ~500000 bytes where as they were over 1500000 before - also sending sigusr1 to get memory status shows no ws handshake memory usage https://gist.github.com/etamme/7470c3e677bd2d947089

**Comment by razvancrainea** [comment]
Could you confirm everything is ok, so we can close this ticket? Thanks!

**Comment by etamme** [comment]
yes - memory is completely stable after several days of usage, i will close the issue.
