### ISSUE TITLE
cachedb_mongodb module crashes when doing a query if mongodb instance is down

### ISSUE THREAD

**Issue by abhowmik123** [OpenSIPS/opensips#747]
found a bug as described above , done some debugging and found that bson->data holds a NULL value when initializing the bson-iterator, which causes the crash. Anyways fixed the crash by aplying a simple check.
problem in source file cachedb_mongodb_dbase.c
problematic code:
.....
mongo_cmd_get_last_error(conn,MONGO_DATABASE(connection),&err_b);
			bson_iterator_init(&i,&err_b);
			while( bson_iterator_next(&i)) {
				LM_ERR("Fetched ERR key [%s]. Val = ",bson_iterator_key(&i));
				switch( bson_iterator_type( &i ) ) {
					case BSON_DOUBLE:
....
fixed it:
.....
mongo_cmd_get_last_error(conn,MONGO_DATABASE(con),&err_b);
                        if(err_b.data!=NULL) // check
                        {
                                bson_iterator_init(&it,&err_b);
                                while( bson_iterator_next(&it)) {
                                        LM_ERR("Fetched ERR key [%s]. Val = ",bson_iterator_key(&it));
                                        switch( bson_iterator_type( &it ) ) {
                                                case BSON_DOUBLE:
.......

**Comment by liviuchircu** [comment]
The crash replicates 100% of the time on my side. All you have to do is to perform *insert* or *remove* operations while shutting down the `mongod`.

The idea behind your patch seems okay. However, I want to make sure we aren't using the driver incorrectly, thus causing this NULL field.
