### ISSUE TITLE
Opensips 2.1 problems on start when cannot connect to redis

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#753]
When opensips 2.1 cannot connect to redis on start, it hangs with these messages in log:

Jan 12 11:57:06 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 160 ms (now 210 ms), it may overlap..
Jan 12 11:57:06 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 210 ms (now 350 ms), it may overlap..
Jan 12 11:57:06 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 350 ms (now 410 ms), it may overlap..
Jan 12 11:57:06 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 410 ms (now 540 ms), it may overlap..
Jan 12 11:57:06 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 540 ms (now 610 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 610 ms (now 720 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 720 ms (now 850 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 850 ms (now 920 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 920 ms (now 1050 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1050 ms (now 1120 ms), it may overlap..
Jan 12 11:57:07 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1120 ms (now 1200 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1200 ms (now 1310 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1310 ms (now 1400 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1400 ms (now 1510 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1510 ms (now 1610 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1610 ms (now 1710 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1710 ms (now 1810 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1810 ms (now 1920 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 1920 ms (now 2010 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 2010 ms (now 2110 ms), it may overlap..
Jan 12 11:57:08 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 2110 ms (now 2200 ms), it may overlap..
Jan 12 11:57:09 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 2200 ms (now 2300 ms), it may overlap..
Jan 12 11:57:09 [25689] WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 2300 ms (now 2400 ms), it may overlap..

**Comment by razvancrainea** [comment]
Hi, Nick!

After it times out, do you still continue to see these logs?
This warning is a known issue, we are working on a fix for it.

Best regards,
Răzvan

**Comment by nikbyte** [comment]
It has no timeout and it's not just warning. If it cannot connect redis, it cannot start, just hangs. I've waited for about 5 minutes, it is still complaining into logs and hangs.

**Comment by nikbyte** [comment]
How to reproduce. Just set redis to working ip with no (not working) redis. Like 8.8.8.8.
