### ISSUE TITLE
Radius accounting problem

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#755]
When opensips has not received BYE packet from peers (both sides disconnected), but generated it by dialog module (dialog timeout), opensips doesn't generate radius accounting stop request.

**Comment by ionutrazvanionita** [comment]
Tried to recreate your bug and used the following config [0] but as you can see in the pcap[1] the accounting requests are generated for both BYEs.

opensips -v output

version: opensips 2.2-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 055f4b1
main.c compiled on 13:21:55 Jan 14 2016 with gcc 4.8

Can you provide more details, please?

[0] https://gist.github.com/ionutrazvanionita/1e911974013e8778db4a
[1] http://www.filedropper.com/radius_1
