### ISSUE TITLE
avp_ops: failure to start if db ops used only in async mode

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#757]
If avp_db_query is used exclusively in async mode, during init, the avp_db_query function is not found in script and opensips is failing to start with the following error being reported:
```
ERROR:avpops:__fixup_db_query_avp: no db url defined to be used by this function
```

Workaround: define a dummy route where avp_db_query is used in sync mode.
The debug logs will show:
```
DBG:core:is_mod_func_used: function avp_db_query found to be used in script
DBG:core:find_mod_export: found <db_bind_api> in module db_mysql [/usr/local/lib64/opensips/modules/]
```

**Comment by razvancrainea** [comment]
Hi, Ovidiu!

Are you using the async query in a `switch` statement? If so, this bug was already fixed in the master branch and I have just backported it to 2.1. A bit too late though :(.

Best regards,
Răzvan

**Comment by ovidiusas** [comment]
All good now. Thanks for the backport.

-ovidiu
