### ISSUE TITLE
is_uri_user_e164

### ISSUE THREAD

**Issue by ferrored** [OpenSIPS/opensips#762]
I migrate from opensips 1.11.5-tls to opensips 1.11.6-tls, and I notice that the function "is_uri_user_e164" no longer work.

In version 1.11.5-tls I used this code :
```
  if (is_uri_user_e164("$ru"))  {  # $rU  begins with the character +   
    
        if ( !enum_query("nrenum.net.") && !enum_query("e164.arpa.") ) 
	         xlog("L_INFO","ROUTE[$var(testo)] Enum resolution FAILED.... ID=$ci\n");
         else 
                 xlog("L_INFO","ROUTE[$var(testo)] Enum resolution SUCCEDED for <$tU> --> <$ru>.... ID=$ci\n");             
                                 
     } else
            xlog("L_INFO","ROUTE[$var(testo)] $rU not e.164 number! ID=$ci\n");
```
I haven't seen anythyng about it in the change log.

Thanks

Piero

**Comment by razvancrainea** [comment]
Can you elaborate a bit "no longer work"? Is it always failing, or it always return true? You're not seeing any of the logs?

**Comment by ferrored** [comment]
I don't see anything in the logs about is_uri_user_e164 function, also with debug=8.

**Comment by ferrored** [comment]
It seems that the function always fails

**Comment by bogdan-iancu** [comment]
what is the $ru you are testing ?

**Comment by ferrored** [comment]
for examples +390249459310

**Comment by ferrored** [comment]
diff opensips-1.11.6-tls/modules/uri/checks.c opensips-1.11.5-tls/modules/uri/checks.c 
356,c356
< 	    if (c < '0' || c > '9') return -1;
---
> 	    if (c < '0' && c > '9') return -1;

replacing (c < '0' || c > '9') with  (c < '0' && c > '9') it seems to work

**Comment by bogdan-iancu** [comment]
I don't think is correct what you did - while iterating through all the chars of the username, it exits with error if any char is not digit -> if it is before OR after the set of digits (in the ascii array). 
So it is an "OR" and not an "AND" . A digit cannot be before 0 AND after 9 in the same time :) .
Can you print "c" in the "if" here:
   https://github.com/OpenSIPS/opensips/blob/2.1/modules/uri/checks.c#L354
(before the return -1).

**Comment by ferrored** [comment]
This is the output you ask:

Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=3
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=9
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=0
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=2
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=4
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=9
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=4
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=5
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=9
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=3
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=1
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=0
Jan 18 17:54:32 proxysiptest /sbin/opensips[24766]: DBG:uri:e164_check: c=@

You're right. I copied (c < '0' && c > '9') from the 1.11.5 branch ( It's the only difference between the checks.c files) without thinking .
