### ISSUE TITLE
Missing path in URL for XMLRPC events

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#763]
If an event subscriber is set as http://192.168.3.132:8080/ccurbiz/xmlrpc (via xmlrpc backend), the event is trigger as http://192.168.3.132:8080 - the path part of the URL is discarded in  the HTTP request of the event.
Reported by Julian Kay - see:
    http://lists.opensips.org/pipermail/users/2016-January/033380.html

**Comment by ionutrazvanionita** [comment]
https://github.com/OpenSIPS/opensips/commit/be43fcdb7696c6ee53673b351380fe701c209a44. If no path provided the default one will be '/RPC2' as before, else the one found between port and method shall be used('/ccurbiz/xmlrpc') in the example above.
