### ISSUE TITLE
Log mysql queries 

### ISSUE THREAD

**Issue by dzhou121** [OpenSIPS/opensips#766]
Hi,

Is there a way to log mysql queries. I need to debug a presentity update error but couldn't find a way to log msyql queries even debug=4. 

Is that due to ?

	/* screws up the terminal when the query contains a BLOB :-( (by bogdan)
	 * LM_DBG("submit_query(): %.*s\n", _s->len, _s->s);
	 */

**Comment by bogdan-iancu** [comment]
Better check them on the mysql server side - you can enable text logging of all queries; Or if you connect to the mysql server via IP:port (and not via unix socket), you can simply sniff it with ngrep (on port 3306).

**Comment by dzhou121** [comment]
Thanks Bogdan. It's a very busy Mysql server and the CPU usage is very high when turning it on. The issue happens very rarely so I can't sniff as well.

On another note, the issue looks to be unique key failure on presentity table. I have a cluster of 2 Opensips. They started at exact the same time and have the same range of pids(forcked). So the etag generated on the 2 servers could be collisioned. Am I right?

**Comment by bogdan-iancu** [comment]
What about sniffing with ngrep on port 3306 for the queries ?

**Comment by dzhou121** [comment]
I'll use ngrep on Opensips servers to see if I can capture it. Thanks.
