### ISSUE TITLE
Git clone opensips 1.11 with Problem

### ISSUE THREAD

**Issue by eliakimfelmorais** [OpenSIPS/opensips#771]
Today OpenSIPS 1.11 from GIT and during the compilation I received message segmentation fault.

Modules activated on compilation

Dialplan, db_mysql, rabbitmq_event, json, xmlrpc, presence, presence_xml, presence_dialoginfo

ompiling sca_db_handler.c
Compiling sca_logic.c
Compiling sca_records.c
In file included from ../../parser/msg_parser.h:49,
                 from ../../sr_module.h:50,
                 from b2b_sca.c:33:
../../parser/../flags.h:64: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
make[2]: *** [b2b_sca.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/usr/src/opensips_1_11/modules/b2b_sca'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/usr/src/opensips_1_11'

tks,

**Comment by bogdan-iancu** [comment]
Well, as the error says, it is a HW or OS problem .

Does this happen only when compiling the presence_callinfo module ?
