### ISSUE TITLE
segfault on startup with latest master  eaef57e

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#772]
on commit  eaef57e  

When i try to start opensips it segfaults immediately.

here are logs: https://gist.github.com/etamme/224380afca240940c525

here is a core dump, and the executable which generated the core:

https://owncloud.uphreak.com/index.php/s/wLFMXfRaRCdE7RG

https://owncloud.uphreak.com/index.php/s/aBaZJb2mlzRcEUx

**Comment by razvancrainea** [comment]
Hey, Eric!

Could you post the TLS parameters you are using? Unfortunately the new memory debugging is not yet completed, and I can't get that much info from the corefile.
Also, what memory allocator are you using? It looks like F_MALLOC. Can you confirm?

Best regards,
Răzvan

**Comment by etamme** [comment]
Hey Raz,

Im actually not 100% sure what happened.  I did a git clean -fxd and rebuilt from master and things seem to be working fine, so I can only assume it was not a clean build.  Since I can no longer reproduce, I will close the ticket.  

I was using F_MALLOC.
