### ISSUE TITLE
cachedb_local doesn't compile by default on V2.2

### ISSUE THREAD

**Issue by telephone-man** [OpenSIPS/opensips#777]
I asked in IRC why "cachedb_local" wasn't in the menuconfigs list of 'excluded modules'. I was told this...

[11:43] <liviuc> cachedb_local isn't listed there, and will compile by default

..However, if you compile via the makemenu, then cachedb_local IS NOT compiled.

However, you can force it to be included in the compile by manually editing the Makefile.conf file.

Steps to recreate:
1. Run make menuconfig
2. Select compile and install opensips
3. when finished, check your modules directory for cachedb_local.so. It won't be there
4. try adding loadmodule "cachedb_local.so" to opensips.cfg and it'll fail to find it

Steps to fix
1. add 'cachedb_local' to 'include_modules?' variable in Makefile.conf
2. Run make menuconfig
3. Select compile and install opensips
4. when finished, check your modules directory for cachedb_local.so. It will now be there
5. try adding loadmodule "cachedb_local.so" to opensips.cfg and it'll succeed

**Comment by telephone-man** [comment]
I was also told..

[11:47] <liviuc> "make modules" is enough to get it to compile

..but havn't tested this on 2.2

**Comment by liviuchircu** [comment]
Are you sure you're installing to the correct prefix? (bottom row in `Makefile.conf`)

*Hint: verify this by checking the modification timestamps of the other modules:*

    $ ls -la /tmp/lib64/opensips/modules/
    ...
    -rwxr-xr-x 1 liviu liviu  57842 ian 29 16:27 benchmark.so
    -rwxr-xr-x 1 liviu liviu  96122 ian 29 16:27 cachedb_local.so
    ...

I've tested both the `make install` and `make modules` commands on `master` branch, and they both correctly handle cachedb_local, just like any other module (you just have to throw a new module in `modules/` and it will automatically be part of the build system).
