### ISSUE TITLE
Not enough free memory Opensips v2.2

### ISSUE THREAD

**Issue by cepehutu** [OpenSIPS/opensips#778]
Feb  1 12:08:44 front-voice-4 opensips_log[4983]: WARNING:core:fm_malloc: Not enough free memory (2004264), will attempt defragmentation
Feb  1 12:08:44 front-voice-4 opensips_log[4983]: ERROR:core:fm_malloc: Defragmentation unsuccessful
Feb  1 12:08:44 front-voice-4 opensips_log[4983]: CRITICAL:core:init_io_wait: could not alloc fd hashtable (2457600 bytes)
Feb  1 12:08:44 front-voice-4 opensips_log[4983]: CRITICAL:core:tcp_main_server: exiting...
Feb  1 12:08:44 front--voice-4 opensips_log[4980]: INFO:rtpengine:rtpe_test: rtp proxy <udp:10.1.246.24:2223> found, support for it enabled
Feb  1 12:08:44 front--voice-4 opensips_log[4982]: INFO:rtpengine:rtpe_test: rtp proxy <udp:10.1.246.24:2223> found, support for it enabled
Feb  1 12:08:44 front--voice-4 opensips_log[4977]: WARNING:core:fm_malloc: Not enough free memory (1994984), will attempt defragmentation
Feb  1 12:08:44 front--voice-4 opensips_log[4977]: ERROR:core:fm_malloc: Defragmentation unsuccessful
Feb  1 12:08:44 front--voice-4 opensips_log[4977]: CRITICAL:core:init_io_wait: could not alloc fd hashtable (2457600 bytes)
Feb  1 12:08:44 front--voice-4 opensips_log[4977]: CRITICAL:core:tcp_worker_proc: exiting...
Feb  1 12:08:44 front--voice-4 opensips_log[4969]: INFO:core:handle_sigs: child process 4983 exited normally, status=255
Feb  1 12:08:44 front--voice-4 opensips_log[4969]: INFO:core:handle_sigs: terminating due to SIGCHL

**Comment by cepehutu** [comment]
[12:08+00 root@front-voice-4:/etc/init.d]# free -m
             total       used       free     shared    buffers     cached
Mem:          7864        643       7221         12         30        279
-/+ buffers/cache:        333       7531
Swap:         2047          0       2047

**Comment by cepehutu** [comment]
version: opensips 2.2-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: a4e3ff8
main.c compiled on 00:48:01 Jan 29 2016 with gcc 4.4.7

**Comment by bogdan-iancu** [comment]
@cepehutu , could you paste here the output of "ulimit -n" please. Also, what is the amount of configured pkg memory ?

**Comment by cepehutu** [comment]
/etc/opensips]# ulimit -n
1024000


Feb  1 15:05:51 front-sender-voice-4 opensips: WARNING:core:trans_load: protocol tls loaded, but no listeners defined! Skipping ...
Feb  1 15:05:51 front--voice-4 opensips: WARNING:core:trans_load: protocol ws loaded, but no listeners defined! Skipping ...
Feb  1 15:05:51 front--voice-4 opensips_log[8726]: NOTICE:core:main: version: opensips 2.2-dev (x86_64/linux)
Feb  1 15:05:51 front--voice-4 opensips_log[8726]: INFO:core:main: using 32 Mb shared memory
Feb  1 15:05:51 front--voice-4 opensips_log[8726]: INFO:core:main: using 2 Mb private memory per process

OS: Centos 6.7
Based of VMware cluster

**Comment by bogdan-iancu** [comment]
@cepehutu , many thanks for the report and help. The issue is now fixed on GIT repo.
