### ISSUE TITLE
B2B GUIDs too short

### ISSUE THREAD

**Issue by abalashov** [OpenSIPS/opensips#783]
In `b2b_entities/dlg.c:b2b_generate_key()`, the use of this format:

`<B2B prefix>.<hash index>.<local index>`

leads to very short Call-IDs like this:

`Call-ID: B2B.27572.17705`

This is impractically short, and is certain to lead to collisions in a high-volume environment with millions of calls daily. There are many database systems etc. that rely on all calls being identifiable by a unique GUID. I don't think it conforms to the RFC 3261 prescription that GUIDs be good GUIDs.

Unfortunately, it's not possible to simply append additional random data to the key string, since the Call-ID has specific meaning that is extracted in sequential requests, as per `b2b_entities/dlg.c:b2b_parse_key()`. This function also foresees the length of the GUID and the positioning of the delimiters to be rather static in nature.

Some sort of solution to increase overall Call-ID length and combinatorial complexity is needed, such as appending time-based data into the string. 

Much appreciated!

**Comment by bogdan-iancu** [comment]
@abalashov , could you please test the following patch:
      https://gist.github.com/bogdan-iancu/694b00fcafb9561bfd31
Please take care, there is not much of a testing done so far on the patch.

**Comment by abalashov** [comment]
Bogdan,

Thank you, will do so ASAP!
