### ISSUE TITLE
Fail to build from source in multiple arches

### ISSUE THREAD

**Issue by devjunix** [OpenSIPS/opensips#785]
Hello,

Thanks to the effort of Razvan Crainea, Opensips landed in GNU Debian.

Right now we have problems to compile it in different arches. Please check the GNU Debian logs:

https://buildd.debian.org/status/package.php?p=opensips

Opensips can be official for the next GNU Debian stable release, but need that it compiles in our all supported arches.

Thanks in advance.

**Comment by razvancrainea** [comment]
Commit ad44a0553a18058449f5407adc88700a1603055b should have fixed the major warnings. Looking into the other issues now.

**Comment by devjunix** [comment]
Hello,

I found that FTBFS in several arches is due parallel issue, GNU Debian builders use by default parallel build.

I've fixed the following error by new empty line
install: cannot stat '': No such file or directory
Makefile:636: recipe for target 'install-app-doc' failed

and this by install-bin target runs first that opensipsmc target

touch           /«PKGBUILDDIR»/debian/opensips/usr/sbin//osipsconfig
  install  -m 755 menuconfig/configure /«PKGBUILDDIR»/debian/opensips/usr/sbin//osipsconfig
  install: cannot stat 'menuconfig/configure': No such file or directory
  Makefile:548: recipe for target 'install-bin' failed
  make[2]: *** [install-bin] Error 1
  make[2]: *** Waiting for unfinished jobs....

Please apply the attached patch file.

[fix_parallel.txt](https://github.com/OpenSIPS/opensips/files/137000/fix_parallel.txt)

**Comment by devjunix** [comment]
Hello,

However I found that some modules fail to install some files:

Relevant parts of the log:
mkdir -p //dbtext/opensips ; \
for FILE in ../../scripts//dbtext/opensips/grp ../../scripts//dbtext/opensips/globalblacklist ../../scripts//dbtext/opensips/cc
_agents ../../scripts//dbtext/opensips/speed_dial ../../scripts//dbtext/opensips/cc_cdrs ../../scripts//dbtext/opensips/rtpprox
y_sockets ../../scripts//dbtext/opensips/emergency_report ../../scripts//dbtext/opensips/dr_groups ../../scripts//dbtext/opensi
ps/fraud_detection ../../scripts//dbtext/opensips/presentity ../../scripts//dbtext/opensips/silo ../../scripts//dbtext/opensips
/active_watchers ../../scripts//dbtext/opensips/dr_rules ../../scripts//dbtext/opensips/dr_partitions ../../scripts//dbtext/ope
nsips/emergency_routing ../../scripts//dbtext/opensips/b2b_logic ../../scripts//dbtext/opensips/load_balancer ../../scripts//db
text/opensips/b2b_entities ../../scripts//dbtext/opensips/sip_trace ../../scripts//dbtext/opensips/xcap ../../scripts//dbtext/o
pensips/aliases ../../scripts//dbtext/opensips/address ../../scripts//dbtext/opensips/version ../../scripts//dbtext/opensips/di
spatcher ../../scripts//dbtext/opensips/carrierfailureroute ../../scripts//dbtext/opensips/watchers ../../scripts//dbtext/opens
ips/pua ../../scripts//dbtext/opensips/domain ../../scripts//dbtext/opensips/subscriber ../../scripts//dbtext/opensips/imc_room
s ../../scripts//dbtext/opensips/re_grp ../../scripts//dbtext/opensips/uri ../../scripts//dbtext/opensips/location ../../script
s//dbtext/opensips/dbaliases ../../scripts//dbtext/opensips/dialog ../../scripts//dbtext/opensips/route_tree ../../scripts//dbt
ext/opensips/pdt ../../scripts//dbtext/opensips/userblacklist ../../scripts//dbtext/opensips/cc_calls ../../scripts//dbtext/ope
nsips/closeddial ../../scripts//dbtext/opensips/carrierroute ../../scripts//dbtext/opensips/missed_calls ../../scripts//dbtext/
opensips/cpl ../../scripts//dbtext/opensips/dr_gateways ../../scripts//dbtext/opensips/rls_watchers ../../scripts//dbtext/opens
ips/imc_members ../../scripts//dbtext/opensips/usr_preferences ../../scripts//dbtext/opensips/rls_presentity ../../scripts//dbt
ext/opensips/cachedb ../../scripts//dbtext/opensips/registrant ../../scripts//dbtext/opensips/acc ../../scripts//dbtext/opensip
s/domainpolicy ../../scripts//dbtext/opensips/b2b_sca ../../scripts//dbtext/opensips/dr_carriers ../../scripts//dbtext/opensips
/dialplan ../../scripts//dbtext/opensips/cc_flows ; do \
        if [ -f $FILE ] ; then \
                touch           $FILE \
                        //dbtext/opensips/`basename "$FILE"` ; \
                install  -m 644 $FILE \
                        //dbtext/opensips/`basename "$FILE"` ; \
        fi ;\
done ;\

mkdir: cannot create directory '//opensipsctl': Permission denied
install: cannot create regular file '//opensipsctl/opensipsctl.dbtext': No such file or directory
touch: cannot touch '//opensipsctl/opensipsdbctl.dbtext': No such file or directory
install: target '//opensipsctl/' is not a directory: No such file or directory
mkdir: cannot create directory '//opensipsctl': Permission denied
touch: cannot touch '//opensipsctl/dbtextdb/dbtextdb.py': No such file or directory
install: target '//opensipsctl/dbtextdb/' is not a directory: No such file or directory
mkdir: cannot create directory '//dbtext': Permission denied
touch: cannot touch '//dbtext/opensips/grp': No such file or directory
install: cannot create regular file '//dbtext/opensips/grp': No such file or directory
touch: cannot touch '//dbtext/opensips/globalblacklist': No such file or directory
install: cannot create regular file '//dbtext/opensips/globalblacklist': No such file or directory
touch: cannot touch '//dbtext/opensips/cc_agents': No such file or directory
install: cannot create regular file '//dbtext/opensips/cc_agents': No such file or directory
touch: cannot touch '//dbtext/opensips/speed_dial': No such file or directory
install: cannot create regular file '//dbtext/opensips/speed_dial': No such file or directory
......
......
Makefile:21: recipe for target 'install_module_custom' failed
make[3]: *** [install_module_custom] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/modules/db_text'

The same happen with db_berkeley, pi_http, db_mysql, db_postgres and perl modules.

it seems that $(modules-prefix)/$(lib-dir) in install_module_custom target are empty but I don't know why is happening.

**Comment by razvancrainea** [comment]
Fix deployed.
