### ISSUE TITLE
please migrate from memcache to memcached

### ISSUE THREAD

**Issue by devjunix** [OpenSIPS/opensips#787]
Hello,

Currently there is a module that use memcache.h

modules/lua/sipmemcache.c:#include <memcache.h>

That module is deprecated some time ago, no upstream developing.
https://bugs.debian.org/499480

Please could you migrate to memcached?

This is important to get Opensips in GNU Debian release.

Thanks in advance.

**Comment by razvancrainea** [comment]
This was implemented in 1ba03270c3d26a400115f5869eaa7e6f55c12813
