### ISSUE TITLE
m_dump does not use REGISTER contact address as destination uri

### ISSUE THREAD

**Issue by itunali** [OpenSIPS/opensips#789]
Hello,

Register contact uri does not use as destination uri for m_dump generated MESSAGE requests. It checks that method is REGISTER and expires value greater than 0 and decide user online or offline correctly but does not use REGISTER contact, always use To uri from DB record.

Documentation says that "The method sends stored messages for the SIP user that is going to register to his actual contact address."

Please look at https://github.com/OpenSIPS/opensips/blob/master/modules/msilo/msilo.c#L992

Regards,

**Comment by bogdan-iancu** [comment]
Hi @itunali , the destination for the message (in msilo) is the actual AOR of the user and not his actual registration address (as while the message is in msilo, the registration may change). So, the msilo module will fire the MESSAGE requests pointing to the AOR -> based on the DNS, they should loop back to your opensips and there you should do lookup(location) for them.

**Comment by itunali** [comment]
Hi bogdan,

I understood that how I should handle MESSAGE requests. May I set $du parameter to loopback interface before m_dump() usage?

Thanks

**Comment by bogdan-iancu** [comment]
No, there is no need and it will not work anyhow.  Better use the outbound_proxy option in the module:
http://www.opensips.org/html/docs/modules/devel/msilo.html#id293612, to point to your server.

**Comment by zjacky0992** [comment]
Has anyone made outbound_proxy + TLS work? I always got error "no TLS client domain found". I have setup client domain as below. Is this the right way to setup the client domain?

modparam("tls_mgm", "client_domain", "dom1")
modparam("tls_mgm", "match_ip_address", "[dom1]*")
modparam("tls_mgm", "match_sip_domain", "[dom1]sip.xyz.com")

modparam("tls_mgm","certificate", "[dom1]/etc/opensips/tls/rootCA/cert2.pem")
modparam("tls_mgm","private_key", "[dom1]/etc/opensips/tls/rootCA/private/privkey2.pem")
modparam("tls_mgm","ca_list", "[dom1]/etc/opensips/tls/user/chain2.pem")


modparam("tls_mgm","tls_method", "[dom1]TLSv1-TLSv1_3")
modparam("tls_mgm","verify_cert", "[dom1]0")
modparam("tls_mgm","require_cert", "[dom1]0")
