### ISSUE TITLE
Topology Hiding: missing 100 Trying

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#791]
Hi
I'm using Opensips 2.2 (updated last week) as an outbound proxy using  topology-hiding module.
I see when opensips received an INVITE and topology-hiding is activated (calling topology_hiding()), Opensips doesn't send back to the caller a 100-Trying response, causing re-INVITEs retransmission until the first provisional response from the called endpoint is received.

Thanks

Alessandro

**Comment by bogdan-iancu** [comment]
Hi @arovetto, do you do any t_newtran() before the t_relay() ? or any async jump ?

**Comment by arovetto** [comment]
Yes, an async rest_post request, and in the resume callback I'm calling topology_hiding("UC") and then t_relay("0x08").

**Comment by bogdan-iancu** [comment]
@arovetto , a similar problem was reported couple of weeks ago and it is related to performing an explicit (or hidden) t_newtran before t_relay().
Let me come back with a fix !

**Comment by arovetto** [comment]
Thank you

**Comment by bogdan-iancu** [comment]
Hi @arovetto , there is fix in 2.2 (devel) trunk - see 0db778 - could you please confirm the fix ?

**Comment by arovetto** [comment]
Thanks, it works!
Just a last question: with the new revision I've had to change a parameter in configuration file, "debug=4" with "log_level=4",  but Opensips with the new parameter does not log at all. Do I need to change some other parameter in order to log via syslog?

Thanks again

**Comment by opensips-github** [comment]
Bogdan, is it the same issue I reported in Jan? Glad if you've fixed it.

**Comment by arovetto** [comment]
> with the new revision I've had to change a parameter in configuration file, "debug=4" with "log_level=4", but Opensips with the new parameter does not log at all. Do I need to change some other parameter in order to log via syslog

Adding "log_stderror=no" in configuration file, opensips started again to log.

**Comment by bogdan-iancu** [comment]
@arovetto, Thank you for confirming the fix. I just did the backport to 1.11 and 2.1.

In regards to your question on log_level - this is just a replacement (as name) for the "debug", without changing its behavior - I tested it with or without log_stderror enabled and it seems to do the trick.
If you noticed some issues or inconsistency, please report it in a different ticket.

Thanks again, Bogdan
