### ISSUE TITLE
Async - not make CDR

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#799]
When use Async radius (radius_send_auth) Opensips 2.2 not make CDR.
Here part of script:
route {
    ......
    if ( is_method("INVITE") ) {
         .....
         async( radius_send_auth("invite","invrespons"), return_invite );
   }
}

route[return_invite] {
     .....
     create_dialog("PB");
     setflag(MAKE_CDR);
     .....
}

**Comment by bogdan-iancu** [comment]
This is a particular case of #810, @ionutrazvanionita has a plan to fix it, working on it.

**Comment by ionutrazvanionita** [comment]
fixed with pr #840 and #841 . Acc module now has a new design
