### ISSUE TITLE
duplicate entry in opensips-1.8.8 

### ISSUE THREAD

**Issue by neha31oct** [OpenSIPS/opensips#801]
I'm using opensips 1.8.8  .The module usrloc if configure as:

modparam("usrloc", "db_mode", 2) 

1.  /usr/local/sbin/opensips[21238]: ERROR:usrloc:wb_timer: inserting contact into database failed

2. CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (1062): Duplicate entry '1111--sip:1111@192.168.26.188:5060;transport=udp;registering_acc=' for key 'account_contact_idx' .

3. Feb 13 04:50:48  /usr/local/sbin/opensips[21238]: ERROR:usrloc:db_insert_ucontact: inserting contact in db failed .

4. Feb 13 04:50:48  /usr/local/sbin/opensips[21238]: ERROR:usrloc:wb_timer: inserting contact into database failed .

5 Feb 13 04:50:48 /usr/local/sbin/opensips[21238]: CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error

**Comment by neha31oct** [comment]
someone already post this issue for opensips-1-11.5 version  and Bodgan had already fix this issue but does this fix also can be applied to opensips-1.8.8?

I am unable to reproduce this issue
This issue comes generaly after restart of opensips

**Comment by bogdan-iancu** [comment]
@neha31oct , yes, there is a fix - see https://github.com/OpenSIPS/opensips/commit/b0553204e58f3db062345f247698c8107e782b98.
As 1.8 is not maintained anymore, there will be no official backport of the fix. But you can apply it by yourself and recompile.
