### ISSUE TITLE
OpenSIPs 2.1 - sip_trace missing initial 100 trying message response to INVITE

### ISSUE THREAD

**Issue by benenta** [OpenSIPS/opensips#802]
We have implemented sip_trace to capture all packets being sent to OpenSIPs, which is then forwarded to our capture server...

route {
        # send packet to "sip_capture"
        route("sip_capture");
...

route["sip_capture"] {

        setflag(22);
        #Duplicate this sip message to capture node
        sip_trace();
}

The capture flag is set to 22 within the sip_trace module configuration. We have noticed this is capturing all packets, except for the initial "100 Trying" response to the initiating UA. Other initial responses, such as "401 Unauthorized" are being logged correctly. It would appear the issue, as far as our testing has revealed, only affects 100 responses.

**Comment by ionutrazvanionita** [comment]
Hi @benenta, your scenario was not supposed to work. You can try the sip_trace module in 2.2 version[0], this problem was fixed if using the dialog(d) flag. 

[0] http://www.opensips.org/html/docs/modules/2.2.x/siptrace 
[1] http://www.opensips.org/html/docs/modules/2.2.x/siptrace#id293470
