### ISSUE TITLE
Perl module - "use UNIVERSAL" is a fatal error starting with Pert 5.22

### ISSUE THREAD

**Issue by lemenkov** [OpenSIPS/opensips#804]
At least two places in OpenSIPS where "use UNIVERSAL" is used:

modules/perl/lib/perl/OpenSIPS/LDAPUtils/LDAPConnection.pm
55:use UNIVERSAL qw( isa );
188:    if( isa($conf ,"OpenSIPS::LDAPUtils::LDAPConnection") ) {

modules/perl/lib/perl/OpenSIPS/VDB.pm
48:use UNIVERSAL qw ( can );
90:		if (can($pkg, $3)) {
92:		} elsif (can($v, "init")) {
95:		} elsif (can($v, "new")) {

This should be fixed as according to this document it will throw a fatal error starting with Perl 5.22:

http://search.cpan.org/~shay/perl-5.21.11/pod/perl5213delta.pod#use%C2%A0UNIVERSAL%C2%A0%27...%27_is_now_a_fatal_error

**Comment by devjunix** [comment]
Hello,

Please apply the attached patch.
[UNIVERSAL-import-deprecated.diff.zip](https://github.com/OpenSIPS/opensips/files/148840/UNIVERSAL-import-deprecated.diff.zip)

**Comment by lemenkov** [comment]
@devjunix thanks for the patch!

**Comment by razvancrainea** [comment]
Committed in e5f0b55da6fd24b6e661801d26d4dd53b1793fd3, all the way to `1.11`.
