### ISSUE TITLE
new apt repository fetch error

### ISSUE THREAD

**Issue by Edwin-Hoff** [OpenSIPS/opensips#805]
If I use the new apt repository (http://apt.opensips.org/packages.php) with Debian Jessie I get an error after dist-upgrade:

W: Failed to fetch http://apt.opensips.org/dists/jessie/Release  No Hash entry in Release file /var/lib/apt/lists/partial/apt.opensips.org_dists_jessie_Release, which is considered strong enough for security purposes
E: Some index files failed to download. They have been ignored, or old ones used instead.

I think it should fetch the Release.gpg file instead.

**Comment by nikbyte** [comment]
I'm not sure if it's problem on the server.
I've installed new debian jessie on vm, added gpg key, repository and successfully installed opensips 2.1.
No any fetch or another errors.

What version of opensips do you try to install?
Do you know any way to reproduce?

**Comment by Edwin-Hoff** [comment]
Hi Nick,

I have this problem on several debian VM's. This is my output:


Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux

cat opensips.list
deb http://apt.opensips.org jessie 2.1-releases

apt-get update
Ign:3 http://apt.opensips.org jessie InRelease
Get:4 http://apt.opensips.org jessie Release [8,150 B]
Get:5 http://apt.opensips.org jessie Release.gpg [181 B]
Hit:6 http://security.debian.org testing/updates InRelease
Fetched 8,331 B in 0s (39.1 kB/s)
Reading package lists... Done
W: Failed to fetch http://apt.opensips.org/dists/jessie/Release  No Hash 
entry in Release file 
/var/lib/apt/lists/partial/apt.opensips.org_dists_jessie_Release, which 
is considered strong enough for security purposes
E: Some index files failed to download. They have been ignored, or old 
ones used instead.


apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5F2FBB7C
Executing: /tmp/tmp.faNbcd6pkF/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
5F2FBB7C
gpg: requesting key 5F2FBB7C from hkp server keyserver.ubuntu.com
gpg: key 5F2FBB7C: "OpenSIPS Solutions <info@opensips.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

Does this anwer the questions? If you need more info, no problem

Gr.

Edwin

Op 22-2-2016 om 21:45 schreef Nick Altmann:

**Comment by nikbyte** [comment]
Are you sure you use Jessie?
cat /etc/debian_version please

and

cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*

**Comment by Edwin-Hoff** [comment]
Hi Nick,

I use 'testing', but normaly this isn't a problem (and it shouldn't be...)

Here is the output:

cat /etc/debian_version
stretch/sid

cat /etc/apt/sources.list
deb http://ftp.nl.debian.org/debian/ testing main non-free contrib
deb http://security.debian.org/ testing/updates main contrib non-free
deb http://ftp.nl.debian.org/debian/ testing-updates main contrib non-free

cat /etc/apt/sources.list.d/*
deb http://apt.opensips.org jessie 2.1-releases

Cheers,

Edwin



Op 22-2-2016 om 22:06 schreef Nick Altmann:
> cat /etc/apt/sources.list
> cat /etc/apt/sources.list.d/*

**Comment by nikbyte** [comment]
Try to do:

```
rm -rf /var/lib/apt/lists/*
apt-get clean
apt-get update
```

**Comment by Edwin-Hoff** [comment]
I already tried, but once again, no luck there:

rm -rf /var/lib/apt/lists/*
apt-get clean
apt-get update
...
Fetched 13.3 MB in 2s (5,194 kB/s)
Reading package lists... Done
W: Failed to fetch http://apt.opensips.org/dists/jessie/Release  No Hash
entry in Release file
/var/lib/apt/lists/partial/apt.opensips.org_dists_jessie_Release, which is
considered strong enough for security purposes
E: Some index files failed to download. They have been ignored, or old ones
used instead.C



It looks like 'http://apt.opensips.org/dists/jessie/ReleaseRelease' is
called in stead of 'http://apt.opensips.org/dists/jessie/ReleaseRelease.gpg'.
The last one contains the keys!


2016-02-23 8:30 GMT+01:00 Nick Altmann <notifications@github.com>:

**Comment by bogdan-iancu** [comment]
Any updates here ? or this still fails ?

**Comment by nikbyte** [comment]
Must work now, it's fixed with latest changes on repo.

**Comment by bogdan-iancu** [comment]
OK, closing time....
