### ISSUE TITLE
Fixed contact not preserved in resume route

### ISSUE THREAD

**Issue by ionutrazvanionita** [OpenSIPS/opensips#807]
If using fix_nated_contact() before doing an async call, in the resume route the fixed contact is lost since the contact header structure is not copied when the message is cloned inside the transaction hence the problem. What's the best way to do this?

Edit:
Reported by Dragomir Haralmbiev

**Comment by opensips-github** [comment]
Hi,
I'm installing opensips 1.8 and i have an error when i compile the sources.
The error is as follows:
Makefile.defs:732: You are using an old ans unsupported gcc version (5.2).
Is it possible to update it and continue the compilation?

NDUWAYEZU Joselyne

2016-02-25 9:18 GMT+01:00 Ionut Ionita <notifications@github.com>:

> If using fix_nated_contact() before doing an async call, in the resume
> route the fixed contact is lost since the contact header structure is not
> copied when the message is cloned inside the transaction hence the problem.
> What's the best way to do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSIPS/opensips/issues/807>.
>
> _______________________________________________
> Devel mailing list
> Devel@lists.opensips.org
> http://lists.opensips.org/cgi-bin/mailman/listinfo/devel
>
>

-- 
Haute École de Bruxelles

**Comment by bogdan-iancu** [comment]
@ionutrazvanionita, as per our discussion, the fix makes no sense at this point. The nathelper module uses some dirty tricks to remember the changed contact, and these tricks get into conflict with how lumps are managed during transaction creation (and sip request cloning in shm mem). Fixing it will be to add yet another even uglier hack and as time as there is a workaround at script level, let's avoid the hacks.
@ionutrazvanionita , please add a comment in documentation, for fix_nated_contact() function - you should not do an async call between fix_nated_contact() and save(location). Do the fix_nated_contact() after the last async call.
The idea is to have this properly fixed when reworking the lumps system in 3.x version.

**Comment by ionutrazvanionita** [comment]
Fixed https://github.com/OpenSIPS/opensips/commit/b68c9b9e227039bea459cdaf44b017d39e259ce0
