### ISSUE TITLE
b2b topology hiding, call to sip:host - incorrect To header in local_route

### ISSUE THREAD

**Issue by DMOsipov** [OpenSIPS/opensips#818]
opensips 1.11.6

I'm using simple b2b topology hiding scenario and trying to call sip:host (without username part), e.g. to sip:192.168.20.1.
If I use $tU core variable in local_route then an error occurs

> ERROR:core:parse_uri: bad char '@' in state 0 parsed: <sip:> (4) / <sip:@192.168.20.1> (17)
> ERROR:core:parse_to_uri: failed to parse To uri
> ERROR:core:pv_get_xto_attr: cannot parse To URI

In the outgoing INVITE there is incorrect To header
> To: sip:@192.168.20.1

**Comment by bogdan-iancu** [comment]
Hi @DMOsipov . When you say you try to call to sip:host, you mean the RURI (before doing the b2b TH in script) does not have a username part, right ? And the local route is for the outgoing INVITE ?

**Comment by DMOsipov** [comment]
Hi Bogdan, 

Yes, you understand my issue right.

**Comment by bogdan-iancu** [comment]
@DMOsipov , thank you for your report, the bug is now fixed on GIT repo.
