### ISSUE TITLE
Crash on MySQL ACC Insert

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#821]
Hello

I get few core dumps per day on a pre-production system based on latest 2.1.2 git revision: 6d126a1.

OS: Debian 7 64bit
MySQL: 5.5.47
Installed on VMWare.

#0  0x00007fc043b0c789 in db_mysql_val2bind (v=v@entry=0x7fc041a33da0 <db_vals+672>,
    binds=binds@entry=0x7fc043fae078, i=i@entry=21) at val.c:295
#1  0x00007fc043b12e2a in db_mysql_do_prepared_query (conn=conn@entry=0x7fc043d6b790,
    v=v@entry=0x7fc041a33b00 <db_vals>, n=n@entry=23, uv=uv@entry=0x0, un=un@entry=0,
    query=0x7fc043d2c9c0 <query_holder>) at dbase.c:676
#2  0x00007fc043b18518 in db_mysql_insert (_h=0x7fc043d6b790, _k=0x7fc041a35180 <db_keys>,
    _v=0x7fc041a33b00 <db_vals>, _n=23) at dbase.c:1265
#3  0x00007fc0417fb5fa in acc_db_request (rq=rq@entry=0x7fc04233be80 <faked_req>,
    rpl=rpl@entry=0xffffffffffffffff, ins_list=ins_list@entry=0x7fc041a364d8 <mc_ins_list>, cdr_flag=2)
    at acc.c:638
#4  0x00007fc04180a06d in on_missed (code=<optimized out>, reply=0xffffffffffffffff,
    req=0x7fc04233be80 <faked_req>, t=<optimized out>) at acc_logic.c:467
#5  tmcb_func (t=<optimized out>, type=<optimized out>, ps=<optimized out>) at acc_logic.c:696
#6  0x00007fc0421152e6 in run_trans_callbacks (type=type@entry=32, trans=trans@entry=0x7fbfbb6533e0,
    req=req@entry=0x7fc04233be80 <faked_req>, rpl=<optimized out>, code=<optimized out>) at t_hooks.c:209
#7  0x00007fc0420cf5a2 in run_failure_handlers (t=0x7fbfbb6533e0) at t_reply.c:569
#8  t_should_relay_response (reply=0xffffffffffffffff, cancel_bitmap=0x7fc043d35b58,
    should_relay=<synthetic pointer>, should_store=<synthetic pointer>, branch=<optimized out>, new_code=408,
    Trans=0x7fbfbb6533e0) at t_reply.c:911
#9  relay_reply (t=t@entry=0x7fbfbb6533e0, p_msg=p_msg@entry=0xffffffffffffffff, branch=<optimized out>,
    msg_status=msg_status@entry=408, cancel_bitmap=cancel_bitmap@entry=0x7fffebfaaa28) at t_reply.c:1125
#10 0x00007fc04212661a in fake_reply (code=408, branch=<optimized out>, t=0x7fbfbb6533e0) at timer.c:260
#11 final_response_handler (fr_tl=<optimized out>) at timer.c:391
#12 timer_routine (ticks=<optimized out>, set=<optimized out>) at timer.c:1066
#13 0x00000000004a15a1 in handle_timer_job () at timer.c:565
#14 0x000000000058dc0f in handle_io (fm=0x7fc043d782b0, fm=0x7fc043d782b0, fm=0x7fc043d782b0,
    idx=<optimized out>, event_type=2) at net/net_udp.c:265
#15 io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:215
#16 udp_rcv_loop (si=si@entry=0x7fc043d35f68) at net/net_udp.c:308
#17 0x000000000058f837 in udp_start_processes (chd_rank=chd_rank@entry=0x84a314 <chd_rank>,
    startup_done=startup_done@entry=0x0) at net/net_udp.c:448
#18 0x000000000041ad73 in main_loop () at main.c:731
#19 main (argc=<optimized out>, argv=<optimized out>) at main.c:1280

I can provide access to the box if required.

Thank you in advanse.

**Comment by bogdan-iancu** [comment]
Hi @apsaras , please provide me, off line, the access to investigate. 

Can you reproduce the crash ?

Regards, Bogdan

**Comment by apsaras** [comment]
Hello Bogdan

No I can not reproduce it. I will send you a pm for access.

Regards

**Comment by bogdan-iancu** [comment]
Thank you @apsaras  for the help - the bug was found and currently @apsaras is testing the fix.
