### ISSUE TITLE
Possible bug in xmlrpc-ng

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#826]
Before 2.1 we used such xmlrpc request:

`<?xml version="1.0" ?><methodCall><methodName>dr_reload</methodName></methodCall>
`
after upgrade to 2.1 this request returns:

ERROR:mi_xmlrpc_ng:mi_xmlrpc_http_run_mi_cmd: missing node params

It works only this way:
`<?xml version="1.0" ?><methodCall><methodName>dr_reload</methodName><params></params></methodCall>
`
Is it okay or bug?

**Comment by bogdan-iancu** [comment]
Hi @nikbyte , reading from the xml rpc syntax (http://xmlrpc.scripting.com/spec.html), it is not sure if the the <params> tag is mandatory:
" If the procedure call has parameters, the <methodCall> must contain a <params> sub-item. The <params> sub-item can contain any number of <param>s, each of which has a <value>. "

Regards,
Bogdan

**Comment by nikbyte** [comment]
dr_reload is without parameters. Before xmlrpc_ng we used query without "params" tag. I think, it's also not necessary here. But after 2.1 we must use only xmlrpc_ng, because xmlrpc was deprecated and now "params" tag is necessary, we need change our external soft to support this. I think it's not correct to require "params" tag if procedure has no parameters.
