### ISSUE TITLE
t_reply is sending provisional message even if 0x01 is set

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#833]
Hello.

It seems that 0x01 flag in t_reply is not working. t_reply is sending provisional message.

if (!t_relay("1"))
        {
                sl_reply_error();
        }

From tcpdum

SIP/2.0 100 Trying (produced with sl_send_reply)
SIP/2.0 100 Giving a try (produced by t_relay)

version: opensips 2.1.2 (x86_64/linux)
git revision: e48bc6f

**Comment by bogdan-iancu** [comment]
@apsaras , do you do any t_newtran() in script for that INVITE ?

**Comment by apsaras** [comment]
I just do create_dialog("B")

**Comment by bogdan-iancu** [comment]
@apsaras , this is related to a recent fix 054836 - any t_newtran() forces a 100 trying reply automatically - this is done to be SIP consistent with all scenarios and also to be able to send the 100 trying as soon as possible.
We will have to remove the 0x01 flag as it is not doing anything anymore.

**Comment by apsaras** [comment]
Is there a way to disable that and handle 100 message from the script?

if not, does the t_newtran() is called on create_dialog()?

Thank you.

**Comment by bogdan-iancu** [comment]
no, create_dialog() does not forces a t_newtran(), maybe some other function you use from script ?

**Comment by apsaras** [comment]
I do not see any.

Those are the modules and steps used before relay. 

create_dialog
permissions
dialogue profile
load balancer
fraud detection
dial plan
topology hiding

Is there a way to figure out which function might execute t_newtrans()?

**Comment by bogdan-iancu** [comment]
Indeed, that is tricky as on a first view none of those function should force an internal t_newtran(). a quick trick you can do is to move your manual sl_send_reply() down in script, until you see the order between the two 100 replies gets swapped

**Comment by bogdan-iancu** [comment]
Hi @apsaras , any progress here ? you can run opensips is log_level debug and send me the logs...I will figure out where the 100 comes from.

**Comment by apsaras** [comment]
Hello.

Trying is sent by t_relay

19:11:16.910525 IP x.x.x.x.sip > y.y.y.y.sip: SIP, length: 304
E`.L.i@.@....*..[..Z.....8.*SIP/2.0 100 Trying 5

19:11:16.910645 IP x.x.x.x.sip > y.y.y.y.sip: SIP, length: 308
E`.P.j@.@....*..[..Z.....<..SIP/2.0 100 Giving a try

sl_send_reply("100","Trying 5");
        if (!t_relay("1"))
        {
                sl_reply_error();
        }
        exit;

**Comment by bogdan-iancu** [comment]
Hi @apsaras, I must have being blind. Using the sl_send_reply() in stateless mode will never see t_relay(). Or better the other way around - the t_relay() (statefull) will not "see" the sl_send_reply (stateless), so it will do another 100 Trying. Better replace the sl_send_reply() with  a simple t_newtran() (which will create the transaction and also fire the 100 Trying in stateful mode).

Mixing stateful and stateless replying in script may confuse opensips when comes to what was sent out or not.

**Comment by bogdan-iancu** [comment]
@apsaras , Indeed, there are some cases where the automatically generated 100 Trying reply may conflict with the needs of the script writer. So, we just added a new param in TM module, the "auto_100trying" to allow you to completely disable the auto sending of the 100 Trying reply from TM module. If you disable this, it is up to you to send the 100 reply from script, as TM will not do it in any case at all.

**Comment by apsaras** [comment]
Great.

I will try that.

So 

modparam("tm","auto_100trying", 0)

?

Thank you for your support.

**Comment by bogdan-iancu** [comment]
Exactly. And by sure you do your own 100 Trying from script.
