### ISSUE TITLE
Problem starting OpenSIPs with TLS

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#834]
I have problem to setup OpenSIPs with TLS on Centos 6 64bit with OpenSSL 1.0.1e-fips

The message I get on service start is the following

Mar 20 23:34:27 [4831] ERROR:proto_tls:mod_init: unable to set the memory allocation functions
Mar 20 23:34:27 [4831] ERROR:core:init_mod: failed to initialize module proto_tls
Mar 20 23:34:27 [4831] ERROR:core:main: error while initializing modules

My config is the following

loadmodule "proto_tls.so"
modparam("proto_tls", "verify_cert", "0")
modparam("proto_tls", "require_cert", "0")
modparam("proto_tls", "ciphers_list", "NULL")
modparam("proto_tls", "tls_method", "TLSv1")
modparam("proto_tls", "certificate", "/etc/opensips/tls/rootCA/cacert.pem")
modparam("proto_tls", "private_key", "/etc/opensips/tls/rootCA/private/cakey.pem")
modparam("proto_tls", "ca_list", "/etc/opensips/tls/rootCA/cacert.pem")
modparam("proto_tls", "ca_dir", "/etc/opensips/tls/rootCA/")

version: opensips 2.1.2 (x86_64/linux)
git revision: 143328f

Thank you in advance

**Comment by razvancrainea** [comment]
Can you apply this[1] patch, run opensips again, and paste the Warning?

[1] https://gist.github.com/razvancrainea/95788fd927d23d84ac10#file-proto_tls_mem_debug-patch

Thanks,
Răzvan

**Comment by apsaras** [comment]
Hello

Mar 21 11:50:06 [8044] WARNING:core:main: no fork mode and no udp listen address found
Mar 21 11:50:06 [8044] NOTICE:core:main: version: opensips 2.1.2 (x86_64/linux)
Mar 21 11:50:06 [8044] NOTICE:signaling:mod_init: initializing module ...
Mar 21 11:50:06 [8044] WARNING:load_balancer:lb_db_load_data: table "load_balancer" empty
Mar 21 11:50:06 [8044] WARNING:proto_tls:mod_init: unable to set the memory allocation functions m=0x7f9c27862139|0x7f9c30439ac0|0x7f9c30439ac0 r=0x7f9c27861f0e|0x7f9c3043ae20|0x7f9c3043ae20 f=0x7f9c2786240f|0x7f9c3043a920|0x7f9c3043a920
Mar 21 11:50:06 [8044] ERROR:core:init_mod: failed to initialize module proto_tls
Mar 21 11:50:06 [8044] ERROR:core:main: error while initializing modules

**Comment by razvancrainea** [comment]
Could you revert the previous patch and apply this one [2]? It looks like the OpenSSL functions are used before setting the memory allocation functions, just as in this thread[3]. Any chance you upgrade the openssl library?

[2] https://gist.github.com/razvancrainea/35d4b039dadc9349941f
[3] https://rt.openssl.org/Ticket/Display.html?id=3137&user=guest&pass=guest

**Comment by apsaras** [comment]
I have the latest Centos 6 OpenSSL version provided by yum and is not easy to upgrade OpenSSL on Centos from sources.

So the problem is OpenSSL related?

I will try the patch and come back to you.

**Comment by apsaras** [comment]
That is the result with the new patch

Mar 22 15:47:36 [2556] WARNING:core:main: no fork mode and no udp listen address found
Mar 22 15:47:36 [2556] NOTICE:core:main: version: opensips 2.1.2 (x86_64/linux)
Mar 22 15:47:36 [2556] NOTICE:signaling:mod_init: initializing module ...
Mar 22 15:47:36 [2556] WARNING:load_balancer:lb_db_load_data: table "load_balancer" empty
Mar 22 15:47:36 [2556] WARNING:proto_tls:mod_init: unable to set the memory allocation functions m=0x7f41aae3c139|0x7f41b3a13ac0|0x7f41b3a13ac0 r=0x7f41aae3bf0e|0x7f41b3a14e20|0x7f41b3a14e20 f=0x7f41aae3c40f|0x7f41b3a14920|0x7f41b3a14920
Mar 22 15:47:36 [2556] ERROR:core:init_mod: failed to initialize module proto_tls
Mar 22 15:47:36 [2556] ERROR:core:main: error while initializing modules

**Comment by krys1976** [comment]
As I already told Bogdan, this is related to openssl-fips version. We had a research on that and we found certain memory allocation failures in openssl hobble version incl. fedora patches bond to fips object module. Currently only two ways to move around:
1) use openssl-1.0.1e without being compiled against fips object module
2) use openssl-1.0.2g-2/3 and try new integration with fips 

This is not opensips-related!

**Comment by apsaras** [comment]
Can you please suggest a Linux Version that has a working ssl package? I am using Centos 6 and I suppose is not easy to go to 1.0.2g.

**Comment by krys1976** [comment]
@apsaras ... openssl-1.0.1e in Centos 6 is just fips enabled. The original package doesn't have the addition -Fips. If you like to use openssl-1.0.2g just install rpmbuild and the openssl-1.0.2g srpm package from fedora 23 and make a package with rpmbuild.

**Comment by bogdan-iancu** [comment]
@krys1976, what should be the correct behavior from the OpenSIPS perspective ? To detect the faulty version and prevent starting ?

**Comment by krys1976** [comment]
From security perspective a faulty version of openssl should prevent a start of OpenSIPS. I would prefer a shutting down daemon, when malloc on openssl isn't possible.

**Comment by bogdan-iancu** [comment]
The faulty version is openssl-1.0.1e ?

**Comment by apsaras** [comment]
Hello krys1976.

I managed to upgrade to upgrade openssl

openssl version
OpenSSL 1.0.2g  1 Mar 2016

Now the service is starting but I am getting the following

Apr  4 19:29:18 sips /sbin/opensips[11945]: WARNING:proto_tls:mod_init: disabling compression due ZLIB problems
Apr  4 19:29:18 sips /sbin/opensips[11945]: NOTICE:proto_tls:init_ssl_ctx_behavior: No EC curve defined
Apr  4 19:29:18 sips /sbin/opensips[11945]: NOTICE:proto_tls:init_ssl_ctx_behavior: cipher list set to NULL
Apr  4 19:29:18 sips /sbin/opensips[11945]: WARNING:proto_tls:init_ssl_ctx_behavior: client verification NOT activated. Weaker security.
Apr  4 19:29:18 sips /sbin/opensips[11945]: NOTICE:proto_tls:init_ssl_ctx_behavior: No EC curve defined
Apr  4 19:29:18 sips /sbin/opensips[11945]: NOTICE:proto_tls:init_ssl_ctx_behavior: cipher list set to NULL
Apr  4 19:29:18 sips /sbin/opensips[11945]: WARNING:proto_tls:init_ssl_ctx_behavior: server verification NOT activated. Weaker security.

I will check the TLS functionality later today and let you know.

Thank you for your help.

**Comment by apsaras** [comment]
Unfortunately I am not able to connect.

Apr  4 22:02:14 sips /sbin/opensips[18844]: ERROR:proto_tls:tls_accept: New TLS connection from 1.1.1.1:40564 failed to accept
Apr  4 22:02:14 sips /sbin/opensips[18844]: ERROR:proto_tls:tls_print_errstack: TLS errstack: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
Apr  4 22:02:14 sips /sbin/opensips[18844]: ERROR:proto_tls:tls_read_req: failed to do pre-tls reading

**Comment by razvancrainea** [comment]
It looks like the engine does not manage to find a common cipher to use. Checking your parameters, it seems that you are not using any ciphers (the ```NULL``` ciphers is set). Perhaps your client does not allow this.
Could you try setting the TLSv1 cipher in the cipher list?
```
modparam("proto_tls", "ciphers_list", "TLSv1")
```
Or simply remove the parameter. If this still does not work, can you try to make a wireshark trace to check the TLS/SSL negociation?

Best regards,
Răzvan
