### ISSUE TITLE
DBG_MALLOC should disable compiler optimizations

### ISSUE THREAD

**Issue by liviuchircu** [OpenSIPS/opensips#838]
It makes no sense to run with `DBG_MALLOC` in order to troubleshoot a crash / leak / race while enabling compiler optimizations (`-O9`), just to make your life harder.

In this case, OpenSIPS should automatically compile with `-O0`.

**Comment by ovidiusas** [comment]
When DBG_MALLOC is set, the optimizations are disabled now.
Commit: 195a7e62e6bcf015545242e13b1b96cc3d2b28b6
