### ISSUE TITLE
TH with Callid Hiding issue with Internally generated messages retransmissions

### ISSUE THREAD

**Issue by vladpaiu** [OpenSIPS/opensips#839]
Hello,

When using topology_hiding("C") , for internally generated messages by the dialog module ( eg. BYEs, Options and Re-INVITE messages ), retransmissions to the callee leg are done using the caller leg callid instead of the proper hidden callid - still, the initial requests goes out with the proper callid.

The initial request goes out properly relying on the current processing context, but the retransmissions go out badly because the transaction does not have the dialog_ctx linked into it - due to the fact that t_request_within does not expose the newly created transaction. 

A proposed fix would be to alter the dlg_t structure to have it contain a void* dialog_ctx field, which, if populated, would lead to the transaction created by t_uac to also inherit that pointer - this would be safe from ref point of view since the transaction is already properly reffed by the dialog module when internally generating messages.

Other suggestions for fixing this ?

Best Regards,
Vlad

**Comment by razvancrainea** [comment]
After discussing on Skype, although this is not the cleanest fix, for now it's the best way to go.
Do you have a patch for something? If so, please commit it in the master branch and backport it back to 1.11.

Best regards,
Răzvan
