### ISSUE TITLE
TLS session closing (maybe related to #670)

### ISSUE THREAD

**Issue by dbeskoek** [OpenSIPS/opensips#843]
Running 1.11.6 (tagged-version) on Debian8.3 there seems to be a problem for running TLS-connections. Some sessions are working fine for hours (REGISTER,SUBSCRIBE, also some calls), but suddenly they were closed by opensips:

Mar 31 15:56:44 test01 /usr/sbin/opensips[118906]: ERROR:core:_tls_read: TLS connection to 192.168.233.19:55817 read failed
Mar 31 15:56:44 test01 /usr/sbin/opensips[118906]: ERROR:core:_tls_read: TLS read error: 1
Mar 31 15:56:44 test01 /usr/sbin/opensips[118906]: ERROR:core:tls_print_errstack: TLS errstack: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca

system is not under heavy load, only 100 tls-connections. I found #670 because of the error-message, maybe this problem is still open.

**Comment by bogdan-iancu** [comment]
Hi @dbeskoek, is this still happening for you? You refer #670 which was fixed.

**Comment by bogdan-iancu** [comment]
@dbeskoek , the problem you reported is either related to #670, either to the latest fixing in port aliasing for TCP/TLS conns (see bc996b and 1a9361 )
Please update from GIT and your issue should be fixed.
Thanks for report, Bogdan
