### ISSUE TITLE
opensips-2.2-beta: module sip_trace: trace_id uri parsing failing

### ISSUE THREAD

**Issue by krys1976** [OpenSIPS/opensips#845]
Hi everybody,

1) when a mysql user has a password including a '=', the parser for the uri will fail. As '=' is an allowed character in mysql-passwords it should be allowed here too. 

2) when using the second param table=XXXX; you'll find an
ERROR:core:db_check_api: module db_mysql does not export db_use_table function

in your logfiles.

Best regards
Chris

**Comment by ionutrazvanionita** [comment]
Hi @krys1976 . Can you check https://github.com/OpenSIPS/opensips/commit/b5a60879842d344ccee41af9288fee0cc1bbd762 and confirm that password parsing is working?

**Comment by ionutrazvanionita** [comment]
for the second problem - are you sure you compiled mysql module? that sort of error means that siptrace can't see mysql module to get the function from it

**Comment by krys1976** [comment]
We'll get a nightly build be tomorrow morning and than I'm able to prepare a new test server to confirm it.
On your last comment: of course it's compiled against mysql-libs, otherwise all other modules won't load when having db_url-modparam.

**Comment by ionutrazvanionita** [comment]
Hey @krys1976 did the patch solve the problems?

**Comment by krys1976** [comment]
Hi Ionutraz,

no it doesn't work proper:

Apr 13 13:40:51 sip02 opensips[3645]: ERROR:siptrace:parse_siptrace_uri: URL is MANDATORY!
Apr 13 13:40:51 sip02 opensips[3645]: ERROR:siptrace:parse_siptrace_id: invalid uri <mysql://dbSIPTraceUser:mo4Ec=i7LeecieBe@host/db_trace;table=sip_trace;>
Apr 13 13:40:51 sip02 opensips[3645]: ERROR:siptrace:parse_trace_id: failed to parse siptrace uri [mysql://dbSIPTraceUser:mo4Ec=i7LeecieBe@host/db_trace;table=sip_trace;]
Apr 13 13:40:51 sip02 opensips[3645]: CRITICAL:core:yyerror: parse error in config file /etc/opensips/includes/features/tracing/core.tracing.cfg, line 5, column 20-21: Parameter <trace_id> not found in module <siptrace> - can't set
Apr 13 13:40:51 sip02 opensips[3645]: CRITICAL:core:yyerror: parse error in config file /etc/opensips/includes/features/tracing/core.tracing.cfg, line 64, column 13-14: unknown command <sip_trace>, missing loadmodule?
Apr 13 13:40:51 sip02 opensips[3645]: ERROR:core:main: bad config file (2 errors)
Apr 13 13:40:51 sip02 opensips[3645]: NOTICE:core:main: Exiting....
Apr 13 13:40:51 sip02 systemd[1]: opensips.service: control process exited, code=exited status=255
Apr 13 13:40:51 sip02 systemd[1]: Failed to start OpenSIPS is a very fast and flexible SIP (RFC3261) server.

**Comment by ionutrazvanionita** [comment]
The syntax is:
[<id name>]uri=<mysql_uri>;table=<table_name>;
Looks like you don't put 'uri=' keyword
