### ISSUE TITLE
[clusterer] dialog:receive_prof_binary_packet: server with clusterer id X timeout

### ISSUE THREAD

**Issue by jarrodb** [OpenSIPS/opensips#849]
I am testing a new clusterer setup with two proxies replicating dialog profiles between the following errors are streaming in the log files:

`Apr  4 12:03:34 lab-proxy1 opensips[25891]: INFO:dialog:receive_prof_binary_packet: server with clusterer id 1 timeout`
`Apr  4 12:04:05 lab-proxy1 opensips[25891]: INFO:dialog:receive_prof_binary_packet: server with clusterer id 1 timeout`
`Apr  4 12:04:36 lab-proxy1 opensips[25889]: INFO:dialog:receive_prof_binary_packet: server with clusterer id 1 timeout`

After investigating, it appears the message is happening because `clusterer.c:375` in the `update_nodes_handler` function is comparing the timestamp from the last message for the node against the current time and determining if a timeout has occurred.  

This seems OK, but the problem is there are no active probing/ping checks going on between the nodes to verify connectivity that would update the node's timestamp and there is no data replicating between them because there is no traffic (this is a lab). 

Are the probe checks missing from the logic or am I missing the way to enable them?  Is this simply relying on actual replicated data to update timestamps?  If so, it seems the INFO message is inconsistent with it's intention.

Thanks for any pointers.

**Comment by jarrodb** [comment]
?

**Comment by bogdan-iancu** [comment]
@jarrodb , there are no explicit probes, as the in dialog replication scenario, the dialog module is periodically broadcasting the data to all the other nodes in the cluster. And these broadcasts do play the role of "probes" .

**Comment by jarrodb** [comment]
Do you think its good practice to report server timeouts when no traffic is occurring and therefore no data is passing?  (I'm only working with profiles)

**Comment by bogdan-iancu** [comment]
It is the same with the profiles - some broadcasting mechanism for the share profiles.

What is the usage scenario for clusterer her ?

**Comment by jarrodb** [comment]
It appears it only 'broadcasts' if there is live traffic... during stagnant times (and in a dev lab) there are no broadcasts happening so it reports timeouts every timeout which happens A LOT.

The scenario is replicating profiles for keeping concurrent call usage across proxies for various trunks.

**Comment by bogdan-iancu** [comment]
Makes sense. Just talked to @razvancrainea and for usrloc we will disable the timeout detection as it is a non-sense (the concept is broken in this case and anyhow there is nothing to be done inside the cluster if one usrloc node went down) .
@razvancrainea will follow up with a fix.
