### ISSUE TITLE
Segfault in t_hooks.c:209

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#856]
Compiled with F_malloc

version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 0546c94
main.c compiled on 14:23:20 Apr 12 2016 with gcc 4.8

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/sbin/opensips -P /var/run/opensips.pid -m 3072 -M 256 -u root -g roo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007fa355e6ee90 in run_trans_callbacks (type=type@entry=2, trans=0x7fa360426688, req=<optimized out>, rpl=rpl@entry=0x7fa41dd6fec8, code=<optimized out>) at t_hooks.c:209
        params = {req = 0x7fa365e8da20, rpl = 0x7fa41dd6fec8, code = 487, param = 0x7fa36c9741d8, extra1 = 0x0, extra2 = 0x0}
        cbp = 0x7fa36c9741c8
        backup = 0x843ab8 <global_avps>
        trans_backup = 0x7fa360426688
        __FUNCTION__ = "run_trans_callbacks"
#2  0x00007fa355e769b5 in t_reply_matching (p_msg=p_msg@entry=0x7fa41dd6fec8, p_branch=<optimized out>) at t_lookup.c:829
        p_cell = <optimized out>
        hash_index = <optimized out>
        entry_label = <optimized out>
        branch_id = <optimized out>
        hashi = <optimized out>
        branchi = <optimized out>
        p = <optimized out>
        hashl = <optimized out>
        branchl = <optimized out>
        scan_space = <optimized out>
        cseq = 0x7fa41dd6e910
        loopi = <optimized out>
        loopl = <optimized out>
        syni = <optimized out>
        synl = <optimized out>
        __FUNCTION__ = "t_reply_matching"
#3  0x00007fa355e77164 in t_check (p_msg=p_msg@entry=0x7fa41dd6fec8, param_branch=param_branch@entry=0x7ffd96aa62c0) at t_lookup.c:900
        local_branch = -1767218577
        __FUNCTION__ = "t_check"
#4  0x00007fa355e990ea in reply_received (p_msg=0x7fa41dd6fec8) at t_reply.c:1386
        msg_status = <optimized out>
        last_uac_status = <optimized out>
        branch = 0
        reply_status = <optimized out>
        timer = 140342851993288
        cancel_bitmap = 8800582
        uac = <optimized out>
        t = <optimized out>
        backup_list = <optimized out>
        has_reply_route = <optimized out>
        __FUNCTION__ = "reply_received"
#5  0x000000000043ebed in forward_reply (msg=msg@entry=0x7fa41dd6fec8) at forward.c:467
        new_buf = 0x0
        to = 0x0
        new_len = 0
        mod = 0x7fa417543508
        proto = <optimized out>
        id = 0
        send_sock = <optimized out>
        s = <optimized out>
        len = <optimized out>
        __FUNCTION__ = "forward_reply"
#6  0x00000000004958e5 in receive_msg (
    buf=0x864800 <buf> "SIP/2.0 487 Request terminated\r\nRecord-Route: <sip:10.0.2.74;lr;ftag=USN0HaKF7ae2a;did=5d7.11966e17>\r\nTo: \"19183961511\" <sip:19183961511@199.47.211.170>;tag=583F898F-570D69FE0002AEC9-437F7700\r\nFrom: <"..., len=<optimized out>,
    rcv_info=rcv_info@entry=0x7ffd96aa64a0, existing_context=existing_context@entry=0x0) at receive.c:257
        ctx = 0x7fa419945b60
        msg = 0x7fa41dd6fec8
        start = {tv_sec = 140339499951424, tv_usec = 140339499951424}
        rc = 3
        in_buff = {s = 0x864800 <buf> "SIP/2.0 487 Request terminated\r\nRecord-Route: <sip:10.0.2.74;lr;ftag=USN0HaKF7ae2a;did=5d7.11966e17>\r\nTo: \"19183961511\" <sip:19183961511@199.47.211.170>;tag=583F898F-570D69FE0002AEC9-437F7700\r\nFrom: <"...,
          len = 471}
        __FUNCTION__ = "receive_msg"
#7  0x00000000005b5b0d in udp_read_req (si=<optimized out>, bytes_read=<optimized out>) at net/proto_udp/proto_udp.c:190
        ri = {src_ip = {af = 2, len = 4, u = {addrl = {18446744070656229386, 18446744073709551615}, addr32 = {1241645066, 4294967295, 4294967295, 4294967295}, addr16 = {10, 18946, 65535, 65535, 65535, 65535, 65535, 65535},
              addr = "\n\000\002J", '\377' <repeats 12 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {1241645066, 0}, addr32 = {1241645066, 0, 0, 0}, addr16 = {10, 18946, 0, 0, 0, 0, 0, 0}, addr = "\n\000\002J", '\000' <repeats 11 times>}}, src_port = 5062,
          dst_port = 5060, proto = 1, proto_reserved1 = 0, proto_reserved2 = 0, src_su = {s = {sa_family = 2, sa_data = "\023\306\n\000\002J\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 50707, sin_addr = {s_addr = 1241645066},
              sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2, sin6_port = 50707, sin6_flowinfo = 1241645066, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0,
                    0}}}, sin6_scope_id = 2}}, bind_address = 0x7fa417601f28}
        len = <optimized out>
        buf = "SIP/2.0 487 Request terminated\r\nRecord-Route: <sip:10.0.2.74;lr;ftag=USN0HaKF7ae2a;did=5d7.11966e17>\r\nTo: \"19183961511\" <sip:19183961511@199.47.211.170>;tag=583F898F-570D69FE0002AEC9-437F7700\r\nFrom: <"...
        fromlen = 16
        p = <optimized out>
        msg = {s = 0x864800 <buf> "SIP/2.0 487 Request terminated\r\nRecord-Route: <sip:10.0.2.74;lr;ftag=USN0HaKF7ae2a;did=5d7.11966e17>\r\nTo: \"19183961511\" <sip:19183961511@199.47.211.170>;tag=583F898F-570D69FE0002AEC9-437F7700\r\nFrom: <"..., len = 471}
        __FUNCTION__ = "udp_read_req"
---Type <return> to continue, or q <return> to quit---
#8  0x00000000005a814a in handle_io (idx=<optimized out>, event_type=<optimized out>, fm=<optimized out>) at net/net_udp.c:259
        read = 391418616
        fm = <optimized out>
#9  io_wait_loop_epoll (h=<optimized out>, t=<optimized out>, repeat=<optimized out>) at net/../io_wait_loop.h:225
        ret = <optimized out>
        e = <optimized out>
        n = 1
        r = 0
#10 udp_rcv_loop (si=si@entry=0x7fa417601f28) at net/net_udp.c:308
        __FUNCTION__ = "udp_rcv_loop"
#11 0x00000000005a96aa in udp_start_processes (chd_rank=chd_rank@entry=0x827640 <chd_rank>, startup_done=startup_done@entry=0x7fa3570ce950) at net/net_udp.c:372
        si = 0x7fa417601f28
        load_p = 0x7fa3570ce970
        pid = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "udp_start_processes"
#12 0x0000000000419c15 in main_loop () at main.c:671
        startup_done = 0x7fa3570ce950
        chd_rank = 17
#13 main (argc=<optimized out>, argv=<optimized out>) at main.c:1252
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffd96aa7e36 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        options = 0x5cd708 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 592613384
        __FUNCTION__ = "main"

**Comment by bogdan-iancu** [comment]
This looks like a mem corruption and it may be a result of the ACC or DIALOG issues ( #855 or #858 ). I will close it and if there are any new crashed after fixing the mentioned issues, we can open a new investigation.
