### ISSUE TITLE
cross compile problem with json-c header

### ISSUE THREAD

**Issue by was4444** [OpenSIPS/opensips#857]
There's a fixed include path(``/usr/include/json-c`` or ``/usr/include/json``) for json headers in [Makefile](https://github.com/OpenSIPS/opensips/blob/master/Makefile#L64) of almost all OpenSIPS branches. 
That seems not that good for cross-compile.

And ``FREERADIUS`` feature depends on ``/usr/include/freeradius-client.h`` https://github.com/OpenSIPS/opensips/blob/master/Makefile#L36.

**Comment by razvancrainea** [comment]
I agree, it would probably be nicer if we could do something similar to the radius library. We will change this.

PS: not sure what's the problem with FREERADIUS, but if there are any, please open a different issue.

**Comment by was4444** [comment]
@razvancrainea, not familiar with ``FREERADIUS``, and the ``Makefile`` has changed a lot, that should be a mistake of mine.

I work with ``RHEL``, ``Ubuntu`` and embeded devices. The json-c header path are almost everywhere.

**Comment by ionutrazvanionita** [comment]
Hi @was4444 , try https://github.com/OpenSIPS/opensips/commit/6ce77bf7520c89b8f3fd6efeb22052c5f5d976b7. Now you can compile with JSONPATH=/your/path/to/json make to set your own path.

**Comment by was4444** [comment]
Thanks, @ionutrazvanionita, I am not in the office these days, but that should work.
