### ISSUE TITLE
Segfaults in ACC module

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#858]
version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 0546c94
main.c compiled on 10:51:20 Apr 13 2016 with gcc 4.8

core.3014
http://pastebin.com/WUCM3L4F

core.24427
http://pastebin.com/eBpCWzCr

core.24445
http://pastebin.com/MaPnkaFJ

core.25111
http://pastebin.com/JNXWDrpa

**Comment by ionutrazvanionita** [comment]
Hi @46labs,
Do you still have this problem after https://github.com/OpenSIPS/opensips/commit/92d20416568c23f58f378fd14b272d2b16d7518e?
