### ISSUE TITLE
Segfault in clusterer.c:1457

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#861]
version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 92d2041
main.c compiled on 10:18:53 Apr 15 2016 with gcc 4.8

Core was generated by `/usr/local/sbin/opensips -P /var/run/opensips.pid -m 2048 -M 256 -u root -g roo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f288642d9a7 in send_to (cluster_id=1, proto=7) at clusterer.c:1457
1457		lock_start_read(ref_lock);
(gdb) bt full
#0  0x00007f288642d9a7 in send_to (cluster_id=1, proto=7) at clusterer.c:1457
        value = <optimized out>
        send_buffer = {s = 0x7f290af064a8 "P4CK<", len = 60}
        ctime = 1460762532
        ok = -1
        __FUNCTION__ = "send_to"
#1  0x00007f2889c44e4d in dlg_replicate_profiles () at dlg_replication.c:775
No locals.
#2  repl_prof_remove (name=0x7f288a993268, value=value@entry=0x7f28932fc920) at dlg_replication.c:965
        module_name = {s = 0x7f2889c5b390 "dialog", len = 6}
        __FUNCTION__ = "repl_prof_remove"
#3  0x00007f2889c3356a in destroy_linkers (linker=0x0, is_replicated=<optimized out>) at dlg_profile.c:614
        entry = <optimized out>
        l = 0x7f28932fc920
        dest = <optimized out>
        __FUNCTION__ = "destroy_linkers"
#4  0x00007f2889c1ce1a in free_dlg_dlg (dlg=<optimized out>) at dlg_hash.c:186
No locals.
#5  destroy_dlg_table () at dlg_hash.c:270
No locals.
#6  0x00007f2889beaf63 in mod_destroy () at dialog.c:1010
No locals.
#7  0x00000000004d026d in destroy_modules () at sr_module.c:527
        t = 0x7f290aecbc58
        foo = 0x7f290aecbaf0
        __FUNCTION__ = "destroy_modules"
#8  0x00000000004449d1 in cleanup (show_status=show_status@entry=1) at main.c:318
        __FUNCTION__ = "cleanup"
#9  0x000000000044572c in handle_sigs () at main.c:520
        chld = 0
        chld_status = 139
        overall_status = 139
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#10 0x0000000000419cfc in main_loop () at main.c:704
        startup_done = <optimized out>
        chd_rank = 72
#11 main (argc=<optimized out>, argv=<optimized out>) at main.c:1252
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x7ffd1210be43 ""
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        options = 0x5d89c8 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 705982730
        __FUNCTION__ = "main"

**Comment by bogdan-iancu** [comment]
The crash happened during a shutdown. Is this shutdown the result of a normal opensips termination, or it is a result of opensips crash ?

**Comment by 46labs** [comment]
crash

**Comment by bogdan-iancu** [comment]
In this case I will discard this report - the shutdown after a crash degenerates in 90% in a second crash (of the attendant process which does the shutdown) as data is already corrupted in mem (due the original crash).
If there are crashes during normal shutdown, please open a new issue.
