### ISSUE TITLE
Multiple instances of rtpproxy and notify socket

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips#865]
I'm receiving a lot of messages such as below:

Apr 25 08:38:00 localhost rtpproxy[2272]: ERR:do_timeout_notification: failed to send timeout notification: Broken pipe

The notify sockets are correct and coming from the right address, but I can't see any answer to the tcp packets. There is no firewall or iptables enabled. 

T 172.10.1.103:39732 -> 172.10.1.102:7891 [AP]
3326.1318020753

T 172.10.1.103:39732 -> 172.10.1.102:7891 [AP]
3565.492631570

The list of sockets in in the database. 

+----+-----------------------+------------+--------+--------+
| id | rtpproxy_sock         | name       | set_id | active |
+----+-----------------------+------------+--------+--------+
|  1 | udp:172.10.1.103:7890 | RTP_PROXY1 |      1 |      1 |
|  3 | udp:172.10.1.103:7891 | RTP_PROXY1 |      1 |      1 |
|  4 | udp:172.10.1.103:7892 | RTP_PROXY1 |      1 |      1 |
| 12 | udp:172.10.1.104:7890 | RTP_PROXY2 |      1 |      1 |
| 13 | udp:172.10.1.104:7891 | RTP_PROXY2 |      1 |      1 |
| 14 | udp:172.10.1.104:7892 | RTP_PROXY2 |      1 |      1 |
+----+-----------------------+------------+--------+--------+

The port is open on the OpenSIPS Server. 

tcp        0      0 172.10.1.102:7891           172.10.1.104:33408          ESTABELECIDA20092/opensips
tcp        0      0 172.10.1.102:7891           172.10.1.103:40315          ESTABELECIDA20092/opensips
tcp        0      0 172.10.1.102:7891           172.10.1.103:40313          ESPERA_FIN2 -

The  notify socket is correct on the rtpproxy instances. 

OPTIONS="-l a.b.c.d -s udp:172.10.1.103:7890 -F -P -i -r /home/rtpproxy -m 10001 -M 20000 -n tcp:172.10.1.102:7891 -T 60 -W 60 -d WARN:LOG_LOCAL1 -L 65535"

but still broken pipe. 

It seems for me that some security mechanism on OpenSIPS is preventing the connections. Maybe the list in the database is not being accepted. Is it possible to turn off the security mechanims of the notifications (not accept from IPs not in the rtpproxy list)?

**Comment by razvancrainea** [comment]
Hi, Flavio!

Did you check OpenSIPS log? If the RTPProxy instance is denied by OpenSIPS, you should see that in the log, but I somehow doubt that's the case.
Can you make a pcap capture for the communication? I am asking because if OpenSIPS was indeed closing the connection, you should have at least seen a FIN TCP message from `172.10.1.102:7891` to `172.10.1.103`.
Also, can you make sure OpenSIPS is indeed listening on that IP and port (`netstat -tlpn | grep opensips`). And double check there are no typos in the parameters `modparam("rtpproxy", "rtpp_notify_socket", "tcp:172.10.1.102:7891")`.

Best regards,
Răzvan

**Comment by flaviogoncalves** [comment]
Hi Razvan, 

Indeed, there is no message. I have even changed in the source code the messages from DBUG to INFO, but no luck.  All the information is below. 

tcp        0      0 172.10.1.102:7891           0.0.0.0:*                   LISTEN      12763/opensips     

modparam("rtpproxy", "rtpp_notify_socket", "tcp:172.10.1.102:7891")

T 2016/05/18 18:25:54.236362 172.10.1.103:57366 -> 172.10.1.102:7891 [AP]
1747.1524433185
2508.335982104


T 2016/05/18 18:25:54.692015 172.10.1.104:35660 -> 172.10.1.102:7891 [AP]
1930.635540533


T 2016/05/18 18:25:55.240047 172.10.1.103:57366 -> 172.10.1.102:7891 [AP]
2008.1624360047


T 2016/05/18 18:25:55.240143 172.10.1.103:57366 -> 172.10.1.102:7891 [AP]
1342.1245742415
888.559615586
1526.442289321
2661.1852595274
992.2062549099
4081.488401396

[root@localhost opensips]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination      

[output.pcap.zip](https://github.com/OpenSIPS/opensips/files/271524/output.pcap.zip)

**Comment by razvancrainea** [comment]
Hi, Flavio!

OpenSIPS does not send anything back when it receives a timeout notification, and from the PCAP I see the messages are properly sent and the connection is not rejected. So the PCAP shows everything works all right. But I presume the dialogs are not changed, right? And if you change the debugs into INFO, you are not seeing any notification received by OpenSIPS?
Also, what version of OpenSIPS are you using?

Best regards,
Răzvan

**Comment by flaviogoncalves** [comment]
The message is still in rtpproxy, but the disconnect is actually working. I thought as the communication is TCP an ACK should be sent as an answer.

**Comment by razvancrainea** [comment]
Hi, Flavio!

Just to be sure we have everything on the table, are you tracing the communication using ngrep or tcpdump? I am asking because ngrep does not capture the entire TCP flow (in this case, it might miss the ACK).
Regarding the broken pipe issue, it looks like there is indeed a communication problem and the connection is closed every time. However I doubt events are missing. If you could try to capture using tcpdump in both directions, that would be great.

Thanks,
Răzvan

**Comment by flaviogoncalves** [comment]
Just updating, whenever I have more than one rtpproxy in the same server, the notifications do not work.

**Comment by razvancrainea** [comment]
Hi, Flavio!

If you could take the TCP trace I was mentioning about, it would be great. Otherwise I will try to setup the two rtpproxy myself to see what's happening.

**Comment by flaviogoncalves** [comment]
This is a tcpdump od the notification port.
 
[rtpproxy.pcap (1).tar.gz](https://github.com/OpenSIPS/opensips/files/1004926/rtpproxy.pcap.1.tar.gz)

**Comment by razvancrainea** [comment]
Hi, Flavio!

This trace might be really helpful. What version of opensips are you running?

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
Actually I don't think the version matters - are you running multiple servers of rtpproxy on the same machine?

**Comment by flaviogoncalves** [comment]
Yes, and this is exactly what causes the problem. Multiple servers in
different machines seems to work fine.

Flavio E. Goncalves
V.Office Redes e Telecomunicações Ltda.
Fone 48 33328590
Skype:flaviogoncalves1
Linkedin: www.linkedin.com/in/flavioegoncalves


2017-05-17 4:43 GMT-03:00 Răzvan Crainea <notifications@github.com>:

**Comment by razvancrainea** [comment]
Figured out the issue, thanks for reporting it and providing all the necessary debugs :).
Working on a fix.

**Comment by flaviogoncalves** [comment]
I will apply and test in OpenSIPS 1.8 and 1.11

Thank you,

Flavio E. Goncalves
V.Office Redes e Telecomunicações Ltda.
Fone 48 33328590
Skype:flaviogoncalves1
Linkedin: www.linkedin.com/in/flavioegoncalves


2017-05-17 5:48 GMT-03:00 Răzvan Crainea <notifications@github.com>:
