### ISSUE TITLE
tls: error on shutdown

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#866]
On shutdown, opensips is printig this error in logs:
ERROR:proto_tls:tls_conn_shutdown: something wrong in SSL: 5, 32, Broken pipe

It is 100% reproducible:
1. start opensips
2. make a tls call
3. stop opensips

I can reproduce this in both 2.1.x and 2.1.x.

**Comment by ionutrazvanionita** [comment]
Hi @ovidiusas , try https://github.com/OpenSIPS/opensips/commit/bdcee39ebf04f8a74b926dc6e6c311487d3ef601
