### ISSUE TITLE
tls: errors during tls calls

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#867]
First call reported the following errors:
```
ERROR:proto_tls:tls_blocking_write: TLS send timeout (100)
ERROR:proto_tls:proto_tls_send: failed to send
ERROR:tm:msg_send: send() for proto 3 failed
ERROR:tm:t_forward_nonack: sending request failed
ERROR:tm:w_t_relay: t_forward_nonack failed
```
Second call reported this errors:
```
CRITICAL:core:io_watch_add: #012>>> [TCP_main] BUG trying to overwrite entry 27 in the hash(27, 19, 0x7f7b4c1dd1d0,1) with (27, 19, 0x7f7b4c1f65b8,1)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
ERROR:proto_tls:tls_blocking_write: TLS send timeout (100)
ERROR:proto_tls:proto_tls_send: failed to send
ERROR:tm:msg_send: send() for proto 3 failed
ERROR:tm:t_forward_nonack: sending request failed
ERROR:tm:w_t_relay: t_forward_nonack failed
```

**Comment by ovidiusas** [comment]
This is happening while trying to send a call over tls to a destination that doesn't listen for tls connections (hence the initial errors).
What's troubling is the CRITICAL error on the second call. Sometimes it takes a few calls to trigger the CRITICAL error.
To reproduce this, try to relay calls over tls (maybe even tcp) to a server that is listening only on udp.

**Comment by bogdan-iancu** [comment]
Hi @ovidiusas , The first logs do not show any connect errors, but only send/write errors. So, somehow, the connection is accepted (or ?).
So, in your setup, opensipsA tries to opens and write over a TLS connection, to a destination (opensipsB) were only TCP is listen. Let's say opensipsB listens on tcp:127.0.0.1:5060 and opensipsA tries to connect via TLS to this 127.0.0.1:5060 ? is this the case ?

**Comment by bogdan-iancu** [comment]
BTW, what opensips version is this ?

**Comment by ovidiusas** [comment]
This is opensips 2.2 and in the scenario that you described, is like opensipsA tries to open a connection to opensipsB on port 5061, but opensipsB doesn't listen at all on 5061.

**Comment by bogdan-iancu** [comment]
@ovidiusas , there is something inconsistent here - the logs show an error in tls_blocking_write() - this function is called from proto_tls_send() after a connection is available (either already found, either freshly created). But if OpenSIPSB does not listen on 5061, how comes that OpenSIPSA "has" a connection towards OpenSIPSB (port 5061) ???
As per logs, definitely there was no attempt to open a new one in proto_tls_send() (as we would see some connect errors); this leave us with the options that a existing connection was found...somehow.... Can you check it with netstat ?

**Comment by ovidiusas** [comment]
I found the old logs and yes, the connection is there (in my previous post I was wrong).
So OpenSIPA is trying to relay a call over tls towards a plain tcp connection on OpenSIPSB.
Sorry for the confusion.

**Comment by bogdan-iancu** [comment]
Even if it sounds strange, that makes sense and it is consistent with some recently discovered issues in the management of the TCP conns, where, due bogus port aliases and improper tcp conn lookup (without proto constraints) you may end up in using wrong TCP conn (TCP / TLS) for sending the packages.
Liviu just commited the fixes with some comprehensive descriptions. 
Updating from repo should solve the problem.
