### ISSUE TITLE
async: db (mysql) connection lost during mysql query

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#868]
While doing an async mysql query, the following error occurred:
````
ERROR:db_mysql:db_mysql_async_raw_resume: error [2013, HY000]: Lost connection to MySQL server during query
ERROR:avpops:resume_async_dbquery: async query returned error
```
On the second call, we got:
````
INFO:db_mysql:switch_state_to_disconnected: disconnect event for 0x7f7e7dbf2ba0
INFO:db_mysql:reset_all_statements: reseting all statements on connection: (0x7f7e7dbb1150) 0x7f7e7dbf2ba0
INFO:db_mysql:connect_with_retry: re-connected successful for 0x7f7e7dbf2ba0
````

When the db connection is lost, opensips should try to re-connect before giving up.

**Comment by 46labs** [comment]
Ovi, did you have a mysql event? Do you have your mysql max connections properly tuned? Any mysql tuning that could have caused this to happen (ie thread caching, etc).

**Comment by ovidiusas** [comment]
We are actively investigating the mysql, but the issue here is that the max_db_retries param has effect for sync queries, but not for async queries.

**Comment by bogdan-iancu** [comment]
@ovidiusas , do you a setup to reproduce this error ?

**Comment by ovidiusas** [comment]
I have a setup which occasionally exhibits the issue.

**Comment by bogdan-iancu** [comment]
@ovidiusas , in non-async ops, if the "connection error" is reported when firing the DB op, OpenSIPS will reconnect and re-try the connection - this works perfectly, as there the op is done in one step (pushing the query and getting back the reply from DB are masked behind the same lib function).
In async mode, the DB ops are done in 2 steps. First sending/pushing the query to DB server - and if a "connection error" is reported here, OpenSIPS will retry this step. Second step (after the async waiting) is to get the reply from DB server - if a "connection error" is reported at this step, there is not much you can do about - as the connection is down, there is no way to recover the query data by re-opening a new conn. So attempting to reconnect at this step is useless (the query was executed by DB server, but the response data was lost on the way).  Also it is impossible to retake the whole the query( both steps) as the data required to build the query again is not available any more at this step (at resume time).
Shortly, a reconnect a resume time does not help in recovering the query, so the query must be considered at failed.
To be honest, I do not see anything to be done in OpenSIPS side - it is a normal communication fault with the DB - maybe you should investigate why the connection is lost during the query.

**Comment by ovidiusas** [comment]
The way I 'fixed' this was to make the route re-entrant on error. This way, on the second try, the connection is detected as broken and re-established.
We can close this one then ...

**Comment by bogdan-iancu** [comment]
Yes, your "fix"is consistent with my "story" on how this works for async. Closing....
