### ISSUE TITLE
core: concatenating variables with a <null> value results in an empty string

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#870]
Test:
````
$var(a) = "a";
$var(b) = null;
$var(c) = $var(a) + ":" + $var(b);
xlog("L_NOTICE", "$$var(a)=[$var(a)] $$var(b)=[$var(b)] $$var(c)=[$var(c)]\n");
````
Output:
````
$var(a)=[a] $var(b)=[<null>] $var(c)=[]
````
The result should be:
````
$var(a)=[a] $var(b)=[<null>] $var(c)=[a:]
````

**Comment by liviuchircu** [comment]
Small correction here: shouldn't the expected output be:

`$var(a)=[a] $var(b)=[<null>] $var(c)=[a:<null>]`

**Comment by ovidiusas** [comment]
Yes, according to how it is implemented now, the output should have the '<null>' marker.

**Comment by liviuchircu** [comment]
I looked through the code, and it's a bit of a mess in terms of consistency. For example, if we are to switch the variables:

```
$var(c) = $var(b) + ":" + $var(a);
xlog("L_NOTICE", "$$var(a)=[$var(a)] $$var(b)=[$var(b)] $$var(c)=[$var(c)]\n");
```

then it will print exactly what you actually expected, omitting the "<null>" marker:

`$var(a)=[a] $var(b)=[<null>] $var(c)=[:a]`

I think the best approach is to maximize backwards compatibility if doing the backport, yet fix all these consistency problems as much as possible in `2.2+`.
