### ISSUE TITLE
OpenSIPS 2.2 Nathelper and WSS keepalive messages

### ISSUE THREAD

**Issue by yuri2000** [OpenSIPS/opensips#875]
Gentlemen,
It looks that something is missing in the Nathelper module for OpenSIPS 2.2 when it comes to WSS keepalives.
With modparam("nathelper", "natping_tcp", 1), modparam("nathelper", "ping_nated_only", 0) and a default pinging method (OPTIONS) the log shows these errors:
 /usr/sbin/opensips[27233]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 72
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Upgrade header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Connection header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Origin header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Sec-WebSocket-Key header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Sec-WebSocket-Version header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_parse_req_handshake: Sec-WebSocket-Protocol header not present!
 /usr/sbin/opensips[27201]: ERROR:proto_ws:ws_read_req: cannot complete WebSocket handshake

With the same modparams + modparam("nathelper", "sipping_method", "INFO") the errors are as follow:
 /usr/sbin/opensips[27510]: INFO:core:init_sock_keepalive: TCP keepalive enabled on socket 72
 /usr/sbin/opensips[27468]: ERROR:proto_ws:ws_parse_req_handshake: Invalid HTTP version: 1.0
 /usr/sbin/opensips[27468]: ERROR:proto_ws:ws_read_req: cannot complete WebSocket handshake

Please advise.
Thank you,
Yuri

**Comment by razvancrainea** [comment]
Just committed a fix that might prevent this.
Can you also make a tcpdump trace to see what messages are exchanged between OpenSIPS and the client?

Best regards,
Răzvan
