### ISSUE TITLE
dispatcher: memory leak

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#876]
When dispatching over multiple set ids, we have a memory leak in ds_fixups.c: set_list_from_string(197)
Script example:
````
$var(setid) = "1,2,3";
$var(algo) = "4,4,4";
$var(flags) = "fM9,fM9,fM9";
ds_select_domain("$var(setid)", "$var(algo)", "$var(flags)")
````

**Comment by ionutrazvanionita** [comment]
Hi Ovidiu,

     Can you please try this patch and tell me if it works? Indeed there 
was a double allocation
bug there.

Ionut Ionita
OpenSIPS Developer

**Comment by ovidiusas** [comment]
The patch seems to be working ok.

Thanks,
Ovidiu

**Comment by ionutrazvanionita** [comment]
Great. I pushed the patch to github.

Regards,

Ionut Ionita
OpenSIPS Developer
