### ISSUE TITLE
opensips-xmlrpc-module package at atp.opensips.org depends on libxmlrpc-c3 but should now depend on libxmlrpc-core-c3

### ISSUE THREAD

**Issue by AlanBell** [OpenSIPS/opensips#88]
The package name has changed and there is a bit of a bug in the way it was renamed, which means xmlrpc support package isn't installable on debian/ubuntu at the moment. 
I have filed a bug on the ubuntu side, libxmlrpc-core-c3 should provide libxmlrpc-c3 so it should be a backwards compatible name change, however the opensips package should be updated to depend on the new package name.
https://bugs.launchpad.net/ubuntu/+source/xmlrpc-c/+bug/1232015

**Comment by ovidiusas** [comment]
The mi_xmlrpc module was replaced by mi_xmlrpc_ng which doesn't depend on the libxmlrpc.
