### ISSUE TITLE
how to make resume invite on opensips

### ISSUE THREAD

**Issue by pntuan** [OpenSIPS/opensips#883]
I cached invite packages from caller when callee offline on redis-cache, push notification to wake up callee and resend to callee. I don't know how to opensips know package (Trying, Ringing,... ) from callee and forward to calller.

Thanks for your help.

**Comment by bogdan-iancu** [comment]
@pntuan , this tracker is for reporting bugs/error and so, not for asking for help or advices. For such purposes, please consider using the " OpenSIPS Users" mailing list: http://lists.opensips.org/cgi-bin/mailman/admin/users
