### ISSUE TITLE
mi_datagram line too long

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#893]
I think I am hitting the UDP payload limit for the mi_datagram module.
ERROR:mi_datagram:mi_datagram_server: failed to build the response 
ERROR:mi_datagram:mi_datagram_recur_flush_tree: failed to write -line too long!!!

Will it work if I work with an UNIX socket?

Could you implement a TCP listener for this to allow for larger answers? As I would like to implement this with polling over the network and not have local scripts talking to the UNIX socket.

**Comment by bogdan-iancu** [comment]
The buffer used in mi_datagram is limited to 65457 bytes and it is related to the datagram size (the size in the datagram packing is on 16 bits). It is not relevant if the datagram is AF_INET of AF_LOCAL.

If you need long data, use a stream oriented MI backedn.

**Comment by hydrosine** [comment]
are the mi_http and mi_json stream oriented?

**Comment by hydrosine** [comment]
Thanks, will test with those.
