### ISSUE TITLE
Clusterer module & Presence server cluster

### ISSUE THREAD

**Issue by goharahmed** [OpenSIPS/opensips#894]
Just a feature request. Is there a possibility of using clusterer module to share presence related data among a group of servers  !

Sharing Dialog states, and (later in future) user location entries among OpenSIPs boxes should have this capability to trigger NOTIFY/PUBLISH to the end users via the Edge/SBC node. 
![design](https://cloud.githubusercontent.com/assets/10055038/15752917/57f40eae-28be-11e6-827b-109e206e3bab.jpg)

Any recommendations on alternative approach to achieve the same !

Regards,
Gohar

**Comment by bogdan-iancu** [comment]
Hi @goharahmed , you should try using a sharing all the presence via DB . See http://www.opensips.org/html/docs/modules/2.2.x/presence.html#id293649

In this way, the servers can share data via a common SQL DB.

**Comment by goharahmed** [comment]
Hi again, 
Though I still think that this could be a useful feature without the need to share a DB between servers. However, I no longer require this anymore. If you like to close this ticket , please go-ahead.

Thanks for your amazing project and team effort. 

Gohar

**Comment by bogdan-iancu** [comment]
Presence clustering is now available starting with OpenSIPS 2.4

**Comment by goharprimo** [comment]
@bogdan-iancu Thankyou , I'll get this tested. Thanks for your amazing work.

**Comment by goharahmed** [comment]
@bogdan-iancu Thankyou, I'll get this one tested and take notes. Thankyou and whole team for amazing work.
