### ISSUE TITLE
Opensips Crashes when primary member of  mongodb replica set goes down .

### ISSUE THREAD

**Issue by sasmita11** [OpenSIPS/opensips#895]
Step to reproduce 

1st problem 
-   Deploy a replica set with three member . Primary , Secondary and Arbitrary .
-   I just stopped the primary member , in some millisecond my secondary member become primary .
-   But in opensips doesnt crashes , but the connection dies and no data get stored in data base for around 2/3min . Then the connection recover .  

2nd Problem 
    - After the above step , when I recover the primary server , till the time secondary became primary . Again for 2/3min opensips loss connection with mongodb .

3rd Problem
    - Now lets everything is working good . Just kill the Primary mongodb server and instantly place a call , then opensips crashes .

4th problem 
    -When everything going fine , Just make shut down the mongodb primary member machine and instantly place a call . Opensips will get crash . 
- Sometime , by just restarting the machine also opensips crashes .

This is easily reproducible . So follow any of the step to reproduce the issue .

Please let me know whenever the error get fixed .

Thanks 
Sasmita

**Comment by razvancrainea** [comment]
This has been sorted out in 2.4.
