### ISSUE TITLE
when a user become online , it is all time online in status 

### ISSUE THREAD

**Issue by behesht** [OpenSIPS/opensips#896]
hi 
when i login a user , the system change status from offline to online , after i logout from sip softphone, it is still online and not  back to offline position 
even in command prompt , or even when reset system , still users are online status
any help?

**Comment by bogdan-iancu** [comment]
@behesht , you talk about the registration status ?

**Comment by behesht** [comment]
yes

**Comment by bogdan-iancu** [comment]
and are you 100% sure your sip phone does send an un-REGISTER request when you go offline ? As that us the only way  for a registration to change.

**Comment by bogdan-iancu** [comment]
any update here ?
