### ISSUE TITLE
cpu is 100%

### ISSUE THREAD

**Issue by behesht** [OpenSIPS/opensips#898]
hi 
i installed opensips on raspberry pi , the problem is when the opensips want to load , it stop and the process hang on 100%
please look attachment
the opensips version is 2.2 lts
any help ?
![untitled](https://cloud.githubusercontent.com/assets/1504126/15870682/52ddeb1e-2d06-11e6-813b-582dcdd23fcc.jpg)

**Comment by bogdan-iancu** [comment]
Please post the output of "opensips -V". Also could you check with "ps" to see how many opensips processes you have?

**Comment by behesht** [comment]
hi 
thanks for your quick answer

version: opensips 2.2.0 (arm6/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, USE_SYSV_SEM
MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 18:33:49 Jun  7 2016 with gcc 4.9.2

please help me to solve this issue

**Comment by behesht** [comment]
my exact problem is , when the compile step finished successfully , and i want to run opensips with command like opensips . or /etc/init.d/opensips start , it will not load , and the opensips.pid in htop become 100% , and system completely crash ,
i use rasbian jessi latest version 
and raspberry bi 3 
,same installation on the server or vm , work fine without problem
now i think i tell a brief history about my issue

**Comment by bogdan-iancu** [comment]
I see opensips compiles with SYSTEM V locking support. Try to change that to POSIX or PTHREAD support - see the corresponding flags in Makefile.conf (be sure to use only on flag for locking support). Recompile and try again.

**Comment by behesht** [comment]
it works well 
thank you very much

**Comment by bogdan-iancu** [comment]
Hi @behesht , which locking support did the trick for you ?

**Comment by behesht** [comment]
hi
POSIX

**Comment by bogdan-iancu** [comment]
@behesht , it turned out that the root problem is the detection of the arch (arm6 in your case). I fixed the Makefile to detect and use the FAST locking support if arm6 is detected (similar to arm).
Please update from GIT and remove the DUSE_POSIX_SEM from your Makefile.conf ; now the makefile will detect arm6 and automatically use the FAST locking.
Let me know if this works for you

**Comment by behesht** [comment]
i get this error



root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../locking.h:65,
from: can't read /var/mail/mem/../locking.h:65,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../statistics.h:144,
from: can't read /var/mail/mem/../statistics.h:144,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/shm_mem.h:30,
from: can't read /var/mail/mem/shm_mem.h:30,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from blacklists.c:35:
from: can't read /var/mail/blacklists.c:35:
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:176:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:176:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:287:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:287:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# In file included from mem/../lock_ops.h:76:0,
-bash: In: command not found
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../locking.h:65,
from: can't read /var/mail/mem/../locking.h:65,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../statistics.h:144,
from: can't read /var/mail/mem/../statistics.h:144,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/shm_mem.h:30,
from: can't read /var/mail/mem/shm_mem.h:30,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from daemonize.c:57:
from: can't read /var/mail/daemonize.c:57:
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:176:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:176:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:287:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:287:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# In file included from lock_ops.h:76:0,
-bash: In: command not found
root@raspberrypi:/usr/local/src/opensips_2_2#                  from locking.h:65,
from: can't read /var/mail/locking.h:65,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from statistics.h:144,
from: can't read /var/mail/statistics.h:144,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from sr_module.h:49,
from: can't read /var/mail/sr_module.h:49,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from ut.h:37,
from: can't read /var/mail/ut.h:37,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from transformations.c:35:
from: can't read /var/mail/transformations.c:35:
root@raspberrypi:/usr/local/src/opensips_2_2# fastlock.h:176:2: error: #error "unknown architecture"
-bash: fastlock.h:176:2:: command not found
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# fastlock.h:287:2: error: #error "unknown architecture"
-bash: fastlock.h:287:2:: command not found
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# In file included from mem/../lock_ops.h:76:0,
-bash: In: command not found
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../locking.h:65,
from: can't read /var/mail/mem/../locking.h:65,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/../statistics.h:144,
from: can't read /var/mail/mem/../statistics.h:144,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from mem/shm_mem.h:30,
from: can't read /var/mail/mem/shm_mem.h:30,
root@raspberrypi:/usr/local/src/opensips_2_2#                  from pt.c:28:
from: can't read /var/mail/pt.c:28:
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:176:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:176:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# mem/../fastlock.h:287:2: error: #error "unknown architecture"
-bash: mem/../fastlock.h:287:2:: No such file or directory
root@raspberrypi:/usr/local/src/opensips_2_2#  #error "unknown architecture"
root@raspberrypi:/usr/local/src/opensips_2_2#   ^
-bash: ^: command not found
root@raspberrypi:/usr/local/src/opensips_2_2# ^Cmake: *** Deleting file 'pt.d'
-bash: :s^Cmake: *** Deleting file 'pt.d': substitution failed

**Comment by bogdan-iancu** [comment]
@behesht , can i get access to the machine to get it fixed for good ?
