### ISSUE TITLE
Opensip SIPREQUEST  is not relaying via WSS 

### ISSUE THREAD

**Issue by varghesepaul** [OpenSIPS/opensips#899]
Hi Team,

We are facing issue while relaying the SIP request to webclient via WSS protocol. We are able to establish the call from webclient and the SIP request BYE from opensip is not relaying to webclient. 

Opensip Version :  2.2 

My call setup : Opensip is acting as a WSS loadbalancer for asterisk server. Webclients are registering to opensips and audio is handling in Asterisk. 

BYE sips:paultest@106.51.64.135:44532;rtcweb-breaker=no;click2call=no;transport=wss SIP/2.0
Via: SIP/2.0/UDP 10.201.17.8:5060;branch=z9hG4bK1aa88db5;rport
Route: <sip:10.201.17.165;r2=on;lr;ftag=w7bSidOOTH70tov8v4Ha;did=2f5.069531f5>,<sip:10.201.17.164:8080;transport=wss;r2=on;lr;ftag=w7bSidOOTH70tov8v4Ha;did=2f5.069531f5>
Max-Forwards: 70
From: <sip:18999990001@paultest.voip.com>;tag=as11228ac4
To: "paultest"<sip:paultest@paultest.voip.com>;tag=w7bSidOOTH70tov8v4Ha
Call-ID: 98e420b5-ec3e-f17a-e6cf-a4ede1560063
CSeq: 102 BYE
User-Agent: paultest
X-Asterisk-HangupCause: Normal Clearing
X-Asterisk-HangupCauseCode: 16
Content-Length: 0

SIP/2.0 476 Unresolvable destination (476/TM)
Via: SIP/2.0/UDP 10.201.17.8:5060;received=10.201.17.8;branch=z9hG4bK1aa88db5;rport=5060
From: <sip:18999990001@paultest.voip.com>;tag=as11228ac4
To: "paultest"<sip:paultest@paultest.voip.com>;tag=w7bSidOOTH70tov8v4Ha
Call-ID: 98e420b5-ec3e-f17a-e6cf-a4ede1560063
CSeq: 102 BYE
Server: OpenSIPS (2.2.0-rc1 (x86_64/linux))
Content-Length: 0

Opensip Console Error :  ERROR:tm:uri2proxy: bad transport for sips uri: 6
                             ERROR:tm:t_forward_nonack: failure to add branches

 We can see that the BYE is relaying properly if we are using **WS**. So there is some issue with **WSS** protocol relay and i am hopping this will be a BUG. 

I am attaching both asterisk and opensips log for the reference. Can you please check and let me know what might be the issue ?.

[opensip.txt](https://github.com/OpenSIPS/opensips/files/304096/opensip.txt)
[asterisk.txt](https://github.com/OpenSIPS/opensips/files/304095/asterisk.txt)

**Comment by bogdan-iancu** [comment]
Hi @varghesepaul, thank you for the report. I just pushed a fix on trunk and 2.2 GIT repos. Indeed, the issue was related to having you client using SIPS in schema (instead of SIP) - and OpenSIPS was not considering WSS as a secure protocol, compatible with SIPS schema.

**Comment by varghesepaul** [comment]
Thanks @bogdan-iancu . I tested the new code and it is working fine.
