### ISSUE TITLE
Topology Hiding No Match

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#901]
Hello

On OpenSIPs 2.1 I am useing topology hiding. I found out that topology_hiding_match does not match on CANCEL

My Script

if (has_totag())
        {

                if(topology_hiding_match())
                {
                        route(RELAY);
                        exit;
                }
                xlog("[$ci] Topology Hiding No Match !!!!");

}

My Log

Jun  1 06:25:34 SIP-PROXY01 /sbin/opensips[18358]: [SBCPI_V11XWVBbRl1UXhAGEVsSBlJRX11bUwVCXltcQQFCWEsiUVJcQF9RV1pYVFxcUEA-] [1
72.17.253.4] Call Canceled - Cancel sip:xxxxx@172.17.253.4 -> sip:xxxxxx@172.17.253.8

Jun  1 06:25:34 SIP-PROXY01 /sbin/opensips[18363]: [SBCPI_V11XWVBbRl1UXhAGEVsSBlJRX11bUwVCXltcQQFCWEsiUVJcQF9RV1pYVFxcUEA-] Topology Hiding No Match !!!!

Is that normal?

**Comment by bogdan-iancu** [comment]
Hi @apsaras , as you can see, the "TH no match" logs is not related to the CANCEL - there are different pids in the too logs, so they come from different processes. 
Also, CANCEL do not have TO tag, so it is impossible for the cancel to get to the  topology_hiding_match().
I suspect you do something wrong when comes to the handling of the cancel in your script.

**Comment by apsaras** [comment]
I have no issue with CANCEL handling. I am just curious if the CANCEL should be matched.

Thank you for your reply
