### ISSUE TITLE
CRITICAL:acc:dlg_free_acc_mask: on restart 2.2.0

### ISSUE THREAD

**Issue by gcuppers** [OpenSIPS/opensips#906]
I am using opensips 2.2.0 with dialog an topology_hiding.
I have the acc module working with postgresql and radius.
A lot of db_extra and aaa_extra args, all defined as xxx=$dlg_val(xxx) though.
Everything working fine as expected.

Every restart I get this error(s). Apparently one per ongoing call and all CDRs of ongoing calls are lost.
Jun 14 17:48:46 localhost <B0><F1><98>^A[36723]: CRITICAL:acc:dlg_free_acc_mask: #012>>> More substitutions than additions in acc mask!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

Please tell me how I can help to solve this issue.

Regards,

Guillermo

**Comment by ionutrazvanionita** [comment]
Hi @gcuppers ,

   Can you tell me if you get this error when the opensips instance is shut down or when the new instance starts? I tried your scenario and i get it when i kill opensips instance.

**Comment by ionutrazvanionita** [comment]
Fixed with https://github.com/OpenSIPS/opensips/commit/ef9f0ff074f3461c51eddf2c21df171e25819b5b(https://github.com/OpenSIPS/opensips/commit/a0cf37a1ab919a82f6bcc4184ac1b689240a092f for 2.2 branch). Please confirm that is working!

**Comment by gcuppers** [comment]
Hello Ionut,

Thank you very much for your answer. It seems that the error happens on shutdown.
I tried your fix and the errors vanished.
However after restart I get the following errors:
Jun 15 12:56:21 localhost opensips[42109]: ERROR:acc:prebuild_extra_arr: cannot fetch core string value
Jun 15 12:56:21 localhost opensips[42109]: ERROR:acc:acc_log_cdrs: cannot copy extra arguments
Jun 15 12:56:21 localhost opensips[42109]: ERROR:acc:acc_dlg_callback: Cannot log values

Always those 3 together. And the CDR is lost.

**Comment by gcuppers** [comment]
Correcting myself. Not all CDRs are lost. It is recovering data correctly of about half of the ongoing calls. I am trying to find out what makes some calls be recovered and what makes them go lost.

**Comment by ionutrazvanionita** [comment]
@gcuppers try applying this patch and please paste here all logs for only callid. The log message

`ERROR:acc:prebuild_extra_arr: cannot fetch core string value`

will now look like 

`ERROR:acc:prebuild_extra_arr: cannot fetch core string value! callid <callid_value>!`

[acc_debug.zip](https://github.com/OpenSIPS/opensips/files/320106/acc_debug.zip)

**Comment by gcuppers** [comment]
Actually I already found more information and a solution.
When calling do_accounting("aaa|db", "cdr|failed"); after restart I get:
Jun 16 10:43:25 localhost opensips[55672]: DBG:dialog:fetch_dlg_value: looking for <accX_core>
Jun 16 10:43:25 localhost opensips[55672]: DBG:dialog:fetch_dlg_value: var found-> <#006>!
Jun 16 10:43:25 localhost opensips[55672]: DBG:dialog:fetch_dlg_value: looking for <accX_log>
Jun 16 10:43:25 localhost opensips[55672]: DBG:dialog:fetch_dlg_value: var NOT found!
Jun 16 10:43:25 localhost opensips[55672]: ERROR:acc:prebuild_extra_arr: cannot fetch core string value
Jun 16 10:43:25 localhost opensips[55672]: ERROR:acc:acc_log_cdrs: cannot copy extra arguments
Jun 16 10:43:25 localhost opensips[55672]: ERROR:acc:acc_dlg_callback: Cannot log values

When calling do_accounting("log|aaa|db", "cdr|failed"); after restart it is able to find accX_log and everything works fine:
Jun 16 16:10:40 localhost opensips[50408]: DBG:dialog:new_dlg_val: inserting <accX_core>=<#006>
Jun 16 16:10:40 localhost opensips[50408]: DBG:dialog:new_dlg_val: inserting <accX_leg>=<>
Jun 16 16:10:40 localhost opensips[50408]: DBG:dialog:new_dlg_val: inserting <accX_log>=<>
Jun 16 16:10:40 localhost opensips[50408]: DBG:dialog:fetch_dlg_value: looking for <cdr_seq_no>
etc, etc.

I hope this helps.

**Comment by ionutrazvanionita** [comment]
Hello again @gcuppers , 

   Can you send me your script privately? I looked through the code, tried hardly to replicate the bug but had no success.

**Comment by ionutrazvanionita** [comment]
Hello @gcuppers,  from https://github.com/OpenSIPS/opensips/commit/fb761edea1cac8881dfb84143ee641a6cdf8e37b the issue should be fixed. Thank you very much for your help!
