### ISSUE TITLE
new tarballs are not in gzip format

### ISSUE THREAD

**Issue by di-shi** [OpenSIPS/opensips#907]
Reported by gzip 1.5-8.el7 on CnetOS 7, all new tarballs, http://opensips.org/pub/opensips/1.11.7/opensips-1.11.7.tar.gz, http://opensips.org/pub/opensips/2.1.3/opensips-2.1.3.tar.gz and http://opensips.org/pub/opensips/2.2.0/opensips-2.2.0.tar.gz, are not in gzip format that is suggested by their names.

**Comment by rgagnon24** [comment]
I can confirm you cannot open the .gz files with 7zip on windows either.  It reports the files are not in .gz format as well

**Comment by di-shi** [comment]
Additional info.
opensips-1.11.7.tar.gz	15-Jun-2016 06:09 	4.3M
opensips-2.1.3.tar.gz	15-Jun-2016 06:09 	4.6M
opensips-2.2.0.tar.gz	15-Jun-2016 06:09 	4.8M

**Comment by rgagnon24** [comment]
I can confirm you cannot open the .gz files with 7zip on windows either. It
reports the files are not in .gz format as well.

They are not .tar, .zip, nor .bz2 either...

weird though that the first few characters of the 1.11.7 file contains
"200000\n"--- looks like someone might have left a debug print message in
the packaging system?

If you remove the "200000\n" from the beginning of the file, then you can
unzip/untar the files.

**Comment by razvancrainea** [comment]
Hey guys!

The tarballs are created by a script that downloads them directly from github using something like:

https://github.com/OpenSIPS/opensips/archive/1.11.7.tar.gz

It looks like for some reason github was dumping bad archives (not sure why yet). I first ran the tarball script again and it got the proper archive for 2.2.0, but not for 1.11.7 and 2.1.3. When I ran it the second time, it downloaded the proper archive. Now all of them are fixed.

Not sure what happened, but I will dig a bit more to see if this is an issue with gitlab or a bug :).

Thanks for reporting it.

Best regards,
Răzvan

**Comment by razvancrainea** [comment]
If the issue does not persist, please close the ticket.

**Comment by di-shi** [comment]
Thanks for the quick fix!

**Comment by razvancrainea** [comment]
This seems to keep happen. I will look into a different solution to deploy tarballs.

**Comment by razvancrainea** [comment]
Updated the latest tarballs. Please re-check and close the ticket.

**Comment by di-shi** [comment]
Hi razvancrainea,

I confirm that the following tarballs work.

opensips-1.11.7.tar.gz	16-Jun-2016 18:41 	4.3M
opensips-2.1.3.tar.gz	16-Jun-2016 18:41 	4.6M
opensips-2.2.0.tar.gz	16-Jun-2016 18:41 	4.8M

Did you find the root reason? If not, I would prefer leaving the ticket open.

Regards,

Di-Shi

**Comment by bogdan-iancu** [comment]
@di-shi , the tarballs are fetched via the GITHUB API, so whatever problem was, was on their side. Have you checked lately the tarballs if ok ?

Also we have  http://download.opensips.org/ where tarballs are provided via our own build.

Regards,
Bogdan

**Comment by di-shi** [comment]
@bogdan-iancu, as I mentioned, the following tarballs were fine.

opensips-1.11.7.tar.gz 16-Jun-2016 18:41 4.3M
opensips-2.1.3.tar.gz 16-Jun-2016 18:41 4.6M
opensips-2.2.0.tar.gz 16-Jun-2016 18:41 4.8M

If you think it is ok to close this ticket, it is fine for me. I just concern it may happen again (it did before), and someone downloads the tarballs from http://opensips.org/pub like me. Also, "http://opensips.org/pub" does not suggest it is a GitHub issue.

Regards,

Di-Shi
