### ISSUE TITLE
debian Changelog not updated for 1.11.7

### ISSUE THREAD

**Issue by telematico** [OpenSIPS/opensips#908]
A minor change is needed in packaging/debian/changelog for release 1.11.7

The minor version change is not specified in changelog file. Without this change after doing a make deb the packages are recognized as 1.11.6 and this can cause a problem in updates

**Comment by razvancrainea** [comment]
That's true.

@nikbyte will you update for the debian and yum packages? Or you want me to do it?

Thanks,
Răzvan
