### ISSUE TITLE
Ever increasing timer_ticker in uac_reg_check

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#910]
Hi,
Tested with 200 and 300 records.
When i have 300+ records in uac_registrant and execute a reg_reload i see this message coming by:

`WARNING:core:timer_ticker: timer task <uac_reg_check> already schedualed for 12830 ms (now 13820 ms), it may overlap..
`
The amount of ms is related to the start time of opensips.

When i decrease the amount of records to 200 (no restart) it does not occur anymore.

The funny thing is that when i go back to 300 records and reload the timer-ticker comes again. But the timer has not reset, it is still increasing from the moment opensips started.

I've tried increasing shmem and pkmem, and also increasing the hash_size and timer_interval for uac_registrant. both without any change in behaviour.

**Comment by bogdan-iancu** [comment]
Hi @hydrosine , the timer warning means that the previous timer execution did not complete by the time of the next triggering. Shortly, the timer handler has no time to finish its processing in one interval.

The interval (for the uac_reg_check) is calculated by the module as timer_interval / hash_size (as power of 2).  As at each timer interval it will try to handle the records kept on one hash entry (this is why it splits the timer_interval into hash_size parts)

What timer _interval and hash_size values do you use ?

**Comment by hydrosine** [comment]
I noticed this first occuring with an timer_interval of 15 and a default hash value of 1.
I have tested with several combinations of timer_interval and hash value. 

My latest test case was done with a timer_interval of 16 and a hash_size of 4.

Based on the ever increasing value of the timer_ticker since opensips start I assume that something goes wrong in the startup of opensips and some process never completes.

**Comment by bogdan-iancu** [comment]
With the interval 15 and  hash 1 -> 2 (2^1) hash entries in 15 seconds -> the timer routine will be called at every 7 seconds (15 / 2) iterating each one hash entry. 

With the interval 16 and  hash 4 -> 16 (2^4) hash entries in 15 seconds -> the timer routine will be called at every 1 second (16 / 16) iterating each on hash entry. 

To be even, it highly depends on the hashing function and how balanced the hash table is.  
So, it is possible that the timer routine has not time (before its next triggering) to finish handling one hash entry.

For the 300 records, maybe set a trimer_interval longer than 15, maybe 30 seconds or so.

I suspect that the problem appears only at startup/reload when _ALL_ the records must be re-registered in the same time.
