### ISSUE TITLE
2.2 runs out of pkg_mem because of db/db_res.c memory leak

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#911]
OpenSIPS 2.2 will run out of pkg_mem, i believe because of a leak in db/db_res.c  

Full memlog dump is available here: https://gist.github.com/etamme/7d42024ad684fe834b9fd514d2bd2412  

I am using db_sqlite - I do not know if the memory leak is specific to using that vs. db_mysql etc.

**Comment by ionutrazvanionita** [comment]
Hi @etamme,

https://github.com/OpenSIPS/opensips/commit/c1aa55e73f7c56ea4894997aeb7f25a03cb289cf should fix the problem unless there's another leak in sqlite.

**Comment by bogdan-iancu** [comment]
@etamme , can you confirm the fix ?

**Comment by ionutrazvanionita** [comment]
Hi @etamme,

Now all sqlite should be fixed. There was a problem with DB_STRING values which were not freed. This caused a major memr. Now it should be stable from commit e20e6a7f2569619d48f3fa4080427562dc89c588 ( https://github.com/OpenSIPS/opensips/commit/2ea575427b10615162d25112e1cd2389f412ff3e for 2.2 branch).
