### ISSUE TITLE
error on raspberry pi 

### ISSUE THREAD

**Issue by behesht** [OpenSIPS/opensips#912]
hi 

i install opensips on raspberry pi , with this command , 

GIT clone of latest stable release (2.2.0) LTS:
   # git clone https://github.com/OpenSIPS/opensips.git -b 2.2 opensips_2_2

and when i want to compile , i get this error : 

fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
In file included from lock_ops.h:76:0,
                 from locking.h:65,
                 from statistics.h:144,
                 from sr_module.h:49,
                 from usr_avp.c:34:
fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
In file included from mem/../lock_ops.h:76:0,
                 from mem/../locking.h:65,
                 from mem/../statistics.h:144,
                 from mem/shm_mem.h:30,
                 from blacklists.c:35:
mem/../fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
mem/../fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
In file included from mem/../lock_ops.h:76:0,
                 from mem/../locking.h:65,
                 from mem/../statistics.h:144,
                 from mem/shm_mem.h:30,
                 from daemonize.c:57:
mem/../fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
mem/../fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
In file included from lock_ops.h:76:0,
                 from locking.h:65,
                 from statistics.h:144,
                 from sr_module.h:49,
                 from ut.h:37,
                 from transformations.c:35:
fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
In file included from mem/../lock_ops.h:76:0,
                 from mem/../locking.h:65,
                 from mem/../statistics.h:144,
                 from mem/shm_mem.h:30,
                 from pt.c:28:
mem/../fastlock.h:176:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
mem/../fastlock.h:287:2: error: #error "unknown architecture"
 #error "unknown architecture"
  ^
^Cmake: *** Deleting file 'pt.d'

**Comment by bogdan-iancu** [comment]
@behesht , run "NICER=0 make" and post the compile line (just ahead the errors).
