### ISSUE TITLE
Wrong advertised_address in VIA header in local ACK

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#917]
I have run into the same problem that was described in this previous post [1], however it doesn’t appear it was ever solved at the time.
 
I have two public IP addresses that are used for two outbound servers; call them A and B. I am using the dispatcher module to route calls to the servers and I am using set_advertised_address to set the outgoing public address depending on which server dispatcher selected. 

For an initial INVITE, if dispatcher returns server A then I set public address A using set_advertised_address prior to sending the request in the request route. If server A returns failure, the ACK is sent correctly. Then dispatcher selects server B and I set public address B, again using set_advertised_address but now it is in the failure_route. For this second call the INVITE is sent with the correct VIA header for public address B. But if this second call also fails, the local ACK that is sent out uses public address A in the VIA header, not public address B the current one for this request. This causes the far end to reject the ACK and continually retransmit the failure response. 
 
[1] http://lists.opensips.org/pipermail/users/2014-August/029779.html

**Comment by bogdan-iancu** [comment]
Description: currently, the advertised_port/address are preserved only in the UAS part of the transaction - that means it is only one value and it is from the setting done in Request Route; whatever later setting done in Failure Route or Branch Route are not preserved at transaction level (even if they are used on the spot, for sending out the INVITE). 
So, when we have to build a local request (ACK or CANCEL), we do not remember which specific address/port were advertised for that particular UAC (branch)

**Comment by bogdan-iancu** [comment]
@bcnewlin , could you please test the above fix ? (if the patch does not go smoothly on 1.11, let me know and I will backport it).

**Comment by bogdan-iancu** [comment]
let me re-generate the patch, as some functions moved across files between 1.11 and 2.2

**Comment by bogdan-iancu** [comment]
Try this one [via_patch.txt](https://github.com/OpenSIPS/opensips/files/362468/via_patch.txt)

**Comment by bcnewlin** [comment]
@bogdan-iancu I have verified that patch against 1.11.8. It does resolve the issue.

**Comment by bogdan-iancu** [comment]
and even more important, have you noticed any side effects or regressions ? :)

**Comment by bcnewlin** [comment]
I have not, but my testing is fairly limited. As I mentioned in the mailing list after finding this issue I went in another direction with my implementation, using record-routing instead of set_advertised_address. So I cannot test this patch in my actual deployment.

**Comment by bogdan-iancu** [comment]
Thanks @bcnewlin , I did more testing on my side and pushed the fix on all maintained branched.

Thank you for your help.
