### ISSUE TITLE
opensips2.2 crash

### ISSUE THREAD

**Issue by Tinet-AaronAn** [OpenSIPS/opensips#918]
```
(gdb) bt
#0  fm_status (qm=0x7f13560b4000) at mem/f_malloc.c:686
#1  0x00000000004e5cd9 in shm_status () at mem/shm_mem.h:526
#2  cleanup (show_status=show_status@entry=1) at main.c:339
#3  0x00000000004e66a0 in handle_sigs () at main.c:520
#4  0x000000000041a017 in main_loop () at main.c:704
#5  main (argc=<optimized out>, argv=<optimized out>) at main.c:1249
(gdb)
```

**Comment by Tinet-AaronAn** [comment]
(gdb) bt full
#0  fm_status (qm=0x7f13560b4000) at mem/f_malloc.c:686
        f = 0x7f13560b489000
        i = 1
        j = 1
        h = 0
        unused = 0
        size = 0
        __FUNCTION__ = "fm_status"
#1  0x00000000004e5cd9 in shm_status () at mem/shm_mem.h:526
No locals.
#2  cleanup (show_status=show_status@entry=1) at main.c:339
        __FUNCTION__ = "cleanup"
#3  0x00000000004e66a0 in handle_sigs () at main.c:520
        chld = 0
        chld_status = 139
        overall_status = 139
        i = <optimized out>
        do_exit = <optimized out>
        __FUNCTION__ = "handle_sigs"
#4  0x000000000041a017 in main_loop () at main.c:704
        startup_done = <optimized out>
        chd_rank = 16
#5  main (argc=<optimized out>, argv=<optimized out>) at main.c:1249
        cfg_stream = <optimized out>
        c = <optimized out>
        r = <optimized out>
        tmp = 0x1 <Address 0x1 out of bounds>
        tmp_len = <optimized out>
        port = <optimized out>
        proto = <optimized out>
        protos_no = <optimized out>
        options = 0x5da740 "f:cCm:M:b:l:n:N:rRvdDFETSVhw:t:u:g:P:G:W:o:"
        ret = -1
        seed = 833780612
        rfd = <optimized out>
        __FUNCTION__ = "main"

**Comment by Tinet-AaronAn** [comment]
this crash ever several calls.

**Comment by razvancrainea** [comment]
do you see any errors in your system logs?

**Comment by Tinet-AaronAn** [comment]
no erros in /var/log/message

**Comment by razvancrainea** [comment]
This seems to be the core dump of the attendant, which means that some other process is failing.
If this is still happening, please follow [this](https://www.opensips.org/Documentation/TroubleShooting-Crash) tutorial and open a new ticket with a proper core file.
