### ISSUE TITLE
dialog end over MI do not work

### ISSUE THREAD

**Issue by itunali** [OpenSIPS/opensips#921]
Hi,

Dialog ending over MI do not reply with 487. I used base config for simulation as attached. Also, debug logs are following;

Opensips version 2.2.0

```log
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <1328>
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:mi_fifo:mi_parse_tree: adding node <> ; val <1858389663>
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:mi_fifo:mi_parse_node: end of input tree
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:mi_fifo:mi_fifo_server: done parsing the mi tree
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:dialog:mi_terminate_dlg: h_entry 1328 h_id 1858389663
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:dialog:lookup_dlg: ref dlg 0x7f80d52fb3c8 with 1 -> 3
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:dialog:lookup_dlg: dialog id=1858389663 found on entry 1328
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:dialog:dlg_end_dlg: trying to find transaction with hash_index = 31149 and label = 134818349
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:tm:t_lookup_ident: REF_UNSAFE:[0x7f80d5308d40] after is 1
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:tm:t_lookup_ident: transaction found
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:tm:t_unref_cell: UNREF_UNSAFE: [0x7f80d5308d40] after is 0
Jul 01 12:45:05 testsip /usr/bin/opensips[3068]: DBG:dialog:unref_dlg: unref dlg 0x7f80d52fb3c8 with 1 -> 2 in entry 0x7f80d52e2bf8
Jul 01 12:45:06 testsip /usr/bin/opensips[3073]: DBG:tm:utimer_routine: timer routine:7,tl=0x7f80d5308f60 next=(nil), timeout=53100000
```

The second issue "t_local_replied" does not hit on failure_route so I can not detect local generated replies.

[opensips.cfg.txt](https://github.com/OpenSIPS/opensips/files/343473/opensips.cfg.txt)

**Comment by bogdan-iancu** [comment]
@itunali , from SIP perspective, are both BYE send to the end points ?  

Why do you expect this 487 ??

**Comment by itunali** [comment]
Hi @bogdan-iancu,

I was sending end_dialog_end command before session establish so I expect 487 reply on a-leg and CANCEL on b-leg side

**Comment by bogdan-iancu** [comment]
Did opensips send the CANCEL to the callee side ? Did the callee reply with 487 ?

**Comment by itunali** [comment]
Opensips did not send the CANCEL request

**Comment by bogdan-iancu** [comment]
For the INVITE you try to cancel, were there any replies received from callee side ?

**Comment by itunali** [comment]
The callee side was not SIP application so was not receive any reply during fr_timeout (60sec). I was trying to simulate callee side has no internet connection or off state

**Comment by bogdan-iancu** [comment]
@itunali , if no reply was received as a result of the INVITE, the RFC3261 says that the proxy must not send the CANCEL to that destination. The canceling is marked internally, but no CANCEL request is sent out (unless there is at least one reply from the callee side).
And (again, based on RFC3261), if there is no reply from callee side, we should not generate any 487 reply (at proxy level), as the callee (with delay) may send some replies, including the 200 OK (after our local cancel). So, in such situation, we simply let the transaction to timeout ; if in the mean while a reply is received, we will fire the CANCEL.

**Comment by itunali** [comment]
@bogdan-iancu, you are right looking from RFC side but I sent end_dialog_end command over MI and I expect 487 for caller side.

**Comment by bogdan-iancu** [comment]
The MI command is terminating a dialog and it is doing it in the proper SIP way. If the dialog is not establish, it tries to CANCEL it. If there is no incoming reply, it will not send out the CANCEL, but only mark the transaction as being canceled.
