### ISSUE TITLE
Opensips 2.2 stable version - crash on SLES

### ISSUE THREAD

**Issue by chiforbogdan** [OpenSIPS/opensips#924]
Hello, 

I am getting a crash on SLES 11 SP3, after the presence module is initialized. After the crash, the process can be restarted only after the database is recreated.

Here are some logs:

Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: INFO:proto_tls:mod_init: initializing TLS protocol
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: INFO:auth:mod_init: initializing...
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: INFO:auth_db:mod_init: initializing...
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: INFO:alias_db:mod_init: initializing...
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: INFO:core:evi_publish_event: Registered event <E_PRESENCE_PUBLISH(13)>
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: NOTICE:presence:mod_init: E_PRESENCE_PUBLISH event registered
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: NOTICE:presence:mod_init: initializing module ...
Jul  5 12:49:02 ssvoice-vm /usr/local/sbin/opensips[4784]: CRITICAL:core:db_free_row:  >>> pkg_free() on non-pkg ptr 0x3 - aborting!  It seems you have hit a programming bug. Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

**Comment by liviuchircu** [comment]
Did you grab your 2.2 off the latest git branch? If yes, then you should definitely pull the latest sources and recompile.

The concerned fix is commit 5936274. Similar reported issue: #926. Please re-open if the issues persist.
