### ISSUE TITLE
Async rest_client timeout

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#929]
Hi guys
I'm using opensips 2.2dev on a CentOS Linux release 7.2.1511. compiled with libcurl 7.48.0
I use the async version of rest_get function as follows:

 async(rest_get("http://localhost/stereo_recording/stereo_recording.php?mode=end&callid=$ci", "$var(body)",,  "$var(rcode)"),"1");

Usually it works correctly, but sometimes the request fails for timeout showing the following error:

Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: DBG:rest_client:start_async_http_req:  >>>>>>>>>> fd 12 ISSET(read)
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: DBG:rest_client:start_async_http_req:  >>>>>>>>>> fd 12 ISSET(read)
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: DBG:rest_client:start_async_http_req:  >>>>>>>>>> fd 12 ISSET(read)
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: DBG:rest_client:start_async_http_req:  >>>>>>>>>> fd 12 ISSET(read)
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: DBG:rest_client:start_async_http_req:  >>>>>>>>>> fd 12 ISSET(read)
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: INFO:rest_client:start_async_http_req: curl_multi_timeout() returned -1, pausing 500ms...
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29778]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 86623850 ms (now 86623950 ms), it may overlap..
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29778]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 86623950 ms (now 86624050 ms), it may overlap..
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29778]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 86624050 ms (now 86624150 ms), it may overlap..
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29778]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 86624150 ms (now 86624250 ms), it may overlap..
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29778]: WARNING:core:utimer_ticker: utimer task <tm-utimer> already schedualed for 86624250 ms (now 86624350 ms), it may overlap..
Jul  9 13:49:43 creditech-cti1 /usr/local/sbin/opensips[29779]: ERROR:rest_client:start_async_http_req: timeout while connecting to 'http://localhost/stereo_recording/stereo_recording.php?mode=end&callid=d4d435e4-3844-e611-9687-005056ab6c62@creditech-cti1' (1 sec)

I checked with a tcpdump, and that http request was answered after 40ms, but opensips missed it.
Another strange thing is that despite of the use of async, opensips does not process any other SIP request while waiting for this missing answer, I see because with default params, with 20s timeout, opensips didn't process REGISTER request and SIP endpoints unregistered, this is the reason because I changed connection timeout to 1s.

Thank you very much

Alessandro

**Comment by arovetto** [comment]
[timeout_err.zip](https://github.com/OpenSIPS/opensips/files/355715/timeout_err.zip)

These are logs and tcpdump of the HTTP request:
http://localhost/stereo_recording/stereo_recording.php?mode=end&callid=d4d435e4-3844-e611-9687-005056ab6c62@creditech-cti1 (13:49:42)

**Comment by arovetto** [comment]
I've discovered that this issue occured only if http keepalive (tcp persistent connection) is enabled.
I've simply added "KeepAlive Off" directive in httpd configuration and the problem stopped.
I hope this info will be useful for debugging.

**Comment by arovetto** [comment]
Hi Liviu
Do you have any news about this issue?
Thanks

**Comment by liviuchircu** [comment]
Sorry for the long response, @arovetto!

First of all, great bug report! found some time to look into the problem. When dealing with short timeouts such as the one you have set (1 sec), the module would sometimes time out some of the requests. This is definitely a bug which can be solved by finer grained waiting. Here [1] is a patch that improves the waiting logic, so we avoid these incorrect timeouts when 200 OK responses actually arrive within 3 ms.

Also, regarding the utimer_ticker() warnings, are you somehow using an OpenSIPS with `tcp_children = 1`, and no other UDP workers? That would explain the warnings, as the timer jobs would have to be run by that worker process as well, so they get delayed if it's stuck in libcurl.

[1]: https://gist.github.com/liviuchircu/ca871b0abc38afe2a52bbb398b8db711

**Comment by arovetto** [comment]
Thanks @liviuchircu,
the problem is present both with 20s and 1s connection timeout, it seems related to the reuse of the tcp connection (maybe because with keepalive off the response time is greater).
I'll try your patch and I let you know.
Regarding children, my configuration is 1 child for UDP and TCP disabled.

check_via=no            # (cmd. line: -v)
dns=no                          # (cmd. line: -r)
rev_dns=no                      # (cmd. line: -R)
children=1
listen=udp:creditech-cti1:5060

**Comment by arovetto** [comment]
I've finally tested the patch and it seems to work, thanks.

**Comment by liviuchircu** [comment]
Patch is merged into `master` for the moment, I'll make sure it gets backported to `2.2` and `2.1` in the next couple of weeks, as it receives even more testing.

**Comment by drivefast** [comment]
Hi @liviuchircu, i'm facing a very similar problem, although for me closing the connection after every request doesn't seem to fix the issue. Granted, i tried something slightly different, i added a "Connection: close" as a request header, which would normally indicate to the server that we want it to ignore its keep-alive setting. Should i try your patch hoping it would solve my issue as well? Thanks.

**Comment by liviuchircu** [comment]
If your problem is also related to timeouts, then the quicker your TCP handshakes are done, the more likely it is for the patch to make a difference.

**Comment by drivefast** [comment]
My problem turned out to be different. For me, most (but not all) http requests were failing (with a timeout) when sent to a remote server, but were running fine if running the http server on the same machine. Sending the same exact requests with command-line curl was always working, so no network issues. My fix was to recompile the rest_client module and move it over to my opensips machine (my opensips was installed from RPM). Looks like the current version of the module included in the 2.2 RPM is bad.
