### ISSUE TITLE
trace_dialog does not trace if flag or avp is not set

### ISSUE THREAD

**Issue by razvancrainea** [OpenSIPS/opensips#932]
Starting with commit 24ba3ed467bebc1f029e5c0627225f8d54163143 the trace_dialog function does not trace the dialog if you don't set either the flag, or the traced_avp.

**Comment by bogdan-iancu** [comment]
This is a documentation error - for both sip_trace() and trace_dialog() you must explicitly set some tracing trigger like the trace flag or the traced user AVP.
