### ISSUE TITLE
MI function 'profile_bin_status' in dialog module documented but missing

### ISSUE THREAD

**Issue by sysreq0** [OpenSIPS/opensips#939]
The 2.2.x version of the 'dialog' module documentation mentions a 'profile_bin_status' MI function, but when issuing the command I get the following error:

```
500 command 'profile_bin_status' not available
```

Ref.: http://www.opensips.org/html/docs/modules/2.2.x/dialog#id297353

**Comment by bogdan-iancu** [comment]
Thank you @sysreq0. Indeed the MI function was removed long time ago (when the dialog module was migrated to clusterer support for sharing profiles). I fixed the docs, the online version will be re-generated over the night.
