### ISSUE TITLE
sst module appending header after Content-Length:

### ISSUE THREAD

**Issue by gcuppers** [OpenSIPS/opensips#951]
When the sst module has to add headers to the sip packet it does so at the end of the headers. Resulting in:
```
Content-Length: 246
Content-Disposition: session; handling=required
Content-Type: application/sdp
Session-Expires: 1800;refresher=uac
```
Some servers don't like this. They expect:
```
Session-Expires: 1800;refresher=uac
Content-Length: 246
Content-Disposition: session; handling=required
Content-Type: application/sdp
```
Would it be possible to modify the sst module so that it inserts Session timer related lines before any "Content-" line?

Thanks,

Guillermo

**Comment by bogdan-iancu** [comment]
@gcuppers , in SIP, there are no constraints when comes to the order of the SIP headers (different ones).
I understand your problem, but it is not a general case (maybe other vendors will require a different order), it is against the SIP RFC , not to mention that is an ugly hack.
