### ISSUE TITLE
Async ldap_search looks broken

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#958]
I was trying to set up async ldap_search and I ended up with:

Sep 23 22:18:35 os1 /usr/local/sbin/opensips[20383]: CRITICAL:tm:io_watch_add: #012>>> [TCP_worker] BUG trying to overwrite entry 24 in the hash(24, 16, 0x7f3e8052c0d0,1) with (24, 16, 0x7f3e8052d928,1)#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Sep 23 22:18:35 os1 /usr/local/sbin/opensips[20383]: ERROR:tm:t_handle_async: failed to add async FD to reactor -> act in sync mode

**Comment by bogdan-iancu** [comment]
Hi @sekil75. What OpenSIPS version is this ? Also, please post the exact script line that triggers this error. 
Is this bug consistently reproducible ?

**Comment by sekil75** [comment]
Somehow my REGISTERs are working, it's the INVITEs and SUBSCRIBEs that cannot auth, even though I see the ldap part being ok (REGISTER wouldn't work). I see no packet from OS after SUBSCRIBEs:

Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:ldap:ldap_url_search_async: LDAP URL parsed into session_name [sipaccounts], base [ou=customers,o=company], scope [2], filter [(&(edited]
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:ldap:lds_search_async: [sipaccounts]: performing LDAP search: dn [ou=customers,o=company], scope [2], filter [(&(edited))], client_timeout [5000000] usecs
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:ldap:ldap_params_search_async: [sipaccounts]: [0] LDAP entries found
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:tm:io_watch_add: [TCP_worker] io_watch_add op (26 on 7) (0x807400, 26, 16, 0x7f79fd93c5d8,1), fd_no=4/1024
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: ERROR:tm:io_watch_add: [TCP_worker] epoll_ctl ADD failed: File exists [17]
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: ERROR:tm:t_handle_async: failed to add async FD to reactor -> act in sync mode
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: LDAP auth: ldap_search: found [1] entries for (fsuid=109)(fsdomainname=test.company)
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: LDAP auth: ldap_result: username = 109, password = blah
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: LDAP auth: ldap_result: callgroup = all
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:auth:check_nonce: comparing [57e9920a000013d1601ac1699c2f29f1cfb3a0eb4a33261f] and [57e9920a000013d1601ac1699c2f29f1cfb3a0eb4a33261f]
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:auth:auth_get_ha1: HA1 string calculated: 60907cb6fc900b450d5ad9fdea604280
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:auth:check_response: our result = 'db299130e2bdc78abda1b30b6b5d553e'
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:auth:check_response: authorization is OK
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:auth:post_auth: nonce index= 5073
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:tm:cleanup_uac_timers: RETR/FR timers reset
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:tm:insert_timer_unsafe: [2]: 0x7f79fd939480 (36847)
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:tm:t_unref: UNREF_UNSAFE: [0x7f79fd939400] after is 0
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:core:destroy_avp_list: destroying list (nil)
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:core:receive_msg: cleaning up
Sep 26 23:23:56 os1 /usr/local/sbin/opensips[29192]: DBG:core:tcp_read_req: tcp_read_req end

**Comment by bogdan-iancu** [comment]
Confirmed, fix in progress !

**Comment by ionutrazvanionita** [comment]
@sekil75  Can you please try the patch attached and tell me if it fixex your problem?
[ldap.zip](https://github.com/OpenSIPS/opensips/files/503339/ldap.zip)

**Comment by sekil75** [comment]
Hi, just tried it. It's the same as before, ldap part is good but nothing comes back from OS in request from the phone.

**Comment by ionutrazvanionita** [comment]
@sekil75 can you please send me your script privately? unfortunately i am unable to replicate the bug
