### ISSUE TITLE
nathelper module sends natping OPTIONS with wrong interval

### ISSUE THREAD

**Issue by kertor** [OpenSIPS/opensips#959]
Hello! I found a small bug. Nathelper module sends natping OPTIONS to UAC with wrong interval.
This is settings Nathelper module:
**loadmodule "nathelper.so"
modparam("nathelper", "natping_interval", 10)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "natping_tcp", 1)
modparam("nathelper", "natping_partitions", 4)
modparam("nathelper", "received_avp", "$avp(received)")
modparam("nathelper", "sipping_bflag", "NAT_FLAG")
modparam("nathelper", "sipping_from", "sip:natping@domain")
modparam("nathelper", "sipping_method", "OPTIONS")
modparam("nathelper", "nortpproxy_str", "a=sdpmangled:yes\r\n")**

In location table i have only one registration(softphone on my PC), which is marked as benind NAT. I ran wireshark sniffer, and filter traffic by natping OPTIONS.
Here is the screenshot of the results that i get:
![screen from pc](https://cloud.githubusercontent.com/assets/3471049/18919455/dff7ff6e-85a6-11e6-982e-f7b61e8cf292.JPG)
You can see the following: Incoming packets received with incorrect, random interval. 
But in module settings set 10 seconds.
Can you help me?
version: opensips 2.1.4 (x86_64/linux)
Thank you very much for your work!

**Comment by bogdan-iancu** [comment]
Confirmed !

**Comment by bogdan-iancu** [comment]
Many thanks @kertor for reporting this problem !
