### ISSUE TITLE
is_registered() does not expose attr_avp

### ISSUE THREAD

**Issue by hydrosine** [OpenSIPS/opensips#960]
Hi,
It seems the variable set with modparam("registrar", "attr_avp", "$avp(attr)") with save("location") is no longer saved.

I've tested on 2.2.1 by setting a value to $avp(attr) and then calling save("location") on a REGISTER. It does not appear in the opensipsctl ul show command. and also on the is_registered("location, "$fu") function on an INVITE the avp stays empty.

Doing 'almost' the same on 1.10.3, so setting a value to $avp(attr), calling save("location") on REGISTER. then using registered("location","$fu") on INVITE returns the value as expected. 1.10.3 also shows the value in opensipsctl ul show.

Could you restore the behaviour to latest versions of opensips? I'm planning on using this feature in a wss setup so i need it on 2.2!

Kind regards,
Rik

**Comment by bogdan-iancu** [comment]
@hydrosine , just tested with 2.2.1 code and it seems to perfectly work. Using the default script, I added:

	modparam("registrar", "attr_avp", "$avp(attr)")

and I have

	if (is_method("REGISTER"))
	{
		$avp(attr) = "bla";
		if (!save("location"))
			sl_reply_error();
		exit;
	}

and 

	# do lookup with method filtering
	if (!lookup("location","m")) {
		t_newtran();
		t_reply("404", "Not Found");
		exit;
	} 

	xlog("-----$avp(attr)\n");

The value "bla" is printed upon delivering a request to the user, also it is present in the registration record:

	AOR:: bob
		Contact:: sip:bob@10.0.0.15:36366;rinstance=0bf15a2d0aa0dec2;transport=UDP Q=
			Expires:: 101
			Callid:: ZGUwMGJkY2ZlNDFjM2JhNmYzZTQ3NWU4ZDFmYWQ4Mzk.
			Cseq:: 2
			User-agent:: Z 3.2.21357 r21103
			State:: CS_NEW
			Flags:: 0
			Cflags:: 
			Socket:: udp:10.0.0.15:5060
			Methods:: 5951
			Attr:: bla

**Comment by hydrosine** [comment]
I agree that that the lookup() functions recovers the attr saved at lookup.
But as you can see in my issue it is about the **is_registered()** function.

I've again tested it on 2.2.1 with the following code piece:

        if( is_registered("location","$fu" ) ){
                xlog("attr from the is_registered [$avp(attr)] ");
        }
        
        if( lookup("location","","$fu" ) ){
                xlog("attr from the lookup [$avp(attr)]");
        }

which results in the logs in: 

        Oct 10 15:09:54 SRV-DEV-HPROXY-1 /usr/sbin/opensips[28688]: attr from the is_registered [<null>] 
        Oct 10 15:09:54 SRV-DEV-HPROXY-1 /usr/sbin/opensips[28688]: attr from the lookup [zwaar]

The old REGISTERED() function in 1.10.x works. http://www.opensips.org/html/docs/modules/1.10.x/registrar#id294412
