### ISSUE TITLE
[dialog] update remote contact

### ISSUE THREAD

**Issue by bogdan-iancu** [OpenSIPS/opensips#964]
Update the remote contact when updated via a re-INVITE

**Comment by razvancrainea** [comment]
According to [rfc3261](https://tools.ietf.org/html/rfc3261#section-12.2), only re-INVITEs can update the contact. However, [rfc3311](https://tools.ietf.org/html/rfc3311#section-5.1) also allows UPDATE messages to update the contact, so we need to handle this as well.

**Comment by milanstanojeviclf** [comment]
Hello @bogdan-iancu @razvancrainea , Is this something that is planned to be implemented/included in codebase soon? Asking since I'm running into specific issue related to this (https://opensips.org/pipermail/users/2017-September/038096.html)

**Comment by razvancrainea** [comment]
Yes, we are still planning to support this. Most likely it will be present in the final 2.4 release.

**Comment by razvancrainea** [comment]
I've just pushed this upstream in commit 125a1dc.

Just need to run a few more tests before pushing it to 2.4.0. It would be great if you could test too before backporting it.

**Comment by razvancrainea** [comment]
Backported down to 2.2.
