### ISSUE TITLE
raise_event() unusual/broken behaviour in 2.2 LTS

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#971]
I am attempting to use raise_event to raise custom events in opensips 2.2 LTS from the Xenial repository.

I have a custom event "E_MYEVENT" and registered a listener;

```
opensipsctl fifo event_subscribe E_MYEVENT udp:127.0.0.1:8888
```

and listen using netcat;
```
# nc -ul -p 8888
```

My event is raised in the main route block when an INVITE method is received. The scnerios are as follows;

Two mobile clients A and B:
1. Start server
2. Subscribe as above
3. Start netcat listener as above
4. A calls B
5. Event is raised
6. Event is received at netcat listener
7. B calls A
8. Event is raised
9. Event is NOT received at netcat listener
10. A calls B
11. Event is raised
12. Event is received at netcat listener  
13. Stop server
14. Start server
15. Subscribe as above
16. Start listener as above
17. B calls A
18. Event is raised
19. Event is received at netcat listener
20. A calls B
21. Event is raised
22. Event is NOT received at netcat listener
23. ...

Essentially, to summarise. When making calls between clients A and B, only the first caller to make the call after server start can cause events to be raised and then received. Calling the other direction shows events raised in the Opensips log but nothing is received at the listener. Restart the server and call the other direction, and now only this other direction works.

small snippet of log from working and non working calls; First event is seen, second event is not. Subsequent repeats of the first call A->B will all work.

```
--- EVI - sip:A@test5 -> sip:B@test5 ---
Oct 20 14:30:55 [16] DBG:core:evi_param_set: adding string param
Oct 20 14:30:55 [16] DBG:core:evi_param_set: adding string param
Oct 20 14:30:55 [16] DBG:core:evi_raise_event_msg: found subscriber 127.0.0.1
--
--- EVI - sip:B@test5 -> sip:A@test5 ---
Oct 20 14:31:05 [15] DBG:core:evi_param_set: adding string param
Oct 20 14:31:05 [15] DBG:core:evi_param_set: adding string param
Oct 20 14:31:05 [15] DBG:core:evi_raise_event_msg: found subscriber 127.0.0.1

```

and here is the config that generated that log;

```
if (is_method("INVITE")) {
        xlog("--- EVI - $fu -> $tu ---\n");
        $avp(attr-name) = "from";
        $avp(attr-name) = "to";
        $avp(attr-val) = $fu;
        $avp(attr-val) = $tu;
        raise_event("E_MYEVENT", $avp(attr-name), $avp(attr-val));
}
```

**Comment by razvancrainea** [comment]
So you are seeing the `--- EVI - $fu -> $tu ---` message in the log for all the events (even for the ones that are not received, right?) Are there any other logs or errors related to this?
Where is that code snippet (`if (is_method("INVITE")) {`)inserted in your script?

**Comment by hamid-elaosta** [comment]
Yes, I see the log for all events, even those not received.

The code snippet is the very first item in the route{} block.

**Comment by razvancrainea** [comment]
And if you trace at the networking level (using ngrep or tcpdump), you still do not see the message? I am asking because it is a bit weird that you do not see the event, because the `raise_event` function simply sends a buffer further. If you don't see the event when you do the trace, I will send you some patches to further investigate this.

**Comment by hamid-elaosta** [comment]
It looks like I was suffering from an issue with netcat.

Having done as you suggested I wiresharked the traffic to see that the events were in fact being raised, which led me to find this: http://www.markhneedham.com/blog/2013/07/30/netcat-strange-behaviour-with-udp-only-receives-first-packet-sent/

I used socat instead and all events are received correctly now. Good news, opensips events work :dancing_women:

**Comment by razvancrainea** [comment]
Awesome! Closing this ticket.
