### ISSUE TITLE
Missing newline for log statement

### ISSUE THREAD

**Issue by hamid-elaosta** [OpenSIPS/opensips#977]
The following log statement is missing a newline character on 2.2 LTS for apt repository for Xenial.

```
ERROR:dialog:load_dialog_info_from_db: Dialog in DB doesn't match any listening socketsOct 27 09:19:37 [22] WARNING:tls_mgm:mod_init:
```

**Comment by razvancrainea** [comment]
Fixed on all branches.

**Comment by razvancrainea** [comment]
Fixed on all branches. Thanks for reporting it!

BR

Răzvan Crainea
OpenSIPS Solutions
www.opensips-solutions.com
