### ISSUE TITLE
mc_compact results in incorrect Content-Length

### ISSUE THREAD

**Issue by rrb3942** [OpenSIPS/opensips#978]
Using a very simple script with no other message manipulation calling mc_compact("Max-Forwards") (same result without white-list) results in an incorrect Content-Length.

Header says length should be 217, but actual body size is 215.

Looked at the module source and nothing jumped out at me.

Using latest git of 2.2
opensips -V
version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: c8a605b
main.c compiled on 13:01:52 Oct 26 2016 with gcc 5.2.1

I attached an example capture.

[mc_compact_bad_content_len.zip](https://github.com/OpenSIPS/opensips/files/557023/mc_compact_bad_content_len.zip)

**Comment by bogdan-iancu** [comment]
@rrb3942 , the mc_compact does not change the body or the value of the contact-len hdr. But I see in the outbound SDP that the "a=rtpmap:0 PCMU/8000" is deleted. Do you do any codec manipulation for the message ?

**Comment by rrb3942** [comment]
@bogdan-iancu the mc_compact documentation states that it removes all rtpmaps for values less than 98.

"This function will realise four different things: headers which are not mandatory and are not in the whitelist will be removed, headers of same type will be put together, separated by ',', header names which have a short form will be reduced to that short form and **sdp rtpmap attribute headers which contain a value lower than 98 will be removed,** because it is no longer needed. No lumps affected by this function, because it is applied after almost all the processing is done."

So when it removes default rtpmaps the content-len isn't being recalculated correctly.

The script was very minimal that triggered this. Basically the default script + mc_compact before t_relay and only some modifications for sequential request handling and no other message manipulation.

**Comment by ionutrazvanionita** [comment]
Can you please try this patch and tell me if it solves the bug?
[compression.zip](https://github.com/OpenSIPS/opensips/files/564482/compression.zip)

**Comment by rrb3942** [comment]
@ionutrazvanionita That patch is working for me. content-len is now correct after using mc_compact().

Thanks!

**Comment by ionutrazvanionita** [comment]
@rrb3942 great i'll push the patch in all branches, thank you.

**Comment by ionutrazvanionita** [comment]
fixed with https://github.com/OpenSIPS/opensips/commit/81498e4ce0e7e2928d229b69da0c440660c97544 (https://github.com/OpenSIPS/opensips/commit/9eb177df3130f088af6f4b0a1d6c22a0dfa369cb for 2.2 and https://github.com/OpenSIPS/opensips/commit/e31fead32e712adbf925afac1e4d9fa321721916 for 2.1)
