### ISSUE TITLE
Missing the final trailing linefeed at the end of the SDP while sending to RTPEngine 

### ISSUE THREAD

**Issue by mvenkatesh431** [OpenSIPS/opensips#980]
Hi all, 
I am using RTPEngine and OpenSIPS, Everything working good. But I just updated OpenSIPS to latest git version. After that, I am getting following error. 
**DOMException: Failed to parse SessionDescription. Invalid SDP line.**

I am calling RTPEngine offer on invite then RTPEngine giving the reply back, But that reply SDP have the problem. It is including two a= elements in one line. Please see below.

a=ssrc:2868484751 label:08b2bfc7-c88d-47c2-9c7a-e46e272f4533a=sendrecv.

Please see the attached logs of  between the OpenSIPS and RTPEngine.

My OpenSIPS script is very straight forward like below.

branch_route[handle_nat] {
        if (!is_method("INVITE") || !has_body("application/sdp"))
                return;

        if (isflagset(SRC_WS) && isbflagset(DST_WS))
                # $var(rtpengine_flags) = "ICE=force-relay DTLS=passive";
                #$var(rtpengine_flags) = "ICE=force DTLS=passive";
                $var(rtpengine_flags) = "DTLS=passive";
}

onreply_route[handle_nat] {
       if (isflagset(SRC_WS) && isbflagset(DST_WS))
                #$var(rtpengine_flags) = "ICE=force DTLS=passive";
                #$var(rtpengine_flags) = "ICE=force-relay DTLS=passive";
                $var(rtpengine_flags) = "DTLS=passive";
}

I also submitted this issue in RTPEngine mailing list. But They replied, Incoming message received by RTPEngine missing the trailing linefeed. Here is the link to my issue in RTPEngine.
https://github.com/sipwise/rtpengine/issues/285

Here is the log file : 
[rtpengine_sdp.txt](https://github.com/OpenSIPS/opensips/files/561697/rtpengine_sdp.txt)

Thank you.

**Comment by liviuchircu** [comment]
Thanks for the report, @mvenkatesh431 ! If you are using the `master` branch, could you just try to revert it to commit fb0d90e and see if the issue persists? This is due to the fact that there is some ongoing work that could affect the code in question. Thanks!

**Comment by mvenkatesh431** [comment]
Thanks !!, It is working now.

**Comment by bogdan-iancu** [comment]
Hi @mvenkatesh431 - I will keep this ticket open as I need to check and fix the latest commits (related to multi part body processing)

**Comment by bogdan-iancu** [comment]
@mvenkatesh431 , I'm trying to understand where the problem happens (as I cannot locate the error you mentioned in the logs you attached).
So, the bogus SDP results when handling the INVITE or when handling its SIP replies ?

**Comment by mvenkatesh431** [comment]
Hi Bogdan, I just updated OpenSIPS to latest git version and Issue is still there. 

Here is my scenario ( WSS1 calls to WSS2  ) : 
WSS1 sends invite to OpenSIPS 
OpenSIPS sends SDP to RTPEngine 
RTPEngine give back the modified SDP ( This SDP contains two attributes in one SDP line.)
**a=ssrc:2868484751 label:08b2bfc7-c88d-47c2-9c7a-e46e272f4533a=sendrecv.**
WSS2 sends 488 not supported with Invalid SDP error.

Here is the OpenSIPS debug log.
[OpenSIPS bug.txt](https://github.com/OpenSIPS/opensips/files/568728/OpenSIPS.bug.txt)

**Comment by bogdan-iancu** [comment]
Hi @mvenkatesh431 - yes, there is no fix yet, as I'm still trying to understand the problem.

I found the broken SDP in the logs from rtpengine, but to understand how is gets there, could you make pcap of the dialog between OpenSIPS and rtpengine ? I need to see the exact SDP send by OpenSIPS and the answer from rtpengine - hopefully this will give me a hint on where the problem is.

Many thanks!

**Comment by bogdan-iancu** [comment]
@mvenkatesh431 , thank you for your support and information. The issue should be fixed. Any confirmation from your side too will he highly appreciated.
