### ISSUE TITLE
Bug in drouting module - if hostname does not resolve, probing stays Active

### ISSUE THREAD

**Issue by petekelly** [OpenSIPS/opensips#982]
I have found what I think is a bug in drouting module when probing gateways.

If a gateway is specified with a hostname (e.g. sip:example.com:5060) and this hostname cannot be resolved to ping, then the gateway should go to _Inactive_.

Instead the gateway stays as _Active_ always, and each time there is a probe attempt you see this in the logs:

````
Nov 03 14:33:09 vp-sbp2c sbp2c[22360]: CRITICAL:core:mk_proxy: could not resolve hostname: "example.com"
Nov 03 14:33:09 vp-sbp2c sbp2c[22360]: ERROR:tm:uri2proxy: bad host name in URI <sip:example.com:5060>
Nov 03 14:33:09 vp-sbp2c sbp2c[22360]: ERROR:drouting:dr_prob_handler: unable to execute dialog
````

I think the behaviour should be that the GW is moved to _Inactive_ if the domain cannot be resolved to an IP.

This was found on version 2.1.4

**Comment by bogdan-iancu** [comment]
Hi @petekelly,

I'm not convinced :) - if the inability to probe should translate into disabling the destination. In your particular case, it makes sense (as you cannot translate the GW name to an IP, so you cannot reach the GW). But the TM function used for sending the probes does not provides detailed reporting on the error - it may be an internal mem issues, which definitely should not result in disabling the GW.

Eventually we can translate this into a feature request, in the idea that we can propagate all the way back to DR the info on the error type.

**Comment by petekelly** [comment]
Hi @bogdan-iancu 

I see your point, I think from a drouting point of view it is useful to know whether the GW is up or not (and not whether TM has memory issues ;)) so it would be a good feature to be able to accurately give the reason to drouting.

It would also mean that the output of dr_gw_status would reflect more accurately the situation.

**Comment by bogdan-iancu** [comment]
@petekelly , over-thinking this, your point may be stronger right now :). Most of the reasons for the ping to fail are related to the impossibility to reach the destination (lack of mem is low, and if you got there, anyhow you are globally foobar)
I will do a patch for this shortly
