### ISSUE TITLE
Mongodb module : "upsert" Feature Request

### ISSUE THREAD

**Issue by jalung** [OpenSIPS/opensips#989]
Using the mongodb module with multiple opensips and doing raw queries to search for a "subkey" in the database. If the subkey is not found, then insert it, else update it.  

The problem seems to be, if all the opensips instances receives a request from the same IP at the "same" time, then the "find/insert/update" does not work very well and sometimes end up with duplicate inserts based on the subkey.

Have tried different script logic which might be the problem, but cannot get it right . Can use the "upsert" from an external script in PHP mongo but want to avoid doing that.

If a single opensips instance, the problem does not occur.

**Comment by liviuchircu** [comment]
Can you show me your exact scripting logic? The raw update queries for _cachedb_mongodb_ have the "upsert" flag enabled by default in all OpenSIPS versions, so you should not end up with duplicate inserts.

If I understand the problem correctly, you should not have a "find/insert/update" logic in your code, but rather just an "update".

**Comment by jalung** [comment]
Liviu, the below snippet is the old code that I was using. I am currently using just a simple  “upsert” via a PHP external script which is working as expected. I was under the impression that the “upsert” feature was not implemented. Thanks for the info that it is supported by just doing an update.

The problem with the below script is evident when more than one opensips servers try to do an insert at the same time, if the same user/IP sends multiple requests at the same time to multiple sips. Since the entry does not exist the insert is triggered. The “_subkey” is based on the user/IP.
    
                #check if record exists or create
                cache_raw_query("mongodb:replicaset1","{ \"ns\" : \"db.collection\", \"op\" : \"find\", \"query\": {\"_subkey\" : \"$var(uipcount)\", \"session\": \"$ci\" }, \"fields\": { \"_subkey\" : 1, \"count\": 1, \"session\": 1, \"expires\" : 1 } }","$avp(mongo_uipcount)");
#               sleep("1");

                if ($(avp(mongo_uipcount)[0]) != NULL) {
                        $json(json_resco) := $(avp(mongo_uipcount)[0]);
                        $var(count) =  $(json(json_resco/count){s.int}) + 1;
                        $var(session) =  $json(json_resco/session);
                        cache_raw_query("mongodb:replicaset1","{ \"ns\" : \"db.collection\", \"op\" : \"update\", \"query\": { \"_subkey\" : \"$var(uipcount)\", \"count\" : $var(count), \"session\": \"$var(session)\", \"expires\" : $var(expires) }, \"match\" : { \"_subkey\" : \"$var(uipcount)\", \"session\": \"$var(session)\" } }");
                        avp_delete("$avp(mongo_uipcount)");

                } else {

                        $var(count) = 1;
                        $var(session) = $ci;
                        if (!cache_fetch("local","$var(uipcount)",$avp(dummy))) {
                                cache_raw_query("mongodb:replicaset1","{  \"ns\" : \"db.collection\", \"op\" : \"insert\", \"query\": {\"_subkey\" : \"$var(uipcount)\", \"count\" : $var(count), \"session\": \"$var(session)\", \"expires\" : $var(expires) } }");
                                cache_store("local","$var(uipcount)","$ci",10);
                        }
                }
