### ISSUE TITLE
Memory error preventing startup when using tls_mgm and db_postgres together on 2.2

### ISSUE THREAD

**Issue by pbaines** [OpenSIPS/opensips#990]
Hello,

OpenSIPs is failing to start with the below error:

Nov 14 12:42:43 [5308] INFO:tls_mgm:mod_init: initializing TLS protocol
Nov 14 12:42:43 [5308] ERROR:tls_mgm:mod_init: unable to set the memory allocation functions
Nov 14 12:42:43 [5308] ERROR:tls_mgm:mod_init: NOTE: check if you have openssl 1.0.1e-fips, as this version is know to be broken; if so, you need to upgrade or downgrade to a differen openssl version !!
Nov 14 12:42:43 [5308] ERROR:core:init_mod: failed to initialize module tls_mgm
Nov 14 12:42:43 [5308] ERROR:core:main: error while initializing modules

Searching the mailing list I've seen similar issues suggesting that the fix is to upgrade the openssl version. I've tried both older and newer versions of openssl on both ubuntu xenial and debian jesse all of which fail with the same error.

After some experimenting it appears that the issue may be with db_postgres initialising, if I use for example db_mysql then the tls_mgm module initiates fine.

I've also attached a simple script to recreate this on both Ubuntu and Debian, look for the string "BUG_BUG_BUG" on line 120.

[opensips.m4.2.2.cfg.txt](https://github.com/OpenSIPS/opensips/files/589308/opensips.m4.2.2.cfg.txt)

Also I've attached the full log with debug_mode = yes.

[opensips_2_2_log.txt](https://github.com/OpenSIPS/opensips/files/589303/opensips_2_2_log.txt)

**Comment by razvancrainea** [comment]
Hi, Pete!

So you're saying that if you are using mysql instead of postgress, OpenSIPS starts without any issue?
Also, what version of openssl were you compiling with?

Best regards,
Răzvan

**Comment by pbaines** [comment]
Yes that is correct, it is easy to recreate if you try to run the config I sent in a VM. I have tried lots of versions of ssl but currently the two machines I have setup are running:

Ubuntu: openssl                          1.0.2g-1ubuntu4.5                 amd64
Debian: openssl                        1.0.1t-1+deb8u5           amd64

I did find a bug report saying that the call to CRYPTO_set_mem_functions should be resolved: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1594748

But I think the fact it works with mysql points more to the postgres driver doing something odd with initalising openssl.

**Comment by razvancrainea** [comment]
I think this might be a different bug than the one the others have experienced.
I don't have a VM available right away, but could you try moving the `loadmodule "tls_mgm.so"` line at the very beginning of your script, just below the `mpath="/usr/local/opensips/lib64/opensips/modules/"`?
Thanks!

**Comment by pbaines** [comment]
Attached: [tls.log.txt](https://github.com/OpenSIPS/opensips/files/589568/tls.log.txt)

**Comment by razvancrainea** [comment]
Could you please apply [this](https://gist.github.com/razvancrainea/cdbd334204e29c2f3ee34891342e5045) patch?
Also, can you try to increase the memory of the VM?

**Comment by pbaines** [comment]
[tls-2.log.txt](https://github.com/OpenSIPS/opensips/files/589654/tls-2.log.txt)

Sorry Razvan - it looks like increasing memory has resolved it - the original error message from about openssl versions put me on the wrong path!

Thanks for your time!
Peter

**Comment by pbaines** [comment]
Also I can confirm order is also important, if I load tls_mgm later on in the script then I get the original error, but if it is the first module loaded then opensips starts up just fine

**Comment by razvancrainea** [comment]
Yes, you are right! This is an issue by itself! Will try to get a fix and then I will close this ticket.

Thanks for reporting this and for debugging!
