### ISSUE TITLE
SST module broken logic for case where only one end supports timers

### ISSUE THREAD

**Issue by etamme** [OpenSIPS/opensips#991]
The SST module has "broken" logic for the case where only one end (UAC or UAS) supports timers but the other does not.

In the case where a UAC has advertised support for timers, but the UAS does not support timers (e.g. no supported: timer) opensips decides that it should still inject the session-expiry header and simply "let the uac take care of it" by appending the refresher=uac parameter.  

In this case, the UAC would start sending UPDATE requests to the UAS which it has no ability to process.  The UAS may ignore the requests, or it might reject them.  In either case, if the UAC thinks that session timers are being used, this will cause the call to drop.

I am looking at function sst_dialog_response_fwded_CB() in sst_handlers.c

**Comment by razvancrainea** [comment]
Although [RFC 4028](https://www.ietf.org/rfc/rfc4028.txt), describes the behavior an UAC must have when the UAS does not support timers, some UAS don't event respond to such Updates/Re-Invites.
According to the discussion on IRC, we need to have a mechanism to specify that a UAS cannot handle SST, and disable this mechanism.
