### ISSUE TITLE
Async rest_client sometimes does not resume script execution

### ISSUE THREAD

**Issue by arovetto** [OpenSIPS/opensips#997]
Hello
Performing a stress test with SIPP, I see that rest_client does not always resume the script execution notwithstanding the HTTP response has been sent (verified with a tcpdump capture).

From the log, extracting only  async rest request and script resuming in a stress test I get the following:
```
Nov 28 12:50:50 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:50.844181 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:50 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:50.850068 - resumeLookupPattern retcode: 1 - 200
Nov 28 12:50:51 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:51.438710 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:51 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:51.445092 - resumeLookupPattern retcode: 1 - 200
Nov 28 12:50:52 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:52.231249 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:52 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:52.240760 - resumeLookupPattern retcode: 1 - 200
Nov 28 12:50:52 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:52.670884 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:52 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:52.688100 - resumeLookupPattern retcode: 1 - 200
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.81683 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.102751 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.130570 - resumeLookupPattern retcode: -5 - 200
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.399512 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.422484 - resumeLookupPattern retcode: -5 - 200
Nov 28 12:50:54 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:54.21003 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:54 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:54.44919 - resumeLookupPattern retcode: -5 - 200
Nov 28 12:50:54 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:54.453832 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:54 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:54.480021 - resumeLookupPattern retcode: -5 - 200
Nov 28 12:50:56 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:56.328804 - Calling async http://localhost:8600/CallRouter/LookupPattern
Nov 28 12:50:56 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:56.352975 - resumeLookupPattern retcode: -5 - 200
```

You see that a resume script is missing, and after that all the async http requests have retcode -5, but they are working.

The first request after the one that has not the resume script logs the following, I think that there is something strange here, because you see headers of two responses.
```
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:w_async_rest_post: async rest post 'http://localhost:8600/CallRouter/LookupPattern' 0x7f3cc7049090 0x7f3cc7049110 0x7f3cc70491f8
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: HTTP/1.1 200 OK
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: Connection: close
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: application/json charset=utf-8
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: Content-Length: 87
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received:
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:start_async_http_req: libcurl TCP connect: we should wait up to 0ms (timeout=20000ms, poll=20ms)!
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:start_async_http_req: ongoing transfer on fd 17
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:start_async_http_req: busy waiting 20ms ...
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: HTTP/1.1 200 OK
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: Connection: close
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: application/json charset=utf-8
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received: Content-Length: 87
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:header_func: Received:
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:start_async_http_req: libcurl TCP connect: we should wait up to 955ms (timeout=20000ms, poll=20ms)!
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:start_async_http_req: done, no need for async!
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:rest_client:set_output_pv_params: Last response code: 200
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: 12:50:53.130570 - resumeLookupPattern retcode: -5 - 200
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: DBG:core:comp_scriptvar: int 29 : 200 / 200
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: HTTP POST returned 200 and body {"result":true,"description" : "success","ruri" : "sip:B2BUAEPtlsA1@10.77.38.99:5060" }
Nov 28 12:50:53 felix-cti1 /usr/local/sbin/opensips[8561]: HTTP POST result is: true
```

Can you help me with this issue?

Thank you

**Comment by arovetto** [comment]
I've used opensips 2.2.2, and here you find the complete log at debug level.
[http_async_issue.log.gz](https://github.com/OpenSIPS/opensips/files/618821/http_async_issue.log.gz)

**Comment by arovetto** [comment]
[root@felix-cti1 opensips]# opensips -V
version: opensips 2.2.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
main.c compiled on 22:55:52 Nov 21 2016 with gcc 4.8.5

**Comment by arovetto** [comment]
Do you have seen something strange from logs? If you need other tests I can easily reproduce it. 
Let me know 
Thank you

**Comment by razvancrainea** [comment]
Can you check with the latest version of OpenSIPS 2.2? Commit a0517e20 might have fixed this issue.

**Comment by arovetto** [comment]
Thank you @razvancrainea, I've tried the latest version but I see the same problem of missing resume execution. After that, all the async rest_client requests have -5 as returning code, while before the issue is 1.

**Comment by razvancrainea** [comment]
Can you point out the git commit your sources are pointing to? Yesterday some of the code has changed and I want to confirm you have those changes.
Also, are all your REST queries successful (replied with a 200OK)?

**Comment by arovetto** [comment]
I used last branch 2.2 commit of 7th Dec.
I confirm that all queries are successful (looking at apache access log).
Now I'm trying with the last commit of master. I let you know soon.
Thank you

**Comment by arovetto** [comment]
It happens also with master downloaded today.
From logs seems the issue is related when there are 2 queries overlapping waiting for responses.

From log at debug level you see here 2 dump of response-headers, but only one resume script:

Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:tm:t_resume_async: resuming on fd 21, transaction 0x7f71250e2900
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: HTTP/1.1 200 OK
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: Connection: close
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: application/json charset=utf-8
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: Content-Length: 64
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received:
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: HTTP/1.1 200 OK
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: Connection: close
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: application/json charset=utf-8
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received: Content-Length: 87
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:header_func: Received:
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:resume_async_http_req: running handles: 0
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:del_transfer: del fd 21
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:rest_client:resume_async_http_req: Last response code: 200
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: DBG:tm:io_watch_del: [UDP_worker] io_watch_del op on index -1 21 (0x810e60, 21, -1, 0x10,0x1) fd_no=4 called
Dec 13 10:36:42 felix-cti1 /usr/local/sbin/opensips[12103]: 10:36:42.56283 - resumeLookupPattern retcode: 1 - 200 - Duration: 40989

All the following rest_client request have -5 as return code.

I hope this could be useful to understand the problem.

Thank you

**Comment by razvancrainea** [comment]
@arovetto we finally spotted the bug; however, the fix is not that straight forward. I will keep you updated.
This bug is not present in the blocking version; you might want to proceed with that version until the async one is sorted out.

Thanks for your report!

**Comment by arovetto** [comment]
Great!
Let me know
Thanks



Alessandro Rovetto
Product Development Manager
Reitek – An Enghouse Interactive company


-------- Messaggio originale --------
Da: Răzvan Crainea <notifications@github.com>
Data: 16/12/2016 15:35 (GMT+01:00)
A: OpenSIPS/opensips <opensips@noreply.github.com>
Cc: Alessandro Rovetto <Alessandro.Rovetto@enghouse.com>, Mention <mention@noreply.github.com>
Oggetto: Re: [OpenSIPS/opensips] Async rest_client sometimes does not resume script execution (#997)


@arovetto<https://github.com/arovetto> we finally spotted the bug; however, the fix is not that straight forward. I will keep you updated.
This bug is not present in the blocking version; you might want to proceed with that version until the async one is sorted out.

Thanks for your report!

**Comment by liviuchircu** [comment]
@arovetto a fix is available on `master` branch. Long story short, the libcurl async API had been slightly misused when it was adapted to work with the OpenSIPS async API. This is now taken care of.

Once the patch proves to hold, we will have it backported as well. FYI, in my lab setup, the stress tests went well.

**Comment by arovetto** [comment]
Thank you @liviuchircu. Now it is working fine also with my stress test,
