### ISSUE TITLE
siptrace 2.2 - documentation and errors

### ISSUE THREAD

**Issue by ishmaelen** [OpenSIPS/opensips#998]
Just a couple of comments regarding siptrace.so in OpenSIPS 2.2.

The example in [siptrace module](http://www.opensips.org/html/docs/modules/2.2.x/siptrace.html) is wrong.
`modparam("siptrace", "trace_id","[tid]uri=hep:10.10.10.12:5061;transport=tcp;version=3")` to
`modparam("siptrace", "trace_id","[tid]uri=hep:10.10.10.12:5061;transport=tcp;version=3;")`

Using the documented example gives "Parameter <trace_id> not found in module".

Also, running siptrace wo/ proper hep_tcp/udp init (listener) gives an error which doesn't seem "right".
I don't believe it's a programming bug but rather a lack of proper error description..

CRITICAL:siptrace:msg_send: #012>>> using proto 9 which is not init!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
ERROR:siptrace:trace_send_hep_duplicate: cannot send duplicate message
ERROR:siptrace:save_siptrace: Failed to duplicate with hep to <:>

Just thoughts to make it easier for people to use siptrace.

**Comment by ionutrazvanionita** [comment]
Hi @ishmaelen,

Fixed the docs thank you for reporting. Will also try to fix the need to have ';' at the end of the definition ASAP, but right now there is some work in siptrace module.
