### ISSUE TITLE
OpenSIPS RR don't support Route header in negative ACK from FreeSWITCH

### ISSUE THREAD

**Issue by sekil75** [OpenSIPS/opensips#999]
Call from FreeSWITCH with preloaded Route header to OpenSIPS to a phone. Phone responds with 486, and FreeSWITCH sends negative ACK with Route header to which OpenSIPS record routing breaks.

As per RFC, negative ACK MUST have same Route header as in INVITE. This is discussed in:
http://sipforum.org/pipermail/techwg/2007-December/001165.html

I have discussed this with Bogdan, this is a bug in OpenSIPS.
Version is 2.2-git.

**Comment by bogdan-iancu** [comment]
@sekil75 , could you please email me again the trace with the INVITE and ACK with pre-loaded Route ? I do not find the original emails you sent me :(

**Comment by bogdan-iancu** [comment]
@sekil75 , here is a overlapping between the RR and TM functionalities.  The RR is done completely unaware of the transaction state, so it has no idea if the ACK is end-2-end (for 2xx OK) and separate transaction or if the ACK is hop-by-hop (for negative replies) and part of the INVITE transaction.

Maybe this should be fixed at script level by discarding asap the hop-by-hop ACK, without getting to the RR part.

Or we can wist the log err you get to avoid it when it looks like ACK with preloaded route. At the end of the day, the routing works ok, it is just about that annoying error log, right ?

**Comment by sekil75** [comment]
@bogdan-iancu , yes routing does work in tests I did. I've also replicated the behaviour with plane INVITE with Route header and CANCEL from a-side (missed call to b-side), so there are other scenarios to look. CANCEL from FS side also has Route header which I think confuses OS.

**Comment by bogdan-iancu** [comment]
Yes @sekil75 , it is exactly the same scenarios (CANCEL and ACK for negative). Still, if you do the CANCEL handling and the ACK-negative handling before any test for pre-loaded route, like in the default opensips cfg, you should not have this  problem, right ?

**Comment by sekil75** [comment]
I have CANCEL handling and ACK handling set like in default script, and those are set before preloaded route test.

**Comment by bogdan-iancu** [comment]
[CANCEL handling](https://github.com/OpenSIPS/opensips/blob/master/etc/opensips.cfg#L158) is above the [preloaded-reoute test](https://github.com/OpenSIPS/opensips/blob/master/etc/opensips.cfg#L179); also, it does not hit the [loose route part](https://github.com/OpenSIPS/opensips/blob/master/etc/opensips.cfg#L123) as CANCEL has no TO tag param. 
So, a CANCEL with preloaded route should not trigger the mentioned error.
Still, an ACK with preloaded route (for negative replies) it will do trigger it due the  [loose route part](https://github.com/OpenSIPS/opensips/blob/master/etc/opensips.cfg#L123) for sequential requests. Maybe we could move the test for hop-by-hop ACK (for negative replies) somewhere before the loose_route(), so we will avoid the bogus error logs ?

**Comment by sekil75** [comment]
I updated my OS 2.2 and put in new config for sequential requests. I'm having an issue where dialogs are not matched now:

ERROR:dialog:dlg_validate_dialog: Script error - validate function before having a dialog
There's also an old error:
WARNING:rr:after_strict: no socket found to match RR

**Comment by bogdan-iancu** [comment]
@sekil75 , could you privately share your script ?

**Comment by bogdan-iancu** [comment]
This was fixed via commit dee4d12f8e99adbb6e46476eaeaf2b80130cb5a9 (to help in properly detecting the hop-by-hop ACKs) and the new script logic for handling the ACKs c393ee982291fab560bdc679c9dfcd7e01f0549b .

**Comment by sekil75** [comment]
I just tested again with new script logic. The RR is broken, ACK and BYEs are not answered from OpenSIPS side.

**Comment by bogdan-iancu** [comment]
What do you mean the ACK/BYEs are not answered ? ACK has no reply, while BYE is replied by UAS and not by OpenSIPS.
I just run some test calls via the default cfg and everything worked as expected. Do you have a SIP trace, script and logs to share ?

**Comment by sekil75** [comment]
What I meant to say was:
- ACK from phone was not propagated to other side
- BYE sent to OS was not propagated to the phone

Right now, I recompiled, re-tested  with default cfg and everything works fine.
Maybe, I just need to sleep() :)
I will close the issue

**Comment by bogdan-iancu** [comment]
OK, perfect. Indeed, it is good to have from time to time a sleep() instead of an usleep() ;)
